### PR TITLE
CalDAV fix search with limit and time range

### LINKED ISSUE #5563: Web UI dashboard "upcoming events" widget only shows personal calendar
### Steps to reproduce

update from 27.0.1 to 27.1.2
Calendar widget is empty

### Expected behavior

Web UI dashboard "upcoming events" widget should show upcoming events

### Actual behaviour

Calendar widget is empty except for personal calendar.  Any linked calendars or newly created calendar events are not shown

### Calendar app version

4.5.2

### CalDAV-clients used

_No response_

### Browser

Chrome, Edge & Firefox

### Client operating system

Windows 10 & 11, Ubuntu 22.04, mint 21.2

### Server operating system

Ubuntu 22.04

### Web server

Apache

### Database engine version

MySQL

### PHP engine version

PHP 8.1

### Nextcloud version

27.1.3

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

```Text
Enabled:
  - admin_audit: 1.17.0
  - bruteforcesettings: 2.7.0
  - calendar: 4.5.2
  - cfg_share_links: 4.2.0
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.4.2
  - dashboard: 7.7.0
  - dav: 1.27.0
  - external: 5.2.1
  - externalportal: 1.2.0
  - federatedfilesharing: 1.17.0
  - files: 1.22.0
  - files_external: 1.19.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_texteditor: 2.15.1
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - nextcloud_announcements: 1.16.0
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - passwords: 2023.10.30
  - previewgenerator: 5.3.0
  - provisioning_api: 1.17.0
  - ransomware_protection: 1.14.0
  - related_resources: 1.2.0
  - richdocuments: 8.2.2
  - richdocumentscode: 23.5.503
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - side_menu: 3.10.3
  - support: 1.10.0
  - suspicious_login: 5.0.0
  - systemtags: 1.17.0
  - text: 3.8.0
  - theming: 2.2.0
  - theming_customcss: 1.14.0
  - twofactor_backupcodes: 1.16.0
  - updatenotification: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - activity: 2.19.0 (installed 2.15.0)
  - circles: 27.0.1 (installed 22.0.0)
  - contactsinteraction: 1.8.0 (installed 1.2.0)
  - encryption: 2.15.0
  - federation: 1.17.0 (installed 1.11.0)
  - photos: 2.3.0 (installed 1.6.0)
  - privacy: 1.11.0 (installed 1.6.0)
  - recommendations: 1.6.0 (installed 1.1.0)
  - spreed: 17.1.2 (installed 17.1.2)
  - survey_client: 1.15.0 (installed 1.10.0)
  - twofactor_totp: 9.0.0
  - user_ldap: 1.17.0
```

### Nextcloud configuration

```Text
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.***REMOVED SENSITIVE VALUE***",
        ],
        "0": "apache_disable_rewrite_ip=0",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "27.1.3.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "remember_login_cookie_lifetime": 31536000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "auto_logout": false,
        "default_language": "en",
        "force_language": "en",
        "default_locale": "en_US",
        "force_locale": "en_US",
        "default_phone_region": "US",
        "auth.bruteforce.protection.enabled": true,
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "logfilemode": 416,
        "loglevel": 1,
        "log_rotate_size": 104857600,
        "logtimezone": "America\/New_York",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "enable_previews": true,
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "maintenance": false,
        "theme": "",
        "allow_local_remote_servers": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 1.5
        },
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "files_texteditor",
            "extract",
            "richdocumentscode",
            "ransomware_protection",
            "documentserver_community",
            "files_downloadactivity"
        ],
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "jpeg_quality": "60"
    }
}
```

### Web server error log

_No response_

### Log file

_No response_

### Browser log

_No response_

### Additional info

The title says it all.  It's been reported and marked as fixed but it still persists.

https://github.com/nextcloud/calendar/issues/5477
https://help.nextcloud.com/t/web-ui-dashboard-upcoming-events-widget-only-shows-personal-calendar/173084

### LINKED ISSUE #5695: Unexpected behavior dashboard "Upcoming events" widget
### Steps to reproduce

1. Have Calendar with upcoming events
2. Have Dashboard with Upcoming events widget
3. Open Dashboard

### Expected behavior

Upcoming events are listed in the widget

### Actual behaviour

Upcoming events not listed or incompletely listed.

Two different users. Two different behaviors.

User 1: Event ten days from today, multiple intermediate events between now and then.
Only the event ten days away is being displayed.

User 2: Multiple events three, four, and 10+ days away. No events are displayed.

### Calendar app version

4.6.3

### CalDAV-clients used

DAVx5

### Browser

Firefox 121.0.1

### Client operating system

Windows 10

### Server operating system

CentOS

### Web server

Apache

### Database engine version

PostgreSQL

### PHP engine version

PHP 8.2

### Nextcloud version

27.1.5

### Updated from an older installed version or fresh install

Updated from an older version

### List of activated apps

_No response_

### Nextcloud configuration

_No response_

### Web server error log

_No response_

### Log file

```Text
No errors in logs
```

### Browser log

_No response_

### Additional info

Logs and additional info can be provided upon request, if required

### LINKED ISSUE #5902: Calendar widget shows events in the order of creation _not_ in the order of schedule
### Steps to reproduce

Create 6 events that all belong to the same calendar (calendar 1) so they show up on the widget (making widget full)
Create a new event in the _same_ calendar (calendar 1) that is supposed to occur _before_ the first event from the group before

all events could be on the same day or different days

### Expected behavior

all events show up in the order of the time of their occurence / schedule, with the new event showing up before the 5 from original 6

### Actual behaviour

this new event will not show up on the widget at all
note 1: if you now change to what calendar event belongs to (for example to calendar 2) it will show up

note 2: not to make it too complicated, but another test case - first 6 events belong to 2 different calendars and for as long as the _new_ event is also in one of the original 2 calendars it will not show up even though it's the earliest of 7. Changing new event's calendar to a new calendar (calendar 3) will make it show up in the dashboard.

### Calendar app version

4.6.7

### CalDAV-clients used

none, looking at the dashboard of a nextcloud in the browser

### Browser

Firefox 123.0.2

### Client operating system

ubuntu, fedora

### Server operating system

TrueNAS Scale 23.10.2

### Web server

Nginx

### Database engine version

PostgreSQL

### PHP engine version

PHP 8.2

### Nextcloud version

28.0.4 (Kubernetes version 1.6.59, Train: charts)

### Updated from an older installed version or fresh install

Fresh install

### List of activated apps

```Text
calendar
bookmarks
tasks
deck
photos
```

### Nextcloud configuration

```Text
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "overwritehost": "nextcloud.home:9001",
        "overwriteprotocol": "https",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "upgrade.disable-web": true,
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "nextcloud.home"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "28.0.4.1",
        "overwrite.cli.url": "https:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 2,
        "default_phone_region": "US",
        "maintenance_window_start": 9,
        "filelocking.enabled": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 30036
        }
    }
}
```

### Web server error log

_No response_

### Log file

_No response_

### Browser log

_No response_

### Additional info

this bug makes it very difficult to track events that were scheduled as recurring events resulting in having a lot of events missing from the dashboard with "tommorow's" events showing up and "today's" events missing

same thing happens in other types of installations, snap, manual etc, so I don't think it's OS dependent

### PR DESCRIPTION
**Pull request by kesselb**
* Resolves: https://github.com/nextcloud/calendar/issues/5563
* Resolves: https://github.com/nextcloud/calendar/issues/5695
* Resolves: https://github.com/nextcloud/calendar/issues/5902

## Summary

Event recurrences are evaluated at runtime because the database only knows the first and last occurrence.

Given, a user created 8 events with a yearly reoccurrence and two for events tomorrow.
The upcoming event widget asks the CalDAV backend for 7 events within the next 14 days.

If limit 7 is applied to the SQL query, we find the 7 events with a yearly reoccurrence and discard the events after evaluating the reoccurrence rules because they are not due within the next 14 days and end up with an empty result even if there are two events to show.

The workaround for search requests with a limit and time range is asking for more row than requested and retrying if we have not reached the limit.

## TODO

- [x] https://github.com/nextcloud/calendar/issues/5592 (could be fixed as well)
- [x] https://github.com/nextcloud/calendar/issues/5944 (could be fixed as well)
- [x] https://github.com/nextcloud/calendar/issues/5902 (related, likely not fixed, but I understand the problem now)
- [x] CI
- [x] Review

## Test cases

[search_with_limit_and_timerange.txt](https://github.com/nextcloud/server/files/15240776/search_with_limit_and_timerange.txt)

A sample calendar with 7 reoccurring events (in January 2024) and two events happening this month. 
GitHub does now allow ICS attachments, thus don't forget to rename.

On master/main the upcoming events widget should be empty.
On this branch Cake Tasting and Pasta Day should appear in the widget. 

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/dav/lib/CalDAV/CalDavBackend.php [hunk 1]
```diff
@@ -1946,52 +1966,38 @@ public function search(
...
+			 *
+			 * 25 rows and 3 retries is entirely arbitrary.
+			 */
+			$maxResults = (int)max($limit, 25);
+			$outerQuery->setMaxResults($maxResults);
+
+			for ($attempt = $objectsCount = 0; $attempt < 3 && $objectsCount < $limit; $attempt++) {
+				$objectsCount = array_push($calendarObjects, ...$this->searchCalendarObjectsByQuery($outerQuery, $start, $end));
+				$outerQuery->setFirstResult($offset += $maxResults);
 			}
```
Comment (kesselb) [inline apps/dav/lib/CalDAV/CalDavBackend.php:1996]: Todo: $objectsCount might be larger than $limit.

Comment (kesselb) [reply apps/dav/lib/CalDAV/CalDavBackend.php:1996]: I think to address https://github.com/nextcloud/calendar/issues/5902 we need to sort the calendar objects by the start date.

**Comment by kesselb** [comment]
Reminder for myself:

The search query does not have an "order by" command.
If we are still seeing weirdnesses with upcoming events / search result, we should consider adding one.

**Comment by ChristophWurst** [comment]
> The search query does not have an "order by" command.
> If we are still seeing weirdnesses with upcoming events / search result, we should consider adding one.

Databases will probably use an index for the query, or traverse the data according to the primary id. So the sorting will be unpredictable across instances but for the same instance it should be stable.

File: apps/dav/lib/CalDAV/CalDavBackend.php [hunk 2]
```diff
@@ -2031,6 +2039,53 @@ public function search(
...
+				// No filter required
+				$calendarObjects[] = $row;
+				continue;
+			}
+
+			$isValid = $this->validateFilterForObject($row, [
+				'name' => 'VCALENDAR',
+				'comp-filters' => [
+					[
+						'name' => 'VEVENT',
```
Comment (tcitworld) [inline apps/dav/lib/CalDAV/CalDavBackend.php:2059]: Should we limit to `VEVENT`s ?
https://icalendar.org/CalDAV-Access-RFC-4791/9-9-caldav-time-range-xml-element.html

**Comment by kesselb** [comment]
Added the test case "testSearchWithLimitAndTimeRangeShouldReturnObjectsInTheSameOrder". 

Cake Tasting (2024-05-09) and Pasta Day (2024-05-14) match the criteria. Pasta Day was added to the calendar first and therefore is the first result returned by the SQL server. Likely, the SQL server(s) sorted the results by the primary id. 

I observed locally that the records are not always sorted by the primary id. Especially if you move around event's a lot, it happens that suddenly the order changes. 

The calendar search api does not document how/if the results are ordered. 

- A is therefore to drop the test case again.
- B is to extend the pull request (add order by to the query, sort the final result by DTSTART) to have more reliable results for the api consumer.

File: apps/dav/lib/CalDAV/CalDavBackend.php (hunk 2 above)
Comment (kesselb) [reply apps/dav/lib/CalDAV/CalDavBackend.php:2059]: Well spotted, thank you :pray: 

A [user mentioned](https://github.com/nextcloud/calendar/issues/5563#issuecomment-1900129501) that the widget is not showing items from the tasks app anymore.  I assume that could be the reason. 

What do you suggest, extending to VEVENT, VTODO?

File: apps/dav/lib/CalDAV/CalDavBackend.php [hunk 3]
```diff
@@ -1946,52 +1966,40 @@ public function search(
...
-				'time-range' => null,
-			]);
-			if (is_resource($row['calendardata'])) {
-				// Put the stream back to the beginning so it can be read another time
-				rewind($row['calendardata']);
-			}
-			if ($isValid) {
-				$calendarObjects[] = $row;
-			}
+		if ($hasLimit && $hasTimeRange) {
```
[the remark this answers is not in the document]
Comment (kesselb) [reply apps/dav/lib/CalDAV/CalDavBackend.php:1979]: The problem to be solved with this pull request exists only when limit and timerange are used together because the evaluation, is the event within the given timerange, cannot be done with sql.

File: apps/dav/lib/CalDAV/CalDavBackend.php (hunk 2 above)
Comment (kesselb) [reply apps/dav/lib/CalDAV/CalDavBackend.php:2075]: I took a look at the missing tasks / the VTODO handling and wrote down my findings at https://github.com/nextcloud/server/issues/45333. 
It's more work than I imagined, and therefore I need to discuss it with Christoph.
Happy to have your feedback / pointers on that one ;)

File: apps/dav/lib/CalDAV/CalDavBackend.php [hunk 4]
```diff
@@ -1920,14 +1920,34 @@ public function search(
 					$this->db->escapeLikeParameter($pattern) . '%')));
 		}
 
+		$start = null;
+		$end = null;
+
+		$hasLimit = is_int($limit);
+		$hasTimeRange = false;
+
 		if (isset($options['timerange'])) {
```
[the remark this answers is not in the document]
Comment (kesselb) [reply apps/dav/lib/CalDAV/CalDavBackend.php]: Good idea, indeed easier to read now.

**Review by ChristophWurst — APPROVED** [review]
Looks good

**Review by miaulalala — APPROVED** [review]
