### PR TITLE
Fix sharing expiration date handling and saving

### LINKED ISSUE #34926: [Bug]: Expiration date field doesn't show previously set value
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Expiration date field doesn't populate itself with the date

### Steps to reproduce

1. Create a folder "test"
2. Share with link
3. Set an expiration date in the future
4. Refresh the page
5. Open the link share dropdown to edit the date

### Expected behavior

Expiration date is set

### Installation method

_No response_

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database engine version

_No response_

### Is this bug present after an update or on a fresh install?

_No response_

### Are you using the Nextcloud Server Encryption module?

_No response_

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
N/A
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

This is on git master c5b21c59bc1efbeb20dd327ca2649576abf144ac

Discovered through https://github.com/nextcloud/server/issues/34695

The expiration date was set successfully as it's there in the database.
The bug is that the date time input field doesn't set it.

- [x] nextcloud-vue bug: https://github.com/nextcloud/nextcloud-vue/issues/3403 https://github.com/nextcloud/nextcloud-vue/pull/3405
- [x] release nextcloud-vue 7.0.2
- [x] update @nextcloud/vue on master
- [x] update @nextcloud/vue on stable25

### PR DESCRIPTION
**Pull request by skjnldsv**
Regression from https://github.com/nextcloud/server/pull/33915

Fix https://github.com/nextcloud/server/issues/34926

## Explanations
- `share.expireDate` represent the Database expiration data. Which expects a `YYYY-MM-DD` format
- The native DatePicker require a javascript `Date` as value
- We need to make sure the data we sent is not UTC-aware.
  ```js
  new Date('2020-01-01 00:00:00').toISOString()
  > '2019-12-31T23:00:00.000Z'
  ```
- The backend forces a time on the expiration field (for clients I'm assuming), so we also need to make sure to ignore this when parsing the data
  https://github.com/nextcloud/server/blob/62919ac81eb856a15c0131f3cf948bb11b2a5b1f/apps/files_sharing/lib/Controller/ShareAPIController.php#L236 https://github.com/nextcloud/server/blob/e03248ec731f918d362c3c37193379b162495bc4/apps/files_sharing/src/mixins/SharesMixin.js#L161-L162

### CODE REVIEW

File: apps/files_sharing/src/components/SharingEntryLink.vue [hunk 1]
```diff
@@ -698,10 +699,12 @@ export default {
 					// Todo: We also need to fix the createShare method in
 					// lib/Controller/ShareAPIController.php to allow file drop
 					// (currently not supported on create, only update)
-				})
+				}
 
-				this.open = false
+				console.debug('Creating link share with options', options)
```
Comment (artonge) [inline apps/files_sharing/src/components/SharingEntryLink.vue:704]: No logger ? :(

File: apps/files_sharing/src/mixins/SharesMixin.js [hunk 2]
```diff
@@ -150,13 +150,36 @@ export default {
...
+			}
+			const regex = /([0-9]{4}-[0-9]{2}-[0-9]{2})/i
+			return new Date(date.match(regex)?.pop())
+		},
+
+		/**
+		 * @param {Date} date
+		 * @return {string} date a date with YYYY-MM-DD format
+		 */
+		formatDateToString(date) {
```
Comment (artonge) [inline apps/files_sharing/src/mixins/SharesMixin.js:169]: Better ?
```suggestion
formatDateToUTCString(date) {
```

**Review by artonge — APPROVED** [review]
Nitpicks but fine otherwise :)

**Review by szaimen — CHANGES_REQUESTED** [review]
Works in my testing. However here we need to add date +1 since otherwise the default will not work as the current date is already reached.
https://github.com/nextcloud/server/blob/e03248ec731f918d362c3c37193379b162495bc4/apps/files_sharing/src/components/SharingEntryLink.vue#L428

File: apps/files_sharing/src/components/SharingEntryLink.vue (hunk 1 above)
Comment (skjnldsv) [reply apps/files_sharing/src/components/SharingEntryLink.vue:704]: Never had that in here before.
Not planning to create more noise than necessary for this PR :see_no_evil:

File: apps/files_sharing/src/mixins/SharesMixin.js (hunk 2 above)
Comment (skjnldsv) [reply apps/files_sharing/src/mixins/SharesMixin.js:169]: No, we're not converting this to a UTC time, we're removing timezone data.
Saying `formatDateToUTCString` would expect this to return the string from the utc date.

File: apps/files_sharing/src/components/SharingEntryLink.vue [hunk 3]
```diff
@@ -427,15 +428,15 @@ export default {
...
+					? this.formatDateToString(defaultExpirationDate)
 					: ''
 				console.debug('Expiration date status', enabled, this.share.expireDate)
 			},
 		},
 
 		dateMaxEnforced() {
 			if (this.config.isDefaultExpireDateEnforced) {
-				return new Date(new Date().setDate(new Date().getDate() + 1 + this.config.defaultExpireDate))
+				return new Date(new Date().setDate(new Date().getDate() + this.config.defaultExpireDate))
```
Comment (skjnldsv) [inline apps/files_sharing/src/components/SharingEntryLink.vue:439]: @szaimen 
> Works in my testing. However here we need to add date +1 since otherwise the default will not work as the current date is already reached.

You're referring to this line? I fixed it actually.
Previously (current master), you cannot set the expiration date if you enforce (let's say) 7 days and select the last allowed date.
image
Capture d’écran_2022-11-16_16-56-30
image

**Comment by szaimen** [comment]
@skjnldsv no: id no defaultexpire date is set, it will use the current day by default which cannot be used as it is already reached...

File: apps/files_sharing/src/components/SharingEntryLink.vue (hunk 3 above)
Comment (szaimen) [reply apps/files_sharing/src/components/SharingEntryLink.vue:439]: This looks good but see below

**Comment by skjnldsv** [comment]
> @skjnldsv no: if no defaultexpirationdate is set, it will use the current day by default which cannot be used as it is already reached...

Gotcha, fixing it! Nice catch :)

**Comment by skjnldsv** [comment]
Pushed and ready to go!

**Review by szaimen — APPROVED** [review]
Didnt test again but I trust you that it works now :)

**Review by PVince81 — APPROVED** [review]
Tested, works :+1:

File: apps/files_sharing/src/mixins/SharesMixin.js (hunk 2 above)
Comment (artonge) [reply apps/files_sharing/src/mixins/SharesMixin.js:169]: Hmm, so I am not sure why `.toISOString().split('T')[0]` on the original date would not work
