### PR TITLE
fix: Correctly ignore lazy ghost initialization in debug warning about direct constructor call

### LINKED ISSUE #53463: [Bug]:  Warning with lazy objects and debug mode "App class OC\\Core\\AppInfo\\Application is not setup via query() but directly"
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

"App class OC\\Core\\AppInfo\\Application is not setup via query() but directly" us logged for each request.

### Steps to reproduce

1. Use php8.4
2. `'enable_lazy_objects' => true,`
3. `'debug' => true,`

### Expected behavior

I might be wrong, but with lazy objects enabled, it seems intentional to call the constructor directly. Therefore, we may need to adjust the check in the application base class.

However, I'm confused as to why we only see that warning for Core and not the other application classes. Initializing this class seems to take an unusual path.

I'm raising this issue for awareness.

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by come-nc**
* Resolves: #53463

## Summary

It appears that ReflectionClass does not appear in the trace in the end, so we need to match the closure to be sure we’re fine.
I use preg_match so that it does not break when the line number of the closure changes.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: lib/public/AppFramework/App.php [hunk 1]
```diff
@@ -70,9 +71,10 @@ public function __construct(string $appName, array $urlParams = []) {
 					$setUpViaQuery = true;
 					break;
 				} elseif (isset($step['class'], $step['function'], $step['args'][0]) &&
-					$step['class'] === \ReflectionClass::class &&
-					$step['function'] === 'initializeLazyObject' &&
+					$step['class'] === SimpleContainer::class &&
+					preg_match('/{closure:OC\\\\AppFramework\\\\Utility\\\\SimpleContainer::buildClass\\(\\):\\d+}/', $step['function']) &&
```
Comment (susnux) [inline lib/public/AppFramework/App.php:75]: Performance wise maybe `str_starts_with` until the end of `buildClass`?

Comment (come-nc) [reply lib/public/AppFramework/App.php:75]: Performance in debug mode is not a concern :shrug: 
But yeah, that would work too, I do not really care which gets merged.

**Review by susnux — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]
:ghost:
