### PR TITLE
fix: correct hint for missing posix extension

### LINKED ISSUE #35750: [Bug]: Settings for background jobs: Third option not displaying right if POSIX is not available
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

If POSIX is not available
https://github.com/nextcloud/server/blob/32ef1f59321397bce7577e30394abb1ea239d835/apps/settings/lib/Settings/Admin/Server.php#L75
the settings page for background jobs looks broken (see third option):

grafik

If POSIX is available, it looks correctly:
grafik

### Steps to reproduce

1. Make sure POSIX is not available
2. Open settings for background jobs
3. See that text for third option is broken

### Expected behavior

The transaction should show correctly and not directly after the text for the second option.

### Installation method

Community Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.XXXXX.XX"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.2.3",
        "overwrite.cli.url": "https:\/\/cloud.XXXXX.XX",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - encryption
  - files_external
  - suspicious_login
  - twofactor_totp
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"2UDIylTsWV1SGzEEzMV0","level":2,"time":"2022-12-13T09:54:06+00:00","remoteAddr":"2001:9e8:4519:9900:d88d:ec9:3796:6eb2","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in https:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0","version":"","data":[]}
{"reqId":"2UDIylTsWV1SGzEEzMV0","level":2,"time":"2022-12-13T09:54:06+00:00","remoteAddr":"2001:9e8:4519:9900:d88d:ec9:3796:6eb2","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in http:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0","version":"","data":[]}
{"reqId":"BHFyCJzFc48aIMW5YJ0M","level":2,"time":"2022-12-13T09:54:36+00:00","remoteAddr":"2001:9e8:4519:9900:d88d:ec9:3796:6eb2","user":"--","app":"no app in context","method":"POST","url":"/index.php","message":"Could not detect any host in https:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0","version":"","data":[]}
{"reqId":"BHFyCJzFc48aIMW5YJ0M","level":2,"time":"2022-12-13T09:54:36+00:00","remoteAddr":"2001:9e8:4519:9900:d88d:ec9:3796:6eb2","user":"--","app":"no app in context","method":"POST","url":"/index.php","message":"Could not detect any host in http:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0","version":"","data":[]}
{"reqId":"A7LyfhOlF5K2cPqZmLuH","level":2,"time":"2022-12-13T09:54:43+00:00","remoteAddr":"195.211.77.140","user":"--","app":"no app in context","method":"GET","url":"/","message":"Host 127.0.1.1 was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (Windows NT 8.1; WOW64) AppleWebKit/537.34 (KHTML, like Gecko) Chrome/36.0.2039.82 Safari/537.34","version":"25.0.2.3","data":[]}
{"reqId":"A7LyfhOlF5K2cPqZmLuH","level":2,"time":"2022-12-13T09:54:43+00:00","remoteAddr":"195.211.77.140","user":"--","app":"no app in context","method":"GET","url":"/","message":"Host 127.0.1.1 was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (Windows NT 8.1; WOW64) AppleWebKit/537.34 (KHTML, like Gecko) Chrome/36.0.2039.82 Safari/537.34","version":"25.0.2.3","data":[]}
{"reqId":"BHFyCJzFc48aIMW5YJ0M","level":3,"time":"2022-12-13T09:54:50+00:00","remoteAddr":"2001:9e8:4519:9900:d88d:ec9:3796:6eb2","user":"jspanier","app":"PHP","method":"POST","url":"/index.php","message":"exif_read_data(): File not supported at /home/users/jspanier/www/XXXXX.XX/cloud/lib/private/Metadata/Provider/ExifProvider.php#59","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0","version":"25.0.2.3","exception":{"Exception":"Error","Message":"exif_read_data(): File not supported at /home/users/jspanier/www/XXXXX.XX/cloud/lib/private/Metadata/Provider/ExifProvider.php#59","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/lib/private/Metadata/Provider/ExifProvider.php","line":59,"function":"exif_read_data"},{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/lib/private/Metadata/MetadataManager.php","line":68,"function":"execute","class":"OC\\Metadata\\Provider\\ExifProvider","type":"->"},{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/lib/private/Metadata/FileEventListener.php","line":101,"function":"generateMetadata","class":"OC\\Metadata\\MetadataManager","type":"->"},{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/lib/private/EventDispatcher/ServiceEventListener.php","line":87,"function":"handle","class":"OC\\Metadata\\FileEventListener","type":"->"},{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":251,"function":"__invoke","class":"OC\\EventDispatcher\\ServiceEventListener","type":"->"},{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/lib/private/EventDispatcher/EventDispatcher.php","line":88,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/lib/private/EventDispatcher/EventDispatcher.php","line":100,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/lib/private/Files/Node/HookConnector.php","line":118,"function":"dispatchTyped","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/lib/private/legacy/OC_Hook.php","line":106,"function":"postWrite","class":"OC\\Files\\Node\\HookConnector","type":"->"},{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/lib/private/Files/View.php","line":641,"function":"emit","class":"OC_Hook","type":"::"},{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/lib/private/Files/View.php","line":692,"function":"emit_file_hooks_post","class":"OC\\Files\\View","type":"->"},{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/lib/private/Files/Node/File.php","line":71,"function":"file_put_contents","class":"OC\\Files\\View","type":"->"},{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/lib/private/legacy/OC_Util.php","line":257,"function":"putContent","class":"OC\\Files\\Node\\File","type":"->"},{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/lib/private/legacy/OC_Util.php","line":216,"function":"copyr","class":"OC_Util","type":"::"},{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/lib/private/User/Session.php","line":553,"function":"copySkeleton","class":"OC_Util","type":"::"},{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/lib/private/User/Session.php","line":403,"function":"prepareUserLogin","class":"OC\\User\\Session","type":"->"},{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/lib/private/User/Session.php","line":616,"function":"completeLogin","class":"OC\\User\\Session","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/lib/private/User/Session.php","line":355,"function":"loginWithPassword","class":"OC\\User\\Session","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/lib/private/Setup.php","line":433,"function":"login","class":"OC\\User\\Session","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/core/Controller/SetupController.php","line":69,"function":"install","class":"OC\\Setup","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/lib/base.php","line":980,"function":"run","class":"OC\\Core\\Controller\\SetupController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/home/users/jspanier/www/XXXXX.XX/cloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
{"reqId":"5LGjk6t92p7L934zQUgQ","level":3,"time":"2022-12-13T09:55:05+00:00","remoteAddr":"2001:9e8:4519:9900:d88d:ec9:3796:6eb2","user":"jspanier","app":"index","method":"GET","url":"/index.php/apps/theming/favicon?v=4a881942","message":"Could not create folder","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0","version":"25.0.2.3","exception":{"Exception":"OCP\\Files\\NotPermittedException","Message":"Could not create folder","Code":0,"Trace":[{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/lib/private/Files/AppData/AppData.php","line":147,"function":"newFolder","class":"OC\\Files\\Node\\Folder","type":"->"},{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/apps/theming/lib/ImageManager.php","line":326,"function":"newFolder","class":"OC\\Files\\AppData\\AppData","type":"->"},{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/apps/theming/lib/ImageManager.php","line":108,"function":"getRootFolder","class":"OCA\\Theming\\ImageManager","type":"->"},{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/apps/theming/lib/Controller/IconController.php","line":118,"function":"getImage","class":"OCA\\Theming\\ImageManager","type":"->"},{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"getFavicon","class":"OCA\\Theming\\Controller\\IconController","type":"->"},{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/home/users/jspanier/www/XXXXX.XX/cloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/home/users/jspanier/www/XXXXX.XX/cloud/lib/private/Files/Node/Folder.php","Line":166,"CustomMessage":"--"}}
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by kesselb**
* Resolves: https://github.com/nextcloud/server/issues/35750

## Summary

| Before | After |
| --- | --- |
|Screenshot from 2023-06-01 14-50-31 |Screenshot from 2023-06-01 15-43-40|
| | Screenshot from 2023-06-01 15-43-31 |

## TODO

- [x] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

File: apps/settings/src/components/BasicSettings/BackgroundJob.vue [hunk 1]
```diff
@@ -125,9 +119,13 @@ export default {
...
 	computed: {
 		cronLabel() {
-			let desc = t('settings', 'Use system cron service to call the cron.php file every 5 minutes. Recommended for all instances.')
+			let desc = t('settings', 'Use system cron service to call the cron.php file every 5 minutes.')
 			if (this.cliBasedCronPossible) {
-				desc += ' ' + t('settings', 'The cron.php needs to be executed by the system user "{user}".', { user: this.cliBasedCronUser })
+				desc += '<br>' + t('settings', 'The cron.php needs to be executed by the system user "{user}".', { user: this.cliBasedCronUser })
+			} else {
+				desc += '<br>' + t('settings', 'The PHP POSIX extension is required. See {linkstart}PHP documentation{linkend} for more details.')
+					.replace('{linkstart}', '<a target="_blank" rel="noreferrer nofollow" class="external" href="https://www.php.net/manual/en/book.posix.php">')
```
Comment (susnux) [inline apps/settings/src/components/BasicSettings/BackgroundJob.vue:127]: You could also disable HTML escaping of the replacements:
`t(..., ..., { foo: '<a...>' }, 0, { escape: false })`

**Review by susnux — APPROVED** [review]
LGTM (one comment but I guess that personal preference)

File: apps/settings/src/components/BasicSettings/BackgroundJob.vue (hunk 1 above)
Comment (susnux) [reply apps/settings/src/components/BasicSettings/BackgroundJob.vue]: never mind, seems to not work (l10n bug)

**Review by nfebe — APPROVED** [review]

**Review by Pytal — APPROVED** [review]
