### PR TITLE
Ext storage error warning fix

### LINKED ISSUE #8363: enabling external storage
I am trying to enable external storage. The external storage settings page just loads a blank/white page.
ext_storage

 
### Steps to reproduce
1. enable external storage
2. go to external storage settings

### Expected behaviour
load settings for external storage
### Actual behaviour
blank / white page
### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4.18

**Database:** Mysql 5.7.21

**PHP version:** 7.1

**Nextcloud version:** (see Nextcloud admin page) Nextcloud 13

**Updated from an older Nextcloud/ownCloud or fresh install:** Recently updated from Nextcloud 12

**Where did you install Nextcloud from:** Nextcloud official download

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**
Full list and versions in the occ app:list below
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - activity: 2.6.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.0
  - comments: 1.3.0
  - contacts: 2.1.0
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.0
  - files_reader: 1.2.2
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.7.9
  - news: 12.0.1
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - richdocuments: 2.0.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - socialsharing_diaspora: 1.0.2
  - socialsharing_email: 1.0.3
  - socialsharing_facebook: 1.0.2
  - socialsharing_googleplus: 1.0.2
  - socialsharing_twitter: 1.0.2
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - twofactor_totp: 1.4.1
  - updatenotification: 1.3.0
  - user_external: 0.4
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - audioplayer
  - encryption
  - firstrunwizard
  - newsbak
  - spreed
  - user_ldap
  - weather

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.tristarcreations.com",
            "www.cloud.tristarcreations.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.tristarcreations.com",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "America\/Denver",
        "installed": true,
        "updater.release.channel": "stable",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/... no

**Are you using encryption:** yes/no no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... no

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "ldap" namespace.   
</details>

### Client configuration
**Browser:** Firefox 58.0.2 and Google Chrome 64.0.3282.140

**Operating system:** Ubuntu 17.10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
empty (and set to log all)
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #8363

### CODE REVIEW

File: apps/files_external/templates/list.php [hunk 1]
```diff
@@ -7,7 +7,7 @@
 <div id="emptycontent" class="hidden">
 	<div class="icon-external"></div>
 	<h2><?php p($l->t('No external storage configured')); ?></h2>
-	<p><a href="<?php p(link_to('', 'index.php/settings/personal#files_external' )); ?>"><?php p($l->t('You can add external storages in the personal settings')); ?></a></p>
+	<p><a href="<?php p(link_to('', 'index.php/settings/admin/externalstorages' )); ?>"><?php p($l->t('You can add external storages in the personal settings')); ?></a></p>
```
Comment (juliushaertl) [inline apps/files_external/templates/list.php]: The message here doesn't make much sense. It is shown, for personal external storage settings and if the administrator disabled the possibility to configure external storages in the personal settings there is nothing users can do about that. Also the link to admin/externalstorages only makes sense for admins.

**Review by juliusknorr — DISMISSED** [review]

File: apps/files_external/templates/list.php (hunk 1 above)
Comment (juliushaertl) [reply apps/files_external/templates/list.php]: Maybe it should be something like: "You cannot configure external storages, since it has been disabled by the administrator"

Comment (skjnldsv) [reply apps/files_external/templates/list.php]: @juliushaertl It's not only about disabled by the admin, if you're the admin but you did not set up one at the moment, the page is still empty :)

"No external storage configured or you don't have the permission to configure them"

**Review by juliusknorr — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by skjnldsv** [comment]
backport in https://github.com/nextcloud/server/pull/8561
