### PR TITLE
Fix styles for input fields on focus state

### LINKED ISSUE #41267: [BITV]: Contrast of focused "Search" and "Search contacts" is not enough
This is accessibility issue.

The contrast between focused and unfocused state on "Search" and "Search contacts" have to be 3:1. Now: unfocused : grey, focused: blue. That is not enough. See https://github.com/nextcloud/server/issues/40711

Screenshot from 2023-10-30 11-46-31
Screenshot from 2023-10-30 11-46-24

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
* Resolves: https://github.com/nextcloud/server/issues/41267

### 🖼️ Screenshots

|  Before   | After                                                        |
|-------------|---------------------------------------------------------------|
| image | Screenshot from 2023-11-03 15-03-42 |-------------|---------------------------------------------------------------|
| image | Screenshot from 2023-11-03 15-02-15

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: core/src/views/ContactsMenu.vue [hunk 1]
```diff
@@ -170,6 +174,12 @@ export default {
 			width: 100%;
 			height: 34px;
 			margin: 8px 0;
+
+			&:focus,
+			&:active {
```
Comment (szaimen) [inline core/src/views/ContactsMenu.vue:179]: what about focus-visible?

**Review by susnux — APPROVED** [review]

File: core/src/views/UnifiedSearch.vue [hunk 2]
```diff
@@ -762,6 +762,12 @@ $input-padding: 6px;
 
 	&__form-input {
 		margin: 0 !important;
+		&:focus,
+		&:focus-visible,
+		&:active {
+			border-color: 2px solid var(--color-main-text) !important;
+			box-shadow: 0 0 0 2px var(--color-main-background) !important;
+		}
```
Comment (ShGKme) [inline core/src/views/UnifiedSearch.vue:770]: IMO, if possible, we should migrate these components to `NcTextField` so we won't need to duplicate all fixes here.

Comment (JuliaKirschenheuter) [reply core/src/views/UnifiedSearch.vue:770]: I would like to make this improvement after all other important issues are solved. Is ok for you?

**Review by ShGKme — APPROVED** [review]

**Review by marcoambrosini — APPROVED** [review]
