### PR TITLE
fix(files_trashbin): check if there is enough space before restoring

### LINKED ISSUE #52303: [Bug]: File should not be recovered if no quota is left.
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Currently the trash volume is not accounted for in the total available space for the package. A user can fill the trash exceeding quota multiple times and then, before the trash bin clear-job runs recover all files from trash and blow the quota.

### Steps to reproduce

1. take a user account with a limited quota and "auto" settings for 'trashbin_retention_obligation'
2. fill up the trash by deleting files exceeding the quota 
3. recover the files from the trash bin
4. observe the files are recovered and available quota is over-boarded.

### Expected behavior

1. take a user account with a limited quota and "auto" settings for 'trashbin_retention_obligation'
2. fill up the trash by deleting files exceeding the quota
3. Try to recover the files from the trash bin
4. it's not possible to recover files if no enough space is left

### Nextcloud Server version

30

### Operating system

None

### PHP engine version

PHP 8.1

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by leftybournes**
* Resolves: #52303 

## Summary
Check if a user has enough space to restore a file before doing it.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [X] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [X] Screenshots before/after for front-end changes
- [X] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by susnux — COMMENTED** [review]
Not sure as the "free space" is cached and could be larger or smaller.
So worst case this is cancelled even if there is enough space, just because its cached with smaller free space.

Maybe instead do that on the trashbin DAV plugin and check if there is enough free space, otherwise fail and report the missing space (http 507).
So we can catch and handle in frontend, but backend has a chance to properly check this.

**Comment by leftybournes** [comment]
Thanks for pointing that out. I'll look into doing it that way instead.

File: apps/files_trashbin/lib/Sabre/TrashbinPlugin.php [hunk 1]
```diff
@@ -129,4 +131,47 @@ public function httpGet(RequestInterface $request, ResponseInterface $response):
...
+		if (!$fileInfo instanceof ITrashItem) {
+			return true;
+		}
+		$user = $fileInfo->getUser();
+		$quota = $user->getQuota();
+		if ($quota === null || $quota === 'none') {
+			return true;
+		}
+
+		$freeSpace = Filesystem::free_space($user->getHome());
```
Comment (provokateurin) [inline apps/files_trashbin/lib/Sabre/TrashbinPlugin.php:168]: I'm not sure if this is going to work, as the restore could also be to a non-home storage where a different/no quota applies. However I'm not sure if we have a generic way to query the quota of a storage so you can check it that way.

File: apps/files_trashbin/src/files_actions/restoreAction.ts [hunk 2]
```diff
@@ -52,6 +53,9 @@ export const restoreAction = new FileAction({
 			emit('files:node:deleted', node)
 			return true
 		} catch (error) {
+			if (error.response?.status === 507) {
+				showError(t('files', 'Not enough free space'))
```
Comment (provokateurin) [inline apps/files_trashbin/src/files_actions/restoreAction.ts:57]:
```suggestion
				showError(t('files', 'Not enough free space to restore the file/folder'))
```

File: apps/files_trashbin/lib/Sabre/TrashbinPlugin.php [hunk 3]
```diff
@@ -129,4 +132,40 @@ public function httpGet(RequestInterface $request, ResponseInterface $response):
...
+	 * @param string $sourcePath
+	 * @param string $destinationPath
+	 * @return bool
+	 */
+	public function beforeMove(string $sourcePath, string $destinationPath): bool {
+		try {
+			$node = $this->server->tree->getNodeForPath($sourcePath);
+			$destinationNode = $this->server->tree->getNodeForPath(dirname($destinationPath));
+		} catch (\Exception $e) {
+			return true;
```
Comment (provokateurin) [inline apps/files_trashbin/lib/Sabre/TrashbinPlugin.php:149]: You should only catch \Sabre\DAV\Exception\NotFound which you can silently ignore. If you ever need to catch a broad set of exceptions make sure to always log the exceptions. Otherwise it can be really hard to debug if you only have the logs and no step-debugger.

File: apps/files_trashbin/lib/Sabre/TrashbinPlugin.php [hunk 4]
```diff
@@ -129,4 +132,40 @@ public function httpGet(RequestInterface $request, ResponseInterface $response):
...
+	 * restore from trashbin unless they have unlimited quota.
+	 *
+	 * @param string $sourcePath
+	 * @param string $destinationPath
+	 * @return bool
+	 */
+	public function beforeMove(string $sourcePath, string $destinationPath): bool {
+		try {
+			$node = $this->server->tree->getNodeForPath($sourcePath);
+			$destinationNode = $this->server->tree->getNodeForPath(dirname($destinationPath));
```
Comment (provokateurin) [inline apps/files_trashbin/lib/Sabre/TrashbinPlugin.php:147]:
```suggestion
			$destinationNodeParent = $this->server->tree->getNodeForPath(dirname($destinationPath));
```
Just to make it clear that this is not the destination node itself but the parent folder.

File: apps/files_trashbin/lib/Sabre/TrashbinPlugin.php [hunk 5]
```diff
@@ -129,4 +132,40 @@ public function httpGet(RequestInterface $request, ResponseInterface $response):
...
+		}
+
+		$fileInfo = $node->getFileInfo();
+		if (!$fileInfo instanceof ITrashItem) {
+			return true;
+		}
+		$restoreFolder = dirname($fileInfo->getOriginalLocation());
+		$freeSpace = $this->view->free_space($restoreFolder);
+		$filesize = $fileInfo->getSize();
+		if ($freeSpace >= 0 && $freeSpace < $filesize) {
```
Comment (provokateurin) [inline apps/files_trashbin/lib/Sabre/TrashbinPlugin.php:164]:
```suggestion
		if ($freeSpace < $filesize) {
```
This should be redundant

File: apps/files_trashbin/tests/Sabre/TrashbinPluginTest.php [hunk 6]
```diff
@@ -0,0 +1,61 @@
...
+		$fileInfo->method('getSize')->willReturn($fileSize);
+		$trashNode = $this->createMock(ITrash::class);
+		$trashNode->method('getFileInfo')->willReturn($fileInfo);
+		$restoreNode = $this->createMock(RestoreFolder::class);
+		$this->server->tree->method('getNodeForPath')->willReturn($trashNode, $restoreNode);
+		$previewManager = $this->createMock(IPreview::class);
+		$view = $this->createMock(View::class);
+		$view->method('free_space')->willReturn($freeSpace);
+		$plugin = new TrashbinPlugin($previewManager, $view);
+		$plugin->initialize($this->server);
```
Comment (provokateurin) [inline apps/files_trashbin/tests/Sabre/TrashbinPluginTest.php:45]:
```suggestion
		$fileInfo = $this->createMock(ITrashItem::class);
		$fileInfo->method('getSize')->willReturn($fileSize);

		$trashNode = $this->createMock(ITrash::class);
		$trashNode->method('getFileInfo')->willReturn($fileInfo);

		$restoreNode = $this->createMock(RestoreFolder::class);

		$this->server->tree->method('getNodeForPath')->willReturn($trashNode, $restoreNode);

		$previewManager = $this->createMock(IPreview::class);

		$view = $this->createMock(View::class);
		$view->method('free_space')->willReturn($freeSpace);

		$plugin = new TrashbinPlugin($previewManager, $view);
		$plugin->initialize($this->server);
```
Just add some empty lines to make it more readable.

**Review by provokateurin — CHANGES_REQUESTED** [review]
LGTM, just some minor ideas for improvement

File: apps/files_trashbin/lib/Sabre/TrashbinPlugin.php (hunk 5 above)
Comment (leftybournes) [reply apps/files_trashbin/lib/Sabre/TrashbinPlugin.php:164]: There are times when `view->free_space()` returns negative values mapping to `FileInfo::SPACE_NOT_COMPUTED`, `FileInfo::SPACE_UNKNOWN` and `FileInfo::SPACE_UNLIMITED` which is why I had the `$freeSpace >= 0` check to ignore and allow restoring in those cases but I realize it might be better to check against those constants explicitly.

Comment (provokateurin) [reply apps/files_trashbin/lib/Sabre/TrashbinPlugin.php:164]: Oh I totally forgot about that! Yes I think it makes sense to check for the constants explicitly so that the code is more self-explanatory.

**Review by provokateurin — APPROVED** [review]
Did not test, but looks nice!

**Review by yemkareems — APPROVED** [review]
