### PR TITLE
fix(setupchecks): Skip checking for OPcache settings if running checks from CLI

### LINKED ISSUE #46351: [Bug]: `occ setupchecks` - OPcache Configuration Checks should not be performed if `opcache.enable_cli` is disabled
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When running the `occ setupchecks` command after upgrading to v29.0.3, the following errors related to PHP OPcache configuration are encountered:

```
✗ PHP opcache: The PHP OPcache module is not properly configured. OPcache is not working as it should, opcache_get_status() returns false, please check configuration.
The maximum number of OPcache keys is nearly exceeded. To assure that all scripts can be kept in the cache, it is recommended to apply "opcache.max_accelerated_files" to your PHP configuration with a value higher than "10000".
The OPcache buffer is nearly full. To assure that all scripts can be hold in cache, it is recommended to apply "opcache.memory_consumption" to your PHP configuration with a value higher than "128"..
```

It appears that the OPcache checks are being performed even when `opcache.enable_cli` is disabled. Since OPcache is intentionally disabled for CLI calls by default, these checks should be skipped in this context.

see: https://github.com/nextcloud/docker/issues/2184#issuecomment-2212576523

### Steps to reproduce

1. Run v29.0.3.
2. Run the `occ setupchecks` command.
3. Observe the OPcache related errors.

### Expected behavior

The `occ setupchecks` command should:

Skip OPcache checks if `opcache.enable_cli` is disabled.
Only perform OPcache checks if `opcache.enable_cli` is enabled.

### Installation method

Community Docker image

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

Link to conversation: https://github.com/nextcloud/docker/issues/2184#issuecomment-2082845207

### Proposed Solution
1. Check if `opcache.enable_cli` is enabled: Before running any OPcache checks, the command should first verify whether `opcache.enable_cli` is enabled.
2. Skip checks if disabled: If `opcache.enable_cli` is disabled (which is a reasonable default and production value), the command should not perform any OPcache checks or return related errors.
3. Perform checks if enabled: If `opcache.enable_cli` is enabled, the command can run the OPcache checks for debugging and development purposes.

### PR DESCRIPTION
**Pull request by solracsf**
* Resolves: https://github.com/nextcloud/server/issues/46351

## Summary

We don't recommend to enable OPcache on CLI, so disable the checks in this case.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/settings/lib/SetupChecks/PhpOpcacheSetup.php [hunk 1]
```diff
@@ -114,6 +114,11 @@ protected function getOpcacheSetupRecommendations(): array {
 	}
 
 	public function run(): SetupResult {
+		// Skip OPcache checks if running from CLI
+		if (PHP_SAPI === 'cli') {
+			return SetupResult::success($this->l10n->t('Checking from CLI, OPcache checks have been skipped.'));
```
Comment (kesselb) [inline apps/settings/lib/SetupChecks/PhpOpcacheSetup.php:119]:
```suggestion
			return SetupResult::info($this->l10n->t('This check is skipped because OPcache is turned off.'));
```

**Review by kesselb — APPROVED** [review]

File: apps/settings/lib/SetupChecks/PhpOpcacheSetup.php (hunk 1 above)
Comment (MichaIng) [inline apps/settings/lib/SetupChecks/PhpOpcacheSetup.php:119]: Just in case is might be ever wanted for debugging, development or CI, an alternative would be to do run those checks, if OPcache is enabled for CLI:
```suggestion
if (PHP_SAPI === 'cli' && !$this->iniGetWrapper->getBool('opcache.enable_cli')) {
	return SetupResult::success($this->l10n->t('OPcache checks are skipped since it is disabled for CLI.'));
```
It could be also done in the last `else` block of `getOpcacheSetupRecommendations()`, to at last do those checks which are still possible from CLI: if the module is enabled, and shared memory based cache enabled for web, theoretically also saved comments etc. However, since PHP modules can be enabled/disabled per SAPI, this bears the risk of false positives.

Comment (MichaIng) [reply apps/settings/lib/SetupChecks/PhpOpcacheSetup.php:119]: Not sure in how far the output style of `info` differs from `success`, but I would indeed rate it as success when OPcache is disabled for CLI, since this is recommended for production systems. And in any case, the text should keep the info that it is skipped because we are running from CLI, or "turned off for CLI", else the information is wrong.

File: apps/settings/lib/SetupChecks/PhpOpcacheSetup.php [hunk 2]
```diff
@@ -114,6 +114,11 @@ protected function getOpcacheSetupRecommendations(): array {
 	}
 
 	public function run(): SetupResult {
+		// Skip OPcache checks if running from CLI
+		if (PHP_SAPI === 'cli') {
```
Comment (come-nc) [inline apps/settings/lib/SetupChecks/PhpOpcacheSetup.php:118]: This is the only place this check is done like this, it should check `\OC::$CLI` instead, no?

**Review by come-nc — COMMENTED** [review]
Why is recommended to disable opcache for CLI? This is unexpected to me, the cron and occ commands should also benefit from opcache, no?

**Comment by solracsf** [comment]
> Why is recommended to disable opcache for CLI? This is unexpected to me, the cron and occ commands should also benefit from opcache, no?

https://github.com/nextcloud/documentation/issues/1439

**Review by MichaIng — APPROVED** [review]
Looks good:
```
        php:
                ✓ PHP default charset: UTF-8
                ✓ PHP set_time_limit: The function is available.
                ✓ Freetype: Supported
                ✓ PHP getenv
                ✓ PHP memory limit: 512 MB
                ℹ PHP modules: This instance is missing some recommended PHP modules. For improved performance and better compatibility it is highly recommended to install them:
- bcmath for WebAuthn passwordless login
- gmp for WebAuthn passwordless login, and SFTP storage
                ✓ PHP opcache: Checking from CLI, OPcache checks have been skipped.
                ✓ PHP "output_buffering" option: Disabled
                ℹ PHP Imagick module: The PHP module "imagick" is not enabled although the theming app is. For favicon generation to work correctly, you need to install and enable this module.
```
After setting `opcache.enable_cli=1`:
```
        php:
                ✓ PHP default charset: UTF-8
                ✓ PHP set_time_limit: The function is available.
                ✓ Freetype: Supported
                ✓ PHP getenv
                ✓ PHP memory limit: 512 MB
                ℹ PHP modules: This instance is missing some recommended PHP modules. For improved performance and better compatibility it is highly recommended to install them:
- bcmath for WebAuthn passwordless login
- gmp for WebAuthn passwordless login, and SFTP storage
                ✓ PHP opcache: Correctly configured
                ✓ PHP "output_buffering" option: Disabled
                ℹ PHP Imagick module: The PHP module "imagick" is not enabled although the theming app is. For favicon generation to work correctly, you need to install and enable this module.
```
_Not sure whether we can easily add correct indentation after line breaks?_
____________
In addition, with `opcache.log_verbosity_level=3`, I see a few pages with lines like:
```
Mon Jul  8 16:01:59 2024 (21777): Message Cached script '/var/www/nextcloud/lib/public/AppFramework/Http/Attribute/UseSession.php'
Mon Jul  8 16:01:59 2024 (21777): Message Added key '/var/www/nextcloud/lib/composer/composer/../../../lib/public/AppFramework/Http/Attribute/UseSession.php'
```
indicating how the OPcache is filled. On a Raspberry Pi 2, this increases the time of all `occ` calls by 1.5 - 2 seconds:
```console
root@micha:/var/www/nextcloud# time ncc setupchecks &> /dev/null

real    0m17.633s
user    0m0.010s
sys     0m0.059s
root@micha:/var/www/nextcloud# time ncc setupchecks &> /dev/null

real    0m17.664s
user    0m0.041s
sys     0m0.030s
root@micha:/var/www/nextcloud# sed -i '/^opcache.enable_cli=/s/^/#/' /etc/php/8.2/mods-available/micha.ini # disable OPcache
root@micha:/var/www/nextcloud# time ncc setupchecks &> /dev/null

real    0m15.744s
user    0m0.025s
sys     0m0.047s
root@micha:/var/www/nextcloud# time ncc setupchecks &> /dev/null

real    0m15.813s
user    0m0.027s
sys     0m0.043s
root@micha:/var/www/nextcloud# time ncc &> /dev/null

real    0m2.557s
user    0m0.031s
sys     0m0.040s
root@micha:/var/www/nextcloud# time ncc &> /dev/null

real    0m2.562s
user    0m0.032s
sys     0m0.039s
root@micha:/var/www/nextcloud# sed -i '/^#opcache.enable_cli=/s/#//' /etc/php/8.2/mods-available/micha.ini # enable OPcache
root@micha:/var/www/nextcloud# time ncc &> /dev/null

real    0m4.123s
user    0m0.032s
sys     0m0.039s
root@micha:/var/www/nextcloud# time ncc &> /dev/null

real    0m4.054s
user    0m0.022s
sys     0m0.051s
```
@come-nc just to demonstrate that it really makes sense to have OPcache disabled for CLI.

**Comment by come-nc** [comment]
Then it should not even say "✓ PHP opcache: Correctly configured" when it is enabled, no?

**Comment by MichaIng** [comment]
But we might want to be able to test checks from CLI? Also, while it is good that we do not print a warning without `opcache.enable_cli=1` anymore (which we did in the past), I am not sure whether we should now actively print a warning with `opcache.enable_cli=1` 🤔. It does not make sense, but it also does not break anything, and at least users/visitors are not affected by CLI performance.

**Comment by come-nc** [comment]
> But we might want to be able to test checks from CLI?

There is the same problem with all checks on PHP configuration, running them from CLI tests the wrong configuration.
So the right way would be to use the API to get the results from server but occ has no access token for that. Experienced admin can always do it by hand with curl.

**Review by szaimen — APPROVED** [review]

**Comment by MichaIng** [comment]
> There is the same problem with all checks on PHP configuration, running them from CLI tests the wrong configuration.

Not necessarily the wrong configuration, only the wrong usage stats for sure. It would still be possible to configure PHP either for all SAPI's or CLI in particular the wrong and right way, and test whether `occ setupchecks` returns the correct results. As far as I can see, after migration to the new API, these checks are not tested? However, if we really want to have admins disabling OPcache for CLI now, and still want to be able to add PHPUnit tests:
```php
		// We cannot check the PHP web SAPI config and OPcache usage stats from CLI
		// and building the OPcache usually worsens the performance of CLI calls.
		// Hence recommend to disable OPcache for CLI (which is the PHP default) and skip further OPcache checks.
		if (\OC::$CLI && !defined('PHPUNIT_RUN')) {
			if ($this->iniGetWrapper->getBool('opcache.enable_cli')) {
				return SetupResult::warning($this->l10n->t('OPcache is enabled for CLI. For better occ and background job performance, it is recommended to apply "opcache.enable_cli=0" to your PHP configuration.'));
			}
			return SetupResult::success($this->l10n->t('OPcache is disabled for CLI as recommended. Skipping further OPcache checks.'));
		}
```

**Comment by come-nc** [comment]
We should not have checks for `PHPUNIT_RUN` in the code, phpunit tests can mock the iniGetWrapper to return a config they want to test, and can set `OC::$CLI` according to what they want to test.

**Review by come-nc — APPROVED** [review]
