### PR TITLE
Set fileInfo correctly for LegacyTabs

### LINKED ISSUE #20106: Files sidebar: Activity tab not updating on file switch
Peek 2020-03-23 13-33

### Steps to reproduce
1. Click on ... > Details at File A => sidebar opens, focusing activity tab in sidebar
2. See activities for File A
3. Click on ... > Details at File B

### Expected behaviour
Activities for File B are shown

### Actual behaviour
Activities for File A are shown

### Server configuration

NC 18.0.2 + 18.0.3

### PR DESCRIPTION
**Pull request by go2sh**
Watch for changes of the fileInfo prop and propagate it to the underlying component.

Fixes #20106.

### CODE REVIEW

File: apps/files/src/components/LegacyTab.vue [hunk 1]
```diff
@@ -68,9 +68,9 @@ export default {
 		},
 	},
 	watch: {
-		activeTab(activeTab) {
-			if (activeTab === this.id && this.fileInfo) {
-				this.setFileInfo(this.fileInfo)
+		fileInfo(fileInfo) {
```
Comment (skjnldsv) [inline apps/files/src/components/LegacyTab.vue:71]: It means every time the fileinfo changes, all the tabs gets reloaded?

Comment (go2sh) [reply apps/files/src/components/LegacyTab.vue:71]: I'am not sure, what you mean. The fileInfo is set once through the open method of the sidebar. (triggered through the Details click in the action list). Each tab get the fileInfo as prop from the sidebar. My change is just here to propagate the change to the component of the legacytab. Currently the fileInfo in the legacy component is only updates on the first load of the sidebar or when you change the tab back and forth (see the if clause). To fix the bug mentioned it needs to propagate every time the prop changes.

Comment (go2sh) [reply apps/files/src/components/LegacyTab.vue:71]: If you want to prevent loading data in the background, I could leave both. The activeTab watch for changing tabs and the fileInfo if it is the activeTab. But I think there is no drawback of loading every thing at once as it makes switching tabs more seamless.

Comment (skjnldsv) [reply apps/files/src/components/LegacyTab.vue:71]: No, I guess it's fine :)
I was concerned about the legacy tabs, but the vue ones should be smart enough to only refresh what is needed, so it's fine!
We'll kill the old tabs eventually! :+1:

**Review by skjnldsv — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
Code looks good 👍

**Comment by MorrisJobke** [comment]
@skjnldsv @go2sh Backport to 18?

**Comment by go2sh** [comment]
Yes, please. The bug is also present in 18 at least.
