### PR TITLE
fix(files): breadcrumbs drag-and-drop & unifying methods

### LINKED ISSUE #42869: [Bug]:  moving files using drag & drop on the "folder breadcrumbs" fails
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Until NC 27 I was able to move around files using drag & drop on the "folder breadcrumbs", such as a file in located in HOME->Documents->Work could easily moved: selected, dragged and dropped on the "Documents" or the "HOME-ICON"

### Steps to reproduce

1. go to any folder under the home, let's we call it "Documents->Work"
2. select a file located in this folder
3. drag it on the "Documents" label in the breadcrumb (the name highlights)
4. drop it to move there

### Expected behavior

the selected file shall be moved to the doped location, as it worked in NC 27

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.fedibox.com:8080",
            "cloud.fedibox.com:80",
            "cloud.fedibox.com:443"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.1.1",
        "overwritehost": "cloud.fedibox.com",
        "overwriteprotocol": "https",
        "overwritewebroot": "\/",
        "overwrite.cli.url": "https:\/\/cloud.fedibox.com\/",
        "installed": true,
        "maintenance": false,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "IT",
        "loglevel": 1,
        "log_rotate_size": 10485760,
        "theme": "",
        "app_install_overwrite": [
            "carnet",
            "fulltextsearch_elasticsearch",
            "workflow_ocr",
            "richdocuments",
            "impersonate",
            "spreed",
            "fulltextsearch",
            "files_fulltextsearch"
        ],
        "has_rebuilt_cache": true
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - calendar: 4.6.2
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contacts: 5.5.1
  - contactsinteraction: 1.9.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_fulltextsearch: 28.0.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - fulltextsearch: 28.0.0
  - fulltextsearch_elasticsearch: 28.0.0
  - impersonate: 1.15.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notes: 4.9.2
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - richdocuments: 8.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - support: 1.11.0
  - survey_client: 1.16.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - workflow_ocr: 1.28.0
  - workflowengine: 2.10.0
Disabled:
  - bruteforcesettings: 2.8.0 (installed 2.3.0)
  - dashboard: 7.8.0 (installed 7.2.0)
  - encryption: 2.16.0
  - files_external: 1.20.0
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - suspicious_login: 6.0.0
  - twofactor_totp: 10.0.0-beta.2
  - user_ldap: 1.19.0
  - weather_status: 1.8.0 (installed 1.2.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
nextcloud        | 127.0.0.1 - - [13/Jan/2024:07:26:44 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.57 (Debian) PHP/8.2.14 (internal dummy connection)"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:26:50 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:27:17 +0000] "GET /apps/files/api/v1/stats HTTP/1.1" 200 931 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:27:21 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:27:51 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:28:19 +0000] "GET /apps/files/api/v1/stats HTTP/1.1" 200 931 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:28:22 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:28:52 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:29:19 +0000] "GET /apps/files/api/v1/stats HTTP/1.1" 200 931 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:29:22 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:29:53 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:30:17 +0000] "PUT /ocs/v2.php/apps/user_status/api/v1/heartbeat?format=json HTTP/1.1" 204 688 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:30:20 +0000] "GET /apps/files/api/v1/stats HTTP/1.1" 200 932 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:30:23 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:30:54 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:31:21 +0000] "GET /apps/files/api/v1/stats HTTP/1.1" 200 932 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:31:25 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:31:55 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:32:16 +0000] "GET /csrftoken HTTP/1.1" 200 894 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:32:22 +0000] "GET /apps/files/api/v1/stats HTTP/1.1" 200 932 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:32:26 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:32:56 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:33:23 +0000] "GET /apps/files/api/v1/stats HTTP/1.1" 200 932 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:33:27 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:33:57 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:34:23 +0000] "GET /apps/files/api/v1/stats HTTP/1.1" 200 932 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:34:28 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:34:58 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 763 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:35:13 +0000] "GET /index.php/settings/integrity/failed HTTP/1.1" 200 808 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
nextcloud        | 192.168.178.45 - - [13/Jan/2024:07:35:14 +0000] "GET /index.php/apps/files/preview-service-worker.js HTTP/1.1" 200 6698 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
```

### Additional info

This is a video capture of the problem,as you can see nothing happens when file is dropped in the breadcrumb labels.

https://github.com/nextcloud/server/assets/25344258/9b67d96e-9971-4a1a-bb72-5f66fd030fc6

moved from #42751

### LINKED ISSUE #43313: [Bug]: File upload via Drag and Drop overwrites existing files without further notice
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Since the upgrade to Nextcloud 28.0.2 file upload via Drag and Drop is working again. However if you use Drag and Drop to upload a file with the exact same name as an existing file, the existing file on the server will be overwritten without further notice.

### Steps to reproduce

1. Create for example a **.bin** file locally with any content (**.bin** as **.txt** would be cached by the text editor)
2. Upload the file to the Nextcloud server
3. Locally change the content of the file
4. Upload the changed file via Drag and Drop
5. Check the content of the file now present on the server.

### Expected behavior

When dropping an existing file Nextcloud should display the usual dialogue which lets you select if you like to keep the existing file, the new file, or both files instead of just overwriting any existing data,  as is the case when uploading an existing file using the file chooser.

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.2.5",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "maintenance": false,
        "overwriteprotocol": "https",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "default_phone_region": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - calendar: 4.6.4
  - cloud_federation_api: 1.11.0
  - contacts: 5.5.1
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - files: 2.0.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - survey_client: 1.16.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_totp: 10.0.0-beta.2
  - updatenotification: 1.18.0
  - viewer: 2.2.0
  - workflowengine: 2.10.0
Disabled:
  - circles: 28.0.0-dev (installed 25.0.0)
  - comments: 1.18.0 (installed 1.15.0)
  - contactsinteraction: 1.9.0 (installed 1.6.0)
  - dashboard: 7.8.0 (installed 7.5.0)
  - encryption: 2.16.0
  - federation: 1.18.0 (installed 1.15.0)
  - files_external: 1.20.0
  - files_pdfviewer: 2.9.0 (installed 2.6.0)
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - firstrunwizard: 2.17.0 (installed 2.14.0)
  - gpxpod: 5.0.15 (installed 5.0.15)
  - mail: 3.5.5 (installed 3.5.5)
  - nextcloud_announcements: 1.17.0 (installed 1.14.0)
  - recommendations: 2.0.0 (installed 1.4.0)
  - related_resources: 1.3.0 (installed 1.0.3)
  - richdocuments: 8.3.1 (installed 8.3.1)
  - richdocumentscode: 23.5.705 (installed 23.5.705)
  - spreed: 18.0.3 (installed 18.0.3)
  - support: 1.11.0 (installed 1.8.0)
  - suspicious_login: 6.0.0
  - systemtags: 1.18.0 (installed 1.15.0)
  - user_ldap: 1.19.0
  - user_status: 1.8.1 (installed 1.5.0)
  - weather_status: 1.8.0 (installed 1.5.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

_No response_

### Additional info

- Firefox 115 ESR

- `[NcButton.mjs:145:37](webpack:///nextcloud/node_modules/@nextcloud/vue/dist/Components/NcButton.mjs)

You need to fill either the text or the ariaLabel props in the button component. 
Object { text: undefined, ariaLabel: "" }
 
Object { _uid: 241, _isVue: true, __v_skip: true, _scope: {…}, "$options": {…}, _renderProxy: {…}, _self: {…}, "$parent": {…}, "$root": {…}, "$children": (1) […], … }
[NcButton.mjs:145:37](webpack:///nextcloud/node_modules/@nextcloud/vue/dist/Components/NcButton.mjs)​`

### LINKED ISSUE #44278: [Bug]: Local folder drag-n-drop to Files folder not working
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When dragging a folder from the local filesystem onto a folder in Nextcloud Files, the folder is not uploaded into the appropriate remote folder and console errors appear.

### Steps to reproduce

1. Create a test folder with some files in it
2. Drag the folder from your file explorer onto a folder in Nextcloud Files and drop it

### Expected behavior

The expected behavior would be that the folder from the local filesystem and its contents are uploaded into the folder on Nextcloud Files.

### Installation method

None

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "debug": true,
        "profiler": true,
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/apps-extra",
                "url": "\/apps-extra",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/apps-shared",
                "url": "\/apps-shared",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/apps-writable",
                "url": "\/apps-writable",
                "writable": true
            }
        ],
        "allow_local_remote_servers": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "1025",
        "skeletondirectory": "\/skeleton",
        "setup_create_db_user": false,
        "loglevel": 2,
        "log_query": false,
        "query_log_file": "\/shared\/log\/querylog-nextcloud.log",
        "query_log_file_requestid": "yes",
        "diagnostics.logging": false,
        "diagnostics.logging.threshold": 0,
        "log.condition": {
            "apps": [
                "diagnostics",
                "admin_audit"
            ]
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "nextcloud",
            "nextcloud.local",
            "192.168.21.6",
            "localhost"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "29.0.0.10",
        "overwrite.cli.url": "http:\/\/nextcloud.local",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "git",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "lookup_server": "",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "collectives"
        ],
        "theme": "",
        "maintenance": false
    }
}
```

### List of activated Apps

```shell
Enabled:
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - collectives: 2.10.0
  - comments: 1.19.0
  - contactsinteraction: 1.10.0
  - dashboard: 7.9.0
  - dav: 1.30.0
  - deck: 1.13.0-beta.1
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.0
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - lookup_server_connector: 1.17.0
  - notes: 4.9.2
  - oauth2: 1.17.0
  - profiler: 1.5.0
  - provisioning_api: 1.19.0
  - recommendations: 2.1.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - systemtags: 1.19.0
  - tables: 0.7.0-beta.2
  - text: 3.10.0
  - theming: 2.4.0
  - twofactor_backupcodes: 1.18.0
  - updatenotification: 1.19.1
  - user_status: 1.9.0
  - viewer: 2.3.0
  - weather_status: 1.9.0
  - workflowengine: 2.11.0
Disabled:
  - admin_audit: 1.19.0
  - encryption: 2.17.0
  - files_external: 1.21.0
  - hmr_enabler: 1.0.0
  - testing: 1.19.0
  - user_ldap: 1.20.0
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

image

### PR DESCRIPTION
**Pull request by skjnldsv**
Needs https://github.com/nextcloud-libraries/nextcloud-upload/pull/1123
Needs https://github.com/nextcloud-libraries/nextcloud-upload/pull/1131

Fix https://github.com/nextcloud/server/issues/42869
Fix https://github.com/nextcloud/server/issues/43313
Fix https://github.com/nextcloud/server/issues/44278

## Progress
- [x] Drag and Drop Area
- [x] Breadcrumbs
- [x] File entry
- [x] Unify drag and drop recursive methods between the three components above
- [x] Tests

### CODE REVIEW

File: apps/files/src/services/DropServiceUtils.ts [hunk 1]
```diff
@@ -0,0 +1,195 @@
...
+	 * Get the last modification time of a file tree
+	 * This is not perfect, but will get us a pretty good approximation
+	 * @param directory the directory to traverse
+	 */
+	_computeDirectoryMtime(directory: Directory): number {
+		return directory.contents.reduce((acc, file) => {
+			return file.lastModified > acc
+				// If the file is a directory, the lastModified will
+				// also return the results of its _computeDirectoryMtime method
+				// Fancy recursion, huh?
```
Comment (artonge) [inline apps/files/src/services/DropServiceUtils.ts:78]: :rofl:

File: apps/files/src/components/BreadCrumbs.vue [hunk 2]
```diff
@@ -160,6 +187,77 @@ export default defineComponent({
...
+		onDragOver(event: DragEvent, path: string) {
+			// Cannot drop on the current directory
+			if (path === this.dirs[this.dirs.length - 1]) {
+				event.dataTransfer.dropEffect = 'none'
+				return
+			}
+
+			// Handle copy/move drag and drop
+			if (event.ctrlKey) {
+				event.dataTransfer.dropEffect = 'copy'
```
Comment (artonge) [inline apps/files/src/components/BreadCrumbs.vue:199]: If we copy, maybe we can allow dragging to the current directory?

**Review by artonge — APPROVED** [review]

File: apps/files/src/components/BreadCrumbs.vue [hunk 3]
```diff
@@ -160,6 +187,77 @@ export default defineComponent({
...
+			} else {
+				event.dataTransfer.dropEffect = 'move'
```
Comment (susnux) [inline apps/files/src/components/BreadCrumbs.vue:201]: We set the mode here and then :arrow_down:

File: apps/files/src/components/BreadCrumbs.vue [hunk 4]
```diff
@@ -160,6 +187,77 @@ export default defineComponent({
...
+			// We might not have the target directory fetched yet
+			const contents = await this.currentView?.getContents(path)
+			const folder = contents?.folder
+			if (!folder) {
+				showError(this.t('files', 'Target folder does not exist any more'))
+				return
+			}
+
+			const canDrop = (folder.permissions & Permission.CREATE) !== 0
+			const isCopy = event.ctrlKey
```
Comment (susnux) [inline apps/files/src/components/BreadCrumbs.vue:233]: :arrow_up: here we again get the information about copy / move. What is the reason to set in on drag over instead of only check it on drop?

File: apps/files/src/components/DragAndDropNotice.vue [hunk 5]
```diff
@@ -161,38 +163,53 @@ export default defineComponent({
...
-					this.$router.push({
-						...this.$route,
-						params: {
-							view: this.$route.params?.view ?? 'files',
-							fileid: parseInt(lastUpload.response!.headers['oc-fileid']),
-						},
-					})
-				}
+			// Caching the selection
+			const items = [...event.dataTransfer?.items || []] as DataTransferItem[]
```
Comment (susnux) [inline apps/files/src/components/DragAndDropNotice.vue:167]: Q: Do you prefer this over this?

```suggestion
			const items: DataTransferItem[] = [...event.dataTransfer?.items || []]
```

File: apps/files/src/services/DropService.ts [hunk 6]
```diff
@@ -21,123 +22,196 @@
...
-	// TODO: Maybe handle `getAsFileSystemHandle()` in the future
-
-	const uploads = [] as Upload[]
-	// we need to cache the entries to prevent Blink engine bug that clears the list (`data.items`) after first access props of one of the entries
-	const entries = [...data.items]
+/**
+ * This function converts a list of DataTransferItems to a file tree.
+ * It uses the Filesystem API if available, otherwise it falls back to the File API.
+ * The File API will NOT be available if the browser is not in a secure context (e.g. HTTP).
+ * ⚠️ When using this method, you need to use it as fast as possible, as the DataTransferItems
```
Comment (susnux) [inline apps/files/src/services/DropService.ts:44]: Blink engine why are you doing this to use?...

**Review by susnux — APPROVED** [review]
Makes sense!

File: apps/files/src/components/DragAndDropNotice.vue (hunk 5 above)
Comment (skjnldsv) [reply apps/files/src/components/DragAndDropNotice.vue:167]: No preferences :)

File: apps/files/src/components/BreadCrumbs.vue (hunk 4 above)
Comment (skjnldsv) [reply apps/files/src/components/BreadCrumbs.vue:233]: Drag over `event.dataTransfer.dropEffect` is only to change the cursor :)

https://github.com/nextcloud/server/assets/14975046/f0421c2e-3855-431f-934e-5f43f7faef0c

You wanted me to do something like this ?
```suggestion
			const isCopy = event.dataTransfer?.dropEffect === 'copy' || event.ctrlKey
```

Comment (susnux) [reply apps/files/src/components/BreadCrumbs.vue:233]: Ah nice!

**Comment by skjnldsv** [comment]
Failure unrelated
