### PR TITLE
fix(db): no hardcoded table prefix is expected

### LINKED ISSUE #39379: systag_by_tagid index is not created via occ db:add-missing-indices
I don't know if this is the right place but I just updated 3 instances, two with MySQL, one with PostgreSQL to 27.0.1 RC1

The /settings/admin/overview throws this message:

image

but on  all of the three instances

`occ db:add-missing-indices`

does not make any changes at all nor do i get the sql query with

`occ db:add-missing-indices --dry-run`

and the warning does not disapear.

```
MariaDB [nextcloud]> explain select * from oc_systemtag_object_mapping where systemtagid = 568;
+------+-------------+-----------------------------+-------+---------------+---------+---------+------+--------+--------------------------+
| id   | select_type | table                       | type  | possible_keys | key     | key_len | ref  | rows   | Extra                    |
+------+-------------+-----------------------------+-------+---------------+---------+---------+------+--------+--------------------------+
|    1 | SIMPLE      | oc_systemtag_object_mapping | index | NULL          | PRIMARY | 524     | NULL | 143547 | Using where; Using index |
+------+-------------+-----------------------------+-------+---------------+---------+---------+------+--------+--------------------------+
1 row in set (0.000 sec)

MariaDB [nextcloud]> DESCRIBE oc_systemtag_object_mapping;
+-------------+---------------------+------+-----+---------+-------+
| Field       | Type                | Null | Key | Default | Extra |
+-------------+---------------------+------+-----+---------+-------+
| objectid    | varchar(64)         | NO   | PRI |         |       |
| objecttype  | varchar(64)         | NO   | PRI |         |       |
| systemtagid | bigint(20) unsigned | NO   | PRI | 0       |       |
+-------------+---------------------+------+-----+---------+-------+
3 rows in set (0.001 sec)

MariaDB [nextcloud]> SHOW INDEXES FROM oc_systemtag_object_mapping;
+-----------------------------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table                       | Non_unique | Key_name | Seq_in_index | Column_name | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
+-----------------------------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| oc_systemtag_object_mapping |          0 | PRIMARY  |            1 | objecttype  | A         |           2 |     NULL | NULL   |      | BTREE      |         |               |
| oc_systemtag_object_mapping |          0 | PRIMARY  |            2 | objectid    | A         |      143547 |     NULL | NULL   |      | BTREE      |         |               |
| oc_systemtag_object_mapping |          0 | PRIMARY  |            3 | systemtagid | A         |      143547 |     NULL | NULL   |      | BTREE      |         |               |
+-----------------------------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
3 rows in set (0.001 sec)


```

_Originally posted by @ernolf in https://github.com/nextcloud/server/issues/38928#issuecomment-1634835032_

### PR DESCRIPTION
**Pull request by blizzz**
* Resolves: #39379

## Summary

The database prefix is variable and can be set upon installation. The database methods expect table names without prefix.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

File: core/Command/Db/AddMissingIndices.php [hunk 1]
```diff
@@ -473,8 +473,8 @@ private function addCoreIndexes(OutputInterface $output, bool $dryRun): void {
 		}
 
 		$output->writeln('<info>Check indices of the oc_systemtag_object_mapping table.</info>');
-		if ($schema->hasTable('oc_systemtag_object_mapping')) {
-			$table = $schema->getTable('oc_systemtag_object_mapping');
+		if ($schema->hasTable('systemtag_object_mapping')) {
+			$table = $schema->getTable('systemtag_object_mapping');
```
Comment (marcelklehr) [inline core/Command/Db/AddMissingIndices.php:477]: damn.

**Review by marcelklehr — APPROVED** [review]
