### PR TITLE
Fix position of search bar

### LINKED ISSUE #28584: NC 22.1.0 - Search modal
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Install a fresh nextcloud 22

### Expected behaviour
The search window should be showed fully

### Actual behaviour
The search modal is going out of screen

### Server configuration

**Operating system:** CentOS 7

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.4

**Nextcloud version:** 22.1.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install 

**Where did you install Nextcloud from:**
Official Nextcloud website

### Client configuration
**Browser:**  Safari and Brave

**Operating system:**
MAC OS Big SUR

alt text

### PR DESCRIPTION
**Pull request by CarlSchwan**
Fix #28584
Close https://github.com/nextcloud/server/pull/28585

New:

image
image

Before:

image
image

Signed-off-by: Carl Schwan <carl@carlschwan.eu>

### CODE REVIEW

**Comment by szaimen** [comment]
@CarlSchwan Can you please show screenshot of this when the notifications app is enabled?
I tried to fix this too in https://github.com/nextcloud/server/pull/28585 btw ;)

**Comment by 488849** [comment]
Thank you

**Comment by CarlSchwan** [comment]
> @CarlSchwan Can you please show screenshot of this when the notifications app is enabled?
> I tried to fix this too in #28585 btw ;)

I didn't know you were already working on it :( 

I figured a hacky way to make it work: using a CSS detection that the notifications element is not empty we can push the carret a bit more to the left.

Here is a screenshot with the notification stuff enabled

image

**Review by 488849 — APPROVED** [review]
That you

**Comment by 488849** [comment]
Thank you

**Comment by 488849** [comment]
Thank u

File: core/src/components/HeaderMenu.vue [hunk 1]
```diff
@@ -163,6 +163,12 @@ export default {
 </script>
 
 <style lang="scss" scoped>
+.notifications:not(:empty) ~ #unified-search {
+	order: -1;
+	.header-menu__carret {
+		right: 175px;
```
Comment (szaimen) [inline core/src/components/HeaderMenu.vue:169]: Are you sure thst this will work?
I think it will be overwritten by the value that you've defined beloe as css is cascading ;)
So it should be moved to the bottom of the file, imho.

**Review by szaimen — APPROVED** [review]
Fine by me unless anyone finds a better way (less hacky) e.g. like suggested here:
https://github.com/nextcloud/server/pull/28585#issuecomment-905369520

**Review by 488849 — APPROVED** [review]

**Review by 488849 — APPROVED** [review]

**Comment by 488849** [comment]
That

File: core/src/components/HeaderMenu.vue (hunk 1 above)
Comment (CarlSchwan) [reply core/src/components/HeaderMenu.vue:169]: It works. Css is cascading but since the rule includes an id and is more specifics it is stronger :D

**Review by 488849 — APPROVED** [review]

File: core/templates/layout.user.php [hunk 2]
```diff
@@ -117,8 +117,8 @@
 			</div>
 
 			<div class="header-right">
-				<div id="unified-search"></div>
 				<div id="notifications"></div>
+				<div id="unified-search"></div>
```
Comment (szaimen) [inline core/templates/layout.user.php:121]: What is the idea here?

Comment (CarlSchwan) [reply core/templates/layout.user.php:121]: The CSS tilde operator only works on the next HTML neighbors, so this is why I switched the elements in the HTML. But I also added an `order: -1` rule so that the search is in the same position as before.

File: core/src/components/HeaderMenu.vue (hunk 1 above)
Comment (szaimen) [reply core/src/components/HeaderMenu.vue:169]: Okay

File: core/templates/layout.user.php (hunk 2 above)
Comment (szaimen) [reply core/templates/layout.user.php:121]: Okay

**Comment by kesselb** [comment]
Hey @488849, thank you for reviewing this pull request. Approving once is enough. We take care of the rest :crossed_fingers:

**Review by Pytal — APPROVED** [review]
Just slightly hacky 😂

**Comment by szaimen** [comment]
Why are there suddenly conflicts after compiling? The compiled files didn't change in master since creating this branch, afaik.
Cc @skjnldsv

**Comment by CarlSchwan** [comment]
> Why are there suddenly conflicts after compiling? The compiled files didn't change in master since creating this branch, afaik.
> 
> Could maybe this be the reason?
> 
> https://github.com/nextcloud/server/blob/4411822b0ef64eb0d7a48a30fc1be82070887b3f/.github/workflows/command-compile.yml#L79
> 
> Cc @skjnldsv

I just rebased and let the compile bot generate the assets again, let see...

**Comment by szaimen** [comment]
> I just rebased and let the compile bot generate the assets again, let see...

Seems to work know but still strange...

**Comment by CarlSchwan** [comment]
ci seems stuck but also unrelated to this PR:

```
[1630425618.218][SEVERE]: bind() failed: Cannot assign requested address (99)
ChromeDriver was started successfully.
```

**Comment by 488849** [comment]
👍

**Comment by 488849** [comment]
👍

File: core/src/components/HeaderMenu.vue (hunk 1 above)
Comment (skjnldsv) [reply core/src/components/HeaderMenu.vue:169]: :judge: hum, this is not a great pieced of maintainable code :see_no_evil: 
https://github.com/nextcloud/server/pull/32702#issuecomment-1144718492
