### PR TITLE
fix(theming): display error messages on image upload and delete previous image only after validation

### LINKED ISSUE #57669: [Bug]: Missing error handling for invalid theming image upload
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Try to upload a svg+xml as favicon

Image

### Steps to reproduce

1. Open admin theming
2. Try to upload an unsupported image type

### Expected behavior

A toast or any kind of feedback

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by cristianscheid**
* Resolves: #57669

## Summary
Display error feedback to users when image upload fails in the theming admin section.

## Changes
- Add error handling on frontend to show server messages for 422 errors and generic messages for other status codes
- Validate new image before deleting the previous one to preserve valid images when upload fails

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)
- [x] [Labels added](https://github.com/nextcloud/server/labels) where applicable (ex: bug/enhancement, `3. to review`, feature component)
- [ ] [Milestone added](https://github.com/nextcloud/server/milestones) for target branch/version (ex: 32.x for `stable32`)

### CODE REVIEW

File: apps/theming/src/components/admin/FileInputField.vue [hunk 1]
```diff
@@ -76,8 +76,17 @@ async function onChange() {
 		})
 		mime.value = file.type
 		emit('updated')
+	} catch (error: any) {
+		if (error?.response?.status === 422) {
```
Comment (susnux) [inline apps/theming/src/components/admin/FileInputField.vue]:
```suggestion
	} catch (error) {
		if (isAxiosError(error) && error.response?.status === 422) {
```

Comment (susnux) [reply apps/theming/src/components/admin/FileInputField.vue]: (fixes the linter error, you just need to also import `isAxiosError` from `@nextcloud/axios`)

**Review by susnux — APPROVED** [review]

**Review by szaimen — APPROVED** [review]
🐘

**Review by provokateurin — APPROVED** [review]

**Comment by cristianscheid** [comment]
> The backport to `stable31` failed. Please do this backport manually.

Since v31 is no longer among the [currently supported versions](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule/), I will not proceed with this backport request.
