### PR TITLE
fix: iMip reply from outlook.com does not contain organizer property

### LINKED ISSUE #53949: [Bug]: iMip reply from outlook.com does not contain organizer property
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

An iMip reply from outlook.com (prod id: Microsoft Exchange Server 2010) does not contain an organizer property. 

Our understanding of the RFC, https://datatracker.ietf.org/doc/html/rfc5546#section-3.2.3, is that the organizer property should be included/copied from the original event. 

We currently enforce at https://github.com/nextcloud/server/blob/8210e128b9183507f4f2328e62245cc64a448335/lib/private/Calendar/Manager.php#L362-L365 and https://github.com/nextcloud/server/blob/8210e128b9183507f4f2328e62245cc64a448335/apps/dav/lib/CalDAV/CalendarImpl.php#L232-L234 and thus iMIP replies from outlook.com are not processed pr

### Steps to reproduce

1. Have mail app enabled (to forward incoming iMip messages from mail to server)
2. Create a event in calendar and invitate a outlook.com user
3. As outlook.com user: accept the invitation
4. See the calendar event is updated and the state in oc_mail_messages is imip_message = true, imip_processed = false, imip_error = true

### Expected behavior

The invitation should be processed

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by SebastianKrupinski**
* Resolves: #53949

## Summary
- Fix Microsoft exchange 2010 reply issue

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by SebastianKrupinski** [comment]
@kesselb 

This is the issue we talked about at Team week. Missing organizer property in MS replies.

This is the best solution I could think of, let me know if you think there is a better way?

**Comment by SebastianKrupinski** [comment]
Tests missing, will write them when once the final solution is agreed on

**Comment by SebastianKrupinski** [comment]
@kesselb The changes we talked about

File: lib/private/Calendar/Manager.php [hunk 1]
```diff
@@ -261,8 +261,13 @@ public function handleIMip(
 		}
 
 		if (!isset($vEvent->ORGANIZER)) {
-			$this->logger->warning('iMip message event dose not contains an organizer');
-			return false;
+			// quirks mode: for Microsoft Exchange Servers use recipient as organizer if no organizer is set
+			if (isset($options['recipient']) && !empty($options['recipient'])) {
```
Comment (kesselb) [inline lib/private/Calendar/Manager.php]:
```suggestion
			if (isset($options['recipient']) && $options['recipient'] !== '') {
```

File: lib/public/Calendar/IManager.php [hunk 2]
```diff
@@ -143,7 +143,7 @@ public function newQuery(string $principalUri) : ICalendarQuery;
 	/**
 	 * Handles a iMip message
 	 *
-	 * @param array{absent?: "create"} $options
+	 * @param array{absent?: "create"|"ignore", recipient?: string} $options
```
Comment (kesselb) [inline lib/public/Calendar/IManager.php]: "ignore" has currently no effect?

**Review by kesselb — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

File: lib/private/Calendar/Manager.php (hunk 1 above)
Comment (SebastianKrupinski) [reply lib/private/Calendar/Manager.php]: Sure

File: lib/public/Calendar/IManager.php (hunk 2 above)
Comment (SebastianKrupinski) [reply lib/public/Calendar/IManager.php]: That was my ocd saying we have a create, there should be an ignore also
