### PR TITLE
Always catch OCP versions of authentication exceptions

### LINKED ISSUE #42394: [Bug]:  NextCloud 28 seems to be handling the Oauth authentication wrongly.
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The token renewal is working properly with NextCloud version 27 and OpenProject (multiple versions including 13.0,13.1) etc.  With NC 28, the OAuth token refresh is not working properly. Even when the token is expired the server return http response code 200 rather than 401. Behavior was proper with NC 27. 

### Steps to reproduce

NC 28 (when logged into OpenProject 13.1 for which session was expired) (NC OP Integration app version - 2.5.1)

1xx.5x.2xx.1xx - - [20/Dec/2023:08:10:56 +0530] "POST /ocs/v1.php/apps/integration_openproject/filesinfo HTTP/1.1" 200 174 "-" "Ruby"

NC 27 (when logged into OpenProject 13.1 for which session was expired) (NC OP Integration app version - 2.4.6/2.5.1)

1xx.5x.2xx.1xx - - [20/Dec/2023:09:28:57 +0530] "POST /ocs/v1.php/apps/integration_openproject/filesinfo HTTP/1.1" 401 140 "-" "Ruby"
1xx.5x.2xx.1xx - - [20/Dec/2023:09:28:57 +0530] "POST /index.php/apps/oauth2/api/v1/token HTTP/1.1" 200 269 "-" "Rack::OAuth2 (2.2.0)"
1xx.5x.2xx.1xx - - [20/Dec/2023:09:28:58 +0530] "POST /ocs/v1.php/apps/integration_openproject/filesinfo HTTP/1.1" 200 251 "-" "Ruby"
1xx.5x.2xx.1xx - - [20/Dec/2023:09:29:01 +0530] "GET /ocs/v1.php/cloud/user HTTP/1.1" 200 519 "-" "Ruby"

### Expected behavior

When the Oauth Token is expired the API response should give 401 error code. 

### Installation method

Other Community project

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by come-nc**
* Resolves: #42394

## Summary

Always catch OCP versions of authentication exceptions.
And always throw OC versions for BC.

Alternative to https://github.com/nextcloud/server/pull/42577 and https://github.com/nextcloud/server/pull/42579 which simply fix internal uses instead of trying to fix back OC Exceptions inheritance.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/settings/lib/Controller/AuthSettingsController.php [hunk 1]
```diff
@@ -292,7 +293,8 @@
 			$token = $e->getToken();
 		}
 		if ($token->getUID() !== $this->uid) {
-			throw new InvalidTokenException('This token does not belong to you!');
+			/* We have to throw the OC version so both OC and OCP catches catch it */
+			throw new OcInvalidTokenException('This token does not belong to you!');
```
[the remark this answers is not in the document]
Comment (come-nc) [reply apps/settings/lib/Controller/AuthSettingsController.php:297]: Needed the workflow to run first is all, it’s marked fixed now.

File: lib/private/Authentication/Token/PublicKeyTokenProvider.php [hunk 2]
```diff
@@ -37,6 +37,7 @@
 use OCP\AppFramework\Db\DoesNotExistException;
 use OCP\AppFramework\Db\TTransactional;
 use OCP\AppFramework\Utility\ITimeFactory;
+use OCP\Authentication\Token\IToken;
```
Comment (nickvergessen) [inline lib/private/Authentication/Token/PublicKeyTokenProvider.php:40]: IIRC there was a time when this (Importing a class/interface that exists in the current namespace already) was not allowed/did not work. Was it a PHP version restriction?

**Review by nickvergessen — COMMENTED** [review]
Seems okay otherwise

**Review by ChristophWurst — APPROVED** [review]
Looks good and preferable over the alternatives

File: lib/private/Authentication/Token/PublicKeyTokenProvider.php (hunk 2 above)
Comment (come-nc) [reply lib/private/Authentication/Token/PublicKeyTokenProvider.php]: Ok, now importing OCP version under another name to avoid the clash

**Review by nickvergessen — APPROVED** [review]
