### PR TITLE
fix: make sure default contact exists by default

### LINKED ISSUE #53894: dav: default contact access polutes debug logs
_Originally posted by @come-nc in https://github.com/nextcloud/server/issues/53568#issuecomment-3056432070_

> The logs of CI for integration are polluted with the following.
> Most likely the default contact is accessed before being created or something like that.
```json
{
  "Exception": "OCP\\Files\\NotFoundException",
  "Message": "/appdata_oc2crh70w5hw/dav/defaultContact",
  "Code": 0,
  "Trace": [
    {
      "file": "/home/runner/actions-runner/_work/server/server/lib/private/Files/Node/LazyFolder.php",
      "line": 138,
      "function": "get",
      "class": "OC\\Files\\Node\\Root",
      "type": "->",
      "args": [
        "/appdata_oc2crh70w5hw/dav/defaultContact"
      ]
    },
    {
      "file": "/home/runner/actions-runner/_work/server/server/lib/private/Files/AppData/AppData.php",
      "line": 114,
      "function": "get",
      "class": "OC\\Files\\Node\\LazyFolder",
      "type": "->",
      "args": [
        "appdata_oc2crh70w5hw/dav/defaultContact"
      ]
    },
    {
      "file": "/home/runner/actions-runner/_work/server/server/apps/dav/lib/Service/ExampleContactService.php",
      "line": 93,
      "function": "getFolder",
      "class": "OC\\Files\\AppData\\AppData",
      "type": "->",
      "args": [
        "defaultContact"
      ]
    },
    {
      "file": "/home/runner/actions-runner/_work/server/server/apps/dav/lib/Listener/UserEventsListener.php",
      "line": 183,
      "function": "createDefaultContact",
      "class": "OCA\\DAV\\Service\\ExampleContactService",
      "type": "->",
      "args": [
        "*** sensitive parameters replaced ***"
      ]
    },
    {
      "file": "/home/runner/actions-runner/_work/server/server/apps/dav/lib/Listener/UserEventsListener.php",
      "line": 77,
      "function": "firstLogin",
      "class": "OCA\\DAV\\Listener\\UserEventsListener",
      "type": "->",
      "args": [
        "*** sensitive parameters replaced ***"
      ]
    },
    {
      "file": "/home/runner/actions-runner/_work/server/server/lib/private/EventDispatcher/ServiceEventListener.php",
      "line": 57,
      "function": "handle",
      "class": "OCA\\DAV\\Listener\\UserEventsListener",
      "type": "->",
      "args": [
        {
          "__class__": "OCP\\User\\Events\\UserFirstTimeLoggedInEvent"
        }
      ]
    },
    {
      "file": "/home/runner/actions-runner/_work/server/server/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
      "line": 220,
      "function": "__invoke",
      "class": "OC\\EventDispatcher\\ServiceEventListener",
      "type": "->",
      "args": [
        {
          "__class__": "OCP\\User\\Events\\UserFirstTimeLoggedInEvent"
        },
        "OCP\\User\\Events\\UserFirstTimeLoggedInEvent",
        {
          "__class__": "Symfony\\Component\\EventDispatcher\\EventDispatcher"
        }
      ]
    },
    {
      "file": "/home/runner/actions-runner/_work/server/server/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
      "line": 56,
      "function": "callListeners",
      "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
      "type": "->",
      "args": [
        [
          {
            "__class__": "Closure"
          }
        ],
        "OCP\\User\\Events\\UserFirstTimeLoggedInEvent",
        {
          "__class__": "OCP\\User\\Events\\UserFirstTimeLoggedInEvent"
        }
      ]
    },
    {
      "file": "/home/runner/actions-runner/_work/server/server/lib/private/EventDispatcher/EventDispatcher.php",
      "line": 67,
      "function": "dispatch",
      "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
      "type": "->",
      "args": [
        {
          "__class__": "OCP\\User\\Events\\UserFirstTimeLoggedInEvent"
        },
        "OCP\\User\\Events\\UserFirstTimeLoggedInEvent"
      ]
    },
    {
      "file": "/home/runner/actions-runner/_work/server/server/lib/private/EventDispatcher/EventDispatcher.php",
      "line": 79,
      "function": "dispatch",
      "class": "OC\\EventDispatcher\\EventDispatcher",
      "type": "->",
      "args": [
        "OCP\\User\\Events\\UserFirstTimeLoggedInEvent",
        {
          "__class__": "OCP\\User\\Events\\UserFirstTimeLoggedInEvent"
        }
      ]
    },
    {
      "file": "/home/runner/actions-runner/_work/server/server/lib/private/User/Session.php",
      "line": 529,
      "function": "dispatchTyped",
      "class": "OC\\EventDispatcher\\EventDispatcher",
      "type": "->",
      "args": [
        {
          "__class__": "OCP\\User\\Events\\UserFirstTimeLoggedInEvent"
        }
      ]
    },
    {
      "file": "/home/runner/actions-runner/_work/server/server/lib/private/User/Session.php",
      "line": 358,
      "function": "prepareUserLogin",
      "class": "OC\\User\\Session",
      "type": "->",
      "args": [
        true,
        "*** sensitive parameters replaced ***"
      ]
    },
    {
      "file": "/home/runner/actions-runner/_work/server/server/lib/private/User/Session.php",
      "line": 586,
      "function": "completeLogin",
      "class": "OC\\User\\Session",
      "type": "->",
      "args": [
        "*** sensitive parameters replaced ***"
      ]
    },
    {
      "file": "/home/runner/actions-runner/_work/server/server/lib/private/User/Session.php",
      "line": 308,
      "function": "loginWithPassword",
      "class": "OC\\User\\Session",
      "type": "->",
      "args": [
        "*** sensitive parameters replaced ***"
      ]
    },
    {
      "file": "/home/runner/actions-runner/_work/server/server/lib/private/User/Session.php",
      "line": 406,
      "function": "login",
      "class": "OC\\User\\Session",
      "type": "->",
      "args": [
        "*** sensitive parameters replaced ***"
      ]
    },
    {
      "file": "/home/runner/actions-runner/_work/server/server/lib/private/User/Session.php",
      "line": 545,
      "function": "logClientIn",
      "class": "OC\\User\\Session",
      "type": "->",
      "args": [
        "*** sensitive parameters replaced ***"
      ]
    },
    {
      "file": "/home/runner/actions-runner/_work/server/server/lib/base.php",
      "line": 1125,
      "function": "tryBasicAuthLogin",
      "class": "OC\\User\\Session",
      "type": "->",
      "args": [
        "*** sensitive parameters replaced ***",
        "*** sensitive parameters replaced ***"
      ]
    },
    {
      "file": "/home/runner/actions-runner/_work/server/server/ocs/v1.php",
      "line": 58,
      "function": "handleLogin",
      "class": "OC",
      "type": "::",
      "args": [
        "*** sensitive parameters replaced ***"
      ]
    }
  ],
  "File": "/home/runner/actions-runner/_work/server/server/lib/private/Files/Node/Root.php",
  "Line": 182,
  "message": "Couldn't get default contact file",
  "exception": {},
  "CustomMessage": "Couldn't get default contact file"
}
```

### PR DESCRIPTION
**Pull request by hamza221**
* Resolves: #53894

## Summary

Create default contact file when the first example contact is to be created.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by st3iny — APPROVED** [review]
Seems to fix the problem.

**Review by kesselb — APPROVED** [review]

**Comment by skjnldsv** [comment]
Related 
`ArgumentCountError: Too few arguments to function OC\Share20\DefaultShareProvider::__construct(), 11 passed in /home/runner/actions-runner/_work/server/server/lib/private/Share20/ProviderFactory.php on line 90 and exactly 12 expected in /home/runner/actions-runner/_work/server/server/lib/private/Share20/DefaultShareProvider.php:51
`

**Comment by skjnldsv** [comment]
Related failures

```
--- Failed scenarios:
    /home/runner/actions-runner/_work/server/server/build/integration/collaboration_features/autocomplete.feature:44
    /home/runner/actions-runner/_work/server/server/build/integration/collaboration_features/autocomplete.feature:65

```

File: build/integration/features/bootstrap/CollaborationContext.php [hunk 1]
```diff
@@ -63,6 +63,23 @@ private function getAutocompleteWithType(int $type, string $search, TableNode $f
 		}, $suggestions, $formData->getHash()));
 	}
 
+	/**
+	 * @Given /^delete example content$/
+	 */
+	public function deleteExampleContact(): void {
+		$this->usingNewDavPath();
+		try {
+			$destination = '/users/admin/contacts/default.vcf';
```
Comment (st3iny) [inline build/integration/features/bootstrap/CollaborationContext.php]: The `default.vcf` file is inside app data, right? I don't get how the path is translated from `/users/admin` to app data.

But I'm fine if it works.

Comment (hamza221) [reply build/integration/features/bootstrap/CollaborationContext.php]: should be default.vcf no ? or am i tripping https://github.com/nextcloud/server/blob/fix/default-contact/apps/dav/lib/Service/ExampleContactService.php#L146

Comment (st3iny) [reply build/integration/features/bootstrap/CollaborationContext.php]: Yeah but isn't it something like `data/appdata_*/contacts/default.vcf`?

Comment (st3iny) [reply build/integration/features/bootstrap/CollaborationContext.php]: Or am I really confused?

Comment (kesselb) [reply build/integration/features/bootstrap/CollaborationContext.php]: makeDavRequest sends an http request

**Comment by st3iny** [comment]
CI will probably still fail until https://github.com/nextcloud/server/pull/54608.

**Comment by st3iny** [comment]
@hamza221 I'm starting to believe that the integration test failure is somehow related.

**Comment by hamza221** [comment]
> @hamza221 I'm starting to believe that the integration test failure is somehow related.

I'll try to get it in before tommorow's rc
