### PR TITLE
fix(user_ldap): Improve case where selected config is undefined

### LINKED ISSUE #56070: Delete configuration in LDAP does not reset form fields (upcoming 33 only)
On the refurbished LDAP wizard, when deleting a configuration, then the form fields are not being reset. In the database, a default/empty configuration is stored, which is fine.

Screenshot after pressing that button; on branch `fix/ldap-get-rid-of-ajax`.

Image

@artonge

### PR DESCRIPTION
**Pull request by artonge**
Multiple fixes to improve deleting a config and configuring a new one:

- Improve case where selected config is undefined
- Disable some buttons when clicking them would lead to an issue
- Properly update local variable for username and password in server settings
- Properly use fall back message in case of empty response
- Properly handle new config creation in settings

Fix https://github.com/nextcloud/server/issues/56070

### CODE REVIEW

**Comment by artonge** [comment]
EDIT: Found the issue, fixed in https://github.com/nextcloud/server/pull/56726/commits/faaf85018549687606f3320dae0950e623c05d88

~~@come-nc one weird irritating thing: when I create a new config, it is disabled by default, which is not bad. But when I test the config, while still disabled, the binding fails here: https://github.com/nextcloud/server/blob/ccabed89dc34ca0db325b9c9eb9da88d0468d8c9/apps/user_ldap/lib/Controller/ConfigAPIController.php#L266-L271~~

~~However, if I activate the config, it works. If I disable the config again, it works too. I tried debugging, but couldn't find any differences in the tested config before or after activating it.~~

~~Any idea?~~

File: apps/user_ldap/src/components/SettingsTabs/ServerTab.vue [hunk 1]
```diff
@@ -120,6 +120,18 @@ const needsToSaveCredentials = computed(() => {
 	return ldapConfigProxy.value.ldapAgentName !== localLdapAgentName.value || ldapConfigProxy.value.ldapAgentPassword !== localLdapAgentPassword.value
 })
 
+watch(
+	() => ldapConfigProxy.value,
```
Comment (susnux) [inline apps/user_ldap/src/components/SettingsTabs/ServerTab.vue]: No need for a getter here, you can just pass refs or computed to watch and directly let watch trigger on the ref instead of first call the getter


```suggestion
	ldapConfigProxy,
```

**Review by susnux — APPROVED** [review]
otherwise it looks good

File: apps/user_ldap/src/store/configs.ts [hunk 2]
```diff
@@ -80,11 +80,21 @@ export const useLDAPConfigsStore = defineStore('ldap-configs', () => {
...
+					delete ldapConfigs.value[configId]
+				}
+			} else {
+				// Select the first config that is not the deleted one
+				selectedConfigId.value = Object.keys(ldapConfigs.value).filter((_configId) => configId !== _configId)[0]
+				delete ldapConfigs.value[configId]
+			}
 		}
-
-		selectedConfigId.value = Object.keys(ldapConfigs.value)[0] ?? await create()
```
Comment (come-nc) [inline apps/user_ldap/src/store/configs.ts:87]: The original code is more readable, for what reason was it not working as expected?

Comment (artonge) [reply apps/user_ldap/src/store/configs.ts:87]: Because between the delete and the creation, we end up without configurations locally, which breaks the state. We could handle the state where there are not configuration locally, but this would imply some flickering.

**Review by come-nc — APPROVED** [review]
