### PR TITLE
Check if TTY is invalid in encryption:encrypt-all and encryption:decrypt-all

### LINKED ISSUE #9894: "occ encryption:decrypt-all" fails with obscure error message when not connected to an interactive terminal
### Steps to reproduce
1. Run `occ encryption:decrypt-all` without an interactive terminal, ie. using docker (`docker exec --user www-data nextcloud php occ encryption:decrypt-all xx`)

### Expected behaviour
Should tell me that it needs an interactive terminal, not just say "aborted".

### Actual behaviour
Outputs: 

    Disable server side encryption... done.
    
    
    You are about to start to decrypt all files stored in xx's account.
    It will depend on the encryption module and your setup if this is possible.
    Depending on the number and size of your files this can take some time
    Please make sure that no user access his files during this process!
    
    Enable server side encryption... done.
    aborted

In the docker case, it works when providing `-it` to docker (ie. `docker exec -it --user www-data nextcloud php occ encryption:decrypt-all xx`)

### Server configuration

**Operating system**: official docker image (up to date as of 2018-06-18) running on Debian x86_64 9.4

**Database:** MariaDB

**PHP version:** 7.1.18

**Updated from an older Nextcloud/ownCloud or fresh install:** Update

**Where did you install Nextcloud from:** Docker

### PR DESCRIPTION
**Pull request by eugulixes**
Inspired by https://github.com/nextcloud/server/issues/9894.
The commands `occ encryption:decrypt-all` and `occ encryption:encrypt-all` transform into interactive processes since they both use `ConfirmationQuestion`. It's not possible to execute the commands in a container via `docker exec` without the `-i` and `-t` options. However, it becomes not obvious from a user point of view _why_ since the result of both commands in this case is `aborted`. This PR tries to solve the problem.
Fixes #9894.

Signed-off-by: Evgeny Golyshev <eugulixes@gmail.com>

### CODE REVIEW

File: core/Command/Encryption/DecryptAll.php [hunk 1]
```diff
@@ -123,6 +123,16 @@ protected function configure() {
 	}
 
 	protected function execute(InputInterface $input, OutputInterface $output) {
+		if (strtoupper(substr(PHP_OS, 0, 3)) !== 'WIN') {
```
Comment (nickvergessen) [inline core/Command/Encryption/DecryptAll.php]: windows is not supported anyway?

Comment (eugulixes) [reply core/Command/Encryption/DecryptAll.php]: yeah, I suggest we will do nothing if we deal with Windows.

Comment (jospoortvliet) [reply core/Command/Encryption/DecryptAll.php]: I would just remove this - that it breaks on windows is not a surprise, all of Nc breaks... Or should we keep it in @nickvergessen ?

Comment (eugulixes) [reply core/Command/Encryption/DecryptAll.php]: The official documentation [doesn't suggest](https://docs.nextcloud.com/server/13.0.0/admin_manual/installation/system_requirements.html#server) Windows as an option, so it would be fair enough to remove the Windows-related checks.

Comment (jospoortvliet) [reply core/Command/Encryption/DecryptAll.php]: @eugulixes go ahead, I suppose, if this was the only issue @nickvergessen had then it would suffice to get this ready to go.

Comment (eugulixes) [reply core/Command/Encryption/DecryptAll.php]: Done.

**Review by MorrisJobke — APPROVED** [review]
Code looks good 👍  Tested and works

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
Failing unit tests

**Comment by ChristophWurst** [comment]
> Failing unit tests

Yeah, these built-in functions don't react well to phpunit (on CI?). I'd suggest to create a simple wrapper class for this that internally calls the php functions. This way we can mock them in unit tests. @eugulixes do you know how that works? I see this is your first contribution, so please let me know if you need assistance :v:

That class would look something like

```php
namespace OCP\Console;

class Environment {

    public function isInteractive(): bool {
        return posix_isatty(STDOUT);
    }
}
```

Inspiration was taken from https://github.com/sebastianbergmann/environment/blob/32c5cba90f7db47b1c10a777b36eccfd44ef8bd7/src/Console.php#L78, so that might also be an option to integrate. I've found traces of that class in my local dev setup.

**Comment by danielkesselberg** [comment]
https://github.com/nextcloud/3rdparty/blob/461663cd1143c593fc71ee976afeb0f4e628b16b/symfony/console/Input/InputInterface.php#L153

You could use `$input->isInteractive()` like @ChristophWurst suggested

**Comment by ChristophWurst** [comment]
> You could use $input->isInteractive() like @ChristophWurst suggested

Ha! Didn't know it was that simple! Thank you :smile:

**Comment by ChristophWurst** [comment]
> You could use `$input->isInteractive()` like @ChristophWurst suggested

@eugulixes ping :)

**Comment by eugulixes** [comment]
@ ChristophWurst, i'm planning to do it this weekend.

**Comment by ChristophWurst** [comment]
Awesome, thanks!

**Comment by danielkesselberg** [comment]
`$input->isInteractive()` is `false` on ci. 

https://github.com/nextcloud/server/blob/9533f4e5edfded577b67d08f7778a8a1704132f2/tests/Core/Command/Encryption/DecryptAllTest.php#L75

You need to mock `isInteractive`. Take the file above and look for the line and insert the following below:
```
$this->consoleInput->expects($this->any())->method('isInteractive')
    ->willReturn(true);
```

I guess the same applies to https://github.com/nextcloud/server/blob/9533f4e5edfded577b67d08f7778a8a1704132f2/tests/Core/Command/Encryption/EncryptAllTest.php#L80

**Comment by eugulixes** [comment]
@ChristophWurst, @danielkesselberg, all tests passed. Thank you for your help.

**Review by kesselb — APPROVED** [review]
