### PR TITLE
fix(files_reminders): add missing import

### LINKED ISSUE #51943: [Bug]: Could not resolve OCA\FilesReminders\AppInfo\NeedNotificationsApp
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

```
OC\AppFramework\Utility\QueryNotFoundException: Could not resolve OCA\FilesReminders\AppInfo\NeedNotificationsApp! Class "OCA\FilesReminders\AppInfo\NeedNotificationsApp" does not exist
#13 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(113): OC\AppFramework\Utility\SimpleContainer::resolve
#12 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(124): OC\AppFramework\Utility\SimpleContainer::query
#11 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(452): OC\AppFramework\DependencyInjection\DIContainer::queryNoFallback
#10 /var/www/nextcloud/lib/private/ServerContainer.php(137): OC\ServerContainer::query
#9 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(42): OC\AppFramework\Utility\SimpleContainer::get
#8 /var/www/nextcloud/lib/public/Server.php(39): OCP\Server::get
#7 /var/www/nextcloud/lib/private/SetupCheck/SetupCheckManager.php(31): OC\SetupCheck\SetupCheckManager::runAll
#6 /settings/lib/Controller/CheckSetupController.php(147): OCA\Settings\Controller\CheckSetupController::check
#5 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(208): OC\AppFramework\Http\Dispatcher::executeController
#4 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(114): OC\AppFramework\Http\Dispatcher::dispatch
#3 /var/www/nextcloud/lib/private/AppFramework/App.php(161): OC\AppFramework\App::main
#2 /var/www/nextcloud/lib/private/Route/Router.php(303): OC\Route\Router::match
#1 /var/www/nextcloud/lib/base.php(1010): OC::handleRequest
#0 /var/www/nextcloud/index.php(24): null
```

### Steps to reproduce

1. Run 30.?.?
2. Upgrade to 31.0.3 RC1 with the web updater

### Expected behavior

Smooth upgrade

### Nextcloud Server version

31

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by susnux**
- Resolves https://github.com/nextcloud/server/issues/51943
- Regression of https://github.com/nextcloud/server/pull/51760

## Summary

1. Add missing import of setup check in application class
2. Add missing `l10n` constructor parameter.
3. Lint the app using psalm so this does not happen again.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by yemkareems — APPROVED** [review]

**Review by kesselb — DISMISSED** [review]

File: apps/files_reminders/lib/SetupChecks/NeedNotificationsApp.php [hunk 1]
```diff
@@ -10,12 +10,14 @@
 namespace OCA\DAV\SetupChecks;
```
Comment (come-nc) [inline apps/files_reminders/lib/SetupChecks/NeedNotificationsApp.php:10]: Indeed that’s worrying. We have no check for namespace<>path consistency?

File: apps/files_reminders/lib/AppInfo/Application.php [hunk 2]
```diff
@@ -10,6 +10,7 @@
 namespace OCA\FilesReminders\AppInfo;
 
 use OCA\DAV\Events\SabrePluginAddEvent;
+use OCA\DAV\SetupChecks\NeedNotificationsApp;
```
[the remark this answers is not in the document]
Comment (susnux) [reply apps/files_reminders/lib/AppInfo/Application.php]: done. Thank you for spotting it!

File: apps/files_reminders/lib/SetupChecks/NeedNotificationsApp.php (hunk 1 above)
Comment (susnux) [reply apps/files_reminders/lib/SetupChecks/NeedNotificationsApp.php]: can psalm do this?

**Review by artonge — APPROVED** [review]
