### PR TITLE
(occ db:convert-type) Add support for UNIX sockets

### LINKED ISSUE #31998: [Bug]: db:convert-type does not support mysql passwordless unix socket auth
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I am able to configure nextcloud to mariadb via unix socket without a password, nextcloud/docker#1284, however when I use `db:convert-type`, I get a 'Connection refused` error.

### Steps to reproduce

1. have a nextcloud install
2. `occ db:convert-type --all-apps --clear-schema mysql nextcloud localhost:/run/mysqld/mysqld.sock nextcloud`

### Expected behavior

it would work

### Installation method

Other

### Operating system

Other

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.example.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "23.0.3.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "apps_paths": [
            {
                "path": "\/usr\/share\/webapps\/nextcloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "appstore.experimental.enabled": true,
        "loglevel": 0,
        "trashbin_retention_obligation": "auto",
        "htaccess.RewriteBase": "\/",
        "mail_smtpmode": "smtp",
        "overwrite.cli.url": "https:\/\/nextcloud.example.com",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "app_install_overwrite": [
            "calendar",
            "keeweb",
            "impersonate",
            "groupfolders",
            "files_accesscontrol",
            "tasks",
            "twofactor_nextcloud_notification",
            "unsplash",
            "contacts"
        ],
        "mysql.utf8mb4": true,
        "mail_sendmailmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "US"
    }
}
```


### List of activated Apps

```shell
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - admin_audit: 1.13.0
  - calendar: 3.0.6
  - cloud_federation_api: 1.6.0
  - cms_pico: 1.0.18
  - comments: 1.13.0
  - contacts: 4.1.0
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - federatedfilesharing: 1.13.0
  - files: 1.18.0
  - files_markdown: 2.3.5
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - firstrunwizard: 2.12.0
  - impersonate: 1.10.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - tasks: 0.14.4
  - text: 3.4.1
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - twofactor_nextcloud_notification: 3.3.1
  - twofactor_totp: 6.2.0
  - twofactor_u2f: 6.3.0
  - unsplash: 1.2.4
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:
  - circles: 22.1.1
  - encryption
  - federation: 1.8.0
  - files_accesscontrol: 1.13.0
  - files_external
  - files_videoplayer: 1.11.0
  - news: 18.0.0
  - phonetrack: 0.7.0
  - support: 1.5.0
  - user_ldap
```


### Nextcloud Signing status

```shell
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- .htaccess
		- 3rdparty/pimple/pimple/src/Pimple/Container.php
		- 3rdparty/pimple/pimple/src/Pimple/Psr11/ServiceLocator.php
		- 3rdparty/pimple/pimple/src/Pimple/ServiceIterator.php
		- 3rdparty/pimple/pimple/src/Pimple/ServiceProviderInterface.php
		- core/Command/Broadcast/Test.php
		- lib/private/Accounts/Account.php
		- lib/private/Accounts/AccountProperty.php
		- lib/private/Accounts/AccountPropertyCollection.php
		- lib/private/AppFramework/Http/Request.php
		- lib/private/AppFramework/Utility/SimpleContainer.php
		- lib/private/Authentication/Token/DefaultToken.php
		- lib/private/Authentication/Token/PublicKeyToken.php
		- lib/private/Cache/CappedMemoryCache.php
		- lib/private/Contacts/ContactsMenu/Actions/LinkAction.php
		- lib/private/EventDispatcher/GenericEventWrapper.php
		- lib/private/Files/Cache/CacheEntry.php
		- lib/private/Files/FileInfo.php
		- lib/private/FullTextSearch/Model/IndexDocument.php
		- lib/private/FullTextSearch/Model/SearchRequestSimpleQuery.php
		- lib/private/L10N/L10NString.php
		- lib/private/Memcache/Cache.php
		- lib/private/Session/CryptoSessionData.php
		- lib/private/Session/Session.php
		- lib/private/Updater/ChangesCheck.php
		- lib/private/Updater/VersionCheck.php
		- lib/public/AppFramework/Services/InitialStateProvider.php
		- lib/public/Dashboard/Model/WidgetSetting.php
		- lib/public/Dashboard/Model/WidgetSetup.php
		- lib/public/Dashboard/Model/WidgetTemplate.php
		- lib/public/DirectEditing/ATemplate.php
		- lib/public/EventDispatcher/GenericEvent.php
		- lib/public/Files/Template/Template.php
		- lib/public/Files/Template/TemplateFileCreator.php
		- lib/public/LDAP/ILDAPProvider.php
		- lib/versioncheck.php
- encryption
	- INVALID_HASH
		- lib/Command/FixEncryptedVersion.php
- user_status
	- INVALID_HASH
		- lib/Service/JSDataService.php
- theming
	- INVALID_HASH
		- lib/Service/JSDataService.php
- files_external
	- INVALID_HASH
		- lib/Lib/Auth/AuthMechanism.php
		- lib/Lib/Backend/Backend.php
		- lib/Lib/DefinitionParameter.php
		- lib/Lib/StorageConfig.php
- user_ldap
	- INVALID_HASH
		- lib/Access.php
		- lib/Connection.php
		- lib/Group_LDAP.php
		- lib/Group_Proxy.php
		- lib/IGroupLDAP.php
		- lib/ILDAPWrapper.php
		- lib/IUserLDAP.php
		- lib/LDAP.php
		- lib/LDAPProvider.php
		- lib/PagedResults/IAdapter.php
		- lib/PagedResults/TLinkId.php
		- lib/User/Manager.php
		- lib/User/User.php
		- lib/User_LDAP.php
		- lib/User_Proxy.php
		- lib/Wizard.php

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => aab002636038627a549cdc33b749fe7ef74fcbb2a52decf1af0b4c90394d869d982dd7a2d3ce72d1d5114b21aa73cb35ddb6c8b54760ca0e7347e7b26760d6ab
                            [current] => d3c7e9af4479dd40a998cde7fea904c49d8748ef36611e7d11fa0e9a7155f31d59c4b91687c89372c8f939957dea1db6dc02680e691863a1167084baeceff7ce
                        )

                    [3rdparty/pimple/pimple/src/Pimple/Container.php] => Array
                        (
                            [expected] => 28ba0d2837953fe09cf55e32a3092d04a894854cd18b27b59b9f0be60aebb882396337bb2fdce523eaaed85f1a29e7d8601057ecc2a6882f22e3443bb2dc1309
                            [current] => df65f8cbbc243de6981b9b049d27f9d9b6fe8e3c77aa3431be118a2be7e3d43a01647f969d2086be0a4eb4e8c390856ec633b6a2ecd4335b99ac09baf8d44dad
                        )

                    [3rdparty/pimple/pimple/src/Pimple/Psr11/ServiceLocator.php] => Array
                        (
                            [expected] => b553a0c4a9dacaf979676f9c8740c36f1a4a1c434e047f47e30e29573ebf4c832ef9edd14891a2c0e4c62955e466dc9b1be59a385a16371c0003cb1f77300888
                            [current] => 0bd9f27f304e66b961d1931310493813b78ee23d33fc828e526c4af0f50bbe30dc216191ee531850c70661e8e02c1f14c42277fb904bd1518b6d008260301f14
                        )

                    [3rdparty/pimple/pimple/src/Pimple/ServiceIterator.php] => Array
                        (
                            [expected] => 804c340792377695ad675f9b97e9452dff52d94f681b99daf2af47f958bd9f1e901cca76ec400b2d2037a5d922cfbc870f9d541dfa4e08aa66c4bc412af5caec
                            [current] => 0f1d05cf9ece24e25ff0a2e9c5966dfe74d435835c9983c0a00f9f0b749a23acb340525487f4db8478a6710949b64bbfb096d8de2aa35e4bda51f9ba2819481f
                        )

                    [3rdparty/pimple/pimple/src/Pimple/ServiceProviderInterface.php] => Array
                        (
                            [expected] => 92a7fc9024da9de6ce11a68c83f09337bc97d7ccf9804df9708e4196291110d188fd7fe845dbb3b1dd7b9a1159049f35737749ea42af16557a784209cb8047f1
                            [current] => 3b9afacbd7206785e0506d3260fd9cc7485f743ed2d5ac627e403795b59e21aa67808bdbf8e5569bf8690e23533a9ba595cf55a210dbc7dcf69a09a541c11a47
                        )

                    [core/Command/Broadcast/Test.php] => Array
                        (
                            [expected] => b8f9f0a75e60995fa07560cabe012a667c8e1e8fc225972af4ac8007ce07a6170a41a0b3cd119a14f8a54325f9ba2c2294ffc56b6c11c03e2b4765bc836e7593
                            [current] => a63b0f943485743a504d92ee6b6629a0db677dbc0350b78255c1045d8f2df47ed8df129f5aa77dcfabd5f0a095e7c9a0640b85bdf4c866e062afcf3b3899876c
                        )

                    [lib/private/Accounts/Account.php] => Array
                        (
                            [expected] => d570d642519ba1967c099759161476b3d4c619e5049f1f1e620ea6369e075b3a55ef579e731908f77e85b3fc2527916cb4f9140427993dda7a43472301872659
                            [current] => 17d13c428957981bb83cf9f8722296285260c5579e7f2f4ec544c1a680b24a12431082198ab00cb457ebd5caae5da03d8c0d46f1098de34ef56fb566bab2559e
                        )

                    [lib/private/Accounts/AccountProperty.php] => Array
                        (
                            [expected] => d56401bcdb8283ed8f5d4f0abf74dea391989481e19cdd8325f305d29343a6341e05302c2acc28e35e4c4e14e09b764cb4355728f2dcbe71fc6521308a2f5bd7
                            [current] => 2f54a83ce61524b1eef039980ee7aa5cb4364855f1bd560982696e3f52f5bfe5b0e4a3f63d129e6fecb561ba864c904de769f1583ce2ce988114fbe4ef41f955
                        )

                    [lib/private/Accounts/AccountPropertyCollection.php] => Array
                        (
                            [expected] => a75cb6f073cf01b4eb44167107cb5546b4fe638448e010a952052a452f535d4eafc4283e02b4125904444582249bd6e582805ad23e25c7d971d3102823441326
                            [current] => c316590d7a9a832e8cb1f71d415c7646704c2c38553b62874a0792366f4fe6a3a0f34a6f8a79d53df013b0d0f3f503077db5024723df6c85c11efb159f5c7b74
                        )

                    [lib/private/AppFramework/Http/Request.php] => Array
                        (
                            [expected] => c2d27eadfcda5963f338c3a0ea48ab3fdbf70f35b48bba1c4221b669132b7ecaa0f496cc8a0a865ce1f29b116ae8d1a9ba43c3a47a3f4c179dc0fc344ad49f8e
                            [current] => 96bba2a8bbc3eb76efddbc836574cea33b708e5e97f4aa2305ad2833d23a00d487fb8d5054f236e82278e0faf1e3fcd5435161ea4a9c6489ebf5ff7a45e63c9a
                        )

                    [lib/private/AppFramework/Utility/SimpleContainer.php] => Array
                        (
                            [expected] => 5e2725313fa0dcf16f45bae9e0c4fd442a4f525924e8f2dd83be7da4e2e71daac396a79a8d12aad9d93d144c235b5f59d60ec7b015c82ffb4f700fc46ddb8e5b
                            [current] => b9cbca71532f3e2ccaaa1ff837532a1ed0c7e8a747af9129622d528c10a32fcfae056b6a6fb5802e82fd6e8d4a44d714c31b8c14661929a3f6b19fcecc9f4897
                        )

                    [lib/private/Authentication/Token/DefaultToken.php] => Array
                        (
                            [expected] => 79b729a20124e204721e29380b0120fb1a2d0f1bd4cf5bb9f055ce40baccb51d589d4298b69e08eea62627f56ba2da7f602d941a9aab5d6bfe891b36c00c971f
                            [current] => 04141e5bf70fb556992af85586a29f97d500134a095229ef698e828b0745815f3fe912d988d7273e14d953b19df5942524b3c4f658cde254d152ca98168892d9
                        )

                    [lib/private/Authentication/Token/PublicKeyToken.php] => Array
                        (
                            [expected] => 8ac787f70f9906f64c9ec9a82afe7041f238f9d15c6e7e3d7f8e2f3f96ca0d3482d75cf5f841b5d35a3f077ab6d9167e1af98769dd1063cc5239aaa34bba0b72
                            [current] => 40385b67bb8dbc4416a2763c59666e1f3bfe8f4bb47512c17d3fa3d3ae921de4308ed7923083586c9da60f3c0abd2c63c38025170983eb61e489fbc0a0c82940
                        )

                    [lib/private/Cache/CappedMemoryCache.php] => Array
                        (
                            [expected] => d9088d54cf88713a1f219d5573102efb98c68ca07dfc6cb11d06bc18e603f23c20798bd3943b0461461621dcb2fc4b0576250b44150b98ab54d2b9acd6640bc0
                            [current] => 26eb456ab1be69210c198f074f429e7f29839805efd3bc209fadcd6019575726d9d61b43e53ba6b19b6560391a5afff65270c4ac757f903cb4edb31c4b430088
                        )

                    [lib/private/Contacts/ContactsMenu/Actions/LinkAction.php] => Array
                        (
                            [expected] => 6488cf0381395c979fc651cc30c18a69985b27eb731fb687fc8f102b6923f393317e142e2dfad58d74f1a88749648260913273d185b7b36e5acd54f0eba5900f
                            [current] => a0240f17aad9de39dd444ffcd97b1608b920943fee4959f0e545eb093bfad9508b92c38326391da3e64472042778eadf52e12e43b38e547abb256ef73d9a018b
                        )

                    [lib/private/EventDispatcher/GenericEventWrapper.php] => Array
                        (
                            [expected] => 32859d2986e8a54afa374c85c77734a10bb60e569449f926ae5764c29449f1504b7b957dd2d34f4bc41c6a9226319d1dbdd58cb27aaeaecdbe2f2d093cc5072b
                            [current] => 4920a7ea19a7c8a815419f9a3975266389ec5d0f1fdb1bedf1b594da6ec8d3248990d829d404b8311a44869af319ad5b5769d8e90da0e24adda3b28280b878e3
                        )

                    [lib/private/Files/Cache/CacheEntry.php] => Array
                        (
                            [expected] => fabb918b27cb7847e5cbc0f31d861ae4f2ec54fdc5a631b8c5be9e84fe14fab43c3d357fc9958145334dceb8c99e7e18f6bffcd5ab69df83b588b891653b1e84
                            [current] => 9d66f4601c110a13896ba7ef09aa6ddbb4a990ed1ab82ee2a9cfae9435102b7b026b62befb150f613590072c772994c40ae52ededfe1a71ba9a6272ff1c0940e
                        )

                    [lib/private/Files/FileInfo.php] => Array
                        (
                            [expected] => 5aee5eed2cc1f72662f93b56fdf2c4fc15ec99c0efcbb8a5db43e989aa6a96746463dd9f798a768a8b48b8f921af134a2d8260367a0c5a676aa13c807bb6ac72
                            [current] => bbb57015eebcada0a72979879d619aaa790fec3a6c0139eb58c513eddddce9f32fbced39040db1ae7d255294a8153314b3cbb4b869bf3eaa0c57569abd3b6dc4
                        )

                    [lib/private/FullTextSearch/Model/IndexDocument.php] => Array
                        (
                            [expected] => 94813d92aa47ac56df41b7938cd093b81f4dff4b56c36af8c953a612dd5f28a87bc78718b6274bf9f879ae35411d775c4e8f66602c73746ca7adbdc2c310e67a
                            [current] => a5872a704c1fc06611ba1ad8fbfc6a688ca3280a3fddaae6b30e9d8066adcb77417632965938de799086ea6ae79fe988c39856a76225c861dfd2d7ea0a3292bb
                        )

                    [lib/private/FullTextSearch/Model/SearchRequestSimpleQuery.php] => Array
                        (
                            [expected] => 0fc07ff2ec577350c3ecb854239ca79344394d58fde14e2a828b70f044725ad9a341c9b5e6ddc92d522e0d14cd1e5b0f6c1ce3edf1552bcf9ecddc71eb965cdc
                            [current] => e103128bac41a0409a7e417d4b4f0d9cd9c32d139ae8d898696faae613ed9c0580c160fd77bd7d8019c0d72fa66504e11eb917a0d3758fa02363dc00a4ed90dc
                        )

                    [lib/private/L10N/L10NString.php] => Array
                        (
                            [expected] => 75468efd1672e56b62bb31ec17256d2f28a5d21a82b5aeafadb61df7a05a8784006d395ef06454cd3516c618c38d5b7b533a1d5353d94851d77ffb8f95558bc0
                            [current] => ec4ddf6250fc09e079016a77f0f77238ab6b309a1247207b605fcba4cb49dd579a3c39aaf2903baa2697424f36ab01530de12c72da4daa6300914c08167161b3
                        )

                    [lib/private/Memcache/Cache.php] => Array
                        (
                            [expected] => 9da860d124301e180045e2b42f697ab96cd80b914e6eb6b3164c283560206847c51c42e50937d3204b1996c542cb02921317286eba6e203a55311a63fcef9625
                            [current] => a829164cc0ac4a16a7dbd150c731ff513fff1f5983e180bd7527141370f00a672728f02614d8af31cb4bced447cd71448e7350aec809fb3e493f8643179b8f2a
                        )

                    [lib/private/Session/CryptoSessionData.php] => Array
                        (
                            [expected] => a5dcb69788be4d1f0b977662e17cd601ba26f6b4f0d25a97e77923f452ad1d68d8754bc13e0a4e1dff9c4877df93e63f6d13da1a9685286651fb91a232acf6bc
                            [current] => a9c919102fe7a65a8ba6cd5fc83b914d1329a3f2300b387a1a81d884fd352b2d8b7b6797cddd7021cafde135d000824febcbf324277a247fc90d4b9fbb35a995
                        )

                    [lib/private/Session/Session.php] => Array
                        (
                            [expected] => 00836237e59a2673c8e2fa54da771bde036972fab311098ea4bf711e4ddf68bdc305e42dc1bc5180c888938f971eb50795a114cef4fc9bfef344272475053268
                            [current] => 6e9f8e77964bb8f015aa3108c1ff1058a32bba0d99b78b6e8780525aa51caa6df3c5dea3c857e2160cc31649ff6adbf81745ff2254711c87ed98a03a7a2ce9fc
                        )

                    [lib/private/Updater/ChangesCheck.php] => Array
                        (
                            [expected] => 40c168fb63a0a238748f93c90f64ae0c94fedd27c79de3deda1c9c364730f2003a60cb29a6ee539f0b37ad7a2a5b11d0c696cb4b5ace00cb4b44816c72e5e334
                            [current] => 11212e81101199357fb8ad2ae80738d89ad91709219a4aacbd6e725128c10be21d134c3602389bee190e2aec0b1cd3a00bdf8719ef5edab0260858d78c83f8a0
                        )

                    [lib/private/Updater/VersionCheck.php] => Array
                        (
                            [expected] => 2ba43f32774893c1f90c780fc3a7a0d758b5c85d3d277129a429c092d2a9723a9a566fb6a5ef13436257c21971d957992973582ea40e82ee4b9845b42ec55916
                            [current] => 379be0552fcf099c12f7e75bc9a9bf47bd5c0f6e838e0a43a8c78976f1698676147dbd13662d2902171c701c80dad22e2039d9ef579c957a1dea0d4e355d5719
                        )

                    [lib/public/AppFramework/Services/InitialStateProvider.php] => Array
                        (
                            [expected] => 6900012ae1dc883540a8ea0e5b77b3854a883c145efb8bee3f144429e64448a840598d49ba47917bd0d4fc8e143922827d7ceaa08533ecf5456e8d261a7e2acb
                            [current] => e137749286a0b8d5afa45735f9a28483e9859d6f916b16f4d48ae196368fdf02f9630bd1132a86656c4bf4e1a051206ddd90fc5a72d6a34c97c2f15691767a71
                        )

                    [lib/public/Dashboard/Model/WidgetSetting.php] => Array
                        (
                            [expected] => f657d3a13ec1505d0e1d6c320f33c836b94e160bbd1e0cc4caf78db4c4e386479ec3f715586edbb5701c444f32c8ac6e9f170b95f548f855de1f5d5ea82c4e5f
                            [current] => f2cd640835198756da252abef2e84dd944dec333ec7e5b08bcc0ff7b09ff3c645733725e1a0233aa5dcc21d9e6f54394ae45adebf690d853bd87581e93f3d3a3
                        )

                    [lib/public/Dashboard/Model/WidgetSetup.php] => Array
                        (
                            [expected] => 3a885fe1759ff70772079562c3c8065c18f1f6e4e6e674242a2765e00c56e66a22e6843c00b983b18d84756cf55db496df9c24e0f7e314f8918b1bd180b75cd3
                            [current] => c6d29abaf14d5a1f379bab2dbabc29421a6e31cabae4e30e15be482dcceb118d2bcfcc33c4d11358126331078438367597faf5eaaeda883b9273f00ec09fc16e
                        )

                    [lib/public/Dashboard/Model/WidgetTemplate.php] => Array
                        (
                            [expected] => f31bb6136c56fcb87a1926a43b9c88a6107c044235259cf3a5bb75e7a9a889e5788dba378920fa7d8b7492842d929dcca1e6e2b2a84c19b5475e8305a9424fe3
                            [current] => 6a9ed4f6a206481e9ca2e7edeb7bbce582342a0f6932965b83ef79c8b030aedd81a67c0b1e6f94f55f46268975c894f649a25c449fc338c7058d9e2820748278
                        )

                    [lib/public/DirectEditing/ATemplate.php] => Array
                        (
                            [expected] => bf5707c3041c09eb585a57ff2bdee8f05a114bf409a5b9733eccc727204d5117a61b618be7eb48d28b7811ae8f54032697a5f4fef592b19e954d822ac0f054cf
                            [current] => d269f03d3833b531aca6f3df118dc441c9fd9a5b675ee50593e8198506c1d98d0771fa29422c27205f0e2d2dec04656602295aa7da2786fee634924dac82e345
                        )

                    [lib/public/EventDispatcher/GenericEvent.php] => Array
                        (
                            [expected] => 57db91204f78aa5921530c58ac93ac94da04bf681b1fb0b969468e89739d86fdf114001d2824ab5e8447caea0b3412c06a0c6b642c26d8635db74781ae074d85
                            [current] => d8fa274841c73cd9fdb81046df5be7fef7fd4cdea4b372f1328092249a58fbd304bb588804aaab1f4255a542991befb9c9bd8bf2692a6124bef9a44c9216acfc
                        )

                    [lib/public/Files/Template/Template.php] => Array
                        (
                            [expected] => 5ad62a4b04b6f12b9f236819b7af060d6bd66284f5de526b1b3483bb17bd18a97c6c03a93d8cdc4f7fe27874231805ca1d917a4ff9d27f5521161844c27d9c83
                            [current] => 92756e6b4c0ac07f7674ee94cb5e93f18a7b952ee237eb531d3b7c0336517599834aff1343695feea8ce0b19dec058496a1b0d71550eb11165adf9944ae8d38a
                        )

                    [lib/public/Files/Template/TemplateFileCreator.php] => Array
                        (
                            [expected] => 94b001819d14b537b720bc4ce552553f73d161b4499b4982775056074506bda22cb3e890f2bba7b9ba744419b9e3bbf6bbc14c71db5da550fa3ea9c9d958e29e
                            [current] => 6e37582d09f8b50cb7e2b8ff067fbdf3af764e79b989fddf3e455a878a5bc7588aaac6163ff0dc0223605642e48e10f4e34ca7097ee34b753ca28faf43dddac9
                        )

                    [lib/public/LDAP/ILDAPProvider.php] => Array
                        (
                            [expected] => 9ace4d5daa1d944c3637f3bf5d83a14f5bce735b096b894362992ab2c93a08489860a5ebb462d7af067914991b6330254e48062c41e149d1a188fb8a72d58555
                            [current] => 64eaad877d23e1b4c2a0b61d253468a0be44d8c7a12baa4cdf27bf6203dbbbc81ae15d04a5e1224c671932dd303bb45e0b32145c295fd6f558b35d5b0c6913bd
                        )

                    [lib/versioncheck.php] => Array
                        (
                            [expected] => 439df0868a788bd5eb7f8974f175e89afac396b747c69ec49f1fcb4bad517d4410aae2d7a83ab0863b92b900f1abe084bf52a505a3a270464a4b53cc3bf140e5
                            [current] => 7547a56a9312f1a6e71dd84e32e1dbbe01022822c40ab758b25675f787902362d7b293382ef07f3b97d4216d3d06b07d15c9c9d7f043f1c84229e48c3c124c89
                        )

                )

        )

    [encryption] => Array
        (
            [INVALID_HASH] => Array
                (
                    [lib/Command/FixEncryptedVersion.php] => Array
                        (
                            [expected] => ad113eb6f154f28d52968b98b5a53ad390283a11286bbc91b68f8c865b781712ea0fd805f6d633f2bf419b5857d5b86d4ed255e6296b431b20ef9c819dfbe740
                            [current] => e6f417c4268e6f51449b365bc6cadb89aef7c056ab5bcbb21c2ff81c5bd0801d76067498a783c550a15e5ac7c006bd87d3bf8c5a84b075f6f2b90ce837295a85
                        )

                )

        )

    [user_status] => Array
        (
            [INVALID_HASH] => Array
                (
                    [lib/Service/JSDataService.php] => Array
                        (
                            [expected] => de0d212660b04c42cd52d786a4d7d18b0405c49b0f643b665e401bedb421c1fdaf65f6d80bbea7a2c819aefaa6dbf5cf8d5070b12d004f25c59b69bec49e5f40
                            [current] => 94676d2111eb61a4ea68a4e97fc29cf55af3c666b93d896762be1f7df60acbc2668fb176d03279512854979311928a694924fdb865be569ec477e033638e1e3f
                        )

                )

        )

    [theming] => Array
        (
            [INVALID_HASH] => Array
                (
                    [lib/Service/JSDataService.php] => Array
                        (
                            [expected] => ad691831034eb716b73ae069826fdc78997af1b9638fe7968bda57af7e2c039b9b18596546e35d8ddaf95b88afca78d7c8d73798cd016571dca8ee072e631f1a
                            [current] => 50e631b40350f7a772482b04f421d23cf485806af16b671d515cdceef07e2e206ea5e693016b196ed0d4be213ce5c1c38223bbbce805ff41b0e28b7ef8d017ce
                        )

                )

        )

    [files_external] => Array
        (
            [INVALID_HASH] => Array
                (
                    [lib/Lib/Auth/AuthMechanism.php] => Array
                        (
                            [expected] => 07b2bebf83a8ec5e3dfc83ad3770be958dd6804b8f5686d39c635f245bbb0ae2b241b5f3e40c27bcd47444d075f2a627d10a0d745e87213ab77c0c3630ffecf2
                            [current] => 5843118acb68a6b662a57cd52b6cd06939f446bc3f72db7d8b05b2d3f2a91425b3652922da666008b893b99dcd11980ad248ee16f594ac85a0f016fb6a97628e
                        )

                    [lib/Lib/Backend/Backend.php] => Array
                        (
                            [expected] => 4168ec80d04b78270d825f30231c8857cc0049a032c22b35861f82f5d4f45799c51fe938cf76bd18bb7d7763ae57c969a270311c6eee17173cf2ba15fef16d82
                            [current] => f7166b783db51bf4013250ae97aa06160f4b58dc7365ee98a915dcc65c9630af2ab3da3be2e0c3a2130a09a04d330bf00c24ad2627bd4d20e5dc2a12c5f3ae47
                        )

                    [lib/Lib/DefinitionParameter.php] => Array
                        (
                            [expected] => e62e705f4d16535207b1dbb65ddda4312eb46eac453a3985b471418fccac3d901fbb788eacbcb4e73dddb891af5f348ed47b15b4f6356a7d9e186d620ef8a43d
                            [current] => 0c445cc3590190223a65b86906fefea585b658da445f171533f4800b02fe14628177bba567bc7ee5bb15085ce9e1ae07b0f6ebec487bf9c1ff8aa599a47f31cf
                        )

                    [lib/Lib/StorageConfig.php] => Array
                        (
                            [expected] => fcc6e9bad8df09850952bfebf0da2d83968f6a0ab5f4d8bbf0092602dbf485d726504416627a682223c7af2c1d17182246b7e9b25c3ec8b229ed4b87f69bf4ff
                            [current] => 0e80962de53d450f370305c92cc528cc4f6fe1ba67fea66ea0e90d842bed554ad382c816fd9155f08d7edb5db505a0a1b9d21a9adbb604eb270b6bd18e026190
                        )

                )

        )

    [user_ldap] => Array
        (
            [INVALID_HASH] => Array
                (
                    [lib/Access.php] => Array
                        (
                            [expected] => aa47383383ea161d95154198741bd7d0c1cc46879b538ea624b40d9113dbfa7b69b987d9d200edf3dd70d54ad1de84b24d1feb9b5cae8b50bd25939691596770
                            [current] => 039be34f362de781f7bc9900dda8e62c4d345a535b9d65735048fbe15363e742123e0172593476efe25bd605041ba8e03aad495635cf23b37e902e3bed51e46a
                        )

                    [lib/Connection.php] => Array
                        (
                            [expected] => b3f6817391f255d025c9ee9e111db499f301e2458cba009511f6b2a6ac621eb303121ada7db977349208c7ad77b6246eec0955c2492ee8c10429fac60b8a3554
                            [current] => 1a3fa99b1611060853584daf1f11eba0acfc78222d1c382249226ffcb3804f52a78d5fbe6c7cd2865362c019dbc518fce67c80210a7a7f11e9ee5f8b4f9165b5
                        )

                    [lib/Group_LDAP.php] => Array
                        (
                            [expected] => b50c1825b6973d11f10cbe1a42ae75c3c1ee6ca0e76dbfc6136a49a447ff8f686b4cf458b820e25752a45f61fa25878c4dbf5ee3e286ff317ad947edf51b7f84
                            [current] => 1c784609d43893cd6cd6c4ede80a849fc71030b33430858a7de5b81e1df7a7c8d1250705cc0ef11626aac7ea137cddf3c56838c2884c9861854b822c44bf03ba
                        )

                    [lib/Group_Proxy.php] => Array
                        (
                            [expected] => f59b07f48ebd9dad9462993c36d2cffc62967a6169263dd2b87ded5d3b3472b8af8337a1ea73f698f03936ba7daf2853d6588738d2764b5a6f49fc96a84a9b3e
                            [current] => 22f457573ad085a9d76270aa5fce7164dc5837c6c030d560b2e2dc30a988a640a28d003bc6eb1c460b42fef6e371ad40eff839ea628505cb9d3c5ba22fc0b162
                        )

                    [lib/IGroupLDAP.php] => Array
                        (
                            [expected] => fb9d995b9c387da29bf4586ee573d45c7e1fd146e761f72e75b1d1289f8013da1cb128d537eb65de51f31ddd22185478997cc2088b39a6c19e283b59737119f8
                            [current] => f1bd949e11da7eefae58437a7114d24662735ddf7fcc2a1b0ec149f0f6435e6fa0cb729e82a4bfd64b7d9315a50eeba141bde98c393fdc8d427d848c49a56874
                        )

                    [lib/ILDAPWrapper.php] => Array
                        (
                            [expected] => 917f041832e3c456565bb185718a9f4636383534f99ceb99cfeca71c173fbac3ab584ccc7c9905fdb1ef95855c429129214f7467b5e66a560ed8611d34c8bd98
                            [current] => f19af5e562e5bb33a39408830631d860f1e7bf6fc160c4d6757cc6c7ac7014de6a44dc1fc99886b5c2f35afb08cdebfe8ca4be4377dc91094b14dd5b579ebb72
                        )

                    [lib/IUserLDAP.php] => Array
                        (
                            [expected] => 175e8471782c2f5476a5f6ae3131cecfd1d3cc43cc3f20262834fa56c9b847e5b3a04afb17369eb72361f4b18b3ae2a2331f9133f1455b2535b0752fad452188
                            [current] => 3bce8559b34b27cbe510a5703d7bdd091bd5adf36a11e753918b9dd017712f6a441d1737b64a92dd5c453248ef90506c457f384522d72abcacb8bc52466cc2fb
                        )

                    [lib/LDAP.php] => Array
                        (
                            [expected] => bdd6954724240ae2e5c1eeeb38b0e875df0e0bc473e990fada1a03ee2c741212b1d6dce3184643e6ffb366b49a4e4cc3ee1bea03fb328ebabb875dd52a32054f
                            [current] => 750c60b92a8d3021efab562e84ad3523041a66a98fdbd987454f18868c90260f5e4acfc1bd70baed20654d31dd44f6a7b8d59ae733b43c962d91adc8af6f9238
                        )

                    [lib/LDAPProvider.php] => Array
                        (
                            [expected] => c3800a2d071e8256afadfa7f83241b41c2ed8be6147c76fd41e1fbf9df4f32a1730403f4f48b081af82ed0d9465bc21a3f3cb7b8d433a5dfc0d80e3268eee570
                            [current] => de25c7640bbf09e8f668c148d9eef5777055745c0dbd9373969f626ed3cbe19d20c53cbe096095c2dfceaba1507c360c88ccb4c44d1437d1fdb2c34535cfd2cb
                        )

                    [lib/PagedResults/IAdapter.php] => Array
                        (
                            [expected] => cf16427e2950c147ebf06852d715d5088d15aeecd371e1be8d9e67356c364f5ef874565102c4ba4d73349182522a0b5e57cab82f66e52dc8720da28988453b29
                            [current] => 0328ada7885b535e9c8ded62dae55af31d1487c1751dfc6412022a8fae37e76b93a8f0230c367218a47130231da2274357a6fffb6a75210d3a5e01578f231869
                        )

                    [lib/PagedResults/TLinkId.php] => Array
                        (
                            [expected] => bc4e388ddaca2566a929c42c2c628ff5733a0fa1405bb636a5cd71e73eaef7e795ecaaa312544b7d92de700b7af8371d71d55b83dcdb190193e668ce5921bf61
                            [current] => 1aabb926ce0f7390803ccb1f4672b1e02cd393a6a5e96deafffb61d48f71ecfdbaec5078a651941cda6a54958a69576faf2785cbe9564cb775b1c640eedcf6bd
                        )

                    [lib/User/Manager.php] => Array
                        (
                            [expected] => 9b7382afc6184908a2d1c0e44a8188f23e5b4749f8be5ee03501602f547e108c46d9a153dbf89d54dfb8943c4babb41e8297961217f1b32bfb3fd8be9d59f3ae
                            [current] => 13757aa1c489f678da5eeaf103b0234bee6471e08eb40d5228fa1860b8bbb29d5d2b5d637f62d2a057874433251b580ea2ad1898e327c519674434085ce45c07
                        )

                    [lib/User/User.php] => Array
                        (
                            [expected] => d13894a7d68f65ad8910d8fbb64c746864d333cdd6f529cfaffd30e9227af42d671117bc9f432ec30c4896fccde844172be8c6a5a58f0049f711fb55450bcd3a
                            [current] => 17d0414436df59d8a59c95054ce4731e561ad3d3cc3bd7ccfeca390335bb538a1c94fe517dd20cb228a5bb1995928a84afac6afb73a649b651f038f886ceb5ac
                        )

                    [lib/User_LDAP.php] => Array
                        (
                            [expected] => e881d45150a2bebc3a46a8cc5b9b3353aba8d31a0bd844fee12a071d029c140b9fe83044f2162fff823431db619afe7b7bc650956b9959a10f8771ec08ddaa8f
                            [current] => a644c328169b981dbdab6c8feaf1ad4022f08ee207351c33f28f6b03ca1d1b7c8676832b2bdce74425ef8cd839aafb9d1375ca8c7d2dac546df307427beb4393
                        )

                    [lib/User_Proxy.php] => Array
                        (
                            [expected] => 7183a5b5f156a7b74bf4ba8288f6df394bcead4c4da3dcf00f8f8112d349785b5cc3f974f098bc189860a6e9dcba210eaed76010653cd033a3c2e3951a36fddd
                            [current] => ebd25b5a26ceac813571cd66a076aa02ba1f0470a4818347a4dd7497261a7264b9f2197666484063f60aea4b30e894c9aa7b48b5e32439edfdc7fb679c8ebee6
                        )

                    [lib/Wizard.php] => Array
                        (
                            [expected] => 6be98f2f0257687dd5e0be5c8bea5864f7e8366bc57b7a7fdea0fa430963240d1bd636dc86a62a10bd6ee05a9909f92d49a3986b30448f151ea749c5b40abd65
                            [current] => fe9b56a2d93962f5027fc6af450bf6dfae20c96e15eeff005d3dbf3183ae0a35da1179fb63461b8cfe66fccbadcdaacd60efffb9a64697ac916682aee8956b9e
                        )

                )

        )

)
```


### Nextcloud Logs

```shell
PHP                 Error: Return type of OCA\LogReader\Log\LogIterator::rewind() should either be compatible with          2022-04-14T06:11:28+00:00  
                              Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily                                  
                              suppress the notice at /usr/share/webapps/nextcloud/apps/logreader/lib/Log/LogIterator.php#69 at                                   
                              lib/private/Log/ErrorHandler.php line 92                                                                                           
                                                                                                                                                                 
                               0. apps/logreader/lib/Log/LogIterator.php line 24                                                                                 
                                  OC\Log\ErrorHandler::onError(                                                                                                  
                                                                                                                                                                 
                                  )                                                                                                                              
                               1. lib/composer/composer/ClassLoader.php line 571                                                                                 
                                  include("\/usr\/share\/webapps\/nextcloud\/apps\/logreader\/lib\/Log\/LogIterator.php")                                        
                               2. lib/composer/composer/ClassLoader.php line 428                                                                                 
                                  Composer\Autoload\includeFile(                                                                                                 
                                                                                                                                                                 
                                  )                                                                                                                              
                               3. .../logreader/lib/Log/LogIteratorFactory.php line 55                                                                           

                                  Composer\Autoload\ClassLoader->loadClass(                                                                                      
                                                                                                                                                                 
                                  )                                                                                                                              
                               4. .../logreader/lib/Command/Tail.php line 65                                                                                     
                                  OCA\LogReader\Log\LogIteratorFactory->getLogIterator(                                                                          
                                                                                                                                                                 
                                  )                                                                                                                              
                               5. 3rdparty/symfony/console/Command/Command.php line 255                                                                          
                                  OCA\LogReader\Command\Tail->execute(                                                                                           
                                                                                                                                                                 
                                  )                                                                                                                              
                               6. core/Command/Base.php line 168                                                                                                 
                                  Symfony\Component\Console\Command\Command->run(                                                                                
                                                                                                                                                                 
                                  )                                                                                                                              
                               7. 3rdparty/symfony/console/Application.php line 1009                                                                             
                                  OC\Core\Command\Base->run(                                                                                                     
                                                                                                                                                                 
                                  )                                                                                                                              
                               8. .../console/Application.php line 273                                                                                           
                                  Symfony\Component\Console\Application->doRunCommand(                                                                           
                                                                                                                                                                 
                                  )                                                                                                                              
                               9. .../symfony/console/Application.php line 149                                                                                   
                                  Symfony\Component\Console\Application->doRun(                                                                                  
                                                                                                                                                                 
                                  )                                                                                                                              
                              10. lib/private/Console/Application.php line 211                                                                                   
                                  Symfony\Component\Console\Application->run(                                                                                    
                                                                                                                                                                 
                                  )                                                                                                                              
                              11. console.php line 99                                                                                                            
                                  OC\Console\Application->run(                                                                                                   
                                                                                                                                                                 
                                  )                                                                                                                              
                              12. occ line 11                                                                                                                    
                                  require_once("\/usr\/share\/webapps\/nextcloud\/console.php")
```


### Additional info

```
In Connection.php line 87:             
  Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused  
```

### PR DESCRIPTION
**Pull request by joshtrichards**
* Resolves: #31998

## Summary

Adds support to `occ db:convert-type` to support UNIX socket connections via MySQL/MariaDB:
* Uses same `dbhost` / `hostname` parameter parsing logic (adapted) as used elsewhere (at least the relevant parts) for consistency. 
* Adds UI support for non-passworded connections.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: core/Command/Db/ConvertType.php [hunk 1]
```diff
@@ -254,6 +257,16 @@ protected function getToDBConnection(InputInterface $input, OutputInterface $out
...
+		if (strpos($input->getOption('hostname'), ':') !== false)  {
+			// Host variable may carry a socket (or port)
+			[$host, $portOrSocket] = explode(':', $input->getOption('hostname'), 2);
+			if (ctype_digit($portOrSocket)) {
+				$connectionParams['port'] = $portOrSocket; // to be consistent with how we handle this elsewhere we accept this too but don't document it
+			} else {
+				$connectionParams['unix_socket'] = $portOrSocket;
+			}
+			$connectionParams['host'] = $host;
+		}
```
Comment (Fenn-CS) [inline core/Command/Db/ConvertType.php:269]:
```suggestion
if (preg_match('/^(.+)(:(\d+|[^:]+))?$/',$input->getOption('hostname'), $matches)) {
    $connectionParams['host'] = $matches[1];
    if (isset($matches[3])) {
        if (is_numeric($matches[3])) {
            $connectionParams['port'] = $matches[3];
        } else {
            $connectionParams['unix_socket'] = $matches[3];
        }
    }
}
```

Suggestion :

 Using regex is most likely better than explode. `/^(.+):(\d+|[^:]+)$/` matches a string that starts with one or more characters `((.+))` followed by a colon `(:)` and then either a numeric value `(\d+)` or one or more non-colon characters `([^:]+)` until the end of the string `($)`.

The regular expression approach allows you to extract the host name and port number or socket path in a single step, which is more concise than using `explode()` and `ctype_digit()`. Additionally, it allows for more flexibility in the format of the option value.

**Review by nfebe — COMMENTED** [review]
Looks okay though I left an inline suggestion. Do you mind using regex instead?

File: core/Command/Db/ConvertType.php (hunk 1 above)
Comment (Fenn-CS) [reply core/Command/Db/ConvertType.php:269]: I did not copy the comments but they are relevant.

**Comment by skjnldsv** [comment]
Hey @joshtrichards 
We cleaned up a some old staled PRs! But a quick look at this PR seems liek a good candidate for an update, let me take over to help you get it merge in 31! :muscle:

**Review by skjnldsv — APPROVED** [review]

**Review by nfebe — APPROVED** [review]
LGTM

**Comment by susnux** [comment]
@joshtrichards as you are a member of Nextcloud organization, could you maybe move this into a local branch? Some CI does not work on forks :pensive:

**Comment by skjnldsv** [comment]
Merged, anyway, tests passed locally for me
