### PR TITLE
don't send invitation emails for past events

### LINKED ISSUE #2855: Invitation send to attendees upon calendar import (also for past events)
Posted on #nextcloud on freenode irc

[15:12:36] just setting up nextcloud on a freebsd server today, and made a test user account and imported some account data from a google account. I imported a calendar and while importing the calendar nextcloud started to notify contacts for past appointments.....
[15:12:45] nextcloud 11.0 stable
[15:13:26] shutdown the postfix service and will remove the queue but guys this is quite an oversight....
[15:17:54] That sounds like a good github issue
[15:18:18] I'm a little surprised it doesn't check whether the date of an appointment is in the past before sending a notification
[15:18:43] there is about 10 years of google appointments getting mailed out to contacts
[15:18:52] import not yet complete
[15:19:07] pretty stunning oversight
[15:20:50] also as the user has not yet defined an email address the mail is going to the postmaster for the domain rofl....
[15:22:07] so basically the calendar app upon import even without a user defining an email address sends out mail via an imagined user/email address named after the site name @ the config domain name

Update 1

X-PHP-Originating-Script: 80:SimpleMailInvoker.php

you guys gotta patch this asap
There should be no immediate outbound mail triggered by importing data from outside data source. The import was not even half way through and the mails were flying out....

your calendar app sent out emails to 10 years of google calendar invitees..... really?

spammers can use this flaw actually...

ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=Some Dude ;X-NUM-GUESTS=0:mailto:user@server.nul
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;CN=Some Dude;X-NUM-GUESTS=0:mailto:user@server.nul
 
### Steps to reproduce
1. new fresh install *unknown if a relevant step*
2. create admin user *unknown if a relevant step*
3. create normal user *unknown if a relevant step*
4. do not create email account for normal user *unknown if a relevant step*
5. import google calendar which includes previous events with invited contacts

### Expected behaviour
upon Importation of google Calendar with past or present events with included invitees should never activate an immediate sending of invitations.

### Actual behaviour
importing the calendar nextcloud started to notify contacts for past appointments 

### Server configuration
FreeBSD 11.0 -p6

Apache 2.4.25

mysql-server 5.6.34

PHP Version: 5.6.29
Memory Limit: 512.0 MB
Max Execution Time: 3600
Upload max size: 511.0 MB

Nextcloud version: 11
Fresh Install
Source from nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - announcementcenter: 3.0.0
  - apporder: 0.3.3
  - audioplayer: 1.4.0
  - bookmarks: 0.9.1
  - calendar: 1.4.1
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - direct_menu: 0.9.3
  - encryption: 1.4.1
  - external: true
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - gpxedit: 0.0.3
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.2
  - nextcloud_announcements: 1.0
  - notes: 2.1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - previewgenerator: 1.0.1
  - provisioning_api: 1.1.0
  - richdocuments: 1.1.24
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreed: 1.1.2
  - spreedme: 0.3.5
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.4
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_external: 0.4
  - workflowengine: 1.1.1
Disabled:
  - files_automatedtagging
  - files_retention
  - user_ldap
  - user_saml
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
{
    "system": {
        "instanceid": "ocha0opv8gho",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.aventia.pw"
        ],
        "datadirectory": "\/usr\/local\/www\/nextcloudav\/data",
        "overwrite.cli.url": "https:\/\/www.aventia.pw\/thera",
        "dbtype": "sqlite3",
        "version": "11.0.0.10",
        "logtimezone": "UTC",
        "installed": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** 
no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** 
no

**Browser:** Chrome current

**Operating system: OSX 10.9.5

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

### PR DESCRIPTION
**Pull request by georgehrke**
fixes #2855

### CODE REVIEW

File: apps/dav/appinfo/v1/caldav.php [hunk 1]
```diff
@@ -52,6 +52,7 @@
 $calDavBackend = new CalDavBackend($db, $principalBackend, $userManager, $random, $dispatcher, true);
 
 $debugging = \OC::$server->getConfig()->getSystemValue('debug', false);
+$sendInvitations = \OC::$server->getConfig()->getSystemValue('caldav_send_invitations', true);
```
Comment (LukasReschke) [inline apps/dav/appinfo/v1/caldav.php]: I'm usually not really a fan of configuration values. Is there a reason we do really need to have that one? 🙈 

Also stuff in the app config is usually easier to deploy on clusters :)

**Review by LukasReschke — DISMISSED** [review]

File: apps/dav/appinfo/v1/caldav.php (hunk 1 above)
Comment (georgehrke) [inline apps/dav/appinfo/v1/caldav.php]: see #2800, #3830
some people run into issues with our server side scheduling and just want to keep sending their invitations via thunderbird.
or they just don't like that invitations are sent out by the server's email address, not their own one.

Comment (georgehrke) [inline apps/dav/appinfo/v1/caldav.php]: also https://github.com/nextcloud/server/issues/2345

Comment (georgehrke) [inline apps/dav/appinfo/v1/caldav.php]: Not sure we will ever change that value on clusters.

**Comment by kosli** [comment]
any update on merging this pull request?

**Comment by georgehrke** [comment]
@kosli There is still something missing, see the first post. Won't have time to look into this before the weekend.

**Comment by kosli** [comment]
@georgehrke ups, I didn't see the ToDo on top. Thanks!

**Comment by georgehrke** [comment]
rebased

**Comment by georgehrke** [comment]
One thing I wasn't sure about:

Should it not send out invitations for any events in the past or only for events that are older than 2 weeks / month ?

**Comment by jospoortvliet** [comment]
I wouldn't sent out any invitations for past events, after all those either have been sent already or the user decided not to sent them...

**Comment by georgehrke** [comment]
Backport to review once this is merged: https://github.com/nextcloud/server/pull/5841

**Comment by ggeorgg** [comment]
Import of a calendar in a fresh nextcloud 12.0.1 with these changes applied is working. The option to turn off resending invitation mails via the config setting is also working.

**Comment by jospoortvliet** [comment]
@LukasReschke happy with the changes/feedback from Georg? It'd be nice to get this in so 12.0.3 will not resent all these invitations 😢

File: apps/dav/appinfo/v1/caldav.php (hunk 1 above)
Comment (ggeorgg) [inline apps/dav/appinfo/v1/caldav.php]: Besides this configuration value, it would be more intuitive to have a checkbox when importing a calendar. The user itself, who has no access to the config.php should be able to decide whether to send invitaions for future events or not while importing a calendar.

Comment (georgehrke) [inline apps/dav/appinfo/v1/caldav.php]: > it would be more intuitive to have a checkbox when importing a calendar

Or maybe never sent invitations on import? 
Anyway, that's out of scope for this pr.
Let's continue the discussion here: https://github.com/nextcloud/calendar/issues/576

**Review by tcitworld — APPROVED** [review]

File: apps/dav/appinfo/v1/caldav.php (hunk 1 above)
Comment (MorrisJobke) [reply apps/dav/appinfo/v1/caldav.php]: I would also not make it a server wide setting. Just remove the added stuff (compared to the backport) and then we can get this in.

**Review by MorrisJobke — CHANGES_REQUESTED** [review]

File: apps/dav/appinfo/v1/caldav.php (hunk 1 above)
Comment (georgehrke) [reply apps/dav/appinfo/v1/caldav.php]: Ok, I will remove that commit for now.
I would anyway still like to add this feature in the future.

Should I just implement it via the appconfig table?

**Review by MorrisJobke — APPROVED** [review]

**Comment by jospoortvliet** [comment]
AWESOME!
