### PR TITLE
Server error/hint pages with a 500 error code to avoid it being seen …

### LINKED ISSUE #6893: Status code should be 500 on error
### Steps to reproduce
1. Make config file write protected
2. Visit Nextcloud main page

### Expected behaviour
The server should return status code 500 to alert standard monitoring systems. (Or ignore, that the config is not writeable)

### Actual behaviour
The server returns status code 200

### Server configuration

**Operating system**:
Debian

**Web server:**
Apache 2

**Database:**
Postgresql

**PHP version:**
5.6

**Nextcloud version:** (see Nextcloud admin page)
12

### PR DESCRIPTION
**Pull request by MorrisJobke**
…instead of the actual resource

* found while reviewing #7205 
* fixes #6893

Could this solve most of the issues we had in the past with files being overwritten? Because error pages were served with HTTP code 200 :/ 

This should at least avoid problems with clients and the web UI.

Usages:

bildschirmfoto 2018-06-26 um 09 20 00

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
:see_no_evil:

File: lib/private/legacy/template.php [hunk 1]
```diff
@@ -317,6 +317,7 @@ public static function printErrorPage( $error_msg, $hint = '' ) {
 			$hint = '';
 		}
 
+		header(self::getHttpProtocol() . ' 500 Internal Server Error');
```
Comment (ChristophWurst) [inline lib/private/legacy/template.php]: What about http://php.net/http_response_code?

Comment (MorrisJobke) [reply lib/private/legacy/template.php]: I just used the way it was before. We can of course also move to this. What is the advantage? No need to juggle again with the protocol and terms behind the code?

Comment (MorrisJobke) [reply lib/private/legacy/template.php]: I would for now vote for this approach to have a minimal backportable solution and then fix the http_response_code in a separated PR.

**Review by skjnldsv — APPROVED** [review]

File: lib/private/legacy/template.php (hunk 1 above)
Comment (MorrisJobke) [reply lib/private/legacy/template.php]: Just noticed that it is not that easy and I will change it already to make the code more clear.

**Comment by MorrisJobke** [comment]
Okay - I fixed a bit more, but now error and exception pages are properly covered. I would not backport it anymore, but this should be fine for now.

Ready for review 🚢

File: lib/private/legacy/template.php [hunk 2]
```diff
@@ -304,9 +304,10 @@ public static function printGuestPage( $application, $name, $parameters = array(
 	 * Print a fatal error page and terminates the script
 	 * @param string $error_msg The error message to show
 	 * @param string $hint An optional hint message - needs to be properly escape
+	 * @param int $statusCode
 	 * @suppress PhanAccessMethodInternal
 	 */
-	public static function printErrorPage( $error_msg, $hint = '' ) {
+	public static function printErrorPage( $error_msg, $hint = '', $statusCode = \OC_Response::STATUS_INTERNAL_SERVER_ERROR ) {
```
Comment (ChristophWurst) [inline lib/private/legacy/template.php]: This might be very specific and unexpected, but what if the `OC_Response` class has not been loaded at this point and autoloading causes another error/exception? Should we use `500` instead, just to be on the safe side?

Comment (MorrisJobke) [reply lib/private/legacy/template.php]: Sure - let me update it.

**Review by ChristophWurst — APPROVED** [review]
LGTM!
