### PR TITLE
fix(files_reminders): Join the reminders with the file system metadata

### LINKED ISSUE #53527: [Bug]: More than 1000 expressions in a list are not allowed on Oracle. (postgresql, in files_reminders / cacheFolder)
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

"More than 1000 expressions in a list are not allowed on Oracle." logged on PROPFIND

### Steps to reproduce

1. view directory in browser
2. observe logs

### Expected behavior

No errors.

### Nextcloud Server version

31

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 32.0.1 to 32.0.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [x] SSO - SAML
- [ ] Other

### Configuration report

```json
"system": {
        "version": "31.0.6.2",
        "config_is_read_only": true,
        "connectivity_check_domains": [],
        "check_for_working_wellknown_setup": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***WHY DID occ config:list system NOT CONSIDER THIS SENSITIVE?***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance_window_start": 21,
        "debug": false,
        "default_phone_region": "DE",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "updatechecker": false,
        "upgrade.disable-web": true,
        "updater.server.url": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "skeletondirectory": "",
        "default_language": "de",
        "overwrite.cli.url": "***WHY DID occ config:list system NOT CONSIDER THIS SENSITIVE?***",
        "htaccess.RewriteBase": "\/",
        "allow_local_remote_servers": true,
        "loglevel": 2,
    "log_type": "syslog",
        "syslog_tag": "nextcloud",
        "logfile": "",
        "logdateformat": "Y-m-d H:i:s",
        "logtimezone": "UTC",
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "log_type_audit": "syslog",
        "syslog_tag_audit": "nextcloud",
        "logfile_audit": "",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcache.locking": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "\/run\/nextcloud\/memcached.sock",
                0
            ]
        ],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "maintenance": false,
        "knowledgebaseenabled": false,
        "enable_previews": true,
        "allow_user_to_change_display_name": false,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "trashbin_retention_obligation": "14, 60",
        "mail_send_plaintext_only": true,
        "theme": "",
        "has_internet_connection": false
    }
```

### List of activated Apps

```shell
Enabled:
  - activity: 4.0.0
  - admin_audit: 1.21.0
  - app_api: 5.0.2
  - calendar: 5.3.2
  - circles: 31.0.0
  - cloud_federation_api: 1.14.0
  - comments: 1.21.0
  - contactsinteraction: 1.12.0
  - dav: 1.33.0
  - federatedfilesharing: 1.21.0
  - files: 2.3.1
  - files_accesscontrol: 2.0.0
  - files_automatedtagging: 2.0.0
  - files_downloadlimit: 4.0.0
  - files_reminders: 1.4.0
  - files_retention: 2.0.1
  - files_sharing: 1.23.1
  - files_trashbin: 1.21.0
  - files_versions: 1.24.0
  - logreader: 4.0.0
  - lookup_server_connector: 1.19.0
  - notifications: 4.0.0
  - oauth2: 1.19.1
  - privacy: 3.0.0
  - profile: 1.0.0
  - provisioning_api: 1.21.0
  - related_resources: 2.0.0
  - richdocuments: 8.7.0
  - serverinfo: 3.0.0
  - settings: 1.14.0
  - systemtags: 1.21.1
  - tasks: 0.16.1
  - text: 5.0.0
  - theming: 2.6.1
  - twofactor_backupcodes: 1.20.0
  - user_saml: 6.6.0
  - viewer: 4.0.0
  - webhook_listeners: 1.2.0
  - workflowengine: 2.13.0
Disabled:
  - bruteforcesettings: 4.0.0 (installed 1.0.3)
  - dashboard: 7.11.0 (installed 7.0.0)
  - encryption: 2.19.0
  - federation: 1.21.0 (installed 1.2.0)
  - files_external: 1.23.0
  - files_pdfviewer: 4.0.0 (installed 2.10.0)
  - nextcloud_announcements: 3.0.0 (installed 1.1)
  - password_policy: 3.0.0 (installed 1.3.0)
  - photos: 4.0.0-dev.1 (installed 1.0.0)
  - recommendations: 4.0.0 (installed 0.8.0)
  - support: 3.0.0 (installed 1.1.0)
  - suspicious_login: 9.0.1
  - twofactor_nextcloud_notification: 5.0.0
  - twofactor_totp: 13.0.0-dev.0
  - updatenotification: 1.21.0 (installed 1.2.0)
  - user_ldap: 1.22.0
  - user_status: 1.11.0 (installed 1.8.1)
  - weather_status: 1.11.0 (installed 1.7.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```json
{"reqId":"**redacted**","level":3,"time":"**redacted**","remoteAddr":"**redacted**","user":"**redacted**","app":"core","method":"PROPFIND","url":"/remote.php/dav/files/**redacted**/**redacted**/","message":"{\"Exception\":\"Doctrine\\\\DBAL\\\\Query\\\\QueryException\",\"Message\":\"More than 1000 expressions in a list are not allowed on Oracle.\",\"Code\":0,\"Trace\":[{\"file\":\"/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php\",\"line\":284,\"function\":\"prepareForExecute\",\"class\":\"OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder\",\"type\":\"->\"},{\"file\":\"/nextcloud/lib/public/AppFramework/Db/QBMapper.php\",\"line\":329,\"function\":\"executeQuery\",\"class\":\"OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder\",\"type\":\"->\"},{\"file\":\"/nextcloud/apps/files_reminders/lib/Db/ReminderMapper.php\",\"line\":159,\"function\":\"findEntities\",\"class\":\"OCP\\\\AppFramework\\\\Db\\\\QBMapper\",\"type\":\"->\"},{\"file\":\"/nextcloud/apps/files_reminders/lib/Service/ReminderService.php\",\"line\":51,\"function\":\"findAllInFolder\",\"class\":\"OCA\\\\FilesReminders\\\\Db\\\\ReminderMapper\",\"type\":\"->\"},{\"file\":\"/nextcloud/apps/files_reminders/lib/Dav/PropFindPlugin.php\",\"line\":80,\"function\":\"cacheFolder\",\"class\":\"OCA\\\\FilesReminders\\\\Service\\\\ReminderService\",\"type\":\"->\"},{\"file\":\"/nextcloud/apps/files_reminders/lib/Dav/PropFindPlugin.php\",\"line\":53,\"function\":\"cacheFolder\",\"class\":\"OCA\\\\FilesReminders\\\\Dav\\\\PropFindPlugin\",\"type\":\"->\"},{\"file\":\"/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php\",\"line\":89,\"function\":\"propFind\",\"class\":\"OCA\\\\FilesReminders\\\\Dav\\\\PropFindPlugin\",\"type\":\"->\"},{\"file\":\"/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php\",\"line\":1052,\"function\":\"emit\",\"class\":\"Sabre\\\\DAV\\\\Server\",\"type\":\"->\"},{\"file\":\"/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php\",\"line\":984,\"function\":\"getPropertiesByNode\",\"class\":\"Sabre\\\\DAV\\\\Server\",\"type\":\"->\"},{\"file\":\"/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php\",\"line\":1664,\"function\":\"getPropertiesIteratorForPath\",\"class\":\"Sabre\\\\DAV\\\\Server\",\"type\":\"->\"},{\"file\":\"/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php\",\"line\":1649,\"function\":\"writeMultiStatus\",\"class\":\"Sabre\\\\DAV\\\\Server\",\"type\":\"->\"},{\"file\":\"/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php\",\"line\":346,\"function\":\"generateMultiStatus\",\"class\":\"Sabre\\\\DAV\\\\Server\",\"type\":\"->\"},{\"file\":\"/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php\",\"line\":89,\"function\":\"httpPropFind\",\"class\":\"Sabre\\\\DAV\\\\CorePlugin\",\"type\":\"->\"},{\"file\":\"/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php\",\"line\":472,\"function\":\"emit\",\"class\":\"Sabre\\\\DAV\\\\Server\",\"type\":\"->\"},{\"file\":\"/nextcloud/apps/dav/lib/Connector/Sabre/Server.php\",\"line\":49,\"function\":\"invokeMethod\",\"class\":\"Sabre\\\\DAV\\\\Server\",\"type\":\"->\"},{\"file\":\"/nextcloud/apps/dav/lib/Server.php\",\"line\":400,\"function\":\"start\",\"class\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Server\",\"type\":\"->\"},{\"file\":\"/nextcloud/apps/dav/appinfo/v2/remote.php\",\"line\":21,\"function\":\"exec\",\"class\":\"OCA\\\\DAV\\\\Server\",\"type\":\"->\"},{\"file\":\"/nextcloud/remote.php\",\"line\":145,\"args\":[\"/nextcloud/apps/dav/appinfo/v2/remote.php\"],\"function\":\"require_once\"}],\"File\":\"/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php\",\"Line\":237,\"message\":\"More than 1000 expressions in a list are not allowed on Oracle.\",\"query\":\"SELECT `id`, `user_id`, `file_id`, `due_date`, `updated_at`, `created_at`, `notified` FROM `*PREFIX*files_reminders` WHERE (`user_id` = :dcValue1) AND (`file_id` IN (:dcValue2)) ORDER BY `due_date` ASC\",\"exception\":{},\"CustomMessage\":\"More than 1000 expressions in a list are not allowed on Oracle.\"}","userAgent":"**redacted**","version":"31.0.6.2"}
```

### Additional info

* At some point *after* the error was thrown, the referenced table was found to be empty:
```
psql <<<'SELECT COUNT(*) FROM oc_files_reminders;'
 count 
-------
     0
(1 row)
```
  * (Does this guarantee the app is entirely unused and can be safely disabled?)

* Unconditionally blaming *Oracle* is misleading. In this case, Nextcloud is emitting this for postgresql, which defaults to somewhat higher limits.
* Some relevant bug reports may be easier to find using the `ORA-01795` code.
  * Most recently fixed previous instance: https://github.com/nextcloud/server/issues/41605

### PR DESCRIPTION
**Pull request by solracsf**
* Resolves: https://github.com/nextcloud/server/issues/53527

Eliminates the need to load `fileIds` into PHP by using a database `INNER JOIN` with the `oc_filecache` table, filtering files by their `parent` (the folder's ID) directly in the SQL query. This avoids the `IN` clause entirely

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by provokateurin — APPROVED** [review]
Thanks, this looks much better and should fix https://github.com/nextcloud/server/issues/53527

**Comment by provokateurin** [comment]
@solracsf any reason to keep it as a draft?

**Comment by solracsf** [comment]
I'll be on holiday for the next 3 weeks, but feel free to open/review.

**Review by come-nc — APPROVED** [review]

File: apps/files_reminders/lib/Db/ReminderMapper.php [hunk 1]
```diff
@@ -137,24 +137,14 @@ public function findNotified(DateTime $buffer, ?int $limit = null) {
...
 		$qb = $this->db->getQueryBuilder();
 
-		$qb->select('id', 'user_id', 'file_id', 'due_date', 'updated_at', 'created_at', 'notified')
-			->from($this->getTableName())
-			->where($qb->expr()->eq('user_id', $qb->createNamedParameter($user->getUID(), IQueryBuilder::PARAM_STR)))
-			->andWhere($qb->expr()->in('file_id', $qb->createNamedParameter($fileIds, IQueryBuilder::PARAM_INT_ARRAY)))
-			->orderBy('due_date', 'ASC');
+		$qb->select('r.id', 'r.user_id', 'r.file_id', 'r.due_date', 'r.updated_at', 'r.created_at', 'r.notified')
+			->from($this->getTableName(), 'r')
+			->innerJoin('r', 'oc_filecache', 'f', $qb->expr()->eq('r.file_id', 'f.fileid'))
```
Comment (kesselb) [inline apps/files_reminders/lib/Db/ReminderMapper.php:144]: This change is breaking the filelist :boom: 

It should be `filecache` and not `oc_filecache`.

**Comment by provokateurin** [comment]
The stable30 backport must also include https://github.com/nextcloud/server/pull/53644!

**Comment by solracsf** [comment]
> The stable30 backport must also include #53644!

`findAllInFolder()` is v31+
