### PR TITLE
fix(files_sharing): Improve expiration date input change handling

### LINKED ISSUE #51875: [Bug]: expiration date can not be set in chrome via keyboard
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

It's not possible to set the year. It always falls back to 1901 
(I can set the date and month when clicking on it with mouse (so no continuous entering possible)

An other user reported for him it is always 1.1.1970

For Firefox it works without problems.

### Steps to reproduce

1. Try to enter an expiration date for a file share in Chrome Browser via keyboard

### Expected behavior

Date can be set with keyboard in Chrome

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

tested with Chromium Version 133.0.6943.141

### PR DESCRIPTION
**Pull request by nfebe**
If the time picker component is emitting a Date object already, then there is redundant call of `new Date(new Date())` and therefore introduces subtle bugs, for example on chrome users could not  enter expiration date with keyboard.

- Use @update:model-value instead of @change/@input for more reliable date updates
- Ensure null and invalid dates are handled correctly in onExpirationChange
- Validate date input before updating defaultExpirationDateEnabled

Resolves : https://github.com/nextcloud/server/issues/51875

### CODE REVIEW

File: apps/files_sharing/src/components/SharingEntryLink.vue [hunk 1]
```diff
@@ -874,9 +875,9 @@ export default {
 		},
 
 		expirationDateChanged(event) {
-			const date = event.target.value
-			this.onExpirationChange(date)
-			this.defaultExpirationDateEnabled = !!date
+			const value = event?.target?.value
+			const isValid = Boolean(value && !isNaN(new Date(value).getTime()))
```
Comment (susnux) [inline apps/files_sharing/src/components/SharingEntryLink.vue:879]:
```suggestion
			const isValid = !!value && !isNaN(new Date(value).getTime())
```

a bit shorter

**Review by susnux — APPROVED** [review]

**Review by miaulalala — APPROVED** [review]
