### PR TITLE
 fix check for more users  in sharing dialogue

### LINKED ISSUE #10903: users is not defined when sharing.maxAutocompleteResults is set
### Steps to reproduce
1.  add `'sharing.maxAutocompleteResults' => 10,` to your config.php
2. open the share dialog for a file
3. search for a potential sharee

### Expected behaviour

No error

### Actual behaviour

ReferenceError: users is not defined[Learn More] sharedialogview.js:410:1

Functionality is not compromised.

In the check in https://github.com/nextcloud/server/blob/master/core/js/sharedialogview.js#L406 the users variable (and following) are not set, after some restructuring.

This could be replaced by `suggestions`, but we cannot get just the length as we need to use it seperately per shareType.

Perhaps best to estimate the max value on _getSuggestions.

### PR DESCRIPTION
**Pull request by blizzz**
fixes #10903 (see this also for reproduction steps)

### CODE REVIEW

File: core/js/sharedialogview.js [hunk 1]
```diff
@@ -557,7 +570,7 @@
 				$shareWithField.focus();
 			};
 
-			var perPage = 200;
+			var perPage = parseInt(oc_config['sharing.maxAutocompleteResults'], 10) || 200;
```
Comment (blizzz) [inline core/js/sharedialogview.js]: this, we actually could hardcode to 2, as it just checks for success as far as i see.

**Comment by blizzz** [comment]
reviews, pozhaluysta? :smile_cat:

**Review by nickvergessen — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]
