### PR TITLE
Fix data Apache2 .htaccess typo

### LINKED ISSUE #19160: AH00566: request failed: malformed request line
[debug.txt](https://github.com/nextcloud/server/files/4117268/debug.txt)

### Steps to reproduce
1. after setup any DB in Wizard
2. blank page

### Expected behaviour

go to auth page

### Actual behaviour
blank page

### Server configuration

Linux x86_64

**Web server:**

Apache 2.4.41 

**Database:** Any

**PHP version:** 7.3.14  and 7.4.02

**Nextcloud version:** latest 18

**Updated from an older Nextcloud/ownCloud or fresh install:**

fresh install

**Where did you install Nextcloud from:**

Website tar.gz

**Signing status:**

enable PHP Debug report this issue :

> [Mon Jan 27 13:55:55.763674 2020] [mpm_worker:notice] [pid 19031:tid 140258544342848] AH00292: Apache/2.4.41 (Unix) OpenSSL/1.1.1d SVN/1.13.0-dev PHP/7.3.14 configured -- resuming normal operations
[Mon Jan 27 13:55:55.763714 2020] [mpm_worker:info] [pid 19031:tid 140258544342848] AH00293: Server built: Aug 28 2019 15:55:24
[Mon Jan 27 13:55:55.763744 2020] [core:notice] [pid 19031:tid 140258544342848] AH00094: Command line: '/opt/Apache73/bin/httpd -f /share/CACHEDEV1_DATA/.qpkg/NextCloud73/httpd.conf'
[Mon Jan 27 13:55:55.763753 2020] [core:debug] [pid 19031:tid 140258544342848] log.c(1571): AH02639: Using SO_REUSEPORT: yes (1)
[Mon Jan 27 13:55:55.763765 2020] [mpm_worker:debug] [pid 19031:tid 140258544342848] worker.c(1758): AH00294: Accept mutex: pthread (default: pthread)
[Mon Jan 27 13:55:55.764229 2020] [watchdog:debug] [pid 19155:tid 140258544342848] mod_watchdog.c(590): AH02981: Watchdog: Created child worker thread (_proxy_hcheck_).
[Mon Jan 27 13:55:55.764378 2020] [proxy:debug] [pid 19155:tid 140258544342848] proxy_util.c(1935): AH00925: initializing worker proxy:reverse shared
[Mon Jan 27 13:55:55.764403 2020] [proxy:debug] [pid 19155:tid 140258544342848] proxy_util.c(1992): AH00927: initializing worker proxy:reverse local
[Mon Jan 27 13:55:55.764427 2020] [proxy:debug] [pid 19155:tid 140258544342848] proxy_util.c(2027): AH00930: initialized pool in child 19155 for (*) min=0 max=61 smax=61
[Mon Jan 27 13:56:40.604177 2020] [authz_core:debug] [pid 19034:tid 140257089337088] mod_authz_core.c(820): [client 192.168.0.2:61093] AH01626: authorization result of Require all granted: granted, referer: http://192.168.0.67:8080/cgi-bin/
[Mon Jan 27 13:56:40.604240 2020] [authz_core:debug] [pid 19034:tid 140257089337088] mod_authz_core.c(820): [client 192.168.0.2:61093] AH01626: authorization result of <RequireAny>: granted, referer: http://192.168.0.67:8080/cgi-bin/
[Mon Jan 27 13:56:40.604268 2020] [charset_lite:debug] [pid 19034:tid 140257089337088] mod_charset_lite.c(219): [client 192.168.0.2:61093] AH01448: incomplete configuration: src unspecified, dst unspecified, referer: http://192.168.0.67:8080/cgi-bin/
[Mon Jan 27 13:56:40.604335 2020] [authz_core:debug] [pid 19034:tid 140257089337088] mod_authz_core.c(820): [client 192.168.0.2:61093] AH01626: authorization result of Require all granted: granted, referer: http://192.168.0.67:8080/cgi-bin/
[Mon Jan 27 13:56:40.604346 2020] [authz_core:debug] [pid 19034:tid 140257089337088] mod_authz_core.c(820): [client 192.168.0.2:61093] AH01626: authorization result of <RequireAny>: granted, referer: http://192.168.0.67:8080/cgi-bin/
[Mon Jan 27 13:56:40.604368 2020] [charset_lite:debug] [pid 19034:tid 140257089337088] mod_charset_lite.c(219): [client 192.168.0.2:61093] AH01448: incomplete configuration: src unspecified, dst unspecified, referer: http://192.168.0.67:8080/cgi-bin/
[Mon Jan 27 13:56:40.812194 2020] [watchdog:debug] [pid 19832:tid 140258544342848] mod_watchdog.c(590): AH02981: Watchdog: Created child worker thread (_proxy_hcheck_).
[Mon Jan 27 13:56:40.812353 2020] [proxy:debug] [pid 19832:tid 140258544342848] proxy_util.c(1935): AH00925: initializing worker proxy:reverse shared
[Mon Jan 27 13:56:40.812381 2020] [proxy:debug] [pid 19832:tid 140258544342848] proxy_util.c(1992): AH00927: initializing worker proxy:reverse local
[Mon Jan 27 13:56:40.812406 2020] [proxy:debug] [pid 19832:tid 140258544342848] proxy_util.c(2027): AH00930: initialized pool in child 19832 for (*) min=0 max=61 smax=61
[Mon Jan 27 13:56:40.871093 2020] [optional_hook_import:error] [pid 19034:tid 140257089337088] AH01866: Optional hook test said: GET / HTTP/1.1
[Mon Jan 27 13:56:40.871111 2020] [optional_fn_export:error] [pid 19034:tid 140257089337088] AH01871: Optional function test said: GET / HTTP/1.1
[Mon Jan 27 13:56:43.810907 2020] [authz_core:debug] [pid 19034:tid 140257089337088] mod_authz_core.c(820): [client 192.168.0.2:61093] AH01626: authorization result of Require all granted: granted
[Mon Jan 27 13:56:43.810958 2020] [authz_core:debug] [pid 19034:tid 140257089337088] mod_authz_core.c(820): [client 192.168.0.2:61093] AH01626: authorization result of <RequireAny>: granted
[Mon Jan 27 13:56:43.810987 2020] [charset_lite:debug] [pid 19034:tid 140257089337088] mod_charset_lite.c(219): [client 192.168.0.2:61093] AH01448: incomplete configuration: src unspecified, dst unspecified
[Mon Jan 27 13:56:49.107392 2020] [authz_core:debug] [pid 19045:tid 140257296316160] mod_authz_core.c(820): [client 192.168.0.2:61117] AH01626: authorization result of Require all granted: granted
[Mon Jan 27 13:56:49.107443 2020] [authz_core:debug] [pid 19045:tid 140257296316160] mod_authz_core.c(820): [client 192.168.0.2:61117] AH01626: authorization result of <RequireAny>: granted
[Mon Jan 27 13:56:49.107473 2020] [charset_lite:debug] [pid 19045:tid 140257296316160] mod_charset_lite.c(219): [client 192.168.0.2:61117] AH01448: incomplete configuration: src unspecified, dst unspecified
[Mon Jan 27 13:56:49.151091 2020] [core:alert] [pid 19155:tid 140257296316160] [client 192.168.0.67:52436] /share/CACHEDEV1_DATA/.qpkg/NextCloud73/nextcloud/data/.htaccess: Expected </IifModule> but saw </IfModule>
[Mon Jan 27 13:56:49.151291 2020] [optional_hook_import:error] [pid 19155:tid 140257296316160] AH01866: Optional hook test said: GET /data/htaccesstest.txt HTTP/1.1
[Mon Jan 27 13:56:49.151301 2020] [optional_fn_export:error] [pid 19155:tid 140257296316160] AH01871: Optional function test said: GET /data/htaccesstest.txt HTTP/1.1
[Mon Jan 27 13:56:49.170704 2020] [core:debug] [pid 19832:tid 140257296316160] protocol.c(1335): [client 192.168.0.67:52438] AH00566: request failed: malformed request line
[Mon Jan 27 13:56:49.170871 2020] [optional_hook_import:error] [pid 19832:tid 140257296316160] AH01866: Optional hook test said: \x16\x03\x01\x02
[Mon Jan 27 13:56:49.170888 2020] [optional_fn_export:error] [pid 19832:tid 140257296316160] AH01871: Optional function test said: \x16\x03\x01\x02
[Mon Jan 27 13:56:49.819602 2020] [core:notice] [pid 19031:tid 140258544342848] AH00052: child pid 19034 exit signal Illegal instruction (4)
[Mon Jan 27 13:56:49.819694 2020] [core:notice] [pid 19031:tid 140258544342848] AH00052: child pid 19045 exit signal Illegal instruction (4)
[Mon Jan 27 13:56:50.823154 2020] [watchdog:debug] [pid 19999:tid 140258544342848] mod_watchdog.c(590): AH02981: Watchdog: Created child worker thread (_proxy_hcheck_).
[Mon Jan 27 13:56:50.823306 2020] [proxy:debug] [pid 19999:tid 140258544342848] proxy_util.c(1935): AH00925: initializing worker proxy:reverse shared
[Mon Jan 27 13:56:50.823338 2020] [proxy:debug] [pid 19999:tid 140258544342848] proxy_util.c(1992): AH00927: initializing worker proxy:reverse local
[Mon Jan 27 13:56:50.823363 2020] [proxy:debug] [pid 19999:tid 140258544342848] proxy_util.c(2027): AH00930: initialized pool in child 19999 for (*) min=0 max=61 smax=61

i have no clue.. tried also latest snapshot same issue , 17.0.2 version was working fine

### PR DESCRIPTION
**Pull request by Simounet**
Fix https://github.com/nextcloud/server/issues/19160

Hi there,
Thank you so much for this amazing piece of software.
Just wanted to fix a quick typo from the data's `.htaccess`. Let me know if I can add anything.
Have a nice day.

### CODE REVIEW

**Comment by kesselb** [comment]
Thanks :+1:

`git commit --amend --signoff`
`git push --force-with-lease origin fix/data-apache-htaccess-typo` 

Would you mind to use the above command to fix the DCO? If you added / removed commits in the meantime the command is proably different.

**Review by kesselb — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by Simounet** [comment]
> Thanks +1
> 
> `git commit --amend --signoff`
> `git push --force-with-lease origin fix/data-apache-htaccess-typo`
> 
> Would you mind to use the above command to fix the DCO? If you added / removed commits in the meantime the command is proably different.

Fixed and thanks for the quick reply!

File: lib/private/Setup.php [hunk 1]
```diff
@@ -573,7 +573,7 @@ public static function protectDataDirectory() {
 		$content .= "    <IfModule mod_authz_host.c>\n";
 		$content .= "      Order Allow,Deny\n";
 		$content .= "      Deny from all\n";
-		$content .= "    <IifModule>\n";
+		$content .= "    <IfModule>\n";
```
Comment (MichaIng) [inline lib/private/Setup.php]: Many thanks, my fault, but it must be: `</IfModule>\n` closing the directive above. 

Passed tests most likely since it is only pared on Apache2.2

**Review by MichaIng — CHANGES_REQUESTED** [review]

File: lib/private/Setup.php (hunk 1 above)
Comment (Simounet) [reply lib/private/Setup.php]: I'm using Apache2.4 and get the parsing error.

Comment (MichaIng) [reply lib/private/Setup.php]: @Simounet
Ah you're right, in my case it's because data dir is outside the webroot.

**Comment by MichaIng** [comment]
The `.htaccess` in config btw was correct: https://github.com/nextcloud/server/blob/master/config/.htaccess#L17

**Comment by MichaIng** [comment]
@Simounet 
 Would you mind to apply the requested change, as we should have this fix ready for next minor release. I hope it's clear that the buggy tag must be a closing tag.

**Comment by Simounet** [comment]
Hello @MichaIng ,
Sorry for the late reply. I just fixed it.

**Comment by kesselb** [comment]
cc @rullzer would be nice for 18.0.1.

**Review by MichaIng — APPROVED** [review]

**Comment by MichaIng** [comment]
:rocket:
