### PR TITLE
fix: return 204 instead of 404

### LINKED ISSUE #3021: Lot of 404 errors / CrowdSec ban me
### Describe the bug

I also have a lot of 404 errors. I think it's related to the lost avatar of my contact
CrowdSec banned me because of this

### Steps to reproduce

1. Go to Contacts App
2. Scroll Contacts view
3. See Console, lot of 404 error

### Expected behavior

Do not have a 404 error when viewing my contacts

### Actual behavior

404 error

image

### Contact version

4.2.2

### Operating system

OMV - Debian 11

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database

MariaDB

### Additional info

Server : 
    Docker [Linuxserver php8](https://github.com/linuxserver/docker-nextcloud/tree/php8)
    Nextcloud : 24.0.6
    Contacts : 4.2.2

Desktop : 
    OS: Windows 10
    Browser : Firefox 105

My reverse Proxy : 
```
192.168.2.42 - - [07/Oct/2022:00:01:18 +0200] "GET /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/14FF37C0-C83C-4CB5-9091-269A9337D362.vcf?photo HTTP/2.0" 404 20 "https://cloud.ndd/apps/contacts/Tous%20les%20contacts/36316526-0bb4-46cf-9bbb-573bec6af646~bvf-panilor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0"
192.168.2.42 - - [07/Oct/2022:00:01:18 +0200] "GET /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/A8BDF343-8283-45EA-93BE-320EC7FC8113.vcf?photo HTTP/2.0" 404 20 "https://cloud.ndd/apps/contacts/Tous%20les%20contacts/36316526-0bb4-46cf-9bbb-573bec6af646~bvf-panilor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0"
192.168.2.42 - - [07/Oct/2022:00:01:18 +0200] "GET /remote.php/dav/addressbooks/users/Evoluzione/commerces/FFB7317A-EECE-4A1E-A231-76497C232589.vcf?photo HTTP/2.0" 404 20 "https://cloud.ndd/apps/contacts/Tous%20les%20contacts/36316526-0bb4-46cf-9bbb-573bec6af646~bvf-panilor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0"
192.168.2.42 - - [07/Oct/2022:00:01:19 +0200] "GET /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/41DC030F-6573-4888-8120-7FD52ED7C3A8.vcf?photo HTTP/2.0" 404 20 "https://cloud.ndd/apps/contacts/Tous%20les%20contacts/36316526-0bb4-46cf-9bbb-573bec6af646~bvf-panilor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0"
192.168.2.42 - - [07/Oct/2022:00:01:19 +0200] "GET /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/CE387EA7-2C4D-4F99-92B6-3FFB316BF985.vcf?photo HTTP/2.0" 404 20 "https://cloud.ndd/apps/contacts/Tous%20les%20contacts/36316526-0bb4-46cf-9bbb-573bec6af646~bvf-panilor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0"
192.168.2.42 - - [07/Oct/2022:00:01:19 +0200] "GET /remote.php/dav/addressbooks/users/Evoluzione/connaissances/9DA090D8-D40E-406C-B8D5-E6D73B2FDA03.vcf?photo HTTP/2.0" 404 20 "https://cloud.ndd/apps/contacts/Tous%20les%20contacts/36316526-0bb4-46cf-9bbb-573bec6af646~bvf-panilor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0"
192.168.2.42 - - [07/Oct/2022:00:01:19 +0200] "GET /remote.php/dav/addressbooks/users/Evoluzione/autres/FCA2429B-3819-455C-BB04-002980D4C7EE.vcf?photo HTTP/2.0" 404 20 "https://cloud.ndd/apps/contacts/Tous%20les%20contacts/36316526-0bb4-46cf-9bbb-573bec6af646~bvf-panilor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0"
192.168.2.42 - - [07/Oct/2022:00:01:20 +0200] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 304 0 "https://cloud.ndd/apps/contacts/Tous%20les%20contacts/36316526-0bb4-46cf-9bbb-573bec6af646~bvf-panilor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0"
```

Console , Firefox 105 : 

```
Proxying an event bus of version 2.1.1 with 1.3.0 index.es.js:2337:14
JQMIGRATE: Migrate is installed, version 3.4.0 core-common.js:2:5520444
Proxying an event bus of version 2.1.1 with 1.3.0 index.es.js:2337:14
[DEBUG] unified-search: Unified Search initialized with the following providers 
Object { 0: {…}, 1: {…}, 2: {…}, 3: {…}, 4: {…}, 5: {…}, 6: {…}, 7: {…}, 8: {…}, 9: {…}, … }
core-common.js:2:482560
Proxying an event bus of version 2.1.1 with 1.3.0 contacts-main.js:2:29456
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 3 core-main.js:2:67484
Initial state loaded defaultProfileState HOME contacts-main.js:2:4847563
Initial state loaded localesState 
Array(750) [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]
contacts-main.js:2:4847621
OCA.Search is deprecated. Please use the unified search API instead core-main.js:2:13191
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. core-main.js:2:67484
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 core-main.js:2:67484
Proxying an event bus of version 2.1.1 with 1.3.0 notifications-main.js:2:29334
Loading theming data for notification bell styling notifications-main.js:2:1200310
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. core-main.js:2:67484
Registering notifications container as a menu notifications-main.js:2:1200548
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 core-main.js:2:67484
Notifications permissions granted notifications-main.js:2:1205484
Polling interval updated to 30000 App.vue:355
Started background fetcher as session_keepalive is enabled notifications-main.js:2:1201985
Proxying an event bus of version 2.1.1 with 1.3.0 index.es.js:2337:14
session heartbeat polling started core-main.js:2:54335
Cette page utilise la propriété non standard « zoom ». Envisagez d’utiliser calc() dans les valeurs des propriétés pertinentes ou utilisez « transform » avec « transform-origin: 0 0 ». menu.js:99:26
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. core-main.js:2:67484
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 5 core-main.js:2:67484
Got notification data notifications-main.js:2:1204049
Polling interval updated to 30000 App.vue:355
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 67 core-main.js:2:67484
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/commerces/D35F7124-D130-44FD-A696-1528433D8E81.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/amis/14D7F41C-3220-4872-B47C-EA49D84B1849.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/amis/F5775E3E-4542-4C32-9F97-9DE1DDEE76E9.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/connaissances/385BF09B-7AEC-4720-96BD-B36945924612.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/304EB99D-62D3-4974-A6F5-04DC47659F01.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/qnap/EF65273A-3736-48C8-914A-A6434DE5BFAC.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/812F7683-333D-4EDF-B792-B4F9EC9710F2.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/E89A7343-B956-40BD-BFA8-7630186F6906.vcf?photo ListItemIcon.js:2:7798
Masonry reflow contacts-main.js:2:4974060
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/6D18E6D3-6E5E-4D17-9A11-669BB0ED25EF.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/mdecine/0BC3E162-E506-4A17-B394-E84DF1C1796C.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/008882E3-9537-4765-A638-32AF57801F8F.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/commerces/0051CBCC-DCB1-4B3A-BF64-F2F8828F0079.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/1E71B851-F0EF-4089-8BBD-26E23683912F.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/A74CD824-DC83-4A01-82D4-A5746CF48033.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/mdecine/5588DC57-EFF5-402F-B8DD-272E037F1045.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/mdecine/81A5EF0B-2F7B-41CF-8815-C3A38D972056.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/mdecine/0A2991AF-0935-46D2-99F9-46F79BA67860.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/816ABA2B-F03A-414D-8C56-173F83A64222.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/amis/8D1E0BD9-55D4-4C65-A187-21D79E264A2C.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/8A7D7DFE-494A-4E10-963D-96498291E526.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/commerces/FC3CD999-3795-4056-88D6-19E3B55AC1CE.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/68EA7BAC-DD3B-4D27-BFDC-F73CAE290E94.vcf?photo ListItemIcon.js:2:7798
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/42FF1610-0663-46E3-B626-FFE42199EB6A.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/connaissances/006F5CE3-3128-457D-AF1B-B1E6EE29E941.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/CDB388D6-1049-4D44-8A9C-1FE7C0DFAE30.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/commerces/87BEC01C-163D-40B5-99E2-9F82B4324487.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/DD204B41-3EFA-4210-AD53-739369F63E2C.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/qnap/EF65273A-3736-48C8-914A-A6434DE5BFAC.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/E89A7343-B956-40BD-BFA8-7630186F6906.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/mdecine/0BC3E162-E506-4A17-B394-E84DF1C1796C.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/008882E3-9537-4765-A638-32AF57801F8F.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/commerces/0051CBCC-DCB1-4B3A-BF64-F2F8828F0079.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/1E71B851-F0EF-4089-8BBD-26E23683912F.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/A74CD824-DC83-4A01-82D4-A5746CF48033.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/z-app-generated--contactsinteraction--recent/78?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/mdecine/5588DC57-EFF5-402F-B8DD-272E037F1045.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/mdecine/81A5EF0B-2F7B-41CF-8815-C3A38D972056.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/mdecine/0A2991AF-0935-46D2-99F9-46F79BA67860.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/816ABA2B-F03A-414D-8C56-173F83A64222.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/amis/8D1E0BD9-55D4-4C65-A187-21D79E264A2C.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/8A7D7DFE-494A-4E10-963D-96498291E526.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/commerces/FC3CD999-3795-4056-88D6-19E3B55AC1CE.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/68EA7BAC-DD3B-4D27-BFDC-F73CAE290E94.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/mdecine/5588DC57-EFF5-402F-B8DD-272E037F1045.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/816ABA2B-F03A-414D-8C56-173F83A64222.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/amis/8D1E0BD9-55D4-4C65-A187-21D79E264A2C.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/8A7D7DFE-494A-4E10-963D-96498291E526.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/mdecine/81A5EF0B-2F7B-41CF-8815-C3A38D972056.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/mdecine/0A2991AF-0935-46D2-99F9-46F79BA67860.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/commerces/FC3CD999-3795-4056-88D6-19E3B55AC1CE.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/68EA7BAC-DD3B-4D27-BFDC-F73CAE290E94.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/42FF1610-0663-46E3-B626-FFE42199EB6A.vcf?photo 2 ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/z-app-generated--contactsinteraction--recent/78?photo 2 ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/connaissances/006F5CE3-3128-457D-AF1B-B1E6EE29E941.vcf?photo 2 ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/CDB388D6-1049-4D44-8A9C-1FE7C0DFAE30.vcf?photo 2 ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/commerces/87BEC01C-163D-40B5-99E2-9F82B4324487.vcf?photo 2 ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/DD204B41-3EFA-4210-AD53-739369F63E2C.vcf?photo 2 ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/1B50EFA8-9043-46FF-AD1F-FF53BA7D32C6.vcf?photo 2 ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/E2A65BCC-F178-4BB4-BC42-653E3979FC17.vcf?photo 2 ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/700EF9E9-6C0E-41DB-AD72-2538C8075863.vcf?photo 2 ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/connaissances/0AED4085-DF8E-40C8-B986-DA6EBF6F25EF.vcf?photo 2 ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/commerces/375484DD-C38D-41A0-8C55-DD15EB5CDD51.vcf?photo 2 ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/CFC7F5AE-DF49-419B-A30C-F2CD512886CF.vcf?photo 2 ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/z-app-generated--contactsinteraction--recent/79?photo 2 ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/connaissances/F1CB6149-5350-4D0A-8475-56452CC11F14.vcf?photo 2 ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/8D6F3333-278E-4368-BE98-F53FC5B71611.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/E182B964-901A-4F1C-8493-DFED198D4C24.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/5F50A0CF-A481-4D8A-8C57-0A7D2759F080.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/CBD8BE25-8C9D-435C-9AF3-CE60E1D88329.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/EBDA47C9-A729-4D5F-944B-5FA769CFE541.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/E88173B2-1167-4CBC-86FC-8F45E23E65D4.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/commerces/642997F8-7AE6-4407-A579-2D9D383F68D4.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/2ac4af35-6b70-4f1d-b021-1290797f3a27.vcf?photo ListItemIcon.js:2:7798
GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/honor-8/1B50EFA8-9043-46FF-AD1F-FF53BA7D32C6.vcf?photo
[HTTP/2 404 Not Found 73ms]

	
GET
	https://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/honor-8/1B50EFA8-9043-46FF-AD1F-FF53BA7D32C6.vcf?photo=
État
404
Not Found
VersionHTTP/2
Transfert994 o (taille 0 o)
Politique de référentsame-origin
Priorité de la requêteLow

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/E2A65BCC-F178-4BB4-BC42-653E3979FC17.vcf?photo
[HTTP/2 404 Not Found 124ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/700EF9E9-6C0E-41DB-AD72-2538C8075863.vcf?photo
[HTTP/2 404 Not Found 263ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/connaissances/0AED4085-DF8E-40C8-B986-DA6EBF6F25EF.vcf?photo
[HTTP/2 404 Not Found 90ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/commerces/375484DD-C38D-41A0-8C55-DD15EB5CDD51.vcf?photo
[HTTP/2 404 Not Found 133ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/connaissances/F1CB6149-5350-4D0A-8475-56452CC11F14.vcf?photo
[HTTP/2 404 Not Found 155ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/z-app-generated--contactsinteraction--recent/79?photo
[HTTP/2 501 Not Implemented 222ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/CFC7F5AE-DF49-419B-A30C-F2CD512886CF.vcf?photo
[HTTP/2 404 Not Found 178ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/honor-8/8D6F3333-278E-4368-BE98-F53FC5B71611.vcf?photo
[HTTP/2 404 Not Found 201ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/autres/5F50A0CF-A481-4D8A-8C57-0A7D2759F080.vcf?photo
[HTTP/2 404 Not Found 261ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/autres/E182B964-901A-4F1C-8493-DFED198D4C24.vcf?photo
[HTTP/2 404 Not Found 262ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/honor-8/CBD8BE25-8C9D-435C-9AF3-CE60E1D88329.vcf?photo
[HTTP/2 404 Not Found 273ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/autres/E88173B2-1167-4CBC-86FC-8F45E23E65D4.vcf?photo
[HTTP/2 404 Not Found 306ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/honor-8/EBDA47C9-A729-4D5F-944B-5FA769CFE541.vcf?photo
[HTTP/2 404 Not Found 292ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/commerces/642997F8-7AE6-4407-A579-2D9D383F68D4.vcf?photo
[HTTP/2 404 Not Found 332ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/2ac4af35-6b70-4f1d-b021-1290797f3a27.vcf?photo
[HTTP/2 404 Not Found 311ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/mdecine/6A96216D-66BA-404A-AA8C-469ED524C355.vcf?photo
[HTTP/2 404 Not Found 350ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/509D2C57-7B9D-4EDF-9748-502F9694DB8F.vcf?photo
[HTTP/2 404 Not Found 375ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/connaissances/A03D1C72-A111-4CB7-863D-1A084F17698E.vcf?photo
[HTTP/2 404 Not Found 361ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/A7504ADC-F39C-41D5-BB13-89235ECE0E5D.vcf?photo
[HTTP/2 404 Not Found 409ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/14FF37C0-C83C-4CB5-9091-269A9337D362.vcf?photo
[HTTP/2 404 Not Found 438ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/A8BDF343-8283-45EA-93BE-320EC7FC8113.vcf?photo
[HTTP/2 404 Not Found 468ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/autres/FCA2429B-3819-455C-BB04-002980D4C7EE.vcf?photo
[HTTP/2 404 Not Found 490ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/commerces/FFB7317A-EECE-4A1E-A231-76497C232589.vcf?photo
[HTTP/2 404 Not Found 480ms]

Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/1B50EFA8-9043-46FF-AD1F-FF53BA7D32C6.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/connaissances/0AED4085-DF8E-40C8-B986-DA6EBF6F25EF.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/E2A65BCC-F178-4BB4-BC42-653E3979FC17.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/commerces/375484DD-C38D-41A0-8C55-DD15EB5CDD51.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/connaissances/F1CB6149-5350-4D0A-8475-56452CC11F14.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/CFC7F5AE-DF49-419B-A30C-F2CD512886CF.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/8D6F3333-278E-4368-BE98-F53FC5B71611.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/z-app-generated--contactsinteraction--recent/79?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/700EF9E9-6C0E-41DB-AD72-2538C8075863.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/E182B964-901A-4F1C-8493-DFED198D4C24.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/5F50A0CF-A481-4D8A-8C57-0A7D2759F080.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/CBD8BE25-8C9D-435C-9AF3-CE60E1D88329.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/EBDA47C9-A729-4D5F-944B-5FA769CFE541.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/E88173B2-1167-4CBC-86FC-8F45E23E65D4.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/2ac4af35-6b70-4f1d-b021-1290797f3a27.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/commerces/642997F8-7AE6-4407-A579-2D9D383F68D4.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/mdecine/6A96216D-66BA-404A-AA8C-469ED524C355.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/connaissances/A03D1C72-A111-4CB7-863D-1A084F17698E.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/509D2C57-7B9D-4EDF-9748-502F9694DB8F.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/A7504ADC-F39C-41D5-BB13-89235ECE0E5D.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/14FF37C0-C83C-4CB5-9091-269A9337D362.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/A8BDF343-8283-45EA-93BE-320EC7FC8113.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/commerces/FFB7317A-EECE-4A1E-A231-76497C232589.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/FCA2429B-3819-455C-BB04-002980D4C7EE.vcf?photo ListItemIcon.js:2:7798
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/z-app-generated--contactsinteraction--recent/78?photo
[HTTP/2 501 Not Implemented 254ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/honor-8/68EA7BAC-DD3B-4D27-BFDC-F73CAE290E94.vcf?photo
[HTTP/2 404 Not Found 198ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/42FF1610-0663-46E3-B626-FFE42199EB6A.vcf?photo
[HTTP/2 404 Not Found 353ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/connaissances/006F5CE3-3128-457D-AF1B-B1E6EE29E941.vcf?photo
[HTTP/2 404 Not Found 352ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/autres/CDB388D6-1049-4D44-8A9C-1FE7C0DFAE30.vcf?photo
[HTTP/2 404 Not Found 349ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/commerces/87BEC01C-163D-40B5-99E2-9F82B4324487.vcf?photo
[HTTP/2 404 Not Found 346ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/DD204B41-3EFA-4210-AD53-739369F63E2C.vcf?photo
[HTTP/2 404 Not Found 345ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/z-app-generated--contactsinteraction--recent/79?photo
[HTTP/2 501 Not Implemented 490ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/honor-8/1B50EFA8-9043-46FF-AD1F-FF53BA7D32C6.vcf?photo
[HTTP/2 404 Not Found 342ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/E2A65BCC-F178-4BB4-BC42-653E3979FC17.vcf?photo
[HTTP/2 404 Not Found 493ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/connaissances/0AED4085-DF8E-40C8-B986-DA6EBF6F25EF.vcf?photo
[HTTP/2 404 Not Found 494ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/700EF9E9-6C0E-41DB-AD72-2538C8075863.vcf?photo
[HTTP/2 404 Not Found 493ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/commerces/375484DD-C38D-41A0-8C55-DD15EB5CDD51.vcf?photo
[HTTP/2 404 Not Found 494ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/connaissances/F1CB6149-5350-4D0A-8475-56452CC11F14.vcf?photo
[HTTP/2 404 Not Found 493ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/CFC7F5AE-DF49-419B-A30C-F2CD512886CF.vcf?photo
[HTTP/2 404 Not Found 493ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/honor-8/8D6F3333-278E-4368-BE98-F53FC5B71611.vcf?photo
[HTTP/2 404 Not Found 615ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/autres/5F50A0CF-A481-4D8A-8C57-0A7D2759F080.vcf?photo
[HTTP/2 404 Not Found 614ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/autres/E182B964-901A-4F1C-8493-DFED198D4C24.vcf?photo
[HTTP/2 404 Not Found 615ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/honor-8/CBD8BE25-8C9D-435C-9AF3-CE60E1D88329.vcf?photo
[HTTP/2 404 Not Found 614ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/honor-8/EBDA47C9-A729-4D5F-944B-5FA769CFE541.vcf?photo
[HTTP/2 404 Not Found 634ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/autres/E88173B2-1167-4CBC-86FC-8F45E23E65D4.vcf?photo
[HTTP/2 404 Not Found 642ms]

GEThttps://cloud.ndd/remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/2ac4af35-6b70-4f1d-b021-1290797f3a27.vcf?photo
[HTTP/2 404 Not Found 624ms]

Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/68EA7BAC-DD3B-4D27-BFDC-F73CAE290E94.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/z-app-generated--contactsinteraction--recent/78?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/connaissances/006F5CE3-3128-457D-AF1B-B1E6EE29E941.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/42FF1610-0663-46E3-B626-FFE42199EB6A.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/CDB388D6-1049-4D44-8A9C-1FE7C0DFAE30.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/commerces/87BEC01C-163D-40B5-99E2-9F82B4324487.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/DD204B41-3EFA-4210-AD53-739369F63E2C.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/1B50EFA8-9043-46FF-AD1F-FF53BA7D32C6.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/z-app-generated--contactsinteraction--recent/79?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/E2A65BCC-F178-4BB4-BC42-653E3979FC17.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/700EF9E9-6C0E-41DB-AD72-2538C8075863.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/connaissances/0AED4085-DF8E-40C8-B986-DA6EBF6F25EF.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/commerces/375484DD-C38D-41A0-8C55-DD15EB5CDD51.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/connaissances/F1CB6149-5350-4D0A-8475-56452CC11F14.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/bvf-panilor/CFC7F5AE-DF49-419B-A30C-F2CD512886CF.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/8D6F3333-278E-4368-BE98-F53FC5B71611.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/E182B964-901A-4F1C-8493-DFED198D4C24.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/5F50A0CF-A481-4D8A-8C57-0A7D2759F080.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/CBD8BE25-8C9D-435C-9AF3-CE60E1D88329.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/samsung-a6/2ac4af35-6b70-4f1d-b021-1290797f3a27.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/honor-8/EBDA47C9-A729-4D5F-944B-5FA769CFE541.vcf?photo ListItemIcon.js:2:7798
Invalid avatar url /remote.php/dav/addressbooks/users/Evoluzione/autres/E88173B2-1167-4CBC-86FC-8F45E23E65D4.vcf?photo ListItemIcon.js:2:7798
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
No new notification data received App.vue:323
Polling interval updated to 30000 App.vue:355
```

### PR DESCRIPTION
**Pull request by SebastianKrupinski**
* Resolves: https://github.com/nextcloud/contacts/issues/3021
* Related: https://github.com/nextcloud/contacts/pull/4249

## Summary
Changed status return to 204 "no content" instead of 404 when a photo does not exist

204 make more sense as it signals that there was no image, instead that a error occurred.

## Checklist
- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by hamza221 — APPROVED** [review]

**Comment by arnowelzel** [comment]
Eventhough this fix solves the issue of having a lot of 404 - but the root cause is still in place: instead of checking, if there is an image at all and not requesting it, the contacts app still tries to load an image for each contact. There will still be a lot of exceptions which trigger the 204-response. It would be better, if a contact had a flag, that there is no image, so the frontend won't even try to load it.

File: apps/dav/lib/CardDAV/ImageExportPlugin.php [hunk 1]
```diff
@@ -90,7 +90,7 @@ public function httpGet(RequestInterface $request, ResponseInterface $response)
 
 			$response->setBody($file->getContent());
 		} catch (NotFoundException $e) {
-			$response->setStatus(404);
+			$response->setStatus(204); // 204 No Content
```
Comment (kesselb) [inline apps/dav/lib/CardDAV/ImageExportPlugin.php:93]:
```suggestion
			$response->setStatus(\OCP\AppFramework\Http::STATUS_NO_CONTENT);
```

Please consider to import the class.

File: apps/dav/tests/unit/CardDAV/ImageExportPluginTest.php [hunk 2]
```diff
@@ -171,7 +171,7 @@ public function testCard($size, $photo): void {
 				->willThrowException(new NotFoundException());
 			$this->response->expects($this->once())
 				->method('setStatus')
-				->with(404);
+				->with(204);
```
Comment (kesselb) [inline apps/dav/tests/unit/CardDAV/ImageExportPluginTest.php:174]:
```suggestion
				->with(\OCP\AppFramework\Http::STATUS_NO_CONTENT);
```

**Comment by kesselb** [comment]
We rejected similar "don't use 404 for fail2ban" requests in the past. 
For example: https://github.com/nextcloud/server/issues/26793.

---

I think using 204 is a good choice. The request was successful, there's just no content to return. 

---

As written by Arno, changing the response code is a workaround for those fail2ban users. The underlying problem is that those requests are happening. The response for the address book contains a has-photo attribute (empty/1).  

```xml
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:card="urn:ietf:params:xml:ns:carddav">
	<d:response>
		<d:href>
			/remote.php/dav/addressbooks/users/admin/contacts/F1D36433-6CC3-48B9-942F-8E7E12A69D4E.vcf
		</d:href>
		<d:propstat>
			<d:prop>
				<d:getetag>&quot;4e748fcff71af1c2a024fb19b9a3812e&quot;</d:getetag>
				<d:getcontenttype>text/vcard; charset=utf-8</d:getcontenttype>
				<d:resourcetype/>
				<card:address-data>BEGIN:VCARD&#13;
					VERSION:3.0&#13;
					PRODID:-//Sabre//Sabre VObject 4.5.6//EN&#13;
					UID:58236d02-66e5-4374-bdaa-5d4f04ce29f4&#13;
					FN:Test 1000&#13;
					EMAIL;TYPE=HOME:&#13;
					END:VCARD&#13;
				</card:address-data>
				<x1:has-photo xmlns:x1="http://nextcloud.com/ns"></x1:has-photo>
			</d:prop>
			<d:status>HTTP/1.1 200 OK</d:status>
		</d:propstat>
	</d:response>
</d:multistatus>
```

The following change for contacts should take the hasPhotos property into account:

```diff
Index: src/models/contact.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/models/contact.js b/src/models/contact.js
--- a/src/models/contact.js	(revision b91012f60c1b011a3ce173c8613b05a221646ae4)
+++ b/src/models/contact.js	(date 1734087428669)
@@ -119,6 +119,16 @@
 		return ''
 	}
 
+	/**
+	 * Return whether a photo is available
+	 *
+	 * @readonly
+	 * @memberof Contact
+	 */
+	get hasPhoto() {
+		return this.dav && this.dav.hasphoto
+	}
+
 	/**
 	 * Return the version
 	 *
Index: src/components/ContactsList/ContactsListItem.vue
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/components/ContactsList/ContactsListItem.vue b/src/components/ContactsList/ContactsListItem.vue
--- a/src/components/ContactsList/ContactsListItem.vue	(revision b91012f60c1b011a3ce173c8613b05a221646ae4)
+++ b/src/components/ContactsList/ContactsListItem.vue	(date 1734087333973)
@@ -141,7 +141,7 @@
 					return
 				}
 				this.avatarUrl = photoUrl
-			} else if (this.source.url) {
+			} else if (this.source.hasPhoto && this.source.url) {
 				this.avatarUrl = `${this.source.url}?photo`
 			}
 		},
```

File: apps/dav/lib/CardDAV/ImageExportPlugin.php (hunk 1 above)
Comment (kesselb) [reply apps/dav/lib/CardDAV/ImageExportPlugin.php:93]: Why would it be a problem to use`\OCP\AppFramework\Http`?

- The status code is the same
- The http class is from our app framework and not specific to SabreDAV or Symfony

**Comment by SebastianKrupinski** [comment]
> The following change for contacts should take the hasPhotos property into account:
 
Sure, we can add this also, makes sense.

**Review by oleksandr-nc — APPROVED** [review]
really good changes

**Review by kesselb — APPROVED** [review]

**Comment by SebastianKrupinski** [comment]
> > /backport to stable28
> 
> See [Wiki: Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule). 28 has reached EOL.

No worries, ill cancel the 28 backport.

FYI, a EOL date not just the month would be a good idea.

image

This can be interpreted as Dec 31st instead of Dec 1st
