### PR TITLE
fix(S3): Use original folder size during copy

### LINKED ISSUE #51916: [Bug]: Object storage (S3) folder on duplication has 0 KB folder size
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Duplication/copy of a non-zero sized folder with any subfolders results in a folder whose size is reported as 0 KB. All the subfolders of this new folder are also 0 KB in size, but the files are reported as correctly sized.
This problem only happens with the folders with subfolders, not with folders with only files or just files.
Object storage was used in this case with S3 (MinIO) as the provider.

configuration used:
```php
'objectstore' => [
        'class' => '\\OC\\Files\\ObjectStore\\S3',
        'arguments' => [
                'bucket' => 'store-nc',
                'hostname' => 'minio',
                'key' => 'xxx',
                'secret' => 'xxx',
                'port' => 9000,
                'use_ssl' => false,
                'use_path_style' => true,
        ],
],
```

### Steps to reproduce

1. Upload a folder with at least one subfolder and some files
2. Copy the folder in the same directory

### Expected behavior

Both the original and the "original (copy)" folders have the same size, but only the original folder has the correct size reported.

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by artonge**
This prevents having copied folders with a wrongly set size of 0KB.

- Fix https://github.com/nextcloud/server/issues/51916

~~Not sure about the `handleCopiesAsOwned` part, but I kept it from `copyFile` to preserve the same behaviour. It was introduced in https://github.com/nextcloud/server/pull/41565. Maybe @susnux you can judge whether it makes sense or not.~~ Validated.

### CODE REVIEW

File: lib/private/Files/ObjectStore/ObjectStoreStorage.php [hunk 1]
```diff
@@ -731,6 +731,27 @@ private function copyFile(ICacheEntry $sourceEntry, string $to) {
...
+		$cache = $this->getCache();
+
+		if (!$cache instanceof Cache) {
+			throw new \Exception('Invalid source cache for object store copy');
+		}
+
+		$targetId = $cache->copyFromCache($cache, $sourceEntry, $to);
+
+		try {
+			if ($this->handleCopiesAsOwned) {
```
Comment (susnux) [inline lib/private/Files/ObjectStore/ObjectStoreStorage.php:744]: yes makes sense.
(I think the plan was to unify on one behavior, so this one should become the default (either in 32 or later)).

File: lib/private/Files/ObjectStore/ObjectStoreStorage.php [hunk 2]
```diff
@@ -731,6 +731,27 @@ private function copyFile(ICacheEntry $sourceEntry, string $to) {
...
 	}
 
+	private function copyFolder(ICacheEntry $sourceEntry, string $to) {
+		$cache = $this->getCache();
+
+		if (!$cache instanceof Cache) {
+			throw new \Exception('Invalid source cache for object store copy');
+		}
+
+		$targetId = $cache->copyFromCache($cache, $sourceEntry, $to);
```
Comment (icewind1991) [inline lib/private/Files/ObjectStore/ObjectStoreStorage.php:741]: this does a recursive copy, which would conflict with the recursion from `copyInner`

**Comment by DaphneMuller** [comment]
@artonge anything that we should be doing here to follow up on it?

**Comment by artonge** [comment]
> @artonge anything that we should be doing here to follow up on it?

No, just prioritizing :)

**Comment by artonge** [comment]
> The least-invasive change would probably be to pass the needed metadata to `mkdir`
> 
> Alternatively you can first do the recursive cache copy, and then do the object copy recursively without changing the cache. (care has to be taken than to not have the db and object store desync if the object copy fails then)

@icewind1991 I ended up keeping the `mkdir` as is, and updating its size right after.

**Comment by DaphneMuller** [comment]
@artonge @icewind1991 any chance this can be merged soon?

**Comment by icewind1991** [comment]
> @icewind1991 I ended up keeping the `mkdir` as is, and updating its size right after.

Pushed a change to do the size in the `mkdir`, there is no need to do 3 queries to the filecache when 1 can suffice.

Also pushed a test to ensure this doesn't regress.

**Review by icewind1991 — APPROVED** [review]

**Review by come-nc — APPROVED** [review]
