### PR TITLE
fix ftp external storage with filezilla server

### LINKED ISSUE #31510: [Bug]: after upgrade NC to 23.0.2 app external storage support stops working
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After upgrade to 23.0.2 app external storage support (FTP) stops working and no folders / files are shown in the files panel.
Problem disappears after deactivating the application.

### Steps to reproduce

1. Upgrade NC to 23.0.2
2. Log in to panel
3. Go to Files

### Expected behavior

Files and folders should be displayed.

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***",
        "10.71.71.100"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "23.0.2.1",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "htaccess.RewriteBase": "\/",
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "trashbin_retention_obligation": "auto, 30",
    "filelocking.enabled": "true",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "dbindex": 0,
        "password": "***REMOVED SENSITIVE VALUE***",
        "timeout": 1.5
    },
    "log_type": "file",
    "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
    "loglevel": 1,
    "logtimezone": "Europe\/Warsaw",
    "theme": "",
    "default_phone_region": "PL",
    "enable_previews": true,
    "simpleSignUpLink.shown": false,
    "skeletondirectory": "",
    "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
    "allow_local_remote_servers": true,
    "maintenance": false,
    "versions_retention_obligation": "auto, 60",
    "lost_password_link": "disabled",
    "app_install_overwrite": [
        "issuetemplate"
    ]
}
```

### List of activated Apps

```shell
- accessibility: 1.9.0
 - activity: 2.15.0
 - admin_audit: 1.13.0
 - bruteforcesettings: 2.3.0
 - circles: 23.0.1
 - cloud_federation_api: 1.6.0
 - comments: 1.13.0
 - contactsinteraction: 1.4.0
 - dashboard: 7.3.0
 - dav: 1.21.0
 - federatedfilesharing: 1.13.0
 - federation: 1.13.0
 - files: 1.18.0
 - files_antivirus: 3.2.2
 - files_external: 1.15.0
 - files_pdfviewer: 2.4.0
 - files_rightclick: 1.2.0
 - files_sharing: 1.15.0
 - files_trashbin: 1.13.0
 - files_versions: 1.16.0
 - files_videoplayer: 1.12.0
 - firstrunwizard: 2.12.0
 - issuetemplate: 0.7.0
 - logreader: 2.8.0
 - lookup_server_connector: 1.11.0
 - nextcloud_announcements: 1.12.0
 - notifications: 2.11.1
 - oauth2: 1.11.0
 - onlyoffice: 7.3.2
 - password_policy: 1.13.0
 - photos: 1.5.0
 - privacy: 1.7.0
 - provisioning_api: 1.13.0
 - recommendations: 1.2.0
 - serverinfo: 1.13.0
 - settings: 1.5.0
 - sharebymail: 1.13.0
 - survey_client: 1.11.0
 - systemtags: 1.13.0
 - text: 3.4.0
 - theming: 1.14.0
 - twofactor_backupcodes: 1.12.0
 - twofactor_totp: 6.2.0
 - updatenotification: 1.13.0
 - user_ldap: 1.13.1
 - user_status: 1.3.1
 - viewer: 1.7.0
 - weather_status: 1.3.0
 - workflowengine: 2.5.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"Ocx2qv93MhCkEsdkFCZe","level":3,"time":"2022-03-07T13:12:20+01:00","remoteAddr":"37.30.19.172","user":"admin","app":"index","method":"GET","url":"/apps/recommendations/api/recommendations","message":"Call to a member function getTimestamp() on bool in file '/var/www/nextcloud/httpdocs/apps/files_external/lib/Lib/Storage/FTP.php' line 358","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36","version":"23.0.2.1","exception":{"Exception":"Exception","Message":"Call to a member function getTimestamp() on bool in file '/var/www/nextcloud/httpdocs/apps/files_external/lib/Lib/Storage/FTP.php' line 358","Code":0,"Trace":[{"file":"/var/www/nextcloud/httpdocs/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/httpdocs/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/httpdocs/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/httpdocs/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/httpdocs/lib/private/AppFramework/Http/Dispatcher.php","Line":158,"Previous":{"Exception":"Error","Message":"Call to a member function getTimestamp() on bool","Code":0,"Trace":[{"file":"/var/www/nextcloud/httpdocs/lib/private/Files/Storage/Wrapper/PermissionsMask.php","line":157,"function":"getDirectoryContent","class":"OCA\\Files_External\\Lib\\Storage\\FTP","type":"->"},{"function":"getDirectoryContent","class":"OC\\Files\\Storage\\Wrapper\\PermissionsMask","type":"->"},{"file":"/var/www/nextcloud/httpdocs/lib/private/Files/Cache/Scanner.php","line":410,"function":"iterator_to_array"},{"file":"/var/www/nextcloud/httpdocs/lib/private/Files/Cache/Scanner.php","line":390,"function":"handleChildren","class":"OC\\Files\\Cache\\Scanner","type":"->"},{"file":"/var/www/nextcloud/httpdocs/lib/private/Files/Cache/Scanner.php","line":342,"function":"scanChildren","class":"OC\\Files\\Cache\\Scanner","type":"->"},{"file":"/var/www/nextcloud/httpdocs/lib/private/Files/View.php","line":1349,"function":"scan","class":"OC\\Files\\Cache\\Scanner","type":"->"},{"file":"/var/www/nextcloud/httpdocs/lib/private/Files/View.php","line":1393,"function":"getCacheEntry","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/httpdocs/lib/private/Files/Node/Root.php","line":200,"function":"getFileInfo","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/httpdocs/lib/private/Files/Node/Node.php","line":286,"function":"get","class":"OC\\Files\\Node\\Root","type":"->"},{"file":"/var/www/nextcloud/httpdocs/apps/recommendations/lib/Service/RecentlyEditedFilesSource.php","line":57,"function":"getParent","class":"OC\\Files\\Node\\Node","type":"->"},{"function":"OCA\\Recommendations\\Service\\{closure}","class":"OCA\\Recommendations\\Service\\RecentlyEditedFilesSource","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/httpdocs/apps/recommendations/lib/Service/RecentlyEditedFilesSource.php","line":65,"function":"array_map"},{"file":"/var/www/nextcloud/httpdocs/apps/recommendations/lib/Service/RecommendationService.php","line":90,"function":"getMostRecentRecommendation","class":"OCA\\Recommendations\\Service\\RecentlyEditedFilesSource","type":"->"},{"function":"OCA\\Recommendations\\Service\\{closure}","class":"OCA\\Recommendations\\Service\\RecommendationService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/httpdocs/apps/recommendations/lib/Service/RecommendationService.php","line":91,"function":"array_reduce"},{"file":"/var/www/nextcloud/httpdocs/apps/recommendations/lib/Controller/RecommendationController.php","line":70,"function":"getRecommendations","class":"OCA\\Recommendations\\Service\\RecommendationService","type":"->"},{"file":"/var/www/nextcloud/httpdocs/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"index","class":"OCA\\Recommendations\\Controller\\RecommendationController","type":"->"},{"file":"/var/www/nextcloud/httpdocs/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/httpdocs/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/httpdocs/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/httpdocs/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/httpdocs/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/httpdocs/apps/files_external/lib/Lib/Storage/FTP.php","Line":358},"CustomMessage":"--"},"id":"6225f852167d2"}
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by icewind1991**
Fix https://github.com/nextcloud/server/issues/31510, Close https://github.com/nextcloud/server/pull/33203

- filezilla doesn't like "" as parameter for `mdtm` (all others seem fine)
- filezilla sends fractional modified date

Haven't had any success with dockerized filezilla server setups so no CI for now :(

### CODE REVIEW

**Comment by kesselb** [comment]
FYI: https://github.com/nextcloud/server/pull/33203

Please verify that the fractional dates handling is not needed in filemtime / $currentDir as well.


> Haven't had any success with dockerized filezilla server setups so no CI for now :(

I can confirm that.

**Comment by icewind1991** [comment]
> Please verify that the fractional dates handling is not needed in filemtime / $currentDir as well.

Shouldn't be needed for filezilla as that supports `mdtm`, I've added it anyway in case there is a server that doesn't but does send fractional dates.

File: apps/files_external/lib/Lib/Storage/FTP.php [hunk 1]
```diff
@@ -355,7 +356,10 @@ public function getDirectoryContent($directory): \Traversable {
 
 			$data = [];
 			$data['mimetype'] = $isDir ? FileInfo::MIMETYPE_FOLDER : $mimeTypeDetector->detectPath($name);
-			$data['mtime'] = \DateTime::createFromFormat('YmdGis', $file['modify'])->getTimestamp();
+
+			// strip fractional seconds
+			[$modify] = explode('.', $file['modify']);
+			$data['mtime'] = \DateTime::createFromFormat('YmdGis', $modify)->getTimestamp();
```
Comment (kesselb) [inline apps/files_external/lib/Lib/Storage/FTP.php:362]: createFromFormat may return false. Please introduce a local variable like in filemtime.

File: apps/files_external/lib/Lib/Storage/FTP.php [hunk 2]
```diff
@@ -123,7 +123,8 @@ public function filemtime($path) {
 					return $item['type'] === 'cdir';
 				}));
 				if ($currentDir) {
-					$time = \DateTime::createFromFormat('YmdHis', $currentDir['modify'] ?? '');
+					[$modify] = explode('.', $currentDir['modify'] ?? '');
```
Comment (come-nc) [inline apps/files_external/lib/Lib/Storage/FTP.php:126]:
```suggestion
					[$modify] = explode('.', $currentDir['modify'] ?? '', 2);
```
