### PR TITLE
Fix userid casting in notifications

### LINKED ISSUE #15677: InvalidArgumentException","Message":"The given user id is invalid
### **I want upgarde 16.0.1 ,but Update failed ,log shows like this:**

`{"reqId":"jTrC7noPG06A7lQ8Co8M","level":1,"time":"2019-05-22T07:53:59+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: Sending notifications to admins and affected users","userAgent":"--","version":"15.0.0.10"}
{"reqId":"jTrC7noPG06A7lQ8Co8M","level":3,"time":"2019-05-22T07:53:59+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":{"Exception":"InvalidArgumentException","Message":"The given user id is invalid","Code":0,"Trace":[{"file":"\/usr\/share\/nginx\/html\/nextcloud\/lib\/private\/Repair\/RemoveLinkShares.php","line":199,"function":"setUser","class":"OC\\Notification\\Notification","type":"->","args":[203]},{"file":"\/usr\/share\/nginx\/html\/nextcloud\/lib\/private\/Repair\/RemoveLinkShares.php","line":224,"function":"sendNotification","class":"OC\\Repair\\RemoveLinkShares","type":"->","args":[]},{"file":"\/usr\/share\/nginx\/html\/nextcloud\/lib\/private\/Repair\/RemoveLinkShares.php","line":230,"function":"repair","class":"OC\\Repair\\RemoveLinkShares","type":"->","args":[{"__class__":"OC\\Repair"}]},{"file":"\/usr\/share\/nginx\/html\/nextcloud\/lib\/private\/Repair.php","line":100,"function":"run","class":"OC\\Repair\\RemoveLinkShares","type":"->","args":[{"__class__":"OC\\Repair"}]},{"file":"\/usr\/share\/nginx\/html\/nextcloud\/lib\/private\/Updater.php","line":272,"function":"run","class":"OC\\Repair","type":"->","args":[]},{"file":"\/usr\/share\/nginx\/html\/nextcloud\/lib\/private\/Updater.php","line":128,"function":"doUpgrade","class":"OC\\Updater","type":"->","args":["16.0.1.1","15.0.0.10"]},{"file":"\/usr\/share\/nginx\/html\/nextcloud\/core\/Command\/Upgrade.php","line":258,"function":"upgrade","class":"OC\\Updater","type":"->","args":[]},{"file":"\/usr\/share\/nginx\/html\/nextcloud\/3rdparty\/symfony\/console\/Command\/Command.php","line":255,"function":"execute","class":"OC\\Core\\Command\\Upgrade","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"\/usr\/share\/nginx\/html\/nextcloud\/3rdparty\/symfony\/console\/Application.php","line":901,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"\/usr\/share\/nginx\/html\/nextcloud\/3rdparty\/symfony\/console\/Application.php","line":262,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"installer":{"__class__":"OC\\Installer"},"__class__":"OC\\Core\\Command\\Upgrade"},{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"\/usr\/share\/nginx\/html\/nextcloud\/3rdparty\/symfony\/console\/Application.php","line":145,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"\/usr\/share\/nginx\/html\/nextcloud\/lib\/private\/Console\/Application.php","line":213,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"\/usr\/share\/nginx\/html\/nextcloud\/console.php","line":97,"function":"run","class":"OC\\Console\\Application","type":"->","args":[]},{"file":"\/usr\/share\/nginx\/html\/nextcloud\/occ","line":11,"args":["\/usr\/share\/nginx\/html\/nextcloud\/console.php"],"function":"require_once"}],"File":"\/usr\/share\/nginx\/html\/nextcloud\/lib\/private\/Notification\/Notification.php","Line":160,"CustomMessage":"--"},"userAgent":"--","version":"15.0.0.10"}
{"reqId":"jTrC7noPG06A7lQ8Co8M","level":3,"time":"2019-05-22T07:53:59+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::failure: InvalidArgumentException: The given user id is invalid","userAgent":"--","version":"15.0.0.10"}
{"reqId":"jTrC7noPG06A7lQ8Co8M","level":3,"time":"2019-05-22T07:53:59+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::updateEnd: Update failed","userAgent":"--","version":"15.0.0.10"}
{"reqId":"jTrC7noPG06A7lQ8Co8M","level":1,"time":"2019-05-22T07:53:59+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::maintenanceActive: Maintenance mode is kept active","userAgent":"--","version":"15.0.0.10"}
{"reqId":"jTrC7noPG06A7lQ8Co8M","level":1,"time":"2019-05-22T07:53:59+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::resetLogLevel: Reset log level to Warning(2)","userAgent":"--","version":"15.0.0.10"}`

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #15677

### CODE REVIEW

File: lib/private/Notification/Notification.php [hunk 1]
```diff
@@ -133,7 +133,7 @@ public function __construct(IValidator $richValidator) {
 	 * @throws \InvalidArgumentException if the app id is invalid
 	 * @since 8.2.0
 	 */
-	public function setApp($app) {
+	public function setApp(\string $app) {
```
Comment (kesselb) [inline lib/private/Notification/Notification.php]: Is `\string` some micro optimization?

**Review by ChristophWurst — APPROVED** [review]

**Comment by skjnldsv** [comment]
@ChristophWurst this is what we should do right?
use \string to force php to not check for existing string class?

Because tests are failing
`PHP Fatal error: Scalar type declaration 'string' must be unqualified in /drone/src/lib/private/Notification/Notification.php on line 136`

**Comment by ChristophWurst** [comment]
> @ChristophWurst this is what we should do right?

Not for primitive types. Only for built-in functions like `\count` it does make sense.

**Comment by skjnldsv** [comment]
Yep, I just realised that ^^
Fixed!

**Comment by kesselb** [comment]
cc @corecode

**Comment by corecode** [comment]
thanks!

**Comment by juliushaertl** [comment]
@skjnldsv Tests are still failing due to this on master. Mind to have a look?

```

1) Test\Notification\NotificationTest::testSetAppInvalid with data set #0 (true)
--
152 | Failed asserting that exception of type "\InvalidArgumentException" is thrown.
153 |  
154 | 2) Test\Notification\NotificationTest::testSetAppInvalid with data set #2 (0)
155 | Failed asserting that exception of type "\InvalidArgumentException" is thrown.
156 |  
157 | 3) Test\Notification\NotificationTest::testSetAppInvalid with data set #3 (1)
158 | Failed asserting that exception of type "\InvalidArgumentException" is thrown.
159 |  
160 | 4) Test\Notification\NotificationTest::testSetAppInvalid with data set #5 (array())
161 | Failed asserting that exception of type "TypeError" matches expected exception "\InvalidArgumentException". Message was: "Argument 1 passed to OC\Notification\Notification::setApp() must be of the type string, array given, called in /drone/src/tests/lib/Notification/NotificationTest.php on line 108" at
162 | /drone/src/lib/private/Notification/Notification.php:137
163 | /drone/src/tests/lib/Notification/NotificationTest.php:108
164 | .
165 |  
166 | 5) Test\Notification\NotificationTest::testSetAppInvalid with data set #7 (array('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'))
167 | Failed asserting that exception of type "TypeError" matches expected exception "\InvalidArgumentException". Message was: "Argument 1 passed to OC\Notification\Notification::setApp() must be of the type string, array given, called in /drone/src/tests/lib/Notification/NotificationTest.php on line 108" at
168 | /drone/src/lib/private/Notification/Notification.php:137
169 | /drone/src/tests/lib/Notification/NotificationTest.php:108
170 | .
171 |  
172 | 6) Test\Notification\NotificationTest::testSetUserInvalid with data set #0 (true)
173 | Failed asserting that exception of type "\InvalidArgumentException" is thrown.
174 |  
175 | 7) Test\Notification\NotificationTest::testSetUserInvalid with data set #2 (0)
176 | Failed asserting that exception of type "\InvalidArgumentException" is thrown.
177 |  
178 | 8) Test\Notification\NotificationTest::testSetUserInvalid with data set #3 (1)
179 | Failed asserting that exception of type "\InvalidArgumentException" is thrown.
180 |  
181 | 9) Test\Notification\NotificationTest::testSetUserInvalid with data set #5 (array())
182 | Failed asserting that exception of type "TypeError" matches expected exception "\InvalidArgumentException". Message was: "Argument 1 passed to OC\Notification\Notification::setUser() must be of the type string, array given, called in /drone/src/tests/lib/Notification/NotificationTest.php on line 136" at
183 | /drone/src/lib/private/Notification/Notification.php:159
184 | /drone/src/tests/lib/Notification/NotificationTest.php:136
185 | .
186 |  
187 | 10) Test\Notification\NotificationTest::testSetUserInvalid with data set #7 (array('aaaaaaaaaaaaaaaaaaaaaaaaaaaaa...aaaaaa'))
188 | Failed asserting that exception of type "TypeError" matches expected exception "\InvalidArgumentException". Message was: "Argument 1 passed to OC\Notification\Notification::setUser() must be of the type string, array given, called in /drone/src/tests/lib/Notification/NotificationTest.php on line 136" at
189 | /drone/src/lib/private/Notification/Notification.php:159
190 | /drone/src/tests/lib/Notification/NotificationTest.php:136
191 | .

```

**Comment by skjnldsv** [comment]
Ah damn, I missed those!
Thanks!

**Comment by nickvergessen** [comment]
the type hint is also part of #15040

Also I would suggest to revert the backport of the type hint and only keep the cast in 16, which also already fixes the problem.

**Comment by skjnldsv** [comment]
@nickvergessen sure thing!
Do whatever you need :)
