### PR TITLE
fix(isLegitimatedForUserId): Setup mountpoints to check file access

### LINKED ISSUE #71: No notification from groupfolders
I have a 'flow' set to notify when a file with a specific name is edited.
It works well for a file in a shared folder, but no notification is pushed for a file in a group folder.

### PR DESCRIPTION
**Pull request by mejo-**
This fixes workflows on groupfolders, as it will consider access to files in groupfolders.

It also fixes false positives where access to files was limited by other means not taken into account before, e.g. access control.

For postDelete events, check for permissions of the parent folder instead, as the file itself no longer exists.

Fixes: nextcloud/flow_notifications#71

Idea taken from https://github.com/nextcloud/server/pull/38946

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/workflowengine/lib/Entity/File.php [hunk 1]
```diff
@@ -136,12 +141,19 @@ public function prepareRuleMatcher(IRuleMatcher $ruleMatcher, string $eventName,
 
 	public function isLegitimatedForUserId(string $uid): bool {
 		try {
-			$node = $this->getNode();
-			if ($node->getOwner()->getUID() === $uid) {
-				return true;
+			$fileId = $this->getNode()->getId();
+			$mounts = $this->userMountCache->getMountsForFileId($fileId);
```
Comment (icewind1991) [inline apps/workflowengine/lib/Entity/File.php:145]: you can add the user filter here since we're only checking for one user

File: apps/workflowengine/lib/Entity/File.php [hunk 2]
```diff
@@ -136,12 +136,15 @@ public function prepareRuleMatcher(IRuleMatcher $ruleMatcher, string $eventName,
 
 	public function isLegitimatedForUserId(string $uid): bool {
 		try {
-			$node = $this->getNode();
-			if ($node->getOwner()->getUID() === $uid) {
-				return true;
```
Comment (icewind1991) [inline apps/workflowengine/lib/Entity/File.php:141]: Probably best to leave this in as a fast path

**Comment by icewind1991** [comment]
> @icewind1991 do you think this can be a performance killer?

It isn't worse than the previous code (`getAccessList` is probably just as bad), but if this gets called in a loop (like for every file in a folder that is being accessed) than performance will be dead yes.
I do not know enough about workflow to know how this code is called

File: apps/workflowengine/lib/Entity/File.php (hunk 1 above)
Comment (mejo-) [reply apps/workflowengine/lib/Entity/File.php]: Good point, fixed now :+1:

File: apps/workflowengine/lib/Entity/File.php (hunk 2 above)
Comment (mejo-) [reply apps/workflowengine/lib/Entity/File.php]: Agreed, also fixed now.

**Comment by mejo-** [comment]
Cypress test failures seem unrelated. PR should be ready for review :blush:

**Comment by mejo-** [comment]
By the way, I manually tested the following scenarios (all with a `flow_notification` flow defined by admin for files with a system tag):

* User `jane` creates/changes a file in a tagged folder shared with her by `admin` -> `isLegitimatedForUserId` returns `true`
* User `jane` deletes a file in a tagged folder shared with her by `admin` -> `isLegitimatedForUserId` returns `true`
* User `jane` creates/changes a file in a tagged groupfolder where `admin` has access  -> `isLegitimatedForUserId` returns `true`
* User `jane` deletes a file in a tagged groupfolder where `admin` has access  ->  -> `isLegitimatedForUserId` returns `true`
* User `jane` creates/changes a file in a tagged groupfolder where `admin` doesn't have access  -> `isLegitimatedForUserId` returns `false`
* User `jane` deletes a file in a tagged groupfolder where `admin` doesn't have access  ->  -> `isLegitimatedForUserId` returns `false`

File: apps/workflowengine/lib/Entity/File.php [hunk 3]
```diff
@@ -140,8 +140,19 @@ public function isLegitimatedForUserId(string $uid): bool {
...
-			$acl = $this->shareManager->getAccessList($node, true, true);
-			return isset($acl['users']) && array_key_exists($uid, $acl['users']);
+			$fileId = $node->getId();
+			$mounts = $this->userMountCache->getMountsForFileId($fileId, $uid);
+			foreach ($mounts as $mount) {
+				$userFolder = $this->root->getUserFolder($uid);
+				if ($this->eventName === self::EVENT_NAMESPACE . 'postDelete') {
+					// At postDelete, the file no longer exists. Check for parent folder instead.
+					$fileId = $node->getParentId();
+				}
```
Comment (icewind1991) [inline apps/workflowengine/lib/Entity/File.php:150]: this can be moved outside the loop

File: apps/workflowengine/lib/Entity/File.php [hunk 4]
```diff
@@ -140,8 +140,19 @@ public function isLegitimatedForUserId(string $uid): bool {
...
+				if (!empty($userFolder->getById($fileId))) {
```
Comment (icewind1991) [inline apps/workflowengine/lib/Entity/File.php:151]: I'm not a fan of doing `getById` here, it not only duplicates some of the logic we just did (getting the mount from the UserMountCache), it also does extra work to setup the nodes that we then just throw away here.

An alternative approach would be to create a `getMountFromMountInfo` (or similarly named) method in the `MountManager` to get the `MountPoint` instance matching a `ICachedMountInfo`. This would setup the mounts for the user and find the mount that matches.

When we have a `MountPoint` we can do `$mount->getStorage()->getCache()->get($id)` to check if the user actually has access.

File: apps/workflowengine/lib/Entity/File.php (hunk 3 above)
Comment (mejo-) [reply apps/workflowengine/lib/Entity/File.php:150]: Agreed, changed now.

File: apps/workflowengine/lib/Entity/File.php (hunk 4 above)
Comment (mejo-) [reply apps/workflowengine/lib/Entity/File.php:159]: See commit 585897014c5e077bdbd99bafd8670a1f076737cc for my current implementation attempt.

Comment (icewind1991) [reply apps/workflowengine/lib/Entity/File.php:159]: That approach looks good.

> Given that the fix needs to be backported until stable26, I guess it's not an option to add getMountFromMountInfo() to the public IMountManager interface, right? Sure we can add it there as well, but at least in the backports we would have to use the private Mount/Manager class, or am I missing something?

Yes, for the backports we can just leave out the interface changes

> What exactly would you compare to match the mount from ICachedMountFileInfo? The rootId?

Mountpoint

Comment (mejo-) [reply apps/workflowengine/lib/Entity/File.php:159]: Thanks for the comments @icewind1991. Unfortunately comparing `$mount->getMountPoint()` and `$info->getMountPoint()` doesn't work in my tests with groupfolders. While `$info->getMountPoint()` is e.g. `/admin/files/testgroupfolder` (for workflows configured by `admin`), `$mount->getMountPoint()` is `/jane/files/testgroupfolder` (for changes done by `jane`). Comparing the `rootId`/`storageRoot` on the other hand would work. What do you think @icewind1991?

File: lib/private/Files/Mount/Manager.php [hunk 5]
```diff
@@ -226,4 +227,21 @@ public function getMountsByMountProvider(string $path, array $mountProviders) {
...
+
+	/**
+	 * Return the mount matching a cached mount info (or mount file info)
+	 *
+	 * @param ICachedMountInfo $info
+	 *
+	 * @return IMountPoint
+	 * @throws NotFoundException
+	 */
+	public function getMountFromMountInfo(ICachedMountInfo $info): IMountPoint {
```
Comment (icewind1991) [inline lib/private/Files/Mount/Manager.php:239]: Probably better to return `null` instead of throwing an exception when the mount is not found imo

File: apps/workflowengine/lib/Entity/File.php (hunk 4 above)
Comment (icewind1991) [reply apps/workflowengine/lib/Entity/File.php:160]: `rootId` is not unique by itself (the root of an ext storage/gf being shared to a user that already has access will lead to 2 mounts with the same `rootId`) which could cause issues as the duplicate mounts might have different permissions.

Might just need to setup the filesystem for `$uid` here

Comment (mejo-) [reply apps/workflowengine/lib/Entity/File.php:160]: How about comparing `$info->getRootInternalPath()` to `$mount->getSourcePath()`? Or does this have the same problem as `rootId`, because it compares the source instead of the mountpoint?

Comment (icewind1991) [reply apps/workflowengine/lib/Entity/File.php:160]: It still has the same `rootid` yes, `mountpoint` is the only field in the mountcache that is unique.

for the specific use case it doesn't really mattert (since we only care that the user has at least one mountpoint that can access the file), but for a method in `IMountManager` it needs to deal with "duplicate" mounts

Comment (mejo-) [reply apps/workflowengine/lib/Entity/File.php]: I implemented it like @icewind1991 suggested now: Setup the filesystem for the mountpoint in `getMountFromMountInfo()`.

**Review by icewind1991 — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]
One psalm complaint, but otherwise seems reasonable :+1:

**Comment by mejo-** [comment]
Thanks @juliushaertl. I addressed the psalm complaint now.

**Comment by mejo-** [comment]
Will need manual backports without the public interface changes to stable27 and stable26.
