### PR TITLE
print the backup codes tab and not the current one

### LINKED ISSUE #2662: NC11.0.0: Printing backup codes fails when Adblock Plus is activated, ABP prevents the new window for printing the backup codes to be opened.
One page is printed, but this is only covering the upper left part of the whole browser window (section "Persönlich" and start of the Profile), but not the codes.

The maintainer expressly asked me to file it here, see his comment on https://github.com/nextcloud/twofactor_totp/issues/103#issuecomment-266965735 .

### PR DESCRIPTION
**Pull request by ChristophWurst**
Fixes https://github.com/nextcloud/server/issues/2662

Before, the *current* tab was printed (and closed), not the temporary one with the backup codes.

Should be backported IMO. cc @karlitschek

### CODE REVIEW

**Comment by karlitschek** [comment]
please backport 👍

**Comment by nickvergessen** [comment]
Doesn't work here with FF:
[mozilla.pdf](https://github.com/nextcloud/server/files/655393/mozilla.pdf)

**Comment by ChristophWurst** [comment]
> Doesn't work here with FF:
> mozilla.pdf

Works here with 50.1.0 🤔

**Comment by ChristophWurst** [comment]
Ouch. Doesn't work on Chromium too.

File: apps/twofactor_backupcodes/js/settingsview.js [hunk 1]
```diff
@@ -113,10 +113,12 @@
...
 		},
 		_onPrintBackupCodes: function () {
-			var url = this._getDownloadDataHref();
-			window.open(url, t('twofactor_backupcodes', 'Nextcloud backup codes'));
-			window.print();
-			window.close();
+			var data = this._getDownloadData();
+			var newTab = window.open('', t('twofactor_backupcodes', 'Nextcloud backup codes'));
+			newTab.document.write('<h1>' + t('twofactor_backupcodes', 'Nextcloud backup codes') + '</h1>');
+			newTab.document.write(data);
```
Comment (ChristophWurst) [inline apps/twofactor_backupcodes/js/settingsview.js]: cc @LukasReschke for possible security implications of writing to the document directly

**Comment by ChristophWurst** [comment]
rebased

**Review by MorrisJobke — APPROVED** [review]
Tested and works with Firefox, Safari and Chrome 👍

**Comment by MorrisJobke** [comment]
@nickvergessen @rullzer @schiessle @LukasReschke Mind to review this one?

**Comment by MorrisJobke** [comment]
> @nickvergessen @rullzer @schiessle @LukasReschke Mind to review this one?

Ping

**Review by rullzer — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@ChristophWurst Please open a backport PR ;)

**Comment by ChristophWurst** [comment]
> @ChristophWurst Please open a backport PR ;)

Done: https://github.com/nextcloud/server/pull/3510 :-)
