### PR TITLE
make file cache updates more robust

### LINKED ISSUE #8299: Decryption failed with s3
### Steps to reproduce
1. Add s3 external storage
2. Enable default encryption module for external storage
3. Create a folder and upload image files to the external storage using web interface.
4. Open the file / download the file
5. Delete the folder.

### Expected behaviour
The web interface should display the image.  Download should be possible.
The folder should get deleted.

### Actual behaviour
Open: "Error! Could not generate a preview for this file." screen stays black.
Download: File not found browser error
Delete: "Error deleting file test" (test is actually a folder)

### Server configuration

**Operating system**:
Ubuntu 16.04
**Web server:**
 nginx/1.10.3
**Database:**
mysql
**PHP version:**
7.0
**Nextcloud version:** 
13.0.0.14
**Updated from an older Nextcloud/ownCloud or fresh install:**
update
**Where did you install Nextcloud from:**
updater
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - bookmarks: 0.10.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.0
  - caniupdate: 0.1.2
  - comments: 1.3.0
  - contacts: 2.0.1
  - dav: 1.4.6
  - encryption: 2.0.0
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_accesscontrol: 1.3.0
  - files_automatedtagging: 1.3.0
  - files_downloadactivity: 1.2.0
  - files_external: 1.4.1
  - files_markdown: 2.0.1
  - files_pdfviewer: 1.2.0
  - files_retention: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.7.9
  - metadata: 0.6.0
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - previewgenerator: 1.0.9
  - provisioning_api: 1.3.0
  - quota_warning: 1.2.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - socialsharing_email: 1.0.3
  - spreed: 3.0.1
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - nextant
  - survey_client
  - user_external
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.example.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.example.com",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "maintenance": false,
        "loglevel": 2,
        "theme": "",
        "appstore.experimental.enabled": false,
        "asset-pipeline.enabled": true,
        "updater.release.channel": "stable",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\PDF"
        ]
    }
}

```
</details>

**Are you using external storage, if yes which one:** 
S3
**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox 58
**Operating system:**
Win 10 
#### Web server error log
<details>
<summary>Web server error log</summary>

```
No errors.
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Open file using web interface:
{"reqId":"GT0dm99KGTkForeBI6wm","level":3,"time":"2018-02-10T16:47:24+00:00","remoteAddr":"xx.xxx.xx.xxx","user":"user","app":"gallery","method":"GET","url":"\/apps\/gallery\/preview\/491404?width=2000&height=2000&c=5a7f1ca7d33cf&requesttoken=C3KpKPDpsldwblDmU%2F1ZgYoTDSLMCC5VeETNRTffyNg%3D%3AJEfnecmY3B0gP2WlZaga6eRCOxH0RGMRMjPmCGK%2Bg4I%3D","message":"Exception: Preview generation has failed","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}


Try to delete folder: 
{"reqId":"wO1IIM9dmHqCSyH3COj0","level":4,"time":"2018-02-10T16:48:11+00:00","remoteAddr":"xx.xxx.xx.xxx","user":"user","app":"webdav","method":"DELETE","url":"\/remote.php\/webdav\/AmazonS3\/test","message":"Exception: {\"Exception\":\"OC\\\\Encryption\\\\Exceptions\\\\DecryptionFailedException\",\"Message\":\"Encryption library: Decryption (symmetric) of content failed: \",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/encryption\\\/lib\\\/Crypto\\\/Crypt.php(471): OCA\\\\Encryption\\\\Crypto\\\\Crypt->decrypt(*** sensitive parameters replaced ***)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/encryption\\\/lib\\\/Crypto\\\/Encryption.php(380): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('LmSZEvMHRwf75VA...', '`\\\\x81oj&\\\\xB6O\\\\xB3\\\\x06\\\\xA3{!\\\\x96\\\\n\\\\xB4...', 'AES-256-CTR', 1, 0)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Stream\\\/Encryption.php(464): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt(*** sensitive parameters replaced ***)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Stream\\\/Encryption.php(295): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#4 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/helper.php(297): fread(Resource id #152, 8192)\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(747): OC_Helper::streamCopy(Resource id #152, Resource id #153)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(644): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->copyBetweenStorage(Object(OCA\\\\FilesAccessControl\\\\StorageWrapper), 'test\\\/15896368_1...', 'files_trashbin\\\/...', false, true)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(739): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->copyFromStorage(Object(OCA\\\\FilesAccessControl\\\\StorageWrapper), 'test\\\/15896368_1...', 'files_trashbin\\\/...', false, true)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(616): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->copyBetweenStorage(Object(OCA\\\\FilesAccessControl\\\\StorageWrapper), 'test', 'files_trashbin\\\/...', true, true)\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(573): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->moveFromStorage(Object(OCA\\\\FilesAccessControl\\\\StorageWrapper), 'test', 'files_trashbin\\\/...')\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(573): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->moveFromStorage(Object(OCA\\\\FilesAccessControl\\\\StorageWrapper), 'test', 'files_trashbin\\\/...')\\n#12 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_accesscontrol\\\/lib\\\/StorageWrapper.php(586): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->moveFromStorage(Object(OCA\\\\FilesAccessControl\\\\StorageWrapper), 'test', 'files_trashbin\\\/...')\\n#13 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_trashbin\\\/lib\\\/Trashbin.php(254): OCA\\\\FilesAccessControl\\\\StorageWrapper->moveFromStorage(Object(OCA\\\\FilesAccessControl\\\\StorageWrapper), 'test', 'files_trashbin\\\/...')\\n#14 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_trashbin\\\/lib\\\/Storage.php(289): OCA\\\\Files_Trashbin\\\\Trashbin::move2trash('AmazonS3\\\/test', false)\\n#15 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_trashbin\\\/lib\\\/Storage.php(208): OCA\\\\Files_Trashbin\\\\Storage->doDelete('test', 'rmdir')\\n#16 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(91): OCA\\\\Files_Trashbin\\\\Storage->rmdir('test')\\n#17 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_accesscontrol\\\/lib\\\/StorageWrapper.php(75): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->rmdir('test')\\n#18 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1148): OCA\\\\FilesAccessControl\\\\StorageWrapper->rmdir('test')\\n#19 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(346): OC\\\\Files\\\\View->basicOperation('rmdir', '\\\/AmazonS3\\\/test', Array)\\n#20 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(303): OC\\\\Files\\\\View->rmdir('\\\/AmazonS3\\\/test')\\n#21 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(179): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->delete()\\n#22 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(287): Sabre\\\\DAV\\\\Tree->delete('AmazonS3\\\/test')\\n#23 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#24 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#25 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\n#26 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#27 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(80): Sabre\\\\DAV\\\\Server->exec()\\n#28 \\\/var\\\/www\\\/nextcloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/nextcl...')\\n#29 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/encryption\\\/lib\\\/Crypto\\\/Crypt.php\",\"Line\":589,\"Hint\":\"Encryption library: Decryption (symmetric) of content failed: \"}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}

Try to download file:
{"reqId":"HXWHRhMs3BsQ8ySmK26M","level":3,"time":"2018-02-10T17:08:10+00:00","remoteAddr":"xx.xxx.xx.xxx","user":"user","app":"PHP","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v2\/notifications","message":"Uncaught Error: Access to undeclared static property: OC\\Files\\Filesystem::$normalizedPathCache in \/var\/www\/nextcloud\/lib\/private\/Files\/Filesystem.php:796\nStack trace:\n#0 \/var\/www\/nextcloud\/lib\/private\/Files\/View.php(2057): OC\\Files\\Filesystem::normalizePath('\/user\/files\/Am...')\n#1 \/var\/www\/nextcloud\/lib\/private\/Files\/View.php(1182): OC\\Files\\View->unlockFile('\/AmazonS3\/test\/...', 1)\n#2 [internal function]: OC\\Files\\View->OC\\Files\\{closure}()\n#3 \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/CallbackWrapper.php(109): call_user_func(Object(Closure))\n#4 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_close()\n#5 {main}\n  thrown at \/var\/www\/nextcloud\/lib\/private\/Files\/Filesystem.php#796","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}


```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
No errors.
```
</details>

### PR DESCRIPTION
**Pull request by schiessle**
Only update the encrypted version after the write operation is finished and the stream is closed

With Amazon S3 as primary storage it happened that we tried to update the "encryption version" before the file was added to the file cache which lead to a wrong version number. By updating the version only after the stream was closed I could solve the issue.

@icewind1991 please have a look if this makes sense. Thanks!

fix https://github.com/nextcloud/server/issues/8299

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
Makes sense. but I'd love for @icewind1991 to have a look

**Comment by schiessle** [comment]
@rullzer done

**Comment by icewind1991** [comment]
I would prefer if it used a `CallbackWrapper` instead and update the cache from the close callback, that way seems a bit cleaner to me and less mixing on concerns.

(you can use the write callback to set the `$fileUpdated` flag)

**Comment by schiessle** [comment]
@icewind1991 I agree with you in general. But as I want to backport it to 13 as well I would like to keep the fix as small as possible:

Suggestion: Let's merge this for 14 and backport it for 13  and I will do a follow up PR for master (15) to add a CallbackWrapper.

File: tests/lib/Files/Stream/EncryptionTest.php [hunk 1]
```diff
@@ -49,6 +52,13 @@ protected function getStream($fileName, $mode, $unencryptedSize, $wrapper = '\OC
 		$util->expects($this->any())
 			->method('getUidAndFilename')
 			->willReturn(['user1', $internalPath]);
+		$storage->expects($this->any())->method('getCache')->willReturn($cache);
+		$entry = new CacheEntry([
+			'fileid' => 5,
+			'encryptedVersion' => 2,
+		]);
+		$cache->expects($this->any())->method('get')->willReturn($entry	);
+		$cache->expects($this->any())->method('update')->with(5, ['encrypted' => 3, 'encryptedVersion' => 3]);
```
Comment (icewind1991) [inline tests/lib/Files/Stream/EncryptionTest.php]: change this to `$this->once()` please

**Review by icewind1991 — CHANGES_REQUESTED** [review]

**Comment by icewind1991** [comment]
> Suggestion: Let's merge this for 14 and backport it for 13 and I will do a follow up PR for master (15) to add a CallbackWrapper.

Sounds good to me

File: tests/lib/Files/Stream/EncryptionTest.php (hunk 1 above)
Comment (schiessle) [reply tests/lib/Files/Stream/EncryptionTest.php]: It is not possible the stream, created in the method is used in various places. Sometimes the method is never called and some tests uses the instance multiple times so it is used more then once. All I want to make sure is that every time it is called, it should be called with the right parameters.

**Comment by schiessle** [comment]
Let's get this in for the beta3 so that it gets some test coverage...

**Comment by MorrisJobke** [comment]
@schiessle Could you prepare the backport?
