### PR TITLE
fix: redirect to proper directory if file not found

### LINKED ISSUE #32177: [Bug]: internal links don't seem to get resolved properly
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

It's possible to simply copy the address bar link and send it to another user who has access to the file, for them to open it. This seems, at least for some users in Nc 24RC2, broken. Link for an internal Nextcloud GmbH user to test:
<https://cloud.nextcloud.com/apps/files/?dir=/Marketing/Marketing%20Automation%20plan&openfile=5993281>
worked for Max, not for Jos and Christoph. Magic!

Possibly related, but only for SMB/LDAP scenario's: https://github.com/nextcloud/server/issues/27969

### Steps to reproduce

1. copy address bar to a file/folder
2. share with a colleague who has access to that file/folder
3. have them open the link and see the URL in the Breadcrumbs bar, but their root as folder contents

Video (also internal share, as it has some semi-sensitive stuff):
https://cloud.nextcloud.com/f/5993616

### Expected behavior

Colleague should see the file be opened.

### Installation method

_No response_

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database engine version

_No response_

### Is this bug present after an update or on a fresh install?

_No response_

### Are you using the Nextcloud Server Encryption module?

_No response_

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
internal nextcloud server
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### LINKED ISSUE #40104: [Bug]: url share not working
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

One way to share a file to a colleague is to just copy over the URL in your browser location bar to a specific file. This works, seemingly, for some people - but it doesn't for me 😢 

### Steps to reproduce

1. (colleague) copy URL to a file
2. (me) paste in top or click link
3. it starts loaded, then I get redirected to https://cloud.nextcloud.com/apps/files/files?dir=/&fileid=350

### Expected behavior

Load the url! It works if I copy a URL myself...

### Installation method

None

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [x] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/server/issues/32177
Fix https://github.com/nextcloud/server/issues/40104

1. If you ask for a fileid in a dir
2. And the fileid doesn't exists in that directory
3. BUT the file only exists in one occurrence in another directory
4. Then redirect to that file

### CODE REVIEW

File: apps/files/lib/Controller/ViewController.php [hunk 1]
```diff
@@ -230,6 +230,19 @@ public function index($dir = '', $view = '', $fileid = null, $fileNotFound = fal
 			$favElements['folders'] = [];
 		}
 
+		// If the file doesn't exists in the folder and
+		// exists in only one occurrence, redirect to that file
+		// int the correct folder
+		if ($fileid && $dir !== '') {
+			$baseFolder = $this->rootFolder->getUserFolder($userId);
+			$nodes = $baseFolder->getById((int) $fileid);
+			$relativePath = dirname($baseFolder->getRelativePath($nodes[0]->getPath()));
```
Comment (skjnldsv) [inline apps/files/lib/Controller/ViewController.php:239]: @icewind1991 why is there no direct way to get the relative userFolder path for a file?
I could not find it and this looks suspicious :see_no_evil:

**Comment by skjnldsv** [comment]
Ping everyone! :pray:

File: apps/files/lib/Controller/ViewController.php [hunk 2]
```diff
@@ -230,6 +230,19 @@ public function index($dir = '', $view = '', $fileid = null, $fileNotFound = fal
 			$favElements['folders'] = [];
 		}
 
+		// If the file doesn't exists in the folder and
+		// exists in only one occurrence, redirect to that file
+		// int the correct folder
```
Comment (Altahrim) [inline apps/files/lib/Controller/ViewController.php:235]:
```suggestion
		// in the correct folder
```

File: apps/files/lib/Controller/ViewController.php [hunk 3]
```diff
@@ -374,7 +387,7 @@ private function redirectToFile(int $fileId) {
 		$uid = $this->userSession->getUser()->getUID();
 		$baseFolder = $this->rootFolder->getUserFolder($uid);
 		$nodes = $baseFolder->getById($fileId);
-		$params = [];
```
Comment (max-nextcloud) [inline apps/files/lib/Controller/ViewController.php:377]: I think the psalm warning is correct and you actually need to keep this line. Otherwise `$params` is undefined.

File: apps/files/lib/Controller/ViewController.php [hunk 4]
```diff
@@ -374,7 +387,7 @@
...
+		$params['view'] = 'files';
```
[the remark this answers is not in the document]
Comment (Altahrim) [reply apps/files/lib/Controller/ViewController.php:390]:
```suggestion
		$params = ['view' => 'files'];
```

**Review by Altahrim — APPROVED** [review]

**Review by max-nextcloud — APPROVED** [review]

**Review by miaulalala — APPROVED** [review]
