### PR TITLE
Always replace the app sidebar view when switching from a different file list

### LINKED ISSUE #10398: Opening details after coming from favorites view is broken
Acceptance tests fail:

```
# /drone/src/github.com/nextcloud/server/tests/acceptance/features/app-files.feature:14
Scenario: viewing a favorite file in its folder does not prevent opening the details view in "All files" section
  Given I am logged in
  And I mark "welcome.txt" as favorite
  And I see that "welcome.txt" is marked as favorite
  And I open the "Favorites" section
  And I open the details view for "welcome.txt"
  And I see that the details view is open
  And I view "welcome.txt" in folder
  And I see that the current section is "All files"
  When I open the details view for "welcome.txt"
  Then I see that the details view is open
    The details view is not open yet after 100 seconds
```

For me the details view opens in Safari, but the error in the console is still there.

JS console:

```
TypeError: undefined is not an object (evaluating 'OCA.Files.App.fileList.changeDirectory(fileModel.get('path'), true, true).then')
```

bildschirmfoto 2018-07-25 um 17 41 23

cc @skjnldsv @juliushaertl @danxuliu @nextcloud/javascript 

That is now the only failing test and we could maybe look into this.

### PR DESCRIPTION
**Pull request by juliusknorr**
This should fix #10398. Once you switch to a different file list type like `FavoritesFileList` the detailsview element from the first file list has been removed from the DOM. Because of that it could not be shown when going back to the first file list.

~The underlying reason is that the current files app layout is based on [one DetailsView per file list](https://github.com/nextcloud/server/blob/b7572da4c8d4e0d7e33b31306d3ffd8123860334/apps/files/js/filelist.js#L277), we should change that for 15 maybe, but I would not introduce such a change now, since it might cause even more breakage.~

~Edit: I have a branch that switches to use a single instance at https://github.com/nextcloud/server/commit/01f885e6941bdd768f46e2216d55a8aa74e3854c but as expected this will lead to various issues with the plugins that are registered for each file list.~

Turns out, we simply can run render to make sure that the sidebar view is updated in the dom when updating the details view from the file list. Thanks @skjnldsv :+1:

### CODE REVIEW

File: apps/files/js/detailsview.js [hunk 1]
```diff
@@ -118,11 +118,7 @@
 		 */
 		render: function() {
 			// remove old instances
-			if ($('#app-sidebar').length === 0) {
-				this.$el.insertAfter($('#app-content'));
-			} else {
-				$('#app-sidebar').replaceWith(this.$el)
-			}
+			this.$el.insertAfter($('#app-content'));
```
Comment (juliushaertl) [inline apps/files/js/detailsview.js]: Yes, that will lead to multiple divs with the same id of `app-content`, but I'd still keep it like this as a temporary fix, as it was like that before as well.

**Comment by juliushaertl** [comment]
The underlying issue seems fixed for now, but the acceptance test still fails because it fails to get the correct app-sidebar container.

**Comment by juliushaertl** [comment]
@danxuliu Maybe you can help here. I'm out of ideas how we could fix this. The underlying issue is solved, the acceptance test tries to get #app-sidebar but there are several ones. As with this fix we don't have any reference in the DOM about what filelist each app-sidebar element is related to. We also cannot use the [approach before](https://github.com/nextcloud/server/commit/562e2aa30bd1c0b1766be01b2cd5de7b8f753008#diff-6c14fe36e2674d71555d4c3797654e27L66), because due to the new structure the element isn't a child of it anymore.

File: apps/files/js/detailsview.js (hunk 1 above)
Comment (skjnldsv) [reply apps/files/js/detailsview.js]: Okay, I fixed this before. The multiple content are not acceptable according to the acceptance tests, we removed all the old tests for this reason. I really think we should not do that.

Why the replacement of the sidebar with the new element does not work?

Comment (juliushaertl) [reply apps/files/js/detailsview.js]: The replacement is only done once when loading the list for the first time, when you try to show the details view for a second time, after a different view has been used, it will not call render and therefore not replace it again. But maybe that is a good idea to just make sure it gets replaced on each opening of the details sidebar. I'll have a look.

Comment (skjnldsv) [reply apps/files/js/detailsview.js]: What about replacing ids or stuff like that?
#app-sidebar-favorites, when selected -> #app-sidebar

Comment (juliushaertl) [reply apps/files/js/detailsview.js]: It was actually even easier: 16f6c07 I now just run the render function on every details sidebar change and just replace it if the element is from a different filelist.

Comment (skjnldsv) [reply apps/files/js/detailsview.js]: Nice!! Well done! :tada: :)

**Review by skjnldsv — APPROVED** [review]
Works!

**Comment by juliushaertl** [comment]
Some other acceptance test is failing, i'll investigate.

**Comment by juliushaertl** [comment]
Ok, I've [adjusted the acceptance test](https://github.com/nextcloud/server/pull/10509/commits/1b4d502bfdd3234a698533d482c8c80e1305aa82) to test for the original 
issue https://github.com/nextcloud/server/issues/1448 that the test was about. Moving to a single `#app-sidebar` container now allows to keep the sidebar open when we show the file in folder, since that is the default behavior when a file is highlighted in the list.

Failure at https://drone.nextcloud.com/nextcloud/server/9428/146 is unrelated.

Ready for review.

**Comment by skjnldsv** [comment]
Wee, green acceptance tests!

**Review by rullzer — APPROVED** [review]
