### PR TITLE
fix(DnsPinning): Ensure to always lookup based on FQDN

### LINKED ISSUE #56489: [Bug]: App Updates with IPv6 and Debian Trixie: RequestException cURL error 60: SSL: no alternative certificate subject name matches target hostname 'github.com'
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

On several servers, since the upgrade from Debian Bookworm (12) to Trixie (13) I get the following error whenever I try to update Nextcloud apps:

```
RequestException
cURL error 60: SSL: no alternative certificate subject name matches target hostname 'github.com' (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://github.com/nextcloud-releases/contacts/releases/download/v8.0.6/contacts-v8.0.6.tar.gz
```

This issue has already been experienced several times in the past:

* https://help.nextcloud.com/t/updating-installing-apps-always-choses-ipv6-but-github-com-hasnt-an-aaaa-entry/211276
* https://help.nextcloud.com/t/requestexception-curl-error-60-ssl-no-alternative-certificate-subject-name-matches-target-hostname-github-com/208178

It still does not seem to be fixed, and I could not find any official bug report for it.

This probably also happens on other OSes, not only Debian Trixie, but I didn't experience this issue with Debian Bookworm.

### Steps to reproduce

1. Install Nextcloud using the tarball on an IPv6 enabled Debian Trixie server. The server's DNS server probably needs to have IPv6 wildcard subdomain resolution to some IPv6 address where an SSL supporting web server must listen.
2. Try to update installed apps which have an update available using the Web UI.
3. The update fails with the abovementioned message - of course, the domain names may vary, depending on the package.

### Expected behavior

Updating Apps is possible if an update is available.

### Nextcloud Server version

32

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 31 to 32)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [x] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by DerDreschner**
* Resolves: #56489 

## Summary
After upgrading my private server from Debian 12 to Debian 13, I've experienced the same issue mentioned in #56489 which resulted in the app store to be totally unusable. Upgrading the Nextcloud version worked without any issues tho.

The investigation got the following results:
- The main issue is the DNS Pinning
- When looking up `github.com`, it tried to resolve A, AAAA and CNAME records
- It only got an A and AAAA record back
- The A record had the correct host and IP, but the AAAA record didn't. It was the result for `github.com.dreschner.net`
- cURL tries to connect via the (incorrectly) provided IPv6 address first
- The certificate doesn't match the expected hostname and resulting in the error 60

For reproducing the issue on command line level, you can use the following command on a server with IPv6 connectivity:

```
curl -v https://github.com/nextcloud-releases/integration_giphy/releases/download/v2.2.0/integration_giphy-v2.2.0.tar.gz --resolve 'github.com:443:140.82.121.4,2a0a:4cc0:c1:71d6:1876:e0ff:fe86:4038'
```

The reason is that we don't use FQDNs for resolving the DNS records and GitHub doesn't provide an AAAA record. Therefore, the program behind `dns_get_records()` looks for the host as subdomain of the local domain name. This works as I have a wildcard AAAA record set-up.

The fix is easy: just add a `.` at the end to make the requested domain name a FQDN and prevent the lookup under the local domain name when no record is being found in the first lookup.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)
- [x] [Labels added](https://github.com/nextcloud/server/labels) where applicable (ex: bug/enhancement, `3. to review`, feature component)
- [ ] [Milestone added](https://github.com/nextcloud/server/milestones) for target branch/version (ex: 32.x for `stable32`)

## AI (if applicable)

- [ ] The content of this PR was partly or fully generated using AI

### CODE REVIEW

File: lib/private/Http/Client/DnsPinMiddleware.php [hunk 1]
```diff
@@ -59,6 +61,10 @@ private function dnsResolve(string $target, int $recursionCount) : array {
 		$dnsTypes = \defined('AF_INET6') || @inet_pton('::1')
 			? [DNS_A, DNS_AAAA, DNS_CNAME]
 			: [DNS_A, DNS_CNAME];
+
+		// Before looking up any DNS record, we need to make sure the
+		// provided target is an FQDN by adding a dot to the end.
+		$target = str_ends_with($target, '.') ? $target : "$target.";
```
Comment (provokateurin) [inline lib/private/Http/Client/DnsPinMiddleware.php]:
```suggestion
		if (!str_ends_with($target, '.')) {
			$target .= '.';
		}
```

**Review by provokateurin — CHANGES_REQUESTED** [review]
Uh that is quite something 😅

File: lib/private/Http/Client/DnsPinMiddleware.php (hunk 1 above)
Comment (kesselb) [inline lib/private/Http/Client/DnsPinMiddleware.php]: Would prefer `rtrim($target, '.') . '.'` ;)

Comment (kesselb) [reply lib/private/Http/Client/DnsPinMiddleware.php]: Maybe through a small helper function `enforceFdqn` or such.

**Review by kesselb — APPROVED** [review]

File: lib/private/Http/Client/DnsPinMiddleware.php (hunk 1 above)
Comment (DerDreschner) [reply lib/private/Http/Client/DnsPinMiddleware.php]: Yeah, that was I were thinking about last night as well. Will change it now.

File: lib/private/Http/Client/DnsPinMiddleware.php [hunk 2]
```diff
@@ -25,6 +25,21 @@ public function __construct(
...
 	}
 
+	/**
+	 * DNS lookups must end with a dot to be marked as
+	 * FQDN. Otherwise, a record without answer may trigger
+	 * a lookup on the local domain name. See GitHub
+	 * issue #56489 for details.
+	 *
+	 * @param string $hostname
+	 * @return string
```
Comment (kesselb) [inline lib/private/Http/Client/DnsPinMiddleware.php]: nit: `@param`/`@return` phpdoc comments are redundant with the type hints

**Review by kesselb — APPROVED** [review]

File: lib/private/Http/Client/DnsPinMiddleware.php (hunk 2 above)
Comment (DerDreschner) [reply lib/private/Http/Client/DnsPinMiddleware.php]: True, I have to figure out how to get PhpStorm to not do that when adding phpdoc comments.

**Review by provokateurin — APPROVED** [review]

**Comment by DerDreschner** [comment]
I've realized that my fix has an unexpected side effect. It totally prevents the usage of relative domains, as all domains are being treated as FQDNs from a DNS point of view. That's totally fine for the app store - but a bit unexpected for other developers and might break some apps, as it's usually possible to use both relative and absolute domains on any HTTP request. As most apps use our implementation, I lean on fixing it before someone might complain about it (and hence merging it into stable33 and stable32).

I can think of two ways to tackle that:
1. Put the list of IANA root zones into the `resources` folder (probably cache it for performance reasons) and check against that before marking the domain as an FQDN.
2. Rewrite the DNS pinning: Let cURL resolve the domain name, lookup the SOA record and then cache the result and inject it into any further request for the specified TTL.

The [suggested change here](https://github.com/nextcloud/server/issues/56489#issuecomment-3618577745) to discard the record if it doesn't match the requested host would have the same unexpected side effect as my fix does. So, that solution is not possible, unfortunately. Also, as the example with `github.com.dreschner.net` demonstrates, we're unable to just check if the domain is likely a hostname (has no dot in it).

Any thoughts on this? @kesselb @provokateurin @ChristophWurst

**Comment by ChristophWurst** [comment]
Unfortunately I absolutely lack expertise in this area. I don't know.

**Comment by kesselb** [comment]
> Rewrite the DNS pinning: Let cURL resolve the domain name, lookup the SOA record and then cache the result and inject it into any further request for the specified TTL.

I've looked into that a while ago, because resolving via curl would also address some issues in gated networks using proxies for outgoing connections, but it wasnt possible at this time.

Since PHP 8.4 we have https://www.php.net/manual/en/curl.constants.php#constant.curlopt-prereqfunction, that could work. However we have the connection established already, so not ideal either. Also not usable for us at the moment because PHP 8.4 or newer.

**Comment by DerDreschner** [comment]
> I've looked into that a while ago, because resolving via curl would also address some issues in gated networks using proxies for outgoing connections, but it wasnt possible at this time.

Ohh, do you have more information about that for me?

I was looking into this during my vacation and it's possible with a little trick using the `on_stats` [request option](https://docs.guzzlephp.org/en/stable/request-options.html#on-stats) as being [described here](https://github.com/guzzle/guzzle/issues/1584#issuecomment-425237576) in 2018. I would guess that the mentioned `CURLOPT_PREREQFUNCTION` is just another way to access the information without using Guzzle.

Additionally, we only get the IP the connection is being established to. If there are multiple A / AAAA records, there is no way we can switch over in case of a failure. I wanted to make a test to see how browsers like Firefox handle that case to see if that is something I should really care about or can ignore safely with DNS Pinning (e.g., to prevent malicious redirects).

I was leaning towards the second option for that reason... But as there may be other features in the future we would have to implement ourself then as well, like DNS over TLS, I honestly don't like doing so.

**Comment by kesselb** [comment]
Case 1)

Private network. Outgoing connections are only possible through HTTP proxy. The nextcloud host could only resolve internal domain names through the DNS resolver. Hence the only option was to disable DNS pinning because we were unable to resolve external domain names. Requests themselves were possible because resolving did happen through the proxy.

Case 2)

https://github.com/nextcloud/server/issues/55847
