### PR TITLE
Fix deletion of additional emails

### LINKED ISSUE #31164: [Bug]: Adding and removing additional e-mail adress
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

1. When deleting the secondary email address added first, the edit menu for the second email address is not shown. To delete the second e-mail address you need a page refresh.

Screenshot:

- Adding two email addresses:

obraz

- Gray inactive menu button for editing the email address added as the second:

obraz

- The email address menu is only active after refreshing the page:

obraz

2. When adding an additional email address, the description "Primary email for password reset and notifications" appears. In my opinion, it is unnecessarily duplicated.

Screenshot:

obraz

### Steps to reproduce

1. Select "Personal info".
2. Add an additional email address.
3. Add a second additional email address.
4. Delete the first additional email address.
5. Try to delete the second email address.

### Expected behavior

1. While deleting email addresses, every email address editing menu should be active, no matter which one you delete first.
2. Deletion of duplicate email description "Primary email for password reset and notifications" when adding an additional email address.

@blizzz Can you fix it?

### Installation method

Manual installation

### Operating system

_No response_

### PHP engine version

PHP 7.3

### Web server

_No response_

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

_No response_

### Are you using the Nextcloud Server Encryption module?

_No response_

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
Accessibility 1.9.0
Activity 2.15.0
Circles 23.0.1
Collaborative tags 1.13.0
Comments 1.13.0
Contacts Interaction 1.4.0
Dashboard 7.3.0
Deleted files 1.13.0
Federation 1.13.0
File sharing 1.15.0
First run wizard 2.12.0
Gestion 2.0.4
Log Reader 2.8.0
Monitoring 1.13.0
Nextcloud announcements 1.12.0
Notes 4.3.0
Notifications 2.11.1
Password policy 1.13.0
PDF viewer 2.4.0
Photos 1.5.0
Privacy 1.7.0
Recommendations 1.2.0
Right click 1.2.0
Share by mail 1.13.0
Support 1.6.0
Text 3.4.0
Theming 1.14.0
Update notification 1.13.0
Usage survey 1.11.0
User status 1.3.1
Versions 1.16.0
Video player 1.12.0
Weather status 1.3.0
Auditing / Logging 1.13.0
Default encryption module 2.11.0
External storage support 1.15.0
LDAP user and group backend 1.13.1
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by Pytal**
Fix https://github.com/nextcloud/server/issues/31164

Using index as the key would cause data from a deleted email to persist into the additional email at the same index due to the component being reused, this is resolved by forcing component replacement with unique string keys

### CODE REVIEW

**Review by blizzz — APPROVED** [review]

File: apps/settings/src/components/PersonalInfo/EmailSection/EmailSection.vue [hunk 1]
```diff
@@ -184,6 +185,10 @@ export default {
 				this.logger.error(errorMessage, error)
 			}
 		},
+
+		generateUniqueKey() {
+			return Math.random().toString(36).substring(2)
```
Comment (PVince81) [inline apps/settings/src/components/PersonalInfo/EmailSection/EmailSection.vue:190]: you can use https://lodash.com/docs/#uniq

Comment (Pytal) [reply apps/settings/src/components/PersonalInfo/EmailSection/EmailSection.vue:190]: For the array?

Comment (Pytal) [reply apps/settings/src/components/PersonalInfo/EmailSection/EmailSection.vue:190]: On the array you mean?

Comment (Pytal) [reply apps/settings/src/components/PersonalInfo/EmailSection/EmailSection.vue:190]: On the array you mean? In which case could you elaborate?

File: apps/settings/src/components/PersonalInfo/EmailSection/EmailSection.vue [hunk 2]
```diff
@@ -46,8 +46,9 @@
 
 		<template v-if="additionalEmails.length">
 			<em class="additional-emails-label">{{ t('settings', 'Additional emails') }}</em>
+			<!-- TODO use additional email itself as key when uniqueness can be guaranteed, see https://github.com/nextcloud/server/issues/26866 -->
 			<Email v-for="(additionalEmail, index) in additionalEmails"
-				:key="index"
+				:key="additionalEmail.key"
```
Comment (artonge) [inline apps/settings/src/components/PersonalInfo/EmailSection/EmailSection.vue:51]:
```suggestion
				:key="index+additionalEmail.value"
```

Comment (Pytal) [reply apps/settings/src/components/PersonalInfo/EmailSection/EmailSection.vue:51]: This wouldn't work as:
1) The email value is updated on every keypress so the component gets replaced and loses input focus on every keypress, the key has to be unique and also not dependent on the value
2) Since additional emails are not unique for the reasons in https://github.com/nextcloud/server/issues/26866, if two duplicate emails are at consecutive indices then deleting the first one will result in the component being reused and cross-contamination of component data i.e. if the first one has "Published" scope and the second has "Local" scope when you delete the first one the second will reuse the data and have an incorrect scope

**Comment by Pytal** [comment]
Now uses https://lodash.com/docs/4.17.15#uniqueId to generate the unique key

File: apps/settings/src/components/PersonalInfo/EmailSection/EmailSection.vue (hunk 1 above)
Comment (skjnldsv) [reply apps/settings/src/components/PersonalInfo/EmailSection/EmailSection.vue]: Also, please don't use lodash. 
https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_uniq

**Review by skjnldsv — COMMENTED** [review]
> Now uses [lodash.com/docs/4.17.15#uniqueId](https://lodash.com/docs/4.17.15#uniqueId) to generate the unique key

I don't like the idea of using lodash. Relying on external libraries for things as simple as this isn't really the most efficient move I would say :)

Just doing any `Math.random().toString(36).substring(2)` like you did is enough imho.
Importing uniqueId doesn't adds much (82B vs 39B), but it's just a good pattern I thik. In the end we should move away from lodash, jQuery and other "tooling" libs that vanilla js can do noaways :wink:

**Comment by PVince81** [comment]
> > Now uses [lodash.com/docs/4.17.15#uniqueId](https://lodash.com/docs/4.17.15#uniqueId) to generate the unique key
> 
> I don't like the idea of using lodash. Relying on external libraries for things as simple as this isn't really the most efficient move I would say :)
> 
> Just doing any `Math.random().toString(36).substring(2)` like you did is enough imho. Importing uniqueId doesn't adds much (82B vs 39B), but it's just a good pattern I thik. In the end we should move away from lodash, jQuery and other "tooling" libs that vanilla js can do noaways wink

I thought it was already imported as we used it in other places. Let's not import it then.

My worry was more that more frontend developers will invent their own key algorithms in various places (with a certain risk of collisions), so perhaps we could add a method in the "OC." namespace that does the equivalent of what lodash does, so that every app dev can use it.
As far as I remember lodash uses a prefix + number and simply increments a number for every call, so it doesn't risk any collisions

**Comment by PVince81** [comment]
(the latter comment was provided to you by someone who's used to chase ghosts, aka bugs that seldom happen and still caused nasty issues, so I'm usually trying to be more careful about probabilities as I tend to be unlucky there)

**Comment by Pytal** [comment]
> I don't like the idea of using lodash. Relying on external libraries for things as simple as this isn't really the most efficient move I would say :)

Yes I did `Math.random().toString(36).substring(2)` as this was my thinking as well, changed it back now

> My worry was more that more frontend developers will invent their own key algorithms in various places (with a certain risk of collisions), so perhaps we could add a method in the "OC." namespace that does the equivalent of what lodash does, so that every app dev can use it.

This is a valid concern but as stated above by @skjnldsv something as simple as unique id generation without any business logic specific requirements does not warrant another abstraction. Whether we make a shared unique id generation method or not is outside the scope of this specific PR and any discussions should be started elsewhere

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@Pytal please resolve the conflicts, not sure if rebasing is necessary considering possible recent changes on master
