### PR TITLE
Convert theming app logo to PNG to show it properly in emails

### LINKED ISSUE #8627: SVG-logos provided via theming can not be rendered in mail-clients
https://github.com/nextcloud/server/issues/4647 fix is not working if you have provided your own SVG-logo via `theming`-app.

As discussed @juliushaertl 😉

### PR DESCRIPTION
**Pull request by juliusknorr**
fixes https://github.com/nextcloud/server/issues/8627

This change will add support for a `$useSvg` parameter to the theming app, so that other parts of the code (like the MailTemplate) can request an image that is not an SVG. This is required for some email clients.

As for the other svg conversion stuff, it requires Imagick with svg support being installed.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> waiting for #8540

Done.

**Comment by juliushaertl** [comment]
Ready for review @nextcloud/theming

**Comment by juliushaertl** [comment]
Rebased :wink:

File: apps/theming/lib/ImageManager.php [hunk 1]
```diff
@@ -165,6 +187,12 @@ public function delete(string $key) {
 		} catch (NotFoundException $e) {
 		} catch (NotPermittedException $e) {
 		}
+		try {
+			$file = $this->appData->getFolder('images')->getFile($key . '.png');
+			$file->delete();
+		} catch (NotFoundException $e) {
+		} catch (NotPermittedException $e) {
+		}
```
Comment (ChristophWurst) [inline apps/theming/lib/ImageManager.php]: I'd prefer having a comment stating why we ignore the exception here ;)

File: apps/theming/lib/ThemingDefaults.php [hunk 2]
```diff
@@ -312,23 +312,12 @@ public function replaceImagePath($app, $image) {
 	 * Check if Imagemagick is enabled and if SVG is supported
 	 * otherwise we can't render custom icons
 	 *
+	 * TODO: move to usage of image manager
```
Comment (ChristophWurst) [inline apps/theming/lib/ThemingDefaults.php]: is this a todo for later PRs or this one?

File: apps/theming/tests/ImageManagerTest.php [hunk 3]
```diff
@@ -42,19 +44,36 @@ class ImageManagerTest extends TestCase {
...
+			$this->cacheFactory
 		);
 	}
 
+	private function checkImagick() {
+		if(!extension_loaded('imagick')) {
+			$this->markTestSkipped('Imagemagick is required for dynamic icon generation.');
+		}
+		$checkImagick = new \Imagick();
+		if (count($checkImagick->queryFormats('SVG')) < 1) {
```
Comment (ChristophWurst) [inline apps/theming/tests/ImageManagerTest.php]: nit: `empty` might make the code a bit easier to read

File: apps/theming/tests/ImageManagerTest.php [hunk 4]
```diff
@@ -42,19 +44,36 @@ class ImageManagerTest extends TestCase {
...
+			$this->markTestSkipped('No SVG provider present.');
+		}
+		if (count($checkImagick->queryFormats('PNG')) < 1) {
```
Comment (ChristophWurst) [inline apps/theming/tests/ImageManagerTest.php]: same here

**Review by ChristophWurst — DISMISSED** [review]

**Comment by juliushaertl** [comment]
I've addressed the comments by @ChristophWurst

**Review by rullzer — APPROVED** [review]
Fine by me then :D

File: apps/theming/lib/ImageManager.php [hunk 5]
```diff
@@ -79,21 +83,39 @@ public function getImageUrl(string $key): string {
...
+		if (!$useSvg && $this->shouldReplaceIcons()) {
+			if (!$folder->fileExists($key . '.png')) {
+				try {
+					$finalIconFile = new \Imagick();
+					$finalIconFile->setBackgroundColor('none');
+					$finalIconFile->readImageBlob($folder->getFile($key)->getContent());
+					$finalIconFile->setImageFormat('png32');
+					$pngFile = $folder->newFile($key . '.png');
+					$pngFile->putContent($finalIconFile->getImageBlob());
+				} catch (\ImagickException $e) {
```
Comment (MorrisJobke) [inline apps/theming/lib/ImageManager.php]: We should log something here. I'm fine with a lower log level, but completely ignoring it seems wrong. Also because we catch the exception and then later return the `$pngFile`. 🤔

Comment (juliushaertl) [reply apps/theming/lib/ImageManager.php]: Right, a log message makes sense. And we should just return the svg in cases when the png conversion fails.

Comment (juliushaertl) [reply apps/theming/lib/ImageManager.php]: Added a log message at INFO level.

**Comment by skjnldsv** [comment]
Ci is crying :sob:

File: apps/theming/lib/Controller/ThemingController.php [hunk 6]
```diff
@@ -356,12 +358,13 @@ public function undo(string $setting): DataResponse {
 	 * @NoCSRFRequired
 	 *
 	 * @param string $key
+	 * @param bool $useSvg
 	 * @return FileDisplayResponse|NotFoundResponse
-	 * @throws \Exception
+	 * @throws NotPermittedException
```
Comment (skjnldsv) [inline apps/theming/lib/Controller/ThemingController.php]: NotFoundResponse ?

File: apps/theming/lib/ImageManager.php (hunk 1 above)
Comment (skjnldsv) [reply apps/theming/lib/ImageManager.php]: Seconded

**Review by skjnldsv — APPROVED** [review]
Two comments, otherwise looks good :) :1st_place_medal:

File: apps/theming/lib/Controller/ThemingController.php (hunk 6 above)
Comment (juliushaertl) [reply apps/theming/lib/Controller/ThemingController.php]: The NotFoundException is catched, and then the method returns a NotFoundResponse (404).

**Comment by MariusBluem** [comment]
@juliushaertl We've talked about a backport in the past... Do you think that's possible?

**Comment by juliushaertl** [comment]
@MariusBluem A backport would be doable but a bit more work, since the class layout changed due to the additional theming options that are available in master but not in 13. Any opinions on that @rullzer @MorrisJobke ?

**Comment by MorrisJobke** [comment]
> @MariusBluem A backport would be doable but a bit more work, since the class layout changed due to the additional theming options that are available in master but not in 13. Any opinions on that @rullzer @MorrisJobke ?

Something for 14 only I would say.
