### PR TITLE
Remove deleted groups from app restrictions fixes #15823

### LINKED ISSUE #15823: App restricted-to list keeps usergroups that no longer exist [NC 16.0.1]
### Steps to reproduce
1. Restrict any app to a specific user group.
2. Delete the user group in the user management.
3. The restricted-to list of the app still contains the non-existant group.

### Expected behaviour
1. The app's restricted-to list should no longer contain a non-existant usergroup.
2. If it was the last group in the restricted-to list, then probably the app should be deactivated. (I was thinking about that for a while, but so far no better solution came to my mind.)

### Actual behaviour
When installing a Nextcloud app, it is possible to restrict it to certain user groups. Yet after a group ceases to exit (=deleted in user management), the non-existant usergroup still appears in the restricted-to list of that app.

### Server configuration

**Operating system**: Ubuntu (Shared hosting)

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.3

**Nextcloud version:** NC 16.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** upgrades since 12.x

**Where did you install Nextcloud from:** web installer

### PR DESCRIPTION
**Pull request by GretaD**
Fixes #15823
After a group is deleted from the user manager, it is also removed from the restriction group list

### CODE REVIEW

File: lib/private/App/AppManager.php [hunk 1]
```diff
@@ -203,6 +225,33 @@ private function checkAppForUser($enabled, $user) {
 		}
 	}
 
+	/**
+	 * @param $enabled
+	 * @param IGroup $group
+	 * @return bool
+	 */
+	private function checkAppForGroups ($enabled, $group) {
```
Comment (nickvergessen) [inline lib/private/App/AppManager.php]:
```suggestion
	private function checkAppForGroups(string $enabled, IGroup $group): bool {
```

File: lib/public/App/IAppManager.php [hunk 2]
```diff
@@ -158,4 +158,18 @@ public function isShipped($appId);
...
+	 * @since 17.0.0
+	 */
+	public function getEnabledAppsForGroups($group);
+
+	/**
+	 * @param String $appId
+	 * @returns String[]|null
+	 * @since 17.0.0
+	 */
+	public function getAppRestriction($appId);
```
Comment (nickvergessen) [inline lib/public/App/IAppManager.php]:
```suggestion
	public function getAppRestriction(string $appId): array;
```

File: lib/public/App/IAppManager.php [hunk 3]
```diff
@@ -158,4 +158,18 @@ public function isShipped($appId);
 	 * @since 9.0.0
 	 */
 	public function getAlwaysEnabledApps();
+
+	/**
+	 * @param \OCP\IGroup $group
+	 * @returns String[]
+	 * @since 17.0.0
+	 */
+	public function getEnabledAppsForGroups($group);
```
Comment (nickvergessen) [inline lib/public/App/IAppManager.php]:
```suggestion
	public function getEnabledAppsForGroups(IGroup $group): string;
```

File: lib/public/App/IAppManager.php [hunk 4]
```diff
@@ -158,4 +158,18 @@ public function isShipped($appId);
...
+
+	/**
+	 * @param String $appId
+	 * @returns String[]|null
```
Comment (nickvergessen) [inline lib/public/App/IAppManager.php]:
```suggestion
	 * @returns string[]
```

File: lib/private/App/AppManager.php [hunk 5]
```diff
@@ -203,6 +225,33 @@ private function checkAppForUser($enabled, $user) {
 		}
 	}
 
+	/**
+	 * @param $enabled
```
Comment (nickvergessen) [inline lib/private/App/AppManager.php]:
```suggestion
	 * @param string $enabled
```

File: lib/private/App/AppManager.php [hunk 6]
```diff
@@ -148,6 +149,27 @@ public function getEnabledAppsForUser(IUser $user) {
...
+	 * @return array
+	 */
+	public function getEnabledAppsForGroups($group) {
+		$apps = $this->getInstalledAppsValues();
+		$appsForGroups = array_filter($apps, function ($enabled) use ($group) {
+			return $this->checkAppForGroups($enabled, $group);
+		});
+		return array_keys($appsForGroups);
+	}
+	public function getAppRestriction($appname) {
```
Comment (nickvergessen) [inline lib/private/App/AppManager.php]:
```suggestion
	public function getAppRestriction(string $appId): array {
```

Also use `$appId` inside please, so it's consistent with the remaining code

File: lib/private/App/AppManager.php [hunk 7]
```diff
@@ -148,6 +149,27 @@ public function getEnabledAppsForUser(IUser $user) {
...
+		$values = $this->getInstalledAppsValues();
+
+		if ($values[$appname] === 'yes' || $values[$appname] === 'no') {
+			return null;
```
Comment (nickvergessen) [inline lib/private/App/AppManager.php]:
```suggestion
			return [];
```

File: lib/private/App/AppManager.php [hunk 8]
```diff
@@ -148,6 +149,27 @@ public function getEnabledAppsForUser(IUser $user) {
 		return array_keys($appsForUser);
 	}
 
+	/**
+	 * @param \OCP\IGroup $group
+	 * @return array
+	 */
+	public function getEnabledAppsForGroups($group) {
```
Comment (nickvergessen) [inline lib/private/App/AppManager.php]:
```suggestion
	public function getEnabledAppsForGroups(IGroup $group): array {
```

File: lib/private/App/AppManager.php [hunk 9]
```diff
@@ -148,6 +149,27 @@ public function getEnabledAppsForUser(IUser $user) {
...
+		});
+		return array_keys($appsForGroups);
+	}
+	public function getAppRestriction(string $appId): array {
+		$values = $this->getInstalledAppsValues();
+
+		if ($values[$appname] === 'yes' || $values[$appname] === 'no') {
+			return [];
+		}
+	return json_decode($values[$appname]);
```
Comment (georgehrke) [inline lib/private/App/AppManager.php]: indentation

File: lib/private/App/AppManager.php [hunk 10]
```diff
@@ -148,6 +149,27 @@ public function getEnabledAppsForUser(IUser $user) {
...
+	 * @return array
+	 */
+	public function getEnabledAppsForGroups(IGroup $group): array {
+		$apps = $this->getInstalledAppsValues();
+		$appsForGroups = array_filter($apps, function ($enabled) use ($group) {
+			return $this->checkAppForGroups($enabled, $group);
+		});
+		return array_keys($appsForGroups);
+	}
+	public function getAppRestriction(string $appId): array {
```
Comment (georgehrke) [inline lib/private/App/AppManager.php]: Please add an empty line and a phpdoc comment block :)

File: lib/base.php [hunk 11]
```diff
@@ -848,6 +849,30 @@ private static function registerAccountHooks() {
...
 	}
 
+	private static function registerAppRestrictionsHooks() {
+		$groupManager = self::$server->query(\OCP\IGroupManager::class);
+		$groupManager->listen ('\OC\Group', 'postDelete', function (\OCP\IGroup $group) {
+			$appManager = self::$server->getAppManager();
+			$apps = $appManager->getEnabledAppsForGroups($group);
+			foreach ($apps as $appId) {
+				$restrictions = $appManager->getAppRestriction($appId);
+				if ($restrictions === null) {
```
Comment (georgehrke) [inline lib/base.php]: Since you changed `getAppRestriction` as per @nickvergessen suggestions, you need to check if restrictions is an empty array here

File: lib/private/App/AppManager.php [hunk 12]
```diff
@@ -268,16 +317,22 @@ public function enableAppForGroups($appId, $groups) {
 
 		$groupIds = array_map(function ($group) {
 			/** @var \OCP\IGroup $group */
-			return $group->getGID();
+			return ($group instanceof IGroup)
```
Comment (georgehrke) [inline lib/private/App/AppManager.php]: It would be good to update the phpblock to allow an array of IGroup or strings:
`@param \OCP\IGroup[]|String[] $groups`

File: lib/private/App/AppManager.php [hunk 13]
```diff
@@ -268,16 +317,22 @@ public function enableAppForGroups($appId, $groups) {
...
 		$this->appConfig->setValue($appId, 'enabled', json_encode($groupIds));
 		$this->dispatcher->dispatch(ManagerEvent::EVENT_APP_ENABLE_FOR_GROUPS, new ManagerEvent(
 			ManagerEvent::EVENT_APP_ENABLE_FOR_GROUPS, $appId, $groups
 		));
 		$this->clearAppsCache();
+
+
 	}
 
+
```
Comment (georgehrke) [inline lib/private/App/AppManager.php]: unnecessary new line

File: lib/base.php (hunk 11 above)
Comment (GretaD) [reply lib/base.php]: ok, but I don't use Arch ;)
cc @skjnldsv @ChristophWurst @juliushaertl

**Comment by georgehrke** [comment]
Please add unit tests :)

**Review by skjnldsv — COMMENTED** [review]
Nice job! :)
Same comment as Georg!

File: lib/private/App/AppManager.php [hunk 14]
```diff
@@ -148,6 +149,32 @@ public function getEnabledAppsForUser(IUser $user) {
 		return array_keys($appsForUser);
 	}
 
+	/**
+	 * @param \OCP\IGroup $group
+	 * @return array
+	 */
+	public function getEnabledAppsForGroups(IGroup $group): array {
```
Comment (georgehrke) [inline lib/private/App/AppManager.php]: Please change to getEnabledAppsForGroup :)

**Review by georgehrke — APPROVED** [review]
👍 👍 👍

File: lib/private/App/AppManager.php [hunk 15]
```diff
@@ -203,12 +234,40 @@ private function checkAppForUser($enabled, $user) {
...
+		} else {
+			if (empty($enabled)) {
+				return false;
+			}
+
+			$groupIds = json_decode($enabled);
+
+			if (!is_array($groupIds)) {
+				$jsonError = json_last_error();
+				\OC::$server->getLogger()->warning('AppManger::checkAppForUser - can\'t decode group IDs: ' . print_r($enabled, true) . ' - json error code: ' . $jsonError, ['app' => 'lib']);
```
Comment (MorrisJobke) [inline lib/private/App/AppManager.php]: Mind to inject `ILogger $logger` into the constructor and use here then the `$this->logger`?

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍
