### PR TITLE
Fix settings chunk loading

### LINKED ISSUE #21024: Apps and Users pages are showing a blank white screen on Migrated Instance
### Expected behaviour
The Apps and Users pages should load allowing me to use those pages

### Actual behaviour
After migrating a Nextcloud install (Docker based with Docker MySQL backend), from one server to another, a blank white page is displayed when navigating to Apps or Users from the Admin menu.  The Settings page loads fine, however.  When navigating to Apps or Users pages I see the following error in the Javascript console:

```
vue-settings-apps-users-management.js?v=e4b8f946-13:45 ChunkLoadError: Loading chunk 0 failed.
(missing: https://cloud.mydomain.com/apps/settings/js/vue-0.js?v=9809a76d427d04d0282b)
    at Function.o.e (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:1:813)
    at Yt (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:45:91718)
    at https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:45:80702
    at https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:45:80947
    at Array.map (<anonymous>)
    at https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:45:80924
    at Array.map (<anonymous>)
    at St (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:45:80875)
    at https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:45:80341
    at d (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:45:83586)
    at r (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:45:80243)
    at r (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:45:80270)
    at At (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:45:80278)
    at e.Pt.confirmTransition (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:45:83813)
    at e.Pt.transitionTo (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:45:82601)
    at Ht.init (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:45:88949)
    at An.beforeCreate (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:45:91006)
    at zt (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:7:11267)
    at en (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:7:25191)
    at An.t._init (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:7:32598)
    at new An (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:7:30225)
    at Module.<anonymous> (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:112:251)
    at o (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:1:361)
    at https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:1:2156
    at https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:1:2167
```

### Server configuration

**Operating system:**
Ubuntu 20.04

**Web server:**
Apache

**Database:**
MariaDB/MySQL

**PHP version:**
7.3.17

**Nextcloud version:** (see Nextcloud admin page)
18.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 16 as the original Version

**Where did you install Nextcloud from:**
Docker Image

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - bruteforcesettings: 1.6.0
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - drawio: 0.9.5
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notes: 3.3.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - richdocuments: 3.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.3
  - updatenotification: 1.8.0
  - video_converter: 0.1.4
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - calendar
  - deck
  - encryption
  - files_external
  - gallery
  - mail
  - music
  - tasks
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.21",
            "cloud.mydomain.com:443"
        ],
        "dbtype": "mysql",
        "version": "18.0.4.2",
        "overwrite.cli.url": "https:\/\/cloud.mydomain.com:443",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.11.0",
            "notify_email_calendar": "0",
            "notify_email_calendar_event": "0",
            "notify_email_calendar_todo": "0",
            "notify_email_comments": "1",
            "notify_email_deck": "0",
            "notify_email_deck_card_description": "0",
            "notify_email_deck_comment": "0",
            "notify_email_favorite": "0",
            "notify_email_file_changed": "0",
            "notify_email_file_created": "0",
            "notify_email_file_deleted": "1",
            "notify_email_file_restored": "0",
            "notify_email_public_links": "0",
            "notify_email_remote_share": "1",
            "notify_email_shared": "1",
            "notify_email_systemtags": "0",
            "notify_setting_batchtime": "3600",
            "notify_setting_self": "1",
            "notify_setting_selfemail": "0",
            "notify_stream_calendar": "1",
            "notify_stream_calendar_event": "1",
            "notify_stream_calendar_todo": "1",
            "notify_stream_comments": "1",
            "notify_stream_deck": "1",
            "notify_stream_deck_card_description": "1",
            "notify_stream_favorite": "1",
            "notify_stream_file_changed": "1",
            "notify_stream_file_created": "1",
            "notify_stream_file_deleted": "1",
            "notify_stream_file_favorite": "0",
            "notify_stream_file_restored": "1",
            "notify_stream_public_links": "1",
            "notify_stream_remote_share": "1",
            "notify_stream_shared": "1",
            "notify_stream_systemtags": "1",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "1230"
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "calendar": {
            "enabled": "no",
            "installed_version": "2.0.3",
            "types": ""
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "3.3.0",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "enterpriseLogoChecked": "yes",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1570062764.3172",
            "lastcron": "1589762401",
            "lastupdateResult": "[]",
            "lastupdatedat": "1589760352",
            "oc.integritycheck.checker": "[]",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "theming.variables": "4e6133f3589c34d3c3d89e214a688ffa",
            "updater.secret.created": "1587652143",
            "vendor": "nextcloud"
        },
        "dav": {
            "buildCalendarReminderIndex": "yes",
            "buildCalendarSearchIndex": "yes",
            "chunks_migrated": "1",
            "enabled": "yes",
            "installed_version": "1.14.0",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "sendEventRemindersPush": "yes",
            "types": "filesystem"
        },
        "deck": {
            "enabled": "no",
            "installed_version": "1.0.0",
            "types": "dav"
        },
        "drawio": {
            "enabled": "yes",
            "installed_version": "0.9.5",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.13.1",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "0.15.2",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.10.1",
            "types": "filesystem"
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.7.0",
            "types": "logging"
        },
        "gallery": {
            "enabled": "no",
            "installed_version": "18.4.0",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.3.0",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "authentication"
        },
        "mail": {
            "enabled": "no",
            "installed_version": "1.3.4",
            "types": ""
        },
        "music": {
            "enabled": "no",
            "installed_version": "0.14.0",
            "ocsid": "164319",
            "types": "filesystem"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notes": {
            "enabled": "yes",
            "installed_version": "3.3.0",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.6.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "passwords": {
            "SSEv1ServerKey": "fImJ5i467hnDe4sJA6ZU4v5tCnG6vPHKmhzcsrlvrS9Hq6BTtmOAq4feQ63CTnY4BQIqIBDtjbmE4ZiHTTiuSa\/BReDeEQgOtpMSYON2k72CwXwDvE0jHDZHEAL1Qdm06Hz4sscIzGRfCRB432lnrod+\/PfphjXM3QBPFZwdv+QFj59GPPf\/TqKVS4Wt+dtVloDi6ABt9y23r2b\/CHtDiEyvcQRu\/V2E+gvMLHfTICfYdHPMlZ8veV\/7VKU\/LGliLzynqUkwVcHENMuv6RdkUhPCfjxpTwogp1nW7dPpYHyY4up0c3v7OvbpR9TqdQ2tgifYcYSwPKMY6epYWmQpL7McQ+vRuJ3jVO5ggIMUXEfz+CcJKIQWK5BUsCNCJti+wK1T+wltvZa1rGyeWv4RrnswufiEoB1kJdCcBX5gnNaF5V0SW1JYaZhLZChHy5qZDX09moyyLwenUguAqv8ohxWKJBn1B3mBVkLyIwmU4IcPxhvmJf8tC5Qbr9ErJ3XvnBxHKGqMdhBBJsR7zBsPDvGPZ4Dih8+qle1yFjhmEtT2NmzXrvp7YIKFiDe3S\/iBVkDU8I+n4CCCDnco60M\/JsIFhwgjNQDOyqiOJTqBjpaFBZmxLECjHjlv1HnoqDXPaukpcPScanrgFbreC8snSLujCOScMNtFrC0CHOJRPmmQNH653KSm82dK+C7imNNKq60T7swqlIWotjH8czmZurgqXBSqjtCJpKlcucH0gk7S0YElIs4ABiRngt+5xayN4QzfIaCspV\/OhxJN9LiYEC9zAiFSID1NhgL0HinvcQ+37645yxXTJqDG4TAVGL2hqI3RBAqWD\/0lqNitFUtWYQFHHyURKlMpQSWpBs6vtpjifn3H0t96sGHd+sgOaEXdcB9KJhicRK0WxqsFoFZ46vRoi6Q8NrjJCGN3\/yBFWQxIBBm6AAYJgn8upXjSN4upbMgz\/g3w08z3zpt9wVI8cuolL3cAxeJNtJMpW5nK8dQb3ZWDlhHXwj0Fzay2W5vb",
            "enabled": "no",
            "installed_version": "2019.10.0",
            "service\/favicon": "fg",
            "service\/preview": "default",
            "survey\/server\/mode": "0",
            "types": ""
        },
        "photos": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "readableLocation": "us",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "prevent_group_restriction"
        },
        "rainloop": {
            "enabled": "no",
            "installed_version": "6.0.4",
            "types": ""
        },
        "recommendations": {
            "enabled": "yes",
            "installed_version": "0.6.0",
            "types": ""
        },
        "richdocuments": {
            "disable_certificate_verification": "",
            "enabled": "yes",
            "installed_version": "3.6.0",
            "public_wopi_url": "https:\/\/collabora.oluhome.com",
            "types": "filesystem,dav,prevent_group_restriction",
            "wopi_url": "http:\/\/collabora.oluhome.com:80"
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "settings": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem"
        },
        "support": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "session"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "last_report": "{\"id\":\"ocxyj6s06v4n\",\"items\":[[\"server\",\"version\",\"18.0.1.3\"],[\"server\",\"code\",\"other\"],[\"server\",\"enable_avatars\",\"yes\"],[\"server\",\"enable_previews\",\"yes\"],[\"server\",\"memcache.local\",\"\\\\OC\\\\Memcache\\\\APCu\"],[\"server\",\"memcache.distributed\",\"none\"],[\"server\",\"asset-pipeline.enabled\",\"no\"],[\"server\",\"filelocking.enabled\",\"yes\"],[\"server\",\"memcache.locking\",\"none\"],[\"server\",\"debug\",\"no\"],[\"server\",\"cron\",\"cron\"],[\"php\",\"version\",\"7.3.14\"],[\"php\",\"memory_limit\",536870912],[\"php\",\"max_execution_time\",3600],[\"php\",\"upload_max_filesize\",1073741824],[\"database\",\"type\",\"mysql\"],[\"database\",\"version\",\"10.4.12\"],[\"database\",\"size\",13549568],[\"apps\",\"accessibility\",\"1.4.0\"],[\"apps\",\"activity\",\"2.11.0\"],[\"apps\",\"bruteforcesettings\",\"1.5.0\"],[\"apps\",\"calendar\",\"2.0.2\"],[\"apps\",\"cloud_federation_api\",\"1.1.0\"],[\"apps\",\"comments\",\"1.8.0\"],[\"apps\",\"contacts\",\"3.2.0\"],[\"apps\",\"dav\",\"1.14.0\"],[\"apps\",\"deck\",\"0.8.0\"],[\"apps\",\"drawio\",\"0.9.5\"],[\"apps\",\"federatedfilesharing\",\"1.8.0\"],[\"apps\",\"federation\",\"1.8.0\"],[\"apps\",\"files\",\"1.13.1\"],[\"apps\",\"files_pdfviewer\",\"1.7.0\"],[\"apps\",\"files_rightclick\",\"0.15.2\"],[\"apps\",\"files_sharing\",\"1.10.1\"],[\"apps\",\"files_trashbin\",\"1.8.0\"],[\"apps\",\"files_versions\",\"1.11.0\"],[\"apps\",\"files_videoplayer\",\"1.7.0\"],[\"apps\",\"firstrunwizard\",\"2.7.0\"],[\"apps\",\"gallery\",\"disabled\"],[\"apps\",\"logreader\",\"2.3.0\"],[\"apps\",\"lookup_server_connector\",\"1.6.0\"],[\"apps\",\"mail\",\"1.1.3\"],[\"apps\",\"music\",\"0.13.0\"],[\"apps\",\"nextcloud_announcements\",\"1.7.0\"],[\"apps\",\"notes\",\"3.1.5\"],[\"apps\",\"notifications\",\"2.6.0\"],[\"apps\",\"oauth2\",\"1.6.0\"],[\"apps\",\"password_policy\",\"1.8.0\"],[\"apps\",\"passwords\",\"disabled\"],[\"apps\",\"photos\",\"1.0.0\"],[\"apps\",\"privacy\",\"1.2.0\"],[\"apps\",\"provisioning_api\",\"1.8.0\"],[\"apps\",\"rainloop\",\"disabled\"],[\"apps\",\"recommendations\",\"0.6.0\"],[\"apps\",\"richdocuments\",\"3.5.2\"],[\"apps\",\"serverinfo\",\"1.8.0\"],[\"apps\",\"settings\",\"1.0.0\"],[\"apps\",\"sharebymail\",\"1.8.0\"],[\"apps\",\"support\",\"1.1.0\"],[\"apps\",\"survey_client\",\"1.6.0\"],[\"apps\",\"systemtags\",\"1.8.0\"],[\"apps\",\"tasks\",\"0.11.3\"],[\"apps\",\"text\",\"2.0.0\"],[\"apps\",\"theming\",\"1.9.0\"],[\"apps\",\"twofactor_backupcodes\",\"1.7.0\"],[\"apps\",\"twofactor_totp\",\"4.1.2\"],[\"apps\",\"updatenotification\",\"1.8.0\"],[\"apps\",\"viewer\",\"1.2.0\"],[\"apps\",\"workflowengine\",\"2.0.0\"],[\"stats\",\"num_files\",10432],[\"stats\",\"num_users\",3],[\"stats\",\"num_storages\",4],[\"stats\",\"num_storages_local\",1],[\"stats\",\"num_storages_home\",3],[\"stats\",\"num_storages_other\",0],[\"stats\",\"num_comments\",0],[\"stats\",\"num_comment_markers\",0],[\"stats\",\"num_systemtags\",0],[\"stats\",\"num_systemtags_mappings\",0],[\"files_sharing\",\"num_shares\",5],[\"files_sharing\",\"num_shares_user\",3],[\"files_sharing\",\"num_shares_groups\",0],[\"files_sharing\",\"num_shares_link\",2],[\"files_sharing\",\"num_shares_link_no_password\",2],[\"files_sharing\",\"num_fed_shares_sent\",0],[\"files_sharing\",\"num_fed_shares_received\",0],[\"files_sharing\",\"permissions_3_1\",\"2\"],[\"files_sharing\",\"permissions_0_19\",\"1\"],[\"files_sharing\",\"permissions_0_31\",\"2\"],[\"encryption\",\"enabled\",\"no\"],[\"encryption\",\"default_module\",\"no\"]]}",
            "last_sent": "1583247393",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "no",
            "installed_version": "0.13.0",
            "types": ""
        },
        "text": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": "dav"
        },
        "theming": {
            "cachebuster": "13",
            "color": "#00796b",
            "enabled": "yes",
            "faviconMime": "image\/png",
            "installed_version": "1.9.0",
            "logoMime": "image\/png",
            "logoheaderMime": "image\/png",
            "name": "oluhome - Cloud",
            "slogan": "***REMOVED SENSITIVE VALUE***",
            "types": "logging",
            "url": "***REMOVED SENSITIVE VALUE***"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "twofactor_totp": {
            "enabled": "yes",
            "installed_version": "4.1.3",
            "types": ""
        },
        "updatenotification": {
            "bruteforcesettings": "1.6.0",
            "calendar": "2.0.3",
            "contacts": "3.3.0",
            "core": "18.0.4.2",
            "deck": "1.0.1",
            "drawio": "0.9.5",
            "enabled": "yes",
            "files_rightclick": "0.15.1",
            "installed_version": "1.8.0",
            "mail": "1.3.4",
            "music": "0.14.0",
            "notes": "3.3.0",
            "richdocuments": "3.6.0",
            "tasks": "0.13.0",
            "twofactor_totp": "4.1.3",
            "types": "",
            "update_check_errors": "0"
        },
        "video_converter": {
            "enabled": "yes",
            "installed_version": "0.1.4",
            "types": ""
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": "filesystem"
        }
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Google Chrome, Brave

**Operating system:**
macOS

#### Web server error log
<details>
<summary>Web server error log</summary>

```
no errors
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
abc@ce9db63e84cc:/data$ tail nextcloud.log
{"reqId":"EIPSPno9Kwd5YVfTCHJe","level":1,"time":"2020-04-23T14:29:37+00:00","remoteAddr":"172.18.0.10","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=cXthaX1eNEtuD2dOhCxsa%2FxgFsq%2B1uDvIORuZ%2BwMsAs%3D%3AST4tJRRvTiUZNiB2tWZUJpIufrzZnpffEKYeLaRYiG4%3D","message":"\\OC\\Updater::maintenanceDisabled: Turned off maintenance mode","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36","version":"18.0.4.2"}
{"reqId":"EIPSPno9Kwd5YVfTCHJe","level":1,"time":"2020-04-23T14:29:37+00:00","remoteAddr":"172.18.0.10","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=cXthaX1eNEtuD2dOhCxsa%2FxgFsq%2B1uDvIORuZ%2BwMsAs%3D%3AST4tJRRvTiUZNiB2tWZUJpIufrzZnpffEKYeLaRYiG4%3D","message":"\\OC\\Updater::resetLogLevel: Reset log level to Warning(2)","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36","version":"18.0.4.2"}
{"reqId":"6gDSqpLJQpeAOH56REIH","level":3,"time":"2020-05-01T08:00:00+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":{"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception occurred while executing 'SELECT `id` FROM `oc_jobs` WHERE (`class` = ?) AND (`argument` = ?) LIMIT 1' with params [\"OC\\\\BackgroundJob\\\\Legacy\\\\RegularJob\", \"[\\\"OCA\\\\\\\\Music\\\\\\\\Backgroundjob\\\\\\\\CleanUp\\\",\\\"run\\\"]\"]:\n\nSQLSTATE[70100]: <<Unknown error>>: 1927 Connection was killed","Code":0,"Trace":[{"file":"/config/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line":169,"function":"convertException","class":"Doctrine\\DBAL\\Driver\\AbstractMySQLDriver","type":"->","args":["An exception occurred while executing 'SELECT `id` FROM `oc_jobs` WHERE (`class` = ?) AND (`argument` = ?) LIMIT 1' with params [\"OC\\\\BackgroundJob\\\\Legacy\\\\RegularJob\", \"[\\\"OCA\\\\\\\\Music\\\\\\\\Backgroundjob\\\\\\\\CleanUp\\\",\\\"run\\\"]\"]:\n\nSQLSTATE[70100]: <<Unknown error>>: 1927 Connection was killed",{"errorInfo":["70100",1927,"Connection was killed"],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"}]},{"file":"/config/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line":145,"function":"wrapException","class":"Doctrine\\DBAL\\DBALException","type":"::","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDOMySql\\Driver"},{"errorInfo":["70100",1927,"Connection was killed"],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"},"An exception occurred while executing 'SELECT `id` FROM `oc_jobs` WHERE (`class` = ?) AND (`argument` = ?) LIMIT 1' with params [\"OC\\\\BackgroundJob\\\\Legacy\\\\RegularJob\", \"[\\\"OCA\\\\\\\\Music\\\\\\\\Backgroundjob\\\\\\\\CleanUp\\\",\\\"run\\\"]\"]:\n\nSQLSTATE[70100]: <<Unknown error>>: 1927 Connection was killed"]},{"file":"/config/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":911,"function":"driverExceptionDuringQuery","class":"Doctrine\\DBAL\\DBALException","type":"::","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDOMySql\\Driver"},{"errorInfo":["70100",1927,"Connection was killed"],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"},"SELECT `id` FROM `oc_jobs` WHERE (`class` = ?) AND (`argument` = ?) LIMIT 1",{"1":"OC\\BackgroundJob\\Legacy\\RegularJob","2":"[\"OCA\\\\Music\\\\Backgroundjob\\\\CleanUp\",\"run\"]"}]},{"file":"/config/www/nextcloud/lib/private/DB/Connection.php","line":199,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["SELECT `id` FROM `oc_jobs` WHERE (`class` = ?) AND (`argument` = ?) LIMIT 1",["OC\\BackgroundJob\\Legacy\\RegularJob","[\"OCA\\\\Music\\\\Backgroundjob\\\\CleanUp\",\"run\"]"],[2,2],null]},{"file":"/config/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php","line":200,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["SELECT `id` FROM `oc_jobs` WHERE (`class` = :dcValue1) AND (`argument` = :dcValue2) LIMIT 1",{"dcValue1":"OC\\BackgroundJob\\Legacy\\RegularJob","dcValue2":"[\"OCA\\\\Music\\\\Backgroundjob\\\\CleanUp\",\"run\"]"},{"dcValue1":2,"dcValue2":2}]},{"file":"/config/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":215,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"/config/www/nextcloud/lib/private/BackgroundJob/JobList.php","line":146,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/config/www/nextcloud/lib/private/BackgroundJob/JobList.php","line":69,"function":"has","class":"OC\\BackgroundJob\\JobList","type":"->","args":["OC\\BackgroundJob\\Legacy\\RegularJob","[\"OCA\\\\Music\\\\Backgroundjob\\\\CleanUp\",\"run\"]"]},{"file":"/config/www/nextcloud/apps/music/appinfo/app.php","line":48,"function":"add","class":"OC\\BackgroundJob\\JobList","type":"->","args":["OC\\BackgroundJob\\Legacy\\RegularJob",["OCA\\Music\\Backgroundjob\\CleanUp","run"]]},{"file":"/config/www/nextcloud/lib/private/legacy/app.php","line":266,"args":["/config/www/nextcloud/apps/music/appinfo/app.php"],"function":"require_once"},{"file":"/config/www/nextcloud/lib/private/legacy/app.php","line":155,"function":"requireAppFile","class":"OC_App","type":"::","args":[{"__class__":"OCA\\Music\\App\\Music"}]},{"file":"/config/www/nextcloud/lib/private/legacy/app.php","line":128,"function":"loadApp","class":"OC_App","type":"::","args":["music"]},{"file":"/config/www/nextcloud/cron.php","line":54,"function":"loadApps","class":"OC_App","type":"::","args":[]}],"File":"/config/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php","Line":106,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDOException","Message":"SQLSTATE[70100]: <<Unknown error>>: 1927 Connection was killed","Code":"70100","Trace":[{"file":"/config/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":903,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDOStatement","type":"->","args":[]},{"file":"/config/www/nextcloud/lib/private/DB/Connection.php","line":199,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["SELECT `id` FROM `oc_jobs` WHERE (`class` = ?) AND (`argument` = ?) LIMIT 1",["OC\\BackgroundJob\\Legacy\\RegularJob","[\"OCA\\\\Music\\\\Backgroundjob\\\\CleanUp\",\"run\"]"],[2,2],null]},{"file":"/config/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php","line":200,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["SELECT `id` FROM `oc_jobs` WHERE (`class` = :dcValue1) AND (`argument` = :dcValue2) LIMIT 1",{"dcValue1":"OC\\BackgroundJob\\Legacy\\RegularJob","dcValue2":"[\"OCA\\\\Music\\\\Backgroundjob\\\\CleanUp\",\"run\"]"},{"dcValue1":2,"dcValue2":2}]},{"file":"/config/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":215,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"/config/www/nextcloud/lib/private/BackgroundJob/JobList.php","line":146,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/config/www/nextcloud/lib/private/BackgroundJob/JobList.php","line":69,"function":"has","class":"OC\\BackgroundJob\\JobList","type":"->","args":["OC\\BackgroundJob\\Legacy\\RegularJob","[\"OCA\\\\Music\\\\Backgroundjob\\\\CleanUp\",\"run\"]"]},{"file":"/config/www/nextcloud/apps/music/appinfo/app.php","line":48,"function":"add","class":"OC\\BackgroundJob\\JobList","type":"->","args":["OC\\BackgroundJob\\Legacy\\RegularJob",["OCA\\Music\\Backgroundjob\\CleanUp","run"]]},{"file":"/config/www/nextcloud/lib/private/legacy/app.php","line":266,"args":["/config/www/nextcloud/apps/music/appinfo/app.php"],"function":"require_once"},{"file":"/config/www/nextcloud/lib/private/legacy/app.php","line":155,"function":"requireAppFile","class":"OC_App","type":"::","args":[{"__class__":"OCA\\Music\\App\\Music"}]},{"file":"/config/www/nextcloud/lib/private/legacy/app.php","line":128,"function":"loadApp","class":"OC_App","type":"::","args":["music"]},{"file":"/config/www/nextcloud/cron.php","line":54,"function":"loadApps","class":"OC_App","type":"::","args":[]}],"File":"/config/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php","Line":119,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[70100]: <<Unknown error>>: 1927 Connection was killed","Code":"70100","Trace":[{"file":"/config/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php","line":117,"function":"execute","class":"PDOStatement","type":"->","args":[null]},{"file":"/config/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":903,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDOStatement","type":"->","args":[]},{"file":"/config/www/nextcloud/lib/private/DB/Connection.php","line":199,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["SELECT `id` FROM `oc_jobs` WHERE (`class` = ?) AND (`argument` = ?) LIMIT 1",["OC\\BackgroundJob\\Legacy\\RegularJob","[\"OCA\\\\Music\{"reqId":"cn4Z5rw7KOPkGQ6aKPgk","level":2,"time":"2020-05-01T13:45:13+00:00","remoteAddr":"","user":"--","app":"appstoreFetcher","method":"","url":"--","message":"Could not connect to appstore: cURL error 28: Operation timed out after 10001 milliseconds with 2234688 out of 4801970 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)","userAgent":"--","version":"18.0.4.2"}
{"reqId":"1XQsVxaK8VKI28VZiWlw","level":3,"time":"2020-05-07T11:56:03+00:00","remoteAddr":"172.20.0.3","user":"myusername","app":"PHP","method":"GET","url":"/apps/deck/","message":"Undefined index: debug at /config/www/nextcloud/apps/deck/templates/main.php#31","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36","version":"18.0.4.2"}
{"reqId":"Qm69fLFNKizQ2yaEXh4Z","level":3,"time":"2020-05-07T11:56:27+00:00","remoteAddr":"172.20.0.3","user":"myusername","app":"PHP","method":"GET","url":"/apps/deck/","message":"Undefined index: debug at /config/www/nextcloud/apps/deck/templates/main.php#31","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36","version":"18.0.4.2"}
{"reqId":"NGq05L8btav9lUgtliB2","level":3,"time":"2020-05-08T03:50:02+00:00","remoteAddr":"","user":"--","app":"mail","method":"","url":"--","message":{"Exception":"OCA\\Mail\\Exception\\ServiceException","Message":"IMAP errorMail server denied authentication.","Code":102,"Trace":[{"file":"/config/www/nextcloud/apps/mail/lib/BackgroundJob/SyncJob.php","line":91,"function":"sync","class":"OCA\\Mail\\IMAP\\MailboxSync","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},true]},{"file":"/config/www/nextcloud/lib/public/BackgroundJob/Job.php","line":79,"function":"run","class":"OCA\\Mail\\BackgroundJob\\SyncJob","type":"->","args":[{"accountId":1}]},{"file":"/config/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":61,"function":"execute","class":"OCP\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},{"file":"/config/www/nextcloud/cron.php","line":125,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/config/www/nextcloud/apps/mail/lib/IMAP/MailboxSync.php","Line":88,"Previous":{"Exception":"Horde_Imap_Client_Exception","Message":"Mail server denied authentication.","Code":102,"Trace":[{"file":"/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php","line":838,"function":"_login","class":"Horde_Imap_Client_Socket","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php","line":1389,"function":"login","class":"Horde_Imap_Client_Base","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/config/www/nextcloud/apps/mail/lib/IMAP/FolderMapper.php","line":60,"function":"listMailboxes","class":"Horde_Imap_Client_Base","type":"->","args":["*",4,{"delimiter":true,"attributes":true,"special_use":true}]},{"file":"/config/www/nextcloud/apps/mail/lib/IMAP/MailboxSync.php","line":85,"function":"getFolders","class":"OCA\\Mail\\IMAP\\FolderMapper","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},{"cacheFields":{"9":"HICenv","10":"HICflags","8":"HIChdrs","11":"HICdate","12":"HICsize","1":"HICstruct"},"changed":true,"statuscache":true,"__class__":"Horde_Imap_Client_Socket"}]},{"file":"/config/www/nextcloud/apps/mail/lib/BackgroundJob/SyncJob.php","line":91,"function":"sync","class":"OCA\\Mail\\IMAP\\MailboxSync","type":"->","args":[{"__class__":"OCA\\Mail\\Account"},true]},{"file":"/config/www/nextcloud/lib/public/BackgroundJob/Job.php","line":79,"function":"run","class":"OCA\\Mail\\BackgroundJob\\SyncJob","type":"->","args":[{"accountId":1}]},{"file":"/config/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":61,"function":"execute","class":"OCP\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},{"file":"/config/www/nextcloud/cron.php","line":125,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/config/www/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php","Line":572},"CustomMessage":"Cron mail sync failed: IMAP errorMail server denied authentication."},"userAgent":"--","version":"18.0.4.2"}
{"reqId":"ljW0jY6DvKaEoi0fKFk8","level":2,"time":"2020-05-12T10:05:12+00:00","remoteAddr":"","user":"--","app":"appstoreFetcher","method":"","url":"--","message":"Could not connect to appstore: cURL error 28: Operation timed out after 10001 milliseconds with 0 out of 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)","userAgent":"--","version":"18.0.4.2"}
{"reqId":"JviofP4O8CPQrwU3CAo0","level":3,"time":"2020-05-14T16:34:49+00:00","remoteAddr":"172.18.0.2","user":"myusername","app":"no app in context","method":"GET","url":"/","message":{"Exception":"Error","Message":"Call to undefined method OCA\\Calendar\\AppInfo\\Application::registerNavigation()","Code":0,"Trace":[{"file":"/config/www/nextcloud/lib/private/legacy/app.php","line":266,"function":"require_once"},{"file":"/config/www/nextcloud/lib/private/legacy/app.php","line":155,"function":"requireAppFile","class":"OC_App","type":"::","args":[{"__class__":"OCA\\Calendar\\AppInfo\\Application"}]},{"file":"/config/www/nextcloud/lib/private/legacy/app.php","line":128,"function":"loadApp","class":"OC_App","type":"::","args":["calendar"]},{"file":"/config/www/nextcloud/lib/base.php","line":1005,"function":"loadApps","class":"OC_App","type":"::","args":[]},{"file":"/config/www/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/config/www/nextcloud/apps/calendar/appinfo/app.php","Line":26,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36","version":"18.0.4.2"}
{"reqId":"JviofP4O8CPQrwU3CAo0","level":3,"time":"2020-05-14T16:34:49+00:00","remoteAddr":"172.18.0.2","user":"myusername","app":"no app in context","method":"GET","url":"/","message":{"Exception":"Error","Message":"Call to undefined method OCA\\Tasks\\AppInfo\\Application::registerNavigation()","Code":0,"Trace":[{"file":"/config/www/nextcloud/lib/private/legacy/app.php","line":266,"function":"require_once"},{"file":"/config/www/nextcloud/lib/private/legacy/app.php","line":155,"function":"requireAppFile","class":"OC_App","type":"::","args":[{"__class__":"OCA\\Tasks\\AppInfo\\Application"}]},{"file":"/config/www/nextcloud/lib/private/legacy/app.php","line":128,"function":"loadApp","class":"OC_App","type":"::","args":["tasks"]},{"file":"/config/www/nextcloud/lib/base.php","line":1005,"function":"loadApps","class":"OC_App","type":"::","args":[]},{"file":"/config/www/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/config/www/nextcloud/apps/tasks/appinfo/app.php","Line":24,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36","version":"18.0.4.2"}
{"reqId":"cBSrIY7rk3nnS6ycyrbL","level":2,"time":"2020-05-15T13:00:11+00:00","remoteAddr":"","user":"--","app":"appstoreFetcher","method":"","url":"--","message":"Could not connect to appstore: cURL error 28: Operation timed out after 10001 milliseconds with 2495435 out of 4876286 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)","userAgent":"--","version":"18.0.4.2"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
notifications.js?v=e4b8f946-13:21 Proxying an event bus of version 1.1.2 with 0.2.1
t @ notifications.js?v=e4b8f946-13:21
(anonymous) @ notifications.js?v=e4b8f946-13:21
n @ notifications.js?v=e4b8f946-13:1
(anonymous) @ notifications.js?v=e4b8f946-13:21
n @ notifications.js?v=e4b8f946-13:1
(anonymous) @ notifications.js?v=e4b8f946-13:21
n @ notifications.js?v=e4b8f946-13:1
(anonymous) @ notifications.js?v=e4b8f946-13:1
n @ notifications.js?v=e4b8f946-13:1
(anonymous) @ notifications.js?v=e4b8f946-13:21
n @ notifications.js?v=e4b8f946-13:1
(anonymous) @ notifications.js?v=e4b8f946-13:1
(anonymous) @ notifications.js?v=e4b8f946-13:1
main.js?v=e4b8f946-13:1082 Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20
ne @ main.js?v=e4b8f946-13:1082
get @ main.js?v=e4b8f946-13:1082
e.default @ notifications.js?v=e4b8f946-13:21
(anonymous) @ notifications.js?v=e4b8f946-13:21
n @ notifications.js?v=e4b8f946-13:1
(anonymous) @ notifications.js?v=e4b8f946-13:7
n @ notifications.js?v=e4b8f946-13:1
(anonymous) @ notifications.js?v=e4b8f946-13:21
n @ notifications.js?v=e4b8f946-13:1
(anonymous) @ notifications.js?v=e4b8f946-13:21
n @ notifications.js?v=e4b8f946-13:1
(anonymous) @ notifications.js?v=e4b8f946-13:1
(anonymous) @ notifications.js?v=e4b8f946-13:1
DevTools failed to load SourceMap: Could not parse content for https://cloud.mydomain.com/core/js/dist/main.js.map: Unexpected token < in JSON at position 0
vue-settings-apps-users-management.js?v=e4b8f946-13:45 Proxying an event bus of version 1.1.2 with 0.2.1
t @ vue-settings-apps-users-management.js?v=e4b8f946-13:45
(anonymous) @ vue-settings-apps-users-management.js?v=e4b8f946-13:45
o @ vue-settings-apps-users-management.js?v=e4b8f946-13:1
(anonymous) @ vue-settings-apps-users-management.js?v=e4b8f946-13:45
o @ vue-settings-apps-users-management.js?v=e4b8f946-13:1
(anonymous) @ vue-settings-apps-users-management.js?v=e4b8f946-13:45
o @ vue-settings-apps-users-management.js?v=e4b8f946-13:1
(anonymous) @ vue-settings-apps-users-management.js?v=e4b8f946-13:7
o @ vue-settings-apps-users-management.js?v=e4b8f946-13:1
(anonymous) @ vue-settings-apps-users-management.js?v=e4b8f946-13:1
o @ vue-settings-apps-users-management.js?v=e4b8f946-13:1
(anonymous) @ vue-settings-apps-users-management.js?v=e4b8f946-13:67
o @ vue-settings-apps-users-management.js?v=e4b8f946-13:1
(anonymous) @ vue-settings-apps-users-management.js?v=e4b8f946-13:1
(anonymous) @ vue-settings-apps-users-management.js?v=e4b8f946-13:1
main.js?v=e4b8f946-13:1082 moment is deprecated: please ship your own, this will be removed in Nextcloud 20
ne @ main.js?v=e4b8f946-13:1082
get @ main.js?v=e4b8f946-13:1082
timestamp @ notifications.js?v=e4b8f946-13:21
vn.get @ notifications.js?v=e4b8f946-13:7
vn.evaluate @ notifications.js?v=e4b8f946-13:7
(anonymous) @ notifications.js?v=e4b8f946-13:7
(anonymous) @ notifications.js?v=e4b8f946-13:21
t._render @ notifications.js?v=e4b8f946-13:7
r @ notifications.js?v=e4b8f946-13:7
vn.get @ notifications.js?v=e4b8f946-13:7
vn @ notifications.js?v=e4b8f946-13:7
(anonymous) @ notifications.js?v=e4b8f946-13:7
On.$mount @ notifications.js?v=e4b8f946-13:7
On.$mount @ notifications.js?v=e4b8f946-13:7
init @ notifications.js?v=e4b8f946-13:7
(anonymous) @ notifications.js?v=e4b8f946-13:7
f @ notifications.js?v=e4b8f946-13:7
v @ notifications.js?v=e4b8f946-13:7
f @ notifications.js?v=e4b8f946-13:7
(anonymous) @ notifications.js?v=e4b8f946-13:7
t._update @ notifications.js?v=e4b8f946-13:7
_update @ notifications.js?v=e4b8f946-13:7
r @ notifications.js?v=e4b8f946-13:7
vn.get @ notifications.js?v=e4b8f946-13:7
vn @ notifications.js?v=e4b8f946-13:7
(anonymous) @ notifications.js?v=e4b8f946-13:7
On.$mount @ notifications.js?v=e4b8f946-13:7
On.$mount @ notifications.js?v=e4b8f946-13:7
init @ notifications.js?v=e4b8f946-13:7
(anonymous) @ notifications.js?v=e4b8f946-13:7
f @ notifications.js?v=e4b8f946-13:7
v @ notifications.js?v=e4b8f946-13:7
f @ notifications.js?v=e4b8f946-13:7
(anonymous) @ notifications.js?v=e4b8f946-13:7
t._update @ notifications.js?v=e4b8f946-13:7
r @ notifications.js?v=e4b8f946-13:7
vn.get @ notifications.js?v=e4b8f946-13:7
vn.run @ notifications.js?v=e4b8f946-13:7
pn @ notifications.js?v=e4b8f946-13:7
(anonymous) @ notifications.js?v=e4b8f946-13:7
Yt @ notifications.js?v=e4b8f946-13:7
Promise.then (async)
Kt @ notifications.js?v=e4b8f946-13:7
re @ notifications.js?v=e4b8f946-13:7
(anonymous) @ notifications.js?v=e4b8f946-13:7
vn.update @ notifications.js?v=e4b8f946-13:7
pt.notify @ notifications.js?v=e4b8f946-13:7
set @ notifications.js?v=e4b8f946-13:7
hn.set @ notifications.js?v=e4b8f946-13:7
(anonymous) @ notifications.js?v=e4b8f946-13:21
Promise.then (async)
_fetch @ notifications.js?v=e4b8f946-13:21
mounted @ notifications.js?v=e4b8f946-13:21
zt @ notifications.js?v=e4b8f946-13:7
en @ notifications.js?v=e4b8f946-13:7
insert @ notifications.js?v=e4b8f946-13:7
O @ notifications.js?v=e4b8f946-13:7
(anonymous) @ notifications.js?v=e4b8f946-13:7
t._update @ notifications.js?v=e4b8f946-13:7
r @ notifications.js?v=e4b8f946-13:7
vn.get @ notifications.js?v=e4b8f946-13:7
vn @ notifications.js?v=e4b8f946-13:7
(anonymous) @ notifications.js?v=e4b8f946-13:7
On.$mount @ notifications.js?v=e4b8f946-13:7
On.$mount @ notifications.js?v=e4b8f946-13:7
t._init @ notifications.js?v=e4b8f946-13:7
On @ notifications.js?v=e4b8f946-13:7
(anonymous) @ notifications.js?v=e4b8f946-13:41
n @ notifications.js?v=e4b8f946-13:1
(anonymous) @ notifications.js?v=e4b8f946-13:1
(anonymous) @ notifications.js?v=e4b8f946-13:1
Show 11 more frames
vue-settings-apps-users-management.js?v=e4b8f946-13:45 ChunkLoadError: Loading chunk 0 failed.
(missing: https://cloud.mydomain.com/apps/settings/js/vue-0.js?v=9809a76d427d04d0282b)
    at Function.o.e (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:1:813)
    at Yt (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:45:91718)
    at https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:45:80702
    at https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:45:80947
    at Array.map (<anonymous>)
    at https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:45:80924
    at Array.map (<anonymous>)
    at St (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:45:80875)
    at https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:45:80341
    at d (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:45:83586)
    at r (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:45:80243)
    at r (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:45:80270)
    at At (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:45:80278)
    at e.Pt.confirmTransition (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:45:83813)
    at e.Pt.transitionTo (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:45:82601)
    at Ht.init (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:45:88949)
    at An.beforeCreate (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:45:91006)
    at zt (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:7:11267)
    at en (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:7:25191)
    at An.t._init (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:7:32598)
    at new An (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:7:30225)
    at Module.<anonymous> (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:112:251)
    at o (https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:1:361)
    at https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:1:2156
    at https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js?v=e4b8f946-13:1:2167
i @ vue-settings-apps-users-management.js?v=e4b8f946-13:45
(anonymous) @ vue-settings-apps-users-management.js?v=e4b8f946-13:45
(anonymous) @ vue-settings-apps-users-management.js?v=e4b8f946-13:45
(anonymous) @ vue-settings-apps-users-management.js?v=e4b8f946-13:45
Promise.then (async)
(anonymous) @ vue-settings-apps-users-management.js?v=e4b8f946-13:45
(anonymous) @ vue-settings-apps-users-management.js?v=e4b8f946-13:45
(anonymous) @ vue-settings-apps-users-management.js?v=e4b8f946-13:45
St @ vue-settings-apps-users-management.js?v=e4b8f946-13:45
(anonymous) @ vue-settings-apps-users-management.js?v=e4b8f946-13:45
d @ vue-settings-apps-users-management.js?v=e4b8f946-13:45
r @ vue-settings-apps-users-management.js?v=e4b8f946-13:45
r @ vue-settings-apps-users-management.js?v=e4b8f946-13:45
At @ vue-settings-apps-users-management.js?v=e4b8f946-13:45
Pt.confirmTransition @ vue-settings-apps-users-management.js?v=e4b8f946-13:45
Pt.transitionTo @ vue-settings-apps-users-management.js?v=e4b8f946-13:45
Ht.init @ vue-settings-apps-users-management.js?v=e4b8f946-13:45
beforeCreate @ vue-settings-apps-users-management.js?v=e4b8f946-13:45
zt @ vue-settings-apps-users-management.js?v=e4b8f946-13:7
en @ vue-settings-apps-users-management.js?v=e4b8f946-13:7
t._init @ vue-settings-apps-users-management.js?v=e4b8f946-13:7
An @ vue-settings-apps-users-management.js?v=e4b8f946-13:7
(anonymous) @ vue-settings-apps-users-management.js?v=e4b8f946-13:112
o @ vue-settings-apps-users-management.js?v=e4b8f946-13:1
(anonymous) @ vue-settings-apps-users-management.js?v=e4b8f946-13:1
(anonymous) @ vue-settings-apps-users-management.js?v=e4b8f946-13:1
DevTools failed to load SourceMap: Could not parse content for https://cloud.mydomain.com/apps/files_sharing/js/dist/main.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://cloud.mydomain.com/apps/files_videoplayer/js/main.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://cloud.mydomain.com/apps/notifications/js/notifications.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://cloud.mydomain.com/settings/js/vue-settings-apps-users-management.js.map?v=7c750b89d661eb4c9c40: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://cloud.mydomain.com/apps/settings/js/vue-0.js.map?v=019e35e82592c2c3331d: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://cloud.mydomain.com/apps/settings/js/vue-5.js.map?v=9f21b095af9b877ae56d: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://cloud.mydomain.com/apps/settings/js/vue-4.js.map?v=844750e6183ea022471a: Unexpected token < in JSON at position 0
```
</details>

### PR DESCRIPTION
**Pull request by skjnldsv**
Potentially fix #21024  

Avoid files conflict when building and try to fix weird webpack chunk loading issue.

### CODE REVIEW

File: apps/settings/webpack.js [hunk 1]
```diff
@@ -5,17 +5,16 @@ module.exports = {
...
 		'settings-admin-security': path.join(__dirname, 'src', 'main-admin-security'),
 		'settings-personal-security': path.join(__dirname, 'src', 'main-personal-security'),
-		'settings-personal-webauthn': path.join(__dirname, 'src', 'main-personal-webauth')
+		'settings-personal-webauthn': path.join(__dirname, 'src', 'main-personal-webauth'),
 	},
 	output: {
 		path: path.resolve(__dirname, './js'),
 		publicPath: '/js/',
-		filename: 'vue-[name].js?v=[chunkhash]',
-		jsonpFunction: 'webpackJsonpSettings'
```
Comment (juliushaertl) [inline apps/settings/webpack.js:14]: We should still keep this.

Comment (skjnldsv) [reply apps/settings/webpack.js:14]: Was causing issues it seemed.
Why is this needed?

Comment (skjnldsv) [reply apps/settings/webpack.js:14]: SHould I add this into the webpackvueconfig ?

Comment (juliushaertl) [reply apps/settings/webpack.js:14]: This is required to avoid multiple webpack builds running into conflicts when they are loaded on the same change.

Might be what is mentioned [here](https://webpack.js.org/configuration/output/#outputjsonpfunction)
> If multiple webpack runtimes (from different compilations) are used on the same webpage, there is a risk of conflicts of on-demand chunks in the global namespace.

So while I'm not sure I get their documentation 100% correct, I would assume that having uniquely named chunks should solve this already.

**Review by juliusknorr — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
@skjnldsv Mind to rebase and recreate?

**Comment by skjnldsv** [comment]
Aaaand, it's outdated again --'

**Comment by MorrisJobke** [comment]
I guess it doesn't make sense to rebase now. First #22635 should get in and then we rebase this again.

**Comment by MorrisJobke** [comment]
> I guess it doesn't make sense to rebase now. First #22635 should get in and then we rebase this again.

I was afraid of the conflicts.

@skjnldsv Mind to do a last one and we merge this next?

cc @rullzer

**Comment by MorrisJobke** [comment]
> The backport to stable19 failed. Please do this backport manually.

@skjnldsv mind to do this manually?

**Comment by skjnldsv** [comment]
Done
