### PR TITLE
fix(files): new folder icon color

### LINKED ISSUE #53028: [Bug]: Folder icons in files list and "new folder" action button have different color
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I think it's confusing that the folder icons in the files list are blue, but the "new folder" action button is white.

### Steps to reproduce

Open the "New" menu in Files app and see.

### Expected behavior

The folder icons should have a consistent color.

### Nextcloud Server version

master

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by skjnldsv**
* Resolves: #53028
* Paired with https://github.com/nextcloud-libraries/nextcloud-upload/pull/1822

## Summary

image

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/files/src/newMenu/newFolder.ts [hunk 1]
```diff
@@ -43,8 +43,11 @@ export const entry = {
 	id: 'newFolder',
 	displayName: t('files', 'New folder'),
 	enabled: (context: Folder) => Boolean(context.permissions & Permission.CREATE) && Boolean(context.permissions & Permission.READ),
-	iconSvgInline: FolderPlusSvg,
+
+	// Make the svg icon color match the primary element color
+	iconSvgInline: FolderPlusSvg.replace(/viewBox/gi, 'style="color: var(--color-primary-element)" viewBox'),
```
Comment (susnux) [inline apps/files/src/newMenu/newFolder.ts:48]: tricky

**Review by susnux — APPROVED** [review]

File: apps/files/src/newMenu/newFolder.ts (hunk 1 above)
Comment (skjnldsv) [reply apps/files/src/newMenu/newFolder.ts:48]: Yeah, but straightforward enough 🤭🤭

**Review by nfebe — APPROVED** [review]

**Comment by skjnldsv** [comment]
/backport 7a893104a205f994001248d9b4f4815f007dd438 to stable31

**Comment by skjnldsv** [comment]
/backport 7a893104a205f994001248d9b4f4815f007dd438 to stable30
