### PR TITLE
fix(files): fix tab navigation from select all checkbox to batch actions

### LINKED ISSUE #58386: [files] wrong tab order of file-list actions
When the "select all" checkbox is selected then the file list actions appear.
Those actions must have then the next tab sequence (after tab on the "select all" checkbox the next focussed element must be the fist action).

Image

### LINKED ISSUE #62249: [accessibility] after selecting files: actions hide table headers
after selecting all checkboxes, the column headers of the table are no longer displayed, and the "Restore" and "Permanently Delete" buttons are shown. If not all checkboxes are selected, the "Restore" and "Download" buttons are shown. The column headers are still accessible via the TAB key, but are no longer visible. The keyboard focus passes through more than three consecutive, invisible positions. (9.2.4.3>B1)

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/server/issues/58386

Not too convinced, but code is clean and it works™

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)
- [x] [Labels added](https://github.com/nextcloud/server/labels) where applicable (ex: bug/enhancement, `3. to review`, feature component)
- [x] [Milestone added](https://github.com/nextcloud/server/milestones) for target branch/version (ex: 32.x for `stable32`)

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
🐘

File: apps/files/src/components/FilesListTableHeaderActions.vue [hunk 1]
```diff
@@ -16,7 +16,8 @@
 			@close="openedSubmenu = null">
 			<!-- Default actions list-->
 			<NcActionButton
-				v-for="action in enabledMenuActions"
+				v-for="(action, idx) in enabledMenuActions"
+				:id="idx === 0 && FileListHeadFirstBatchAction"
```
Comment (susnux) [inline apps/files/src/components/FilesListTableHeaderActions.vue]: so there is an id `false`?


```suggestion
				:id="idx === 0 ? FileListHeadFirstBatchAction : undefined"
```

File: apps/files/src/components/FilesListTableHeaderActions.vue [hunk 2]
```diff
@@ -93,6 +95,8 @@ import { useActiveStore } from '../store/active.ts'
 import { useFilesStore } from '../store/files.ts'
 import { useSelectionStore } from '../store/selection.ts'
 
+export const FileListHeadFirstBatchAction = 'files-list-head-first-batch-action'
```
Comment (susnux) [inline apps/files/src/components/FilesListTableHeaderActions.vue]: Makes it a bit more self explaining that this is not a component, class or whatever.

```suggestion
export const FileListHeadFirstBatchActionId = 'files-list-head-first-batch-action'
```

(while in general not sure if PascalCase for those constants is a good choice as this clashes with classes and components and might be misleading, I think we otherwise simply use camelCase or ALL_CAPS for constants).

**Review by susnux — COMMENTED** [review]
Looks like a good solution, just some comments for readability

File: apps/files/src/components/FilesListTableHeaderActions.vue (hunk 2 above)
Comment (skjnldsv) [reply apps/files/src/components/FilesListTableHeaderActions.vue]: for constants I like to use something else than :camel: 
Let's approach with CAPS

File: apps/files/src/components/FilesListTableHeaderActions.vue (hunk 1 above)
Comment (skjnldsv) [reply apps/files/src/components/FilesListTableHeaderActions.vue]: False is no id for vue, but I can make it more explicit with undefined, sure! :+1: :blush:

**Review by susnux — APPROVED** [review]
Now its screaming at me but thats fine 😆
