### PR TITLE
fix(settings): Clarify peculiarities of enabling encryption

### LINKED ISSUE #48829: enh(Settings): Provide visual feedback to user when encryption app not installed.
Under : `Admin settings` -> `Security`,  The "Enable server-side encryption", toggle does not do anything unless the "encryption" app is present.

That make sense but it should provide visual feedback as to what is going on.

### PR DESCRIPTION
**Pull request by susnux**
* Resolves #48829 

## Summary

- Clarify that enabling server side encryption will not encrypt existing files but only new or changed files.
- Clarify that server side encryption can only be disabled using OCC
- Ensure there is accessible information of encryption state (`disabled` input will not be announced so make it `aria-disabled` instead)
- Make warning more prominent by moving it into a dialog

## Screenshots

before | after
---|---
Screenshot 2025-01-25 at 14-09-52 Security - Administration settings - Nextcloud|Screenshot 2025-01-25 at 14-10-35 Security - Administration settings - Nextcloud
Screenshot 2025-01-25 at 14-11-53 Security - Administration settings - Nextcloud|Screenshot 2025-01-25 at 14-11-32 Security - Administration settings - Nextcloud

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by joshtrichards** [comment]
Related:

#40468
#48829
 #49200

File: apps/settings/src/components/Encryption/EncryptionSettings.vue [hunk 1]
```diff
@@ -7,32 +7,30 @@
...
+			:checked="encryptionEnabled"
+			:aria-disabled="encryptionEnabled ? 'true' : undefined"
+			:aria-describedby="encryptionEnabled ? 'server-side-encryption-disable-hint' : undefined"
+			:loading="loadingEncryptionState"
 			type="switch"
 			@update:checked="displayWarning">
 			{{ t('settings', 'Enable server-side encryption') }}
 		</NcCheckboxRadioSwitch>
+		<p v-if="encryptionEnabled" id="server-side-encryption-disable-hint" class="disable-hint">
+			{{ t('settings', 'Disabling server side encryption is only possible using OCC, please refer to the documentation.') }}
```
Comment (artonge) [inline apps/settings/src/components/Encryption/EncryptionSettings.vue:30]: Can we have a link to the documentation?

**Review by artonge — APPROVED** [review]

**Review by szaimen — APPROVED** [review]
Tested and LGTM so far but did not review the code.

However shouldnt we check the following requirement before we allow to enable the SSE?
(This hint is only displayed after the SSE was activated)
image

**Comment by susnux** [comment]
> However shouldnt we check the following requirement before we allow to enable the SSE?

Makes sense :white_check_mark:

File: apps/settings/src/components/Encryption/EncryptionSettings.vue (hunk 1 above)
Comment (susnux) [reply apps/settings/src/components/Encryption/EncryptionSettings.vue:138]: Its already in the section header (directly on top of it)

**Review by szaimen — APPROVED** [review]
Tested again and LGTM

Just as an idea: we could even disable the switch to enable SSE if the encryption module is not enabled, no?

**Comment by susnux** [comment]
/backport cdaeb6386288268976c518d4a66c500c2cdee4d5 to stable30

**Comment by susnux** [comment]
/backport cdaeb6386288268976c518d4a66c500c2cdee4d5 to stable29
