### PR TITLE
fix(files): fixed breadcrumbs dissapearing on narrow screens

### LINKED ISSUE #44120: opening sidebar hides broadscrombs totally with some screen resolutions
Just tested on nc29.0.0b1,
opening the sidebar hides the broadscrumbs totally under some circumstances:
### Sidebar open:
image
### Sidebar closed:
image

### PR DESCRIPTION
**Pull request by emoral435**
* Resolves #44120

## Summary
NcBreadcrumbs already handled for when breadcrumbs are too long for the view-width by making the unmaintainable breadcrumbs composed into a drop-down list, so we only have to care about hiding the breadcrumbs on small view ports. I tried 420, as that is what we use everywhere for standard, but 400 worked much better with the styling of the navbar.

## Screenshot
https://github.com/nextcloud/server/assets/110193237/dca24ae3-9567-4e74-bf40-e3699e45ba9a

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/files/src/components/BreadCrumbs.vue [hunk 1]
```diff
@@ -126,9 +126,9 @@ export default defineComponent({
 			return this.uploaderStore.queue.length !== 0
 		},
 
-		// Hide breadcrumbs if an upload is ongoing on arrow screens
+		// Hide breadcrumbs if an upload is ongoing
 		shouldShowBreadcrumbs(): boolean {
-			return this.filesListWidth > 768 && !this.isUploadInProgress
+			return this.filesListWidth > 400 && !this.isUploadInProgress
```
Comment (skjnldsv) [inline apps/files/src/components/BreadCrumbs.vue:131]: This is not really a number we use anywhere.
Can we use one of them? 512 or 768 ?

Comment (emoral435) [reply apps/files/src/components/BreadCrumbs.vue:131]: Ahh, both suggested numbers are still not big enough to fix the initial problem of the breadcrumbs disappearing. 

There is also the route of simply removing the viewport width check, but then on big screens, the breadcrumbs leave for a second and then reappear, which looks weird in my personal opinion. 

420 works, but there is a small section of viewport where it disappears, but it does not seem to be that big of a problem. We use 420 in other libraries, should we use that instead?

Comment (susnux) [reply apps/files/src/components/BreadCrumbs.vue:131]: Yes I think I have seen 420 as well for mobile devices like smartphones. So 420 would make sense.

>  512 or 768

Nice numbers, but they are not very useful for responsiveness here IMHO.

Comment (skjnldsv) [reply apps/files/src/components/BreadCrumbs.vue:131]: > Nice numbers, but they are not very useful for responsiveness here IMHO.

Right
https://github.com/nextcloud-libraries/nextcloud-vue/blob/b3aee0c29b85618e591006fd7363224a57a3957b/src/assets/variables.scss#L57-L58

In any case, searching for `@media` on the nc org is a nightmare. We need to use appropriate numbers, everyone uses different ones :see_no_evil:

**Review by skjnldsv — APPROVED** [review]

File: apps/files/src/components/BreadCrumbs.vue (hunk 1 above)
Comment (skjnldsv) [reply apps/files/src/components/BreadCrumbs.vue:131]: We can keep 400 @emoral435

Comment (susnux) [reply apps/files/src/components/BreadCrumbs.vue:131]: Yes I agree :) 
For me when talking about mobile devices I mostly think about smartphones used in portrait mode, so this would be something below 480px which mostly need special handling.

**Review by susnux — APPROVED** [review]

**Comment by skjnldsv** [comment]
@emoral435 now, even on wide screens, we hide the breadcrumbs if any upload is ongoing, this seems like a regression?

**Comment by emoral435** [comment]
@skjnldsv Agreed 👍 Will make a PR to fix this. However, I will test to see if the last return condition is even needed, as within somewhere in FilesList there already is a feature to truncate the breadcrumbs around that view port width anyways, so having two places hide the breadcrumbs just increases the complexity / amount of things we would have to find and then change in the future in case we decide to change this :)
