### PR TITLE
fix(l10n): Fix plural issue with different locale and language

### LINKED ISSUE #9558: Fails to list rooms in Czech locale and English language
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Configure Czech locale and English language in Nextcloud
2. Open Talk
3. See no rooms

### Expected behaviour
I'd expect to see the rooms.

### Actual behaviour
There are no rooms listed, see below for logs.

## Talk app

**Talk app version:**  16.0.3

**Custom Signaling server configured:** no

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Debian

**Browser name:** Firefox

**Browser version:** 102

### Browser log

`GET /apps/spreed/api/v4/room?includeStatus=true` fails with HTTP 500
 
<details>

```

XHRGEThttps://nextcloud/ocs/v2.php/apps/spreed/api/v4/room?includeStatus=true
[HTTP/1.1 500 Internal Server Error 104ms]

```

</details>

## Server configuration

**Operating system**: Debian

**Web server:** Apache/Nginx

**Database:** Maria

**PHP version:** 8.1

**Nextcloud Version:**  26.0.1

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)

```
Unable to choose a translation for "%count% guest|%count% guests" with locale "cs" for value "5".
```

<details>

```

{"reqId":"nmJmygobrNxwvCpPSV6O","level":3,"time":"2023-05-17T10:33:46+00:00","remoteAddr":"2001:1ae9:50:5800::439","user":"nijel","app":"no app in context","method":"GET","url":"/ocs/v2.php/apps/spreed/api/v4/room?includeStatus=true","message":"Unable to choose a translation for \"%count% guest|%count% guests\" with locale \"cs\" for value \"5\". Double check that this translation has the correct plural options (e.g. \"There is one apple|There are %count% apples\").","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0","version":"26.0.1.1","exception":{"Exception":"Symfony\\Component\\Translation\\Exception\\InvalidArgumentException","Message":"Unable to choose a translation for \"%count% guest|%count% guests\" with locale \"cs\" for value \"5\". Double check that this translation has the correct plural options (e.g. \"There is one apple|There are %count% apples\").","Code":0,"Trace":[{"file":"/var/www/html/3rdparty/symfony/translation/IdentityTranslator.php","line":46,"function":"doTrans","class":"Symfony\\Component\\Translation\\IdentityTranslator","type":"->","args":["%count% guest|%count% guests",[5],null,"cs"]},{"file":"/var/www/html/lib/private/L10N/L10NString.php","line":86,"function":"trans","class":"Symfony\\Component\\Translation\\IdentityTranslator","type":"->","args":["%count% guest|%count% guests",[5]]},{"file":"/var/www/html/lib/private/L10N/L10N.php","line":126,"function":"__toString","class":"OC\\L10N\\L10NString","type":"->","args":[]},{"file":"/var/www/html/lib/private/L10N/LazyL10N.php","line":55,"function":"n","class":"OC\\L10N\\L10N","type":"->","args":["%n guest","%n guests",5,[]]},{"file":"/var/www/html/custom_apps/spreed/lib/Chat/Parser/SystemMessage.php","line":940,"function":"n","class":"OC\\L10N\\LazyL10N","type":"->","args":["%n guest","%n guests",5]},{"file":"/var/www/html/custom_apps/spreed/lib/Chat/Parser/SystemMessage.php","line":181,"function":"parseCall","class":"OCA\\Talk\\Chat\\Parser\\SystemMessage","type":"->","args":["call_ended",[["nijel"],5,2120],[["user","nijel","Michal \u010ciha\u0159"]]]},{"file":"/var/www/html/custom_apps/spreed/lib/Chat/Parser/Listener.php","line":88,"function":"parseMessage","class":"OCA\\Talk\\Chat\\Parser\\SystemMessage","type":"->","args":[["OCA\\Talk\\Model\\Message"]]},{"file":"/var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":251,"function":"parseSystemMessage","class":"OCA\\Talk\\Chat\\Parser\\Listener","type":"::","args":[["OCA\\Talk\\Events\\ChatMessageEvent"],"OCA\\Talk\\Chat\\MessageParser::parseMessage",["Symfony\\Component\\EventDispatcher\\EventDispatcher"]]},{"file":"/var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[["Closure"],["Closure"],["Closure"],["Closure"],["Closure"],["Closure"]],"OCA\\Talk\\Chat\\MessageParser::parseMessage",["OCA\\Talk\\Events\\ChatMessageEvent"]]},{"file":"/var/www/html/lib/private/EventDispatcher/EventDispatcher.php","line":87,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[["OCA\\Talk\\Events\\ChatMessageEvent"],"OCA\\Talk\\Chat\\MessageParser::parseMessage"]},{"file":"/var/www/html/custom_apps/spreed/lib/Chat/MessageParser.php","line":77,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->","args":["OCA\\Talk\\Chat\\MessageParser::parseMessage",["OCA\\Talk\\Events\\ChatMessageEvent"]]},{"file":"/var/www/html/custom_apps/spreed/lib/Service/RoomFormatter.php","line":363,"function":"parseMessage","class":"OCA\\Talk\\Chat\\MessageParser","type":"->","args":[["OCA\\Talk\\Model\\Message"]]},{"file":"/var/www/html/custom_apps/spreed/lib/Service/RoomFormatter.php","line":344,"function":"formatLastMessage","class":"OCA\\Talk\\Service\\RoomFormatter","type":"->","args":["json",["OCA\\Talk\\Room"],["OCA\\Talk\\Participant"],["OC\\Comments\\Comment"]]},{"file":"/var/www/html/custom_apps/spreed/lib/Service/RoomFormatter.php","line":73,"function":"formatRoomV4","class":"OCA\\Talk\\Service\\RoomFormatter","type":"->","args":["json",[2835,717,214,935,1687,2174,2570,3093,3143,3150,3191,3208],["OCA\\Talk\\Room"],["OCA\\Talk\\Participant"],[["OCA\\UserStatus\\Connector\\UserStatus"]],false,false]},{"file":"/var/www/html/custom_apps/spreed/lib/Controller/RoomController.php","line":395,"function":"formatRoom","class":"OCA\\Talk\\Service\\RoomFormatter","type":"->","args":["json",[2835,717,214,935,1687,2174,2570,3093,3143,3150,3191,3208],["OCA\\Talk\\Room"],["OCA\\Talk\\Participant"],[["OCA\\UserStatus\\Connector\\UserStatus"]],false,false]},{"file":"/var/www/html/custom_apps/spreed/lib/Controller/RoomController.php","line":251,"function":"formatRoom","class":"OCA\\Talk\\Controller\\RoomController","type":"->","args":[["OCA\\Talk\\Room"],["OCA\\Talk\\Participant"],[["OCA\\UserStatus\\Connector\\UserStatus"]]]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"getRooms","class":"OCA\\Talk\\Controller\\RoomController","type":"->","args":[0,true,0]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Talk\\Controller\\RoomController"],"getRooms"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Talk\\Controller\\RoomController"],"getRooms"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Talk\\Controller\\RoomController","getRooms",["OC\\AppFramework\\DependencyInjection\\DIContainer"],["v4","ocs.spreed.Room.getRooms"]]},{"file":"/var/www/html/ocs/v1.php","line":64,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/apps/spreed/api/v4/room"]},{"file":"/var/www/html/ocs/v2.php","line":23,"args":["/var/www/html/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/html/3rdparty/symfony/translation-contracts/TranslatorTrait.php","Line":125,"CustomMessage":"--"}}
```

</details>

### PR DESCRIPTION
**Pull request by nickvergessen**
We need to use the language code here instead of the locale, because Symfony does not distinguish between the two and would otherwise e.g. with locale "Czech" and language "German" try to pick a non-existing plural rule, because Czech has 4 plural forms and German only 2.

* Resolves: https://github.com/nextcloud/spreed/issues/9558

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: tests/lib/L10N/L10nTest.php [hunk 1]
```diff
@@ -85,6 +85,15 @@ public function testCzechPluralTranslations() {
 		$this->assertEquals('5 oken', (string)$l->n('%n window', '%n windows', 5));
 	}
 
+	public function testGermanPluralWithCzechLocaleTranslations() {
+		$transFile = \OC::$SERVERROOT.'/tests/data/l10n/de.json';
+		$l = new L10N($this->getFactory(), 'test', 'de', 'cs_CZ', [$transFile]);
+
+		$this->assertEquals('1 Datei', (string) $l->n('%n file', '%n files', 1));
+		$this->assertEquals('2 Dateien', (string) $l->n('%n file', '%n files', 2));
+		$this->assertEquals('5 Dateien', (string) $l->n('%n file', '%n files', 5));
```
Comment (nickvergessen) [inline tests/lib/L10N/L10nTest.php:94]: Before the patch this here fails:
```
1) Test\L10N\L10nTest::testGermanPluralWithCzechLocaleTranslations
Symfony\Component\Translation\Exception\InvalidArgumentException: Unable to choose a translation for "%count% Datei|%count% Dateien" with locale "cs_CZ" for value "5". Double check that this translation has the correct plural options (e.g. "There is one apple|There are %count% apples").
```

**Review by juliusknorr — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Review by bigcat88 — APPROVED** [review]
