### PR TITLE
Fix DnsPinMiddleware resolve pinning bug

### LINKED ISSUE #27582: GuzzleHttp\Exception\ConnectException: cURL error 7
Nextcloud 21.0.2
and
Nextcloud 22.0.0 beta 5

Ubuntu server 20.04

nginx version: nginx/1.19.3
built by gcc 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)
built with OpenSSL 1.1.1g  21 Apr 2020
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --user=nginx --group=nginx --with-cc-opt=-Wno-deprecated-declarations --with-cc-opt=-Wno-ignored-qualifiers --with-threads --with-file-aio --with-http_ssl_module --with-http_v2_module --with-http_mp4_module --with-http_auth_request_module --with-http_slice_module --with-http_stub_status_module --with-http_realip_module --with-http_sub_module --add-module=/usr/local/src/nginx/modules/incubator-pagespeed-ngx-1.13.35.2-stable --add-module=/usr/local/src/nginx/modules/ngx_brotli --add-module=/usr/local/src/nginx/modules/headers-more-nginx-module-0.33 --add-module=/usr/local/src/nginx/modules/ngx_http_geoip2_module-3.3 --with-openssl=/usr/local/src/nginx/modules/openssl-1.1.1g --add-module=/usr/local/src/nginx/modules/ngx_cache_purge --add-module=/usr/local/src/nginx/modules/fancyindex

PHP 7.4.20

PostgreSQL 13.3

app:list
Enabled:
  - accessibility: 1.7.0
  - activity: 2.15.0
  - circles: 22.0.0-beta.1
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contactsinteraction: 1.2.0
  - dav: 1.18.0
  - federatedfilesharing: 1.11.0
  - files: 1.16.0
  - files_external: 1.12.1
  - files_pdfviewer: 2.3.0
  - files_rightclick: 1.1.0
  - files_sharing: 1.13.2
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.9.0
  - nextcloud_announcements: 1.11.0
  - notes: 4.0.4
  - notifications: 2.10.1
  - oauth2: 1.9.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.11.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.3.0
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.11.0
  - text: 3.3.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.1
  - updatenotification: 1.11.0
  - viewer: 1.6.0
  - workflowengine: 2.3.0
Disabled:
  - admin_audit
  - dashboard
  - encryption
  - federation
  - sharebymail
  - user_ldap
  - user_status
  - weather_status

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud-test.exemple.ru"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "22.0.0.8",
        "overwrite.cli.url": "https:\/\/cloud-test.exemple.ru",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 2,
        "logtimezone": "Asia\/Omsk",
        "logfile": "\/var\/log-cloud\/nextcloud-test.log",
        "log_rotate_size": 52428800,
        "cron_log": true,
        "filesystem_check_changes": true,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "enable_previews": true,
        "enabledPreviewProviders": {
            "1": "OC\\Preview\\Image",
            "2": "OC\\Preview\\PNG",
            "3": "OC\\Preview\\JPEG",
            "4": "OC\\Preview\\GIF",
            "5": "OC\\Preview\\BMP",
            "6": "OC\\Preview\\Movie"
        },
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "updater.release.channel": "beta",
        "theme": "",
        "app_install_overwrite": [
            "onlyoffice",
            "mail",
            "audioplayer",
            "spreed",
            "calendar",
            "social",
            "files_frommail",
            "printer",
            "event_update_notification",
            "audioplayer_sonos",
            "audioplayer_editor"
        ],
        "default_phone_region": "RU",
        "data-fingerprint": "545d956ea4edad554e05e24358758c2f",
        "mail_sendmailmode": "smtp",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

Error | internet_connection_check | GuzzleHttp\Exception\ConnectException:&nbsp;cURL error 7: (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://www.nextcloud.com//var/www/cloud-test/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php&nbsp;- line 158:GuzzleHttp\Handler\CurlFactory::createRejection()/var/www/cloud-test/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php&nbsp;- line 110:GuzzleHttp\Handler\CurlFactory::finishError()/var/www/cloud-test/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php&nbsp;- line 47:GuzzleHttp\Handler\CurlFactory::finish()/var/www/cloud-test/lib/private/Http/Client/DnsPinMiddleware.php&nbsp;- line 124:GuzzleHttp\Handler\CurlHandler-&gt;__invoke()/var/www/cloud-test/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php&nbsp;- line 35:OC\Http\Client\DnsPinMiddleware-&gt;OC\Http\Client\{closure}("*** sensiti ... *")/var/www/cloud-test/3rdparty/guzzlehttp/guzzle/src/Middleware.php&nbsp;- line 31:GuzzleHttp\PrepareBodyMiddleware-&gt;__invoke()/var/www/cloud-test/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php&nbsp;- line 71:GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensiti ... *")/var/www/cloud-test/3rdparty/guzzlehttp/guzzle/src/Middleware.php&nbsp;- line 63:GuzzleHttp\RedirectMiddleware-&gt;__invoke()/var/www/cloud-test/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php&nbsp;- line 75:GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensiti ... *")/var/www/cloud-test/3rdparty/guzzlehttp/guzzle/src/Client.php&nbsp;- line 331:GuzzleHttp\HandlerStack-&gt;__invoke()/var/www/cloud-test/3rdparty/guzzlehttp/guzzle/src/Client.php&nbsp;- line 168:GuzzleHttp\Client-&gt;transfer()/var/www/cloud-test/3rdparty/guzzlehttp/guzzle/src/Client.php&nbsp;- line 187:GuzzleHttp\Client-&gt;requestAsync()/var/www/cloud-test/lib/private/Http/Client/Client.php&nbsp;- line 223:GuzzleHttp\Client-&gt;request()/var/www/cloud-test/apps/settings/lib/Controller/CheckSetupController.php&nbsp;- line 179:OC\Http\Client\Client-&gt;get()/var/www/cloud-test/apps/settings/lib/Controller/CheckSetupController.php&nbsp;- line 162:OCA\Settings\Controller\CheckSetupController-&gt;isSiteReachable()/var/www/cloud-test/apps/settings/lib/Controller/CheckSetupController.php&nbsp;- line 738:OCA\Settings\Controller\CheckSetupController-&gt;hasInternetConnectivityProblems()/var/www/cloud-test/lib/private/AppFramework/Http/Dispatcher.php&nbsp;- line 217:OCA\Settings\Controller\CheckSetupController-&gt;check()/var/www/cloud-test/lib/private/AppFramework/Http/Dispatcher.php&nbsp;- line 126:OC\AppFramework\Http\Dispatcher-&gt;executeController()/var/www/cloud-test/lib/private/AppFramework/App.php&nbsp;- line 156:OC\AppFramework\Http\Dispatcher-&gt;dispatch()/var/www/cloud-test/lib/private/Route/Router.php&nbsp;- line 303:OC\AppFramework\App::main()/var/www/cloud-test/lib/base.php&nbsp;- line 998:OC\Route\Router-&gt;match()/var/www/cloud-test/index.php&nbsp;- line 36:OC::handleRequest()
-- | -- | --

### PR DESCRIPTION
**Pull request by nullspoon**
Fix https://github.com/nextcloud/server/issues/27582
Libcurl expects the value of the CURLOPT_RESOLVE configurations to be an
array of strings, those strings containing a comma delimited list of
resolved IPs for each host:port combination.
  
The original code here does create that array with the host:port:ip
combination, but multiple ips for a single host:port result in
additional array entries, rather than adding them to the end of the
string with a comma. Per the libcurl docs, the `CURLOPT_RESOLVE` array
entries should match the syntax `host:port:address[,address]`.
  
This creates a function-scoped associative array which uses `host:port`
as the key (which are supposed to be unique and this ensures that), and
the value is an array containing IP strings (ipv4 or ipv6). Once the
associative array is populated, it is then set to the CURLOPT_RESOLVE
array, imploding the ip arrays using a comma delimiter so the array
syntax matches the expected by libcurl.
  
Note that this reorders the "foreach ip" and "foreach port" loops.
Rather than looping over ips then ports, we now loop over ports then
ips, since ports are part of the unique host:port map, and multiple ips
can exist therein.

Signed-off-by: Aaron Ball <nullspoon@oper.io>

### CODE REVIEW

**Comment by PVince81** [comment]
@nullspoon mind pointing at the place where you saw that the $options used inside a handler is a numeric non-associative array ?

the docs at https://docs.guzzlephp.org/en/stable/handlers-and-middleware.html aren't very clear about this and just say "array of request options"

this PR would result in an options array looking like this:
```
[
   ['curl' => 
      [CURLOPT_RESOLVE => ['entry1', 'entry2', ...]
   ],
]
```
which means an options array could potentially end up having multiple sets of request options from a single handler, like

```
[
   ['curl' => 
      [CURLOPT_RESOLVE => ['entry1', 'entry2', ...]
   ],
   ['curl' =>
      [CURLOPT_SOMETHING =>...],
   ],
]
```

this feels a bit strange which is why I wanted to double check the docs

**Comment by nullspoon** [comment]
whoops! You're right. Sorry about that. I took a second look through all the docs and bugs I found during research and noticed they mentioned their faq section, which didn't come up during my initial digging. See https://docs.guzzlephp.org/en/stable/faq.html#how-can-i-add-custom-curl-options

> cURL offers a huge number of customizable options. While Guzzle normalizes many of these options across different handlers, there are times when you need to set custom cURL options. This can be accomplished by passing an **associative array** of cURL settings in the curl key of a request.

I'll refactor shortly. :)

**Comment by nullspoon** [comment]
Actually, upon further testing here, I think I might have found a red herring. Something else appears to be causing the bug. I iterrated over the `$options['curl'][CURLOPT_RESOLVE]` array with the original code and it indeed was populated correctly. My fault for missing that. I'll get back to troubleshooting this tomorrow when it's not so late at night.

**Comment by PVince81** [comment]
@nullspoon thanks a lot for your efforts

I still wonder why people in the original ticket have reported that this PR helped fix the issue for them ?

**Comment by nullspoon** [comment]
> @nullspoon thanks a lot for your efforts

I've been using Nextcloud a long time now and and very happy to contribute back to the project if I can!

> I still wonder why people in the original ticket have reported that this PR helped fix the issue for them ?

The reason why my first comment on the bug fixes things is because it removes the call to the `addDnsPinning` method, which is almost certainly where the issue arises. I think the reason why this PR in its current bad state also "fixes" things is because it incorrectly stores these values and so effectively unsets (well, never sets) the `CURLOPT_RESOLVE` configuration, so dns is never pinned, thus it cannot fail.

That said, I woke up this morning and about 10 minutes in I realized what was wrong here. In short, the way the original code is storing dns entries is overriding itself I think. The syntax defined by the libcurl docs is comma-delimited ips per host:port combination, not one ip per host:port, and thus multiple duplicate host:port entries. I'll have an actual fix in for this later today (work calls first!).  😄

**Comment by nullspoon** [comment]
Hokay! I have the fix in and tested on my server with success (actual success this time I think) 😄 

Since the method of fixing is so different, I'm going to force push over my old branch so it only has the actual fix this time around.

File: lib/private/Http/Client/DnsPinMiddleware.php [hunk 1]
```diff
@@ -112,15 +112,22 @@ public function addDnsPinning() {
 
 				$targetIps = $this->dnsResolve($hostName, 0);
 
-				foreach ($targetIps as $ip) {
-					$this->localAddressChecker->ThrowIfLocalIp($ip);
+				$curlResolves = [];
 
-					foreach ($ports as $port) {
-						$curlEntry = $hostName . ':' . $port . ':' . $ip;
```
Comment (PVince81) [inline lib/private/Http/Client/DnsPinMiddleware.php:119]: wouldn't it be much shorter to:
1) separate the local address checker to its own loop: just iterate over target IPs and check them

2) separate the ports loop and do as here: `$curlEntry = $hostName . ':' . $port . ':' . implode(',', $targetIps);`

at least this would require less gymnastics, unless I missed some important detail ?

Comment (kesselb) [reply lib/private/Http/Client/DnsPinMiddleware.php:119]:
```
Index: lib/private/Http/Client/DnsPinMiddleware.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lib/private/Http/Client/DnsPinMiddleware.php b/lib/private/Http/Client/DnsPinMiddleware.php
--- a/lib/private/Http/Client/DnsPinMiddleware.php	(revision 5f8246be971f9e4fb9174dcc2066e853eb9f683e)
+++ b/lib/private/Http/Client/DnsPinMiddleware.php	(date 1625477696112)
@@ -120,14 +120,15 @@
 				}
 
 				$targetIps = $this->dnsResolve($hostName, 0);
+				$targetIps = array_unique($targetIps);
 
 				foreach ($targetIps as $ip) {
 					$this->localAddressChecker->ThrowIfLocalIp($ip);
+				}
 
-					foreach ($ports as $port) {
-						$curlEntry = $hostName . ':' . $port . ':' . $ip;
-						$options['curl'][CURLOPT_RESOLVE][] = $curlEntry;
-					}
+				foreach ($ports as $port) {
+					$curlEntry = $hostName . ':' . $port . ':' . implode(',', $targetIps);
+					$options['curl'][CURLOPT_RESOLVE][] = $curlEntry;
 				}
 
 				return $handler($request, $options);
```

Works for me ;) The array_unique is to filter out duplicate ip addresses. For example www.startpage.com is a cname for startpage.com. `dns_get_record('www.startpage.com', DNS_A);` will return the ip address even if there is no "a" record.

**Review by LukasReschke — APPROVED** [review]
✅  Requesting a website that requests a local resource via CNAME fails

```php
\OC::$server->getHTTPClientService()->newClient()->get('http://localredirect.statuscode.ch');
```

✅  Requesting a website that A records a local address fails

```php
\OC::$server->getHTTPClientService()->newClient()->get('http://localhost.statuscode.ch');
```

The generated `CURLOPT_RESOLVE` also looks reasonable in my testing.

```
[0]=> string(50) "google.de:80:142.251.37.3,2a00:1450:4016:80b::2003"
[1]=> string(51) "google.de:443:142.251.37.3,2a00:1450:4016:80b::2003"
```

**Comment by LukasReschke** [comment]
Failing tests look unrelated.

**Review by skjnldsv — APPROVED** [review]

**Comment by nodje** [comment]
I'm using 22.2.0 and the issue is still there.
If it's been merged into stable22, i assume it'd mean it should be solved in 22.2.0 isn't it?
