### PR TITLE
Fix return type and make type stricter

### LINKED ISSUE #32514: [Bug]: PROPFIND on dav returns null instead of 404
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

With NC23 this works:
- create a file
- do a propfind with comments-unread
- see 207 multi-part response with <oc:comments-unread/> in 404 status part

Now with master it is in 200 status part:
<oc:comments-unread></oc:comments-unread>

As Android expects this to be an integer, it is translated to null, which fails.

### Steps to reproduce

- create a file
- do a propfind with comments-unread

### Expected behavior

Same as in NC23: <oc:comments-unread/> in 404 status part.

### Installation method

Manual installation

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database engine version

_No response_

### Is this bug present after an update or on a fresh install?

_No response_

### Are you using the Nextcloud Server Encryption module?

_No response_

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
/
```

### Nextcloud Signing status

```shell
/
```

### Nextcloud Logs

```shell
/
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by CarlSchwan**
Fix #32514

### CODE REVIEW

**Review by come-nc — APPROVED** [review]

File: apps/dav/lib/Connector/Sabre/CommentPropertiesPlugin.php [hunk 1]
```diff
@@ -115,29 +116,27 @@ public function handleGetProperties(
...
 		$href = $this->server->getBaseUri();
 		$entryPoint = strpos($href, '/remote.php/');
 		if ($entryPoint === false) {
 			// in case we end up somewhere else, unexpectedly.
 			return null;
 		}
-		$commentsPart = 'dav/comments/files/' . rawurldecode($node->getId());
-		$href = substr_replace($href, $commentsPart, $entryPoint + strlen('/remote.php/'));
+		$commentsPart = 'dav/comments/files/' . rawurldecode((string)$node->getId());
+		$href = (string)substr_replace($href, $commentsPart, $entryPoint + strlen('/remote.php/'));
```
Comment (nickvergessen) [inline apps/dav/lib/Connector/Sabre/CommentPropertiesPlugin.php:139]: RedundantCast: Redundant cast to string
```suggestion
		$href = substr_replace($href, $commentsPart, $entryPoint + strlen('/remote.php/'));
```

**Review by nickvergessen — APPROVED** [review]

**Comment by tobiasKaminsky** [comment]
Can you add a test so that this regression cannot happen again?
Having Android/me finding out about this is a bit too late 😇
