### PR TITLE
fix(files): show hidden files and folders count in summary

### LINKED ISSUE #47592: [Bug]: Since NC 28, hidden items counting  are no longer displayed in the folder and file count.
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

This is a Nextcloud 27 screenshot. 

In those days, we had : "X folders and X file (including X hidden)"
Since Nextcloud 28 (28, 29 and 30), “(including X hidden)” has disappeared.

I think it's a bug because I can't see any good reason for removing this information, given that you can always upload or create hidden files or folders and that there's always an option in the settings to show or hide them.

### Steps to reproduce

Read above

### Expected behavior

Read above

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

master

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 28.0.1 to 28.0.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nc30.test.mydomain.fr"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "30.0.0.10",
    "overwrite.cli.url": "https:\/\/nc30.test.mydomain.fr",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "updater.release.channel": "stable",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "log_type": "file",
    "logfile": "\/var\/log\/nextcloud\/nc30.test.mydomain.fr\/nextcloud.log",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "password": "***REMOVED SENSITIVE VALUE***",
        "port": 6379,
        "dbindex": 3,
        "timeout": 0
    },
    "skeletondirectory": "",
    "logtimezone": "Europe\/Paris",
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "PLAIN",
    "default_language": "fr",
    "default_phone_region": "FR",
    "defaultapp": "dashboard,files,photos,activity",
    "trashbin_retention_obligation": "20,40",
    "versions_retention_obligation": "auto,40",
    "appstoreurl": "https:\/\/apps.nextcloud.com\/api\/v1",
    "check_for_working_wellknown_setup": false,
    "quota_include_external_storage": false,
    "cron_log": true,
    "has_internet_connection": true,
    "updatechecker": true,
    "appstoreenabled": true,
    "filelocking.enabled": true,
    "session_keepalive": true,
    "knowledgebaseenabled": true,
    "allow_user_to_change_display_name": true,
    "enable_previews": true,
    "enable_avatars": true,
    "auth.bruteforce.protection.enabled": true,
    "loglevel": 1,
    "log_rotate_size": 104857600,
    "mail_smtpauth": 1,
    "mail_smtpport": 465,
    "session_lifetime": 86400,
    "remember_login_cookie_lifetime": 1296000,
    "preview_max_filesize_image": 50,
    "activity_expire_days": 120,
    "maintenance_window_start": 1,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "app_install_overwrite": [
        "admin_audit",
        "user_ldap",
        "richdocuments",
        "onlyoffice",
        "workspace",
        "groupfolders",
        "deck",
        "contacts"
    ],
    "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
    "maintenance": false
}
```

### List of activated Apps

```shell
Enabled:
 - activity: 3.0.0
 - admin_audit: 1.20.0
 - approve_links: 1.0.2
 - assistant: 2.0.3
 - bruteforcesettings: 3.0.0
 - circles: 30.0.0-dev
 - cloud_federation_api: 1.13.0
 - collectives: 2.14.2
 - comments: 1.20.1
 - contacts: 6.0.0
 - contactsinteraction: 1.11.0
 - context_chat: 3.0.2
 - dashboard: 7.10.0
 - dav: 1.31.1
 - deck: 1.13.1
 - federatedfilesharing: 1.20.0
 - federation: 1.20.0
 - files: 2.2.0
 - files_confidential: 3.0.3
 - files_downloadlimit: 3.0.0
 - files_pdfviewer: 3.0.0
 - files_reminders: 1.3.0
 - files_retention: 1.19.0
 - files_sharing: 1.22.0
 - files_trashbin: 1.20.1
 - files_versions: 1.23.0
 - firstrunwizard: 3.0.0
 - groupfolders: 18.0.0
 - guests: 4.0.0
 - impersonate: 1.17.0
 - integration_deepl: 1.2.0
 - integration_giphy: 1.0.11
 - integration_openai: 3.0.1
 - integration_replicate: 3.0.0
 - intros: 1.0.1
 - logreader: 3.0.0
 - lookup_server_connector: 1.18.0
 - mail: 3.7.7
 - nextcloud_announcements: 2.0.0
 - notes: 4.10.1
 - notifications: 3.0.0
 - oauth2: 1.18.0
 - onlyoffice: 9.3.0
 - password_policy: 2.0.0
 - photos: 3.0.2
 - privacy: 2.0.0
 - provisioning_api: 1.20.0
 - recommendations: 3.0.0
 - related_resources: 1.5.0
 - richdocuments: 8.4.5
 - serverinfo: 2.0.0
 - settings: 1.13.0
 - sharebymail: 1.20.0
 - sharereview: 1.1.0
 - support: 2.0.0
 - systemtags: 1.20.0
 - tables: 0.7.5
 - tasks: 0.16.1
 - text: 4.1.0
 - text2image_stablediffusion: 1.1.0
 - theming: 2.5.0
 - twofactor_backupcodes: 1.19.0
 - twofactor_nextcloud_notification: 4.0.0
 - updatenotification: 1.20.0
 - user_ldap: 1.21.0
 - user_status: 1.10.0
 - viewer: 3.0.0
 - weather_status: 1.10.0
 - workflowengine: 2.12.0
 - workspace: 4.0.0-dev3
Disabled:
 - encryption
 - files_external
 - survey_client: 2.0.0
 - suspicious_login
 - twofactor_totp
 - webhook_listeners
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Can be provided if necessary
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/server/issues/47592

| Shown | Hidden |
|:---------:|:------:|
|||

### CODE REVIEW

File: apps/files/src/utils/fileUtils.ts [hunk 1]
```diff
@@ -21,25 +21,31 @@ export const extractFilePaths = function(path) {
...
+		summary = n('files', '{fileCount} file and 1 folder', '{fileCount} files and 1 folder', fileCount, { fileCount })
+	} else {
+		summary = t('files', '{fileCount} files and {folderCount} folders', { fileCount, folderCount })
 	}
 
-	if (folderCount === 1) {
-		return n('files', '{fileCount} file and 1 folder', '{fileCount} files and 1 folder', fileCount, { fileCount })
+	if (hidden > 0) {
+		// TRANSLATORS: This is a summary of files and folders, where {hiddenFilesAndFolders} is the number of hidden files and folders
+		summary += n('files', ' ({hiddenFilesAndFolders} hidden)', ' ({hiddenFilesAndFolders} hidden)', hidden, { hiddenFilesAndFolders: hidden })
```
Comment (skjnldsv) [inline apps/files/src/utils/fileUtils.ts:47]: Used a string concat anyway as the context is different. Covering all possible cases with two different plural variables is far too complex and not worth it

**Review by AndyScherzinger — APPROVED** [review]

File: apps/files/src/utils/fileUtils.ts (hunk 1 above)
Comment (susnux) [reply apps/files/src/utils/fileUtils.ts:47]: Its not needed when you have multiple sentences. (you can always concat multiple sentences in languages, this is also correct for RTL and is even recommended for longer text blocks).

Comment (skjnldsv) [reply apps/files/src/utils/fileUtils.ts:47]: Can you suggest an alternative then? Because I scratched my brain and couldn't figure one out :thinking:

Comment (susnux) [reply apps/files/src/utils/fileUtils.ts:47]: but do not have any leading whitespace.
```suggestion
		summary += ' ' + n('files', '(%n hidden)', ' (%n hidden)', hidden)
```

File: apps/files/src/views/FilesList.vue [hunk 2]
```diff
@@ -165,35 +166,36 @@ import IconAlertCircleOutline from 'vue-material-design-icons/AlertCircleOutline
...
-import NcEmptyContent from '@nextcloud/vue/components/NcEmptyContent'
-import NcIconSvgWrapper from '@nextcloud/vue/components/NcIconSvgWrapper'
-import NcLoadingIcon from '@nextcloud/vue/components/NcLoadingIcon'
+import NcAppContent from '@nextcloud/vue/dist/Components/NcAppContent.js'
+import NcActions from '@nextcloud/vue/dist/Components/NcActions.js'
+import NcActionButton from '@nextcloud/vue/dist/Components/NcActionButton.js'
+import NcButton from '@nextcloud/vue/dist/Components/NcButton.js'
+import NcEmptyContent from '@nextcloud/vue/dist/Components/NcEmptyContent.js'
+import NcIconSvgWrapper from '@nextcloud/vue/dist/Components/NcIconSvgWrapper.js'
+import NcLoadingIcon from '@nextcloud/vue/dist/Components/NcLoadingIcon.js'
```
Comment (susnux) [inline apps/files/src/views/FilesList.vue:175]: Please revert import style.

**Review by susnux — DISMISSED** [review]
Looks good, but please revert the changes to the nextcloud-vue imports.

File: apps/files/src/utils/fileUtils.ts (hunk 1 above)
Comment (susnux) [reply apps/files/src/utils/fileUtils.ts:47]: @skjnldsv no I meant its correct what you are doing :)

File: apps/files/src/views/FilesList.vue (hunk 2 above)
Comment (skjnldsv) [reply apps/files/src/views/FilesList.vue:175]: Weird, I guess I missed it in a rebase :thinking: 
Nice catch!

File: apps/files/src/utils/fileUtils.ts (hunk 1 above)
Comment (skjnldsv) [reply apps/files/src/utils/fileUtils.ts]: Ah, nice!
I'm reassured :sweat_smile:

Comment (susnux) [reply apps/files/src/utils/fileUtils.ts]: E.g. this would be correct:

```ts
const files = n('%n file', '%n files', numberFiles)
const folders = n('%n folder', '%n folders', numberFolders)
const hidden = n('%n hidden', '%n hidden', numberHidden)
let summary = ''
if (numberFiles > 0) {
    summary = files
}
if (numberFolders > 0) {
    if (summary !== '') {
        summary += ' • '
    }
    summary += folders
}
if (numberHidden > 0) {
    if (summary !== '') {
        summary += ' • '
    }
    summary += hidden
}
```

Which is equal to vue:
```html
<div>
    <span v-if="numberFiles">{{ n('%n file', '%n files', numberFiles) }}</span>
    <span v-if="numberFolders">
        <span v-if="numberFiles">•</span>
        {{ n('%n folder', '%n folders', numberFolders) }}</span>
    </span>
    <span v-if="numberHidden">
        <span v-if="numberFiles || numberFolders">•</span>
        {{ n('%n hidden', '%n hidden', numberHidden) }}</span>
    </span>
</div>
```

**Review by susnux — APPROVED** [review]
