### PR TITLE
Set up FS before querying storage info in settings

### LINKED ISSUE #24099: `Call to a member function getFileInfo() on null` on /settings/user page
```json
{
  "reqId": "5GdOC6Zt2kvmbJIF8JsE",
  "level": 3,
  "time": "2020-11-13T10:03:21+00:00",
  "remoteAddr": "172.19.0.1",
  "user": "admin",
  "app": "index",
  "method": "GET",
  "url": "/settings/user",
  "message": {
    "Exception": "Exception",
    "Message": "Call to a member function getFileInfo() on null",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/App.php",
        "line": 157,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OCA\\Settings\\Controller\\PersonalSettingsController"
          },
          "index"
        ]
      },
      {
        "file": "/var/www/nextcloud/lib/private/Route/Router.php",
        "line": 309,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::",
        "args": [
          "OCA\\Settings\\Controller\\PersonalSettingsController",
          "index",
          {
            "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
          },
          {
            "section": "personal-info",
            "action": null,
            "_route": "settings.PersonalSettings.index"
          }
        ]
      },
      {
        "file": "/var/www/nextcloud/lib/base.php",
        "line": 1008,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->",
        "args": [
          "/settings/user"
        ]
      },
      {
        "file": "/var/www/nextcloud/index.php",
        "line": 37,
        "function": "handleRequest",
        "class": "OC",
        "type": "::",
        "args": []
      }
    ],
    "File": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
    "Line": 159,
    "Previous": {
      "Exception": "Error",
      "Message": "Call to a member function getFileInfo() on null",
      "Code": 0,
      "Trace": [
        {
          "file": "/var/www/nextcloud/lib/private/legacy/OC_Helper.php",
          "line": 488,
          "function": "getFileInfo",
          "class": "OC\\Files\\Filesystem",
          "type": "::",
          "args": [
            "/",
            false
          ]
        },
        {
          "file": "/var/www/nextcloud/apps/settings/lib/Settings/Personal/PersonalInfo.php",
          "line": 108,
          "function": "getStorageInfo",
          "class": "OC_Helper",
          "type": "::",
          "args": [
            "/"
          ]
        },
        {
          "file": "/var/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php",
          "line": 137,
          "function": "getForm",
          "class": "OCA\\Settings\\Settings\\Personal\\PersonalInfo",
          "type": "->",
          "args": []
        },
        {
          "file": "/var/www/nextcloud/apps/settings/lib/Controller/PersonalSettingsController.php",
          "line": 77,
          "function": "formatSettings",
          "class": "OCA\\Settings\\Controller\\PersonalSettingsController",
          "type": "->",
          "args": [
            {
              "10": [
                {
                  "__class__": "OCA\\Settings\\Settings\\Personal\\PersonalInfo"
                }
              ],
              "1000": [
                {
                  "__class__": "OCA\\Settings\\Settings\\Personal\\ServerDevNotice"
                }
              ]
            }
          ]
        },
        {
          "file": "/var/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php",
          "line": 148,
          "function": "getSettings",
          "class": "OCA\\Settings\\Controller\\PersonalSettingsController",
          "type": "->",
          "args": [
            "personal-info"
          ]
        },
        {
          "file": "/var/www/nextcloud/apps/settings/lib/Controller/PersonalSettingsController.php",
          "line": 68,
          "function": "getIndexResponse",
          "class": "OCA\\Settings\\Controller\\PersonalSettingsController",
          "type": "->",
          "args": [
            "personal",
            "personal-info"
          ]
        },
        {
          "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
          "line": 218,
          "function": "index",
          "class": "OCA\\Settings\\Controller\\PersonalSettingsController",
          "type": "->",
          "args": [
            "personal-info"
          ]
        },
        {
          "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
          "line": 127,
          "function": "executeController",
          "class": "OC\\AppFramework\\Http\\Dispatcher",
          "type": "->",
          "args": [
            {
              "__class__": "OCA\\Settings\\Controller\\PersonalSettingsController"
            },
            "index"
          ]
        },
        {
          "file": "/var/www/nextcloud/lib/private/AppFramework/App.php",
          "line": 157,
          "function": "dispatch",
          "class": "OC\\AppFramework\\Http\\Dispatcher",
          "type": "->",
          "args": [
            {
              "__class__": "OCA\\Settings\\Controller\\PersonalSettingsController"
            },
            "index"
          ]
        },
        {
          "file": "/var/www/nextcloud/lib/private/Route/Router.php",
          "line": 309,
          "function": "main",
          "class": "OC\\AppFramework\\App",
          "type": "::",
          "args": [
            "OCA\\Settings\\Controller\\PersonalSettingsController",
            "index",
            {
              "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
            },
            {
              "section": "personal-info",
              "action": null,
              "_route": "settings.PersonalSettings.index"
            }
          ]
        },
        {
          "file": "/var/www/nextcloud/lib/base.php",
          "line": 1008,
          "function": "match",
          "class": "OC\\Route\\Router",
          "type": "->",
          "args": [
            "/settings/user"
          ]
        },
        {
          "file": "/var/www/nextcloud/index.php",
          "line": 37,
          "function": "handleRequest",
          "class": "OC",
          "type": "::",
          "args": []
        }
      ],
      "File": "/var/www/nextcloud/lib/private/Files/Filesystem.php",
      "Line": 864
    },
    "CustomMessage": "--"
  },
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
  "version": "21.0.0.7"
}
```

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/nextcloud/server/issues/24099

The personal info section of the personal settings is querying the
storage quota information. For this it requires the FS to be setup which
is not always guaranteed.

This fixes an issue where refreshing the settings page would cause it to
fail after Redis caches are full. It is likely that when Redis cache is
populated, some code path is initializing the FS, so it works so far.
But when the cache is populated, that code path is skipped so the FS is
not guaranteed to be setup...

- [x] check if this happens on stable20

### CODE REVIEW

**Comment by PVince81** [comment]
it doesn't happen on stable20 but I'd still recommend a backport, just as a measure of precaution...

**Review by skjnldsv — APPROVED** [review]

File: lib/private/legacy/OC_Helper.php [hunk 1]
```diff
@@ -475,6 +475,9 @@ public static function findBinaryPath($program) {
 	/**
 	 * Calculate the disc space for the given path
 	 *
+	 * BEWARE: this requires that Util::setupFS() was called
```
Comment (ChristophWurst) [inline lib/private/legacy/OC_Helper.php:478]: so can't we move the call into this method? :thinking:

Comment (PVince81) [reply lib/private/legacy/OC_Helper.php:478]: not sure if this will have side effects. in theory there should not be any.
but for some reason the setupFS was added outside for other calls, so not sure

**Review by ChristophWurst — APPROVED** [review]

File: lib/private/legacy/OC_Helper.php (hunk 1 above)
Comment (PVince81) [reply lib/private/legacy/OC_Helper.php:478]: now thinking further: setupFS would need a user and I'm unsure if it's safe letting it assume what the current user is.
this is very old code, I'd rather not wake up old ghosts :sweat_smile:
