### PR TITLE
fix(ConvertType): Read dbtype in createConnectionParams and remove safeguard

### LINKED ISSUE #45257: [Bug]: `occ db:convert-type` broken since `PrimaryReadReplicaConnection` support added
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The OCC-Command `db:convert-type` seems to ignore the DB properties (type, user, host, database, port, password) provided through the CLI and instead operates on the database configured in `config.php`

I believe this may be related to the commit  79c4986 as this reworked the parameter handling in `ConnectionFactory.php`.

If I read this correctly, the default parameters are now always generated based on the system config instead of the passed arguments.

Running `db:convert-type --clean-schema` drops the tables in the "old" database.

### Steps to reproduce

1. Have Nextcloud 29.0.0 running with a MySQL database, and an empty PostgreSQL database
2. run `php occ db:convert-type --password=<PASSWORD> --port=5432 pgsql nextcloud_app postgres nextcloud` (note: the host `postgres` is a Kubernetes service name)
3. The command executes no matter if the Postgres Database is running or not, the command throws Constraint Violation errors in the table `oc_accounts`, I assume because it tries to migrate the content of the old database into itself.

### Expected behavior

`db:convert-type` 

### Installation method

Community Docker image

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.178.32",
            "cloud.awae.ch"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "29.0.0.19",
        "overwrite.cli.url": "https:\/\/cloud.awae.ch",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "overwriteprotocol": "https",
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "default_language": "de",
        "default_phone_region": "CH",
        "app_install_overwrite": [
            "polls"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.21.1
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - comments: 1.19.0
  - contactsinteraction: 1.10.0
  - dashboard: 7.9.0
  - dav: 1.30.1
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.0
  - files_downloadlimit: 2.0.0
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - firstrunwizard: 2.18.0
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - nextcloud_announcements: 1.18.0
  - notes: 4.10.0
  - notifications: 2.17.0
  - oauth2: 1.17.0
  - password_policy: 1.19.0
  - photos: 2.5.0
  - polls: 7.0.3
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - support: 1.12.0
  - survey_client: 1.17.0
  - systemtags: 1.19.0
  - text: 3.10.0
  - theming: 2.4.0
  - twofactor_backupcodes: 1.18.0
  - updatenotification: 1.19.1
  - viewer: 2.3.0
  - workflowengine: 2.11.0
Disabled:
  - admin_audit: 1.19.0
  - bruteforcesettings: 2.9.0 (installed 2.4.0)
  - encryption: 2.17.0
  - extract: 1.3.6 (installed 1.3.6)
  - files_external: 1.21.0
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - maps: 1.1.0 (installed 1.1.0)
  - suspicious_login: 7.0.0
  - twofactor_totp: 11.0.0-dev
  - user_ldap: 1.20.0
  - user_status: 1.9.0 (installed 1.4.0)
  - weather_status: 1.9.0 (installed 1.4.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

_No response_

### Additional info

* Docker Image: `nextcloud:29.0.0`
* MySQL Database: `mysql:8.4.0`
* Postgres Databse: `postgres:16.3`

### PR DESCRIPTION
**Pull request by provokateurin**
## Summary

Fixes https://github.com/nextcloud/server/issues/45257
Unforked version of https://github.com/nextcloud/server/pull/48666.
While testing I also found that https://github.com/nextcloud/server/pull/39242 read the hostname wrong which never worked.

I tested it successfully like this (make sure to have `pdo_pgsql` enabled):
```
docker run --rm --network=host --env POSTGRES_PASSWORD=postgres postgres:17
./occ maintenance:install --admin-pass admin
./occ db:convert-type --all-apps --password=postgres -- pgsql postgres localhost postgres
rm data/owncloud.db
```

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: core/Command/Db/ConvertType.php [hunk 1]
```diff
@@ -243,7 +236,7 @@ protected function getToDBConnection(InputInterface $input, OutputInterface $out
 		}
 
 		// parse hostname for unix socket
-		if (preg_match('/^(.+)(:(\d+|[^:]+))?$/', $input->getOption('hostname'), $matches)) {
+		if (preg_match('/^(.+)(:(\d+|[^:]+))?$/', $input->getArgument('hostname'), $matches)) {
```
Comment (solracsf) [inline core/Command/Db/ConvertType.php:239]: Is this regex really necessary? Would this be more efficient?

```
$hostname = $input->getArgument('hostname');
if (str_contains($hostname, ':')) {
    [$host, $suffix] = explode(':', $hostname, 2);
    $connectionParams['host'] = $host;

    if (is_numeric($suffix)) {
        $connectionParams['port'] = $suffix;
    } else {
        $connectionParams['unix_socket'] = $suffix;
    }
} else {
    $connectionParams['host'] = $hostname;
}
```

File: core/Command/Db/ConvertType.php [hunk 2]
```diff
@@ -229,7 +222,7 @@ protected function createSchema(Connection $fromDB, Connection $toDB, InputInter
 
 	protected function getToDBConnection(InputInterface $input, OutputInterface $output) {
 		$type = $input->getArgument('type');
-		$connectionParams = $this->connectionFactory->createConnectionParams();
+		$connectionParams = $this->connectionFactory->createConnectionParams('', [], $type);
```
Comment (nfebe) [inline core/Command/Db/ConvertType.php:225]:
```suggestion
		$connectionParams = $this->connectionFactory->createConnectionParams(type:$$type);
```

**Review by nfebe — COMMENTED** [review]
Are the any auto tests for this?

**Comment by provokateurin** [comment]
> Are the any auto tests for this?

No unfortunately not, as changing the DB inside the tests is not a good idea. I still want to add a test for it later though, but will have to see in what form.

**Review by come-nc — APPROVED** [review]

**Review by nfebe — APPROVED** [review]
