### PR TITLE
Shorten index name of calendar changes table

### LINKED ISSUE #12410: Unknown column 'calendartype' (table calendarobjects)
As discovered when testing https://github.com/nextcloud/contacts/pull/706, it's not possible to create a contact on latest master. Apparently this is a regression of https://github.com/nextcloud/server/pull/10059.

Raw DAV response (HTTP500)
```xml
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Doctrine\DBAL\Exception\InvalidFieldNameException</s:exception>
  <s:message>An exception occurred while executing 'SELECT `id`, `uri`, `lastmodified`, `etag`, `calendarid`, `size`, `calendardata`, `componenttype`, `classification` FROM `oc_calendarobjects` WHERE (`calendarid` = ?) AND (`uri` = ?) AND (`calendartype` = ?)' with params ["18", "contacts-5942F193-088E-41FE-AABD-8044A15194E1.vcf.ics", 0]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'calendartype' in 'where clause'</s:message>
</d:error>

```

This column was added in #10593, but the migration was never run:
```
> select * from oc_migrations where app = 'dav' and version = '1006Date20180628111625';
Empty set (0.00 sec)
```

cc @georgehrke @nickvergessen

### LINKED ISSUE #12446: Index identifier `calendarid_calendartype_synctoken` is too long
Oracle install is broken again:
> An exception occurred while executing 'CREATE INDEX calendarid_calendartype_synctoken ON \"oc_calendarchanges\" (\"calendarid\", \"calendartype\", \"synctoken\")':\n\nORA-00972: identifier is too long

Regression from https://github.com/nextcloud/server/pull/10059

cc @georgehrke

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #12446 
Fix #12410

### CODE REVIEW

**Comment by nickvergessen** [comment]
Tests running in https://travis-ci.org/nextcloud/notifications/builds/454880005

File: apps/dav/composer/composer/ClassLoader.php [hunk 1]
```diff
@@ -279,7 +279,7 @@ public function isClassMapAuthoritative()
      */
     public function setApcuPrefix($apcuPrefix)
     {
-        $this->apcuPrefix = function_exists('apcu_fetch') && filter_var(ini_get('apc.enabled'), FILTER_VALIDATE_BOOLEAN) ? $apcuPrefix : null;
+        $this->apcuPrefix = function_exists('apcu_fetch') && ini_get('apc.enabled') ? $apcuPrefix : null;
```
Comment (MorrisJobke) [inline apps/dav/composer/composer/ClassLoader.php]: This looks like you are using an outdated composer. Because my local composer (which says is up to date) also produced the output as stated in the deleted line and the checker CI job also complains.

File: apps/dav/lib/Migration/Version1008Date20181114084440.php [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+	 * @param IOutput $output
+	 * @param Closure $schemaClosure The `\Closure` returns a `ISchemaWrapper`
+	 * @param array $options
+	 * @return null|ISchemaWrapper
+	 */
+	public function changeSchema(IOutput $output, Closure $schemaClosure, array $options) {
+		/** @var ISchemaWrapper $schema */
+		$schema = $schemaClosure();
+
+		if ($schema->hasTable('calendarchanges')) {
```
Comment (MorrisJobke) [inline apps/dav/lib/Migration/Version1008Date20181114084440.php]: Why is this needed? Can't we assume, that it is there? Same for the other two if statements below.

Comment (nickvergessen) [reply apps/dav/lib/Migration/Version1008Date20181114084440.php]: I just copied the original migration, yes we could assume it exists, but does it hurt?

File: apps/dav/composer/composer/ClassLoader.php (hunk 1 above)
Comment (nickvergessen) [reply apps/dav/composer/composer/ClassLoader.php]: yeah, still had 1.7.2, now all other ClassLoaders where updated to the filter_var version

**Comment by danielkesselberg** [comment]
I guess it's not wrong to use short table/index/whatever names but oracle 11 is eol (without a subscription) since 2017. The 30 characters limitation has been increased to 128 with 12.2 (https://blog.dbi-services.com/oracle-12cr2-long-identifiers/). Maybe running the tests with a newer oracle db would work? :confused:

**Comment by nickvergessen** [comment]
Well most people that use Oracle in a larger instance have a subscription.

File: apps/dav/lib/Migration/Version1008Date20181114084440.php (hunk 2 above)
Comment (MorrisJobke) [reply apps/dav/lib/Migration/Version1008Date20181114084440.php]: Not really - it just confuses.

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Comment by MorrisJobke** [comment]
@rullzer Mind to review?

**Review by rullzer — APPROVED** [review]
