### PR TITLE
fix(session): Avoid useless authtoken DB queries for anonymous requests

### LINKED ISSUE #42589: [Bug]: Two useless authtoken database queries for every anonymous request
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Reading query logs I noticed

```
 primary SELECT * FROM `oc_appconfig`
 replica SELECT * FROM `oc_authtoken` WHERE (`token` = :dcValue1) AND (`version` = :dcValue2)
 replica SELECT * FROM `oc_authtoken` WHERE (`token` = :dcValue1) AND (`version` = :dcValue2)
```

for every anonymous request.

The problem is that `\OC\User\Session::tryTokenLogin` tries to find a token for the current PHP session. `\OC\Authentication\Token\PublicKeyTokenProvider::getToken` does up to two lookups when the instance has an instance secret set. **There will never be a hit**. The only exception would be a hash collision of the new session ID and a previous one.

The solution would be to check if the request had sent a cookie with the instance id as name. Those are used for the PHP session. If there is no cookie, this is a new session, and there won't be a token.

### Steps to reproduce

1.  ``curl https://localhost/login``

### Expected behavior

```
 primary SELECT * FROM `oc_appconfig`
```

### Installation method

None

### Nextcloud Server version

26

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by solracsf**
* Resolves: https://github.com/nextcloud/server/issues/42589

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: lib/private/User/Session.php [hunk 1]
```diff
@@ -858,6 +858,13 @@ public function tryTokenLogin(IRequest $request) {
 			return false;
 		}
 
+		// Check if the request had sent a cookie with the instance id as name
+		// If there is no cookie, this is a new session
+		$instanceId = $this->config->getSystemValueString('instanceid');
+		if (is_null($request->getCookie($instanceId))) {
+			return false;
+		}
```
Comment (juliushaertl) [inline lib/private/User/Session.php:866]: Without looking in depth, just from the following code lines I think that this could have unexpected side effects when just authenticating with an app password which is also a token but not necessarily has cookies if clients send it.

Comment (ChristophWurst) [reply lib/private/User/Session.php]: Adjusted so that the token lookup by session id only happens if there is neither an Authrorization header nor session cookie

**Review by ChristophWurst — APPROVED** [review]
Bildschirmfoto vom 2024-01-16 19-19-41

:+1: as expected

tested with 100 samples of `GET /login`

**Review by juliusknorr — APPROVED** [review]

File: lib/private/User/Session.php [hunk 2]
```diff
@@ -842,13 +842,16 @@ public function tryTokenLogin(IRequest $request) {
 		$authHeader = $request->getHeader('Authorization');
 		if (str_starts_with($authHeader, 'Bearer ')) {
 			$token = substr($authHeader, 7);
-		} else {
-			// No auth header, let's try session id
+		} else if ($request->getCookie($this->config->getSystemValueString('instanceid')) !== null) {
```
Comment (solracsf) [inline lib/private/User/Session.php:845]:
```suggestion
		} elseif ($request->getCookie($this->config->getSystemValueString('instanceid')) !== null) {
```
