### PR TITLE
Do not setup a session when not required on API requests

### LINKED ISSUE #7628: Session handling: api and webdav requests shall not start a session
### Steps to reproduce
1. Use NextCloud with macOS Calendar
2. do find phptmp/* | wc -l 
3. get: 3825 -> more than 3800 session files in about 1-2 weeks

### Expected behaviour
For WebDav connections there should be no session file generated.

### Actual behaviour
for every webdav connection there is a session file

For the rest, take a look at: 
https://github.com/owncloud/core/issues/29779

and the old one: 
https://github.com/owncloud/core/issues/5383

and last but not least, be faster as the oc-team. nah just kidding, merry christmas and a happy new year :-)

### LINKED ISSUE #27603: Hundreds of odd oc_authtoken entries for a user slow down performance
This is a summary of https://help.nextcloud.com/t/hundreds-of-odd-oc-authtoken-entries-slow-down-performance-for-a-user-bug-report/117742

### Expected behaviour
1 oc_authtoken per user+device

$ curl -s -X PROPFIND "https://SERVER/remote.php/webdav/Handy/DCIM/Camera/IMG_2021-0602_202145.jpg" -u user2
→ 1-2 seconds

### Actual behaviour
hundreds of oc_authtoken entries:
$ mysql mycloud -B -e "select count(\*) from oc_authtoken where uid='andy'"
count(*)
167

$ curl -X PROPFIND "https://SERVER/remote.php/webdav/Handy/DCIM/Camera/IMG_20210602_223758.jpg" -u andy
→ between 12-17 seconds

After "DELETE \* from oc_authtoken where uid=‘andy’"
the server responds quick again. The curl command needs less than a second.

But this was not a permanent solution. 157 new(!) entries were back the next day.
Here is just a short part of it:

### Questions/Doubts
- Where did all these extra DB lines come from?
- Why do they reappear after a while
- Why did they have no effect until the update to NC 21?

### Server configuration

**Operating system:**
4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

**Web server:**
Apache 2.4.38-3+deb10u4

**Database:**
mysql  Ver 15.1 Distrib 10.3.27-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:**
PHP version (eg, 7.4): 2:7.3+69

**Nextcloud version:** (see Nextcloud admin page)
21.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
latest v20

**Where did you install Nextcloud from:**
with the internal NC updater

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - admin_audit: 1.11.0
  - apporder: 0.12.0
  - audioplayer: 3.1.0
  - bbb: 1.4.1
  - bookmarks: 4.2.2
  - bruteforcesettings: 2.2.0
  - calendar: 2.2.2
  - carnet: 0.24.1
  - cloud_federation_api: 1.4.0
  - cms_pico: 1.0.15
  - comments: 1.11.0
  - contacts: 3.5.1
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - data_request: 1.8.0
  - dav: 1.17.1
  - deck: 1.4.2
  - drawio: 1.0.0
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_external: 1.12.0
  - files_markdown: 2.3.3
  - files_pdfviewer: 2.1.0
  - files_retention: 1.10.1
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - forms: 2.2.4
  - gpxmotion: 0.1.0
  - gpxpod: 4.2.8
  - impersonate: 1.8.0
  - integration_google: 1.0.2
  - integration_whiteboard: 0.0.14
  - integration_zammad: 1.0.1
  - keeweb: 0.6.5
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - mail: 1.9.5
  - nextcloud_announcements: 1.10.0
  - notes: 4.0.4
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - openhab: 0.9.5
  - password_policy: 1.11.0
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - rainloop: 7.1.2
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - socialsharing_email: 2.2.0
  - spreed: 11.2.2
  - support: 1.4.0
  - survey_client: 1.9.0
  - systemtags: 1.11.0
  - tasks: 0.13.6
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - user_usage_report: 1.5.0
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
Disabled:
  - encryption
  - passwords
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 2,
        "theme": "",
        "trusted_domains": [
            "cloud.mydomain.de",
        ],
        "share_folder": "\/Shared",
        "defaultapp": "calendar",
        "trashbin_retention_obligation": "auto, 14",
        "versions_retention_obligation": "auto, 14",
        "default_language": "en",
        "default_phone_region": "DE",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "overwrite.cli.url": "https:\/\/cloud.mydomain.de",
        "blacklisted_files": [
            "._*",
            ".DS_Store",
            ".DS_STORE",
            ".ds_store"
        ],
        "integrity.check.disabled": false,
        "mysql.utf8mb4": true,
        "mail_smtpauthtype": "LOGIN",
        "mail_sendmailmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "tls",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "apporder",
            "calendar",
            "bookmarks"
        ],
        "has_rebuilt_cache": true,
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
irrelevant

#### Web server error log
<details>
<summary>Web server error log</summary>

```
(only irrelevant lines like:)
[Tue Jun 22 16:57:47.274268 2021] [access_compat:error] [pid 32647] [client 62.216.xx.yy:64788] AH01797: client denied by server configuration: /var/www/nextcloud/config
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"YNIMvrdbUoVOcoItzNhK1QAAAAw","level":3,"time":"2021-06-22T16:15:59+00:00","remoteAddr":"138.246.3.189","user":"andy","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/andy/","message":"Module 'mbstring' already loaded at Unknown#0","userAgent":"Mozilla/5.0 (Linux) mirall/3.2.2-20210531.142805.04afaa1fe-1.0~focal1 (Nextcloud, ubuntu-5.4.0-74-generic ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"21.0.2.1"}
```

The output of your Nextcloud log in Admin > Logging:
 ``Error	PHP	Module 'mbstring' already loaded at Unknown#0``
(shows up every time when I call curl)
</details>

### PR DESCRIPTION
**Pull request by juliusknorr**
This would resolve https://github.com/nextcloud/server/issues/7628 as currently every API request to webdav/OCS that is using HTTP auth is generating a PHP session even though it is never used afterwards as any follow-up request is sending the auth headers again and therefore just creating another session. This reduces the amount of sessions being created and that would need to be kept by the php session handler which might otherwise grow extensively on large setups with logs of API calls happening.

As we already use a wrapper for the session returning early in the session setup will just result in the memory session implementation being used as a fallback https://github.com/nextcloud/server/blob/7179002600ccde6d6757c068c9388430ed71a2f1/lib/private/Server.php#L516

Ideally the check would be performed when the request is handled and the login checks are performed is handled, but the risk of breaking something when setting up the session that late in the execution flow seems much higher.

Fix https://github.com/nextcloud/server/issues/27603

- [x] Double check if authtokens get still created and shown in the security settings
- [x] Get rid of config flag and make it the default behaviour
- [ ] Smoke testing with pyocclient 
- [x] Still attempt to initiate a session if a session cookie is present during the request, this could happen on public share links if the browser sends both the existing session cookie as well as basic auth for the share link token/password

### CODE REVIEW

**Review by Pytal — DISMISSED** [review]

**Review by CarlSchwan — DISMISSED** [review]

**Comment by juliushaertl** [comment]
Some integration test failures I've not seen so far. Will look into those:

- [ ] integration-auth
- [ ] integration-provisioning
- [ ] integration-download

They all seem related to the attempt to use the session id:
```
{"Exception":"OCP\\Session\\Exceptions\\SessionNotAvailableException","Message":"Memory session does not have an ID","Code":0,"Trace":[{"file":"\/drone\/src\/lib\/private\/Authentication\/TwoFactorAuth\/Manager.php","line":348,"function":"getId","class":"OC\\Session\\Memory","type":"->","args":[]},{"file":"\/drone\/src\/lib\/private\/legacy\/OC_Util.php","line":1065,"function":"needsSecondFactor","class":"OC\\Authentication\\TwoFactorAuth\\Manager","type":"->","args":[{"__class__":"OC\\User\\User"}]},{"file":"\/drone\/src\/apps\/files\/recentlist.php","line":27,"function":"checkLoggedIn","class":"OC_Util","type":"::","args":[]},{"file":"\/drone\/src\/apps\/files\/lib\/Controller\/ViewController.php","line":136,"args":["\/drone\/src\/apps\/files\/recentlist.php"],"function":"include"},{"file":"\/drone\/src\/apps\/files\/lib\/Controller\/ViewController.php","line":276,"function":"renderScript","class":"OCA\\Files\\Controller\\ViewController","type":"->","args":["files","recentlist.php"]},{"file":"\/drone\/src\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":217,"function":"index","class":"OCA\\Files\\Controller\\ViewController","type":"->","args":["","",null,false,null]},{"file":"\/drone\/src\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\ViewController"},"index"]},{"file":"\/drone\/src\/lib\/private\/AppFramework\/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\ViewController"},"index"]},{"file":"\/drone\/src\/lib\/private\/Route\/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files\\Controller\\ViewController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"files.view.index"}]},{"file":"\/drone\/src\/lib\/base.php","line":1004,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/files"]},{"file":"\/drone\/src\/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/drone\/src\/lib\/private\/Session\/Memory.php","Line":107,"CustomMessage":"--"}
```

**Comment by juliushaertl** [comment]
- [ ] Integration tests seem to make quite some heavy use of sending requests with basic auth and a cookie for the session, which currently breaks with the new approach

**Comment by martinlanger90** [comment]
Hopefully soon gets merged. I want to get rid of that thousands of session files.

**Comment by PVince81** [comment]
this could also break tools like https://github.com/owncloud/pyocclient which also rely on the session, I imagine that there might be more out there so this PR would need to be treated as "breaking change" which we cannot backport

or if backport, have a config switch with a different default in previous versions for those setups where the admin knows what kind of clients are being used

and maybe such switch could be turned on for the integration tests to pass, for now @juliushaertl 

- [ ] clarify compatibility / backportability

**Comment by PVince81** [comment]
Tests:

- [ ] Android files app
- [ ] Android talk app
- [ ] iOS files app
- [ ] iOS talk app
- [ ] Desktop client

**Comment by PVince81** [comment]
it looks like the tests like https://github.com/nextcloud/server/blob/enh/http-auth-session/build/integration/features/auth.feature#L19 were expecting basic auth to create a session when done on the web UI endpoints like "index.php/apps/files" as the subsequent test is relying on said session

but in this PR the session is not created any more in that case, not sure if we should keep this or if we should filter the session removal to DAV and OCS only ? @juliushaertl 

depending on the latter decision we'll need to rework the tests to reflect the expected behavior

**Comment by PVince81** [comment]
- [ ] we need to rediscuss whether a switch is preferable: the decision about not having a switch was based on the assumption that this PR only applies to Webdav requests. however, it turns out that it also applies to other requests like OCS and even web
    - should we limit the fix to only Webdav ? (and not need the switch or have it default to no-cookies)
    - or should we keep it as is and have a swich
    - other ideas ?

- [ ] to gather more data, test with more third party tools / libraries if possible and see how they react when there's no cookies

Note: the test issues so far were not at all related to the missing session, it was only that some test code was written in the wrong way but did work because a session happened to be there (ex: missing cookie jar usage)

**Comment by nickvergessen** [comment]
Breaks integration tests on notifications app:

```
  Scenario: Successful registration                            # /home/nickv/Nextcloud/24/server/appsbabies/notifications/tests/Integration/features/push-registration.feature:34
[Mon Feb  7 18:54:20 2022] 127.0.0.1:34172 Accepted
[Mon Feb  7 18:54:20 2022] could not get login credentials because session is unavailable
[Mon Feb  7 18:54:20 2022] 127.0.0.1:34172 [403]: GET /ocs/v2.php/core/getapppassword?format=json
[Mon Feb  7 18:54:20 2022] 127.0.0.1:34172 Closing
    Given user "test1" creates an app password                 # FeatureContext::createAppPassword()
      │ array(0) {
      │ }
      │ 
      Notice: Undefined index: apppassword in …/apps/notifications/tests/Integration/features/bootstrap/FeatureContext.php line 325
    Given user "test1" registers for push notifications with   # FeatureContext::registerForPushNotifications()
      | pushTokenHash   | 12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678 |
      | devicePublicKey | VALID_KEY                                                                                                                        |
      | proxyServer     | https://push-notifications.nextcloud.com/                                                                                        |
    Then status code is 201     
```

Problem is: `GET /ocs/v2.php/core/getapppassword?format=json` does not work anymore.
It returns a 403 with the exception being logged:
https://github.com/nextcloud/server/blob/215aef3cbdc1963be1bb6bca5218ee0a4b7f1665/lib/private/Authentication/LoginCredentials/Store.php#L100-L101

**Comment by nickvergessen** [comment]
Potential hardcoded patch:
```diff
diff --git a/lib/base.php b/lib/base.php
index c3ecc01b36..6ef2fdd576 100644
--- a/lib/base.php
+++ b/lib/base.php
@@ -410,7 +410,13 @@ class OC {
                if (self::$server->getRequest()->getHeader('Authorization') !== '' && !isset($_COOKIE[OC_Util::getInstanceId()])) {
                        // Do not initialize the session if a request is authenticated directly
                        // unless there is a session cookie already sent along
-                       return;
+                       $request = \OC::$server->getRequest();
+                       if ($request->getRawPathInfo() !== '/core/getapppassword'
+                               && !$request->getRawPathInfo() !== '/core/apppassword/rotate'
+                               && !$request->getRawPathInfo() !== '/core/apppassword') {
+                               return;
+                       }
+
                }
                if (self::$server->getRequest()->getServerProtocol() === 'https') {
                        ini_set('session.cookie_secure', 'true');
```

But I expect a lot breakage in several other apps and areas due to unavailable sessions 🙈

**Comment by nickvergessen** [comment]
Talk is also completely red CI.
We write the talk session into the phpsession. that is needed so people can join the same room multiple times.

Maybe we first limit this to webdav endpoints? OCS stuff needs a lot more looking first

**Comment by juliushaertl** [comment]
Pushed a commit to only use the memory session on webdav and if no session cookie is already present

**Comment by juliushaertl** [comment]
@nickvergessen Could you maybe retrigger the talk/notifications tests to double check?

**Comment by martinlanger90** [comment]
> @nickvergessen Could you maybe retrigger the talk/notifications tests to double check?

So if I understand that correctly: a webdav request creates no php session file anymore?

**Comment by nickvergessen** [comment]
> So if I understand that correctly: a webdav request creates no php session file anymore?

Yes, that's the idea

**Comment by nickvergessen** [comment]
Repushed:
* Notifications: https://github.com/nextcloud/notifications/pull/1147
* Talk: https://github.com/nextcloud/spreed/pull/6878

**Comment by nickvergessen** [comment]
Both integration tests green again.

**Comment by juliushaertl** [comment]
Meanwhile received some feedback about degraded webdav performance using macOS, of some I would expect due to the additional password validation that happens on each request, but need to perform some profiling in that regard.

- [ ] Check if certain WebDAV clients may still use cookies with some additional logging (e.g macOS Finder, Cyberduck, Windows WebDAV mount)

**Comment by nickvergessen** [comment]
But didn't you implement that we use cookies/session when given?
Is the problem it now never gets any?

**Comment by nickvergessen** [comment]
Maybe we respond with the cookie on the root?

**Comment by juliushaertl** [comment]
From discussion in the call

- [ ] Still send back a cookie on the first request (without a session) -> return a session on a follow up request that has this cookie

**Comment by PVince81** [comment]
any chance to finish this or are there more concerns ?

**Comment by nickvergessen** [comment]
> any chance to finish this or are there more concerns ?

It breaks talk which uses sessions in OCS heavily to allow multiple participants in a call/chat of the same user. So yes heavy concerns

**Comment by martinlanger90** [comment]
So is that cancelled?

**Comment by PVince81** [comment]
I think we had a chat where we said we could limit this change to Webdav only and exclude the OCS related change.

**Comment by juliushaertl** [comment]
Rebased and squashed so that now only WebDAV requests will be affected by this change. Besides that in order to still support clients which make use of any sent over session cookie, we set a test cookie and still start up a session for those cases on any follow up request.

**Comment by juliushaertl** [comment]
Overall much less impact than the original proposal, but should be sufficient to handle exhausted session creation for clients which always do basic auth against WebDAV.

**Comment by martinlanger90** [comment]
Really? Another year full of session files?

**Comment by juliushaertl** [comment]
🏓 for reviews now for 26

**Review by skjnldsv — APPROVED** [review]

**Comment by tobiasKaminsky** [comment]
Is this something that affects clients? 
Shall we give it a smoke test?

**Comment by tobiasKaminsky** [comment]
Smoke test on Android works.
Only one app token is used.
Not sure, but feels a bit faster…

**Comment by juliushaertl** [comment]
Rebased. Still looking for another review 😉

File: lib/base.php [hunk 1]
```diff
@@ -73,7 +74,7 @@
 use OCP\EventDispatcher\IEventDispatcher;
 use OCP\Group\Events\UserRemovedEvent;
 use OCP\ILogger;
-use OCP\IURLGenerator;
+use OCP\IRequest;use OCP\IURLGenerator;
```
Comment (ChristophWurst) [inline lib/base.php:77]: creative formatting technique

File: lib/base.php [hunk 2]
```diff
@@ -1,4 +1,5 @@
 <?php
+<?php
```
Comment (ChristophWurst) [inline lib/base.php:2]: :monocle_face:

**Review by ChristophWurst — COMMENTED** [review]
Looks good otherwise

File: lib/base.php (hunk 2 above)
Comment (juliushaertl) [reply lib/base.php]: 🙄 Not sure what got wrong there, redid the rebase and should look better now 🙈

**Review by ChristophWurst — APPROVED** [review]

**Comment by juliushaertl** [comment]
Checker failure unrelated, fix is in https://github.com/nextcloud/server/pull/35855
