### PR TITLE
fix: force lowercase emails

### LINKED ISSUE #53367: [Bug]: Uppercase Letters in Email Addresses Cause Login and Email Delivery Issues
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Subject: Bug: Uppercase Letters in Email Addresses Cause Login and Email Delivery Issues

Description:
When creating a user in Nextcloud with an email address that contains uppercase letters, the address is displayed correctly (with uppercase letters) in the account overview.
However, internally, the email address is saved or processed in all lowercase (or with uppercase letters removed).
This leads to the following issues:

Users cannot log in with their email address as expected.

Emails are sent to the "modified" (lowercase or shortened) version of the address, so users do not receive emails.

### Steps to reproduce

1. Create a new user in Nextcloud with an email address containing uppercase letters (e.g., John.Doe@Example.com).
2. Check the account overview: the email address appears with uppercase letters.
3. Try to log in or send a test email:

Login via email does not work as expected.
Emails are not delivered because they are sent to the "shortened" email address.

### Expected behavior

Either:

Only allow lowercase letters when entering an email address (validate and reject uppercase letters),
or

Ensure that all routines (login, email delivery, etc.) properly handle email addresses with uppercase letters, as per standard (email addresses are case-insensitive in the local part by most providers, but should not be modified).

### Nextcloud Server version

31

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by skjnldsv**
## Summary

* Resolves: https://github.com/nextcloud/server/issues/53367

Not 100% sure this is the best in terms of code quality, but seems the most straightforward :shrug: 

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by provokateurin — APPROVED** [review]
Technically wrong, accepted in reality :woman_shrugging:

File: lib/private/User/User.php [hunk 1]
```diff
@@ -154,6 +154,7 @@ public function setEMailAddress($mailAddress) {
 	 */
 	public function setSystemEMailAddress(string $mailAddress): void {
 		$oldMailAddress = $this->getSystemEMailAddress();
+		$mailAddress = mb_strtolower(trim($mailAddress));
```
Comment (come-nc) [inline lib/private/User/User.php:157]: This is enough, you do not need to add calls to mb_strtolower prior to calling this method, no?
Feels like you added the conversion both outside and inside of the setter. Inside is enough IMO

Comment (skjnldsv) [reply lib/private/User/User.php:157]: Yes, it's because the email/value is sometimes also used at later stages of the parent methods.
So the setter is nice, but not enough

**Review by come-nc — APPROVED** [review]

**Comment by provokateurin** [comment]
The psalm baseline was not adjusted:

```
ERROR: UnusedBaselineEntry
at :0:0
Baseline for issue "DeprecatedMethod" has 1 extra entry. (see https://psalm.dev/316)
```

PR will follow in a few seconds.

**Comment by skjnldsv** [comment]
> The psalm baseline was not adjusted:
> 
> ```
> ERROR: UnusedBaselineEntry
> at :0:0
> Baseline for issue "DeprecatedMethod" has 1 extra entry. (see https://psalm.dev/316)
> ```
> 
> PR will follow in a few seconds.

Weird, it didn't complain on CI and I did run a baseline update (you can see it in the changed files)
What should I have done to catch this?

**Comment by provokateurin** [comment]
I'm not sure either, it's a bit weird. I think it might just be psalm doing weird things again.

**Comment by unvermuthet** [comment]
Does this fix #53367 if I have existing users with capitalized mail addresses?

**Comment by skjnldsv** [comment]
> Does this fix #53367 if I have existing users with capitalized mail addresses?

I think it should, we'll be happy to have some feedback if you can try the RC1 releases of yesterday :)
