### PR TITLE
Fix the patched Backbone instance and use that exclusively

### LINKED ISSUE #13939: Clicking on `< Shared` in the details of the file list does not open the share tab in the sidebar anymore
Instead the first tab (activity) is opened.

If you manually select the share tab and then switch to another file the tab is kept.

Also selecting the versions tab does not highlight it as active anymore.

cc @skjnldsv @juliushaertl

### PR DESCRIPTION
**Pull request by ChristophWurst**
Backbone and its patches were moved to the webpack bundle in #13870. Apparently apps like Talk replace the global `Backbone` instance and therefore the monkey patched functions `davCall` and `davSync` "methods" reference a wrong instance. This patch encapsulates the Backbone instance with the method so that it is immune to a replacement.

I don't know if it makes any difference with webpack, but I'm now using the `noConflict` API again.

Ref https://github.com/nextcloud/server/pull/13870#discussion_r251777767.
Fix #13939

cc @danxuliu

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]
Fixes #13939

File: core/src/OC/backbone.js [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+ * GNU Affero General Public License for more details.
+ *
+ * You should have received a copy of the GNU Affero General Public License
+ * along with this program.  If not, see <http://www.gnu.org/licenses/>.
+ */
+
+import VendorBackbone from 'backbone';
+import {davCall, davSync} from './backbone-webdav';
+
+const Backbone = VendorBackbone.noConflict();
```
Comment (danxuliu) [inline core/src/OC/backbone.js]: As far as I understand (and after having checked it with a quick test ;-) ) it seems that the lines 22-25 could be simplified to:
```
import Backbone from 'backbone'
import {davCall, davSync} from './backbone-webdav'
```

However, I do not know if there is any scenario in which `noConflicts` would be needed, so I am not sure about the simplification.

File: core/src/OC/backbone.js [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+
+// Patch Backbone for DAV
+Object.assign(Backbone, {
+	davCall,
+	davSync: davSync(Backbone),
+});
+
+export default Backbone;
```
Comment (danxuliu) [inline core/src/OC/backbone.js]: In _core/src/OC/index.js_ the trailing _;_ were removed, but in _core/src/OC/backbone.js_ they were kept. Is there any special reason for that (like being processed in a different way by Webpack or something like that)?

**Review by danxuliu — COMMENTED** [review]
Tested and works, but please check the comments :-)

File: core/src/OC/backbone.js (hunk 1 above)
Comment (ChristophWurst) [reply core/src/OC/backbone.js]: Yeah, me neither. `noConflict` was used in previous versions, so I added it again. It might work without but I'm not sure. I would leave it as it is now.

File: core/src/OC/backbone.js (hunk 2 above)
Comment (ChristophWurst) [reply core/src/OC/backbone.js]: Yeah, this is quite inconsistent. We have to define a coding style and use that everywhere. I think there's a ticket for that.

The ; is optional, hence I usually don't use it.

**Review by danxuliu — APPROVED** [review]
Tested and works :+1:
