### PR TITLE
Only enforce schema limits for supported apps

### LINKED ISSUE #10518: Long database names in apps break the update
Apps that have a to long identifier name break the update.

So far I found:
- gpxmotion
- groupfolders
- mail https://github.com/nextcloud/mail/issues/1002
- notes
- music

Ref https://github.com/nextcloud/server/pull/10221

Is there anything we could do about that to avoid having the update stopped with those long names? Like can we just enforce the check on oracle and maybe only log a warning on other database types where this is not an issue?

Disabling the app also doesn't work, since the check is executed anyway.

cc @nickvergessen

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #10518

### CODE REVIEW

File: lib/private/DB/MigrationService.php [hunk 1]
```diff
@@ -80,6 +84,21 @@ public function __construct($appName, IDBConnection $connection, IOutput $output
 			$namespace = App::buildAppNamespace($appName);
 			$this->migrationsPath = "$appPath/lib/Migration";
 			$this->migrationsNamespace = $namespace . '\\Migration';
+
+			$infoParser = new InfoParser();
+			$info = $infoParser->parse($appPath . '/appinfo/info.xml');
+			if (!isset($info['dependencies']['database'])) {
+				$this->checkOracle = true;
```
Comment (rullzer) [inline lib/private/DB/MigrationService.php]: so by default we check always check oracle?

Comment (nickvergessen) [reply lib/private/DB/MigrationService.php]: Yeah if the author did not define a db, you can install it on any. It a db is given the dependency check ensures it. So that mathes the logic here

**Comment by rullzer** [comment]
Lets do this properly for 15

**Comment by MorrisJobke** [comment]
@nickvergessen Could you please rebase to fix the conflict?

**Comment by nickvergessen** [comment]
Done

**Review by MorrisJobke — APPROVED** [review]
Tested and works with shipped apps 👍

**Comment by MorrisJobke** [comment]
Looks like some tests fail 🙈

**Comment by MorrisJobke** [comment]
> Looks like some tests fail 🙈

Resolved.

**Comment by MorrisJobke** [comment]
@nickvergessen @rullzer Should we do this now or wait for 16?

**Comment by nickvergessen** [comment]
I'm always in favor of it. but well I manually cross check that oracle still works via the notifications tests…

**Comment by MorrisJobke** [comment]
Let's move it to 16 and merge it early this time.

**Comment by nickvergessen** [comment]
Rebased to re-execuite the tests, please merge soonish

**Review by blizzz — APPROVED** [review]
