### PR TITLE
fix(storage): fallback to copy and unlink when rename fails

### LINKED ISSUE #14743: can not copy or move directory between different external file storage, but files work fine
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce

I can not copy or move directory between different external file storage, but normal files work fine. How can I get this working?

`The first argument to copy() function cannot be a directory at
`
```
{"reqId":"XJAjnlYH6@rVQbcVclaXfwAAAAg","level":3,"time":"2019-03-18T23:02:54+00:00","remoteAddr":"80.127.158.83","user":"jdejong","app":"PHP","method":"MOVE","url":"\/nextcloud\/remote.php\/dav\/files\/jdejong\/Communications\/communication-jdejong","message":"rename(): The first argument to copy() function cannot be a directory at \/var\/www\/html\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#272","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"15.0.4.0"}
{"reqId":"XJAjnlYH6@rVQbcVclaXfwAAAAg","level":3,"time":"2019-03-18T23:02:54+00:00","remoteAddr":"80.127.158.83","user":"jdejong","app":"PHP","method":"MOVE","url":"\/nextcloud\/remote.php\/dav\/files\/jdejong\/Communications\/communication-jdejong","message":"rename(\/\/mnt\/nfs\/communications\/communication-jdejong,\/\/mnt\/nfs\/programmes\/communication-jdejong): Invalid cross-device link at \/var\/www\/html\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#272","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"15.0.4.0"}
```

Moving a normal file works but still gives this message:

`{"reqId":"XJAmBLAHf2Bocyt--HDF@gAAAAA","level":3,"time":"2019-03-18T23:13:08+00:00","remoteAddr":"80.127.158.83","user":"jdejong","app":"PHP","method":"MOVE","url":"\/nextcloud\/remote.php\/dav\/files\/jdejong\/Communications\/communication-jdejong\/communicaton-jdejong.txt","message":"rename(\/\/mnt\/nfs\/communications\/communication-jdejong\/communicaton-jdejong.txt,\/\/mnt\/nfs\/programmes\/communicaton-jdejong.txt): Operation not permitted at \/var\/www\/html\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#272","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"15.0.4.0"}
`

The setup:
```
sudo -u apache php occ group:add communications
sudo -u apache php occ group:add generalinformation
sudo -u apache php occ group:add officemanagement
sudo -u apache php occ group:add programmes
sudo -u apache php occ files_external:create -c datadir=/mnt/nfs/communications "Communications" local null::null
sudo -u apache php occ files_external:create -c datadir=/mnt/nfs/generalinformation "General Information" local null::null
sudo -u apache php occ files_external:create -c datadir=/mnt/nfs/officemanagement "Office Management" local null::null
sudo -u apache php occ files_external:create -c datadir=/mnt/nfs/programmes "Programmes" local null::null
sudo -u apache php occ files_external:applicable --add-group communications 11
sudo -u apache php occ files_external:option 11 enable_sharing true
sudo -u apache php occ files_external:option 11 encrypt false
sudo -u apache php occ files_external:applicable --add-group generalinformation 14
sudo -u apache php occ files_external:option 14 enable_sharing true
sudo -u apache php occ files_external:option 14 encrypt false
sudo -u apache php occ files_external:applicable --add-group officemanagement 15
sudo -u apache php occ files_external:option 15 enable_sharing true
sudo -u apache php occ files_external:option 15 encrypt false
sudo -u apache php occ files_external:applicable --add-group programmes 16
sudo -u apache php occ files_external:option 16 enable_sharing true
sudo -u apache php occ files_external:option 16 encrypt false
```

```
# sudo -u apache php occ --version
Nextcloud 15.0.4
# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 
```

### LINKED ISSUE #38569: [Bug]: Error when deleting folder: `rename()`: The first argument to `copy()` function cannot be a directory
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When deleting a folder (whatever it is empty or not), it will report a error.
image

After reloading page, the folder is gone and I couldn't find it on trash bin or anywhere. The `Logging` has some errors:
image

### Steps to reproduce

1. select a existing folder or create a new folder
2. delete it
3. error happens

### Expected behavior

The folder should be in the trash bin after deleting.

### Installation method

Community Docker image

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

8.2.6

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "filesystem_check_changes": 1,
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "26.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "maintenance": false
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.18.0
  - cloud_federation_api: 1.9.0
  - comments: 1.16.0
  - dav: 1.25.0
  - federatedfilesharing: 1.16.0
  - files: 1.21.1
  - files_pdfviewer: 2.7.0
  - files_rightclick: 1.5.0
  - files_sharing: 1.18.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - notifications: 2.14.0
  - oauth2: 1.14.0
  - photos: 2.2.0
  - provisioning_api: 1.16.0
  - serverinfo: 1.16.0
  - settings: 1.8.0
  - text: 3.7.2
  - theming: 2.1.1
  - twofactor_backupcodes: 1.15.0
  - twofactor_totp: 8.0.0
  - viewer: 1.10.0
  - workflowengine: 2.8.0
Disabled:
  - admin_audit: 1.16.0
  - bruteforcesettings: 2.6.0
  - circles: 26.0.0 (installed 26.0.0)
  - contactsinteraction: 1.7.0 (installed 1.7.0)
  - dashboard: 7.6.0 (installed 7.6.0)
  - encryption: 2.14.0
  - federation: 1.16.0 (installed 1.16.0)
  - files_external: 1.18.0
  - firstrunwizard: 2.15.0 (installed 2.15.0)
  - nextcloud_announcements: 1.15.0 (installed 1.15.0)
  - password_policy: 1.16.0 (installed 1.16.0)
  - privacy: 1.10.0 (installed 1.10.0)
  - recommendations: 1.5.0 (installed 1.5.0)
  - related_resources: 1.1.0-alpha1 (installed 1.1.0-alpha1)
  - sharebymail: 1.16.0 (installed 1.16.0)
  - support: 1.9.0 (installed 1.9.0)
  - survey_client: 1.14.0 (installed 1.14.0)
  - suspicious_login: 4.4.0
  - systemtags: 1.16.0 (installed 1.16.0)
  - updatenotification: 1.16.0 (installed 1.16.0)
  - user_ldap: 1.16.0
  - user_status: 1.6.0 (installed 1.6.0)
  - weather_status: 1.6.0 (installed 1.6.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by kesselb**
* Resolves: https://github.com/nextcloud/server/issues/14743
* Resolves: https://github.com/nextcloud/server/issues/38569

## Summary

Alternative approach to https://github.com/nextcloud/server/pull/19289 

If you use docker's OverlayFS and mount two folders into your container from the same disk it's also not possible to rename, but `$stat['dev']` is equal.[^1]

Many thanks again to @kubatek94 for the initial pull request.

## TODO

- [x] CI

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

[^1]: https://docs.docker.com/storage/storagedriver/overlayfs-driver/#modifying-files-or-directories

### CODE REVIEW

**Comment by solracsf** [comment]
Is this somehow related to https://github.com/nextcloud/server/issues/38569 ?

File: lib/private/Files/Storage/Local.php [hunk 1]
```diff
@@ -361,21 +361,14 @@ public function rename($source, $target) {
...
-
 			$this->checkTreeForForbiddenItems($this->getSourcePath($source));
 		}
 
-		return rename($this->getSourcePath($source), $this->getSourcePath($target));
+		if (@rename($this->getSourcePath($source), $this->getSourcePath($target))) {
+			return true;
+		}
+
+		return $this->copy($source, $target) && $this->rmdir($source);
```
Comment (kesselb) [inline lib/private/Files/Storage/Local.php:371]: @icewind1991 should we add the copy + unlink fallback only for directories or also for files?

**Review by come-nc — APPROVED** [review]

File: lib/private/Files/Storage/Local.php [hunk 2]
```diff
@@ -335,7 +335,7 @@ private function checkTreeForForbiddenItems(string $path) {
 		}
 	}
 
-	public function rename($source, $target) {
+	public function rename($source, $target): bool {
```
Comment (Fenn-CS) [inline lib/private/Files/Storage/Local.php:338]: Nice opportunity to type the function params

**Review by nfebe — APPROVED** [review]

**Comment by kesselb** [comment]
Follow-up to change rmdir to unlink: https://github.com/nextcloud/server/pull/38623

**Comment by szaimen** [comment]
🎉🎉🎉
