### PR TITLE
fix(CardDAV): only run upgrade sync if 1000 users or less

### LINKED ISSUE #39744: [Bug]: <dav> upgrade step takes hours when server connected to large LDAP directory, or has hundreds of users
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When upgrading from 26.0.4 to 27.0.1 there is a step in the upgrade flow that says:

"Updating \<dav\> ..."

which seems to query the ldap directory and for every entry in LDAP update the "System Address Book" in the 'addressbooks' table as well as create an account in the 'accounts' table with a corresponding entry in the 'ldap_user_mapping' table.

If a server is connected to an LDAP directory with thousands, tens of thousands or hundreds of thousands of users, this can take hours to recurse through and it does not seem that this is a step that should block the completion of the upgrade. Can this step please be moved to a separate recommendation, like the addition of indexes for performance, that would appear in the admin interface alongside other security & performance recommendations. This would enable the server to get out of maintenance mode quicker, rather than have the server offline for hours (or days) while tens of thousands of LDAP accounts are probed and accounts created and/or carddav 'cards' in the "system" addressbook updated (often without them needing to be as they should only be created when the user attempts to login to nextcloud with their LDAP credentials).

### Steps to reproduce

1. Enable LDAP integration
2. Attempt to upgrade from Nextcloud 26.0.4 to 27.0.1
3. Tail updater.log which gives the impression the upgrade is complete but the cli is still hanging at "Updating \<dav\> ..."
4. Tail nextcloud.log -f to see the large number of ldap queries continuously race by for hours

### Expected behavior

Upgrade should complete without the need to recurse the whole connected LDAP directory.

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### LINKED ISSUE #39769: [Bug]: Updating <dav> ... very slow with a lot of users
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The <dav> Update step takes forever

the step is massively frustrating, as the logs do not display which entries are modified:

```{"reqId":"CvpSmDdyZsVDkPMhVqWb","level":0,"time":"2023-08-09T07:30:08+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Automatic conversion of false to array is deprecated at /export/htdocs/nextcloud/lib/private/Files/Stream/SeekableHttpStream.php#222","userAgent":"--","version":"26.0.4.3","data":{"app":"PHP"}}
```

### Steps to reproduce

1. install NC Enterprise 26.0.4
2. update to NC Enterprise 27.0.1

### Expected behavior

Fast Update or background process

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Configuration report

```shell
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
{
    "system": {
        "objectstore_multibucket": {
            "class": "OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "num_buckets": 1,
                "bucket": "nc-test-",
                "autocreate": true,
                "key": "***REMOVED SENSITIVE VALUE***",
                "secret": "***REMOVED SENSITIVE VALUE***",
                "hostname": "obs.eu-de.otc.t-systems.com",
                "use_ssl": true,
                "region": "eu-de"
            }
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***",
            "***",
            "***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "data\/skeleton\/",
        "dbtype": "mysql",
        "version": "26.0.4.3",
        "overwrite.cli.url": "https:\/\/wolke.schullogin.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "debug": false,
        "default_locale": "de_DE",
        "default_language": "de",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 1.5
        },
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "theme": "",
        "loglevel": 0,
        "maintenance": true,
        "updater.server.url": "https:\/\/updates.nextcloud.com\/customers\.../",
        "app_install_overwrite": [
            "circles",
            "documentserver_community"
        ],
        "updater.release.channel": "enterprise",
        "default_phone_region": "DE",
        "sentry.dsn": "***REMOVED SENSITIVE VALUE***",
        "defaultapp": "files"
    }
}
```

### List of activated Apps

```shell
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Enabled:
  - activity: 2.19.0
  - admin_audit: 1.16.0
  - announcementcenter: 6.6.1
  - bruteforcesettings: 2.6.0
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.16.0
  - contacts: 5.3.2
  - contactsinteraction: 1.7.0
  - dashboard: 7.6.0
  - dav: 1.25.0
  - federatedfilesharing: 1.16.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_antivirus: 5.2.1
  - files_pdfviewer: 2.7.0
  - files_sharing: 1.18.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - firstrunwizard: 2.15.0
  - logreader: 2.11.0
  - lookup_server_connector: 1.15.0
  - nextcloud_announcements: 1.15.0
  - notes: 4.8.1
  - notifications: 2.14.0
  - oauth2: 1.15.1
  - photos: 2.3.0
  - previewgenerator: 5.3.0
  - privacy: 1.10.0
  - provisioning_api: 1.16.0
  - quota_warning: 1.17.0
  - recommendations: 1.5.0
  - related_resources: 1.1.0
  - serverinfo: 1.16.0
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - support: 1.9.0
  - survey_client: 1.14.0
  - systemtags: 1.16.0
  - text: 3.7.2
  - theming: 2.1.1
  - twofactor_backupcodes: 1.15.0
  - updatenotification: 1.16.0
  - user_saml: 5.2.1
  - user_status: 1.6.0
  - viewer: 1.10.0
  - weather_status: 1.6.0
  - workflowengine: 2.8.0
Disabled:
  - approval: 1.1.0 (installed 1.1.0)
  - bbb: 2.5.0 (installed 2.5.0)
  - encryption: 2.15.0
  - external: 5.1.0 (installed 5.1.0)
  - files_accesscontrol: 1.16.0 (installed 1.16.0)
  - files_confidential: 1.0.3
  - files_downloadactivity: 1.16.0 (installed 1.16.0)
  - files_external: 1.19.0
  - files_lock: 27.0.0 (installed 27.0.0)
  - files_rightclick: 1.6.0 (installed 1.3.0)
  - globalsiteselector: 2.4.3
  - impersonate: 1.13.1 (installed 1.13.1)
  - onlyoffice: 7.8.0 (installed 7.8.0)
  - password_policy: 1.17.0 (installed 1.15.0)
  - suspicious_login: 5.0.0
  - twofactor_totp: 9.0.0
  - user_ldap: 1.17.0
```

### Nextcloud Signing status

```shell
not possible due to maintenance mode
```

### Nextcloud Logs

```shell
{"reqId":"CvpSmDdyZsVDkPMhVqWb","level":0,"time":"2023-08-09T07:34:12+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Automatic conversion of false to array is deprecated at /export/htdocs/nextcloud/lib/private/Files/Stream/SeekableHttpStream.php#222","userAgent":"--","version":"26.0.4.3","data":{"app":"PHP"}}
{"reqId":"CvpSmDdyZsVDkPMhVqWb","level":0,"time":"2023-08-09T07:34:12+00:00","remoteAddr":"","user":"--","app":"dav","method":"","url":"--","message":"Activity generated for a changed card in addressbook 3","userAgent":"--","version":"26.0.4.3","data":{"app":"dav"}}
{"reqId":"CvpSmDdyZsVDkPMhVqWb","level":0,"time":"2023-08-09T07:34:12+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Automatic conversion of false to array is deprecated at /export/htdocs/nextcloud/lib/private/Files/Stream/SeekableHttpStream.php#222","userAgent":"--","version":"26.0.4.3","data":{"app":"PHP"}}
{"reqId":"CvpSmDdyZsVDkPMhVqWb","level":0,"time":"2023-08-09T07:34:12+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Automatic conversion of false to array is deprecated at /export/htdocs/nextcloud/lib/private/Files/Stream/SeekableHttpStream.php#222","userAgent":"--","version":"26.0.4.3","data":{"app":"PHP"}}
{"reqId":"CvpSmDdyZsVDkPMhVqWb","level":0,"time":"2023-08-09T07:34:12+00:00","remoteAddr":"","user":"--","app":"dav","method":"","url":"--","message":"Activity generated for a changed card in addressbook 3","userAgent":"--","version":"26.0.4.3","data":{"app":"dav"}}
{"reqId":"CvpSmDdyZsVDkPMhVqWb","level":0,"time":"2023-08-09T07:34:12+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Automatic conversion of false to array is deprecated at /export/htdocs/nextcloud/lib/private/Files/Stream/SeekableHttpStream.php#222","userAgent":"--","version":"26.0.4.3","data":{"app":"PHP"}}
{"reqId":"CvpSmDdyZsVDkPMhVqWb","level":0,"time":"2023-08-09T07:34:12+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Automatic conversion of false to array is deprecated at /export/htdocs/nextcloud/lib/private/Files/Stream/SeekableHttpStream.php#222","userAgent":"--","version":"26.0.4.3","data":{"app":"PHP"}}
{"reqId":"CvpSmDdyZsVDkPMhVqWb","level":0,"time":"2023-08-09T07:34:12+00:00","remoteAddr":"","user":"--","app":"dav","method":"","url":"--","message":"Activity generated for a changed card in addressbook 3","userAgent":"--","version":"26.0.4.3","data":{"app":"dav"}}
{"reqId":"CvpSmDdyZsVDkPMhVqWb","level":0,"time":"2023-08-09T07:34:13+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Automatic conversion of false to array is deprecated at /export/htdocs/nextcloud/lib/private/Files/Stream/SeekableHttpStream.php#222","userAgent":"--","version":"26.0.4.3","data":{"app":"PHP"}}
{"reqId":"CvpSmDdyZsVDkPMhVqWb","level":0,"time":"2023-08-09T07:34:13+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Automatic conversion of false to array is deprecated at /export/htdocs/nextcloud/lib/private/Files/Stream/SeekableHttpStream.php#222","userAgent":"--","version":"26.0.4.3","data":{"app":"PHP"}}
{"reqId":"CvpSmDdyZsVDkPMhVqWb","level":0,"time":"2023-08-09T07:34:13+00:00","remoteAddr":"","user":"--","app":"dav","method":"","url":"--","message":"Activity generated for a changed card in addressbook 3","userAgent":"--","version":"26.0.4.3","data":{"app":"dav"}}
{"reqId":"CvpSmDdyZsVDkPMhVqWb","level":0,"time":"2023-08-09T07:34:14+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Automatic conversion of false to array is deprecated at /export/htdocs/nextcloud/lib/private/Files/Stream/SeekableHttpStream.php#222","userAgent":"--","version":"26.0.4.3","data":{"app":"PHP"}}
{"reqId":"CvpSmDdyZsVDkPMhVqWb","level":0,"time":"2023-08-09T07:34:14+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Automatic conversion of false to array is deprecated at /export/htdocs/nextcloud/lib/private/Files/Stream/SeekableHttpStream.php#222","userAgent":"--","version":"26.0.4.3","data":{"app":"PHP"}}
```
```


### Additional info

Maybe related to 

* https://github.com/nextcloud/server/issues/39744

### PR DESCRIPTION
**Pull request by miaulalala**
* Resolves: https://github.com/nextcloud/server/issues/39744 
* Resolves: https://github.com/nextcloud/server/issues/39769

## Summary
Limit the upgrade sync to instances with 1000 users or less and show a warning in the admin section if the sync hasn't been run:

image

## TODO

- [ ] Adjust tests

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/settings/lib/SetupChecks/HasDavSyncRun.php [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+
+	public function severity(): string {
+		return 'warning';
+	}
+
+	public function run(): bool {
+		if($this->config->getAppValue('dav', 'upgrade_dav_sync_run') !== 'no') {
+			return true;
+		}
+		return false;
```
Comment (tcitworld) [inline apps/settings/lib/SetupChecks/HasDavSyncRun.php:47]: **suggestion:** 
```suggestion
		return $this->config->getAppValue('dav', 'upgrade_dav_sync_run') !== 'no';
```
And you can add a `'no'` fallback and check for `== 'yes' instead.

Comment (miaulalala) [reply apps/settings/lib/SetupChecks/HasDavSyncRun.php:47]: smort

File: apps/dav/lib/Migration/Version1027Date20230504122946.php [hunk 2]
```diff
@@ -37,22 +39,28 @@
...
+								private IUserManager $userManager,
+								private IConfig $config) {}
 	/**
 	 * @param IOutput $output
 	 * @param Closure(): ISchemaWrapper $schemaClosure
 	 * @param array $options
 	 */
 	public function postSchemaChange(IOutput $output, Closure $schemaClosure, array $options): void {
+		if($this->userManager->countUsers() > 1000) {
+			$this->logger->info('Could not sync system address books during update as too many user records found. Please call occ dav:sync-system-addressbook manually.');
```
Comment (ChristophWurst) [inline apps/dav/lib/Migration/Version1027Date20230504122946.php:53]:
```suggestion
			$this->logger->info('Could not sync system address books during update as too many user records have been found. Please call occ dav:sync-system-addressbook manually.');
```

grammar

File: apps/dav/lib/Migration/Version1027Date20230504122946.php [hunk 3]
```diff
@@ -37,22 +39,28 @@
...
+			$this->config->setAppValue('dav', 'upgrade_dav_sync_run', 'no');
+			$output->info('System address book sync failed. See logs for details');
```
Comment (ChristophWurst) [inline apps/dav/lib/Migration/Version1027Date20230504122946.php:55]: the default log level won't log info so let's also print the occ hint here

File: apps/settings/composer/composer/ClassLoader.php [hunk 4]
```diff
@@ -45,63 +45,66 @@ class ClassLoader
     /** @var \Closure(string):void */
     private static $includeFile;
 
-    /** @var string|null */
```
Comment (ChristophWurst) [inline apps/settings/composer/composer/ClassLoader.php:48]: nit: undo the composer changes, only commit the updated class map

https://nuclearsquid.com/writings/git-add/

**Review by ChristophWurst — COMMENTED** [review]
nit: append 27 to upgrade_dav_sync_run to allow future dav upgrade syncs to have a unique key too

**Comment by kesselb** [comment]
> nit: append 27 to upgrade_dav_sync_run to allow future dav upgrade syncs to have a unique key too

I don't understand :confused: Let's say we need another sync from 28 to 29. If we use the app config key without a prefix/suffix, we can reuse the same logic without changing the command or setup check.

**Comment by ChristophWurst** [comment]
Fair point if we reset upgrade_dav_sync_run. Sorry for the misdirection.

File: apps/dav/lib/Command/SyncSystemAddressBook.php [hunk 5]
```diff
@@ -62,6 +58,7 @@ protected function execute(InputInterface $input, OutputInterface $output): int
 
 		$progress->finish();
 		$output->writeln('');
+		$this->config->setAppValue('dav', 'upgrade_dav_sync_run', 'yes');
```
Comment (kesselb) [inline apps/dav/lib/Command/SyncSystemAddressBook.php:61]:
```suggestion
		$this->config->deleteAppValue('dav', 'needs_system_address_book_sync');
```

File: apps/dav/lib/Migration/Version1027Date20230504122946.php [hunk 6]
```diff
@@ -37,22 +39,27 @@
...
+								private IUserManager $userManager,
+								private IConfig $config) {}
 	/**
 	 * @param IOutput $output
 	 * @param Closure(): ISchemaWrapper $schemaClosure
 	 * @param array $options
 	 */
 	public function postSchemaChange(IOutput $output, Closure $schemaClosure, array $options): void {
+		if($this->userManager->countUsers() > 1000) {
+			$this->config->setAppValue('dav', 'upgrade_dav_sync_run', 'no');
```
Comment (kesselb) [inline apps/dav/lib/Migration/Version1027Date20230504122946.php:53]:
```suggestion
			$this->config->setAppValue('dav', 'needs_system_address_book_sync', 'yes');
```

File: apps/dav/lib/Migration/Version1027Date20230504122946.php [hunk 7]
```diff
@@ -37,22 +39,27 @@
...
+			$output->info('Could not sync system address books during update - too many user records have been found. Please call occ dav:sync-system-addressbook manually.');
+			return;
+		}
+
 		try {
 			$this->syncService->syncInstance();
+			$this->config->setAppValue('dav', 'upgrade_dav_sync_run', 'yes');
```
Comment (kesselb) [inline apps/dav/lib/Migration/Version1027Date20230504122946.php:60]:
```suggestion
```

File: apps/dav/lib/Migration/Version1027Date20230504122946.php [hunk 8]
```diff
@@ -37,22 +39,27 @@
...
 		} catch (Throwable $e) {
+			$this->config->setAppValue('dav', 'upgrade_dav_sync_run', 'no');
```
Comment (kesselb) [inline apps/dav/lib/Migration/Version1027Date20230504122946.php:62]:
```suggestion
			$this->config->setAppValue('dav', 'needs_system_address_book_sync', 'yes');
```

File: apps/settings/lib/SetupChecks/NeedsSystemAddressBookSync.php [hunk 9]
```diff
@@ -0,0 +1,46 @@
...
+	public function description(): string {
+		return $this->l10n->t('The DAV system address book sync has not run yet as your instance has more than 1000 users or because an error occured. Please run it manually by calling occ dav:sync-system-addressbook.');
+	}
+
+	public function severity(): string {
+		return 'warning';
+	}
+
+	public function run(): bool {
+		return $this->config->getAppValue('dav', 'upgrade_dav_sync_run', 'no') === 'yes';
```
Comment (kesselb) [inline apps/settings/lib/SetupChecks/NeedsSystemAddressBookSync.php:44]:
```suggestion
		return $this->config->getAppValue('dav', 'needs_system_address_book_sync', 'no') === 'no';
```

**Comment by kesselb** [comment]
How to test:

- Patch countUsers in lib/private/User/Manager.php to return 1001
- `php occ migrations:execute dav 1027Date2023050412294`
-  Should show the warning: "Could not sync system address books during update - too many user records have been found. Please call occ dav:sync-system-addressbook manually."
- Login as admin and head to overview.
- Should see a warning: "The DAV system address book sync has not run yet as your instance has more than 1000 users or because an error occured. Please run it manually by calling occ dav:sync-system-addressbook."
- `php occ dav:sync-system-addressbook`
- Warning in overview should be gone.

**Review by kesselb — APPROVED** [review]
:+1: 

Tested the process by manually executing the migration.

Your call if you want to align the app config key or not ;)

File: apps/dav/lib/Command/SyncSystemAddressBook.php (hunk 5 above)
Comment (miaulalala) [reply apps/dav/lib/Command/SyncSystemAddressBook.php:61]: I was considering deleting the app value too but then I figured it will make stuff harder to debug if the value isn't there in case we run into issues

**Review by st3iny — APPROVED** [review]

File: apps/settings/lib/SetupChecks/NeedsSystemAddressBookSync.php [hunk 10]
```diff
@@ -0,0 +1,46 @@
...
+	public function description(): string {
+		return $this->l10n->t('The DAV system address book sync has not run yet as your instance has more than 1000 users or because an error occured. Please run it manually by calling occ dav:sync-system-addressbook.');
+	}
+
+	public function severity(): string {
+		return 'warning';
+	}
+
+	public function run(): bool {
+		return $this->config->getAppValue('dav', 'needs_system_address_book_sync', 'no') === 'yes';
```
Comment (kesselb) [inline apps/settings/lib/SetupChecks/NeedsSystemAddressBookSync.php:44]:
```suggestion
		return $this->config->getAppValue('dav', 'needs_system_address_book_sync', 'no') === 'no';
```

run should return true when everything is all right, and false if the setup check fails.

Comment (miaulalala) [reply apps/settings/lib/SetupChecks/NeedsSystemAddressBookSync.php:44]: Nonono that's the weird thing with those run commands, no? if everything is ok, return false, otherwise, return true?

Comment (kesselb) [reply apps/settings/lib/SetupChecks/NeedsSystemAddressBookSync.php:44]: No ;)

Comment (miaulalala) [reply apps/settings/lib/SetupChecks/NeedsSystemAddressBookSync.php:44]: But this gives me the message. I have set the appconfig value to "no". If I apply your changes, the message disappears, which is not correct.

Comment (miaulalala) [reply apps/settings/lib/SetupChecks/NeedsSystemAddressBookSync.php:44]: Dis PR is on faiaaaa :fire:

File: apps/dav/lib/Migration/Version1027Date20230504122946.php [hunk 11]
```diff
@@ -37,22 +39,27 @@
...
+								private IUserManager $userManager,
+								private IConfig $config) {}
 	/**
 	 * @param IOutput $output
 	 * @param Closure(): ISchemaWrapper $schemaClosure
 	 * @param array $options
 	 */
 	public function postSchemaChange(IOutput $output, Closure $schemaClosure, array $options): void {
+		if($this->userManager->countUsers() > 1000) {
+			$this->config->setAppValue('dav', 'needs_system_address_book_sync', 'no');
```
Comment (kesselb) [inline apps/dav/lib/Migration/Version1027Date20230504122946.php]:
```suggestion
			$this->config->setAppValue('dav', 'needs_system_address_book_sync', 'yes');
```

File: apps/dav/lib/Migration/Version1027Date20230504122946.php [hunk 12]
```diff
@@ -37,22 +39,27 @@
...
+			$output->info('Could not sync system address books during update - too many user records have been found. Please call occ dav:sync-system-addressbook manually.');
+			return;
+		}
+
 		try {
 			$this->syncService->syncInstance();
+			$this->config->setAppValue('dav', 'needs_system_address_book_sync', 'yes');
```
Comment (kesselb) [inline apps/dav/lib/Migration/Version1027Date20230504122946.php]:
```suggestion
			$this->config->setAppValue('dav', 'needs_system_address_book_sync', 'no');
```

File: apps/settings/tests/Controller/CheckSetupControllerTest.php [hunk 13]
```diff
@@ -662,6 +662,7 @@ public function testCheck() {
 				'isFairUseOfFreePushService' => false,
 				'temporaryDirectoryWritable' => false,
 				\OCA\Settings\SetupChecks\LdapInvalidUuids::class => ['pass' => true, 'description' => 'Invalid UUIDs of LDAP users or groups have been found. Please review your "Override UUID detection" settings in the Expert part of the LDAP configuration and use "occ ldap:update-uuid" to update them.', 'severity' => 'warning'],
+				\OCA\Settings\SetupChecks\NeedsSystemAddressBookSync::class => ['pass' => false, 'description' => 'The DAV system address book sync has not run yet as your instance has more than 1000 users or because an error occured. Please run it manually by calling occ dav:sync-system-addressbook.', 'severity' => 'warning'],
```
Comment (kesselb) [inline apps/settings/tests/Controller/CheckSetupControllerTest.php]:
```suggestion
				\OCA\Settings\SetupChecks\NeedsSystemAddressBookSync::class => ['pass' => true, 'description' => 'The DAV system address book sync has not run yet as your instance has more than 1000 users or because an error occured. Please run it manually by calling occ dav:sync-system-addressbook.', 'severity' => 'warning'],
```
