### PR TITLE
Fix #20913: Check image resource before attempting to preserve alpha

### LINKED ISSUE #20913: imagesavealpha() expects parameter 1 to be resource, boolean given
### Steps to reproduce
Most  probably relates to thumbnail generation:
```
sudo -u www-data php occ preview:generate-all
```

The exact message is:
```
imagesavealpha() expects parameter 1 to be resource, boolean given at ***/lib/private/legacy/image.php#571
imagesavealpha() expects parameter 1 to be resource, boolean given at ***/lib/private/legacy/image.php#572
```

**Operating system:**
Ubuntu 18.04.4 LTS

**Web server:**
apache2 - 2.4.29-1ubuntu4.13

**Database:**
mysql-5.7

**PHP version:**
php7.2-fpm

imagemagick 8:6.9.7.4+dfsg-16ubuntu6.8

**Nextcloud version:** (see Nextcloud admin page)
18.0.4 (currently the latest)

**Updated from an older Nextcloud/ownCloud or fresh install:**
started years ago and upgrading since then

**Where did you install Nextcloud from:**
official site

**Signing status:**
```
No errors have been found.
```

**List of activated apps:**
```
Enabled:
  - activity: 2.11.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.1.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - files: 1.13.1
  - files_fulltextsearch: 1.4.2
  - files_fulltextsearch_tesseract: 1.4.1
  - files_markdown: 2.2.0
  - files_mindmap: 0.0.21
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - fulltextsearch: 1.4.1
  - fulltextsearch_elasticsearch: 1.5.1
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notes: 3.3.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - ocr: 6.0.37
  - password_policy: 1.8.0
  - passwords: 2020.5.0
  - photos: 1.0.0
  - previewgenerator: 2.3.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - ransomware_protection: 1.6.1
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.8
  - tasks: 0.12.2
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
```

**Nextcloud configuration:**
What exact part is needed?

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** yes/no
No.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No.

### Client configuration
**Browser:**
N/A

**Operating system:**
N/A

#### Web server error log
Nothing related.

#### Browser log
N/A

### PR DESCRIPTION
**Pull request by simonspa**
This fixes #20913 by first checking if an image resource has been properly created before attempting to set alpha/transparency. This is implemented for both GIF and PNG images.

### CODE REVIEW

File: lib/private/legacy/OC_Image.php [hunk 1]
```diff
@@ -562,9 +562,13 @@ public function loadFromFile($imagePath = false) {
...
 					$this->resource = imagecreatefromgif($imagePath);
-					// Preserve transparency
-					imagealphablending($this->resource, true);
-					imagesavealpha($this->resource, true);
+					if ($this->resource) {
+						// Preserve transparency
+						imagealphablending($this->resource, true);
+						imagesavealpha($this->resource, true);
+					} else {
+						$this->logger->debug('OC_Image->loadFromFile, GIF image not valid: ' . $imagePath, ['app' => 'core']);
```
Comment (szaimen) [inline lib/private/legacy/OC_Image.php:570]: Maybe an info log makes more sense here and below?

**Review by szaimen — APPROVED** [review]
Apart from a small detail, LGTM

File: lib/private/legacy/OC_Image.php (hunk 1 above)
Comment (kesselb) [reply lib/private/legacy/OC_Image.php:570]: I would say we don't log anything ;) What can an administrator (the one able to view the log) do when a user uploads a broken gif?

Comment (szaimen) [reply lib/private/legacy/OC_Image.php:570]: The admin could notify the affected user that a specific gif/png is broken...

Comment (simonspa) [reply lib/private/legacy/OC_Image.php:570]: So I gather a `debug` log is exactly the middle between "nothing" and `info`? :)

I guess having a debug message makes debugging things easier, e.g. when a user asks why no previews are available for some of his images, but it's not an `info` message because, as @kesselb says, it's not something that calls for action.

Comment (acsfer) [reply lib/private/legacy/OC_Image.php:570]: I agree with both; these log are useless (and sometimes less-techy admins think it's a "bad" error...), and a `debug` can be a compromise.

**Review by juliusknorr — APPROVED** [review]

**Comment by simonspa** [comment]
Thanks for merging @juliushaertl !

This could probably be backported also to 21 and 22?

**Comment by juliushaertl** [comment]
Yes, backport makes sense :+1:
