### PR TITLE
fix: Fix empty sections appearing in search results

### LINKED ISSUE #48591: [Bug]: Universal search shows "Mobile & desktop" even if the settings section is empty
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The personal settings section "Mobile & desktop" (ID: `sync-clients`) is provided by the server, but only populated by apps like first run wizard or Talk. If there is not content, then this section will also not be shown. Now, when searching for "sync" in the universal search, this settings entry is shown in the results. Clicking on it brings the user to an empty page. Cf. screen recording.
https://github.com/user-attachments/assets/0864ef2a-e3e4-4f47-880c-7cc1dc888702

### Steps to reproduce

1. Make sure to have first run wizard and talk disabled
2. open universal search and look for "sync"
3. Clock on the "Mobile & desktop" result

### Expected behavior

The settings section is not presented in the search results when it does not have content.

### Nextcloud Server version

30

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by Pytal**
## Summary

Fix https://github.com/nextcloud/server/issues/48591

Fixes empty sections being shown in search results that lead to blank pages

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/settings/lib/Search/SectionSearch.php [hunk 1]
```diff
@@ -74,17 +74,33 @@ public function getOrder(string $route, array $routeParameters): int {
 	public function search(IUser $user, ISearchQuery $query): SearchResult {
 		$isAdmin = $this->groupManager->isAdmin($user->getUID());
 
+		$personalSections = $this->settingsManager->getPersonalSections();
+		foreach ($personalSections as $priority => &$sections) {
+			$sections = array_values(array_filter(
```
Comment (provokateurin) [inline apps/settings/lib/Search/SectionSearch.php:79]:
```suggestion
		foreach ($personalSections as $priority => $sections) {
			$personalSections[$priority] = array_values(array_filter(
```
Please avoid using refs in loops, nasty stuff can happen if you are not careful.

File: apps/settings/lib/Search/SectionSearch.php [hunk 2]
```diff
@@ -74,17 +74,33 @@ public function getOrder(string $route, array $routeParameters): int {
...
+				$sections,
+				fn (IIconSection $section) => !empty($this->settingsManager->getPersonalSettings($section->getID())),
+			));
+		}
+
+		$adminSections = $this->settingsManager->getAdminSections();
+		foreach ($adminSections as $priority => &$sections) {
+			$sections = array_values(array_filter(
```
Comment (provokateurin) [inline apps/settings/lib/Search/SectionSearch.php:87]: Same here

**Review by provokateurin — APPROVED** [review]

**Review by blizzz — APPROVED** [review]
