### PR TITLE
Formats file sizes using the user's locale

### LINKED ISSUE #7837: Values of filesize are displayed with "." (Dot) instead of "," (comma)
### Steps to reproduce
1. Open Nextcloud Webinterface
2. Watch the filesize values 

### Expected behaviour
In my case the values are expected to have the "," like 100,8 MB

### Actual behavior
Values of filesize are displayed with "." (Dot), witch is wrong for my locale (German)

auswahl_20180113_07 34 57
See also my old issue @OC repository: https://github.com/owncloud/core/issues/20674#issuecomment-357396942

### Server configuration

**Operating system**: Linux HP-T610 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux

**Web server:** Apache2

**Database:** mysql  Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:** PHP 7.0.27-0+deb9u1 (cli) (built: Jan  5 2018 13:51:52) ( NTS )

**Nextcloud version:** 12.0.4

**Updated from Nextcloud**

```
Alle Überprüfungen bestanden.
```

**List of activated apps:**
<details>
<summary>App list</summary>

```
[/var/www/nextcloud] # sudo -u www-data php occ app:list
Enabled:
  - activity: 2.5.2
  - audioplayer: 2.2.2
  - bruteforcesettings: 1.0.3
  - calendar: 1.5.7
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_downloadactivity
  - files_external
  - user_external
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
[/var/www/nextcloud] # sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "ocgv3ctfvkf0",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "darkwing.ddns.net",
            "HP-T610"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/darkwing.ddns.net\/nextcloud",
        "dbtype": "mysql",
        "version": "12.0.4.3",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "logtimezone": "UTC",
        "installed": true,
        "updater.release.channel": "stable",
        "mail_smtpmode": "smtp",
        "mail_from_address": "Darkwing",
        "mail_domain": "Quantentunnel.de",
        "mail_smtpauth": 1,
        "mail_smtphost": "mail.gmx.net",
        "mail_smtpsecure": "tls",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}

```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 57.0.4

**Operating system:** Linux Mint 18.3 Cinnamon

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here

Fatal | webdav | Sabre\DAV\Exception\Conflict: Parent node does not exist | 2018-01-05T14:51:04+0100
-- | -- | -- | --
Info | updater | \OC\Updater::resetLogLevel: Reset log level to Warning(2) | 2017-12-04T12:54:44+0100
Info | updater | \OC\Updater::maintenanceDisabled: Turned off maintenance mode | 2017-12-04T12:54:44+0100
Info | updater | \OC\Updater::updateEnd: Update successful | 2017-12-04T12:54:44+0100
Info | updater | \OC\Updater::finishedCheckCodeIntegrity: Finished code integrity check | 2017-12-04T12:54:44+0100
Info | updater | \OC\Updater::startCheckCodeIntegrity: Starting code integrity check... | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::step: Repair step: Rename folder with user specific keys | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::step: Repair step: Repair invalid paths in file cache | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::step: Repair step: Install new core bundle components | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::step: Repair step: Repair language codes | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::info: Repair info: No mounts updated | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::step: Repair step: Fix potential broken mount points | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::step: Repair step: Add preview cleanup background jobs | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::info: Repair info: Repair step already executed | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::step: Repair step: Add move avatar background job | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::info: Repair info: .step file moved to .step-previous-update | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::info: Repair info: .step-previous-update removed | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::info: Repair info: .step file exists | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::step: Repair step: Move .step file of updater to backup location | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::step: Repair step: Remove shares of a users root folder | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::step: Repair step: Repair invalid shares | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::info: Repair info: 0 tags with no entries have been removed. | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::info: Repair info: 0 tag entries for deleted tags have been removed. | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::info: Repair info: 0 tags for delete files have been removed. | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::info: Repair info: 0 tags of deleted users have been removed. | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::step: Repair step: Clean tags and favorites | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::step: Repair step: Repair mime types | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::info: Repair info: All tables already have the correct collation -> nothing to do | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::step: Repair step: Repair MySQL collation | 2017-12-04T12:54:35+0100
Info | updater | \OC\Updater::checkAppStoreApp: Checked for update of app "workflowengine" in appstore | 2017-12-04T12:54:35+0100


```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

### PR DESCRIPTION
**Pull request by caugner**
Fixes #7837

### CODE REVIEW

**Comment by caugner** [comment]
Before:
image

After:
image

**Review by rullzer — APPROVED** [review]
Awesome.
And with tests :) :heart:

**Comment by caugner** [comment]
Unfortunately the test fails (I tried to run them locally, but `phantom` failed to spawn, I'm using NixOS, which doesn't support running the downloaded binaries):

image

I have two possible explanations:

1. Either my `sinon.stub(OC, 'getLocale')` approach doesn't work.
2. Or `phantomjs` doesn't support `toLocaleString` (at least not with the specified locale `de`).

**Comment by danielkesselberg** [comment]
>     2. Or `phantomjs` doesn't support `toLocaleString` (at least not with the specified locale `de`).

https://github.com/ariya/phantomjs/issues/12581#issuecomment-166645579 :sad

**Comment by ChristophWurst** [comment]
> First-time contributor

Awesome first-time contribution :v: Thanks a lot :rocket:

**Review by MorrisJobke — APPROVED** [review]

**Review by MorrisJobke — CHANGES_REQUESTED** [review]
Nice 👍 but it does not work with something like `de_DE`:

```js
parseFloat('8.5').toLocaleString('de_DE');

RangeError: invalid language tag: de_DE
```

I still have no idea how to work around this phantomJS limitation :/ Maybe @danxuliu or @skjnldsv can help here

**Comment by caugner** [comment]
@MorrisJobke Yes, looks like we need to convert the Nextcloud locale we get from `OC.getLocale()` into a BCP-47 compliant language tag (which uses a dash instead of an underscore to separate language code from region code): https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#locales_argument

**Comment by rullzer** [comment]
I would be fine to get this in for now. If phantomjs doesn't play nice then so be it.

File: core/js/js.js [hunk 1]
```diff
@@ -770,6 +770,15 @@ var OCP = {},
 		return false;
 	},
 
+	/**
+	 * Returns the user's locale as a BCP 47 compliant language tag
+	 *
+	 * @return {String} locale string
+	 */
+	getCanonicalLocale: function() {
+		return this.getLocale().replace(/_/g, '-');
```
Comment (caugner) [inline core/js/js.js]: getLocale() can be undefined
```suggestion
		var locale = this.getLocale();
		return typeof locale === 'string' ? locale.replace(/_/g, '-') : locale;
```

**Review by caugner — COMMENTED** [review]
Need to cover case where `getLocale()` is undefined.

File: core/js/tests/specs/coreSpec.js [hunk 2]
```diff
@@ -560,7 +579,26 @@ describe('Core base tests', function() {
 		});
 	});
 	describe('Util', function() {
+		var locale;
+		var localeStub;
+
+		beforeEach(function() {
+			locale = OC.getLocale();
```
Comment (caugner) [inline core/js/tests/specs/coreSpec.js]: Use `OC.getCanonicalLocale()` here.

```suggestion
			locale = OC.getCanonicalLocale();
```

**Review by caugner — COMMENTED** [review]
Took stub fallback value from wrong method.

**Comment by rullzer** [comment]
I took the liberty of rebasing

**Review by ChristophWurst — APPROVED** [review]
Nice enhancement. Code looks good and is covered by tests -> :+1:

**Review by skjnldsv — APPROVED** [review]

File: core/js/tests/specs/coreSpec.js [hunk 3]
```diff
@@ -273,6 +273,25 @@ describe('Core base tests', function() {
...
+
+		beforeEach(function() {
+			localeStub = sinon.stub(OC, 'getLocale');
+		});
+		afterEach(function() {
+			localeStub.restore();
+		});
+
+		it("Returns primary locales as is", function() {
+			expect(OC.getCanonicalLocale('de')).toEqual('de');
```
Comment (caugner) [inline core/js/tests/specs/coreSpec.js]: Rather than calling `getCanonicalLocale` with the locale as a parameter, set the `localeStub` to return this locale.

File: core/js/tests/specs/coreSpec.js [hunk 4]
```diff
@@ -273,6 +273,25 @@ describe('Core base tests', function() {
...
+			expect(OC.getCanonicalLocale('zu')).toEqual('zu');
+		});
+		it("Returns extended locales with hyphens", function() {
+			expect(OC.getCanonicalLocale('az_Cyrl_AZ')).toEqual('az-Cyrl-AZ');
```
Comment (caugner) [inline core/js/tests/specs/coreSpec.js]: dito

**Review by caugner — COMMENTED** [review]
Need to fix test for `getCanonicalLocale`

File: core/js/tests/specs/coreSpec.js [hunk 5]
```diff
@@ -273,6 +273,25 @@ describe('Core base tests', function() {
...
+		beforeEach(function() {
+			localeStub = sinon.stub(OC, 'getLocale');
+		});
+		afterEach(function() {
+			localeStub.restore();
+		});
+
+		it("Returns primary locales as is", function() {
+			expect(OC.getCanonicalLocale('de')).toEqual('de');
+			expect(OC.getCanonicalLocale('zu')).toEqual('zu');
```
Comment (caugner) [inline core/js/tests/specs/coreSpec.js]:
```suggestion
			localeStub.returns('zu');
			expect(OC.getCanonicalLocale()).toEqual('zu');
```

File: core/js/tests/specs/coreSpec.js [hunk 6]
```diff
@@ -273,6 +273,25 @@ describe('Core base tests', function() {
...
+		});
+		it("Returns extended locales with hyphens", function() {
+			expect(OC.getCanonicalLocale('az_Cyrl_AZ')).toEqual('az-Cyrl-AZ');
+			expect(OC.getCanonicalLocale('de_DE')).toEqual('de-DE');
```
Comment (caugner) [inline core/js/tests/specs/coreSpec.js]:
```suggestion
			localeStub.returns('de_DE');
			expect(OC.getCanonicalLocale()).toEqual('de-DE');
```

**Comment by MorrisJobke** [comment]
There is still an error in the JSUnit tests :'(

**Comment by caugner** [comment]
@MorrisJobke Looks like a test artefact to me: https://drone.nextcloud.com/nextcloud/server/11798/284

Is there an easy way to trigger another CI run?

**Comment by skjnldsv** [comment]
@caugner https://drone.nextcloud.com/nextcloud/server/11833/283

**Comment by danxuliu** [comment]
>  Looks like either a test artefact or an unrelated test failing

Unrelated; fix is in #12039 ;-)

**Comment by MorrisJobke** [comment]
> Unrelated; fix is in #12039 ;-)

@caugner Mind to rebase on current master as the fix was merged 😉

**Comment by MorrisJobke** [comment]
> > 
> 
> @caugner Mind to rebase on current master as the fix was merged 😉

I just had a look and it is exactly the same stack trace -> merging.

**Comment by MorrisJobke** [comment]
@caugner Thanks for your contribution. You could have a look at other nice starter issues if you wish so: https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

I will also invite you to the Nextcloud organization here ;)
