### PR TITLE
fix(settings): federation scope menu a11y

### LINKED ISSUE #41903: [BITV] 9.4.1.2/6.3 - "Change scope" menus - Alle menus have been implemented using the aria-haspopup="menu" attribute, which informs users that a menu is being opened.(1)
> [!IMPORTANT]
> For QA, please just check that PR is merged to stable28

 However, even though the menu items can be navigated using arrow keys, the corresponding ARIA roles role="menu" and role="menuitem" are completely missing. 

https://report.bitvtest.de/default-en/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-bfbf07e5c3-v6-n3

### PR DESCRIPTION
**Pull request by ShGKme**
* Resolves: #41903 

## Summary

Use new `radio` behavior feature from `NcActionButton`.
- Remove intermediate `FederationControlAction`
  - `NcActions` doesn't fully support intermediate components
  - Fixes the `menu` role
  - Fixes keyboard navigation - Tab switches to the next UI element
- Use new `type="radio"`
  - Adjusts to `menuitemradio` role
- Remove custom styles to use new defaults
- Slightly fix padding on a small additional button
  Before | After
  ---|---
  image |  image

## Screenshots

Before | After
---|---
image | image

We also have now the default design for radio menus. See discussion in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4744#issuecomment-1790996427

So I also removed the custom design. cc @nextcloud/designers 

Old custom design | New default design
---|---
image | image

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/settings/src/components/PersonalInfo/shared/FederationControl.vue [hunk 1]
```diff
@@ -21,29 +21,31 @@
...
-			:tooltip-disabled="federationScope.tooltipDisabled"
-			:tooltip="federationScope.tooltip" />
+			:close-after-click="true"
+			:disabled="!supportedScopes.includes(federationScope.name)"
+			:icon="federationScope.iconClass"
+			:name="federationScope.displayName"
+			type="radio"
+			:value="federationScope.name"
+			:model-value="scope"
+			@update:modelValue="changeScope">
```
Comment (ShGKme) [inline apps/settings/src/components/PersonalInfo/shared/FederationControl.vue:38]: Cannot use `@update:model-value` here because NcActionButton triggers event in camelCase instead of kebab-case.

**Review by Pytal — APPROVED** [review]

File: apps/settings/src/components/PersonalInfo/shared/FederationControl.vue (hunk 1 above)
Comment (susnux) [reply apps/settings/src/components/PersonalInfo/shared/FederationControl.vue:38]: bug?

**Review by susnux — APPROVED** [review]

File: apps/settings/src/components/PersonalInfo/shared/FederationControl.vue (hunk 1 above)
Comment (ShGKme) [reply apps/settings/src/components/PersonalInfo/shared/FederationControl.vue:38]: In Vue 3 this would work, but in Vue 2 an event name is case-sensitive. So to be able to use kebab case in template (respecting recommendation and our styles), the event had to be emitted in kebab-case.

What's why in Vue 2 it was recommended to use kebab-case for events.

While for Vue 3 - camelCase 🙈

Comment (ShGKme) [reply apps/settings/src/components/PersonalInfo/shared/FederationControl.vue:38]: I'd not call it a bug. `.sync` modifier supports both.

Anyway, we cannot change it without a breaking change. Or emit both names, but I'm not sure it is good idea. (but why not)

Comment (ShGKme) [reply apps/settings/src/components/PersonalInfo/shared/FederationControl.vue:38]: image

https://v2.vuejs.org/v2/guide/components-custom-events

Comment (susnux) [reply apps/settings/src/components/PersonalInfo/shared/FederationControl.vue:38]: Alright,  thank you for the explanation :)

**Review by JuliaKirschenheuter — APPROVED** [review]
🥳

**Review by jancborchardt — APPROVED** [review]
Very nice, looks great to me design-wise. :)
