### PR TITLE
 fix(files_sharing): Hide own reshares

### LINKED ISSUE #51988: [Bug]: Reshare with (own) group ends up as double share for sharee
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

A Reshare with (own) group ends up as double share for the sharee.
This problem seems to be only with folders, where you get a reshare which is reshared to a group.
Only occurs to reshares, so not to if you're the owner of a folder and just share it with a group, where you're member of.

### Steps to reproduce

Account A shares a folder with Account B.
Account B creates a Team/Group, where he is owner of, and add Account C as member. Let's say Group A.
Account B shares a subfolder from the share of Account A with Group A, with which this reshare also comes into the files overview for Account B.

### Expected behavior

For Account B, the reshare should not be shown in the files overview.

### Nextcloud Server version

all

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by provokateurin**
* Resolves: https://github.com/nextcloud/server/issues/51988

## Summary

Another attempt at https://github.com/nextcloud/server/issues/51988.
The fix is the same, but I've dug deeper into the issue and found that the integration tests don't transfer incoming shares when doing the ownership transfer. Just enabling incoming share transfer would have been enough, but this actually pointed to problem that we currently break reshares when doing ownership transfer without incoming shares.
The original user will still have the incoming share, while the outgoing (re-)share is transferred to the new user. My fix for hiding own reshares assumed, that one would always have access to the original share when you have a reshare for it.
With the partial ownership transfer this is not true and I believe this is wrong as we must always transfer all shares to guarantee that reshares are still working as expected.

This will require some changes in Talk integration tests because paths have changed:
```diff
diff --git a/tests/integration/features/sharing-4/transfer-ownership.feature b/tests/integration/features/sharing-4/transfer-ownership.feature
index cbf596344..12f547f0f 100644
--- a/tests/integration/features/sharing-4/transfer-ownership.feature
+++ b/tests/integration/features/sharing-4/transfer-ownership.feature
@@ -65,11 +65,11 @@ Feature: transfer-ownership
       | displayname_owner      | participant2-displayname |
       | uid_file_owner         | participant3 |
       | displayname_file_owner | participant3-displayname |
-      | path                   | /welcome (2).txt |
+      | path                   | /Talk/welcome (2).txt |
       | item_type              | file |
       | mimetype               | text/plain |
-      | storage_id             | shared::/welcome (2).txt |
-      | file_target            | /welcome (2).txt |
+      | storage_id             | shared::/Talk/welcome (2).txt |
+      | file_target            | /Talk/welcome (2).txt |
       | share_with             | group room |
       | share_with_displayname | Group room |
     And user "participant2" gets last share
@@ -78,10 +78,10 @@ Feature: transfer-ownership
       | displayname_owner      | participant2-displayname |
       | uid_file_owner         | participant3 |
       | displayname_file_owner | participant3-displayname |
-      | path                   | /Talk/welcome (2).txt |
+      | path                   | REGEXP /^\/Transferred from participant1-displayname on [0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}-[0-9]{2}-[0-9]{2}\/welcome \(2\)\.txt$/ |
       | item_type              | file |
       | mimetype               | text/plain |
-      | storage_id             | shared::/Talk/welcome (2).txt |
+      | storage_id             | REGEXP /^shared::\/Transferred from participant1-displayname on [0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}-[0-9]{2}-[0-9]{2}\/welcome \(2\)\.txt$/ |
       | file_target            | /Talk/welcome (2).txt |
       | share_with             | group room |
       | share_with_displayname | Group room |
```

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by come-nc — COMMENTED** [review]
Code-wise this is okay, but I’m not sure about the design decision.
There might be no reshares, do we really want to remove the possibility to transfer ownership without incoming shares?

**Review by come-nc — COMMENTED** [review]
Also, transfer takes a path to transfer ownership only of a folder, but with this PR all incoming shares including outside of this path will be included I think?

**Comment by provokateurin** [comment]
>  There might be no reshares, do we really want to remove the possibility to transfer ownership without incoming shares?

TBH I don't see why we have it as an option in the first place. The PR that added it has no explanation or review comments that give a reason for the option to exist.

> Also, transfer takes a path to transfer ownership only of a folder, but with this PR all incoming shares including outside of this path will be included I think?

I didn't look into it because I thought this was already done correctly, so I suppose this is another bug with the existing implementation outside of the bug I'm trying to fix (but of course I will fix it as well).

File: apps/files/lib/Service/OwnershipTransferService.php [hunk 1]
```diff
@@ -388,14 +387,22 @@ private function collectIncomingShares(string $sourceUid,
...
-				foreach ($sharePage as $singleShare) {
-					$shares[$singleShare->getNodeId()] = $singleShare;
-				}
-			} else {
-				foreach ($sharePage as $singleShare) {
-					$shares[] = $singleShare;
-				}
+
+			if ($path !== null && $path !== "$sourceUid/files") {
+				$userFolder = $this->rootFolder->getUserFolder($sourceUid);
```
Comment (come-nc) [inline apps/files/lib/Service/OwnershipTransferService.php]: Not sure how big the impact is but this could be done outside of the while to avoid rebuilding the userFolders on each page

File: apps/files/lib/Service/OwnershipTransferService.php [hunk 2]
```diff
@@ -388,14 +387,22 @@ private function collectIncomingShares(string $sourceUid,
...
+				$normalizedPath = Filesystem::normalizePath($path);
```
Comment (come-nc) [inline apps/files/lib/Service/OwnershipTransferService.php]: Same, should be done only once.

File: apps/files/lib/Service/OwnershipTransferService.php [hunk 3]
```diff
@@ -388,14 +387,22 @@ private function collectIncomingShares(string $sourceUid,
...
+
+				$sharePage = array_filter($sharePage, static function (IShare $share) use ($userFolder, $normalizedPath) {
+					try {
+						return str_starts_with(Filesystem::normalizePath($userFolder->getFirstNodeById($share->getNodeId())->getPath() . '/', false), $normalizedPath . '/');
```
Comment (come-nc) [inline apps/files/lib/Service/OwnershipTransferService.php]:
```suggestion
						return str_starts_with(Filesystem::normalizePath($share->getTarget()) . '/', false), $normalizedPath . '/');
```
This should work, no?

File: apps/files/lib/Command/TransferOwnership.php [hunk 4]
```diff
@@ -60,12 +60,6 @@ protected function configure(): void {
 				null,
 				InputOption::VALUE_NONE,
 				'move data from source user to root directory of destination user, which must be empty'
-			)->addOption(
```
Comment (nickvergessen) [inline apps/files/lib/Command/TransferOwnership.php]: removing command options is a breaking change of scripting that could be in place.
Could instead keep it and change the description stating that it now is (not?) done by default

**Review by come-nc — APPROVED** [review]

**Review by susnux — APPROVED** [review]

**Comment by provokateurin** [comment]
Marking as draft for now, as I still want to address @nickvergessen's comment.

File: apps/files_sharing/lib/MountProvider.php [hunk 5]
```diff
@@ -55,7 +55,7 @@ public function getMountsForUser(IUser $user, IStorageFactory $loader) {
 
 		// filter out excluded shares and group shares that includes self
 		$shares = array_filter($shares, function (IShare $share) use ($user) {
-			return $share->getPermissions() > 0 && $share->getShareOwner() !== $user->getUID();
+			return $share->getPermissions() > 0 && $share->getShareOwner() !== $user->getUID() && $share->getSharedBy() !== $user->getUID();
```
Comment (nickvergessen) [inline apps/files_sharing/lib/MountProvider.php:58]: Should also apply on https://github.com/nextcloud/server/blob/2bb8c72c471b58125deb1d30aa6cdc1cd91c56cc/apps/files_sharing/lib/Controller/ShareAPIController.php#L870 ?
