### PR TITLE
fix(updater): Stop expiring secret prematurely

### LINKED ISSUE #574: Web update cannot continue after long backup
Sometimes I am stuck at this position when using web updater:

Screenshot_20240713_220835

And *Retry update* would fail, because the reason is that the updater secret is meanwhile outdated:

Screenshot_20240713_220948

That is the same secret with which the previous "step 4" (download) succeeded. The previous backup step took 15.3s. 

Something must have reset or deleted the updater secret in this process.

Opening the admin overview page and from there opening the updater again, let's me finish the update.

### LINKED ISSUE #45714: Log `updater.secret` creation and expiration
We should be logging whenever the `updater.secret` gets set and whenever it expires out. This may help catch some situations such as:

- clicking on the "Open updater" button in different tabs/windows/browsers (which will break an existing Updater run in the original tab/window/browser)
- ? not sure but that's why we should log this sort of thing to make debugging easier :)

The `updater.secret` is re-generated every time the "Open updater" button is clicked in the *Administration settings->Overview* screen. 

https://github.com/nextcloud/server/blob/3237123293205e1f241d4e95960e58f48f2c3c53/apps/updatenotification/src/components/UpdateNotification.vue#L57

https://github.com/nextcloud/server/blob/3237123293205e1f241d4e95960e58f48f2c3c53/apps/updatenotification/src/components/UpdateNotification.vue#L426

https://github.com/nextcloud/server/blob/08baf177862cf428f6e64648a669f44deecefcdf/apps/updatenotification/lib/Controller/AdminController.php#L56

The token is also automatically deleted 48 hours later:

https://github.com/nextcloud/server/blob/08baf177862cf428f6e64648a669f44deecefcdf/apps/updatenotification/lib/BackgroundJob/ResetToken.php#L44-L46

We should log:
 
- when the `updater.secret` is generated 
- when an outdated `updater.secret` is removed

The log level should be WARN so that it's picked up by default in most environments. This should be acceptable because the secret is generated rarely and the expiration background job can only have a secret to clear (and thus log about) as often as a new secret is generated.

### PR DESCRIPTION
**Pull request by joshtrichards**
* Resolves: nextcloud/updater#574 
* Resolves: #45714

## Summary

#43967 introduced a regression in the handling of the expiration of `updater.secret`. The result is that `updater.secret` is expired at the next job interval (~10 minutes). If the web Updater takes >10 minutes this prevents it from continuing. 

* Fixed expiration handling
* Added logging when we expire the secret
* Added cleanup of the `updater.secret.created` value when we expire a secret
* Added handling for `config_is_read_only` in the `AdminController`
* Changed `ResetToken` background job unit tests to catch the scenario addressed by this PR
* Expanded `ResetToken` background job unit test coverage in general
* Expanded `AdminController` unit test coverage in general

## TODO

- [ ] Tests: Confirm new tests are working (I eliminated the `static` used in the `ResetToken` test since it didn't seem to serve a purpose but I may have broken it so may require another look)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/updatenotification/lib/BackgroundJob/ResetToken.php [hunk 1]
```diff
@@ -26,24 +27,31 @@ public function __construct(
...
 	/**
 	 * @param $argument
 	 */
 	protected function run($argument) {
 		if ($this->config->getSystemValueBool('config_is_read_only')) {
+			$this->logger->debug('Skipping `updater.secret` reset since config_is_read_only is set', ['app' => 'updatenotification']);
 			return;
 		}
 
 		$secretCreated = $this->appConfig->getValueInt('core', 'updater.secret.created', $this->time->getTime());
```
Comment (nickvergessen) [inline apps/updatenotification/lib/BackgroundJob/ResetToken.php:46]:
```suggestion
		$secretCreated = $this->appConfig->getValueInt('core', 'updater.secret.created');
		if ($secretCreated === 0) {
			...
```

Should handle the "does not even exist" case.
Or should we even always try the delete of the `updater.secret`, when the timestamp is missing?

File: apps/updatenotification/lib/BackgroundJob/ResetToken.php [hunk 2]
```diff
@@ -26,24 +27,31 @@ public function __construct(
...
 		// Delete old tokens after 2 days
-		if ($secretCreated >= 172800) {
```
Comment (nickvergessen) [inline apps/updatenotification/lib/BackgroundJob/ResetToken.php:45]: What an oversight 🙈

File: apps/updatenotification/tests/BackgroundJob/ResetTokenTest.php [hunk 3]
```diff
@@ -50,29 +55,53 @@ public function testRunWithNotExpiredToken(): void {
...
+			->method('deleteKey');
+		$this->logger
+			->expects($this->never())
+			->method('warning');
+		$this->logger
+			->expects($this->once())
+			->method('debug');
 
-		static::invokePrivate($this->resetTokenBackgroundJob, 'run', [null]);
+		$this->invokePrivate($this->resetTokenBackgroundJob, 'run', [null]);
```
Comment (nickvergessen) [inline apps/updatenotification/tests/BackgroundJob/ResetTokenTest.php:68]:
```suggestion
		static::invokePrivate($this->resetTokenBackgroundJob, 'run', [null]);
```

Static is the correct/new stuff. `$this->invokePrivate` actually generates a warning in IDEs?

Ref https://github.com/nextcloud/server/commit/ffb3a3e33a2b0468a39ab9f11cf8f63f020bd0bb

File: apps/updatenotification/tests/BackgroundJob/ResetTokenTest.php [hunk 4]
```diff
@@ -13,35 +13,40 @@
...
 		$this->resetTokenBackgroundJob = new BackgroundJobResetToken(
 			$this->timeFactory,
 			$this->config,
 			$this->appConfig,
+			$this->logger,
 		);
 	}
 
-	public function testRunWithNotExpiredToken(): void {
+	public function testRunWithNotExpiredToken(): void { // Affirm if updater.secret.created <48 hours ago then `updater.secret` is left alone
```
Comment (nickvergessen) [inline apps/updatenotification/tests/BackgroundJob/ResetTokenTest.php:40]: Make the comment part of the function name, so the failing test explains it right away without diving into test code,
Otherwise at least make it a proper doc block above the test case

**Review by nickvergessen — DISMISSED** [review]

**Comment by heeplr** [comment]
Any news on this?

Issue #610 just happened again when updating from 30.0.10 to 30.0.11 (download took very long).

File: apps/updatenotification/tests/BackgroundJob/ResetTokenTest.php (hunk 4 above)
Comment (susnux) [reply apps/updatenotification/tests/BackgroundJob/ResetTokenTest.php:40]:
```suggestion
	/**
	 * Affirm if updater.secret.created <48 hours ago then `updater.secret` is left alone.
	 */
	public function testKeepSecretWhenCreatedRecently(): void {
```

**Review by come-nc — APPROVED** [review]

**Review by susnux — APPROVED** [review]

**Comment by artonge** [comment]
- Rebased
- Fixed php-cs error
- Fixed unit test error

**Comment by SystemKeeper** [comment]
Looks like this will now log a warning on each run, as the default value from `getValueInt` was removed and no check for non-zero values was added. https://help.nextcloud.com/t/warning-updatenotification-cleared-old-updater-secret-that-was-created-1763885703-seconds-ago-every-hour/236299

**Comment by gvanteylingen** [comment]
Experiencing same log issue Cleared old `updater.secret` that was created xxxxxx seconds ago, twice every 65 minutes after updating to 32.0.2.
