### PR TITLE
fix(Template): harden enabled-theme logic

### LINKED ISSUE #52388: [Bug]: Error page not rendered correctly
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Because of a mistake I made today, my dev instance was set to `installed => false`. That resulted in the following exception (plain PHP error):

```
Autoload path not allowed: /var/www/html/apps/theming/lib/service/themesservice.php /var/www/html/lib/autoloader.php at 119
#0 /var/www/html/lib/autoloader.php(144): OC\Autoloader->isValidPath('/var/www/html/a...')
#1 [internal function]: OC\Autoloader->load('OCA\\Theming\\Ser...')
#2 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(104): ReflectionClass->__construct('OCA\\Theming\\Ser...')
#3 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(124): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Theming\\Ser...')
#4 /var/www/html/lib/private/ServerContainer.php(155): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Theming\\Ser...', true)
#5 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(42): OC\ServerContainer->query('OCA\\Theming\\Ser...')
#6 /var/www/html/lib/public/Server.php(37): OC\AppFramework\Utility\SimpleContainer->get('OCA\\Theming\\Ser...')
#7 /var/www/html/lib/private/TemplateLayout.php(202): OCP\Server::get('OCA\\Theming\\Ser...')
#8 /var/www/html/lib/private/Template/Template.php(115): OC\TemplateLayout->getPageTemplate('error', '')
#9 /var/www/html/lib/private/Template/Base.php(103): OC\Template\Template->fetchPage()
#10 /var/www/html/lib/private/Template/TemplateManager.php(129): OC\Template\Base->printPage()
#11 /var/www/html/index.php(90): OC\Template\TemplateManager->printExceptionErrorPage(Object(OCP\AutoloadNotAllowedException), 500)
#12 {main}
```

which points to https://github.com/nextcloud/server/blob/56b9974c419f797d85b9e48d1402374e6cfacfb6/lib/private/TemplateLayout.php#L202, as we don't catch that specific error. 

After commenting this, I had a themed error page again, this time with

```
Nachricht: Autoload path not allowed: /var/www/html/apps/theming/lib/service/themesservice.php
Datei: /var/www/html/lib/autoloader.php
Zeile: 119

Trace
#0 /var/www/html/lib/autoloader.php(144): OC\Autoloader->isValidPath('/var/www/html/a...')
#1 [internal function]: OC\Autoloader->load('OCA\\Theming\\Ser...')
#2 /var/www/html/lib/private/TemplateLayout.php(148): class_exists('\\OCA\\Theming\\Se...')
#3 /var/www/html/lib/private/Template/Template.php(115): OC\TemplateLayout->getPageTemplate('guest', '')
#4 /var/www/html/lib/private/Template/Base.php(103): OC\Template\Template->fetchPage()
#5 /var/www/html/lib/private/Template/TemplateManager.php(49): OC\Template\Base->printPage()
#6 /var/www/html/core/Controller/SetupController.php(66): OC\Template\TemplateManager->printGuestPage('', 'installation_fo...')
#7 /var/www/html/core/Controller/SetupController.php(44): OC\Core\Controller\SetupController->displaySetupForbidden()
#8 /var/www/html/lib/base.php(1004): OC\Core\Controller\SetupController->run(Array)
#9 /var/www/html/index.php(25): OC::handleRequest()
#10 {main}
```

(so at https://github.com/nextcloud/server/blob/56b9974c419f797d85b9e48d1402374e6cfacfb6/lib/private/TemplateLayout.php#L148-L151). After commenting this part as well, I ended up in the "correct" error message:

> Es sieht so aus, als ob Sie Nextcloud erneut installieren möchten. Es fehlt jedoch die Datei CAN_INSTALL in ihrem Konfigurationsordner. Bitte erstellen Sie die Datei CAN_INSTALL im Konfigurationsordner um fortzufahren.

Regression from https://github.com/nextcloud/server/pull/51752 and https://github.com/nextcloud/server/pull/51933 ?

### Nextcloud Server version

master

### PR DESCRIPTION
**Pull request by susnux**
* Resolves https://github.com/nextcloud/server/issues/52388

Only on master as 31 and below have a different logic.

### CODE REVIEW

**Comment by SystemKeeper** [comment]
Can confirm it works again now, but this reverts the changes from https://github.com/nextcloud/server/pull/50076. Should we also do a try-catch at that point?

**Comment by susnux** [comment]
@SystemKeeper no it does not I just removed the duplicated logic. It is added for all views in the try-catch block no need to have a special handling in the switch block

**Comment by SystemKeeper** [comment]
Mistook the break for a return 😅

**Review by SystemKeeper — APPROVED** [review]

**Review by AndyScherzinger — APPROVED** [review]

File: lib/private/TemplateLayout.php [hunk 1]
```diff
@@ -200,10 +194,9 @@ public function getPageTemplate(string $renderAs, string $appId): ITemplate {
 		// Set body data-theme
 		try {
 			$themesService = Server::get(\OCA\Theming\Service\ThemesService::class);
-		} catch (\OCP\AppFramework\QueryException) {
+		} catch (\Exception) {
```
Comment (come-nc) [inline lib/private/TemplateLayout.php:197]: Should be logged to debug at least :stuck_out_tongue:
