### PR TITLE
Add repair command to fix wrong share ownership

### LINKED ISSUE #28503: Repair step for invalid oc_share.uid_owner values
### Steps

1. Create users "user1", "user2", "user3"
2. Add "user2" to "group1"
3. Login as "user1"
4. Create a folder "test" with some contents
5. Share "test" with "user1"
6. Share "test" with "group1"
7. Search for the user share with `select * from oc_share where share_type=0 and share_with='user2'` and take note of the share id
8. Set the uid_owner to another user: `update oc_share set uid_owner='user3' where id=$id`, replace $id with the id from the previous query
9. Login as "user2"
10. Enter the folder "test"

### Expected result
Contents of "test" visible.

### Actual result
Folder "test" appears empty.

### Versions
The behavior was observed on Nextcloud 20.0.8.
But I was able to reproduce it on master 3ac9b565dbd9e32b7075322bf40a14abcca813c4

### Analysis

Please note that this situation has been reported following a transfer ownership operation that failed in some way, and left the oc_share table in the state created above.

Because the "uid_owner" does not match the actual owner of the storage to which the "item_source" points, it seems the code decides to return no data.

### Solutions

1) Make the code that creates the "supershare" more robust and tolerate wrong "uid_owner" values, but is that safe ? This should probably also log a warning of sorts, but without polluting the logs.

2) Write a repair step that finds such scenarios and updates "uid_owner" to the correct value based on who the original storage owner is.

### PR DESCRIPTION
**Pull request by artonge**
Fix https://github.com/nextcloud/server/issues/28503
Follow up of https://github.com/nextcloud/server/issues/30791

### CODE REVIEW

File: lib/private/Repair/RepairShareOwnership.php [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+			}
+
+			$share = $this->shareManager->getShareById($shareId);
+
+			if ($share->getShareOwner() === $share->getSharedBy()) {
+				$share->setSharedBy($mountOwner);
+			}
+			$share->setShareOwner($mountOwner);
+
+			$this->shareManager->updateShare($share);
```
Comment (PVince81) [inline lib/private/Repair/RepairShareOwnership.php:84]: I guess we don't run into dead locks here as we're updating results on which we are currently iterating ?

File: lib/private/Repair/RepairShareOwnership.php [hunk 2]
```diff
@@ -0,0 +1,94 @@
...
+		$qb = $this->dbConnection->getQueryBuilder();
+		$brokenShare = $qb
+			->select('s.id', 'm.user_id', 's.uid_owner', 's.uid_initiator', 's.share_with')
+			->from('share', 's')
+			->join('s', 'filecache', 'f', $qb->expr()->eq('s.item_source', 'f.fileid'))
+			->join('s', 'mounts', 'm', $qb->expr()->eq('f.storage', 'm.storage_id'))
+			->where($qb->expr()->neq('m.user_id', 's.uid_owner'))
+			->andWhere($qb->expr()->eq($qb->func()->concat($qb->expr()->literal('/'), 'm.user_id', $qb->expr()->literal('/')), 'm.mount_point'))
+			->executeQuery()
+			->fetchAll();
```
Comment (PVince81) [inline lib/private/Repair/RepairShareOwnership.php:62]: if this is the query from my ticket, we ran it on c.nc.com and it took 4-7 minutes to reply, so I wonder if we need additional indices there or if we should split the query somehow ? @icewind1991 any advice ?

Comment (PVince81) [reply lib/private/Repair/RepairShareOwnership.php:62]: it seems we also have the concept of expensive repair steps, possibly with some flag to set
I believe that the expensive ones would not be executing during an upgrade but we can recommend running them with `occ maintenance:repair --include-expensive` or make it an occ command instead

if occ we'd want to provide some form of progress bar (support exists as part of occ commands)

Comment (PVince81) [reply lib/private/Repair/RepairShareOwnership.php:62]: let's move this occ as discussed earlier

**Comment by PVince81** [comment]
conflict

**Comment by PVince81** [comment]
- [ ] we should test this with group folders and system-wide external storages (and shares created from there) to make sure we're not messing these up

**Comment by PVince81** [comment]
@icewind1991 please take over

**Comment by icewind1991** [comment]
- moved to occ command
- added option to repair for single user only
- added progressbar
- verified that shares from groupfolders are ignored

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
- [ ] BUG: doesn't work with group shares, the repair command fails with an error about unknown share type 2

Share type 2 is for the sub-shares, we either need to exclude them and hope that the API calls below will straighten them out, or repair them directly in the database if the former approach doesn't work.

@icewind1991

**Comment by PVince81** [comment]
- [ ] BUG: in a test we also found the share type 11 which appears to be internal to talk, so probably we should exclude a few unrelated share types (if applicable). possibly those will need a different approach for repairing, separately

**Comment by PVince81** [comment]
- [ ] BUG: a case was found on our server with this:

```
Could not get proper share mount for 1820943. Failing since else the next calls are called with null
```

**Comment by icewind1991** [comment]
I guess doing the repairs directly in the DB makes most sense

**Comment by icewind1991** [comment]
switched to updating the db directly instead of going through the share manager

File: core/Command/Maintenance/RepairShareOwnership.php [hunk 3]
```diff
@@ -86,13 +87,15 @@ protected function execute(InputInterface $input, OutputInterface $output): int
 		foreach ($found as $item) {
 			$output->writeln($item);
 		}
+		$this->dbConnection->commit();
```
Comment (PVince81) [inline core/Command/Maintenance/RepairShareOwnership.php:90]: should we commit in batches ? not sure how much data we'll find out there

Comment (icewind1991) [reply core/Command/Maintenance/RepairShareOwnership.php:87]: I expect the to be a small number of writes, the commit is mostly there to prevent leaving the db in an in-between state if an exception happens

**Comment by PVince81** [comment]
@icewind1991 is this ready for testing ? if yes, please coordinate with @matthieugallien

**Comment by icewind1991** [comment]
switched to a 2-step of first gathering all broken shares and then updating them in one go, this reduces the duration of the transaction and allow for a bit nicer ux

File: core/Command/Maintenance/RepairShareOwnership.php [hunk 4]
```diff
@@ -0,0 +1,173 @@
...
+				return 1;
+			}
+			$shares = $this->getWrongShareOwnershipForUser($user);
+		} else {
+			$shares = [];
+			$userCount = $this->userManager->countSeenUsers();
+			$progress = new ProgressBar($output, $userCount);
+			$this->userManager->callForSeenUsers(function (IUser $user) use (&$shares, $progress) {
+				$progress->advance();
+				$shares = array_merge($shares, $this->getWrongShareOwnershipForUser($user));
```
Comment (PVince81) [inline core/Command/Maintenance/RepairShareOwnership.php:78]: if this gets very big like 1000+ entries on bigger instances with lots of users and shares ?
would the generator pattern work here ?

it wouldn't allow us to count the number of cases to fix though

and the generator pattern would likely lock something in the DB while we keep the cursor open, so here probably we'd recommend a "all users" fix outside of active hours

File: core/Command/Maintenance/RepairShareOwnership.php [hunk 5]
```diff
@@ -0,0 +1,173 @@
...
+			->andWhere($qb->expr()->eq($qb->func()->concat($qb->expr()->literal('/'), 'm.user_id', $qb->expr()->literal('/')), 'm.mount_point'))
+			->andWhere($qb->expr()->eq('s.share_with', $qb->createNamedParameter($user->getUID())))
+			->executeQuery()
+			->fetchAll();
+
+		$found = [];
+
+		foreach ($brokenShares as $share) {
+			$found[] = [
+				'shareId' => (int) $share['id'],
```
Comment (PVince81) [inline core/Command/Maintenance/RepairShareOwnership.php:132]: ... at least saving some memory here by only picking the data we need

File: lib/private/Share20/Manager.php [hunk 6]
```diff
@@ -2088,4 +2088,8 @@ public function getAllShares(): iterable {
 			yield from $provider->getAllShares();
 		}
 	}
+
+	public function getProviderForType(int $shareType): IShareProvider {
```
Comment (PVince81) [inline lib/private/Share20/Manager.php:2092]: add to public interface ? it's a "for use only, don't extend" anyway so it's safe

**Review by PVince81 — APPROVED** [review]
Code looks fine apart from some concerns with bigger instances

**Comment by PVince81** [comment]
@icewind1991 please tick the (bug) checkboxes to confirm that you fixed those

@matthieugallien you should be able to retest this command

File: core/Command/Maintenance/RepairShareOwnership.php (hunk 5 above)
Comment (icewind1991) [reply core/Command/Maintenance/RepairShareOwnership.php:132]: we use all of these fields

File: core/Command/Maintenance/RepairShareOwnership.php (hunk 4 above)
Comment (icewind1991) [reply core/Command/Maintenance/RepairShareOwnership.php:78]: it also wouldn't allow showing the broken shares before starting the repair.

I really don't expect this to be an issue and in the worst case an admin will hit a memory error before anything is committed and they can re-run it per-user.

File: lib/private/Share20/Manager.php (hunk 6 above)
Comment (icewind1991) [reply lib/private/Share20/Manager.php]: this is no longer needed, removed

File: core/Command/Maintenance/RepairShareOwnership.php [hunk 7]
```diff
@@ -0,0 +1,196 @@
+<?php
+
+declare(strict_types=1);
+
+/**
+ * @copyright Copyright (c) 2020 Arthur Schiwon <blizzz@arthur-schiwon.de>
+ *
+ * @author Arthur Schiwon <blizzz@arthur-schiwon.de>
```
Comment (artonge) [inline core/Command/Maintenance/RepairShareOwnership.php:8]: Impersonation

**Review by artonge — COMMENTED** [review]
:heavy_check_mark: Looks good, but can't approve as I am an author.

**Comment by PVince81** [comment]
@mgallien are you talking about the latest version of the code ? I just realize that @icewind1991 had pushed recently, so just wanted to double check that it's indeed what you ran

**Comment by mgallien** [comment]
> @mgallien are you talking about the latest version of the code ? I just realize that @icewind1991 had pushed recently, so just wanted to double check that it's indeed what you ran

@PVince81 the changes were done before the command was run on our server and done after feedback from first run on our instance
so yes, I approve the behavior of the last push

**Comment by PVince81** [comment]
okay, so this would be ready to merge. (Louis approved the changes made after his ones)

@icewind1991 please merge if you agree

**Comment by PVince81** [comment]
second review please, this is long overdue

**Review by szaimen — APPROVED** [review]
🐘

**Comment by PVince81** [comment]
@icewind1991 some checkers fail, autoloader likely

**Comment by monsieurhannes** [comment]
Just tried to find documentation about it and ended up here. Anyone who can add it to the docs (as I don't know what it does)?
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html#maintenance-commands
