### PR TITLE
Extend pending shares list in frontend to include remote shares

### LINKED ISSUE #23769: Cannot accept or decline federated share after dismissing notification
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce

1. Share a file with a remote user
2. Dismiss notification in the remote Nextcloud instance without clicking "accept" or "decline"
3. Cannot accept or dismiss external share anymore

### Expected behaviour

The pending external share should be shown somewhere, for instance, in "Pending shares".

### Actual behaviour

The pending external share is nowhere to be found. The entry in the `oc_share_external` table still exists, though.

### Server configuration

**Operating system:** Fedora 32

**Web server:** Apache 2.4.46

**Database:** PostgreSQL 12.4

**PHP version:** 7.4.11

**Nextcloud version:** 20.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from Nextcloud 19.x

**Where did you install Nextcloud from:** Installed manually using tarballs.

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration

**Browser:** Chrome 86

**Operating system:** Fedora 32

#### Web server error log

<details>
<summary>Web server error log</summary>
Nothing relevant in the logs.
</details>

#### Nextcloud log (data/nextcloud.log)

<details>
<summary>Nextcloud log</summary>
Nothing relevant in the logs.
</details>

### PR DESCRIPTION
**Pull request by PVince81**
And adjust the accept/decline actions to use the right endpoint for remote shares.
Note: the backend API was already available.

Fixes https://github.com/nextcloud/server/issues/23769

Also makes the following scenario work:

1. On instance A share a folder "test" with a group "group1" on instance B
2. On instance B, add a new user "new-user" to the group "group1"
3. Login as "new-user"
4. Go to "Pending shares" and accept the received remote share

In this scenario no notification is generated for the newly added user, and I don't think we want to.
This PR still makes the pending remote share visible in the correct place.

### Single user remote share
- [x] list
- [x] accept
- [x] reject
- re-accept => not possible, once rejected it's gone, by design
- re-reject  => not possible, once rejected it's gone, by design

### Group remote share

- [x] list
- [x] accept
- [x] reject
- [x] add user to group => pending share appears for that user
- [x] re-accept
- [x] re-reject

### CODE REVIEW

**Comment by PVince81** [comment]
- [ ] bug: adjust endpoint target for rejecting share: needs extra "/pending" suffix

**Comment by PVince81** [comment]
- [ ] bug: some mess happening after accepting a group share, it seems the share entries have duplicated in the DB but now for the current user

I wonder if that existing backend part is really reliable or whether it contains yet to be discovered bugs :thinking:

**Comment by PVince81** [comment]
it looks like "oc_share_external" for groups works in a similar fashion like "oc_share": for a group share there's a main entry and sub-entries.

This is how it looks like after rejecting the group share "new-group-share-reject":
```
+----+--------+------------+--------------------------------+-----------+-----------------+----------+-------------------------+-------+-------------+-----------------------------------------------------+----------------------------------+----------+
| id | parent | share_type | remote                         | remote_id | share_token     | password | name                    | owner | user        | mountpoint                                          | mountpoint_hash                  | accepted |
+----+--------+------------+--------------------------------+-----------+-----------------+----------+-------------------------+-------+-------------+-----------------------------------------------------+----------------------------------+----------+
|  6 |     -1 |          1 | https://vvortex-release.local/ | 32        | 5HRRJLdWNSZzSmE |          | /new-group-share-accept | admin | named-users | {{TemporaryMountPointName#/new-group-share-accept}} | 3bea95b0013a55aa8d1b0fc5bd9198c9 |        0 |
|  7 |     -1 |          1 | https://vvortex-release.local/ | 33        | ynZpKQYrw5jcN9O |          | /new-group-share-reject | admin | named-users | {{TemporaryMountPointName#/new-group-share-reject}} | 3ef4d6505bba0fc9dd07a6877f387731 |        0 |
|  8 |      7 |          1 | https://vvortex-release.local/ | 33        | ynZpKQYrw5jcN9O |          | /new-group-share-reject | admin | evert       | {{TemporaryMountPointName#/new-group-share-reject}} | 3ef4d6505bba0fc9dd07a6877f387731 |        0 |
+----+--------+------------+--------------------------------+-----------+-----------------+----------+-------------------------+-------+-------------+-----------------------------------------------------+----------------------------------+----------+
```

The trouble is that all these entries are returned by the "/pending" endpoint as is, so I now see the "new-group-share-reject" entry twice in the UI. But the accept/reject actions only operate on the share id of the group share entry, the other ones return 404.

It seems that this listing endpoint is missing the logic that transforms it to the point of view of the current user. This logic should be in the backend like for regular shares. :-/

**Comment by PVince81** [comment]
yup, confirmed, the complex aggregation logic is missing here: https://github.com/nextcloud/server/blob/enh/23769/accept-decline-fed-sharing-ui/apps/files_sharing/lib/External/Manager.php#L644

File: apps/files_sharing/js/sharedfilelist.js [hunk 1]
```diff
@@ -263,6 +276,7 @@
 			},
 
 			reloadCallback: function(shares, remoteShares, additionalShares) {
+				console.log('## reloadCallback', shares, remoteShares, additionalShares)
```
Comment (juliushaertl) [inline apps/files_sharing/js/sharedfilelist.js:279]: Leftover?

**Comment by PVince81** [comment]
I've fixed the backend now and extended the unit tests, it was a bit more complicated than expected.

I've used the old style queries to save some time. At some point we should move to the query builder.

Up next: retesting through the frontend and checking for bugs

File: apps/files_sharing/lib/External/Manager.php [hunk 2]
```diff
@@ -629,23 +646,39 @@ private function getShares($accepted) {
...
+			foreach ($shares as $share) {
+				if ((int)$share['share_type'] === IShare::TYPE_GROUP && $share['parent'] > 0) {
+					$toRemove[] = $share['parent'];
+				}
+			}
+			$shares = array_filter($shares, function ($share) use ($toRemove) {
+				return !in_array($share['id'], $toRemove, true);
+			});
+
+			if (!is_null($accepted)) {
```
Comment (PVince81) [inline apps/files_sharing/lib/External/Manager.php:673]: note: I had to move this out of the SQL query because when fetching the group share entry is never "accepted" but the sub-entry might be, and we need to have the non-accepted group share present to delete it from the results with the above filter

**Comment by PVince81** [comment]
fixed postgresql tests by adding more casting for the returned DB values

**Comment by PVince81** [comment]
- [ ] BUG: can't re-accept after rejecting group share once: this is because the share entry returned by the API is actually the sub-share, and this one can't be re-inserted...

**Comment by PVince81** [comment]
- [ ] make sure we only fetch a single share when processing the mount

**Comment by PVince81** [comment]
- [ ] remove "reject" action for pending group share as it cannot be discarded

**Comment by PVince81** [comment]
- [ ] prevent sidebar to open/load for remote shares as we have no data ? (click the avatar of owner)

**Comment by PVince81** [comment]
- [ ] bug: only remove the "reject" action for received **group shares** not user shares

**Comment by PVince81** [comment]
I've fixed the mess in the backend and now it is possible to work with the sub-share entry when re-accepting or rejecting.

- [ ] check what happens when operating on the group share id whenever a sub-share id already exists...

**Comment by PVince81** [comment]
- [ ] backport/split the code that adds missing remote group share handling for status icon ?
- [ ] split the code that enhances fileactions ?

**Comment by PVince81** [comment]
- [ ] icon should be of a share, and maybe of a group (people + folder) for a received group share

because the user needs to understand why they can't get rid of the group share when opting out while they can for the remote user share

**Comment by PVince81** [comment]
I've fixed the issues with the file actions: the share list now has no more sidebar and the default actions are disabled, including the goto plugin. This way the user doesn't end up with a 404.

**Comment by PVince81** [comment]
I just re-ran `make build-js-production` and there are no local changes, and yet Node complains about core.js updates... I didn't even touch anything related. https://github.com/nextcloud/server/pull/27751/checks?check_run_id=2989100482

Maybe because I'm running node v14, I'll try again with v12...

**Comment by PVince81** [comment]
looks like there's no unique key that prevents two sub-shares to be created for a user with the same parent... so might need another strategy to prevent duplicate sub-shares...

**Comment by PVince81** [comment]
okay, problem solved now... when accessing through API we always operate on the sub-share when it exists, regardless whether the id of the parent or the sub-share was given.

**Comment by PVince81** [comment]
I've redone a quick test with accepting, rejecting, then reaccepting a remote group share and it worked fine.

Ready for review, now.

**Comment by PVince81** [comment]
would be good to backport to 22 for a future minor even though it's a bigger thing

**Review by juliusknorr — DISMISSED** [review]
Tested and works :+1:

**Review by juliusknorr — COMMENTED** [review]
Just noticed the following when trying to reject the remote group share through the notification:

```
{
  "reqId": "8fn2qjSY2jdHp9LuDMjO",
  "level": 3,
  "time": "2021-07-12T11:41:30+00:00",
  "remoteAddr": "192.168.21.6",
  "user": "admin",
  "app": "no app in context",
  "method": "DELETE",
  "url": "/ocs/v2.php/apps/files_sharing/api/v1/remote_shares/pending/4",
  "message": "An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'admin-964931522bcd01381cddc4984b4e604b' for key 'sh_external_mp'",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0",
  "version": "23.0.0.0",
  "exception": {
    "Exception": "Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException",
    "Message": "An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'admin-964931522bcd01381cddc4984b4e604b' for key 'sh_external_mp'",
    "Code": 1062,
    "Trace": [
      {
        "file": "/var/www/html/3rdparty/doctrine/dbal/src/Connection.php",
        "line": 1728,
        "function": "convert",
        "class": "Doctrine\\DBAL\\Driver\\API\\MySQL\\ExceptionConverter",
        "type": "->",
        "args": [
          {
            "xdebug_message": "<tr><th align='left' bgcolor='#f57900' colspan=\"5\"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Doctrine\\DBAL\\Driver\\PDO\\Exception: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'admin-964931522bcd01381cddc4984b4e604b' for key 'sh_external_mp' in /var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Exception.php on line <i>26</i></th></tr>\n<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>\n<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>\n<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0002</td><td bgcolor='#eeeeec' align='right'>405984</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/var/www/html/ocs/v2.php' bgcolor='#eeeeec'>.../v2.php<b>:</b>0</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0002</td><td bgcolor='#eeeeec' align='right'>406976</td><td bgcolor='#eeeeec'>require_once( <font color='#00bb00'>'/var/www/html/ocs/v1.php'</font> )</td><td title='/var/www/html/ocs/v2.php' bgcolor='#eeeeec'>.../v2.php<b>:</b>23</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.1361</td><td bgcolor='#eeeeec' align='right'>5948240</td><td bgcolor='#eeeeec'>OC\\Route\\CachingRouter->match(  )</td><td title='/var/www/html/ocs/v1.php' bgcolor='#eeeeec'>.../v1.php<b>:</b>62</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.1435</td><td bgcolor='#eeeeec' align='right'>6303288</td><td bgcolor='#eeeeec'>OC\\AppFramework\\App::main(  )</td><td title='/var/www/html/lib/private/Route/Router.php' bgcolor='#eeeeec'>.../Router.php<b>:</b>301</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>0.2126</td><td bgcolor='#eeeeec' align='right'>8786408</td><td bgcolor='#eeeeec'>OC\\AppFramework\\Http\\Dispatcher->dispatch(  )</td><td title='/var/www/html/lib/private/AppFramework/App.php' bgcolor='#eeeeec'>.../App.php<b>:</b>157</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>0.2164</td><td bgcolor='#eeeeec' align='right'>8840616</td><td bgcolor='#eeeeec'>OC\\AppFramework\\Http\\Dispatcher->executeController(  )</td><td title='/var/www/html/lib/private/AppFramework/Http/Dispatcher.php' bgcolor='#eeeeec'>.../Dispatcher.php<b>:</b>126</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>0.2165</td><td bgcolor='#eeeeec' align='right'>8841408</td><td bgcolor='#eeeeec'>OCA\\Files_Sharing\\Controller\\RemoteController->declineShare(  )</td><td title='/var/www/html/lib/private/AppFramework/Http/Dispatcher.php' bgcolor='#eeeeec'>.../Dispatcher.php<b>:</b>217</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>0.2165</td><td bgcolor='#eeeeec' align='right'>8841408</td><td bgcolor='#eeeeec'>OCA\\Files_Sharing\\External\\Manager->declineShare(  )</td><td title='/var/www/html/apps/files_sharing/lib/Controller/RemoteController.php' bgcolor='#eeeeec'>.../RemoteController.php<b>:</b>102</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>9</td><td bgcolor='#eeeeec' align='center'>0.2171</td><td bgcolor='#eeeeec' align='right'>8869248</td><td bgcolor='#eeeeec'>OCA\\Files_Sharing\\External\\Manager->writeShareToDb(  )</td><td title='/var/www/html/apps/files_sharing/lib/External/Manager.php' bgcolor='#eeeeec'>.../Manager.php<b>:</b>401</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>10</td><td bgcolor='#eeeeec' align='center'>0.2171</td><td bgcolor='#eeeeec' align='right'>8871648</td><td bgcolor='#eeeeec'>OC\\DB\\PreparedStatement->execute(  )</td><td title='/var/www/html/apps/files_sharing/lib/External/Manager.php' bgcolor='#eeeeec'>.../Manager.php<b>:</b>221</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>11</td><td bgcolor='#eeeeec' align='center'>0.2171</td><td bgcolor='#eeeeec' align='right'>8871704</td><td bgcolor='#eeeeec'>Doctrine\\DBAL\\Statement->execute(  )</td><td title='/var/www/html/lib/private/DB/PreparedStatement.php' bgcolor='#eeeeec'>.../PreparedStatement.php<b>:</b>87</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>12</td><td bgcolor='#eeeeec' align='center'>0.2171</td><td bgcolor='#eeeeec' align='right'>8879696</td><td bgcolor='#eeeeec'>Doctrine\\DBAL\\Driver\\PDO\\Statement->execute(  )</td><td title='/var/www/html/3rdparty/doctrine/dbal/src/Statement.php' bgcolor='#eeeeec'>.../Statement.php<b>:</b>175</td></tr>\n",
            "__class__": "Doctrine\\DBAL\\Driver\\PDO\\Exception"
          },
          {
            "__class__": "Doctrine\\DBAL\\Query"
          }
        ]
      },
      {
        "file": "/var/www/html/3rdparty/doctrine/dbal/src/Connection.php",
        "line": 1667,
        "function": "handleDriverException",
        "class": "Doctrine\\DBAL\\Connection",
        "type": "->",
        "args": [
          {
            "xdebug_message": "<tr><th align='left' bgcolor='#f57900' colspan=\"5\"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Doctrine\\DBAL\\Driver\\PDO\\Exception: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'admin-964931522bcd01381cddc4984b4e604b' for key 'sh_external_mp' in /var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Exception.php on line <i>26</i></th></tr>\n<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>\n<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>\n<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0002</td><td bgcolor='#eeeeec' align='right'>405984</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/var/www/html/ocs/v2.php' bgcolor='#eeeeec'>.../v2.php<b>:</b>0</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0002</td><td bgcolor='#eeeeec' align='right'>406976</td><td bgcolor='#eeeeec'>require_once( <font color='#00bb00'>'/var/www/html/ocs/v1.php'</font> )</td><td title='/var/www/html/ocs/v2.php' bgcolor='#eeeeec'>.../v2.php<b>:</b>23</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.1361</td><td bgcolor='#eeeeec' align='right'>5948240</td><td bgcolor='#eeeeec'>OC\\Route\\CachingRouter->match(  )</td><td title='/var/www/html/ocs/v1.php' bgcolor='#eeeeec'>.../v1.php<b>:</b>62</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.1435</td><td bgcolor='#eeeeec' align='right'>6303288</td><td bgcolor='#eeeeec'>OC\\AppFramework\\App::main(  )</td><td title='/var/www/html/lib/private/Route/Router.php' bgcolor='#eeeeec'>.../Router.php<b>:</b>301</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>0.2126</td><td bgcolor='#eeeeec' align='right'>8786408</td><td bgcolor='#eeeeec'>OC\\AppFramework\\Http\\Dispatcher->dispatch(  )</td><td title='/var/www/html/lib/private/AppFramework/App.php' bgcolor='#eeeeec'>.../App.php<b>:</b>157</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>0.2164</td><td bgcolor='#eeeeec' align='right'>8840616</td><td bgcolor='#eeeeec'>OC\\AppFramework\\Http\\Dispatcher->executeController(  )</td><td title='/var/www/html/lib/private/AppFramework/Http/Dispatcher.php' bgcolor='#eeeeec'>.../Dispatcher.php<b>:</b>126</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>0.2165</td><td bgcolor='#eeeeec' align='right'>8841408</td><td bgcolor='#eeeeec'>OCA\\Files_Sharing\\Controller\\RemoteController->declineShare(  )</td><td title='/var/www/html/lib/private/AppFramework/Http/Dispatcher.php' bgcolor='#eeeeec'>.../Dispatcher.php<b>:</b>217</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>0.2165</td><td bgcolor='#eeeeec' align='right'>8841408</td><td bgcolor='#eeeeec'>OCA\\Files_Sharing\\External\\Manager->declineShare(  )</td><td title='/var/www/html/apps/files_sharing/lib/Controller/RemoteController.php' bgcolor='#eeeeec'>.../RemoteController.php<b>:</b>102</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>9</td><td bgcolor='#eeeeec' align='center'>0.2171</td><td bgcolor='#eeeeec' align='right'>8869248</td><td bgcolor='#eeeeec'>OCA\\Files_Sharing\\External\\Manager->writeShareToDb(  )</td><td title='/var/www/html/apps/files_sharing/lib/External/Manager.php' bgcolor='#eeeeec'>.../Manager.php<b>:</b>401</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>10</td><td bgcolor='#eeeeec' align='center'>0.2171</td><td bgcolor='#eeeeec' align='right'>8871648</td><td bgcolor='#eeeeec'>OC\\DB\\PreparedStatement->execute(  )</td><td title='/var/www/html/apps/files_sharing/lib/External/Manager.php' bgcolor='#eeeeec'>.../Manager.php<b>:</b>221</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>11</td><td bgcolor='#eeeeec' align='center'>0.2171</td><td bgcolor='#eeeeec' align='right'>8871704</td><td bgcolor='#eeeeec'>Doctrine\\DBAL\\Statement->execute(  )</td><td title='/var/www/html/lib/private/DB/PreparedStatement.php' bgcolor='#eeeeec'>.../PreparedStatement.php<b>:</b>87</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>12</td><td bgcolor='#eeeeec' align='center'>0.2171</td><td bgcolor='#eeeeec' align='right'>8879696</td><td bgcolor='#eeeeec'>Doctrine\\DBAL\\Driver\\PDO\\Statement->execute(  )</td><td title='/var/www/html/3rdparty/doctrine/dbal/src/Statement.php' bgcolor='#eeeeec'>.../Statement.php<b>:</b>175</td></tr>\n",
            "__class__": "Doctrine\\DBAL\\Driver\\PDO\\Exception"
          },
          {
            "__class__": "Doctrine\\DBAL\\Query"
          }
        ]
      },
      {
        "file": "/var/www/html/3rdparty/doctrine/dbal/src/Statement.php",
        "line": 179,
        "function": "convertExceptionDuringQuery",
        "class": "Doctrine\\DBAL\\Connection",
        "type": "->",
        "args": [
          {
            "xdebug_message": "<tr><th align='left' bgcolor='#f57900' colspan=\"5\"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Doctrine\\DBAL\\Driver\\PDO\\Exception: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'admin-964931522bcd01381cddc4984b4e604b' for key 'sh_external_mp' in /var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Exception.php on line <i>26</i></th></tr>\n<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>\n<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>\n<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0002</td><td bgcolor='#eeeeec' align='right'>405984</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/var/www/html/ocs/v2.php' bgcolor='#eeeeec'>.../v2.php<b>:</b>0</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0002</td><td bgcolor='#eeeeec' align='right'>406976</td><td bgcolor='#eeeeec'>require_once( <font color='#00bb00'>'/var/www/html/ocs/v1.php'</font> )</td><td title='/var/www/html/ocs/v2.php' bgcolor='#eeeeec'>.../v2.php<b>:</b>23</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.1361</td><td bgcolor='#eeeeec' align='right'>5948240</td><td bgcolor='#eeeeec'>OC\\Route\\CachingRouter->match(  )</td><td title='/var/www/html/ocs/v1.php' bgcolor='#eeeeec'>.../v1.php<b>:</b>62</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.1435</td><td bgcolor='#eeeeec' align='right'>6303288</td><td bgcolor='#eeeeec'>OC\\AppFramework\\App::main(  )</td><td title='/var/www/html/lib/private/Route/Router.php' bgcolor='#eeeeec'>.../Router.php<b>:</b>301</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>0.2126</td><td bgcolor='#eeeeec' align='right'>8786408</td><td bgcolor='#eeeeec'>OC\\AppFramework\\Http\\Dispatcher->dispatch(  )</td><td title='/var/www/html/lib/private/AppFramework/App.php' bgcolor='#eeeeec'>.../App.php<b>:</b>157</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>0.2164</td><td bgcolor='#eeeeec' align='right'>8840616</td><td bgcolor='#eeeeec'>OC\\AppFramework\\Http\\Dispatcher->executeController(  )</td><td title='/var/www/html/lib/private/AppFramework/Http/Dispatcher.php' bgcolor='#eeeeec'>.../Dispatcher.php<b>:</b>126</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>0.2165</td><td bgcolor='#eeeeec' align='right'>8841408</td><td bgcolor='#eeeeec'>OCA\\Files_Sharing\\Controller\\RemoteController->declineShare(  )</td><td title='/var/www/html/lib/private/AppFramework/Http/Dispatcher.php' bgcolor='#eeeeec'>.../Dispatcher.php<b>:</b>217</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>0.2165</td><td bgcolor='#eeeeec' align='right'>8841408</td><td bgcolor='#eeeeec'>OCA\\Files_Sharing\\External\\Manager->declineShare(  )</td><td title='/var/www/html/apps/files_sharing/lib/Controller/RemoteController.php' bgcolor='#eeeeec'>.../RemoteController.php<b>:</b>102</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>9</td><td bgcolor='#eeeeec' align='center'>0.2171</td><td bgcolor='#eeeeec' align='right'>8869248</td><td bgcolor='#eeeeec'>OCA\\Files_Sharing\\External\\Manager->writeShareToDb(  )</td><td title='/var/www/html/apps/files_sharing/lib/External/Manager.php' bgcolor='#eeeeec'>.../Manager.php<b>:</b>401</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>10</td><td bgcolor='#eeeeec' align='center'>0.2171</td><td bgcolor='#eeeeec' align='right'>8871648</td><td bgcolor='#eeeeec'>OC\\DB\\PreparedStatement->execute(  )</td><td title='/var/www/html/apps/files_sharing/lib/External/Manager.php' bgcolor='#eeeeec'>.../Manager.php<b>:</b>221</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>11</td><td bgcolor='#eeeeec' align='center'>0.2171</td><td bgcolor='#eeeeec' align='right'>8871704</td><td bgcolor='#eeeeec'>Doctrine\\DBAL\\Statement->execute(  )</td><td title='/var/www/html/lib/private/DB/PreparedStatement.php' bgcolor='#eeeeec'>.../PreparedStatement.php<b>:</b>87</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>12</td><td bgcolor='#eeeeec' align='center'>0.2171</td><td bgcolor='#eeeeec' align='right'>8879696</td><td bgcolor='#eeeeec'>Doctrine\\DBAL\\Driver\\PDO\\Statement->execute(  )</td><td title='/var/www/html/3rdparty/doctrine/dbal/src/Statement.php' bgcolor='#eeeeec'>.../Statement.php<b>:</b>175</td></tr>\n",
            "__class__": "Doctrine\\DBAL\\Driver\\PDO\\Exception"
          },
          "\n\t\t\t\tINSERT INTO `oc_share_external`\n\t\t\t\t\t(`remote`, `share_token`, `password`, `name`, `owner`, `user`, `mountpoint`, `mountpoint_hash`, `accepted`, `remote_id`, `parent`, `share_type`)\n\t\t\t\tVALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)\n\t\t\t",
          [
            "https://nextcloud.local.dev.bitgrid.net/",
            "Iw6MQuHIzsUFLzF",
            "",
            "/dfgdg",
            "user1",
            "And 7 more entries, set log level to debug to see all entries"
          ],
          []
        ]
      },
      {
        "file": "/var/www/html/lib/private/DB/PreparedStatement.php",
        "line": 87,
        "function": "execute",
        "class": "Doctrine\\DBAL\\Statement",
        "type": "->",
        "args": [
          [
            "https://nextcloud.local.dev.bitgrid.net/",
            "Iw6MQuHIzsUFLzF",
            "",
            "/dfgdg",
            "user1",
            "And 7 more entries, set log level to debug to see all entries"
          ]
        ]
      },
      {
        "file": "/var/www/html/apps/files_sharing/lib/External/Manager.php",
        "line": 221,
        "function": "execute",
        "class": "OC\\DB\\PreparedStatement",
        "type": "->",
        "args": [
          [
            "https://nextcloud.local.dev.bitgrid.net/",
            "Iw6MQuHIzsUFLzF",
            "",
            "/dfgdg",
            "user1",
            "And 7 more entries, set log level to debug to see all entries"
          ]
        ]
      },
      {
        "file": "/var/www/html/apps/files_sharing/lib/External/Manager.php",
        "line": 401,
        "function": "writeShareToDb",
        "class": "OCA\\Files_Sharing\\External\\Manager",
        "type": "->",
        "args": [
          "https://nextcloud.local.dev.bitgrid.net/",
          "Iw6MQuHIzsUFLzF",
          "",
          "/dfgdg",
          "user1",
          "admin",
          "{{TemporaryMountPointName#/dfgdg}}",
          "964931522bcd01381cddc4984b4e604b",
          0,
          "56",
          4,
          "1"
        ]
      },
      {
        "file": "/var/www/html/apps/files_sharing/lib/Controller/RemoteController.php",
        "line": 102,
        "function": "declineShare",
        "class": "OCA\\Files_Sharing\\External\\Manager",
        "type": "->",
        "args": [
          4
        ]
      },
      {
        "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 217,
        "function": "declineShare",
        "class": "OCA\\Files_Sharing\\Controller\\RemoteController",
        "type": "->",
        "args": [
          4
        ]
      },
      {
        "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 126,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OCA\\Files_Sharing\\Controller\\RemoteController"
          },
          "declineShare"
        ]
      },
      {
        "file": "/var/www/html/lib/private/AppFramework/App.php",
        "line": 157,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OCA\\Files_Sharing\\Controller\\RemoteController"
          },
          "declineShare"
        ]
      },
      {
        "file": "/var/www/html/lib/private/Route/Router.php",
        "line": 301,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::",
        "args": [
          "OCA\\Files_Sharing\\Controller\\RemoteController",
          "declineShare",
          {
            "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
          },
          {
            "id": "4",
            "_route": "ocs.files_sharing.Remote.declineShare"
          }
        ]
      },
      {
        "file": "/var/www/html/ocs/v1.php",
        "line": 62,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->",
        "args": [
          "/ocsapp/apps/files_sharing/api/v1/remote_shares/pending/4"
        ]
      },
      {
        "file": "/var/www/html/ocs/v2.php",
        "line": 23,
        "args": [
          "/var/www/html/ocs/v1.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/var/www/html/3rdparty/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php",
    "Line": 60,
    "Previous": {
      "Exception": "Doctrine\\DBAL\\Driver\\PDO\\Exception",
      "Message": "SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'admin-964931522bcd01381cddc4984b4e604b' for key 'sh_external_mp'",
      "Code": 1062,
      "Trace": [
        {
          "file": "/var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php",
          "line": 84,
          "function": "new",
          "class": "Doctrine\\DBAL\\Driver\\PDO\\Exception",
          "type": "::",
          "args": [
            {
              "errorInfo": [
                "23000",
                1062,
                "Duplicate entry 'admin-964931522bcd01381cddc4984b4e604b' for key 'sh_external_mp'"
              ],
              "xdebug_message": "<tr><th align='left' bgcolor='#f57900' colspan=\"5\"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'admin-964931522bcd01381cddc4984b4e604b' for key 'sh_external_mp' in /var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php on line <i>82</i></th></tr>\n<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>\n<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>\n<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0002</td><td bgcolor='#eeeeec' align='right'>405984</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/var/www/html/ocs/v2.php' bgcolor='#eeeeec'>.../v2.php<b>:</b>0</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0002</td><td bgcolor='#eeeeec' align='right'>406976</td><td bgcolor='#eeeeec'>require_once( <font color='#00bb00'>'/var/www/html/ocs/v1.php'</font> )</td><td title='/var/www/html/ocs/v2.php' bgcolor='#eeeeec'>.../v2.php<b>:</b>23</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.1361</td><td bgcolor='#eeeeec' align='right'>5948240</td><td bgcolor='#eeeeec'>OC\\Route\\CachingRouter->match(  )</td><td title='/var/www/html/ocs/v1.php' bgcolor='#eeeeec'>.../v1.php<b>:</b>62</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.1435</td><td bgcolor='#eeeeec' align='right'>6303288</td><td bgcolor='#eeeeec'>OC\\AppFramework\\App::main(  )</td><td title='/var/www/html/lib/private/Route/Router.php' bgcolor='#eeeeec'>.../Router.php<b>:</b>301</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>0.2126</td><td bgcolor='#eeeeec' align='right'>8786408</td><td bgcolor='#eeeeec'>OC\\AppFramework\\Http\\Dispatcher->dispatch(  )</td><td title='/var/www/html/lib/private/AppFramework/App.php' bgcolor='#eeeeec'>.../App.php<b>:</b>157</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>0.2164</td><td bgcolor='#eeeeec' align='right'>8840616</td><td bgcolor='#eeeeec'>OC\\AppFramework\\Http\\Dispatcher->executeController(  )</td><td title='/var/www/html/lib/private/AppFramework/Http/Dispatcher.php' bgcolor='#eeeeec'>.../Dispatcher.php<b>:</b>126</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>0.2165</td><td bgcolor='#eeeeec' align='right'>8841408</td><td bgcolor='#eeeeec'>OCA\\Files_Sharing\\Controller\\RemoteController->declineShare(  )</td><td title='/var/www/html/lib/private/AppFramework/Http/Dispatcher.php' bgcolor='#eeeeec'>.../Dispatcher.php<b>:</b>217</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>0.2165</td><td bgcolor='#eeeeec' align='right'>8841408</td><td bgcolor='#eeeeec'>OCA\\Files_Sharing\\External\\Manager->declineShare(  )</td><td title='/var/www/html/apps/files_sharing/lib/Controller/RemoteController.php' bgcolor='#eeeeec'>.../RemoteController.php<b>:</b>102</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>9</td><td bgcolor='#eeeeec' align='center'>0.2171</td><td bgcolor='#eeeeec' align='right'>8869248</td><td bgcolor='#eeeeec'>OCA\\Files_Sharing\\External\\Manager->writeShareToDb(  )</td><td title='/var/www/html/apps/files_sharing/lib/External/Manager.php' bgcolor='#eeeeec'>.../Manager.php<b>:</b>401</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>10</td><td bgcolor='#eeeeec' align='center'>0.2171</td><td bgcolor='#eeeeec' align='right'>8871648</td><td bgcolor='#eeeeec'>OC\\DB\\PreparedStatement->execute(  )</td><td title='/var/www/html/apps/files_sharing/lib/External/Manager.php' bgcolor='#eeeeec'>.../Manager.php<b>:</b>221</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>11</td><td bgcolor='#eeeeec' align='center'>0.2171</td><td bgcolor='#eeeeec' align='right'>8871704</td><td bgcolor='#eeeeec'>Doctrine\\DBAL\\Statement->execute(  )</td><td title='/var/www/html/lib/private/DB/PreparedStatement.php' bgcolor='#eeeeec'>.../PreparedStatement.php<b>:</b>87</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>12</td><td bgcolor='#eeeeec' align='center'>0.2171</td><td bgcolor='#eeeeec' align='right'>8879696</td><td bgcolor='#eeeeec'>Doctrine\\DBAL\\Driver\\PDO\\Statement->execute(  )</td><td title='/var/www/html/3rdparty/doctrine/dbal/src/Statement.php' bgcolor='#eeeeec'>.../Statement.php<b>:</b>175</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>13</td><td bgcolor='#eeeeec' align='center'>0.2171</td><td bgcolor='#eeeeec' align='right'>8879696</td><td bgcolor='#eeeeec'><a href='http://www.php.net/PDOStatement.execute' target='_new'>execute</a>\n(  )</td><td title='/var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php' bgcolor='#eeeeec'>.../Statement.php<b>:</b>82</td></tr>\n",
              "__class__": "PDOException"
            }
          ]
        },
        {
          "file": "/var/www/html/3rdparty/doctrine/dbal/src/Statement.php",
          "line": 175,
          "function": "execute",
          "class": "Doctrine\\DBAL\\Driver\\PDO\\Statement",
          "type": "->",
          "args": [
            [
              "https://nextcloud.local.dev.bitgrid.net/",
              "Iw6MQuHIzsUFLzF",
              "",
              "/dfgdg",
              "user1",
              "And 7 more entries, set log level to debug to see all entries"
            ]
          ]
        },
        {
          "file": "/var/www/html/lib/private/DB/PreparedStatement.php",
          "line": 87,
          "function": "execute",
          "class": "Doctrine\\DBAL\\Statement",
          "type": "->",
          "args": [
            [
              "https://nextcloud.local.dev.bitgrid.net/",
              "Iw6MQuHIzsUFLzF",
              "",
              "/dfgdg",
              "user1",
              "And 7 more entries, set log level to debug to see all entries"
            ]
          ]
        },
        {
          "file": "/var/www/html/apps/files_sharing/lib/External/Manager.php",
          "line": 221,
          "function": "execute",
          "class": "OC\\DB\\PreparedStatement",
          "type": "->",
          "args": [
            [
              "https://nextcloud.local.dev.bitgrid.net/",
              "Iw6MQuHIzsUFLzF",
              "",
              "/dfgdg",
              "user1",
              "And 7 more entries, set log level to debug to see all entries"
            ]
          ]
        },
        {
          "file": "/var/www/html/apps/files_sharing/lib/External/Manager.php",
          "line": 401,
          "function": "writeShareToDb",
          "class": "OCA\\Files_Sharing\\External\\Manager",
          "type": "->",
          "args": [
            "https://nextcloud.local.dev.bitgrid.net/",
            "Iw6MQuHIzsUFLzF",
            "",
            "/dfgdg",
            "user1",
            "admin",
            "{{TemporaryMountPointName#/dfgdg}}",
            "964931522bcd01381cddc4984b4e604b",
            0,
            "56",
            4,
            "1"
          ]
        },
        {
          "file": "/var/www/html/apps/files_sharing/lib/Controller/RemoteController.php",
          "line": 102,
          "function": "declineShare",
          "class": "OCA\\Files_Sharing\\External\\Manager",
          "type": "->",
          "args": [
            4
          ]
        },
        {
          "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
          "line": 217,
          "function": "declineShare",
          "class": "OCA\\Files_Sharing\\Controller\\RemoteController",
          "type": "->",
          "args": [
            4
          ]
        },
        {
          "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
          "line": 126,
          "function": "executeController",
          "class": "OC\\AppFramework\\Http\\Dispatcher",
          "type": "->",
          "args": [
            {
              "__class__": "OCA\\Files_Sharing\\Controller\\RemoteController"
            },
            "declineShare"
          ]
        },
        {
          "file": "/var/www/html/lib/private/AppFramework/App.php",
          "line": 157,
          "function": "dispatch",
          "class": "OC\\AppFramework\\Http\\Dispatcher",
          "type": "->",
          "args": [
            {
              "__class__": "OCA\\Files_Sharing\\Controller\\RemoteController"
            },
            "declineShare"
          ]
        },
        {
          "file": "/var/www/html/lib/private/Route/Router.php",
          "line": 301,
          "function": "main",
          "class": "OC\\AppFramework\\App",
          "type": "::",
          "args": [
            "OCA\\Files_Sharing\\Controller\\RemoteController",
            "declineShare",
            {
              "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
            },
            {
              "id": "4",
              "_route": "ocs.files_sharing.Remote.declineShare"
            }
          ]
        },
        {
          "file": "/var/www/html/ocs/v1.php",
          "line": 62,
          "function": "match",
          "class": "OC\\Route\\Router",
          "type": "->",
          "args": [
            "/ocsapp/apps/files_sharing/api/v1/remote_shares/pending/4"
          ]
        },
        {
          "file": "/var/www/html/ocs/v2.php",
          "line": 23,
          "args": [
            "/var/www/html/ocs/v1.php"
          ],
          "function": "require_once"
        }
      ],
      "File": "/var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Exception.php",
      "Line": 26,
      "Previous": {
        "Exception": "PDOException",
        "Message": "SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'admin-964931522bcd01381cddc4984b4e604b' for key 'sh_external_mp'",
        "Code": "23000",
        "Trace": [
          {
            "file": "/var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php",
            "line": 82,
            "function": "execute",
            "class": "PDOStatement",
            "type": "->",
            "args": [
              [
                "https://nextcloud.local.dev.bitgrid.net/",
                "Iw6MQuHIzsUFLzF",
                "",
                "/dfgdg",
                "user1",
                "And 7 more entries, set log level to debug to see all entries"
              ]
            ]
          },
          {
            "file": "/var/www/html/3rdparty/doctrine/dbal/src/Statement.php",
            "line": 175,
            "function": "execute",
            "class": "Doctrine\\DBAL\\Driver\\PDO\\Statement",
            "type": "->",
            "args": [
              [
                "https://nextcloud.local.dev.bitgrid.net/",
                "Iw6MQuHIzsUFLzF",
                "",
                "/dfgdg",
                "user1",
                "And 7 more entries, set log level to debug to see all entries"
              ]
            ]
          },
          {
            "file": "/var/www/html/lib/private/DB/PreparedStatement.php",
            "line": 87,
            "function": "execute",
            "class": "Doctrine\\DBAL\\Statement",
            "type": "->",
            "args": [
              [
                "https://nextcloud.local.dev.bitgrid.net/",
                "Iw6MQuHIzsUFLzF",
                "",
                "/dfgdg",
                "user1",
                "And 7 more entries, set log level to debug to see all entries"
              ]
            ]
          },
          {
            "file": "/var/www/html/apps/files_sharing/lib/External/Manager.php",
            "line": 221,
            "function": "execute",
            "class": "OC\\DB\\PreparedStatement",
            "type": "->",
            "args": [
              [
                "https://nextcloud.local.dev.bitgrid.net/",
                "Iw6MQuHIzsUFLzF",
                "",
                "/dfgdg",
                "user1",
                "And 7 more entries, set log level to debug to see all entries"
              ]
            ]
          },
          {
            "file": "/var/www/html/apps/files_sharing/lib/External/Manager.php",
            "line": 401,
            "function": "writeShareToDb",
            "class": "OCA\\Files_Sharing\\External\\Manager",
            "type": "->",
            "args": [
              "https://nextcloud.local.dev.bitgrid.net/",
              "Iw6MQuHIzsUFLzF",
              "",
              "/dfgdg",
              "user1",
              "admin",
              "{{TemporaryMountPointName#/dfgdg}}",
              "964931522bcd01381cddc4984b4e604b",
              0,
              "56",
              4,
              "1"
            ]
          },
          {
            "file": "/var/www/html/apps/files_sharing/lib/Controller/RemoteController.php",
            "line": 102,
            "function": "declineShare",
            "class": "OCA\\Files_Sharing\\External\\Manager",
            "type": "->",
            "args": [
              4
            ]
          },
          {
            "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
            "line": 217,
            "function": "declineShare",
            "class": "OCA\\Files_Sharing\\Controller\\RemoteController",
            "type": "->",
            "args": [
              4
            ]
          },
          {
            "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
            "line": 126,
            "function": "executeController",
            "class": "OC\\AppFramework\\Http\\Dispatcher",
            "type": "->",
            "args": [
              {
                "__class__": "OCA\\Files_Sharing\\Controller\\RemoteController"
              },
              "declineShare"
            ]
          },
          {
            "file": "/var/www/html/lib/private/AppFramework/App.php",
            "line": 157,
            "function": "dispatch",
            "class": "OC\\AppFramework\\Http\\Dispatcher",
            "type": "->",
            "args": [
              {
                "__class__": "OCA\\Files_Sharing\\Controller\\RemoteController"
              },
              "declineShare"
            ]
          },
          {
            "file": "/var/www/html/lib/private/Route/Router.php",
            "line": 301,
            "function": "main",
            "class": "OC\\AppFramework\\App",
            "type": "::",
            "args": [
              "OCA\\Files_Sharing\\Controller\\RemoteController",
              "declineShare",
              {
                "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
              },
              {
                "id": "4",
                "_route": "ocs.files_sharing.Remote.declineShare"
              }
            ]
          },
          {
            "file": "/var/www/html/ocs/v1.php",
            "line": 62,
            "function": "match",
            "class": "OC\\Route\\Router",
            "type": "->",
            "args": [
              "/ocsapp/apps/files_sharing/api/v1/remote_shares/pending/4"
            ]
          },
          {
            "file": "/var/www/html/ocs/v2.php",
            "line": 23,
            "args": [
              "/var/www/html/ocs/v1.php"
            ],
            "function": "require_once"
          }
        ],
        "File": "/var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php",
        "Line": 82
      }
    },
    "CustomMessage": "--"
  }
}
```

**Comment by juliushaertl** [comment]
Ok, seems to be only an issue if the recipient group id and user id of the accepting user matches (both admin in my case), since then the user/mountpoint unique key does conflict with the existing parent entry:

```
MariaDB [nextcloud]> select id, parent, share_type, owner, user, mountpoint, accepted from oc_share_external;
+----+--------+------------+-------+-------+------------------------------------+----------+
| id | parent | share_type | owner | user  | mountpoint                         | accepted |
+----+--------+------------+-------+-------+------------------------------------+----------+
|  4 |     -1 |          1 | user1 | admin | {{TemporaryMountPointName#/dfgdg}} |        0 |
|  7 |     -1 |          1 | admin | admin | {{TemporaryMountPointName#/Media}} |        0 |
|  9 |      7 |          1 | admin | admin | /Media                             |        1 |
| 10 |     -1 |          1 | admin | bgm   | {{TemporaryMountPointName#/Talk}}  |        0 |
| 11 |     10 |          1 | admin | user1 | {{TemporaryMountPointName#/Talk}}  |        0 |
+----+--------+------------+-------+-------+------------------------------------+----------+
```

Fine to file later for a follow up from my perspective :+1:

**Review by artonge — COMMENTED** [review]
The frontend looks good. But I think I miss to mutch context for the PHP part. Especially with the sub and parent share part.

Also, I tried locally, but it did not work as I expected. I can see the share in "pending shares" behind the notification, but if I click on the notification's cross, the remote share disappears after a reload.

Screenshot 2021-07-12 at 18-25-24 Pending shares - Nextcloud

**Comment by kesselb** [comment]
The query to select the pending shares is broken if the (receiving) user is in more than one group.

**Comment by PVince81** [comment]
- [ ] test with federated shares added through public link
- [ ] test with federated shares added when no notification app is enabled

@artonge can you confirm that this is how you tested it ? I had notifications app enabled so I never see that popup dialog

**Comment by PVince81** [comment]
@kesselb I've pushed a fix for the multiple user group issues, thanks for spotting.

I'll rebase once I address the other reported JS issue

**Comment by artonge** [comment]
> @artonge can you confirm that this is how you tested it ? I had notifications app enabled so I never see that popup dialog

Indeed, the notifications app helps, and it works as intended now :)

File: apps/files_sharing/js/sharedfilelist.js [hunk 3]
```diff
@@ -311,12 +337,29 @@
...
+								file.path = '/'
+							}
+							file.remoteId = share.remote_id
+							file.shareOwnerId = share.owner
+						}
+
+						if (!file.type) {
+							// pending shares usually have no type, so default to showing a directory icon
+							file.mimetype = 'dir-shared'
+						}
```
[the remark this answers is not in the document]
Comment (PVince81) [reply apps/files_sharing/js/sharedfilelist.js:361]: good point, it seems both should be defined: https://github.com/nextcloud/server/blob/enh/23769/accept-decline-fed-sharing-ui/apps/files_sharing/lib/Controller/RemoteController.php#L127

and "type" is more the share type than mime type

[the remark this answers is not in the document]
Comment (PVince81) [reply apps/files_sharing/js/sharedfilelist.js:361]: as far as I can see here, pending shares have neither mimetype nor type:
image

but now I see why your proposal makes sense, for consistency.
so let's go with that

[the remark this answers is not in the document]
Comment (PVince81) [reply apps/files_sharing/js/sharedfilelist.js]: adjusted now

**Comment by PVince81** [comment]
rebased and fixed the JS based on comments

next up: have a look at the test cases in https://github.com/nextcloud/server/pull/27751#issuecomment-879206836 and decide whether they are worth fixing here or separate

**Comment by PVince81** [comment]
- [ ] BUG: with notifications app off, the mount point is mangled:

1. disable notifications app
2. on instance B share with a group on instance A (with remote group sharing enabled on both)
3. on instance A go to the files app
4. a popup dialog appears, but don't accept the share
5. go to "pending shares"
6. accept it here
7. go to "shared with you"

Expected result: properly accepted share
Actual result: mangled name:
image

likely due to the temporary mountpoint string handling.

not sure if this is related to this PR or another issue, but I'll have a quick look still

**Comment by PVince81** [comment]
Seems https://github.com/nextcloud/server/pull/27751#issuecomment-882885947 was due to an uncovered scenario. I've added it to the tests and fixed it.

All should work fine now! Please re-review!

File: apps/federatedfilesharing/lib/OCM/CloudFederationProviderFiles.php [hunk 4]
```diff
@@ -250,7 +250,8 @@ public function shareReceived(ICloudFederationShare $share) {
 				\OC::$server->getGroupManager(),
 				\OC::$server->getUserManager(),
 				$shareWith,
-				\OC::$server->query(IEventDispatcher::class)
+				\OC::$server->query(IEventDispatcher::class),
+				\OC::$server->getLogger()
```
Comment (CarlSchwan) [inline apps/federatedfilesharing/lib/OCM/CloudFederationProviderFiles.php:254]:
```suggestion
				\OC::$server->get(LoggerInterface::class)
```

Also need to add the use statement

File: apps/files_sharing/lib/AppInfo/Application.php [hunk 5]
```diff
@@ -98,7 +98,8 @@ public function __construct(array $urlParams = []) {
 				$server->getGroupManager(),
 				$server->getUserManager(),
 				$uid,
-				$server->query(IEventDispatcher::class)
+				$server->query(IEventDispatcher::class),
+				$server->getLogger()
```
Comment (CarlSchwan) [inline apps/files_sharing/lib/AppInfo/Application.php:102]:
```suggestion
				$server->get(LoggerInterface::class)
```

File: apps/files_sharing/lib/Hooks.php [hunk 6]
```diff
@@ -43,7 +43,8 @@ public static function deleteUser($params) {
 			\OC::$server->getGroupManager(),
 			\OC::$server->getUserManager(),
 			$params['uid'],
-			\OC::$server->query(IEventDispatcher::class)
+			\OC::$server->query(IEventDispatcher::class),
+			\OC::$server->getLogger()
```
Comment (CarlSchwan) [inline apps/files_sharing/lib/Hooks.php:47]:
```suggestion
			\OC::$server->get(LoggerInterface::class)
```

File: apps/files_sharing/lib/External/Manager.php [hunk 7]
```diff
@@ -44,6 +46,7 @@
 use OCP\Http\Client\IClientService;
 use OCP\IDBConnection;
 use OCP\IGroupManager;
+use OCP\ILogger;
```
Comment (CarlSchwan) [inline apps/files_sharing/lib/External/Manager.php:49]:
```suggestion
use use Psr\Log\LoggerInterface;
```

File: apps/files_sharing/lib/External/Manager.php [hunk 8]
```diff
@@ -89,18 +92,24 @@ class Manager {
...
-								IClientService $clientService,
-								IManager $notificationManager,
-								IDiscoveryService $discoveryService,
-								ICloudFederationProviderManager $cloudFederationProviderManager,
-								ICloudFederationFactory $cloudFederationFactory,
-								IGroupManager $groupManager,
-								IUserManager $userManager,
-								?string $uid,
-								IEventDispatcher $eventDispatcher) {
+	/** @var ILogger */
```
Comment (CarlSchwan) [inline apps/files_sharing/lib/External/Manager.php:95]:
```suggestion
	/** @var LoggerInterface */
```

File: apps/files_sharing/lib/External/Manager.php [hunk 9]
```diff
@@ -89,18 +92,24 @@ class Manager {
...
+		IClientService $clientService,
+		IManager $notificationManager,
+		IDiscoveryService $discoveryService,
+		ICloudFederationProviderManager $cloudFederationProviderManager,
+		ICloudFederationFactory $cloudFederationFactory,
+		IGroupManager $groupManager,
+		IUserManager $userManager,
+		?string $uid,
+		IEventDispatcher $eventDispatcher,
+		ILogger $logger
```
Comment (CarlSchwan) [inline apps/files_sharing/lib/External/Manager.php:111]:
```suggestion
		LoggerInterface $logger
```

File: apps/files_sharing/lib/External/Manager.php [hunk 10]
```diff
@@ -268,21 +324,46 @@ public function acceptShare($id) {
...
+						$acceptShare = $this->connection->prepare('
+						UPDATE `*PREFIX*share_external`
+						SET `accepted` = ?,
+							`mountpoint` = ?,
+							`mountpoint_hash` = ?
+						WHERE `id` = ? AND `user` = ?');
+						$acceptShare->execute([1, $mountPoint, $hash, $subshare['id'], $this->uid]);
+						$result = true;
+					} catch (Exception $e) {
+						$this->logger->logException($e);
```
Comment (CarlSchwan) [inline apps/files_sharing/lib/External/Manager.php:346]:
```suggestion
						$this->logger->emergency('Couldn't update share', ['exception' => $e]);
```

File: apps/files_sharing/lib/External/Manager.php [hunk 11]
```diff
@@ -268,21 +324,46 @@ public function acceptShare($id) {
...
+							$share['name'],
+							$share['owner'],
+							$this->uid,
+							$mountPoint, $hash, 1,
+							$share['remote_id'],
+							$id,
+							$share['share_type']);
+						$result = true;
+					} catch (Exception $e) {
+						$this->logger->logException($e);
```
Comment (CarlSchwan) [inline apps/files_sharing/lib/External/Manager.php:364]:
```suggestion
						$this->logger->emergency('Couldn't create share', ['exception' => $e]);
```

File: apps/files_sharing/lib/External/Manager.php [hunk 12]
```diff
@@ -318,23 +399,42 @@ public function declineShare($id) {
...
+			} else {
+				$subshare = $this->fetchUserShare($id, $this->uid);
+			}
+
+			if ($subshare !== null) {
+				try {
+					$this->updateAccepted((int)$subshare['id'], false);
+					$result = true;
+				} catch (Exception $e) {
+					$this->logger->logException($e);
```
Comment (CarlSchwan) [inline apps/files_sharing/lib/External/Manager.php:415]:
```suggestion
					$this->logger->emergency('Couldn't update share', ['exception' => $e]);
```

File: apps/files_sharing/lib/External/Manager.php [hunk 13]
```diff
@@ -318,23 +399,42 @@ public function declineShare($id) {
...
+						$this->uid,
+						$share['mountpoint'],
+						$share['mountpoint_hash'],
+						0,
+						$share['remote_id'],
+						$id,
+						$share['share_type']);
+					$result = true;
+				} catch (Exception $e) {
+					$this->logger->logException($e);
```
Comment (CarlSchwan) [inline apps/files_sharing/lib/External/Manager.php:435]:
```suggestion
					$this->logger->emergency('Couldn't create share', ['exception' => $e]);
```

File: apps/files_sharing/lib/External/Manager.php [hunk 14]
```diff
@@ -519,22 +623,18 @@ public function removeShare($mountPoint): bool {
...
-					SET `accepted` = ?
-					WHERE `id` = ?');
-				$updateResult = $query->execute([0, (int)$share['id']]);
-				$updateResult->closeCursor();
+				$this->updateAccepted((int)$share['id'], false);
 			}
 
 			$this->removeReShares($id);
 		} catch (\Doctrine\DBAL\Exception $ex) {
+			$this->logger->logException($ex);
```
Comment (CarlSchwan) [inline apps/files_sharing/lib/External/Manager.php:637]:
```suggestion
			$this->logger->emergency('Couldn't update share', ['exception' => $ex]);
```

File: apps/files_sharing/lib/External/Manager.php [hunk 15]
```diff
@@ -588,7 +694,19 @@ public function removeUserShares($uid): bool {
...
+				// TODO: batch this with query builder
+				$query = $this->connection->prepare('
+					DELETE FROM `*PREFIX*share_external`
+					WHERE `parent` = ?
+				');
+				$deleteResult = $query->execute([$deletedId]);
+				$deleteResult->closeCursor();
+			}
 		} catch (\Doctrine\DBAL\Exception $ex) {
+			$this->logger->logException($ex);
```
Comment (CarlSchwan) [inline apps/files_sharing/lib/External/Manager.php:709]:
```suggestion
				$this->logger->emergency('Couldn't get shares', ['exception' => $ex]);
```

File: apps/files_sharing/lib/External/Manager.php [hunk 16]
```diff
@@ -629,23 +747,44 @@ private function getShares($accepted) {
...
+			});
+
+			if (!is_null($accepted)) {
+				$shares = array_filter($shares, function ($share) use ($accepted) {
+					return (bool)$share['accepted'] === $accepted;
+				});
+			}
+			return array_values($shares);
 		} catch (\Doctrine\DBAL\Exception $e) {
+			$this->logger->logException($e);
```
Comment (CarlSchwan) [inline apps/files_sharing/lib/External/Manager.php:787]:
```suggestion
			$this->logger->emergency('Error when retriving shares', ['exception' => $e]);
```

File: apps/federatedfilesharing/lib/OCM/CloudFederationProviderFiles.php (hunk 4 above)
Comment (PVince81) [reply apps/federatedfilesharing/lib/OCM/CloudFederationProviderFiles.php:254]: cool, thanks for the hints.
I wasn't aware that it's possible to pass an exception in the LoggerInterface

File: apps/files_sharing/tests/External/ManagerTest.php [hunk 17]
```diff
@@ -112,6 +114,9 @@ protected function setUp(): void {
 			->method('search')
 			->willReturn([]);
 
+		$logger = $this->createMock(ILogger::class);
+		$logger->expects($this->never())->method('logException');
```
Comment (PVince81) [inline apps/files_sharing/tests/External/ManagerTest.php:118]: note to self: will also need to adjust this one

**Comment by PVince81** [comment]
one does not simply commit suggestions :sweat_smile: 
```
9) OCA\Files_Sharing\Tests\External\ManagerTest::testDeclineGroupShareAgainThroughMountPoint
ParseError: syntax error, unexpected 'use' (T_USE), expecting identifier (T_STRING) or function (T_FUNCTION) or const (T_CONST) or \\ (T_NS_SEPARATOR)
```

I'll fix it

**Comment by PVince81** [comment]
I've fixed/adjusted the logger interface, also in the test. The unit tests pass locally for me.

Ready for review again, thanks. :smile:

File: apps/files_sharing/lib/External/Manager.php [hunk 18]
```diff
@@ -588,7 +694,19 @@ public function removeUserShares($uid): bool {
 			');
 			$deleteResult = $query->execute([$uid]);
 			$deleteResult->closeCursor();
+
+			// delete sub-entries from deleted parents
+			foreach ($deletedGroupShares as $deletedId) {
+				// TODO: batch this with query builder
+				$query = $this->connection->prepare('
+					DELETE FROM `*PREFIX*share_external`
+					WHERE `parent` = ?
```
Comment (PVince81) [inline apps/files_sharing/lib/External/Manager.php:703]: add "$this->uid" to properly delete it

double check this

File: apps/files_sharing/tests/External/ManagerTest.php [hunk 19]
```diff
@@ -318,19 +392,211 @@ public function testAddShare() {
...
+
+		// decline again, this keeps the sub-share
+		$this->assertTrue($this->manager->declineShare($groupShare['id']));
+		$this->verifyDeclinedGroupShare($shareData, '/SharedFolder');
+
+		// this will return sub-entries
+		$openShares = $this->manager->getOpenShares();
+
+		// accept through sub-share
+		$this->assertTrue($this->manager->acceptShare($groupShare['id']));
```
Comment (PVince81) [inline apps/files_sharing/tests/External/ManagerTest.php:467]: use $openShares for second accept

File: apps/files_sharing/tests/External/ManagerTest.php [hunk 20]
```diff
@@ -318,19 +392,211 @@ public function testAddShare() {
...
+		$this->verifyAcceptedGroupShare($shareData);
+
+		// decline again, this keeps the sub-share
+		$this->assertTrue($this->manager->declineShare($groupShare['id']));
+		$this->verifyDeclinedGroupShare($shareData, '/SharedFolder');
+
+		// this will return sub-entries
+		$openShares = $this->manager->getOpenShares();
+
+		// accept through sub-share
```
Comment (PVince81) [inline apps/files_sharing/tests/External/ManagerTest.php:466]: accept through group share

**Comment by PVince81** [comment]
resolved conflicts and fixed route problems and missing imports for LoggerInterface

it works again.

however, while going through the code with @artonge we found some additional issues to fix

**Comment by PVince81** [comment]
I've now fixed user deletion and also added a new method for group deletion, mostly for the sake of tests: https://github.com/nextcloud/server/pull/27751/commits/f6f2f63016e8183c7054fb28007a7d51666d8475

User deletion should now be properly limited to its share type and group subshares, and so is group deletion.

Note: I didn't add a hook yet for group deletion as it seems it will be more complicated and I didn't want to dig further in code unrelated to the task at hand.

**Comment by PVince81** [comment]
@artonge can you review again ?

**Review by artonge — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by PVince81** [comment]
thanks a lot everyone! what a journey...
