### PR TITLE
Respect empty `expiryDate` value in server

### LINKED ISSUE #44219: [Bug]: When creating email share expiry date is set by default without enforcement
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When creating an email share with the option "Set expiration date" unchecked and "Enforce expiry date" unchecked, the default expiry date is set anyway.
You can see it by clicking "customize link".

This is how it looks like when creating the email share:
grafik

This is how it looks like when customizing the share afterwards:
grafik

After unchecking "Set expiration date" and updating share again, the values stays ok.

### Steps to reproduce

1. Configure the Sharing options like this.
    - [x] Allow users to share via link end emails
    - [x] Always ask for a password
    - [x] Enforce password protection
    - [x] Set default expiry date -> Expire after 30 day(s)
    - [ ] Enforce expiry date
2. Create an email share and uncheck the option "Set expiration date"
3. Click on "customize link" and see that it's wrong.
4. Uncheck "Set expiration date" again and update the link.
5. Click on "customize link" again and see that now it worked how it should work in first place.

### Expected behavior

If the option "Set expiration date" is unchecked when creating the share, it should be stored correctly in the database like this and not only at the second updating

### Nextcloud Server version

27.1.7 28.0.3

### PR DESCRIPTION
**Pull request by nfebe**
If `expireDate` is an empty string and not `null` then the server should not set a default.

Resolves : https://github.com/nextcloud/server/issues/44219

### CODE REVIEW

**Comment by Fenn-CS** [comment]
Related changes : https://github.com/nextcloud/server/pull/44912

File: lib/private/Share20/Manager.php [hunk 1]
```diff
@@ -487,25 +417,6 @@ protected function validateExpirationDateLink(IShare $share) {
 			}
 		}
 
-		// If expiredate is empty set a default one if there is a default
```
Comment (nickvergessen) [inline lib/private/Share20/Manager.php:490]: but you are removing the default functionality?

Comment (Fenn-CS) [reply lib/private/Share20/Manager.php:490]: Yes :)... Since the users now have the opportunity to modify this settings before a share is created. `i.e` the user can see on the share creation menu, that an expiry date is required and can either allow the default or remove if not enforced.

Leaving this default functionality means, we always force shares to have expiry dates even when that's not the users intention.

Comment (nickvergessen) [reply lib/private/Share20/Manager.php:490]: The problem is that currently existing clients and app might rely on the default and not populate it via the UI or send it with each request.
So this is a breaking change that is impossible to discover and will lead to a lot of shares not expiring although they should.

Comment (Fenn-CS) [reply lib/private/Share20/Manager.php:490]: I see. This breaking change is inevitable if we would solve https://github.com/nextcloud/server/issues/44219 though.

I am not sure but perhaps I could introduce checks for clients/app calls.

Another though is that `Manager` class is only part of the private API and maybe all we need to do is make sure the apps we maintain that uses the non public share interface are updated?

Comment (nickvergessen) [reply lib/private/Share20/Manager.php:490]: > Another though is that Manager class is only part of the private API and maybe all we need to do is make sure the apps we maintain that uses the non public share interface are updated?

I meant apps like Android, iOS and our Desktop Client:
- https://github.com/nextcloud/server/blob/490f545006024ad982c801b5c986ff8d03826821/apps/files_sharing/lib/Controller/ShareAPIController.php#L574
- https://github.com/nextcloud/server/blob/490f545006024ad982c801b5c986ff8d03826821/apps/files_sharing/lib/Controller/ShareAPIController.php#L648-L656

That being said, the update also supports it, but basically you need to set it to `''` (empty string) not null when updating a share and removing a expiration date.

Seems to work when updating, just not when creating, as the check is always executed then.
So instead of tampering with `validateExpirationDateInternal` like this, I would try to get the information into the share object that no expirationDate was sent and in https://github.com/nextcloud/server/blob/ec5133b739eabc76271789504b4dbb91a534f552/lib/private/Share20/Manager.php#L423 instead of only checking `$expirationDate === null` you also check whether it was sent with the empty string, and only set the default date when it was not sent as empty string.

**Review by nfebe — COMMENTED** [review]
Backtracked on the initial radical and breaking approach where, we allow defaults to be set entire by the client.

Propose new approach: 

- If client sends empty string, then do not set any defaults
- Set defaults it no `expireDate` is sent
- Set default if `expireDate` sent is null

File: apps/files_sharing/lib/Controller/ShareAPIController.php [hunk 2]
```diff
@@ -646,12 +646,16 @@ public function createShare(
...
+		if ($expireDate !== null) {
+			if ($expireDate !== '') {
+				try {
+					$expireDateTime = $this->parseDate($expireDate);
+					$share->setExpirationDate($expireDateTime);
+				} catch (\Exception $e) {
+					throw new OCSNotFoundException($this->l->t('Invalid date, date format must be YYYY-MM-DD'));
+				}
+			} else {
+				$share->setExpirationDate('');
```
Comment (Fenn-CS) [inline apps/files_sharing/lib/Controller/ShareAPIController.php:658]: Since, `null` is the basis for setting default expiration date in the share manager for new shares, we just can't set this to null here.

Comment (Fenn-CS) [inline apps/files_sharing/lib/Controller/ShareAPIController.php:658]:
```suggestion
				$share->setExpirationDate(null);
```

Since, `null` is the basis for setting default expiration date in the share manager for new shares, we just can't set this to null here.


But can be done much later in `validateExpirationDateInternal` and `validateExpirationDateLink`

File: lib/public/Share/IShare.php [hunk 3]
```diff
@@ -385,11 +385,11 @@ public function getNote();
 	/**
 	 * Set the expiration date
 	 *
-	 * @param null|\DateTime $expireDate
+	 * @param \DateTime|string|null $expireDate
```
Comment (provokateurin) [inline lib/public/Share/IShare.php:388]:
```suggestion
	 * @param \DateTime|''|null $expireDate
```
To avoid any other string than the empty string. I'm questioning a bit if this couldn't be solved differently because two "null" values are not great

File: lib/private/Share20/Manager.php [hunk 4]
```diff
@@ -389,6 +337,13 @@ protected function validateExpirationDateInternal(IShare $share) {
 
 		$expirationDate = $share->getExpirationDate();
 
+		// If $expirationDate is an empty string, then the client unset expiration  date
+		// Hence no validation required
```
Comment (nickvergessen) [inline lib/private/Share20/Manager.php:341]: This is not correct. If the enforcement is enabled you still have to.

File: lib/private/Share20/Manager.php [hunk 5]
```diff
@@ -475,6 +430,13 @@ protected function validateExpirationDateInternal(IShare $share) {
 	protected function validateExpirationDateLink(IShare $share) {
 		$expirationDate = $share->getExpirationDate();
 
+		// If $expirationDate is an empty string, then the client unset expiration  date
+		// Hence no validation required
```
Comment (nickvergessen) [inline lib/private/Share20/Manager.php:434]: Same here

File: lib/public/Share/IShare.php (hunk 3 above)
Comment (nickvergessen) [reply lib/public/Share/IShare.php:388]: Which is why i would have added another prop for this. Also helps to improve the enforcement handling above

**Review by nickvergessen — DISMISSED** [review]

File: lib/private/Share20/Share.php [hunk 6]
```diff
@@ -41,61 +41,34 @@
...
+	private ?IAttributes $attributes = null;
+	private ?int $status = null;
+	private ?string $note = null;
+	private ?\DateTime $expireDate = null;
+	private bool $overwriteFalsyExpirationDate = true;
+	private ?string $password = null;
 	private ?\DateTimeInterface $passwordExpirationTime = null;
-	/** @var bool */
-	private $sendPasswordByTalk = false;
-	/** @var string */
```
Comment (come-nc) [inline lib/private/Share20/Share.php:81]: You’re gonna get trouble with all this strong typing. I tried it in the psalm update PR and typing in this class is inconsistent between props and methods. Main problem is the class can be used to represent an incomplete share while some code path expect it to be complete.

I’d advice not touching the typing or do it in a separate PR which fixes the problems.

**Review by come-nc — COMMENTED** [review]
I have to say I do not understand why the share object has to carry the information of whether a default date was used, it should simply contain the date. So this new method in IShare is not logical to me.

Code around this sounds quite convoluted.

File: apps/files_sharing/lib/Controller/ShareAPIController.php [hunk 7]
```diff
@@ -646,12 +646,17 @@ public function createShare(
...
-				$share->setExpirationDate($expireDateTime);
-			} catch (\Exception $e) {
-				throw new OCSNotFoundException($this->l->t('Invalid date, date format must be YYYY-MM-DD'));
+		if ($expireDate !== null) {
+			if ($expireDate !== '') {
+				try {
+					$expireDateTime = $this->parseDate($expireDate);
+					$share->setExpirationDate($expireDateTime);
+				} catch (\Exception $e) {
+					throw new OCSNotFoundException($this->l->t('Invalid date, date format must be YYYY-MM-DD'));
```
[the remark this answers is not in the document]
Comment (come-nc) [reply apps/files_sharing/lib/Controller/ShareAPIController.php:655]: `	 * @throws OCSNotFoundException Creating the share failed
`
Apparently not :thinking: 
This API is really weird.

**Comment by come-nc** [comment]
> I have to say I do not understand why the share object has to carry the information of whether a default date was used, it should simply contain the date. So this new method in IShare is not logical to me.
> 
> Code around this sounds quite convoluted.

Ok I’m starting to understand, the share object is used both to convey the parameter for creation and the final created object, this is quite bad.
So I do not see a better way than what you did for storing the info without a bigger refactor.
I do not understand the name `setOverwriteFalsyExpirationDate` though.
Why not `setNoExpirationDate(bool)` ?

File: lib/public/Share/IShare.php [hunk 8]
```diff
@@ -385,20 +385,38 @@ public function getNote();
...
 	public function getExpirationDate();
 
+	/**
+	 * Set overwrite flag for falsy expiry date vavlues
+	 *
+	 * @param bool $overwriteFalsyExpirationDate
+	 * @return \OCP\Share\IShare The modified object
+	 * @since 27.0.0
+	 */
+	public function setOverwriteFalsyExpirationDate(bool $overwriteFalsyExpirationDate);
```
Comment (nickvergessen) [inline lib/public/Share/IShare.php:409]:
```suggestion
	public function setNoExpirationDate(bool $noExpirationDate);
```
etc

**Comment by Fenn-CS** [comment]
> I do not understand the name setOverwriteFalsyExpirationDate though.
> Why not setNoExpirationDate(bool) ?

The method name `setOverwriteFalsyExpirationDate` was chosen for its explicitness in indicating that the method controls whether to overwrite falsy values, such as `null` or an empty string (`''`), in the `expireDate` field. 

Because, that is exactly what the method and its corresponding property is currently used for in the code, we use it to decide if we want to **overwrite** the value of `$expireDate` when it has *falsy* values (`null`, `''`, `0'`, etc) ...

However, following your suggestion, I have changed the name to `setNoExpirationDate(bool)` as it might be easier especially for non-native English speakers to grab.

File: lib/private/Share20/Manager.php [hunk 9]
```diff
@@ -474,6 +429,13 @@ protected function validateExpirationDateInternal(IShare $share) {
 	 */
 	protected function validateExpirationDateLink(IShare $share) {
```
[the remark this answers is not in the document]
Comment (Fenn-CS) [reply lib/private/Share20/Manager.php:430]: Yes the method is in use.

File: lib/private/Share20/Manager.php [hunk 10]
```diff
@@ -474,6 +429,13 @@ protected function validateExpirationDateInternal(IShare $share) {
...
 		$expirationDate = $share->getExpirationDate();
+		$isEnforced = $this->shareApiLinkDefaultExpireDateEnforced();
+
+		// If $expirationDate is falsy, overwrite flag is false, no expiration is set
+		if(empty($expirationDate) && !$share->getOverwriteFalsyExpirationDate() && !$isEnforced) {
+			$share->setExpirationDate(null);
```
[the remark this answers is not in the document]
Comment (Fenn-CS) [reply lib/private/Share20/Manager.php:436]: Yes because `''` (empty string) value would lead to `DBAL` exceptions when trying to convert a string into value that should be stored on a `nullable` `datetime` field.

File: lib/private/Share20/Share.php (hunk 6 above)
Comment (Fenn-CS) [reply lib/private/Share20/Share.php]: Moved to : https://github.com/nextcloud/server/pull/45156

File: lib/private/Share20/Manager.php [hunk 11]
```diff
@@ -409,17 +375,6 @@ protected function validateExpirationDateInternal(IShare $share) {
...
-			$isEnforced = $this->shareApiRemoteDefaultExpireDateEnforced();
-		} else {
-			$defaultExpireDate = $this->shareApiInternalDefaultExpireDate();
-			$defaultExpireDays = $this->shareApiInternalDefaultExpireDays();
-			$configProp = 'internal_defaultExpDays';
-			$isEnforced = $this->shareApiInternalDefaultExpireDateEnforced();
-		}
 		if ($fullId === null && $expirationDate === null && $defaultExpireDate) {
 			$expirationDate = new \DateTime('now', $this->dateTimeZone->getTimeZone());
 			$expirationDate->setTime(0, 0, 0);
```
[the remark this answers is not in the document]
Comment (Fenn-CS) [reply lib/private/Share20/Manager.php:380]: @come-nc  not clear here please...

File: apps/files_sharing/lib/Controller/ShareAPIController.php (hunk 7 above)
[the remark this answers is not in the document]
Comment (Fenn-CS) [reply apps/files_sharing/lib/Controller/ShareAPIController.php:655]: To avoid more back and forth for something unrelated moved to : https://github.com/nextcloud/server/pull/45157

File: lib/private/Share20/Manager.php (hunk 11 above)
[the remark this answers is not in the document]
Comment (Fenn-CS) [reply lib/private/Share20/Manager.php:380]: Figured.

**Comment by nickvergessen** [comment]
Would really be good to add a new test into https://github.com/nextcloud/server/tree/058b69eef02be9bfa77e9b6a1d12d15f29ac6b0c/build/integration/sharing_features which proves the thing you fixed, so it does not get reverted at some point and no test fails :P

File: apps/files_sharing/lib/Controller/ShareAPIController.php [hunk 12]
```diff
@@ -549,7 +549,8 @@ public function deleteShare(string $id): DataResponse {
 	 * @param string $publicUpload If public uploading is allowed
 	 * @param string $password Password for the share
 	 * @param string|null $sendPasswordByTalk Send the password for the share over Talk
-	 * @param string $expireDate Expiry date of the share using user timezone at 00:00. It means date in UTC timezone will be used.
+	 * @param ?string $expireDate The expiry date of the share in the user's timezone (UTC) at 00:00.
```
Comment (come-nc) [inline apps/files_sharing/lib/Controller/ShareAPIController.php:552]:
```suggestion
	 * @param ?string $expireDate The expiry date of the share in the user's timezone at 00:00.
```
The user’s timezone is not always UTC

File: lib/private/Share20/Manager.php (hunk 10 above)
[the remark this answers is not in the document]
Comment (come-nc) [reply lib/private/Share20/Manager.php:436]: But expirationDate is null or DateTime it cannot be `''` in the share object.

**Comment by come-nc** [comment]
I agree that we need tests for this.

**Comment by blizzz** [comment]
Is it possible to get some momentum into this PR? With regard to Red CI and the suggested test?

File: build/integration/sharing_features/sharing-v1.feature [hunk 13]
```diff
@@ -229,6 +229,23 @@ Feature: sharing
       | url | AN_URL |
       | mimetype | httpd/unix-directory |
 
+  Scenario: Creating a new share with expiration date removed, when default expiration is set
```
Comment (Fenn-CS) [inline build/integration/sharing_features/sharing-v1.feature:232]: Would fix up commit to main changes once tests are approved

**Review by nfebe — COMMENTED** [review]
WIP commit present.

File: lib/private/Share20/Manager.php [hunk 14]
```diff
@@ -379,28 +307,53 @@ protected function validateExpirationDateInternal(IShare $share) {
...
-		if ($fullId === null && $expirationDate === null && $defaultExpireDate) {
-			$expirationDate = new \DateTime('now', $this->dateTimeZone->getTimeZone());
-			$expirationDate->setTime(0, 0, 0);
-			$days = (int)$this->config->getAppValue('core', $configProp, (string)$defaultExpireDays);
-			if ($days > $defaultExpireDays) {
-				$days = $defaultExpireDays;
+
+		// If $expirationDate is falsy, noExpirationDate is true and expiration not enforced
+		// Then skip expiration date validation as null is accepted
+		if(!(empty($expirationDate) && $share->getNoExpirationDate() && !$isEnforced)) {
```
Comment (Fenn-CS) [inline lib/private/Share20/Manager.php:313]: Does not make a difference, would update.

```suggestion
		if(!($share->getNoExpirationDate() && !$isEnforced)) {
```

**Review by nfebe — COMMENTED** [review]
If `noExpirationDate` is set to true and no enforcement no validation is needed irresepective of the value of `expirationDate`

File: build/integration/sharing_features/sharing-v1.feature [hunk 15]
```diff
@@ -229,6 +229,24 @@ Feature: sharing
...
+      | shareWith | user1 |
+      | shareType | 0 |
+      | expireDate | |
+    Then the OCS status code should be "100"
+    And the HTTP status code should be "200"
+    And Getting info of last share
+    Then the OCS status code should be "100"
+    And the HTTP status code should be "200"
+    And Share fields of last share match with
+      | expiration ||
```
Comment (Fenn-CS) [inline build/integration/sharing_features/sharing-v1.feature:248]: @artonge In case you are wondering this is what the test suite is complaining about.

Context:

- We updated the backend to not set expiry date when an empty value is sent
- So when the expiry is created it returns expiration that should be nullable or an empty space.
- So next step is to try `| null |` currently I am passing `||` and not sure how Gherkin would parse that.

**Review by artonge — APPROVED** [review]

File: lib/public/Share/IShare.php [hunk 16]
```diff
@@ -385,20 +385,38 @@ public function getNote();
...
 	 * @since 9.0.0
 	 */
 	public function getExpirationDate();
 
+	/**
+	 * Set overwrite flag for falsy expiry date vavlues
+	 *
+	 * @param bool $noExpirationDate
+	 * @return \OCP\Share\IShare The modified object
+	 * @since 27.0.0
```
Comment (come-nc) [inline lib/public/Share/IShare.php:407]:
```suggestion
	 * @since 29.0.0
```
And then adapted in backports

Comment (come-nc) [reply lib/public/Share/IShare.php:407]: (same for  `getNoExpirationDate`)

**Review by come-nc — APPROVED** [review]

**Comment by ShGKme** [comment]
This breaks uploading in Talk which expects `$expireDate` to be `string`

**Comment by blizzz** [comment]
> This breaks uploading in Talk which expects `$expireDate` to be `string`

Also on 27?

**Comment by Antreesy** [comment]
> Also on 27?

Confirm for stable27
image

File: lib/public/Share/IShare.php [hunk 17]
```diff
@@ -385,20 +385,38 @@ public function getNote();
...
+	public function setNoExpirationDate(bool $noExpirationDate);
+
+
+	/**
+	 * Get value of overwrite falsy expiry date flag
+	 *
+	 * @return bool
+	 * @since 30.0.0
+	 */
+	public function getNoExpirationDate();
```
Comment (nickvergessen) [inline lib/public/Share/IShare.php:418]: @Fenn-CS Please document in https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_30.html#id1

(all changes in lib/public/)

Comment (Fenn-CS) [reply lib/public/Share/IShare.php:418]: https://github.com/nextcloud/documentation/pull/12051
