### PR TITLE
Fix dav has-photo plugin extend

### LINKED ISSUE #14483: 404 on /remote.php/dav/addressbooks/admin/ on fresh install
Tried it multiple times, I always get a 404 on fresh install of nc16.

## to reproduce:
1. fresh install master with sqlite
2. install contacts
3. open the devtools
4. go to the contacts app
5. cry

@rullzer @MorrisJobke @georgehrke :woman_shrugging: 
Can anyone reproduce?

``` json
{
  "reqId": "T51jTxNlnaUun9quFSX4",
  "level": 3,
  "time": "2019-03-03T10:06:00+00:00",
  "remoteAddr": "172.21.0.1",
  "user": "admin",
  "app": "PHP",
  "method": "PROPFIND",
  "url": "/remote.php/dav/addressbooks/admin/",
  "message": "Uncaught Sabre\\DAV\\Exception\\NotFound: File not found: admin in 'addressbooks' in /var/www/html/3rdparty/sabre/dav/lib/DAV/SimpleCollection.php:91
    Stack trace:
    #0 /var/www/html/3rdparty/sabre/dav/lib/DAV/Collection.php(54): Sabre\\DAV\\SimpleCollection->getChild('admin')
    #1 /var/www/html/3rdparty/sabre/dav/lib/DAV/Tree.php(105): Sabre\\DAV\\Collection->childExists('admin')
    #2 /var/www/html/3rdparty/sabre/dav/lib/DAVACL/Plugin.php(878): Sabre\\DAV\\Tree->nodeExists('addressbooks/ad...')
    #3 /var/www/html/apps/dav/lib/Connector/Sabre/DavAclPlugin.php(95): Sabre\\DAVACL\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))
    #4 [internal function]: OCA\\DAV\\Connector\\Sabre\\DavAclPlugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))
    #5 /var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
    #6 /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php(466): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)
    #7 /var/www/html/3rdparty/sa at /var/www/html/3rdparty/sabre/dav/lib/DAV/SimpleCollection.php#91",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36",
  "version": "16.0.0.1"
}
```

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #14483

### CODE REVIEW

File: apps/dav/lib/CardDAV/HasPhotoPlugin.php [hunk 1]
```diff
@@ -28,10 +28,11 @@
 use Sabre\DAV\INode;
 use Sabre\DAV\PropFind;
 use Sabre\DAV\Server;
+use Sabre\DAV\ServerPlugin;
 use Sabre\VObject\Component\VCard;
 use Sabre\VObject\Reader;
 
-class HasPhotoPlugin extends \Sabre\CardDAV\Plugin {
+class HasPhotoPlugin extends ServerPlugin {
```
Comment (georgehrke) [inline apps/dav/lib/CardDAV/HasPhotoPlugin.php]: Tiny but important detail 😉 👍

**Review by georgehrke — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
