### PR TITLE
Fix(core): fix app menu alignment in RTL mode.

### LINKED ISSUE #49018: [Bug]: App menu alignment issue in RTL mode.
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hello everyone,

This is a bug in the newly introduced UI RTL mode for languages such as Arabic and Persian. When switching the UI language to Arabic, app menu text and active app icon are shifted to the left. 

Image

### Steps to reproduce
1. Switch Nextcloud UI interface to non-Latin languages. More specifically, switch to languages with RTL mode such as Arabic or Persian.
2. Go to the dashboard or files app.

### Expected behavior
The text should be correctly aligned with the app icon exactly like left-to-right interface:
Image

### Nextcloud Server version

master

### PR DESCRIPTION
**Pull request by falghamdi125**
* Resolves: #49018 

## Summary
Hello,

This PR solves the app menu alignment in RTL mode. 

Before:
image

After:
image

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: core/src/components/AppMenuEntry.vue [hunk 1]
```diff
@@ -114,6 +117,9 @@ watch(() => props.app.name, calculateSize)
 			transition: all var(--animation-quick) ease-in-out;
 			opacity: 1;
 		}
+		body[dir=rtl] &::before {
+			transform: translateX(50%) !important;
+		}
```
Comment (skjnldsv) [inline core/src/components/AppMenuEntry.vue:122]:
```suggestion
		}
```

Comment (falghamdi125) [reply core/src/components/AppMenuEntry.vue]: Done

**Review by skjnldsv — APPROVED** [review]

**Review by Pytal — APPROVED** [review]
