### PR TITLE
Fix dark theme on public link shares

### LINKED ISSUE #27371: [Accessability] [Dark theme] Folder shared link size and modified columns text not visible
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1.Go to Accessibility, enable dark theme
2.Share link from one folder
3.Open the shared link

### Expected behaviour
The size and modified columns text should be white 

### Actual behaviour
The size and modified columns text are grey and black

### Server configuration

Freebsd 12

Nginx 1.18.0

MariaDB 10.5.8

PHP 7.4.16

Nexcloud 21.0.2

Updated from an older Nextcloud

Where did you install Nextcloud from: Web

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
Browser:
Firefox 78.10.0 esr (64-bit)

Operating system:
Debian 10.9

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

### PR DESCRIPTION
**Pull request by szaimen**
Fix https://github.com/nextcloud/server/issues/27371

Check the file size and date on a public share

Before | After
---|---
Bildschirmfoto von 2021-07-09 09-29-54 | Bildschirmfoto von 2021-07-09 09-29-42

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Comment by szaimen** [comment]
This breaks iternally if the accessibility app is deaktivated

**Comment by szaimen** [comment]
Fixed :)

File: apps/files/js/filelist.js [hunk 1]
```diff
@@ -1661,7 +1661,10 @@
 			td.append(linkElem);
 			tr.append(td);
 
-			var isDarkTheme = OCA.Accessibility && OCA.Accessibility.theme === 'dark'
+			var isDarkTheme = false
+			if (window.getComputedStyle(document.body, null).getPropertyValue('background-color') === 'rgb(24, 24, 24)') {
```
Comment (nickvergessen) [inline apps/files/js/filelist.js:1665]: That's a hack... Does it even work with high-contrast?


Can you not check if `body` has the class `theme--dark`? 
That is how we do it in all other apps

**Review by nickvergessen — DISMISSED** [review]

File: apps/files/js/filelist.js (hunk 1 above)
Comment (szaimen) [reply apps/files/js/filelist.js:1665]: Thanks for the idea! Will have a look then :)

Comment (szaimen) [reply apps/files/js/filelist.js:1665]: Unfortunatley 
```
			var isDarkTheme = false
			if (document.body.classList.contains('theme--dark')) {
				isDarkTheme = true
			}
```

Doesn't work if the accessibility app is disabled either since the class comes from the app...

Comment (szaimen) [reply apps/files/js/filelist.js]: f918369 is the best I am able to come up with. I've tested it with all senarios: dark-mode, high-contrast mode, public page with prefers-color-scheme dark, accessibility app disabled and it works.

If the solution is not good enough, I think somebody else needs to take this over...

**Comment by szaimen** [comment]
0a0a608 fixes a bug in the filepicker where the filesize is not correctly colored in dark mode. Together with f918369 this gets fixed too.

File: apps/files/js/filelist.js (hunk 1 above)
Comment (nickvergessen) [reply apps/files/js/filelist.js]: It's an accessibility feature. If the app is disabled and it doesn't work, that is acceptable.
Checking for the class is the only proper thing. The old way also only worked with the app enabled.

Comment (juliushaertl) [reply apps/files/js/filelist.js]: How about this to also cover the prefers-color-scheme:

```
var isDarkTheme = (OCA.Accessibility && OCA.Accessibility.theme === 'dark') || window.matchMedia('(prefers-color-scheme: dark)').matches
``

https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia

Comment (szaimen) [reply apps/files/js/filelist.js]: The big problem is that the accessibility javascript isn't available on public pages wich will because of that never add the class theme--dark on public pages hence the following always returns false on public pages in my testing: 
```
if (document.body.classList.contains('theme--dark'))
```

Comment (szaimen) [reply apps/files/js/filelist.js]: Thanks for the idea @juliushaertl but this unfortunately doesn't work either because the dark mode on public pages only gets injected via the accessibility app on the server but doesn't if the app is not enabled which in return always turns the text then to white because the prefers-color-scheme is set on the client...

Comment (juliushaertl) [reply apps/files/js/filelist.js]: In that case just make it depend on the accessibility app :wink: 

```
var isDarkTheme = OCA.Accessibility 
    && (OCA.Accessibility.theme === 'dark' || window.matchMedia('(prefers-color-scheme: dark)').matches)
```

Comment (nickvergessen) [reply apps/files/js/filelist.js]: https://github.com/nextcloud/server/blob/215aef3cbdc1963be1bb6bca5218ee0a4b7f1665/apps/accessibility/lib/AppInfo/Application.php#L74-L81

basically the 
```php
\OCP\Util::addScript('accessibility', 'accessibilityoca');
```
is missing in the guest case. So let's fix that, or can script tags not have media queries?

Comment (szaimen) [reply apps/files/js/filelist.js]: @juliushaertl @nickvergessen could maybe one of you handle making the accessibility.js available on public pages? That exceeds my expertise...

**Comment by nickvergessen** [comment]
Ready to review

**Review by szaimen — COMMENTED** [review]
👍 Works in my testing. Thank you @nickvergessen for fixing this! :)

**Review by juliusknorr — APPROVED** [review]

**Comment by MichaIng** [comment]
/backport to stable20

I hope the JS does not comflict.
