### PR TITLE
fix(settings): show group label instead of gid in accounts management

### LINKED ISSUE #52130: [Bug]: Accounts page - Group GIDs shown instead of names in groups column
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

We're using [SocialLogin](https://apps.nextcloud.com/apps/sociallogin) in combination with Keycloak to externally manage users and groups. Since there are different groups with identical names, we have to use Keycloak's technical group IDs when creating the groups in NC. After creation, we're setting the group name to the human readable version as provided by Keycloak.

With the recent update to `30.0.9`, the accounts page is now using the gid instead of the group's name, making it hard to see which groups a user belongs to. 

Image

Oddly enough, the dropdown shows the actual labels, same as the sidebar.

Image

We've checked the release notes and found this PR, which might be related to this issue: https://github.com/nextcloud/server/pull/51782

More specifically this part, where the `gid` is used as `id` and as a name for the group:
https://github.com/nextcloud/server/pull/51782/files#diff-ab529eede9c79bab1c6362047a62f396fed0118faeaad199dbc4183e8b0ae60eR756-R757

```js
this.availableGroups.push({ id: gid, name: gid })
```

We're wondering if this is intentional. We get that this is not an issue for regular groups that are created using the UI, since you can't specify gid/name separately, but I'm sure we're also not the only ones using SocialLogin and external identity providers either.

### Steps to reproduce

1. Create a group with name "Test" (which will set its' gid to "Test" as well)
2. Set the name to "Something else"
3. The groups column on the accounts page will show "Test"

### Expected behavior

The group column should display the names of the groups, not their gid. Just as it does in the sidebar or the dropdown when assigning a group to a user.

### Nextcloud Server version

30

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [x] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/server/issues/52130

| Before | After |
|:---------:|:------:|
|||

### CODE REVIEW

File: apps/settings/src/components/Users/UserRow.vue [hunk 1]
```diff
@@ -425,13 +425,27 @@ export default {
...
 		userGroupsLabels() {
 			return this.userGroups
-				.map(group => group.name ?? group.id)
+				.map(group => {
+					// Try to match with more extensive group data
+					const availableGroup = this.availableGroups.find(g => g.id === group.id)
+					if (availableGroup) {
+						return availableGroup.name ?? availableGroup.id
+					}
+					return group.name ?? group.id
```
Comment (susnux) [inline apps/settings/src/components/Users/UserRow.vue]: Also works in 1 line if preferred:
```suggestion
					return availableGroup.name ?? group.name ?? group.id
```

**Review by susnux — APPROVED** [review]

File: apps/settings/src/components/Users/UserRow.vue (hunk 1 above)
Comment (skjnldsv) [reply apps/settings/src/components/Users/UserRow.vue]: Fair! :+1:

File: apps/settings/src/components/Users/UserRow.vue [hunk 2]
```diff
@@ -425,13 +425,27 @@ export default {
...
 		userSubAdminGroupsLabels() {
 			return this.userSubAdminGroups
-				.map(group => group.name ?? group.id)
+				.map(group => {
+					// Try to match with more extensive group data
+					const availableGroup = this.availableSubAdminGroups.find(g => g.id === group.id)
+					if (availableGroup) {
+						return availableGroup.name ?? availableGroup.id
+					}
+					return group.name ?? group.id
```
Comment (skjnldsv) [inline apps/settings/src/components/Users/UserRow.vue]:
```suggestion
					return availableGroup.name ?? group.name ?? group.id
```

**Review by AndyScherzinger — APPROVED** [review]
