### PR TITLE
fix(s3): Don't wait indefinitely for S3 to return

### LINKED ISSUE #46303: [Bug]: timeout not set in S3Client
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The timeout is not set in the S3Client options.  

https://github.com/nextcloud/server/blob/03d71e859cc28adcb774f60f4955b7ce0b41f716/lib/private/Files/ObjectStore/S3ConnectionTrait.php#L92-L103

If my s3 is unreachable and I run `occ file:scan`, it sets a lock on the file and hangs forever.  

Changing the options like this works
```
'http' => ['verify' => $this->getCertificateBundlePath(), 'connect_timeout' => 10, 'timeout' => 10],
```
But it does not log anything in the file:scan and it is not marked as an error (maybe this is normal).

### Steps to reproduce

1. Setup a external storage with type Amazon S3
2. Simulate a network problem
3. Do `occ files:scan`

### Expected behavior

There should be a (configurable) timeout and should raise a error.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by solracsf**
* Resolves: https://github.com/nextcloud/server/issues/46303

## Summary

By default, SDK never timeout. Insert some sane defaults.
https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#config-http

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: lib/private/Files/ObjectStore/S3ConnectionTrait.php [hunk 1]
```diff
@@ -98,7 +99,11 @@ public function getConnection() {
 			'signature_provider' => \Aws\or_chain([self::class, 'legacySignatureProvider'], ClientResolver::_default_signature_provider()),
 			'csm' => false,
 			'use_arn_region' => false,
-			'http' => ['verify' => $this->getCertificateBundlePath()],
+			'http' => [
+				'verify' => $this->getCertificateBundlePath(),
+				'connect_timeout' => 10,
+				'timeout' => 60
```
Comment (juliushaertl) [inline lib/private/Files/ObjectStore/S3ConnectionTrait.php:105]: Do you know if this also applies when downloading large files? Such requests could take longer, but I'm not entirely sure if guzzle would apply a timeout while something is actually being transferred.

Comment (solracsf) [reply lib/private/Files/ObjectStore/S3ConnectionTrait.php]: Good point; let's handle just the connection failures, **not the requests** that can be slow and a "good" value could be very hard to find?

**Review by juliusknorr — APPROVED** [review]

**Review by come-nc — APPROVED** [review]
