### PR TITLE
fix(files): Inherit some node attributes when creating new nodes to preserve shared state

### LINKED ISSUE #41725: [Bug]: When I create a file in a shared folder, it is shown as not shared
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I created a file on a shared folder, the file is shown as not shared. After refresh, it looks good

### Steps to reproduce

1. Open a shared folder
2. Create a file
3. See if its shared

### Expected behavior

the file is shown as shared directly to avoid confusion

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

Screenshot from 2023-11-24 10-25-58

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: https://github.com/nextcloud/server/issues/41725

## Summary
When creating new nodes (e.g. new text file or folder) then we also need to inherit some attributes in the first node version before loading from backend. Otherwise files created in folders shared with you will not be shown as shared.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/files/src/views/TemplatePicker.vue [hunk 1]
```diff
@@ -29,7 +29,7 @@
 		<form class="templates-picker__form"
 			:style="style"
 			@submit.prevent.stop="onSubmit">
-			<h2>{{ t('files', 'Pick a template for {name}', { name: nameWithoutExt }) }}</h2>
+			<h2>{{ t('files', 'Pick a template for {name}', { name: nameWithoutExt ?? '' }) }}</h2>
```
Comment (emoral435) [inline apps/files/src/views/TemplatePicker.vue:32]: suggestion: instead of having the right hand be an empty string if the left is null/falsey, should it be something generic like `file/folder`, since that is the generic item that can be chosen in the template picker?

**Review by emoral435 — APPROVED** [review]
Small suggestion aside, this is a good PR! :)

**Review by artonge — APPROVED** [review]
Looks good. Eduardo's comment make sense.
