### PR TITLE
fix(settings): Sort all settings - incl declarative settings - by priority

### LINKED ISSUE #47109: [Bug]: Declarative settings are always rendered last
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When using declarative settings, the settings are always rendered last.
But if you specify a priority higher than a "legacy" setting, it should be rendered before them.

### Steps to reproduce

1. Add a declarative settings on a existing section
2. set higher priority than other
3. see the setting is always rendered last

### Expected behavior

Should have the same control over the priority as with legacy settings.

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

`DeclarativeManager::getFormIDs` only returns the IDs sorted, but not the priority so we can not sort in the settings app.

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: #47109 

## Summary

Previously declarative settings were sorted by priority but behind the "native" settings, this is now fixed, meaning a declarative setting with higher priority than an `ISetting` will be correctly rendered before that `ISetting` in the settings list.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by susnux** [comment]
cc @SebastianKrupinski

File: apps/settings/lib/Controller/CommonSettingsTrait.php [hunk 1]
```diff
@@ -106,53 +108,67 @@ protected function formatAdminSections(string $currentType, string $currentSecti
...
 		}
 		return ['content' => $html];
 	}
 
 	/**
 	 * @psalm-param 'admin'|'personal' $type
+	 * @param ISetting[] $settings
+	 * @param DeclarativeSettingsFormSchemaWithoutValues[] $declarativeSettings
 	 */
 	private function getIndexResponse(string $type, string $section): TemplateResponse {
```
Comment (provokateurin) [inline apps/settings/lib/Controller/CommonSettingsTrait.php:141]: These params don't exist

File: apps/settings/lib/Controller/CommonSettingsTrait.php [hunk 2]
```diff
@@ -106,53 +108,67 @@ protected function formatAdminSections(string $currentType, string $currentSecti
...
+			$settings = array_values($this->settingsManager->getPersonalSettings($section));
 			if ($section === 'theming') {
 				$this->navigationManager->setActiveEntry('accessibility_settings');
 			} else {
 				$this->navigationManager->setActiveEntry('settings');
 			}
 		} elseif ($type === 'admin') {
+			$settings = array_values($this->settingsManager->getAllowedAdminSettings($section, $user));
+			if (empty($settings) && empty($declarativeSettings)) {
+				throw new NotAdminException('Logged in user does not have permission to access these settings.');
```
Comment (provokateurin) [inline apps/settings/lib/Controller/CommonSettingsTrait.php:156]: Causality between this error message and empty settings might not be there, something else could cause no settings to be returned.

**Review by provokateurin — CHANGES_REQUESTED** [review]
Psalm is not happy, please fix

File: apps/settings/lib/Controller/CommonSettingsTrait.php (hunk 2 above)
Comment (susnux) [reply apps/settings/lib/Controller/CommonSettingsTrait.php:156]: This is not new just moved.
If there is another error than the other error should throw, this only happens if the current user does not have permissions (required for admin delegation where normal users can see parts of the admin settings).

**Review by provokateurin — APPROVED** [review]

**Review by SebastianKrupinski — APPROVED** [review]
Tested. Works great!
