### PR TITLE
fix(files): Ensure actions never overflow filename

### LINKED ISSUE #51451: [Bug]: grid view: 3-dot "..." menu overlaps with the filename
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

grid view: 3-dot "..." menu overlaps with the filename

Image

details will be added later

### Steps to reproduce

grid view: 3-dot "..." menu overlaps with the filename

### Expected behavior

...

### Nextcloud Server version

29

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: https://github.com/nextcloud/server/issues/51451

### Small screen
before | after
---|---
Screenshot 2025-03-13 at 19-04-39 Files - Nextcloud|Screenshot 2025-03-13 at 19-04-17 Files - Nextcloud

### Wide screen

before | after
---|---
Screenshot 2025-03-13 at 19-04-55 Files - Nextcloud|Screenshot 2025-03-13 at 19-05-28 Files - Nextcloud

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

File: apps/files/src/components/FilesListVirtual.vue [hunk 1]
```diff
@@ -958,4 +958,21 @@ export default defineComponent({
 		height: var(--clickable-area);
 	}
 }
+
+@media screen and (max-width: 768px) {
```
Comment (skjnldsv) [inline apps/files/src/components/FilesListVirtual.vue:962]: We cannot use vars in here, right?

**Review by Pytal — APPROVED** [review]

File: apps/files/src/components/FilesListVirtual.vue (hunk 1 above)
Comment (susnux) [reply apps/files/src/components/FilesListVirtual.vue:962]: No that is not possible for media queries. We need to wait for: https://drafts.csswg.org/css-env-1/

Otherwise classes are the way to go, e.g. setting standardized classes on the body using some core JS script, for example: `body.viewport-extra-small`, `body.viewport-small`, `body.viewport-medium`, `body.viewport-large`
