### PR TITLE
fix(personal-files): correctly filters groupfolders now

### LINKED ISSUE #44359: `files` Personal View contains groupfolders
@emoral435 thanks for the work here ! this one has been expected for a long time and will make happy a lot of people :)
I was testing it, and on our cloud I can still see groupfolders under the Personal Files view, which I think should not be there 🙃
image

_Originally posted by @maximelehericy in https://github.com/nextcloud/server/issues/42919#issuecomment-2006968516_

### PR DESCRIPTION
**Pull request by emoral435**
* Resolves: #44359

## Summary
Previously, group folders where not being filtered out through the personal files view.
With this change, this cleaned up the code a bit and now correctly filters what it did previously, and now group folders :)

Check the screen recording below to see it in effect!

https://github.com/nextcloud/server/assets/110193237/2bec269a-ec01-42f7-a8a8-093a2ba3c686

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by susnux — APPROVED** [review]
makes sense!

**Review by Altahrim — APPROVED** [review]

File: apps/files/src/services/PersonalFiles.ts [hunk 1]
```diff
@@ -36,19 +36,22 @@ const currUserID = getCurrentUser()?.uid
...
  * @return {Boolean}
  */
-export const personalFile = function(node: File): Boolean {
-	const isNotShared = currUserID ? node.owner === currUserID : true
-						&& node.attributes['mount-type'] !== 'group'
-						&& node.attributes['mount-type'] !== 'shared'
-	return isNotShared
+export const isPersonalFile = function(node: File): Boolean {
+	// the type of mounts that determine whether the file is shared
+	const sharedMountTypes = ["group", "shared"]
```
Comment (artonge) [inline apps/files/src/services/PersonalFiles.ts:41]: Shouldn't it be any kind of mount point? Are external storage excluded?

Comment (emoral435) [reply apps/files/src/services/PersonalFiles.ts:41]: Perhaps. Is it not possible that these external storage's containing files still belong solely to the user? These mount types are more defined to be shared, so I think its best to leave it to these. It can change easily in the future though.

Comment (artonge) [reply apps/files/src/services/PersonalFiles.ts:41]: True, but they are still not personal files as "files in your personal folder".
Maybe @nextcloud/designers can give us their opinion
