### PR TITLE
fix(SetupChecks): Make sure array key is set

### LINKED ISSUE #49370: Better error message when configured hostnames/URLs are invalid  (versus `Trying to access array offset on value of type bool`)
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi,
I have no operating problem about my nextcloud instance, but in my nextcloud log, I have this error : 
` Trying to access array offset on value of type bool at /paht/of/my/nextcloud/apps/settings/lib/SetupChecks/CheckServerResponseTrait.php#97`
Can someone tell me why and what's the problem please ?

### Steps to reproduce

1.just visit web interface of my nextcloud
2.go in log
3.I can see the error

### Expected behavior

No errors ...

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "30.0.2.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "default_language": "fr",
        "installed": true,
        "maxZipInputSize": 1073741824,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "enable_avatars": false,
        "allowZipDownload": true,
        "loglevel": 1,
        "maintenance": false,
        "theme": "",
        "default_phone_region": "FR",
        "enable_previews": true,
        "preview_max_x": 640,
        "preview_max_y": 640,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "enabledPreviewProviders": [
            "OC\\Preview\\Movie",
            "OC\\Preview\\Image"
        ],
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "0": [
            "192.168.0.5"
        ],
        "overwrite.cli.url": xwww.com",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "forcessl": true,
        "trusted_domains": [
            "xwww.com",
            "192.168.0.43",
            "192.168.0.21",
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": true,
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "debug": false,
        "htaccess.RewriteBase": "\/",
        "check_for_working_htaccess": false,
        "mail_smtpauthtype": "LOGIN",
        "maintenance_window_start": 1,
        "mysql.utf8mb4": true,
        "app_install_overwrite": [
            "calendar",
            "end_to_end_encryption",
            "keeweb",
            "previewgenerator",
            "talk_simple_poll",
            "libresign"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 3.0.0
  - admin_audit: 1.20.0
  - app_api: 4.0.0
  - bruteforcesettings: 3.0.0
  - calendar: 5.0.1
  - cloud_federation_api: 1.13.0
  - contacts: 6.1.1
  - contactsinteraction: 1.11.0
  - cookbook: 0.11.2
  - dashboard: 7.10.0
  - dav: 1.31.1
  - federatedfilesharing: 1.20.0
  - files: 2.2.0
  - files_downloadlimit: 3.0.0
  - files_external: 1.22.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - music: 2.0.1
  - nextcloud_announcements: 2.0.0
  - notes: 4.11.0
  - notifications: 3.0.0
  - oauth2: 1.18.1
  - password_policy: 2.0.0
  - passwords: 2024.11.20
  - photos: 3.0.2
  - previewgenerator: 5.7.0
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - related_resources: 1.5.0
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - spreed: 20.0.2
  - support: 2.0.0
  - survey_client: 2.0.0
  - text: 4.1.0
  - theming: 2.5.0
  - twofactor_backupcodes: 1.19.0
  - updatenotification: 1.20.0
  - user_status: 1.10.0
  - viewer: 3.0.0
  - weather_status: 1.10.0
  - webhook_listeners: 1.1.0-dev
  - workflowengine: 2.12.0
Disabled:
  - circles: 30.0.0 (installed 0.18.4)
  - comments: 1.20.1 (installed 0.3.0)
  - encryption: 2.18.0
  - federation: 1.20.0 (installed 0.1.0)
  - files_pdfviewer: 3.0.0 (installed 1.2.1)
  - files_versions: 1.23.0 (installed 1.12.0)
  - firstrunwizard: 3.0.0 (installed 1.0)
  - forms: 4.3.3 (installed 4.3.3)
  - groupfolders: 18.0.5 (installed 18.0.5)
  - libresign: 10.2.0 (installed 10.2.0)
  - phonetrack: 0.8.1 (installed 0.8.1)
  - recommendations: 3.0.0 (installed 1.3.0)
  - suspicious_login: 8.0.0
  - systemtags: 1.20.0 (installed 0.3.0)
  - twofactor_nextcloud_notification: 4.0.0
  - twofactor_totp: 12.0.0-dev
  - user_ldap: 1.21.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```json
{"reqId":"cJNCntClIpqPDqyVL76I","level":3,"time":"2024-11-19T10:43:30+00:00","remoteAddr":"192.168.0.254","user":"tigermick","app":"PHP","method":"GET","url":"/settings/ajax/checksetup","message":"Trying to access array offset on value of type bool at /var/www/owncloud/apps/settings/lib/SetupChecks/CheckServerResponseTrait.php#97","userAgent":"Mozilla/5.0 (Android 15; Mobile; rv:132.0) Gecko/132.0 Firefox/132.0","version":"30.0.2.2","data":{"app":"PHP"},"id":"673c6d655a422"}
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by solracsf**
* Resolves: https://github.com/nextcloud/server/issues/49370

## Summary

Backporting a portion of https://github.com/nextcloud/server/pull/47947 to fix an error. This targets `stable30` on purpose.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/settings/lib/SetupChecks/CheckServerResponseTrait.php [hunk 1]
```diff
@@ -93,6 +93,10 @@ protected function getTestUrls(string $url, bool $isRootRequest = false): array
 	protected function normalizeUrl(string $url, bool $removeWebroot): string {
 		if ($removeWebroot) {
 			$segments = parse_url($url);
+			if (!isset($segments['scheme']) || !isset($segments['host'])) {
+				throw new \InvalidArgumentException('URL is missing scheme or host');
+			}
+
```
Comment (joshtrichards) [inline apps/settings/lib/SetupChecks/CheckServerResponseTrait.php:99]:
```suggestion
                if (!filter_var($url, FILTER_VALIDATE_URL)) {
                        throw new \InvalidArgumentException('URL ($url) is invalid - Please verify syntax of all URLs / domains / IP addresses in your config');
                }
		if ($removeWebroot) {
			$segments = parse_url($url);
```

Probably fine either way, but I think using `filter_var` is safer / more likely to catch edge cases.

Also adding the url in the error will help the operator track down the culprit faster.

**Review by joshtrichards — APPROVED** [review]

File: apps/settings/lib/SetupChecks/CheckServerResponseTrait.php (hunk 1 above)
Comment (solracsf) [reply apps/settings/lib/SetupChecks/CheckServerResponseTrait.php:99]: Fine by me, but in that case, this should be into `master` too/first.

Comment (joshtrichards) [reply apps/settings/lib/SetupChecks/CheckServerResponseTrait.php:99]: I guess if we change the approach here, we'll need to do the same in `master`: 

https://github.com/nextcloud/server/blob/935f0d27acfdbb60b11924688aeaaeced62a1e6e/lib/public/SetupCheck/CheckServerResponseTrait.php#L150-L161

Comment (joshtrichards) [reply apps/settings/lib/SetupChecks/CheckServerResponseTrait.php:99]: On it... (in `master`)

Comment (joshtrichards) [reply apps/settings/lib/SetupChecks/CheckServerResponseTrait.php:99]: #49379

**Review by come-nc — APPROVED** [review]

**Comment by solracsf** [comment]
Should we wait for https://github.com/nextcloud/server/pull/49379 ?

**Comment by solracsf** [comment]
Merging here, let's having the new PR backported where applicable.
