### PR TITLE
Bugfix/36644 pruneOutdatedSyncTokens deletes all entries

### LINKED ISSUE #36644: [Bug]: Syncing (shared) calendar misses some events
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

For a number of years, I have run my own NextCloud instance, on which I have renamed my user's default calendar to "Fælles Kalender" (Danish for Common Calendar), so my wife and I can both enter events into it, to update each other on events that affect us both.

Both of us sync from Android phones (via DAVX5 as recommended), and I have also been subscribed via Thunderbird on both my personal and my work computers.

As for the latter subscriptions, I used to just use the built-in CalDAV functionality, but have switched to the CalDAV connector for TbSync as per recommended, but to no avail of the problem described below.

For quite some time, we have experienced the unfortunate state of affairs that, seemingly at random, her updates from her Android phone will not show up in my sync'ed applications, vice versa, and sometimes previously sync'ed events seem to "go missing".

Due to lack of mental and chronological surplus, I have postponed looking further into this, but it cannot continue.

I have recently noticed that the events will typically be shown in the web view of the calendar, and will, typically, show up if I un- and resubscribe, leading me to believe that the problem does not lie in actually storing new events or alterations to existing events, but I am at a loss regarding how to even ascertain whether this is even a NextCloud problem, or a problem shared between CalDAV implementations of Thunderbird, TbSync and DAVX5.

Hence, initially, I am asking for help pinpointing where the problem lies, but have labeled is a bug, as the common denominator seem to be NextCloud, rather than the various clients.

Please advise

### Steps to reproduce

1. Have more than one user share a calendar
2.  Have them sync with multiple clients
3. ???
4. Events disappear

### Expected behavior

Shared access to a calendar should mean that all participants, whatever their CalDAV client, should be able to create and alter events and have their events, or changes to such, be reflected to all participants, regardless of the CalDAV-compliant client software used to sync.

### Installation method

Community Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "hashingCost": 10,
        "trusted_domains": [
            "nephele.molgaard.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nephele.molgaard.org",
        "version": "25.0.3.2",
        "dbtype": "pgsql",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "logtimezone": "UTC",
        "installed": true,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "maintenance": false,
        "loglevel": 2,
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "nephele.molgaard.org",
        "overwriteprotocol": "https",
        "overwritecondaddr": "^195\\.201\\.133\\.130$",
        "enable_previews": true,
        "updatechecker": true,
        "htaccess.RewriteBase": "\/",
        "theme": "",
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "files_downloadactivity",
            "ojsxc",
            "calendar",
            "contacts",
            "spreed",
            "socialsharing_twitter",
            "bruteforcesettings",
            "socialsharing_facebook",
            "files_trackdownloads"
        ],
        "default_phone_region": "ISO 3166-2:DK",
        "secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.2.3
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.1.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.3
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_downloadactivity: 1.15.0
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trackdownloads: 1.11.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.4
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - socialsharing_facebook: 2.5.0
  - socialsharing_twitter: 2.5.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - encryption: 2.10.0
  - ojsxc: 5.0.0
  - spreed: 15.0.3
  - suspicious_login: 4.2.1
  - twofactor_totp
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Irrelevant for now, I think, as I have not myself been able to find anything in the logs.

Please do advise as to changes to logging levels if relevant.
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by charno**
* Resolves: #36644

## Summary

With Nextcloud 26, CalDAV / CardDAV Clients which are using SyncToken (for example Thunderbird) don't receive calendar / contact updates which happened before the last run of `pruneOutdatedSyncTokens`. During collaborative research we found out that `pruneOutdatedSyncTokens` does delete all entries of calendarchanges / addressbookchanges by accident.

This pull request changes the `pruneOutdatedSyncTokens` functions to first select the highest ID in the `*changes` table and use it in a WHERE clause during deletion of the tokens.

Sine calendar on Thunderbird / maybe other clients are regularly missing events I would say this is a quite high impact bug. For me and others, calendar syncing is currently practically unusable.

## Checklist

- [x] Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting) (I hope)
- [x] [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests

### CODE REVIEW

File: apps/dav/lib/CalDAV/CalDavBackend.php [hunk 1]
```diff
@@ -3134,10 +3134,19 @@ public function pruneOutdatedSyncTokens(int $keep = 10_000): int {
...
 			throw new \InvalidArgumentException();
 		}
+
 		$query = $this->db->getQueryBuilder();
-		$query->delete('calendarchanges')
+		$query->select('c.id')
+			->from('calendarchanges', 'c')
 			->orderBy('id', 'DESC')
-			->setFirstResult($keep);
+			->setMaxResults(1);
```
Comment (tcitworld) [inline apps/dav/lib/CalDAV/CalDavBackend.php:3142]: **suggestion:** As the `id` column is primary key and indexed, doing a `MAX()` instead of ordering and getting first result should be faster.
https://stackoverflow.com/a/426785/10204399

File: apps/dav/lib/CalDAV/CalDavBackend.php [hunk 2]
```diff
@@ -3134,10 +3134,19 @@ public function pruneOutdatedSyncTokens(int $keep = 10_000): int {
...
+
+		$maxid =  $query->execute()->fetchOne();
+		if(! $maxid) return 0;
+
+		$query = $this->db->getQueryBuilder();
+		$query->delete('calendarchanges')
+			->where('id <= ' . $maxid - $keep);
```
Comment (tcitworld) [inline apps/dav/lib/CalDAV/CalDavBackend.php:3149]: **issue:** 
Use [the QueryBuilder](https://www.doctrine-project.org/projects/doctrine-orm/en/current/reference/query-builder.html) to build safe queries.
```suggestion
			->where('id <= ' . $maxid - $keep);
			->andWhere($query->expr()->lte('id', $query->createNamedParameter($maxid - $keep, IQueryBuilder::PARAM_INT), IQueryBuilder::PARAM_INT))
```

File: apps/dav/lib/CalDAV/CalDavBackend.php [hunk 3]
```diff
@@ -3134,10 +3134,19 @@ public function pruneOutdatedSyncTokens(int $keep = 10_000): int {
...
+
 		$query = $this->db->getQueryBuilder();
-		$query->delete('calendarchanges')
+		$query->select('c.id')
+			->from('calendarchanges', 'c')
 			->orderBy('id', 'DESC')
-			->setFirstResult($keep);
+			->setMaxResults(1);
+
+		$maxid =  $query->execute()->fetchOne();
```
Comment (tcitworld) [inline apps/dav/lib/CalDAV/CalDavBackend.php:3144]: **nitpick:** 
```suggestion
		$maxid =  $query->executeQuery()->fetchOne();
```

**Review by tcitworld — COMMENTED** [review]
Thanks for the PR!

I have posted a couple of comments on the `CalDavBackend.php` file. The same applies to `CardDavBackend.php`.

EDIT : Make sure to lint your code as well to fix other CI failures.

**Comment by charno** [comment]
@tcitworld Thanks for the feedback, I'll have a look in the evening. Do you know by chance how I can run the linters using vs code and the dev container?

Also I just noticed that you tagged this for Version 28. Do you plan to backport this to 26 / 27?

**Comment by tcitworld** [comment]
> Do you know by chance how I can run the linters using vs code and the dev container?

Unfortunately I don't know. However, it seems the only issues you have should be resolved alongside with the issues I pointed out above.

> Also I just noticed that you tagged this for Version 28. Do you plan to backport this to 26 / 27?

Yup, that's planned.

**Comment by charno** [comment]
More detailed testing (request from Issue) and cleanups are done. Now for hoping linter / psalm is happy

File: apps/dav/lib/CalDAV/CalDavBackend.php [hunk 4]
```diff
@@ -3134,10 +3134,17 @@ public function pruneOutdatedSyncTokens(int $keep = 10_000): int {
...
+			->from('calendarchanges');
+
+		$maxid =  $query->executeQuery()->fetchOne();
+		if(! $maxid) return 0;
+
 		$query = $this->db->getQueryBuilder();
 		$query->delete('calendarchanges')
-			->orderBy('id', 'DESC')
-			->setFirstResult($keep);
+			->where($query->expr()->lte('id', $query->createNamedParameter($maxid - $keep, IQueryBuilder::PARAM_INT), IQueryBuilder::PARAM_INT));
```
Comment (kesselb) [inline apps/dav/lib/CalDAV/CalDavBackend.php:3147]: Should we check if $maxId < $keep?

Comment (charno) [reply apps/dav/lib/CalDAV/CalDavBackend.php:3149]: makes sense to move "no-op" load from the DB to the app server.

Theoretically the first query could be expanded to return "MIN(id)" as well, then we could check if anything would be changed in the DB before executing the second query. But that's maybe a bit too much optimizing for a function which is called exactly once per day

File: apps/dav/lib/CalDAV/CalDavBackend.php (hunk 2 above)
Comment (tcitworld) [reply apps/dav/lib/CalDAV/CalDavBackend.php]: Yup :+1:

**Review by tcitworld — APPROVED** [review]

**Comment by charno** [comment]
@kesselb Can you also add / push the changes to CardDavBackend? I'm away from my dev workstation for the next days

File: apps/dav/lib/CardDAV/CardDavBackend.php [hunk 5]
```diff
@@ -1399,10 +1399,19 @@ public function pruneOutdatedSyncTokens(int $keep = 10_000): int {
 		if ($keep < 0) {
 			throw new \InvalidArgumentException();
 		}
+
+		$query = $this->db->getQueryBuilder();
+		$query->select($query->createFunction('MAX(`id`)'))
+			->from('addressbookchanges');
+
+		$maxid =  $query->executeQuery()->fetchOne();
+		if(! $maxid) return 0;
```
Comment (solracsf) [inline apps/dav/lib/CardDAV/CardDavBackend.php:1408]:
```suggestion
		if (!$maxid) {
			return 0;
		}
```

File: apps/dav/lib/CardDAV/CardDavBackend.php [hunk 6]
```diff
@@ -1399,10 +1399,19 @@ public function pruneOutdatedSyncTokens(int $keep = 10_000): int {
...
+
+		if($maxid < $keep) return 0;
```
Comment (solracsf) [inline apps/dav/lib/CardDAV/CardDavBackend.php:1410]:
```suggestion
		if ($maxid < $keep) {
			return 0;
		}
```

**Comment by charno** [comment]
I'll do some cleanup on weekend (Port changes done to Cal to Card, squishing formatting commits), then from my side I think it is finished

**Comment by charno** [comment]
I have done the formatting changes, now hopefully everything should be fine

File: apps/dav/lib/CalDAV/CalDavBackend.php [hunk 7]
```diff
@@ -3134,10 +3134,19 @@ public function pruneOutdatedSyncTokens(int $keep = 10_000): int {
 		if ($keep < 0) {
 			throw new \InvalidArgumentException();
 		}
+
+		$query = $this->db->getQueryBuilder();
+		$query->select($query->createFunction('MAX(`id`)'))
```
Comment (tcitworld) [inline apps/dav/lib/CalDAV/CalDavBackend.php:3139]: **nitpick:** 
```suggestion
		$query->select($query->func()->max('id'))
```
Same with CardDAV.

**Review by tcitworld — APPROVED** [review]

**Review by tcitworld — APPROVED** [review]
Squash commits and fix sign-off and that's perfect.

Thanks a lot for that!

**Comment by charno** [comment]
Thanks for reviewing! I'm happy when this bug is gone, this one was especially painful for me

**Review by st3iny — APPROVED** [review]
Tested and works. Nice catch!

**Comment by szaimen** [comment]
CI failure unrelated

**Comment by charno** [comment]
> /backport to stable25

This will probably not be possible since the functionality this fixes is not present in 25

**Comment by tcitworld** [comment]
Backports in #38919 and #38920.

There's nothing to backport below 26 as there was no purge of outdated tokens before that, so other issues stated in #36644 are unrelated.
