### PR TITLE
Fix public download activity

### LINKED ISSUE #51097: [Bug]: NC31.0.0 not logging view/download activity
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I have been using NC for a long time and just upgraded to 31. I can create public shares with no issues, but I no longer see public share views and downloads listed under activity. It shows the share being created and deleted but nothing related to views/downloads. I checked the "oc_activity" table, and the rows in that table match what I am seeing.

I shared a document on 2/22, and it showed as downloaded in activity and the oc_activity table. This was before I upgraded. The share is still active and accessible since upgrading, but now, when I perform the same activity (e.g., access the file via the share link), views/downloads no longer appear in oc_activity or in the activity stream.

In case it matters, when I upgraded, I got all kinds of “incorrect row format found in your database” errors. It is described in [this post](https://help.nextcloud.com/t/upgrade-to-nextcloud-hub-10-31-0-0-incorrect-row-format-found-in-your-database/218366). I used that script and manually updated every row and the errors are gone. I have no idea if that matters, but I wanted to share.

I also found this [GitHub issue](https://github.com/nextcloud/server/issues/50785), which looks similar. However, it is for a different version, and it suggests that activity is still logged when files are downloaded rather than viewed. For me, activity is never logged other than "share" and "unshare."

This is new behavior as it worked previously, as shown from the example from 2/22. As an aside, I also [posted about this](https://help.nextcloud.com/t/activity-history-with-public-links-no-longer-updating-post-31-0-0-upgrade/218506) in the NC forum.

### Steps to reproduce

1. Share a file and copy the link
2. Open Incognito window
3. Paste the link and view the file
4. View the activity screen in NC or query all records in oc_activity

### Expected behavior

Views and downloads should appear in the activity stream as in the past.

### Nextcloud Server version

31

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 31 to 32)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwritecondaddr": "<IP>",
        "trusted_domains": {
            "1": "<FQDN>",
            "2": "<FQDN>",
            "3": "<IP>",
            "4": "<IP>"
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "<FQDN>",
        "dbtype": "mysql",
        "version": "31.0.0.18",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "loglevel": 2,
        "default_phone_region": "US",
        "maintenance": false,
        "htaccess.RewriteBase": "\/",
        "theme": "",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "mail_sendmailmode": "smtp",
        "mysql.utf8mb4": true,
        "maintenance_window_start": 6
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 4.0.0
  - app_api: 5.0.2
  - bruteforcesettings: 4.0.0
  - circles: 31.0.0-dev.0
  - cloud_federation_api: 1.14.0
  - comments: 1.21.0
  - contactsinteraction: 1.12.0
  - dashboard: 7.11.0
  - dav: 1.33.0
  - federatedfilesharing: 1.21.0
  - federation: 1.21.0
  - files: 2.3.1
  - files_downloadlimit: 4.0.0
  - files_pdfviewer: 4.0.0
  - files_reminders: 1.4.0
  - files_sharing: 1.23.1
  - files_trashbin: 1.21.0
  - files_versions: 1.24.0
  - firstrunwizard: 4.0.0
  - logreader: 4.0.0
  - lookup_server_connector: 1.19.0
  - nextcloud_announcements: 3.0.0
  - notifications: 4.0.0
  - oauth2: 1.19.1
  - password_policy: 3.0.0
  - photos: 4.0.0-dev.1
  - privacy: 3.0.0
  - profile: 1.0.0
  - provisioning_api: 1.21.0
  - recommendations: 4.0.0
  - related_resources: 2.0.0
  - serverinfo: 3.0.0
  - settings: 1.14.0
  - sharebymail: 1.21.0
  - survey_client: 3.0.0
  - suspicious_login: 9.0.1
  - text: 5.0.0
  - theming: 2.6.1
  - twofactor_backupcodes: 1.20.0
  - twofactor_totp: 13.0.0-dev.0
  - updatenotification: 1.21.0
  - viewer: 4.0.0
  - weather_status: 1.11.0
  - webhook_listeners: 1.2.0
  - workflowengine: 2.13.0
```

### Nextcloud Signing status

```shell
No errors have been found
```

### Nextcloud Logs

```json
{"reqId":"iqYqZ3QZsXElkuqMc852","level":3,"time":"2025-02-26T20:30:01+00:00","remoteAddr":"162.158.6.61","user":false,"app":"no app in context","method":"GET","url":"/.well-known/","message":"Could not decrypt or decode encrypted session data","userAgent":"--","version":"31.0.0.18","exception":{"Exception":"Exception","Message":"HMAC does not match.","Code":0,"Trace":[{"file":"/var/www/html/owncloud/lib/private/Security/Crypto.php","line":98,"function":"decryptWithoutSecret","class":"OC\\Security\\Crypto","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/owncloud/lib/private/Session/CryptoSessionData.php","line":70,"function":"decrypt","class":"OC\\Security\\Crypto","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/owncloud/lib/private/Session/CryptoSessionData.php","line":47,"function":"initializeSession","class":"OC\\Session\\CryptoSessionData","type":"->"},{"file":"/var/www/html/owncloud/lib/private/Session/CryptoWrapper.php","line":94,"function":"__construct","class":"OC\\Session\\CryptoSessionData","type":"->"},{"file":"/var/www/html/owncloud/lib/base.php","line":410,"function":"wrapSession","class":"OC\\Session\\CryptoWrapper","type":"->"},{"file":"/var/www/html/owncloud/lib/base.php","line":679,"function":"initSession","class":"OC","type":"::"},{"file":"/var/www/html/owncloud/lib/base.php","line":1149,"function":"init","class":"OC","type":"::"},{"file":"/var/www/html/owncloud/index.php","line":22,"args":["/var/www/html/owncloud/lib/base.php"],"function":"require_once"}],"File":"/var/www/html/owncloud/lib/private/Security/Crypto.php","Line":162,"message":"Could not decrypt or decode encrypted session data","exception":[],"CustomMessage":"Could not decrypt or decode encrypted session data"},"id":"67bf94c8beee9"}
```

### Additional info

I don't think that the log is relevant, and I wanted to share it even so. The line has been repeated once.

### PR DESCRIPTION
**Pull request by come-nc**
* Resolves: #51097 

## Summary

Fix pubilc download activity in 31+, and improve upon it to make sure it’s consistent.

## TODO

- [x] Viewing a video triggers several activity events. They are merged in activity feed, but generate a lot of notifications.
- [ ] ~Viewing a photo through preview does not trigger activity, is that an issue?~
- [x] Downloading the whole share triggers activity for the folder and then for each file.
- [x] Downloading several files in a zip triggers activity for each file. I think that’s good?
- [x] The manual activity publishing in ShareController should be removed to avoid duplicates. But I think that’s the one publishing the activity for folder download, so we should make sure we do not lose it.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/files_sharing/lib/Listener/BeforeNodeReadListener.php [hunk 1]
```diff
@@ -0,0 +1,116 @@
...
+
+namespace OCA\Files_Sharing\Listener;
+
+use OCA\Files_Sharing\Activity\Providers\Downloads;
+use OCP\EventDispatcher\Event;
+use OCP\EventDispatcher\IEventListener;
+use OCP\Files\Events\Node\BeforeNodeReadEvent;
+use OCP\Files\File;
+use OCP\Files\IRootFolder;
+use OCP\Files\Storage\ISharedStorage;
```
Comment (susnux) [inline apps/files_sharing/lib/Listener/BeforeNodeReadListener.php:18]:
```suggestion
use OCP\Files\NotFoundException;
use OCP\Files\Storage\ISharedStorage;
```

**Comment by come-nc** [comment]
> * [ ]  Viewing a photo through preview does not trigger activity, is that an issue?

This one is not a regression so let’s postpone for later.
A solution would be to listen to `BeforePreviewFetchedEvent`, but we’d have to decide at which size of preview we consider that downloading, because opening the file list already loads previews of small sizes.

**Comment by come-nc** [comment]
I would like to add tests for this, but activity application is needed.
I can add the tests in activity application cypress tests, but that mean a PR breaking the feature on server will have green CI and we will only figure it out later. Still better than no tests I suppose?
Other ideas?

**Comment by susnux** [comment]
> I would like to add tests for this, but activity application is needed.

Is there no OCS API or something you can test with behat?

Otherwise I see two ways:
1. Do it like we do for some Talk tests and install the Activity for some Behat tests (IMHO this makes sense for all things that have integrations in OCP)
2. Only add them to Activity -> would not be directly spotted if something breaks the app.

**Comment by daniel-richter** [comment]
Just a heads-up: I had the same issue (downloads of individual files from a shared folder weren't showing up in the activities, #51097). I can confirm that the suggested changes solve the problem for me.

**Comment by daniel-richter** [comment]
> * [x]  Viewing a video triggers several activity events. They are merged in activity feed, but generate a lot of notifications.
> * [ ]  ~Viewing a photo through preview does not trigger activity, is that an issue?~

Well, that's how it used to be. If you watched a video, it would show up in the "downloaded via public link" log. For images, you had to click "download" for it to show up in the log. Just viewing the image didn't do it.

**Comment by susnux** [comment]
Did not yet had time to test this, but old behavior was also inconsistent as there were some endpoints that never caused a download notification.
Also we should define what this notification means.

Because either it only means real downloads, then we only need to track the DAV endpoints (`GET` on file or zipfolder plugin).
Or it also means viewing the file, then we also need to track preview endpoints (which is used by the viewer for images).

If I get the code right then this PR implements both. Which is fine but might confuse users as they will see "file downloaded" notifications even if they set "download permission" to `false` because previews are shown.

**Comment by daniel-richter** [comment]
I see two options here:
1. Track only real _downloads_.
2. If we want to track _views_, too, we should introduce a separate subject, "public_shared_file_viewed" (in contrast to "public_shared_file_downloaded").

**Comment by come-nc** [comment]
> > I would like to add tests for this, but activity application is needed.
> 
> Is there no OCS API or something you can test with behat?

It’s DAV, not OCS, but that can be tested with behat. But still needs the activity app.

> Otherwise I see two ways:
> 
> 1. Do it like we do for some Talk tests and install the Activity for some Behat tests (IMHO this makes sense for all things that have integrations in OCP)

I will try that.

> If I get the code right then this PR implements both. Which is fine but might confuse users as they will see "file downloaded" notifications even if they set "download permission" to `false` because previews are shown.

No, this PR only logs downloads through DAV, kind of the same as old behavior.
Preview endpoint does not trigger any notifications.

Actually, something I did not test is if a public link is loaded in which there is a file with no preview yet. Then opening the folder may trigger the preview computing and a download activity. But I’m not 100% sure that is possible in real life. How do you share a folder without triggering preview caching?

File: build/integration/features/bootstrap/BasicStructure.php [hunk 2]
```diff
@@ -192,8 +192,8 @@ protected function sendRequestForJSON(string $verb, string $url, $body = null, a
 		$options = [];
 		if ($this->currentUser === 'admin') {
 			$options['auth'] = ['admin', 'admin'];
-		} elseif (strpos($this->currentUser, 'guest') !== 0) {
-			$options['auth'] = [$this->currentUser, self::TEST_PASSWORD];
```
Comment (nickvergessen) [inline build/integration/features/bootstrap/BasicStructure.php:196]: Can we keep this unchanged to not break apps that use integration test base from server?

Comment (come-nc) [reply build/integration/features/bootstrap/BasicStructure.php]: No that breaks it. Can you explain how to fix it then? Why is sendingToWith using $this->regularUser but this one use another password?

Comment (nickvergessen) [reply build/integration/features/bootstrap/BasicStructure.php]: I mixed it up I think. Seems everyone is only using the sendingToWith

Comment (nickvergessen) [reply build/integration/features/bootstrap/BasicStructure.php]: Well now it says:
Fatal error: Undefined constant SharingContext::TEST_PASSWORD (Behat\Testwork\Call\Exception\FatalThrowableError)

So that's something different?
The actual fix is replacing `strpos() !== 0`. It does not account for `=== false` when it does not contain the word guest at all

Comment (come-nc) [reply build/integration/features/bootstrap/BasicStructure.php:196]: No, `!==0` is on purpose. The idea is that if the user name starts with X, we do not set auth. But it’s anonymous in the other methods and guest in this one. But TEST_PASSWORD does not exist anyway.

I removed the last commit as it was breaking.

Do you know of applications using this method or is that theoretical?

Comment (nickvergessen) [reply build/integration/features/bootstrap/BasicStructure.php:196]: Marked it as resolved already, not aware of the JSON method being used

**Review by skjnldsv — APPROVED** [review]

**Review by AndyScherzinger — APPROVED** [review]
