### PR TITLE
Make sure urlparams are correctly injected in global routes

### LINKED ISSUE #14621: Public share links are broken
Regression from #14548 

@MorrisJobke @rullzer 

> TESTS=acceptance, TESTS-ACCEPTANCE=app-files-sharing-link
> 
>     tests/acceptance/features/app-files-sharing-link.feature:3
>     tests/acceptance/features/app-files-sharing-link.feature:26
>     tests/acceptance/features/app-files-sharing-link.feature:40
>     tests/acceptance/features/app-files-sharing-link.feature:60
>     tests/acceptance/features/app-files-sharing-link.feature:81
>     tests/acceptance/features/app-files-sharing-link.feature:116
>     tests/acceptance/features/app-files-sharing-link.feature:128
>     tests/acceptance/features/app-files-sharing-link.feature:139

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #14621

### CODE REVIEW

File: core/routes.php [hunk 1]
```diff
@@ -78,6 +78,17 @@
 		['name' => 'contactsMenu#findOne', 'url' => '/contactsmenu/findOne', 'verb' => 'POST'],
 		['name' => 'WalledGarden#get', 'url' => '/204', 'verb' => 'GET'],
 		['name' => 'Search#search', 'url' => '/core/search', 'verb' => 'GET'],
+
+		// Legacy routes that need to be globally available while they are handled by an app
+		['name' => 'viewcontroller#showFile', 'url' => '/f/{fileid}', 'verb' => 'GET', 'app' => 'files'],
```
Comment (nickvergessen) [inline core/routes.php]: I think it should also be possible, to move those to the respective apps, when at the same time we allow defining a `root' => '/cloud'` similar to OCS urls.
Just not sure how this breaks existing route generations (because all lowercase instead of CamelCase controller names, which is why the hacks in `lib/private/AppFramework/Routing/RouteConfig.php` were necessary)

File: lib/private/AppFramework/App.php [hunk 2]
```diff
@@ -94,6 +96,12 @@ public static function main(string $controllerName, string $methodName, DIContai
 		try {
 			$controller = $container->query($controllerName);
 		} catch(QueryException $e) {
+			if (strpos($controllerName, '\\Controller\\') !== false) {
+				// This is from a global registered app route that is not enabled.
+				[/*OC(A)*/, $app, /* Controller/Name*/] = explode('\\', $controllerName, 3);
+				throw new HintException('App ' . strtolower($app) . ' is not enabled');
```
Comment (nickvergessen) [inline lib/private/AppFramework/App.php]: this is inaccurate for `cloud_federation_api` as it shows `cloudfederationapi` instead.
Worth adding another hack? however it's pretty useless anyway.

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍 Also the code looks good 👍

**Review by ChristophWurst — APPROVED** [review]
Makes sense, code looks good!

**Comment by leonklingele-work** [comment]
faily-bot was still complaining about failures yet this PR got merged?!

**Comment by MorrisJobke** [comment]
> faily-bot was still complaining about failures yet this PR got merged?!

Yes because there are some failures on master and we are currently looking into how to fix them. They slipped through.
