### PR TITLE
fix(FilesPicker): Prevent selection of nodes without create permission

### LINKED ISSUE #50199: [Bug]: remove files from the list of recent items in the move/copy modal
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

hello hello, usually, in any system, it is not possible to move a file or a folder inside a file (yes, inside a file). But apparently, in Nextcloud, that is possible 🙃 

Image

### Steps to reproduce

1. right click on an item, then click copy/move
2. when the modal appears, select the recent entry in the left menu
3. wait a bit that it loads
4. you now have the opportunity to move a folder inside a file 🪄

### Expected behavior

Files should not appear in the Recent list

### Nextcloud Server version

30

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

c.nc.c

### PR DESCRIPTION
**Pull request by artonge**
It is misleading to show those nodes in the file picker, as picking them will always result in an error.

Todo:

- [x] Update `@nextcloud/dialog` to uses the new API from https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/2033

The new version will also prevent navigation to non-readable folders. This will prevent navigating to E2EE folders.

| Before | After |
|--------|--------|
| image |Screenshot From 2025-10-17 11-17-19 |

### CODE REVIEW

**Comment by susnux** [comment]
I think we discussed this somewhere with Jan, the outcome was that it is even more confusing to not see all your files.
The solution that was agreed is to grey out non-selectable files.

We probably need a second filter way for this on the library though...

**Comment by artonge** [comment]
> We probably need a second filter way for this on the library though...

Or we instead gray out the files based on that already existing function? Is there a specific use case where we actually want to filter out some nodes?

File: apps/files/src/actions/moveOrCopyAction.ts [hunk 1]
```diff
@@ -22,6 +22,8 @@ import logger from '../logger.ts'
 import { getContents } from '../services/Files.ts'
 import { canCopy, canMove, getQueue, MoveCopyAction } from './moveOrCopyActionUtils.ts'
 
+import '@nextcloud/dialogs/style.css'
```
Comment (susnux) [inline apps/files/src/actions/moveOrCopyAction.ts]: Already be included in server styles - so no need to import

Comment (artonge) [reply apps/files/src/actions/moveOrCopyAction.ts]: Doesn't it make sense to keep the import close to the usage?
Or will it import it twice?

**Comment by artonge** [comment]
I don't think this will work.

We might not have create permission on a specific folder, but still have them on one of its subfolders. Groupfolders with ACLs for example.

So we still need to be able to navigate into those folders.
But for E2EE folders, it makes sense to not be able to navigate to them.

Maybe we also need a `canNavigate` function?

**Comment by susnux** [comment]
>  But for E2EE folders, it makes sense to not be able to navigate to them.

Then you should be able to navigate into those greyed folder but not be able to pick them.
Thats all that this prop says: not pickable

File: apps/files/src/actions/moveOrCopyAction.ts (hunk 1 above)
Comment (susnux) [reply apps/files/src/actions/moveOrCopyAction.ts]: It duplicates as the styles are globally registered already (e.g. we use them OC and OCP API).

In apps they also only need to be imported once per entry point, for server this is globally done in the server styles.

**Comment by artonge** [comment]
> Then you should be able to navigate into those greyed folder but not be able to pick them.

No, for E2EE it does not make sense as we cannot even load their content. But luckily, they are also not readable, I'll push a better approach in a few minutes.

Edit: done

**Review by jancborchardt — APPROVED** [review]
Looks good!

Might additionally be good to have some textual support there, like a title on hover & focus which says "No permissions to upload to this folder", for example.

**Review by susnux — APPROVED** [review]

**Comment by artonge** [comment]
/backport cb062d26915ddc76ca246e2e88f7d785466e82b1 to stable32

**Comment by artonge** [comment]
/backport cb062d26915ddc76ca246e2e88f7d785466e82b1 to stable31

**Comment by artonge** [comment]
/backport cb062d26915ddc76ca246e2e88f7d785466e82b1 to stable30
