### PR TITLE
Fix idn emails not working in shares

### LINKED ISSUE #30595: No email suggestion when sharing with IDN email address
### Steps

1. Create a folder
2. Open the right sidebar
3. Type an email address like "test@example.com" and wait
4. Then change it to "test@äxample.com" and wait

### Expected result
In both 3 and 4 an entry with an envelope must appear in the dropdown.

### Actual result
Only in case 3 without the umlaut the entry with the envelope appears.

### Versions
Observed on 22.2.3 and master

I've tried with this IDN fix of the backend https://github.com/nextcloud/server/pull/27961 but it didn't solve the problem.
I suspect that there's also some JS code in the frontend that tried to detect email addresses and will need to be adjusted.

### PR DESCRIPTION
**Pull request by CarlSchwan**
Fix #30595

Signed-off-by: Carl Schwan <carl@carlschwan.eu>

### CODE REVIEW

**Review by tcitworld — CHANGES_REQUESTED** [review]
You can use `OCP\Mail\Mailer::validateMailAddress` that already has the IDN check.
https://github.com/nextcloud/server/blob/796764aafd318cfeedf6d19af4551e846a40ac94/lib/private/Mail/Mailer.php#L216-L249

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
if possible for this code path would be good to add unit tests with an IDN address

File: apps/sharebymail/lib/ShareByMailProvider.php [hunk 1]
```diff
@@ -334,6 +334,16 @@ protected function createMailShare(IShare $share) {
 			$share->getNote()
 		);
 
+		if ($this->mailer->validateMailAddress($share->getSharedWith())) {
+			$this->removeShareFromTable($shareId);
+			$e = new HintException('Failed to send share by mail. Got an invalid email address: ' . $share->getSharedWith(),
+				$this->l->t('Failed to send share by email. Got an invalid email address'));
+			$this->logger->error($e->getMessage(), [
```
Comment (tcitworld) [inline apps/sharebymail/lib/ShareByMailProvider.php:341]: I think this should be the other way around, the message as first argument, and the whole exception as `"exception"` context key, so that it's future proof for the migration to `LoggerInterface`.

File: apps/sharebymail/lib/ShareByMailProvider.php [hunk 2]
```diff
@@ -334,6 +334,16 @@ protected function createMailShare(IShare $share) {
 			$share->getNote()
 		);
 
+		if ($this->mailer->validateMailAddress($share->getSharedWith())) {
```
Comment (tcitworld) [inline apps/sharebymail/lib/ShareByMailProvider.php:337]: Off-topic, but that `getSharedWith()` should return an array, according to the interface, and therefore not be used as a string here.

**Review by tcitworld — APPROVED** [review]

File: apps/sharebymail/lib/ShareByMailProvider.php (hunk 2 above)
Comment (CarlSchwan) [reply apps/sharebymail/lib/ShareByMailProvider.php:337]: Did I miss something? Looking at the interfaces `lib/public/Share/IShare.php::getSharedWith` returns a string, it's `lib/public/Share/IManager.php::getSharedWith` that returns an array.

Comment (tcitworld) [reply apps/sharebymail/lib/ShareByMailProvider.php:337]: Correct, I was mistaken.

**Comment by CarlSchwan** [comment]
I'm looking into the php unit failures, strange that is works locally for me :/

**Comment by CarlSchwan** [comment]
I found why the tests seemed to work locally and fixed them :)

**Review by PVince81 — APPROVED** [review]
:+1:
