### PR TITLE
fix(files): trim names on new node creation

### LINKED ISSUE #46401: [Bug]: Trailing whitespace doesn't get trimmed when creating folders/files in the WebUI
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When renaming folders or files in the WebUI, whitespace gets trimmed from the name, but not when creating files/folders.

### Steps to reproduce

1. Create a new file or folder in the WebUI.
2. Put a space in the beginning of the name
4. Create it. It now has a name that's beginning with space(s), but the WebUI doesn't show these in the file list.
5. If you then try to rename, it it shows the space. Then, even when you don't manually change something - just by pressing enter - the file/folder name will get trimmed.

### Expected behavior

Creating folders/files should also trim whitespace the same way renaming does.

### Installation method

Community VM appliance

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "default_language": "de",
        "default_phone_region": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "29.0.3.4",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": "true",
        "asset-pipeline.enabled": true,
        "auth.bruteforce.protection.enabled": true,
        "mail_smtpmode": "smtp",
        "mail_smtpport": "587",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "dbindex": 0
        },
        "htaccess.RewriteBase": "\/",
        "maintenance": false,
        "loglevel": 2,
        "theme": "",
        "updater.release.channel": "beta",
        "mail_smtpauthtype": "LOGIN",
        "mysql.utf8mb4": true,
        "mail_smtpauth": 1,
        "mail_sendmailmode": "smtp",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "session_relaxed_expiry": true,
        "session_keepalive": true,
        "auto_logout": false,
        "maintenance_window_start": 1,
        "defaultapp": "files",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forbidden_chars": [
            "?",
            "<",
            ">",
            ":",
            "*",
            "|",
            "\"",
            "\u0000",
            "\n",
            "\r"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.21.1
  - admin_audit: 1.19.0
  - bruteforcesettings: 2.9.0
  - cfg_share_links: 5.1.0
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - comments: 1.19.0
  - contacts: 6.0.0
  - contactsinteraction: 1.10.0
  - dav: 1.30.1
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.0
  - files_downloadlimit: 2.0.0
  - files_external: 1.21.0
  - files_notify_redis: 0.3.3
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - impersonate: 1.16.0
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - notifications: 2.17.0
  - notify_push: 0.6.12
  - oauth2: 1.17.0
  - password_policy: 1.19.0
  - photos: 2.5.0
  - previewgenerator: 5.5.0
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - support: 1.12.0
  - systemtags: 1.19.0
  - text: 3.10.1
  - theming: 2.4.0
  - twofactor_backupcodes: 1.18.0
  - updatenotification: 1.19.1
  - user_status: 1.9.0
  - viewer: 2.3.0
  - workflowengine: 2.11.0
Disabled:
  - dashboard: 7.9.0 (installed 7.0.0)
  - encryption: 2.17.0
  - firstrunwizard: 2.18.0 (installed 2.14.0)
  - nextcloud_announcements: 1.18.0 (installed 1.0)
  - survey_client: 1.17.0 (installed 0.1.5)
  - suspicious_login: 7.0.0 (installed 7.0.0)
  - twofactor_totp: 11.0.0-dev
  - user_ldap: 1.20.0
  - weather_status: 1.9.0 (installed 1.9.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/server/issues/46401

### CODE REVIEW

**Review by sorbaugh — APPROVED** [review]

**Review by szaimen — APPROVED** [review]
LGTM but didnt test

File: apps/files/src/components/NewNodeDialog.vue [hunk 1]
```diff
@@ -118,15 +118,15 @@ function submit() {
 
 // Reset local name on props change
 watch(() => props.defaultName, () => {
-	localDefaultName.value = getUniqueName(props.defaultName, props.otherNames)
+	localDefaultName.value = getUniqueName(props.defaultName, props.otherNames).trim()
```
Comment (susnux) [inline apps/files/src/components/NewNodeDialog.vue:121]: Is this expected behavior? I understand `trimEnd` because of mobile browsers that tend to add spaces on auto complete.
Having whitespace on the start is an edge case but is completely valid, meaning this will change names if you accidentally click rename on such a file

Comment (skjnldsv) [reply apps/files/src/components/NewNodeDialog.vue:121]: > Having whitespace on the start is an edge case but is completely valid

Having a white space at the end is also valid in many filesystems :)
I figured it's not about what is valid or not, but what makes most sense from a UX perspective.
And from my experience, I've yet to see someone willingly prepend or append a space in their file name :thinking:

Comment (susnux) [reply apps/files/src/components/NewNodeDialog.vue:121]: sure, thats why I am asking. This PR only touches the new name handling so should be fine.
