### PR TITLE
Don't put the SMTP password into the HTML code

### LINKED ISSUE #4354: SMTP password visible in admin page HTML
### Steps to reproduce
1. Set up E-Mail sending in the 'Admin' page via SMTP under "Additional settings" -> "Email server".
2. Save the settings and open up the page again.
3. Checking the contents of the input field for the password (next to 'Credentials') shows the full SMTP password as 'value'. 

### Expected behaviour
The SMTP password should not be available via the HTML client.

### Actual behaviour
SMTP password is available in input field value. 

### Server configuration

**Operating system**: Debian 8.7

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 5.6.30

**Nextcloud version:** 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** yes

**Where did you install Nextcloud from:** official tar.bz2

### Client configuration
**Browser:** Chromium 57.0.2987.98

**Operating system:** Ubuntu 16.10

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #4354

### CODE REVIEW

**Review by blizzz — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

File: settings/templates/admin/additional-mail.php [hunk 1]
```diff
@@ -60,81 +60,81 @@
...
+			<input type="text" name="mail_domain" id="mail_domain" placeholder="example.com"
+				   value="<?php p($_['mail_domain']) ?>" />
 		</p>
 
-		<p id="setting_smtpauth" <?php if ($_['mail_smtpmode'] != 'smtp') print_unescaped(' class="hidden"'); ?>>
-			<label for="mail_smtpauthtype"><?php p($l->t( 'Authentication method' )); ?></label>
-			<select name='mail_smtpauthtype' id='mail_smtpauthtype'>
+		<p id="setting_smtpauth" <?php if ($_['mail_smtpmode'] !== 'smtp') print_unescaped(' class="hidden"'); ?>>
+			<label for="mail_smtpauthtype"><?php p($l->t('Authentication method')); ?></label>
+			<select name="mail_smtpauthtype" id="mail_smtpauthtype'>
```
Comment (MorrisJobke) [inline settings/templates/admin/additional-mail.php]: One `'` was not replaced 🙈 (see #11218)
