### PR TITLE
LDAP's checkPassword should only catch when a user was not found, fixes #2431

### LINKED ISSUE #2431: App passwords vanish
### Steps to reproduce
1. Enable TOTP Plugin in 
2. Create 2 or more App Passwords
3. After some time the Desktop App starts asking for the per-device Token.

### Expected behaviour
App Passwords (per-device passwords) should work infinite, 

### Actual behaviour
somehow the app passwords vanish from the personal menu in NC. I have to genereate a new App Password, then the Desktop Client works again.

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4

**Database:** Mysql

**PHP version:** 5.6

**Nextcloud version:** (see Nextcloud admin page) 10.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** NC tarball

**Signing status:**
<details>
<summary>Signing status</summary>

```
Results
=======
- core
	- INVALID_HASH
		- core/js/mimetypelist.js
		- lib/private/Share/MailNotifications.php
	- EXTRA_FILE
		- resources/config/mimetypemapping.json

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/js/mimetypelist.js] => Array
                        (
                            [expected] => 013e97237eeb9627ac398a50d0924621f1faa5d84ba94ab7bcc4970fbf6af55232afcf9bdef601f7f8fd6663e8e59bcb32877fd6353e893fde2c63c0893f537c
                            [current] => 1533e80c77d5eb738008b5c4c045ea014fe3653053c4c118e1eca267c4e56102788ed31a5d79d6041f1e639fa5ab55d060ea0035980fbb4915989a36ebcf96f0
                        )

                    [lib/private/Share/MailNotifications.php] => Array
                        (
                            [expected] => ff4d6280890f3d370907086c8f920a51674c72224ab5cf865b1ae42140ea2c614bb03cc0547a59205810d62e35a3d365925738d7983375e272acf826bce1633f
                            [current] => 1875a25f8593737e2e3e00b0e2ecccb14471a844922f5232275cc69ceddc144b5b6bbde350aad5f817164e390808c3c3b9ca8fe76ad6cb037e4ad7498a1a5366
                        )

                )

            [EXTRA_FILE] => Array
                (
                    [resources/config/mimetypemapping.json] => Array
                        (
                            [expected] => 
                            [current] => e98fd0313bc3ced2ab0d92d87d73cf38b3104c93cafce38ebd079d2c0b419378831b9d7635df8e078dc2bd56ef7b141e78fdea6a8012c471843509cef6a427bc
                        )

                )

        )

)
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.3.2
  - admin_audit: 1.0.0
  - calendar: 1.4.0
  - comments: 1.0.0
  - contacts: true
  - dav: 1.0.0
  - documents: true
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_pdfviewer: 0.8.1
  - files_retention: 1.0.0
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - gallery: 15.0.0
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - tasks: 0.9.3
  - templateeditor: 0.1
  - theming: 1.0.1
  - twofactor_totp: 0.4.1
  - updatenotification: 1.0.1
  - user_external: 0.4
  - workflowengine: 1.0.1
Disabled:
  - encryption
  - external
  - files_external
  - firstrunwizard
  - user_ldap
  - user_saml
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'trusted_domains' => 
  array (
    0 => 'nc.niedermayr.net',
    1 => 'oc.niedermayr.net',
    2 => 'nct.niedermayr.net',
  ),
  'datadirectory' => '/var/www/nc.niedermayr.net/data',
  'dbtype' => 'mysql',
  'version' => '9.1.0.16',
  'dbname' => 'oc_niedermayr_net',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_niedermayr_ne',
  'dbpassword' => '',
  'installed' => true,
  'defaultapp' => 'activity',
  'theme' => '',
  'maintenance' => false,
  'forcessl' => true,
  'secret' => '',
  'mail_from_address' => 'oc',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'niedermayr.net',
  'filelocking.enabled' => 'true',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
    0 => '/tmp/redis.sock',
    'port' => 6379,
    'timeout' => 0,
    'dbindex' => 0,
  ),
  'user_backends' => 
  array (
    0 => 
    array (
      'class' => 'OC_User_IMAP',
      'arguments' => 
      array (
        0 => '{XXXX:993/imap/ssl}INBOX',
      ),
    ),
  ),
  'loglevel' => 2,
  'trashbin_retention_obligation' => 'auto',
  'updater.release.channel' => 'stable',
);

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** yes/no

no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

yes, user_external (imap)

### Client configuration
**Browser:**

Palemoon X64 / Linux

**Operating system:**

Ubuntu 16.04

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

### PR DESCRIPTION
**Pull request by blizzz**
LDAP's checkPassword() always returned false, no matter whether the user who tried to log in could not be found on the server, or the server is unavailable. This was due to too broadly catching Exceptions, which now is fixed.

While debugging I figured out that ldap_search calls did not pass error processing in the wrapper, because of a different return format. 

In order to reproduce the whole thing I
1. set a breakpoint at https://github.com/nextcloud/server/blob/master/lib/private/User/Session.php#L632 (often it wouldn't stop, a breakpoint at L518 and some stepping helps then)
2.  I kept the client running, restarted the webserver, and changed something in the synced folder
3. When  the IDE stopped at the breakpoint, I turned of the LDAP server

When letting it go, usually the app password got revoked.

### CODE REVIEW

**Comment by blizzz** [comment]
@eggithub @laurentdinclaux @lephisto  could you check whether this solves your issues with #2431 ?

**Comment by eggithub** [comment]
@blizz I do not use LDAP...

**Comment by blizzz** [comment]
@eggithub how would I know? Please state your full setup in the original issue (ideally using https://raw.githubusercontent.com/nextcloud/server/master/issue_template.md)

**Comment by eggithub** [comment]
Hi @blizz,

You could not have known I don't use LDAP.  My issue is #2431. I'm not the one who made notice of this issue in the #2431, just that I mentioned also seeing app passwords disappear. I don't use any external authentication api, is all I can say for now. I'm heading back to #2431...

Cheers!

File: apps/user_ldap/lib/LDAP.php [hunk 1]
```diff
@@ -258,6 +258,31 @@ public function isResource($resource) {
...
+	 * @param $result
+	 * @return bool
+	 */
+	protected function isResultFalse($result) {
+		if($result === false) {
+			return true;
+		}
+
+		if($this->curFunc === 'ldap_search' && is_array($result)) {
+			foreach ($result as $singleResult) {
```
Comment (ChristophWurst) [inline apps/user_ldap/lib/LDAP.php]: I *think* we could simplify this with ``return in_array(false, $result, true)``

Comment (blizzz) [inline apps/user_ldap/lib/LDAP.php]: Yeah we could. With big results sets I expect this to be faster (not that it would matter to much). At least few years ago it was better to loop through an array, create a new one with those values as key and isset them over an in_array call. http://nickology.com/2012/07/03/php-faster-array-lookup-than-using-in_array/

**Review by ChristophWurst — APPROVED** [review]
Tested and works 👍 

I set up an LDAP user, created an app password and sent requests with curl. After turning off the LDAP server, requests fail with
```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\ServiceUnavailable</s:exception>
  <s:message>OC\ServerNotAvailableException: Lost connection to LDAP server.</s:message>
</d:error>
```
but the app password does not vanish.

**Review by LukasReschke — APPROVED** [review]

**Comment by oparoz** [comment]
Backport please @blizzz , we need this in for 11.0.2 :)

**Comment by blizzz** [comment]
Backport to stable11 goes https://github.com/nextcloud/server/pull/3493, reviewers needed :)
