### PR TITLE
limit ldap_dn columns to 4000

### LINKED ISSUE #31681: [Bug]: reduce ldap_dn field to 4000 bytes
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Oracle, by default, limits varchar2 types to 4000 bytes (cf. https://github.com/nextcloud/server/pull/31679). In https://github.com/nextcloud/server/blob/v22.2.5/apps/user_ldap/lib/Migration/Version1130Date20211102154716.php#L118-L122 we increase it from 255 to 4096 bytes, which may lead into invalid data conversion type issues (it seems).

### Steps to reproduce

1. have Oracle with MAX_STRING_SIZE set to Standard
2. upgrade from e.g. 22.2.3 to current stable22

### Expected behavior

Smooth upgrade

### Installation method

_No response_

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database engine version

Oracle

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

_No response_

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
not relevant
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by blizzz**
fixes #31681, satisfies #31679

### CODE REVIEW

File: apps/user_ldap/lib/Migration/Version1141Date20220323143801.php [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+
+			$qb = $this->dbc->getQueryBuilder();
+			$qb->select('ldap_dn')
+				->from($tableName)
+				->where($qb->expr()->gt($qb->createFunction($lengthExpr), '255', IQueryBuilder::PARAM_INT));
+
+			$result = $qb->executeQuery();
+			while($dn = $result->fetchOne()) {
+				if(mb_strlen($dn) > 4000) {
+					$dnsTooLong = [$dn];
```
Comment (nickvergessen) [inline apps/user_ldap/lib/Migration/Version1141Date20220323143801.php:43]:
```suggestion
					$dnsTooLong[] = $dn;
```
?

File: apps/user_ldap/lib/Migration/Version1141Date20220323143801.php [hunk 2]
```diff
@@ -0,0 +1,98 @@
+<?php
+
+declare(strict_types=1);
+
```
Comment (come-nc) [inline apps/user_ldap/lib/Migration/Version1141Date20220323143801.php:4]: Add copyright

File: apps/user_ldap/lib/Migration/Version1141Date20220323143801.php [hunk 3]
```diff
@@ -0,0 +1,98 @@
...
+use Closure;
+use OCP\DB\ISchemaWrapper;
+use OCP\DB\QueryBuilder\IQueryBuilder;
+use OCP\IDBConnection;
+use OCP\Migration\IOutput;
+use OCP\Migration\SimpleMigrationStep;
+
+/**
+ * Auto-generated migration step: Please modify to your needs!
```
Comment (come-nc) [inline apps/user_ldap/lib/Migration/Version1141Date20220323143801.php:15]: Remove comment

File: apps/user_ldap/lib/Migration/Version1141Date20220323143801.php [hunk 4]
```diff
@@ -0,0 +1,98 @@
...
+	 */
+	public function preSchemaChange(IOutput $output, Closure $schemaClosure, array $options): void {
+		foreach (['ldap_user_mapping', 'ldap_group_mapping'] as $tableName) {
+			$dnsTooLong = [];
+			$lengthExpr = $this->dbc->getDatabasePlatform()->getLengthExpression('ldap_dn');
+
+			$qb = $this->dbc->getQueryBuilder();
+			$qb->select('ldap_dn')
+				->from($tableName)
+				->where($qb->expr()->gt($qb->createFunction($lengthExpr), '255', IQueryBuilder::PARAM_INT));
```
Comment (come-nc) [inline apps/user_ldap/lib/Migration/Version1141Date20220323143801.php:38]: Why not 4000? because of the bytes vs char thing?

File: apps/user_ldap/lib/Migration/Version1141Date20220323143801.php [hunk 5]
```diff
@@ -0,0 +1,98 @@
...
+
+			$result = $qb->executeQuery();
+			while($dn = $result->fetchOne()) {
```
Comment (come-nc) [inline apps/user_ldap/lib/Migration/Version1141Date20220323143801.php:41]:
```suggestion
			while(($dn = $result->fetchOne()) !== false) {
```
Let’s be extra cautious with those now, we had trouble in the past.

File: apps/user_ldap/lib/Migration/Version1141Date20220323143801.php [hunk 6]
```diff
@@ -0,0 +1,98 @@
...
+			->where($qb->expr()->eq('ldap_dn', $qb->createParameter('originalDn')));
+
+		$pageSize = 1000;
+		$page = 0;
+		do {
+			$subset = array_slice($dns, $page * $pageSize, $pageSize);
+			try {
+				$this->dbc->beginTransaction();
+				foreach ($subset as $dn) {
+					$shortenedDN = mb_substr($dn, 0, 4000);
```
Comment (come-nc) [inline apps/user_ldap/lib/Migration/Version1141Date20220323143801.php:64]: Will that do any good? What is a mapping entry with an incomplete dn good for? These entries would actually be refused if it was new entries.

**Review by come-nc — COMMENTED** [review]
You also need to change the check in AbstractMapping::map
And I do not think the migration step for existing data is correct. Incomplete dn in mapping is just broken mapping lines which will appear as remnants for users and ghost for groups.
These lines should be deleted I suppose? Or the migration should just fail and we consider this an invalid previous state.

Realistically the case should not appear as maximum dn length was 255 not long ago and I would not expect anyone using >4000 dn.

Ok so actually maybe it’s good to truncate the lines because it will allow the admin to use the remnant system to clean up users. And they can see what the dn was to know which entry is concerned.
So maybe leave it like this but log which entries have been truncated?

**Comment by blizzz** [comment]
I got confirmation that the first commits unblocks update with Oracle for good.

File: apps/user_ldap/lib/Migration/Version1141Date20220323143801.php (hunk 2 above)
Comment (blizzz) [reply apps/user_ldap/lib/Migration/Version1141Date20220323143801.php:4]: Should be also fixed within `occ migration:generate` command.

File: apps/user_ldap/lib/Migration/Version1141Date20220323143801.php (hunk 4 above)
Comment (blizzz) [reply apps/user_ldap/lib/Migration/Version1141Date20220323143801.php:38]: > Why not 4000? because of the bytes vs char thing?

Yes, that was the thinking behind it.

File: apps/user_ldap/lib/Migration/Version1141Date20220323143801.php (hunk 6 above)
Comment (blizzz) [reply apps/user_ldap/lib/Migration/Version1141Date20220323143801.php:64]: Would they be refused? Maybe depends on DB, MySQL for instance would silently cut them short. I don't recall for other engines.

File: apps/user_ldap/lib/Migration/Version1141Date20220323143801.php (hunk 4 above)
Comment (come-nc) [reply apps/user_ldap/lib/Migration/Version1141Date20220323143801.php:57]: Can you review https://github.com/nextcloud/server/pull/31696 and once merged try to use it instead?

**Review by come-nc — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Comment by come-nc** [comment]
I do not understand the checkers failure, was there a composer update or something?
