### PR TITLE
[stable12] Fix email buttons for white theme

### LINKED ISSUE #7557: Button text in sharing email is invisible in case of a white primary color
### Steps to reproduce
1. Setup a custom themes
2. Define getColorPrimary to #FFFFFF (white)
3. Share a file and check the sharing email received

### Expected behaviour
The button text in the email should be visible 

### Actual behaviour
The button text invisible due to being white on white.

Some color are hard coded in EMailTemplate.php

### Server configuration

**Operating system**: Debian 9

**Web server:** apache 2.4

**Database:** Galera/MariaDB

**PHP version:** 7.0.19

**Nextcloud version:** 12.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:** 12.0.3 -> 12.0.4

**Where did you install Nextcloud from:** nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.5.2
  - apporder: 0.4.1
  - comments: 1.2.0
  - dav: 1.3.0
  - external: 2.0.3
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - twofactor_backupcodes: 1.1.1
  - twofactor_totp: 1.3.1
  - twofactor_u2f: 1.4.0
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - announcementcenter
  - encryption
  - files_external
  - nextcloud_announcements
  - systemtags
  - theming
  - user_external
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** 

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

### PR DESCRIPTION
**Pull request by MorrisJobke**
Backport of #7427
Fixes #7557 for stable12

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I just tested this and it works fine 👍

File: lib/public/Defaults.php [hunk 1]
```diff
@@ -212,4 +212,13 @@ public function buildDocLinkToKey($key) {
 	public function getTitle() {
 		return $this->defaults->getTitle();
 	}
+
+	/**
+	 * Returns primary color
+	 * @return string
+	 * @since 13.0.0
```
Comment (blizzz) [inline lib/public/Defaults.php]: back to the future?

Comment (MorrisJobke) [reply lib/public/Defaults.php]: Yes - but I just don't want to change it all the way - for this single time it is a bit off, but shouldn't hurt or does it? Because adding "since 12.0.5" doesn't add that much.

Comment (rullzer) [reply lib/public/Defaults.php]: Agreed. No app should really depend on it anyways as it isn't available in 12 in general.

**Review by rullzer — APPROVED** [review]

File: lib/public/Defaults.php (hunk 1 above)
Comment (blizzz) [reply lib/public/Defaults.php]: ok
