### PR TITLE
Fix GIF being converted when used as a login image

### LINKED ISSUE #16232: Basic Theming: "login image" always converted to JPEG format
### Steps to reproduce
1. Find great GIF animation to be used as a login image
2. Under "Theming" settings, upload as "Login image"
3. Log out of nextcloud to examine login image

### Expected behaviour
The GIF should stay animated.

### Actual behaviour
The GIF is converted to a JPEG image and becomes static.

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache

**Database:** Postgres

**PHP version:** 7.2

**Nextcloud version:** 16.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from v15

**Where did you install Nextcloud from:** Downloaded tgz from nextcloud.com

### Example image to use

44ydfcun

### PR DESCRIPTION
**Pull request by jacobneplokh**
Fixes #16232

- Added it to an if-statement where SVGs already are (as recommended by https://github.com/nextcloud/server/issues/16232#issuecomment-679920284)

Signed-off-by: Jacob Neplokh <me@jacobneplokh.com>

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
Sure, not great considering how big gifs can be, but what the hell :see_no_evil:

File: apps/theming/lib/ImageManager.php [hunk 1]
```diff
@@ -223,7 +223,7 @@ public function updateImage(string $key, string $tmpFile) {
 			throw new \Exception('Unsupported image type');
 		}
 
-		if ($key === 'background' && strpos($detectedMimeType, 'image/svg') === false) {
+		if ($key === 'background' && strpos($detectedMimeType, 'image/svg') || strpos($detectedMimeType, 'image/gif') === false) {
```
Comment (juliushaertl) [inline apps/theming/lib/ImageManager.php:226]:
```suggestion
		if ($key === 'background' && (strpos($detectedMimeType, 'image/svg') === false || strpos($detectedMimeType, 'image/gif') === false)) {
```

Otherwise this will not trigger on svg images anymore.

**Review by juliusknorr — CHANGES_REQUESTED** [review]
See inline.

File: apps/theming/lib/ImageManager.php [hunk 2]
```diff
@@ -223,7 +223,7 @@ public function updateImage(string $key, string $tmpFile) {
 			throw new \Exception('Unsupported image type');
 		}
 
-		if ($key === 'background' && strpos($detectedMimeType, 'image/svg') === false) {
+		if ($key === 'background' && (strpos($detectedMimeType, 'image/svg') === false || strpos($detectedMimeType, 'image/gif') === false)) {
```
Comment (juliushaertl) [inline apps/theming/lib/ImageManager.php:226]: Sorry, I was also proposing something wrong there. It should of course be converted only if not svg AND not gif:

```suggestion
		if ($key === 'background' && strpos($detectedMimeType, 'image/svg') === false && strpos($detectedMimeType, 'image/gif') === false) {
```

**Review by juliusknorr — APPROVED** [review]
