### PR TITLE
fix(caldav): convert iMip recipient name to a string

### LINKED ISSUE #36897: [Bug]: iMip Email: Invalid type of recipient name parameter
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Sending an iMip email fails because the constructor of `Symfony\Component\Mime\Address` expects a string but receives a `Sabre\VObject\Parameter` as its second parameter ($name).

### Steps to reproduce

1. Create an event.
2. Trigger dispatching an iMip message (e.g. by changing it).
3. Look at the server log.

### Expected behavior

The message should be dispatched and there shouldn't be an error.

### Installation method

None

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
c.nc.c
```

### List of activated Apps

```shell
c.nc.c
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

```shell
{
  "level": 3,
  "app": "webdav",
  "method": "PUT",
  "url": "remote.php/dav/calendars/REDACTED",
  "message": "Symfony\\Component\\Mime\\Address::__construct(): Argument #2 ($name) must be of type string, Sabre\\VObject\\Parameter given, called in REDACTED/nextcloud/lib/private/Mail/Message.php on line 96",
  "version": "26.0.0.7",
  "exception": {
    "Exception": "TypeError",
    "Message": "Symfony\\Component\\Mime\\Address::__construct(): Argument #2 ($name) must be of type string, Sabre\\VObject\\Parameter given, called in REDACTED/nextcloud/lib/private/Mail/Message.php on line 96",
    "Code": 0,
    "Trace": [
      {
        "file": "REDACTED/nextcloud/lib/private/Mail/Message.php",
        "line": 96,
        "function": "__construct",
        "class": "Symfony\\Component\\Mime\\Address",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***",
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "function": "OC\\Mail\\{closure}",
        "class": "OC\\Mail\\Message",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "REDACTED/nextcloud/lib/private/Mail/Message.php",
        "line": 98,
        "function": "array_walk",
        "args": [
          [
            "*** sensitive parameters replaced ***"
          ],
          [
            "Closure"
          ]
        ]
      },
      {
        "file": "REDACTED/nextcloud/lib/private/Mail/Message.php",
        "line": 288,
        "function": "convertAddresses",
        "class": "OC\\Mail\\Message",
        "type": "->",
        "args": [
          [
            "*** sensitive parameters replaced ***"
          ]
        ]
      },
      {
        "file": "REDACTED/nextcloud/lib/private/Mail/Mailer.php",
        "line": 194,
        "function": "setRecipients",
        "class": "OC\\Mail\\Message",
        "type": "->",
        "args": []
      },
      {
        "file": "REDACTED/nextcloud/apps/dav/lib/CalDAV/Schedule/IMipPlugin.php",
        "line": 298,
        "function": "send",
        "class": "OC\\Mail\\Mailer",
        "type": "->",
        "args": [
          [
            "OC\\Mail\\Message"
          ]
        ]
      },
      {
        "file": "REDACTED/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "schedule",
        "class": "OCA\\DAV\\CalDAV\\Schedule\\IMipPlugin",
        "type": "->",
        "args": [
          [
            "Sabre\\VObject\\ITip\\Message",
            "a3a48f5a-be54-43c3-9ff3-ea0149a70251",
            "VEVENT",
            "REPLY",
            2,
            "*** sensitive parameters replaced ***",
            "*** sensitive parameters replaced ***",
            "*** sensitive parameters replaced ***",
            "*** sensitive parameters replaced ***",
            "1.2;Message delivered locally",
            [
              "Sabre\\VObject\\Component\\VCalendar",
              "*** sensitive parameters replaced ***",
              "VCALENDAR"
            ],
            true
          ]
        ]
      },
      {
        "file": "REDACTED/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php",
        "line": 350,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "schedule",
          [
            [
              "Sabre\\VObject\\ITip\\Message",
              "a3a48f5a-be54-43c3-9ff3-ea0149a70251",
              "VEVENT",
              "REPLY",
              2,
              "*** sensitive parameters replaced ***",
              "*** sensitive parameters replaced ***",
              "*** sensitive parameters replaced ***",
              "*** sensitive parameters replaced ***",
              "1.2;Message delivered locally",
              [
                "Sabre\\VObject\\Component\\VCalendar",
                "*** sensitive parameters replaced ***",
                "VCALENDAR"
              ],
              true
            ]
          ]
        ]
      },
      {
        "file": "REDACTED/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php",
        "line": 627,
        "function": "deliver",
        "class": "Sabre\\CalDAV\\Schedule\\Plugin",
        "type": "->",
        "args": [
          [
            "Sabre\\VObject\\ITip\\Message",
            "a3a48f5a-be54-43c3-9ff3-ea0149a70251",
            "VEVENT",
            "REPLY",
            2,
            "*** sensitive parameters replaced ***",
            "*** sensitive parameters replaced ***",
            "*** sensitive parameters replaced ***",
            "*** sensitive parameters replaced ***",
            "1.2;Message delivered locally",
            [
              "Sabre\\VObject\\Component\\VCalendar",
              "*** sensitive parameters replaced ***",
              "VCALENDAR"
            ],
            true
          ]
        ]
      },
      {
        "file": "REDACTED/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php",
        "line": 337,
        "function": "processICalendarChange",
        "class": "Sabre\\CalDAV\\Schedule\\Plugin",
        "type": "->",
        "args": [
          [
            "Sabre\\VObject\\Component\\VCalendar",
            "*** sensitive parameters replaced ***",
            "VCALENDAR"
          ],
          [
            "Sabre\\VObject\\Component\\VCalendar",
            "*** sensitive parameters replaced ***",
            "VCALENDAR"
          ],
          [
            "*** sensitive parameters replaced ***",
            "/remote.php/dav/principals/REDACTED"
          ],
          [],
          true
        ]
      },
      {
        "file": "REDACTED/nextcloud/apps/dav/lib/CalDAV/Schedule/Plugin.php",
        "line": 165,
        "function": "calendarObjectChange",
        "class": "Sabre\\CalDAV\\Schedule\\Plugin",
        "type": "->",
        "args": [
          [
            "Sabre\\HTTP\\Request"
          ],
          [
            "Sabre\\HTTP\\Response"
          ],
          [
            "Sabre\\VObject\\Component\\VCalendar",
            "*** sensitive parameters replaced ***",
            "VCALENDAR"
          ],
          "calendars/REDACTED",
          true,
          false
        ]
      },
      {
        "file": "REDACTED/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "calendarObjectChange",
        "class": "OCA\\DAV\\CalDAV\\Schedule\\Plugin",
        "type": "->",
        "args": [
          [
            "Sabre\\HTTP\\Request"
          ],
          [
            "Sabre\\HTTP\\Response"
          ],
          [
            "Sabre\\VObject\\Component\\VCalendar",
            "*** sensitive parameters replaced ***",
            "VCALENDAR"
          ],
          "calendars/REDACTED",
          true,
          false
        ]
      },
      {
        "file": "REDACTED/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php",
        "line": 897,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "calendarObjectChange",
          [
            [
              "Sabre\\HTTP\\Request"
            ],
            [
              "Sabre\\HTTP\\Response"
            ],
            [
              "Sabre\\VObject\\Component\\VCalendar",
              "*** sensitive parameters replaced ***",
              "VCALENDAR"
            ],
            "*** sensitive parameters replaced ***",
            true,
            "And 1 more entries, set log level to debug to see all entries"
          ]
        ]
      },
      {
        "file": "REDACTED/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php",
        "line": 739,
        "function": "validateICalendar",
        "class": "Sabre\\CalDAV\\Plugin",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***",
          "*** sensitive parameters replaced ***",
          false,
          [
            "Sabre\\HTTP\\Request"
          ],
          [
            "Sabre\\HTTP\\Response"
          ],
          false
        ]
      },
      {
        "file": "REDACTED/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "beforeWriteContent",
        "class": "Sabre\\CalDAV\\Plugin",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***",
          [
            "OCA\\DAV\\CalDAV\\CalendarObject"
          ],
          "*** sensitive parameters replaced ***",
          false
        ]
      },
      {
        "file": "REDACTED/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 1133,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "beforeWriteContent",
          [
            "*** sensitive parameters replaced ***",
            [
              "OCA\\DAV\\CalDAV\\CalendarObject"
            ],
            "*** sensitive parameters replaced ***",
            false
          ]
        ]
      },
      {
        "file": "REDACTED/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
        "line": 492,
        "function": "updateFile",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "REDACTED/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "httpPut",
        "class": "Sabre\\DAV\\CorePlugin",
        "type": "->",
        "args": [
          [
            "Sabre\\HTTP\\Request"
          ],
          [
            "Sabre\\HTTP\\Response"
          ]
        ]
      },
      {
        "file": "REDACTED/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 472,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "method:PUT",
          [
            [
              "Sabre\\HTTP\\Request"
            ],
            [
              "Sabre\\HTTP\\Response"
            ]
          ]
        ]
      },
      {
        "file": "REDACTED/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 253,
        "function": "invokeMethod",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          [
            "Sabre\\HTTP\\Request"
          ],
          [
            "Sabre\\HTTP\\Response"
          ]
        ]
      },
      {
        "file": "REDACTED/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 321,
        "function": "start",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "REDACTED/nextcloud/apps/dav/lib/Server.php",
        "line": 363,
        "function": "exec",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "REDACTED/nextcloud/apps/dav/appinfo/v2/remote.php",
        "line": 35,
        "function": "exec",
        "class": "OCA\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "REDACTED/nextcloud/remote.php",
        "line": 171,
        "args": [
          "REDACTED/nextcloud/apps/dav/appinfo/v2/remote.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "REDACTED/nextcloud/3rdparty/symfony/mime/Address.php",
    "Line": 42,
    "message": "Symfony\\Component\\Mime\\Address::__construct(): Argument #2 ($name) must be of type string, Sabre\\VObject\\Parameter given, called in REDACTED/nextcloud/lib/private/Mail/Message.php on line 96",
    "exception": {},
    "CustomMessage": "Symfony\\Component\\Mime\\Address::__construct(): Argument #2 ($name) must be of type string, Sabre\\VObject\\Parameter given, called in REDACTED/nextcloud/lib/private/Mail/Message.php on line 96"
  }
}
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by st3iny**
* Resolves: #36897
* (Possible) Regression of: #35743 (backports are still pending!)

## Summary

The recipient name is expected to be a string or null. Before this PR, it was a `Sabre\VObject\Parameter` so we need to convert it to a string.

The `\Sabre\VObject\ITip\Message::$recipientName` property should be string or null and is wrongly annotated upstream (in Sabre).

```php
    /**
     * The name of the recipient. This is usually populated with the CN
     * parameter from the ATTENDEE or ORGANIZER property, if it's available.
     *
     * @var string|null
     */
    public $recipientName;
```

## TODO

- [ ] Trigger backports when backports of #35743 were merged 

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/dav/lib/CalDAV/Schedule/IMipPlugin.php [hunk 1]
```diff
@@ -174,6 +174,9 @@ public function schedule(Message $iTipMessage) {
 			return;
 		}
 		$recipientName = $iTipMessage->recipientName ?: null;
+		if (!is_null($recipientName) && !is_string($recipientName)) {
+			$recipientName = (string)$recipientName;
+		}
```
Comment (tcitworld) [inline apps/dav/lib/CalDAV/Schedule/IMipPlugin.php:179]: **suggestion:** Three lines less, still understandable to me
```suggestion
		$recipientName = $iTipMessage->recipientName ? (string)$iTipMessage->recipientName : null;
```

**Review by tcitworld — APPROVED** [review]

File: apps/dav/lib/CalDAV/Schedule/IMipPlugin.php (hunk 1 above)
Comment (st3iny) [reply apps/dav/lib/CalDAV/Schedule/IMipPlugin.php:179]: The ternary operator makes sense here. I applied your suggestion.

**Review by nickvergessen — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Comment by nickvergessen** [comment]
Applied on our instance

**Comment by nickvergessen** [comment]
Now errors a bit further down, as it assumes `$this->userId` would be set.
```
{
  "reqId": "aYk6tC4vpMagsgJaEjAU",
  "level": 3,
  "time": "2023-03-01T08:04:12+00:00",
  "remoteAddr": "2a02:8108:3240:3d0c:71a9:1fac:9e03:e514",
  "user": "…",
  "app": "webdav",
  "method": "PUT",
  "url": "/remote.php/dav/calendars/…/…/cf33c5ec-….ics",
  "message": "OC\\User\\Manager::getDisplayName(): Argument #1 ($uid) must be of type string, null given, called in /var/www/cloud.nextcloud.com/nextcloud/apps/dav/lib/CalDAV/Schedule/IMipPlugin.php on line 213",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Thunderbird/102.8.0",
  "version": "26.0.0.7",
  "exception": {
    "Exception": "TypeError",
    "Message": "OC\\User\\Manager::getDisplayName(): Argument #1 ($uid) must be of type string, null given, called in /var/www/cloud.nextcloud.com/nextcloud/apps/dav/lib/CalDAV/Schedule/IMipPlugin.php on line 213",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/cloud.nextcloud.com/nextcloud/apps/dav/lib/CalDAV/Schedule/IMipPlugin.php",
        "line": 213,
        "function": "getDisplayName",
        "class": "OC\\User\\Manager",
        "type": "->",
        "args": [
          null
        ]
      },
      {
        "file": "/var/www/cloud.nextcloud.com/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "schedule",
        "class": "OCA\\DAV\\CalDAV\\Schedule\\IMipPlugin",
        "type": "->",
        "args": [
          [
            "Sabre\\VObject\\ITip\\Message",
            "cf33c5ec-…",
            "VEVENT",
            "REQUEST",
            1,
            "mailto:f…",
            null,
            "mailto:s…",
            null,
            "1.2;Message delivered locally",
            [
              "Sabre\\VObject\\Component\\VCalendar",
              null,
              "VCALENDAR"
            ],
            true
          ]
        ]
      },
      {
        "file": "/var/www/cloud.nextcloud.com/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php",
        "line": 350,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "schedule",
          [
            [
              "Sabre\\VObject\\ITip\\Message",
              "cf33c5ec-…",
              "VEVENT",
              "REQUEST",
              1,
              "mailto:f…",
              null,
              "mailto:s…",
              null,
              "1.2;Message delivered locally",
              [
                "Sabre\\VObject\\Component\\VCalendar",
                null,
                "VCALENDAR"
              ],
              true
            ]
          ]
        ]
      },
      {
        "file": "/var/www/cloud.nextcloud.com/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php",
        "line": 627,
        "function": "deliver",
        "class": "Sabre\\CalDAV\\Schedule\\Plugin",
        "type": "->",
        "args": [
          [
            "Sabre\\VObject\\ITip\\Message",
            "cf33c5ec-…",
            "VEVENT",
            "REQUEST",
            1,
            "mailto:f…",
            null,
            "mailto:s…",
            null,
            "1.2;Message delivered locally",
            [
              "Sabre\\VObject\\Component\\VCalendar",
              null,
              "VCALENDAR"
            ],
            true
          ]
        ]
      },
      {
        "file": "/var/www/cloud.nextcloud.com/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php",
        "line": 337,
        "function": "processICalendarChange",
        "class": "Sabre\\CalDAV\\Schedule\\Plugin",
        "type": "->",
        "args": [
          null,
          [
            "Sabre\\VObject\\Component\\VCalendar",
            null,
            "VCALENDAR"
          ],
          [
            "mailto:f…",
            "/remote.php/dav/principals/users/…/"
          ],
          [],
          true
        ]
      },
      {
        "file": "/var/www/cloud.nextcloud.com/nextcloud/apps/dav/lib/CalDAV/Schedule/Plugin.php",
        "line": 165,
        "function": "calendarObjectChange",
        "class": "Sabre\\CalDAV\\Schedule\\Plugin",
        "type": "->",
        "args": [
          [
            "Sabre\\HTTP\\Request"
          ],
          [
            "Sabre\\HTTP\\Response"
          ],
          [
            "Sabre\\VObject\\Component\\VCalendar",
            null,
            "VCALENDAR"
          ],
          "calendars/…/…",
          true,
          true
        ]
      },
      {
        "file": "/var/www/cloud.nextcloud.com/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "calendarObjectChange",
        "class": "OCA\\DAV\\CalDAV\\Schedule\\Plugin",
        "type": "->",
        "args": [
          [
            "Sabre\\HTTP\\Request"
          ],
          [
            "Sabre\\HTTP\\Response"
          ],
          [
            "Sabre\\VObject\\Component\\VCalendar",
            null,
            "VCALENDAR"
          ],
          "calendars/…/…",
          true,
          true
        ]
      },
      {
        "file": "/var/www/cloud.nextcloud.com/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php",
        "line": 897,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "calendarObjectChange",
          [
            [
              "Sabre\\HTTP\\Request"
            ],
            [
              "Sabre\\HTTP\\Response"
            ],
            [
              "Sabre\\VObject\\Component\\VCalendar",
              null,
              "VCALENDAR"
            ],
            "calendars/…/…",
            true,
            "And 1 more entries, set log level to debug to see all entries"
          ]
        ]
      },
      {
        "file": "/var/www/cloud.nextcloud.com/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php",
        "line": 766,
        "function": "validateICalendar",
        "class": "Sabre\\CalDAV\\Plugin",
        "type": "->",
        "args": [
          "BEGIN:VCALENDAR\r\n…",
          "calendars/…/…/cf33c5ec-….ics",
          false,
          [
            "Sabre\\HTTP\\Request"
          ],
          [
            "Sabre\\HTTP\\Response"
          ],
          true
        ]
      },
      {
        "file": "/var/www/cloud.nextcloud.com/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "beforeCreateFile",
        "class": "Sabre\\CalDAV\\Plugin",
        "type": "->",
        "args": [
          "calendars/…/…/cf33c5ec-….ics",
          "BEGIN:VCALENDAR\r\nPRODID…",
          [
            "OCA\\DAV\\CalDAV\\Calendar"
          ],
          false
        ]
      },
      {
        "file": "/var/www/cloud.nextcloud.com/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 1094,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "beforeCreateFile",
          [
            "calendars/…/…/cf33c5ec-….ics",
            "BEGIN:VCALENDAR\r\nPRODID…",
            [
              "OCA\\DAV\\CalDAV\\Calendar"
            ],
            false
          ]
        ]
      },
      {
        "file": "/var/www/cloud.nextcloud.com/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
        "line": 504,
        "function": "createFile",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "calendars/…/…/cf33c5ec-….ics",
          "BEGIN:VCALENDAR\r\nPRODID…",
          null
        ]
      },
      {
        "file": "/var/www/cloud.nextcloud.com/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "httpPut",
        "class": "Sabre\\DAV\\CorePlugin",
        "type": "->",
        "args": [
          [
            "Sabre\\HTTP\\Request"
          ],
          [
            "Sabre\\HTTP\\Response"
          ]
        ]
      },
      {
        "file": "/var/www/cloud.nextcloud.com/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 472,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "method:PUT",
          [
            [
              "Sabre\\HTTP\\Request"
            ],
            [
              "Sabre\\HTTP\\Response"
            ]
          ]
        ]
      },
      {
        "file": "/var/www/cloud.nextcloud.com/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 253,
        "function": "invokeMethod",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          [
            "Sabre\\HTTP\\Request"
          ],
          [
            "Sabre\\HTTP\\Response"
          ]
        ]
      },
      {
        "file": "/var/www/cloud.nextcloud.com/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 321,
        "function": "start",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/cloud.nextcloud.com/nextcloud/apps/dav/lib/Server.php",
        "line": 363,
        "function": "exec",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/cloud.nextcloud.com/nextcloud/apps/dav/appinfo/v2/remote.php",
        "line": 35,
        "function": "exec",
        "class": "OCA\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/cloud.nextcloud.com/nextcloud/remote.php",
        "line": 171,
        "args": [
          "/var/www/cloud.nextcloud.com/nextcloud/apps/dav/appinfo/v2/remote.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/var/www/cloud.nextcloud.com/nextcloud/lib/private/User/Manager.php",
    "Line": 193,
    "message": "OC\\User\\Manager::getDisplayName(): Argument #1 ($uid) must be of type string, null given, called in /var/www/cloud.nextcloud.com/nextcloud/apps/dav/lib/CalDAV/Schedule/IMipPlugin.php on line 213",
    "exception": {},
    "CustomMessage": "OC\\User\\Manager::getDisplayName(): Argument #1 ($uid) must be of type string, null given, called in /var/www/cloud.nextcloud.com/nextcloud/apps/dav/lib/CalDAV/Schedule/IMipPlugin.php on line 213"
  }
}
```
