### PR TITLE
Fix duplicate event email notifications

### LINKED ISSUE #21370: Calendar sends duplicate notifications if there is an additional attendee [$250]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce

The calendar normally sends one notification (whether push or email) around the specified time for events that do not have attendees.
This also works correctly for shared calendars, every user with whom the calendar & event is shared receives one notification.
However, if I add an event to a non-shared calendar and add an attendee, both I and the attendee will receive two notifications for each notification event. This happens both with push and email notifications.
Is this a known issue? A cursory search here in Github didn't come up with anything relating to calendar notifications.

- Create calendar event on non-shared calendar
- Add a notification for x minutes before event, set to email
- Add an attendee that has an email address
- Ensure 'send email' is checked on attendee

Expected behaviour:

Organiser and attendee each receive one single email notification.

Actual behaviour:

Organiser and attendee each receive TWO email notifications, at the same time.
This also happens if notifications are pushed to an installed Nextcloud app on a mobile device.

Setup:

Ubuntu 18.04.3 LTS
Nextcloud 18.0.4 via Snap
No security or setup warnings on admin panel

### PR DESCRIPTION
**Pull request by st3iny**
Fix #21370

### This PR incorporates 2 fixes:
1. VALARMs shouldn't be propagated to attendees via iTIP (not mandatory but recommended by RFC).
2. Multiple email notifications are dispatched because there is no differentiation between when the owning user is the organizer of an event and when the owning user is an attendee.
3. ~The email of the organizer was never extracted properly because the usage of `strcasecmp($organizer->getValue(), 'mailto:') !== 0` was wrong. This lead to the `Reply-To` header not being set.~ -> **Moved to a separate PR because it's not related.**

### Preparations

1. Have at least 2 users.
4. Configure your instance to be able to send emails.
5. Enable instant event reminder sending: `occ config:app:set dav sendEventRemindersMode --value occ`
6. Apply the following patch to make testing easier (by ignoring actual trigger date and time):
```diff
diff --git a/apps/dav/lib/CalDAV/Reminder/Backend.php b/apps/dav/lib/CalDAV/Reminder/Backend.php
index b0476e9594c..74a980d3f91 100644
--- a/apps/dav/lib/CalDAV/Reminder/Backend.php
+++ b/apps/dav/lib/CalDAV/Reminder/Backend.php
@@ -66,7 +66,6 @@ class Backend {
 		$query = $this->db->getQueryBuilder();
 		$query->select(['cr.*', 'co.calendardata', 'c.displayname', 'c.principaluri'])
 			->from('calendar_reminders', 'cr')
-			->where($query->expr()->lte('cr.notification_date', $query->createNamedParameter($this->timeFactory->getTime())))
 			->join('cr', 'calendarobjects', 'co', $query->expr()->eq('cr.object_id', 'co.id'))
 			->join('cr', 'calendars', 'c', $query->expr()->eq('cr.calendar_id', 'c.id'));
 		$stmt = $query->execute();
```

### Routine

1. Create a new event with at least one email reminder (trigger date and time don't matter).
2. Add the other user as an attendee.
3. Save the event.
4. Trigger reminder sending: `occ dav:send-event-reminders`
7. Observe that each users receives a **single** reminder email -> **Duplicate emails fixed** :heavy_check_mark: 
8. Login with the other user (which is an attendee).
9. Observe that there are no reminders on the incoming event -> **ALARMS shouldn't be propagated (recommended by the RFC)** :heavy_check_mark: 
10. Add a *"private"* email reminder to my local copy.
11. Save the event and trigger reminder sending again.
12. Observe that **only** I (the attendee) receive an email -> **Only the email reminders of organizers should be sent to all attendees** :heavy_check_mark:

### CODE REVIEW

File: apps/dav/lib/CalDAV/Reminder/ReminderService.php [hunk 1]
```diff
@@ -171,16 +172,18 @@ public function processReminders() :void {
 			}
 
 			$user = $this->getUserFromPrincipalURI($reminder['principaluri']);
+			$userEmailAddress = null;
 			if ($user) {
 				$users[] = $user;
+				$userEmailAddress = $user->getEMailAddress();
```
Comment (tcitworld) [inline apps/dav/lib/CalDAV/Reminder/ReminderService.php:178]: I'm wondering if we shouldn't consider the user's additional emails as well, as they are registered for `alternate-URI-set` and `calendar-user-address-set` since https://github.com/nextcloud/server/pull/31029.

Comment (st3iny) [reply apps/dav/lib/CalDAV/Reminder/ReminderService.php:178]: Great idea! We could even use that in the frontend to determine if a user is the organizer or an attendee of an event. Currently, the logic is also using the primary user email and breaks if it's changed.

Comment (st3iny) [reply apps/dav/lib/CalDAV/Reminder/ReminderService.php:178]: The email addresses of `email-address`, `alternate-URI-set`, `calendar-user-address-set` and `email-address-set` are also checked now.

**Review by tcitworld — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]
Code looks good and I can follow it for the most part :+1:

**Review by miaulalala — APPROVED** [review]
:heart:
