### PR TITLE
Use NavigationManager instead of AppManager to handle custom apps order

### LINKED ISSUE #47479: [Bug]: "Could not set global default apps"
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Cannot set an external link as the global default app

### Steps to reproduce

1. Install app: External sites
2. Create an external site (will show up on top bar)
3. Install app: Theming
4. Go to Administration settings > Theming
5. Turn on: Use custom default app
6. X out one of the existing ones (there seems to be a limit of two)
7. Add your own external site that you created above

### Expected behavior

External site is added as the custom default app

---

Actual behavior: error message:

> Could not set global default apps

Screenshot 2024-08-23 at 13 36 31

### Installation method

Official All-in-One appliance

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by provokateurin**
* Resolves: https://github.com/nextcloud/server/issues/47479

## Summary

The custom defaults "apps" and order were using the apps and not navigation entries (see the linked issue for more details).
The confusion lead to a few problems that can only be solved by only using the NavigationManager and not the AppManager.
Most of the logic is the same, except for checking against available navigation entries and not apps.

I tried touching as little as possible, all the frontend code is still the same and uses the incorrect "app" over "navigation entry" concept. On the frontend it still makes a bit sense, since the concept is a lot easier to grasp for users.
The config keys on the backend are kept the same to avoid migrations and deprecations.

In theory one could spend a lot more time on trying to fix this, but I already tried that a bit and it is a rabbit hole that is too deep for fixing and backporting.

The last commit is a fix that is useful even without all the other changes. In case an app is disabled while also being used for a custom order, the frontend would display "undefined" entries.

As for backporting, I kept the old broken interface by providing a proxy implementation. I hope this is good enough to be backported.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: lib/private/App/AppManager.php [hunk 1]
```diff
@@ -82,6 +83,14 @@ public function __construct(
 	) {
 	}
 
+	private function getNavigationManager(): INavigationManager {
+		if ($this->navigationManager !== null) {
+			return $this->navigationManager;
+		}
+		$this->navigationManager = \OCP\Server::get(INavigationManager::class);
```
Comment (susnux) [inline lib/private/App/AppManager.php:90]: Could save one line ;)

```suggestion
		if ($this->navigationManager === null) {
			$this->navigationManager = \OCP\Server::get(INavigationManager::class);
		}
```

File: lib/private/URLGenerator.php [hunk 2]
```diff
@@ -288,14 +298,14 @@ public function linkToDefaultPageUrl(): string {
...
-		$appId = $this->getAppManager()->getDefaultAppForUser();
-
-		if ($this->config->getSystemValueBool('htaccess.IgnoreFrontController', false)
-			|| getenv('front_controller_active') === 'true') {
-			return $this->getAbsoluteURL('/apps/' . $appId . '/');
+		$entryId = $this->getNavigationManager()->getDefaultEntryIdForUser();
+		$entry = $this->getNavigationManager()->get($entryId);
+		$href = (string)$entry['href'];
+		if ($href === '') {
+			throw new \InvalidArgumentException('Missing href');
```
Comment (susnux) [inline lib/private/URLGenerator.php:305]:
```suggestion
			throw new \InvalidArgumentException('Default navigation entry is missing href');
```

File: tests/lib/App/AppManagerTest.php [hunk 3]
```diff
@@ -733,159 +733,6 @@ public function testGetAppRestriction() {
 		$this->assertEquals(['foo'], $this->manager->getAppRestriction('test3'));
 	}
 
-	public function provideDefaultApps(): array {
```
Comment (susnux) [inline tests/lib/App/AppManagerTest.php:736]: The function still exists, no?

Comment (susnux) [reply tests/lib/App/AppManagerTest.php:736]: It is deprecated right? I saw you added tests for the new functions, so that would be enough for me :)

Comment (provokateurin) [reply tests/lib/App/AppManagerTest.php:736]: Yes. The new test is just the same as this removed test but adapted to the changes.

File: lib/private/App/AppManager.php [hunk 4]
```diff
@@ -820,60 +828,42 @@ public function getDefaultEnabledApps(): array {
...
+	 * @inheritdoc
+	 */
 	public function getDefaultApps(): array {
-		return explode(',', $this->config->getSystemValueString('defaultapp', 'dashboard,files'));
+		$ids = $this->getNavigationManager()->getDefaultEntryIds();
+
+		return array_map(function (string $id) {
+			$entry = $this->getNavigationManager()->get($id);
+			return (string)$entry['app'];
+		}, $ids);
```
Comment (come-nc) [inline lib/private/App/AppManager.php:849]:
```suggestion
		return array_values(array_unique(array_map(function (string $id) {
			$entry = $this->getNavigationManager()->get($id);
			return (string)$entry['app'];
		}, $ids)));
```
Should remove duplicates, no?

File: lib/private/NavigationManager.php [hunk 5]
```diff
@@ -93,7 +101,7 @@ public function add($entry) {
 			}
 
 			// This is the default app that will always be shown first
-			$entry['default'] = ($entry['app'] ?? false) === $this->defaultApp;
+			$entry['default'] = ($entry['app'] ?? false) === $this->defaultEntry;
```
Comment (come-nc) [inline lib/private/NavigationManager.php:104]: This is comparing app id with entry id, no?

File: lib/private/NavigationManager.php [hunk 6]
```diff
@@ -401,4 +409,80 @@ private function isSubadmin() {
...
+
+	public function get(string $id): array|null {
+		foreach ($this->getAll() as $entry) {
+			if ($entry['id'] === $id) {
+				return $entry;
+			}
+		}
+
+		return null;
+	}
```
Comment (come-nc) [inline lib/private/NavigationManager.php:421]: Looks innefficient, should we add an index? How often is that called?

File: lib/private/NavigationManager.php [hunk 7]
```diff
@@ -401,4 +409,80 @@ private function isSubadmin() {
...
+		}
+		return array_filter($ids);
+	}
+
+	public function setDefaultEntryIds(array $ids): void {
+		$entryIds = array_map(static fn (array $entry) => $entry['id'], $this->getAll());
+
+		foreach ($ids as $id) {
+			if (!in_array($id, $entryIds, true)) {
+				$this->logger->debug('Can not set unavailable entry as default entry', ['missing_entry' => $id]);
```
Comment (come-nc) [inline lib/private/NavigationManager.php:481]:
```suggestion
				$this->logger->debug('Cannot set unavailable entry as default entry', ['missing_entry' => $id]);
```

File: lib/private/TemplateLayout.php [hunk 8]
```diff
@@ -99,11 +99,10 @@ public function __construct($renderAs, $appId = '') {
 			$logoUrl = $this->config->getSystemValueString('logo_url', '');
 			$this->assign('logoUrl', $logoUrl);
 
-			// Set default app name
-			$defaultApp = \OC::$server->getAppManager()->getDefaultAppForUser();
-			$defaultAppInfo = \OC::$server->getAppManager()->getAppInfo($defaultApp);
-			$l10n = \OC::$server->get(IFactory::class)->get($defaultApp);
-			$this->assign('defaultAppName', $l10n->t($defaultAppInfo['name']));
+			// Set default entry name
+			$defaultEntryId = \OC::$server->getNavigationManager()->getDefaultEntryIdForUser();
```
Comment (come-nc) [inline lib/private/TemplateLayout.php:103]:
```suggestion
			$defaultEntryId = \OCP\Server::get(INavigationManager::class)->getDefaultEntryIdForUser();
```
Same for the other line.

**Review by come-nc — COMMENTED** [review]
What happens if you actually set an external site as default entry, you cannot use Nextcloud anymore? (login would redirect to external site, no?)

File: lib/private/App/AppManager.php (hunk 1 above)
Comment (come-nc) [reply lib/private/App/AppManager.php]: Could save all of them:
```php
return $this->navigationManager ??= \OCP\Server::get(INavigationManager::class);
```

But who’s counting?

**Comment by come-nc** [comment]
Is the comment in https://github.com/nextcloud/server/blob/558877c8422c1a7083d083b2fe0be553f3047ba0/config/config.sample.php#L1169-L1178 still true after your PR is merged?

File: lib/private/NavigationManager.php (hunk 6 above)
Comment (provokateurin) [reply lib/private/NavigationManager.php:421]: Agreed, I already found it weird that the entries are a list and not a hashmap.

Comment (provokateurin) [reply lib/private/NavigationManager.php:421]: Ah it already is, I just didn't check...

**Comment by provokateurin** [comment]
Cypress failure is related for once :sweat_smile:

**Comment by provokateurin** [comment]
Fix will not be backported to any version due to the new interfaces and the close release of 30.

File: lib/private/URLGenerator.php [hunk 9]
```diff
@@ -288,14 +298,17 @@ public function linkToDefaultPageUrl(): string {
...
-		if ($this->config->getSystemValueBool('htaccess.IgnoreFrontController', false)
-			|| getenv('front_controller_active') === 'true') {
-			return $this->getAbsoluteURL('/apps/' . $appId . '/');
+		$entryId = $this->getNavigationManager()->getDefaultEntryIdForUser();
+		$entry = $this->getNavigationManager()->get($entryId);
+		$href = (string)$entry['href'];
+		if ($href === '') {
+			throw new \InvalidArgumentException('Default navigation entry is missing href: ' . $entryId);
+		}
+		if (str_starts_with($href, '/index.php/') && ($this->config->getSystemValueBool('htaccess.IgnoreFrontController', false) || getenv('front_controller_active') === 'true')) {
```
Comment (come-nc) [inline lib/private/URLGenerator.php:307]: Does that check works on instances with pretty url without the index.php?

Comment (provokateurin) [reply lib/private/URLGenerator.php:307]: The check is exactly for that purpose. It will only change the href if pretty-urls are available. We should create a common function for this check as it is used a few times in multiple places and it's not really self-explanatory.

**Review by come-nc — APPROVED** [review]

**Comment by provokateurin** [comment]
Cypress issues are resolved (caused by bugs in the backend). @susnux can you review again?

**Review by susnux — APPROVED** [review]

**Comment by nickvergessen** [comment]
This actually broke the guests app, which is going nasty stuff:
https://github.com/nextcloud/guests/blob/master/lib/FilteredNavigationManager.php
