### PR TITLE
fix(setup-checks): Ensure URL with webroot works

### LINKED ISSUE #45033: [Bug]: NC29  .well-known URLs, failed on: /.well-known/caldav
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

With NC28 I had no well-known URL errors, and no change to the NGINX configuration. After upgrading to NC29, I now have the following message: 
`Your web server is not properly set up to resolve .well-known URLs, failed on: /.well-known/caldav For more details see the [documentation ↗](https://docs.nextcloud.com/server/29/go.php?to=admin-setup-well-known-URL).`

In the NGINX logs, I see a 401 errors:
```
192.168.9.6 - - [25/Apr/2024:13:02:21 +0000] "PROPFIND /.well-known/caldav HTTP/1.1" 301 162 "-" "Nextcloud Server Crawler"
192.168.9.6 - - [25/Apr/2024:13:02:21 +0000] "GET /remote.php/dav HTTP/1.1" 401 569 "-" "Nextcloud Server Crawler"
192.168.9.6 - - [25/Apr/2024:13:02:21 +0000] "GET /.well-known/caldav HTTP/1.1" 301 162 "-" "Nextcloud Server Crawler"
192.168.9.6 - - [25/Apr/2024:13:02:21 +0000] "GET /remote.php/dav HTTP/1.1" 401 569 "-" "Nextcloud Server Crawler"
```
My Android DAVx5 client doesn't seem to have any issues and continues to work well.

A curl test, shows the 301 redirect working, followed by a 401, but I'm assume that's expected with an unauthenticated request
```
curl -IL https://nextcloud.mydomain.com/.well-known/caldav

HTTP/2 301 
server: nginx/1.25.4
date: Thu, 25 Apr 2024 13:12:51 GMT
content-type: text/html
content-length: 162
location: https://nextcloud.mydomain.com/remote.php/dav
referrer-policy: no-referrer
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-robots-tag: noindex, nofollow
x-xss-protection: 1; mode=block
strict-transport-security: max-age=15768000; includeSubDomains; preload;

HTTP/2 401 
server: nginx/1.25.4
date: Thu, 25 Apr 2024 13:12:51 GMT
content-type: application/xml; charset=utf-8
set-cookie: oc_sessionPassphrase=NoBfvCYLv%2B7Hzw7eRoiL4VWZNyADXzcx2k5fgbu4FerYYBJjgl%2Fq8xLrTWscFxu3ithDlInkdabcfGg0nbL0wrG3B%2BPRkOCYjtibS4QvsluoWlkgrT5DdSWiQGUwHxi9; path=/; secure; HttpOnly; SameSite=Lax
set-cookie: __Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
set-cookie: __Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
set-cookie: oc2a3d1f7bcc=6eadda8dbfe0995012c16997240ee6b0; path=/; secure; HttpOnly; SameSite=Lax
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache
content-security-policy: default-src 'none';
www-authenticate: Basic realm="MyDomain, charset="UTF-8"
referrer-policy: no-referrer
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-robots-tag: noindex, nofollow
x-xss-protection: 1; mode=block
strict-transport-security: max-age=15768000; includeSubDomains; preload;
```

There is an error in Nextcloud.log that appears relevant:
```
    "File": "/usr/share/nginx/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php",
    "Line": 152,
    "message": "No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured"
```

### Steps to reproduce

1. Upgrade from NC28 to NC29
2. well-known message in admin settings

### Expected behavior

No well-known errors

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

29

### Operating system

Other

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.mydomain.com",
            "nextcloud"
        ],
        "apps_paths": [
            {
                "path": "\/usr\/share\/nginx\/html\/nextcloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/usr\/share\/nginx\/html\/nextcloud\/custom-apps",
                "url": "\/custom-apps",
                "writable": true
            }
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "29.0.0.19",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR",
            "HTTP_X_FORWARDED",
            "HTTP_FORWARDED_FOR"
        ],
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "loglevel": 0,
        "maintenance": false,
        "enable_previews": true,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "filesystem_check_changes": 0,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 1.5,
            "read_timeout": 1.5,
            "dbindex": 0
        },
        "trashbin_retention_obligation": "auto",
        "overwrite.cli.url": "https:\/\/nextcloud.mydomain.com",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "theme": "",
        "app_install_overwrite": [
            "joplin"
        ],
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false,
        "default_language": "en",
        "default_phone_region": "CA",
        "maintenance_window_start": 1,
        "memories.db.triggers.fcu": true,
        "memories.exiftool": "\/usr\/share\/nginx\/html\/nextcloud\/custom-apps\/memories\/bin-ext\/exiftool-amd64-glibc",
        "memories.vod.path": "\/usr\/share\/nginx\/html\/nextcloud\/custom-apps\/memories\/bin-ext\/go-vod-amd64",
        "memories.gis_type": 2,
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\Movie",
            "OC\\Preview\\TIFF"
        ]
    }
}
```

### List of activated Apps

_No response_

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{
  "reqId": "6jDGw0WbOAAarIrEpjXS",
  "level": 0,
  "time": "2024-04-25T13:21:06+00:00",
  "remoteAddr": "192.168.9.6",
  "user": "--",
  "app": "webdav",
  "method": "GET",
  "url": "/remote.php/dav",
  "message": "No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured",
  "userAgent": "Nextcloud Server Crawler",
  "version": "29.0.0.19",
  "exception": {
    "Exception": "Sabre\\DAV\\Exception\\NotAuthenticated",
    "Message": "No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured",
    "Code": 0,
    "Trace": [
      {
        "file": "/usr/share/nginx/html/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "beforeMethod",
        "class": "Sabre\\DAV\\Auth\\Plugin",
        "type": "->",
        "args": [
          [
            "Sabre\\HTTP\\Request"
          ],
          [
            "Sabre\\HTTP\\Response"
          ]
        ]
      },
      {
        "file": "/usr/share/nginx/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 456,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "beforeMethod:GET",
          [
            [
              "Sabre\\HTTP\\Request"
            ],
            [
              "Sabre\\HTTP\\Response"
            ]
          ]
        ]
      },
      {
        "file": "/usr/share/nginx/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 253,
        "function": "invokeMethod",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          [
            "Sabre\\HTTP\\Request"
          ],
          [
            "Sabre\\HTTP\\Response"
          ]
        ]
      },
      {
        "file": "/usr/share/nginx/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 321,
        "function": "start",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/usr/share/nginx/html/nextcloud/apps/dav/lib/Server.php",
        "line": 374,
        "function": "exec",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/usr/share/nginx/html/nextcloud/apps/dav/appinfo/v2/remote.php",
        "line": 35,
        "function": "exec",
        "class": "OCA\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/usr/share/nginx/html/nextcloud/remote.php",
        "line": 172,
        "args": [
          "/usr/share/nginx/html/nextcloud/apps/dav/appinfo/v2/remote.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/usr/share/nginx/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php",
    "Line": 152,
    "message": "No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured",
    "exception": {},
    "CustomMessage": "No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured"
  }
}
```

### Additional info

_No response_

### LINKED ISSUE #47880: [Bug]: URLGenerator getAbsoluteURL is not working properly
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

My nextcloud instance is running without issues; I use [Nextcloud in a subdir of the NGINX webroot](https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html#nextcloud-in-a-subdir-of-the-nginx-webroot) setup with a slight variation: 
I add the nginx `root` declaration (e.g. `root /var/www`) inside `location ^~ /nextcloud` declaration because I want to have another `root` for my nginx global configuration. 

When I run `occ setupchecks -vv` and use echo to check the `URLGenerator->getAbsoluteURL(...)` internal workings I notice that `if (\OC::$CLI && !\defined('PHPUNIT_RUN'))` doesn't take into account the possibility for `$url` parameter to already contain the Nextcloud subdir (e.g. /nextcloud). This breaks the url for "JavaScript source map support" and "JavaScript modules support" tests. Nextcloud instance on nginx works fine though; that's, I guess, because `if (\OC::$WEBROOT !== '' && str_starts_with($url, \OC::$WEBROOT))` is used for web which takes into account the Nextcloud subdir.

### Steps to reproduce

1. `occ setupchecks -vv`
2. JavaScript source map support test fails because behind scenes a bad URL is used
3. JavaScript modules support test fails because behind scenes a bad URL is used

### Expected behavior

"JavaScript source map support" and "JavaScript modules support" tests should pass

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "default_phone_region": "RO",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "adrhc.go.ro"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Bucharest",
        "debug": false,
        "logfile": "\/home\/gigi\/apps\/log\/nextcloud.log",
        "loglevel": 2,
        "dbtype": "mysql",
        "version": "29.0.6.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "overwriteprotocol": "https",
        "overwritehost": "adrhc.go.ro",
        "overwritewebroot": "\/nextcloud",
        "overwrite.cli.url": "https:\/\/adrhc.go.ro\/nextcloud",
        "preview_max_memory": 409600,
        "preview_max_filesize_image": 10240,
        "enabledPreviewProviders": [
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\StarOffice",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Font",
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\Krita"
        ]
    }
}
```

### List of activated Apps

```shell
php apps/opt/php-pages/nextcloud/occ app:list
Enabled:
  - activity: 2.21.1
  - camerarawpreviews: 0.8.5
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - comments: 1.19.0
  - contactsinteraction: 1.10.0
  - dashboard: 7.9.0
  - dav: 1.30.1
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.1
  - files_downloadlimit: 2.0.0
  - files_external: 1.21.0
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - firstrunwizard: 2.18.0
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - nextcloud_announcements: 1.18.0
  - notes: 4.10.1
  - notifications: 2.17.0
  - oauth2: 1.17.0
  - password_policy: 1.19.0
  - photos: 2.5.0
  - previewgenerator: 5.6.0
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - support: 1.12.0
  - survey_client: 1.17.0
  - systemtags: 1.19.0
  - text: 3.10.1
  - theming: 2.4.0
  - twofactor_backupcodes: 1.18.0
  - updatenotification: 1.19.1
  - user_status: 1.9.0
  - viewer: 2.3.0
  - weather_status: 1.9.0
  - workflowengine: 2.11.0
Disabled:
  - admin_audit: 1.19.0
  - bruteforcesettings: 2.9.0
  - encryption: 2.17.0
  - suspicious_login: 7.0.0 (installed 6.0.0)
  - twofactor_totp: 11.0.0-dev
  - user_ldap: 1.20.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

no logs are creating when running `occ setupchecks -vv`

### Additional info

Nextcloud Signing status was generated by this URL: [https://adrhc.go.ro/nextcloud/index.php/settings/integrity/failed](https://adrhc.go.ro/nextcloud/index.php/settings/integrity/failed)

### PR DESCRIPTION
**Pull request by susnux**
* Resolves https://github.com/nextcloud/server/issues/47880

## Summary
We basically mock the way `URLGenerator::getAbsoluteURL` works, so we must make sure that the URL might already contain the webroot. Because `baseURL` and `cliURL` also contain the webroot we need to remove the webroot from the URL first.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/settings/lib/SetupChecks/CheckServerResponseTrait.php [hunk 1]
```diff
@@ -41,6 +41,15 @@ protected function serverConfigHelp(): string {
 	 * @return string[] List of possible absolute URLs
 	 */
 	protected function getTestUrls(string $url, bool $removeWebroot): array {
+		if (!str_starts_with($url, '/')) {
+			$url = '/' . $url;
+		}
+		// Similar to `getAbsoluteURL` of URLGenerator:
+		// The Nextcloud web root could be already be prepended.
```
Comment (solracsf) [inline apps/settings/lib/SetupChecks/CheckServerResponseTrait.php:48]:
```suggestion
		// The Nextcloud web root could already be prepended.
```

File: lib/private/URLGenerator.php [hunk 2]
```diff
@@ -264,7 +264,7 @@ public function getAbsoluteURL(string $url): string {
 		if (\OC::$CLI && !\defined('PHPUNIT_RUN')) {
 			return rtrim($this->config->getSystemValueString('overwrite.cli.url'), '/') . '/' . ltrim($url, '/');
 		}
-		// The ownCloud web root can already be prepended.
+		// The Nextcloud web root could be already be prepended.
```
Comment (solracsf) [inline lib/private/URLGenerator.php:267]:
```suggestion
		// The Nextcloud web root could already be prepended.
```

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/issues/47880 => 29.0.6
https://github.com/nextcloud/server/pull/46255 => 29.0.7

The bug report is for 29.0.6, Come and I just finished a patch for 29.0.7 to resolve some issues with webroot.

We still need this patch and if yes, how's the case different?

File: apps/settings/lib/SetupChecks/CheckServerResponseTrait.php [hunk 3]
```diff
@@ -76,8 +85,8 @@ protected function getTestUrls(string $url, bool $removeWebroot): array {
 				/* Ignore domains with a wildcard */
 				continue;
 			}
-			$hosts[] = 'https://' . $host . $url;
-			$hosts[] = 'http://' . $host . $url;
+			$testUrls[] = $this->normalizeUrl("https://$host/$webroot", $webroot, $removeWebroot) . $url;
```
Comment (susnux) [inline apps/settings/lib/SetupChecks/CheckServerResponseTrait.php:88]: @kesselb see this: If you install into `/nextcloud/` then this will be wrong otherwise as the trusted domain does not contain the webroot.
Meaning we need to add the webroot here.

Comment (susnux) [reply apps/settings/lib/SetupChecks/CheckServerResponseTrait.php:88]: (also those URLs were not added but only "hosts")

File: apps/settings/lib/SetupChecks/CheckServerResponseTrait.php [hunk 4]
```diff
@@ -41,6 +41,15 @@ protected function serverConfigHelp(): string {
 	 * @return string[] List of possible absolute URLs
 	 */
 	protected function getTestUrls(string $url, bool $removeWebroot): array {
+		if (!str_starts_with($url, '/')) {
+			$url = '/' . $url;
+		}
+		// Similar to `getAbsoluteURL` of URLGenerator:
+		// The Nextcloud web root could already be prepended.
+		if (\OC::$WEBROOT !== '' && str_starts_with($url, \OC::$WEBROOT)) {
```
Comment (susnux) [inline apps/settings/lib/SetupChecks/CheckServerResponseTrait.php:49]: @kesselb This is needed because if you use the URLGenerator (e.g. the JavaScriptModules test), the resulting URL already contains the webroot.

Then you concat `cliUrl` or `baseUrl` with that url, but both of them also contain the webroot.

E.g. the URL is `/nextcloud/apps/settings/js/test.mjs` and the `cliUrl` is `https://example.com/nextcloud`

**Comment by susnux** [comment]
> We still need this patch and if yes, how's the case different?

See the inline comments I just added to point out current bugs we have with webroots.

**Comment by kesselb** [comment]
Thanks @susnux :+1: 

1) I made a mistake in normalizeUrl. https://github.com/nextcloud/server/blob/897c341c5d894aa76ad1823f8f656f589515a903/apps/settings/lib/SetupChecks/CheckServerResponseTrait.php#L91-L93 That should be ` substr($url, 0, -strlen($webroot));`  to remove the webroot (right now it does extract the webroot :see_no_evil:)

2) We did not adjust the javascript checks. They runHead method should also accept a "removeWebroot" parameter and forward it to the runRequest method.

What do you think?

**Comment by susnux** [comment]
@kesselb good point, fixed that as well and added proper unit tests to make sure we cover all cases.

> They runHead method should also accept a "removeWebroot" parameter

I do not think so, the tests **should** contain the webroot the request is not agains the root like with well-known URLs.
I think developers should not need to care about if the URLGenerator adds the webroot or not, you should just put in your expected URL and decide: Is this a root request or a Nextcloud request?
Please see my added unit tests :)

File: apps/settings/lib/SetupChecks/CheckServerResponseTrait.php [hunk 5]
```diff
@@ -38,66 +38,69 @@ protected function serverConfigHelp(): string {
...
 	 *
 	 * @param string $url The relative URL to test starting with a /
-	 * @return string[] List of possible absolute URLs
+	 * @return list<string> List of possible absolute URLs
 	 */
 	protected function getTestUrls(string $url, bool $removeWebroot): array {
-		$testUrls = [];
+		if (!str_starts_with($url, '/')) {
+			$url = '/' . $url;
+		}
```
Comment (kesselb) [inline apps/settings/lib/SetupChecks/CheckServerResponseTrait.php:46]:
```suggestion
		$url = '/' . ltrim($url, '/');
```

Maybe?

**Comment by kesselb** [comment]
```
  'overwrite.cli.url' => 'https://server.internal/testcloud',
  'overwritewebroot' => '/testcloud',
```

- Run `occ setupchecks` 
- Set a breakpoint in testUrls
- Check JavaScriptModules 

image

The generated URL contains the webroot twice: `https://server.internal/testcloud/testcloud/apps/settings/js/esm-test.mjs` 

I don't know whether the webroot should start with a slash or not. The referenced bug is using a leading slash.

**Comment by kesselb** [comment]
Too many forward slashes for me :see_no_evil:

**Review by kesselb — APPROVED** [review]

File: apps/settings/lib/SetupChecks/DataDirectoryProtected.php [hunk 6]
```diff
@@ -41,8 +41,7 @@ public function getName(): string {
 
 	public function run(): SetupResult {
 		$datadir = str_replace(\OC::$SERVERROOT . '/', '', $this->config->getSystemValue('datadirectory', ''));
```
Comment (come-nc) [inline apps/settings/lib/SetupChecks/DataDirectoryProtected.php:43]:
```suggestion
		$datadir = str_replace(\OC::$SERVERROOT . '/', '', $this->config->getSystemValueString('datadirectory', ''));
```

File: apps/settings/lib/SetupChecks/CheckServerResponseTrait.php [hunk 7]
```diff
@@ -38,66 +38,67 @@ protected function serverConfigHelp(): string {
...
-	 * @return string[] List of possible absolute URLs
+	 * @return list<string> List of possible absolute URLs
 	 */
 	protected function getTestUrls(string $url, bool $removeWebroot): array {
-		$testUrls = [];
+		$url = '/' . ltrim($url, '/');
 
 		$webroot = rtrim($this->urlGenerator->getWebroot(), '/');
+		// Similar to `getAbsoluteURL` of URLGenerator:
+		// The Nextcloud web root could already be prepended.
```
[the remark this answers is not in the document]
Comment (kesselb) [reply apps/settings/lib/SetupChecks/CheckServerResponseTrait.php:48]: Good point :+1: 

@susnux explained his idea/approach here: https://github.com/nextcloud/server/pull/47883#issuecomment-2343440098

I also think we should have one way for the URLs and not accept different formats. 

Example JavaScriptModules: https://github.com/nextcloud/server/blob/8feef455068533c18f7ab25e2274187733217a5e/apps/settings/lib/SetupChecks/JavaScriptModules.php#L43

- Is using the url generator and thus contains the webroot already.

Example WellKnownUrls: https://github.com/nextcloud/server/blob/8feef455068533c18f7ab25e2274187733217a5e/apps/settings/lib/SetupChecks/WellKnownUrls.php#L46-L51

- Not using the url generator.


1. We added the option to strip the webroot with https://github.com/nextcloud/server/pull/46255 for the wellknown use case to using the cli url (that includes the webroot) and remove the webroot for the root request. 
2. I think it's also okay to require that all urls, to test, contain the webroot if necessary. 

Nice would be to have only one way, to avoid further bewilderment ;)

[the remark this answers is not in the document]
Comment (susnux) [reply apps/settings/lib/SetupChecks/CheckServerResponseTrait.php]: I refactored it like discussed:

- Always expect absolute path (so including the web-root if needed, meaning you can just use the output of the URLGenerator)
- Option to make the request a root request which removes the webroot from CLI URL and base URL.

File: apps/settings/lib/SetupChecks/CheckServerResponseTrait.php [hunk 8]
```diff
@@ -37,85 +37,93 @@ protected function serverConfigHelp(): string {
...
 		}
 
-		return $testUrls;
+		return array_map(fn (string $host) => $host . $url, array_values(array_unique($baseUrls)));
 	}
 
 	/**
 	 * Strip a trailing slash and remove the webroot if requested.
+	 * @param string $url The URL to normalize. Should be an absolute URL containing scheme, host and optionally web-root.
+	 * @param string $removeWebroot If set the web-root is removed from the URL and an absolute URL with only the scheme and host (optional port) is returned
```
Comment (come-nc) [inline apps/settings/lib/SetupChecks/CheckServerResponseTrait.php:91]:
```suggestion
	 * @param bool $removeWebroot If set the web-root is removed from the URL and an absolute URL with only the scheme and host (optional port) is returned
```

**Review by come-nc — APPROVED** [review]
I think fixing the wrong type in the phpdoc should fix psalm errors.
Nice job :+1:

**Comment by come-nc** [comment]
phpunit tests also need to be adapted to change from getSystemValue to getSystemValueString
