### PR TITLE
Don't try to purge objects from the birthday calendar when it doesn't exist

### LINKED ISSUE #29617: Error: Trying to access array offset on value of type null at /apps/dav/lib/CalDAV/BirthdayService.php#306
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. No Sure
2.
3.

### Server configuration

**Operating system:**
Ubuntu 20.4
**Web server:**
Apache 2
**Database:**
10.5.12
**PHP version:**
8.0.12
**Nextcloud version:** (see Nextcloud admin page)
22.2.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Install
**Where did you install Nextcloud from:**
Nextcloud website 

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"IoPpj4uCj4eCF585ahy3","level":3,"time":"2021-11-09T20:25:01+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Trying to access array offset on value of type null at /var/www/nextcloud/apps/dav/lib/CalDAV/BirthdayService.php#306","userAgent":"--","version":"22.2.0.2","exception":{"Exception":"Error","Message":"Trying to access array offset on value of type null at /var/www/nextcloud/apps/dav/lib/CalDAV/BirthdayService.php#306","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/dav/lib/CalDAV/BirthdayService.php","line":306,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/apps/dav/lib/BackgroundJob/GenerateBirthdayCalendarBackgroundJob.php","line":69,"function":"resetForUser","class":"OCA\\DAV\\CalDAV\\BirthdayService","type":"->"},{"file":"/var/www/nextcloud/lib/private/BackgroundJob/Job.php","line":51,"function":"run","class":"OCA\\DAV\\BackgroundJob\\GenerateBirthdayCalendarBackgroundJob","type":"->"},{"file":"/var/www/nextcloud/lib/private/BackgroundJob/QueuedJob.php","line":45,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/nextcloud/cron.php","line":127,"function":"execute","class":"OC\\BackgroundJob\\QueuedJob","type":"->"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"618aebfd2848f"}
```
</details>

### PR DESCRIPTION
**Pull request by tcitworld**
Doesn't matter much as it's been recreated afterwards (with `ensureCalendarExists`).

Closes #29617

### CODE REVIEW

File: apps/dav/lib/CalDAV/BirthdayService.php [hunk 1]
```diff
@@ -273,6 +273,7 @@ public function buildDateFromContact(string $cardData,
 	public function resetForUser(string $user):void {
 		$principal = 'principals/users/'.$user;
 		$calendar = $this->calDavBackEnd->getCalendarByUri($principal, self::BIRTHDAY_CALENDAR_URI);
+		if (!$calendar) return; // The user's birthday calendar doesn't exist
```
Comment (blizzz) [inline apps/dav/lib/CalDAV/BirthdayService.php:276]:
```suggestion
		if (!$calendar) {
			return;
		}
```

we always use brackets

Comment (tcitworld) [reply apps/dav/lib/CalDAV/BirthdayService.php]: I thought cs-fixer would have caught that :thinking:

**Review by blizzz — APPROVED** [review]

**Review by miaulalala — APPROVED** [review]
