### PR TITLE
fix(Streamer): use localtime for ZIP files

### LINKED ISSUE #54311: [Bug]: Time get the wrong timezone when downloaded as zip
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When downloading previously generated or uploaded files as ZIP archives via the Nextcloud interface, the changed time metadata of the contained files shows an incorrect timezone.

### Steps to reproduce

1. Make a Folder
2. Add files
3. Download the whole folder as zip
4. Look into the zip file: There you see the wrong time

### Expected behavior

Correct filedate as shown on nextcloud webview.

### Nextcloud Server version

31

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

If needed I can provide other informations

### PR DESCRIPTION
**Pull request by susnux**
- [x] follow up on https://github.com/nextcloud/server/pull/54401
- Resolves https://github.com/nextcloud/server/issues/54311

## Summary

ZIP does not use a proper timestamp but uses something called "DOS time".
This is a weird old format with some limitations like accuracy of only
2 seconds, but also no timezone information.
Also unlike UNIX time it is not relative to some specific point in time
with timezone information, but is always considered to be the local
time. Meaning we need to convert it first to the users local time.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: lib/private/Streamer.php [hunk 1]
```diff
@@ -191,4 +192,14 @@ public function addEmptyDir(string $dirName, int $timestamp = 0): bool {
 	public function finalize() {
 		return $this->streamerInstance->finalize();
 	}
+
+	private function fixTimestamp(int $timestamp): int {
+		if ($this->streamerInstance instanceof ZipStreamer) {
+			// Zip does not support any timezone information
+			// while tar is interpreted as Unix time the Zip time is interpreted as local time of the user...
+			$zone = \OCP\Server::get(IDateTimeZone::class)->getTimeZone($timestamp);
```
Comment (icewind1991) [inline lib/private/Streamer.php]: can we get the `IDateTimeZone` once instead of N times.

**Review by AndyScherzinger — APPROVED** [review]

File: lib/private/Streamer.php (hunk 1 above)
Comment (susnux) [reply lib/private/Streamer.php]: done!

**Review by icewind1991 — APPROVED** [review]

**Review by come-nc — COMMENTED** [review]
That means users A and B downloading the same zip content will get different time information in there? So if I download stuff and then send it to someone on another time zone times will look wrong on their computer?

**Comment by susnux** [comment]
> That means users A and B downloading the same zip content will get different time information in there? So if I download stuff and then send it to someone on another time zone times will look wrong on their computer?

Yes and there is no fix - ZIP time is considered the local time of the user that created it.
You should rather use the TAR download ;)

**Review by come-nc — APPROVED** [review]
