### PR TITLE
Fix app name of files app

### LINKED ISSUE #3479: App name in Files app says »Apps« instead of »Files«
capture du 2017-02-14 20-16-56

When did that happen @nextcloud/designers? Was it intentional?

### PR DESCRIPTION
**Pull request by MorrisJobke**
* fixes #3479

### CODE REVIEW

File: apps/files/lib/Controller/ViewController.php [hunk 1]
```diff
@@ -244,7 +239,6 @@ public function index($dir = '', $view = '', $fileid = null, $fileNotFound = fal
 		$params['fileNotFound'] = $fileNotFound ? 1 : 0;
 		$params['appNavigation'] = $nav;
 		$params['appContents'] = $contentItems;
-		$this->navigationManager->setActiveEntry('files_index');
```
Comment (MorrisJobke) [inline apps/files/lib/Controller/ViewController.php]: This is the actual fix. The rest is just cleanup of unneeded code due to this change 😉

Comment (skjnldsv) [inline apps/files/lib/Controller/ViewController.php]: Nice catch! 😮

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Test restarted

**Review by blizzz — APPROVED** [review]
