### PR TITLE
fix(snowflake): cast lastId to string

### LINKED ISSUE #637: occ preview:cleanup Peview:cleanup An unhandled exception has been thrown:
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

### Steps to reproduce
1. sudo -u www-data php /var/www/nextcloud/occ preview:cleanup
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
```
sudo -u www-data php /var/www/nextcloud/occ preview:cleanup
An unhandled exception has been thrown:
TypeError: OC\Preview\Db\PreviewMapper::getPreviews(): Argument #1 ($lastId) must be of type int, string given, called in /var/www/nextcloud/lib/private/Preview/PreviewService.php on line 115 and defined in /var/www/nextcloud/lib/private/Preview/Db/PreviewMapper.php:207
Stack trace:
#0 /var/www/nextcloud/lib/private/Preview/PreviewService.php(115): OC\Preview\Db\PreviewMapper->getPreviews()
#1 /var/www/nextcloud/core/Command/Preview/Cleanup.php(52): OC\Preview\PreviewService->deleteAll()
#2 /var/www/nextcloud/core/Command/Preview/Cleanup.php(40): OC\Core\Command\Preview\Cleanup->deletePreviewFromPreviewTable()
#3 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(326): OC\Core\Command\Preview\Cleanup->execute()
#4 /var/www/nextcloud/core/Command/Base.php(220): Symfony\Component\Console\Command\Command->run()
#5 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1078): OC\Core\Command\Base->run()
#6 /var/www/nextcloud/3rdparty/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#7 /var/www/nextcloud/3rdparty/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#8 /var/www/nextcloud/lib/private/Console/Application.php(187): Symfony\Component\Console\Application->run()
#9 /var/www/nextcloud/console.php(92): OC\Console\Application->run()
#10 /var/www/nextcloud/occ(33): require_once('...')
#11 {main}root@nextcloud:~#
```

### Server configuration

**Web server:** Apache/Nginx
Apache

**Database:** MySQL/Maria/SQLite/PostgreSQL
Maraia
**PHP version:** 8.2/8.3/8.4
8.4
**Nextcloud version:** (see Nextcloud admin page)
33.0.0 RC3
<details>
<summary>List of activated apps</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

<details>
<summary>Nextcloud configuration</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Browser

**Browser name:** Firefox/Chrome/Safari/…

**Browser version:** 124/125/…

**Operating system:** Windows/Ubuntu/Mac/…

<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

### PR DESCRIPTION
**Pull request by miaulalala**
Fixes https://github.com/nextcloud/previewgenerator/issues/637

## Summary

Snowflake IDs are strings, so the mapper method needs to change

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)
- [x] [Labels added](https://github.com/nextcloud/server/labels) where applicable (ex: bug/enhancement, `3. to review`, feature component)
- [x] [Milestone added](https://github.com/nextcloud/server/milestones) for target branch/version (ex: 32.x for `stable32`)

### CODE REVIEW

**Comment by AndyXheli** [comment]
Tested on server and i can confirm this fixes the issue

File: lib/private/Preview/PreviewService.php [hunk 1]
```diff
@@ -121,7 +121,7 @@ public function deleteAll(): void {
 			foreach ($previews as $preview) {
 				$this->deletePreview($preview);
 				$i++;
-				$lastId = $preview->getId();
+				$lastId = (int)$preview->getId();
 			}
 
 			if ($i !== 1000) {
```
Comment (CarlSchwan) [inline lib/private/Preview/PreviewService.php:127]:
```suggestion
$lastId = '0';
while (true) {
$previews = $this->previewMapper->getPreviews($lastId, 1000);
$i = 0;

// FIXME: Should we use transaction here? Du to the I/O created when
// deleting the previews from the storage, which might be on a network
// This might take a non trivial amount of time where the DB is locked.
foreach ($previews as $preview) {
$this->deletePreview($preview);
$i++;
				$lastId = $preview->getId();
}

if ($i !== 1000) {
```

and in lib/private/Preview/Db/PreviewMapper.php replace int by string in the argument of `getPreviews` and remove `IQueryBuilder::PARAM_INT` from that function

Otherwise this breaks 32 bits

Comment (miaulalala) [reply lib/private/Preview/PreviewService.php:127]: Right, makes sense!

**Review by Altahrim — APPROVED** [review]

**Review by CarlSchwan — APPROVED** [review]
