### PR TITLE
fix(files_sharing): Filter own shares that are reshares

### LINKED ISSUE #51988: [Bug]: Reshare with (own) group ends up as double share for sharee
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

A Reshare with (own) group ends up as double share for the sharee.
This problem seems to be only with folders, where you get a reshare which is reshared to a group.
Only occurs to reshares, so not to if you're the owner of a folder and just share it with a group, where you're member of.

### Steps to reproduce

Account A shares a folder with Account B.
Account B creates a Team/Group, where he is owner of, and add Account C as member. Let's say Group A.
Account B shares a subfolder from the share of Account A with Group A, with which this reshare also comes into the files overview for Account B.

### Expected behavior

For Account B, the reshare should not be shown in the files overview.

### Nextcloud Server version

all

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by provokateurin**
* Resolves: https://github.com/nextcloud/server/issues/51988

## Summary

Shares were only filtered if the current user is the owner, but in a reshare they are not the owner.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by susnux — APPROVED** [review]

**Comment by provokateurin** [comment]
Yes, I'm fixing the existing tests and will add a new test for this as well.

File: apps/files_sharing/lib/MountProvider.php [hunk 1]
```diff
@@ -55,7 +55,7 @@ public function getMountsForUser(IUser $user, IStorageFactory $loader) {
 
 		// filter out excluded shares and group shares that includes self
 		$shares = array_filter($shares, function (IShare $share) use ($user) {
-			return $share->getPermissions() > 0 && $share->getShareOwner() !== $user->getUID();
+			return $share->getPermissions() > 0 && $share->getSharedBy() !== $user->getUID();
```
Comment (come-nc) [inline apps/files_sharing/lib/MountProvider.php:58]: What if the user is the share owner but not the sharer?

Like Bob shares to Alice which shares to Bob (through a group or something?), these kind of shares were excluded before and will not be now.
What I’m really asking is whether we should test both owner and sharedBy to exclude both?

Comment (provokateurin) [reply apps/files_sharing/lib/MountProvider.php:58]: True that is a scenario I didn't consider. I wanted to do it like that in the first place, but though the this would be enough.

**Review by yemkareems — APPROVED** [review]

**Review by come-nc — APPROVED** [review]

**Comment by blizzz** [comment]
The same tests fails three times in a row:

Screenshot_20250506_174147

Not sure whether related, but could be.

**Comment by provokateurin** [comment]
It's related, I'm working on it.

**Review by skjnldsv — APPROVED** [review]
