### PR TITLE
fix(files_versions): Do not expire versions newer than min age

### LINKED ISSUE #19791: Versioning ignores versions_retention_obligation `D, auto`
### Steps to reproduce
1. Configure versions_retention_obligation to .e.g. `"versions_retention_obligation": "14, auto",` as described here https://github.com/nextcloud/server/blob/master/config/config.sample.php#L603. 
```
 * * ``D, auto``
 *     keep versions at least for D days, apply expire rules to all versions
 *     that are older than D days
```
2. Create file, e.g. todo.txt
3. Update this file few times
4. See that older version are deleted, but they must be kept for a configured (here 14) amount of days.

### Expected behaviour
Older files versions must be handled as it is configured in config.php and as it is described in a Doku.

### Actual behaviour
Older files versions has being deleted independent of settings in config.php:
grafik

### Server configuration

**Operating system:** Ubuntu 18.04

**Web server:** Apache 2.4.41

**Database:** 10.1.44-MariaDB

**PHP version:** 7.3.15

**Nextcloud version:** 17.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** update

**Where did you install Nextcloud from:** Official

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - admin_audit: 1.7.0
  - audioplayer: 2.9.0
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.2
  - checksum: 0.4.4
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - data_request: 1.4.0
  - dav: 1.13.0
  - deck: 0.8.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_automatedtagging: 1.7.0
  - files_external: 1.8.0
  - files_pdfviewer: 1.6.0
  - files_retention: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - flowupload: 0.1.8
  - gallery: 18.4.0
  - gpxpod: 4.1.1
  - keeweb: 0.6.2
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - mail: 1.1.3
  - maps: 0.1.5
  - nextcloud_announcements: 1.6.0
  - notes: 3.1.5
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - ocdownloader: 1.7.6
  - password_policy: 1.7.0
  - phonetrack: 0.6.2
  - polls: 1.3.0
  - previewgenerator: 2.2.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - radio: 0.6.6
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - twofactor_totp: 4.1.2
  - unsplash: 1.1.5
  - updatenotification: 1.7.0
  - viewer: 1.2.0
  - weather: 1.7.1
  - workflowengine: 1.7.0
Disabled:
  - encryption
  - impersonate
  - sharerenamer
  - support
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "***REMOVED SENSITIVE VALUE***",
            "2": "***REMOVED SENSITIVE VALUE***"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***\/nextcloud",
        "dbtype": "mysql",
        "version": "17.0.3.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "filesystem_check_changes": 0,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 1.5
        },
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "logfile": "\/var\/nextcloud\/data\/nextcloud.log",
        "loglevel": 1,
        "trashbin_retention_obligation": "14, auto",
        "versions_retention_obligation": "14, auto",
        "data-fingerprint": "***REMOVED SENSITIVE VALUE***",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "preview_max_x": 1080,
        "preview_max_y": 1920,
        "auth.bruteforce.protection.enabled": true,
        "simpleSignUpLink.shown": false,
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [],
        "has_rebuilt_cache": true,
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "keeweb",
            "radio"
        ]
    }
}
```
</details>

**Are you using external storage, if yes which one:** local smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"KiDyFYmuoD4HjXfIhfs7","level":1,"time":"2020-03-05T10:00:39+00:00","remoteAddr":"","user":"--","app":"files_versions","method":"","url":"--","message":"Mark to expire \/todo.txt next version should be 1583401846 or smaller. (prevTimestamp: 1583401906; step: 60","userAgent":"--","version":"17.0.3.1"}
{"reqId":"KiDyFYmuoD4HjXfIhfs7","level":1,"time":"2020-03-05T10:00:39+00:00","remoteAddr":"","user":"--","app":"files_versions","method":"","url":"--","message":"Mark to expire \/todo.txt next version should be 1583401846 or smaller. (prevTimestamp: 1583401906; step: 60","userAgent":"--","version":"17.0.3.1"}
{"reqId":"KiDyFYmuoD4HjXfIhfs7","level":1,"time":"2020-03-05T10:00:39+00:00","remoteAddr":"","user":"--","app":"files_versions","method":"","url":"--","message":"Mark to expire \/todo.txt next version should be 1583401846 or smaller. (prevTimestamp: 1583401906; step: 60","userAgent":"--","version":"17.0.3.1"}
{"reqId":"KiDyFYmuoD4HjXfIhfs7","level":1,"time":"2020-03-05T10:00:39+00:00","remoteAddr":"","user":"--","app":"files_versions","method":"","url":"--","message":"Expire: \/todo.txt.v1583401886","userAgent":"--","version":"17.0.3.1"}
{"reqId":"KiDyFYmuoD4HjXfIhfs7","level":1,"time":"2020-03-05T10:00:40+00:00","remoteAddr":"","user":"--","app":"files_versions","method":"","url":"--","message":"Expire: \/todo.txt.v1583401876","userAgent":"--","version":"17.0.3.1"}
{"reqId":"KiDyFYmuoD4HjXfIhfs7","level":1,"time":"2020-03-05T10:00:40+00:00","remoteAddr":"","user":"--","app":"files_versions","method":"","url":"--","message":"Expire: \/todo.txt.v1583401859","userAgent":"--","version":"17.0.3.1"}
```
</details>

### PR DESCRIPTION
**Pull request by artonge**
The auto expire logic does not take into account the min retention age set by the admin. So versions were eagerly deleted.

Fix https://github.com/nextcloud/server/issues/19791

### CODE REVIEW

File: apps/files_versions/lib/Storage.php [hunk 1]
```diff
@@ -696,7 +696,15 @@ protected static function getExpireList($time, $versions, $quotaExceeded = false
 		$expiration = self::getExpiration();
 
 		if ($expiration->shouldAutoExpire()) {
-			[$toDelete, $size] = self::getAutoExpireList($time, $versions);
+			// Exclude versions that are newer than the minimum age from the auto expiration logic.
+			$minAge = $expiration->getMinAgeAsTimestamp();
+			if ($minAge !== false) {
+				$versionsToAutoExpire = array_filter($versions, fn ($version) => $version['version'] < $minAge);
```
Comment (come-nc) [inline apps/files_versions/lib/Storage.php:702]: The timestamp is in `'version'` key? :thinking:

**Review by come-nc — APPROVED** [review]

File: apps/files_versions/lib/Storage.php (hunk 1 above)
Comment (artonge) [reply apps/files_versions/lib/Storage.php:702]: Yes: https://github.com/nextcloud/server/blob/07719064f776e5d1d8486428546c70a4f8bc8e01/apps/files_versions/lib/Storage.php#L497

**Review by yemkareems — APPROVED** [review]
