### PR TITLE
fix(dav): Prevent out-of-office event time drifts

### LINKED ISSUE #42139: [Bug]: Absence event starts one day too early and is always set to UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Despite https://github.com/nextcloud/server/pull/41703, setting an out of office with 28 RC3 leads to a calendar event that starts one day too early and is drifting for timezones with an offset due to the event being set to UTC.

### Steps to reproduce

1. Log into Nextcloud
2. Configure an absence
3. Open Calendar

### Expected behavior

Absence events starts 00:00 of my first day of absence and ends 00:00 of the first day I'm back.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ChristophWurst**
* Resolves: https://github.com/nextcloud/server/issues/42139

## Summary

This fixes both symptoms of https://github.com/nextcloud/server/issues/42139

Users whose calendar has no `timezone` property had wrong calendar start dates when their actual timezone has an offset from UTC. This happens for CET for example. The fix is to use the new *timezone service* that has more sources for a timezone and therefore higher changing of finding data.

The known downside of this fix is that in contrast to the calendar timezone, the timezone service only returns the *timezone id*, not the full *VTIMEZONE* object. Therefore the ooo events have DTSTART and DTEND with TZID=x but no VTIMEZONE component. This is not ideal but IMO a better solution than the current drifts.

## How to test

0. Clear your absence if you already had one
1. Set your default calendar `timezone` to NULL in oc_calendars
2. Schedule a new absence
3. Open the calendar

master: event is created, but at UTC and it starts one day before absence if you live in UTC+1
here: event is created, has DTSTART and DTEND set to your timezone id and starts at the first day of absence.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/dav/lib/Listener/OutOfOfficeListener.php [hunk 1]
```diff
@@ -188,21 +190,6 @@ private function createVCalendarEvent(IOutOfOfficeData $data, ?string $timeZoneD
...
-		if ($timeZoneData !== null) {
-			/** @var VCalendar $vtimezoneObj */
-			$vtimezoneObj = Reader::read($timeZoneData);
-			/** @var VTimeZone $vtimezone */
-			$vtimezone = $vtimezoneObj->VTIMEZONE;
-			$calendarTimeZone = $vtimezone->getTimeZone();
-			$vCalendar->add($vtimezone);
-
-			/** @psalm-suppress UndefinedMethod */
-			$vEvent->DTSTART->setDateTime($start->setTimezone($calendarTimeZone)->setTime(0, 0));
```
Comment (ChristophWurst) [inline apps/dav/lib/Listener/OutOfOfficeListener.php:202]: the day drift happened here because we set the time above without a timezone. if the actual time is on UTC+1 and you set to 00:00 the date moves by one day. So even if we set the time again here, it's one day too early.

setting timezone first, then the time ensures that the day does not change unexpectedly

**Comment by tcitworld** [comment]
> Therefore the ooo events have DTSTART and DTEND with TZID=x but no VTIMEZONE component. This is not ideal but IMO a better solution than the current drifts.

Want to create an issue to have such a service that generates VTIMEZONE data? There's probably a lot of places it could be used.

**Review by tcitworld — APPROVED** [review]

**Comment by ChristophWurst** [comment]
> Want to create an issue to have such a service that generates VTIMEZONE data? There's probably a lot of places it could be used.

https://github.com/nextcloud/server/issues/42145

**Review by miaulalala — APPROVED** [review]
Looks reasonable

**Comment by ChristophWurst** [comment]
@miaulalala could you please test it, too?

**Review by nickvergessen — APPROVED** [review]
Makes sense

**Comment by miaulalala** [comment]
Tested it, works.

**Comment by blizzz** [comment]
accidentally merged the wrong PR, sorry. ^ recreating the backport.
