### PR TITLE
Enhancements: Fix and updates to most recent global search UI

### LINKED ISSUE #41492: Global search filter for "since" and "until" are broken
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

---

* Today filters with since=1700048245 (NOW) and until=1700048245 (NOW) (same timestamp, should range from 0:00 this day until 23:59 this day) - basically will never find something at the moment
* Last 7 days filters with since=1699443555 (NOW - 7\*24h) and until=1700048355 (NOW), the range is 7\*24h instead of the beginning of that day (is at least unexpected for me)
* This year  filters with since=1672527600 (1.1. 0:00 - Ok) and until=1700048599 (NOW), which might be problematic for things like a calendar where you would also like to find future events of THIS year.
* Custom range, I select "yesterday and today"  with since=1699916400 (14.11. 0:00 - Ok) and until=1700002800 (15.11. 0:00) - I would expect today to be included, but it actually searches only yesterday at all
 grafik

### PR DESCRIPTION
**Pull request by nfebe**
- Allow future dates in custom date range
- Fix date ranges for example, before now, today range was roughly between `now()` to `now() + a few milli seconds`

Resolves : https://github.com/nextcloud/server/issues/41492, https://github.com/nextcloud/server/issues/41381

## High
- [x] Date filter logic broken #41492 
- [x] Mail previews not right 
- [x] Broken folder icon in files results
- [x] Messages: avatar in circles not squares
- [x] “Search in app” is only available for a few apps (remove links)
- [x] Search field is not focused automatically when the modal is opened

## Medium
- [x] Contacts filter shouldn’t be available if contacts app is not available 
- [ ] No space for icons in modified

## Low
- [x] Apply range primary to the right 
- [x] Date range filter -> custom date range
- [x] Apply range -> Search in date range
- [ ] "No matching results" emptycontent icon should be a search icon instead of the current one
- [ ] Text in People" menu regular not bold
- [ ] Close icon material design icon "close" instead of "close-thick"
- [x] Cursor pointer instead on hovering close icon
- [x] Avatar in filter chips shouldn't be clickable and size should be 24px

### CODE REVIEW

**Comment by Fenn-CS** [comment]
This should get reviewed and merged, so smaller follow up prs get in faster, it makes things faster and gets as much as possible into the regular build schedule.

**Review by artonge — APPROVED** [review]

File: core/src/components/GlobalSearch/CustomDateRangeModal.vue [hunk 1]
```diff
@@ -1,33 +1,33 @@
 <template>
 	<NcModal v-if="isModalOpen"
 		id="global-search"
-		:name="t('core', 'Date range filter')"
+		:name="t('core', 'Custom date range')"
 		:show.sync="isModalOpen"
 		:size="'small'"
 		:clear-view-delay="0"
-		:title="t('Date range filter')"
+		:title="t('Custom date range')"
```
Comment (susnux) [inline core/src/components/GlobalSearch/CustomDateRangeModal.vue:8]:
```suggestion
		:title="t('core', 'Custom date range')"
```

**Review by susnux — CHANGES_REQUESTED** [review]
missing appkey for translation, this will not work :/

File: core/src/components/GlobalSearch/SearchResult.vue [hunk 2]
```diff
@@ -0,0 +1,162 @@
+<template>
+	<NcListItem class="result-items__item"
+		:name="title ?? ''"
+		:bold="false"
+		@click="openResult(result)">
+		<template #icon>
+			<div class="result-items__item-icon"
```
Comment (susnux) [inline core/src/components/GlobalSearch/SearchResult.vue:7]: Either this or set `alt=""` on the `` tag. But I think hiding it is correct here as this is pure representation (images).

```suggestion
			<div aria-hidden="true"
				class="result-items__item-icon"
```

File: core/src/components/GlobalSearch/SearchResult.vue [hunk 3]
```diff
@@ -0,0 +1,162 @@
...
+		 * enter still opens the first result
+		 */
+		focused: {
+			type: Boolean,
+			default: false,
+		},
+	},
+	data() {
+		return {
+			thumbnailHasError: false,
```
Comment (susnux) [inline core/src/components/GlobalSearch/SearchResult.vue:78]: Maybe we need a:
```js
watch: {
    thumbnailUrl() {
        this.thumbnailHasError = false
    }
}
```

Because if this component is recycled because of changing results and the thumbnail has an error, the new result will also show the thumbnail error.
If this happens depends on whether the component will be recycled by `GlobalSearchModal` or not (depending on the `key` value in the `v-for` look).

**Review by susnux — APPROVED** [review]
