### PR TITLE
fix(AppFramework): Log malformed protocol values and unify fallback behavior

### LINKED ISSUE #14306: Nextcloud failing to setup: `ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW`
### Cause of error
```java
Exception in thread "main" android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=HTTPS://nextcloud.mydomain.com/... flg=0x10000000 }
    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2252)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1878)
    at android.app.Activity.startActivityForResult(Activity.java:5783)
    at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.kt:704)
    at android.app.Activity.startActivityForResult(Activity.java:5741)
    at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.kt:683)
    at android.app.Activity.startActivity(Activity.java:6239)
    at android.app.Activity.startActivity(Activity.java:6206)
    at com.owncloud.android.authentication.AuthenticatorActivity.launchDefaultWebBrowser(AuthenticatorActivity.java:493)
    at com.owncloud.android.authentication.AuthenticatorActivity.lambda$anonymouslyPostLoginRequest$1(AuthenticatorActivity.java:462)
    at com.owncloud.android.authentication.AuthenticatorActivity.$r8$lambda$HghPOrCvYiC9MbGZkBiQhXwJPi8(Unknown Source:0)
    at com.owncloud.android.authentication.AuthenticatorActivity$$ExternalSyntheticLambda9.run(D8$$SyntheticClass:0)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:9063)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300690`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `e3q`
* Model: `SM-S928U1`
* Id: `UP1A.231005.007`
* Product: `e3quew`

### Firmware
* SDK: `34`
* Release: `14`
* Incremental: `S928U1UES4AXKF`

### LINKED ISSUE #14474: Crash on Graphene OS after entering server address: `No Activity found to handle Intent { act=android.intent.action.VIEW dat=HTTP:`
### ⚠️ Before posting ⚠️

- [x] This is a **bug**, not a question or an enhancement.
- [x] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [x] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Open app after installing
2. Enter address for my server
3. Click arrow to connect

### Expected behaviour

It shouldn't crash; it should show the login prompt.

### Actual behaviour

Crash with log (see below).

### Android version

15

### Device brand and model

Google pixel 8

### Stock or custom OS?

Custom (explain in "additional information")

### Nextcloud android app version

30300890

### Nextcloud server version

30.0.5

### Using a reverse proxy?

Yes

### Cause of error
```java
Exception in thread "main" android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=HTTP://nextcloud.borgie.lan/... flg=0x10000000 }
    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2448)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:2018)
    at android.app.Activity.startActivityForResult(Activity.java:5928)
    at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.kt:704)
    at android.app.Activity.startActivityForResult(Activity.java:5847)
    at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.kt:683)
    at android.app.Activity.startActivity(Activity.java:6395)
    at android.app.Activity.startActivity(Activity.java:6362)
    at com.owncloud.android.authentication.AuthenticatorActivity.launchDefaultWebBrowser(AuthenticatorActivity.java:493)
    at com.owncloud.android.authentication.AuthenticatorActivity.lambda$anonymouslyPostLoginRequest$1(AuthenticatorActivity.java:462)
    at com.owncloud.android.authentication.AuthenticatorActivity.$r8$lambda$HghPOrCvYiC9MbGZkBiQhXwJPi8(Unknown Source:0)
    at com.owncloud.android.authentication.AuthenticatorActivity$$ExternalSyntheticLambda9.run(D8$$SyntheticClass:0)
    at android.os.Handler.handleCallback(Handler.java:991)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.app.ActivityThread.main(ActivityThread.java:8826)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
    at com.android.internal.os.ExecInit.main(ExecInit.java:50)
    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30300890`
* Build flavor: `gplay`

### Device information
* Brand: `google`
* Device: `shiba`
* Model: `Pixel 8`
* Id: `AP4A.250105.002`
* Product: `shiba`

### Firmware
* SDK: `35`
* Release: `15`
* Incremental: `2025012700`

### Server error logs

```bash

```

### Additional information

Running on Graphene OS version 2025012700 (latest)

### PR DESCRIPTION
**Pull request by joshtrichards**
* Resolves: nextcloud/android#14306 
* Resolves: nextcloud/android#14474

While the above are configuration matters so they're now closed, we can handle it better here in `server` which is that this PR proposes.

## Summary

This PR:

- Unifies existing fallback behavior regardless of method used to specify protocol  (i.e. always returning `http` at a minimum).
- Adds logging whenever the fallback is used so the admin has a chance to fix whatever is causing it.

We currently:

* Fallback to a sane protocol value (`http`) when a malformed protocol value is received from a reverse proxy (via `X-Forwarded-Proto`).
* Silently fallback, which can make troubleshooting challenging.
* Trust the value of `overwriteprotocol` to be reasonable.
* Have no fallback behavior for malformed `overwriteprotocol` values (unlike `X-Forwarded-Proto`).

The fallback is not a default value. It's just means a reasonable protocol is returned. When the fallback is used, it's basically an error. If it wasn't existing behavior, we might consider throwing an exception here instead. This PR just adds similar fallback behavior for malformed `overwriteprotocol` values and also logs when the fallback is used.

Details:

- Sanity checks value `overwriteprotocol` (if any) and when malformed uses same fallback value (http) as we do for `X-Forwarded-Proto`
- Adds logging when the server protocol is malformed (regardless of source)
- Treats upper/mixed case values (i.e. `HTTP` / `HTTPS`) as valid for `overwriteprotocol` (just as it already does for `X-Forwarded-Proto`)
- Refactors code slightly (formatting, comments, eliminates unnecessary comparisons, minor structure change) 

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: lib/private/AppFramework/Http/Request.php [hunk 1]
```diff
@@ -613,36 +614,46 @@ private function isOverwriteCondition(): bool {
...
-			&& $this->server['HTTPS'] !== '') {
-			return 'https';
+		) {
+			$proto = 'https';
 		}
 
-		return 'http';
+		if ($proto !== 'https' && $proto !== 'http') {
+			// log unrecognized value so admin has a chance to fix it
+			\OC::$server->get(LoggerInterface::class)->critical(
```
Comment (skjnldsv) [inline lib/private/AppFramework/Http/Request.php]:
```suggestion
			\OCP\Server::get(LoggerInterface::class)->critical(
```

**Review by skjnldsv — APPROVED** [review]

**Review by sorbaugh — APPROVED** [review]
