### PR TITLE
Fix js l10n registration to also work with more than one bundle

### LINKED ISSUE #15803: Login bundle doesn't handle translation
When setting the locale to dutch I would assume the login page to be in dutch...

Screen Shot 2019-05-29 at 22 26 20

The language is send correctly it seems as the bottom line is translated properly 

But If I run in the console: `t('core', 'Username or email')`
I do get: `Gebruikersnaam of email`

So also JS is doing it right. But just the vue part doesn't do it right.

### PR DESCRIPTION
**Pull request by ChristophWurst**
Fixes https://github.com/nextcloud/server/issues/15803

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Little detail on the new architecture: instead of having a singleton that keeps track of the state there can be more than one instance of the l10n (registry) module but all operate on the same data so it *just works*.

I don't think we can do much better in js. But if anybody has ideas please let me know :nerd_face:

**Review by skjnldsv — APPROVED** [review]

File: core/src/OC/l10n.js [hunk 1]
```diff
@@ -69,21 +75,19 @@ const L10n = {
...
+		registerAppTranslations(appName, bundle)
 
-			// generate plural function based on form
-			this._pluralFunctions[appName] = this._getPlural;
-		} else {
-			// Theme overwriting the default language
-			_.extend(self._bundles[appName], bundle);
-		}
+		// generate plural function based on form
+		this._pluralFunctions[appName] = this._getPlural;
```
Comment (MorrisJobke) [inline core/src/OC/l10n.js]: This then also needs to go into a global, otherwise it would be not set in other instances of the `L10n` object. (= other web pack bundles)

Comment (MorrisJobke) [reply core/src/OC/l10n.js]: Looking into the code is even weirder. As we just register the general plural method `_getPlural` here we can skip this completely and just call this method directly without storing it in `_pluralFunctions` in `translatePlural`.

Comment (MorrisJobke) [reply core/src/OC/l10n.js]: Problem then is if the user has `uk` as language, but for one app this translation is not available. Then the wrong plural method is used. So the plural method still needs to be set per language that is registered.

File: core/src/OC/l10n.js [hunk 2]
```diff
@@ -42,7 +48,7 @@ const L10n = {
 	 */
 	load: function(appName, callback) {
 		// already available ?
-		if (this._bundles[appName] || OC.getLocale() === 'en') {
```
Comment (MorrisJobke) [inline core/src/OC/l10n.js]: You can then remove the member variable `_bundles` as well. 😉

**Review by rullzer — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]
