### PR TITLE
Svg color api

### LINKED ISSUE #8702: icon-white class doesn't work on IE11
Since IE11 is still supported we cannot use the `.icon-white` class as added in #7319, since `filter:invert(100%);` is not supported: https://caniuse.com/#search=invert

A possible solution would be to use something like https://github.com/shekhardesigner/InvertImages to provide a fallback solution for IE11. We could even simplify the script a bit: https://github.com/shekhardesigner/InvertImages/blob/master/jquery.invertImages.js

@nextcloud/designers @pixelipo

### PR DESCRIPTION
**Pull request by skjnldsv**
This create a new endpoint to get one of our svg and change the colour.
This will allow us to:
- Only maintain black svg
- Only maintain one set of icon
- Allow us not to use any filter to invert icons: ie11 compatibility and better handling of background images

Fix #8702 

@nextcloud/designers do you see any issues with this?
@juliushaertl how do you think we should handle custom paths? Right now I implemented this for the actions folder only, but in the end we'll probably need this for the apps menu and other stuff.

Any example on where to use this?

### CODE REVIEW

File: core/Controller/SvgController.php [hunk 1]
```diff
@@ -0,0 +1,97 @@
...
+	 * @NoCSRFRequired
+	 *
+	 * Generate svg from filename with the requested color
+	 *
+	 * @param string $fileName
+	 * @param string $color
+	 * @return DataDisplayResponse|NotFoundException
+	 */
+	public function getSvg(string $fileName, $color = 'ffffff') {
+		$path = $this->serverRoot . "/core/img/actions/$fileName.svg";
```
Comment (MorrisJobke) [inline core/Controller/SvgController.php]: This then needs to be redone for all the other icon locations :/

Comment (skjnldsv) [reply core/Controller/SvgController.php]: Yeah, it was a first shot, I'm asking for feedback on how to tackle this :)
> how do you think we should handle custom paths? Right now I implemented this for the actions folder only, but in the end we'll probably need this for the apps menu and other stuff.

Comment (MorrisJobke) [reply core/Controller/SvgController.php]: On the other side I'm fine with doing it like this for now and test it.

Comment (skjnldsv) [reply core/Controller/SvgController.php]: @rullzer though we'll need to access icons in apps, so I guess I will add a new endpoint for apps icons

Comment (rullzer) [reply core/Controller/SvgController.php]: Sure but like I said. Small endpoints beat complex ones. so :rocket:

**Comment by juliushaertl** [comment]
> how do you think we should handle custom paths? Right now I implemented this for the actions folder only, but in the end we'll probably need this for the apps menu and other stuff.

I think we can add another endpoint that is a bit more generic, so it works for other apps with different icon paths as well. We do have such a route in the theming app already: https://github.com/nextcloud/server/blob/master/apps/theming/appinfo/routes.php#L80-L84

File: core/Controller/SvgController.php [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+
+		// replace any fill or stroke colors
+		$svg = preg_replace('/stroke="#([a-z0-9]{3,6})"/mi', 'stroke="#' . $color . '"', $svg);
+		$svg = preg_replace('/fill="#([a-z0-9]{3,6})"/mi', 'fill="#' . $color . '"', $svg);
+
+		$response = new DataDisplayResponse($svg, Http::STATUS_OK, ['Content-Type' => 'image/svg+xml']);
+
+		// Set cache control
+		$ttl = 31536000;
+		$response->addHeader('Cache-Control', 'max-age=' . $ttl . ', immutable');
```
Comment (juliushaertl) [inline core/Controller/SvgController.php]: Use $response->cacheFor() https://docs.nextcloud.com/server/13/developer_manual/api/OCP/AppFramework/Http/Response.html#OCP\AppFramework\Http\Response::cacheFor

**Comment by juliushaertl** [comment]
> I've added a new /svg/app/icon/color path :)

@skjnldsv I cannot find it, maybe you forgot to push? :wink:

**Comment by skjnldsv** [comment]
> @skjnldsv I cannot find it, maybe you forgot to push? wink

😅😅

**Review by MorrisJobke — APPROVED** [review]
I like it 👍

**Comment by skjnldsv** [comment]
@MorrisJobke still some fixes to do :)
- [ ] Find a way to recompile the icons on accessibility theme update
- [ ] Fix tests

File: lib/private/Template/IconsCacher.php [hunk 3]
```diff
@@ -0,0 +1,138 @@
...
+		try {
+			$data = $this->folder->getFile($this->fileName)->getContent();
+		} catch (NotFoundException $e) {
+			$data = '';
+		}
+		$icons = $this->getIconsFromCss($data . $css);
+
+		$data = '';
+		foreach ($icons as $icon => $url) {
+			$data .= "--$icon: url('$url?v=1');";
```
Comment (juliushaertl) [inline lib/private/Template/IconsCacher.php]: Is there a reason that the v=1 is appended here and not at the css level? I think that could lead to icons not being reloaded if they are changed.

Comment (skjnldsv) [reply lib/private/Template/IconsCacher.php]: I have no idea, they were always like that, so I didn't give it a lot of thought :)

Comment (juliushaertl) [reply lib/private/Template/IconsCacher.php]: I mean usually we have it inside of the css file, which is fine, since then it can be bumped once the icon file is changed, and the browsers can detect that they should load the file again.

Comment (skjnldsv) [reply lib/private/Template/IconsCacher.php]: We should probably remove all of those ?v=1 then

Comment (rullzer) [reply lib/private/Template/IconsCacher.php]: Probably yes.

**Comment by skjnldsv** [comment]
Okay, that's how I proceed:
I added a mixin for our scss which automatically handle the svg colour api
``` scss
.icon-screen-off {
	@include icon-color('screen-off', 'actions', $color-black, true);
}
```

Basically you just need to add this to your css and the background-image will be automatically added to a variable. The Mixin works that way:
``` scss
/**
 * SVG COLOR API
 * 
 * @param string $icon the icon filename
 * @param string $dir the icon folder within /core/img if $core or app name
 * @param string $color the desired color in hexadecimal
 * @param bool [$core] search icon in core
 *
 * @returns string the url to the svg api endpoint
 */
@mixin icon-color($icon, $dir, $color, $core: false)
```

Then, every time the scss is compiled, the system will detect if an icon is used via this mixin and export it to a new css file called icons-vars.css (cached into the appdata)
The accessibility on dark theme automatically parse the icons-vars file and invert the proper colors from fff->000 and 000->fff (we don't reverse any other colours)


@nextcloud/designers what are your thoughts? Is this a good behavior?
@MorrisJobke @jancborchardt @juliushaertl @rullzer

**Comment by skjnldsv** [comment]
I don't get the phan failure, can someone help?

```
+ ./lib/composer/phan/phan/phan -k build/.phan/config.php
lib/private/Log/Systemdlog.php:74 PhanUndeclaredFunction Call to undeclared function \sd_journal_send()
```

**Comment by nickvergessen** [comment]
Just needs a rebase.

**Comment by skjnldsv** [comment]
Failure unrelated!
Please review @nextcloud/designers

File: core/css/functions.scss [hunk 4]
```diff
@@ -0,0 +1,47 @@
...
+@mixin icon-color($icon, $dir, $color, $core: false) {
+	// remove # from color
+	// inspect cast int to string
+	$index: str-index(inspect($color), '#');
+	@if $index {
+		$color: str-slice(inspect($color), 2);
+	}
+	$varName: "--icon-#{$icon}-#{$color}";
+	@if $core {
+		#{$varName}: url('#{$webroot}/svg/core/#{$dir}/#{$icon}/#{$color}?v=1');
```
Comment (juliushaertl) [inline core/css/functions.scss]: Shouldn't we have another parameter in the mixin for this so app developers can bump the number if they change the icons?

Comment (skjnldsv) [reply core/css/functions.scss]: @juliushaertl I guess we could :)
Currently no one seems to use the version increment :/

Comment (juliushaertl) [reply core/css/functions.scss]: At least for the core CSS we have some:

```
core/css/styles.scss
98:	background-image: url('../img/background.png?v=2');

core/css/inputs.scss
245:				background-image: url('../img/actions/confirm-fade.svg?v=2') !important;

core/css/variables.scss
39:$image-login-background: url('../img/background.png?v=2');

core/css/icons.scss
119:	background-image: url('../img/actions/audio.svg?v=2');
154:	background-image: url('../img/actions/clippy.svg?v=2');
170:	background-image: url('../img/actions/confirm.svg?v=2');
174:	background-image: url('../img/actions/confirm-fade.svg?v=2');
178:	background-image: url('../img/actions/confirm-white.svg?v=2');
451:	background-image: url('../img/actions/video.svg?v=2');

core/css/guest.css
26:	background-image: url('../img/background.png?v=2');
632:	background-image: url('../img/actions/info-white.svg?v=2');
635:	background-image: url('../img/actions/confirm.svg?v=2');
638:	background-image: url('../img/actions/confirm-white.svg?v=2');
```

Also from my understanding we have no option to force reloading icons otherwise if they change.

**Comment by juliushaertl** [comment]
@skjnldsv Seems to have an issue with the index.php prefix again:

```
http://localhost:8140/svg/core/actions/timezone/000?v=1 404 (Not Found)
```

**Comment by skjnldsv** [comment]
@juliushaertl strange, the webroot should be applied here: 
https://github.com/nextcloud/server/pull/9984/files#diff-3a9a30c772db7b84e90a0d119b278f94R43
https://github.com/nextcloud/server/pull/9984/files#diff-dc68e93a3894ea57d470448bd3fd66e3R260

File: apps/accessibility/css/themedark.scss [hunk 5]
```diff
@@ -37,12 +37,16 @@ $color-border-dark: lighten($color-main-background, 14%);
...
 .app-navigation-entry-menu,
 .popovermenu,
 #header .menu {
 	border: 1px solid var(--color-border);
 }
+
+// since svg icons are inverted, revert to white for the header
+.header-right > * {
+	[class^='icon-'], [class*=' icon-'] {
+		filter: invert(100%);
```
Comment (juliushaertl) [inline apps/accessibility/css/themedark.scss]: Can we get rid of this invert rule as well?

Comment (skjnldsv) [reply apps/accessibility/css/themedark.scss]: No, header needs to use the proper urls
Or we need to exclude the variable invert for the header icons :)

Comment (juliushaertl) [reply apps/accessibility/css/themedark.scss]: Yes, I'd say we should exclude those. Their color anyway depends on the theming app color so we should keep that and not invert it.

Comment (skjnldsv) [reply apps/accessibility/css/themedark.scss]: Hum, since we're changing the global variables, I'm not sure we can ignore them :/

Comment (juliushaertl) [reply apps/accessibility/css/themedark.scss]: How about just setting the icon for the header with $color-primary-text instead of $color-white? Then they should not be inverted, if I get the code right.

Comment (juliushaertl) [reply apps/accessibility/css/themedark.scss]: So we would have the regular .icon-contacts with $color-white and a header .icon-contacts with $color-primary-text. Yes this will be some duplication, but the icons where this is used are quite limited, so it would be ok i think.

Comment (skjnldsv) [reply apps/accessibility/css/themedark.scss]: @juliushaertl Of course!!! Great thinking! :+1: :hugs:

**Comment by rullzer** [comment]
What is left to do here?

**Comment by skjnldsv** [comment]
@rullzer one small fix for the header :)
You can review still, everything works

**Comment by skjnldsv** [comment]
@juliushaertl yeah, it's a tricky part.
I cannot use the variables name in scss unless we go for scss maps.
So I cannot differentiate variables that are using the $primary or $white colour since in the end, both of them will be ffffff. 
Not sure if I'm being clear :p

**Comment by juliushaertl** [comment]
@skjnldsv I've pushed two other minor fixes. I'd say we should get this in and maybe handle the inverted other icons later. This is anyway just an issue for IE11 in combination for accessibility. For everything else this fixes the issue of inverting background images and makes it much easier to keep various colors of the icons without storing them individually. So it would be good from my side now.

cc @nextcloud/accessibility @nextcloud/designers

**Comment by juliushaertl** [comment]
- [ ] We need to fix other apps like activity, since some use `IURLGenerator->imagePath('core', 'places/contacts-dark.svg');` which is not available anymore after this PR.

**Comment by rullzer** [comment]
Conflicts.

**Comment by juliushaertl** [comment]
@rullzer Rebased.

File: core/Controller/SvgController.php [hunk 6]
```diff
@@ -0,0 +1,136 @@
...
+	/**
+	 * @NoAdminRequired
+	 * @NoCSRFRequired
+	 *
+	 * Generate svg from filename with the requested color
+	 *
+	 * @param string $folder
+	 * @param string $fileName
+	 * @param string $color
+	 * @return DataDisplayResponse|NotFoundException
```
Comment (rullzer) [inline core/Controller/SvgController.php]: You don't return an exception you throw it ;)

File: core/Controller/SvgController.php [hunk 7]
```diff
@@ -0,0 +1,136 @@
...
+	 */
+	public function getSvgFromCore(string $folder, string $fileName, string $color = 'ffffff') {
```
Comment (rullzer) [inline core/Controller/SvgController.php]: You can also declare return types ;)

File: core/Controller/SvgController.php [hunk 8]
```diff
@@ -0,0 +1,136 @@
...
+	/**
+	 * @NoAdminRequired
+	 * @NoCSRFRequired
+	 *
+	 * Generate svg from filename with the requested color
+	 *
+	 * @param string $app
+	 * @param string $fileName
+	 * @param string $color
+	 * @return DataDisplayResponse|NotFoundException
```
Comment (rullzer) [inline core/Controller/SvgController.php]: NotFoundResponse it seems

**Review by MorrisJobke — CHANGES_REQUESTED** [review]
Unit tests fail:


```

1) Test\Template\SCSSCacherTest::testProcessUncachedFileNoAppDataFolder

/drone/src/github.com/nextcloud/server/tests/lib/Template/SCSSCacherTest.php:127
/drone/src/github.com/nextcloud/server/lib/private/Template/SCSSCacher.php:245
/drone/src/github.com/nextcloud/server/lib/private/Template/SCSSCacher.php:142
/drone/src/github.com/nextcloud/server/tests/lib/Template/SCSSCacherTest.php:143

2) Test\Template\SCSSCacherTest::testProcessUncachedFile

/drone/src/github.com/nextcloud/server/tests/lib/Template/SCSSCacherTest.php:167
/drone/src/github.com/nextcloud/server/lib/private/Template/SCSSCacher.php:245
/drone/src/github.com/nextcloud/server/lib/private/Template/SCSSCacher.php:142
/drone/src/github.com/nextcloud/server/tests/lib/Template/SCSSCacherTest.php:179

3) Test\Template\SCSSCacherTest::testProcessCachedFile

/drone/src/github.com/nextcloud/server/tests/lib/Template/SCSSCacherTest.php:203
/drone/src/github.com/nextcloud/server/lib/private/Template/SCSSCacher.php:245
/drone/src/github.com/nextcloud/server/lib/private/Template/SCSSCacher.php:142
/drone/src/github.com/nextcloud/server/tests/lib/Template/SCSSCacherTest.php:210

4) Test\Template\SCSSCacherTest::testProcessCachedFileMemcache

/drone/src/github.com/nextcloud/server/tests/lib/Template/SCSSCacherTest.php:242
/drone/src/github.com/nextcloud/server/lib/private/Template/SCSSCacher.php:245
/drone/src/github.com/nextcloud/server/lib/private/Template/SCSSCacher.php:142
/drone/src/github.com/nextcloud/server/tests/lib/Template/SCSSCacherTest.php:249

5) Test\Template\SCSSCacherTest::testGetCachedSCSS with data set #0 ('core', 'core/css/styles.scss', '/css/core/styles.css', '14.0.0 alpha')
Expectation failed for method name is equal to "linkToRoute" when invoked 1 time(s)
Parameter 1 for invocation OCP\IURLGenerator::linkToRoute('core.Css.getCss', Array (...)): string does not match expected value.
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    'fileName' => '77d8-8422-styles.css'
+    'fileName' => '77d8-0ab8-styles.css'

/drone/src/github.com/nextcloud/server/lib/private/Template/SCSSCacher.php:365
/drone/src/github.com/nextcloud/server/tests/lib/Template/SCSSCacherTest.php:454

6) Test\Template\SCSSCacherTest::testGetCachedSCSS with data set #1 ('files', 'apps/files/css/styles.scss', '/css/files/styles.css', '1.9.0')
Expectation failed for method name is equal to "linkToRoute" when invoked 1 time(s)
Parameter 1 for invocation OCP\IURLGenerator::linkToRoute('core.Css.getCss', Array (...)): string does not match expected value.
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    'fileName' => 'd16b-8422-styles.css'
+    'fileName' => 'd16b-0ab8-styles.css'

/drone/src/github.com/nextcloud/server/lib/private/Template/SCSSCacher.php:365
/drone/src/github.com/nextcloud/server/tests/lib/Template/SCSSCacherTest.php:454
```

File: core/Controller/SvgController.php [hunk 9]
```diff
@@ -0,0 +1,136 @@
...
+	 */
+	public function getSvgFromApp(string $app, string $fileName, string $color = 'ffffff') {
+
+		if ($app === 'settings') {
+			$path = $this->serverRoot . "/settings/img/$fileName.svg";
+			return $this->getSvg($path, $color, $fileName);
+		}
+
+		$appPath = \OC_App::getAppWebPath($app);
```
Comment (rullzer) [inline core/Controller/SvgController.php]: Can't the appmanager do this?

File: lib/private/Template/IconsCacher.php [hunk 10]
```diff
@@ -0,0 +1,146 @@
+<?php
+/**
```
Comment (rullzer) [inline lib/private/Template/IconsCacher.php]: strict

File: tests/lib/Template/IconsCacherTest.php [hunk 11]
```diff
@@ -0,0 +1,126 @@
+<?php
+/**
```
Comment (rullzer) [inline tests/lib/Template/IconsCacherTest.php]: strict

**Review by rullzer — DISMISSED** [review]

**Review by rullzer — APPROVED** [review]
Lets do this. :guitar:

**Review by MorrisJobke — APPROVED** [review]

File: lib/private/Template/IconsCacher.php [hunk 12]
```diff
@@ -0,0 +1,147 @@
...
+	protected $appData;
+
+	/** @var ISimpleFolder */
+	private $folder;
+
+	/** @var IURLGenerator */
+	protected $urlGenerator;
+
+	/** @var string */
+	private $iconVarRE = '/--(icon-[a-z0-9-]+): url\(["\']([a-z0-9-_\~\/\?\&\=\.]+)[^;]+;/m';
```
Comment (skjnldsv) [inline lib/private/Template/IconsCacher.php]: @juliushaertl some of the icons are broken because of your last edit.
We shoudl exclude the ?v= from the matches because otherwise it gets re-added on every compile and we get stuff like that: --icon-confirm-fade-000: url('/svg/core/actions/confirm-fade/000?v=2?v=1?v=1?v=1?v=1');

Was there a specific reason? Or can I remove the ?=& from the regex? :)

Comment (juliushaertl) [reply lib/private/Template/IconsCacher.php]: No, your right, we can remove those. The others might be needed depending on the base URL of the nextcloud installation.

Comment (skjnldsv) [reply lib/private/Template/IconsCacher.php]: Weeee :balloon:

File: core/css/icons.scss [hunk 13]
```diff
@@ -101,545 +116,545 @@ img, object, video, button, textarea, input, select, div[contenteditable='true']
...
-	background-image: url('../img/actions/video.svg?v=1');
+	@include icon-color('video', 'actions', $color-black, 2, true);
 }
 
-/* TODO: to be deprecated; use .icon-video-off.icon-white.icon-shadow */
 .icon-video-white {
-	background-image: url('../img/actions/video.svg?v=2');
-	filter: invert(100%) drop-shadow(1px 1px 4px var(--color-box-shadow));
+	@include icon-color('video', 'actions', $color-white, 1, true);
+	filter: drop-shadow(1px 1px 4px var(--color-box-shadow));
```
Comment (nickvergessen) [inline core/css/icons.scss]: Is there a bigger reason the `invert(100%)` was removed? this breaks the icons on the Talk UI, because now the white icon has a white shadow on a white background while you are waiting for a participant to join the call

Comment (juliushaertl) [reply core/css/icons.scss]: Invert is not available in IE11 (see #8702)

@skjnldsv Do you have an idea why the shadow would be white? The drop shadow should not be changed, right?

**Comment by skjnldsv** [comment]
The shadow? you mean `drop-shadow`?
It should not be touched.

@nickvergessen are you using the proper new css class? `icon-video`

**Comment by MorrisJobke** [comment]
This causes high load on Safari: #11179

😢
