### PR TITLE
fix(SharedStorage): Check if storage ID is set on cache

### LINKED ISSUE #50235: [Bug]: Undefined array key "storage_string_id" at /apps/files_sharing/lib/SharedStorage.php#483
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After updating from 29.0.10 to 29.0.11.1, I got lots of errors in the Nextcloud logfile, all of the same kind for a WebDAV PROPFIND operation with different filenames.

### Steps to reproduce

1. Update to 29.0.11
2. Sync files via WebDAV
3. See logfile

### Expected behavior

No errors in log

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 28.0.1 to 28.0.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [x] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "XXX",
            "XXX"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "29.0.11.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbdriveroptions": {
            "1002": "SET wait_timeout = 28800"
        },
        "installed": true,
        "default_language": "de",
        "updatechecker": true,
        "has_internet_connection": true,
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "appstoreenabled": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "loglevel": 2,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "overwritehost": "XXX",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "XXX",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "\/data\/nextcloud_skel",
        "activity_expire_days": 14,
        "integrity.check.disabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "knowledgebaseenabled": false,
        "defaultapp": "",
        "sharing.minSearchStringLength": 4,
        "sharing.maxAutocompleteResults": 5,
        "maintenance": false,
        "debug": false,
        "htaccess.RewriteBase": "\/",
        "proxy": "XXX",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "updater.release.channel": "stable",
        "lookup_server": "",
        "app_install_overwrite": [
            "quotaadmin",
            "drop_account",
            "gpxedit",
            "twofactor_u2f",
            "metadata",
            "files_mindmap"
        ],
        "enable_previews": true,
        "preview_max_x": 700,
        "preview_max_y": 700,
        "preview_max_scale_factor": 2,
        "tempdirectory": "\/data\/tmp\/nextcloud",
        "localstorage.allowsymlinks": true,
        "hashingMemoryCost": 8,
        "default_phone_region": "de",
        "upgrade.disable-web": true,
        "preview_max_filesize_image": 20,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "profile.enabled": false,
        "lost_password_link": "disabled",
        "bulkupload.enabled": false,
        "trashbin_retention_obligation": "auto, 14",
        "versions_retention_obligation": "auto, 14",
        "maintenance_window_start": 18,
        "files_no_background_scan": true
    }
}
```

### List of activated Apps

```shell
- activity: 2.21.1
  - announcementcenter: 7.0.1
  - bruteforcesettings: 2.9.0
  - calendar: 4.7.16
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - collectives: 2.15.2
  - comments: 1.19.0
  - contacts: 6.0.2
  - contactsinteraction: 1.10.0
  - dav: 1.30.1
  - deck: 1.13.3
  - drawio: 3.0.3
  - drop_account: 2.6.1
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.1
  - files_antivirus: 5.6.1
  - files_downloadactivity: 1.17.0
  - files_downloadlimit: 2.0.0
  - files_mindmap: 0.0.32
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_retention: 1.18.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - forms: 4.3.5
  - guests: 3.2.0
  - login_notes: 1.6.1
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - metadata: 0.21.0
  - notes: 4.11.0
  - notifications: 2.17.0
  - oauth2: 1.17.1
  - photos: 2.5.0
  - polls: 7.2.9
  - provisioning_api: 1.19.0
  - quota_warning: 1.20.0
  - quotaadmin: 0.0.5
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - spreed: 19.0.12
  - systemtags: 1.19.0
  - tables: 0.8.3
  - tasks: 0.16.1
  - text: 3.10.1
  - theming: 2.4.0
  - theming_customcss: 1.18.0
  - twofactor_backupcodes: 1.18.0
  - twofactor_totp: 11.0.0-dev
  - twofactor_webauthn: 1.4.0
  - updatenotification: 1.19.1
  - user_ldap: 1.20.0
  - viewer: 2.3.0
  - whiteboard: 1.0.4
  - workflowengine: 2.11.0
```

### Nextcloud Signing status

```shell
Integrity checker has been disabled. Integrity cannot be verified.
```

### Nextcloud Logs

```json
{"reqId":"XXX","level":3,"time":"2025-01-17T13:43:47+00:00","remoteAddr":"XXX","user":"XXX","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/fXXX","message":"Undefined array key \"storage_string_id\" at /data/nextcloud_a2/apps/files_sharing/lib/SharedStorage.php#483","userAgent":"Mozilla/5.0 (Linux) mirall/3.12.0-20240214.183952.1c1e752c4-1.0~jammy1 (Nextcloud, ubuntu-6.5.0-21-generic ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"29.0.11.1","data":{"app":"PHP"}}
```

### Additional info

The code at the error position is this:
```
$node = $this->getShare()->getNodeCacheEntry();
if ($node instanceof CacheEntry) {
           $storageId = $node->getData()['storage_string_id'];  // <---- error line
```
I tried to find something, but the $node there does not contain the key storage_string_id, it looks like there are only the columns from the filecache table, so only the numerical storageid is there. I don't know where this is generated / comes from, the $this->getShare() returns a IShare supershare attribute, which is set via $arguments in the constructor, so I don't know how to fix it.

### PR DESCRIPTION
**Pull request by solracsf**
* Resolves: https://github.com/nextcloud/server/issues/50235

## Summary

Else handle cache updating by the share source

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/files_sharing/lib/SharedStorage.php [hunk 1]
```diff
@@ -437,16 +438,15 @@ public function getWatcher(string $path = '', ?IStorage $storage = null): IWatch
 		// Get node information
 		$node = $this->getShare()->getNodeCacheEntry();
 		if ($node instanceof CacheEntry) {
-			$storageId = $node->getData()['storage_string_id'];
+			$storageId = $node->getData()['storage_string_id'] ?? null;
 			// for shares from the home storage we can rely on the home storage to keep itself up to date
 			// for other storages we need use the proper watcher
-			if (!(str_starts_with($storageId, 'home::') || str_starts_with($storageId, 'object::user'))) {
+			if ($storageId && !(str_starts_with($storageId, 'home::') || str_starts_with($storageId, 'object::user'))) {
```
Comment (susnux) [inline apps/files_sharing/lib/SharedStorage.php:444]:
```suggestion
			if ($storageId !== null && !(str_starts_with($storageId, 'home::') || str_starts_with($storageId, 'object::user'))) {
```

**Review by ChristophWurst — APPROVED** [review]
I'm not an expert for file sharing but this looks sane and like a good hardening :+1:

**Comment by gonzalo** [comment]
I tried to apply this file on my server because I'm having thousands of errors related.  And I got instead this other error message (lots of them)

{"reqId":"2fioH9S87r60gMdePQlk","level":3,"time":"2025-02-13T11:29:46+00:00","remoteAddr":"172.16xxxxxx","user":"xxxxxx@xxxx.xxxxx","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/xxxxxx%40xxxxx/Espai_IUIEG/xxxxxxxxxxx","message":"Declaration of OCA\\Files_Sharing\\SharedStorage::__construct(array $parameters) must be compatible with OCP\\Files\\Storage\\IStorage::__construct($parameters) at /aplica/nextcloud/www/nextcloud/apps/files_sharing/lib/SharedStorage.php#92","userAgent":"Microsoft-WebDAV-MiniRedir/10.0.19045","version":"30.0.5.1","data":{"app":"PHP"}}

**Comment by susnux** [comment]
> Running nextcloud 30.0.5

Yes because the parameter is incompatible on 30. You need to remove the `array` before `$parameters`

**Comment by gonzalo** [comment]
I will try but... commit should be adapted depending on nextcloud version?

**Comment by solracsf** [comment]
> I will try but... commit should be adapted depending on nextcloud version?

Yes, dont replace a file from different branches. You can always apply the patch:
https://patch-diff.githubusercontent.com/raw/nextcloud/server/pull/50769.patch
https://www.cyberciti.biz/faq/appy-patch-file-using-patch-command/

But, if you're not familiar with these, just wait for an **official and released** version please (recommended).

**Comment by inDane** [comment]
> > I will try but... commit should be adapted depending on nextcloud version?
> 
> Yes, dont replace a file from different branches. You can always apply the patch: https://patch-diff.githubusercontent.com/raw/nextcloud/server/pull/50769.patch https://www.cyberciti.biz/faq/appy-patch-file-using-patch-command/
> 
> But, if you're not familiar with these, just wait for an **official and released** version please (recommended).

I've tried this for Nxcl 29.0.11.1 but i think the patch is for nextcloud 30, right? Because for me it failed. Just a heads up for others.

**Review by Altahrim — APPROVED** [review]
