### PR TITLE
fix(l10n): Less jargon in source strings

### LINKED ISSUE #53775: [Bug]: Unable to share files internally
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I cannot share files. When I press Share, the dropdown menu has no users to share files with.
Sharing functionality is broken

Image

### Steps to reproduce

1. Install Nextcloud (31.0.6) on a server, Enter it from PC via Chrome
2. Add 2 users (both are in group admins)
3. Try to share a file from one user to another
4. See that there no other users

### Expected behavior

I expect to see a username is dropdown menu with who I want to share a file or folder.

### Nextcloud Server version

31

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 31 to 32)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "31.0.6.2",
        "overwrite.cli.url": ,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "memories.db.triggers.fcu": true,
        "memories.exiftool": "\/var\/www\/nextcloud\/apps\/memories\/bin-ext\/exiftool-amd64-glibc",
        "memories.vod.path": "\/var\/www\/nextcloud\/apps\/memories\/bin-ext\/go-vod-amd64",
        "memories.gis_type": 1,
        "defaultapp": "files,dashboard"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - app_api: 5.0.2
  - bruteforcesettings: 4.0.0
  - circles: 31.0.0
  - cloud_federation_api: 1.14.0
  - contactsinteraction: 1.12.0
  - dashboard: 7.11.0
  - dav: 1.33.0
  - federatedfilesharing: 1.21.0
  - files: 2.3.1
  - files_downloadlimit: 4.0.0
  - files_external: 1.23.0
  - files_pdfviewer: 4.0.0
  - files_reminders: 1.4.0
  - files_sharing: 1.23.1
  - files_trashbin: 1.21.0
  - files_versions: 1.24.0
  - firstrunwizard: 4.0.0
  - logreader: 4.0.0
  - lookup_server_connector: 1.19.0
  - memories: 7.5.2
  - nextcloud_announcements: 3.0.0
  - notifications: 4.0.0
  - oauth2: 1.19.1
  - password_policy: 3.0.0
  - photos: 4.0.0-dev.1
  - privacy: 3.0.0
  - profile: 1.0.0
  - provisioning_api: 1.21.0
  - recommendations: 4.0.0
  - related_resources: 2.0.0
  - serverinfo: 3.0.0
  - settings: 1.14.0
  - sharebymail: 1.21.0
  - support: 3.0.0
  - survey_client: 3.0.0
  - text: 5.0.0
  - theming: 2.6.1
  - twofactor_backupcodes: 1.20.0
  - updatenotification: 1.21.0
  - user_status: 1.11.0
  - viewer: 4.0.0
  - webhook_listeners: 1.2.0
  - workflowengine: 2.13.0
Disabled:
  - activity: 4.0.0 (installed 2.21.1)
  - admin_audit: 1.21.0
  - comments: 1.21.0 (installed 1.15.0)
  - encryption: 2.19.0
  - federation: 1.21.0 (installed 1.15.0)
  - suspicious_login: 9.0.1
  - systemtags: 1.21.1 (installed 1.15.0)
  - twofactor_nextcloud_notification: 5.0.0
  - twofactor_totp: 13.0.0-dev.0
  - user_ldap: 1.22.0
  - weather_status: 1.11.0 (installed 1.5.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```json

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by kra-mo**
Resolves #53775

## Summary
Removes:
- “enable” for settings
- “settings” for settings sections
- “all” when there is no obvious subset of items
- “show” and “open” for navigation actions
- “changes” for applying/discarding
- “to clipboard” when copying
- Explaining things that cannot happen
- Explaining things twice, right below each other
- Unnecessary technical jargon
- Text that sounds like marketing copy and serves no other purpose

If there is anything in particular that was there for a specific reason, please do tell me.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required

### CODE REVIEW

**Comment by kra-mo** [comment]
cc @marcoambrosini @jancborchardt

File: apps/federatedfilesharing/src/components/PersonalSettings.vue [hunk 1]
```diff
@@ -146,7 +146,7 @@ export default {
 </a>`
 		},
 		copyLinkTooltip() {
-			return this.isCopied ? t('federatedfilesharing', 'Cloud ID copied to the clipboard') : t('federatedfilesharing', 'Copy to clipboard')
+			return this.isCopied ? t('federatedfilesharing', 'Cloud ID copied to the clipboard') : t('federatedfilesharing', 'Copy')
```
Comment (skjnldsv) [inline apps/federatedfilesharing/src/components/PersonalSettings.vue]: Wanna remove that section too?

```suggestion
			return this.isCopied ? t('federatedfilesharing', 'Cloud ID copied') : t('federatedfilesharing', 'Copy')
```

**Review by skjnldsv — APPROVED** [review]
Looking good, let's see tests results!

File: apps/federatedfilesharing/src/components/PersonalSettings.vue (hunk 1 above)
Comment (kra-mo) [reply apps/federatedfilesharing/src/components/PersonalSettings.vue]: Aha! Only searched for "to clipboard", not "to the clipboard".

Hold on… :)

Comment (skjnldsv) [reply apps/federatedfilesharing/src/components/PersonalSettings.vue]: image

Comment (kra-mo) [reply apps/federatedfilesharing/src/components/PersonalSettings.vue]: Surprisingly, it seems like that was the only place it appeared haha

**Review by susnux — COMMENTED** [review]
Would be nice to split such changes, at least into commits but better into separate PRs.
Because you not only change l10n strings as the commit and the PR suggests, but also remove user notifications from the actions.

So e.g. on PR with only the string change + one PR with removing notifications.

File: apps/files/src/filters/TypeFilter.ts [hunk 2]
```diff
@@ -73,7 +73,7 @@ const getTypePresets = async () => [
 	{
 		id: 'image',
 		// TRANSLATORS: This is for filtering files, e.g. PNG or JPEG, so photos, drawings, or images in general
-		label: t('files', 'Photos and images'),
+		label: t('files', 'Images'),
```
Comment (susnux) [inline apps/files/src/filters/TypeFilter.ts:76]: Not sure about this one, we had a discussion with translators in the past about this being not clear.

File: apps/files/src/views/Settings.vue [hunk 3]
```diff
@@ -113,22 +113,20 @@
 		</NcAppSettingsSection>
 
 		<NcAppSettingsSection id="warning" :name="t('files', 'Warnings')">
-			<em>{{ t('files', 'Prevent warning dialogs from open or reenable them.') }}</em>
 			<NcCheckboxRadioSwitch type="switch"
 				:checked="userConfig.show_dialog_file_extension"
 				@update:checked="setConfig('show_dialog_file_extension', $event)">
-				{{ t('files', 'Show a warning dialog when changing a file extension.') }}
+				{{ t('files', 'Warn me before changing a file extension') }}
```
Comment (susnux) [inline apps/files/src/views/Settings.vue]: I do not think we use this tone somewhere else, IIRC all apps and other places do not speak to you in first person (omitting the `me`). Which I imagine could be a translation problem for consistency (because translations use the formal language, in the default German this is hard to translate (event though we have two different translations for German, a formal ("Sie") and a informal one - but the formal one if the Nextcloud official)

Comment (susnux) [reply apps/files/src/views/Settings.vue]: (just saying that this maybe needs coordination with out translators as a change of language)

File: apps/files/src/views/Settings.vue [hunk 4]
```diff
@@ -137,39 +135,39 @@
...
+						{{ t('files', 'Delete') }}
 					</dd>
 				</div>
 				<div>
 					<dt class="shortcut-key">
 						<kbd>s</kbd>
 					</dt>
 					<dd class="shortcut-description">
-						{{ t('files', 'Favorite or remove a file from favorites') }}
+						{{ t('files', 'Add or remove favorite') }}
```
Comment (susnux) [inline apps/files/src/views/Settings.vue:162]: Is it possible in English to use the zeroarticle here? I mean instead of

```suggestion
						{{ t('files', 'Add or remove a favorite') }}
```

File: apps/files_sharing/src/views/SharingTab.vue [hunk 5]
```diff
@@ -230,9 +230,9 @@ export default {
...
-			externalSharesHelpText: t('files_sharing', 'Use this method to share files with individuals or organizations outside your organization. Files and folders can be shared via public share links and email addresses. You can also share to other Nextcloud accounts hosted on different instances using their federated cloud ID.'),
-			additionalSharesHelpText: t('files_sharing', 'Shares that are not part of the internal or external shares. This can be shares from apps or other sources.'),
+			internalSharesHelpText: t('files_sharing', 'Share files within your organization. Recipients who can already view the file can also use this link for easy access.'),
+			externalSharesHelpText: t('files_sharing', 'Share files with others outside your organization via public links and email addresses. You can also share to Nextcloud accounts on other instances using their federated cloud ID.'),
+			additionalSharesHelpText: t('files_sharing', 'Shares from apps or other sources which are not internal or external.'),
```
Comment (susnux) [inline apps/files_sharing/src/views/SharingTab.vue]: I think the last part is a bit confusing, if its only me then you should add a comment for translators as there would be likely also confused ones :sweat_smile:
At least for me its easier readable if

```suggestion
			additionalSharesHelpText: t('files_sharing', 'Shares from apps or other sources which are not included in internal or external shares.'),
```

To make clear that the last part is about the two other sections in the UI and not about the `sources`.

**Review by susnux — COMMENTED** [review]
I am not sure about the removed cancellation notifications, as I remember we had requests to explicitly add those to make clear whats going on.
Otherwise just a few comments.

File: apps/federatedfilesharing/src/components/PersonalSettings.vue (hunk 1 above)
Comment (skjnldsv) [reply apps/federatedfilesharing/src/components/PersonalSettings.vue]: I blame my french brain

File: apps/files/src/views/Settings.vue (hunk 3 above)
Comment (jancborchardt) [reply apps/files/src/views/Settings.vue]: How about this?
```suggestion
				{{ t('files', 'Warn before changing a file extension') }}
```

File: apps/files/src/views/Settings.vue (hunk 4 above)
Comment (jancborchardt) [reply apps/files/src/views/Settings.vue:162]: @susnux it sounds fine to me without article.

File: apps/files/src/filters/TypeFilter.ts (hunk 2 above)
Comment (jancborchardt) [reply apps/files/src/filters/TypeFilter.ts:76]: Yeah I remember too – "Photos and images" seems explicitly clearer for regular people.

**Review by jancborchardt — COMMENTED** [review]
Good on removing the overbearing notifications. For the record @susnux yes we did talk about it and also had a request for it, but in practice this proves to be super annoying and results in notification fatigue and missing actually important notifications. :\

File: apps/files/src/components/FilesNavigationSearch.vue [hunk 6]
```diff
@@ -55,9 +55,9 @@ const isSearchView = computed(() => currentView.value.id === VIEW_ID)
  */
 const searchLabel = computed(() => {
 	if (searchStore.scope === 'globally') {
-		return t('files', 'Search globally by filename …')
+		return t('files', 'Search everywhere …')
 	}
-	return t('files', 'Search here by filename …')
+	return t('files', 'Search this location …')
```
Comment (jancborchardt) [inline apps/files/src/components/FilesNavigationSearch.vue]: Wouldn’t this be more brief and "human"?
```suggestion
	return t('files', 'Search here …')
```

File: apps/files/src/components/FilesNavigationSearch.vue [hunk 7]
```diff
@@ -72,13 +72,13 @@ const searchLabel = computed(() => {
 					<template #icon>
 						<NcIconSvgWrapper :path="mdiMagnify" />
 					</template>
-					{{ t('files', 'Filter and search from this location') }}
+					{{ t('files', 'Search this location') }}
```
Comment (jancborchardt) [inline apps/files/src/components/FilesNavigationSearch.vue]: Similarly here:
```suggestion
					{{ t('files', 'Search here') }}
```

**Review by jancborchardt — COMMENTED** [review]
Really good also on the general simpler wording @kra-mo :) makes everything much easier to read.

File: apps/files/src/views/Settings.vue (hunk 4 above)
Comment (susnux) [reply apps/files/src/views/Settings.vue:162]: yeah than I am fine with it - my German brain does not like the *zero article* ^^

**Comment by kra-mo** [comment]
> Good on removing the overbearing notifications. For the record @susnux yes we did talk about it and also had a request for it, but in practice this proves to be super annoying and results in notification fatigue and missing actually important notifications. :\

I think it is totally fair to show toasts for actions that aren't all that visible and that you might miss otherwise, but for cancellation of actions, you can see the dialog disappear. There already is visual confirmation, I don't think anyone would miss the toasts there.

File: apps/files/src/filters/TypeFilter.ts (hunk 2 above)
Comment (jancborchardt) [reply apps/files/src/filters/TypeFilter.ts:76]: @rakekniven do you remember what this discussion was about? Other apps like e.g. Google Files on Android, Files on iOS use just "Images", so it would be good to adjust to what’s commonly used and only do that.

File: apps/files/src/components/FilesNavigationSearch.vue (hunk 6 above)
Comment (kra-mo) [reply apps/files/src/components/FilesNavigationSearch.vue]: Fair enough, I iterated a lot on this one lol.

File: apps/files/src/views/Settings.vue [hunk 8]
```diff
@@ -101,7 +101,7 @@
 					:href="webdavDocs"
 					target="_blank"
 					rel="noreferrer noopener">
-					{{ t('files', 'Use this address to access your Files via WebDAV.') }} ↗
+					{{ t('files', 'How to access files using WebDAV') }} ↗
```
Comment (rakekniven) [inline apps/files/src/views/Settings.vue:104]: This isn't a replacement.

File: apps/systemtags/src/components/SystemTagPicker.vue [hunk 9]
```diff
@@ -89,7 +89,7 @@
 			<!-- Note -->
 			<div class="systemtags-picker__note">
 				<NcNoteCard v-if="!hasChanges" type="info">
-					{{ canEditOrCreateTag ? t('systemtags', 'Select or create tags to apply to all selected files'): t('systemtags', 'Select tags to apply to all selected files') }}
```
Comment (rakekniven) [inline apps/systemtags/src/components/SystemTagPicker.vue:98]: The option to create tags is omitted here

File: apps/files/src/views/Settings.vue (hunk 8 above)
Comment (kra-mo) [reply apps/files/src/views/Settings.vue:104]: It's a link to the documentation explaining just that, so I think it is a lot more appropriate. "Use this address to access your Files via WebDAV." is just redundant and doesn't actually explain where clicking the link brings you.

**Comment by rakekniven** [comment]
> Would be nice to split such changes, at least into commits but better into separate PRs. Because you not only change l10n strings as the commit and the PR suggests, but also remove user notifications from the actions.
> 
> So e.g. on PR with only the string change + one PR with removing notifications.

I fully support this.

What is the background of these changes?
It affects many apps, but only here in the server repo.

I would like us to work on the [Guidelines](https://docs.nextcloud.com/server/latest/developer_manual/basics/translations.html#guidelines) so that all apps here are better and more consistent.

File: apps/files/src/utils/davUtils.ts [hunk 10]
```diff
@@ -29,7 +29,7 @@ export function humanizeWebDAVError(error: unknown) {
 			} else if (status === 403) {
 				return t('files', 'This operation is forbidden')
 			} else if (status === 500) {
-				return t('files', 'This directory is unavailable, please check the logs or contact the administrator')
+				return t('files', 'This folder is unavailable, please try again later or contact the administrator')
```
Comment (rakekniven) [inline apps/files/src/utils/davUtils.ts]: administrator -> administration

**Comment by kra-mo** [comment]
> What is the background of these changes? It affects many apps, but only here in the server repo.
> 
> I would like us to work on the [Guidelines](https://docs.nextcloud.com/server/latest/developer_manual/basics/translations.html#guidelines) so that all apps here are better and more consistent.

Sure, I completely agree. This is a bit of a personal initiative of mine to improve strings across Nextcloud, I started with `server` just to set an example and discuss initially, but I'd like to expand changes more generally.

File: apps/files/src/views/Settings.vue [hunk 11]
```diff
@@ -8,7 +8,7 @@
 		:name="t('files', 'Files settings')"
 		@update:open="onClose">
 		<!-- Settings API-->
-		<NcAppSettingsSection id="settings" :name="t('files', 'Files settings')">
+		<NcAppSettingsSection id="settings" :name="t('files', 'General')">
```
Comment (rakekniven) [inline apps/files/src/views/Settings.vue:11]: "Files" ist the app name.
For nearly all apps we have "`<appname>` setting e. g. "Mail settings"
Please revert this as it breaks an unwritten rule.

**Review by rakekniven — CHANGES_REQUESTED** [review]

File: apps/files/src/views/Settings.vue (hunk 11 above)
Comment (kra-mo) [reply apps/files/src/views/Settings.vue:11]: This is not the main title, it is the first section. You just experienced how confusing it was :)

File: apps/systemtags/src/components/SystemTagPicker.vue (hunk 9 above)
Comment (kra-mo) [reply apps/systemtags/src/components/SystemTagPicker.vue:98]: On purpose, it is repeated information as it is already explained somewhere else in the same dialog.

File: apps/files/src/utils/davUtils.ts (hunk 10 above)
Comment (kra-mo) [reply apps/files/src/utils/davUtils.ts]: Fair enough but not part of this PR. I'd make it a separate one if you want to change it, it'd be a bigger initiative to merge the two ways of phrasing since it is used *a lot*, across apps.

File: apps/files/src/views/Settings.vue (hunk 11 above)
Comment (rakekniven) [reply apps/files/src/views/Settings.vue:11]: Isn't this the same string which is shown bottom left next to the gear icon?

If so, please refer to my previous comment.

File: apps/files/src/filters/TypeFilter.ts (hunk 2 above)
Comment (rakekniven) [reply apps/files/src/filters/TypeFilter.ts:76]: Unfortunately, I have no memory of this discussion.

File: apps/files/src/utils/davUtils.ts (hunk 10 above)
Comment (rakekniven) [reply apps/files/src/utils/davUtils.ts]: Your changes are also part of a larger initiative (across apps) that is only being started here.
You can see this well on Transifex if you know almost all the strings.

I am not happy you close my conversations. Let's discuss first.

**Review by rakekniven — CHANGES_REQUESTED** [review]

File: apps/files/src/utils/davUtils.ts (hunk 10 above)
Comment (rakekniven) [reply apps/files/src/utils/davUtils.ts]: For technical messages (such as those from the DAV area), "directory" is often used.
Users talk about "folder".
Wouldn't it be better to process this topic as a separate issue globally in the server repo?

File: apps/files/src/views/Settings.vue (hunk 11 above)
Comment (kra-mo) [reply apps/files/src/views/Settings.vue:11]: No, not the actual title, it is this:

Image

Which as you can see was previously duplicated between the title and the first section.

Comment (rakekniven) [reply apps/files/src/views/Settings.vue:11]: This wasn't my question. 

> Isn't this the same string which is shown bottom left next to the gear icon?

As you can see it is.

Bildschirmfoto 2025-08-05 um 15 43 26


At Transifex we have ONE string:

Bildschirmfoto 2025-08-05 um 15 40 17

So changing it will break the common rule.

Comment (kra-mo) [reply apps/files/src/views/Settings.vue:11]: Yes, currently it should be the same string, but after the changes, it will be two separate ones.

File: apps/files/src/components/FilesListTableHeaderActions.vue [hunk 12]
```diff
@@ -305,16 +305,16 @@ export default defineComponent({
...
 					}
 
-					showError(this.t('files', '"{displayName}" failed on some elements', { displayName }))
+					showError(this.t('files', '{displayName}: failed on some elements', { displayName }))
 					return
 				}
 
 				// Show success message and clear selection
-				showSuccess(this.t('files', '"{displayName}" batch action executed successfully', { displayName }))
+				showSuccess(this.t('files', '{displayName}: done', { displayName }))
```
Comment (rakekniven) [inline apps/files/src/components/FilesListTableHeaderActions.vue:313]: What's the deal with the colon?
In my opinion, it doesn't read well.

**Review by rakekniven — CHANGES_REQUESTED** [review]

**Comment by rakekniven** [comment]
@kra-mo Please refrain from marking the conversation as resolved if I still have unanswered questions for you. Once the questions have been clarified, it is acceptable; otherwise, it is unprofessional.

I am always open to discuss and improve source strings and translations.

File: apps/files/src/filters/TypeFilter.ts (hunk 2 above)
Comment (susnux) [reply apps/files/src/filters/TypeFilter.ts:76]: Maybe it was translated to "Abbilder" in German? Something like that?

In that case the translator comment should be enough to have context for proper translations, no?

File: apps/files/src/components/FilesListTableHeaderActions.vue (hunk 12 above)
Comment (susnux) [reply apps/files/src/components/FilesListTableHeaderActions.vue:313]: Will result in something like "moving files: done"

File: apps/files/src/views/Settings.vue (hunk 11 above)
Comment (susnux) [reply apps/files/src/views/Settings.vue:11]: yes this change should be fine as it does not touch the button label

**Comment by kra-mo** [comment]
> Would be nice to split such changes, at least into commits but better into separate PRs. Because you not only change l10n strings as the commit and the PR suggests, but also remove user notifications from the actions.
> 
> So e.g. on PR with only the string change + one PR with removing notifications.

Opened #54260 for the toasts

File: apps/files/src/utils/davUtils.ts (hunk 10 above)
Comment (susnux) [reply apps/files/src/utils/davUtils.ts]: > Fair enough but not part of this PR

But then it can be directly solved when touching the string, because otherwise translators will work on this new string just to discard all their work when this is fixed again. Better to only change strings once to not double the work for them.

File: apps/files/src/components/FilesListTableHeaderActions.vue (hunk 12 above)
Comment (rakekniven) [reply apps/files/src/components/FilesListTableHeaderActions.vue:313]: Understood. Why not using native sentences like "Moving the files is finished"?

Comment (susnux) [reply apps/files/src/components/FilesListTableHeaderActions.vue:313]: It is just a concatenation of the displayname, it could also be "Restore: done".
We do not have knowledge of the display name here.

But this should also only be shown if the action does not provide a message themself, so  I would say this is fine here and use proper messages in the individual actions.

File: apps/files/src/filters/TypeFilter.ts (hunk 2 above)
Comment (rakekniven) [reply apps/files/src/filters/TypeFilter.ts:76]: Germans are difficult: Fotos, Bilder, Abbildungen

Photos are taken with a camera. A PNG file is not a photo, but an image :-)

File: apps/files/src/components/FilesListTableHeaderActions.vue (hunk 12 above)
Comment (kra-mo) [reply apps/files/src/components/FilesListTableHeaderActions.vue:313]: > Understood. Why not using native sentences like "Moving the files is finished"?

Because the inserted strings can be arbitrary and might not follow this format. This would indeed be preferable in the long run, but I'm not sure if/how it's possible.

As for why a colon over quotes: quotes should only really be used for user-provided strings.

**Comment by kra-mo** [comment]
> @kra-mo Please refrain from marking the conversation as resolved if I still have unanswered questions for you. Once the questions have been clarified, it is acceptable; otherwise, it is unprofessional.

Sorry, I expected my answers to answer your questions.

File: apps/files/src/utils/davUtils.ts (hunk 10 above)
Comment (kra-mo) [reply apps/files/src/utils/davUtils.ts]: > Better to only change strings once to not double the work for them.

That is fair, yeah. I can change this one string as they are already inconsistent. But I do not want this PR to get out of hand and become an unrebasable mess :D

Comment (kra-mo) [reply apps/files/src/utils/davUtils.ts]: > For technical messages (such as those from the DAV area), "directory" is often used.

And yes, but "folder" is used in this exact same context and is the preferred term nowadays.

File: apps/files/src/views/Settings.vue (hunk 11 above)
Comment (rakekniven) [reply apps/files/src/views/Settings.vue:11]: For all translations and related source code changes, my focus is on standardization.

Now, with this commit for the Files app, the title is to be changed in the settings.
I understand the improvement for the Files app.

But what about all the other apps that are part of the server bundle?
This is not conducive to the UX.

Comment (kra-mo) [reply apps/files/src/views/Settings.vue:11]: I don't know of any other apps that have "{app name} settings" as a settings *section* and Contacts for example already has a "General" one (although they also have "settings" in the name).

Comment (kra-mo) [reply apps/files/src/views/Settings.vue:11]: Mail also has "General".

File: apps/files/src/filters/TypeFilter.ts (hunk 2 above)
Comment (jancborchardt) [reply apps/files/src/filters/TypeFilter.ts:76]: Right, so in English it should be "Images", and the German equivalent in this case should be "Bilder". :)

File: apps/files/src/views/Settings.vue (hunk 11 above)
Comment (rakekniven) [reply apps/files/src/views/Settings.vue:11]: Have you checked all apps of the server bundle?

Comment (kra-mo) [reply apps/files/src/views/Settings.vue:11]: Yes. Talk, Calendar, Contacts, Mail all don't have it. Neither does anything else I checked.

Comment (rakekniven) [reply apps/files/src/views/Settings.vue:11]: Mentioned apps are not part of the server bundle.
See https://github.com/nextcloud/server/blob/master/core/shipped.json

File: apps/files/src/filters/TypeFilter.ts (hunk 2 above)
Comment (rakekniven) [reply apps/files/src/filters/TypeFilter.ts:76]: On iOS the Photos App uses "Fotos" as german name.

File: apps/files/src/views/Settings.vue (hunk 11 above)
Comment (joshtrichards) [reply apps/files/src/views/Settings.vue:11]: So for *Files* we currently have [Button: *Files settings*] --> [Heading: *Files settings*] -> [1st Section: *Files settings*].

As a comparison to another shipped app...

For *Photos* we currently have [Button: *Photos settings*] --> [Heading: *Photos settings*] -> [1st Section: *View*].

With this PR for *Files* we'd have [Button: *Files settings*] --> [Heading: *Files settings*] -> [1st Section: *General*].

That works for me.

**Comment by joshtrichards** [comment]
Related: #53775 for:

https://github.com/nextcloud/server/blob/e027cd44e4ea1ef853bedde64627e46c336a0c9c/apps/files_sharing/src/views/SharingTab.vue#L273-L274

**Comment by kra-mo** [comment]
> Related: #53775 for:
> 
> https://github.com/nextcloud/server/blob/e027cd44e4ea1ef853bedde64627e46c336a0c9c/apps/files_sharing/src/views/SharingTab.vue#L273-L274

Yeah, fair. I updated those strings.

File: apps/files/src/filters/TypeFilter.ts (hunk 2 above)
Comment (kra-mo) [reply apps/files/src/filters/TypeFilter.ts:76]: Yes, but that is a brand name. The iOS Files app however uses "images" which Apple translates to "Bilder". I think `Images` with the comment should work.

**Review by rakekniven — APPROVED** [review]

**Review by susnux — APPROVED** [review]

**Comment by susnux** [comment]
Testes in `cypress/e2e/files/search.cy.ts` need to be adjusted

**Comment by kra-mo** [comment]
> Testes in `cypress/e2e/files/search.cy.ts` need to be adjusted

Could you help me with that? I tried to look but couldn't find anything.

And the e2e one seemed to be failing for other PRs too, but maybe that was unrelated?

File: cypress/e2e/files/search.cy.ts
Comment (kra-mo) [inline cypress/e2e/files/search.cy.ts:1]: Ah, that one. Thanks.

Comment (rakekniven) [reply cypress/e2e/files/search.cy.ts:1]: Just a wild guess :-)

**Comment by susnux** [comment]
@kra-mo Cypress is related because this string changed:

https://github.com/nextcloud/server/blob/b4302fe57c35794204245f467047cf59e7a5b233/cypress/e2e/files/files-xml-regression.cy.ts#L43

**Comment by kra-mo** [comment]
> @kra-mo Cypress is related because this string changed:
> 
> https://github.com/nextcloud/server/blob/b4302fe57c35794204245f467047cf59e7a5b233/cypress/e2e/files/files-xml-regression.cy.ts#L43

Ah, thank you. Let me try and fix it.

**Comment by kra-mo** [comment]
Thanks everyone for the help 🥹
