### PR TITLE
Install nextcloud via migrations instead of the db_structure.xml

### LINKED ISSUE #4914: occ db:convert-type mysql -> UniqueConstraintViolationException
### Steps to reproduce
1. run: occ db:convert-type --all-apps --clear-schema mysql db username hostname database
2.
3.

### Expected behaviour
Migrate Nextcloud PostgreSQL database to MySQL without any issues.

### Actual behaviour
```
oc_filecache
chunked query, 15 chunks
  5700/14898 [==========>-----------------]  38%
                                                                                                                                                                                   
  [Doctrine\DBAL\Exception\UniqueConstraintViolationException]                                                                                                                     
  An exception occurred while executing 'INSERT INTO `oc_filecache` (`fileid`, `storage`, `path`, `path_hash`, `parent`, `name`, `mimetype`, `mimepart`, `size`, `mtime`, `storag  
  e_mtime`, `encrypted`, `unencrypted_size`, `etag`, `permissions`, `checksum`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [463919, 1, "files\/000_Folder\/Directory\/file.odt", "4a1f98565842fa63d3398b42198dd7bd", 463857, "file.odt", 7, 5, 73841, 147109182  
  3, 1471091823, 0, 0, "8756a2b3c9cebbb0aec8d1bd8d296030", 27, ""]:                                                                                                                
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '463919' for key 'PRIMARY'                                                                            
 
 [Doctrine\DBAL\Driver\PDOException]                                                               
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '463919' for key 'PRIMARY'  
               
  [PDOException]                                                                                    
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '463919' for key 'PRIMARY'                                                                                                 
```

### Server configuration

**Operating system**: Debian 7

**Web server:** nginx 1.8.1

**Database:** 9.1.24

**PHP version:** 5.6.30

**Nextcloud version:** 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** yes, updated

**Where did you install Nextcloud from:** from the shell

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - bookmarks: 0.10.0
  - calendar: 1.5.2
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_ldap: 1.1.2
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - richdocuments
  - user_external
  - user_saml
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ocrioxxj1qez",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.domain.com"
        ],
        "datadirectory": "\/srv\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/cloud.domain.com",
        "dbtype": "pgsql",
        "version": "11.0.2.7",
        "dbname": "nc",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "mail_from_address": "cloud",
        "mail_smtpmode": "php",
        "mail_domain": "domain.comt",
        "ldapIgnoreNamingRules": false,
        "maintenance": false,
        "theme": "mytheme",
        "loglevel": 2,
        "logtimezone": "Europe\/Berlin",
        "trashbin_retention_obligation": "auto,30",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.release.channel": "stable",
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "appstore.experimental.enabled": true,
        "activity_expire_days": 180
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
+-------------------------------+---------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                               |
+-------------------------------+---------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                                                                 |
| hasPagedResultSupport         |                                                                                                   |
| homeFolderNamingRule          |                                                                                                   |
| lastJpegPhotoLookup           | 0                                                                                                 |
| ldapAgentName                 | cn=proxyagent,ou=ldapusers,dc=domain,dc=com                                                      |
| ldapAgentPassword             | ***                                                                                               |
| ldapAttributesForGroupSearch  |                                                                                                   |
| ldapAttributesForUserSearch   |                                                                                                   |
| ldapBackupHost                | ldap2.domain.com                                                                           |
| ldapBackupPort                | 389                                                                                               |
| ldapBase                      | ou=people,dc=domain,dc=com                                                                       |
| ldapBaseGroups                | ou=people,dc=domain,dc=com                                                                       |
| ldapBaseUsers                 | ou=people,dc=domain,dc=com                                                                      |
| ldapCacheTTL                  | 600                                                                                               |
| ldapConfigurationActive       | 1                                                                                                 |
| ldapDynamicGroupMemberURL     |                                                                                                   |
| ldapEmailAttribute            | mail                                                                                              |
| ldapExperiencedAdmin          | 0                                                                                                 |
| ldapExpertUUIDGroupAttr       |                                                                                                   |
| ldapExpertUUIDUserAttr        |                                                                                                   |
| ldapExpertUsernameAttr        | uid                                                                                               |
| ldapGroupDisplayName          | cn                                                                                                |
| ldapGroupFilter               |                                                                                                   |
| ldapGroupFilterGroups         |                                                                                                   |
| ldapGroupFilterMode           | 1                                                                                                 |
| ldapGroupFilterObjectclass    |                                                                                                   |
| ldapGroupMemberAssocAttr      | uniqueMember                                                                                      |
| ldapHost                      | ldap1.domain.com                                                                           |
| ldapIgnoreNamingRules         |                                                                                                   |
| ldapLoginFilter               | (&(|(objectclass=inetOrgPerson))(uid=%uid)(memberOf=cn=cloud,ou=groups,dc=domain,dc=com)) |
| ldapLoginFilterAttributes     |                                                                                                   |
| ldapLoginFilterEmail          | 0                                                                                                 |
| ldapLoginFilterMode           | 1                                                                                                 |
| ldapLoginFilterUsername       | 1                                                                                                 |
| ldapNestedGroups              | 0                                                                                                 |
| ldapOverrideMainServer        | 0                                                                                                 |
| ldapPagingSize                | 500                                                                                               |
| ldapPort                      | 389                                                                                               |
| ldapQuotaAttribute            |                                                                                                   |
| ldapQuotaDefault              |                                                                                                   |
| ldapTLS                       | 1                                                                                                 |
| ldapUserDisplayName           | cn                                                                                                |
| ldapUserDisplayName2          |                                                                                                   |
| ldapUserFilter                | (|(objectclass=inetOrgPerson))                                                                    |
| ldapUserFilterGroups          |                                                                                                   |
| ldapUserFilterMode            | 0                                                                                                 |
| ldapUserFilterObjectclass     | inetOrgPerson                                                                                     |
| ldapUuidGroupAttribute        | auto                                                                                              |
| ldapUuidUserAttribute         | auto                                                                                              |
| turnOffCertCheck              | 0                                                                                                 |
| turnOnPasswordChange          | 0                                                                                                 |
| useMemberOfToDetectMembership | 1                                                                                                 |
+-------------------------------+---------------------------------------------------------------------------------------------------+
```
</details>

### Client configuration
**Browser:** Firefox 45.0.9

**Operating system:** Debian 8

#### Web server error log
<details>
<summary>Web server error log</summary>

```
nothing relevant
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
nothing relevant
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
n/a
```
</details>

### LINKED ISSUE #5646: db:convert-type can not convert apps that use migrations
The logic is missing from the `createSchema()` method.

### PR DESCRIPTION
**Pull request by nickvergessen**
Installing Nextcloud now uses migrations only instead of the old db_structure.xml
The old file was not taken into consideration on updates anymore anyway, which caused a problem for @fancycode and @Ivansss with sqlite, after the accounts table was dropped it was not recreated on update.

This is now fixed, because all the structure is in a migration file.

Fix #5646 
Fix #4914

### CODE REVIEW

File: core/Command/Db/Migrations/GenerateCommand.php [hunk 1]
```diff
@@ -66,7 +66,7 @@ public function preSchemaChange(IOutput $output, \Closure $schemaClosure, array
 	 * @since 13.0.0
 	 */
 	public function changeSchema(IOutput $output, \Closure $schemaClosure, array $options) {
-		return null;
+<schemabody>
```
Comment (MorrisJobke) [inline core/Command/Db/Migrations/GenerateCommand.php]: This looks weird 🤔

**Review by MorrisJobke — DISMISSED** [review]
Tested and works (and code looks good as well

**Comment by nickvergessen** [comment]
@MorrisJobke I can replace all placeholders with `{{...}}` if you think that is better. I used the `<..>` because that is what OC used.

File: build/files-checker.php [hunk 2]
```diff
@@ -58,7 +58,6 @@
 	'COPYING-README',
 	'core',
 	'cron.php',
-	'db_structure.xml',
```
Comment (nickvergessen) [inline build/files-checker.php]: @LukasReschke mentioning you as requested for potential build script adjustments

**Comment by nickvergessen** [comment]
db_structure.xml is still used by db convert and fix charset commands, will fix.

File: build/files-checker.php (hunk 2 above)
Comment (MorrisJobke) [inline build/files-checker.php]: I guess for this case no adjustment is needed, because it was a shipped file. We only should test the updater to check if the file list needs to be updated somehow.

**Comment by MorrisJobke** [comment]
BTW this is another step towards #2270

**Comment by nickvergessen** [comment]
Migrations? yes. This here? no.

**Comment by nickvergessen** [comment]
Should be ready for merge now

**Review by rullzer — APPROVED** [review]
AWESOME!

More tests would be nice. But lets get this in ASAP so we can catch error during development. But works like a charm here...

**Review by LukasReschke — APPROVED** [review]
