### PR TITLE
fix(initializeSession): only log HMAC problem to critical logs if indeed critical

### LINKED ISSUE #42157: [Bug]: HMAC does not match. Could not decrypt or decode encrypted session data
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Getting following error on NC 28 RC4. Might be the same as https://github.com/nextcloud/server/issues/41254#issuecomment-1849257556

### Steps to reproduce

Not Sure

### Expected behavior

Not Sure

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

```shell
{"reqId":"FuMPRjC8eJRqt0MgX7ET","level":3,"time":"2023-12-10T16:02:10-06:00","remoteAddr":"172.58.164.60","user":"--","app":"no app in context","method":"REPORT","url":"/remote.php/dav/files/axheli","message":"Could not decrypt or decode encrypted session data","userAgent":"Mozilla/5.0 (iOS) Nextcloud-iOS/4.9.3","version":"28.0.0.10","exception":{"Exception":"Exception","Message":"HMAC does not match.","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Security/Crypto.php","line":119,"function":"decryptWithoutSecret","class":"OC\\Security\\Crypto","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Session/CryptoSessionData.php","line":90,"function":"decrypt","class":"OC\\Security\\Crypto","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Session/CryptoSessionData.php","line":67,"function":"initializeSession","class":"OC\\Session\\CryptoSessionData","type":"->"},{"file":"/var/www/nextcloud/lib/private/Session/CryptoWrapper.php","line":112,"function":"__construct","class":"OC\\Session\\CryptoSessionData","type":"->"},{"file":"/var/www/nextcloud/lib/base.php","line":449,"function":"wrapSession","class":"OC\\Session\\CryptoWrapper","type":"->"},{"file":"/var/www/nextcloud/lib/base.php","line":705,"function":"initSession","class":"OC","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1200,"function":"init","class":"OC","type":"::"},{"file":"/var/www/nextcloud/remote.php","line":119,"args":["/var/www/nextcloud/lib/base.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Security/Crypto.php","Line":158,"message":"Could not decrypt or decode encrypted session data","exception":[],"CustomMessage":"Could not decrypt or decode encrypted session data"},"id":"6577154851e3b"}
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by szaimen**
- Close https://github.com/nextcloud/server/issues/42157

### CODE REVIEW

**Review by miaulalala — APPROVED** [review]
makes sense to me

File: lib/private/Security/Crypto.php [hunk 1]
```diff
@@ -96,7 +96,7 @@ public function decrypt(string $authenticatedCiphertext, string $password = ''):
 				return $this->decryptWithoutSecret($authenticatedCiphertext, $secret);
 			}
 			return $this->decryptWithoutSecret($authenticatedCiphertext, $password);
-		} catch (Exception $e) {
+		} catch (\RuntimeException|Exception $e) {
```
Comment (come-nc) [inline lib/private/Security/Crypto.php]:
```suggestion
		} catch (Exception $e) {
```
RuntimeException extends Exception already.

**Review by come-nc — CHANGES_REQUESTED** [review]

File: lib/private/Security/Crypto.php (hunk 1 above)
Comment (szaimen) [reply lib/private/Security/Crypto.php]: I didnt know this. Thanks for the hint!

Comment (szaimen) [reply lib/private/Security/Crypto.php]: fixed

**Review by come-nc — APPROVED** [review]
