### PR TITLE
Invert header if primary is bright and background disabled

### LINKED ISSUE #35664: Use primary colour for luminance calculations if background is disabled
> Well, how can we know if the background you selected has a bright top header? We're gonna improve for 26, but until then, it's not a bug, just not implemented.

@skjnldsv At least you could know if one has selected like `#ffffff` in the color picker. Not talking about background image. In fact any picked color tending towards white makes the GUI unusable right now. Call it a bug or broken by design. It is an issue. As long as you cannot set it dynamically, a small toggle switch (switch between light and dark header icons) could also do the trick. Quick and easy.

_Originally posted by @HannesJo0139 in https://github.com/nextcloud/server/issues/34965#issuecomment-1340976569_

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #35664

* [x] Cypress testing for both admin and user use-cases

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

File: apps/theming/lib/Themes/CommonThemeTrait.php [hunk 1]
```diff
@@ -95,8 +95,10 @@ protected function generateGlobalBackgroundVariables(): array {
 		// If primary as background has been request or if we have a custom primary colour
 		// let's not define the background image
 		if ($backgroundDeleted) {
-			$variables['--color-background-plain'] = $this->themingDefaults->getColorPrimary();
+			$variables['--color-background-plain'] = $this->defaultPrimaryColor;
```
Comment (skjnldsv) [inline apps/theming/lib/Themes/CommonThemeTrait.php:98]: This change is intentional.
We're in the admin section, we should use `defaultPrimaryColor` instead of `primaryColor`
If logged in, this var will be overruled below in the user section

**Review by artonge — CHANGES_REQUESTED** [review]

File: apps/theming/lib/Themes/CommonThemeTrait.php (hunk 1 above)
Comment (artonge) [reply apps/theming/lib/Themes/CommonThemeTrait.php:98]: Could you explain their differences ?

Comment (skjnldsv) [reply apps/theming/lib/Themes/CommonThemeTrait.php:98]: defaultPrimaryColor = admin defined, instance-wide
primaryColor = user, active for current session

**Review by artonge — APPROVED** [review]

**Review by Pytal — APPROVED** [review]

**Comment by skjnldsv** [comment]
Failure unrelated




```
And I see that the contact "user0" in the Contacts menu is not shown                                                      # ContactsMenuContext::iSeeThatTheContactInTheContactsMenuIsNotShown()
158 | Failed asserting that true is false.
```
<br class="Apple-interchange-newline">

File: cypress/e2e/theming/admin-settings.cy.ts [hunk 2]
```diff
@@ -132,14 +132,57 @@ describe('Remove the default background and restore it', function() {
 	})
 })
 
+describe.only('Remove the default background with a bright color', function() {
```
Comment (skjnldsv) [inline cypress/e2e/theming/admin-settings.cy.ts:135]:
```suggestion
describe('Remove the default background with a bright color', function() {
```

:roll_eyes:

Comment (artonge) [reply cypress/e2e/theming/admin-settings.cy.ts:135]: And now, everybody knows

Comment (skjnldsv) [reply cypress/e2e/theming/admin-settings.cy.ts:135]: I'll take the walk of shame :see_no_evil:

Comment (skjnldsv) [reply cypress/e2e/theming/admin-settings.cy.ts:135]: https://github.com/nextcloud/server/pull/39203
