### PR TITLE
show error message when "files-drop" upload fails

### LINKED ISSUE #3726: Error on files drop has no visible feedback
### Steps to reproduce
1. Add Access Control rule that prevents uploads (just block by time and select the full range)
2. Share a file as "files drop"
3. Upload a file into the files drop

### Expected behaviour
There should be something like ❌  as a feedback on the file list

### Actual behaviour
Loading spinner continues forever

@nextcloud/javascript

### PR DESCRIPTION
**Pull request by individual-it**
when upload fails for any reason the user gets a notification and the icon is set to an exclamation mark

if the user should not receive any information about why the upload failed this should fix  #3726 and partly #4389

### CODE REVIEW

**Review by LukasReschke — APPROVED** [review]

File: apps/files_sharing/js/files_drop.js [hunk 1]
```diff
@@ -72,34 +72,43 @@
...
+			$('[data-toggle="tooltip"]').tooltip();
+		},
+		
 		initialize: function () {
 			$(document).bind('drop dragover', function (e) {
 				// Prevent the default browser drop action:
 				e.preventDefault();
 			});
 			var output = this.template();
+			var fileName = undefined;
```
Comment (blizzz) [inline apps/files_sharing/js/files_drop.js]: not necessary to assign ``undefined``

**Review by blizzz — APPROVED** [review]
