### PR TITLE
Wait for cron to finish before running upgrade command

### LINKED ISSUE #9562: Check before running "upgrade" if cronjob is still running and wait for it to finish
Basically #5172 doesn't work because it does not reload the content of the config.php. So it's maybe better to check if the cronjob currently runs and wait for it to finish. It should be possible to cancel this waiting and it also should not have any impact at all.

As discussed with @rullzer 

cc @ChristophWurst @skjnldsv @nickvergessen

### PR DESCRIPTION
**Pull request by MorrisJobke**
* fixes #9562

To test this, add this:

```patch
diff --git a/lib/private/Authentication/Token/DefaultTokenProvider.php b/lib/private/Authentication/Token/DefaultTokenProvider.php
index 7a43dbb23e..fb2b33f564 100644
--- a/lib/private/Authentication/Token/DefaultTokenProvider.php
+++ b/lib/private/Authentication/Token/DefaultTokenProvider.php
@@ -281,9 +281,11 @@ class DefaultTokenProvider implements IProvider {
 	public function invalidateOldTokens() {
 		$olderThan = $this->time->getTime() - (int) $this->config->getSystemValue('session_lifetime', 60 * 60 * 24);
 		$this->logger->debug('Invalidating session tokens older than ' . date('c', $olderThan), ['app' => 'cron']);
+		sleep(15);
 		$this->mapper->invalidateOld($olderThan, IToken::DO_NOT_REMEMBER);
 		$rememberThreshold = $this->time->getTime() - (int) $this->config->getSystemValue('remember_login_cookie_lifetime', 60 * 60 * 24 * 15);
 		$this->logger->debug('Invalidating remembered session tokens older than ' . date('c', $rememberThreshold), ['app' => 'cron']);
+		sleep(15);
 		$this->mapper->invalidateOld($rememberThreshold, IToken::REMEMBER);
 	}
```

Then start a cron job `cron.php`, raise the version number in `version.php` or lower it in `config/config.php` and then trigger the upgrade by calling `occ upgrade`.

It then looks like this:

```
$ occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Waiting for cron to finish (checks again in 5 seconds)...
Waiting for cron to finish (checks again in 5 seconds)...
Waiting for cron to finish (checks again in 5 seconds)...
Waiting for cron to finish (checks again in 5 seconds)...
Updating database schema
Updated database
Checking for update of app activity in appstore
Checked for update of app "activity" in appstore 
Checking for update of app bruteforcesettings in appstore
Checked for update of app "bruteforcesettings" in appstore 
Checking for update of app comments in appstore
Checked for update of app "comments" in appstore 
...
```

When no cron job runs, then it looks like this:

```
$ occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Checking for update of app activity in appstore
Checked for update of app "activity" in appstore 
Checking for update of app bruteforcesettings in appstore
Checked for update of app "bruteforcesettings" in appstore 
Checking for update of app comments in appstore
Checked for update of app "comments" in appstore 
...
```

### CODE REVIEW

**Comment by MorrisJobke** [comment]
The web UI looks like this:

bildschirmfoto 2018-06-18 um 17 28 22

**Comment by MorrisJobke** [comment]
I'm tempted to backport this, because we think that this could fix the issue #4978

**Review by skjnldsv — APPROVED** [review]
Makes a lot of sense!

File: lib/private/BackgroundJob/JobList.php [hunk 1]
```diff
@@ -333,4 +333,25 @@ public function setExecutionTime(IJob $job, $timeTaken) {
...
+	/**
+	 * checks if a job is still running (reserved_at time is smaller than 12 hours ago)
+	 *
+	 * @return bool
+	 */
+	public function isAnyJobRunning(): bool {
+		$query = $this->connection->getQueryBuilder();
+		$query->select('*')
+			->from('jobs')
+			->where($query->expr()->gt('reserved_at', $query->createNamedParameter($this->timeFactory->getTime() - 12 * 3600, IQueryBuilder::PARAM_INT)))
```
Comment (blizzz) [inline lib/private/BackgroundJob/JobList.php]: Let's document why this is supposed to be working. The code is clear, but the thought behinds should be expressed.

Strictly speaking, it does only report whether a job should run (it might be running, or it might be due with the next job run). Correct me if I am wrong. It could perhaps lead to an infinite loop when a job reincarnates and registers  to run next time again. Though, cron should not be triggered when maintenance mode is enabled, which in the whole scenario is the case, so it would block for 12 hours instead. 

Are the 12 hours based on something?

Comment (blizzz) [reply lib/private/BackgroundJob/JobList.php]: From a UX perspective it still is problematic if it will take that long, as it'll look that nothing is happening. Of course stating "it might take up to 12 hours" in the GUI would scare people away. OK, let's get it in and collect some experience.

**Review by blizzz — APPROVED** [review]

**Comment by MorrisJobke** [comment]
This will only trigger for 14.0.0.7+, because it would cause #9992 otherwise. See #10010

**Comment by MorrisJobke** [comment]
Let's not backport this.

**Comment by MorrisJobke** [comment]
Reverted in #12188
