### PR TITLE
Bugfix: user is not allowed

### LINKED ISSUE #11311: Installing on PostgreSQL fails if the database exists and the installer creates a new user
When installing Nextcloud on PostgreSQL [if the given database user has create role permissions](https://github.com/nextcloud/server/blob/a661f043e1a8764cb7c795f50df77b830d3e352b/lib/private/Setup/PostgreSQL.php#L49-L71) a new database user is created by prepending `oc_` [to the admin user name](https://github.com/nextcloud/server/blob/253f962241ba7c96610f22e6940c31184650041d/lib/private/Setup.php#L290); this new user [will be the one used by Nextcloud](https://github.com/nextcloud/server/blob/a661f043e1a8764cb7c795f50df77b830d3e352b/lib/private/Setup/PostgreSQL.php#L66). If the given database user does not have create role permissions then [that given user is the one used instead](https://github.com/nextcloud/server/blob/0eebff152a177dd59ed8773df26f1679f8a88e90/lib/private/Setup/AbstractDatabase.php#L84).

After that a database with the given database name is created and the user, either the new one or the given one, depending on the case, [is made its owner](https://github.com/nextcloud/server/blob/a661f043e1a8764cb7c795f50df77b830d3e352b/lib/private/Setup/PostgreSQL.php#L112). However, if a database with the given database name already exists, [all the privileges for the public role are revoked from the database](https://github.com/nextcloud/server/blob/a661f043e1a8764cb7c795f50df77b830d3e352b/lib/private/Setup/PostgreSQL.php#L120) instead.

The problem is that when the given database user has create role permissions and the given database name exists the new user has no permissions on the existing database, so it can not connect to it and then the installation fails with `Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: SQLSTATE[08006] [7] FATAL:  permission denied for database "nextcloud" DETAIL:  User does not have CONNECT privilege.`

This failure is related to the recent failures in the integration tests run by Drone on PostgreSQL; for more information about that please see nextcloud/spreed#1205.

**How to reproduce:**
- Start a Docker container for the PostgreSQL server
  - In a terminal, leave PostgreSQL running with `docker run --rm --name postgres-installation-failure-db postgres:10`
    - If no user is explicitly given then the Docker container will use `postgres` by default (no matter if the image is actually `postgres:10.5` or earlier)
- Create a database for Nextcloud in the PostgreSQL server
  - In another terminal, execute `docker exec --interactive --tty --user postgres postgres-installation-failure-db psql -c "CREATE DATABASE nextcloud;"`
- Create a Docker container for the Nextcloud server (it is assumed that you have a Nextcloud Git directory somewhere)
  - In the previous terminal, execute `docker run --rm --volume /PATH/TO/THE/NEXTCLOUD/GIT/DIRECTORY/:/var/www/html --volume /var/www/html/data --volume /var/www/html/config --interactive --tty --network container:postgres-installation-failure-db --name postgres-installation-failure nextcloudci/php7.1:php7.1-16 bash`
- Install Nextcloud on PostgreSQL (all the following commands are performed in the Bash session inside the container)
  - Change to the Nextcloud directory with `cd /var/www/html`
  - Perform the installation with `php occ maintenance:install --admin-pass=admin --database=pgsql --database-name=nextcloud --database-host=localhost --database-user=postgres --database-pass=it-does-not-matter`

**Possible fixes:**
I do not really know which one would be better, as my database knowledge is pretty limited and rusty :-P

- After revoking the privileges, if a new user was created, make the new user the owner of the existing database with something like
```
$query = $connection->prepare("ALTER DATABASE " . addslashes($this->dbName) . " OWNER TO " . addslashes($this->dbUser));
try {
	$query->execute();
} catch (DatabaseException $e) {
	$this->logger->error('Error while trying to set database owner');
	$this->logger->logException($e);
}
```
- After revoking the privileges, if a new user was created, grant all privileges on the existing database to the new user with something like
```
$query = $connection->prepare("GRANT ALL PRIVILEGES ON DATABASE " . addslashes($this->dbName) . " TO " . addslashes($this->dbUser));
try {
	$query->execute();
} catch (DatabaseException $e) {
	$this->logger->error('Error while trying to grant database permissions');
	$this->logger->logException($e);
}
```
- Other approaches I have not tried :-)

### PR DESCRIPTION
**Pull request by vitormattos**
The created user using PostgreSQL database don't has permission to connect to database.

I changed the code to give permission

resolve #11311

### CODE REVIEW

**Comment by vitormattos** [comment]
I believe that continuous integration is in trouble. The status is that it is still running.

Another point is that the tests that broke in my PR are not influenced by my PR.

File: lib/private/Setup/PostgreSQL.php [hunk 1]
```diff
@@ -154,6 +154,10 @@ private function createDBUser(IDBConnection $connection) {
 			// create the user
 			$query = $connection->prepare("CREATE USER " . addslashes($this->dbUser) . " CREATEDB PASSWORD '" . addslashes($this->dbPassword) . "'");
 			$query->execute();
+			if ($this->databaseExists($connection)) {
+				$query = $connection->prepare('GRANT CONNECT ON DATABASE ' . $this->dbName . ' TO '.addslashes($this->dbUser));
```
Comment (shyim) [inline lib/private/Setup/PostgreSQL.php]: You forgot addslashes on $this->dbName

Comment (vitormattos) [reply lib/private/Setup/PostgreSQL.php]: @shyim done!

**Comment by vitormattos** [comment]
@shyim done!

**Review by nickvergessen — APPROVED** [review]
Fine by me, but can't test

**Comment by vitormattos** [comment]
Hello @nickvergessen!
The tests in the master are breaking, not because of the change I made.

**Comment by rullzer** [comment]
@icewind1991 mind to have a look and check?

**Comment by vitormattos** [comment]
Hello everybody!
This is my first PR to NC.
I want to send more but I need feedback on this PR. Do I need to do any other fixes?
@icewind1991 @rullzer @nickvergessen @shyim

**Comment by J0WI** [comment]
Can we plan this for the next release? https://github.com/nextcloud/docker/issues/345 is a frequently discussed issue.

**Comment by kesselb** [comment]
@J0WI I don't like these create database / database user code. Would it be a problem for the docker images if we remove those? Nextcloud should use the database / database user provided.

**Review by kesselb — COMMENTED** [review]
Make sense :+1: 

I think you could move the logic into another method. There is already a `createDatabase`  method. If the database already exist we drop all the permission there. You may add the `grant` statment to this method.

**Comment by charlag** [comment]
In case it helps: I tried this little patch on my system and it finally worked.
Environment described here:
https://github.com/docker-library/postgres/issues/584#issuecomment-499983501

**Comment by charlag** [comment]
I would also say that using credentials other than provided is *super* confusing and I was blaming the `postgres` container for that.
Thanks for the patch.

**Comment by J0WI** [comment]
> Would it be a problem for the docker images if we remove those? Nextcloud should use the database / database user provided.

That's fine for Docker. It can already be created in the database container.

**Comment by Brightside56** [comment]
Oh... I see, power of opensource :+1:

**Comment by vitormattos** [comment]
@rullzer have any pending for me to do in this PR?

**Comment by nickvergessen** [comment]
So nothing to do here anymore?

**Comment by vitormattos** [comment]
Hi @nickvergessen, I think this PR is in the queue to be mergeado by @rullzer  next to PR # 16064. I believe the merge is necessary because it solves some issues.

**Comment by lukasmrtvy** [comment]
Merge?
Its really annoying , because its not possible to upgrade nextcloud ( change docker image version ) !

```
Error while trying to create admin user: Failed to connect to the database: An exception occurred in driver: SQLSTATE[08006] [7] FATAL:  permission denied for database "nextcloud"
DETAIL:  User does not have CONNECT privilege.
```
Should be fixed/merged asap.

**Review by rullzer — APPROVED** [review]
Fine by me

File: lib/private/Setup/PostgreSQL.php [hunk 2]
```diff
@@ -154,6 +154,10 @@ private function createDBUser(IDBConnection $connection) {
 			// create the user
 			$query = $connection->prepare("CREATE USER " . addslashes($this->dbUser) . " CREATEDB PASSWORD '" . addslashes($this->dbPassword) . "'");
 			$query->execute();
+			if ($this->databaseExists($connection)) {
+				$query = $connection->prepare('GRANT CONNECT ON DATABASE ' . addslashes($this->dbName) . ' TO '.addslashes($this->dbUser));
```
Comment (tianon) [inline lib/private/Setup/PostgreSQL.php]: Given that this is using `->prepare`, shouldn't this be using `?` and arguments instead of `addslashes`?
(https://www.php.net/addslashes -- "The addslashes() is sometimes incorrectly used to try to prevent SQL Injection. Instead, database-specific escaping functions and/or prepared statements should be used.")

I think this is one of the roots of what's being discussed over in https://github.com/docker-library/official-images/pull/6252#issuecomment-520093256 (in PostgreSQL, `-` needs to be escaped, but `addslashes` won't do so, for example).

**Comment by skjnldsv** [comment]
Please backport manually

**Comment by nickvergessen** [comment]
Not needed anymore as it is in 17+ and 16 goes EOL soon
