### PR TITLE
[stable29] fix(files): handling numbered type owner name & id

### LINKED ISSUE #45723: [Bug]: Numerical accounts show all files/folders in "Shared" status in the web UI
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Use accounts with all numerical symbols (e.g. 11223344), after logging in, all files and folders will be displayed as shared, and the first symbol of the account will be in English letters, which is normal.
aaaaaaaa

### Steps to reproduce

1. Login to the backend
2. Add users
3. Set the user account to 112233
4. Other arbitrary
5. Login using 112233
6. View the file list, which shows that all files are shared

### Expected behavior

"Shared" should not appear

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by sanskar-soni-9**
* Resolves: #45723 

## Summary
Handles numbered 'owner-id' and 'owner-display-name'

### Before
240610_19h37m29s_screenshot

### After
240610_19h33m51s_screenshot

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by susnux — APPROVED** [review]
Fixed on master but on stable29 and stable28 we need this.
Thank you.

**Review by Pytal — APPROVED** [review]

File: apps/files/src/services/Files.ts [hunk 1]
```diff
@@ -66,7 +66,9 @@ export const resultToNode = function(node: FileStat): File | Folder {
 		attributes: {
 			...node,
 			...props,
-			hasPreview: props?.['has-preview'],
+			'owner-id': owner,
+			'owner-display-name': String(props['owner-display-name']),
```
Comment (skjnldsv) [inline apps/files/src/services/Files.ts:70]: That should not be needed :thinking:

Comment (skjnldsv) [reply apps/files/src/services/Files.ts:70]: I see we made some mistake and used it in a few locations, I would suggest we fix the usage instead of providing `owner-id`  as extra attributes :thinking: 

`owner-display-name` on the other hand s fine I think

Comment (skjnldsv) [reply apps/files/src/services/Files.ts:70]: Well, we fixed it for NC30 and above, I think we can merge for older branches as a safety measure.
I'll create a PR for master :rocket:

**Review by skjnldsv — APPROVED** [review]
