### PR TITLE
fix(singularandpluralfiles):implemented ternary operator to handle si…

### LINKED ISSUE #50986: [l10n]: Singular and plural for number of files
If the value of `{count}` is a number of files, then the text string should decline for singular and plural.

https://github.com/nextcloud/server/blob/b694c2eafeeac8f7bf586f454a74f532ccb8a196/apps/files/src/actions/convertUtils.ts#L80-L81

### PR DESCRIPTION
**Pull request by caitjordan17**
fix(singularandpluralfiles): implemented ternary operator to handle singular and plural cases. Signed-off-by: Caitlin J Hobbs <jordan.cait17@gmail.com>

* Resolves: #50986 <[l10n]: Singular and plural for number of files >

## Summary
Used ternary operator to handle singular and plural cases depending on the value of {count} in showError and showSuccess

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/files/src/actions/convertUtils.ts [hunk 1]
```diff
@@ -77,8 +77,8 @@ export const convertFiles = async function(fileIds: number[], targetMimeType: st
 
 			// We already check above when all files failed
 			// if we're here, we have a mix of failed and successful files
-			showError(t('files', '{count} files could not be converted', { count: failed.length }))
-			showSuccess(t('files', '{count} files successfully converted', { count: fileIds.length - failed.length }))
+			showError(t('files', failed.length === 1 ? '{count} file could not be converted' : '{count} files could not be converted', { count: failed.length }))
+			showSuccess(t('files', fileIds.length === 1 ? '{count} file successfully converted' : '{count} files successfully converted', { count: fileIds.length - failed.length }))
```
Comment (susnux) [inline apps/files/src/actions/convertUtils.ts:81]: This does not work as you cannot have conditions in translations - this will not be extracted correctly.
Also it should use the plural form `n`:

```suggestion
			showError(n('files', 'one file could not be converted', '%n files could not be converted', failed.length))
			showSuccess(n('files', 'one file successfully converted', '%n files successfully converted', fileIds.length - failed.length))
```

**Review by susnux — CHANGES_REQUESTED** [review]
Thank you for the pull request!
But this will not work as conditions do not work inside `t` and `n` (will break the string extraction).
Also for plural forms `n` should be used.

File: apps/files/src/actions/convertUtils.ts (hunk 1 above)
Comment (skjnldsv) [reply apps/files/src/actions/convertUtils.ts:81]: None of the above, `failed.length === 1` is already handled 10 lines above

**Comment by skjnldsv** [comment]
See comment on the issue :)

File: apps/files/src/actions/convertUtils.ts (hunk 1 above)
Comment (susnux) [reply apps/files/src/actions/convertUtils.ts:81]: yes but not the difference between how plural is handled in different languages.
Not every language has the same form for plural.

**Review by susnux — APPROVED** [review]

**Comment by susnux** [comment]
We need this as you can never assume anything about other languages and how they do plural.
Everything that refers to N elements must go through `n(...)` for proper translation.

**Comment by susnux** [comment]
@caitjordan17 thank you very much for your contribution :)

**Review by skjnldsv — APPROVED** [review]
Changes looks good :+1:
