### PR TITLE
Fix/unified search

### LINKED ISSUE #22092: Unified search: followups
## Providers
- [x] #22011 
- [x] #22020 (@georgehrke) 
- [x] #22095
- [x] Enabled apps #22102 

### Enhancements
- [ ] Check the additional filters feature, interface for the "in:files" etc #22111
- [x] Add global event #22526 
- [x] Users & apps filtering

### Issues
- [x] Sort results of currently active app first #22104 
- [x] The search icon should remain white even in dark mode
- [x] Click load more on paginated type show the loading emptycontent
- [x] Files are lib/composer/composernot showed with appropriate mime icons
- [x] When you set the theming color to `#FFFFFF` and `#181818` respectively the section headers are invisible on bright/dark theme.
- [x] A problem might be that the search is not persistent, as soon as the unified search input is closed, the filtering is reset https://github.com/nextcloud/server/pull/22526#issue-476511478

### Unrelated
- [x] Ctrl-F doesn’t work with `Text` enabled  (@juliushaertl) https://github.com/nextcloud/text/pull/988

## Documentation
- [ ] How to implement inner-app search (eventListener prevent default)
- [ ] Update php API requirements
- [ ] Simple example

## Order

- [-50] App search itself
- [-1] Current app
- [5] Files
- [10] Comments
- [15] Talk @nickvergessen 
- [20] Mail @ChristophWurst 
- [25] Contacts
- [30] Calendar
- [35] Tasks
- [500] Settings
- Install apps - Not implemented
- Documentation - Not implemented

## Future Improvements
- [x] SHow placeholder instead of loader
- [ ] Suggestions as emptycontent e.g. pre-filters
- [ ] See how unified search relates to the Contacts menu (depending on how we improve the Contacts menu)
- [ ] Alignment further to the right
- [ ] In the case of Files, for a file or folder which is in the current folder we don’t really need to refresh for the scrollto highlight – possible enhancement?
- [ ] Define criteria for relevant results and sort them first

cc @jancborchardt

### PR DESCRIPTION
**Pull request by skjnldsv**
Partly fixes #22092

### CODE REVIEW

File: lib/public/Search/IProvider.php [hunk 1]
```diff
@@ -64,6 +64,15 @@ public function getId(): string;
 	 */
 	public function getName(): string;
 
+	/**
+	 * Get the search provider order
```
Comment (nickvergessen) [inline lib/public/Search/IProvider.php:68]: Please add whether low or high means earlier.

File: lib/private/TemplateLayout.php [hunk 2]
```diff
@@ -74,7 +78,10 @@ public function __construct($renderAs, $appId = '') {
 		$this->config = \OC::$server->get(IConfig::class);
 
 		/** @var IInitialStateService */
-		$this->initialState = \OC::$server->get(InitialStateService::class);
+		$this->initialState = \OC::$server->get(IInitialStateService::class);
+
+		/** @var INavigationManager */
+		$this->navigationManager = \OC::$server->get(INavigationManager::class);
```
Comment (nickvergessen) [inline lib/private/TemplateLayout.php:84]: Please move this into the `$renderAs === TemplateResponse::RENDER_AS_USER` part
to avoid issues on error pages and others.

File: lib/private/Search/SearchComposer.php [hunk 3]
```diff
@@ -107,22 +107,31 @@ private function loadLazyProviders(): void {
...
-					'name' => $provider->getName()
+					'name' => $provider->getName(),
+					'order' => $provider->getOrder()
 				];
-			}, $this->providers));
+			}, $this->providers)
+		);
+
+		usort($providers, function ($provider1, $provider2) {
+			return $provider1['order'] <=> $provider2['order'];
```
Comment (nickvergessen) [inline lib/private/Search/SearchComposer.php:128]: best operator :)

Comment (skjnldsv) [reply lib/private/Search/SearchComposer.php:128]: Yep :D

File: lib/private/TemplateLayout.php (hunk 2 above)
Comment (skjnldsv) [reply lib/private/TemplateLayout.php:84]: Also, we should document the existing initial states

**Comment by nickvergessen** [comment]
> OCA\DAV\Tests\unit\ContactsSearchProviderTest::testSearch
Undefined index: iconClass

related

**Comment by skjnldsv** [comment]
> [@nickvergessen ](/nickvergessen)
> ` [Fix property name](/nextcloud/server/pull/22099/commits/87371ffe95fabbda42ec7a34be309ad6ee9659bd) ` …

Careful, I'm also working on this branch :)

File: core/src/views/UnifiedSearch.vue [hunk 4]
```diff
@@ -155,6 +162,32 @@ export default {
...
 
+		/**
+		 * Order results by putting the active app first
+		 * @returns {Object}
+		 */
+		orderedResults() {
+			const ordered = {}
+			Object.keys(this.results)
+				.sort((a, b) => {
+					if (a.startsWith(activeApp) && b.startsWith(activeApp)) {
```
Comment (nickvergessen) [inline core/src/views/UnifiedSearch.vue:173]:
```suggestion
					if (a.startsWith(activeApp) === b.startsWith(activeApp)) {
```

Comment (skjnldsv) [reply core/src/views/UnifiedSearch.vue:173]: Nice catch

Comment (nickvergessen) [reply core/src/views/UnifiedSearch.vue:173]: Currently you only sort by order when both apps start with the active app, instead of always.

**Comment by skjnldsv** [comment]
> There was 1 error:
> 
> 1) OCA\DAV\Tests\unit\ContactsSearchProviderTest::testSearch
> PHPUnit\Framework\InvalidArgumentException: Argument #1 of PHPUnit\Framework\Assert::assertInstanceOf() must be a class or interface name
> 
> /drone/src/apps/dav/tests/unit/Search/ContactsSearchProviderTest.php:219

@georgehrke help? :pray:

**Comment by georgehrke** [comment]
It seems @nickvergessen didn't fix the `assertInstanceOf` when making `SearchResultEntry` non abstract.

**Comment by skjnldsv** [comment]
Done, let's get this in so it doesn't turn into a crazy PR™

File: core/src/components/UnifiedSearch/SearchResultPlaceholder.vue [hunk 5]
```diff
@@ -0,0 +1,68 @@
+<template>
+	<svg
+		class="unified-search__result-placeholder"
+		xmlns="http://www.w3.org/2000/svg"
+		fill="url(#unified-search__result-placeholder-gradient)">
+		<defs>
+			<linearGradient id="unified-search__result-placeholder-gradient">
+				<stop offset="0%" stop-color="#ededed"><animate attributeName="stop-color"
+					values="#ededed; #ededed; #cccccc; #cccccc; #ededed"
```
Comment (nickvergessen) [inline core/src/components/UnifiedSearch/SearchResultPlaceholder.vue:9]: Dark mode sings:
https://www.youtube.com/watch?v=Rpq35wyDi7I

**Review by nickvergessen — APPROVED** [review]

File: core/src/components/UnifiedSearch/SearchResultPlaceholder.vue (hunk 5 above)
Comment (skjnldsv) [reply core/src/components/UnifiedSearch/SearchResultPlaceholder.vue:9]: I'll fix in a followup

**Review by jancborchardt — APPROVED** [review]
Tested and looks good!
