### PR TITLE
fix(session): Do not log fresh/empty session as error

### LINKED ISSUE #41254: [Bug]: 28.0.0-beta1 - "Could not decrypt or decode encrypted session data"
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

~~While clicking thru Polls the app freeses and I get an error message in the logs~~
**Edit:** The observation seems to be not connected to the error message

### Steps to reproduce

1. ~~Random clicking thru polls (or maybe another app)~~ Just wait until the cron.php is called

### Expected behavior

no error

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

master

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "projects.enabled": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "foo.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "tempdirectory": "\/tmp\/foo.com\/nextcloud",
        "dbtype": "mysql",
        "version": "28.0.0.3",
        "overwrite.cli.url": "https:\/\/foo.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_language": "de",
        "default_phone_region": "DE",
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "updater.release.channel": "beta",
        "htaccess.RewriteBase": "\/",
        "htaccess.IgnoreFrontController": true,
        "app_install_overwrite": [
            "deck",
            "spreed",
            "impersonate",
            "dashboard",
            "circles",
            "talk_simple_poll",
            "polls",
            "calendar",
            "contacts",
            "unsplash",
            "richdocumentscode",
            "spgverein",
            "collectives"
        ],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "tls",
        "mail_send_plaintext_only": false,
        "ldapIgnoreNamingRules": false
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - bruteforcesettings: 2.8.0
  - calendar: 4.6.0-beta.1
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contacts: 5.5.0-beta.3
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - deck: 1.11.0
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_reminders: 1.0.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - mail: 3.5.0-beta.1
  - nextcloud_announcements: 1.17.0
  - notes: 4.8.1
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - polls: 6.0.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.0
  - sharebymail: 1.18.0
  - spreed: 18.0.0-beta.1
  - support: 1.11.0
  - systemtags: 1.18.0
  - text: 3.9.0
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - admin_audit: 1.18.0
  - calendar_resource_management: 0.5.0 (installed 0.5.0)
  - collectives: 2.8.2 (installed 2.8.2)
  - encryption: 2.16.0 (installed 2.11.0)
  - files_external: 1.20.0 (installed 1.13.0)
  - files_pdfviewer: 2.9.0 (installed 2.8.0)
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - firstrunwizard: 2.17.0 (installed 2.10.0)
  - forms: 3.3.1 (installed 3.3.1)
  - guests: 2.5.0 (installed 2.5.0)
  - impersonate: 1.14.0 (installed 1.14.0)
  - integration_mattermost: 1.0.5 (installed 1.0.5)
  - integration_openai: 1.0.13 (installed 1.0.13)
  - login_notes: 1.3.1 (installed 1.3.1)
  - photos: 2.4.0 (installed 1.7.1)
  - privacy: 1.12.0 (installed 1.11.0)
  - survey_client: 1.16.0 (installed 1.6.0)
  - suspicious_login: 6.0.0-dev (installed 4.3.0)
  - tables: 0.6.0 (installed 0.6.0)
  - talk_simple_poll: 1.3.1 (installed 1.3.1)
  - tasks: 0.15.0 (installed 0.15.0)
  - twofactor_totp: 10.0.0-beta.2
  - unsplash: 2.2.1 (installed 2.2.1)
  - user_ldap: 1.19.0 (installed 1.13.0)
```

### Nextcloud Signing status

```shell
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! causes for failing:
!! ContentSecurityPolicy:
!! protected $evalScriptAllowed = true;
!! 
!! user.ini
!! memory_limit=512M
!!!!!!!!!!!!!!!!!!!!!!!!!!!


Results
=======
- core
	- INVALID_HASH
		- .user.ini
		- lib/public/AppFramework/Http/ContentSecurityPolicy.php

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.user.ini] => Array
                        (
                            [expected] => 4843b3217e91f8536cb9b52700efb20300290292cf6286f92794d4cec99df286afeb7dd6c91b1be20bc55eda541eef230a5c5e7dcd46c189edd0ed1e80c6d3f5
                            [current] => 3fecf59adb63f3529c30449b25264e1fd2a447b855afae05821110b50039a5e51f6c4f3349399512602b5544a65cdf6fa3c50b81f16fcbe2e0be175d9f6c4c82
                        )

                    [lib/public/AppFramework/Http/ContentSecurityPolicy.php] => Array
                        (
                            [expected] => 7680c1d38baf63b02c1db176bc86d67adc9f8e546ea6eee85aa42948e63d0aa3a51647026aa1561a01654ade9b9136b3ff1f6c890a26b0b23e2d26b3ef95d0a4
                            [current] => 2bba4ee2c452df66a21be3e4a3a04f60114281fca3c04e0ff0accb018c86f5e2de510a1271dc6c5058253436b815da6f985e952f6f9825f5eaea2645c23669b7
                        )

                )

        )

)
```

### Nextcloud Logs

```json
{
	"reqId": "ZUSNjd4h6SX8yH7-niD4bwAAGzY",
	"level": 3,
	"time": "2023-11-03T06:05:02+00:00",
	"remoteAddr": "85.13.165.115",
	"user": "--",
	"app": "core",
	"method": "GET",
	"url": "/cron.php",
	"message": "Could not decrypt or decode encrypted session data",
	"userAgent": "cronBROWSE v1.1",
	"version": "28.0.0.3",
	"exception": {
		"Exception": "Exception",
		"Message": "Authenticated ciphertext could not be decoded.",
		"Code": 0,
		"Trace": [
			{
				"file": "/www/htdocs/server/lib/private/Security/Crypto.php",
				"line": 119,
				"function": "decryptWithoutSecret",
				"class": "OC\\Security\\Crypto",
				"type": "->",
				"args": [
					"*** sensitive parameters replaced ***"
				]
			},
			{
				"file": "/www/htdocs/server/lib/private/Session/CryptoSessionData.php",
				"line": 85,
				"function": "decrypt",
				"class": "OC\\Security\\Crypto",
				"type": "->",
				"args": [
					"*** sensitive parameters replaced ***"
				]
			},
			{
				"file": "/www/htdocs/server/lib/private/Session/CryptoSessionData.php",
				"line": 66,
				"function": "initializeSession",
				"class": "OC\\Session\\CryptoSessionData",
				"type": "->",
				"args": []
			},
			{
				"file": "/www/htdocs/server/lib/private/Session/CryptoWrapper.php",
				"line": 112,
				"function": "__construct",
				"class": "OC\\Session\\CryptoSessionData",
				"type": "->",
				"args": [
					[
						"OC\\Session\\Memory"
					],
					[
						"OC\\Security\\Crypto"
					],
					"*** sensitive parameters replaced ***"
				]
			},
			{
				"file": "/www/htdocs/server/cron.php",
				"line": 62,
				"function": "wrapSession",
				"class": "OC\\Session\\CryptoWrapper",
				"type": "->",
				"args": [
					[
						"OC\\Session\\Memory"
					]
				]
			}
		],
		"File": "/www/htdocs/server/lib/private/Security/Crypto.php",
		"Line": 135,
		"message": "Could not decrypt or decode encrypted session data",
		"exception": [],
		"CustomMessage": "Could not decrypt or decode encrypted session data"
	},
	"id": "65448da9f12e5"
}
```

### Additional info

Fresh update to 28.0.0-beta1
Cron is called via Webcron

### PR DESCRIPTION
**Pull request by ChristophWurst**
* Resolves: https://github.com/nextcloud/server/issues/41254

This regression was introduced with https://github.com/nextcloud/server/pull/40879.

## Summary

An empty session can't be decrypted. We can safely ignore this condition and only log if a value is set and that value can't be decrypted.

## How to test

1. Open Nextcloud
2. Restart the webserver to flush session data
3. Reload the Nextcloud page

Master: error is logged because the session file is empty.
Here: no error is logged.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: lib/private/Session/CryptoSessionData.php [hunk 1]
```diff
@@ -80,19 +81,24 @@ public function __destruct() {
...
-				512,
-				JSON_THROW_ON_ERROR,
-			);
-		} catch (\Exception $e) {
-			logger('core')->critical('Could not decrypt or decode encrypted session data', [
-				'exception' => $e,
-			]);
+		if ($encryptedSessionData === '') {
+			// Nothing to decrypt
 			$this->sessionValues = [];
```
Comment (ChristophWurst) [inline lib/private/Session/CryptoSessionData.php:86]: What I'm not entirely sure about is whether we need to regenerate the session ID here. But it seems useless if the session we currently have is empty anyway. Regenerating will more likely cause race conditions.

**Review by nickvergessen — APPROVED** [review]

**Review by AndyScherzinger — APPROVED** [review]
