### PR TITLE
fix(files): Allow to set node name before creating + bring back new-file highlingting

### LINKED ISSUE #41260: Can not create folders with a unique name when not having update permissions
### Steps

1. As UserA create a folder FolderA
2. As UserA share FolderA with UserB with `read+create` permissions
3. As UserB try to create a FolderB inside FolderA
4. The folder `New folder` gets created and due to lack of update permissions you can not rename it:

grafik

### LINKED ISSUE #42097: [Bug]: Issues with newly created files (set name and open automatically)
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

In previous versions when creating a new file you could set a name and the new file was opened directly with the default file action.

With 28 it seems that this behaviour changed in multiple ways due to the files to vue migration:

- There is no way to edit the file name directly after selecting the template
- The file is not highlighted anymore
- The new file is not opening automatically anymore

### Steps to reproduce

1. Create a new text file through the new file menu

### Expected behavior

- The file name is editable
- The file entry is highlighted
- The file opens automatically after confirming the new name

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### LINKED ISSUE #43051: [Bug]: slow folder loading and actions in Files
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Using Files (new UI is really good 😍) I noticed I often had to wait quite some time when I was performing an action. I made a few measures :
- opening a "shared with me" folder with 1500+ subfolders take ~22-24s to load
- Inside, Files need between 4 to 10 seconds to display a newly created folder, after I click the create new folder button. This is also true if the newly created folder is in a sub sub folder.
- Files need from 3 to 5s to take into account the renaming action on the newly created folder.

In my personal directory (not shared, and with ~30 entries), all the steps above take ~1s.

### Steps to reproduce

1. create a folder containing 1500+ subfolders
2. open a subfolder, and test creating a folder
3. rename the newly created folder

### Expected behavior

1. When I open a folder, I don't expect to wait for 22s in front of my screen to see the content. Past 10s loading, I tend to reach to the unified search which takes me faster to the folder I am looking for (great new search BTW :).
2. when I create a new (sub)folder, I expect the newly created folder to appear within 2s
3. when I rename a folder, I expect the renaming to be taken into account within 1s

(I gave estimations of time I expect, but I in reality, I don't have a very good idea of what is acceptable. Sure thing is, the current time seem to me too long.)

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

c.nc.c

### LINKED ISSUE #43052: [Bug]: inconsistency in creating folders behavior
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The create a new folder action consequences depends on the number of subfolders and display.

#### Behavior 1
1. In an empty folder, create a new folder
2. The new folder appear in edit mode so you can rename it.
3. Rename it, and hit enter.
4. The new folder is visible.

#### behavior 2
1. Go into a folder with a list a subfolders that exceeds your screen display capacity.
2. Make sure you cannot see the folders starting by "N"
5. Click create a new folder
6. The new folder is instantly created, but is not visible.
7. You have to scroll to the "N" folders to find it.
8. When you found it, it is not in edit mode.
9. To rename it, you must click the three dots menu > rename

### Expected behavior

I don't expect the behaviors to differ. I am surprised in behavior 2 that I can't see my newly created folder. I am surprised I have to scroll up or down to find it.
Also, once renamed, I may have to scroll again to find it (if I renamed it starting with an A, I have to scroll up again to the A).

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

c.nc.c

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: #42097
* Resolves: #41260
* Resolves: #43052
* Resolves: #43051

## Summary
Most important: This brings back the ability to select a folder name before creating it - this is required for shares where you can create but not update.

This feature is reused for all new-menu entries, meaning also for new template folder and new files like new text files if **text** app is installed.

Moreover this fixes:
* The file name is not editable: see above
* The file entry is not highlighted: This was already possible or planned as the styles were available but the class was not assigned, this is now done.
* The file does not open automatically after confirming the new name: This was more tricky as files does not provide e.g. `files:node:open` but opening a file is left as a action provided by the viewer app. So this is now handled by searching for the *view* action and if not available then at least open the sidebar for more details.

### Workflow (screen cast)

https://github.com/nextcloud/server/assets/1855448/1fd31ea3-8bc4-4c3a-b933-2323e554c691

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/files/src/views/FilesList.vue [hunk 1]
```diff
@@ -437,10 +437,12 @@ export default defineComponent({
 	mounted() {
 		this.fetchContent()
 		subscribe('files:node:updated', this.onUpdatedNode)
+		subscribe('files:node:focus', this.onFocusNode)
```
Comment (skjnldsv) [inline apps/files/src/views/FilesList.vue:440]: Not acceptable imho, an event is not meant to trigger a reaction like a focus.

If you want to focus the node, you need to change the URL and provide a new fileId, the filelist will scroll it in the current view
https://github.com/nextcloud/server/blob/3f77b543e3ee55177f87ca845d31bb7d2776d467/apps/files/src/components/FilesListVirtual.vue#L234-L242
https://github.com/nextcloud/server/blob/b1a9017f5fbe15a6fe3ccb592ff000661ce2e3ad/apps/files/src/components/VirtualList.vue#L245-L251

I would say the `scrollTo` needs to be updated then so it also focuses :)

**Review by skjnldsv — DISMISSED** [review]
Very very clean!!! :rocket: 
Aside from the `files:node:focus`, looks good to me! Thank you so much :)

File: apps/files/src/views/FilesList.vue (hunk 1 above)
Comment (susnux) [reply apps/files/src/views/FilesList.vue:440]: > an event is not meant to trigger a reaction like a focus.

But we have an event for opening the sidebar?

Comment (susnux) [reply apps/files/src/views/FilesList.vue:440]: I mean I could drop all the event related parts, but then you might help me understanding why `openfile=true` only works if you reload the page (hard reload) with that in the query. While when only adding it through the router is does not work.

Comment (skjnldsv) [reply apps/files/src/views/FilesList.vue:440]: > But we have an event for opening the sidebar?

Because it was poorly done to have a simpler relationship with legacy code iirc

Comment (skjnldsv) [reply apps/files/src/views/FilesList.vue:440]: > you might help me understanding why `openfile=true` only works if you reload the page (hard reload) with that in the query.

Because it's only provided by the backend via initialstate.
If you want reactivity to it, you need to implement it on the front too, similarely to the fileid change watched that scrolls to the file

Comment (susnux) [reply apps/files/src/views/FilesList.vue]: @skjnldsv I pushed a commit implementing reactive `openfile` instead of that event, please review :)

**Review by skjnldsv — APPROVED** [review]
Other than the highlight simplification we talked about, I'm good for this :+1: 
Awesome work!

Btw, related issue: https://github.com/nextcloud/server/issues/21609

**Comment by susnux** [comment]
> Other than the highlight simplification we talked about, I'm good for this 👍

Removed that :+1:

**Review by AndyScherzinger — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
:shipit:

**Comment by nickvergessen** [comment]
Doesn't seem to work for Text files,
but works nicely for folders <3

**Comment by Luncheon3462** [comment]
Not fixed in 28.0.3 While I can create a file name, the document does not open.   Correct behavior is creating a file name and then the document should open automatically.   NC27 works fine/appropriately.

**Comment by susnux** [comment]
If you do not have any templates, this indeed does not work. Somehow I missed on of the `node:focus` events when removing them.
