### PR TITLE
fix(filesDrop): drag-and-drop folder upload

### LINKED ISSUE #58454: [Bug]: Drag&Drop folder upload not working
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After updating to version 33 the Drag&Drop upload of a folder to an external S3 storage doesn't work anymore. I get the following messages:
```
Some files could not be uploaded
Target folder does not exist any more
```
Tested with Safari and Firefox. The error is present only when folders are uploaded and only when the destination is an external S3 storage. Single or multiple files upload via Drag&Drop without issues.

Curiously the uploaded folders structure is created in user's root folder instead and it's empty (no files). Only the folder tree is created.

### Steps to reproduce

1. Upload via Drag&Drop a folder (or a bunch of nested folders) to an external S3 storage destination in Nextcloud via browser
2. Error notification appear, no files are uploaded and an empty folder tree is created in user's root instead

### Expected behavior

The uploaded folder structure should be created in the S3 destination folder and its content files uploaded.

### Nextcloud Server version

33

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 31 to 32)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by solracsf**
* Resolves: https://github.com/nextcloud/server/pull/59294
  * Resolves duplicate: https://github.com/nextcloud/groupfolders/issues/4515
  * Resolves duplicate: https://github.com/nextcloud/server/issues/59197

## Summary

When dragging and dropping a folder structure into any non-root destination (group folders, subfolders), subdirectories were created at the wrong WebDAV path. For team folders, the directory was created in the user's personal files entirely. Files then failed to upload because the target directory didn't exist in the team folder.

**The fix:** pass the destination (`IFolder`) to `createDirectoryIfNotExists` so it uses `destination.source` as its WebDAV base URL, as `uploader.upload` already does.

---

Please note: the bug affects any non-root destination equally.

The old code only worked "by accident" when the user was at the root level, because `destination.source` happened to equal `defaultRemoteURL + defaultRootPath`. The moment you navigate into any subfolder, regular or Team Folder, and drag-drop a folder there, the MKCOL goes to the wrong location (it creates the directory at the user root instead of the current folder).

The fix should apply universally to any non-root destination.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)
- [x] [Labels added](https://github.com/nextcloud/server/labels) where applicable (ex: bug/enhancement, `3. to review`, feature component)
- [x] [Milestone added](https://github.com/nextcloud/server/milestones) for target branch/version (ex: 32.x for `stable32`)

## AI (if applicable)

- [ ] The content of this PR was partly or fully generated using AI

### CODE REVIEW

**Comment by susnux** [comment]
Should already be fixed with https://github.com/nextcloud/server/pull/58680

**Comment by solracsf** [comment]
@susnux not on 32.0.7 RC1 (and that PR is included).

File: apps/files/src/services/DropServiceUtils.ts [hunk 1]
```diff
@@ -133,17 +133,21 @@ function readDirectory(directory: FileSystemDirectoryEntry): Promise<FileSystemE
...
+ * @param path - The path relative to the destination root
+ * @param destination - The destination folder. When provided, directories are created relative
+ *   to its source URL instead of the default user root. This is needed for uploads into
+ *   non-default locations like team folders.
  */
-export async function createDirectoryIfNotExists(path: string) {
-	const davUrl = join(defaultRemoteURL, defaultRootPath)
+export async function createDirectoryIfNotExists(path: string, destination?: IFolder) {
+	const davUrl = destination?.source ?? join(defaultRemoteURL, defaultRootPath)
+	const davRoot = destination?.root ?? defaultRootPath
```
Comment (susnux) [inline apps/files/src/services/DropServiceUtils.ts:143]: How does this fix the described problem?

Because what you have changed is only the davclient now has a dav url pointing to the `subfolder` not to the dav root. But that seems wrong:

```js
// before it evaluated like
const davUrl = 'http://instance/remote.php/dav/files/user`
client.createDirectory('some-subfolder/new-folder')
// results in MKCOL http://instance/remote.php/dav/files/user/some-subfolder/new-folder

// now
const davUrl = 'http://instance/remote.php/dav/files/user/some-subfolder`
client.createDirectory('some-subfolder/new-folder')
// results in MKCOL http://instance/remote.php/dav/files/user/some-subfolder/some-subfolder/new-folder
```

Comment (solracsf) [reply apps/files/src/services/DropServiceUtils.ts:143]: Because, as a read it, `relativePath` never includes the destination path and it starts from `'/'`?
Otherwise point me to the right direction.

Comment (susnux) [reply apps/files/src/services/DropServiceUtils.ts:143]: ah yes its relative to the destination not the root 👀

**Review by susnux — APPROVED** [review]
I see this is not about not uploading in the "root" but its about different dav roots

**Review by cristianscheid — APPROVED** [review]
Looks good to me.
