### PR TITLE
Fix ETAG returned by bulk upload

### LINKED ISSUE #4243: 3.4.2 conflicts on every edit
I was affected by #4016, and as a result of that, I've updated all clients on all machines to 3.4.2, updated the server from 22.0.0 -> 22.1.1 -> 22.2.3 -> 23.0.0 -> 23.0.1, and followed https://github.com/nextcloud/desktop/wiki/Fix-bug-invalid-modification-date to fix the invalid modification dates on the server.

Unfortunately, I'm now affected by an even more severe bug:

### Steps to reproduce
1. I create a new file "test.txt" and write a single letter "a" into it, and hit Ctrl+S to save. I even wait until the Nextcloud client shows it is synchronized.
2. With the editor still open, I add a second letter "b" and hit Ctrl+S again.
3. The Nextcloud client shows "Conflict: Server version downloaded, local copy renamed and not uploaded", I get a "test (conflicted copy 2022-02-03 084856).txt", and Nextcloud asks me what version to keep.
   Even worse, Nextcloud first overwrites my just edited version of the file by the server copy (which only contains "a"). My editor notices that and asks me whether to reload the file. If I hit "Yes", my latest edit is gone.

This is perfectly reproducible on two Windows 10.0.19044 systems (connected to the same Nextcloud account).
I'm using a traditional setup with a single Nextcloud folder that is locally synchronized (no virtual folders).

### Expected behaviour
Nextcloud uploads the newly edited file without a notice, as it did for years.

### Actual behaviour
Nextcloud replaces my edits with the last copy from the server and asks for conflict resolution, making work inside the Nextcloud folder impossible.

### Client configuration
Client version: 3.4.2
Operating system: Windows 10 (10.0.19044)
OS language: German
Installation path of client: C:\Program Files\Nextcloud

### Server configuration
Nextcloud version: 23.0.1
Storage backend (external storage): local

### PR DESCRIPTION
**Pull request by come-nc**
Refresh Node object to get fresh fileinfo data after touch.
Should fix https://github.com/nextcloud/desktop/issues/4243

Problem was that $node->touch updates mtime but not etag. @icewind1991 do you know of a cleaner way to refresh the etag after calling touch?

Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

### CODE REVIEW

File: apps/dav/lib/BulkUpload/BulkUploadPlugin.php [hunk 1]
```diff
@@ -90,6 +90,7 @@ public function httpPost(RequestInterface $request, ResponseInterface $response)
 
 				$node = $this->userFolder->newFile($headers['x-file-path'], $content);
 				$node->touch($mtime);
+				$node = $this->userFolder->getById($node->getId());
```
Comment (artonge) [inline apps/dav/lib/BulkUpload/BulkUploadPlugin.php:93]:
```suggestion
					$node = $this->userFolder->getById($node->getId())[0];
```

**Review by artonge — CHANGES_REQUESTED** [review]

File: apps/dav/lib/BulkUpload/BulkUploadPlugin.php (hunk 1 above)
Comment (come-nc) [reply apps/dav/lib/BulkUpload/BulkUploadPlugin.php]: So how come it worked when @mgallien tested it :thinking:

Comment (mgallien) [reply apps/dav/lib/BulkUpload/BulkUploadPlugin.php]: tested again on stable24 branch with bulk upload advertised in capabilities and I can confirm that it works
without `[0]` I get an exception no idea how I missed it when testing

**Review by mgallien — APPROVED** [review]
works fine
desktop client manages to bulk upload and receives a valid etag with this change

**Review by artonge — APPROVED** [review]
