### PR TITLE
fix(core): Do not invert app menu text color

### LINKED ISSUE #38759: [Bug]: Inverted app label color for light background color
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When selecting a plain color as background and choose a light one (e.g., white), the app icons in the top bar are inverted to a dark color but the labels stay white and are therefore not/poorly visible.

image

This is, because the color of the whole app menu entry is inverted for a light background color, while the `--color-primary-element-text'` is inverted as well, leading to a white text color on a light background.

### Steps to reproduce

1. In the appearance and accessibility settings select "No background" 
2. Change the color to white or a very light shade

### Expected behavior

The labels of the apps in the top bar should have a dark colour to be easily readable.

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by Hephi2**
* Resolves: #38759 
Fixes #38759

## Summary
Instead of inverting the color of the whole app entry in the menubar when using a light background, only the color of the app icon is inverted. The invertion of the label color already happens here: https://github.com/nextcloud/server/blob/63bf207ca7a18dd50ce3aeaea42e53f4ee400fc0/apps/theming/lib/Themes/CommonThemeTrait.php#L68

##Screenshots
Before:
image

After:
image

Tested on Chrome, Edge, Firefox and Opera Browser

### CODE REVIEW

**Comment by szaimen** [comment]
Conflicts...

File: core/src/components/AppMenu.vue [hunk 1]
```diff
@@ -146,7 +146,7 @@ $header-icon-size: 20px;
 		height: 50px;
 		position: relative;
 		display: flex;
-		filter: var(--background-image-invert-if-bright);
+		opacity: .7;
```
Comment (szaimen) [inline core/src/components/AppMenu.vue:149]: I think this was removed by purpose:
```suggestion
```

Comment (Hephi2) [reply core/src/components/AppMenu.vue:149]: Oh yeah, my mistake while resolving the conflicts.

**Review by szaimen — APPROVED** [review]
Seems to fix the linked problem in my testing

**Review by mejo- — APPROVED** [review]

**Comment by mejo-** [comment]
The cypress tests need to be fixed first, I think @Hephi2 will do so later.

**Review by susnux — APPROVED** [review]

**Comment by mejo-** [comment]
> It is most of the time faster to compile and commit it locally :)

Thanks @susnux! But for the sake of easier backports its still better to keep source changes and compiled asset changes in separate commits, no?

**Comment by mejo-** [comment]
I don't understand why the Cypress Tests fail here :thinking:

**Comment by susnux** [comment]
Locally it works. Cypress seems currently broken on CI (server master) (see all other CI runs)

**Comment by mejo-** [comment]
I splitted the PR between source code changes and compiled JS assets and rebased. Cypress CI test issues seem to have solved themselves :magic_wand:

**Comment by Hephi2** [comment]
/backport 7f861980a3b9d07076b89bbb9311f9bab00a935f to stable27
