### PR TITLE
Fix UniqueConstraintViolationException while insert into oc_filecache

### LINKED ISSUE #6160: Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO "oc_filecache"
### Steps to reproduce
Don't know

### Expected behaviour
No error

### Actual behaviour
See Nextcloud log

### General server configuration

**Operating system:** Linux cloud.techandme.se 4.4.0-91-generic #114-Ubuntu SMP Tue Aug 8 11:56:56 UTC 2017 x86_64

**Web server:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** pgsql PostgreSQL 9.6.4 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, 64-bit

**PHP version:** 7.0.22-0ubuntu0.16.04.1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - filter
 - hash
 - Reflection
 - SPL
 - session
 - standard
 - apache2handler
 - PDO
 - xml
 - calendar
 - ctype
 - curl
 - dom
 - mbstring
 - fileinfo
 - ftp
 - gd
 - gettext
 - iconv
 - imap
 - intl
 - json
 - ldap
 - exif
 - mcrypt
 - pdo_pgsql
 - pdo_sqlite
 - pgsql
 - Phar
 - posix
 - readline
 - redis
 - shmop
 - SimpleXML
 - smbclient
 - sockets
 - sqlite3
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xmlreader
 - xmlwriter
 - xsl
 - zip
 - libsmbclient
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.2 - 12.0.2.0

**Updated from an older Nextcloud/ownCloud or fresh install:** YOUR ANSWER HERE

**Where did you install Nextcloud from:**  YOUR ANSWER HERE

**Are you using external storage, if yes which one:** Array
(
    [0] => \OC\Files\Storage\Local
    [1] => \OCA\Files_External\Lib\Storage\FTP
    [2] => \OC\Files\Storage\DAV
    [3] => \OCA\Files_External\Lib\Storage\OwnCloud
    [4] => \OCA\Files_External\Lib\Storage\SFTP
    [5] => \OCA\Files_External\Lib\Storage\AmazonS3
    [6] => \OCA\Files_External\Lib\Storage\Dropbox
    [7] => \OCA\Files_External\Lib\Storage\Google
    [8] => \OCA\Files_External\Lib\Storage\Swift
    [9] => \OCA\Files_External\Lib\Storage\SFTP
    [10] => \OCA\Files_External\Lib\Storage\SMB
    [11] => \OCA\Files_External\Lib\Storage\SMB
)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** NO
(LDAP/ActiveDirectory/Webdav/...)

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - admin_notifications: 1.0.0
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - checksum: 0.3.5
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_downloadactivity: 1.1.1
 - files_external: 1.3.0
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - impersonate: 1.0.1
 - issuetemplate: 0.2.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.6.4
 - nextcloud_announcements: 1.1
 - notes: 2.3.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - ocsms: 1.12.0
 - password_policy: 1.2.2
 - previewgenerator: 1.0.6
 - provisioning_api: 1.2.0
 - qownnotesapi: 17.5.0
 - richdocuments: 1.12.34
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - socialsharing_diaspora: 1.0.1
 - socialsharing_email: 1.0.1
 - socialsharing_facebook: 1.0.1
 - socialsharing_googleplus: 1.0.1
 - socialsharing_twitter: 1.0.1
 - spreed: 2.0.1
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - twofactor_totp: 1.3.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - admin_audit
 - encryption
 - user_external
 - user_ldap
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "updatechecker": false,
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "192.168.4.111",
        "cloud.techandme.se",
    ],
    "datadirectory": "\/var\/ncdata",
    "overwrite.cli.url": "https:\/\/cloud.techandme.se\/",
    "dbtype": "pgsql",
    "version": "12.0.2.0",
    "dbname": "nextcloud_db",
    "dbhost": "127.0.0.1",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "Europe\/Stockholm",
    "installed": true,
    "instanceid": "oc7aii0tkiol",
    "mail_smtpmode": "smtp",
    "mail_smtpauth": 1,
    "mail_smtpport": "587",
    "mail_smtphost": "mail.citynetwork.se",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "no-reply",
    "mail_domain": "techandme.se",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "allowZipDownload": true,
    "session_lifetime": 1800,
    "forcessl": true,
    "logfile": "\/var\/log\/nfs-share\/nextcloud.log",
    "loglevel": 2,
    "memcache.local": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": true,
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "\/var\/run\/redis\/redis.sock",
        "port": 0,
        "timeout": 0,
        "dbindex": 0
    },
    "trusted_proxies": [
        [
            "192.168.10.201"
        ]
    ],
    "forwarded_for_headers": [
        "HTTP_X_FORWARDED",
        "HTTP_FORWARDED_FOR"
    ],
    "maintenance": false,
    "mail_smtpsecure": "tls",
    "htaccess.RewriteBase": "\/",
    "theme": "",
    "updater.release.channel": "stable",
    "trashbin_retention_obligation": "auto, 30",
    "activity_expire_days": 60
}
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36

**Operating system:** Ubuntu 16.04 Server

### Logs

<details>
        <summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO "oc_filecache" ("mimepart","mimetype","mtime","size","etag","storage_mtime","permissions","checksum","path_hash","path","parent","name","storage") SELECT ?,?,?,?,?,?,?,?,?,?,?,?,? FROM "oc_filecache" WHERE "storage" = ? AND "path_hash" = ? HAVING COUNT(*) = 0' with params [1, 2, 1502911047, -1, "59949a47cabae", 1502911047, 31, "", "fb66dca5f27af6f15c1d1d81e6f8d28b", "files_trashbin", 1742774, "files_trashbin", 136, 136, "fb66dca5f27af6f15c1d1d81e6f8d28b"]: SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "fs_storage_path_hash" DETAIL: Key (storage, path_hash)=(136, fb66dca5f27af6f15c1d1d81e6f8d28b) already exists.
/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php - line 128: Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php - line 1015: Doctrine\DBAL\DBALException driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO "oc...', Array)
/var/www/nextcloud/lib/private/DB/Connection.php - line 213: Doctrine\DBAL\Connection->executeUpdate('INSERT INTO "oc...', Array, Array)
/var/www/nextcloud/lib/private/DB/Adapter.php - line 114: OC\DB\Connection->executeUpdate('INSERT INTO "oc...', Array)
/var/www/nextcloud/lib/private/DB/Connection.php - line 251: OC\DB\Adapter->insertIfNotExist('*PREFIX*filecac...', Array, Array)
/var/www/nextcloud/lib/private/Files/Cache/Cache.php - line 273: OC\DB\Connection->insertIfNotExist('*PREFIX*filecac...', Array, Array)
/var/www/nextcloud/lib/private/Files/Cache/Cache.php - line 230: OC\Files\Cache\Cache->insert('files_trashbin', Array)
/var/www/nextcloud/lib/private/Files/Cache/Scanner.php - line 279: OC\Files\Cache\Cache->put('files_trashbin', Array)
/var/www/nextcloud/lib/private/Files/Cache/Scanner.php - line 216: OC\Files\Cache\Scanner->addToCache('files_trashbin', Array, -1)
/var/www/nextcloud/lib/private/Files/Cache/Scanner.php - line 175: OC\Files\Cache\Scanner->scanFile('files_trashbin')
/var/www/nextcloud/lib/private/Files/Cache/Scanner.php - line 322: OC\Files\Cache\Scanner->scanFile('files_trashbin/...', 3, -1, NULL, false)
/var/www/nextcloud/lib/private/Files/Cache/Updater.php - line 124: OC\Files\Cache\Scanner->scan('files_trashbin/...', false, 3, false)
/var/www/nextcloud/lib/private/Files/View.php - line 321: OC\Files\Cache\Updater->update('files_trashbin/...', 1502911047)
/var/www/nextcloud/lib/private/Files/View.php - line 1151: OC\Files\View->writeUpdate(Object(OCA\Files_Trashbin\Storage), 'files_trashbin/...')
/var/www/nextcloud/lib/private/Files/View.php - line 269: OC\Files\View->basicOperation('mkdir', '/files_trashbin...', Array)
/var/www/nextcloud/apps/files_trashbin/lib/Trashbin.php - line 154: OC\Files\View->mkdir('files_trashbin/...')
/var/www/nextcloud/apps/files_trashbin/lib/Trashbin.php - line 225: OCA\Files_Trashbin\Trashbin setUpTrash('klas')
/var/www/nextcloud/apps/files_trashbin/lib/Storage.php - line 247: OCA\Files_Trashbin\Trashbin move2trash('Photos', false)
/var/www/nextcloud/apps/files_trashbin/lib/Storage.php - line 189: OCA\Files_Trashbin\Storage->doDelete('files/Photos', 'rmdir')
/var/www/nextcloud/lib/private/Files/View.php - line 1136: OCA\Files_Trashbin\Storage->rmdir('files/Photos')
/var/www/nextcloud/lib/private/Files/View.php - line 348: OC\Files\View->basicOperation('rmdir', '/Photos', Array)
/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php - line 303: OC\Files\View->rmdir('/Photos')
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php - line 179: OCA\DAV\Connector\Sabre\Directory->delete()
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 287: Sabre\DAV\Tree->delete('Photos')
[internal function] Sabre\DAV\CorePlugin->httpDelete(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method DELETE', Array)
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/nextcloud/apps/dav/appinfo/v1/webdav.php - line 71: Sabre\DAV\Server->exec()
/var/www/nextcloud/remote.php - line 162: require_once('/var/www/nextcl...')
{main}
```
</details>

<details>
        <summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

### LINKED ISSUE #12228: Exception: Doctrine\\DBAL\\Exception\\DriverException | cannot start web service
Let's say the the problem is something like this:
– erroneous parsing of a filepath
– therefore invalid file cache (my uneducated guess: but not necesarrily broken database)
What would be the approach then? I'd be happy to rename/remove those offending files with fancy filepaths, clean the file cache and rerun the scan.
Do you think it is a viable course to take? How to debug more.. Thanks,
–Mateusz

### Steps to reproduce
1. initiate 
2. add a FTP local network external storage
3. wait for Nextcloud to scan the external storage

### Expected behaviour
regular Nextcloud start

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:
Armbian 5.25  Debian 8 Jessie   4.14.70 

**Web server:**
Apache 2.4.25, with HTTP2 enabled

**Database:**
MariaDB 10

**PHP version:**
PHP 7.2

**Nextcloud version:** (see Nextcloud admin page)
14.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh

**Where did you install Nextcloud from:**
[NextcloudPi flavour](https://github.com/nextcloud/nextcloudpi) run as [docker container](https://hub.docker.com/r/ownyourbits/nextcloudpi-armhf/)

**List of activated apps:**
**Nextcloud configuration:**

App list:
```
I'm unable to run any php command
```

<details>
<summary>config.php:</summary>

```
<?php
$CONFIG = array (
  'passwordsalt' => 'xxxxxxxxxxxxxxxxx',
  'secret' => 'xxxxxxxxxxxxxxx',
  'trusted_domains' => 
  array (
    0 => 'xxxxlhost',
    1 => 'xxxx17.0.2',
    2 => 'xxxxgepi.local',
    3 => 'xxxxngepi',
    4 => 'xxxxxxx.club',
    5 => 'xxxx168.0.11',
    6 => 'xxxxk.club',
    7 => 'xxxxcloudpi',
    8 => 'xxxxcloudpi.lan',
  ),
  'datadirectory' => '/data/app/data',
  'dbtype' => 'mysql',
  'version' => '14.0.3.0',
  'overwrite.cli.url' => 'https://xxxxxxx.club/',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'ncadmin',
  'dbpassword' => 'xxxxxxxxxxxxxxxxxxxxx',
  'installed' => true,
  'instanceid' => 'ockss4hwkl9y',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => '/var/run/redis/redis.sock',
    'port' => 0,
    'timeout' => 0.0,
    'password' => 'xxxxxxxxxxxxxxxxxxxxxxxx',
  ),
  'mail_smtpmode' => 'sendmail',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_from_address' => 'admin',
  'mail_domain' => 'ownyourbits.com',
  'overwriteprotocol' => 'https',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 0,
  'htaccess.RewriteBase' => '/',
);
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
– federated Nextcloud over internet
– FTP local storage

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### Web server error log
<details>
<summary>Web server error log</summary>

Web server keep spitting JSONs like this:
```
{"reqId":"riZBS6fd7hYtkmSh6w4d","level":0,"time":"2018-10-29T18:50:36+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":{"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`parent`,`checksum`,`path_hash`,`path`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,? FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ? HAVING COUNT(*) = 0' with params [\"7\", \"14\", 1494090201, 655, \"5bd7567c5e78c\", 1494090201, 27, 29827, \"\", \"883e7a025438168eebe9e9a6385f2c73\", \"mateusz\\\/komputerowe\\\/backupy\\\/ptaszor_z_windowsa\\\/MIOD-PITNY\\\/Data\\\/$OF\\\/76637\\\/24955 (2017_05_06 17_54_27 UTC).pyc\", \"24955 (2017_05_06 17_54_27 UTC).pyc\", 5, 5, \"883e7a025438168eebe9e9a6385f2c73\"]:\n\nSQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction","Code":0,"Trace":[{"file":"\/data\/app\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php","line":128,"function":"convertException","class":"Doctrine\\DBAL\\Driver\\AbstractMySQLDriver","type":"->","args":["An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`parent`,`checksum`,`path_hash`,`path`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,? FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ? HAVING COUNT(*) = 0' with params [\"7\", \"14\", 1494090201, 655, \"5bd7567c5e78c\", 1494090201, 27, 29827, \"\", \"883e7a025438168eebe9e9a6385f2c73\", \"mateusz\\\/komputerowe\\\/backupy\\\/ptaszor_z_windowsa\\\/MIOD-PITNY\\\/Data\\\/$OF\\\/76637\\\/24955 (2017_05_06 17_54_27 UTC).pyc\", \"24955 (2017_05_06 17_54_27 UTC).pyc\", 5, 5, \"883e7a025438168eebe9e9a6385f2c73\"]:\n\nSQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction",{"errorInfo":["40001",1213,"Deadlock found when trying to get lock; try restarting transaction"],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"}]},{"file":"\/data\/app\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php","line":1015,"function":"driverExceptionDuringQuery","class":"Doctrine\\DBAL\\DBALException","type":"::","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDOMySql\\Driver"},{"errorInfo":["40001",1213,"Deadlock found when trying to get lock; try restarting transaction"],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"},"INSERT INTO `oc_filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`parent`,`checksum`,`path_hash`,`path`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,? FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ? HAVING COUNT(*) = 0",{"1":"7","2":"14","3":1494090201,"4":655,"5":"5bd7567c5e78c","6":1494090201,"7":27,"8":29827,"9":"","10":"883e7a025438168eebe9e9a6385f2c73","11":"mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc","12":"24955 (2017_05_06 17_54_27 UTC).pyc","13":5,"14":5,"15":"883e7a025438168eebe9e9a6385f2c73"}]},{"file":"\/data\/app\/lib\/private\/DB\/Connection.php","line":216,"function":"executeUpdate","class":"Doctrine\\DBAL\\Connection","type":"->","args":["INSERT INTO `oc_filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`parent`,`checksum`,`path_hash`,`path`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,? FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ? HAVING COUNT(*) = 0",["7","14",1494090201,655,"5bd7567c5e78c",1494090201,27,29827,"","883e7a025438168eebe9e9a6385f2c73","mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc","24955 (2017_05_06 17_54_27 UTC).pyc",5,5,"883e7a025438168eebe9e9a6385f2c73"],[]]},{"file":"\/data\/app\/lib\/private\/DB\/Adapter.php","line":114,"function":"executeUpdate","class":"OC\\DB\\Connection","type":"->","args":["INSERT INTO `oc_filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`parent`,`checksum`,`path_hash`,`path`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,? FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ? HAVING COUNT(*) = 0",["7","14",1494090201,655,"5bd7567c5e78c",1494090201,27,29827,"","883e7a025438168eebe9e9a6385f2c73","mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc","24955 (2017_05_06 17_54_27 UTC).pyc",5,5,"883e7a025438168eebe9e9a6385f2c73"]]},{"file":"\/data\/app\/lib\/private\/DB\/Connection.php","line":254,"function":"insertIfNotExist","class":"OC\\DB\\Adapter","type":"->","args":["*PREFIX*filecache",{"mimepart":"7","mimetype":"14","mtime":1494090201,"size":655,"etag":"5bd7567c5e78c","storage_mtime":1494090201,"permissions":27,"parent":29827,"checksum":"","path_hash":"883e7a025438168eebe9e9a6385f2c73","path":"mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc","name":"24955 (2017_05_06 17_54_27 UTC).pyc","storage":5},["storage","path_hash"]]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Cache.php","line":272,"function":"insertIfNotExist","class":"OC\\DB\\Connection","type":"->","args":["*PREFIX*filecache",{"mimepart":"7","mimetype":"14","mtime":1494090201,"size":655,"etag":"5bd7567c5e78c","storage_mtime":1494090201,"permissions":27,"parent":29827,"checksum":"","path_hash":"883e7a025438168eebe9e9a6385f2c73","path":"mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc","name":"24955 (2017_05_06 17_54_27 UTC).pyc","storage":5},["storage","path_hash"]]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Wrapper\/CacheWrapper.php","line":128,"function":"insert","class":"OC\\Files\\Cache\\Cache","type":"->","args":["mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc",{"mimetype":"application\/octet-stream","mtime":1494090201,"size":655,"etag":"5bd7567c5e78c","storage_mtime":1494090201,"permissions":27,"scan_permissions":27,"parent":29827,"checksum":"","path":"mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc","name":"24955 (2017_05_06 17_54_27 UTC).pyc"}]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Wrapper\/CacheWrapper.php","line":114,"function":"insert","class":"OC\\Files\\Cache\\Wrapper\\CacheWrapper","type":"->","args":["mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc",{"mimetype":"application\/octet-stream","mtime":1494090201,"size":655,"etag":"5bd7567c5e78c","storage_mtime":1494090201,"permissions":27,"scan_permissions":27,"parent":"29827","checksum":""}]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Scanner.php","line":292,"function":"put","class":"OC\\Files\\Cache\\Wrapper\\CacheWrapper","type":"->","args":["mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc",{"mimetype":"application\/octet-stream","mtime":1494090201,"size":655,"etag":"5bd7567c5e78c","storage_mtime":1494090201,"permissions":27,"scan_permissions":27,"parent":"29827","checksum":""}]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Scanner.php","line":221,"function":"addToCache","class":"OC\\Files\\Cache\\Scanner","type":"->","args":["mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc",{"mimetype":"application\/octet-stream","mtime":1494090201,"size":655,"etag":"5bd7567c5e78c","storage_mtime":1494090201,"permissions":27,"scan_permissions":27,"parent":"29827","checksum":""},-1]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Scanner.php","line":438,"function":"scanFile","class":"OC\\Files\\Cache\\Scanner","type":"->","args":["mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc",3,"29827",false,true]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Scanner.php","line":406,"function":"handleChildren","class":"OC\\Files\\Cache\\Scanner","type":"->","args":["mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637",2,3,"29827",true,0]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Scanner.php","line":338,"function":"scanChildren","class":"OC\\Files\\Cache\\Scanner","type":"->","args":["mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637",2,3,"29827",true]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Scanner.php","line":521,"function":"scan","class":"OC\\Files\\Cache\\Scanner","type":"->","args":["mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637",2,3]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Scanner.php","line":532,"function":"OC\\Files\\Cache\\{closure}","class":"OC\\Files\\Cache\\Scanner","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Scanner.php","line":522,"function":"runBackgroundScanJob","class":"OC\\Files\\Cache\\Scanner","type":"->","args":[{"__class__":"Closure"},"mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637"]},{"file":"\/data\/app\/lib\/private\/Files\/Utils\/Scanner.php","line":173,"function":"backgroundScan","class":"OC\\Files\\Cache\\Scanner","type":"->","args":[]},{"file":"\/data\/app\/apps\/files\/lib\/BackgroundJob\/ScanFiles.php","line":88,"function":"backgroundScan","class":"OC\\Files\\Utils\\Scanner","type":"->","args":[""]},{"file":"\/data\/app\/apps\/files\/lib\/BackgroundJob\/ScanFiles.php","line":112,"function":"runScanner","class":"OCA\\Files\\BackgroundJob\\ScanFiles","type":"->","args":[{"__class__":"OC\\User\\User"}]},{"file":"\/data\/app\/lib\/private\/BackgroundJob\/Job.php","line":61,"function":"run","class":"OCA\\Files\\BackgroundJob\\ScanFiles","type":"->","args":[null]},{"file":"\/data\/app\/lib\/private\/BackgroundJob\/TimedJob.php","line":55,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},{"file":"\/data\/app\/cron.php","line":123,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"\/data\/app\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":115,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDOException","Message":"SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction","Code":"40001","Trace":[{"file":"\/data\/app\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php","line":1008,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDOStatement","type":"->","args":[["7","14",1494090201,655,"5bd7567c5e78c",1494090201,27,29827,"","883e7a025438168eebe9e9a6385f2c73","mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc","24955 (2017_05_06 17_54_27 UTC).pyc",5,5,"883e7a025438168eebe9e9a6385f2c73"]]},{"file":"\/data\/app\/lib\/private\/DB\/Connection.php","line":216,"function":"executeUpdate","class":"Doctrine\\DBAL\\Connection","type":"->","args":["INSERT INTO `oc_filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`parent`,`checksum`,`path_hash`,`path`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,? FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ? HAVING COUNT(*) = 0",["7","14",1494090201,655,"5bd7567c5e78c",1494090201,27,29827,"","883e7a025438168eebe9e9a6385f2c73","mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc","24955 (2017_05_06 17_54_27 UTC).pyc",5,5,"883e7a025438168eebe9e9a6385f2c73"],[]]},{"file":"\/data\/app\/lib\/private\/DB\/Adapter.php","line":114,"function":"executeUpdate","class":"OC\\DB\\Connection","type":"->","args":["INSERT INTO `oc_filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`parent`,`checksum`,`path_hash`,`path`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,? FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ? HAVING COUNT(*) = 0",["7","14",1494090201,655,"5bd7567c5e78c",1494090201,27,29827,"","883e7a025438168eebe9e9a6385f2c73","mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc","24955 (2017_05_06 17_54_27 UTC).pyc",5,5,"883e7a025438168eebe9e9a6385f2c73"]]},{"file":"\/data\/app\/lib\/private\/DB\/Connection.php","line":254,"function":"insertIfNotExist","class":"OC\\DB\\Adapter","type":"->","args":["*PREFIX*filecache",{"mimepart":"7","mimetype":"14","mtime":1494090201,"size":655,"etag":"5bd7567c5e78c","storage_mtime":1494090201,"permissions":27,"parent":29827,"checksum":"","path_hash":"883e7a025438168eebe9e9a6385f2c73","path":"mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc","name":"24955 (2017_05_06 17_54_27 UTC).pyc","storage":5},["storage","path_hash"]]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Cache.php","line":272,"function":"insertIfNotExist","class":"OC\\DB\\Connection","type":"->","args":["*PREFIX*filecache",{"mimepart":"7","mimetype":"14","mtime":1494090201,"size":655,"etag":"5bd7567c5e78c","storage_mtime":1494090201,"permissions":27,"parent":29827,"checksum":"","path_hash":"883e7a025438168eebe9e9a6385f2c73","path":"mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc","name":"24955 (2017_05_06 17_54_27 UTC).pyc","storage":5},["storage","path_hash"]]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Wrapper\/CacheWrapper.php","line":128,"function":"insert","class":"OC\\Files\\Cache\\Cache","type":"->","args":["mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc",{"mimetype":"application\/octet-stream","mtime":1494090201,"size":655,"etag":"5bd7567c5e78c","storage_mtime":1494090201,"permissions":27,"scan_permissions":27,"parent":29827,"checksum":"","path":"mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc","name":"24955 (2017_05_06 17_54_27 UTC).pyc"}]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Wrapper\/CacheWrapper.php","line":114,"function":"insert","class":"OC\\Files\\Cache\\Wrapper\\CacheWrapper","type":"->","args":["mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc",{"mimetype":"application\/octet-stream","mtime":1494090201,"size":655,"etag":"5bd7567c5e78c","storage_mtime":1494090201,"permissions":27,"scan_permissions":27,"parent":"29827","checksum":""}]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Scanner.php","line":292,"function":"put","class":"OC\\Files\\Cache\\Wrapper\\CacheWrapper","type":"->","args":["mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc",{"mimetype":"application\/octet-stream","mtime":1494090201,"size":655,"etag":"5bd7567c5e78c","storage_mtime":1494090201,"permissions":27,"scan_permissions":27,"parent":"29827","checksum":""}]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Scanner.php","line":221,"function":"addToCache","class":"OC\\Files\\Cache\\Scanner","type":"->","args":["mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc",{"mimetype":"application\/octet-stream","mtime":1494090201,"size":655,"etag":"5bd7567c5e78c","storage_mtime":1494090201,"permissions":27,"scan_permissions":27,"parent":"29827","checksum":""},-1]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Scanner.php","line":438,"function":"scanFile","class":"OC\\Files\\Cache\\Scanner","type":"->","args":["mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc",3,"29827",false,true]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Scanner.php","line":406,"function":"handleChildren","class":"OC\\Files\\Cache\\Scanner","type":"->","args":["mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637",2,3,"29827",true,0]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Scanner.php","line":338,"function":"scanChildren","class":"OC\\Files\\Cache\\Scanner","type":"->","args":["mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637",2,3,"29827",true]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Scanner.php","line":521,"function":"scan","class":"OC\\Files\\Cache\\Scanner","type":"->","args":["mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637",2,3]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Scanner.php","line":532,"function":"OC\\Files\\Cache\\{closure}","class":"OC\\Files\\Cache\\Scanner","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Scanner.php","line":522,"function":"runBackgroundScanJob","class":"OC\\Files\\Cache\\Scanner","type":"->","args":[{"__class__":"Closure"},"mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637"]},{"file":"\/data\/app\/lib\/private\/Files\/Utils\/Scanner.php","line":173,"function":"backgroundScan","class":"OC\\Files\\Cache\\Scanner","type":"->","args":[]},{"file":"\/data\/app\/apps\/files\/lib\/BackgroundJob\/ScanFiles.php","line":88,"function":"backgroundScan","class":"OC\\Files\\Utils\\Scanner","type":"->","args":[""]},{"file":"\/data\/app\/apps\/files\/lib\/BackgroundJob\/ScanFiles.php","line":112,"function":"runScanner","class":"OCA\\Files\\BackgroundJob\\ScanFiles","type":"->","args":[{"__class__":"OC\\User\\User"}]},{"file":"\/data\/app\/lib\/private\/BackgroundJob\/Job.php","line":61,"function":"run","class":"OCA\\Files\\BackgroundJob\\ScanFiles","type":"->","args":[null]},{"file":"\/data\/app\/lib\/private\/BackgroundJob\/TimedJob.php","line":55,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},{"file":"\/data\/app\/cron.php","line":123,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"\/data\/app\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php","Line":107,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction","Code":"40001","Trace":[{"file":"\/data\/app\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php","line":105,"function":"execute","class":"PDOStatement","type":"->","args":[["7","14",1494090201,655,"5bd7567c5e78c",1494090201,27,29827,"","883e7a025438168eebe9e9a6385f2c73","mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc","24955 (2017_05_06 17_54_27 UTC).pyc",5,5,"883e7a025438168eebe9e9a6385f2c73"]]},{"file":"\/data\/app\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php","line":1008,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDOStatement","type":"->","args":[["7","14",1494090201,655,"5bd7567c5e78c",1494090201,27,29827,"","883e7a025438168eebe9e9a6385f2c73","mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc","24955 (2017_05_06 17_54_27 UTC).pyc",5,5,"883e7a025438168eebe9e9a6385f2c73"]]},{"file":"\/data\/app\/lib\/private\/DB\/Connection.php","line":216,"function":"executeUpdate","class":"Doctrine\\DBAL\\Connection","type":"->","args":["INSERT INTO `oc_filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`parent`,`checksum`,`path_hash`,`path`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,? FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ? HAVING COUNT(*) = 0",["7","14",1494090201,655,"5bd7567c5e78c",1494090201,27,29827,"","883e7a025438168eebe9e9a6385f2c73","mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc","24955 (2017_05_06 17_54_27 UTC).pyc",5,5,"883e7a025438168eebe9e9a6385f2c73"],[]]},{"file":"\/data\/app\/lib\/private\/DB\/Adapter.php","line":114,"function":"executeUpdate","class":"OC\\DB\\Connection","type":"->","args":["INSERT INTO `oc_filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`parent`,`checksum`,`path_hash`,`path`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,? FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ? HAVING COUNT(*) = 0",["7","14",1494090201,655,"5bd7567c5e78c",1494090201,27,29827,"","883e7a025438168eebe9e9a6385f2c73","mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc","24955 (2017_05_06 17_54_27 UTC).pyc",5,5,"883e7a025438168eebe9e9a6385f2c73"]]},{"file":"\/data\/app\/lib\/private\/DB\/Connection.php","line":254,"function":"insertIfNotExist","class":"OC\\DB\\Adapter","type":"->","args":["*PREFIX*filecache",{"mimepart":"7","mimetype":"14","mtime":1494090201,"size":655,"etag":"5bd7567c5e78c","storage_mtime":1494090201,"permissions":27,"parent":29827,"checksum":"","path_hash":"883e7a025438168eebe9e9a6385f2c73","path":"mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc","name":"24955 (2017_05_06 17_54_27 UTC).pyc","storage":5},["storage","path_hash"]]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Cache.php","line":272,"function":"insertIfNotExist","class":"OC\\DB\\Connection","type":"->","args":["*PREFIX*filecache",{"mimepart":"7","mimetype":"14","mtime":1494090201,"size":655,"etag":"5bd7567c5e78c","storage_mtime":1494090201,"permissions":27,"parent":29827,"checksum":"","path_hash":"883e7a025438168eebe9e9a6385f2c73","path":"mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc","name":"24955 (2017_05_06 17_54_27 UTC).pyc","storage":5},["storage","path_hash"]]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Wrapper\/CacheWrapper.php","line":128,"function":"insert","class":"OC\\Files\\Cache\\Cache","type":"->","args":["mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc",{"mimetype":"application\/octet-stream","mtime":1494090201,"size":655,"etag":"5bd7567c5e78c","storage_mtime":1494090201,"permissions":27,"scan_permissions":27,"parent":29827,"checksum":"","path":"mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc","name":"24955 (2017_05_06 17_54_27 UTC).pyc"}]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Wrapper\/CacheWrapper.php","line":114,"function":"insert","class":"OC\\Files\\Cache\\Wrapper\\CacheWrapper","type":"->","args":["mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc",{"mimetype":"application\/octet-stream","mtime":1494090201,"size":655,"etag":"5bd7567c5e78c","storage_mtime":1494090201,"permissions":27,"scan_permissions":27,"parent":"29827","checksum":""}]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Scanner.php","line":292,"function":"put","class":"OC\\Files\\Cache\\Wrapper\\CacheWrapper","type":"->","args":["mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc",{"mimetype":"application\/octet-stream","mtime":1494090201,"size":655,"etag":"5bd7567c5e78c","storage_mtime":1494090201,"permissions":27,"scan_permissions":27,"parent":"29827","checksum":""}]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Scanner.php","line":221,"function":"addToCache","class":"OC\\Files\\Cache\\Scanner","type":"->","args":["mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc",{"mimetype":"application\/octet-stream","mtime":1494090201,"size":655,"etag":"5bd7567c5e78c","storage_mtime":1494090201,"permissions":27,"scan_permissions":27,"parent":"29827","checksum":""},-1]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Scanner.php","line":438,"function":"scanFile","class":"OC\\Files\\Cache\\Scanner","type":"->","args":["mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc",3,"29827",false,true]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Scanner.php","line":406,"function":"handleChildren","class":"OC\\Files\\Cache\\Scanner","type":"->","args":["mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637",2,3,"29827",true,0]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Scanner.php","line":338,"function":"scanChildren","class":"OC\\Files\\Cache\\Scanner","type":"->","args":["mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637",2,3,"29827",true]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Scanner.php","line":521,"function":"scan","class":"OC\\Files\\Cache\\Scanner","type":"->","args":["mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637",2,3]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Scanner.php","line":532,"function":"OC\\Files\\Cache\\{closure}","class":"OC\\Files\\Cache\\Scanner","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/data\/app\/lib\/private\/Files\/Cache\/Scanner.php","line":522,"function":"runBackgroundScanJob","class":"OC\\Files\\Cache\\Scanner","type":"->","args":[{"__class__":"Closure"},"mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637"]},{"file":"\/data\/app\/lib\/private\/Files\/Utils\/Scanner.php","line":173,"function":"backgroundScan","class":"OC\\Files\\Cache\\Scanner","type":"->","args":[]},{"file":"\/data\/app\/apps\/files\/lib\/BackgroundJob\/ScanFiles.php","line":88,"function":"backgroundScan","class":"OC\\Files\\Utils\\Scanner","type":"->","args":[""]},{"file":"\/data\/app\/apps\/files\/lib\/BackgroundJob\/ScanFiles.php","line":112,"function":"runScanner","class":"OCA\\Files\\BackgroundJob\\ScanFiles","type":"->","args":[{"__class__":"OC\\User\\User"}]},{"file":"\/data\/app\/lib\/private\/BackgroundJob\/Job.php","line":61,"function":"run","class":"OCA\\Files\\BackgroundJob\\ScanFiles","type":"->","args":[null]},{"file":"\/data\/app\/lib\/private\/BackgroundJob\/TimedJob.php","line":55,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},{"file":"\/data\/app\/cron.php","line":123,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"\/data\/app\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php","Line":105}},"CustomMessage":"Exception while scanning file \"mateusz\/komputerowe\/backupy\/ptaszor_z_windowsa\/MIOD-PITNY\/Data\/$OF\/76637\/24955 (2017_05_06 17_54_27 UTC).pyc\""},"userAgent":"--","version":"14.0.3.0"}
```

few more of them here [https://paste.ee/p/36Mch)](https://paste.ee/p/36Mch) the only difference is the filename in question

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

The whole log is 32MiB. There is one very strange line which is 9MiB long… it includes some paths in it, which I enclose below. Seems like parsing of `#` sign is dodgy.. idk

<p>filename as in log
this is strange. those `#` characters

```
"mateusz/komputerowe/backupy/ptaszor_z_windowsa/MIOD-PITNY/Data/D/Ptaszor/Programowanie__/web/angluar2/tutorial/sample-Groceries/node_modules/es5-ext/array/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/_is-extensible (2017_01_18 21_28_48 UTC).js/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/valid-array (2017_01_18 21_28_48 UTC).js/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#//#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#"
```

</p>
<p>
actual filepath

```
"mateusz/komputerowe/backupy/ptaszor_z_windowsa/MIOD-PITNY/Data/D/Ptaszor/Programowanie__/web/angluar2/tutorial/sample-Groceries/node_modules/es5-ext/array/#/<many folders here>
```

</p>

</details>

#### BONUS offending command log

<details>
<summary>file content:</summary>

```
sudo -u www-data php occ files:scan --all
```
</details>

<details>
<summary>log</summary>

```
root@7c72ebb97d68:/# /usr/local/bin/ncp-scan                       
An unhandled exception has been thrown:
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'ncadmin'@'localhost' (using password: YES) in /data/app/lib/private/DB/Connection.php:64
Stack trace:
#0 /data/app/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /data/app/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /data/app/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /data/app/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /data/app/lib/private/DB/Connection.php(151): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /data/app/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#6 /data/app/lib/private/DB/ConnectionFactory.php(152): Doctrine\DBAL\DriverManager::getConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#7 /data/app/lib/private/Server.php(630): OC\DB\ConnectionFactory->getConnection('mysql', Array)
#8 /data/app/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#9 /data/app/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('OCP\\IDBConnecti...')
#10 /data/app/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OCP\\IDBConnecti...')
#11 /data/app/lib/private/AppFramework/Utility/SimpleContainer.php(165): OC\ServerContainer->query('OCP\\IDBConnecti...')
#12 /data/app/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#13 /data/app/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('DatabaseConnect...')
#14 /data/app/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('DatabaseConnect...')
#15 /data/app/lib/private/Server.php(1532): OC\ServerContainer->query('DatabaseConnect...')
#16 /data/app/lib/private/Server.php(352): OC\Server->getDatabaseConnection()
#17 /data/app/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#18 /data/app/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('OC\\Authenticati...')
#19 /data/app/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#20 /data/app/lib/private/AppFramework/Utility/SimpleContainer.php(68): OC\ServerContainer->query('OC\\Authenticati...')
#21 /data/app/lib/private/AppFramework/Utility/SimpleContainer.php(98): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#22 /data/app/lib/private/AppFramework/Utility/SimpleContainer.php(119): OC\AppFramework\Utility\SimpleContainer->resolve('OC\\Authenticati...')
#23 /data/app/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#24 /data/app/lib/private/AppFramework/Utility/SimpleContainer.php(68): OC\ServerContainer->query('OC\\Authenticati...')
#25 /data/app/lib/private/AppFramework/Utility/SimpleContainer.php(98): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#26 /data/app/lib/private/AppFramework/Utility/SimpleContainer.php(119): OC\AppFramework\Utility\SimpleContainer->resolve('OC\\Authenticati...')
#27 /data/app/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#28 /data/app/lib/private/AppFramework/Utility/SimpleContainer.php(165): OC\ServerContainer->query('OC\\Authenticati...')
#29 /data/app/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#30 /data/app/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('OC\\Authenticati...')
#31 /data/app/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#32 /data/app/lib/private/Server.php(364): OC\ServerContainer->query('OC\\Authenticati...')
#33 /data/app/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#34 /data/app/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('OCP\\IUserSessio...')
#35 /data/app/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OCP\\IUserSessio...')
#36 /data/app/lib/private/AppFramework/Utility/SimpleContainer.php(165): OC\ServerContainer->query('OCP\\IUserSessio...')
#37 /data/app/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#38 /data/app/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('UserSession')
#39 /data/app/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('UserSession')
#40 /data/app/lib/private/Server.php(1408): OC\ServerContainer->query('UserSession')
#41 /data/app/lib/private/Server.php(683): OC\Server->getUserSession()
#42 /data/app/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#43 /data/app/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('OC\\App\\AppManag...')
#44 /data/app/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\App\\AppManag...')
#45 /data/app/lib/private/AppFramework/Utility/SimpleContainer.php(165): OC\ServerContainer->query('OC\\App\\AppManag...')
#46 /data/app/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#47 /data/app/lib/private/AppFramework/Utility/SimpleContainer.php(117): Pimple\Container->offsetGet('AppManager')
#48 /data/app/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('AppManager')
#49 /data/app/lib/private/Server.php(1703): OC\ServerContainer->query('AppManager')
#50 /data/app/lib/private/legacy/app.php(342): OC\Server->getAppManager()
#51 /data/app/lib/private/legacy/app.php(113): OC_App::getEnabledApps()
#52 /data/app/lib/base.php(654): OC_App::loadApps(Array)
#53 /data/app/lib/base.php(1068): OC::init()
#54 /data/app/console.php(46): require_once('/data/app/lib/b...')
#55 /data/app/occ(11): require_once('/data/app/conso...')
#56 {main}
```

</details>

Every other `occ` command throws the same trace

I'm very eager to perform any additional tests per request 🙄

### PR DESCRIPTION
**Pull request by MorrisJobke**
* fixes #6160 by not being prone to the race condition in insertIfNotExists
* fixes #12228 by not using a query that can result in a deadlock
* replaces the insertIfNotExists call with an insert which is wrapped into a try-catch block
* followup to #12371 

I would back port this one to stable13 and stable14 as well because it is a smaller and not that invasive version of #12371 and it also fixes the deadlocks.

### CODE REVIEW

File: lib/private/Files/Cache/Cache.php [hunk 1]
```diff
@@ -268,12 +269,20 @@ public function insert($file, array $data) {
...
+			}
+
+			if ($builder->execute()) {
+				return (int)$this->connection->lastInsertId('*PREFIX*filecache');
+			}
+		} catch(UniqueConstraintViolationException $e) {
+			// entry exists already
 		}
 
 		// The file was created in the mean time
```
Comment (nickvergessen) [inline lib/private/Files/Cache/Cache.php]: The exception text in the else needs to be adjusted

Comment (MorrisJobke) [reply lib/private/Files/Cache/Cache.php]: Good point - let me adjust this.

File: lib/private/Files/Cache/Cache.php [hunk 2]
```diff
@@ -268,20 +271,28 @@ public function insert($file, array $data) {
...
-		])
-		) {
-			return (int)$this->connection->lastInsertId('*PREFIX*filecache');
+
+		try {
+			$builder = $this->connection->getQueryBuilder();
+			$builder->insert('filecache');
+
+			foreach ($values as $column => $value) {
+				$builder->setValue($column, $builder->createNamedParameter($value));
```
Comment (MorrisJobke) [inline lib/private/Files/Cache/Cache.php]: It also said, that there is an sql injection problem (this came from our plugin to Phan). I double checked and the column as well as the argument are both properly escaped.

**Review by nickvergessen — APPROVED** [review]

**Review by JanDragon — APPROVED** [review]

**Review by kesselb — APPROVED** [review]

**Comment by MorrisJobke** [comment]
> ```
> 
> ```
> Query looks good and unique constraint is working. `mimepart` and `mimetype` passed as `string` and stored as `bigint` but `insertIfNotExist` works similiar 👍

Yep - I didn't changed anything there. We can tackle the types later, but for now I want to go for the least intrusive way.
