### PR TITLE
fix: Reduce deprecation warnings in phpunit_nodb CI jobs

### LINKED ISSUE #57019: phpunit_nodb GitHub Action logs flooded with deprecation warnings
The phpunit_nodb GitHub Action logs currently display a significant number of deprecation warnings which makes it difficult to quickly identify actual test failures or relevant output during CI runs.

Link: https://github.com/nextcloud/server/actions/runs/20064467169/job/57550090547

### PR DESCRIPTION
**Pull request by abhinavohri**
* Resolves: https://github.com/nextcloud/server/issues/57019

## Summary
 This PR addresses the high volume of deprecation warnings appearing in the phpunit_nodb logs making it difficult to spot actual failures and potential issues.

Relevant links:
- https://github.com/sebastianbergmann/phpunit/issues/5241
- https://github.com/sebastianbergmann/phpunit/issues/5423
- https://github.com/sebastianbergmann/phpunit/issues/5243

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)
- [ ] [Labels added](https://github.com/nextcloud/server/labels) where applicable (ex: bug/enhancement, `3. to review`, feature component)
- [ ] [Milestone added](https://github.com/nextcloud/server/milestones) for target branch/version (ex: 32.x for `stable32`)

### CODE REVIEW

**Comment by SebastianKrupinski** [comment]
CalDAV part looks good

**Review by ChristophWurst — APPROVED** [review]

File: apps/files_external/tests/FrontendDefinitionTraitTest.php [hunk 1]
```diff
@@ -11,14 +11,18 @@
 use OCA\Files_External\Lib\FrontendDefinitionTrait;
 use OCA\Files_External\Lib\StorageConfig;
 
+class MockFrontendDefinitionTrait {
```
Comment (provokateurin) [inline apps/files_external/tests/FrontendDefinitionTraitTest.php]:
```suggestion
class MockFrontendDefinitionTraitClass {
```

Just to make it clear that this is a class (that uses the trait) and not a trait itself.

File: apps/files_external/tests/LegacyDependencyCheckPolyfillTest.php [hunk 2]
```diff
@@ -11,6 +11,14 @@
 use OCA\Files_External\Lib\LegacyDependencyCheckPolyfill;
 use OCA\Files_External\Lib\MissingDependency;
 
+class MockLegacyDependencyCheckPolyfill {
```
Comment (provokateurin) [inline apps/files_external/tests/LegacyDependencyCheckPolyfillTest.php]: Same here

**Review by provokateurin — APPROVED** [review]
Cool, just two minor things you could change.

**Review by provokateurin — APPROVED** [review]
