### PR TITLE
Remove the loop of calendars when only one is needed

### LINKED ISSUE #33599: get calendar gets all calendar for user
Line | Method
-- | --
3rdparty/doctrine/dbal/src/Connection.php 1045 | OC\DB\BacktraceDebugStack->startQuery
lib/private/DB/Connection.php 261 | Doctrine\DBAL\Connection->executeQuery
3rdparty/doctrine/dbal/src/Query/QueryBuilder.php 345 | OC\DB\Connection->executeQuery
lib/private/DB/QueryBuilder/QueryBuilder.php 281 | Doctrine\DBAL\Query\QueryBuilder->execute
lib/private/DB/QueryBuilder/QueryBuilder.php 294 | OC\DB\QueryBuilder\QueryBuilder->execute
apps/dav/lib/CalDAV/CalDavBackend.php 391 | OC\DB\QueryBuilder\QueryBuilder->executeQuery
apps/dav/lib/CalDAV/CalendarHome.php 163 | OCA\DAV\CalDAV\CalDavBackend->getCalendarsForUser
3rdparty/sabre/dav/lib/DAV/Tree.php 78 | OCA\DAV\CalDAV\CalendarHome->getChild
apps/dav/lib/Connector/Sabre/FilesReportPlugin.php 183 | Sabre\DAV\Tree->getNodeForPath
3rdparty/sabre/event/lib/WildcardEmitterTrait.php 89 | OCA\DAV\Connector\Sabre\FilesReportPlugin->onReport
3rdparty/sabre/dav/lib/DAV/CorePlugin.php 690 | Sabre\DAV\Server->emit
3rdparty/sabre/event/lib/WildcardEmitterTrait.php 89 | Sabre\DAV\CorePlugin->httpReport
3rdparty/sabre/dav/lib/DAV/Server.php 472 | Sabre\DAV\Server->emit
3rdparty/sabre/dav/lib/DAV/Server.php 253 | Sabre\DAV\Server->invokeMethod
3rdparty/sabre/dav/lib/DAV/Server.php 321 | Sabre\DAV\Server->start
apps/dav/lib/Server.php 357 | Sabre\DAV\Server->exec
apps/dav/appinfo/v2/remote.php 35 | OCA\DAV\Server->exec
remote.php 167 | require_once

### PR DESCRIPTION
**Pull request by miaulalala**
Fixes #33599

### CODE REVIEW

File: apps/dav/lib/CalDAV/CalendarHome.php [hunk 1]
```diff
@@ -159,11 +159,10 @@ public function getChild($name) {
 			return new TrashbinHome($this->caldavBackend, $this->principalInfo);
 		}
 
-		// Calendars
-		foreach ($this->caldavBackend->getCalendarsForUser($this->principalInfo['uri']) as $calendar) {
-			if ($calendar['uri'] === $name) {
-				return new Calendar($this->caldavBackend, $calendar, $this->l10n, $this->config, $this->logger);
-			}
+		// Calendar
+		$calendar = $this->caldavBackend->getCalendarByUri($this->principalInfo['uri'], $name);
```
Comment (tcitworld) [inline apps/dav/lib/CalDAV/CalendarHome.php:163]: I think `getCalendarByUri` doesn't work with shared calendars (the URI is suffixed with `_shared_by_$name` and it won't match anything here), can you check that?

Comment (miaulalala) [reply apps/dav/lib/CalDAV/CalendarHome.php:163]: yep, looks like it's breaking in calendar too. I'll see what I can do to fix this

File: apps/dav/lib/CalDAV/CalendarHome.php [hunk 2]
```diff
@@ -159,11 +159,10 @@
...
```
[the remark this answers is not in the document]
Comment (tcitworld) [reply apps/dav/lib/CalDAV/CalendarHome.php:163]: Also this makes psalm not happy as `getCalendarByUri` is an extra method from us, not in `BackendInterface`.

[the remark this answers is not in the document]
Comment (miaulalala) [reply apps/dav/lib/CalDAV/CalendarHome.php:163]: yeah i know. but it will reduce the queries to the dashboard and calendars by a fair amount and will help with performance.

File: apps/dav/lib/CalDAV/CalendarHome.php (hunk 1 above)
Comment (kesselb) [inline apps/dav/lib/CalDAV/CalendarHome.php:163]:
```suggestion
		if ($name === 'personal' || $name === 'contact_birthdays') {
			$calendarByUri = $this->caldavBackend->getCalendarByUri($this->principalInfo['uri'], $name);
			if (is_array($calendarByUri)) {
				return new Calendar($this->caldavBackend, $calendarByUri, $this->l10n, $this->config, $this->logger);
			}
		}

		foreach ($this->caldavBackend->getCalendarsForUser($this->principalInfo['uri']) as $calendar) {
			if ($calendar['uri'] === $name) {
				return new Calendar($this->caldavBackend, $calendar, $this->l10n, $this->config, $this->logger);
			}
		}
```

Comment (tcitworld) [reply apps/dav/lib/CalDAV/CalendarHome.php:163]: Well there's no need to restrict ourselves to these hardcoded calendar names, we could always try to load the calendar by URI and name, and fallback to the foreach loop in case it's not found.

Comment (kesselb) [reply apps/dav/lib/CalDAV/CalendarHome.php:163]: Sounds good!

**Review by tcitworld — APPROVED** [review]
Good enough for now, but I suggest the following to make psalm happy properly (possibly as an extra PR):

* Add a new interface DirectURIAccess providing the `getCalendarByUri` and `getSubscriptionByUri`.
* Implement `getSubscriptionByUri` in CalDAV backend
* This allows to do pretty much the same for subscriptions below (more speed :zap: )
* Put all of this into a `if ($this->caldavBackend instanceof DirectURIAccess)` check so that psalm is happy and we're keeping things clean).

**Comment by tcitworld** [comment]
Testing trashbin should work the same btw, through a `TrashbinSupport` interface.

**Comment by CarlSchwan** [comment]
Still some failures in drone

**Review by ChristophWurst — APPROVED** [review]

**Comment by miaulalala** [comment]
Drone failures with file sharing acceptance tests (unrelated?)

**Comment by nickvergessen** [comment]
Maybe a rebase can tell?

**Comment by st3iny** [comment]
Rebased to (hopefully) fix tests.

**Comment by ChristophWurst** [comment]
Drone restarted

**Comment by blizzz** [comment]
Linter is unhappy

**Comment by miaulalala** [comment]
Drone failure due to:

```


latest: Pulling from nextcloud/continuous-integration-php8.0
--
2 | Digest: sha256:3708f22218d6e3b8477d653fd83bf75230b8b61f0be9c25c162d96a14e89661f
3 | Status: Image is up to date for ghcr.io/nextcloud/continuous-integration-php8.0:latest
4 | + bash tests/drone-run-php-tests.sh \|\| exit 0
5 | =========================
6 | = List of changed files =
7 | =========================
8 | apps/dav/lib/CalDAV/CalendarHome.php
9 | apps/dav/tests/unit/CalDAV/CalendarHomeTest.php
10 | =========================
11 | PHP files are modified
12 | + NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh mariadb
13 | Using PHP executable /usr/bin/php
14 | Using database oc_autotest
15 | Setup environment for mariadb testing on local storage ...
16 | Waiting for MariaDB initialisation ...
17 | ............................................................................................................................................................................................................................................................................................................
18 | [ERROR] Waited 300 seconds, no response


```
