### PR TITLE
Accessibility fixes for header and global elements

### LINKED ISSUE #9994: Keyboard accessibility
There are some few things missing at the moment for proper keyboard-only accessibility:

- highlight + tooltip for contacts icon in header
- highlight + tooltip for settings icon in header
- possibly same for notifications
- Upload function in Files add menu not focusable

What else @nextcloud/accessibility @nextcloud/designers?

### LINKED ISSUE #10008: Unable to open file or folder with keyboard
Currently you can navigate the file list via keyboard, with 3 Tab-clicks per row:
- Folder/file itself
- Sharing that folder/file
- 3-dot menu of that folder/file

Now the problem is that pressing enter on the folder/file itself opens the right sidebar instead of opening it. We need to change it to opening, otherwise it is not possible to enter into folders or open files.

@nextcloud/designers @nextcloud/accessibility

### PR DESCRIPTION
**Pull request by jancborchardt**
Fix https://github.com/nextcloud/server/issues/9994 and fix https://github.com/nextcloud/server/issues/10008 :tada: 

- [x] Settings icon / avatar: fix opening on enter
- [x] Contacts: fix opening on enter
- [x] Notification icon: fix keyboard tab feedback and opening on enter: https://github.com/nextcloud/notifications/pull/146
- [x] Fix Upload in +Menu not launching when using keyboard

cc @nextcloud/accessibility :)

### CODE REVIEW

**Comment by jancborchardt** [comment]
Could use some help with JS here on how to do the trigger using enter so that it works for all .menutoggle elements and we don’t need to change the markup. @nextcloud/javascript or what do you think?

Similar for the **Unable to open file or folder with keyboard** #10008 issue where pressing enter on a folder/file opens the sidebar instead of opening the folder/file itself.

**Comment by jancborchardt** [comment]
This is now ready to review, together with the related Notifications pull request at https://github.com/nextcloud/notifications/pull/146

Please check @nextcloud/accessibility @nextcloud/designers :)

**Review by tyrylu — APPROVED** [review]
From the point of view of the markup and script changes, it looks alright and useful, so thank you.

**Review by skjnldsv — APPROVED** [review]

File: apps/files/js/newfilemenu.js [hunk 1]
```diff
@@ -235,6 +235,11 @@
 				items: this._menuItems
 			}));
 			OC.Util.scaleFixForIE8(this.$('.svg'));
+
+			// Trigger upload action also with keyboard navigation on enter
+			this.$el.find('[for="file_upload_start"]').on('keypress', function() {
+				$('#file_upload_start').trigger('click');
```
Comment (kevgathuku) [inline apps/files/js/newfilemenu.js]: Right now this is triggered for every keypress.
Ideally, only the `Enter` and `Spacebar` keys should activate the functionality.
A potential fix would be something like this:
```
this.$el.find('[for="file_upload_start"]').on("keypress", function(event) {
  if (event.key === " " || event.key === "Enter") {
    $("#file_upload_start").trigger("click");
  }
});
```

Comment (skjnldsv) [reply apps/files/js/newfilemenu.js]: @jancborchardt yup, we forgot this one! :)

**Comment by skjnldsv** [comment]
Fix #9994 too?

File: apps/files/js/newfilemenu.js (hunk 1 above)
Comment (jancborchardt) [reply apps/files/js/newfilemenu.js]: @kevgathuku ah right! Do you want to add a commit to the pull request? :)

Comment (kevgathuku) [reply apps/files/js/newfilemenu.js]: @jancborchardt sure. I'll add it

File: apps/files/js/newfilemenu.js [hunk 2]
```diff
@@ -237,8 +237,10 @@
 			OC.Util.scaleFixForIE8(this.$('.svg'));
 
 			// Trigger upload action also with keyboard navigation on enter
-			this.$el.find('[for="file_upload_start"]').on('keypress', function() {
-				$('#file_upload_start').trigger('click');
+			this.$el.find('[for="file_upload_start"]').on('keyup', function(event) {
+				if (event.key === " " || event.key === "Enter") {
```
Comment (skjnldsv) [inline apps/files/js/newfilemenu.js]: Thanks for your commit! :tada: 

Why not use the codeKey? 
Is there a special reason for allowing the " " ? :)

Comment (kevgathuku) [reply apps/files/js/newfilemenu.js]: Hi @skjnldsv 
Thanks 👍 

> Why not use the codeKey?

The `keyCode` is [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) and `event.key` is preferred instead.

> Is there a special reason for allowing the " " ? :)

For this instance, the behavior is more like a button, which is usually activated using either the `Spacebar` (" ") or `Enter` keys. I'm thinking it would be better to stick to this convention. 

Let me know whether this makes sense 😄

Comment (skjnldsv) [reply apps/files/js/newfilemenu.js]: Nice! Thanks for the tip, I did not know it was deprecated :)

Can you also move the edits we dit Jan and I from keyCode to key?

File: core/js/js.js [hunk 3]
```diff
@@ -684,10 +684,15 @@ var OCP = {},
 	registerMenu: function($toggle, $menuEl, toggle, headerMenu) {
 		var self = this;
 		$menuEl.addClass('menu');
-		$toggle.on('click.menu', function(event) {
+		$toggle.on('click.menu keypress.menu', function(event) {
 			// prevent the link event (append anchor to URL)
 			event.preventDefault();
 
+			// allow enter key as a trigger
+			if (event.keyCode && event.keyCode !== 13) {
```
Comment (skjnldsv) [inline core/js/js.js]: We should `key` instead

File: core/js/js.js [hunk 4]
```diff
@@ -1422,7 +1427,14 @@ function initCore() {
 	OC.registerMenu($('#expand'), $('#expanddiv'), false, true);
 
 	// toggle for menus
+	//$(document).on('mouseup.closemenus keyup', function(event) {
 	$(document).on('mouseup.closemenus', function(event) {
+
+		// allow enter as a trigger
+		// if (event.keyCode && event.keyCode !== 13) {
```
Comment (skjnldsv) [inline core/js/js.js]: We should `key` instead

File: apps/files/js/newfilemenu.js (hunk 2 above)
Comment (kevgathuku) [reply apps/files/js/newfilemenu.js]: Sure! I'll make the edits.

**Review by skjnldsv — APPROVED** [review]

**Comment by MorrisJobke** [comment]
CI is here: https://drone.nextcloud.com/nextcloud/server/9129

**Comment by MorrisJobke** [comment]
JSUnit tests fail 🙈

**Comment by MorrisJobke** [comment]
JSUnit tests fail:

https://drone.nextcloud.com/nextcloud/server/9129/247

**Comment by danxuliu** [comment]
I have amended the offending commit and fixed the JavaScript unit tests ;-)

**Review by MorrisJobke — APPROVED** [review]

**Comment by jancborchardt** [comment]
Thanks @skjnldsv @kevgathuku @danxuliu for the help! :) This is another great fix for better accessibility.
