### PR TITLE
Fix OCM implementation has wrong parameter names

### LINKED ISSUE #36340: [Bug]: OCM implementation has wrong parameter names
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

https://github.com/nextcloud/server/blob/master/apps/cloud_federation_api/lib/Controller/RequestHandlerController.php#L115-L116 contains `sharedBy` and `sharedByDisplayName`, but neither is documented in the OCM spec ([1.0](https://github.com/cs3org/OCM-API/blob/ac6c340250a55887d6e8ea2d88a8c621bfb1a3fd/spec.yaml#L233-L253) or [latest](https://github.com/cs3org/OCM-API/blob/develop/spec.yaml#L258-L275)). The spec contains `sender` and `senderDisplayName` so the variables names in the implementation are probably just wrong.

cc @schiessle 

### Steps to reproduce

-

### Expected behavior

Correct implementation of the spec

### Installation method

None

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
-
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by michielbdejong**
* Resolves: #36340

## Summary
Copy `sharedBy` and `sharedByDisplayName` fields to `sender` and `senderDisplayName` to allow non-Nextcloud implementations of Open Cloud Mesh to find this information when receiving a share from a nextcloud user.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by provokateurin — APPROVED** [review]
LGTM, but you need to change the commit message to follow https://www.conventionalcommits.org/en/v1.0.0/

**Review by joshtrichards — APPROVED** [review]
Thanks, @michielbdejong. Please clean-up the commit message and should be good.

File: lib/private/Federation/CloudFederationShare.php [hunk 1]
```diff
@@ -155,6 +157,7 @@ public function setOwnerDisplayName($ownerDisplayName) {
 	 */
 	public function setSharedBy($sharedBy) {
 		$this->share['sharedBy'] = $sharedBy;
+		$this->share['sender'] = $sharedBy;
```
Comment (nickvergessen) [inline lib/private/Federation/CloudFederationShare.php:160]: Is it a cloudId (Could be read like it should be from https://github.com/cs3org/OCM-API/blob/develop/spec.yaml#L526 ) or the user id?

Comment (michielbdejong) [reply lib/private/Federation/CloudFederationShare.php:160]: I think it's supposed to be the userId, although it can be any identifier the sending server chooses to use - including a random hash, or indeed a full cloudId.

**Comment by michielbdejong** [comment]
I added 'fix:' to the beginning of the message, but left the ', fixes #36340' at the end of the description, since it felt informative and I didn't find anything in https://www.conventionalcommits.org/en/v1.0.0/ about how to use closing keywords. But let me know if you want that removed or changed as well.
