### PR TITLE
fix(systemtags): Use literal strings for i18n in showSuccess

### LINKED ISSUE #50363: i18n: Incorrect string with incomplete placeholder from vue in Transifex
https://github.com/nextcloud/server/blame/4d61fd2e5a6ef61686e3606382e17dd8febb8e79/apps/systemtags/src/components/SystemTagsCreationControl.vue#L67

Image

### PR DESCRIPTION
**Pull request by nfebe**
Resolve : https://github.com/nextcloud/server/issues/50363

### CODE REVIEW

**Review by rakekniven — APPROVED** [review]

File: apps/systemtags/src/components/SystemTagsCreationControl.vue [hunk 1]
```diff
@@ -64,7 +64,11 @@ export default {
 		handleResponse({ isRestricted, status, errorMessage, error }) {
 			if (status === 'ok') {
 				this.systemTagsCreationRestrictedToAdmin = isRestricted
-				showSuccess(t('settings', `System tag creation is now ${isRestricted ? 'restricted to administrators' : 'allowed for everybody'}`))
+				showSuccess(
+					t('settings', isRestricted
+						? 'System tag creation is now restricted to administrators'
+					 : 'System tag creation is now allowed for everybody'),
+				)
```
Comment (susnux) [inline apps/systemtags/src/components/SystemTagsCreationControl.vue:71]: This does not work. It will not be extracted correctly.

```suggestion
				showSuccess(isRestricted
					? t('settings', 'System tag creation is now restricted to administrators')
					: t('settings', 'System tag creation is now allowed for everybody'),
				)
```

File: apps/systemtags/src/components/SystemTagsCreationControl.vue [hunk 2]
```diff
@@ -64,7 +64,11 @@ export default {
 		handleResponse({ isRestricted, status, errorMessage, error }) {
 			if (status === 'ok') {
 				this.systemTagsCreationRestrictedToAdmin = isRestricted
-				showSuccess(t('settings', `System tag creation is now ${isRestricted ? 'restricted to administrators' : 'allowed for everybody'}`))
+				showSuccess(
+					t('settings', isRestricted
+						? 'System tag creation is now restricted to administrators'
+					 : 'System tag creation is now allowed for everybody'),
```
Comment (Pytal) [inline apps/systemtags/src/components/SystemTagsCreationControl.vue]: I think this needs to be:
```js
isRestricted ? t('settings', 'System tag creation is now restricted to administrators') : t('settings', 'System tag creation is now allowed for everybody')
```
for parsing to work

Comment (Pytal) [reply apps/systemtags/src/components/SystemTagsCreationControl.vue]: Nevermind 🙈

**Review by Pytal — APPROVED** [review]

**Review by susnux — APPROVED** [review]

**Comment by nickvergessen** [comment]
Since the string was completely broken, we should have backported during the string freeze.
Translators now were asked to translaet:
```
System tag creation is now ${isRestricted ? 
```
