### PR TITLE
fix(files): Properly encode URLs when preparing ZIP download

### LINKED ISSUE #51617: [Bug]: Downloads of multiple files with "," in filename fails
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi, since NC 30, downloading multiple files where at least on file has a colon "," in it's name, fails. 

### Steps to reproduce

1. sctivate checkboxes in front of files where on file has a , in it's name
2.download
3.browser reports "Download.html" not found 

### Expected behavior

files should download as in versions before 30

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 31 to 32)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json
{
    "system": {
        "default_phone_region": "DE",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "31.0.2.1",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "loglevel": 2,
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "log_type": "file",
        "theme": "",
        "updater.release.channel": "stable",
        "mail_sendmailmode": "smtp",
        "maintenance_window_start": 1
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 4.0.0
  - admin_audit: 1.21.0
  - app_api: 5.0.2
  - bruteforcesettings: 4.0.0
  - calendar: 5.2.0
  - circles: 31.0.0
  - cloud_federation_api: 1.14.0
  - comments: 1.21.0
  - contacts: 7.0.4
  - contactsinteraction: 1.12.0
  - dav: 1.33.0
  - deck: 1.15.0
  - federatedfilesharing: 1.21.0
  - federation: 1.21.0
  - files: 2.3.1
  - files_downloadlimit: 4.0.0
  - files_external: 1.23.0
  - files_pdfviewer: 4.0.0
  - files_reminders: 1.4.0
  - files_sharing: 1.23.1
  - files_trashbin: 1.21.0
  - files_versions: 1.24.0
  - firstrunwizard: 4.0.0
  - logreader: 4.0.0
  - lookup_server_connector: 1.19.0
  - nextcloud_announcements: 3.0.0
  - notifications: 4.0.0
  - oauth2: 1.19.1
  - password_policy: 3.0.0
  - photos: 4.0.0-dev.1
  - privacy: 3.0.0
  - profile: 1.0.0
  - provisioning_api: 1.21.0
  - recommendations: 4.0.0
  - related_resources: 2.0.0
  - serverinfo: 3.0.0
  - settings: 1.14.0
  - sharebymail: 1.21.0
  - support: 3.0.0
  - survey_client: 3.0.0
  - systemtags: 1.21.1
  - text: 5.0.0
  - theming: 2.6.1
  - twofactor_backupcodes: 1.20.0
  - updatenotification: 1.21.0
  - user_status: 1.11.0
  - viewer: 4.0.0
  - weather_status: 1.11.0
  - webhook_listeners: 1.2.0
  - workflowengine: 2.13.0
Disabled:
  - dashboard: 7.11.0 (installed 7.0.0)
  - encryption: 2.19.0
  - files_mindmap: 0.0.33 (installed 0.0.33)
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - files_trackdownloads: 1.11.0 (installed 1.11.0)
  - groupfolders: 19.0.4 (installed 19.0.4)
  - mailnotifier: 0.0.3 (installed 0.0.3)
  - mindmaps: 0.1.0 (installed 0.1.0)
  - sharerenamer: 3.5.0 (installed 3.4.0)
  - spreed: 21.0.1 (installed 21.0.1)
  - suspicious_login: 9.0.1
  - twofactor_nextcloud_notification: 5.0.0
  - twofactor_totp: 13.0.0-dev.0
  - user_ldap: 1.22.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```json
No relevant logentries found?!
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by fabianzw**
* Resolves: #51617 

## Summary
Fixed two issues in downloadAction.ts that prevented users from downloading multiple files when one of the file names included a comma or a hash symbol.

1) downloadAction.ts:66: Changed decodeURI to decodeURIComponent
decodeURI does not decode characters that are not part of the URI syntax. For example, a file named "A,B.txt" was requested as "A%2CB.txt".

2) downloadAction.ts:58,61: Changed "new URL(nodes[0].source)" to "new URL(nodes[0].encodedSource)"
In .source, hash symbols are not escaped, which confuses the logic as url.pathname does not include the hash symbol and everything after it.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

Sorry for the second PR, I forgot the signoff message in the first..

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

File: apps/files/src/actions/downloadAction.ts [hunk 1]
```diff
@@ -55,15 +55,15 @@ const downloadNodes = function(nodes: Node[]) {
 			url.searchParams.append('accept', 'zip')
 		}
 	} else {
-		url = new URL(nodes[0].source)
+		url = new URL(nodes[0].encodedSource)
 		let base = url.pathname
 		for (const node of nodes.slice(1)) {
-			base = longestCommonPath(base, (new URL(node.source).pathname))
+			base = longestCommonPath(base, (new URL(node.encodedSource).pathname))
```
Comment (susnux) [inline apps/files/src/actions/downloadAction.ts:61]: Not sure about this path as the URL constructor should already encode the URL so this smells like double encoding. Will test tomorrow with some more examples.

**Review by susnux — APPROVED** [review]

**Comment by skjnldsv** [comment]
Not backportable for 29 & 30 because https://github.com/nextcloud/server/pull/48098 created too much differences :)
