### PR TITLE
fix(dav): do not require CSRF for safe and indempotent HTTP methods

### LINKED ISSUE #18856: CSRF is not skipped for HEAD requests
In the file [/apps/dav/lib/Connector/Sabre/Auth](https://github.com/nextcloud/server/blob/master/apps/dav/lib/Connector/Sabre/Auth.php) Line 173 (Function requiresCSRFCheck) we skip CSRF checks only for GET requests. Why not for HEAD requests?

I mean a HEAD request is a GET request without the BODY:

Can we add a the HEAD method here too? If yes I can create a pull request if you want.

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: https://github.com/nextcloud/server/issues/18856

## Summary
Safe methods (and idempotent) do not need CSRF protection - especially as HEAD is basically a GET without a body.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/dav/lib/Connector/Sabre/Auth.php [hunk 1]
```diff
@@ -118,8 +118,9 @@ public function check(RequestInterface $request, ResponseInterface $response) {
 	 * Checks whether a CSRF check is required on the request
 	 */
 	private function requiresCSRFCheck(): bool {
-		// GET requires no check at all
-		if ($this->request->getMethod() === 'GET') {
+		
+		$methodsWithoutCsrf = ['GET', 'HEAD', 'OPTIONS'];
```
Comment (provokateurin) [inline apps/dav/lib/Connector/Sabre/Auth.php:122]: A HEAD request is turned into a GET request by the web server, so PHP will never see any HEAD requests.

Comment (come-nc) [reply apps/dav/lib/Connector/Sabre/Auth.php:122]: Is that true for all webserver configurations?

**Review by come-nc — APPROVED** [review]

**Review by artonge — APPROVED** [review]
