### PR TITLE
fix(files): Do not fail on missing sidebar in files list

### LINKED ISSUE #3815: Files sometimes do not get opened immediately on internal links
### Steps to reproduce
1. Have an internal link like /f/1234
2. Open it in a browser (e.g. from clicking in an email)

### Expected behaviour
The file should open

### Actual behaviour
Sometimes the file doesn't open automatically and there is an error thrown. It seems happening more often with cleared browser cache.

Now the odd thing here is that the error is thrown before the viewer app is initialized, so there seems to be some kind of timing issue when trying to get the file actions for the requested file.

https://github.com/nextcloud/server/pull/45586 would help with the error but I cannot see how it would solve the file then just not opening up.

I have not managed to reproduce this locally on any of the versions,  but tech-preview is affected (currently on 29.0.0) and another instance on 28.0.6 (both should be upgraded 🙈 )

@susnux Do you have any idea on why the order in which the `handleOpenFile` and the viewer registrations would be executed might differ?

Screenshot 2024-07-09 at 10 05 21
Screenshot 2024-07-09 at 10 06 15

### PR DESCRIPTION
**Pull request by eszkadev**
When using richdocuments it was failing in case of shared links or when user with opened file did a wheel click on a refresh page. Then new tab appeared but instead opening the file it was doing nothing (showing the list of files) or downloading the file.

Make code more defensive. I found these logs while debugging:
```
OCA.Files.Settings initialized
Sidebar.js:19 OCA.Files.Sidebar initialized
ShareSearch.js:16 OCA.Sharing.ShareSearch initialized comments-app.js:15 OCA.Comments.View initialized
index.mjs:54 [ERROR] files: Error while opening sidebar Object log @ index.mjs:54
index.mjs:54 [ERROR] files: Error while opening sidebar Objectapp: "files"error: TypeError: window.OCA.Files.Sidebar.open is not a function
    at h.exec (http://nc/dist/files-main.js?v=106d16db-0:1:70123)
    at o.openSidebarForFile (http://nc/dist/files-main.js?v=106d16db-0:1:163422)
    at o.handleOpenQueries (http://nc/dist/files-main.js?v=106d16db-0:1:163167)
    at o.openDetails (http://nc/dist/files-main.js?v=106d16db-0:1:162349)
    at fn (http://nc/dist/core-common.js?v=106d16db-0:1:3942538)
    at e.run (http://nc/dist/core-common.js?v=106d16db-0:1:3946900)
    at sa (http://nc/dist/core-common.js?v=106d16db-0:1:3948728)
    at Array.<anonymous> (http://nc/dist/core-common.js?v=106d16db-0:1:3943585)
    at bn (http://nc/dist/core-common.js?v=106d16db-0:1:3942986)level: 2uid: "admin"[[Prototype]]: Object
log @ index.mjs:54
```
Possibly regression from
https://github.com/nextcloud/server/commit/e7001022c75b3a818356378bb53bbfe5129a10fe

Fixes https://github.com/nextcloud/richdocuments/issues/3815

### CODE REVIEW

File: apps/files/src/actions/sidebarAction.ts [hunk 1]
```diff
@@ -43,15 +43,15 @@ export const action = new FileAction({
 	async exec(node: Node, view: View, dir: string) {
 		try {
 			// If the sidebar is already open for the current file, do nothing
-			if (window.OCA.Files.Sidebar.file === node.path) {
+			if (window?.OCA?.Files?.Sidebar.file === node.path) {
```
Comment (susnux) [inline apps/files/src/actions/sidebarAction.ts]: `window` and `OCA` are always defined, so that is enough:


```suggestion
			if (window.OCA.Files?.Sidebar.file === node.path) {
```

**Review by skjnldsv — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

**Comment by eszkadev** [comment]
thank you very much for solving conflicts :)

**Comment by Kamilko16** [comment]
The problem still exists in 31.0.13
