### PR TITLE
fix(external_storage): fix settings save

### LINKED ISSUE #49829: [Bug]: Can't save global credentials in external storage
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi, 
A couple of weeks ago, there was a bug in Global Credentials ( https://github.com/nextcloud/server/issues/49349 ).
The temporary solution provided by @a-lys was working.
Now, after updating to Nextcloud 30.0.3 and 30.0.4, the Global Credentials can't be saved anymore.

The problem seems a bit different : when i input a new password, there is a input box, that ask for users's password to confirm the new password store in global credentials.
I tested and I checked my password : I'm sure it is the good one (the password is that is store in our OpenLDAP server).
Nextcloud says that the input password is wrong.

### Steps to reproduce

1. Log in to Nextcloud
2. Go to your Personnal parameters
3. Input a new password in Global Credentials aera
4. Save
5. Input your password to confirm

### Expected behavior

The input box that check your password, should verify your password.

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 28.0.1 to 28.0.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [x] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "30.0.4.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "maxZipInputSize": 1073741824,
        "allowZipDownload": true,
        "theme": "",
        "overwrite.cli.url": "https:\/\/cloud.iut-orsay.fr",
        "htaccess.RewriteBase": "\/",
        "maintenance": false,
        "maintenance_window_start": 2,
        "default_language": "fr",
        "default_phone_region": "FR",
        "defaultapp": "files,dashboard",
        "log_type": "owncloud",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 0,
        "enable_previews": false,
        "trusted_domains": [
            "cloud.iut-orsay.fr"
        ],
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "dbindex": 0,
            "timeout": 0
        },
        "onlyoffice": {
            "jwt_secret": "***REMOVED SENSITIVE VALUE***",
            "jwt_header": "AuthorizationJwt"
        },
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "ldapUserCleanupInterval": "60",
        "updater.release.channel": "stable",
        "mysql.utf8mb4": true,
        "mail_sendmailmode": "smtp",
        "app_install_overwrite": [
            "printer"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 3.0.0
  - admin_audit: 1.20.0
  - announcementcenter: 7.0.1
  - app_api: 4.0.3
  - bruteforcesettings: 3.0.0
  - circles: 30.0.0
  - cloud_federation_api: 1.13.0
  - comments: 1.20.1
  - contactsinteraction: 1.11.0
  - dashboard: 7.10.0
  - dav: 1.31.1
  - drawio: 3.0.3
  - federatedfilesharing: 1.20.0
  - federation: 1.20.0
  - files: 2.2.0
  - files_downloadlimit: 3.0.0
  - files_external: 1.22.0
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - firstrunwizard: 3.0.0
  - groupfolders: 18.0.7
  - lookup_server_connector: 1.18.0
  - nextcloud_announcements: 2.0.0
  - notifications: 3.0.0
  - oauth2: 1.18.1
  - onlyoffice: 9.5.0
  - password_policy: 2.0.0
  - photos: 3.0.2
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - recommendations: 3.0.0
  - related_resources: 1.5.0
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - support: 2.0.0
  - survey_client: 2.0.0
  - suspicious_login: 8.0.0
  - systemtags: 1.20.0
  - tasks: 0.16.1
  - text: 4.1.0
  - theming: 2.5.0
  - twofactor_backupcodes: 1.19.0
  - twofactor_totp: 12.0.0-dev
  - updatenotification: 1.20.0
  - user_ldap: 1.21.0
  - user_status: 1.10.0
  - viewer: 3.0.0
  - weather_status: 1.10.0
  - webhook_listeners: 1.1.0-dev
  - workflowengine: 2.12.0
Disabled:
  - encryption: 2.18.0
  - logreader: 3.0.0 (installed 2.14.0)
  - twofactor_nextcloud_notification: 4.0.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```json
No error have been found in logs.
```

### Additional info

Image

Here, you'll find the browser console output : 

Image

Image

### PR DESCRIPTION
**Pull request by skjnldsv**
- Returning boolean on a controller just output said boolean as plain text in the reponse
- Encoding JSON before sending the request with axios will result in double encoding and failure to be read by the backend
- Added error handling from the backend too

Fix https://github.com/nextcloud/server/issues/49829
Followup from https://github.com/nextcloud/server/pull/50910

Regression from
- https://github.com/nextcloud/server/pull/48788
- https://github.com/nextcloud/server/pull/49493

### CODE REVIEW

File: apps/files_external/lib/Controller/AjaxController.php [hunk 1]
```diff
@@ -73,10 +77,13 @@ public function getSshKeys($keyLength = 1024) {
 	 */
 	#[NoAdminRequired]
 	#[PasswordConfirmationRequired(strict: true)]
-	public function saveGlobalCredentials($uid, $user, $password) {
+	public function saveGlobalCredentials($uid, $user, $password): JSONResponse {
```
Comment (skjnldsv) [inline apps/files_external/lib/Controller/AjaxController.php:80]: I'm questioning the relevancy of this file.
1. I can't see where the `getSshKeys` seems to be used anywhere else
2. We do provide the `$uid` from the front, as if there was a place where an admin could update another Account's credentials. But I fail to see where this is even implemented.

File: apps/files_external/lib/Controller/AjaxController.php [hunk 2]
```diff
@@ -56,27 +59,30 @@ private function generateSshKeys($keyLength) {
...
-		return new JSONResponse(
-			['data' => [
+		return new JSONResponse([
+			'data' => [
 				'private_key' => $key['privatekey'],
 				'public_key' => $key['publickey']
 			],
-				'status' => 'success'
-			]);
+			'status' => 'success'
```
Comment (susnux) [inline apps/files_external/lib/Controller/AjaxController.php:67]: If reformatting then diff friendly?

```suggestion
			'status' => 'success',
```

File: apps/files_external/src/settings.js [hunk 3]
```diff
@@ -4,9 +4,11 @@
  * SPDX-License-Identifier: AGPL-3.0-or-later
  */
 
-import axios from '@nextcloud/axios'
-import { t } from '@nextcloud/l10n'
 import { addPasswordConfirmationInterceptors, PwdConfirmationMode } from '@nextcloud/password-confirmation'
+import { generateUrl } from '@nextcloud/router'
+import { showError } from '@nextcloud/dialogs'
+import { t } from '@nextcloud/l10n'
```
Comment (susnux) [inline apps/files_external/src/settings.js:10]:
```suggestion
import { showError } from '@nextcloud/dialogs'
import { t } from '@nextcloud/l10n'
import { addPasswordConfirmationInterceptors, PwdConfirmationMode } from '@nextcloud/password-confirmation'
import { generateUrl } from '@nextcloud/router'
```

**Review by susnux — APPROVED** [review]
Makes sense

File: apps/files_external/lib/Controller/AjaxController.php (hunk 1 above)
Comment (kesselb) [reply apps/files_external/lib/Controller/AjaxController.php:79]: Hi,



`getSshKeys` is the backend code for "Generate keys". The button "Generate keys" is missing since Nextcloud 25[^1]. It seems that "api" for to hook into the external storages view and render own buttons or even to xhr requests was removed. 

Is it necessary to bring the button back? No. It's also possible to generate the keys locally and enter them in Nextcloud. 

If you decide to remove getSshKeys, please close the reference issue as won't fix and log an issue at documentation to rework that part of our documentation[^2]  ;)


[^1]: https://github.com/nextcloud/server/issues/35829.
[^2]: https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/external_storage/auth_mechanisms.html#public-key-mechanisms

File: apps/files_external/src/settings.js (hunk 3 above)
Comment (skjnldsv) [reply apps/files_external/src/settings.js:10]: Ahah, you sort by lib import?
I sort by alphabetical import :grin:

File: apps/files_external/lib/Controller/AjaxController.php (hunk 1 above)
Comment (skjnldsv) [reply apps/files_external/lib/Controller/AjaxController.php:79]: Wow :exploding_head:

**Review by AndyScherzinger — APPROVED** [review]
🙏

File: apps/files_external/src/settings.js (hunk 3 above)
Comment (susnux) [reply apps/files_external/src/settings.js:10]: Alphabetically `@nextcloud/dialogs` comes before `@nextcloud/router` or what you mean?

**Comment by nsemov** [comment]
I'm running 31.0.0 and noticed that when saving global credentials the browser says it submits payload:
{"uid":"","user":"asdasd","password":"asdasdasd"}

But by the time saveGlobalCredentials is called in AjaxController, $uid is NULL rather than an empty string, so the $uid === '' comparison fails and permission to set the credentials is denied. 

Unfortunately I'm too basic to see if all these changes that were implemented will correctly pass an empty string to the saveGlobalCredentials rather than a NULL.

**Comment by skjnldsv** [comment]
> Error: Failed to create pull request: Validation Failed: {"resource":"PullRequest","field":"head","code":"invalid"}

That's a new one :thinking:
