### PR TITLE
Apptoken v3: imrpove token handling on external password change

### LINKED ISSUE #11043: Do not delete invalid AppToken
When an apptoken is still valid in the DB but the password validation fails we should mark it as such. That way we can on next (successful) login update all the tokens that are marked as invalid.

For https://github.com/orgs/nextcloud/projects/22

This should make changing the password in LDAP possible for example.

TODO:
- [x] Add field to mark apppassword as outdated to DB
- [x] If the password fails to verify mark the apptoken as outdated (do not delete it)
- [x] On successfull login update outdated tokens

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #11043 

Easiest to review per commit

1. Add the new column
2. Mark the token as invalid if needed
3. Update the tokens on web login

Todo:
- [x] Testing
- [x] Tests

### CODE REVIEW

File: lib/private/Authentication/Token/DefaultTokenProvider.php [hunk 1]
```diff
@@ -338,4 +338,10 @@ private function decryptPassword(string $password, string $token): string {
 		}
 	}
 
+	public function markPasswordInvalid(IToken $token, string $tokenId) {
+		//No need to mark as invalid. We just invalide default tokens
+		$this->invalidateToken($tokenId);
```
Comment (ChristophWurst) [inline lib/private/Authentication/Token/DefaultTokenProvider.php]: You don't check the concrete class here …

File: lib/private/Authentication/Token/PublicKeyTokenProvider.php [hunk 2]
```diff
@@ -317,4 +317,16 @@ private function newToken(string $token,
 
 		return $dbToken;
 	}
+
+	public function markPasswordInvalid(IToken $token, string $tokenId) {
+		if (!($token instanceof PublicKeyToken)) {
```
Comment (ChristophWurst) [inline lib/private/Authentication/Token/PublicKeyTokenProvider.php]: … but you do here? :thinking:

File: lib/private/Authentication/Token/PublicKeyTokenProvider.php [hunk 3]
```diff
@@ -317,4 +317,16 @@ private function newToken(string $token,
...
+			throw new InvalidTokenException();
+		}
+
+		$token->setPasswordInvalid(true);
+		$this->mapper->update($token);
+		return $token;
```
Comment (ChristophWurst) [inline lib/private/Authentication/Token/PublicKeyTokenProvider.php]: return value is neither in the interface nor does the manager pass it on

File: lib/private/User/Session.php [hunk 4]
```diff
@@ -694,12 +694,18 @@ private function checkTokenCredentials(IToken $dbToken, $token) {
 			return true;
 		}
 
-		if ($this->manager->checkPassword($dbToken->getLoginName(), $pwd) === false
-			|| (!is_null($this->activeUser) && !$this->activeUser->isEnabled())) {
+		// Invalidate tken if the user is no longer active
```
Comment (ChristophWurst) [inline lib/private/User/Session.php]: typo: "tken" -> "token"

File: lib/private/User/Session.php [hunk 5]
```diff
@@ -694,12 +694,18 @@ private function checkTokenCredentials(IToken $dbToken, $token) {
...
+		if (!is_null($this->activeUser) && !$this->activeUser->isEnabled()) {
 			$this->tokenProvider->invalidateToken($token);
-			// Password has changed or user was disabled -> log user out
 			return false;
 		}
+
+		// If the token password is no longer valid mark it as such
+		if ($this->manager->checkPassword($dbToken->getLoginName(), $pwd) === false) {
+			$this->tokenProvider->markPasswordInvalid($dbToken, $token);
+			return false;
```
Comment (ChristophWurst) [inline lib/private/User/Session.php]: (maybe add this as comment here) the user will be logged out after this `false` return value, right? That's what I get form the comments above.

File: lib/private/User/Session.php [hunk 6]
```diff
@@ -922,5 +922,9 @@ public function updateSessionTokenPassword($password) {
 		}
 	}
 
+	public function updateTokens(string $uid, string $password) {
```
Comment (ChristophWurst) [inline lib/private/User/Session.php]: At some point we should discuss a refactoring of this user session class. This will soon be unmaintainable due to its complexity :see_no_evil:

**Review by ChristophWurst — COMMENTED** [review]
Looks good so far! :rocket:

File: lib/private/Authentication/Token/DefaultTokenProvider.php (hunk 1 above)
Comment (rullzer) [reply lib/private/Authentication/Token/DefaultTokenProvider.php]: I should be consitent yes. However I do check it in the PublicKeyTokenProvider since we use a function that is only available on this function always works. Anyway let me be consistent ;)

**Comment by rullzer** [comment]
@blizzz could you give this a test with LDAP?

1. Create a user
2. Login
3. Create an app password
4. see the the apppassword works `curl -u <USER>:<APPPASS> <server>/remote.php/dav -X PROPFIND`
5. Change the password in LDAP
6. see that the apppassword fails (might need a timeout of 5min to kick in)
7. Relogin on the web
8. See that the apppassword works again.

**Comment by blizzz** [comment]
> @blizzz could you give this a test with LDAP?

Will do today.

**Comment by blizzz** [comment]
@rullzer tested, workz!

**Comment by rullzer** [comment]
Ready for review :)

File: lib/private/Authentication/Token/PublicKeyTokenMapper.php [hunk 7]
```diff
@@ -169,4 +169,19 @@ public function deleteTempToken(PublicKeyToken $except) {
 
 		$qb->execute();
 	}
+
+	public function hasExpiredTokens(string $uid): bool {
+		$qb = $this->db->getQueryBuilder();
+		$qb->select('*')
+			->from('authtoken')
+			->where($qb->expr()->eq('uid', $qb->createNamedParameter($uid)))
+			->andWhere($qb->expr()->eq('password_invalid', $qb->createNamedParameter(true)))
```
Comment (ChristophWurst) [inline lib/private/Authentication/Token/PublicKeyTokenMapper.php]: better specify the type (bool) here

**Review by ChristophWurst — APPROVED** [review]
:+1:

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍
