### PR TITLE
fix(SetupChecks): Don't test caches using binary data

### LINKED ISSUE #50110: [Bug]: 29.0.11 RC1 & 30.0.5 RC1: Security & setup warnings: Failed to write and read a value from distributed cache
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Got this message after upgrade from 29.0.10 to 29.0.11 RC1. Nothing else changed.
Distributed cache is Redis. I think that's a false positive, no entries in the logs.
Any comments?

### Steps to reproduce

1. Upgrade nextcloud which uses redis as ditributed cache from 29.0.10  to 29.0.11 RC1.
2. 

### Expected behavior

There should be no error in the Security & setup warnings.

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "testcloud.emrich-ebersheim.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/testcloud.emrich-ebersheim.de\/",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "29.0.11.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "filelocking.enabled": true,
        "appstore.experimental.enabled": "true",
        "updater.release.channel": "stable",
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "enable_previews": true,
        "preview_max_x": 1024,
        "preview_max_y": 1024,
        "preview_max_scale_factor": 8,
        "trashbin_retention_obligation": "auto",
        "maintenance": false,
        "default_language": "de",
        "default_phone_region": "DE",
        "theme": "",
        "loglevel": 2,
        "mysql.utf8mb4": true,
        "app_install_overwrite": [
            "files_readmemd",
            "co2clock",
            "data_request",
            "carnet",
            "breezedark"
        ],
        "has_rebuilt_cache": true,
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance_window_start": 2
    }
}
```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by solracsf**
## Summary

- Fix https://github.com/nextcloud/server/issues/50110 _(reproduced on my side too using Redis)_.
This shoud be enough for this simple `set` & `get` test, so no serialization/unserialization of data is involved.
- Regression from #49588

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/settings/lib/SetupChecks/MemcacheConfigured.php [hunk 1]
```diff
@@ -60,7 +60,7 @@ public function run(): SetupResult {
 		}
 
 		if ($this->cacheFactory->isLocalCacheAvailable()) {
-			$random = random_bytes(64);
+			$random = uniqid();
```
Comment (nickvergessen) [inline apps/settings/lib/SetupChecks/MemcacheConfigured.php:63]: this yields a security warning in IDEs, so let's instead bin2hex it

**Review by nickvergessen — APPROVED** [review]

**Review by provokateurin — APPROVED** [review]

**Review by Altahrim — APPROVED** [review]
