### PR TITLE
Make it possible to rename app passwords

### LINKED ISSUE #6717: App password descriptions should be editable
## Expected behavior
It should be possible to change the description of an app password.

## Current behavior
It isn't currently possible to change the description of an app password.

### Steps to reproduce
1. Open the personal settings and select 'security'.
2. Try to change the description of an app password.

#### Server Configuration
OS: Linux 3.16.47
Web server: Apache2 2.4.26
Database: MariaDB 10.0.32
PHP version: 5.6.30
Nextcloud version: 12.0.3

#### Client Configuration
Browser: Mozilla Firefox 56.0
Operating system: Windows 7

### PR DESCRIPTION
**Pull request by kesselb**
Close #6717 
peek 2019-01-20 21-02

Not sure if its save to use https://caniuse.com/#feat=keyboardevent-key here.

### CODE REVIEW

File: settings/Controller/AuthSettingsController.php [hunk 1]
```diff
@@ -203,6 +206,11 @@ public function update($id, array $scope) {
 		$token->setScope([
 			'filesystem' => $scope['filesystem']
 		]);
+
+		if ($token instanceof DefaultToken || $token instanceof PublicKeyToken) {
```
Comment (ChristophWurst) [inline settings/Controller/AuthSettingsController.php]: May I suggest to introduce a new interface for this, like a `INamedToken extends IToken` that has a getter and setter for the name? That would make the code easier to follow and makes the API more clear :+1: 

Of course this can be an *internal* interface in `OC` as it's not used outside of the server.

**Review by ChristophWurst — DISMISSED** [review]
Just a nitpick regarding API design. Looks great otherwise! Thanks for adding this feature!

**Review by jancborchardt — DISMISSED** [review]
Very nice work! :+1: Only a nitpick from me too: Could you modify it so the height of the row doesn’t change in rename mode? :)

**Comment by danielkesselberg** [comment]
peek 2019-02-02 14-51

**Comment by danielkesselberg** [comment]
https://drone.nextcloud.com/nextcloud/server/15458/168 :boom: 

> Argument 3 passed to OC\\Settings\\Controller\\AuthSettingsController::update() must be of the type string

There are two ways to fix this:

1. Adjust test and add name parameter to request
2. Make name optional

Are desktop or mobile using this endpoints? If so we should make name optional.

**Comment by danielkesselberg** [comment]
Integration-Auth is happy again. Time for another review ;-)

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
@danielkesselberg as a followup could you also add activities for renaming a token?

**Comment by rullzer** [comment]
Ah and I just forgot. Renaming should probably also require a password confirmation...
