### PR TITLE
fix(sharing): Adapt share suggestions to match trusted servers configs

### LINKED ISSUE #54511: [Bug]: new setting `show_federated_shares_to_trusted_servers_as_internal` returns options for federated shares in the internal section when searching for an email
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

**Context:**
- federated setup (at least two instances)
- instances trust each other, and exchange their address book

As shown below, with the parameter `show_federated_shares_to_trusted_servers_as_internal` set to `true`, federated cloudId is possible in the External Share search input.
Image

However, when I type an email in the Internal share section input to find the user with that email, I am returned with: 
- one option for a federeted user,
- one for a federated group,
- one for the user matching the email

Image

The options for `federated user` and `federated group` are unexpected.

### Steps to reproduce

1. Have two nextcloud instances that trust each other and share their address book. Alice is on instance A, Bob on instance B.
2. Run `php occ config:app:set files_sharing show_federated_shares_to_trusted_servers_as_internal --value true --type boolean`
3. With Alice on instance A, input Bob's email address in the Internal Share field input.

### Expected behavior

Only Bob's account from the synced address books should show up.

Image

### Nextcloud Server version

29

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

Related PR: https://github.com/nextcloud/server/pull/53661

### PR DESCRIPTION
**Pull request by nfebe**
When `show_federated_shares_to_trusted_servers_as_internal` is enabled but `show_federated_shares_as_internal` is not, filter federated share suggestions to only include trusted servers. Previously, searching for an email address would suggest non-trusted federated servers.

Resolved: #54511

### CODE REVIEW

File: lib/private/Collaboration/Collaborators/RemotePlugin.php [hunk 1]
```diff
@@ -27,11 +30,45 @@ public function __construct(
 		private IConfig $config,
 		private IUserManager $userManager,
 		IUserSession $userSession,
+		private ?IAppConfig $appConfig = null,
+		private ?TrustedServers $trustedServers = null,
```
Comment (susnux) [inline lib/private/Collaboration/Collaborators/RemotePlugin.php]: How can those ever be null? App config is always available thus it should be able to always inject here

File: lib/private/Collaboration/Collaborators/RemotePlugin.php [hunk 2]
```diff
@@ -27,11 +30,45 @@ public function __construct(
...
 
+	private function shouldOnlyShowTrustedServers(): bool {
+		if ($this->appConfig === null) {
+			return false;
+		}
+
+		$showFederatedToTrustedAsInternal = $this->appConfig->getValueBool(
+			'files_sharing',
+			ConfigLexicon::SHOW_FEDERATED_TO_TRUSTED_AS_INTERNAL,
+			false
```
Comment (susnux) [inline lib/private/Collaboration/Collaborators/RemotePlugin.php]: The default is already set by the config lexicon

```suggestion
```

File: lib/private/Collaboration/Collaborators/RemotePlugin.php [hunk 3]
```diff
@@ -27,11 +30,45 @@ public function __construct(
...
+		private ?TrustedServers $trustedServers = null,
 	) {
 		$this->userId = $userSession->getUser()?->getUID() ?? '';
 		$this->shareeEnumeration = $this->config->getAppValue('core', 'shareapi_allow_share_dialog_user_enumeration', 'yes') === 'yes';
 	}
 
+	private function shouldOnlyShowTrustedServers(): bool {
+		if ($this->appConfig === null) {
+			return false;
+		}
```
Comment (susnux) [inline lib/private/Collaboration/Collaborators/RemotePlugin.php]: How could this be null? (see above)

File: lib/private/Collaboration/Collaborators/RemotePlugin.php [hunk 4]
```diff
@@ -27,11 +30,45 @@ public function __construct(
...
+
+		$showFederatedToTrustedAsInternal = $this->appConfig->getValueBool(
+			'files_sharing',
+			ConfigLexicon::SHOW_FEDERATED_TO_TRUSTED_AS_INTERNAL,
+			false
+		);
+		$showFederatedAsInternal = $this->appConfig->getValueBool(
+			'files_sharing',
+			ConfigLexicon::SHOW_FEDERATED_AS_INTERNAL,
+			false
```
Comment (susnux) [inline lib/private/Collaboration/Collaborators/RemotePlugin.php]: should come from config lexicon

```suggestion
```

File: lib/private/Collaboration/Collaborators/RemotePlugin.php [hunk 5]
```diff
@@ -27,11 +30,45 @@ public function __construct(
...
+		);
+
+		return $showFederatedToTrustedAsInternal && !$showFederatedAsInternal;
+	}
+
+	private function isServerTrusted(string $serverUrl): bool {
+		if ($this->trustedServers === null) {
+			return true;
+		}
```
Comment (susnux) [inline lib/private/Collaboration/Collaborators/RemotePlugin.php]: Is there a case where injection could fail?

File: lib/private/Collaboration/Collaborators/RemotePlugin.php [hunk 6]
```diff
@@ -27,11 +30,45 @@ public function __construct(
...
+
+		$normalizedUrl = $serverUrl;
+		if (!str_contains($normalizedUrl, '://')) {
+			$normalizedUrl = 'https://' . $normalizedUrl;
+		}
```
Comment (susnux) [inline lib/private/Collaboration/Collaborators/RemotePlugin.php]: This is already done by the `TrustedServers` class in `isTrustedServer`

File: lib/private/Collaboration/Collaborators/RemotePlugin.php [hunk 7]
```diff
@@ -120,24 +161,25 @@ public function search($search, $limit, $offset, ISearchResult $searchResult): b
...
+							'label' => $remoteUser . " ($serverUrl)",
+							'uuid' => $remoteUser,
+							'name' => $remoteUser,
+							'value' => [
+								'shareType' => IShare::TYPE_REMOTE,
+								'shareWith' => $search,
+								'server' => $serverUrl,
+							],
+						];
+					}
```
Comment (susnux) [inline lib/private/Collaboration/Collaborators/RemotePlugin.php]: Isnt this removing all possible remote shares from suggestions? Meaning it will also no longer be listed in "external shares" section?
That would be not the intended behavior then, as also with this config set remote shares should still be possible in the external section

**Review by susnux — COMMENTED** [review]
I do not fully understand how this is possible only on backend side.
Because with "show trusted servers as internal" the search request from the frontend is basically the same, both "internal shares" and "external shares" will search for remote type.

The difference is only that with "show trusted servers as internal" that only trusted servers should be shown in the "internal share" results, while all other remotes should still be listed in "external shares" results

**Comment by maximelehericy** [comment]
Summary of the experiments:

  | Nextcloud vanilla | Nextcloud with flag to TRUE | Nextcloud with PR55080 			  			 			and  			 			  			 			 flag to TRUE | Nextcloud with PR 55080 modified 			  			 			and flag to TRUE
-- | -- | -- | -- | --
Match on email search | works | works | Do not work | Works
Display shares to users from lookup server (and trusted servers) 			in the internal share section | Do not work | works | works | Works
No federated cloud ID proposition in the search results upon email 			search | works | Do not work | works | Works

Conclusion: Fon's last modification has the correct behavior :rocket: 

Searching for an email:
- returns only a user matching that email, 
- do not return a potential existing federated cloud id
- creating the share to an account from the lookup server shows it in the Internal section


NB: the mentionned flag is `show_federated_shares_to_trusted_servers_as_internal`

File: tests/lib/Collaboration/Collaborators/RemotePluginTest.php [hunk 8]
```diff
@@ -36,6 +38,12 @@ class RemotePluginTest extends TestCase {
 	/** @var ICloudIdManager|\PHPUnit\Framework\MockObject\MockObject */
 	protected $cloudIdManager;
 
+	/** @var IAppConfig|\PHPUnit\Framework\MockObject\MockObject */
+	protected $appConfig;
+
+	/** @var TrustedServers|\PHPUnit\Framework\MockObject\MockObject */
+	protected $trustedServers;
```
Comment (artonge) [inline tests/lib/Collaboration/Collaborators/RemotePluginTest.php]:
```suggestion
	protected IAppConfig&MockObject $appConfig;
	protected TrustedServer&MockObject $trustedServers;
```

File: apps/files_sharing/src/components/SharingInput.vue [hunk 9]
```diff
@@ -457,6 +460,28 @@ export default {
...
+				return true
+			}
+
+			if (this.config.showFederatedSharesToTrustedServersAsInternal) {
+				return result.value.isTrustedServer || false
+			}
+
+			return true
+		},
+
```
Comment (artonge) [inline apps/files_sharing/src/components/SharingInput.vue]: Feels more direct.

```suggestion
			const isRemoteEntity = result.value.shareType === ShareType.Remote || result.value.shareType === ShareType.RemoteGroup

			if (isRemoteEntity && this.config.showFederatedSharesToTrustedServersAsInternal) {
				return result.value.isTrustedServer === true
			}

			return true
		},
```

File: lib/private/Collaboration/Collaborators/RemotePlugin.php [hunk 10]
```diff
@@ -82,7 +84,17 @@ public function search($search, $limit, $offset, ISearchResult $searchResult): b
...
+					if (isset($contact['EMAIL'])) {
+						$emails = is_array($contact['EMAIL']) ? $contact['EMAIL'] : [$contact['EMAIL']];
+						foreach ($emails as $email) {
+							if (is_string($email) && strtolower($email) === $lowerSearch) {
+								$emailMatch = true;
+								break;
+							}
+						}
+					}
+					if (strtolower($contact['FN']) === $lowerSearch || strtolower($cloudId) === $lowerSearch || $emailMatch) {
```
Comment (come-nc) [inline lib/private/Collaboration/Collaborators/RemotePlugin.php]:
```suggestion
					if ($emailMatch || strtolower($contact['FN']) === $lowerSearch || strtolower($cloudId) === $lowerSearch) {
```
You should put the bool first to avoid doing unnecessary comparisons.

File: tests/lib/Collaboration/Collaborators/RemotePluginTest.php [hunk 11]
```diff
@@ -36,6 +39,9 @@ class RemotePluginTest extends TestCase {
 	/** @var ICloudIdManager|\PHPUnit\Framework\MockObject\MockObject */
 	protected $cloudIdManager;
 
+	protected IAppConfig|MockObject $appConfig;
+	protected ICloudIdManager|MockObject $trustedServers;
```
Comment (artonge) [inline tests/lib/Collaboration/Collaborators/RemotePluginTest.php:43]:
```suggestion
	protected IAppConfig&MockObject $appConfig;
	protected ICloudIdManager&MockObject $trustedServers;
```

**Review by artonge — APPROVED** [review]
Beside the typing error, looks good

**Review by come-nc — APPROVED** [review]

File: lib/private/Collaboration/Collaborators/RemotePlugin.php [hunk 12]
```diff
@@ -27,17 +29,20 @@ public function __construct(
 		private IConfig $config,
 		private IUserManager $userManager,
 		IUserSession $userSession,
+		private IAppConfig $appConfig,
+		private TrustedServers $trustedServers,
```
Comment (nickvergessen) [inline lib/private/Collaboration/Collaborators/RemotePlugin.php:33]: This app is not (and must not be) always enabled, so server can not use it like this, as it results in:
```
  "version": "33.0.0.1",
  "exception": {
    "Exception": "OCP\\AppFramework\\QueryException",
    "Message": "Could not resolve OCA\\Federation\\TrustedServers! Class \"OCA\\Federation\\TrustedServers\" does not exist",
    "Code": 0,
    "Trace": [
      {
        "function": "OC\\AppFramework\\Utility\\{closure}",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
```

Comment (nfebe) [reply lib/private/Collaboration/Collaborators/RemotePlugin.php:33]: https://github.com/nextcloud/server/pull/55893
