### PR TITLE
Always set displayname and display-name for user data

### LINKED ISSUE #36539: [Bug]: provisioning_api current user display name field
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

https://github.com/nextcloud/server/commit/3e6c40eeb4408f3f52bdabad5ae876dc0e5581ff#diff-388d86396b3a70ff465e035b0db5d78bce90716631ab322d00425fbb317042ebR214 has a hack that sets the `display-name` and removes the `displayname` field. It seems like this was done to match an older API.
Ideally I'd like to drop this in order to make the API output the same regardless of requesting the current user or any other user, we should probably just set both fields for all APIs to make it easier for clients, because otherwise they have to switch between these different fields.

### Steps to reproduce

/

### Expected behavior

Only the same one field set for all APIs or both fields set for all APIs.

### Installation method

None

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
/
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by provokateurin**
* Resolves: https://github.com/nextcloud/server/issues/36539

## Summary

Always set both fields to make the returned data the same regardless of the endpoint.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Needs a doc update at https://docs.nextcloud.com/server/latest/developer_manual/client_apis/OCS/ocs-api-overview.html#user-metadata

**Review by ShGKme — APPROVED** [review]
Tested on my server, works as expected 🐸

**Comment by julien-nc** [comment]
Drone failures are unrelated.

**Comment by nickvergessen** [comment]
grafik

**Comment by nickvergessen** [comment]
Drone failures ARE TOTALLY related. Please fix asap to restore green CI

File: lib/public/Accounts/IAccountManager.php [hunk 1]
```diff
@@ -106,6 +107,7 @@ interface IAccountManager {
 
 	public const PROPERTY_AVATAR = 'avatar';
 	public const PROPERTY_DISPLAYNAME = 'displayname';
+	public const PROPERTY_DISPLAYNAME_LEGACY = 'display-name';
```
Comment (nickvergessen) [inline lib/public/Accounts/IAccountManager.php:110]: Please document in https://github.com/nextcloud/server/issues/37039

Comment (provokateurin) [reply lib/public/Accounts/IAccountManager.php:110]: It's a non-breaking backwards compatible change, but it should still be documented?

Comment (provokateurin) [reply lib/public/Accounts/IAccountManager.php:110]: Can you tell me how I should write it down? I'm not sure exactly what I should write

Comment (nickvergessen) [reply lib/public/Accounts/IAccountManager.php:110]: In the *Backend* section just write a new bullet point:

> * `OCP\Accounts\IAccounManager::PROPERTY_DISPLAYNAME_LEGACY` was added to be used for …


And then leave a comment with your changes, so that people that are subscribed to the ticket know that the list was modified.

**Comment by DaphneMuller** [comment]
Hello!
Thank you for your work on this! I noticed that your PR still has the label 'documentation'. I'm not sure if you already had a look at the documentation for your PR, but at Nextcloud we strive to document changes that affect other app developers or other admins before the release takes place, and I'm pinging you with the hope to get this done. 

Are you familiar with our documentation process already? 
Changes that affect app developers should be documented here:
https://docs.nextcloud.com/server/27/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_27.html

Changes that affect administrators should be documented here:
https://docs.nextcloud.com/server/latest/admin_manual/release_notes/upgrade_to_27.html

While I understand sometimes it's handy to merge fast to get your changes in, it would be great if next time you could try to add the documentation before merging. You can find more information on that here:
https://docs.nextcloud.com/server/27/developer_manual/prologue/compatibility_app_ecosystem.html#documentation-procedures-of-changes-that-affect-app-developers

If all your documentation efforts are done, please remove the label 'documentation' and check the checkbox in your opening note and I'll stop bugging you :) 

Many thanks in advance and thanks again for your work!
