### PR TITLE
[stable27] Use table prefix in metadata migration

### LINKED ISSUE #43966: [Bug]: "There is no table with name 'nextcloud.oc_file_metadata' in the schema" during "occ: maintenance:repair" (seen first on 27.1.7.2 update)
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

`occ maintenance:repair` triggers an error. Not sure if there are any negative side effects of this, as this happened during a update. Also happens when running the occ command manually, so it's reproducable. Introduced (for me) with 27.1.7.2 update.

Likely because the occ command still checks hardcoded for the “oc” prefix… which fails if that prefix has been changed, like it is in my case: `nextcloud.nc_file_metadata` is the correct, existing table.

### Steps to reproduce

1. Rename "nextcloud.oc_file_metadata" to e. g. "nextcloud.nc_file_metadata"
2. Run "occ maintenance:repair"
3. Check NC log

### Expected behavior

NC server checks for the existence based on any prefix naming convention, not the legacy hardcoded "oc" one. OwnCloud times are a real thing from the past for many many years... time to adopt to that reality code-wise maybe :-)

### Installation method

None

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

```shell
[no app in context] Fehler: Doctrine\DBAL\Schema\SchemaException: There is no table with name 'nextcloud.oc_file_metadata' in the schema. at <<closure>>

 0. /var/www/nextcloud/3rdparty/doctrine/dbal/src/Schema/Schema.php line 189
    Doctrine\DBAL\Schema\SchemaException::tableDoesNotExist()
 1. /var/www/nextcloud/lib/private/Repair/AddMetadataMigrationJob.php line 44
    Doctrine\DBAL\Schema\Schema->getTable()
 2. /var/www/nextcloud/lib/private/Repair.php line 128
    OC\Repair\AddMetadataMigrationJob->run()
 3. /var/www/nextcloud/lib/private/Updater.php line 299
    OC\Repair->run()
 4. /var/www/nextcloud/lib/private/Updater.php line 139
    OC\Updater->doUpgrade()
 5. /var/www/nextcloud/core/Command/Upgrade.php line 225
    OC\Updater->upgrade()
 6. /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php line 298
    OC\Core\Command\Upgrade->execute()
 7. /var/www/nextcloud/3rdparty/symfony/console/Application.php line 1040
    Symfony\Component\Console\Command\Command->run()
 8. /var/www/nextcloud/3rdparty/symfony/console/Application.php line 301
    Symfony\Component\Console\Application->doRunCommand()
 9. /var/www/nextcloud/3rdparty/symfony/console/Application.php line 171
    Symfony\Component\Console\Application->doRun()
10. /var/www/nextcloud/lib/private/Console/Application.php line 218
    Symfony\Component\Console\Application->run()
11. /var/www/nextcloud/console.php line 100
    OC\Console\Application->run()
12. /var/www/nextcloud/occ line 11
    require_once("/var/www/nextcloud/console.php")

at 2024-03-03T21:15:32+01:00


[updater] Fehler: OC\Repair\Events\RepairErrorEvent: Repair error: There is no table with name 'nextcloud.oc_file_metadata' in the schema.

at 2024-03-03T21:15:32+01:00


[no app in context] Fehler: Doctrine\DBAL\Schema\SchemaException: There is no table with name 'nextcloud.oc_file_metadata' in the schema. at <<closure>>

 0. /var/www/nextcloud/3rdparty/doctrine/dbal/src/Schema/Schema.php line 189
    Doctrine\DBAL\Schema\SchemaException::tableDoesNotExist()
 1. /var/www/nextcloud/lib/private/Repair/AddMetadataMigrationJob.php line 44
    Doctrine\DBAL\Schema\Schema->getTable()
 2. /var/www/nextcloud/lib/private/Repair.php line 128
    OC\Repair\AddMetadataMigrationJob->run()
 3. /var/www/nextcloud/core/Command/Maintenance/Repair.php line 123
    OC\Repair->run()
 4. /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php line 298
    OC\Core\Command\Maintenance\Repair->execute()
 5. /var/www/nextcloud/3rdparty/symfony/console/Application.php line 1040
    Symfony\Component\Console\Command\Command->run()
 6. /var/www/nextcloud/3rdparty/symfony/console/Application.php line 301
    Symfony\Component\Console\Application->doRunCommand()
 7. /var/www/nextcloud/3rdparty/symfony/console/Application.php line 171
    Symfony\Component\Console\Application->doRun()
 8. /var/www/nextcloud/lib/private/Console/Application.php line 218
    Symfony\Component\Console\Application->run()
 9. /var/www/nextcloud/console.php line 100
    OC\Console\Application->run()
10. /var/www/nextcloud/occ line 11
    require_once("/var/www/nextcloud/console.php")

at 2024-03-03T21:29:08+01:00
```

### Additional info

https://help.nextcloud.com/t/there-is-no-table-with-name-nextcloud-oc-file-metadata-in-the-schema/162467

### PR DESCRIPTION
**Pull request by artonge**
Follow up of https://github.com/nextcloud/server/pull/43580

Resolves https://github.com/nextcloud/server/issues/43966

### CODE REVIEW

File: core/BackgroundJobs/MetadataMigrationJob.php [hunk 1]
```diff
@@ -48,7 +50,8 @@ public function __construct(
 	}
 
 	protected function run(mixed $argument): void {
-		if (!$this->db->createSchema()->getTable('oc_file_metadata')->hasColumn('metadata')) {
+		$prefix = $this->config->getSystemValue('dbtableprefix', 'oc_');
```
Comment (come-nc) [inline core/BackgroundJobs/MetadataMigrationJob.php:53]:
```suggestion
		$prefix = $this->config->getSystemValueString('dbtableprefix', 'oc_');
```
use the types, Luke

File: lib/private/Repair/AddMetadataMigrationJob.php [hunk 2]
```diff
@@ -41,7 +43,9 @@ public function getName() {
 
 	public function run(IOutput $output) {
 		$schema = $this->db->createSchema();
-		$metadataTable = $schema->getTable('oc_file_metadata');
+
+		$prefix = $this->config->getSystemValue('dbtableprefix', 'oc_');
```
Comment (come-nc) [inline lib/private/Repair/AddMetadataMigrationJob.php:47]:
```suggestion
		$prefix = $this->config->getSystemValueString('dbtableprefix', 'oc_');
```

**Review by come-nc — APPROVED** [review]

**Review by solracsf — APPROVED** [review]

**Review by icewind1991 — APPROVED** [review]
