### PR TITLE
fix(files): only disable template creation when both skeleton directories are empty

### LINKED ISSUE #55262: [Bug]: User template directory cannot be created when `templatedirectory` is an empty string
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When the `templatedirectory` property in `config.php` is set to an empty string (i.e. `''`) the option to create a user template directory exists in the "New file" menu, but it ends up failing. The relevant code block below indicates that when `templatedirectory` is an empty string, that a template directory should not be created:

https://github.com/nextcloud/server/blob/52acc5ef1515c37bbcfd3da349df5ba09970cbc3/lib/private/Files/Template/TemplateManager.php#L332-L335

However, this behavior is wrong according to the `config.php` documentation:

https://github.com/nextcloud/server/blob/52acc5ef1515c37bbcfd3da349df5ba09970cbc3/config/config.sample.php#L310-L321

Specifically, "Set empty string to not copy any template files." The default behavior when `templatedirectory` is not set at all is to allow the user to create an empty template directory. I think when `templatedirectory` is explicitly set to an empty string it should either behave in the same way or totally disable the user's ability to create a template directory.

### Steps to reproduce

1. Set `templatedirectory` in `config.php` to `''`
2. From any user account, create a template directory from the "New file" menu
3. See how it navigates the user to a folder which does not exist (it cannot be created)

### Expected behavior

The expected behavior is that, when the `templatedirectory` is explicitly set to an empty string (i.e. `''`), the "Create templates directory" entry of the "New file" menu should not be shown.

### Nextcloud Server version

master

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by benjaminfrueh**
## Problem
When `templatedirectory` was set to an empty string, clicking "Create templates folder" resulted in a "folder not found" error, when `skeletondirectory` was still configured (not an empty string).

## Root cause
`initializeTemplateDirectory()` returns early when only `templatedirectory` is empty, while the frontend showed the button with an || condition, so if either of them is not an empty string.

## Fix
As it is documented in `config.sample.php`:
> To disable creating a template directory, set both skeletondirectory and templatedirectory to empty strings.

The early return now only happens when both are empty, and only for automatic initialization, not when the user manually requests template folder creation.

## Note
`skeletondirectory` and `templatedirectory` are used for provisioning files during initialization. In my opinion it should not take the manual "Create templates folder" feature away from users, that could remain in the users control while still preventing the automatic creation as expected from the config. Every user can create and use their own templates. If an admin wants to explicitly disable this feature, there should be a new config option for that, not a side effect of the file provisioning configuration.

Open for discussion, I am happy to hear if there is a different opinion on how this should be handled.

### CODE REVIEW

File: apps/files/lib/Controller/ViewController.php [hunk 1]
```diff
@@ -194,7 +194,7 @@ public function index($dir = '', $view = '', $fileid = null) {
 			$this->eventDispatcher->dispatchTyped(new LoadViewer());
 		}
 
-		$this->initialState->provideInitialState('templates_enabled', ($this->config->getSystemValueString('skeletondirectory', \OC::$SERVERROOT . '/core/skeleton') !== '') || ($this->config->getSystemValueString('templatedirectory', \OC::$SERVERROOT . '/core/skeleton/Templates') !== ''));
+		$this->initialState->provideInitialState('templates_enabled', true);
```
Comment (come-nc) [inline apps/files/lib/Controller/ViewController.php:197]: This will make the button appear even if it may do nothing?

**Review by come-nc — CHANGES_REQUESTED** [review]
What about setting the condition in the UI as well on if the templatedirectory is empty only ?
skeletondirectory should only matter for user initialization, no?

File: apps/files/lib/Controller/ViewController.php (hunk 1 above)
Comment (benjaminfrueh) [reply apps/files/lib/Controller/ViewController.php:197]: In my tests the button always works correctly even if both configurations are empty. It manually creates a template directory in the users directory and is only available for users who don't have a template directory configured yet.

This wasn't working before because the condition in `initializeTemplateDirectory` was blocking it even when coming from a manual user request, not from the automatic initialization on new user setup.

The change was originally implemented to prevent the automatic creation of the template folder, the manual creation is a feature a user could always opt-in and use.

So in my opinion the manual creation could always be possible regardless of both configurations. If the nextcloud configurated `templatedirectory` is a empty string, no files will be seeded automatically from there, but the user can still create it and add their own templates to it.

File: lib/private/Files/Template/TemplateManager.php [hunk 2]
```diff
@@ -328,7 +328,7 @@ public function initializeTemplateDirectory(?string $path = null, ?string $userI
 		$isDefaultTemplates = $skeletonTemplatePath === $defaultTemplateDirectory;
 		$userLang = $this->l10nFactory->getUserLanguage($this->userManager->get($this->userId));
 
-		if ($skeletonTemplatePath === '') {
+		if ($path === null && $skeletonTemplatePath === '' && $skeletonPath === '') {
```
Comment (provokateurin) [inline lib/private/Files/Template/TemplateManager.php:331]: Why is $path also checked now?

Comment (benjaminfrueh) [reply lib/private/Files/Template/TemplateManager.php:331]: The `path` check is to prevent the template dir creation only for the automatic initialization setup (when a user is created). For the manual creation with the button in the Web UI, there is always a `path` given. The same `path` check is used a few lines later to detect initial user setup.

**Comment by benjaminfrueh** [comment]
@come-nc @provokateurin I think the main confusion here is, both configurations, `skeletondirectory` and `templatedirectory` are only needed for seeding the template folder and template files automatically from a shared source, but they are both not needed for manually creating a empty template directory via the web ui, where the user can then add his own templates to.

**Review by come-nc — APPROVED** [review]

**Review by susnux — APPROVED** [review]
