### PR TITLE
fix(status): Avoid session creation for status requests

### LINKED ISSUE #11125: Don't open PHP session for status.php
### Steps to reproduce
1. Fetch the status of the instance via status.php, for example via `curl -I https://example.com/nextcloud/status.php` or your favourite monitoring solution.

### Expected behaviour
No new session is created, because a) this most likely is an automated request, and b) status.php doesn't use anything from that session anyway.

### Actual behaviour
A new session is created and sent via the `Set-Cookie:` header, causing stale sessions to pile up due to monitoring requests.

## Server configuration detail

**Operating system:** Debian Stretch

**Webserver:** Apache

**Database:** MariaDB

**PHP version:** 

7.0.30

**Nextcloud version:** 13.0.6 - 13.0.6.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** 

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - bruteforcesettings: 1.1.0
 - calendar: 1.6.1
 - contacts: 2.1.5
 - dav: 1.4.7
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_external: 1.4.1
 - files_pdfviewer: 1.2.1
 - files_rightclick: 0.8.4
 - files_sharing: 1.5.0
 - files_snapshots: 0.1.1
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - gallery: 18.0.0
 - impersonate: 1.0.4
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - mail: 0.8.3
 - metadata: 0.7.0
 - news: 12.0.4
 - notifications: 2.1.2
 - oauth2: 1.1.1
 - polls: 0.8.3
 - provisioning_api: 1.3.0
 - sharebymail: 1.3.0
 - tasks: 0.9.7
 - theming: 1.4.5
 - twofactor_backupcodes: 1.2.3
 - twofactor_totp: 1.4.1
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - comments
 - encryption
 - firstrunwizard
 - nextcloud_announcements
 - password_policy
 - serverinfo
 - survey_client
 - systemtags
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "13.0.6.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "Europe\/Berlin",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "loglevel": 1,
    "log_type": "syslog",
    "updatechecker": true,
    "htaccess.RewriteBase": "\/",
    "appstore.experimental.enabled": true,
    "config_is_read_only": false,
    "check_for_working_htaccess": false,
    "appstoreenabled": true,
    "syslog_tag": "nextcloud",
    "mysql.utf8mb4": true,
    "theme": ""
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:**

### PR DESCRIPTION
**Pull request by solracsf**
* Resolves: https://github.com/nextcloud/server/issues/11125

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: lib/base.php [hunk 1]
```diff
@@ -363,6 +363,14 @@ private static function printUpgradePage(\OC\SystemConfig $systemConfig): void {
 	public static function initSession(): void {
 		$request = Server::get(IRequest::class);
 
+		// Do not initialize sessions for 'status.php' requests
+		// Monitoring endpoints can quickly flood session handlers
+		// and 'status.php' doesn't require sessions anyway
+		$isStatusRequest = str_starts_with($request->getRequestUri(), '/status.php');
```
Comment (szaimen) [inline lib/base.php:369]: Shouldnt that be str_ends_with or am I missing something?

Comment (solracsf) [reply lib/base.php:369]: Well, after reading I think neither should be used here since we're looking for an exact match, not at the start or at the end. I'll fix this. 👌🏻

Comment (solracsf) [reply lib/base.php]: Fixed.

File: lib/base.php [hunk 2]
```diff
@@ -363,6 +363,13 @@ private static function printUpgradePage(\OC\SystemConfig $systemConfig): void {
 	public static function initSession(): void {
 		$request = Server::get(IRequest::class);
 
+		// Do not initialize sessions for 'status.php' requests
+		// Monitoring endpoints can quickly flood session handlers
+		// and 'status.php' doesn't require sessions anyway
+		if ($request->getRequestUri() === '/status.php') {
```
Comment (szaimen) [inline lib/base.php:369]: And what about subdir instaolations? Or is the part before stripped from the uri?

**Review by juliusknorr — APPROVED** [review]

File: lib/base.php (hunk 2 above)
Comment (solracsf) [reply lib/base.php]: My bad, you're right. Thanks. 🥇

**Review by szaimen — APPROVED** [review]
LGTM but didnt test

**Review by nickvergessen — CHANGES_REQUESTED** [review]

File: lib/base.php [hunk 3]
```diff
@@ -363,6 +363,13 @@ private static function printUpgradePage(\OC\SystemConfig $systemConfig): void {
 	public static function initSession(): void {
 		$request = Server::get(IRequest::class);
 
+		// Do not initialize sessions for 'status.php' requests
+		// Monitoring endpoints can quickly flood session handlers
+		// and 'status.php' doesn't require sessions anyway
+		if (str_ends_with($request->getRequestUri(), '/status.php')) {
```
[the remark this answers is not in the document]
Comment (nickvergessen) [reply lib/base.php:369]:
```suggestion
		if (str_ends_with($request->getScriptName(), '/status.php')) {
```

should do, ref:
https://github.com/nextcloud/server/blob/381077028adf388a7081cf42026570c6be47b198/apps/workflowengine/lib/Check/RequestURL.php#L60-L63

[the remark this answers is not in the document]
Comment (solracsf) [reply lib/base.php]: Thanks. 👍 Do you believe it's a better option than `OC::$SUBURI` already available in base.php?

**Review by nickvergessen — APPROVED** [review]
But since we have a valid request class in the place already, it should be fine

**Comment by szaimen** [comment]
Hey,  it looks like this broke the security scanner. See https://help.nextcloud.com/t/update-nextcloud-to-31-0-0-now-scaner-showing-rating-a/218485/13. So revert?

**Comment by nickvergessen** [comment]
Requests from scanner 1/month or 1/year
Requests from sync clients which don't need this 1.000.000 * x

We can add a force header to do the session or we scan a second endpoint.

**Comment by szaimen** [comment]
Resolved by https://github.com/nextcloud/server/pull/51184
