### PR TITLE
Check for app updates on disabled page

### LINKED ISSUE #2403: Problem updating/enabling apps installed via git in NC 11
### Steps to reproduce
1. On NC 10 install an old version of one of these Apps via git: News, Two Factor TOTP Provider (? Mail, ownNote, Tasks, Bookmarks)
2. Update to NC11
3. Search for it in the corresponding app category and try to update/enable it in NC11

### Expected behaviour
During installation apps are updated automatically.
Or if not, a message informing you of your outdated version and that there is a newer one supporting NC11 you can update to.

or at least

Message informing you, that you have to uninstall and install again, but there wont be loss of data. Because a lot of apps could only be installed via git in NC10, this is relevant. Of course admins should find out themselves or do manual upgrades, but it's not ideal at all.

### Actual behaviour
```
App "XXX" cannot be installed because the following dependencies are not fulfilled: Server version 9.2 or lower is required.
```
nov -29-2016 14-12-31

This is how the my apps look after the update from 10 to 11 and I reinstalled News and TwoFactor alreeady. I added
bildschirmfoto 2016-11-29 um 14 40 41

### Server configuration
**Operating system**: CentOS 6

**Web server:** Apache 2.4

**Database:** MySQL

**PHP version:** PHP 5.6.21

**Nextcloud version:** (see Nextcloud admin page) 11.0 beta 2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from NC10 vie Web Updater and `occ upgrade`

**Update logs:**
<details>
<summary>occ upgrade</summary>

```
occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Updating database schema
Updated database
Disabled 3rd-party app: apporder
Disabled incompatible app: bookmarks
Disabled 3rd-party app: bookmarks
Disabled 3rd-party app: calendar
Disabled incompatible app: contacts
Disabled 3rd-party app: contacts
Disabled 3rd-party app: direct_menu
Disabled incompatible app: mail
Disabled 3rd-party app: mail
Disabled incompatible app: news
Disabled 3rd-party app: news
Disabled incompatible app: ownnote
Disabled 3rd-party app: ownnote
Disabled incompatible app: tasks
Disabled 3rd-party app: tasks
Disabled incompatible app: twofactor_totp
Disabled 3rd-party app: twofactor_totp
Updating <federatedfilesharing> ...
Updated <federatedfilesharing> to 1.1.1
Updating <files_texteditor> ...
Updated <files_texteditor> to 2.2
Updating <files_videoplayer> ...
Updated <files_videoplayer> to 1.0.0
Updating <firstrunwizard> ...
Updated <firstrunwizard> to 2.0
Updating <gallery> ...
Updated <gallery> to 16.0.0
Updating <password_policy> ...
Updated <password_policy> to 1.1.0
Updating <provisioning_api> ...
Updated <provisioning_api> to 1.1.0
Updating <templateeditor> ...
Updated <templateeditor> to 0.2
Updating <updatenotification> ...
Updated <updatenotification> to 1.1.1
Updating <federation> ...
Updated <federation> to 1.1.1
Updating <files> ...
Updated <files> to 1.6.1
Updating <activity> ...
Updated <activity> to 2.4.1
Updating <dav> ...
Updated <dav> to 1.1.1
Updating <files_external> ...
Updated <files_external> to 1.1.2
Updating <files_retention> ...
Updated <files_retention> to 1.0.1
Updating <files_sharing> ...
Updated <files_sharing> to 1.1.1
Updating <files_trashbin> ...
Updated <files_trashbin> to 1.1.0
Updating <files_versions> ...
Updated <files_versions> to 1.4.0
Updating <workflowengine> ...
Updated <workflowengine> to 1.1.1
Updating <admin_audit> ...
Updated <admin_audit> to 1.1.0
Updating <comments> ...
Updated <comments> to 1.1.0
Updating <notifications> ...
Updated <notifications> to 1.0.1
Updating <theming> ...
Updated <theming> to 1.1.1
Update 3rd-party app: apporder
Update 3rd-party app: contacts
Update 3rd-party app: direct_menu
Drop old database tables

 Done
 31/31 [============================] 100%
Remove old (< 9.0) calendar/contact shares
 Done
 4/4 [============================] 100%
Fix permissions so avatars can be stored again
 Done
 2/2 [============================] 100%
Update successful
Maintenance mode is kept active
Reset log level

```
</details>

**Where did you install Nextcloud from:** ⬆️ 

**Signing status:**
<details>
<summary>Signing status</summary>

```
Integrity checker has been disabled. Integrity cannot be verified.
```
:flushed:
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - apporder: 0.3.3
  - calendar: 1.4.1
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - direct_menu: 0.9.3
  - external: 1.2
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_retention: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 1.3.1
  - lookup_server_connector: 1.0.0
  - news: true
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.0
  - survey_client: 0.1.5
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: true
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - bookmarks
  - encryption
  - files_accesscontrol
  - files_automatedtagging
  - files_pdfviewer
  - mail
  - ownnote
  - systemtags
  - tasks
  - user_external
  - user_ldap
  - user_saml
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ocztm7fxpnfx",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "epp.cloud"
        ],
        "datadirectory": "\/home\/eppcloud\/ocdata",
        "overwrite.cli.url": "https:\/\/epp.cloud",
        "dbtype": "mysql",
        "version": "11.0.0.5",
        "dbname": "eppcloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": 2,
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/home\/eppcloud\/.redis\/sock",
            "port": 0,
            "timeout": 0
        },
        "forcessl": true,
        "mail_from_address": "botler",
        "mail_smtpmode": "php",
        "mail_domain": "epp.cloud",
        "maintenance": false,
        "htaccess.RewriteBase": "\/",
        "updater.release.channel": "beta",
        "debug": true,
        "appstore.experimental.enabled": true,
        "htaccess.IgnoreFrontController": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.4.1",
            "types": "filesystem"
        },
        "admin_audit": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "logging"
        },
        "apporder": {
            "enabled": "yes",
            "installed_version": "0.3.3",
            "ocsid": "174715",
            "types": ""
        },
        "backgroundjob": {
            "lastjob": "1529"
        },
        "bookmarks": {
            "enabled": "no",
            "installed_version": "0.9.0",
            "ocsid": "168710",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.4.1",
            "ocsid": "168707",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "1.5.2",
            "ocsid": "168708",
            "types": ""
        },
        "core": {
            "OC_Channel": "beta",
            "backgroundjobs_mode": "cron",
            "installedat": "1460404187.1843",
            "lastcron": "1480425267",
            "lastupdateResult": "[]",
            "lastupdatedat": "1480424791",
            "oc.integritycheck.checker": "[]",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "shareapi_allow_public_notification": "yes",
            "umgmt_send_email": "true",
            "umgmt_show_backend": "false",
            "umgmt_show_email": "true",
            "umgmt_show_last_login": "true",
            "umgmt_show_storage_location": "true",
            "updater.secret.created": "1480418446",
            "vendor": "nextcloud"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "filesystem"
        },
        "direct_menu": {
            "enabled": "yes",
            "installed_version": "0.9.3",
            "ocsid": "169148",
            "types": ""
        },
        "external": {
            "enabled": "yes",
            "installed_version": "1.2",
            "ocsid": "166046",
            "sites": "[[\"Hackpad\",\"https:\\\/\\\/pad.epp.cloud\",\"external.svg\"],[\"Wallabag\",\"https:\\\/\\\/bag.epp.cloud\",\"\"]]",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "default_quota": "5 GB",
            "enabled": "yes",
            "installed_version": "1.6.1",
            "types": "filesystem"
        },
        "files_accesscontrol": {
            "enabled": "no",
            "installed_version": "1.1.2",
            "types": "filesystem"
        },
        "files_automatedtagging": {
            "enabled": "no",
            "installed_version": "1.1.1",
            "types": "filesystem"
        },
        "files_external": {
            "enabled": "yes",
            "installed_version": "1.1.2",
            "ocsid": "166048",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "no",
            "installed_version": "0.8",
            "ocsid": "166049",
            "types": ""
        },
        "files_retention": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "filesystem"
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.2",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.0",
            "types": "logging"
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "16.0.0",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "1.3.1",
            "ocsid": "170871",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "authentication"
        },
        "mail": {
            "enabled": "no",
            "installed_version": "0.6.0",
            "ocsid": "169914",
            "signed": "true",
            "types": ""
        },
        "news": {
            "enabled": "yes",
            "installed_version": "0",
            "ocsid": "168040",
            "types": ""
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.0",
            "types": "logging"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "logging"
        },
        "ownnote": {
            "enabled": "no",
            "folder": "Notes",
            "installed_version": "0",
            "ocsid": "168512",
            "types": ""
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "minLength": "8",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "prevent_group_restriction"
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "0.1.5",
            "last_report": "{...}",
            "last_sent": "1479389369",
            "types": ""
        },
        "systemtags": {
            "enabled": "no",
            "installed_version": "1.0.2",
            "types": "logging"
        },
        "tasks": {
            "enabled": "no",
            "installed_version": "0.9.3",
            "ocsid": "164356",
            "types": ""
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.2",
            "types": ""
        },
        "theming": {
            "backgroundMime": "image\/jpeg",
            "cachebuster": "83",
            "color": "#009C9A",
            "enabled": "yes",
            "installed_version": "1.1.1",
            "logoMime": "image\/svg+xml",
            "name": "eppCloud",
            "slogan": "discreetly serving ",
            "types": "logging"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "twofactor_totp": {
            "enabled": "yes",
            "installed_version": "0",
            "ocsid": "174726",
            "types": ""
        },
        "updatenotification": {
            "calendar": "1.4.1",
            "contacts": "1.4.0.0",
            "core": "11.0.0.5",
            "direct_menu": "0.9.2",
            "enabled": "[\"admin\"]",
            "installed_version": "1.1.1",
            "mail": "0.6.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "filesystem"
        }
    }
}

```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

#### Web server error log
<details>
<summary>Web server error log</summary>

```
[Tue Nov 29 13:30:12 2016] [error] [client 213.160.22.98] File does not exist: /var/www/virtual/eppcloud/html/ocs-provider
[Tue Nov 29 13:30:16 2016] [error] [client 213.160.22.98] File does not exist: /var/www/virtual/eppcloud/html/ocs-provider
[Tue Nov 29 13:30:19 2016] [error] [client 213.160.22.98] File does not exist: /var/www/virtual/eppcloud/html/ocs-provider
[Tue Nov 29 13:30:21 2016] [error] [client 213.160.22.98] File does not exist: /var/www/virtual/eppcloud/html/ocs-provider
[Tue Nov 29 13:30:23 2016] [warn] [client 213.160.22.98] mod_fcgid: stderr: PHP Warning:  require(/var/www/virtual/eppcloud/html/3rdparty/composer/../symfony/polyfill-mbstring/bootstrap.php): failed to open stream: No such file or directory in /var/www/virtual/eppcloud/html/3rdparty/composer/autoload_real.php on line 61
[Tue Nov 29 13:30:23 2016] [warn] [client 213.160.22.98] mod_fcgid: stderr: PHP Fatal error:  require(): Failed opening required '/var/www/virtual/eppcloud/html/3rdparty/composer/../symfony/polyfill-mbstring/bootstrap.php' (include_path='/var/www/virtual/eppcloud/html/3rdparty/pear/console_getopt:/var/www/virtual/eppcloud/html/3rdparty/pear/pear_exception:/var/www/virtual/eppcloud/html/3rdparty/pear/pear-core-minimal/src:/var/www/virtual/eppcloud/html/3rdparty/pear/archive_tar:/var/www/virtual/eppcloud/html/apps') in /var/www/virtual/eppcloud/html/3rdparty/composer/autoload_real.php on line 61
[Tue Nov 29 14:04:00 2016] [warn] [client 109.90.232.108] (70008)Partial results are valid but processing is incomplete: mod_fcgid: can't get data from http client
[Tue Nov 29 14:18:53 2016] [error] [client 2a02:908:df54:2c20:651d:8201:3cf:dfd0] File does not exist: /var/www/virtual/eppcloud/html/favicon.ico, referer: https://epp.cloud/index.php/settings/integrity/failed
[Tue Nov 29 14:23:08 2016] [error] [client 2a02:908:df54:2c20:651d:8201:3cf:dfd0] File does not exist: /var/www/virtual/eppcloud/html/favicon.ico, referer: https://epp.cloud/index.php/settings/integrity/failed
[Tue Nov 29 14:23:13 2016] [error] [client 2a02:908:df54:2c20:651d:8201:3cf:dfd0] File does not exist: /var/www/virtual/eppcloud/html/favicon.ico, referer: https://epp.cloud/settings/integrity/failed
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"VeiE+u94ggyViTz+od5w","remoteAddr":"","app":"no app in context","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"settings_admin\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/lib\\\/private\\\/Route\\\/Router.php(333): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('settings_admin', Array, 1)\\n#1 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/lib\\\/private\\\/Route\\\/CachingRouter.php(60): OC\\\\Route\\\\Router->generate('settings_admin', Array, false)\\n#2 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/lib\\\/private\\\/URLGenerator.php(69): OC\\\\Route\\\\CachingRouter->generate('settings_admin', Array)\\n#3 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/lib\\\/private\\\/URLGenerator.php(82): OC\\\\URLGenerator->linkToRoute('settings_admin', Array)\\n#4 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/apps\\\/updatenotification\\\/lib\\\/Notification\\\/BackgroundJob.php(101): OC\\\\URLGenerator->linkToRouteAbsolute('settings_admin')\\n#5 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/apps\\\/updatenotification\\\/lib\\\/Notification\\\/BackgroundJob.php(84): OCA\\\\UpdateNotification\\\\Notification\\\\BackgroundJob->checkCoreUpdate()\\n#6 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(53): OCA\\\\UpdateNotification\\\\Notification\\\\BackgroundJob->run(NULL)\\n#7 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(54): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#8 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/cron.php(121): OC\\\\BackgroundJob\\\\TimedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":130}","level":3,"time":"2016-11-29T04:44:25+00:00","method":"--","url":"--","user":"--"}
{"reqId":"1\/Y6Wip+n+giJMPf2Cer","remoteAddr":"54.198.134.244","app":"core","message":"Trusted domain error. \"54.198.134.244\" tried to access using \"epp.earth\" as host.","level":2,"time":"2016-11-29T09:15:28+00:00","method":"GET","url":"\/","user":"--"}
{"reqId":"Q7QKm95unhFqZdvSuL60","remoteAddr":"54.198.134.244","app":"core","message":"Trusted domain error. \"54.198.134.244\" tried to access using \"epp.earth\" as host.","level":2,"time":"2016-11-29T09:15:30+00:00","method":"GET","url":"\/index.php\/core\/js\/oc.js?v=762fc604934ba1f3fc7ee3ec31f25040","user":"--"}
{"reqId":"\/xbvrAfTU1s7A42nCHua","remoteAddr":"2a02:908:df54:2c20:651d:8201:3cf:dfd0","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 System in maintenance mode.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/remote.php(165): require_once('\\\/var\\\/www\\\/virtua...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/MaintenancePlugin.php\",\"Line\":85,\"User\":\"eppfel\"}","level":4,"time":"2016-11-29T12:28:07+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"eppfel"}
{"reqId":"xGPlJU+IOYObqA3kgS68","remoteAddr":"2a02:908:df54:2c20:651d:8201:3cf:dfd0","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 System in maintenance mode.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/remote.php(165): require_once('\\\/var\\\/www\\\/virtua...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/MaintenancePlugin.php\",\"Line\":85,\"User\":\"eppfel\"}","level":4,"time":"2016-11-29T12:28:38+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"eppfel"}
{"reqId":"5iaC\/0K0wRWSTP8OozZp","remoteAddr":"2a02:908:df54:2c20:651d:8201:3cf:dfd0","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 System in maintenance mode.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/remote.php(165): require_once('\\\/var\\\/www\\\/virtua...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/MaintenancePlugin.php\",\"Line\":85,\"User\":\"eppfel\"}","level":4,"time":"2016-11-29T12:29:11+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"eppfel"}
{"reqId":"aQe57DkMzjzxB3lamLc2","remoteAddr":"2a02:908:df54:2c20:651d:8201:3cf:dfd0","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 System in maintenance mode.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/remote.php(165): require_once('\\\/var\\\/www\\\/virtua...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/MaintenancePlugin.php\",\"Line\":85,\"User\":\"eppfel\"}","level":4,"time":"2016-11-29T12:29:43+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"eppfel"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"core","message":"starting upgrade from 9.1.1.5 to 11.0.0.5","level":0,"time":"2016-11-29T12:31:17+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::step: Repair step: Repair MySQL database engine","level":1,"time":"2016-11-29T12:31:18+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::step: Repair step: Repair MySQL collation","level":1,"time":"2016-11-29T12:31:18+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::step: Repair step: Repair SQLite autoincrement","level":1,"time":"2016-11-29T12:31:18+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::step: Repair step: Repair duplicate entries in oc_lucene_status","level":1,"time":"2016-11-29T12:31:18+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::info: Repair info: lucene_status table does not exist -> nothing to do","level":1,"time":"2016-11-29T12:31:18+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::dbUpgradeBefore: Updating database schema","level":1,"time":"2016-11-29T12:31:18+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::dbUpgrade: Updated database","level":1,"time":"2016-11-29T12:31:23+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::thirdPartyAppDisabled: Disabled 3rd-party app: apporder","level":1,"time":"2016-11-29T12:31:23+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::incompatibleAppDisabled: Disabled incompatible app: bookmarks","level":1,"time":"2016-11-29T12:31:23+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::thirdPartyAppDisabled: Disabled 3rd-party app: bookmarks","level":1,"time":"2016-11-29T12:31:23+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::thirdPartyAppDisabled: Disabled 3rd-party app: calendar","level":1,"time":"2016-11-29T12:31:23+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::incompatibleAppDisabled: Disabled incompatible app: contacts","level":1,"time":"2016-11-29T12:31:23+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::thirdPartyAppDisabled: Disabled 3rd-party app: contacts","level":1,"time":"2016-11-29T12:31:23+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::thirdPartyAppDisabled: Disabled 3rd-party app: direct_menu","level":1,"time":"2016-11-29T12:31:23+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::incompatibleAppDisabled: Disabled incompatible app: mail","level":1,"time":"2016-11-29T12:31:23+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::thirdPartyAppDisabled: Disabled 3rd-party app: mail","level":1,"time":"2016-11-29T12:31:24+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::incompatibleAppDisabled: Disabled incompatible app: news","level":1,"time":"2016-11-29T12:31:24+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::thirdPartyAppDisabled: Disabled 3rd-party app: news","level":1,"time":"2016-11-29T12:31:24+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::incompatibleAppDisabled: Disabled incompatible app: ownnote","level":1,"time":"2016-11-29T12:31:24+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::thirdPartyAppDisabled: Disabled 3rd-party app: ownnote","level":1,"time":"2016-11-29T12:31:24+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::incompatibleAppDisabled: Disabled incompatible app: tasks","level":1,"time":"2016-11-29T12:31:24+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::thirdPartyAppDisabled: Disabled 3rd-party app: tasks","level":1,"time":"2016-11-29T12:31:24+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::incompatibleAppDisabled: Disabled incompatible app: twofactor_totp","level":1,"time":"2016-11-29T12:31:24+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::thirdPartyAppDisabled: Disabled 3rd-party app: twofactor_totp","level":1,"time":"2016-11-29T12:31:24+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgradeStarted: Updating <federatedfilesharing> ...","level":1,"time":"2016-11-29T12:31:24+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgrade: Updated <federatedfilesharing> to 1.1.1","level":1,"time":"2016-11-29T12:31:25+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgradeStarted: Updating <files_texteditor> ...","level":1,"time":"2016-11-29T12:31:25+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgrade: Updated <files_texteditor> to 2.2","level":1,"time":"2016-11-29T12:31:25+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgradeStarted: Updating <files_videoplayer> ...","level":1,"time":"2016-11-29T12:31:25+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgrade: Updated <files_videoplayer> to 1.0.0","level":1,"time":"2016-11-29T12:31:25+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgradeStarted: Updating <firstrunwizard> ...","level":1,"time":"2016-11-29T12:31:25+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgrade: Updated <firstrunwizard> to 2.0","level":1,"time":"2016-11-29T12:31:25+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgradeStarted: Updating <gallery> ...","level":1,"time":"2016-11-29T12:31:25+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgrade: Updated <gallery> to 16.0.0","level":1,"time":"2016-11-29T12:31:25+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgradeStarted: Updating <password_policy> ...","level":1,"time":"2016-11-29T12:31:25+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgrade: Updated <password_policy> to 1.1.0","level":1,"time":"2016-11-29T12:31:25+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgradeStarted: Updating <provisioning_api> ...","level":1,"time":"2016-11-29T12:31:25+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgrade: Updated <provisioning_api> to 1.1.0","level":1,"time":"2016-11-29T12:31:25+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgradeStarted: Updating <templateeditor> ...","level":1,"time":"2016-11-29T12:31:25+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgrade: Updated <templateeditor> to 0.2","level":1,"time":"2016-11-29T12:31:25+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgradeStarted: Updating <updatenotification> ...","level":1,"time":"2016-11-29T12:31:25+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgrade: Updated <updatenotification> to 1.1.1","level":1,"time":"2016-11-29T12:31:25+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgradeStarted: Updating <federation> ...","level":1,"time":"2016-11-29T12:31:25+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgrade: Updated <federation> to 1.1.1","level":1,"time":"2016-11-29T12:31:25+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgradeStarted: Updating <files> ...","level":1,"time":"2016-11-29T12:31:25+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgrade: Updated <files> to 1.6.1","level":1,"time":"2016-11-29T12:31:25+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgradeStarted: Updating <activity> ...","level":1,"time":"2016-11-29T12:31:25+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgrade: Updated <activity> to 2.4.1","level":1,"time":"2016-11-29T12:31:27+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgradeStarted: Updating <dav> ...","level":1,"time":"2016-11-29T12:31:27+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::step: Repair step: Fix component of birthday calendars","level":1,"time":"2016-11-29T12:31:27+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::info: Repair info: 6 birthday calendars updated.","level":1,"time":"2016-11-29T12:31:27+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgrade: Updated <dav> to 1.1.1","level":1,"time":"2016-11-29T12:31:27+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgradeStarted: Updating <files_external> ...","level":1,"time":"2016-11-29T12:31:27+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgrade: Updated <files_external> to 1.1.2","level":1,"time":"2016-11-29T12:31:28+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgradeStarted: Updating <files_retention> ...","level":1,"time":"2016-11-29T12:31:28+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgrade: Updated <files_retention> to 1.0.1","level":1,"time":"2016-11-29T12:31:28+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgradeStarted: Updating <files_sharing> ...","level":1,"time":"2016-11-29T12:31:28+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgrade: Updated <files_sharing> to 1.1.1","level":1,"time":"2016-11-29T12:31:28+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgradeStarted: Updating <files_trashbin> ...","level":1,"time":"2016-11-29T12:31:28+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgrade: Updated <files_trashbin> to 1.1.0","level":1,"time":"2016-11-29T12:31:29+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgradeStarted: Updating <files_versions> ...","level":1,"time":"2016-11-29T12:31:29+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgrade: Updated <files_versions> to 1.4.0","level":1,"time":"2016-11-29T12:31:29+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgradeStarted: Updating <workflowengine> ...","level":1,"time":"2016-11-29T12:31:29+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgrade: Updated <workflowengine> to 1.1.1","level":1,"time":"2016-11-29T12:31:29+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgradeStarted: Updating <admin_audit> ...","level":1,"time":"2016-11-29T12:31:29+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgrade: Updated <admin_audit> to 1.1.0","level":1,"time":"2016-11-29T12:31:29+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgradeStarted: Updating <comments> ...","level":1,"time":"2016-11-29T12:31:29+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgrade: Updated <comments> to 1.1.0","level":1,"time":"2016-11-29T12:31:29+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgradeStarted: Updating <notifications> ...","level":1,"time":"2016-11-29T12:31:29+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgrade: Updated <notifications> to 1.0.1","level":1,"time":"2016-11-29T12:31:29+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgradeStarted: Updating <theming> ...","level":1,"time":"2016-11-29T12:31:29+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgrade: Updated <theming> to 1.1.1","level":1,"time":"2016-11-29T12:31:29+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"PHP","message":"rewinddir(): 847 is not a valid Directory resource at \/var\/www\/virtual\/eppcloud\/html\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#31","level":0,"time":"2016-11-29T12:31:30+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::upgradeAppStoreApp: Update 3rd-party app: apporder","level":1,"time":"2016-11-29T12:31:30+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::upgradeAppStoreApp: Update 3rd-party app: contacts","level":1,"time":"2016-11-29T12:31:33+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::upgradeAppStoreApp: Update 3rd-party app: direct_menu","level":1,"time":"2016-11-29T12:31:35+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::step: Repair step: Repair MySQL collation","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::step: Repair step: Repair mime types","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::step: Repair step: Repair legacy storages","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::step: Repair step: Remove asset cache","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::info: Repair info: Asset cache cleared.","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::step: Repair step: Generate ETags for file where no ETag is present.","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::info: Repair info: ETags have been fixed for 0 files\/folders.","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::step: Repair step: Clean tags and favorites","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::info: Repair info: 0 tags of deleted users have been removed.","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::info: Repair info: 0 tags for delete files have been removed.","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::info: Repair info: 0 tag entries for deleted tags have been removed.","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::info: Repair info: 0 tags with no entries have been removed.","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::step: Repair step: Drop old database tables","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::startProgress: Starting ... Drop old database tables (31)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance: Drop old database table: calendar_calendars (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance: Drop old database table: calendar_objects (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance: Drop old database table: calendar_share_calendar (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance: Drop old database table: calendar_share_event (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance: Drop old database table: file_map (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance: Drop old database table: foldersize (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance: Drop old database table: fscache (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance: Drop old database table: gallery_sharing (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance: Drop old database table: locks (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance: Drop old database table: log (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance: Drop old database table: media_albums (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance: Drop old database table: media_artists (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance: Drop old database table: media_sessions (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance: Drop old database table: media_songs (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance: Drop old database table: media_users (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance: Drop old database table: permissions (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance: Drop old database table: pictures_images_cache (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance: Drop old database table: principalgroups (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance: Drop old database table: principals (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance: Drop old database table: queuedtasks (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance: Drop old database table: sharing (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance: Drop old database table: clndr_calendars (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance: Drop old database table: clndr_objects (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance: Drop old database table: clndr_share_event (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance: Drop old database table: clndr_share_calendar (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance: Drop old database table: clndr_repeat (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance: Drop old database table: contacts_addressbooks (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance: Drop old database table: contacts_cards (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance: Drop old database table: contacts_cards_properties (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance: Drop old database table: gallery_albums (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance: Drop old database table: gallery_photos (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::finishProgress","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::step: Repair step: Drop old background jobs","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::step: Repair step: Remove getetag entries in properties table","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::info: Repair info: Removed 0 unneeded \"{DAV:}getetag\" entries from properties table.","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::step: Repair step: Repair outdated OCS IDs","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::step: Repair step: Repair invalid shares","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::step: Repair step: Remove old share propagation app entries","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::step: Repair step: Remove old (< 9.0) calendar\/contact shares","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::startProgress: Starting ... Remove old (< 9.0) calendar\/contact shares (4)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance:  (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance:  (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance:  (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance:  (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::finishProgress","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::step: Repair step: Fix permissions so avatars can be stored again","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::startProgress: Starting ... Fix permissions so avatars can be stored again (2)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::advance:  (1)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::finishProgress","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::step: Repair step: Remove shares of a users root folder","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::step: Repair step: Repair unmerged shares","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::step: Repair step: Move .step file of updater to backup location","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::info: Repair info: .step file exists","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::info: Repair info: .step file moved to .step-previous-update","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Repair::step: Repair step: Add mover avatar background job","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::updateEnd: Update successful","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"11.0.0.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::maintenanceActive: Maintenance mode is kept active","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"11.0.0.5"}
{"reqId":"LSzh3LGxuhAGivA8aUU4","remoteAddr":"","app":"updater","message":"\\OC\\Updater::resetLogLevel: Reset log level to Warning(2)","level":1,"time":"2016-11-29T12:31:37+00:00","method":"--","url":"--","user":"--","version":"11.0.0.5"}
{"reqId":"lTvFQZC\/olm59f1Sm\/hC","remoteAddr":"2a02:908:df54:2c20:651d:8201:3cf:dfd0","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 System in maintenance mode.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/remote.php(165): require_once('\\\/var\\\/www\\\/virtua...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/MaintenancePlugin.php\",\"Line\":85,\"User\":\"eppfel\"}","level":4,"time":"2016-11-29T12:31:51+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"eppfel","version":"11.0.0.5"}
{"reqId":"RlHYMrinPYbSdPBxSd3s","remoteAddr":"2a02:908:df54:2c20:651d:8201:3cf:dfd0","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 System in maintenance mode.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/remote.php(165): require_once('\\\/var\\\/www\\\/virtua...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/MaintenancePlugin.php\",\"Line\":85,\"User\":\"eppfel\"}","level":4,"time":"2016-11-29T12:32:23+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"eppfel","version":"11.0.0.5"}
{"reqId":"MBL62gyUrElgY5cX\/+ZR","remoteAddr":"2a02:908:df54:2c20:651d:8201:3cf:dfd0","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 System in maintenance mode.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/remote.php(165): require_once('\\\/var\\\/www\\\/virtua...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/MaintenancePlugin.php\",\"Line\":85,\"User\":\"eppfel\"}","level":4,"time":"2016-11-29T12:32:55+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"eppfel","version":"11.0.0.5"}
{"reqId":"zr4ehOHn6NJwsfKbjung","remoteAddr":"2a02:908:df54:2c20:651d:8201:3cf:dfd0","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 System in maintenance mode.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/remote.php(165): require_once('\\\/var\\\/www\\\/virtua...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/MaintenancePlugin.php\",\"Line\":85,\"User\":\"eppfel\"}","level":4,"time":"2016-11-29T12:33:27+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"eppfel","version":"11.0.0.5"}
{"reqId":"GmB8dIXu2GtcQ1l9Trme","remoteAddr":"2a02:908:df54:2c20:651d:8201:3cf:dfd0","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 System in maintenance mode.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/remote.php(165): require_once('\\\/var\\\/www\\\/virtua...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/MaintenancePlugin.php\",\"Line\":85,\"User\":\"eppfel\"}","level":4,"time":"2016-11-29T12:33:59+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"eppfel","version":"11.0.0.5"}
{"reqId":"hcbIxuO1vxuMLTmcE6oo","remoteAddr":"2a02:908:df54:2c20:651d:8201:3cf:dfd0","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 System in maintenance mode.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/remote.php(165): require_once('\\\/var\\\/www\\\/virtua...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/MaintenancePlugin.php\",\"Line\":85,\"User\":\"eppfel\"}","level":4,"time":"2016-11-29T12:34:31+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"eppfel","version":"11.0.0.5"}
{"reqId":"h9nUghH9dXiKRIowm5Cg","remoteAddr":"2a02:908:df54:2c20:651d:8201:3cf:dfd0","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 System in maintenance mode.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/remote.php(165): require_once('\\\/var\\\/www\\\/virtua...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/MaintenancePlugin.php\",\"Line\":85,\"User\":\"eppfel\"}","level":4,"time":"2016-11-29T12:35:03+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"eppfel","version":"11.0.0.5"}
{"reqId":"GiYNb5ilU8WcUG4Cg9sq","remoteAddr":"2a02:908:df54:2c20:651d:8201:3cf:dfd0","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 System in maintenance mode.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/remote.php(165): require_once('\\\/var\\\/www\\\/virtua...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/MaintenancePlugin.php\",\"Line\":85,\"User\":\"eppfel\"}","level":4,"time":"2016-11-29T12:35:35+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"eppfel","version":"11.0.0.5"}
{"reqId":"GqxvVvgazK8Ub9v20LpE","remoteAddr":"2a02:908:df54:2c20:651d:8201:3cf:dfd0","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 System in maintenance mode.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/remote.php(165): require_once('\\\/var\\\/www\\\/virtua...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/virtual\\\/eppcloud\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/MaintenancePlugin.php\",\"Line\":85,\"User\":\"eppfel\"}","level":4,"time":"2016-11-29T12:36:07+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"eppfel","version":"11.0.0.5"}
{"reqId":"ezmm2+gvVIrpXmesKJXt","remoteAddr":"2a02:908:df54:2c20:651d:8201:3cf:dfd0","app":"core","message":"Trusted domain error. \"2a02:908:df54:2c20:651d:8201:3cf:dfd0\" tried to access using \"epp.earth\" as host.","level":2,"time":"2016-11-29T12:50:23+00:00","method":"GET","url":"\/","user":"--","version":"11.0.0.5"}
{"reqId":"3ouMlsqUDNOZUl9lVnuR","remoteAddr":"2a02:908:df54:2c20:651d:8201:3cf:dfd0","app":"core","message":"App \"Two Factor TOTP Provider\" cannot be installed because the following dependencies are not fulfilled: Server version 9.2 or lower is required.","level":3,"time":"2016-11-29T13:03:30+00:00","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php","user":"eppfel","version":"11.0.0.5"}
{"reqId":"Zw5Ereern5rP1tH5F\/7S","remoteAddr":"2a02:908:df54:2c20:651d:8201:3cf:dfd0","app":"core","message":"App \"News\" cannot be installed because the following dependencies are not fulfilled: Server version 10 or lower is required.","level":3,"time":"2016-11-29T13:10:40+00:00","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php","user":"eppfel","version":"11.0.0.5"}
{"reqId":"9d7431VQ61VN6\/DkxpIY","remoteAddr":"2a02:908:df54:2c20:651d:8201:3cf:dfd0","app":"core","message":"App \"News\" cannot be installed because the following dependencies are not fulfilled: Server version 10 or lower is required.","level":3,"time":"2016-11-29T13:11:01+00:00","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php","user":"eppfel","version":"11.0.0.5"}
{"reqId":"xRP+8mF6Q6v+8fhfz1NX","remoteAddr":"2a02:908:df54:2c20:651d:8201:3cf:dfd0","app":"core","message":"App \"Mail\" cannot be installed because the following dependencies are not fulfilled: Server version 9.2 or lower is required.","level":3,"time":"2016-11-29T13:41:42+00:00","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php","user":"eppfel","version":"11.0.0.5"}

```
</details>

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #2403

We need to check for updates of disabled apps so that if you update with
incompatible apps you at least get a chance to upgrade.

### CODE REVIEW

File: settings/Controller/AppSettingsController.php [hunk 1]
```diff
@@ -296,6 +296,16 @@ public function listApps($category = '') {
 				$apps = array_filter($apps, function ($app) {
 					return !$app['active'];
 				});
+
+				$appFetcher = \OC::$server->getAppFetcher();
+				$apps = array_map(function ($app) use ($appFetcher) {
+					$newVersion = \OC\Installer::isUpdateAvailable($app['id'], $appFetcher);
```
Comment (nickvergessen) [inline settings/Controller/AppSettingsController.php]: Use `$this->appFetcher`

**Review by nickvergessen — CHANGES_REQUESTED** [review]

File: settings/Controller/AppSettingsController.php (hunk 1 above)
Comment (rullzer) [inline settings/Controller/AppSettingsController.php]: ah mmm didn't see it was there...

File: settings/Controller/AppSettingsController.php [hunk 2]
```diff
@@ -296,6 +296,15 @@ public function listApps($category = '') {
 				$apps = array_filter($apps, function ($app) {
 					return !$app['active'];
 				});
+
+				$apps = array_map(function ($app) {
+					$newVersion = \OC\Installer::isUpdateAvailable($app['id'], $this->appFetcher);
+					if ($newVersion !== faslse) {
+						$app['update'] = $newVersion;
```
Comment (ChristophWurst) [inline settings/Controller/AppSettingsController.php]: did you mean 'false'? 🙈

File: settings/Controller/AppSettingsController.php [hunk 3]
```diff
@@ -296,6 +296,15 @@ public function listApps($category = '') {
 				$apps = array_filter($apps, function ($app) {
 					return !$app['active'];
 				});
+
+				$apps = array_map(function ($app) {
+					$newVersion = \OC\Installer::isUpdateAvailable($app['id'], $this->appFetcher);
+					if ($newVersion !== faslse) {
```
Comment (ChristophWurst) [inline settings/Controller/AppSettingsController.php]: did you mean 'false'? 🙈

Comment (rullzer) [inline settings/Controller/AppSettingsController.php]: maybe :stuck_out_tongue:

**Review by nickvergessen — APPROVED** [review]

**Review by LukasReschke — APPROVED** [review]
