### PR TITLE
fix: display chinese character avatar

### LINKED ISSUE #45473: First Character of Chinese or other multi-bytes characters display name
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. Set display name to Chinese or other multi-bytes characters 
2. See the error. It is intended to show the first character. But it is displaying a square.

Web and Android:
Screenshot_20240523_131133_Firefox
Screenshot_20240523_131315_Nextcloud

### Expected behaviour

First character 

### Actual behaviour

square

### Android version

14

### Device brand and model

Samsung S23

### Stock or custom OS?

Stock

### Nextcloud android app version

3.29.0

### Nextcloud server version

Shouldn't matter

### Using a reverse proxy?

Yes

### Android logs

_No response_

### Server error logs

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Phreeman33**
* Resolves: #45473
* Closes: https://github.com/nextcloud/server/pull/42534

## Summary
This PR builds upon #42534 for fixes an issue where Chinese character avatars were not displaying properly. It also applies fonts tailored to the regional variations in Chinese writing conventions. The code was modified by a noob and has only undergone basic testing, so further testing and review may be necessary.

## Screenshots
\u89d2 in SC<br>角(SC)
\u89d2 in TC/HK/JP/KR<br>角(TC HK JP KR)
\u8005 in KR<br>者(KR)
\u8005 in SC/TC/HK/JP<br>者(SC TC HK JP)
\u8aaa in JP/KR<br>說(JP KR)
\u8aaa in SC/TC/HK<br>說(SC TC HK)

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: lib/private/Avatar/Avatar.php [hunk 1]
```diff
@@ -35,20 +37,21 @@ abstract class Avatar implements IAvatar {
...
+		$this->config = $config;
 	}
 
-	/**
-	 * Returns the user display name.
-	 */
-	abstract public function getDisplayName(): string;
-
 	/**
 	 * Returns the first letter of the display name, or "?" if no name given.
```
Comment (susnux) [inline lib/private/Avatar/Avatar.php:51]: This changes seem to be unrelated, can you revert or is there a good reason to change the way the displayname is fetched?

File: lib/private/Avatar/Avatar.php [hunk 2]
```diff
@@ -95,6 +97,24 @@ protected function getAvatarVector(int $size, bool $darkTheme): string {
 		return str_replace($toReplace, [$size, $fill, $fgFill, $text], $this->svgTemplate);
 	}
 
+	protected function getFont(string $userDisplayName): string {
+		if (preg_match('/\p{Han}/u', $userDisplayName) === 1) {
+			switch ($this->config->getUserValue($this->user->getUID(), 'core', 'lang', '')) {
```
Comment (skjnldsv) [inline lib/private/Avatar/Avatar.php:102]: That's a good starting point, but that still means that if I set my lang to English this will still generate a wrong avatar :thinking:

Comment (susnux) [reply lib/private/Avatar/Avatar.php:102]: IIRC there is no other way to detect this, with the regex we only know if there is a CJK character, but you do not know which language. Meaning they all map to the same unicode character, but only differ in rendering defined by the language.
Maybe we should fallback to some of those if it is CJK

File: lib/private/Avatar/Avatar.php [hunk 3]
```diff
@@ -151,7 +171,7 @@ protected function generateAvatar(string $userDisplayName, int $size, bool $dark
 		}
 		imagefilledrectangle($im, 0, 0, $size, $size, $background);
 
-		$font = __DIR__ . '/../../../core/fonts/NotoSans-Regular.ttf';
+		$font = $this->getFont($userDisplayName);
```
Comment (susnux) [inline lib/private/Avatar/Avatar.php:174]: I am not sure how common it is to have roman letter in front of the name, but as the CJK fonts are pretty huge we can improve performance and maybe prevent errors here by using the text only which is rendered (so only check the really needed fonts):

```suggestion
		$font = $this->getFont($text);
```

File: lib/private/Avatar/Avatar.php (hunk 2 above)
Comment (skjnldsv) [reply lib/private/Avatar/Avatar.php:102]: can't we merge the fonts? :thinking:

File: lib/private/Avatar/Avatar.php (hunk 1 above)
Comment (Phreeman33) [reply lib/private/Avatar/Avatar.php:51]: These changes are indeed not necessary. The main reason is that when I examined the getDisplayName() function, I found that it simply wraps a single line: `return $this->user->getDisplayName();`—and I question how much benefit this approach actually provides. However, after further reflection, these modifications seem rather hasty, and I'm not entirely sure whether this function is used elsewhere.

File: lib/private/Avatar/Avatar.php (hunk 2 above)
Comment (susnux) [reply lib/private/Avatar/Avatar.php:102]: @skjnldsv  see https://en.wikipedia.org/wiki/Han_unification

The problem is that they share the same code point for different "glyphs", also if this would be possible this would result in a like 100MB font file which will lead to memory issues with out PHP config of 512MB (and other perf issues).

Also @Phreeman33  I think this is a good solution, but as I noted below please just test the `$text` that is rendered for the CJK characters. Also if it contains CJK characters just fallback to `NotoSansSC` if language is not set to any CJK. `locale` should not be used, this is only for the formatting of number, money, dates and times - it is unrelated to the language of the text or the writing.

Comment (skjnldsv) [reply lib/private/Avatar/Avatar.php:102]: We could also use https://github.com/PhenX/php-font-lib to check if the font contains all the glyph of a string :thinking: 
Ideally I would also just check the first two letters from the `getAvatarText` method. That should avoid checking too many characters.

File: lib/private/Avatar/Avatar.php (hunk 1 above)
Comment (skjnldsv) [reply lib/private/Avatar/Avatar.php:51]: Considering the GuestAvatar construct is different, I'd like to keep the DI out of the abstract class :)

File: lib/private/Avatar/Avatar.php (hunk 3 above)
Comment (Phreeman33) [reply lib/private/Avatar/Avatar.php]: Thanks for the suggestion. I've tested it and submitted the changes.

File: lib/private/Avatar/Avatar.php [hunk 4]
```diff
@@ -108,8 +128,8 @@ protected function generateAvatarFromSvg(int $size, bool $darkTheme): ?string {
 			return null;
 		}
 		try {
-			$font = __DIR__ . '/../../../core/fonts/NotoSans-Regular.ttf';
-			$svg = $this->getAvatarVector($size, $darkTheme);
+			$font = $this->getFont($userDisplayName);
+			$svg = $this->getAvatarVector($userDisplayName, $size, $darkTheme);
```
Comment (Phreeman33) [inline lib/private/Avatar/Avatar.php:132]: This function is missing the input value "string $userDisplayName".

File: lib/private/Avatar/Avatar.php (hunk 2 above)
Comment (susnux) [reply lib/private/Avatar/Avatar.php:102]: > Ideally I would also just check the first two letters from the getAvatarText method. That should avoid checking too many characters.

Already done below, it gets only passed the text that is rendered (the letter).

> We could also use https://github.com/PhenX/php-font-lib to check if the font contains all the glyph of a string 🤔

As said this does not work as they are the same but only different design due to language (all of this are based on the same code point but differ in design depending on language):
https://en.wikipedia.org/wiki/Han_unification#/media/File:Source_Han_Sans_Version_Difference.svg

**Review by susnux — COMMENTED** [review]
@Phreeman33 could you please revert all other changes to keep the abstract `getDisplayName` method?
The only changes needed in this PR are:
- `getFont`
- `generateAvatar`
- the regular fonts

File: core/fonts/NotoSansHK-Bold.ttf
Comment (susnux) [inline core/fonts/NotoSansHK-Bold.ttf:1]: not needed?

File: core/fonts/NotoSansJP-Bold.ttf
Comment (susnux) [inline core/fonts/NotoSansJP-Bold.ttf:1]: not needed?

File: core/fonts/NotoSansKR-Bold.ttf
Comment (susnux) [inline core/fonts/NotoSansKR-Bold.ttf:1]: not needed?

File: core/fonts/NotoSansSC-Bold.ttf
Comment (susnux) [inline core/fonts/NotoSansSC-Bold.ttf:1]: not needed?

File: core/fonts/NotoSansTC-Bold.ttf
Comment (susnux) [inline core/fonts/NotoSansTC-Bold.ttf:1]: not needed?

File: lib/private/Avatar/Avatar.php (hunk 2 above)
Comment (skjnldsv) [reply lib/private/Avatar/Avatar.php:102]: Ok, I guess I'm lacking the knowledge for this :)

**Comment by Phreeman33** [comment]
@susnux
Done! Please review the code.

File: lib/private/Avatar/Avatar.php [hunk 5]
```diff
@@ -95,21 +96,44 @@ protected function getAvatarVector(int $size, bool $darkTheme): string {
 		return str_replace($toReplace, [$size, $fill, $fgFill, $text], $this->svgTemplate);
 	}
 
+	/**
+	 * Select the rendering font based on the user's display name and language 
+	 */
+	private function getFont(string $userDisplayName): string {
+		if (preg_match('/\p{Han}/u', $userDisplayName) === 1) {
+			$userlang = $this->config->getUserValue($this->user->getUID(), 'core', 'lang', '');
```
Comment (susnux) [inline lib/private/Avatar/Avatar.php:104]: `$this->config` as well as `$this->user` does not exist on the `Avatar` class

Comment (susnux) [reply lib/private/Avatar/Avatar.php:104]: Maybe add a `protected` method in Avatar like `getLanguage` which just returns the system default language.
In `UserAvatar` you override this to provide the user language.

**Comment by skjnldsv** [comment]
@susnux anything else you think needs to be addressed ?

**Comment by susnux** [comment]
> anything else you think needs to be addressed ?

@skjnldsv yes the psalm error was related. I fixed that one and now it should be fine.
Tested it also locally and it seems to work perfectly :heavy_check_mark:

**Review by susnux — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by susnux** [comment]
@Phreeman33 thank you for your PR :sparkles:
