### PR TITLE
Fix distorted previews when using imaginary

### LINKED ISSUE #323: Some images generated with imaginary are incorrect
Some square preview images generated with command
`$ occ preview:generate-all -vvv`
are a crop of the original images and the aspect ratio are not preserved.
On the other hand, the square preview images generated by web interface of Nextcloud are correctly. They respect the aspect ratios and letterboxed correctly.

Environment:

- Nextcloud docker: linuxserver/nextcloud:latest

> - Nextcloud version 24.0.6
> - previewgenerator version 5.1.0

- imaginary docker: h2non/imaginary:latest

> - Imaginary version 1.2.4

- host OS: DSM 7.1.1-42962 Update 1
- hardware: Synology DS-918+

The content of the config.php:
```
<?php
$CONFIG = array (
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'redis',
    'port' => 6379,
    'timeout' => 1.5,
  ),
  'filelocking.enabled' => true,
  'datadirectory' => '/data',
  'instanceid' => '<omitted for security>',
  'passwordsalt' => '<omitted for security>',
  'secret' => '<omitted for security>',
  'trusted_domains' => 
  array (
    0 => '<omitted> for security>',
  ),
  'dbtype' => 'mysql',
  'version' => '24.0.6.1',
  'trusted_proxies' => ['swag'],
  'overwrite.cli.url' => '<omitted for security>',
  'dbname' => 'nextcloud',
  'dbhost' => '10.27.0.40:3306',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => '<omitted for security>',
  'dbpassword' => '<omitted for security>',
  'installed' => true,
  'app_install_overwrite' => 
  array (
    0 => 'files_excludedirs',
  ),
  'default_phone_region' => 'GB',
  'maintenance' => false,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'ssl',
  'mail_sendmailmode' => 'smtp',
  'mail_smtpauth' => 1,
  'mail_from_address' => 'No.Reply',
  'mail_domain' => '<omitted for security>',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => '<omitted for security>',
  'mail_smtpport' => '465',
  'mail_smtpname' => '<omitted for security>',
  'mail_smtppassword' => '<omitted for security>',
  'preview_max_x' => null,
  'preview_max_y' => null,
  'jpeg_quality' => '60',
  'preview_max_scale_factor' => 1,
  'enabledPreviewProviders' => [
    'OC\Preview\MP3',
    'OC\Preview\TXT',
    'OC\Preview\MarkDown',
    'OC\Preview\OpenDocument',
    'OC\Preview\Krita',
    'OC\Preview\Imaginary',
  ],
  'preview_imaginary_url' => 'http://imaginary:9000',
);
```

The previewgenerator settings:
```
$ php /config/www/nextcloud/occ config:app:get previewgenerator squareSizes
64 256 1024
$ php /config/www/nextcloud/occ config:app:get previewgenerator widthSizes
64 256 1024
$ php /config/www/nextcloud/occ config:app:get previewgenerator heightSizes
64 256 1024
```

A sample of an original image: 
200042733-9284683a-bf54-4180-b0e4-63faba51b630

The preview generated for both grid view and detailed view on the Files pane.
200042792-55a96c2c-3ce2-4390-b3f3-6d4aa512268d

Another example of an original image:
200041760-34ad1f18-4f18-42bc-8549-486b11ad6d82

The preview generated for both grid view and detailed view on the Files pane.
200042005-39e74c9b-b6ce-4833-a9f8-e82b23ada8c3

### PR DESCRIPTION
**Pull request by st3iny**
Fix https://github.com/nextcloud/previewgenerator/issues/323

Imaginary upstream has introduced the possibility to send width and height of the outputted image along with the request. However, the decision was made that this feature is optional and gated behind a cli parameter (`-return-size`).

Ref https://github.com/h2non/imaginary/pull/382
Ref https://github.com/h2non/imaginary/pull/382/files#diff-77ed712c0c6f7b52686415504853bc522f5f0ee3e9e0399cfd60a48813aa6aaeR110

## Problem

Our code relies on the presence of those headers. If they aren't present, the max values are used as default and thus previews might be distorted. Especially smaller images are affected.

## Reproducability

Use both images from the linked issue and generate previews. You'll see that they are always distorted.

With my patch applied they are correct. It doesn't matter if the flag of Imaginary is enabled or not. The performance is slightly better if the flag is enabled.

## Documentation

I plan to add a hint to the server tuning docs. We should recommend using the flag by default to admins.

Ref https://docs.nextcloud.com/server/latest/admin_manual/installation/server_tuning.html#previews

### CODE REVIEW

File: lib/private/Preview/Imaginary.php [hunk 1]
```diff
@@ -126,12 +127,21 @@ public function getCroppedThumbnail(File $file, int $maxX, int $maxY, bool $crop
 			return null;
 		}
 
-		if ($response->getHeader('X-Image-Width') && $response->getHeader('X-Image-Height')) {
-			$maxX = (int)$response->getHeader('X-Image-Width');
-			$maxY = (int)$response->getHeader('X-Image-Height');
```
Comment (szaimen) [inline lib/private/Preview/Imaginary.php:131]: Lets wait for @CarlSchwan to chwck if it is okay to not check for this header anymore. It might be possibke that we brake some instances otherwise

**Review by CarlSchwan — APPROVED** [review]

File: lib/private/Preview/Imaginary.php (hunk 1 above)
Comment (CarlSchwan) [reply lib/private/Preview/Imaginary.php:131]: This will break one instance using my fork of imaginary. I'll communicate this to them after my vacation

Comment (CarlSchwan) [reply lib/private/Preview/Imaginary.php:131]: Alternative we need to convince the imaginary maintainer that using a X- prefix for custom headers is more correct.

Comment (szaimen) [reply lib/private/Preview/Imaginary.php:131]: I thought so. Thanks Carl! :)

Comment (st3iny) [reply lib/private/Preview/Imaginary.php:131]: Right, I should probably keep the old headers as a fallback. Just in case someone is using a custom version of Imaginary with Carls original patch.

**Review by szaimen — APPROVED** [review]
LGTM but didn't test
