### PR TITLE
fix showing of all apps are up-to-date in apps management

### LINKED ISSUE #31915: [Bug]: index.php/settings/apps incorrectly shows "All apps are up-to-date." while there is 1 not up-to-date
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The displayed status for available updates is wrong under some conditions.
- Under "Your apps" and "Updates" shows "All apps are up-to-date." when there is one update available.
- Under "Active apps" shows "All apps are up-to-date." when one and two updates (maybe more) are available.

### Steps to reproduce

1. Nextcloud v23.0.3 and Nextcloud 24.0.0 beta 3
2. 1 or more updates for apps available
3. check index.php/settings/apps etc. for the status line above the apps list

(Your apps, 1 update, 24.0.0 beta 3)

(Your apps, 1 update, 23.0.3)

(Active apps, 2 updates)

### Expected behavior

Displaying the actual count of available updates.

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "frija.kleines-miststueck.de",
            "nc.march42.net",
            "march42.net",
            "kleines-miststueck.de",
            "enyo.kleines-miststueck.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.3.2",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "pipe",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "default_language": "de",
        "default_locale": "de_DE",
        "default_phone_region": "DE",
        "logtimezone": "Europe\/Berlin",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": "true",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "timeout": 2,
            "dbindex": 2
        },
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "preview_max_x": 600,
        "preview_max_y": 600,
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\TXT",
            "OC\\Preview\\Markdown",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\PDF"
        ],
        "enable_previews": true,
        "filelocking.enabled": true
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.15.0
  - backup: 1.0.6
  - calendar: 3.2.2
  - circles: 23.1.0
  - cloud_federation_api: 1.6.0
  - contacts: 4.1.0
  - contactsinteraction: 1.4.0
  - dav: 1.21.0
  - deck: 1.6.1
  - duplicatefinder: 0.0.13
  - event_update_notification: 1.5.0
  - external: 3.10.2
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_external: 1.15.0
  - files_pdfviewer: 2.4.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - fileslibreofficeedit: 1.0.4
  - groupfolders: 11.1.2
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - mail: 1.11.7
  - metadata: 0.15.0
  - notes: 4.3.1
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - previewgenerator: 4.0.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - spreed: 13.0.5
  - systemtags: 1.13.0
  - text: 3.4.1
  - theming: 1.14.0
  - transfer: 0.2.1
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_ldap: 1.13.1
  - user_status: 1.3.1
  - viewer: 1.7.0
  - workflowengine: 2.5.0
Disabled:
  - accessibility: 1.9.0
  - admin_audit
  - comments: 1.13.0
  - dashboard: 7.3.0
  - encryption
  - files_antivirus: 3.2.2
  - files_rightclick: 1.2.0
  - firstrunwizard: 2.12.0
  - gpgmailer: 0.0.4
  - nextcloud_announcements: 1.12.0
  - recommendations: 1.2.0
  - richdocuments: 5.0.3
  - richdocumentscode: 21.11.204
  - support: 1.6.0
  - survey_client: 1.11.0
  - weather_status: 1.3.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"MQVHJoaOfUlBNJuttNuN","level":3,"time":"2022-04-08T23:22:15+02:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"OC_Image::fixOrientation(): No image loaded","userAgent":"--","version":"23.0.3.2"}
{"reqId":"MQVHJoaOfUlBNJuttNuN","level":3,"time":"2022-04-08T23:22:18+02:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"OC_Image::fixOrientation(): No image loaded","userAgent":"--","version":"23.0.3.2"}
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by szaimen**
Fix https://github.com/nextcloud/server/issues/31915

Signed-off-by: szaimen <szaimen@e.mail.de>

<details>
<summary>For my own testing</summary>

```
docker run -it \
-e SERVER_BRANCH=fix/31915/up-to-date-fix \
-p 8443:443 \
-e TRUSTED_DOMAIN=192.168.146.128 \
--name nextcloud-easy-test \
ghcr.io/szaimen/nextcloud-easy-test:latest
```

</details>

### CODE REVIEW

File: apps/settings/src/components/AppList.vue [hunk 1]
```diff
@@ -125,10 +125,10 @@ export default {
 			return this.$store.getters.loading('list')
 		},
 		hasPendingUpdate() {
-			return this.apps.filter(app => app.update).length > 1
+			return this.apps.filter(app => app.update).length > 0
```
Comment (szaimen) [inline apps/settings/src/components/AppList.vue:128]: not sure if it is expected that the updateall button shows up if only one update is available...

File: apps/settings/src/components/AppList.vue [hunk 2]
```diff
@@ -125,10 +125,10 @@ export default {
...
 		},
 		showUpdateAll() {
-			return this.hasPendingUpdate && ['installed', 'updates'].includes(this.category)
+			return this.hasPendingUpdate && ['installed', 'updates', 'enabled'].includes(this.category)
```
Comment (szaimen) [inline apps/settings/src/components/AppList.vue:131]: should we also add 'disabled' here?

File: apps/settings/src/components/AppList.vue (hunk 1 above)
Comment (GretaD) [reply apps/settings/src/components/AppList.vue:128]: Update all should show only if theres at least 2 apps, otherwise "all" doesnt make too much sense i would say

File: apps/settings/src/components/AppList.vue (hunk 2 above)
Comment (GretaD) [reply apps/settings/src/components/AppList.vue:131]: technically shouldnt be shown on the disabled one. I dont think people would be interested on updating disabled apps

Comment (szaimen) [reply apps/settings/src/components/AppList.vue:131]: good point but lets cc @jancborchardt and @nimishavijay on this :)

File: apps/settings/src/components/AppList.vue (hunk 1 above)
Comment (szaimen) [reply apps/settings/src/components/AppList.vue:128]: also good point... I guess @jancborchardt and @nimishavijay should probably decide then :)

File: apps/settings/src/components/AppList.vue (hunk 2 above)
Comment (nimishavijay) [reply apps/settings/src/components/AppList.vue:131]: > I dont think people would be interested on updating disabled apps

Agreed, I don't think it's necessary either

Comment (szaimen) [reply apps/settings/src/components/AppList.vue:131]: fine, then lets leave it like this 👍

File: apps/settings/src/components/AppList.vue (hunk 1 above)
Comment (szaimen) [reply apps/settings/src/components/AppList.vue:128]: ping @nimishavijay :)

File: apps/settings/src/components/AppList.vue (hunk 2 above)
Comment (szaimen) [reply apps/settings/src/components/AppList.vue:131]: just reopening this: is it possible that app updates show up on the disabled page? Maybe @skjnldsv knows?

File: apps/settings/src/components/AppList.vue (hunk 1 above)
Comment (nimishavijay) [reply apps/settings/src/components/AppList.vue:128]: Both could work... I like the idea of showing the message on top so that an admin can just click the same button everytime to update, but as Greta said "Update all" doesn't with if there is only one update.

What do you think about showing a message "1 app has an update available. [Update button]" if there is only 1 update available?

Comment (szaimen) [reply apps/settings/src/components/AppList.vue:128]: Good idea! at least the description is already implemented like this: https://github.com/nextcloud/server/blob/b897db3020b4fed05dc3da3ebe3cccbe5d9d7944/apps/settings/src/components/AppList.vue#L28
What could the update button in the case of only one update state? https://github.com/nextcloud/server/blob/b897db3020b4fed05dc3da3ebe3cccbe5d9d7944/apps/settings/src/components/AppList.vue#L33

File: apps/settings/src/components/AppList.vue (hunk 2 above)
Comment (szaimen) [reply apps/settings/src/components/AppList.vue]: lets do it differently.

File: apps/settings/src/components/AppList.vue [hunk 3]
```diff
@@ -125,10 +125,10 @@ export default {
 			return this.$store.getters.loading('list')
 		},
 		hasPendingUpdate() {
-			return this.apps.filter(app => app.update).length > 1
+			return this.apps.filter(app => app.update).length > 0
 		},
 		showUpdateAll() {
-			return this.hasPendingUpdate && ['installed', 'updates'].includes(this.category)
+			return this.hasPendingUpdate && this.useListView
```
Comment (szaimen) [inline apps/settings/src/components/AppList.vue:131]: I think this is the best fix because we now handle this in one method:
https://github.com/nextcloud/server/blob/2a5e455d8d80e9103a8449d87f631f37eae29934/apps/settings/src/components/AppList.vue#L193

File: apps/settings/src/components/AppList.vue [hunk 4]
```diff
@@ -30,7 +30,7 @@
 						id="app-list-update-all"
 						type="primary"
 						@click="updateAll">
-						{{ t('settings', 'Update all') }}
+						{{ n('settings', 'Update', 'Update all', counter) }}
```
[the remark this answers is not in the document]
Comment (szaimen) [reply apps/settings/src/components/AppList.vue:33]: in case of 1 app update: `Update` and in case of multiple: `Update all`

**Comment by szaimen** [comment]
@GretaD does this look good to you now? :)

File: apps/settings/src/components/AppList.vue (hunk 4 above)
[the remark this answers is not in the document]
Comment (nimishavijay) [reply apps/settings/src/components/AppList.vue:33]: Sounds great! 🚀  :)

[the remark this answers is not in the document]
Comment (szaimen) [reply apps/settings/src/components/AppList.vue:33]: cool :)

File: apps/settings/src/components/AppList.vue (hunk 1 above)
Comment (szaimen) [reply apps/settings/src/components/AppList.vue:128]: implemented

File: apps/settings/src/components/AppList.vue (hunk 4 above)
[the remark this answers is not in the document]
Comment (szaimen) [reply apps/settings/src/components/AppList.vue:33]: I think it should indeed work

**Review by skjnldsv — APPROVED** [review]

**Review by come-nc — APPROVED** [review]

File: apps/settings/src/components/AppList.vue (hunk 1 above)
Comment (jancborchardt) [reply apps/settings/src/components/AppList.vue:128]: > What could the update button in the case of only one update state? 

@szaimen not sure if you already did that, but if it’s only 1 app, the button can simply be labeled "Update". :)

Comment (szaimen) [reply apps/settings/src/components/AppList.vue:128]: yes, already implemented like this :)
