### PR TITLE
Remove posix_getpwuid and compare only userid

### LINKED ISSUE #11088: [NC14] Error while checking server setup
### Steps to reproduce
1. Login as Admin
2. Go to Settings -> Administration -> Overview

### Expected behaviour
Checking server setup should pass.

### Actual behaviour
Get error under "Security & setup warning"

grafik

### Server configuration

**Operating system**: CentsOS 7.5

**Web server:** nginx 1.15.3

**Database:** mariadb 10.3.9

**PHP version:** 7.2.9

**Nextcloud version:** 14.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** yes

**Where did you install Nextcloud from:** docker image

**Signing status:**
The error is about the server setup checking.

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox 62.0

**Operating system:** ArchLinux

#### Web server error log
nothing here

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"qruZgYucXWF7sk27q0O9","level":3,"time":"2018-09-06T12:57:27+02:00","remoteAddr":"xx.xx.xx.x","user":"admin_user","app":"index","method":"GET","url":"\/settings\/ajax\/checksetup","message":"Exception":"TypeError","Message":"Argument 1 passed to OC\\Settings\Controller\\CheckSetupController::getAppDirsWithDifferentOwnerForAppRoot() must be of the type array, boolean given, called in \/nextcloud\/settings\/Controller\/CheckSetupController.php on line 551","Code":0,"Trace":[{"file":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","line":551,"function":"getAppDirsWithDifferentOwnerForAppRoot","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[false,{"path":"\/apps2","url":"\/apps2","writable":true}]},{"file":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","line":624,"function":"getAppDirsWithDifferentOwner","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"check","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\CheckSetupController"},"check"]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\CheckSetupController"},"check"]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Settings\\Controller\\CheckSetupController","check",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"settings.CheckSetup.check"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":{"_route":"settings.CheckSetup.check"}]},{"file":"\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"settings.CheckSetup.check"}]},{"file":"\/nextcloud\/lib\/base.php","line":989,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/settings\/ajax\/checksetup"]},{"file":"\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","Line":568,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:62.0) Gecko\/20100101 Firefox\/62.0","version":"14.0.0.19"}
```
</details>

#### Browser log
nothing

### LINKED ISSUE #11089: error after update from 13.0.6 to 14.0.0
### Steps to reproduce
Updateing from Nextcloud 13.0.6 to 14.0.0.
The Nextcloud has no obvious problems but now I get following errors inside the logs:

### Actual behaviour
```
TypeError: Argument 1 passed to OC\Settings\Controller\CheckSetupController::getAppDirsWithDifferentOwnerForAppRoot() must be of the type array, boolean given, called in /nextcloud/settings/Controller/CheckSetupController.php on line 551

    /nextcloud/settings/Controller/CheckSetupController.php - line 551: OC\Settings\Controller\CheckSetupController->getAppDirsWithDifferentOwnerForAppRoot(false, { path: "/apps2", url: "/apps2", writable: true})

    /nextcloud/settings/Controller/CheckSetupController.php - line 624: OC\Settings\Controller\CheckSetupController->getAppDirsWithDifferentOwner()

    /nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 166: OC\Settings\Controller\CheckSetupController->check()

    /nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99:  OC\AppFramework\Http\Dispatcher->executeController(OC\Settings\Controller\CheckSetupController{}, "check")

    /nextcloud/lib/private/AppFramework/App.php - line 118:  OC\AppFramework\Http\Dispatcher->dispatch(OC\Settings\Controller\CheckSetupController{}, "check")

    /nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:   OC\AppFramework\App::main("OC\\Settings\\Controller\\CheckSetupController", "check", OC\AppFramework\DependencyInjection\DIContainer{}, { _route: "settig.CheckSetup.check})

    OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "settig.CheckSetup.check "}) 

    /nextcloud/lib/private/Route/Router.php - line 297:  call_user_func(OC\AppFramework\Routing\RouteAction\Handler {}, { _route: "settig.CheckSetup.check"})

    /nextcloud/lib/base.php - line 989:    OC\Route\Router->match("/settings/ajax/checksetup")

    /nextcloud/index.php - line 42:     OC::handleRequest()
```

### Server configuration

**Operating system**:
Ubuntu 18.04 LTS (Bionic Beaver)
**Web server:**
NGINX Stable 

**Database:**
MySQL

**PHP version:**
PHP 7.2.9

**Nextcloud version:** (see Nextcloud admin page)
14.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updating from 13.0.6 

**Where did you install Nextcloud from:**
local docker image 

**Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.**
No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
/ # occ app:list
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_audit: 1.4.0
  - bruteforcesettings: 1.1.0
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.0
  - end_to_end_encryption: 1.0.5
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_external: 1.5.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - mail: 0.10.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - richdocuments: 2.0.11
  - serverinfo: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - drawio
  - encryption
  - passwords
  - sharebymail
  - spreed
  - twofactor_totp
  - user_external
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder


/ # occ config:list system
{
    "system": {
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "apps_paths": [
            {
                "path": "\/nextcloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/apps2",
                "url": "\/apps2",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "logdateformat": "Y-m-d H:i:s",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.example.org"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.example.org",
        "dbtype": "mysql",
        "version": "14.0.0.19",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 2,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpport": "587",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, SMB

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Firefox 61.02
**Operating system:**
Win10 Pro x64

#### Web server error log
<details>
<summary>Web server error log</summary>

```
10.0.10.127 - - [06/Sep/2018:11:07:36 +0000] "GET /apps/logreader/poll?lastReqId=jwTW91TD66Pn32Nbes4A HTTP/2.0" 200 2 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0"
10.0.10.127 - - [06/Sep/2018:11:07:56 +0000] "GET /apps/logreader/poll?lastReqId=jwTW91TD66Pn32Nbes4A HTTP/2.0" 200 2 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0"
10.0.10.127 - - [06/Sep/2018:11:07:58 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 200 74 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0"

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:20","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::maintenanceEnabled: Turned on maintenance mode","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":0,"time":"2018-09-06 12:03:20","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"starting upgrade from 13.0.6.1 to 14.0.0.19","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:20","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Repair MySQL collation","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:20","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: All tables already have the correct collation -> nothing to do","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:20","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Repair SQLite autoincrement","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:20","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Copy data from accounts table when migrating from ownCloud","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:23","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Drop account terms table when migrating from ownCloud","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:23","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::dbUpgradeBefore: Updating database schema","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:32","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::dbUpgrade: Updated database","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:32","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::incompatibleAppDisabled: Disabled incompatible app: drawio","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:32","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::incompatibleAppDisabled: Disabled incompatible app: spreed","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:32","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::incompatibleAppDisabled: Disabled incompatible app: twofactor_totp","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:32","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgradeStarted: Updating <federatedfilesharing> ...","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:32","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgrade: Updated <federatedfilesharing> to 1.4.0","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:32","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgradeStarted: Updating <files_pdfviewer> ...","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:33","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgrade: Updated <files_pdfviewer> to 1.3.2","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:33","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgradeStarted: Updating <files_texteditor> ...","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:33","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgrade: Updated <files_texteditor> to 2.6.0","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:33","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgradeStarted: Updating <files_videoplayer> ...","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:34","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgrade: Updated <files_videoplayer> to 1.3.0","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:34","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgradeStarted: Updating <gallery> ...","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:34","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgrade: Updated <gallery> to 18.1.0","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:34","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgradeStarted: Updating <password_policy> ...","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:35","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgrade: Updated <password_policy> to 1.4.0","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:35","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgradeStarted: Updating <provisioning_api> ...","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:35","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgrade: Updated <provisioning_api> to 1.4.0","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:35","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgradeStarted: Updating <serverinfo> ...","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:36","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgrade: Updated <serverinfo> to 1.4.0","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:36","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgradeStarted: Updating <survey_client> ...","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:36","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgrade: Updated <survey_client> to 1.2.0","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:36","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgradeStarted: Updating <twofactor_backupcodes> ...","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:38","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgrade: Updated <twofactor_backupcodes> to 1.3.1","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:38","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgradeStarted: Updating <updatenotification> ...","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:38","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgrade: Updated <updatenotification> to 1.4.1","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:38","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgradeStarted: Updating <federation> ...","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:39","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgrade: Updated <federation> to 1.4.0","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:39","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgradeStarted: Updating <lookup_server_connector> ...","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:39","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgrade: Updated <lookup_server_connector> to 1.2.0","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:39","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgradeStarted: Updating <oauth2> ...","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:40","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Update OAuth token expiration times","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:40","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgrade: Updated <oauth2> to 1.2.1","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:40","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgradeStarted: Updating <files> ...","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:40","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgrade: Updated <files> to 1.9.0","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:40","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgradeStarted: Updating <activity> ...","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:40","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgrade: Updated <activity> to 2.7.0","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:40","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgradeStarted: Updating <dav> ...","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:44","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Fix component of birthday calendars","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:44","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: 2 birthday calendars updated.","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:44","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Fix broken values of calendar objects","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:44","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::startProgress: Starting ... Fix broken values of calendar objects (0)","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:44","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::finishProgress","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:44","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Registering building of calendar search index as background job","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:44","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: Repair step already executed","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:44","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgrade: Updated <dav> to 1.6.0","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:44","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgradeStarted: Updating <files_external> ...","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:45","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgrade: Updated <files_external> to 1.5.0","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:45","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgradeStarted: Updating <files_sharing> ...","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:45","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Fix the share type of guest shares when migrating from ownCloud","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:45","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Copy the share password into the dedicated column","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:45","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgrade: Updated <files_sharing> to 1.6.2","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:45","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgradeStarted: Updating <files_trashbin> ...","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:46","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgrade: Updated <files_trashbin> to 1.4.1","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:46","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgradeStarted: Updating <files_versions> ...","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:46","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgrade: Updated <files_versions> to 1.7.1","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:46","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgradeStarted: Updating <workflowengine> ...","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:47","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgrade: Updated <workflowengine> to 1.4.0","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:47","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgradeStarted: Updating <admin_audit> ...","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:47","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgrade: Updated <admin_audit> to 1.4.0","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:47","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgradeStarted: Updating <comments> ...","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:48","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgrade: Updated <comments> to 1.4.0","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:48","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgradeStarted: Updating <firstrunwizard> ...","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:48","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgrade: Updated <firstrunwizard> to 2.3.0","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:48","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgradeStarted: Updating <nextcloud_announcements> ...","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:49","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgrade: Updated <nextcloud_announcements> to 1.3.0","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:49","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgradeStarted: Updating <notifications> ...","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:49","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgrade: Updated <notifications> to 2.2.1","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:49","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgradeStarted: Updating <systemtags> ...","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:50","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgrade: Updated <systemtags> to 1.4.0","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:50","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgradeStarted: Updating <theming> ...","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:50","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::appUpgrade: Updated <theming> to 1.5.0","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:50","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"activity\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":0,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":"No cache entry found for \/appdata_ocadc83b19e7\/preview\/4 (storage: local::\/data\/, internalPath: appdata_ocadc83b19e7\/preview\/4)","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"activity\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"admin_audit\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"admin_audit\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"bruteforcesettings\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"bruteforcesettings\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"cloud_federation_api\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"cloud_federation_api\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"comments\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"comments\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"dav\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"dav\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"end_to_end_encryption\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"end_to_end_encryption\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"federatedfilesharing\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"federatedfilesharing\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"federation\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"federation\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"files\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"files\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"files_external\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"files_external\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"files_pdfviewer\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"files_pdfviewer\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"files_sharing\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"files_sharing\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"files_texteditor\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"files_texteditor\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"files_trashbin\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"files_trashbin\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"files_versions\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"files_versions\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"files_videoplayer\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"files_videoplayer\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"firstrunwizard\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"firstrunwizard\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"gallery\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"gallery\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"logreader\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"logreader\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"lookup_server_connector\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"lookup_server_connector\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"mail\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:03:51","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::upgradeAppStoreApp: Update app \"mail\" from appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Purify and migrate collected mail addresses","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::startProgress: Starting ... Purify and migrate collected mail addresses (0)","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::finishProgress","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"mail\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"nextcloud_announcements\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"nextcloud_announcements\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"notifications\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"notifications\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"oauth2\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"oauth2\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"password_policy\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"password_policy\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"provisioning_api\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"provisioning_api\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"richdocuments\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"richdocuments\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"serverinfo\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"serverinfo\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"survey_client\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"survey_client\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"systemtags\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"systemtags\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"theming\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"theming\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"twofactor_backupcodes\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"twofactor_backupcodes\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"updatenotification\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"updatenotification\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"workflowengine\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"workflowengine\" in appstore","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:03","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Repair MySQL collation","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:03","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: All tables already have the correct collation -> nothing to do","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:04:03","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Repair mime types","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:05:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: Fixed visio mime types","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:05:57","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Clean tags and favorites","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:05:57","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: 0 tags of deleted users have been removed.","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:05:57","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: 0 tags for delete files have been removed.","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:05:57","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: 0 tag entries for deleted tags have been removed.","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:05:57","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: 0 tags with no entries have been removed.","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:05:57","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Repair invalid shares","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:05:58","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Remove shares of a users root folder","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:05:58","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Move .step file of updater to backup location","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:05:58","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Fix potential broken mount points","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:05:58","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: No mounts updated","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:05:58","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Repair invalid paths in file cache","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:05:58","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Add log rotate job","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:05:58","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Clear frontend caches","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:05:58","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: Image cache cleared","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:05:59","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: SCSS cache cleared","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:06:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: JS cache cleared","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:06:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Add preview background cleanup job","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:06:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Queue a one-time job to cleanup old backups of the updater","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:06:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Repair pending cron jobs","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:06:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: Repaired 6 pending cron job(s).","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:06:01","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::startCheckCodeIntegrity: Starting code integrity check...","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:06:23","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::finishedCheckCodeIntegrity: Finished code integrity check","userAgent":"--","version":"13.0.6.1"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:06:23","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::updateEnd: Update successful","userAgent":"--","version":"14.0.0.19"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:06:23","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::maintenanceDisabled: Turned off maintenance mode","userAgent":"--","version":"14.0.0.19"}
{"reqId":"Cv0xdIrn1xtsga6Ani0x","level":1,"time":"2018-09-06 12:06:23","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::resetLogLevel: Reset log level to Warning(2)","userAgent":"--","version":"14.0.0.19"}
{"reqId":"YukBEfvzH0P1WWq7cQox","level":3,"time":"2018-09-06 12:08:48","remoteAddr":"172.29.0.1","user":"cloudadmin","app":"index","method":"GET","url":"\/settings\/ajax\/checksetup","message":{"Exception":"TypeError","Message":"Argument 1 passed to OC\\Settings\\Controller\\CheckSetupController::getAppDirsWithDifferentOwnerForAppRoot() must be of the type array, boolean given, called in \/nextcloud\/settings\/Controller\/CheckSetupController.php on line 551","Code":0,"Trace":[{"file":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","line":551,"function":"getAppDirsWithDifferentOwnerForAppRoot","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[false,{"path":"\/apps2","url":"\/apps2","writable":true}]},{"file":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","line":624,"function":"getAppDirsWithDifferentOwner","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"check","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\CheckSetupController"},"check"]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\CheckSetupController"},"check"]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Settings\\Controller\\CheckSetupController","check",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"settings.CheckSetup.check"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"settings.CheckSetup.check"}]},{"file":"\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"settings.CheckSetup.check"}]},{"file":"\/nextcloud\/lib\/base.php","line":989,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/settings\/ajax\/checksetup"]},{"file":"\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","Line":568,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko\/20100101 Firefox\/61.0","version":"14.0.0.19"}
{"reqId":"1YojbTRjbjv5DefYT644","level":3,"time":"2018-09-06 12:08:50","remoteAddr":"172.29.0.1","user":"cloudadmin","app":"index","method":"GET","url":"\/settings\/ajax\/checksetup","message":{"Exception":"TypeError","Message":"Argument 1 passed to OC\\Settings\\Controller\\CheckSetupController::getAppDirsWithDifferentOwnerForAppRoot() must be of the type array, boolean given, called in \/nextcloud\/settings\/Controller\/CheckSetupController.php on line 551","Code":0,"Trace":[{"file":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","line":551,"function":"getAppDirsWithDifferentOwnerForAppRoot","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[false,{"path":"\/apps2","url":"\/apps2","writable":true}]},{"file":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","line":624,"function":"getAppDirsWithDifferentOwner","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"check","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\CheckSetupController"},"check"]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\CheckSetupController"},"check"]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Settings\\Controller\\CheckSetupController","check",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"settings.CheckSetup.check"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"settings.CheckSetup.check"}]},{"file":"\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"settings.CheckSetup.check"}]},{"file":"\/nextcloud\/lib\/base.php","line":989,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/settings\/ajax\/checksetup"]},{"file":"\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","Line":568,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko\/20100101 Firefox\/61.0","version":"14.0.0.19"}
{"reqId":"ghJbdGy703Iti0gUQmlC","level":3,"time":"2018-09-06 12:11:46","remoteAddr":"172.29.0.1","user":"cloudadmin","app":"index","method":"GET","url":"\/settings\/ajax\/checksetup","message":{"Exception":"TypeError","Message":"Argument 1 passed to OC\\Settings\\Controller\\CheckSetupController::getAppDirsWithDifferentOwnerForAppRoot() must be of the type array, boolean given, called in \/nextcloud\/settings\/Controller\/CheckSetupController.php on line 551","Code":0,"Trace":[{"file":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","line":551,"function":"getAppDirsWithDifferentOwnerForAppRoot","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[false,{"path":"\/apps2","url":"\/apps2","writable":true}]},{"file":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","line":624,"function":"getAppDirsWithDifferentOwner","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"check","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\CheckSetupController"},"check"]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\CheckSetupController"},"check"]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Settings\\Controller\\CheckSetupController","check",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"settings.CheckSetup.check"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"settings.CheckSetup.check"}]},{"file":"\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"settings.CheckSetup.check"}]},{"file":"\/nextcloud\/lib\/base.php","line":989,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/settings\/ajax\/checksetup"]},{"file":"\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","Line":568,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko\/20100101 Firefox\/61.0","version":"14.0.0.19"}
{"reqId":"PpjIWn8QhwGZA62fRIoR","level":3,"time":"2018-09-06 12:13:53","remoteAddr":"172.29.0.1","user":"cloudadmin","app":"index","method":"GET","url":"\/settings\/ajax\/checksetup","message":{"Exception":"TypeError","Message":"Argument 1 passed to OC\\Settings\\Controller\\CheckSetupController::getAppDirsWithDifferentOwnerForAppRoot() must be of the type array, boolean given, called in \/nextcloud\/settings\/Controller\/CheckSetupController.php on line 551","Code":0,"Trace":[{"file":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","line":551,"function":"getAppDirsWithDifferentOwnerForAppRoot","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[false,{"path":"\/apps2","url":"\/apps2","writable":true}]},{"file":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","line":624,"function":"getAppDirsWithDifferentOwner","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"check","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\CheckSetupController"},"check"]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\CheckSetupController"},"check"]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Settings\\Controller\\CheckSetupController","check",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"settings.CheckSetup.check"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"settings.CheckSetup.check"}]},{"file":"\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"settings.CheckSetup.check"}]},{"file":"\/nextcloud\/lib\/base.php","line":989,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/settings\/ajax\/checksetup"]},{"file":"\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","Line":568,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko\/20100101 Firefox\/61.0","version":"14.0.0.19"}
{"reqId":"6lJIMjgQfhIA3GdfYHtp","level":3,"time":"2018-09-06 12:20:46","remoteAddr":"172.29.0.1","user":"cloudadmin","app":"index","method":"GET","url":"\/settings\/ajax\/checksetup","message":{"Exception":"TypeError","Message":"Argument 1 passed to OC\\Settings\\Controller\\CheckSetupController::getAppDirsWithDifferentOwnerForAppRoot() must be of the type array, boolean given, called in \/nextcloud\/settings\/Controller\/CheckSetupController.php on line 551","Code":0,"Trace":[{"file":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","line":551,"function":"getAppDirsWithDifferentOwnerForAppRoot","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[false,{"path":"\/apps2","url":"\/apps2","writable":true}]},{"file":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","line":624,"function":"getAppDirsWithDifferentOwner","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"check","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\CheckSetupController"},"check"]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\CheckSetupController"},"check"]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Settings\\Controller\\CheckSetupController","check",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"settings.CheckSetup.check"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"settings.CheckSetup.check"}]},{"file":"\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"settings.CheckSetup.check"}]},{"file":"\/nextcloud\/lib\/base.php","line":989,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/settings\/ajax\/checksetup"]},{"file":"\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","Line":568,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko\/20100101 Firefox\/61.0","version":"14.0.0.19"}
{"reqId":"AZYjzoGhHELEhUdyRrRN","level":3,"time":"2018-09-06 12:20:50","remoteAddr":"172.29.0.1","user":"cloudadmin","app":"index","method":"GET","url":"\/settings\/ajax\/checksetup","message":{"Exception":"TypeError","Message":"Argument 1 passed to OC\\Settings\\Controller\\CheckSetupController::getAppDirsWithDifferentOwnerForAppRoot() must be of the type array, boolean given, called in \/nextcloud\/settings\/Controller\/CheckSetupController.php on line 551","Code":0,"Trace":[{"file":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","line":551,"function":"getAppDirsWithDifferentOwnerForAppRoot","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[false,{"path":"\/apps2","url":"\/apps2","writable":true}]},{"file":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","line":624,"function":"getAppDirsWithDifferentOwner","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"check","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\CheckSetupController"},"check"]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\CheckSetupController"},"check"]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Settings\\Controller\\CheckSetupController","check",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"settings.CheckSetup.check"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"settings.CheckSetup.check"}]},{"file":"\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"settings.CheckSetup.check"}]},{"file":"\/nextcloud\/lib\/base.php","line":989,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/settings\/ajax\/checksetup"]},{"file":"\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","Line":568,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko\/20100101 Firefox\/61.0","version":"14.0.0.19"}
{"reqId":"zqy9p1Bh6UDrtmtlhRZS","level":3,"time":"2018-09-06 12:20:58","remoteAddr":"172.29.0.1","user":"cloudadmin","app":"index","method":"GET","url":"\/settings\/ajax\/checksetup","message":{"Exception":"TypeError","Message":"Argument 1 passed to OC\\Settings\\Controller\\CheckSetupController::getAppDirsWithDifferentOwnerForAppRoot() must be of the type array, boolean given, called in \/nextcloud\/settings\/Controller\/CheckSetupController.php on line 551","Code":0,"Trace":[{"file":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","line":551,"function":"getAppDirsWithDifferentOwnerForAppRoot","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[false,{"path":"\/apps2","url":"\/apps2","writable":true}]},{"file":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","line":624,"function":"getAppDirsWithDifferentOwner","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"check","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\CheckSetupController"},"check"]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\CheckSetupController"},"check"]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Settings\\Controller\\CheckSetupController","check",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"settings.CheckSetup.check"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"settings.CheckSetup.check"}]},{"file":"\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"settings.CheckSetup.check"}]},{"file":"\/nextcloud\/lib\/base.php","line":989,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/settings\/ajax\/checksetup"]},{"file":"\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","Line":568,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko\/20100101 Firefox\/61.0","version":"14.0.0.19"}
{"reqId":"YglhHA0KKbfKweP8R4Iu","level":3,"time":"2018-09-06 12:22:02","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":{"Exception":"Error","Message":"Call to undefined method OCP\\AppFramework\\Http\\DataResponse::succeeded()","Code":0,"Trace":[{"file":"\/nextcloud\/lib\/private\/BackgroundJob\/Job.php","line":61,"function":"run","class":"OCA\\Survey_Client\\BackgroundJobs\\MonthlyReport","type":"->","args":[null]},{"file":"\/nextcloud\/lib\/private\/BackgroundJob\/TimedJob.php","line":55,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},{"file":"\/nextcloud\/cron.php","line":123,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"\/nextcloud\/apps\/survey_client\/lib\/BackgroundJobs\/MonthlyReport.php","Line":43,"CustomMessage":"--"},"userAgent":"--","version":"14.0.0.19"}
{"reqId":"ZfKeMYHqlEZJDJt9gU3y","level":3,"time":"2018-09-06 12:28:25","remoteAddr":"172.29.0.1","user":"cloudadmin","app":"index","method":"GET","url":"\/settings\/ajax\/checksetup","message":{"Exception":"TypeError","Message":"Argument 1 passed to OC\\Settings\\Controller\\CheckSetupController::getAppDirsWithDifferentOwnerForAppRoot() must be of the type array, boolean given, called in \/nextcloud\/settings\/Controller\/CheckSetupController.php on line 551","Code":0,"Trace":[{"file":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","line":551,"function":"getAppDirsWithDifferentOwnerForAppRoot","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[false,{"path":"\/apps2","url":"\/apps2","writable":true}]},{"file":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","line":624,"function":"getAppDirsWithDifferentOwner","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"check","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\CheckSetupController"},"check"]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\CheckSetupController"},"check"]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Settings\\Controller\\CheckSetupController","check",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"settings.CheckSetup.check"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"settings.CheckSetup.check"}]},{"file":"\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"settings.CheckSetup.check"}]},{"file":"\/nextcloud\/lib\/base.php","line":989,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/settings\/ajax\/checksetup"]},{"file":"\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","Line":568,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko\/20100101 Firefox\/61.0","version":"14.0.0.19"}
{"reqId":"AFd7fVNjx0O4JKCOWkq8","level":3,"time":"2018-09-06 12:28:26","remoteAddr":"172.29.0.1","user":"cloudadmin","app":"index","method":"GET","url":"\/settings\/ajax\/checksetup","message":{"Exception":"TypeError","Message":"Argument 1 passed to OC\\Settings\\Controller\\CheckSetupController::getAppDirsWithDifferentOwnerForAppRoot() must be of the type array, boolean given, called in \/nextcloud\/settings\/Controller\/CheckSetupController.php on line 551","Code":0,"Trace":[{"file":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","line":551,"function":"getAppDirsWithDifferentOwnerForAppRoot","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[false,{"path":"\/apps2","url":"\/apps2","writable":true}]},{"file":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","line":624,"function":"getAppDirsWithDifferentOwner","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"check","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\CheckSetupController"},"check"]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\CheckSetupController"},"check"]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Settings\\Controller\\CheckSetupController","check",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"settings.CheckSetup.check"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"settings.CheckSetup.check"}]},{"file":"\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"settings.CheckSetup.check"}]},{"file":"\/nextcloud\/lib\/base.php","line":989,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/settings\/ajax\/checksetup"]},{"file":"\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","Line":568,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko\/20100101 Firefox\/61.0","version":"14.0.0.19"}
{"reqId":"6UlSVHvyTAcS1eRJlikC","level":3,"time":"2018-09-06 12:31:56","remoteAddr":"172.29.0.1","user":"cloudadmin","app":"index","method":"GET","url":"\/settings\/ajax\/checksetup","message":{"Exception":"TypeError","Message":"Argument 1 passed to OC\\Settings\\Controller\\CheckSetupController::getAppDirsWithDifferentOwnerForAppRoot() must be of the type array, boolean given, called in \/nextcloud\/settings\/Controller\/CheckSetupController.php on line 551","Code":0,"Trace":[{"file":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","line":551,"function":"getAppDirsWithDifferentOwnerForAppRoot","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[false,{"path":"\/apps2","url":"\/apps2","writable":true}]},{"file":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","line":624,"function":"getAppDirsWithDifferentOwner","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"check","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\CheckSetupController"},"check"]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\CheckSetupController"},"check"]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Settings\\Controller\\CheckSetupController","check",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"settings.CheckSetup.check"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"settings.CheckSetup.check"}]},{"file":"\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"settings.CheckSetup.check"}]},{"file":"\/nextcloud\/lib\/base.php","line":989,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/settings\/ajax\/checksetup"]},{"file":"\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","Line":568,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko\/20100101 Firefox\/61.0","version":"14.0.0.19"}
{"reqId":"xUz9GKojISoTXwQKMyq7","level":3,"time":"2018-09-06 12:32:00","remoteAddr":"172.29.0.1","user":"cloudadmin","app":"index","method":"GET","url":"\/settings\/ajax\/checksetup","message":{"Exception":"TypeError","Message":"Argument 1 passed to OC\\Settings\\Controller\\CheckSetupController::getAppDirsWithDifferentOwnerForAppRoot() must be of the type array, boolean given, called in \/nextcloud\/settings\/Controller\/CheckSetupController.php on line 551","Code":0,"Trace":[{"file":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","line":551,"function":"getAppDirsWithDifferentOwnerForAppRoot","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[false,{"path":"\/apps2","url":"\/apps2","writable":true}]},{"file":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","line":624,"function":"getAppDirsWithDifferentOwner","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"check","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\CheckSetupController"},"check"]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\CheckSetupController"},"check"]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Settings\\Controller\\CheckSetupController","check",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"settings.CheckSetup.check"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"settings.CheckSetup.check"}]},{"file":"\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"settings.CheckSetup.check"}]},{"file":"\/nextcloud\/lib\/base.php","line":989,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/settings\/ajax\/checksetup"]},{"file":"\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","Line":568,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko\/20100101 Firefox\/61.0","version":"14.0.0.19"}
{"reqId":"aqTPK0pwNcmxtrd1ZUHX","level":3,"time":"2018-09-06 12:32:05","remoteAddr":"172.29.0.1","user":"cloudadmin","app":"index","method":"GET","url":"\/settings\/ajax\/checksetup","message":{"Exception":"TypeError","Message":"Argument 1 passed to OC\\Settings\\Controller\\CheckSetupController::getAppDirsWithDifferentOwnerForAppRoot() must be of the type array, boolean given, called in \/nextcloud\/settings\/Controller\/CheckSetupController.php on line 551","Code":0,"Trace":[{"file":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","line":551,"function":"getAppDirsWithDifferentOwnerForAppRoot","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[false,{"path":"\/apps2","url":"\/apps2","writable":true}]},{"file":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","line":624,"function":"getAppDirsWithDifferentOwner","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"check","class":"OC\\Settings\\Controller\\CheckSetupController","type":"->","args":[]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\CheckSetupController"},"check"]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\CheckSetupController"},"check"]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Settings\\Controller\\CheckSetupController","check",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"settings.CheckSetup.check"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"settings.CheckSetup.check"}]},{"file":"\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"settings.CheckSetup.check"}]},{"file":"\/nextcloud\/lib\/base.php","line":989,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/settings\/ajax\/checksetup"]},{"file":"\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/nextcloud\/settings\/Controller\/CheckSetupController.php","Line":568,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko\/20100101 Firefox\/61.0","version":"14.0.0.19"}

```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Netweork:
HTTP/2.0 500 Internal Server Error
server: nginx
date: Thu, 06 Sep 2018 11:15:29 GMT
content-type: text/html; charset=UTF-8
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache
content-security-policy: default-src 'self'; script-src 'self' 'unsafe-eval' 'nonce-UGI2M2djcFhKaE5ENEdqczBXZ3prZlhGRGN1TVhDYlMrWnhwLzZpdFp3TT06QkliUjZyZ09jMVlydGhpQXRCOWY4cVR5Zk9EOUYyQzNydTB4eHR2R0VtMD0='; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *; object-src 'none'; base-uri 'self';
x-frame-options: SAMEORIGIN
X-Firefox-Spdy: h2


Java Script Console:
Content Security Policy: Die Direktive 'child-src' sollte nicht mehr verwendet werden. Bitte verwenden Sie stattdessen die Direktive 'worker-src' zum Kontrollieren von Workern bzw. die Direktive 'frame-src' zum Kontrollieren von Frames.
JQMIGRATE: Migrate is installed, version 1.4.0 core.js:7:542
unreachable code after return statement[Weitere Informationen] merged.js:1498:4
window.controllers/Controllers sollte nicht mehr verwendet werden. Verwenden Sie es nicht für die Browser-Erkennung. merged.js:2176
New search handler registered search.js:66:4
querying Whats New data was successful: nocontent merged-template-prepend.js:4478:4
undefined merged-template-prepend.js:4479:4
Source-Map-Fehler: TypeError: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.org/apps/notifications/js/notifications.js?v=22303c99-25
Source-Map-Adresse: notifications.js.map[Weitere Informationen]
```
</details>

### PR DESCRIPTION
**Pull request by kesselb**
Close #11088 
Close #11089 

posix_getpwuid returns an array with information about user/group/etc. for current user. These information is not available when /etc/passwd is not readable (see https://secure.php.net/manual/en/function.posix-getpwuid.php#45994).

@weeman1337 @rullzer is it enough to compare the user id? i guess we could check the group id as well.

### CODE REVIEW

**Comment by weeman1337** [comment]
It's okay for me. At the moment the check is only for the same owner (not group).

**Review by weeman1337 — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]
Well, calling `posix_getpwuid(` twice should not result in something different for the same input, and if it is not the same input, the result is also never the same, right?

File: settings/Controller/CheckSetupController.php [hunk 1]
```diff
@@ -561,19 +561,19 @@ protected function getAppDirsWithDifferentOwner(): array {
 	/**
 	 * Tests if the directories for one apps directory are writable by the current user.
 	 *
-	 * @param array $currentUser The current user
+	 * @param int $currentUser The current user
 	 * @param array $appRoot The app root config
 	 * @return string[] The none writable directory paths inside the app root
 	 */
-	private function getAppDirsWithDifferentOwnerForAppRoot(array $currentUser, array $appRoot): array {
+	private function getAppDirsWithDifferentOwnerForAppRoot($currentUser, array $appRoot): array {
```
Comment (blizzz) [inline settings/Controller/CheckSetupController.php]: type hint `int` missing
