### PR TITLE
🐘 Support postgres15

### LINKED ISSUE #34617: [Bug]: NC 25 RC5 not compatible with postgresql 15
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Postgresql 15 was released today and nextcloud 25 RC5 and it is not happy with postgresql 15. Any ETA on a fix?

### Steps to reproduce

Install PHP 8.1-fpm and postgresql 15 and try installing NC 25 RC5 on debian 11.

Install using source https://download.nextcloud.com/server/prereleases/nextcloud-25.0.0rc5.zip

### Expected behavior

Works as expected

### Installation method

_No response_

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
All standard apps on install
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by vitormattos**
close #34617

Tested with Postgres 12, 13, 14 and 15 and worked fine.

### CODE REVIEW

File: lib/private/Setup/PostgreSQL.php [hunk 1]
```diff
@@ -70,6 +71,9 @@ public function setupDatabase($username) {
 				$this->dbPassword = \OC::$server->getSecureRandom()->generate(30, ISecureRandom::CHAR_ALPHANUMERIC);
 
 				$this->createDBUser($connection);
+				// Go to main database and grant all privileges on schema public
+				$connectionMainDatabase->executeQuery('GRANT ALL PRIVILEGES ON SCHEMA public TO ' . $this->dbUser);
```
Comment (szaimen) [inline lib/private/Setup/PostgreSQL.php:75]: This doesnt look like the safest approach based on https://www.postgresql.org/docs/15/ddl-schemas.html#DDL-SCHEMAS-PATTERNS

Comment (szaimen) [reply lib/private/Setup/PostgreSQL.php:75]: If we should still go this way, I guess we should also document this then for cases when manually creating the databas beforehand.

Comment (nickvergessen) [reply lib/private/Setup/PostgreSQL.php:75]: If we don't do it in such a way, we will have problems when trying to apply updates in the future.
That being said, it could still be done in a schema owned by the user?

But also I'm not sure how the transition works. I read it as all existing privileges are dropped in the update from 14 to 15, so that existing Nextclouds will break as we have schema changes between 24 and 25?

Comment (szaimen) [reply lib/private/Setup/PostgreSQL.php:75]: I think upgrades should work: 
Screenshot_20221018_085302

Comment (szaimen) [reply lib/private/Setup/PostgreSQL.php:75]: > This doesnt look like the safest approach based on https://www.postgresql.org/docs/15/ddl-schemas.html#DDL-SCHEMAS-PATTERNS

If we assume that the database is only used by one user then it should be fine going this way.
Screenshot_20221018_085947
However if we assume that this is not the case should we not do this and use a schema that is owned by the user. But this would mean that the database would somehow need to get migrated...

Comment (szaimen) [reply lib/private/Setup/PostgreSQL.php:75]: > I think upgrades should work: Screenshot_20221018_085302

I may be wrong: https://github.com/nextcloud/server/issues/34617#issuecomment-1282216067

Comment (vitormattos) [reply lib/private/Setup/PostgreSQL.php]: I reduced the permission as described in release notes of version 15 and put this in a comment block to explain the reason.

File: lib/private/Setup/PostgreSQL.php [hunk 2]
```diff
@@ -70,6 +71,13 @@ public function setupDatabase($username) {
 				$this->dbPassword = \OC::$server->getSecureRandom()->generate(30, ISecureRandom::CHAR_ALPHANUMERIC);
 
 				$this->createDBUser($connection);
+				// Go to main database and grant create on schema public
+				// This is implemented to make possible work with PostgreSQL version 15:
+				// https://www.postgresql.org/docs/release/15.0/
+				//
+				// From release note: For new databases having no need to defend against insider threats, granting CREATE permission will yield the behavior of prior releases.
```
[the remark this answers is not in the document]
Comment (vitormattos) [reply lib/private/Setup/PostgreSQL.php:78]: Is good!
Could you help with the text?

[the remark this answers is not in the document]
Comment (szaimen) [reply lib/private/Setup/PostgreSQL.php:78]: > Could you help with the text?

yes, later

**Review by szaimen — APPROVED** [review]
lgtm now

**Comment by nickvergessen** [comment]
So this fixes new installations. Any chance that we can fix existing ones on update?

**Comment by szaimen** [comment]
> So this fixes new installations. Any chance that we can fix existing ones on update?

Not sure, they should get broken upon upgrade, IIRC?

Or if they are because they upgrade to Postgresql 15 wrongly, you need to run `GRANT ALL PRIVILEGES ON SCHEMA public TO $DB_USER` once which we cannot do if our user is not postgresql admin which it should be anyway.

**Comment by nickvergessen** [comment]
> Or if they are because they upgrade to Postgresql 15 wrongly, you need to run `GRANT ALL PRIVILEGES ON SCHEMA public TO $DB_USER` once which we cannot do if our user is not postgresql admin which it also should not be anyway.

But we could show this as an error with the correct user already filled in? Instead of "Insufficient privileges" (not sure if we can detect it https://github.com/nextcloud/server/issues/34617#issuecomment-1282216067 )

**Comment by szaimen** [comment]
docs improvements in https://github.com/nextcloud/documentation/pull/9227

File: lib/private/Setup/PostgreSQL.php [hunk 3]
```diff
@@ -70,6 +71,16 @@ public function setupDatabase($username) {
...
 				$this->createDBUser($connection);
+
+				// Go to the main database and grant create on the public schema
+				// The code below is implemented to make installing possible with PostgreSQL version 15:
+				// https://www.postgresql.org/docs/release/15.0/
+				// From the release notes: For new databases having no need to defend against insider threats, granting CREATE permission will yield the behavior of prior releases
+				// Therefore we assume that the database is only used by one user/service which is Nextcloud
+				// Additional services should get installed in a separate database in order to stay secure
+				// Also see https://www.postgresql.org/docs/15/ddl-schemas.html#DDL-SCHEMAS-PATTERNS
+				$connectionMainDatabase->executeQuery('GRANT CREATE ON SCHEMA public TO ' . $this->dbUser);
```
Comment (PVince81) [inline lib/private/Setup/PostgreSQL.php:82]: please escape "dbUser"

**Review by juliusknorr — DISMISSED** [review]
Can we add drone jobs for postgres 14 and 15 as well?

10 can probably be dropped for master as it will have its final release this November according to https://www.postgresql.org/support/versioning/ but not sure about how we decided about dropping database versions in the past.

**Comment by nickvergessen** [comment]
> but not sure about how we decided about dropping database versions in the past.

I would argue the same way as with PHP. The next major after it was dropped from upstream we should remove it. So +1 on dropping 10 with Nextcloud 26

**Comment by szaimen** [comment]
> Can we add drone jobs for postgres 14 and 15 as well?
> 
> 10 can probably be dropped for master as it will have its final release this November according to https://www.postgresql.org/support/versioning/ but not sure about how we decided about dropping database versions in the past.

@juliushaertl can we do that in a follow-up PR?

**Comment by juliushaertl** [comment]
> > Can we add drone jobs for postgres 14 and 15 as well?
> > 10 can probably be dropped for master as it will have its final release this November according to [postgresql.org/support/versioning](https://www.postgresql.org/support/versioning/) but not sure about how we decided about dropping database versions in the past.
> 
> @juliushaertl can we do that in a follow-up PR?

Dropping the old ones sure, for merging I'd still feel more confident if a CI job at least for 15 is added to this PR before merging.

Should be quite straight forward to duplicate the existing one with postgres:15

https://github.com/nextcloud/server/blob/master/.drone.yml#L507-L541

**Comment by szaimen** [comment]
@vitormattos all postgres test seem to fail now. Can you look into it? 

As for the postgres 15 container, we first need to create it here: https://github.com/nextcloud/docker-ci

File: .drone.yml [hunk 4]
```diff
@@ -540,6 +540,42 @@ trigger:
...
+  commands:
+    - bash tests/drone-run-php-tests.sh || exit 0
+    - sleep 10 # gives the database enough time to initialize
+    - POSTGRES=15 NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh pgsql
+
+services:
+- name: cache
+  image: ghcr.io/nextcloud/continuous-integration-redis:latest
+- name: postgres-15
+  image: ghcr.io/nextcloud/continuous-integration-postgres-15:postgres-15
```
Comment (nickvergessen) [inline .drone.yml:563]: This image doesn't exist?

There is a PR to add 14 in https://github.com/nextcloud/docker-ci/pull/430
So maybe we can do a second PR to add 15?

Comment (szaimen) [reply .drone.yml:563]: yes, this is why I wanted to postpone it...

Comment (nickvergessen) [reply .drone.yml:563]: 🙄 Why postpone, it's a single line file can be done straight away
https://github.com/nextcloud/docker-ci/pull/456

Comment (szaimen) [reply .drone.yml:563]: last time I tried to create a new image I didn't have enough permissionis to make the resulting package publicly available...

Comment (nickvergessen) [reply .drone.yml:563]: postgres-15:latest is now available:
https://github.com/nextcloud/docker-ci/pkgs/container/continuous-integration-postgres-15

Comment (nickvergessen) [reply .drone.yml:563]:
```suggestion
- name: postgres-15
  image: ghcr.io/nextcloud/continuous-integration-postgres-15:latest
```

Comment (nickvergessen) [reply .drone.yml:563]: > last time I tried to create a new image I didn't have enough permissionis to make the resulting package publicly available...

Ah okay, didn't know. A PR still helps to visualize that :)

**Comment by nickvergessen** [comment]
The PR breaks the old versions:
```
PostgreSQL username and/or password not valid
 -> You need to enter details of an existing account.
Trace: #0 /drone/src/lib/private/Setup.php(353): OC\Setup\PostgreSQL->setupDatabase()
#1 /drone/src/core/Command/Maintenance/Install.php(105): OC\Setup->install()
#2 /drone/src/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Maintenance\Install->execute()
#3 /drone/src/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#4 /drone/src/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#5 /drone/src/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#6 /drone/src/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
#7 /drone/src/console.php(100): OC\Console\Application->run()
#8 /drone/src/occ(11): require_once('/drone/src/cons...')
#9 {main}

Previous: Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] FATAL:  database "oc_autotest" does not exist
Trace: #0 /drone/src/lib/private/Setup/PostgreSQL.php(110): OC\DB\Connection->connect()
#1 /drone/src/lib/private/Setup.php(353): OC\Setup\PostgreSQL->setupDatabase()
#2 /drone/src/core/Command/Maintenance/Install.php(105): OC\Setup->install()
#3 /drone/src/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Maintenance\Install->execute()
#4 /drone/src/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#5 /drone/src/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#6 /drone/src/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#7 /drone/src/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
#8 /drone/src/console.php(100): OC\Console\Application->run()
#9 /drone/src/occ(11): require_once('/drone/src/cons...')
#10 {main}
```

I guess you need to wrap the new code bits with a check for postgres 15+

**Comment by vitormattos** [comment]
> database "oc_autotest" does not exist

I observed a strange problem with Drone, I sent a PR fixing the error of database does not exist, but I don't know because the last Drone execution don't executed with the fix #34736

**Comment by szaimen** [comment]
> > database "oc_autotest" does not exist
> 
> I observed a strange problem with Drone, I sent a PR fixing the error of database does not exist, but I don't know because the last Drone execution don't executed with the fix #34736

I already rebased so drone should have used the fix already...

**Comment by szaimen** [comment]
@vitormattos can you take care of the check? :)

**Review by ChristophWurst — APPROVED** [review]

**Comment by szaimen** [comment]
ping @vitormattos ? :)

**Comment by szaimen** [comment]
ping @vitormattos ? :)

File: .drone.yml [hunk 5]
```diff
@@ -540,6 +540,42 @@ trigger:
...
+    - POSTGRES=15 NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh pgsql
+
+services:
+- name: cache
+  image: ghcr.io/nextcloud/continuous-integration-redis:latest
+- name: postgres-15
+  image: ghcr.io/nextcloud/continuous-integration-postgres-15:latest
+  environment:
+    POSTGRES_USER: oc_autotest
+    POSTGRES_DB: oc_autotest_dummy
```
Comment (szaimen) [inline .drone.yml:566]: So maybe this clashes now with https://github.com/nextcloud/server/blob/32b1d4fc8e61d5ed4b355c8d0393b069590e339a/autotest.sh#L16?

**Comment by szaimen** [comment]
It works 🎉🎉🎉

**Comment by IrwenXYZ** [comment]
hi guys, thanks for the quick fix for psql 15. I'm planning on setting up a Nextcloud instance, and was wondering if a Nextcloud 20.0.1 instance can upgrade gracefully from Postgres 14 to 15 through this PR?

alternatively, should I was for 25.0.2 to release to set it up?

thank you!

**Comment by nickvergessen** [comment]
Not sure if it is a typo, but 20.0.1 is not updated and not supported anymore. If you mean 25.0.1 the answer is *No*, you should wait for 25.0.2 which is planned to be released soon, (RC1 was released last week and then it usually doesn't take a long time).

**Comment by IrwenXYZ** [comment]
Yes I meant 25.0.2. Thank you for the answer, I will wait for 25.0.2!

**Comment by DaphneMuller** [comment]
hello @vitormattos @szaimen , 
Thank you for your work on this pull request! This ticket seems to have the tag 'missing documentation', is there any chance you could clarify what documentation is missing? Is this for admins or for app developers?

**Comment by szaimen** [comment]
documentation is done already
