### PR TITLE
fix: Remove redundant toast notifications

### LINKED ISSUE #52868: Revise toasts
There are some general issues with wording in toasts.
1. They are unnecessarily verbose. Things like '"{}" action executed successfully' could be reworded to '"{}" was successful' or something similar.
2. They should not be displayed for trivial actions, such as cancelling the creation of a folder. I'm not sure if there are other examples.

cc @marcoambrosini

### PR DESCRIPTION
**Pull request by kra-mo**
Split out from #54202

* Resolves: #52868

## Summary

Since these actions already have highly visible visual confirmation, no extra notifications are needed.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Review by susnux — APPROVED** [review]

File: apps/systemtags/src/components/SystemTagPicker.vue [hunk 1]
```diff
@@ -131,7 +131,6 @@ import { emit } from '@nextcloud/event-bus'
 import { getCurrentUser } from '@nextcloud/auth'
 import { getLanguage, n, t } from '@nextcloud/l10n'
 import { loadState } from '@nextcloud/initial-state'
-import { showError, showInfo } from '@nextcloud/dialogs'
```
Comment (joshtrichards) [inline apps/systemtags/src/components/SystemTagPicker.vue:140]: I think `showError` is still needed here.

**Review by joshtrichards — CHANGES_REQUESTED** [review]
Nice polish. Thanks for streamlining the toasts, @kra-mo!

File: apps/systemtags/src/components/SystemTagPicker.vue (hunk 1 above)
Comment (susnux) [reply apps/systemtags/src/components/SystemTagPicker.vue:140]: yes needs to be added back

Comment (kra-mo) [reply apps/systemtags/src/components/SystemTagPicker.vue:140]: Oops, indeed, fixed.

**Review by joshtrichards — APPROVED** [review]
