### PR TITLE
Respect custom webroot in setup form

### LINKED ISSUE #41188: [Bug]:
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

While I was setting up a Nextcloud instance under a custom webroot (`<my-url>/cloud`) I was prompted to create an Admin account. But the form was broken since its action did not respect the custom webroot, and was pointing to `<my-url>/index.php` instead of `<my-url>/cloud/index.php`. I was able to create an account by altering the markup and all other forms work fine (e.g. sign in).

### Steps to reproduce

1. Create a fresh nextcloud instance without creating an admin account
2. Configure it with a custom webroot with `overwritewebroot`
3. Open the url and inspect the target of the create admin form

### Expected behavior

The form should respect my custom webroot.

### Installation method

Community Docker image

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
throws error (since setup wasn't completed)
```

### List of activated Apps

```shell
throws error (since setup wasn't completed)
```

### Nextcloud Signing status

```shell
does not apply
```

### Nextcloud Logs

```shell
empty
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by HolonProduction**
* Resolves: #41188

## Summary

Passes an url generator to the installation template and uses it to generate an absoluteUrl.

### CODE REVIEW

File: core/templates/installation.php [hunk 1]
```diff
@@ -1,11 +1,13 @@
...
 script('core', 'install');
+
+$urlGenerator = $_['urlGenerator'];
 ?>
 <input type='hidden' id='hasMySQL' value='<?php p($_['hasMySQL']) ?>'>
 <input type='hidden' id='hasSQLite' value='<?php p($_['hasSQLite']) ?>'>
 <input type='hidden' id='hasPostgreSQL' value='<?php p($_['hasPostgreSQL']) ?>'>
 <input type='hidden' id='hasOracle' value='<?php p($_['hasOracle']) ?>'>
-<form action="index.php" method="post" class="guest-box install-form">
+<form action="<?php $urlGenerator->getAbsoluteURL("index.php") ?>" method="post" class="guest-box install-form">
```
Comment (kesselb) [inline core/templates/installation.php:10]:
```suggestion
<form action="<?= $urlGenerator->getAbsoluteURL("index.php") ?>" method="post" class="guest-box install-form">
```

If you generate the url you should also echo it ;)

It should also work to remove the action attribute because the default is then the current page.

**Review by kesselb — CHANGES_REQUESTED** [review]

File: core/templates/installation.php (hunk 1 above)
Comment (kesselb) [inline core/templates/installation.php:10]:
```suggestion
<form method="post" class="guest-box install-form">
```

Would be my favorite.

Comment (HolonProduction) [reply core/templates/installation.php:10]: I wasn't sure on this since the template isn't directly linked to `index.php`. But giving it a second thought setting it to `index.php` makes assumptions about the location of the form as well so yeah that's probably the best solution.

**Review by skjnldsv — APPROVED** [review]
Code make sense and worked for me

**Review by kesselb — APPROVED** [review]

**Comment by Altahrim** [comment]
@HolonProduction  CI failures seems unrelated.
Can you reabse and reword your commit to use [conventional commit](https://www.conventionalcommits.org/) please?

**Comment by HolonProduction** [comment]
Done
