### PR TITLE
fx(dav): file request guest nickname encoding

### LINKED ISSUE #48942: [Bug]: Upload Error with guest name containing umlaut in File Request
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

An error occurs after uploading a file request if you use an umlaut in the name. Such as “Büro”

### Steps to reproduce

1. Share an Folder for File Request
2. Open URL of File Request
3. Enter a Name with an Umlaut Ä,Ö,Ü
4. Try uploading a file

### Expected behavior

File should be successfully uploaded

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 28.0.1 to 28.0.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [x] Other

### Configuration report
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.paddif.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "30.0.1.2",
        "user_backends": [
            {
                "class": "\\OCA\\UserExternal\\IMAP",
                "arguments": [
                    "mail.paddif.de",
                    143,
                    "tls"
                ]
            }
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6380
        },
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "3307",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "default_phone_region": "DE",
        "maintenance": false,
        "theme": "",
        "simpleSignUpLink.shown": false,
        "loglevel": 2,
        "oidc_login_provider_url": "***REMOVED SENSITIVE VALUE***",
        "oidc_login_client_id": "***REMOVED SENSITIVE VALUE***",
        "oidc_login_client_secret": "***REMOVED SENSITIVE VALUE***",
        "oidc_login_auto_redirect": false,
        "oidc_login_button_text": "Log in with Active Directory",
        "oidc_login_disable_registration": false,
        "maintenance_window_start": 1,
        "oidc_login_attributes": {
            "id": "profile.upn",
            "name": "profile.unique_name"
        },
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "user_external",
            "webhooks"
        ]
    }
}
```
### List of activated Apps
```
  - activity: 3.0.0
  - app_api: 4.0.0
  - calendar: 5.0.1
  - cloud_federation_api: 1.13.0
  - comments: 1.20.1
  - contacts: 6.1.0
  - contactsinteraction: 1.11.0
  - dav: 1.31.1
  - deck: 1.14.1
  - federatedfilesharing: 1.20.0
  - federation: 1.20.0
  - files: 2.2.0
  - files_downloadlimit: 3.0.0
  - files_lock: 30.0.0
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - firstrunwizard: 3.0.0
  - flow_notifications: 1.10.0
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - nextcloud_announcements: 2.0.0
  - notifications: 3.0.0
  - oauth2: 1.18.1
  - password_policy: 2.0.0
  - photos: 3.0.2
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - recommendations: 3.0.0
  - related_resources: 1.5.0
  - richdocuments: 8.5.1
  - richdocumentscode: 24.4.802
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - support: 2.0.0
  - survey_client: 2.0.0
  - systemtags: 1.20.0
  - text: 4.1.0
  - theming: 2.5.0
  - twofactor_backupcodes: 1.19.0
  - updatenotification: 1.20.0
  - user_external: 3.4.0
  - user_status: 1.10.0
  - viewer: 3.0.0
  - weather_status: 1.10.0
  - webhook_listeners: 1.1.0-dev
  - webhooks: 0.4.3
  - workflow_script: 1.15.0
  - workflowengine: 2.12.0
```
### Nextcloud Signing status

No errors have been found.

### Nextcloud Logs
```
{
  "reqId": "NADdfKDEOC8KgeYde1b3",
  "level": 3,
  "time": "2024-10-28T12:15:47+00:00",
  "remoteAddr": "<private information>",
  "user": "--",
  "app": "webdav",
  "method": "PUT",
  "url": "/public.php/dav/files/waetBcSG8Pxq4WH/300_21536.pdf",
  "message": "An exception occurred while executing a query: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xFCro' for column `nextcld`.`oc_filecache`.`name` at row 1",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0",
  "version": "30.0.1.2",
  "exception": {
    "Exception": "Doctrine\\DBAL\\Exception\\DriverException",
    "Message": "An exception occurred while executing a query: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xFCro' for column `nextcld`.`oc_filecache`.`name` at row 1",
    "Code": 1366,
    "Trace": [
      {
        "file": "/var/www/clients/client1/web48/web/3rdparty/doctrine/dbal/src/Connection.php",
        "line": 1939,
        "function": "convert",
        "class": "Doctrine\\DBAL\\Driver\\API\\MySQL\\ExceptionConverter",
        "type": "->"
      },
      {
        "file": "/var/www/clients/client1/web48/web/3rdparty/doctrine/dbal/src/Connection.php",
        "line": 1881,
        "function": "handleDriverException",
        "class": "Doctrine\\DBAL\\Connection",
        "type": "->"
      },
      {
        "file": "/var/www/clients/client1/web48/web/3rdparty/doctrine/dbal/src/Connection.php",
        "line": 1213,
        "function": "convertExceptionDuringQuery",
        "class": "Doctrine\\DBAL\\Connection",
        "type": "->"
      },
      {
        "file": "/var/www/clients/client1/web48/web/3rdparty/doctrine/dbal/src/Connections/PrimaryReadReplicaConnection.php",
        "line": 292,
        "function": "executeStatement",
        "class": "Doctrine\\DBAL\\Connection",
        "type": "->"
      },
      {
        "file": "/var/www/clients/client1/web48/web/lib/private/DB/Connection.php",
        "line": 462,
        "function": "executeStatement",
        "class": "Doctrine\\DBAL\\Connections\\PrimaryReadReplicaConnection",
        "type": "->"
      },
      {
        "file": "/var/www/clients/client1/web48/web/lib/private/DB/ConnectionAdapter.php",
        "line": 67,
        "function": "executeStatement",
        "class": "OC\\DB\\Connection",
        "type": "->"
      },
      {
        "file": "/var/www/clients/client1/web48/web/lib/private/DB/QueryBuilder/QueryBuilder.php",
        "line": 306,
        "function": "executeStatement",
        "class": "OC\\DB\\ConnectionAdapter",
        "type": "->"
      },
      {
        "file": "/var/www/clients/client1/web48/web/lib/private/DB/QueryBuilder/QueryBuilder.php",
        "line": 268,
        "function": "executeStatement",
        "class": "OC\\DB\\QueryBuilder\\QueryBuilder",
        "type": "->"
      },
      {
        "file": "/var/www/clients/client1/web48/web/lib/private/Files/Cache/Cache.php",
        "line": 285,
        "function": "execute",
        "class": "OC\\DB\\QueryBuilder\\QueryBuilder",
        "type": "->"
      },
      {
        "file": "/var/www/clients/client1/web48/web/lib/private/Files/Cache/Wrapper/CacheWrapper.php",
        "line": 129,
        "function": "insert",
        "class": "OC\\Files\\Cache\\Cache",
        "type": "->"
      },
      {
        "file": "/var/www/clients/client1/web48/web/lib/private/Files/Cache/Scanner.php",
        "line": 284,
        "function": "insert",
        "class": "OC\\Files\\Cache\\Wrapper\\CacheWrapper",
        "type": "->"
      },
      {
        "file": "/var/www/clients/client1/web48/web/lib/private/Files/Cache/Scanner.php",
        "line": 217,
        "function": "addToCache",
        "class": "OC\\Files\\Cache\\Scanner",
        "type": "->"
      },
      {
        "file": "/var/www/clients/client1/web48/web/lib/private/Files/Cache/Scanner.php",
        "line": 329,
        "function": "scanFile",
        "class": "OC\\Files\\Cache\\Scanner",
        "type": "->"
      },
      {
        "file": "/var/www/clients/client1/web48/web/lib/private/Files/Cache/Updater.php",
        "line": 110,
        "function": "scan",
        "class": "OC\\Files\\Cache\\Scanner",
        "type": "->"
      },
      {
        "file": "/var/www/clients/client1/web48/web/lib/private/Files/View.php",
        "line": 259,
        "function": "update",
        "class": "OC\\Files\\Cache\\Updater",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/clients/client1/web48/web/lib/private/Files/View.php",
        "line": 1153,
        "function": "writeUpdate",
        "class": "OC\\Files\\View",
        "type": "->"
      },
      {
        "file": "/var/www/clients/client1/web48/web/lib/private/Files/View.php",
        "line": 208,
        "function": "basicOperation",
        "class": "OC\\Files\\View",
        "type": "->"
      },
      {
        "file": "/var/www/clients/client1/web48/web/apps/dav/lib/Files/Sharing/FilesDropPlugin.php",
        "line": 81,
        "function": "mkdir",
        "class": "OC\\Files\\View",
        "type": "->"
      },
      {
        "file": "/var/www/clients/client1/web48/web/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "beforeMethod",
        "class": "OCA\\DAV\\Files\\Sharing\\FilesDropPlugin",
        "type": "->"
      },
      {
        "file": "/var/www/clients/client1/web48/web/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 456,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/clients/client1/web48/web/apps/dav/lib/Connector/Sabre/Server.php",
        "line": 43,
        "function": "invokeMethod",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/clients/client1/web48/web/apps/dav/appinfo/v2/publicremote.php",
        "line": 139,
        "function": "start",
        "class": "OCA\\DAV\\Connector\\Sabre\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/clients/client1/web48/web/public.php",
        "line": 82,
        "args": [
          "/var/www/clients/client1/web48/web/apps/dav/appinfo/v2/publicremote.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/var/www/clients/client1/web48/web/3rdparty/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php",
    "Line": 118,
    "Previous": {
      "Exception": "Doctrine\\DBAL\\Driver\\PDO\\Exception",
      "Message": "SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xFCro' for column `nextcld`.`oc_filecache`.`name` at row 1",
      "Code": 1366,
      "Trace": [
        {
          "file": "/var/www/clients/client1/web48/web/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php",
          "line": 132,
          "function": "new",
          "class": "Doctrine\\DBAL\\Driver\\PDO\\Exception",
          "type": "::"
        },
        {
          "file": "/var/www/clients/client1/web48/web/3rdparty/doctrine/dbal/src/Connection.php",
          "line": 1207,
          "function": "execute",
          "class": "Doctrine\\DBAL\\Driver\\PDO\\Statement",
          "type": "->"
        },
        {
          "file": "/var/www/clients/client1/web48/web/3rdparty/doctrine/dbal/src/Connections/PrimaryReadReplicaConnection.php",
          "line": 292,
          "function": "executeStatement",
          "class": "Doctrine\\DBAL\\Connection",
          "type": "->"
        },
        {
          "file": "/var/www/clients/client1/web48/web/lib/private/DB/Connection.php",
          "line": 462,
          "function": "executeStatement",
          "class": "Doctrine\\DBAL\\Connections\\PrimaryReadReplicaConnection",
          "type": "->"
        },
        {
          "file": "/var/www/clients/client1/web48/web/lib/private/DB/ConnectionAdapter.php",
          "line": 67,
          "function": "executeStatement",
          "class": "OC\\DB\\Connection",
          "type": "->"
        },
        {
          "file": "/var/www/clients/client1/web48/web/lib/private/DB/QueryBuilder/QueryBuilder.php",
          "line": 306,
          "function": "executeStatement",
          "class": "OC\\DB\\ConnectionAdapter",
          "type": "->"
        },
        {
          "file": "/var/www/clients/client1/web48/web/lib/private/DB/QueryBuilder/QueryBuilder.php",
          "line": 268,
          "function": "executeStatement",
          "class": "OC\\DB\\QueryBuilder\\QueryBuilder",
          "type": "->"
        },
        {
          "file": "/var/www/clients/client1/web48/web/lib/private/Files/Cache/Cache.php",
          "line": 285,
          "function": "execute",
          "class": "OC\\DB\\QueryBuilder\\QueryBuilder",
          "type": "->"
        },
        {
          "file": "/var/www/clients/client1/web48/web/lib/private/Files/Cache/Wrapper/CacheWrapper.php",
          "line": 129,
          "function": "insert",
          "class": "OC\\Files\\Cache\\Cache",
          "type": "->"
        },
        {
          "file": "/var/www/clients/client1/web48/web/lib/private/Files/Cache/Scanner.php",
          "line": 284,
          "function": "insert",
          "class": "OC\\Files\\Cache\\Wrapper\\CacheWrapper",
          "type": "->"
        },
        {
          "file": "/var/www/clients/client1/web48/web/lib/private/Files/Cache/Scanner.php",
          "line": 217,
          "function": "addToCache",
          "class": "OC\\Files\\Cache\\Scanner",
          "type": "->"
        },
        {
          "file": "/var/www/clients/client1/web48/web/lib/private/Files/Cache/Scanner.php",
          "line": 329,
          "function": "scanFile",
          "class": "OC\\Files\\Cache\\Scanner",
          "type": "->"
        },
        {
          "file": "/var/www/clients/client1/web48/web/lib/private/Files/Cache/Updater.php",
          "line": 110,
          "function": "scan",
          "class": "OC\\Files\\Cache\\Scanner",
          "type": "->"
        },
        {
          "file": "/var/www/clients/client1/web48/web/lib/private/Files/View.php",
          "line": 259,
          "function": "update",
          "class": "OC\\Files\\Cache\\Updater",
          "type": "->",
          "args": [
            "*** sensitive parameters replaced ***"
          ]
        },
        {
          "file": "/var/www/clients/client1/web48/web/lib/private/Files/View.php",
          "line": 1153,
          "function": "writeUpdate",
          "class": "OC\\Files\\View",
          "type": "->"
        },
        {
          "file": "/var/www/clients/client1/web48/web/lib/private/Files/View.php",
          "line": 208,
          "function": "basicOperation",
          "class": "OC\\Files\\View",
          "type": "->"
        },
        {
          "file": "/var/www/clients/client1/web48/web/apps/dav/lib/Files/Sharing/FilesDropPlugin.php",
          "line": 81,
          "function": "mkdir",
          "class": "OC\\Files\\View",
          "type": "->"
        },
        {
          "file": "/var/www/clients/client1/web48/web/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
          "line": 89,
          "function": "beforeMethod",
          "class": "OCA\\DAV\\Files\\Sharing\\FilesDropPlugin",
          "type": "->"
        },
        {
          "file": "/var/www/clients/client1/web48/web/3rdparty/sabre/dav/lib/DAV/Server.php",
          "line": 456,
          "function": "emit",
          "class": "Sabre\\DAV\\Server",
          "type": "->"
        },
        {
          "file": "/var/www/clients/client1/web48/web/apps/dav/lib/Connector/Sabre/Server.php",
          "line": 43,
          "function": "invokeMethod",
          "class": "Sabre\\DAV\\Server",
          "type": "->"
        },
        {
          "file": "/var/www/clients/client1/web48/web/apps/dav/appinfo/v2/publicremote.php",
          "line": 139,
          "function": "start",
          "class": "OCA\\DAV\\Connector\\Sabre\\Server",
          "type": "->"
        },
        {
          "file": "/var/www/clients/client1/web48/web/public.php",
          "line": 82,
          "args": [
            "/var/www/clients/client1/web48/web/apps/dav/appinfo/v2/publicremote.php"
          ],
          "function": "require_once"
        }
      ],
      "File": "/var/www/clients/client1/web48/web/3rdparty/doctrine/dbal/src/Driver/PDO/Exception.php",
      "Line": 28,
      "Previous": {
        "Exception": "PDOException",
        "Message": "SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xFCro' for column `nextcld`.`oc_filecache`.`name` at row 1",
        "Code": "22007",
        "Trace": [
          {
            "file": "/var/www/clients/client1/web48/web/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php",
            "line": 130,
            "function": "execute",
            "class": "PDOStatement",
            "type": "->"
          },
          {
            "file": "/var/www/clients/client1/web48/web/3rdparty/doctrine/dbal/src/Connection.php",
            "line": 1207,
            "function": "execute",
            "class": "Doctrine\\DBAL\\Driver\\PDO\\Statement",
            "type": "->"
          },
          {
            "file": "/var/www/clients/client1/web48/web/3rdparty/doctrine/dbal/src/Connections/PrimaryReadReplicaConnection.php",
            "line": 292,
            "function": "executeStatement",
            "class": "Doctrine\\DBAL\\Connection",
            "type": "->"
          },
          {
            "file": "/var/www/clients/client1/web48/web/lib/private/DB/Connection.php",
            "line": 462,
            "function": "executeStatement",
            "class": "Doctrine\\DBAL\\Connections\\PrimaryReadReplicaConnection",
            "type": "->"
          },
          {
            "file": "/var/www/clients/client1/web48/web/lib/private/DB/ConnectionAdapter.php",
            "line": 67,
            "function": "executeStatement",
            "class": "OC\\DB\\Connection",
            "type": "->"
          },
          {
            "file": "/var/www/clients/client1/web48/web/lib/private/DB/QueryBuilder/QueryBuilder.php",
            "line": 306,
            "function": "executeStatement",
            "class": "OC\\DB\\ConnectionAdapter",
            "type": "->"
          },
          {
            "file": "/var/www/clients/client1/web48/web/lib/private/DB/QueryBuilder/QueryBuilder.php",
            "line": 268,
            "function": "executeStatement",
            "class": "OC\\DB\\QueryBuilder\\QueryBuilder",
            "type": "->"
          },
          {
            "file": "/var/www/clients/client1/web48/web/lib/private/Files/Cache/Cache.php",
            "line": 285,
            "function": "execute",
            "class": "OC\\DB\\QueryBuilder\\QueryBuilder",
            "type": "->"
          },
          {
            "file": "/var/www/clients/client1/web48/web/lib/private/Files/Cache/Wrapper/CacheWrapper.php",
            "line": 129,
            "function": "insert",
            "class": "OC\\Files\\Cache\\Cache",
            "type": "->"
          },
          {
            "file": "/var/www/clients/client1/web48/web/lib/private/Files/Cache/Scanner.php",
            "line": 284,
            "function": "insert",
            "class": "OC\\Files\\Cache\\Wrapper\\CacheWrapper",
            "type": "->"
          },
          {
            "file": "/var/www/clients/client1/web48/web/lib/private/Files/Cache/Scanner.php",
            "line": 217,
            "function": "addToCache",
            "class": "OC\\Files\\Cache\\Scanner",
            "type": "->"
          },
          {
            "file": "/var/www/clients/client1/web48/web/lib/private/Files/Cache/Scanner.php",
            "line": 329,
            "function": "scanFile",
            "class": "OC\\Files\\Cache\\Scanner",
            "type": "->"
          },
          {
            "file": "/var/www/clients/client1/web48/web/lib/private/Files/Cache/Updater.php",
            "line": 110,
            "function": "scan",
            "class": "OC\\Files\\Cache\\Scanner",
            "type": "->"
          },
          {
            "file": "/var/www/clients/client1/web48/web/lib/private/Files/View.php",
            "line": 259,
            "function": "update",
            "class": "OC\\Files\\Cache\\Updater",
            "type": "->",
            "args": [
              "*** sensitive parameters replaced ***"
            ]
          },
          {
            "file": "/var/www/clients/client1/web48/web/lib/private/Files/View.php",
            "line": 1153,
            "function": "writeUpdate",
            "class": "OC\\Files\\View",
            "type": "->"
          },
          {
            "file": "/var/www/clients/client1/web48/web/lib/private/Files/View.php",
            "line": 208,
            "function": "basicOperation",
            "class": "OC\\Files\\View",
            "type": "->"
          },
          {
            "file": "/var/www/clients/client1/web48/web/apps/dav/lib/Files/Sharing/FilesDropPlugin.php",
            "line": 81,
            "function": "mkdir",
            "class": "OC\\Files\\View",
            "type": "->"
          },
          {
            "file": "/var/www/clients/client1/web48/web/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
            "line": 89,
            "function": "beforeMethod",
            "class": "OCA\\DAV\\Files\\Sharing\\FilesDropPlugin",
            "type": "->"
          },
          {
            "file": "/var/www/clients/client1/web48/web/3rdparty/sabre/dav/lib/DAV/Server.php",
            "line": 456,
            "function": "emit",
            "class": "Sabre\\DAV\\Server",
            "type": "->"
          },
          {
            "file": "/var/www/clients/client1/web48/web/apps/dav/lib/Connector/Sabre/Server.php",
            "line": 43,
            "function": "invokeMethod",
            "class": "Sabre\\DAV\\Server",
            "type": "->"
          },
          {
            "file": "/var/www/clients/client1/web48/web/apps/dav/appinfo/v2/publicremote.php",
            "line": 139,
            "function": "start",
            "class": "OCA\\DAV\\Connector\\Sabre\\Server",
            "type": "->"
          },
          {
            "file": "/var/www/clients/client1/web48/web/public.php",
            "line": 82,
            "args": [
              "/var/www/clients/client1/web48/web/apps/dav/appinfo/v2/publicremote.php"
            ],
            "function": "require_once"
          }
        ],
        "File": "/var/www/clients/client1/web48/web/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php",
        "Line": 130
      }
    },
    "message": "An exception occurred while executing a query: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xFCro' for column `nextcld`.`oc_filecache`.`name` at row 1",
    "exception": [],
    "CustomMessage": "An exception occurred while executing a query: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xFCro' for column `nextcld`.`oc_filecache`.`name` at row 1"
  },
  "id": "671f85fe4f51b"
}
```
### Additional info

_No response_

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/server/issues/48942

## Steps
1. Create a file request
2. Access the file request URI
3. Enter a guest name with an umlaut `Mörris`
4. Upload a file and see a 500 request

### CODE REVIEW

**Review by provokateurin — APPROVED** [review]

File: apps/dav/lib/Files/Sharing/FilesDropPlugin.php [hunk 1]
```diff
@@ -64,7 +64,7 @@ public function beforeMethod(RequestInterface $request, ResponseInterface $respo
 		// Extract the attributes for the file request
 		$isFileRequest = false;
 		$attributes = $this->share->getAttributes();
-		$nickName = $request->getHeader('X-NC-Nickname');
+		$nickName = $request->hasHeader('X-NC-Nickname') ? urldecode($request->getHeader('X-NC-Nickname')) : null;
```
Comment (susnux) [inline apps/dav/lib/Files/Sharing/FilesDropPlugin.php:67]: Why not simply:

```suggestion
		$nickName = urldecode($request->getHeader('X-NC-Nickname'));
```

if there is no header then the empty string should be returned, this would simplify the condition below (line 73):

```diff
- if ($isFileRequest && ($nickName == null || trim($nickName) === '')) {
+ if ($isFileRequest && trim($nickName) === '') {
			throw new MethodNotAllowed('Nickname is required for file requests');
}
```

Comment (skjnldsv) [reply apps/dav/lib/Files/Sharing/FilesDropPlugin.php:67]: Because `getHeader` can return null and then `urldecode` throws

**Review by Pytal — APPROVED** [review]
