### PR TITLE
fix(files): File type filter UI sync with filter state

### LINKED ISSUE #47251: [Bug]: nextcloud 30 RC1 - Filter does not survive the change to a subdirectory
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I set the filter e.g. to "folder" and "PDFs" and hope that i can navigate to subfolders to find only PDFs.

### Steps to reproduce

1. Nextcloud 30 RC 1
2. set filter to e.g. "folder" and "PDFs"
3. filter is set
4. change to subfolder
5. filter is unset

### Expected behavior

After change to subfolder the filter is not unset but set to e.g. "folder" and "PDFs".

2024-08-15 07_34_59-Window

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

master

### Operating system

Other

### PHP engine version

None

### Web server

Other

### Database engine version

Other

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by susnux**
* Resolves https://github.com/nextcloud/server/issues/47251

## Summary

When changing the folder the filter will be re-mounted by the file list, so we need to pass the current state of the filter to the filter UI.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/files/src/components/FileListFilter/FileListFilterType.vue [hunk 1]
```diff
@@ -45,6 +45,10 @@ export default defineComponent({
 	},
 
 	props: {
+		preset: {
```
Comment (Pytal) [inline apps/files/src/components/FileListFilter/FileListFilterType.vue:48]:
```suggestion
		presets: {
```
We should use either singular or plural everywhere to minimize confusion

File: apps/files/src/filters/TypeFilter.ts [hunk 2]
```diff
@@ -142,7 +145,8 @@ class TypeFilter extends FileListFilter {
 	}
 
 	public setPreset(presets?: ITypePreset[]) {
-		this.currentPresets = presets
+		this.currentPresets = presets ?? []
+		this.currentInstance!.$props.preset = presets
```
Comment (Pytal) [inline apps/files/src/filters/TypeFilter.ts:149]:
```suggestion
		this.currentInstance!.$props.preset = presets ?? []
```
The proptype is an array so we could do this and remove the `|| []` in FileListFilterType?

File: apps/files/src/components/FileListFilter/FileListFilterType.vue [hunk 3]
```diff
@@ -71,6 +75,10 @@ export default defineComponent({
 	},
 
 	watch: {
+		/** Reset selected options if property is changed */
+		preset() {
```
Comment (Pytal) [inline apps/files/src/components/FileListFilter/FileListFilterType.vue:79]:
```suggestion
		presets() {
```
Looks like the prop was renamed to `presets`

File: apps/files/src/filters/TypeFilter.ts [hunk 4]
```diff
@@ -142,7 +144,8 @@ class TypeFilter extends FileListFilter {
...
```
Comment (Pytal) [inline apps/files/src/filters/TypeFilter.ts:148]:
```suggestion
		this.currentInstance!.$props.presets = presets
```
Same as above

**Review by nfebe — APPROVED** [review]

**Review by Pytal — APPROVED** [review]
