### PR TITLE
fix: test variables before returning

### LINKED ISSUE #47193: [Bug]: cannot delete single event of a recurring event
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

cannot delete a single event out of an recurring event

### Steps to reproduce

1. have an event series, recurring every week
2. delete one, e.g. today
3. see 500

```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>TypeError</s:exception>
  <s:message>OCA\DAV\CalDAV\EventReaderRRule::daysOfWeek(): Return value must be of type array, null returned</s:message>
</d:error>
```

### Expected behavior

delete should work

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
happens on c.nc.c
```

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by SebastianKrupinski**
* Resolves: #47193

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

File: apps/dav/lib/CalDAV/EventReaderRRule.php [hunk 1]
```diff
@@ -57,31 +57,31 @@ public function concludesOn(): DateTime | null {
 	}
 
 	public function daysOfWeek(): array {
-		return $this->byDay;
+		return is_array($this->byDay) ? $this->byDay : [];
```
Comment (miaulalala) [inline apps/dav/lib/CalDAV/EventReaderRRule.php:60]:
```suggestion
		return $this->byDay ?? [];
```

Comment (SebastianKrupinski) [reply apps/dav/lib/CalDAV/EventReaderRRule.php:60]: The doc block says that the values are only arrays, but the php declaration "protected $byDay;" has no type, so i think its safer to make sure its an array.

**Review by miaulalala — APPROVED** [review]
