### PR TITLE
Fix comments when used by other apps

### LINKED ISSUE #971: Mentioning with @ not working in Announcement Comments
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

### Steps to reproduce
1. Open Announcement Center
2. Open the Comment section of an Announcement
3. Try to mention someone with @ 

### Expected behaviour
I expect that any matching NC user will be shown similar to how mention works in the rest of Nextcloud

### Actual behaviour
The @ does not get recognized and nothing happens.

### Server configuration

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.1/8.2/8.3

**Nextcloud Announcement version:**
7.2.1

Image

### PR DESCRIPTION
**Pull request by nickvergessen**
* Resolves: https://github.com/nextcloud/announcementcenter/issues/971

## Summary

- Fix autocomplete PHP type error when commenting in another app, e.g. announcements most likely a regression from https://github.com/nextcloud/server/pull/44868/
- Fix console error spam when a user has a numeric user id

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)
- [x] [Labels added](https://github.com/nextcloud/server/labels) where applicable (ex: bug/enhancement, `3. to review`, feature component)
- [x] [Milestone added](https://github.com/nextcloud/server/milestones) for target branch/version (ex: 32.x for `stable32`)

### CODE REVIEW

File: apps/comments/src/mixins/CommentView.ts [hunk 1]
```diff
@@ -27,6 +27,7 @@ export default defineComponent({
 				key: 'editor',
 			},
 			userData: {},
+			currentResourceId: 0
```
Comment (Antreesy) [inline apps/comments/src/mixins/CommentView.ts]: Should be removed in Comments.vue (or moved from there), I guess:

```
currentResourceId: this.resourceId,
```

File: apps/comments/src/views/Comments.vue [hunk 2]
```diff
@@ -206,6 +206,9 @@ export default {
 					this.done = true
 				}
 
+				// Ensure actor id is a string
+				comments.map((comment) => {comment.props.actorId = '' + comment.props.actorId})
+
```
Comment (Antreesy) [inline apps/comments/src/views/Comments.vue:212]: For better readability, and to not have issues with reactivity at later point:
```js
// Ensure actor id is a string
comments.forEach((comment) => {
	comment.props.actorId = comment.props.actorId.toString()
})
// Insert results
this.comments = [...this.comments, ...comments]
```

File: apps/comments/src/mixins/CommentView.ts [hunk 3]
```diff
@@ -27,6 +27,7 @@ export default defineComponent({
 				key: 'editor',
 			},
 			userData: {},
+			currentResourceId: this.resourceId
```
Comment (susnux) [inline apps/comments/src/mixins/CommentView.ts]:
```suggestion
			currentResourceId: this.resourceId,
```

File: apps/comments/src/views/Comments.vue [hunk 4]
```diff
@@ -206,8 +205,13 @@ export default {
 					this.done = true
 				}
 
+				// Ensure actor id is a string
+				comments.forEach((comment) => {
+					comment.props.actorId = comment.props.actorId.toString()
+				})
```
Comment (susnux) [inline apps/comments/src/views/Comments.vue]: Why not a plain for loop?


```suggestion
				for (const comment of comments) {
					comment.props.actorId = comment.props.actorId.toString()
				}
```

**Review by susnux — APPROVED** [review]
looks good overall

**Review by Antreesy — APPROVED** [review]

**Comment by nickvergessen** [comment]
/backport fa17c55588b7d73b132b677bde54fabd2d768ee9 8ab5cf4009043a3e58d029791da0a720eb6345b8 d659cbcd0ef7d06a974913402bc1e8280b338c61 d332091105929a1e9eb2de8ad7ab0b9688253a69 to stable32

**Comment by nickvergessen** [comment]
/backport fa17c55588b7d73b132b677bde54fabd2d768ee9 8ab5cf4009043a3e58d029791da0a720eb6345b8 d659cbcd0ef7d06a974913402bc1e8280b338c61 d332091105929a1e9eb2de8ad7ab0b9688253a69 to stable31
