### PR TITLE
provide event class and typed event to LDAP loaded event; also fixing a logged deprecation message

### LINKED ISSUE #19097: Deprecated event type for OCA\User_LDAP\User\User::postLDAPBackendAdded: null
After 18.0.0, my log is being flooded with  LDAP logs like these.

```
Info | user_ldap | Cannot determine UUID for cn=W,ou=Z,dc=Y,dc=X. Skipping. 
Error | user_ldap | Could not autodetect the UUID attribute
Info | no app in context | Deprecated event type for OCA\User_LDAP\User\User::postLDAPBackendAdded: null
```
I had no errors like these on 17.0.2.

### PR DESCRIPTION
**Pull request by blizzz**
fixes #19097 

I am not  aware of any current consumers. The event is not very usable as it is fired before most apps are loaded. To keep things stable and avoid surprises nevertheless, this is the safe, backportable approach (code diverted a bit, but no biggy). With 20 and the `IBootstrap` bits from @ChristophWurst it should be a viable approach to subscribe to the typed event.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
TBH: I couldn't find any users of this event. Let's just remove it? Why should we add an event where there is no use case? If there is one we can still add it properly.

File: apps/user_ldap/lib/AppInfo/Application.php [hunk 1]
```diff
@@ -103,13 +107,15 @@ public function boot(IBootContext $context): void {
 					$configPrefixes, $ldapWrapper, $config, $notificationManager, $userSession, $userPluginManager
 				);
 				$groupBackend = new Group_Proxy($configPrefixes, $ldapWrapper, $groupPluginManager);
-				// register user backend
-				\OC_User::useBackend($userBackend);
 
-				// Hook to allow plugins to work on registered backends
-				$dispatcher->dispatch('OCA\\User_LDAP\\User\\User::postLDAPBackendAdded');
```
Comment (MorrisJobke) [inline apps/user_ldap/lib/AppInfo/Application.php:110]: I just noticed: this never worked, because the actual event is missing. Yep - for sure we should just remove those two lines and then backport them.

**Comment by blizzz** [comment]
> TBH: I couldn't find any users of this event. Let's just remove it? Why should we add an event where there is no use case? If there is one we can still add it properly.

There is, but the way it is pre-20 is not working, because the event is fired to early due to app loarding order.

File: apps/user_ldap/lib/AppInfo/Application.php (hunk 1 above)
Comment (blizzz) [reply apps/user_ldap/lib/AppInfo/Application.php:110]: So, is this a :+1: ? :)

**Comment by MorrisJobke** [comment]
> > 
> 
> There is, but the way it is pre-20 is not working, because the event is fired to early due to app loarding order.

Where?

File: apps/user_ldap/lib/AppInfo/Application.php (hunk 1 above)
Comment (MorrisJobke) [reply apps/user_ldap/lib/AppInfo/Application.php:110]: No rather a "remove it completely"

**Comment by blizzz** [comment]
> > > 
> > 
> > 
> > There is, but the way it is pre-20 is not working, because the event is fired to early due to app loarding order.
> 
> Where?

ldap_write_support (and upstream) would have taken advantage of it

File: apps/user_ldap/lib/AppInfo/Application.php (hunk 1 above)
Comment (blizzz) [reply apps/user_ldap/lib/AppInfo/Application.php:110]: OK, let's drop the legacy one for 20 and also for the stable releases. 20 gets the new stuff, stable ones nothing. okidoki?

Comment (MorrisJobke) [reply apps/user_ldap/lib/AppInfo/Application.php:110]: If this is actually used, then we can go for your current approach and provide both ways. Just need to deprecate the old way with 20. And then we can also backport the fixes (including the new events).

**Review by MorrisJobke — APPROVED** [review]
Please add a deprecation notice to #20953 for `'OCA\\User_LDAP\\User\\User::postLDAPBackendAdded'` and that the new event should be used.

File: apps/user_ldap/lib/AppInfo/Application.php (hunk 1 above)
Comment (blizzz) [reply apps/user_ldap/lib/AppInfo/Application.php:110]: > If this is actually used, then we can go for your current approach and provide both ways. Just need to deprecate the old way with 20. And then we can also backport the fixes (including the new events).

It will. I mean, I can bring ldap_write_support to that level, but rather next week.

**Review by rullzer — APPROVED** [review]

**Comment by blizzz** [comment]
> Please add a deprecation notice to #20953 for `'OCA\\User_LDAP\\User\\User::postLDAPBackendAdded'` and that the new event should be used.

done

**Comment by MorrisJobke** [comment]
> > Please add a deprecation notice to #20953 for `'OCA\\User_LDAP\\User\\User::postLDAPBackendAdded'` and that the new event should be used.
> 
> done

I added it to the table we have in that ticket

**Comment by blizzz** [comment]
> > > Please add a deprecation notice to #20953 for `'OCA\\User_LDAP\\User\\User::postLDAPBackendAdded'` and that the new event should be used.
> > 
> > 
> > done
> 
> I added it to the table we have in that ticket

oh, that's better. (life's too short to scroll down though :flushed: )

**Comment by MorrisJobke** [comment]
ref #14552
