### PR TITLE
Avoid db connections when logging db connection errors

### LINKED ISSUE #37424: [Bug]: Error handling when unable to connect to database
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

We had a network failure and our nextcloud instance lost connection to the mysql database server we are running. The error handling in this situation was inadequate to troubleshoot the issue. No logs were written to nextcloud.logs (loglevel debug) and no hint about the issue was given to the user. I would like this error to produce some kind of log to nextcloud.logs to enable efficient troubleshooting. My way of solving it was to simply remove the catches in index.php to expose the raw exception to the end user, no other method I tried managed to produce any indication at all about what was wrong.

### Steps to reproduce

1. Setup docker container running mysql:8.0.32.
2. Setup docker container running nextcloud:25.0.3-apache.
3. Disable network connection between containers.
4. Access nextcloud start page.

### Expected behavior

Exceptions thrown in index.php error handling should write to nextcloud.log.

### Installation method

Community Docker image

### Nextcloud Server version

25

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
Unable to run command in docker container.
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

_No response_

### Additional info

nextcloud.log only contains logs from before the network failure.

### PR DESCRIPTION
**Pull request by nfebe**
`\OC\Log\LogDetails::logDetails` depends on `\OC_App::getAppVersions()` which makes a database connection causing the logger to break when the database service is unavaiable.

Resolves: #37424

### CODE REVIEW

**Comment by Fenn-CS** [comment]
*As part of this PR, I decided to equally move away from our `ILogger` since it's deprecated*

> The ILogger is marked as deprecated with a decision to now use the more stadard `Psr\Log\LoggerInterface`.
> 
> This commit move all logging dependent on our custom
>  ILogger to `Psr\Log\LoggerInterface`
> 
> See : https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md#3-psrlogloggerinterface

The required changes regarding the above is much bigger project that I expected so this is work in progress but it would nice to have feedback it this is the right path.

cc: @ChristophWurst (Thank you in advance)

**Comment by ChristophWurst** [comment]
I do not thing that this fixes https://github.com/nextcloud/server/issues/37424 but it's an important and appreciated code cleanup :+1: 

We have to do this change carefully. There is still a lot of code to rely on ILogger, even if has been deprecated for a while. But we don't want to break apps, yet.

I would suggest to only continue replacing ILogger method calls with LoggerInterface for now, and leave the ILogger constants in place.

**Comment by ChristophWurst** [comment]
> I noticed that too, and my intention was to do app refactoring-next and append to this commit.

Note that only a few apps live inside this repos and are tightly bundled with Nextcloud server: https://github.com/nextcloud/server/tree/master/apps. The rest lives in independent repositories.

We will not be able to replace all ILogger usages at once. Let's try to migrate this repo and app repos independently. And once if looks like ILogger isn't use any longer we drop it from the public API found in the `\OCP` namespace.

File: lib/public/BackgroundJob/IJob.php [hunk 1]
```diff
@@ -55,7 +55,7 @@ interface IJob {
 	 * @deprecated since 25.0.0 Use start() instead. This method will be removed
 	 * with the ILogger interface
 	 */
-	public function execute(IJobList $jobList, ILogger $logger = null);
+	public function execute(IJobList $jobList, LoggerInterface $logger = null);
```
Comment (ChristophWurst) [inline lib/public/BackgroundJob/IJob.php:58]: We can't do this backwards incompatible change *yet*. Apps that implement `IJob` would have to adjust when going from Nextcloud 26 to Nextcloud 27. In the same way apps that want to support a wider range of Nextcloud, like 25-27, would not be able to exist.

The interface method has already been marked for removal in Nextcloud 25. We can drop it in Nextcloud 28.

File: lib/public/Log/ILogFactory.php [hunk 2]
```diff
@@ -40,15 +39,6 @@ interface ILogFactory {
 	 */
 	public function get(string $type): IWriter;
 
-	/**
-	 * @param string $path
-	 * @return ILogger
-	 * @since 14.0.0
-	 * @deprecated use \OCP\Log\ILogFactory::getCustomPsrLogger
```
Comment (ChristophWurst) [inline lib/public/Log/ILogFactory.php:47]: unrelated to your change but the method lacks info about the version it was deprecated

needs research on whether it is ok to remove the method already. we keep deprecated APIs for at least three major versions.

**Review by ChristophWurst — CHANGES_REQUESTED** [review]
Public APIs are tricky :)

File: lib/public/BackgroundJob/IJob.php (hunk 1 above)
Comment (Fenn-CS) [reply lib/public/BackgroundJob/IJob.php:58]: Make sense! I would backtrack and stick with your earlier recommendation!

File: lib/private/Server.php [hunk 3]
```diff
@@ -1834,6 +1834,13 @@ public function getLogger() {
 		return $this->get(ILogger::class);
 	}
 
+	public function getPsrLogger(): LoggerInterface {
+		$logFactory = $this->get(LogFactory::class);
+		$default = $this->getConfig()->getSystemValue('datadirectory', \OC::$SERVERROOT . '/data') . '/nextcloud.log';
```
Comment (Fenn-CS) [inline lib/private/Server.php:1839]: `getConfig()` and `getSystemConfig()` methods are marked as deprecated, what new method is available to achieve this?

**Review by nfebe — COMMENTED** [review]
Overall, this catches the DB error and displays something like

```
Fatal error: Uncaught Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] could not connect to server: Connection refused Is the server running on host "localhost" (127.0.0.1) and accepting TCP/IP connections on port 5432? in /home/fenn/nextcloud/nextcloud/lib/private/DB/Connection.php:142 Stack trace: #0 /home/fenn/nextcloud/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1531): OC\DB\Connection->connect() #1 /home/fenn/nextcloud/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1029): Doctrine\DBAL\Connection->getWrappedConnection() #2 /home/fenn/nextcloud/nextcloud/lib/private/DB/Connection.php(264): Doctrine\DBAL\Connection->executeQuery() #3 /home/fenn/nextcloud/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php(345): OC\DB\Connection->executeQuery() #4 /home/fenn/nextcloud/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(280): Doctrine\DBAL\Query\QueryBuilder->execute() #5 /home/fenn/nextcloud/nextcloud/lib/private/AppConfig.php(418): OC\DB\QueryBuilder\QueryBuilder->execute() #6 /home/fenn/nextcloud/nextcloud/lib/private/AppConfig.php(226): OC\AppConfig->loadConfigValues() #7 /home/fenn/nextcloud/nextcloud/lib/private/AllConfig.php(217): OC\AppConfig->getValue() #8 /home/fenn/nextcloud/nextcloud/lib/private/Server.php(1840): OC\AllConfig->getAppValue() #9 /home/fenn/nextcloud/nextcloud/index.php(77): OC\Server->getPsrLogger() #10 {main} thrown in /home/fenn/nextcloud/nextcloud/lib/private/DB/Connection.php on line 142
```

instead of the regular

```
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.
```

I am also able to see the error in `/var/log/apache2/error.log`

My expectation was that the `customPsrLogger` would log to `$dataDir.'nextcloud.log'` but nothing is written on that log.

Finally I didn't expect to logger to interrupt the sending regular error message that points to the logs.

File: lib/private/Server.php (hunk 3 above)
Comment (Fenn-CS) [reply lib/private/Server.php:1839]: Turns out `getSystemValue()` and `getAppValue()` all depend on a working database connection so it causes the issue I reported  in my self review.

Is there a way to read the values from `config.php` that does not require the db set up?

Comment (miaulalala) [reply lib/private/Server.php:1839]: you're probably going to read the `config.php` directly. At this point, the database is already a goner and it's just about handling the error gracefully, so that is unusual but the only way to do it.

**Comment by Fenn-CS** [comment]
So after setting a `Psr` compliant logger in `index.php` it appears to me like the only way to write to the log file is to use one of these methods `OC\Log\Errorlog->write()` or `\OC\Log\File->write()` in the `catch` section of the db connect function where this error is thrown (and caught in `index.php` without being logged)

https://github.com/nextcloud/server/blob/8a79636bcb407229a677f12f4ececaeaefdcb5b4/lib/private/DB/Connection.php#L138-L141


So something like 

```php
		} catch (Exception $e) {
			$logFilePath = \OC::getLogFile();
			$logFile = new File($logFilePath, '', $this->systemConfig);
			$logFile->write('app', 'Log testing', 3); // Throws memory limit exceeded
                        // Additionally
			$connectionErrorLogger = \OC::$server->get(LogFactory::class);
			$connectionErrorLogger = $connectionErrorLogger->getCustomPsrLogger($logFilePath);
			$connectionErrorLogger->error("Test Error Message", []); // Throws memory limit exceeded
			 throw new Exception('Failed to connect to the database: ' . $e->getMessage(), $e->getCode());
		}
```

Essentially calling various log methods in the `OC\DB\Connection->connect()` would lead to a memory limit exceeded error.

```Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /home/fenn/nextcloud/nextcloud/3rdparty/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php on line 81```

Questions
---
- Is this something that anyone has seen and what could be the issue? 
- Are my conclusions about the methods necessary to write to log file true?

Thank you! 

cc : @miaulalala @ChristophWurst

**Comment by Fenn-CS** [comment]
Update (now fixed)
--- 
I added the commit :

```
Avoid making db connection when logging about database connection

For various reasons, sometimes a database would not be possible. Our file
 logger before this commit has a function call that relies on a db connection
 that is ironic and creates some kind of chicken and egg scenario. This commit,
resolves that.
```

### How does log file look when db there's a db connection problem?

```
"app":"no app in context","message":{"Exception":"Doctrine\\DBAL\\Exception","Message":"Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"localhost\" (127.0.0.1) and accepting\n\tTCP\/IP connections on port 5432?","Code":7,"Trace":[{"file":"\/home\/fenn\/nextcloud\/nextcloud\/3rdparty\/doctrine\/dbal\/src\/Connection.php","line":1531,"function":"connect","class":"OC\\DB\\Connection","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/3rdparty\/doctrine\/dbal\/src\/Connection.php","line":1029,"function":"getWrappedConnection","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/DB\/Connection.php","line":285,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/3rdparty\/doctrine\/dbal\/src\/Query\/QueryBuilder.php","line":345,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/DB\/QueryBuilder\/QueryBuilder.php","line":280,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/AppConfig.php","line":418,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/AppConfig.php","line":184,"function":"loadConfigValues","class":"OC\\AppConfig","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/AppConfig.php","line":374,"function":"getApps","class":"OC\\AppConfig","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/legacy\/OC_App.php","line":801,"function":"getValues","class":"OC\\AppConfig","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/Server.php","line":731,"function":"getAppVersions","class":"OC_App","type":"::"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":171,"function":"OC\\{closure}","class":"OC\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php","line":122,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":138,"function":"offsetGet","class":"Pimple\\Container","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/ServerContainer.php","line":171,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":65,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":193,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":171,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php","line":118,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":138,"function":"offsetGet","class":"Pimple\\Container","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/ServerContainer.php","line":171,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":65,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/Server.php","line":1111,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":171,"function":"OC\\{closure}","class":"OC\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php","line":122,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":138,"function":"offsetGet","class":"Pimple\\Container","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/ServerContainer.php","line":171,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":65,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/Server.php","line":2074,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/Files\/View.php","line":119,"function":"getLockingProvider","class":"OC\\Server","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/Server.php","line":465,"function":"__construct","class":"OC\\Files\\View","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":171,"function":"OC\\{closure}","class":"OC\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php","line":122,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":138,"function":"offsetGet","class":"Pimple\\Container","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/ServerContainer.php","line":171,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":65,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/Server.php","line":1469,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/base.php","line":624,"function":"boot","class":"OC\\Server","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/base.php","line":1181,"function":"init","class":"OC","type":"::"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/index.php","line":35,"args":["\/home\/fenn\/nextcloud\/nextcloud\/lib\/base.php"],"function":"require_once"}],"File":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/DB\/Connection.php","Line":158,"message":"Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"localhost\" (127.0.0.1) and accepting\n\tTCP\/IP connections on port 5432?","exception":{},"CustomMessage":"Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"localhost\" (127.0.0.1) and accepting\n\tTCP\/IP connections on port 5432?"},"level":1}
{"app":"core","message":{"Exception":"Doctrine\\DBAL\\Exception","Message":"Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host \"localhost\" (127.0.0.1) and accepting\n\tTCP\/IP connections on port 5432?","Code":7,"Trace":[{"file":"\/home\/fenn\/nextcloud\/nextcloud\/3rdparty\/doctrine\/dbal\/src\/Connection.php","line":1531,"function":"connect","class":"OC\\DB\\Connection","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/3rdparty\/doctrine\/dbal\/src\/Connection.php","line":1029,"function":"getWrappedConnection","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/DB\/Connection.php","line":285,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/3rdparty\/doctrine\/dbal\/src\/Query\/QueryBuilder.php","line":345,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/DB\/QueryBuilder\/QueryBuilder.php","line":280,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/AppConfig.php","line":418,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/AppConfig.php","line":184,"function":"loadConfigValues","class":"OC\\AppConfig","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/AppConfig.php","line":374,"function":"getApps","class":"OC\\AppConfig","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/legacy\/OC_App.php","line":801,"function":"getValues","class":"OC\\AppConfig","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/Server.php","line":731,"function":"getAppVersions","class":"OC_App","type":"::"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":171,"function":"OC\\{closure}","class":"OC\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php","line":122,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":138,"function":"offsetGet","class":"Pimple\\Container","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/ServerContainer.php","line":171,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":65,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":193,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":171,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php","line":118,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":138,"function":"offsetGet","class":"Pimple\\Container","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/ServerContainer.php","line":171,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":65,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/Server.php","line":1111,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":171,"function":"OC\\{closure}","class":"OC\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php","line":122,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":138,"function":"offsetGet","class":"Pimple\\Container","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/ServerContainer.php","line":171,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":65,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/Server.php","line":2074,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/Files\/View.php","line":119,"function":"getLockingProvider","class":"OC\\Server","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/Server.php","line":465,"function":"__construct","class":"OC\\Files\\View","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":171,"function":"OC\\{closure}","class":"OC\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php","line":122,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":138,"function":"offsetGet","class":"Pimple\\Container","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/ServerContainer.php","line":171,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":65,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/Server.php","line":1469,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/base.php","line":624,"function":"boot","class":"OC\\Server","type":"->"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/base.php","line":1181,"function":"init","class":"OC","type":"::"},{"file":"\/home\/fenn\/nextcloud\/nextcloud\/index.php","line":35,"args":["\/home\/fenn\/nextcloud\/nextcloud\/lib\/base.php"],"function":"require_once"}],"File":"\/home\/fenn\/nextcloud\/nextcloud\/lib\/private\/DB\/Connection.php","Line":158,"CustomMessage":"--"},"level":1}
```

### About the question in the last update

I am still not sure why calling various methods (I tried with logger methods such  and `Log\File->write()`) would lead to a memory execeeded exception in `DBAL` but my best guess is, those methods use a fair amount of memory and are then called multiples times. Printing a string once from the error handling catch for `OC\DB\Connection.php` leads to the string being printed more than 10 times on output, which implies a db connection is attempted several times for the application is boostraped.

**Comment by kesselb** [comment]
> Our file logger before this commit has a function call that relies on a db connection that is ironic and creates some kind of chicken and egg scenario.

Hi, do you know which function is the issue?

File: lib/base.php [hunk 4]
```diff
@@ -1160,6 +1160,22 @@ protected static function handleAuthHeaders(): void {
...
+	/*
+	* Sometimes the database service might not be available, see issue #37424
+	* hence getting configuration via the database would not be possible.
+	* This method would return the logfile path read directly from the config
+	* file. This is an anti-pattern and only done because there's no other way
+	* to gracefully handle database connection errors. We also don't want to expose the full
+	* self::$config object as it might contain important secrets.
+	*/
+	public static function getLogFilePath(): string {
+		return self::$config->getValue('logfile', self::$SERVERROOT . '/data' . '/nextcloud.log');
```
Comment (artonge) [inline lib/base.php:1173]: Admins can change the location of the data directory, so this might not always work:

```php
  'datadirectory' => '/arbitrary_data_path',
```

File: lib/private/Server.php [hunk 5]
```diff
@@ -1834,6 +1834,13 @@ public function getLogger() {
 		return $this->get(ILogger::class);
 	}
 
+	public function getPsrLogger(): LoggerInterface {
+		$logFactory = $this->get(LogFactory::class);
+		$logFile = \OC::$server->get(SystemConfig::class)->getValue('logfile', false);
+		$logFile = $logFile ? $logFile : \OC::$SERVERROOT . '/data/nextcloud.log';
```
Comment (artonge) [inline lib/private/Server.php:1840]: Same here

File: index.php [hunk 6]
```diff
@@ -30,12 +30,16 @@
...
 try {
 	require_once __DIR__ . '/lib/base.php';
 
 	OC::handleRequest();
 } catch (\OC\ServiceUnavailableException $ex) {
-	\OC::$server->getLogger()->logException($ex, ['app' => 'index']);
+	\OC::$server->getPsrLogger()->error($ex->getMessage(), [
+		'exception' => $ex,
+	]);
+	\OC::getLogFile()->write('core', $ex->getMessage(), 3);
```
Comment (artonge) [inline index.php:42]: Why do we need to log twice?

File: lib/base.php (hunk 4 above)
Comment (Fenn-CS) [reply lib/base.php:1173]: @artonge I wonder if that would have an effect here because when there's a database connection error, the values set by the admin can't be read except looking at the config file directly.

This looks at the config file and if it's not set uses a default.

File: index.php (hunk 6 above)
Comment (Fenn-CS) [reply index.php:42]: The first logger does not actually write to file, the second logger writes to file.

**Comment by Fenn-CS** [comment]
@kesselb Sorry for the delayed response the function that does this is `logDetailsAsJSON`.

See : https://github.com/nextcloud/server/blob/master/lib/private/Log/LogDetails.php

File: lib/base.php (hunk 4 above)
Comment (kesselb) [reply lib/base.php:1173]: > the values set by the admin can't be read except by looking at the config file directly.

https://github.com/nextcloud/server/blob/master/lib/private/Config.php
https://github.com/nextcloud/server/blob/master/lib/private/SystemConfig.php

Should work, even with invalid database credentials.

**Comment by kesselb** [comment]
> @kesselb Sorry for the delayed response the function that does this is `logDetailsAsJSON`.
> 
> See : https://github.com/nextcloud/server/blob/master/lib/private/Log/LogDetails.php

Thank you :+1: 

It could be \OC_User::getUser() in logDetails then.

File: lib/base.php (hunk 4 above)
Comment (Fenn-CS) [reply lib/base.php]: Right @artonge, thanks for pointing that out. Now resolved.

@kesselb yep, thanks for that, it is actually what I am currently using.

File: index.php (hunk 6 above)
Comment (Fenn-CS) [reply index.php:42]: I am not sure why methods like `error`, `info` and `warning` from our implementation of the `Psr` `LoggerInterface` would not write to file.

But I realized they don't and that writing to file is only currently possible via [`OC/Log/File`](https://github.com/nextcloud/server/blob/master/lib/private/Log/File.php)

@kesselb Do you know if this is true?

**Comment by kesselb** [comment]
> > @kesselb Sorry for the delayed response the function that does this is `logDetailsAsJSON`.
> > See : https://github.com/nextcloud/server/blob/master/lib/private/Log/LogDetails.php
> 
> Thank you +1
> 
> It could be \OC_User::getUser() in logDetails then.

https://github.com/nextcloud/server/blob/b294edad804f40618a96116845615831302d0357/lib/private/Server.php#L733

The above line causes the issue. getAppVersions requires a working database connection to fetch the app versions. The function is called in the memcache factory :(

**Comment by Fenn-CS** [comment]
> The above line causes the issue. getAppVersions requires a working database connection to fetch the app versions. The function is called in the memcache factory :(

Thank you @kesselb .... Are you suggesting that a solution to refactor that method is sort? 

For now, the logic is "manually" create the json entry if `logAsJSON` fails with a database connection error...

```php
		try {
			$entry = $this->logDetailsAsJSON($app, $message, $level);
		} catch (\Doctrine\DBAL\Exception $e) {
		    $entry = json_encode(['app' => $app, 'message' => $message, 'level' => 1]);
}
```
Please let me what course of action you are suggesting.

File: lib/private/Server.php [hunk 7]
```diff
@@ -1834,6 +1834,14 @@ public function getLogger() {
...
 	}
 
+	public function getPsrLogger(): LoggerInterface {
+		$logFactory = $this->get(LogFactory::class);
+		$logFile = \OC::$server->get(SystemConfig::class)->getValue('logfile', false);
+		$dataDirectory = \OC::$server->get(SystemConfig::class)->getValue('datadirectory', '/data');
+		$logFile = $logFile ? $logFile : \OC::$SERVERROOT . $dataDirectory . '/nextcloud.log';
+		return $logFactory->getCustomPsrLogger($logFile);
+	}
+
```
Comment (come-nc) [inline lib/private/Server.php:1844]: What is that?
You should use `\OCP\Server::get(LoggerInterface::class)` in index.php. Or does it fail in this specific case for some reason?
```suggestion
```

**Comment by come-nc** [comment]
If the problem really is the call to `\OC_App::getAppVersions();`, wrapping it in a try/catch should be enough?

File: lib/private/Server.php (hunk 7 above)
Comment (Fenn-CS) [reply lib/private/Server.php:1844]: Yes it does not work.... I believe the class would not be loaded yet for use in `index.php` since that's where the boostraping starts?

Trial report :

```

Comment (Fenn-CS) [reply lib/private/Server.php:1844]: Also, it's my observation that calling the `LoggerInterace`'s `error()` or similar functions does not result to it writing on file.

Comment (come-nc) [reply lib/private/Server.php:1844]: But that is how all the rest of the software is writing logs?
Also, ILogger::class and LoggerInterface::class are registered at the same time, so since index.php is using getLogger, it should be able to use get(LoggerInterface::class) as well.

Comment (Fenn-CS) [reply lib/private/Server.php:1844]: @come-nc Sure... I guess the issue those depend on a database connection?

**Comment by come-nc** [comment]
> If the problem really is the call to `\OC_App::getAppVersions();`, wrapping it in a try/catch should be enough?

This kind of things seem to work for me:
```
diff --git a/lib/private/Server.php b/lib/private/Server.php
index bb4e217efa3..c0071114b8f 100644
--- a/lib/private/Server.php
+++ b/lib/private/Server.php
@@ -730,7 +730,12 @@ class Server extends ServerContainer implements IServerContainer {
 
                        if ($config->getSystemValueBool('installed', false) && !(defined('PHPUNIT_RUN') && PHPUNIT_RUN)) {
                                if (!$config->getSystemValueBool('log_query')) {
-                                       $v = \OC_App::getAppVersions();
+                                       try {
+                                               $v = \OC_App::getAppVersions();
+                                       } catch (\Throwable $t) {
+                                               // If this throws, we have to ignore it to be able to log errors in database connection
+                                               $v = [];
+                                       }
                                } else {
                                        // If the log_query is enabled, we can not get the app versions
                                        // as that does a query, which will be logged and the logging
```

Now the problem is that this silently ignore an error. I would feel better if I understood why it’s not possible to log without building `OC\Memcache\Factory`

File: index.php (hunk 6 above)
Comment (Fenn-CS) [reply index.php:42]: I figured this out! Thanks to @artonge

File: index.php [hunk 8]
```diff
@@ -30,12 +30,15 @@
...
+
 try {
 	require_once __DIR__ . '/lib/base.php';
 
 	OC::handleRequest();
 } catch (\OC\ServiceUnavailableException $ex) {
-	\OC::$server->getLogger()->logException($ex, ['app' => 'index']);
+	\OC::$server->getPsrLogger()->error($ex->getMessage(), [
+		'exception' => $ex,
+	]);
```
Comment (come-nc) [inline index.php:41]:
```suggestion
	\OC::$server->get(LoggerInterface::class)->error($ex->getMessage(), [
		'exception' => $ex,
	]);
```

Comment (come-nc) [reply index.php:41]: Or even better
```suggestion
	\OCP::Server::get(LoggerInterface::class)->error($ex->getMessage(), [
		'exception' => $ex,
	]);
```

File: index.php [hunk 9]
```diff
@@ -30,12 +30,15 @@
...
+
 try {
 	require_once __DIR__ . '/lib/base.php';
 
 	OC::handleRequest();
 } catch (\OC\ServiceUnavailableException $ex) {
-	\OC::$server->getLogger()->logException($ex, ['app' => 'index']);
+	\OC::$server->get(LoggerInterface::class)->error($ex->getMessage(), [
+		'exception' => $ex,
+	]);
```
[the remark this answers is not in the document]
Comment (Fenn-CS) [reply index.php:41]: Alright.

**Comment by Fenn-CS** [comment]
> Now the problem is that this silently ignore an error. I would feel better if I understood why it’s not possible to log without building OC\Memcache\Factory

I added a try-catch that would only catch db connection  failures, I guess that's a more convenient work around.

**Review by artonge — COMMENTED** [review]
So the fix is in `Server.php` and the other changes in `index.php` are only to modernize how we get the logger right?

**Comment by Fenn-CS** [comment]
> So the fix is in Server.php and the other changes in index.php are only to modernize how we get the logger right?

Exactly!

**Comment by kesselb** [comment]
> Now the problem is that this silently ignore an error. I would feel better if I understood why it’s not possible to log without building OC\Memcache\Factory

Good question :+1: 

https://github.com/nextcloud/server/blob/fc076271c791998272856b640be4b63cfe3263a2/lib/private/Log/LogDetails.php#L54

https://github.com/nextcloud/server/blob/fc076271c791998272856b640be4b63cfe3263a2/lib/private/AppFramework/Http/Request.php#L123

CsrfTokenManager -> SessionStorage -> ISession 

https://github.com/nextcloud/server/blob/b294edad804f40618a96116845615831302d0357/lib/private/Server.php#L1403-L1405

https://github.com/nextcloud/server/blob/b294edad804f40618a96116845615831302d0357/lib/private/Server.php#L669

\OC\User\Session -> OC\User\Manager -> ICacheFactory 

ICacheFactory then uses `\OC_App::getAppVersions();` for the cache prefix :cry: 

The good news is, that the csrf token manager is not an essential dependency for the request object itself. We can extract the functionality from the request object to an own service.

**Review by artonge — APPROVED** [review]

File: lib/private/Server.php [hunk 10]
```diff
@@ -730,7 +730,13 @@ public function __construct($webRoot, \OC\Config $config) {
 
 			if ($config->getSystemValueBool('installed', false) && !(defined('PHPUNIT_RUN') && PHPUNIT_RUN)) {
 				if (!$config->getSystemValueBool('log_query')) {
-					$v = \OC_App::getAppVersions();
+					try {
+						$v = \OC_App::getAppVersions();
+					} catch (\Doctrine\DBAL\Exception $e) {
+						// Database service probably unavailable
+						// Probably related to https://github.com/nextcloud/server/issues/37424
+						$v = [];
```
Comment (kesselb) [inline lib/private/Server.php:738]: $v = [] means we are using the nextcloud version number as cache prefix. I'm uncertain if we need a cache prefix/a memcache instance after all.  Likely the database is not available, what do we want to cache? 

```suggestion
						return $arrayCacheFactory;
```

I don't know if that's better or worse. Technically, we disable permanent caching when using the arrayCacheFactory and use a temporary cache,

File: lib/private/Server.php [hunk 11]
```diff
@@ -730,7 +730,13 @@ public function __construct($webRoot, \OC\Config $config) {
 
 			if ($config->getSystemValueBool('installed', false) && !(defined('PHPUNIT_RUN') && PHPUNIT_RUN)) {
 				if (!$config->getSystemValueBool('log_query')) {
-					$v = \OC_App::getAppVersions();
+					try {
+						$v = \OC_App::getAppVersions();
+					} catch (\Doctrine\DBAL\Exception $e) {
```
Comment (come-nc) [inline lib/private/Server.php:735]: I’m lost, in the call we had, I thought the conclusion was that this was the wrong place to put the try/catch, and that it should be… I can’t remember where.
On the call to getUser in the logger, no?

Comment (Fenn-CS) [reply lib/private/Server.php:735]: @come-nc Yeah you are right, however by the time you left I had realized `getUser` was not the culprit. It makes not database access AFIAK.

The stack trace points to `\OC_App::getAppVersions()` and catching the exception there worked unlike with `getUser`

File: lib/private/Server.php (hunk 10 above)
Comment (Fenn-CS) [reply lib/private/Server.php:738]: I would let you decide on that since you have more experience with this code base and I would implement the conclusion.

Thanks @kesselb

Comment (kesselb) [reply lib/private/Server.php:738]: Fair question. I think we should return the arrayCacheFactory when the database is unavailable (and we run into the exception block).

What would we cache when the database is unavailable? ;) If the database is available again, the cache prefix is different, hence the old data is stale. A fluent cache provide seems reasonable for this scenario.

Comment (Fenn-CS) [reply lib/private/Server.php:738]: Thanks @kesselb would do this right away to this can be closed ASAP!

I hear you are not well, I wish you fast recovery! :)

**Review by come-nc — APPROVED** [review]

**Comment by Fenn-CS** [comment]
@ChristophWurst please can you approve this for merging?

**Review by ChristophWurst — APPROVED** [review]
