### PR TITLE
fix(userstatus): catch unique constraint violation

### LINKED ISSUE #42625: [Bug]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'userid' for key 'user_status_uid_ix'
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I don't know (yet).

Log (sentry) says

```
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'userid' for key 'user_status_uid_ix'
#20 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php(130): PDOStatement::execute
#19 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php(130): Doctrine\DBAL\Driver\PDO\Statement::execute
#18 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1202): Doctrine\DBAL\Connection::executeStatement
#17 /var/www/nextcloud/lib/private/DB/Connection.php(294): OC\DB\Connection::executeStatement
#16 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php(386): Doctrine\DBAL\Query\QueryBuilder::execute
#15 /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(280): OC\DB\QueryBuilder\QueryBuilder::execute
#14 /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(326): OC\DB\QueryBuilder\QueryBuilder::executeStatement
#13 /var/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php(137): OCP\AppFramework\Db\QBMapper::insert
#12 /user_status/lib/Listener/UserLiveStatusListener.php(113): OCA\UserStatus\Listener\UserLiveStatusListener::handle
#11 /var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php(86): OC\EventDispatcher\ServiceEventListener::__invoke
#10 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(230): Symfony\Component\EventDispatcher\EventDispatcher::callListeners
#9 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher::dispatch
#8 /var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php(94): OC\EventDispatcher\EventDispatcher::dispatch
#7 /var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php(106): OC\EventDispatcher\EventDispatcher::dispatchTyped
#6 /user_status/lib/Controller/HeartbeatController.php(100): OCA\UserStatus\Controller\HeartbeatController::heartbeat
#5 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(230): OC\AppFramework\Http\Dispatcher::executeController
#4 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(137): OC\AppFramework\Http\Dispatcher::dispatch
#3 /var/www/nextcloud/lib/private/AppFramework/App.php(184): OC\AppFramework\App::main
#2 /var/www/nextcloud/lib/private/Route/Router.php(315): OC\Route\Router::match
#1 /var/www/nextcloud/ocs/v1.php(65): require_once
#0 /var/www/nextcloud/ocs/v2.php(23): null

Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'userid' for key 'user_status_uid_ix'
#20 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Exception.php(28): Doctrine\DBAL\Driver\PDO\Exception::new
#19 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php(132): Doctrine\DBAL\Driver\PDO\Statement::execute
#18 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1202): Doctrine\DBAL\Connection::executeStatement
#17 /var/www/nextcloud/lib/private/DB/Connection.php(294): OC\DB\Connection::executeStatement
#16 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php(386): Doctrine\DBAL\Query\QueryBuilder::execute
#15 /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(280): OC\DB\QueryBuilder\QueryBuilder::execute
#14 /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(326): OC\DB\QueryBuilder\QueryBuilder::executeStatement
#13 /var/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php(137): OCP\AppFramework\Db\QBMapper::insert
#12 /user_status/lib/Listener/UserLiveStatusListener.php(113): OCA\UserStatus\Listener\UserLiveStatusListener::handle
#11 /var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php(86): OC\EventDispatcher\ServiceEventListener::__invoke
#10 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(230): Symfony\Component\EventDispatcher\EventDispatcher::callListeners
#9 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher::dispatch
#8 /var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php(94): OC\EventDispatcher\EventDispatcher::dispatch
#7 /var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php(106): OC\EventDispatcher\EventDispatcher::dispatchTyped
#6 /user_status/lib/Controller/HeartbeatController.php(100): OCA\UserStatus\Controller\HeartbeatController::heartbeat
#5 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(230): OC\AppFramework\Http\Dispatcher::executeController
#4 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(137): OC\AppFramework\Http\Dispatcher::dispatch
#3 /var/www/nextcloud/lib/private/AppFramework/App.php(184): OC\AppFramework\App::main
#2 /var/www/nextcloud/lib/private/Route/Router.php(315): OC\Route\Router::match
#1 /var/www/nextcloud/ocs/v1.php(65): require_once
#0 /var/www/nextcloud/ocs/v2.php(23): null

Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'userid' for key 'user_status_uid_ix'
#21 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php(62): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter::convert
#20 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1938): Doctrine\DBAL\Connection::handleDriverException
#19 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1880): Doctrine\DBAL\Connection::convertExceptionDuringQuery
#18 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1208): Doctrine\DBAL\Connection::executeStatement
#17 /var/www/nextcloud/lib/private/DB/Connection.php(294): OC\DB\Connection::executeStatement
#16 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php(386): Doctrine\DBAL\Query\QueryBuilder::execute
#15 /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(280): OC\DB\QueryBuilder\QueryBuilder::execute
#14 /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(326): OC\DB\QueryBuilder\QueryBuilder::executeStatement
#13 /var/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php(137): OCP\AppFramework\Db\QBMapper::insert
#12 /user_status/lib/Listener/UserLiveStatusListener.php(113): OCA\UserStatus\Listener\UserLiveStatusListener::handle
#11 /var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php(86): OC\EventDispatcher\ServiceEventListener::__invoke
#10 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(230): Symfony\Component\EventDispatcher\EventDispatcher::callListeners
#9 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher::dispatch
#8 /var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php(94): OC\EventDispatcher\EventDispatcher::dispatch
#7 /var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php(106): OC\EventDispatcher\EventDispatcher::dispatchTyped
#6 /user_status/lib/Controller/HeartbeatController.php(100): OCA\UserStatus\Controller\HeartbeatController::heartbeat
#5 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(230): OC\AppFramework\Http\Dispatcher::executeController
#4 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(137): OC\AppFramework\Http\Dispatcher::dispatch
#3 /var/www/nextcloud/lib/private/AppFramework/App.php(184): OC\AppFramework\App::main
#2 /var/www/nextcloud/lib/private/Route/Router.php(315): OC\Route\Router::match
#1 /var/www/nextcloud/ocs/v1.php(65): require_once
#0 /var/www/nextcloud/ocs/v2.php(23): null

OC\DB\Exceptions\DbalException: An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'userid' for key 'user_status_uid_ix'
#15 /var/www/nextcloud/lib/private/DB/Exceptions/DbalException.php(71): OC\DB\Exceptions\DbalException::wrap
#14 /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(328): OC\DB\QueryBuilder\QueryBuilder::executeStatement
#13 /var/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php(137): OCP\AppFramework\Db\QBMapper::insert
#12 /user_status/lib/Listener/UserLiveStatusListener.php(113): OCA\UserStatus\Listener\UserLiveStatusListener::handle
#11 /var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php(86): OC\EventDispatcher\ServiceEventListener::__invoke
#10 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(230): Symfony\Component\EventDispatcher\EventDispatcher::callListeners
#9 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher::dispatch
#8 /var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php(94): OC\EventDispatcher\EventDispatcher::dispatch
#7 /var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php(106): OC\EventDispatcher\EventDispatcher::dispatchTyped
#6 /user_status/lib/Controller/HeartbeatController.php(100): OCA\UserStatus\Controller\HeartbeatController::heartbeat
#5 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(230): OC\AppFramework\Http\Dispatcher::executeController
#4 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(137): OC\AppFramework\Http\Dispatcher::dispatch
#3 /var/www/nextcloud/lib/private/AppFramework/App.php(184): OC\AppFramework\App::main
#2 /var/www/nextcloud/lib/private/Route/Router.php(315): OC\Route\Router::match
#1 /var/www/nextcloud/ocs/v1.php(65): require_once
#0 /var/www/nextcloud/ocs/v2.php(23): null
```

### Steps to reproduce

1. ???

### Expected behavior

No error

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

More error details in https://nextcloud-gmbh.sentry.io/issues/4628540536

### PR DESCRIPTION
**Pull request by miaulalala**
* Resolves: https://github.com/nextcloud/server/issues/42625

## Summary
Due to how we have our read/write commit set up, sometimes a different process writes to the DB but we don't read it when running a SELECT. We can therefore ignore the Unique Constraint Violation and drop the insert completely.

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] ~~Screenshots before/after for front-end changes~~
- [ ] ~~Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required~~
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by blizzz — APPROVED** [review]

File: apps/user_status/lib/Listener/UserLiveStatusListener.php [hunk 1]
```diff
@@ -110,7 +113,15 @@ public function handle(Event $event): void {
 			$userStatus->setIsUserDefined(false);
 
 			if ($userStatus->getId() === null) {
-				$this->mapper->insert($userStatus);
+				try {
+					$this->mapper->insert($userStatus);
+				} catch (Exception $e) {
+					if ($e->getReason() === Exception::REASON_UNIQUE_CONSTRAINT_VIOLATION) {
+						$this->logger->debug('Unique constraint violation for live user status');
```
Comment (ChristophWurst) [inline apps/user_status/lib/Listener/UserLiveStatusListener.php:120]: nit: log the exception object for debuggability

File: apps/user_status/lib/Listener/UserLiveStatusListener.php [hunk 2]
```diff
@@ -110,7 +113,15 @@ public function handle(Event $event): void {
...
+						return;
```
Comment (ChristophWurst) [inline apps/user_status/lib/Listener/UserLiveStatusListener.php:121]: please leave a comment explaining *why* this error condition is ignored

**Review by ChristophWurst — APPROVED** [review]
nitpicks, otherwise :+1:

**Review by ChristophWurst — APPROVED** [review]
:sunglasses:

**Comment by miaulalala** [comment]
Failing test is OCA\Files_External\Tests\Storage\SmbTest::testNotifyGetChanges (unrelated).

@blizzz can I haz force merge possibly?

**Comment by ChristophWurst** [comment]
@jendrikw thank you for the feedback. What you are reporting with https://github.com/nextcloud/server/issues/42625#issuecomment-2708773721 is not the same code path.
