### PR TITLE
CalDavBackend: check if timerange is array before accessing

### LINKED ISSUE #20784: CalDavBackend.php: Trying to access array offset on value of type bool
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create a calendar
2. Add the Nextcloud account to Gnome

### Expected behaviour
No errors in the log file

### Actual behaviour
`Trying to access array offset on value of type bool at /var/www/nextcloud/apps/dav/lib/CalDAV/CalDavBackend.php#1323`
Refers to this line in the master branch:
https://github.com/nextcloud/server/blob/8910a1ffcba8d78831a238d170700e8ace3e0979/apps/dav/lib/CalDAV/CalDavBackend.php#L1320

### Server configuration

**Operating system:** CentOS 8

**Web server:** Nginx

**Database:** PostgreSQL

**PHP version:** 7.4

**Nextcloud version:** 18.0.4.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from previous minor version

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/latest.tar.bz2

**Signing status:** No errors have been found.

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Logs
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"XXX","level":3,"time":"XXX","remoteAddr":"XXX","user":"admin","app":"PHP","method":"REPORT","url":"/remote.php/caldav/calendars/admin/XXX/","message":"Trying to access array offset on value of type bool at /var/www/nextcloud/apps/dav/lib/CalDAV/CalDavBackend.php#1323","userAgent":"Evolution/3.34.4","version":"18.0.4.2"}
```
</details>

### PR DESCRIPTION
**Pull request by simonspa**
This fixes #20784. Some CalDav clients (such as Evolution/GNOME contacts) seem to send `time-range: false` instead of not adding the `time-range` keyword at all, so we need to check if it is an array before actually using it.

### CODE REVIEW

File: apps/dav/lib/CalDAV/CalDavBackend.php [hunk 1]
```diff
@@ -1364,7 +1365,7 @@ public function calendarQuery($calendarId, array $filters, $calendarType = self:
 				$requirePostFilter = false;
 			}
 			// There was a time-range filter
-			if ($componentType === 'VEVENT' && isset($filters['comp-filters'][0]['time-range'])) {
+			if ($componentType === 'VEVENT' && isset($filters['comp-filters'][0]['time-range']) && is_array($filters['comp-filters'][0]['time-range'])) {
```
Comment (nickvergessen) [inline apps/dav/lib/CalDAV/CalDavBackend.php:1368]:
```suggestion
			if ($componentType === 'VEVENT' && isset($filters['comp-filters'][0]['time-range']['start'], $filters['comp-filters'][0]['time-range']['end'])) {
```

Comment (simonspa) [reply apps/dav/lib/CalDAV/CalDavBackend.php:1368]: Only one is already a valid time range, see https://tools.ietf.org/html/rfc4791#section-9.9 so checking for both will break things.

Comment (nickvergessen) [reply apps/dav/lib/CalDAV/CalDavBackend.php:1368]: So this requires both keys, but the code below would also work with just 1 of those values, so maybe the is_array is good enough

**Review by kesselb — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]
