### PR TITLE
fix: added a label element to the NcSelect in update settings

### LINKED ISSUE #43088: [BITV]: Select has no connected label
On `/settings/admin/overview`:

Screenshot from 2024-01-24 17-43-53

### PR DESCRIPTION
**Pull request by emoral435**
* Resolves: #43088

## Summary
@JuliaKirschenheuter (all credit to her) found that in `index.php/settings/admin/overview`, there is a NcSelect without a corresponding label. This fixes that, No visual change, gave the label input the corresponding styles that would accompany the change from h4 element 👍

## TODO

- [X] Added a label to correspond with out input element, as well as matching their ID's
## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [X] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [X] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/updatenotification/src/components/UpdateNotification.vue [hunk 1]
```diff
@@ -131,8 +131,9 @@
 			<em v-html="noteDelayedStableString" />
 		</p>
 
-		<h4>{{ t('updatenotification', 'Notify members of the following groups about available updates:') }}</h4>
+		<label :for="selectLabel">{{ t('updatenotification', 'Notify members of the following groups about available updates:') }}</label>
 		<NcSelect v-model="notifyGroups"
+			:inputId="selectLabel"
```
Comment (ShGKme) [inline apps/updatenotification/src/components/UpdateNotification.vue:136]:
```suggestion
			:input-id="selectLabel"
```

File: apps/updatenotification/src/components/UpdateNotification.vue [hunk 2]
```diff
@@ -221,6 +222,7 @@ export default {
 			hideAvailableUpdates: true,
 			openedWhatsNew: false,
 			openedUpdateChannelMenu: false,
+			selectLabel: 'select-input-label-update-settings',
```
Comment (ShGKme) [inline apps/updatenotification/src/components/UpdateNotification.vue:225]: To not call it a `label`, because it is an `id` of `input`, not of the `label` or a label itself.

```suggestion
			selectId: 'notify-members-settings-select-input',
```

Comment (ShGKme) [reply apps/updatenotification/src/components/UpdateNotification.vue:225]: But I'd set it directly in the template. It is used only on 2 close lines in the template, not generated, not a part of component data (doesn't define reactive state of the component).

**Review by ShGKme — APPROVED** [review]
Some nitpicks

**Comment by ShGKme** [comment]
> No visual change, gave the label input the corresponding styles that would accompany the change from h4 element 👍

I think we can make it plain text. It looks inconsistent now, not sure it was needed to be h4 with h4 styles. cc @szaimen

File: apps/updatenotification/src/components/UpdateNotification.vue [hunk 3]
```diff
@@ -131,8 +131,9 @@
 			<em v-html="noteDelayedStableString" />
 		</p>
 
-		<h4>{{ t('updatenotification', 'Notify members of the following groups about available updates:') }}</h4>
+		<label :for="selectLabel">{{ t('updatenotification', 'Notify members of the following groups about available updates:') }}</label>
```
[the remark this answers is not in the document]
Comment (ShGKme) [reply apps/updatenotification/src/components/UpdateNotification.vue:134]: Agree, but probably the width should be adjusted because the label is long here.

**Comment by emoral435** [comment]
@Pytal Fixed! And styling should be the same - had to add high order specifiers with ID's and whatnot because Vue's default styling on their Select component was beating out most things I tried. This kept it pretty consistent:

firefox_3QXFPCor22

File: apps/updatenotification/src/components/UpdateNotification.vue [hunk 4]
```diff
@@ -131,8 +131,10 @@
 			<em v-html="noteDelayedStableString" />
 		</p>
 
-		<h4>{{ t('updatenotification', 'Notify members of the following groups about available updates:') }}</h4>
 		<NcSelect v-model="notifyGroups"
+			id="notify-members-settings-select-wrapper"
+			:input-label="t('updatenotification', 'Notify members of the following groups about available updates:')"
+			input-id="notify-members-settings-select-input"
```
Comment (Pytal) [inline apps/updatenotification/src/components/UpdateNotification.vue:137]:
```suggestion
```
Not needed anymore

**Comment by Pytal** [comment]
I'd say we should to drop the custom select__label styles and set `width: fit-content` on the wrapper + `min-width: 100%` on the dropdown toggle to have the select and label be the same width

@nextcloud/designers for design input

**Comment by szaimen** [comment]
> Agreed, IMO I think that having the label be 900px wide but then having the select be way smaller is a bit weird. Will push this then try to see what the designers say. Here is how it looks like, for the @nextcloud/designers :
> 
> firefox_dTCLp67UjB [ firefox_dTCLp67UjB ](https://private-user-images.githubusercontent.com/110193237/300040605-b286bf7c-131f-49e1-a64e-a7b2b59b91d0.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyODc3OTcsIm5iZiI6MTcwNjI4NzQ5NywicGF0aCI6Ii8xMTAxOTMyMzcvMzAwMDQwNjA1LWIyODZiZjdjLTEzMWYtNDllMS1hNjRlLWE3YjJiNTliOTFkMC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQxNjQ0NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzgyY2Q5NTY0NjYyNjM5YzdlMjAxNzc5OGNjZDE4OGM0MDQyODYyNjkxNzU1Zjg5YTIzZmE3ZmU3NGFmNjdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YNfdVtvB4kmtMHjpocNPY3Y5OeWl5ORddfxnLXs_O1c) [ ](https://private-user-images.githubusercontent.com/110193237/300040605-b286bf7c-131f-49e1-a64e-a7b2b59b91d0.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyODc3OTcsIm5iZiI6MTcwNjI4NzQ5NywicGF0aCI6Ii8xMTAxOTMyMzcvMzAwMDQwNjA1LWIyODZiZjdjLTEzMWYtNDllMS1hNjRlLWE3YjJiNTliOTFkMC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQxNjQ0NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzgyY2Q5NTY0NjYyNjM5YzdlMjAxNzc5OGNjZDE4OGM0MDQyODYyNjkxNzU1Zjg5YTIzZmE3ZmU3NGFmNjdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YNfdVtvB4kmtMHjpocNPY3Y5OeWl5ORddfxnLXs_O1c)

Honestly from design perspective I'd say this detail doesnt really matter as there are many other things on this page that don't look visually perfect 😅🙈

**Review by Pytal — APPROVED** [review]

**Review by ShGKme — APPROVED** [review]

**Review by susnux — APPROVED** [review]
