### PR TITLE
Auto set password for new email shares

### LINKED ISSUE #40493: [Bug]: After upgrade 27.0.x->27.1.0 public-type shares (web link) with self-generated password don't work
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi all,
I just upgraded to version 27.1.0 from the previous last version of 27.0.x and a problem came up (upgrade all ok).
When I generate a public share (web link) having set up forced password usage a random password is (correctly) generated.
Process that has always worked correctly on version 27.0.x.
However, the automatic password appears to have expired a few seconds ago.
If I set a password by typing it in, it works correctly.

PLEASE NOTE: 

the problem occurs ONLY on links with automatically generated password on version 27.1.0.
If the link was previously generated (27.0.x or 26.0.x) there is no problem.
The same behavior has been verified on two different servers.

### Steps to reproduce

1.I create a public share
2.An automatic password is assigned (because it is forced)
3.Sharing appears to have expired a few seconds ago

If I set a password manually (overwriting the automatic one) it works correctly.

### Expected behavior

That the link is working properly

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by nfebe**
Suggest auto generated password for new public share (mail share).

Resolves : https://github.com/nextcloud/server/issues/40493

### CODE REVIEW

**Review by sorbaugh — APPROVED** [review]

**Review by artonge — APPROVED** [review]

**Comment by Fenn-CS** [comment]
Sorry for the review spam if you get here... Don't know what happened :)

File: apps/files_sharing/src/views/SharingDetailsTab.vue [hunk 1]
```diff
@@ -680,11 +680,17 @@ export default {
...
+		async initializeAttributes() {
+			let hasAdvancedAttributes = false
 
-			if (this.isNewShare) return
+			if (this.isNewShare) {
+				if (this.isPasswordEnforced && this.isPublicShare) {
+					this.share.newPassword = await GeneratePassword()
+					this.advancedSectionAccordionExpanded = true
+				}
+				return
```
Comment (JuliaKirschenheuter) [inline apps/files_sharing/src/views/SharingDetailsTab.vue:691]: why do we need this `return`?

**Review by JuliaKirschenheuter — COMMENTED** [review]
Thanks for resolving this issue!
Could you please post screenshots "before" and "after"?

File: apps/files_sharing/src/views/SharingDetailsTab.vue (hunk 1 above)
Comment (Fenn-CS) [reply apps/files_sharing/src/views/SharingDetailsTab.vue:691]: Do avoid doing 4 other checks that are only needed for existing shares.

Comment (skjnldsv) [reply apps/files_sharing/src/views/SharingDetailsTab.vue:691]: it was there before :)

**Review by skjnldsv — APPROVED** [review]

**Review by JuliaKirschenheuter — APPROVED** [review]

**Review by susnux — APPROVED** [review]
