### PR TITLE
fix(share): assume download enabled on federated share

### LINKED ISSUE #52060: [Bug]: Federated sharing and re-sharing no longer works
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I have two Nextcloud instances.
In Cloud 1 (shared by the admin user), the "Public" folder is shared via federation with Cloud 2 (shared with the admin user).
In Cloud 2, this folder is shared with a "Partner" group provided via LDAP. The problem is that sharing in Cloud 2 automatically removes the "Allow download" checkbox. This means that members of the "Partner" group can see the files, but cannot open or download them.
The admin user in Cloud 2 can download, open, and share them.

### Steps to reproduce

1. Install two Nextcloud instances version 31.0.2
2. Create a folder called "test" in instance 1 and share it with instance 2 (with full permissions).
3. Create a group called "group1" in instance 2.
4. In instance 2, share this folder called "test" with the "group1" in instance 2
5. Users in the "group1" group cannot open or download the files.

### Expected behavior

The users of group1 must be able to open and download the files.

### Nextcloud Server version

31

### Operating system

Other

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 31 to 32)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [x] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ArtificialOwl**
fix #52060

The logic behind this condition is that if the file originate from a remote instance (federated share), then we can assume that the file is set as downloadable. We only know that for sure when trying to access the remote document.

Meaning that if you reshare it, you can assume that the document is downloadable and enable the checkbox on the share interface. Then the $hideDownload kicks in and disable the download to the final recipient, in case download permission is not kept on the reshare

### CODE REVIEW

File: apps/files_sharing/lib/Controller/ShareAPIController.php [hunk 1]
```diff
@@ -2118,6 +2118,8 @@ private function checkInheritedAttributes(IShare $share): void {
 				$hideDownload = $hideDownload && $originalShare->getHideDownload();
 				// allow download if already allowed by previous share or when the current share allows downloading
 				$canDownload = $canDownload || $inheritedAttributes === null || $inheritedAttributes->getAttribute('permissions', 'download') !== false;
+			} elseif ($node->getStorage()->instanceOfStorage(Storage::class)) {
+				$canDownload = true; // in case of federation storage, we can expect the download to be activated by default
```
Comment (provokateurin) [inline apps/files_sharing/lib/Controller/ShareAPIController.php:2122]: And what happens if it is not enabled?

Comment (ArtificialOwl) [reply apps/files_sharing/lib/Controller/ShareAPIController.php:2122]: Then, there is no share.
The idea behind this condition is that if the file originate from a remote instance (federated share), then we can assume that the file is set as downloadable. We only know that for sure when trying to access the remote document.

Meaning that if you reshare it, you can assume that the document is downloadable and enable the checkbox on the share interface. Then the `$hideDownload` kicks in and disable the download to the final recipient, in case download permission is not kept on the reshare

Comment (ArtificialOwl) [reply apps/files_sharing/lib/Controller/ShareAPIController.php:2122]: _(posted the explanation to the original message)_

**Review by provokateurin — APPROVED** [review]
:woman_shrugging:

**Review by yemkareems — APPROVED** [review]
