### PR TITLE
fix(systemtags): emit assign and unassign bulk tagging events

### LINKED ISSUE #51849: [bug] using bulk action for tagging does not trigger workflows
> But using "Manage tags" seems not to be the same as using the details bar. E.g. workflows which shall betriggered by tagging are not executed in case of "Manage tags" (probably some emit call is missing or broken). I can't find the issue report on the first view but saw something about it here or at help.nextcloud.com.  

 _Originally posted by @XueSheng-GIT in [#51814](https://github.com/nextcloud/server/issues/51814#issuecomment-2768940219)_

---

Details by @D592VN5 
### Bug description

I assign a tag (tag is of public type) to a file. From the UI it looks like tag is properly assigned (tag appears on the file row and also under Tags filter page - index.php/apps/files/tags).

However, the event/activity of tag assignment does NOT appear in the activity app (index.php/apps/activity/all).

I double checked this with different tags and with different users.

In raw mysql table called 'oc_activity' there is also no such activity.

Log, even under debug level, does not mention anything about problems with tag assignment.

Nextcloud 31.02
Collaborative tags 1.21.1
No upgrade history, fresh install.
All the installed apps are strictly from the Store, verified/tested ones only.

The weird thing is that IF 'Files automated tagging' app is used for automatic tagging of files (like new files), then this event (triggered by the app) does appear in the activity app.

The problem with this is that I wanted to create a flow to generate PDFs based on tag assignment. It is not possible to do this with this bug, since NextCloud does not know that the tag has been assigned.

Here is a screenshot of how this event looks like in the Activities app when 'Files automated tagging' app tags a file itself.

Image

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/server/issues/51849

### CODE REVIEW

File: lib/private/SystemTag/SystemTagObjectMapper.php [hunk 1]
```diff
@@ -332,6 +335,16 @@ public function setObjectIdsForTag(string $tagId, string $objectType, array $obj
 				[(int)$tagId]
 			));
 		}
+
+		// Dispatch unassign events for removed object ids
+		foreach ($removedObjectIds as $objectId) {
+			$this->dispatcher->dispatch(MapperEvent::EVENT_UNASSIGN, new MapperEvent(
```
Comment (susnux) [inline lib/private/SystemTag/SystemTagObjectMapper.php:341]: we do not have typed events for this? :eyes: 
Something we should fix rather sooner than later before we have to drop the untyped dispatch due to symphony update.

**Review by susnux — APPROVED** [review]

**Review by artonge — APPROVED** [review]
