### PR TITLE
Fix share expiration date not shown

### LINKED ISSUE #20520: Share expiration date not shown
### Steps to reproduce
1. Share a file (doesn't matter if link, internal, group or email)
2. set an expiration date by date picker

### Expected behaviour
- Expiration date is shown in date field
- Expiration date has been written to the database (oc_share.expiration)

### Actual behaviour
Date has been written to the DB, but doesn't appear on the UI

### Server configuration

NC 19.0.0 Beta4

### PR DESCRIPTION
**Pull request by gary-kim**
Fixes #20520 

~~Needs to be built with nextcloud/nextcloud-vue#1029~~ No longer necessary.

Signed-off-by: Gary Kim <gary@garykim.dev>

### CODE REVIEW

File: apps/files_sharing/src/mixins/SharesMixin.js [hunk 1]
```diff
@@ -56,6 +56,9 @@ export default {
 			saving: false,
 			open: false,
 
+			// processed data
+			expireDateObject: new Date(this.share?.expireDate),
```
Comment (gary-kim) [inline apps/files_sharing/src/mixins/SharesMixin.js:60]: I wanted to make this a computed property but I'm having problems with reactivity. Changes in `share.expireDate` won't update the computed property.

Comment (skjnldsv) [reply apps/files_sharing/src/mixins/SharesMixin.js:60]: So doing this is very risky, this is where you risk loosing track of the original data.0
You can use a computed get/set https://vuejs.org/v2/guide/computed.html#Computed-Setter

Comment (gary-kim) [reply apps/files_sharing/src/mixins/SharesMixin.js:60]: That's how I originally had it and how I would prefer it but it won't update when changes are made to `this.share.expireDate`. I'm really sure why the reactivity doesn't work with it.

Comment (skjnldsv) [reply apps/files_sharing/src/mixins/SharesMixin.js:60]: What about changing the expireDate key then?
https://github.com/nextcloud/server/blob/510a29f871ded9c84ca9d24dea4c9623d1c5ae73/apps/files_sharing/src/models/Share.js#L208

Comment (skjnldsv) [reply apps/files_sharing/src/mixins/SharesMixin.js:60]: Or else, the vue datepicker have an option to define the value type 
https://github.com/mengxiong10/vue2-datepicker#value-type

Comment (skjnldsv) [reply apps/files_sharing/src/mixins/SharesMixin.js:60]: Actually I think using the value-type is the way to go, this is what it was made for :)

Comment (skjnldsv) [reply apps/files_sharing/src/mixins/SharesMixin.js:60]: also https://github.com/mengxiong10/vue2-datepicker#token

Comment (gary-kim) [reply apps/files_sharing/src/mixins/SharesMixin.js]: That works! Thank you @skjnldsv 
Now I feel a little dumb that I didn't think of that earlier :laughing:

Comment (skjnldsv) [reply apps/files_sharing/src/mixins/SharesMixin.js]: Well, I discovered this :p
I think this is because it was automated before and with the version 3.0 it changed :thinking:

**Review by skjnldsv — APPROVED** [review]
Code looks good :D

**Comment by gary-kim** [comment]
There's also a seperate issue where the `not-before` and `not-after` don't do anything in `vue2-datepicker`. It wants a `disabled-date` function instead. Should we implement that in `@nextcloud/vue` or here?

**Comment by skjnldsv** [comment]
> There's also a seperate issue where the `not-before` and `not-after` don't do anything in `vue2-datepicker`. It wants a `disabled-date` function instead. Should we implement that in `@nextcloud/vue` so other apps can reuse it or here?

I guess we should adapt this here :)
We shouldn't be more complicated than the original library. W''re just wrapping our styling mostly :)

So let's upgrade to disabled-date here ?

**Comment by ChristophWurst** [comment]
> So let's upgrade to disabled-date here ?

@gary-kim @skjnldsv is this ok to merge or are there any missing changes?

**Comment by gary-kim** [comment]
> > So let's upgrade to disabled-date here ?
> 
> @gary-kim @skjnldsv is this ok to merge or are there any missing changes?

I'd say that's a separate issue that's better addressed in another PR.

**Review by ChristophWurst — APPROVED** [review]

**Comment by skjnldsv** [comment]
Please rebase :)

**Comment by gary-kim** [comment]
> Please rebase :)

Done!

**Comment by skjnldsv** [comment]
Wait, this actually broke things :see_no_evil: 
`value-type="format"` means they'll use the data provided by "format".
But we don't provide any format :shrug:

**Comment by skjnldsv** [comment]
AH it's fine, format has default `'YYYY-MM-DD'`
Let me see what broke then, might not be this pr
