### PR TITLE
fix(settings): define a 'heartbeat' route, so SecurityHeaders can handle redirected root

### LINKED ISSUE #44234: [Bug]: Missing headers are reported when using the SSO application
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi,

I'm running NC 29.0.0 beta 3.

I am getting this error: 

```
Some headers are not set correctly on your instance - The `X-Robots-Tag` HTTP header is not set to `noindex,nofollow`. This is a potential security or privacy risk, as it is recommended to adjust this setting accordingly. - The `X-Permitted-Cross-Domain-Policies` HTTP header is not set to `none`. This is a potential security or privacy risk, as it is recommended to adjust this setting accordingly. 
```

The thing is that the headers are correctly set.

I am using the `user_saml` (SSO) application, and when I disable it, the error is gone. I realize that it's testing the root, because of the redirect to IdP, it's failing to see the headers that aren't set there.

Maybe the test should exclude redirects to the idp? 

### Steps to reproduce

1. Have Saml configured to an external idp
2. Missing headers error will show
3. Disable sso
4. No complaints about headers

### Expected behavior

It should only test for missing headers on its own domain, not on the idp.

### Installation method

Community Docker image

### Nextcloud Server version

master

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by smokris**
## Problem
On sites where the root (`/`) path is redirected (e.g. when using the [Social login plugin](https://github.com/zorn-v/nextcloud-social-login)), the Admin Overview page incorrectly shows errors about security headers not being set:

> Some headers are not set correctly on your instance - The `X-Robots-Tag` HTTP header is not set to `noindex,nofollow`. This is a potential security or privacy risk, as it is recommended to adjust this setting accordingly. - The `X-Permitted-Cross-Domain-Policies` HTTP header is not set to `none`. This is a potential security or privacy risk, as it is recommended to adjust this setting accordingly. For more details see the documentation ↗.

## Analysis
In `lib/base.php`, the request path `/heartbeat` is [handled specially by returning early](https://github.com/nextcloud/server/blob/c60de5bea094ff1b1791bb6bc630ab20df39553d/lib/base.php#L1003), but no formal route is defined for it.

`OCA\Settings\SetupChecks\SecurityHeaders` [calls `URLGenerator::linkToRoute('heartbeat')`](https://github.com/nextcloud/server/blob/c60de5bea094ff1b1791bb6bc630ab20df39553d/apps/settings/lib/SetupChecks/SecurityHeaders.php#L60), but the generated URL is emptystring, since there's no route defined by that name.

It then performs a request on the root (`/`) path (instead of the expected `/heartbeat` path).  On sites where the root path redirects, `SecurityHeaders` then incorrectly analyzes the headers _of the redirect_, instead of analyzing the headers _of the Nextcloud heartbeat page_.

## Proposed solution
Define a `heartbeat` route, so that `URLGenerator::linkToRoute('heartbeat')` returns `/heartbeat` as the `SecurityHeaders` test seems to expect.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [~] Screenshots before/after for front-end changes — N/A
- [~] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required — N/A
- [~] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes) — N/A

### CODE REVIEW

File: core/routes.php [hunk 1]
```diff
@@ -40,3 +40,5 @@
 // Routing
 $this->create('core_ajax_update', '/core/ajax/update.php')
 	->actionInclude('core/ajax/update.php');
+
+$this->create('heartbeat', '/heartbeat')->get();
```
Comment (provokateurin) [inline core/routes.php:44]: So what happens when the route is called? Which code path handles it?

File: tests/lib/Route/RouterTest.php [hunk 2]
```diff
@@ -40,7 +40,10 @@
  * @package Test\Route
  */
 class RouterTest extends TestCase {
-	public function testGenerateConsecutively(): void {
+	/** @var Router */
+	private $router;
```
Comment (provokateurin) [inline tests/lib/Route/RouterTest.php:44]:
```suggestion
	private Router $router;
```

**Review by provokateurin — CHANGES_REQUESTED** [review]
It would be good to add a test to the setup checks that validates that the check now works.

**Comment by provokateurin** [comment]
TBH I've never seen this warning on my local dev instance, can you tell me how to reproduce it?

File: core/routes.php (hunk 1 above)
Comment (come-nc) [reply core/routes.php:44]: https://github.com/nextcloud/server/blob/master/lib/base.php#L1003

**Comment by come-nc** [comment]
I cannot tell if adding a route like this is the right fix for this. The heartbeat short circuits a lot of things so it cannot be put in a controller.
It is still a supported URL endpoint so maybe it’s fine to add it like that?

**Comment by cdammanintopix** [comment]
Hello,
Thank you for this fix.
Without it, I had the following issue in my logs:
```
{
  "reqId": "xxxxxxxxxx",
  "level": 1,
  "time": "2024-05-22T08:09:18+00:00",
  "remoteAddr": "xxxxxxxxxx",
  "user": "xxxxxxxxxx",
  "app": "no app in context",
  "method": "GET",
  "url": "/settings/ajax/checksetup",
  "message": "Unable to generate a URL for the named route \"heartbeat\" as such route does not exist.",
  "userAgent": "xxxxxxxxxx",
  "version": "29.0.0.19",
  "exception": {
    "Exception": "Symfony\\Component\\Routing\\Exception\\RouteNotFoundException",
    "Message": "Unable to generate a URL for the named route \"heartbeat\" as such route does not exist.",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/html/lib/private/Route/Router.php",
        "line": 410,
        "function": "generate",
        "class": "Symfony\\Component\\Routing\\Generator\\UrlGenerator",
        "type": "->",
        "args": [
          "heartbeat",
          [],
          1
        ]
      },
      {
        "file": "/var/www/html/lib/private/Route/CachingRouter.php",
        "line": 65,
        "function": "generate",
        "class": "OC\\Route\\Router",
        "type": "->",
        "args": [
          "heartbeat",
          [],
          false
        ]
      },
      {
        "file": "/var/www/html/lib/private/URLGenerator.php",
        "line": 103,
        "function": "generate",
        "class": "OC\\Route\\CachingRouter",
        "type": "->",
        "args": [
          "heartbeat",
          []
        ]
      },
      {
        "file": "/var/www/html/apps/settings/lib/SetupChecks/SecurityHeaders.php",
        "line": 60,
        "function": "linkToRoute",
        "class": "OC\\URLGenerator",
        "type": "->",
        "args": [
          "heartbeat"
        ]
      },
      {
        "file": "/var/www/html/lib/private/SetupCheck/SetupCheckManager.php",
        "line": 51,
        "function": "run",
        "class": "OCA\\Settings\\SetupChecks\\SecurityHeaders",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/html/apps/settings/lib/Controller/CheckSetupController.php",
        "line": 179,
        "function": "runAll",
        "class": "OC\\SetupCheck\\SetupCheckManager",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 232,
        "function": "check",
        "class": "OCA\\Settings\\Controller\\CheckSetupController",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 138,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          [
            "OCA\\Settings\\Controller\\CheckSetupController"
          ],
          "check"
        ]
      },
      {
        "file": "/var/www/html/lib/private/AppFramework/App.php",
        "line": 184,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          [
            "OCA\\Settings\\Controller\\CheckSetupController"
          ],
          "check"
        ]
      },
      {
        "file": "/var/www/html/lib/private/Route/Router.php",
        "line": 338,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::",
        "args": [
          "OCA\\Settings\\Controller\\CheckSetupController",
          "check",
          [
            "OC\\AppFramework\\DependencyInjection\\DIContainer"
          ],
          [
            "settings.checksetup.check"
          ]
        ]
      },
      {
        "file": "/var/www/html/lib/base.php",
        "line": 1050,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->",
        "args": [
          "/settings/ajax/checksetup"
        ]
      },
      {
        "file": "/var/www/html/index.php",
        "line": 49,
        "function": "handleRequest",
        "class": "OC",
        "type": "::",
        "args": []
      }
    ],
    "File": "/var/www/html/3rdparty/symfony/routing/Generator/UrlGenerator.php",
    "Line": 144,
    "message": "Unable to generate a URL for the named route \"heartbeat\" as such route does not exist.",
    "exception": [],
    "CustomMessage": "Unable to generate a URL for the named route \"heartbeat\" as such route does not exist."
  },
  "id": "xxxxxxxxxx"
}
```
Applying this change fixed the issue.

**Comment by joshtrichards** [comment]
Added a link to issue #44234 since this is a potential fix for that.

**Review by come-nc — APPROVED** [review]

**Review by provokateurin — APPROVED** [review]

**Comment by andreas-bulling** [comment]
I've upgraded to 29.0.3 and I still see the error in the log

**Comment by joshtrichards** [comment]
That's because it's scheduled for the upcoming maintenance release via #45956
