### PR TITLE
Array access on int will fail on php7.4

### LINKED ISSUE #18689: NC18rc1 - php7.4 report
debian 10
php7.4-fpm
nginx 1.17.7

[PHP] Error: Trying to access array offset on value of type int at /var/www/nextcloud/lib/private/AppFramework/OCS/BaseResponse.php#129

GET /ocs/v2.php/cloud/capabilities?
from x.x.x.x by user at 2020-01-06T09:15:14+01:00

### PR DESCRIPTION
**Pull request by kesselb**
Fix #18689 

Probably possible to move writeAttribute into the else block of is_numeric. No idea how to trigger this kind of failure in the wild hence those weird test ;)

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]

File: lib/private/AppFramework/OCS/BaseResponse.php [hunk 1]
```diff
@@ -126,7 +126,7 @@ protected function renderResult(array $meta): string {
 	 */
 	protected function toXML(array $array, \XMLWriter $writer) {
 		foreach ($array as $k => $v) {
-			if ($k[0] === '@') {
+			if (strpos($k, '@') === 0) {
```
Comment (ChristophWurst) [inline lib/private/AppFramework/OCS/BaseResponse.php]: but if `$k` is a string, it will also have an incorrect type for [`strpos`](https://www.php.net/manual/en/function.strpos.php), right?

Comment (kesselb) [reply lib/private/AppFramework/OCS/BaseResponse.php]: You mean: If $k would be an integer?

Comment (ChristophWurst) [reply lib/private/AppFramework/OCS/BaseResponse.php]: yes :speak_no_evil:

Comment (kesselb) [reply lib/private/AppFramework/OCS/BaseResponse.php]: Think so. It seems that those magic type conversions are not applied for array access hence the warning. I'm fine with making that more strict but I have no idea what those code should do in general :)

Comment (ChristophWurst) [reply lib/private/AppFramework/OCS/BaseResponse.php]: Me neither. I guess the best we can do is something like `if (is_string($k) && isset($k[0]) && $k[0] === '@')`

File: lib/private/AppFramework/OCS/BaseResponse.php [hunk 2]
```diff
@@ -126,7 +126,7 @@ protected function renderResult(array $meta): string {
 	 */
 	protected function toXML(array $array, \XMLWriter $writer) {
 		foreach ($array as $k => $v) {
-			if ($k[0] === '@') {
+			if (\is_string($k) && strpos($k, '@') === 0) {
```
Comment (ChristophWurst) [inline lib/private/AppFramework/OCS/BaseResponse.php]: Works, but `strpos` has the disadvantage that it will search for the char in the full string. Depending on the input this might perform worse than checking a single position.

Comment (kesselb) [reply lib/private/AppFramework/OCS/BaseResponse.php]: Good point. Did some research why Php Inspections recommends to not use strpos: https://github.com/kalessil/phpinspectionsea/issues/1313

**Review by nickvergessen — APPROVED** [review]
