### PR TITLE
theming: handle not being in the serverroot

### LINKED ISSUE #8462: Theming: logo and background images don't work with apps outside server root
### Steps to reproduce
1. Move `/var/www/nextcloud/apps` to `/var/www/apps`.
2. Update config.php to include:
```
'apps_paths' =>  
  array (
    0 =>  
    array (
      'path' => '/var/www/apps',
      'url' => '/apps',
      'writable' => true,
    ),  
  ), 
```
3. Set alias in httpd.conf:
```
Alias /apps /var/www/apps
```

### Expected behaviour
Theming should work as normal.

### Actual behaviour
Spinners just spin forever when setting the logo/background image, preview doesn't display, and settings don't actually seem to take hold (log out and images aren't set).

### Server configuration

**Operating system**:

Ubuntu 16.04

**Web server:**

Apache 2.4

**Database:**

sqlite

**PHP version:**

7.1

**Nextcloud version:** (see Nextcloud admin page)

12.0.5 (or master)

**Updated from an older Nextcloud/ownCloud or fresh install:**

Fresh

**Where did you install Nextcloud from:**

Source

### PR DESCRIPTION
**Pull request by kyrofa**
Currently, the theming app assumes it's in the serverroot. However, with Nextcloud's flexibility regarding configurable app paths, this is not a safe assumption to make. If it happens to be an incorrect assumption, the theming app fails to work.

Instead of relying on the serverroot, this PR fixes #8462 by simply using the app path from the AppManager and utilizing relative paths for assets from there. Note that, in order to make this testable, the ability to inject an `IAppManager` to the `ThemingController` was added.

As this has been broken since v12, a backport to both stable13 and stable12 would be great (happy to do the legwork if given the okay).

### CODE REVIEW

File: apps/theming/lib/Controller/ThemingController.php [hunk 1]
```diff
@@ -118,6 +123,12 @@ public function __construct(
 		$this->appData = $appData;
 		$this->scssCacher = $scssCacher;
 		$this->urlGenerator = $urlGenerator;
+
+		if (!is_null($appManager)) {
```
Comment (juliushaertl) [inline apps/theming/lib/Controller/ThemingController.php]: There should be no need for such a check. The AppManager will be injected automatically.

File: apps/theming/lib/Controller/ThemingController.php [hunk 2]
```diff
@@ -409,12 +420,13 @@ public function getLoginBackground() {
 	 * @return FileDisplayResponse|NotFoundResponse
 	 */
 	public function getStylesheet() {
-		$appPath = substr(\OC::$server->getAppManager()->getAppPath('theming'), strlen(\OC::$SERVERROOT) + 1);
+		$appPath = $this->appManager->getAppPath('theming');
```
Comment (juliushaertl) [inline apps/theming/lib/Controller/ThemingController.php]: :see_no_evil: :+1:

**Review by juliusknorr — CHANGES_REQUESTED** [review]
Looks good besides one minor comment.

File: apps/theming/lib/Controller/ThemingController.php (hunk 1 above)
Comment (kyrofa) [reply apps/theming/lib/Controller/ThemingController.php]: Well, only in [this test case](https://github.com/nextcloud/server/pull/8463/files#diff-60ef3451b737acfb4dc0ecc3f6645921R845), right? If it's not injected (like the other test cases, or in typical usage) it should default back to the server's app manager. Perhaps I misunderstand?

**Comment by kyrofa** [comment]
(Note that the test failure here seems unrelated.)

**Comment by kyrofa** [comment]
I'd very much like to backport this for 12.0.6 and 13.0.1!

File: apps/theming/lib/Controller/ThemingController.php (hunk 1 above)
Comment (juliushaertl) [reply apps/theming/lib/Controller/ThemingController.php]: The mock should just be added to the controller here: https://github.com/kyrofa/server/blob/a1f18241166f335b89a6cf3d002efd3d825fde19/apps/theming/tests/Controller/ThemingControllerTest.php#L109

Then of course the method need to be configured  to the other tests as well.

Comment (kyrofa) [reply apps/theming/lib/Controller/ThemingController.php]: Sure, I can do that, although we'll still need the null check for the real system. Is that okay, or would you prefer to see this parameter become non-optional and have all the callers modified to pass it in?

Comment (kyrofa) [reply apps/theming/lib/Controller/ThemingController.php]: Updated the tests to add the mock in setUp.

Comment (juliushaertl) [reply apps/theming/lib/Controller/ThemingController.php]: Ok, great. Then you can get rid of the is_null check since the appManager will be injected automatically, just like the other constructor arguments. So it will always be `\OC::$server->getAppManager()` except for the tests where we call the constructor ourselfs and it will be mocked then.

Comment (juliushaertl) [reply apps/theming/lib/Controller/ThemingController.php]: You can read more about the dependency injection here: https://docs.nextcloud.com/server/13/developer_manual/app/container.html#how-does-automatic-assembly-work

This is basically where the "magic" happens: :wink: 
https://github.com/nextcloud/server/blob/0eebff152a177dd59ed8773df26f1679f8a88e90/lib/private/AppFramework/Utility/SimpleContainer.php#L50

**Review by juliusknorr — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

File: apps/theming/lib/Controller/ThemingController.php (hunk 1 above)
Comment (kyrofa) [reply apps/theming/lib/Controller/ThemingController.php]: Ahhh and the puzzle pieces come together! Thank you for helping me understand this :) .

**Comment by kyrofa** [comment]
Thanks folks. Can I get a yea/nay on backporting to stable{12,13}? Happy to propose.

**Comment by kyrofa** [comment]
Backport PRs are up:

- #8549 for v12
- #8554 for v13
