### PR TITLE
Make sure root storage is valid before checking its size

### LINKED ISSUE #23579: Adding users creates php error
### Steps to reproduce
Try to create new user without setting a password

### Expected behaviour
User created without errors

### Actual behaviour
No users are shown, every refresh creates an error
Can't delete new created users

## Server configuration detail

**Operating system:** Linux 5.4.41-1-pve #1 SMP PVE 5.4.41-1 (Fri, 15 May 2020 15:06:08 +0200) x86_64

**Webserver:** nginx/1.18.0 (fpm-fcgi)

**Database:** mysql 5.7.28

**PHP version:** 

7.4.10
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, cgi-fcgi, pdlib, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, exif, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 19.0.4 - 19.0.4.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.12.1
 - admin_audit: 1.9.0
 - apporder: 0.11.0
 - bruteforcesettings: 2.0.1
 - camerarawpreviews: 0.7.8
 - cloud_federation_api: 1.2.0
 - dav: 1.15.0
 - documentserver_community: 0.1.8
 - external: 3.6.0
 - facerecognition: 0.6.3
 - federatedfilesharing: 1.9.0
 - federation: 1.9.0
 - files: 1.14.0
 - files_accesscontrol: 1.9.1
 - files_downloadactivity: 1.8.0
 - files_pdfviewer: 1.8.0
 - files_rightclick: 0.16.0
 - files_sharing: 1.11.0
 - files_trashbin: 1.9.0
 - files_versions: 1.12.0
 - files_videoplayer: 1.8.0
 - imageconverter: 1.2.1
 - issuetemplate: 0.7.0
 - logreader: 2.4.0
 - lookup_server_connector: 1.7.0
 - maps: 0.1.6
 - music: 0.17.0
 - notifications: 2.7.0
 - oauth2: 1.7.0
 - occweb: 0.0.7
 - onlyoffice: 6.0.2
 - password_policy: 1.9.1
 - photos: 1.1.0
 - previewgenerator: 2.3.0
 - privacy: 1.3.0
 - provisioning_api: 1.9.0
 - recommendations: 0.7.0
 - serverinfo: 1.9.0
 - settings: 1.1.0
 - support: 1.2.1
 - survey_client: 1.7.0
 - text: 3.0.1
 - theming: 1.10.0
 - twofactor_backupcodes: 1.8.0
 - updatenotification: 1.9.0
 - video_converter: 0.1.5
 - viewer: 1.3.0
 - workflowengine: 2.1.0
Disabled:
 - accessibility
 - calendar
 - comments
 - contactsinteraction
 - deck
 - encryption
 - files_external
 - firstrunwizard
 - forms
 - nextcloud_announcements
 - sharebymail
 - spreed
 - systemtags
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
       
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "19.0.4.2",
    "overwrite.cli.url": "https:\/\/****",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "updater.release.channel": "stable",
    "filelocking.enabled": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "dbindex": 0,
        "timeout": 1.5
    },
    "default_language": "de",
    "force_locale": "de_DE",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "app_install_overwrite": [
        "files_reader",
        "occweb",
        "files_external_gdrive"
    ],
    "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
    "enable_previews": true,
    "enabledPreviewProviders": [
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\OpenDocument",
        "OC\\Preview\\PDF",
        "OC\\Preview\\MSOffice2003",
        "OC\\Preview\\MSOfficeDoc",
        "OC\\Preview\\PDF",
        "OC\\Preview\\Image",
        "OC\\Preview\\Photoshop",
        "OC\\Preview\\TIFF",
        "OC\\Preview\\SVG",
        "OC\\Preview\\Font",
        "OC\\Preview\\MP3",
        "OC\\Preview\\Movie",
        "OC\\Preview\\MKV",
        "OC\\Preview\\MP4",
        "OC\\Preview\\AVI"
    ],
    "quota_include_external_storage": true,
    "theme": "",
    "loglevel": 2,
    "mail_smtpsecure": "tls",
    "data-fingerprint": "38cf46f187e9cbed0904ced4e800492d",
    "preview_max_x": "2048",
    "preview_max_y": "2048",
    "jpeg_quality": "60"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
Access.log:

194.140.113.137 - - [20/Oct/2020:07:43:30 +0000] "GET /apps/logreader/get?offset=0&count=50&levels=11111 HTTP/2.0" 200 183370 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:43:32 +0000] "POST /contactsmenu/contacts HTTP/2.0" 200 380 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - Niclas [20/Oct/2020:07:43:32 +0000] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - Niclas [20/Oct/2020:07:43:32 +0000] "PROPFIND /remote.php/dav/files/Niclas/ HTTP/1.1" 207 400 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - - [20/Oct/2020:07:43:36 +0000] "GET /apps/logreader/poll?lastReqId=M72PaLr0QoSTNcsR2f17 HTTP/2.0" 499 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:43:36 +0000] "GET /settings/users HTTP/2.0" 200 31141 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:43:36 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 200 74 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:43:36 +0000] "GET /apps/apporder/getOrder HTTP/2.0" 200 203 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:43:36 +0000] "GET /ocs/v2.php/cloud/users/details?offset=0&limit=25&search= HTTP/2.0" 404 286 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:43:41 +0000] "GET /ocs/v2.php/cloud/groups/admin/users/details?offset=0&limit=25&search= HTTP/2.0" 200 619 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:43:41 +0000] "GET /ocs/v2.php/cloud/groups/admin/users/details?offset=25&limit=25&search= HTTP/2.0" 200 84 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:43:43 +0000] "GET /ocs/v2.php/cloud/users/details?offset=0&limit=25&search= HTTP/2.0" 404 286 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:43:45 +0000] "GET /ocs/v2.php/cloud/groups/Gast/users/details?offset=0&limit=25&search= HTTP/2.0" 404 286 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:43:46 +0000] "GET /ocs/v2.php/cloud/users/details?offset=0&limit=25&search= HTTP/2.0" 404 286 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - Niclas [20/Oct/2020:07:43:50 +0000] "PROPFIND /remote.php/dav/files/Niclas/ HTTP/1.1" 207 380 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - - [20/Oct/2020:07:43:56 +0000] "GET /settings/user HTTP/2.0" 200 45920 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:43:56 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 200 74 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:43:56 +0000] "GET /apps/apporder/getOrder HTTP/2.0" 200 203 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:43:58 +0000] "GET /settings/admin/logging HTTP/2.0" 200 31022 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:43:58 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 200 74 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:43:58 +0000] "GET /apps/apporder/getOrder HTTP/2.0" 200 203 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:43:58 +0000] "GET /apps/logreader/settings HTTP/2.0" 200 98 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:43:58 +0000] "GET /apps/logreader/get?offset=0&count=50&levels=11111 HTTP/2.0" 200 195484 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - Niclas [20/Oct/2020:07:44:04 +0000] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - Niclas [20/Oct/2020:07:44:04 +0000] "PROPFIND /remote.php/dav/files/Niclas/ HTTP/1.1" 207 400 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - - [20/Oct/2020:07:44:19 +0000] "GET /apps/logreader/poll?lastReqId=g1kMSjsQ3krHzHkcHO0a HTTP/2.0" 499 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:44:19 +0000] "GET /settings/admin/issuetemplate HTTP/2.0" 200 30740 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:44:19 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 200 74 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:44:19 +0000] "GET /apps/issuetemplate/components HTTP/2.0" 200 71365 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:44:19 +0000] "GET /apps/apporder/getOrder HTTP/2.0" 200 203 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - Niclas [20/Oct/2020:07:44:20 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications?format=json HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - Niclas [20/Oct/2020:07:44:20 +0000] "PROPFIND /remote.php/dav/files/Niclas/ HTTP/1.1" 207 380 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - - [20/Oct/2020:07:44:22 +0000] "GET /apps/issuetemplate/sections/server HTTP/2.0" 200 175 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:44:22 +0000] "GET /apps/issuetemplate/details/server/server-detail HTTP/2.0" 200 7353 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:44:22 +0000] "GET /apps/issuetemplate/details/server/client-detail HTTP/2.0" 200 524 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:44:22 +0000] "GET /apps/issuetemplate/details/server/log-detail HTTP/2.0" 200 680 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - Niclas [20/Oct/2020:07:44:36 +0000] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - Niclas [20/Oct/2020:07:44:36 +0000] "PROPFIND /remote.php/dav/files/Niclas/ HTTP/1.1" 207 400 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - - [20/Oct/2020:07:44:49 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - Niclas [20/Oct/2020:07:44:50 +0000] "PROPFIND /remote.php/dav/files/Niclas/ HTTP/1.1" 207 380 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - Niclas [20/Oct/2020:07:45:08 +0000] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - Niclas [20/Oct/2020:07:45:08 +0000] "PROPFIND /remote.php/dav/files/Niclas/ HTTP/1.1" 207 400 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - - [20/Oct/2020:07:45:19 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - Niclas [20/Oct/2020:07:45:20 +0000] "PROPFIND /remote.php/dav/files/Niclas/ HTTP/1.1" 207 380 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - Niclas [20/Oct/2020:07:45:40 +0000] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - Niclas [20/Oct/2020:07:45:40 +0000] "PROPFIND /remote.php/dav/files/Niclas/ HTTP/1.1" 207 400 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - - [20/Oct/2020:07:45:41 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:45:49 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - Niclas [20/Oct/2020:07:45:50 +0000] "PROPFIND /remote.php/dav/files/Niclas/ HTTP/1.1" 207 380 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - - [20/Oct/2020:07:46:07 +0000] "GET /apps/files/ HTTP/2.0" 200 51747 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:46:07 +0000] "GET /apps/maps/js/filetypes.js?v=8007bdb9-12 HTTP/2.0" 302 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:46:07 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 200 74 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:46:07 +0000] "GET /apps/files/ HTTP/2.0" 200 51747 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:46:07 +0000] "GET /apps/apporder/getOrder HTTP/2.0" 200 203 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:46:08 +0000] "GET /apps/onlyoffice/ajax/settings HTTP/2.0" 200 3276 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:46:08 +0000] "PROPFIND /remote.php/dav/files/Niclas/ HTTP/2.0" 207 15686 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:46:08 +0000] "GET /ocs/v2.php/core/whatsnew?format=json HTTP/2.0" 204 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:46:08 +0000] "GET /apps/recommendations/api/recommendations HTTP/2.0" 200 17 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:46:08 +0000] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/2.0" 200 240 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:46:10 +0000] "GET /settings/user HTTP/2.0" 200 45924 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:46:10 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 200 74 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:46:10 +0000] "GET /apps/apporder/getOrder HTTP/2.0" 200 203 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:46:12 +0000] "GET /settings/admin/logging HTTP/2.0" 200 31028 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - Niclas [20/Oct/2020:07:46:12 +0000] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - Niclas [20/Oct/2020:07:46:12 +0000] "PROPFIND /remote.php/dav/files/Niclas/ HTTP/1.1" 207 400 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - - [20/Oct/2020:07:46:12 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 200 74 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:46:12 +0000] "GET /apps/apporder/getOrder HTTP/2.0" 200 203 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:46:12 +0000] "GET /apps/logreader/settings HTTP/2.0" 200 98 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:46:12 +0000] "GET /apps/logreader/get?offset=0&count=50&levels=11111 HTTP/2.0" 200 194964 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - Niclas [20/Oct/2020:07:46:20 +0000] "PROPFIND /remote.php/dav/files/Niclas/ HTTP/1.1" 207 380 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - - [20/Oct/2020:07:46:22 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:46:32 +0000] "GET /apps/logreader/poll?lastReqId=SlGaUgDqDRJihjfYojeG HTTP/2.0" 200 2 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:46:42 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - Niclas [20/Oct/2020:07:46:44 +0000] "PROPFIND /remote.php/dav/files/Niclas/ HTTP/1.1" 207 400 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - Niclas [20/Oct/2020:07:46:44 +0000] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - Niclas [20/Oct/2020:07:46:50 +0000] "PROPFIND /remote.php/dav/files/Niclas/ HTTP/1.1" 207 380 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - - [20/Oct/2020:07:46:52 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:46:52 +0000] "GET /apps/logreader/poll?lastReqId=SlGaUgDqDRJihjfYojeG HTTP/2.0" 200 2 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:47:12 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:47:13 +0000] "GET /apps/logreader/poll?lastReqId=SlGaUgDqDRJihjfYojeG HTTP/2.0" 200 2 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - Niclas [20/Oct/2020:07:47:16 +0000] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - Niclas [20/Oct/2020:07:47:16 +0000] "PROPFIND /remote.php/dav/files/Niclas/ HTTP/1.1" 207 400 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - Niclas [20/Oct/2020:07:47:20 +0000] "PROPFIND /remote.php/dav/files/Niclas/ HTTP/1.1" 207 380 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - - [20/Oct/2020:07:47:22 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:47:30 +0000] "GET /csrftoken HTTP/2.0" 200 102 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:47:33 +0000] "GET /apps/logreader/poll?lastReqId=SlGaUgDqDRJihjfYojeG HTTP/2.0" 200 2 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:47:42 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - Niclas [20/Oct/2020:07:47:48 +0000] "PROPFIND /remote.php/dav/files/Niclas/ HTTP/1.1" 207 400 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - Niclas [20/Oct/2020:07:47:48 +0000] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - Niclas [20/Oct/2020:07:47:50 +0000] "PROPFIND /remote.php/dav/files/Niclas/ HTTP/1.1" 207 380 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - - [20/Oct/2020:07:47:52 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:47:53 +0000] "GET /apps/logreader/poll?lastReqId=SlGaUgDqDRJihjfYojeG HTTP/2.0" 200 2 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:48:13 +0000] "GET /apps/logreader/poll?lastReqId=SlGaUgDqDRJihjfYojeG HTTP/2.0" 200 2 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:48:14 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - Niclas [20/Oct/2020:07:48:20 +0000] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - Niclas [20/Oct/2020:07:48:20 +0000] "PROPFIND /remote.php/dav/files/Niclas/ HTTP/1.1" 207 400 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - Niclas [20/Oct/2020:07:48:20 +0000] "PROPFIND /remote.php/dav/files/Niclas/ HTTP/1.1" 207 380 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - - [20/Oct/2020:07:48:23 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:48:34 +0000] "GET /apps/logreader/poll?lastReqId=SlGaUgDqDRJihjfYojeG HTTP/2.0" 200 2 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - Niclas [20/Oct/2020:07:48:50 +0000] "PROPFIND /remote.php/dav/files/Niclas/ HTTP/1.1" 207 380 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - - [20/Oct/2020:07:48:50 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:48:51 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - Niclas [20/Oct/2020:07:48:52 +0000] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - Niclas [20/Oct/2020:07:48:52 +0000] "PROPFIND /remote.php/dav/files/Niclas/ HTTP/1.1" 207 400 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.2git (build 3559) (Nextcloud)"
194.140.113.137 - - [20/Oct/2020:07:48:53 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
194.140.113.137 - - [20/Oct/2020:07:48:54 +0000] "GET /apps/logreader/poll?lastReqId=SlGaUgDqDRJihjfYojeG HTTP/2.0" 200 2 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
```
</details>

<details><summary>Nextcloud log</summary>

```
Exception: Call to a member function getSize() on bool

{"reqId":"SlGaUgDqDRJihjfYojeG","level":3,"time":"2020-10-20T07:45:02+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":{"Exception":"Error","Message":"Call to a member function getSize() on bool","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Quota.php","line":100,"function":"getSize","class":"OC\\Files\\Storage\\Wrapper\\Quota","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Quota.php","line":216,"function":"free_space","class":"OC\\Files\\Storage\\Wrapper\\Quota","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":83,"function":"mkdir","class":"OC\\Files\\Storage\\Wrapper\\Quota","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Files/Filesystem.php","line":443,"function":"mkdir","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Files/Filesystem.php","line":376,"function":"initMountPoints","class":"OC\\Files\\Filesystem","type":"::"},{"file":"/var/www/html/nextcloud/lib/private/legacy/OC_Util.php","line":308,"function":"init","class":"OC\\Files\\Filesystem","type":"::"},{"file":"/var/www/html/nextcloud/lib/private/Files/Utils/Scanner.php","line":116,"function":"setupFS","class":"OC_Util","type":"::"},{"file":"/var/www/html/nextcloud/lib/private/Files/Utils/Scanner.php","line":155,"function":"getMounts","class":"OC\\Files\\Utils\\Scanner","type":"->"},{"file":"/var/www/html/nextcloud/apps/files/lib/BackgroundJob/ScanFiles.php","line":83,"function":"backgroundScan","class":"OC\\Files\\Utils\\Scanner","type":"->"},{"file":"/var/www/html/nextcloud/apps/files/lib/BackgroundJob/ScanFiles.php","line":111,"function":"runScanner","class":"OCA\\Files\\BackgroundJob\\ScanFiles","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/BackgroundJob/Job.php","line":62,"function":"run","class":"OCA\\Files\\BackgroundJob\\ScanFiles","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/BackgroundJob/TimedJob.php","line":57,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/html/nextcloud/cron.php","line":126,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Quota.php","Line":74,"CustomMessage":"Error while running background job (class: OCA\\Files\\BackgroundJob\\ScanFiles, arguments: )"},"userAgent":"--","version":"19.0.4.2","id":"5f8e95c480ceb"}
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log

[Error] Failed to load resource: the server responded with a status of 404 () (details, line 0)
[Error]  (2)
Object

__ob__: Ct {value: Object, dep: ft, vmCount: 0, walk: function, observeArray: function}

apps: 

oc: 

route: 

settings: 

users: 

Object Prototyp

__defineGetter__(propertyName, getterFunction)

__defineSetter__(propertyName, setterFunction)

__lookupGetter__(propertyName)

__lookupSetter__(propertyName)

constructor: function()

hasOwnProperty(propertyName)

isPrototypeOf(property)

propertyIsEnumerable(propertyName)

toLocaleString()

toString()

valueOf()
Error: Request failed with status code 404
(anonyme Funktion) — createError.js:16
(anonyme Funktion) — settle.js:18
(anonyme Funktion) — xhr.js:61
	API_FAILURE (vue-settings-apps-users-management.js:1:257827)
	(anonyme Funktion) (vue-settings-apps-users-management.js:1:207784)
	(anonyme Funktion) (vue-settings-apps-users-management.js:1:209299)
	forEach
	(anonyme Funktion) (vue-settings-apps-users-management.js:1:209284)
	(anonyme Funktion) (vue-settings-apps-users-management.js:1:210822)
	(anonyme Funktion) (vue-settings-apps-users-management.js:1:209262)
	promiseReactionJob

	b) The network log
	c) 
</details>

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/server/issues/23579

### CODE REVIEW

File: lib/private/Files/Storage/Wrapper/Quota.php [hunk 1]
```diff
@@ -71,7 +71,9 @@ public function getQuota() {
 	protected function getSize($path, $storage = null) {
 		if ($this->config->getValue('quota_include_external_storage', false)) {
 			$rootInfo = Filesystem::getFileInfo('', 'ext');
-			return $rootInfo->getSize(true);
+			if ($rootInfo) {
+				return $rootInfo->getSize(true);
+			}
```
Comment (rullzer) [inline lib/private/Files/Storage/Wrapper/Quota.php:76]: Nope... you should properly return SPACE_NOT_COMPUTED then or something. Just retruning nothing seems weird.

**Review by rullzer — CHANGES_REQUESTED** [review]

File: lib/private/Files/Storage/Wrapper/Quota.php (hunk 1 above)
Comment (skjnldsv) [reply lib/private/Files/Storage/Wrapper/Quota.php:76]: Done
Missed that

**Review by MorrisJobke — APPROVED** [review]
🙈

**Review by ChristophWurst — APPROVED** [review]
