### PR TITLE
fix(files_sharing): file request pass empty string if password or expiration is disabled

### LINKED ISSUE #52064: [Bug]: Shares created with "Create file request" and unticked "expiration date" have the expiration date set.
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Shares via the "Create file request" feature are created with "expiration time", even if the expiration time is removed from the UI"

### Steps to reproduce

1. Go to `Administrations settings->Sharing` and enable "Set default expiration date for share via link or email"
2. In Files App click `New->Create file request`
3. Untick "Set a submission expiration date" during creation.
4. Share is created with "expiration date" althougth the checkbox was unticked and the "Enforce expiration date" is not enabled. 

### Expected behavior

Share should be created without "expiration date"

### Nextcloud Server version

master

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

Reproducable on both `master` and `stable30` branches.

Request is send correctly from Frontend to Backend without `expireDate` present:

`POST https://stable30.local/ocs/v2.php/apps/files_sharing/api/v1/shares`:

```
{"shareType":4,"permissions":4,"label":"","path":"/avx","note":"","shareWith":"","attributes":"[{\"value\":true,\"key\":\"enabled\",\"scope\":\"fileRequest\"}]"}
```

Problem is somewhere in the backend, imho.

Edited: Found such code in the backend:

https://github.com/nextcloud/server/blob/edeccc897f9994abeba6a7246349662ac22f2936/apps/files_sharing/lib/Controller/ShareAPIController.php#L641-L657

Looks like I was wrong, and it is Frontend, that should sent an empty string in `expireDate`

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/server/issues/52064

+ Tests to cover more cases on null/undefined behaviour change

### CODE REVIEW

File: build/integration/features/bootstrap/Sharing.php [hunk 1]
```diff
@@ -54,8 +54,12 @@ public function asCreatingAShareWith($user, $body) {
 			$fd = $body->getRowsHash();
 			if (array_key_exists('expireDate', $fd)) {
 				$dateModification = $fd['expireDate'];
-				if (!empty($dateModification)) {
+				if ($dateModification === 'null') {
```
Comment (nfebe) [inline build/integration/features/bootstrap/Sharing.php:57]:
```suggestion
				if ($dateModification === 'null' || $dateModification === null) {
```

**Review by nfebe — COMMENTED** [review]
I am not sure where `$dateModification` is coming from but `null` should not lead to it being set as an empty string?

File: build/integration/features/bootstrap/Sharing.php (hunk 1 above)
Comment (skjnldsv) [reply build/integration/features/bootstrap/Sharing.php:57]: It's being read as a string from the integration tests.
`null` is differently handled in the backend, that is the issue. We need to make sure we have some use cases for it

Like I commented sooner:
- `null` sets the default expiration date
- `undefined` also sets the default expiration date
- `''` sets no expiration date

**Review by nfebe — APPROVED** [review]

**Review by come-nc — APPROVED** [review]

**Comment by oleksandr-nc** [comment]
Can we backport this fix to the Nextcloud 30?

**Comment by skjnldsv** [comment]
> Can we backport this fix to the Nextcloud 30?

See the requests of backports above :+1:
