### PR TITLE
fix(dav): Handle duplicate event reminder

### LINKED ISSUE #41695: [Bug]: Deduplicate VALARM creates duplicate calendar notification
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I have an event that has tons of VALARM components. It's probably caused by a bug in Evolution.

```
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER:-PT15M
DESCRIPTION:Default Mozilla Description
X-EVOLUTION-ALARM-UID:7db2b9aea6d9ed8e3d05d090e24df8e399eb5cad
END:VALARM
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER:-PT15M
DESCRIPTION:Default Mozilla Description
X-EVOLUTION-ALARM-UID:0fbb4a0653e314ed123803620b490b44ed4c5be8
END:VALARM
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER:-PT15M
DESCRIPTION:Default Mozilla Description
X-EVOLUTION-ALARM-UID:73644b7baac717bbfea098df0e5fedc1cd6e92de
END:VALARM
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER:-PT15M
DESCRIPTION:Default Mozilla Description
X-EVOLUTION-ALARM-UID:cc7b0ab01d25278f0e1cf450107048ca6828e9dd
END:VALARM
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER:-PT15M
DESCRIPTION:Default Mozilla Description
X-EVOLUTION-ALARM-UID:b77009d5b1d879da58d2da8c4fd5307155b0a62b
END:VALARM
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER:-PT15M
DESCRIPTION:Default Mozilla Description
X-EVOLUTION-ALARM-UID:88363f16b6d74cd3b0e98f1cbbc351d7c7c60aef
END:VALARM
```

15 minutes before this event starts, I get overloaded with duplicate notifications.

Let's try to deduplicate identical notifications to work around these kind of client bugs.

### Steps to reproduce

1. Import an event with two identical VALARMs
2. Wait for the alarm time to be reached

### Expected behavior

See one single notification

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by hamza221**
* Resolves: #41695

## 

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/dav/lib/CalDAV/Reminder/Backend.php [hunk 1]
```diff
@@ -68,7 +68,8 @@ public function getRemindersToProcess():array {
 			->from('calendar_reminders', 'cr')
 			->where($query->expr()->lte('cr.notification_date', $query->createNamedParameter($this->timeFactory->getTime())))
 			->join('cr', 'calendarobjects', 'co', $query->expr()->eq('cr.object_id', 'co.id'))
-			->join('cr', 'calendars', 'c', $query->expr()->eq('cr.calendar_id', 'c.id'));
+			->join('cr', 'calendars', 'c', $query->expr()->eq('cr.calendar_id', 'c.id'))
+			->groupBy('cr.notification_date', 'cr.event_hash');
```
Comment (ChristophWurst) [inline apps/dav/lib/CalDAV/Reminder/Backend.php:72]: should it be the other way around? would it be possible to have a collision of notification date by two independent events of two or more users?

you will have to add all projected columns into the group clause because you are not allowed to have them in the SELECT otherwise, at least for strict databases: https://dev.mysql.com/doc/refman/8.0/en/group-by-handling.html.

File: apps/dav/lib/CalDAV/Reminder/ReminderService.php [hunk 2]
```diff
@@ -467,7 +467,16 @@ private function getRemindersForVAlarm(VAlarm $valarm,
 	 * @param array $reminders
 	 */
 	private function writeRemindersToDatabase(array $reminders): void {
+		$uniqueReminders = [];
+		$seen = [];
 		foreach ($reminders as $reminder) {
+			$key = $reminder['notification_date']. $reminder['event_hash'];
+			if(!isset($seen[$key])) {
+				$seen[$key] = true;
+				$uniqueReminders[] = $reminder;
```
Comment (tcitworld) [inline apps/dav/lib/CalDAV/Reminder/ReminderService.php:476]: Can't you just use a keyed array for `$uniqueReminders` instead of having an extra `$seen` array, and use `array_values` in the `foreach`?

File: apps/dav/lib/CalDAV/Reminder/Backend.php (hunk 1 above)
Comment (hamza221) [reply apps/dav/lib/CalDAV/Reminder/Backend.php:72]: AFAIK there should be one db entry for each recurrence independently from users . 

> would it be possible to have a collision of notification date by two independent events of two or more users?

we're grouping by`'cr.event_hash'` so it shouldn't affect independent events as far as I understand, no?

Comment (tcitworld) [reply apps/dav/lib/CalDAV/Reminder/Backend.php:72]: I think @ChristophWurst was just suggesting to group by `cr.event_hash`, then per `cr.notification_date`, which makes more sense to me as well.

File: apps/dav/lib/CalDAV/Reminder/Backend.php [hunk 3]
```diff
@@ -64,11 +64,12 @@ public function __construct(IDBConnection $db,
...
 	public function getRemindersToProcess():array {
 		$query = $this->db->getQueryBuilder();
-		$query->select(['cr.*', 'co.calendardata', 'c.displayname', 'c.principaluri'])
+		$query->select(['cr.*', 'co.calendardata', 'c.displayname', 'c.principaluri','cr.notification_date', 'cr.event_hash'])
 			->from('calendar_reminders', 'cr')
 			->where($query->expr()->lte('cr.notification_date', $query->createNamedParameter($this->timeFactory->getTime())))
 			->join('cr', 'calendarobjects', 'co', $query->expr()->eq('cr.object_id', 'co.id'))
-			->join('cr', 'calendars', 'c', $query->expr()->eq('cr.calendar_id', 'c.id'));
+			->join('cr', 'calendars', 'c', $query->expr()->eq('cr.calendar_id', 'c.id'))
+			->groupBy('cr.notification_date', 'cr.event_hash');
```
Comment (ChristophWurst) [inline apps/dav/lib/CalDAV/Reminder/Backend.php:72]:
```suggestion
			->groupBy('cr.event_hash', 'cr.notification_date');
```

Yep. If the hash and the date is equal we fully deduplicate.
If the hash differs but the date is equal we leave the duplicates.

**Review by tcitworld — COMMENTED** [review]
Code looks good, tests says no

File: apps/dav/lib/CalDAV/Reminder/ReminderService.php [hunk 4]
```diff
@@ -467,7 +467,14 @@ private function getRemindersForVAlarm(VAlarm $valarm,
 	 * @param array $reminders
 	 */
 	private function writeRemindersToDatabase(array $reminders): void {
+		$uniqueReminders = [];
 		foreach ($reminders as $reminder) {
+			$key = $reminder['notification_date']. $reminder['event_hash'];
```
Comment (tcitworld) [inline apps/dav/lib/CalDAV/Reminder/ReminderService.php:472]: As you can see in the test change you made, the key should also contain the `$reminder['type']`, as you can have two reminder of different types on the same date for the same event.

File: apps/dav/lib/CalDAV/Reminder/Backend.php [hunk 5]
```diff
@@ -64,11 +64,12 @@ public function __construct(IDBConnection $db,
 	 */
 	public function getRemindersToProcess():array {
 		$query = $this->db->getQueryBuilder();
-		$query->select(['cr.*', 'co.calendardata', 'c.displayname', 'c.principaluri'])
+		$query->select(['cr.*', 'co.calendardata', 'c.displayname', 'c.principaluri','cr.notification_date', 'cr.event_hash'])
```
Comment (tcitworld) [inline apps/dav/lib/CalDAV/Reminder/Backend.php:67]:
```suggestion
		$query->select(['cr.*', 'co.calendardata', 'c.displayname', 'c.principaluri','cr.notification_date', 'cr.event_hash', 'cr.type'])
```

File: apps/dav/lib/CalDAV/Reminder/Backend.php [hunk 6]
```diff
@@ -64,11 +64,12 @@ public function __construct(IDBConnection $db,
...
 			->from('calendar_reminders', 'cr')
 			->where($query->expr()->lte('cr.notification_date', $query->createNamedParameter($this->timeFactory->getTime())))
 			->join('cr', 'calendarobjects', 'co', $query->expr()->eq('cr.object_id', 'co.id'))
-			->join('cr', 'calendars', 'c', $query->expr()->eq('cr.calendar_id', 'c.id'));
+			->join('cr', 'calendars', 'c', $query->expr()->eq('cr.calendar_id', 'c.id'))
+			->groupBy('cr.event_hash', 'cr.notification_date');
```
Comment (tcitworld) [inline apps/dav/lib/CalDAV/Reminder/Backend.php:72]:
```suggestion
			->groupBy('cr.event_hash', 'cr.notification_date', 'cr.type');
```

File: apps/dav/tests/unit/CalDAV/Reminder/BackendTest.php [hunk 7]
```diff
@@ -134,9 +134,8 @@ public function testGetRemindersToProcess(): void {
 
 		$rows = $this->reminderBackend->getRemindersToProcess();
 
-		$this->assertCount(2, $rows);
```
Comment (tcitworld) [inline apps/dav/tests/unit/CalDAV/Reminder/BackendTest.php:137]: Adding the reminder type should allow you to revert these changes.

**Review by tcitworld — CHANGES_REQUESTED** [review]
We need the type as well.

**Comment by ChristophWurst** [comment]
@szaimen wrong button?

**Comment by szaimen** [comment]
> @szaimen wrong button?

Apparently. Sorry, not sure how this happened

File: apps/dav/tests/unit/CalDAV/Reminder/BackendTest.php [hunk 8]
```diff
@@ -111,7 +111,7 @@ public function testGetRemindersToProcess(): void {
 			->method('getTime')
 			->with()
 			->willReturn(123457);
-
+
```
Comment (tcitworld) [inline apps/dav/tests/unit/CalDAV/Reminder/BackendTest.php:114]: white space :eyes:

File: apps/dav/tests/unit/CalDAV/Reminder/BackendTest.php [hunk 9]
```diff
@@ -153,7 +153,6 @@ public function testGetRemindersToProcess(): void {
 			'principaluri' => 'principals/users/user001',
 		]);
 	}
-
```
Comment (tcitworld) [inline apps/dav/tests/unit/CalDAV/Reminder/BackendTest.php:156]: bye bye new line :cry:

**Review by tcitworld — APPROVED** [review]
Just cs issues

**Review by ChristophWurst — APPROVED** [review]
