### PR TITLE
fix(node): emit hooks on `Node::copy()`

### LINKED ISSUE #1756: Attachments get lost when copying a page
**Describe the bug**
In some situations, when copying a page, its attachments get lost.

**To Reproduce**
1. Create a page and add some images
2. Copy the page via "Copy or move" page action
3. Open the new page
4. See that images/attachments are missing

**Server details:**
- Collectives app version: 2.16.3

### PR DESCRIPTION
**Pull request by mejo-**
When calling `Files\Node\Node::copy()`, `Files\View::copy()` gets called, but `Files\View::fakeRoot` is empty so the hooks are not emitted if no path is given to `Files\View::shouldEmitHooks()`.

This results in node-related events like `NodeCopiedEvent` not being fired when copying files via `Files\Node\Node::copy()`.

`Files\View::shouldEmitHooks()` is given a path as parameter in almost all places except when called from the `copy()` function. This commit changes it and passes the copy target path.

Fixes: nextcloud/collectives#1756

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
Seems logical

**Review by icewind1991 — APPROVED** [review]
Makes sense

File: apps/files/lib/Listener/SyncLivePhotosListener.php [hunk 1]
```diff
@@ -37,6 +37,7 @@ class SyncLivePhotosListener implements IEventListener {
 	private array $pendingRenames = [];
 	/** @var Array<int, bool> */
 	private array $pendingDeletion = [];
+	private string $copyTargetPath = '';
```
Comment (artonge) [inline apps/files/lib/Listener/SyncLivePhotosListener.php:40]: This need to be an array as multiple live photo could be copied at once. When copying a folder, for example. Also, maybe use the same semantic and variable type as the other variables. An array of fileids would be enough I think.

```suggestion
	private string $pendingCopy = [];
```

File: apps/files/lib/Listener/SyncLivePhotosListener.php [hunk 2]
```diff
@@ -53,6 +54,10 @@ public function handle(Event $event): void {
 		}
 
 		if ($event instanceof BeforeNodeCopiedEvent || $event instanceof NodeCopiedEvent) {
+			if ($this->copyTargetPath === $event->getTarget()->getPath()) {
+				$this->copyTargetPath = '';
+				return;
+			}
```
Comment (artonge) [inline apps/files/lib/Listener/SyncLivePhotosListener.php:60]: Maybe move that to the `handleCopyRecursive` method.

**Review by artonge — COMMENTED** [review]
Overall, maybe just look into what the `handleMove` method is doing, as it seems to be doing something very similar.

File: apps/files/lib/Listener/SyncLivePhotosListener.php (hunk 1 above)
Comment (mejo-) [reply apps/files/lib/Listener/SyncLivePhotosListener.php]: Ah, good point! Changed this now.

**Review by artonge — APPROVED** [review]
