### PR TITLE
Fix hook encryption with cron job

### LINKED ISSUE #186: An unhandled exception has been thrown
Hi guys!

I've installed "Share Listing"-App(v0.3.0) on my NextCloud-Instance (v18.0.7).

I execute that App like this:
`root@share:/var/www/html/nextcloud# sudo -u apache php ./occ sharing:list`

Instead of getting a list of all my sharings, i recieve the following error:
`{"reqId":"do9Df3SBmMv3L1dI4laq","level":0,"time":"2020-09-14T09:15:19+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":"Deprecated event type for OCP\\Share::preUnshare: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"--","version":"18.0.7.1"}
{"reqId":"do9Df3SBmMv3L1dI4laq","level":0,"time":"2020-09-14T09:15:19+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":"Deprecated event type for OCP\\Share::postUnshare: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"--","version":"18.0.7.1"}
An unhandled exception has been thrown:
Error: Call to a member function getPath() on null in /var/www/html/nextcloud/lib/private/Files/Filesystem.php:901
Stack trace:
#0 /var/www/html/nextcloud/lib/private/Encryption/Update.php(105): OC\Files\Filesystem::getPath(373756)
#1 /var/www/html/nextcloud/lib/private/Encryption/HookManager.php(39): OC\Encryption\Update->postUnshared(Array)
#2 /var/www/html/nextcloud/lib/private/legacy/hook.php(111): OC\Encryption\HookManager::postUnshared(Array)
#3 /var/www/html/nextcloud/lib/private/Share20/LegacyHooks.php(84): OC_Hook::emit('OCP\\Share', 'post_unshare', Array)
#4 /var/www/html/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(260): OC\Share20\LegacyHooks->postUnshare(Object(Symfony\Component\EventDispatcher\GenericEvent), 'OCP\\Share::post...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#5 /var/www/html/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(235): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'OCP\\Share::post...', Object(Symfony\Component\EventDispatcher\GenericEvent))
#6 /var/www/html/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'OCP\\Share::post...', Object(Symfony\Component\EventDispatcher\GenericEvent))
#7 /var/www/html/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php(70): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Symfony\Component\EventDispatcher\GenericEvent), Object(Symfony\Component\EventDispatcher\GenericEvent))
#8 /var/www/html/nextcloud/lib/private/Share20/Manager.php(1172): OC\EventDispatcher\SymfonyAdapter->dispatch('OCP\\Share::post...', Object(Symfony\Component\EventDispatcher\GenericEvent))
#9 /var/www/html/nextcloud/lib/private/Share20/Manager.php(1480): OC\Share20\Manager->deleteShare(Object(OC\Share20\Share))
#10 /var/www/html/nextcloud/lib/private/Share20/Manager.php(1276): OC\Share20\Manager->checkExpireDate(Object(OC\Share20\Share))
#11 /var/www/html/nextcloud/apps/sharelisting/lib/Service/SharesList.php(204): OC\Share20\Manager->getSharesBy('tre', 4, NULL, true, -1, 0)
#12 /var/www/html/nextcloud/apps/sharelisting/vendor/nikic/iter/src/iter.php(204): OCA\ShareListing\Service\SharesList->getShares('tre')
#13 /var/www/html/nextcloud/apps/sharelisting/vendor/nikic/iter/src/iter.php(80): iter\filter(Object(Closure), Object(Generator))
#14 /var/www/html/nextcloud/apps/sharelisting/lib/Command/ListShares.php(107): iter\map(Object(Closure), Object(Generator))
#15 /var/www/html/nextcloud/lib/private/User/Manager.php(562): OCA\ShareListing\Command\ListShares->OCA\ShareListing\Command\{closure}(Object(OC\User\User))
#16 /var/www/html/nextcloud/apps/sharelisting/lib/Command/ListShares.php(110): OC\User\Manager->callForSeenUsers(Object(Closure))
#17 /var/www/html/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\ShareListing\Command\ListShares->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(915): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OCA\ShareListing\Command\ListShares), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/nextcloud/lib/private/Console/Application.php(214): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/nextcloud/console.php(99): OC\Console\Application->run()
#23 /var/www/html/nextcloud/occ(11): require_once('/var/www/html/n...')`

Is there anything i'm missing? Or anything i could do to fix that problem?

The following additional Apps are installed:
**Enabled**:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - dav: 1.14.0
  - documentserver_community: 0.1.7
  - encryption: 2.6.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - forms: 2.0.2
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.3.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - polls: 1.4.3
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - sharelisting: 0.3.0
  - support: 1.1.1
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0

**Disabled**:
  - admin_audit
  - files_external
  - user_ldap

Thank you and best Regards,
Perry

### LINKED ISSUE #284: Server-side Encryption - Call to a member function `getPath()` on null
Not documented, but it seems that this app in not compatible with Nextcloud server-side encryption.

```
/.occ sharing:list
An unhandled exception has been thrown:
Error: Call to a member function getPath() on null in /lib/private/Files/Filesystem.php:901

Stack trace:
#0 /lib/private/Encryption/Update.php(105): OC\Files\Filesystem::getPath(47106057)
#1 /lib/private/Encryption/HookManager.php(39): OC\Encryption\Update->postUnshared(Array)
#2 /lib/private/legacy/hook.php(111): OC\Encryption\HookManager::postUnshared(Array)
#3 /lib/private/Share20/LegacyHooks.php(84): OC_Hook::emit('OCP\\Share', 'post_unshare', Array)
#4 /3rdparty/symfony/event-dispatcher/EventDispatcher.php(260): OC\Share20\LegacyHooks->postUnshare(Object(Symfony\Component\EventDispatcher\GenericEvent), 'OCP\\Share::post...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#5 /3rdparty/symfony/event-dispatcher/EventDispatcher.php(235): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'OCP\\Share::post...', Object(Symfony\Component\EventDispatcher\GenericEvent))
#6 /3rdparty/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'OCP\\Share::post...', Object(Symfony\Component\EventDispatcher\GenericEvent))
#7 /lib/private/EventDispatcher/SymfonyAdapter.php(70): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Symfony\Component\EventDispatcher\GenericEvent), Object(Symfony\Component\EventDispatcher\GenericEvent))
#8 /lib/private/Share20/Manager.php(1173): OC\EventDispatcher\SymfonyAdapter->dispatch('OCP\\Share::post...', Object(Symfony\Component\EventDispatcher\GenericEvent))
#9 /lib/private/Share20/Manager.php(1481): OC\Share20\Manager->deleteShare(Object(OC\Share20\Share))
#10 /lib/private/Share20/Manager.php(1277): OC\Share20\Manager->checkExpireDate(Object(OC\Share20\Share))
#11 /apps/sharelisting/lib/Service/SharesList.php(204): OC\Share20\Manager->getSharesBy('GroupAlixia', 3, NULL, true, -1, 0)
#12 /apps/sharelisting/vendor/nikic/iter/src/iter.php(204): OCA\ShareListing\Service\SharesList->getShares('GroupAlixia')
#13 /apps/sharelisting/vendor/nikic/iter/src/iter.php(80): iter\filter(Object(Closure), Object(Generator))
#14 /apps/sharelisting/lib/Command/ListShares.php(107): iter\map(Object(Closure), Object(Generator))
#15 /lib/private/User/Manager.php(562): OCA\ShareListing\Command\ListShares->OCA\ShareListing\Command\{closure}(Object(OC\User\User))
#16 /apps/sharelisting/lib/Command/ListShares.php(110): OC\User\Manager->callForSeenUsers(Object(Closure))
#17 /3rdparty/symfony/console/Command/Command.php(255): OCA\ShareListing\Command\ListShares->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /3rdparty/symfony/console/Application.php(915): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OCA\ShareListing\Command\ListShares), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /lib/private/Console/Application.php(214): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /console.php(99): OC\Console\Application->run()
#23 /occ(11): require_once('/var/www/nextcl...')
#24 {main}
```

### LINKED ISSUE #29674: Error: Call to a member function getPath() on null in /lib/private/Files/Filesystem.php:878
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
Not known

### Actual behaviour
On Cronjob `/var/www/html/nextcloud/cron.php`:
```
Error: Call to a member function getPath() on null in /var/www/html/nextcloud/lib/private/Files/Filesystem.php:878
Stack trace:
#0 /var/www/html/nextcloud/lib/private/Encryption/Update.php(107): OC\Files\Filesystem::getPath()
#1 /var/www/html/nextcloud/lib/private/Encryption/HookManager.php(40): OC\Encryption\Update->postUnshared()
#2 /var/www/html/nextcloud/lib/private/legacy/OC_Hook.php(106): OC\Encryption\HookManager::postUnshared()
#3 /var/www/html/nextcloud/lib/private/Share20/LegacyHooks.php(84): OC_Hook::emit()
#4 /var/www/html/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(264): OC\Share20\LegacyHooks->postUnshare()
#5 /var/www/html/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch()
#6 /var/www/html/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
#7 /var/www/html/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php(123): Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
#8 /var/www/html/nextcloud/lib/private/Share20/Manager.php(1202): OC\EventDispatcher\SymfonyAdapter->dispatch()
#9 /var/www/html/nextcloud/lib/private/Share20/Manager.php(1510): OC\Share20\Manager->deleteShare()
#10 /var/www/html/nextcloud/lib/private/Share20/Manager.php(1411): OC\Share20\Manager->checkExpireDate()
#11 /var/www/html/nextcloud/apps/files_sharing/lib/ExpireSharesJob.php(97): OC\Share20\Manager->getShareById()
#12 /var/www/html/nextcloud/lib/public/BackgroundJob/Job.php(79): OCA\Files_Sharing\ExpireSharesJob->run()
#13 /var/www/html/nextcloud/lib/public/BackgroundJob/TimedJob.php(63): OCP\BackgroundJob\Job->execute()
#14 /var/www/html/nextcloud/cron.php(127): OCP\BackgroundJob\TimedJob->execute()
#15 {main}
```
### Server configuration

**Operating system:**
CentOS 7

**Web server:**
Apache 2.4.6

**Database:**
MariaDB-server-10.3.31-1

**PHP version:**
PHP 7.4.25
Zend Engine v3.4.0

**Nextcloud version:** (see Nextcloud admin page)
22.2.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from Nextcloud 21

**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder

Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - apporder: 0.13.0
  - bookmarks: 10.0.2
  - bruteforcesettings: 2.2.0
  - calendar: 2.3.4
  - checksum: 1.1.2
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.0.6
  - contactsinteraction: 1.3.0
  - dashboard: 7.2.0
  - dav: 1.19.0
  - encryption: 2.10.0
  - external: 3.9.0
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_external: 1.13.0
  - files_markdown: 2.3.4
  - files_pdfviewer: 2.3.0
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - groupfolders: 10.0.0
  - impersonate: 1.9.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - mail: 1.10.5
  - metadata: 0.14.0
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - quota_warning: 1.11.0
  - recommendations: 1.1.0
  - richdocuments: 4.2.3
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - sharingpath: 0.4.3
  - support: 1.5.0
  - tasks: 0.14.2
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - twofactor_totp: 6.1.0
  - twofactor_u2f: 6.2.0
  - unsplash: 1.2.3
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.0
Disabled:
  - admin_audit
  - notes
  - socialsharing_diaspora
  - socialsharing_facebook
  - socialsharing_twitter
  - survey_client
  - systemtags
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.2.0.2",
        "overwrite.cli.url": "***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "overwritecondaddr": "***",
        "overwritehost": "***",
        "overwriteprotocol": "https",
        "overwritewebroot": "\/",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "filelocking.enabled": true,
        "log_rotate_size": 10485760,
        "loglevel": 3,
        "logtimezone": "Europe\/Zurich",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "dbindex": 0,
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "maintenance": false,
        "skeletondirectory": "\/var\/www\/html\/nextcloud\/core\/custom_skeleton",
        "theme": "",
        "app_install_overwrite": [
            "sharerenamer",
            "calendar"
        ],
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false,
        "default_phone_region": "CH"
    }
}

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)

<?php
$CONFIG = array (
  'passwordsalt' => '***',
  'secret' => '***',
  'trusted_domains' =>
  array (
    0 => 'localhost',
    1 => '***',
  ),
  'datadirectory' => '/var/www/html/nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '22.2.0.2',
  'overwrite.cli.url' => '***',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'oc_nextcloud-adm',
  'dbpassword' => '***',
  'installed' => true,
  'instanceid' => '***,
  'overwritecondaddr' => '***',
  'overwritehost' => '***',
  'overwriteprotocol' => 'https',
  'overwritewebroot' => '/',
  'trusted_proxies' =>
  array (
    0 => '***',
  ),
  'filelocking.enabled' => true,
  'log_rotate_size' => 10485760,
  'loglevel' => 3,
  'logtimezone' => 'Europe/Zurich',
  'mail_domain' => '***',
  'mail_from_address' => 'noreply',
  'mail_smtphost' => 'localhost',
  'mail_smtpmode' => 'smtp',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'dbindex' => 0,
    'host' => '127.0.0.1',
    'port' => 6379,
    'timeout' => 0,
  ),
  'maintenance' => false,
  'skeletondirectory' => '/var/www/html/nextcloud/core/custom_skeleton',
  'theme' => '',
  'app_install_overwrite' =>
  array (
    0 => 'sharerenamer',
    1 => 'calendar',
  ),
  'encryption.legacy_format_support' => false,
  'encryption.key_storage_migrated' => false,
  'default_phone_region' => 'CH',
);
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### PR DESCRIPTION
**Pull request by CarlSchwan**
Make sure the setup fs is set before using the Update service

Fix #29674
Fix https://github.com/nextcloud/sharelisting/issues/284
Fix https://github.com/nextcloud/sharelisting/issues/186

Signed-off-by: Carl Schwan <carl@carlschwan.eu>

### CODE REVIEW

File: lib/private/Encryption/HookManager.php [hunk 1]
```diff
@@ -25,39 +25,56 @@
...
 
-	public static function postRename($params) {
+	public static function postRename($params): void {
 		self::getUpdate()->postRename($params);
+		self::tearDown();
 	}
 
-	public static function postRestore($params) {
+	public static function postRestore($params): void {
 		self::getUpdate()->postRestore($params);
```
Comment (nickvergessen) [inline lib/private/Encryption/HookManager.php:50]: No tearDown here?

Comment (CarlSchwan) [reply lib/private/Encryption/HookManager.php:50]: Good catch 😅

**Review by artonge — DISMISSED** [review]

**Comment by CarlSchwan** [comment]
Code is a bit horrible and any suggestions on how to improve it are welcome

**Comment by PVince81** [comment]
@icewind1991 would be good if you could check this, to confirm that there will be no side effects. thanks

**Comment by CarlSchwan** [comment]
> I think the teardown isn't required and there is less chance of side effects without it

done :)

File: lib/private/Encryption/HookManager.php [hunk 2]
```diff
@@ -25,39 +25,51 @@
...
 
-	public static function postShared($params) {
+	public static function postShared($params): void {
 		self::getUpdate()->postShared($params);
 	}
-	public static function postUnshared($params) {
-		self::getUpdate()->postUnshared($params);
+	public static function postUnshared($params): void {
+		// In case the unsharing happens in a background job, we don't have
+		// a session and we load instead the user from the UserManager
```
Comment (PVince81) [inline lib/private/Encryption/HookManager.php:39]: I don't see an `if` condition for the "in case", so I assume that the current logic also works fine when we have a session

Comment (PVince81) [inline lib/private/Encryption/HookManager.php:39]: I don't see an `if` condition for the "in case", so I assume that the current logic also works fine when we have a session

**Review by PVince81 — APPROVED** [review]
:+1:

File: lib/private/Encryption/HookManager.php (hunk 2 above)
Comment (CarlSchwan) [reply lib/private/Encryption/HookManager.php:39]: we basically get the owner of the file from the fileSource in that case. We could also first try the session and then fallback to the uid in the fileSource path, but I don't think this offer any advantage

**Review by icewind1991 — APPROVED** [review]

**Comment by PVince81** [comment]
@CarlSchwan backport to NC <= 23 will need manual adjustments because the FS setup is using the old API, please have a look

**Comment by PVince81** [comment]
@CarlSchwan please take care of the backports

**Comment by CarlSchwan** [comment]
Backports https://github.com/nextcloud/server/pull/32987 https://github.com/nextcloud/server/pull/32986

**Comment by Ecmoechr** [comment]
are comments disappearing here? interesting . . .
