### PR TITLE
fix(previews): Make thumbnail generation a bit more robust

### LINKED ISSUE #501: An unhandled exception has been thrown
Hi

we had this problem sometimes:
there are vwx (Vectorworks) and dwg (Autocad) files in the folder

Error:
`An unhandled exception has been thrown:
ValueError: Path cannot be empty in /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/apps/richdocuments/lib/Preview/Office.php:65
Stack trace:
#0 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/apps/richdocuments/lib/Preview/Office.php(65): fopen()
#1 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/lib/private/Preview/GeneratorHelper.php(64): OCA\Richdocuments\Preview\Office->getThumbnail()
#2 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/lib/private/Preview/Generator.php(361): OC\Preview\GeneratorHelper->getThumbnail()
#3 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/lib/private/Preview/Generator.php(337): OC\Preview\Generator->generateProviderPreview()
#4 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/lib/private/Preview/Generator.php(143): OC\Preview\Generator->getMaxPreview()
#5 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/lib/private/PreviewManager.php(211): OC\Preview\Generator->generatePreviews()
#6 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/apps/previewgenerator/lib/Command/Generate.php(232): OC\PreviewManager->generatePreviews()
#7 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/apps/previewgenerator/lib/Command/Generate.php(214): OCA\PreviewGenerator\Command\Generate->parseFile()
#8 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/apps/previewgenerator/lib/Command/Generate.php(212): OCA\PreviewGenerator\Command\Generate->parseFolder()
#9 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/apps/previewgenerator/lib/Command/Generate.php(212): OCA\PreviewGenerator\Command\Generate->parseFolder()
#10 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/apps/previewgenerator/lib/Command/Generate.php(212): OCA\PreviewGenerator\Command\Generate->parseFolder()
#11 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/apps/previewgenerator/lib/Command/Generate.php(212): OCA\PreviewGenerator\Command\Generate->parseFolder()
#12 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/apps/previewgenerator/lib/Command/Generate.php(183): OCA\PreviewGenerator\Command\Generate->parseFolder()
#13 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/apps/previewgenerator/lib/Command/Generate.php(131): OCA\PreviewGenerator\Command\Generate->generatePathPreviews()
#14 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/3rdparty/symfony/console/Command/Command.php(298): OCA\PreviewGenerator\Command\Generate->execute()
#15 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#16 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#17 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#18 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
#19 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/console.php(102): OC\Console\Application->run()
#20 /var/www/vhosts/lautwerfer.cloud/httpdocs/nextcloud/occ(11): require_once('...')
`

### PR DESCRIPTION
**Pull request by joshtrichards**
* Resolves: nextcloud/previewgenerator#501

## Summary

Makes thumbnail generation a bit more robust for Office / MP3 / Image / Movie types.

Same thing is already being done for other types e.g. HEIC:

https://github.com/nextcloud/server/blob/c54038cae610a73c9c2165e6d24d84d7c2bb076b/lib/private/Preview/HEIC.php#L45-L52

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by kesselb** [comment]
- Added the imports for LoggerInterface::class
- \OC::$server->get => \OCP\Server::get
- Squashed the commits

**Review by oleksandr-nc — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]

File: lib/private/Preview/Image.php [hunk 1]
```diff
@@ -25,6 +26,13 @@ public function getThumbnail(File $file, int $maxX, int $maxY): ?IImage {
 		$image = new \OCP\Image();
 
 		$fileName = $this->getLocalFile($file);
+		if ($fileName === false) {
+			\OCP\Server::get(LoggerInterface::class)->error(
+				'Failed to get thumbnail for: ' . $file->getPath(),
```
Comment (nickvergessen) [inline lib/private/Preview/Image.php:31]:
```suggestion
				'Failed to get local file to generate thumbnail for: ' . $file->getPath(),
```

**Review by nickvergessen — APPROVED** [review]

**Comment by solracsf** [comment]
Maybe also update HEIC file too for consistence across files 😉 

https://github.com/nextcloud/server/blob/c54038cae610a73c9c2165e6d24d84d7c2bb076b/lib/private/Preview/HEIC.php#L46-L50

Happy new year 🥳

**Review by AndyScherzinger — APPROVED** [review]

**Review by solracsf — APPROVED** [review]
