### PR TITLE
Fix relation "user_id" already exists migration error

### LINKED ISSUE #29986: upgrade to 23 (beta) failed
### Steps to reproduce
1. Have the latest version 22.x
2. Switch to beta chanel
3. Start upgrade
4. After checks, backups etc. start upgrade in web
5. Fail in DB step

### Expected behaviour
Finished upgrade

### Actual behaviour
Exception: Database error when running migration latest for app core
Update failed

### Server configuration

**Operating system:**
Linux, Debian, Docker

**Web server:**
Traefik v2

**Database:**
Postgresql 13.1

**PHP version:**
php 7.4

**Nextcloud version:** (see Nextcloud admin page)
23.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
from latest 22 (22.3?)

**Where did you install Nextcloud from:**
from settings by self-upgrade

**Signing status:**
can't reach

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - apporder: 0.13.0
  - bookmarks: 10.0.2
  - calendar: 3.0.0
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - cms_pico: 1.0.16
  - comments: 1.12.0
  - contacts: 4.0.6
  - contactsinteraction: 1.3.0
  - dashboard: 7.2.0
  - dav: 1.19.0
  - deck: 1.5.5
  - drawio: 1.0.1
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_markdown: 2.3.4
  - files_mindmap: 0.0.25
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - impersonate: 1.9.0
  - integration_google: 1.0.6
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - mail: 1.11.0
  - maps: 0.1.9
  - metadata: 0.14.0
  - music: 1.5.0
  - news: 17.0.0
  - nextcloud_announcements: 1.11.0
  - notes: 4.2.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - recommendations: 1.1.0
  - richdocuments: 4.2.3
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - social: 0.4.2
  - spreed: 12.1.2
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - talk_matterbridge: 1.22.4
  - talked: 0.2.0
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - video_converter: 1.0.3
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.0
Disabled:
  - admin_audit
  - audioplayer_editor
  - cookbook
  - encryption
  - facerecognition
  - files_external
  - flowupload
  - forms
  - polls
  - socialsharing_email
  - socialsharing_facebook
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.arns.lt",
            "cloud.arns.lt",
            "c.arns.lt"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "22.2.3.0",
        "overwrite.cli.url": "https:\/\/nextcloud.arns.lt",
        "installed": true,
        "maintenance": false,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 0,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.release.channel": "beta",
        "app_install_overwrite": [
            "files_readmemd",
            "drawio",
            "dropit",
            "files_ebookreader",
            "social",
            "flowupload"
        ],
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false,
        "data-fingerprint": "c9dad6fda7c4bd0bad14223b2f966ea7",
        "overwriteprotocol": "https",
        "default_phone_region": "LT",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "types": "",
            "installed_version": "1.8.0"
        },
        "activity": {
            "enabled": "yes",
            "types": "filesystem",
            "installed_version": "2.15.0"
        },
        "apporder": {
            "types": "",
            "enabled": "yes",
            "installed_version": "0.13.0"
        },
        "audioplayer": {
            "types": "filesystem",
            "enabled": "no",
            "installed_version": "3.0.0"
        },
        "audioplayer_editor": {
            "installed_version": "0.3.0",
            "types": "filesystem",
            "enabled": "no"
        },
        "backgroundjob": {
            "lastjob": "7014"
        },
        "bookmarks": {
            "installed_version": "10.0.2",
            "types": "",
            "enabled": "yes",
            "performance.maxBookmarksperAccount": ""
        },
        "calendar": {
            "installed_version": "3.0.0",
            "types": "",
            "enabled": "yes"
        },
        "circles": {
            "members_limit": "50",
            "types": "filesystem,dav",
            "test_nc_base": "",
            "allow_linked_groups": "1",
            "skip_invitation_to_closed_circles": "0",
            "allow_federated": "1",
            "installed_version": "22.1.1",
            "enabled": "yes",
            "migration_run": "0",
            "loopback_tmp_scheme": "https",
            "migration_22": "1",
            "migration_22_1": "1",
            "maintenance_run": "0",
            "maintenance_update": "{\"maximum\":3,\"3\":1638278702,\"2\":1638279302,\"1\":1638279302,\"4\":1638237603,\"5\":1637982002}"
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "types": "filesystem",
            "installed_version": "1.5.0"
        },
        "cms_pico": {
            "limit_groups": "[]",
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "1.0.16",
            "system_templates": "{\"empty\":{\"name\":\"empty\",\"type\":1,\"compat\":true},\"sample_pico\":{\"name\":\"sample_pico\",\"type\":1,\"compat\":true}}",
            "themes_etag": "08K39es7QC",
            "system_themes": "{\"default\":{\"name\":\"default\",\"type\":1,\"compat\":true}}",
            "plugins_etag": "VJShVwNrA7",
            "system_plugins": "{\"PicoDeprecated\":{\"name\":\"PicoDeprecated\",\"type\":1,\"compat\":true}}",
            "link_mode": "1"
        },
        "comments": {
            "enabled": "yes",
            "types": "logging",
            "installed_version": "1.12.0"
        },
        "contacts": {
            "types": "dav",
            "enabled": "yes",
            "installed_version": "4.0.6"
        },
        "contactsinteraction": {
            "types": "dav",
            "enabled": "yes",
            "installed_version": "1.3.0"
        },
        "cookbook": {
            "types": "",
            "enabled": "no",
            "installed_version": "0.9.7"
        },
        "core": {
            "default_encryption_module": "OC_DEFAULT_MODULE",
            "installedat": "1563655269.9071",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "scss.variables": "db81cddf52fdb3c8ca1e4c859e214124",
            "vendor": "nextcloud",
            "oc.integritycheck.checker": "[]",
            "enterpriseLogoChecked": "yes",
            "moveavatarsdone": "yes",
            "previewsCleanedUp": "1",
            "public_webfinger": "social\/lib\/webfinger.php",
            "public_host-meta": "social\/lib\/hostmeta.php",
            "backgroundjobs_mode": "cron",
            "updater.secret.created": "1638279494",
            "lastupdatedat": "1638279455",
            "theming.variables": "688602013bee7460f11aa9490db1911e",
            "lastupdateResult": "{\"version\":\"23.0.0.10\",\"versionstring\":\"Nextcloud 23.0.0\",\"url\":\"https:\\\/\\\/download.nextcloud.com\\\/server\\\/releases\\\/nextcloud-23.0.0.zip\",\"web\":\"https:\\\/\\\/docs.nextcloud.com\\\/server\\\/23\\\/admin_manual\\\/maintenance\\\/upgrade.html\",\"changes\":\"https:\\\/\\\/updates.nextcloud.com\\\/changelog_server\\\/?version=23.0.0\",\"autoupdater\":\"1\",\"eol\":\"0\"}",
            "lastcron": "1638279302"
        },
        "dashboard": {
            "types": "",
            "installed_version": "7.2.0",
            "enabled": "yes"
        },
        "dav": {
            "enabled": "yes",
            "types": "filesystem",
            "installed_version": "1.19.0",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "buildCalendarSearchIndex": "yes",
            "buildCalendarReminderIndex": "yes",
            "sendEventRemindersPush": "yes",
            "chunks_migrated": "1"
        },
        "deck": {
            "types": "dav",
            "enabled": "yes",
            "installed_version": "1.5.5"
        },
        "drawio": {
            "types": "filesystem",
            "DrawioUrl": "https:\/\/www.draw.io",
            "enabled": "yes",
            "DrawioXml": "yes",
            "DrawioOffline": "no",
            "DrawioLang": "auto",
            "DrawioTheme": "minimal",
            "installed_version": "1.0.1"
        },
        "dropit": {
            "types": "",
            "enabled": "no",
            "installed_version": "0.4.0"
        },
        "encryption": {
            "masterKeyId": "master_9f739947",
            "publicShareKeyId": "pubShare_9f739947",
            "recoveryKeyId": "recoveryKey_9f739947"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "types": "",
            "installed_version": "1.12.0"
        },
        "federation": {
            "enabled": "yes",
            "types": "authentication",
            "installed_version": "1.12.0"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "types": "filesystem",
            "installed_version": "1.17.0"
        },
        "files_markdown": {
            "types": "",
            "installed_version": "2.3.4",
            "enabled": "yes"
        },
        "files_mindmap": {
            "types": "",
            "enabled": "yes",
            "installed_version": "0.0.25"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "types": "",
            "installed_version": "2.3.1"
        },
        "files_rightclick": {
            "enabled": "yes",
            "types": "",
            "installed_version": "1.1.0"
        },
        "files_sharing": {
            "enabled": "yes",
            "types": "filesystem",
            "installed_version": "1.14.0"
        },
        "files_texteditor": {
            "installed_version": "2.8.0",
            "types": "",
            "enabled": "no"
        },
        "files_trashbin": {
            "enabled": "yes",
            "types": "filesystem,dav",
            "installed_version": "1.12.0"
        },
        "files_versions": {
            "enabled": "yes",
            "types": "filesystem,dav",
            "installed_version": "1.15.0"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "types": "",
            "installed_version": "1.11.0"
        },
        "firstrunwizard": {
            "enabled": "yes",
            "types": "logging",
            "installed_version": "2.11.0"
        },
        "flowupload": {
            "installed_version": "1.1.2",
            "types": "",
            "enabled": "no"
        },
        "forms": {
            "types": "",
            "installed_version": "2.4.0",
            "enabled": "no"
        },
        "gallery": {
            "types": "",
            "enabled": "no",
            "installed_version": "18.4.0"
        },
        "impersonate": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.9.0",
            "authorized": "[\"L\u012b\u010d\u012bna\"]"
        },
        "integration_google": {
            "installed_version": "1.0.6",
            "types": "",
            "enabled": "yes"
        },
        "keeweb": {
            "types": "",
            "installed_version": "0.6.4",
            "enabled": "no"
        },
        "logreader": {
            "enabled": "yes",
            "types": "",
            "installed_version": "2.7.0"
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "types": "authentication",
            "installed_version": "1.10.0"
        },
        "mail": {
            "types": "",
            "installed_version": "1.11.0",
            "enabled": "yes"
        },
        "maps": {
            "installed_version": "0.1.9",
            "types": "filesystem",
            "enabled": "yes"
        },
        "metadata": {
            "types": "",
            "enabled": "yes",
            "installed_version": "0.14.0"
        },
        "music": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "1.5.0"
        },
        "news": {
            "autoPurgeMinimumInterval": "60",
            "autoPurgeCount": "200",
            "maxRedirects": "10",
            "feedFetcherTimeout": "60",
            "useCronUpdates": "1",
            "exploreUrl": "",
            "types": "",
            "updateInterval": "3600",
            "installed_version": "17.0.0",
            "enabled": "yes"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "types": "logging",
            "installed_version": "1.11.0",
            "notification_groups": "[\"admin\"]",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200"
        },
        "notes": {
            "types": "",
            "enabled": "yes",
            "installed_version": "4.2.0"
        },
        "notifications": {
            "enabled": "yes",
            "types": "logging",
            "installed_version": "2.10.1"
        },
        "oauth2": {
            "enabled": "yes",
            "types": "authentication",
            "installed_version": "1.10.0"
        },
        "occweb": {
            "installed_version": "0.0.7",
            "types": "",
            "enabled": "no"
        },
        "ocsms": {
            "installed_version": "2.2.0",
            "types": "",
            "enabled": "no"
        },
        "password_policy": {
            "enabled": "yes",
            "types": "authentication",
            "installed_version": "1.12.0"
        },
        "passwords": {
            "installed_version": "2020.12.1",
            "migration\/customFields": "2020.2.0",
            "types": "",
            "enabled": "no",
            "SSEv1ServerKey": "5yoAVwluZMtZfrbh2JdXcjzwI47Vgy+ywdzYPBJEGfS+OTE2Dobls\/irLmYotiEdi1QRuy9L+7ErLqwa2ilwDXgShf3b5hXynGQw+MBvFbi5MnojaeTx2DivYA1w8V6FzJYZ5VVdUL2T77O18+nI8NF539IILrEhHjYDbwe5iQyUPNA+OE83cIbUKF4maZAIgyCyTVf+Wc09wX28Vzcs+kEROdlrW1K4UGG79onvfnl4zrhnSUjPQjeqZpL8+4+u3yHVLs\/PkyrQTIWh\/XEjfzs0ISZZveDcFbIpsnO823Lmcsy6wJqi4SkhbD8PL+h2D0eC3BJFpnjicA3P+vUHcCbLhrlxVL7AQiFTvXiNlOt5JtfJdFNJv6JJoMNq5jNVoCiHnzRNDOXmB7PPrnnmJ3u99fhTsTmdqe58hujM3DzKZEJWySbFP3w+42mkLk1pWvBq89FJIK5fQeoI2NTYCXXdFYF6GxxjUTKKShAP0XeYm+qAK7tvmTfrFYWf3BFmH7IiE8DI6\/DrV2gKoZ8bwLTDGWqYFOElugN0Wkwo5upE+XiGelwco0ZEaavd6bS8F0VIuysZpr5oBb\/bhpNRlwYKG7LrotER5akWaH+Yb9Due9xRjFhiXxB80K\/Qv1ZmWReY9qPI1o54ELbKXCPNpvksotfwlE1DT0\/5s5jy5r+aDQhKq+1tOB\/rODM+hidQFTJX4hHD3x5Mk6qfASj99JLseMi\/uS63LWJ7F6PjTs4dXNTHqXOOs7Mepjgun+ictDLx4x5VRGb2ojhRtMUaIuzQ0OlLad1eidPNRXNYH579a\/25OiKln9l7XutnwFxOU67pMkwf7AAhz+3ZBR0nGPRx+OO6gnefaD7+g7g1\/d\/QaG7FH0ywwMm\/7h7hp1aZUmfKfRDWO0YAbKH0qWJNi\/qUoPXPoIB++DYY7fFqsPDQz6P+7K6LLEWGzTVfHAahsjSZeKTSSiCZ9nBRJfqn4ZQLQRdda5S6Iw8p+6MlqhppJqFj5UPbBbCm31PeaZHe",
            "users\/deleted": "[]",
            "passwords\/localdb\/type": "hibp"
        },
        "phonetrack": {
            "installed_version": "0.5.2",
            "types": "",
            "enabled": "no"
        },
        "photos": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.4.0"
        },
        "polls": {
            "types": "",
            "installed_version": "3.3.0",
            "enabled": "no"
        },
        "privacy": {
            "enabled": "yes",
            "types": "",
            "installed_version": "1.6.0"
        },
        "provisioning_api": {
            "enabled": "yes",
            "types": "prevent_group_restriction",
            "installed_version": "1.12.0"
        },
        "qownnotesapi": {
            "installed_version": "19.4.0",
            "types": "",
            "enabled": "no"
        },
        "radio": {
            "installed_version": "0.6.6",
            "types": "",
            "enabled": "no"
        },
        "recommendations": {
            "enabled": "yes",
            "types": "",
            "installed_version": "1.1.0"
        },
        "richdocuments": {
            "types": "prevent_group_restriction",
            "enabled": "yes",
            "canonical_webroot": "",
            "external_apps": "",
            "public_wopi_url": "https:\/\/collobora.arns.lt",
            "disable_certificate_verification": "",
            "wopi_url": "collobora.arns.lt",
            "installed_version": "4.2.3"
        },
        "richdocumentscode": {
            "types": "",
            "installed_version": "6.4.403",
            "enabled": "no"
        },
        "serverinfo": {
            "enabled": "yes",
            "types": "",
            "installed_version": "1.12.0",
            "cached_count_storages": "7",
            "cached_count_filecache": "59546"
        },
        "settings": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.4.0"
        },
        "sharebymail": {
            "enabled": "yes",
            "types": "filesystem",
            "installed_version": "1.12.0"
        },
        "social": {
            "types": "",
            "social_url": "http:\/\/nextcloud.arns.lt\/index.php\/apps\/social\/",
            "update_checked": "0.3",
            "cloud_url": "https:\/\/nextcloud.arns.lt",
            "enabled": "yes",
            "installed_version": "0.4.2"
        },
        "socialsharing_diaspora": {
            "installed_version": "1.0.4",
            "types": "",
            "enabled": "no"
        },
        "socialsharing_email": {
            "types": "",
            "enabled": "no",
            "installed_version": "2.4.0"
        },
        "socialsharing_facebook": {
            "types": "",
            "installed_version": "2.4.0",
            "enabled": "no"
        },
        "spreed": {
            "has_reference_id": "yes",
            "project_access_invalidated": "1",
            "types": "dav,prevent_group_restriction",
            "matterbridge_binary": "\/var\/www\/html\/apps\/talk_matterbridge\/bin\/matterbridge-1.22.3-linux-64bit",
            "installed_version": "12.1.2",
            "enabled": "yes",
            "stun_servers": "***REMOVED SENSITIVE VALUE***",
            "signaling_ticket_secret": "***REMOVED SENSITIVE VALUE***",
            "bridge_bot_password": "***REMOVED SENSITIVE VALUE***",
            "enable_matterbridge": "1",
            "turn_servers": "***REMOVED SENSITIVE VALUE***"
        },
        "support": {
            "enabled": "yes",
            "types": "session",
            "installed_version": "1.5.0",
            "SwitchUpdaterServerHasRun": "yes"
        },
        "survey_client": {
            "enabled": "yes",
            "types": "",
            "installed_version": "1.10.0",
            "last_sent": "1636710002",
            "last_report": "{\"id\":\"ocmf43eznlil\",\"items\":[[\"server\",\"version\",\"22.2.0.2\"],[\"server\",\"code\",\"other\"],[\"server\",\"enable_avatars\",\"yes\"],[\"server\",\"enable_previews\",\"yes\"],[\"server\",\"memcache.local\",\"\\\\OC\\\\Memcache\\\\APCu\"],[\"server\",\"memcache.distributed\",\"none\"],[\"server\",\"asset-pipeline.enabled\",\"no\"],[\"server\",\"filelocking.enabled\",\"yes\"],[\"server\",\"memcache.locking\",\"none\"],[\"server\",\"debug\",\"no\"],[\"server\",\"cron\",\"cron\"],[\"php\",\"version\",\"7.4.15\"],[\"php\",\"memory_limit\",536870912],[\"php\",\"max_execution_time\",0],[\"php\",\"upload_max_filesize\",2097152],[\"database\",\"type\",\"pgsql\"],[\"database\",\"version\",\"PostgreSQL 13.1 (Debian 13.1-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit\"],[\"database\",\"size\",155922991],[\"apps\",\"files_texteditor\",\"disabled\"],[\"apps\",\"gallery\",\"disabled\"],[\"apps\",\"forms\",\"disabled\"],[\"apps\",\"audioplayer_editor\",\"disabled\"],[\"apps\",\"comments\",\"1.12.0\"],[\"apps\",\"federation\",\"1.12.0\"],[\"apps\",\"files_versions\",\"1.15.0\"],[\"apps\",\"oauth2\",\"1.10.0\"],[\"apps\",\"password_policy\",\"1.12.0\"],[\"apps\",\"files\",\"1.17.0\"],[\"apps\",\"cloud_federation_api\",\"1.5.0\"],[\"apps\",\"dav\",\"1.19.0\"],[\"apps\",\"files_sharing\",\"1.14.0\"],[\"apps\",\"files_trashbin\",\"1.12.0\"],[\"apps\",\"sharebymail\",\"1.12.0\"],[\"apps\",\"workflowengine\",\"2.4.0\"],[\"apps\",\"firstrunwizard\",\"2.11.0\"],[\"apps\",\"nextcloud_announcements\",\"1.11.0\"],[\"apps\",\"notifications\",\"2.10.1\"],[\"apps\",\"systemtags\",\"1.12.0\"],[\"apps\",\"federatedfilesharing\",\"1.12.0\"],[\"apps\",\"files_pdfviewer\",\"2.3.0\"],[\"apps\",\"files_videoplayer\",\"1.11.0\"],[\"apps\",\"logreader\",\"2.7.0\"],[\"apps\",\"privacy\",\"1.6.0\"],[\"apps\",\"provisioning_api\",\"1.12.0\"],[\"apps\",\"recommendations\",\"1.1.0\"],[\"apps\",\"serverinfo\",\"1.12.0\"],[\"apps\",\"support\",\"1.5.0\"],[\"apps\",\"survey_client\",\"1.10.0\"],[\"apps\",\"twofactor_backupcodes\",\"1.11.0\"],[\"apps\",\"updatenotification\",\"1.12.0\"],[\"apps\",\"viewer\",\"1.6.0\"],[\"apps\",\"theming\",\"1.13.0\"],[\"apps\",\"talked\",\"0.2.0\"],[\"apps\",\"workflow_script\",\"disabled\"],[\"apps\",\"socialsharing_diaspora\",\"disabled\"],[\"apps\",\"qownnotesapi\",\"disabled\"],[\"apps\",\"phonetrack\",\"disabled\"],[\"apps\",\"timetracker\",\"disabled\"],[\"apps\",\"flowupload\",\"disabled\"],[\"apps\",\"user_saml\",\"disabled\"],[\"apps\",\"passwords\",\"disabled\"],[\"apps\",\"keeweb\",\"disabled\"],[\"apps\",\"uploaddetails\",\"disabled\"],[\"apps\",\"audioplayer\",\"disabled\"],[\"apps\",\"dropit\",\"disabled\"],[\"apps\",\"polls\",\"disabled\"],[\"apps\",\"files_markdown\",\"2.3.4\"],[\"apps\",\"socialsharing_facebook\",\"disabled\"],[\"apps\",\"circles\",\"22.1.1\"],[\"apps\",\"settings\",\"1.4.0\"],[\"apps\",\"metadata\",\"0.14.0\"],[\"apps\",\"bookmarks\",\"10.0.2\"],[\"apps\",\"calendar\",\"2.3.4\"],[\"apps\",\"impersonate\",\"1.9.0\"],[\"apps\",\"socialsharing_email\",\"disabled\"],[\"apps\",\"activity\",\"2.15.0\"],[\"apps\",\"notes\",\"4.1.1\"],[\"apps\",\"photos\",\"1.4.0\"],[\"apps\",\"text\",\"3.3.0\"],[\"apps\",\"contacts\",\"4.0.6\"],[\"apps\",\"spreed\",\"12.1.2\"],[\"apps\",\"mail\",\"1.10.5\"],[\"apps\",\"apporder\",\"0.13.0\"],[\"apps\",\"ocsms\",\"disabled\"],[\"apps\",\"radio\",\"disabled\"],[\"apps\",\"occweb\",\"disabled\"],[\"apps\",\"drawio\",\"1.0.1\"],[\"apps\",\"richdocumentscode\",\"disabled\"],[\"apps\",\"news\",\"16.2.0\"],[\"apps\",\"music\",\"1.4.1\"],[\"apps\",\"dashboard\",\"7.2.0\"],[\"apps\",\"social\",\"0.4.2\"],[\"apps\",\"contactsinteraction\",\"1.3.0\"],[\"apps\",\"cookbook\",\"disabled\"],[\"apps\",\"user_status\",\"1.2.0\"],[\"apps\",\"weather_status\",\"1.2.0\"],[\"apps\",\"video_converter\",\"1.0.3\"],[\"apps\",\"accessibility\",\"1.8.0\"],[\"apps\",\"files_mindmap\",\"0.0.25\"],[\"apps\",\"deck\",\"1.5.5\"],[\"apps\",\"talk_matterbridge\",\"1.22.4\"],[\"apps\",\"richdocuments\",\"4.2.3\"],[\"apps\",\"cms_pico\",\"1.0.16\"],[\"apps\",\"lookup_server_connector\",\"1.10.0\"],[\"apps\",\"files_rightclick\",\"1.1.0\"],[\"stats\",\"num_files\",59240],[\"stats\",\"num_users\",5],[\"stats\",\"num_storages\",7],[\"stats\",\"num_storages_local\",1],[\"stats\",\"num_storages_home\",6],[\"stats\",\"num_storages_other\",0],[\"stats\",\"num_comments\",399],[\"stats\",\"num_comment_markers\",3],[\"stats\",\"num_systemtags\",0],[\"stats\",\"num_systemtags_mappings\",0],[\"files_sharing\",\"num_shares\",8],[\"files_sharing\",\"num_shares_user\",0],[\"files_sharing\",\"num_shares_groups\",0],[\"files_sharing\",\"num_shares_link\",7],[\"files_sharing\",\"num_shares_link_no_password\",7],[\"files_sharing\",\"num_fed_shares_sent\",0],[\"files_sharing\",\"num_fed_shares_received\",0],[\"files_sharing\",\"permissions_10_19\",1],[\"files_sharing\",\"permissions_3_17\",7],[\"encryption\",\"enabled\",\"no\"],[\"encryption\",\"default_module\",\"yes\"]]}"
        },
        "systemtags": {
            "enabled": "yes",
            "types": "logging",
            "installed_version": "1.12.0"
        },
        "talk_matterbridge": {
            "installed_version": "1.22.4",
            "types": "prevent_group_restriction",
            "enabled": "yes"
        },
        "talked": {
            "installed_version": "0.2.0",
            "types": "",
            "enabled": "yes"
        },
        "text": {
            "types": "dav",
            "enabled": "yes",
            "installed_version": "3.3.0"
        },
        "theming": {
            "types": "logging",
            "name": "Udovi\u010d Cloud",
            "slogan": "***REMOVED SENSITIVE VALUE***",
            "cachebuster": "12",
            "installed_version": "1.13.0",
            "enabled": "yes",
            "url": "***REMOVED SENSITIVE VALUE***",
            "color": "#064D00"
        },
        "timetracker": {
            "enabled": "no",
            "types": "",
            "installed_version": "0.0.42"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "types": "",
            "installed_version": "1.11.0"
        },
        "updatenotification": {
            "audioplayer_editor": "0.3.0",
            "enabled": "yes",
            "types": "",
            "calendar": "2.4.0",
            "timetracker": "0.0.42",
            "cms_pico": "1.0.16",
            "installed_version": "1.12.0",
            "notify_groups": "[\"admin\"]",
            "integration_google": "1.0.6",
            "passwords": "2020.3.1",
            "spreed": "11.3.3",
            "files_mindmap": "0.0.25",
            "mail": "1.10.5",
            "notes": "4.2.0",
            "flowupload": "1.1.2",
            "bookmarks": "10.0.2",
            "circles": "0.21.4",
            "ocsms": "2.1.8",
            "update_check_errors": "0",
            "dropit": "0.4.0",
            "impersonate": "1.5.2",
            "socialsharing_email": "2.1.0",
            "socialsharing_facebook": "2.1.0",
            "user_saml": "3.2.1",
            "forms": "2.2.4",
            "video_converter": "1.0.3",
            "contacts": "4.0.6",
            "drawio": "1.0.1",
            "deck": "1.4.5",
            "news": "17.0.0",
            "files_markdown": "2.3.4",
            "metadata": "0.14.0",
            "cookbook": "0.8.4",
            "music": "1.5.0",
            "core": "22.2.2.0",
            "apporder": "0.13.0",
            "polls": "1.8.3",
            "richdocuments": "4.2.3",
            "talk_matterbridge": "1.22.4"
        },
        "uploaddetails": {
            "installed_version": "0.1.3",
            "types": "",
            "enabled": "no"
        },
        "user_saml": {
            "installed_version": "3.3.1",
            "enabled": "no",
            "types": "authentication",
            "type": "saml",
            "general-idp0_display_name": "Udovi\u010d SSO",
            "providerIds": "1",
            "general-allow_multiple_user_back_ends": "1"
        },
        "user_status": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.2.0"
        },
        "video_converter": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.0.3"
        },
        "viewer": {
            "enabled": "yes",
            "types": "",
            "installed_version": "1.6.0"
        },
        "weather_status": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.2.0"
        },
        "workflow_script": {
            "installed_version": "1.5.0",
            "enabled": "no",
            "types": "filesystem"
        },
        "workflowengine": {
            "enabled": "yes",
            "types": "filesystem",
            "installed_version": "2.4.0"
        }
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome

**Operating system:** Linux

### Logs

see nextcloud.log

#### Web server error log
<details>
<summary>Web server error log</summary>

```
nothing interesting
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"zJoaqgJeoAphSCEGlfxq","level":3,"time":"2021-11-30T14:10:14+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":"Database error when running migrat
ion latest for app core","userAgent":"--","version":"22.2.3.0","exception":{"Exception":"Exception","Message":"Database error when running migration latest for app core","Code":0,"Trace":[{"file":"/v
ar/www/html/lib/private/Updater.php","line":315,"function":"migrate","class":"OC\\DB\\MigrationService","type":"->","args":[]},{"file":"/var/www/html/lib/private/Updater.php","line":254,"function":"d
oCoreUpgrade","class":"OC\\Updater","type":"->","args":[]},{"file":"/var/www/html/lib/private/Updater.php","line":133,"function":"doUpgrade","class":"OC\\Updater","type":"->","args":["23.0.0.10","22.
2.3.0"]},{"file":"/var/www/html/core/Command/Upgrade.php","line":235,"function":"upgrade","class":"OC\\Updater","type":"->","args":[]},{"file":"/var/www/html/3rdparty/symfony/console/Command/Command.
php","line":255,"function":"execute","class":"OC\\Core\\Command\\Upgrade","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\
Output\\ConsoleOutput"}]},{"file":"/var/www/html/3rdparty/symfony/console/Application.php","line":1009,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->","args":[{"_
_class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/var/www/html/3rdparty/symfony/console/Application.php","line"
:273,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"OC\\Core\\Command\\Upgrade"},{"__class__":"Symfony\\Component\\Console\\Input\\Argv
Input"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/var/www/html/3rdparty/symfony/console/Application.php","line":149,"function":"doRun","class":"Symfony\\Component
\\Console\\Application","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/var/www/html/l
ib/private/Console/Application.php","line":211,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"
__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/var/www/html/console.php","line":99,"function":"run","class":"OC\\Console\\Application","type":"->","args":[]},{"file":"/v
ar/www/html/occ","line":11,"args":["/var/www/html/console.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/DB/MigrationService.php","Line":429,"Previous":{"Exception":"Doctrine\\DB
AL\\Exception\\TableExistsException","Message":"An exception occurred while executing a query: SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation \"user_id\" already exists","Code":7,"Trace":[{"fil
e":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":1780,"function":"convert","class":"Doctrine\\DBAL\\Driver\\API\\PostgreSQL\\ExceptionConverter","type":"->","args":[{"__class__":"D
octrine\\DBAL\\Driver\\PDO\\Exception"},{"__class__":"Doctrine\\DBAL\\Query"}]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":1719,"function":"handleDriverException","class
":"Doctrine\\DBAL\\Connection","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDO\\Exception"},{"__class__":"Doctrine\\DBAL\\Query"}]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Con
nection.php","line":1067,"function":"convertExceptionDuringQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDO\\Exception"},"CREATE UNIQUE INDEX
user_id ON oc_profile_config (user_id)",[],[]]},{"file":"/var/www/html/lib/private/DB/Connection.php","line":236,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["CR
EATE UNIQUE INDEX user_id ON oc_profile_config (user_id)",[],[],null]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":1809,"function":"executeQuery","class":"OC\\DB\\Connect
ion","type":"->","args":["CREATE UNIQUE INDEX user_id ON oc_profile_config (user_id)"]},{"file":"/var/www/html/lib/private/DB/Migrator.php","line":175,"function":"query","class":"Doctrine\\DBAL\\Conn
ection","type":"->","args":["CREATE UNIQUE INDEX user_id ON oc_profile_config (user_id)"]},{"file":"/var/www/html/lib/private/DB/Migrator.php","line":76,"function":"applySchema","class":"OC\\DB\\Migr
ator","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Schema\\Schema"}]},{"file":"/var/www/html/lib/private/DB/Connection.php","line":532,"function":"migrate","class":"OC\\DB\\Migrator","type":"->"
,"args":[{"__class__":"Doctrine\\DBAL\\Schema\\Schema"}]},{"file":"/var/www/html/lib/private/DB/MigrationService.php","line":540,"function":"migrateToSchema","class":"OC\\DB\\Connection","type":"->",
"args":[{"__class__":"Doctrine\\DBAL\\Schema\\Schema"}]},{"file":"/var/www/html/lib/private/DB/MigrationService.php","line":425,"function":"executeStep","class":"OC\\DB\\MigrationService","type":"->"
,"args":["23000Date20210930122352",false]},{"file":"/var/www/html/lib/private/Updater.php","line":315,"function":"migrate","class":"OC\\DB\\MigrationService","type":"->","args":[]},{"file":"/var/www/
html/lib/private/Updater.php","line":254,"function":"doCoreUpgrade","class":"OC\\Updater","type":"->","args":[]},{"file":"/var/www/html/lib/private/Updater.php","line":133,"function":"doUpgrade","cla
ss":"OC\\Updater","type":"->","args":["23.0.0.10","22.2.3.0"]},{"file":"/var/www/html/core/Command/Upgrade.php","line":235,"function":"upgrade","class":"OC\\Updater","type":"->","args":[]},{"file":"/
var/www/html/3rdparty/symfony/console/Command/Command.php","line":255,"function":"execute","class":"OC\\Core\\Command\\Upgrade","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\A
rgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/var/www/html/3rdparty/symfony/console/Application.php","line":1009,"function":"run","class":"Symfony\\Compone
nt\\Console\\Command\\Command","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/var/www
/html/3rdparty/symfony/console/Application.php","line":273,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"OC\\Core\\Command\\Upgrade"},
{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/var/www/html/3rdparty/symfony/console/Application.php","li
ne":149,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Conso
le\\Output\\ConsoleOutput"}]},{"file":"/var/www/html/lib/private/Console/Application.php","line":211,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class_
_":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/var/www/html/console.php","line":99,"function":"run","class":"OC\\Co
nsole\\Application","type":"->","args":[]},{"file":"/var/www/html/occ","line":11,"args":["/var/www/html/console.php"],"function":"require_once"}],"File":"/var/www/html/3rdparty/doctrine/dbal/src/Driv
er/API/PostgreSQL/ExceptionConverter.php","Line":70,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDO\\Exception","Message":"SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation \"user_id\" alread
y exists","Code":7,"Trace":[{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Connection.php","line":87,"function":"new","class":"Doctrine\\DBAL\\Driver\\PDO\\Exception","type":"::","args"
:[{"__class__":"PDOException","errorInfo":["42P07",7,"ERROR:  relation \"user_id\" already exists"]}]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":1062,"function":"query"
,"class":"Doctrine\\DBAL\\Driver\\PDO\\Connection","type":"->","args":["CREATE UNIQUE INDEX user_id ON oc_profile_config (user_id)"]},{"file":"/var/www/html/lib/private/DB/Connection.php","line":236,
"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["CREATE UNIQUE INDEX user_id ON oc_profile_config (user_id)",[],[],null]},{"file":"/var/www/html/3rdparty/doctrine/d
bal/src/Connection.php","line":1809,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["CREATE UNIQUE INDEX user_id ON oc_profile_config (user_id)"]},{"file":"/var/www/html/li
b/private/DB/Migrator.php","line":175,"function":"query","class":"Doctrine\\DBAL\\Connection","type":"->","args":["CREATE UNIQUE INDEX user_id ON oc_profile_config (user_id)"]},{"file":"/var/www/html
/lib/private/DB/Migrator.php","line":76,"function":"applySchema","class":"OC\\DB\\Migrator","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Schema\\Schema"}]},{"file":"/var/www/html/lib/private/DB/
Connection.php","line":532,"function":"migrate","class":"OC\\DB\\Migrator","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Schema\\Schema"}]},{"file":"/var/www/html/lib/private/DB/MigrationService.
php","line":540,"function":"migrateToSchema","class":"OC\\DB\\Connection","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Schema\\Schema"}]},{"file":"/var/www/html/lib/private/DB/MigrationService.p
hp","line":425,"function":"executeStep","class":"OC\\DB\\MigrationService","type":"->","args":["23000Date20210930122352",false]},{"file":"/var/www/html/lib/private/Updater.php","line":315,"function":
"migrate","class":"OC\\DB\\MigrationService","type":"->","args":[]},{"file":"/var/www/html/lib/private/Updater.php","line":254,"function":"doCoreUpgrade","class":"OC\\Updater","type":"->","args":[]},
{"file":"/var/www/html/lib/private/Updater.php","line":133,"function":"doUpgrade","class":"OC\\Updater","type":"->","args":["23.0.0.10","22.2.3.0"]},{"file":"/var/www/html/core/Command/Upgrade.php","
line":235,"function":"upgrade","class":"OC\\Updater","type":"->","args":[]},{"file":"/var/www/html/3rdparty/symfony/console/Command/Command.php","line":255,"function":"execute","class":"OC\\Core\\Com
@@@
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
nothing interesting
```
</details>

### PR DESCRIPTION
**Pull request by zordsdavini**
Ref: https://github.com/nextcloud/server/issues/29986

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

File: core/Migrations/Version23000Date20210930122352.php [hunk 1]
```diff
@@ -60,7 +60,7 @@ public function changeSchema(IOutput $output, Closure $schemaClosure, array $opt
 				'notnull' => true,
 			]);
 			$table->setPrimaryKey(['id']);
-			$table->addUniqueIndex(['user_id'], 'user_id');
+			$table->addUniqueIndex(['user_id'], 'pc_user_id');
```
Comment (Pytal) [inline core/Migrations/Version23000Date20210930122352.php:63]:
```suggestion
			$table->addUniqueIndex(['user_id'], 'profile_config_user_id_idx');
```
Would suggest something more explicit :)

**Review by Pytal — CHANGES_REQUESTED** [review]

**Review by Pytal — APPROVED** [review]

**Comment by Pytal** [comment]
Thanks @zordsdavini!

Last thing we need is a signoff for your commits with:
```
git rebase HEAD~2 --signoff
git push --force-with-lease origin patch-1
```

**Comment by Pytal** [comment]
Thanks for the fix @zordsdavini!

We just need is a signoff for your commits with:
```
git rebase HEAD~2 --signoff
git push --force-with-lease origin patch-1
```

**Comment by Pytal** [comment]
Thanks for the fix @zordsdavini!

**Review by skjnldsv — APPROVED** [review]

**Comment by Pytal** [comment]
@skjnldsv @blizzz any idea on the drone failures?

**Comment by juliushaertl** [comment]
Restarted drone

**Review by blizzz — DISMISSED** [review]
missing a  repair step to rename the index on existing setup

**Comment by Pytal** [comment]
Fix now updates index name of original migration to fix new upgrades and adds a new migration for previously migrated setups to rename the existing index

File: core/Migrations/Version23000Date20211203110726.php [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+		if ($schema->hasTable(self::TABLE_NAME)) {
+			$table = $schema->getTable(self::TABLE_NAME);
+			if ($table->hasIndex('user_id')) {
+				$table->renameIndex('user_id', self::TABLE_NAME . '_user_id_idx');
+				return $schema;
+			}
+			return null;
+		}
+
+		return null;
```
Comment (skjnldsv) [inline core/Migrations/Version23000Date20211203110726.php:56]:
```suggestion
		$table = $schema->getTable(self::TABLE_NAME);
		if ($table->hasIndex('user_id')) {
			$table->renameIndex('user_id', self::TABLE_NAME . '_user_id_idx');
			return $schema;
		}
		return null;
```

**Review by skjnldsv — APPROVED** [review]
