### PR TITLE
Fix fail when keys/files folder already exists

### LINKED ISSUE #30564: Transfer ownership fails in move mode with encryption enabled
### Steps

1. Enable master key encryption
2. Login as admin
3. Upload some files
4. Create a new user "alice"
5. Login as "alice"
6. Delete all files in the web UI
7. Run: `occ files:transfer-ownership admin alice --move -vvv`

### Expected result
Transfer worked.

### Actual result
Transfer fails.
On some setups there's an error about `mkdir` failing for "files_encryption/keys/files" on the target but I don't have the log for it.

### Versions
Nextcloud 22.2.3

### Analysis
The bug appears because everything goes through a copy operation and the latter expects the target to not exist yet.
But when copying the keys, the target folder "files_encryption/keys/files/" already exists so it fails.

### PR DESCRIPTION
**Pull request by PVince81**
Fixes an issue with transfer ownership in move mode where the folder
"files_encryption/keys/files" already exists.

Instead of failing, its existence is checked before calling mkdir.

Fixes https://github.com/nextcloud/server/issues/30564

Note: normally the target folders don't exist yet when doing a copy over webdav because the webdav code (or higher layers) will first delete the target before starting the copy. With transfer ownership we operate on a different layer so this pre-deletion is not done but there's a check upfront that the target storage is empty.

### CODE REVIEW

**Review by julien-nc — APPROVED** [review]
:+1:

**Review by CarlSchwan — APPROVED** [review]

File: lib/private/Files/Storage/Wrapper/Encryption.php [hunk 1]
```diff
@@ -768,7 +768,11 @@ private function copyBetweenStorage(Storage\IStorage $sourceStorage, $sourceInte
 
 		if ($sourceStorage->is_dir($sourceInternalPath)) {
 			$dh = $sourceStorage->opendir($sourceInternalPath);
-			$result = $this->mkdir($targetInternalPath);
+			if (!$this->is_dir($targetInternalPath)) {
```
Comment (CarlSchwan) [inline lib/private/Files/Storage/Wrapper/Encryption.php:771]: If think you could also use a try { mkdir } to reduce the number of db query needed

Comment (PVince81) [reply lib/private/Files/Storage/Wrapper/Encryption.php:771]: this is the storage layer, so there are no DB queries involved

**Comment by PVince81** [comment]
JS failure unrelated, merging
