### PR TITLE
Fix mimetype update query

### LINKED ISSUE #4318: Some folders whose name matches with a filetype extensions gets the wrong mimetype
Some folders whose name matches with a filetype extensions gets the mimetype of that filetype (but the correct mimepart for a folder).
For example. A folder called TIFF gets a mimetype of 15 (image/tiff) but a mimepart of 1 (httpd). That happens only *sometimes*. I have not been able to find a difference in permissions or anything else.

### Steps to reproduce
1. Have a folder whose name matches with a filetype extension

### Expected behaviour
The folder is recognized as such.

### Actual behaviour
Sometimes the folder is misinterpreted as a file. Navigation within contents of the folder is therefore not possible.

### Server configuration

**Operating system**: CentOS

**Web server:** Apache

**Database:** mySQL 5.1.73

**PHP version:** 7.0.7

**Nextcloud version:** 11.0.2 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** manual installation with occ

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.

</details>

**List of activated apps:**
<details>
Enabled:

- activity: 2.4.1
- dav: 1.1.1
- federatedfilesharing: 1.1.1
- files: 1.6.1
- files_sharing: 1.1.1
- logreader: 2.0.0
- lookup_server_connector: 1.0.0
- provisioning_api: 1.1.0
- serverinfo: 1.1.1
- survey_client: 0.1.5
- twofactor_backupcodes: 1.0.0
- updatenotification: 1.1.1
- workflowengine: 1.1.1

Disabled:

- admin_audit
- comments
- encryption
- external
- federation
- files_accesscontrol
- files_automatedtagging
- files_external
- files_pdfviewer
- files_retention
- files_texteditor
- files_trashbin
- files_versions
- files_videoplayer
- firstrunwizard
- gallery
- nextcloud_announcements
- notifications
- password_policy
- sharebymail
- systemtags
- templateeditor
- theming
- user_external
- user_ldap
- user_saml

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

$CONFIG = array (
  'passwordsalt' => '***',
  'secret' => '***',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => '<server>',
  ),
  'datadirectory' => '/informacion_ambiental/descargas',
  'overwrite.cli.url' => 'http://<server>/repo',
  'htaccess.RewriteBase' => '/repo',
  'dbtype' => 'mysql',
  'version' => '11.0.2.7',
  'dbname' => '***',
  'dbhost' => 'localhost',
  'dbport' => '***',
  'dbtableprefix' => 'nc_',
  'dbuser' => '***',
  'dbpassword' => '***',
  'logtimezone' => 'UTC',
  'installed' => true,
  'enable_previews' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'default_language' => 'es',
  'theme' => 'custom',
  'instanceid' => '***',
  'loglevel' => 2,
);
</details>

**Are you using external storage, if yes which one:** nfs

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 52

**Operating system:** Windows 7

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"LkoWews\/DEklCLNvb0Iq","remoteAddr":"217.12.16.133","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\Lock\\\\LockedException\",\"Message\":\"\\\"files\\\/cd7ec8f11815f5c5e620270150c3af01\\\" is locked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(680): OC\\\\Lock\\\\DBLockingProvider->acquireLock('files\\\/cd7ec8f11...', 2)\\n#1 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(588): OC\\\\Files\\\\Storage\\\\Common->acquireLock('scanner::', 2, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#2 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(588): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('scanner::', 2, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(316): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('scanner::', 2, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#4 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/util.php(345): OC\\\\Files\\\\Cache\\\\Scanner->scan('', true)\\n#5 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Session.php(414): OC_Util::copySkeleton('publico', Object(OC\\\\Files\\\\Node\\\\Folder))\\n#6 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Session.php(479): OC\\\\User\\\\Session->prepareUserLogin(true)\\n#7 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Session.php(299): OC\\\\User\\\\Session->loginWithPassword(*** sensitive parameters replaced ***)\\n#8 \\\/var\\\/www\\\/html\\\/nextcloud\\\/core\\\/Controller\\\/LoginController.php(244): OC\\\\User\\\\Session->login(*** sensitive parameters replaced ***)\\n#9 [internal function]: OC\\\\Core\\\\Controller\\\\LoginController->tryLogin(*** sensitive parameters replaced ***)\\n#10 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#11 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#12 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#13 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Core\\\\\\\\Control...', 'tryLogin', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#14 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#15 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#16 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/login')\\n#17 \\\/var\\\/www\\\/html\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Lock\\\/DBLockingProvider.php\",\"Line\":187}","level":3,"time":"2017-04-10T14:33:45+00:00","method":"POST","url":"\/nextcloud\/index.php\/login","user":"publico","version":"11.0.2.7"}





{"reqId":"3q\/gj0lV33tLyyrDV\/Fw","remoteAddr":"217.12.16.133","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\UniqueConstraintViolationException\",\"Message\":\"An exception occurred while executing 'INSERT INTO `nc_file_locks` (`key`,`lock`,`ttl`) SELECT ?,?,? FROM `nc_file_locks` WHERE `key` = ? HAVING COUNT(*) = 0' with params [\\\"files\\\\\\\/30d2aaa81465a8cdaecd2f3c06604a07\\\", -1, 1491839046, \\\"files\\\\\\\/30d2aaa81465a8cdaecd2f3c06604a07\\\"]:\\n\\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'files\\\/30d2aaa81465a8cdaecd2f3c06604a07' for key 'lock_key_index'\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO `nc...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/DB\\\/Connection.php(215): Doctrine\\\\DBAL\\\\Connection->executeUpdate('INSERT INTO `nc...', Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/DB\\\/Adapter.php(114): OC\\\\DB\\\\Connection->executeUpdate('INSERT INTO `nc...', Array)\\n#4 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/DB\\\/Connection.php(253): OC\\\\DB\\\\Adapter->insertIfNotExist('*PREFIX*file_lo...', Array, Array)\\n#5 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Lock\\\/DBLockingProvider.php(118): OC\\\\DB\\\\Connection->insertIfNotExist('*PREFIX*file_lo...', Array, Array)\\n#6 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Lock\\\/DBLockingProvider.php(178): OC\\\\Lock\\\\DBLockingProvider->initLockField('files\\\/30d2aaa81...', -1)\\n#7 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(680): OC\\\\Lock\\\\DBLockingProvider->acquireLock('files\\\/30d2aaa81...', 2)\\n#8 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(588): OC\\\\Files\\\\Storage\\\\Common->acquireLock('scanner::appdat...', 2, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#9 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(588): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('scanner::appdat...', 2, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#10 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(316): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('scanner::appdat...', 2, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#11 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1301): OC\\\\Files\\\\Cache\\\\Scanner->scan('appdata_ocwxtca...', false)\\n#12 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1342): OC\\\\Files\\\\View->getCacheEntry(Object(OCA\\\\Files_Trashbin\\\\Storage), 'appdata_ocwxtca...', '\\\/appdata_ocwxtc...')\\n#13 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Root.php(196): OC\\\\Files\\\\View->getFileInfo('\\\/appdata_ocwxtc...')\\n#14 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Folder.php(122): OC\\\\Files\\\\Node\\\\Root->get('\\\/appdata_ocwxtc...')\\n#15 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/AppData\\\/AppData.php(89): OC\\\\Files\\\\Node\\\\Folder->get('theming')\\n#16 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/AppData\\\/AppData.php(105): OC\\\\Files\\\\AppData\\\\AppData->getAppDataFolder()\\n#17 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/theming\\\/lib\\\/ImageManager.php(62): OC\\\\Files\\\\AppData\\\\AppData->getFolder('0')\\n#18 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/theming\\\/lib\\\/ImageManager.php(78): OCA\\\\Theming\\\\ImageManager->getCacheFolder()\\n#19 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/theming\\\/lib\\\/Controller\\\/IconController.php(94): OCA\\\\Theming\\\\ImageManager->getCachedImage('icon-core-filet...')\\n#20 [internal function]: OCA\\\\Theming\\\\Controller\\\\IconController->getThemedIcon('core', 'filetypes\\\/appli...')\\n#21 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#22 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Theming\\\\Controller\\\\IconController), 'getThemedIcon')\\n#23 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Theming\\\\Controller\\\\IconController), 'getThemedIcon')\\n#24 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Theming\\\\\\\\Con...', 'getThemedIcon', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#25 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#26 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#27 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/apps\\\/theming\\\/i...')\\n#28 \\\/var\\\/www\\\/html\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#29 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":66}","level":3,"time":"2017-04-10T14:44:07+00:00","method":"GET","url":"\/nextcloud\/index.php\/apps\/theming\/img\/core\/filetypes\/application-pdf.svg?v=0","user":"adminrediam","version":"11.0.2.7"}


































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































{"reqId":"DHr3DbOLJLx4WSC\/hm46","remoteAddr":"217.12.16.133","app":"PHP","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes) at \/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#104","level":3,"time":"2017-04-11T11:54:34+00:00","method":"DELETE","url":"\/nextcloud\/remote.php\/webdav\/Photos","user":"publico","version":"11.0.2.7"}
{"reqId":"iNvfB6dqDQfcYNSzMkj+","remoteAddr":"217.12.16.133","app":"PHP","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes) at \/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#104","level":3,"time":"2017-04-11T11:57:38+00:00","method":"DELETE","url":"\/nextcloud\/remote.php\/webdav\/Photos","user":"publico","version":"11.0.2.7"}



{"reqId":"Y22WO1FFKoBplDL8WMuW","remoteAddr":"5.226.22.166","app":"PHP","message":"Uncaught Error: Access to undeclared static property: OC\\Files\\Filesystem::$normalizedPathCache in \/var\/www\/html\/repo\/lib\/private\/Files\/Filesystem.php:806\nStack trace:\n#0 \/var\/www\/html\/repo\/lib\/private\/Files\/View.php(2018): OC\\Files\\Filesystem::normalizePath('\/publico\/files\/...')\n#1 \/var\/www\/html\/repo\/lib\/private\/Files\/View.php(1156): OC\\Files\\View->unlockFile('\/RUR\/01_CARACTE...', 1)\n#2 [internal function]: OC\\Files\\View->OC\\Files\\{closure}()\n#3 \/var\/www\/html\/repo\/3rdparty\/icewind\/streams\/src\/CallbackWrapper.php(109): call_user_func(Object(Closure))\n#4 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_close()\n#5 {main}\n  thrown at \/var\/www\/html\/repo\/lib\/private\/Files\/Filesystem.php#806","level":3,"time":"2017-04-11T13:56:47+00:00","method":"GET","url":"\/repo\/s\/RUR\/download?path=%2F01_CARACTERIZACION_TERRITORIO%2F06_USOS_COBERTURAS%2F02_MUCVA_25000%2FMUCVA25_1999%2FInfGeografica%2FInfVectorial%2FETRS89_30%2FShapes&files=%5B%22MUCVA25_1999_EscalaDetalle.prj%22%2C%22MUCVA25_1999_EscalaDetalle.qix%22%2C%22MUCVA25_1999_EscalaDetalle.shx%22%2C%22MUCVA25_1999_EscalaDetalle.sbx%22%2C%22MUCVA25_1999_EscalaDetalle.sbn%22%2C%22MUCVA25_1999_EscalaDetalle.shp%22%5D&downloadStartSecret=yy0u9e7xgei","user":"--","version":"11.0.2.7"}
{"reqId":"vLet4xWomETzB\/1HgfS\/","remoteAddr":"5.226.22.166","app":"PHP","message":"Uncaught Error: Access to undeclared static property: OC\\Files\\Filesystem::$normalizedPathCache in \/var\/www\/html\/repo\/lib\/private\/Files\/Filesystem.php:806\nStack trace:\n#0 \/var\/www\/html\/repo\/lib\/private\/Files\/View.php(2018): OC\\Files\\Filesystem::normalizePath('\/publico\/files\/...')\n#1 \/var\/www\/html\/repo\/lib\/private\/Files\/View.php(1156): OC\\Files\\View->unlockFile('\/RUR\/01_CARACTE...', 1)\n#2 [internal function]: OC\\Files\\View->OC\\Files\\{closure}()\n#3 \/var\/www\/html\/repo\/3rdparty\/icewind\/streams\/src\/CallbackWrapper.php(109): call_user_func(Object(Closure))\n#4 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_close()\n#5 {main}\n  thrown at \/var\/www\/html\/repo\/lib\/private\/Files\/Filesystem.php#806","level":3,"time":"2017-04-11T13:58:37+00:00","method":"PROPFIND","url":"\/repo\/public.php\/webdav\/","user":"--","version":"11.0.2.7"}
{"reqId":"QlYCyY9WxFbCIwrwFzhX","remoteAddr":"5.226.22.166","app":"index","message":"Exception: {\"Exception\":\"TypeError\",\"Message\":\"Argument 3 passed to OCA\\\\Files\\\\Service\\\\TagService::__construct() must be an instance of OCP\\\\ITags, null given, called in \\\/var\\\/www\\\/html\\\/repo\\\/apps\\\/files\\\/lib\\\/AppInfo\\\/Application.php on line 88\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/repo\\\/apps\\\/files\\\/lib\\\/AppInfo\\\/Application.php(88): OCA\\\\Files\\\\Service\\\\TagService->__construct(Object(OC\\\\User\\\\Session), Object(OC\\\\Activity\\\\Manager), NULL, NULL)\\n#1 \\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OCA\\\\Files\\\\AppInfo\\\\Application->OCA\\\\Files\\\\AppInfo\\\\{closure}(Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#2 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(115): Pimple\\\\Container->offsetGet('TagService')\\n#3 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/DependencyInjection\\\/DIContainer.php(544): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('TagService')\\n#4 \\\/var\\\/www\\\/html\\\/repo\\\/apps\\\/files\\\/lib\\\/AppInfo\\\/Application.php(47): OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer->query('TagService')\\n#5 \\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OCA\\\\Files\\\\AppInfo\\\\Application->OCA\\\\Files\\\\AppInfo\\\\{closure}(Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#6 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(115): Pimple\\\\Container->offsetGet('APIController')\\n#7 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/DependencyInjection\\\/DIContainer.php(544): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('APIController')\\n#8 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/App.php(91): OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer->query('APIController')\\n#9 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('APIController', 'updateFileSorti...', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#12 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/api...')\\n#13 \\\/var\\\/www\\\/html\\\/repo\\\/index.php(40): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/repo\\\/apps\\\/files\\\/lib\\\/Service\\\/TagService.php\",\"Line\":56}","level":3,"time":"2017-04-11T14:12:29+00:00","method":"POST","url":"\/repo\/apps\/files\/api\/v1\/sorting","user":"--","version":"11.0.2.7"}
{"reqId":"j3OPERaaMgEyBmKv1Flk","remoteAddr":"5.226.22.166","app":"index","message":"Exception: {\"Exception\":\"TypeError\",\"Message\":\"Argument 3 passed to OCA\\\\Files\\\\Service\\\\TagService::__construct() must be an instance of OCP\\\\ITags, null given, called in \\\/var\\\/www\\\/html\\\/repo\\\/apps\\\/files\\\/lib\\\/AppInfo\\\/Application.php on line 88\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/repo\\\/apps\\\/files\\\/lib\\\/AppInfo\\\/Application.php(88): OCA\\\\Files\\\\Service\\\\TagService->__construct(Object(OC\\\\User\\\\Session), Object(OC\\\\Activity\\\\Manager), NULL, NULL)\\n#1 \\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OCA\\\\Files\\\\AppInfo\\\\Application->OCA\\\\Files\\\\AppInfo\\\\{closure}(Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#2 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(115): Pimple\\\\Container->offsetGet('TagService')\\n#3 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/DependencyInjection\\\/DIContainer.php(544): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('TagService')\\n#4 \\\/var\\\/www\\\/html\\\/repo\\\/apps\\\/files\\\/lib\\\/AppInfo\\\/Application.php(47): OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer->query('TagService')\\n#5 \\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OCA\\\\Files\\\\AppInfo\\\\Application->OCA\\\\Files\\\\AppInfo\\\\{closure}(Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#6 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(115): Pimple\\\\Container->offsetGet('APIController')\\n#7 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/DependencyInjection\\\/DIContainer.php(544): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('APIController')\\n#8 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/App.php(91): OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer->query('APIController')\\n#9 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('APIController', 'updateFileSorti...', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#12 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/api...')\\n#13 \\\/var\\\/www\\\/html\\\/repo\\\/index.php(40): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/repo\\\/apps\\\/files\\\/lib\\\/Service\\\/TagService.php\",\"Line\":56}","level":3,"time":"2017-04-11T14:12:30+00:00","method":"POST","url":"\/repo\/apps\/files\/api\/v1\/sorting","user":"--","version":"11.0.2.7"}
{"reqId":"vLmoxSTk4\/0ajyzTv4fP","remoteAddr":"5.226.22.166","app":"index","message":"Exception: {\"Exception\":\"TypeError\",\"Message\":\"Argument 3 passed to OCA\\\\Files\\\\Service\\\\TagService::__construct() must be an instance of OCP\\\\ITags, null given, called in \\\/var\\\/www\\\/html\\\/repo\\\/apps\\\/files\\\/lib\\\/AppInfo\\\/Application.php on line 88\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/repo\\\/apps\\\/files\\\/lib\\\/AppInfo\\\/Application.php(88): OCA\\\\Files\\\\Service\\\\TagService->__construct(Object(OC\\\\User\\\\Session), Object(OC\\\\Activity\\\\Manager), NULL, NULL)\\n#1 \\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OCA\\\\Files\\\\AppInfo\\\\Application->OCA\\\\Files\\\\AppInfo\\\\{closure}(Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#2 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(115): Pimple\\\\Container->offsetGet('TagService')\\n#3 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/DependencyInjection\\\/DIContainer.php(544): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('TagService')\\n#4 \\\/var\\\/www\\\/html\\\/repo\\\/apps\\\/files\\\/lib\\\/AppInfo\\\/Application.php(47): OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer->query('TagService')\\n#5 \\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OCA\\\\Files\\\\AppInfo\\\\Application->OCA\\\\Files\\\\AppInfo\\\\{closure}(Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#6 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(115): Pimple\\\\Container->offsetGet('APIController')\\n#7 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/DependencyInjection\\\/DIContainer.php(544): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('APIController')\\n#8 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/App.php(91): OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer->query('APIController')\\n#9 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('APIController', 'updateFileSorti...', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#12 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/api...')\\n#13 \\\/var\\\/www\\\/html\\\/repo\\\/index.php(40): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/repo\\\/apps\\\/files\\\/lib\\\/Service\\\/TagService.php\",\"Line\":56}","level":3,"time":"2017-04-11T14:20:38+00:00","method":"POST","url":"\/repo\/apps\/files\/api\/v1\/sorting","user":"--","version":"11.0.2.7"}
{"reqId":"pJzIIIzYv5IJMW53gLTy","remoteAddr":"5.226.22.166","app":"index","message":"Exception: {\"Exception\":\"TypeError\",\"Message\":\"Argument 3 passed to OCA\\\\Files\\\\Service\\\\TagService::__construct() must be an instance of OCP\\\\ITags, null given, called in \\\/var\\\/www\\\/html\\\/repo\\\/apps\\\/files\\\/lib\\\/AppInfo\\\/Application.php on line 88\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/repo\\\/apps\\\/files\\\/lib\\\/AppInfo\\\/Application.php(88): OCA\\\\Files\\\\Service\\\\TagService->__construct(Object(OC\\\\User\\\\Session), Object(OC\\\\Activity\\\\Manager), NULL, NULL)\\n#1 \\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OCA\\\\Files\\\\AppInfo\\\\Application->OCA\\\\Files\\\\AppInfo\\\\{closure}(Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#2 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(115): Pimple\\\\Container->offsetGet('TagService')\\n#3 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/DependencyInjection\\\/DIContainer.php(544): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('TagService')\\n#4 \\\/var\\\/www\\\/html\\\/repo\\\/apps\\\/files\\\/lib\\\/AppInfo\\\/Application.php(47): OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer->query('TagService')\\n#5 \\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OCA\\\\Files\\\\AppInfo\\\\Application->OCA\\\\Files\\\\AppInfo\\\\{closure}(Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#6 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(115): Pimple\\\\Container->offsetGet('APIController')\\n#7 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/DependencyInjection\\\/DIContainer.php(544): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('APIController')\\n#8 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/App.php(91): OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer->query('APIController')\\n#9 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('APIController', 'updateFileSorti...', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#12 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/api...')\\n#13 \\\/var\\\/www\\\/html\\\/repo\\\/index.php(40): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/repo\\\/apps\\\/files\\\/lib\\\/Service\\\/TagService.php\",\"Line\":56}","level":3,"time":"2017-04-11T14:21:03+00:00","method":"POST","url":"\/repo\/apps\/files\/api\/v1\/sorting","user":"--","version":"11.0.2.7"}
{"reqId":"aBdpOUOOqbsfZUH+uW4Q","remoteAddr":"5.226.22.166","app":"index","message":"Exception: {\"Exception\":\"TypeError\",\"Message\":\"Argument 3 passed to OCA\\\\Files\\\\Service\\\\TagService::__construct() must be an instance of OCP\\\\ITags, null given, called in \\\/var\\\/www\\\/html\\\/repo\\\/apps\\\/files\\\/lib\\\/AppInfo\\\/Application.php on line 88\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/repo\\\/apps\\\/files\\\/lib\\\/AppInfo\\\/Application.php(88): OCA\\\\Files\\\\Service\\\\TagService->__construct(Object(OC\\\\User\\\\Session), Object(OC\\\\Activity\\\\Manager), NULL, NULL)\\n#1 \\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OCA\\\\Files\\\\AppInfo\\\\Application->OCA\\\\Files\\\\AppInfo\\\\{closure}(Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#2 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(115): Pimple\\\\Container->offsetGet('TagService')\\n#3 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/DependencyInjection\\\/DIContainer.php(544): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('TagService')\\n#4 \\\/var\\\/www\\\/html\\\/repo\\\/apps\\\/files\\\/lib\\\/AppInfo\\\/Application.php(47): OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer->query('TagService')\\n#5 \\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OCA\\\\Files\\\\AppInfo\\\\Application->OCA\\\\Files\\\\AppInfo\\\\{closure}(Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#6 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(115): Pimple\\\\Container->offsetGet('APIController')\\n#7 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/DependencyInjection\\\/DIContainer.php(544): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('APIController')\\n#8 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/App.php(91): OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer->query('APIController')\\n#9 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('APIController', 'updateFileSorti...', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#12 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/api...')\\n#13 \\\/var\\\/www\\\/html\\\/repo\\\/index.php(40): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/repo\\\/apps\\\/files\\\/lib\\\/Service\\\/TagService.php\",\"Line\":56}","level":3,"time":"2017-04-11T14:21:06+00:00","method":"POST","url":"\/repo\/apps\/files\/api\/v1\/sorting","user":"--","version":"11.0.2.7"}
















































































































































































































































































































{"reqId":"5jTlcAQJTi0GIQcPhLI\/","remoteAddr":"5.226.22.166","app":"no app in context","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'UPDATE `nc_file_locks` SET `lock` = `lock` + 1, `ttl` = ? WHERE `key` = ? AND `lock` >= 0' with params [1491972247, \\\"files\\\\\\\/8ab969ab38e5377d5e670993d1af6c7d\\\"]:\\n\\nSQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE `nc_file...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/DB\\\/Connection.php(215): Doctrine\\\\DBAL\\\\Connection->executeUpdate('UPDATE `nc_file...', Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Lock\\\/DBLockingProvider.php(167): OC\\\\DB\\\\Connection->executeUpdate('UPDATE `nc_file...', Array)\\n#4 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(680): OC\\\\Lock\\\\DBLockingProvider->acquireLock('files\\\/8ab969ab3...', 1)\\n#5 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(588): OC\\\\Files\\\\Storage\\\\Common->acquireLock('files\\\/RUR', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#6 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/View.php(1894): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/RUR', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#7 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/View.php(2001): OC\\\\Files\\\\View->lockPath('\\\/RUR', 1)\\n#8 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/legacy\\\/files.php(321): OC\\\\Files\\\\View->lockFile('\\\/RUR\\\/04_RECURSO...', 1)\\n#9 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/legacy\\\/files.php(146): OC_Files::lockFiles(Object(OC\\\\Files\\\\View), '\\\/RUR\\\/04_RECURSO...', Array)\\n#10 \\\/var\\\/www\\\/html\\\/repo\\\/apps\\\/files_sharing\\\/lib\\\/Controller\\\/ShareController.php(529): OC_Files::get('\\\/RUR\\\/04_RECURSO...', 'Shapes', Array)\\n#11 [internal function]: OCA\\\\Files_Sharing\\\\Controller\\\\ShareController->downloadShare('RUR', 'Shapes', '\\\/04_RECURSOS_NA...', 'fuc7xo61kn5')\\n#12 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#13 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'downloadShare')\\n#14 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'downloadShare')\\n#15 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/public\\\/AppFramework\\\/App.php(136): OC\\\\AppFramework\\\\App::main('ShareController', 'downloadShare', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#16 \\\/var\\\/www\\\/html\\\/repo\\\/core\\\/routes.php(99): OCP\\\\AppFramework\\\\App->dispatch('ShareController', 'downloadShare')\\n#17 [internal function]: OC\\\\Route\\\\Router->{closure}(Array)\\n#18 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(Closure), Array)\\n#19 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/s\\\/RUR\\\/download')\\n#20 \\\/var\\\/www\\\/html\\\/repo\\\/index.php(40): OC::handleRequest()\\n#21 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":116}","level":3,"time":"2017-04-12T03:44:59+00:00","method":"GET","url":"\/repo\/s\/RUR\/download?path=%2F04_RECURSOS_NATURALES%2F01_BIODIVERSIDAD%2F00_BIODIVERSIDAD%2FMapa_biodiversidad%2FInfGeografica%2FInfVectorial&files=Shapes&downloadStartSecret=fuc7xo61kn5","user":"--","version":"11.0.2.7"}
{"reqId":"J+0N3u1CCncT\/RE5kDXQ","remoteAddr":"5.226.22.166","app":"no app in context","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'UPDATE `nc_file_locks` SET `lock` = `lock` + 1, `ttl` = ? WHERE `key` = ? AND `lock` >= 0' with params [1491972311, \\\"files\\\\\\\/8ab969ab38e5377d5e670993d1af6c7d\\\"]:\\n\\nSQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE `nc_file...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/DB\\\/Connection.php(215): Doctrine\\\\DBAL\\\\Connection->executeUpdate('UPDATE `nc_file...', Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Lock\\\/DBLockingProvider.php(167): OC\\\\DB\\\\Connection->executeUpdate('UPDATE `nc_file...', Array)\\n#4 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(680): OC\\\\Lock\\\\DBLockingProvider->acquireLock('files\\\/8ab969ab3...', 1)\\n#5 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(588): OC\\\\Files\\\\Storage\\\\Common->acquireLock('files\\\/RUR', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#6 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/View.php(1894): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/RUR', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#7 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/View.php(2001): OC\\\\Files\\\\View->lockPath('\\\/RUR', 1)\\n#8 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/legacy\\\/files.php(321): OC\\\\Files\\\\View->lockFile('\\\/RUR\\\/04_RECURSO...', 1)\\n#9 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/legacy\\\/files.php(146): OC_Files::lockFiles(Object(OC\\\\Files\\\\View), '\\\/RUR\\\/04_RECURSO...', Array)\\n#10 \\\/var\\\/www\\\/html\\\/repo\\\/apps\\\/files_sharing\\\/lib\\\/Controller\\\/ShareController.php(529): OC_Files::get('\\\/RUR\\\/04_RECURSO...', 'Shapes', Array)\\n#11 [internal function]: OCA\\\\Files_Sharing\\\\Controller\\\\ShareController->downloadShare('RUR', 'Shapes', '\\\/04_RECURSOS_NA...', 'vez3hvhvtj')\\n#12 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#13 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'downloadShare')\\n#14 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'downloadShare')\\n#15 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/public\\\/AppFramework\\\/App.php(136): OC\\\\AppFramework\\\\App::main('ShareController', 'downloadShare', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#16 \\\/var\\\/www\\\/html\\\/repo\\\/core\\\/routes.php(99): OCP\\\\AppFramework\\\\App->dispatch('ShareController', 'downloadShare')\\n#17 [internal function]: OC\\\\Route\\\\Router->{closure}(Array)\\n#18 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(Closure), Array)\\n#19 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/s\\\/RUR\\\/download')\\n#20 \\\/var\\\/www\\\/html\\\/repo\\\/index.php(40): OC::handleRequest()\\n#21 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":116}","level":3,"time":"2017-04-12T03:46:02+00:00","method":"GET","url":"\/repo\/s\/RUR\/download?path=%2F04_RECURSOS_NATURALES%2F01_BIODIVERSIDAD%2F00_BIODIVERSIDAD%2FMapa_biodiversidad%2FInfGeografica%2FInfVectorial&files=Shapes&downloadStartSecret=vez3hvhvtj","user":"--","version":"11.0.2.7"}
{"reqId":"4IqEuqJlaW3ZWSHk85Kz","remoteAddr":"5.226.22.166","app":"no app in context","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'UPDATE `nc_file_locks` SET `lock` = `lock` + 1, `ttl` = ? WHERE `key` = ? AND `lock` >= 0' with params [1491972333, \\\"files\\\\\\\/8ab969ab38e5377d5e670993d1af6c7d\\\"]:\\n\\nSQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE `nc_file...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/DB\\\/Connection.php(215): Doctrine\\\\DBAL\\\\Connection->executeUpdate('UPDATE `nc_file...', Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Lock\\\/DBLockingProvider.php(167): OC\\\\DB\\\\Connection->executeUpdate('UPDATE `nc_file...', Array)\\n#4 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(680): OC\\\\Lock\\\\DBLockingProvider->acquireLock('files\\\/8ab969ab3...', 1)\\n#5 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(588): OC\\\\Files\\\\Storage\\\\Common->acquireLock('files\\\/RUR', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#6 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/View.php(1894): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/RUR', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#7 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/View.php(2001): OC\\\\Files\\\\View->lockPath('\\\/RUR', 1)\\n#8 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/legacy\\\/files.php(321): OC\\\\Files\\\\View->lockFile('\\\/RUR\\\/04_RECURSO...', 1)\\n#9 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/legacy\\\/files.php(146): OC_Files::lockFiles(Object(OC\\\\Files\\\\View), '\\\/RUR\\\/04_RECURSO...', Array)\\n#10 \\\/var\\\/www\\\/html\\\/repo\\\/apps\\\/files_sharing\\\/lib\\\/Controller\\\/ShareController.php(529): OC_Files::get('\\\/RUR\\\/04_RECURSO...', 'InfVectorial', Array)\\n#11 [internal function]: OCA\\\\Files_Sharing\\\\Controller\\\\ShareController->downloadShare('RUR', 'InfVectorial', '\\\/04_RECURSOS_NA...', 'fe2odvlk7zn')\\n#12 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#13 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'downloadShare')\\n#14 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'downloadShare')\\n#15 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/public\\\/AppFramework\\\/App.php(136): OC\\\\AppFramework\\\\App::main('ShareController', 'downloadShare', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#16 \\\/var\\\/www\\\/html\\\/repo\\\/core\\\/routes.php(99): OCP\\\\AppFramework\\\\App->dispatch('ShareController', 'downloadShare')\\n#17 [internal function]: OC\\\\Route\\\\Router->{closure}(Array)\\n#18 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(Closure), Array)\\n#19 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/s\\\/RUR\\\/download')\\n#20 \\\/var\\\/www\\\/html\\\/repo\\\/index.php(40): OC::handleRequest()\\n#21 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":116}","level":3,"time":"2017-04-12T03:46:24+00:00","method":"GET","url":"\/repo\/s\/RUR\/download?path=%2F04_RECURSOS_NATURALES%2F01_BIODIVERSIDAD%2F00_BIODIVERSIDAD%2FMapa_biodiversidad%2FInfGeografica&files=InfVectorial&downloadStartSecret=fe2odvlk7zn","user":"--","version":"11.0.2.7"}
{"reqId":"C709YSNRU5ynX8opf1+Y","remoteAddr":"5.226.22.166","app":"no app in context","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'UPDATE `nc_file_locks` SET `lock` = `lock` + 1, `ttl` = ? WHERE `key` = ? AND `lock` >= 0' with params [1491972336, \\\"files\\\\\\\/8ab969ab38e5377d5e670993d1af6c7d\\\"]:\\n\\nSQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE `nc_file...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/DB\\\/Connection.php(215): Doctrine\\\\DBAL\\\\Connection->executeUpdate('UPDATE `nc_file...', Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Lock\\\/DBLockingProvider.php(167): OC\\\\DB\\\\Connection->executeUpdate('UPDATE `nc_file...', Array)\\n#4 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(680): OC\\\\Lock\\\\DBLockingProvider->acquireLock('files\\\/8ab969ab3...', 1)\\n#5 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(588): OC\\\\Files\\\\Storage\\\\Common->acquireLock('files\\\/RUR', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#6 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/View.php(1894): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/RUR', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#7 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/View.php(2001): OC\\\\Files\\\\View->lockPath('\\\/RUR', 1)\\n#8 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/legacy\\\/files.php(321): OC\\\\Files\\\\View->lockFile('\\\/RUR\\\/04_RECURSO...', 1)\\n#9 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/legacy\\\/files.php(146): OC_Files::lockFiles(Object(OC\\\\Files\\\\View), '\\\/RUR\\\/04_RECURSO...', Array)\\n#10 \\\/var\\\/www\\\/html\\\/repo\\\/apps\\\/files_sharing\\\/lib\\\/Controller\\\/ShareController.php(529): OC_Files::get('\\\/RUR\\\/04_RECURSO...', 'InfVectorial', Array)\\n#11 [internal function]: OCA\\\\Files_Sharing\\\\Controller\\\\ShareController->downloadShare('RUR', 'InfVectorial', '\\\/04_RECURSOS_NA...', 'eci2kupp8t')\\n#12 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#13 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'downloadShare')\\n#14 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'downloadShare')\\n#15 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/public\\\/AppFramework\\\/App.php(136): OC\\\\AppFramework\\\\App::main('ShareController', 'downloadShare', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#16 \\\/var\\\/www\\\/html\\\/repo\\\/core\\\/routes.php(99): OCP\\\\AppFramework\\\\App->dispatch('ShareController', 'downloadShare')\\n#17 [internal function]: OC\\\\Route\\\\Router->{closure}(Array)\\n#18 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(Closure), Array)\\n#19 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/s\\\/RUR\\\/download')\\n#20 \\\/var\\\/www\\\/html\\\/repo\\\/index.php(40): OC::handleRequest()\\n#21 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":116}","level":3,"time":"2017-04-12T03:46:27+00:00","method":"GET","url":"\/repo\/s\/RUR\/download?path=%2F04_RECURSOS_NATURALES%2F01_BIODIVERSIDAD%2F00_BIODIVERSIDAD%2FMapa_biodiversidad%2FInfGeografica&files=InfVectorial&downloadStartSecret=eci2kupp8t","user":"--","version":"11.0.2.7"}
{"reqId":"ISRlkHc6DFRz7Yzk1D45","remoteAddr":"5.226.22.166","app":"no app in context","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'UPDATE `nc_file_locks` SET `lock` = `lock` + 1, `ttl` = ? WHERE `key` = ? AND `lock` >= 0' with params [1491972336, \\\"files\\\\\\\/8ab969ab38e5377d5e670993d1af6c7d\\\"]:\\n\\nSQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE `nc_file...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/DB\\\/Connection.php(215): Doctrine\\\\DBAL\\\\Connection->executeUpdate('UPDATE `nc_file...', Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Lock\\\/DBLockingProvider.php(167): OC\\\\DB\\\\Connection->executeUpdate('UPDATE `nc_file...', Array)\\n#4 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(680): OC\\\\Lock\\\\DBLockingProvider->acquireLock('files\\\/8ab969ab3...', 1)\\n#5 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(588): OC\\\\Files\\\\Storage\\\\Common->acquireLock('files\\\/RUR', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#6 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/View.php(1894): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/RUR', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#7 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/View.php(2001): OC\\\\Files\\\\View->lockPath('\\\/RUR', 1)\\n#8 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/legacy\\\/files.php(321): OC\\\\Files\\\\View->lockFile('\\\/RUR\\\/04_RECURSO...', 1)\\n#9 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/legacy\\\/files.php(146): OC_Files::lockFiles(Object(OC\\\\Files\\\\View), '\\\/RUR\\\/04_RECURSO...', Array)\\n#10 \\\/var\\\/www\\\/html\\\/repo\\\/apps\\\/files_sharing\\\/lib\\\/Controller\\\/ShareController.php(529): OC_Files::get('\\\/RUR\\\/04_RECURSO...', 'InfVectorial', Array)\\n#11 [internal function]: OCA\\\\Files_Sharing\\\\Controller\\\\ShareController->downloadShare('RUR', 'InfVectorial', '\\\/04_RECURSOS_NA...', 'ep42e61hinl')\\n#12 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#13 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'downloadShare')\\n#14 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'downloadShare')\\n#15 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/public\\\/AppFramework\\\/App.php(136): OC\\\\AppFramework\\\\App::main('ShareController', 'downloadShare', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#16 \\\/var\\\/www\\\/html\\\/repo\\\/core\\\/routes.php(99): OCP\\\\AppFramework\\\\App->dispatch('ShareController', 'downloadShare')\\n#17 [internal function]: OC\\\\Route\\\\Router->{closure}(Array)\\n#18 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(Closure), Array)\\n#19 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/s\\\/RUR\\\/download')\\n#20 \\\/var\\\/www\\\/html\\\/repo\\\/index.php(40): OC::handleRequest()\\n#21 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":116}","level":3,"time":"2017-04-12T03:46:27+00:00","method":"GET","url":"\/repo\/s\/RUR\/download?path=%2F04_RECURSOS_NATURALES%2F01_BIODIVERSIDAD%2F00_BIODIVERSIDAD%2FMapa_biodiversidad%2FInfGeografica&files=InfVectorial&downloadStartSecret=ep42e61hinl","user":"--","version":"11.0.2.7"}
{"reqId":"lWnz8Fpe3RpDMgQv1In+","remoteAddr":"5.226.22.166","app":"no app in context","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'UPDATE `nc_file_locks` SET `lock` = `lock` + 1, `ttl` = ? WHERE `key` = ? AND `lock` >= 0' with params [1491972336, \\\"files\\\\\\\/8ab969ab38e5377d5e670993d1af6c7d\\\"]:\\n\\nSQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE `nc_file...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/DB\\\/Connection.php(215): Doctrine\\\\DBAL\\\\Connection->executeUpdate('UPDATE `nc_file...', Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Lock\\\/DBLockingProvider.php(167): OC\\\\DB\\\\Connection->executeUpdate('UPDATE `nc_file...', Array)\\n#4 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(680): OC\\\\Lock\\\\DBLockingProvider->acquireLock('files\\\/8ab969ab3...', 1)\\n#5 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(588): OC\\\\Files\\\\Storage\\\\Common->acquireLock('files\\\/RUR', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#6 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/View.php(1894): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/RUR', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#7 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/View.php(2001): OC\\\\Files\\\\View->lockPath('\\\/RUR', 1)\\n#8 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/legacy\\\/files.php(321): OC\\\\Files\\\\View->lockFile('\\\/RUR\\\/04_RECURSO...', 1)\\n#9 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/legacy\\\/files.php(146): OC_Files::lockFiles(Object(OC\\\\Files\\\\View), '\\\/RUR\\\/04_RECURSO...', Array)\\n#10 \\\/var\\\/www\\\/html\\\/repo\\\/apps\\\/files_sharing\\\/lib\\\/Controller\\\/ShareController.php(529): OC_Files::get('\\\/RUR\\\/04_RECURSO...', 'InfVectorial', Array)\\n#11 [internal function]: OCA\\\\Files_Sharing\\\\Controller\\\\ShareController->downloadShare('RUR', 'InfVectorial', '\\\/04_RECURSOS_NA...', 'xv92967w5zn')\\n#12 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#13 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'downloadShare')\\n#14 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'downloadShare')\\n#15 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/public\\\/AppFramework\\\/App.php(136): OC\\\\AppFramework\\\\App::main('ShareController', 'downloadShare', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#16 \\\/var\\\/www\\\/html\\\/repo\\\/core\\\/routes.php(99): OCP\\\\AppFramework\\\\App->dispatch('ShareController', 'downloadShare')\\n#17 [internal function]: OC\\\\Route\\\\Router->{closure}(Array)\\n#18 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(Closure), Array)\\n#19 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/s\\\/RUR\\\/download')\\n#20 \\\/var\\\/www\\\/html\\\/repo\\\/index.php(40): OC::handleRequest()\\n#21 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":116}","level":3,"time":"2017-04-12T03:46:27+00:00","method":"GET","url":"\/repo\/s\/RUR\/download?path=%2F04_RECURSOS_NATURALES%2F01_BIODIVERSIDAD%2F00_BIODIVERSIDAD%2FMapa_biodiversidad%2FInfGeografica&files=InfVectorial&downloadStartSecret=xv92967w5zn","user":"--","version":"11.0.2.7"}
{"reqId":"aTUyWap0HCNWOyzIWkhN","remoteAddr":"5.226.22.166","app":"no app in context","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'UPDATE `nc_file_locks` SET `lock` = `lock` + 1, `ttl` = ? WHERE `key` = ? AND `lock` >= 0' with params [1491972336, \\\"files\\\\\\\/8ab969ab38e5377d5e670993d1af6c7d\\\"]:\\n\\nSQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE `nc_file...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/DB\\\/Connection.php(215): Doctrine\\\\DBAL\\\\Connection->executeUpdate('UPDATE `nc_file...', Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Lock\\\/DBLockingProvider.php(167): OC\\\\DB\\\\Connection->executeUpdate('UPDATE `nc_file...', Array)\\n#4 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(680): OC\\\\Lock\\\\DBLockingProvider->acquireLock('files\\\/8ab969ab3...', 1)\\n#5 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(588): OC\\\\Files\\\\Storage\\\\Common->acquireLock('files\\\/RUR', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#6 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/View.php(1894): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/RUR', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#7 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/View.php(2001): OC\\\\Files\\\\View->lockPath('\\\/RUR', 1)\\n#8 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/legacy\\\/files.php(321): OC\\\\Files\\\\View->lockFile('\\\/RUR\\\/04_RECURSO...', 1)\\n#9 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/legacy\\\/files.php(146): OC_Files::lockFiles(Object(OC\\\\Files\\\\View), '\\\/RUR\\\/04_RECURSO...', Array)\\n#10 \\\/var\\\/www\\\/html\\\/repo\\\/apps\\\/files_sharing\\\/lib\\\/Controller\\\/ShareController.php(529): OC_Files::get('\\\/RUR\\\/04_RECURSO...', 'InfVectorial', Array)\\n#11 [internal function]: OCA\\\\Files_Sharing\\\\Controller\\\\ShareController->downloadShare('RUR', 'InfVectorial', '\\\/04_RECURSOS_NA...', 'q05aqvjhyuc')\\n#12 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#13 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'downloadShare')\\n#14 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'downloadShare')\\n#15 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/public\\\/AppFramework\\\/App.php(136): OC\\\\AppFramework\\\\App::main('ShareController', 'downloadShare', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#16 \\\/var\\\/www\\\/html\\\/repo\\\/core\\\/routes.php(99): OCP\\\\AppFramework\\\\App->dispatch('ShareController', 'downloadShare')\\n#17 [internal function]: OC\\\\Route\\\\Router->{closure}(Array)\\n#18 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(Closure), Array)\\n#19 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/s\\\/RUR\\\/download')\\n#20 \\\/var\\\/www\\\/html\\\/repo\\\/index.php(40): OC::handleRequest()\\n#21 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":116}","level":3,"time":"2017-04-12T03:46:27+00:00","method":"GET","url":"\/repo\/s\/RUR\/download?path=%2F04_RECURSOS_NATURALES%2F01_BIODIVERSIDAD%2F00_BIODIVERSIDAD%2FMapa_biodiversidad%2FInfGeografica&files=InfVectorial&downloadStartSecret=q05aqvjhyuc","user":"--","version":"11.0.2.7"}
{"reqId":"hKEvXIMLJppJiApsiGhi","remoteAddr":"5.226.22.166","app":"no app in context","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'UPDATE `nc_file_locks` SET `lock` = `lock` + 1, `ttl` = ? WHERE `key` = ? AND `lock` >= 0' with params [1491972339, \\\"files\\\\\\\/8ab969ab38e5377d5e670993d1af6c7d\\\"]:\\n\\nSQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE `nc_file...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/DB\\\/Connection.php(215): Doctrine\\\\DBAL\\\\Connection->executeUpdate('UPDATE `nc_file...', Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Lock\\\/DBLockingProvider.php(167): OC\\\\DB\\\\Connection->executeUpdate('UPDATE `nc_file...', Array)\\n#4 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(680): OC\\\\Lock\\\\DBLockingProvider->acquireLock('files\\\/8ab969ab3...', 1)\\n#5 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(588): OC\\\\Files\\\\Storage\\\\Common->acquireLock('files\\\/RUR', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#6 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/View.php(1894): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/RUR', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#7 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/View.php(2001): OC\\\\Files\\\\View->lockPath('\\\/RUR', 1)\\n#8 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/legacy\\\/files.php(321): OC\\\\Files\\\\View->lockFile('\\\/RUR\\\/04_RECURSO...', 1)\\n#9 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/legacy\\\/files.php(146): OC_Files::lockFiles(Object(OC\\\\Files\\\\View), '\\\/RUR\\\/04_RECURSO...', Array)\\n#10 \\\/var\\\/www\\\/html\\\/repo\\\/apps\\\/files_sharing\\\/lib\\\/Controller\\\/ShareController.php(529): OC_Files::get('\\\/RUR\\\/04_RECURSO...', 'InfVectorial', Array)\\n#11 [internal function]: OCA\\\\Files_Sharing\\\\Controller\\\\ShareController->downloadShare('RUR', 'InfVectorial', '\\\/04_RECURSOS_NA...', 'e5bzid13h5n')\\n#12 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#13 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'downloadShare')\\n#14 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'downloadShare')\\n#15 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/public\\\/AppFramework\\\/App.php(136): OC\\\\AppFramework\\\\App::main('ShareController', 'downloadShare', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#16 \\\/var\\\/www\\\/html\\\/repo\\\/core\\\/routes.php(99): OCP\\\\AppFramework\\\\App->dispatch('ShareController', 'downloadShare')\\n#17 [internal function]: OC\\\\Route\\\\Router->{closure}(Array)\\n#18 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(Closure), Array)\\n#19 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/s\\\/RUR\\\/download')\\n#20 \\\/var\\\/www\\\/html\\\/repo\\\/index.php(40): OC::handleRequest()\\n#21 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":116}","level":3,"time":"2017-04-12T03:46:30+00:00","method":"GET","url":"\/repo\/s\/RUR\/download?path=%2F04_RECURSOS_NATURALES%2F01_BIODIVERSIDAD%2F00_BIODIVERSIDAD%2FMapa_biodiversidad%2FInfGeografica&files=InfVectorial&downloadStartSecret=e5bzid13h5n","user":"--","version":"11.0.2.7"}
{"reqId":"dzTi+UnYbd7YWsDVL9jA","remoteAddr":"5.226.22.166","app":"no app in context","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'UPDATE `nc_file_locks` SET `lock` = `lock` + 1, `ttl` = ? WHERE `key` = ? AND `lock` >= 0' with params [1491972339, \\\"files\\\\\\\/8ab969ab38e5377d5e670993d1af6c7d\\\"]:\\n\\nSQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE `nc_file...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/DB\\\/Connection.php(215): Doctrine\\\\DBAL\\\\Connection->executeUpdate('UPDATE `nc_file...', Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Lock\\\/DBLockingProvider.php(167): OC\\\\DB\\\\Connection->executeUpdate('UPDATE `nc_file...', Array)\\n#4 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(680): OC\\\\Lock\\\\DBLockingProvider->acquireLock('files\\\/8ab969ab3...', 1)\\n#5 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(588): OC\\\\Files\\\\Storage\\\\Common->acquireLock('files\\\/RUR', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#6 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/View.php(1894): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/RUR', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#7 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/View.php(2001): OC\\\\Files\\\\View->lockPath('\\\/RUR', 1)\\n#8 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/legacy\\\/files.php(321): OC\\\\Files\\\\View->lockFile('\\\/RUR\\\/04_RECURSO...', 1)\\n#9 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/legacy\\\/files.php(146): OC_Files::lockFiles(Object(OC\\\\Files\\\\View), '\\\/RUR\\\/04_RECURSO...', Array)\\n#10 \\\/var\\\/www\\\/html\\\/repo\\\/apps\\\/files_sharing\\\/lib\\\/Controller\\\/ShareController.php(529): OC_Files::get('\\\/RUR\\\/04_RECURSO...', 'InfVectorial', Array)\\n#11 [internal function]: OCA\\\\Files_Sharing\\\\Controller\\\\ShareController->downloadShare('RUR', 'InfVectorial', '\\\/04_RECURSOS_NA...', 'swc5bj3eqy8')\\n#12 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#13 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'downloadShare')\\n#14 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'downloadShare')\\n#15 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/public\\\/AppFramework\\\/App.php(136): OC\\\\AppFramework\\\\App::main('ShareController', 'downloadShare', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#16 \\\/var\\\/www\\\/html\\\/repo\\\/core\\\/routes.php(99): OCP\\\\AppFramework\\\\App->dispatch('ShareController', 'downloadShare')\\n#17 [internal function]: OC\\\\Route\\\\Router->{closure}(Array)\\n#18 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(Closure), Array)\\n#19 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/s\\\/RUR\\\/download')\\n#20 \\\/var\\\/www\\\/html\\\/repo\\\/index.php(40): OC::handleRequest()\\n#21 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":116}","level":3,"time":"2017-04-12T03:46:30+00:00","method":"GET","url":"\/repo\/s\/RUR\/download?path=%2F04_RECURSOS_NATURALES%2F01_BIODIVERSIDAD%2F00_BIODIVERSIDAD%2FMapa_biodiversidad%2FInfGeografica&files=InfVectorial&downloadStartSecret=swc5bj3eqy8","user":"--","version":"11.0.2.7"}
{"reqId":"cd75BpUZ1EKOJF0tZj5x","remoteAddr":"5.226.22.166","app":"no app in context","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'UPDATE `nc_file_locks` SET `lock` = `lock` + 1, `ttl` = ? WHERE `key` = ? AND `lock` >= 0' with params [1491972340, \\\"files\\\\\\\/8ab969ab38e5377d5e670993d1af6c7d\\\"]:\\n\\nSQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE `nc_file...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/DB\\\/Connection.php(215): Doctrine\\\\DBAL\\\\Connection->executeUpdate('UPDATE `nc_file...', Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Lock\\\/DBLockingProvider.php(167): OC\\\\DB\\\\Connection->executeUpdate('UPDATE `nc_file...', Array)\\n#4 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(680): OC\\\\Lock\\\\DBLockingProvider->acquireLock('files\\\/8ab969ab3...', 1)\\n#5 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(588): OC\\\\Files\\\\Storage\\\\Common->acquireLock('files\\\/RUR', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#6 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/View.php(1894): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/RUR', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#7 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Files\\\/View.php(2001): OC\\\\Files\\\\View->lockPath('\\\/RUR', 1)\\n#8 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/legacy\\\/files.php(321): OC\\\\Files\\\\View->lockFile('\\\/RUR\\\/04_RECURSO...', 1)\\n#9 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/legacy\\\/files.php(146): OC_Files::lockFiles(Object(OC\\\\Files\\\\View), '\\\/RUR\\\/04_RECURSO...', Array)\\n#10 \\\/var\\\/www\\\/html\\\/repo\\\/apps\\\/files_sharing\\\/lib\\\/Controller\\\/ShareController.php(529): OC_Files::get('\\\/RUR\\\/04_RECURSO...', 'InfVectorial', Array)\\n#11 [internal function]: OCA\\\\Files_Sharing\\\\Controller\\\\ShareController->downloadShare('RUR', 'InfVectorial', '\\\/04_RECURSOS_NA...', 'xl22vtbbv7f')\\n#12 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#13 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'downloadShare')\\n#14 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'downloadShare')\\n#15 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/public\\\/AppFramework\\\/App.php(136): OC\\\\AppFramework\\\\App::main('ShareController', 'downloadShare', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#16 \\\/var\\\/www\\\/html\\\/repo\\\/core\\\/routes.php(99): OCP\\\\AppFramework\\\\App->dispatch('ShareController', 'downloadShare')\\n#17 [internal function]: OC\\\\Route\\\\Router->{closure}(Array)\\n#18 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(Closure), Array)\\n#19 \\\/var\\\/www\\\/html\\\/repo\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/s\\\/RUR\\\/download')\\n#20 \\\/var\\\/www\\\/html\\\/repo\\\/index.php(40): OC::handleRequest()\\n#21 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/repo\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":116}","level":3,"time":"2017-04-12T03:46:31+00:00","method":"GET","url":"\/repo\/s\/RUR\/download?path=%2F04_RECURSOS_NATURALES%2F01_BIODIVERSIDAD%2F00_BIODIVERSIDAD%2FMapa_biodiversidad%2FInfGeografica&files=InfVectorial&downloadStartSecret=xl22vtbbv7f","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Undefined index: activity at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Undefined index: backgroundjob at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Undefined index: comments at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Undefined index: core at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Undefined index: dav at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Undefined index: federatedfilesharing at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Undefined index: federation at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Undefined index: files at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Undefined index: files_pdfviewer at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Undefined index: files_sharing at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Undefined index: files_texteditor at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Undefined index: files_trashbin at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Undefined index: files_versions at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Undefined index: files_videoplayer at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Undefined index: firstrunwizard at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Undefined index: gallery at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Undefined index: logreader at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Undefined index: lookup_server_connector at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Undefined index: nextcloud_announcements at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Undefined index: notifications at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Undefined index: password_policy at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Undefined index: provisioning_api at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Undefined index: serverinfo at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Undefined index: sharebymail at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Undefined index: survey_client at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Undefined index: systemtags at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Undefined index: theming at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Undefined index: twofactor_backupcodes at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Undefined index: updatenotification at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Undefined index: workflowengine at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"mtEGa4Ttb4C3VslPw\/RF","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/repo\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-04-12T07:52:28+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

### PR DESCRIPTION
**Pull request by nickvergessen**
Downstream 27668

1. Create a folder called `wav`
1. Create a folder called `.wav`
1. Create a file called `test.wav`
1. Delete the mimetype `audio/wav` from oc_mimetypes
1. Run `occ maintenance:mimetype:update-db --repair-filecache`

### Expected
`test.wav` has mimetype `audio/wav`

### Actual
`wav` has mimetype `audio/wav`

with the first commit nothing has `audio/wav` (oc), but I fixed it.

Fixes #4318

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I get this when executing the command:

bildschirmfoto 2017-05-12 um 01 06 11


Also when I execute the repair step on master it seems to mess up with the app data files for SCSS and gzipped JS. o.O

**Comment by nickvergessen** [comment]
> Also when I execute the repair step on master it seems to mess up with the app data files for SCSS and gzipped JS. o.O

exactly, because the folders are called css and js and they are currently then having their mimetypes updated. Exactly what this PR fixes...

I fixed the SQL error.

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

File: lib/private/Files/Type/Loader.php [hunk 1]
```diff
@@ -158,14 +158,19 @@ private function loadMimetypes() {
 	 * @return int number of changed rows
 	 */
 	public function updateFilecache($ext, $mimetypeId) {
+		$isFolderId = $this->getId('httpd/unix-directory');
```
Comment (ChristophWurst) [inline lib/private/Files/Type/Loader.php]: IMO this variable name is misleading. I though it was a boolean and thus the code/patch was hard to read. Wouldn't something like `$folderMimeType` fit better here?

Comment (nickvergessen) [inline lib/private/Files/Type/Loader.php]: Done

**Review by icewind1991 — APPROVED** [review]

**Comment by MorrisJobke** [comment]
I will move the signed off check to the bottom. I ran the other checker tests locally and they passed.
