### PR TITLE
fix: changed text alignment and icon logic 

### LINKED ISSUE #43839: [Bug]: Padded breadcrumbs
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

image

### Steps to reproduce

1. Open Files
2. Go into a directory

### Expected behavior

The directory shows in the breadcrumbs with no additional padding on its left

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by emoral435**
* Resolves #43839
## Summary
1. Previously, for every breadcrumb, we where loading an icon alongside its text. Because we where using NcButton, this meant that the button was trying to load an icon and its accompanying text, splitting the button width into two, which is why the padding looked funky!
2. The icon rendering logic now needs to change in order to fit the new NcBreadcrumb logic, so we serve the component an icon that we use now instead of having it on every section!

Unrelated, but while testing this, it seems that the uploading section of this component seems to block the view of the breadcrumbs even when you are not uploading something. May have to do with our upload stores queue not updating correctly? Will test later!

## Screenshots of the new change
SCR-20240227-jtcg

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/files/src/components/BreadCrumbs.vue [hunk 1]
```diff
@@ -97,6 +99,13 @@ export default defineComponent({
 		}
 	},
 
+	data() {
+		return {
+			// used to show the views icon for the first breadcrumb
+			icon: this.$navigation.active?.icon ?? null
```
Comment (susnux) [inline apps/files/src/components/BreadCrumbs.vue:105]: This does not need to be a reactive variable, it is never set again so it stays at the initial value.
So I would move this to `computed` instead.

File: apps/files/src/components/BreadCrumbs.vue [hunk 2]
```diff
@@ -36,7 +36,9 @@
 			:aria-description="ariaForSection(section)"
 			@click.native="onClick(section.to)">
 			<template v-if="index === 0" #icon>
-				<NcIconSvgWrapper v-if="section.icon" :size="20" :svg="section.icon" />
+				<NcIconSvgWrapper v-if="icon"
```
Comment (susnux) [inline apps/files/src/components/BreadCrumbs.vue:39]: Would this not just add an empty icon slot in case there is no icon? How about this:

```vue
			<template v-if="index === 0 && icon" #icon>
				<NcIconSvgWrapper :size="20" :svg="icon" />
```

Comment (skjnldsv) [reply apps/files/src/components/BreadCrumbs.vue:39]: No because we want to fallback to the Home con if the section doesn't have one defined :)

Comment (susnux) [reply apps/files/src/components/BreadCrumbs.vue:39]: Ah yes I see

File: apps/files/src/components/BreadCrumbs.vue (hunk 1 above)
Comment (emoral435) [reply apps/files/src/components/BreadCrumbs.vue:105]: Agreed! Will change this :)

File: apps/files/src/components/BreadCrumbs.vue [hunk 3]
```diff
@@ -132,6 +133,11 @@ export default defineComponent({
 		shouldShowBreadcrumbs(): boolean {
 			return this.filesListWidth < 768 && !this.isUploadInProgress
 		},
+
+		// used to show the views icon for the first breadcrumb
+		getViewIcon(): string | null {
+			return this.$navigation.active?.icon ?? null
+		}
```
Comment (susnux) [inline apps/files/src/components/BreadCrumbs.vue:140]: I do not think computed are getters, so I would go with `viewIcon` directly.
But how about simplify the code a but and use:

```suggestion
		getViewIcon(): string {
			return this.$navigation.active?.icon ?? homeSvg
		}
```

Then you can remove the `v-if` `v-else` in the template. And replace the import of `Home` with:
`import homeSvg from '@mdi/svg/svg/home.svg?raw'`

Comment (skjnldsv) [reply apps/files/src/components/BreadCrumbs.vue:140]: Clean!

**Review by susnux — APPROVED** [review]
Looks good to me now :)

**Review by skjnldsv — APPROVED** [review]

**Comment by emoral435** [comment]
Fixed 🐘

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/pull/43773 is most likely getting in first :see_no_evil:
