### PR TITLE
fix: Move storage constructor to specific interface

### LINKED ISSUE #32709: Remove constructor from IStorage interface
`\OCP\Files\Storage\IStorage` and `\OCP\Files\Storage` contain a constructor, which triggers errors and warninigs en classes implementing those that other parameters in their constructor, like `\OC\Encryption\Keys\Storage`.

I’m _pretty_ sure there is no reason to have these constructors in the interfaces, unless we sometime build an instance without knowing which class it is?

### PR DESCRIPTION
**Pull request by come-nc**
* Resolves: #32709

## Summary

That allows Wrappers to use DI and not care about the constructor

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by icewind1991 — APPROVED** [review]

File: lib/public/Files/Storage/IConstructableStorage.php [hunk 1]
```diff
@@ -0,0 +1,26 @@
+<?php
+
+declare(strict_types=1);
+
+/**
+ * SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
+ * SPDX-License-Identifier: AGPL-3.0-only
+ */
+// use OCP namespace for all classes that are considered public.
+// This means that they should be used by apps instead of the internal Nextcloud classes
```
Comment (provokateurin) [inline lib/public/Files/Storage/IConstructableStorage.php:10]: Why is this comment here?

File: lib/public/Files/Storage/IConstructableStorage.php [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+namespace OCP\Files\Storage;
+
+/**
+ * Marks a storage as constructable. Allows to pass the storage as a string to a mounpoint and let it build the instance.
+ *
+ * @since 31.0.0
+ */
+interface IConstructableStorage {
+	/**
+	 * $parameters is a free form array with the configuration options needed to construct the storage
```
Comment (provokateurin) [inline lib/public/Files/Storage/IConstructableStorage.php:21]:
```suggestion
	 * @param array $parameters is a free form array with the configuration options needed to construct the storage
```
Use a proper docblock for LSPs to resolve the comment

**Review by provokateurin — APPROVED** [review]
Makes sense :+1:

File: lib/public/Files/Storage/IConstructableStorage.php (hunk 1 above)
Comment (come-nc) [reply lib/public/Files/Storage/IConstructableStorage.php:10]: Copied from IStorage. Felt like it made sense.
