### PR TITLE
Fix missing setlocale with php 8

### LINKED ISSUE #29296: No video preview when the folder has UTF8 characters
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1.Open a folder that has an accent letter on it e.g.: á
2. Find a folder inside that one with a video

### Expected behaviour
The server should generate a thumbnail

### Actual behaviour
No thumbnail appears, the browser receives a 404

### Server configuration

**Operating system:** Docker

**Web server:** Apache

**Database:** Postgress

**PHP version:** 8.0.11

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** 22.2.0

**List of activated apps:**
<details>
<summary>App list</summary>Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - breezedark: 22.0.2
  - bruteforcesettings: 2.2.0
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contactsinteraction: 1.3.0
  - dashboard: 7.2.0
  - dav: 1.19.0
  - duplicatefinder: 0.0.12
  - facerecognition: 0.8.3
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_pdfviewer: 2.3.0
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - nextcloud_announcements: 1.11.0
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - previewgenerator: 3.1.1
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.0
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.145:85",
            "next.lan"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "22.2.0.2",
        "overwrite.cli.url": "http:\/\/192.168.1.145:85",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 2,
        "maintenance": false,
        "app_install_overwrite": [
            "previewgenerator"
        ],
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\Movie",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MP3",
            "OC\\Preview\\MKV",
            "OC\\Preview\\MP4",
            "OC\\Preview\\AVI",
            "OC\\Preview\\3GP"
        ],
        "theme": "",
        "default_locale": "pt_BR"
    }
}
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>
173.24.0.222 - - [18/Oct/2021:11:07:36 +0000] "GET /apps/files/?dir=/EnvioAutom%C3%A1tico/Camera/videos/2021/08&fileid=972808 HTTP/1.1" 303 797 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:36 +0000] "GET /apps/files/?dir=/EnvioAutom%C3%A1tico/Camera/videos/2021/08 HTTP/1.1" 200 11605 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:36 +0000] "GET /custom_apps/breezedark/css/guest.css?v=a8c08e7c-2 HTTP/1.1" 200 2019 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:36 +0000] "GET /css/text/593e-4e14-icons.css?v=70d94a086a6d4d9cba9fcd290c81aa4e-593ed86d-2 HTTP/1.1" 200 1306 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:36 +0000] "GET /css/core/dd9a-4e14-server.css?v=70d94a086a6d4d9cba9fcd290c81aa4e-106fce8d-2 HTTP/1.1" 200 20746 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:36 +0000] "GET /css/files/95cf-4e14-merged.css?v=70d94a086a6d4d9cba9fcd290c81aa4e-95cfeb87-2 HTTP/1.1" 200 6718 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/files_rightclick/css/app.css?v=7d23ff90-2 HTTP/1.1" 200 726 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:36 +0000] "GET /css/files_sharing/f5a2-4e14-icons.css?v=70d94a086a6d4d9cba9fcd290c81aa4e-f5a209a9-2 HTTP/1.1" 200 991 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:36 +0000] "GET /css/breezedark/a8c0-4e14-server.css?v=70d94a086a6d4d9cba9fcd290c81aa4e-a8c08e7c-2 HTTP/1.1" 200 17052 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:36 +0000] "GET /css/core/dd9a-4e14-css-variables.css?v=70d94a086a6d4d9cba9fcd290c81aa4e-106fce8d-2 HTTP/1.1" 200 1526 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /css/activity/96db-4e14-style.css?v=70d94a086a6d4d9cba9fcd290c81aa4e-96dba882-2 HTTP/1.1" 200 1998 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /css/facerecognition/c5f3-4e14-fr-dialogs.css?v=70d94a086a6d4d9cba9fcd290c81aa4e-c5f3f5c1-2 HTTP/1.1" 200 1247 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /core/js/dist/files_fileinfo.js?v=106fce8d-2 HTTP/1.1" 200 10001 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /core/js/dist/files_client.js?v=106fce8d-2 HTTP/1.1" 200 43548 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /core/js/dist/main.js?v=106fce8d-2 HTTP/1.1" 200 480463 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /css/user_status/62ab-4e14-user-status-menu.css?v=70d94a086a6d4d9cba9fcd290c81aa4e-62abc69f-2 HTTP/1.1" 200 1132 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/accessibility/js/accessibilityoca.js?v=106fce8d-2 HTTP/1.1" 200 5186 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /custom_apps/breezedark/js/breezedark.js?v=106fce8d-2 HTTP/1.1" 200 1131 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/files_videoplayer/js/main.js?v=106fce8d-2 HTTP/1.1" 200 3488 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/files_sharing/js/dist/main.js?v=106fce8d-2 HTTP/1.1" 200 1615 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/files/js/dist/templates.js?v=106fce8d-2 HTTP/1.1" 200 174938 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/files_sharing/js/dist/collaboration.js?v=106fce8d-2 HTTP/1.1" 200 1780 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /core/js/dist/systemtags.js?v=106fce8d-2 HTTP/1.1" 200 20111 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /css/icons/icons-vars.css?v=1634330701 HTTP/1.1" 200 72822 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/comments/js/comments.js?v=106fce8d-2 HTTP/1.1" 200 3071 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/systemtags/js/systemtags.js?v=106fce8d-2 HTTP/1.1" 200 6574 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/federatedfilesharing/js/external.js?v=106fce8d-2 HTTP/1.1" 200 2336 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/files_versions/js/files_versions.js?v=106fce8d-2 HTTP/1.1" 200 12383 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/accessibility/css/user-d41d8cd98f00b204e9800998ecf8427e HTTP/1.1" 200 749 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/recommendations/js/main.js?v=106fce8d-2 HTTP/1.1" 200 77894 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/files_sharing/js/dist/files_sharing.js?v=106fce8d-2 HTTP/1.1" 200 5402 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/files_sharing/js/dist/additionalScripts.js?v=106fce8d-2 HTTP/1.1" 200 7139 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/files/js/fileinfomodel.js?v=106fce8d-2 HTTP/1.1" 200 1795 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/text/js/files.js?v=106fce8d-2 HTTP/1.1" 200 74591 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/files/js/dist/sidebar.js?v=106fce8d-2 HTTP/1.1" 200 264042 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/comments/js/comments-tab.js?v=106fce8d-2 HTTP/1.1" 200 1942 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /facerecognition/js/vendor/autocomplete.js?v=106fce8d-2 HTTP/1.1" 200 8504 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /facerecognition/js/fr-dialogs.js?v=106fce8d-2 HTTP/1.1" 200 2212 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /facerecognition/js/personssidebar.js?v=106fce8d-2 HTTP/1.1" 200 50742 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/theming/styles?v=2 HTTP/1.1" 200 1415 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/files_pdfviewer/js/files_pdfviewer-main.js?v=106fce8d-2 HTTP/1.1" 200 9901 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/text/js/viewer.js?v=106fce8d-2 HTTP/1.1" 200 10574 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/comments/js/comments-app.js?v=106fce8d-2 HTTP/1.1" 200 418957 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/files_trashbin/js/files_trashbin.js?v=106fce8d-2 HTTP/1.1" 200 6494 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/files_rightclick/js/script.js?v=106fce8d-2 HTTP/1.1" 200 3762 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/files_rightclick/js/files.js?v=106fce8d-2 HTTP/1.1" 200 1813 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/firstrunwizard/js/about.js?v=106fce8d-2 HTTP/1.1" 200 834 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/theming/js/theming.js?v=106fce8d-2 HTTP/1.1" 200 547 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/user_status/js/user-status-menu.js?v=106fce8d-2 HTTP/1.1" 200 163147 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /js/core/merged-template-prepend.js?v=106fce8d-2 HTTP/1.1" 200 3879 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/files_sharing/js/dist/files_sharing_tab.js?v=106fce8d-2 HTTP/1.1" 200 411149 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/files/js/dist/files-app-settings.js?v=106fce8d-2 HTTP/1.1" 200 27415 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/viewer/js/viewer-main.js?v=106fce8d-2 HTTP/1.1" 200 355827 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /js/files/merged-index.js?v=106fce8d-2 HTTP/1.1" 200 95429 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /core/js/dist/unified-search.js?v=106fce8d-2 HTTP/1.1" 200 168508 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /js/activity/activity-sidebar.js?v=106fce8d-2 HTTP/1.1" 200 320598 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/dashboard/img/dashboard.svg?v=106fce8d HTTP/1.1" 200 935 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/files/img/app.svg?v=106fce8d HTTP/1.1" 200 701 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/activity/img/activity.svg?v=106fce8d HTTP/1.1" 200 696 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/photos/img/app.svg?v=106fce8d HTTP/1.1" 200 973 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /custom_apps/duplicatefinder/img/app.svg?v=106fce8d HTTP/1.1" 200 1761 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/settings/img/admin.svg?v=106fce8d HTTP/1.1" 200 715 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/user_status/img/app.svg?v=106fce8d HTTP/1.1" 200 896 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/settings/img/apps.svg?v=106fce8d HTTP/1.1" 200 643 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/settings/img/help.svg?v=106fce8d HTTP/1.1" 200 999 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/firstrunwizard/img/info.svg?v=106fce8d HTTP/1.1" 200 854 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /apps/settings/img/users.svg?v=106fce8d HTTP/1.1" 200 1318 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /core/img/actions/delete.svg HTTP/1.1" 200 726 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /core/img/actions/logout.svg?v=106fce8d HTTP/1.1" 200 822 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /svg/core/logo/logo?color=ffffff&v=1 HTTP/1.1" 200 1095 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /avatar/dev/32?v=0 HTTP/1.1" 200 1256 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:37 +0000] "GET /core/js/dist/main.js.map HTTP/1.1" 200 1450360 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:38 +0000] "GET /apps/files/js/dist/templates.js.map HTTP/1.1" 200 554834 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:38 +0000] "GET /core/img/favicon.ico HTTP/1.1" 200 3754 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:38 +0000] "GET /core/img/favicon-touch.png HTTP/1.1" 200 7273 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:38 +0000] "GET /apps/files/js/dist/sidebar.js.map HTTP/1.1" 200 812956 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:38 +0000] "GET /apps/comments/js/comments-app.js.map HTTP/1.1" 200 1139143 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:38 +0000] "GET /apps/files_sharing/js/dist/files_sharing_tab.js.map HTTP/1.1" 200 969157 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:38 +0000] "PUT /apps/user_status/heartbeat HTTP/1.1" 200 864 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:39 +0000] "GET /ocs/v2.php/search/providers?from=%2Fapps%2Ffiles%2F%3Fdir%3D%2FEnvioAutom%25C3%25A1tico%2FCamera%2Fvideos%2F2021%2F08 HTTP/1.1" 200 1023 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:38 +0000] "GET /apps/viewer/js/viewer-main.js.map?v=e90c2feca473d3bb80b3 HTTP/1.1" 200 985405 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:39 +0000] "GET /apps/files_sharing/api/externalShares HTTP/1.1" 200 772 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:39 +0000] "GET /core/img/breadcrumb.svg?v=1 HTTP/1.1" 200 667 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:39 +0000] "GET /apps/systemtags/lastused HTTP/1.1" 200 772 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:39 +0000] "PROPFIND /remote.php/dav/files/dev/EnvioAutom%C3%A1tico/Camera/videos/2021/08 HTTP/1.1" 207 1450 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:39 +0000] "GET /apps/recommendations/api/recommendations HTTP/1.1" 200 1043 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:40 +0000] "GET /apps/files/js/dist/files-app-settings.js.map HTTP/1.1" 200 121605 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:40 +0000] "GET /apps/text/js/files.js.map HTTP/1.1" 200 286451 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:40 +0000] "GET /core/js/dist/unified-search.js.map HTTP/1.1" 200 528868 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:40 +0000] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2FEnvioAutom%C3%A1tico%2FCamera%2Fvideos%2F2021%2F08 HTTP/1.1" 200 949 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:40 +0000] "GET /apps/theming/img/core/filetypes/video.svg?v=2 HTTP/1.1" 200 1152 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
173.24.0.222 - - [18/Oct/2021:11:07:40 +0000] "GET /core/preview?fileId=1211012&c=e7f2fedf4a6db0de8e2b2a2247f4652b&x=250&y=250&forceIcon=0&a=0 HTTP/1.1" 404 734 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
` {"reqId":"lyBBYevnJOuWyYzVUvkd","level":3,"time":"2021-10-18T11:07:40+00:00","remoteAddr":"192.168.1.114","user":"dev","app":"core","method":"GET","url":"/core/preview?fileId=1211012&c=e7f2fedf4a6db0de8e2b2a2247f4652b&x=250&y=250&forceIcon=0&a=0","message":"Movie preview generation failed Output: [\"ffmpeg version 4.3.2-0+deb11u2 Copyright (c) 2000-2021 the FFmpeg developers\",\"  built with gcc 10 (Debian 10.2.1-6)\",\"  configuration: --prefix=/usr --extra-version=0+deb11u2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared\",\"  libavutil      56. 51.100 / 56. 51.100\",\"  libavcodec     58. 91.100 / 58. 91.100\",\"  libavformat    58. 45.100 / 58. 45.100\",\"  libavdevice    58. 10.100 / 58. 10.100\",\"  libavfilter     7. 85.100 /  7. 85.100\",\"  libavresample   4.  0.  0 /  4.  0.  0\",\"  libswscale      5.  7.100 /  5.  7.100\",\"  libswresample   3.  7.100 /  3.  7.100\",\"  libpostproc    55.  7.100 / 55.  7.100\",\"/var/www/html/data/dev/files/EnvioAutomtico/Camera/videos/2021/08/20210809_070004.mp4: No such file or directory\"]","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0","version":"22.2.0.2"}
{"reqId":"lyBBYevnJOuWyYzVUvkd","level":3,"time":"2021-10-18T11:07:41+00:00","remoteAddr":"192.168.1.114","user":"dev","app":"core","method":"GET","url":"/core/preview?fileId=1211012&c=e7f2fedf4a6db0de8e2b2a2247f4652b&x=250&y=250&forceIcon=0&a=0","message":"Movie preview generation failed Output: [\"ffmpeg version 4.3.2-0+deb11u2 Copyright (c) 2000-2021 the FFmpeg developers\",\"  built with gcc 10 (Debian 10.2.1-6)\",\"  configuration: --prefix=/usr --extra-version=0+deb11u2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared\",\"  libavutil      56. 51.100 / 56. 51.100\",\"  libavcodec     58. 91.100 / 58. 91.100\",\"  libavformat    58. 45.100 / 58. 45.100\",\"  libavdevice    58. 10.100 / 58. 10.100\",\"  libavfilter     7. 85.100 /  7. 85.100\",\"  libavresample   4.  0.  0 /  4.  0.  0\",\"  libswscale      5.  7.100 /  5.  7.100\",\"  libswresample   3.  7.100 /  3.  7.100\",\"  libpostproc    55.  7.100 / 55.  7.100\",\"/var/www/html/data/dev/files/EnvioAutomtico/Camera/videos/2021/08/20210809_070004.mp4: No such file or directory\"]","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0","version":"22.2.0.2"} `
</details>

#### Browser log
<details>
<summary>Browser log</summary>
image

</details>

### PR DESCRIPTION
**Pull request by YoitoFes**
When php version = 8, basename('§') returns '§' even if LC_ALL is non-UTF-8 locale.
Since OC_Util::isSetLocaleWorking() assumes basename('§') returns empty string with non-UTF-8 locale,
the function  with php 8 incorrectly skips setlocale("C.UTF-8").

Fix it by using escapeshellcmd instead of basename.

This issue found in #29296 and The PR may be able to resolve it.

### CODE REVIEW

File: lib/private/legacy/OC_Util.php [hunk 1]
```diff
@@ -1245,16 +1245,17 @@ public function isHtaccessWorking(\OCP\IConfig $config) {
 	 * @return bool
 	 */
 	public static function isSetLocaleWorking() {
-		if ('' === basename('§')) {
+		if ('' === escapeshellcmd('§')) {
```
Comment (PVince81) [inline lib/private/legacy/OC_Util.php:1248]: should we keep both checks, just in case ?
otherwise we'd need to check if `escapeshellcmd` behaves the same as `basename` in all past supported PHP versions

Comment (YoitoFes) [reply lib/private/legacy/OC_Util.php:1248]: @PVince81 
Thank you for your feedback!

I added the `testIsSetLocaleWorking()` to PHPUnit. By using the test, GitHub Actions/Drone CI can check if `escapeshellcmd` behaves the same as `basename` in all supported PHP.

Comment (PVince81) [reply lib/private/legacy/OC_Util.php:1248]: indeed, that's clever

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by come-nc — APPROVED** [review]

**Comment by acsfer** [comment]
What if `escapeshellcmd()` is a disabled function in php? 🤔

**Comment by PVince81** [comment]
> What if `escapeshellcmd()` is a disabled function in php? thinking

not sure if it's as common as disabling the `exec` and `shell_exec`

but you're right to be careful, is there a way to detect disabled functions ?
if disabled then we could fall back to `basename`

**Comment by acsfer** [comment]
@PVince81 https://www.php.net/manual/en/function.function-exists.php
```
if (!function_exists('escapeshellcmd')) {
...
}
```

**Comment by YoitoFes** [comment]
Is `escapeshellarg` disabled less often than `escapeshellcmd`? `escapeshellarg` is used in Nextcloud's source code while `escapeshellcmd` is not.

**Comment by acsfer** [comment]
Hard to say, but it is always a good practice check if the function exists before call it, and have a fallback 😉

**Comment by YoitoFes** [comment]
I think `basename` can be used as a fallback as the function with php8 cause the issue.
So I added `escapeshellarg` and `preg_match` as fallbacks.

**Review by PVince81 — APPROVED** [review]
Fine by me :+1:

File: lib/private/legacy/OC_Util.php [hunk 2]
```diff
@@ -1239,22 +1239,38 @@ public function isHtaccessWorking(\OCP\IConfig $config) {
...
 	/**
-	 * Check if the setlocal call does not work. This can happen if the right
+	 * Check if current locale is non-UTF8
+	 *
+	 * @return bool
+	 */
+	private static function isNonUTF8Locale() {
+		if (function_exists("escapeshellcmd")) {
+			return ('' === escapeshellcmd('§'));
+		} else if (function_exists("escapeshellarg")) {
```
Comment (acsfer) [inline lib/private/legacy/OC_Util.php:1249]: `elseif` 😝

**Comment by PVince81** [comment]
seems the bot is lagging, no further backports yet?
