### PR TITLE
enh(files): Allow to copy files into same directory

### LINKED ISSUE #10441: Allow to duplicate a file by copying it to the same directory
Related to issue #9931.

It is not currently possible, but I'd love to be able to duplicate a text file + re-name it to .md at the same time while using the copy menu.  System notice that appears to the user is:

> Could not copy "Markdown Examples.txt"; target exists.

but it could become

> "Markdown Examples.txt" already exists; Do you want to Duplicate or Rename the copy?

My request is to allow users to duplicate (copy) and re-name a file within the Copy and Move menu when target already exists.
duplicate

### LINKED ISSUE #18846: Copy whole folder fails because of 'target exists'
related to #15785
when copying a whole folder, there is no way to paste that folder in the current parent.

### Steps to reproduce
1. create a folder `parent`
2. create a folder inside `parent` called `test`
3. select and make action `Move or copy`
4. click `copy` in the dialogue that appears

outcome is the error message: `could not copy "test", target exists`

### Expected behaviour
If there is an attempt to copy a folder into a target where the same name exists, an option should be provided to rename the copied folder.  Alternatively, a safe name could be suggested like `test_copy`.

### Actual behaviour
Copy of folder fails with no option to change the destination name.

### Server configuration

**Operating system:**
Debian 9

**Web server:**
Apache2.4

**Database:
MariaDB

**PHP version:**
7.2.26

**Nextcloud version:** 
17.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated

### Client configuration
**Browser:**
Firefox (latest)

**Operating system:**
OS X

### LINKED ISSUE #41768: [Bug]: Not able to create a copy of a file in the same directory
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I have a folder in Files with a file template for a meeting protocol. Every week I copy the file to the same directory to get a new copy. This is no longer possible in 28.

### Steps to reproduce

1. Create a folder
2. Create a file in the folder
3. Click the *Move or copy*

### Expected behavior

The file picker lets me pick the source directory for *Copy*.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by susnux**
* Bring back: #10825 
* Resolves https://github.com/nextcloud/server/issues/18846
* Resolves https://github.com/nextcloud/server/issues/10441
* Resolves: https://github.com/nextcloud/server/issues/41768

## Summary
Bring back copy to current directory behavior which will clone the file and add a "copy" suffix on the file name.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/files/src/actions/moveOrCopyAction.ts [hunk 1]
```diff
@@ -69,6 +67,30 @@ const getActionForNodes = (nodes: Node[]): MoveCopyAction => {
  * @return {Promise<void>} A promise that resolves when the copy/move is done
  */
 export const handleCopyMoveNodeTo = async (node: Node, destination: Folder, method: MoveCopyAction.COPY | MoveCopyAction.MOVE, overwrite = false) => {
+	/**
+	 * Create an unique name for a node
+	 * @param node Node that is copied
+	 * @param otherNodes Other nodes in the target directory to check for unique name
+	 * @return Either the node basename, if unique, or the name with a `(copy N)` suffix that is unique
+	 */
+	const makeUniqueName = (node: Node, otherNodes: Node[]|FileStat[]) => {
```
Comment (skjnldsv) [inline apps/files/src/actions/moveOrCopyAction.ts:76]: We already have a method and pattern for that :)
https://github.com/nextcloud/server/blob/9f157d7f8030a1f7a9455be10810ee11f1cb15f0/apps/files/src/newMenu/newFolder.ts#L59-L67

**Review by skjnldsv — CHANGES_REQUESTED** [review]

File: apps/files/src/actions/moveOrCopyAction.ts (hunk 1 above)
Comment (skjnldsv) [reply apps/files/src/actions/moveOrCopyAction.ts:76]: Ah, I have no preferences, I used the old behavior, which was just the number! Please adjust the method then so we have whatever the design team approved! :+1:

File: apps/files/src/actions/moveOrCopyAction.ts [hunk 2]
```diff
@@ -86,33 +109,43 @@ export const handleCopyMoveNodeTo = async (node: Node, destination: Folder, meth
 	 * node: /foo/bar/file.txt -> path = /foo/bar
 	 * destination: /foo
 	 * Allow move of /foo does not start with /foo/bar so allow
+	 * But allow copy a file to the same directory
 	 */
-	if (destination.path.startsWith(node.path)) {
+	if (destination.path.startsWith(node.path) && destination.path !== node.path) {
```
Comment (artonge) [inline apps/files/src/actions/moveOrCopyAction.ts:114]: Does it prevent moving a folder into itself? Not sure how it could happen, but still.
```js
destination.path = "/a/b"
node.path = "/a/b"

destination.path.startsWith(node.path) === true
(destination.path !== node.path) === false
```

I think the following would work:
```suggestion
	if (destination.path.startsWith(node.path) && (destination.path !== node.path || node.type === Folder)) {
```

But warning, I might simply be confused.

File: apps/files/src/actions/moveOrCopyAction.ts [hunk 3]
```diff
@@ -86,33 +109,43 @@ export const handleCopyMoveNodeTo = async (node: Node, destination: Folder, meth
...
+			const currentPath = join(davRootPath, node.path)
+			const destinationPath = join(davRootPath, destination.path)
 
-			// If we're moving, update the node
-			// if we're copying, we don't need to update the node
-			// the view will refresh itself
-			if (method === MoveCopyAction.MOVE) {
+			if (method === MoveCopyAction.COPY) {
+				let target = node.basename
+				// If we do not allow overwriting than find an unique name
```
Comment (artonge) [inline apps/files/src/actions/moveOrCopyAction.ts:130]:
```suggestion
				// If we do not allow overwriting then find an unique name
```

File: apps/files/src/actions/moveOrCopyAction.ts (hunk 2 above)
Comment (susnux) [reply apps/files/src/actions/moveOrCopyAction.ts:114]: No the whole `&& ...` can be dropped.

Because if your target folder is `/foo/bar` then ofcourse I can not move `/foo` into it, but I can also not move `/foo/bar` into it, and I am even not allowed to copy it into itself, because if both have the same path I try:
`/foo/bar` -> `/foo/bar` leading to `/foo/bar/bar` which is also not allowed.

To clone that directory you would need to pass `/foo` as the destination and then the check is ok as it was.

File: apps/files/src/actions/moveOrCopyAction.ts (hunk 1 above)
Comment (skjnldsv) [reply apps/files/src/actions/moveOrCopyAction.ts:76]: Perfect!!  Thanks @susnux :)

**Review by artonge — APPROVED** [review]

File: apps/files/src/utils/fileUtils.ts [hunk 4]
```diff
@@ -21,6 +21,25 @@
...
+ */
+export const getUniqueName = (name: string, otherNames: string[], suffix = (n: number) => `(${n})`): string => {
+	let newName = name
+	let i = 1
+	while (otherNames.includes(newName)) {
+		const ext = extname(name)
+		newName = `${basename(name, ext)} ${suffix(i++)}${ext}`
+	}
+	return newName
+}
```
Comment (emoral435) [inline apps/files/src/utils/fileUtils.ts:42]: Seems like if you move folders with no extension name, getUniqueName clips the last letter from the file when you append the suffix to the end of the new file name:

image

Probably due to files not having extensions, so might have to add a check for that for files

**Review by emoral435 — CHANGES_REQUESTED** [review]
Just needs the file part and it LGTM!!

**Comment by susnux** [comment]
@emoral435 can you check again if that still happens for you?

**Review by emoral435 — APPROVED** [review]
Checked, and it works perfectly for me now :) sorry for being nitpicky!

**Comment by emoral435** [comment]
@skjnldsv before we merge this in, it still says that you have requested changes. I'm 99% sure your fine with this, but just to make sure, all the changes now are fine by you, correct? :)

**Review by skjnldsv — APPROVED** [review]
