### PR TITLE
fix(l10n): Don't fallback from 3-letter languages to 2-letter

### LINKED ISSUE #55274: [Bug]: mix georgian and kabyle language
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi,

I would like to report this long dated issue with NextCloud WebUI.
When trying to test the progression of kabyle translation on demo server in kabyle language, it is always displayed in georgian language.

In fact Georgian language is a 2 letter code `ka` and kabyle language which is norh african has a `kab` : 3 letters. Our localization team would like, if possible to check this issue.

After that, we will continue translating NextCloud,

Thank you !

### Steps to reproduce

1. Set your Firefox browser in kabyle language
2. Go to any NextCloud instance.
3. You'll see it is georgian not kabyle.

### Expected behavior

Expected behaviour ; Kabyle translations should be displayed instead of georgian.

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.4

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #55274

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)
- [x] [Labels added](https://github.com/nextcloud/server/labels) where applicable (ex: bug/enhancement, `3. to review`, feature component)
- [x] [Milestone added](https://github.com/nextcloud/server/milestones) for target branch/version (ex: 32.x for `stable32`)

### CODE REVIEW

File: tests/lib/L10N/FactoryTest.php [hunk 1]
```diff
@@ -351,6 +351,11 @@ public static function dataSetLanguageFromRequest(): array {
 			[null, 'de,en', ['ru', 'en'], 'en'],
 			[null, 'de-DE,en-US;q=0.8,en;q=0.6', ['ru', 'en'], 'en'],
 
+			// Don't fall back from kab (Kabyle) to ka (Georgian) - Unless specifically requested
+			[null, 'kab;q=0.8,en;q=0.6', ['ka', 'en'], 'en'],
+			[null, 'kab;q=0.8,de;q=0.6', ['ka', 'en', 'de'], 'de'],
+			[null, 'kab;q=0.8,de;q=0.6,ka;q=0.6', ['ka', 'en', 'de'], 'de'],
```
Comment (come-nc) [inline tests/lib/L10N/FactoryTest.php]:
```suggestion
			[null, 'kab;q=0.8,de;q=0.6,ka;q=0.6', ['ka', 'en', 'de'], 'ka'],
```
No?

Comment (nickvergessen) [reply tests/lib/L10N/FactoryTest.php]: de matches before as it's the second requested language, ka is only 3rd in the list

Comment (come-nc) [reply tests/lib/L10N/FactoryTest.php]: Hum okay, I would’ve added a test that checks ka matches when in fallback list still.

**Review by come-nc — APPROVED** [review]

File: tests/lib/L10N/FactoryTest.php (hunk 1 above)
Comment (nickvergessen) [reply tests/lib/L10N/FactoryTest.php]: Added both now:
- kab;q=0.8,de;q=0.7,ka;q=0.6
- kab;q=0.8,ka;q=0.7,de;q=0.6

**Review by salmart-dev — APPROVED** [review]
Is there any way to import the incomplete translations and test this locally?

**Comment by nickvergessen** [comment]
> Is there any way to import the incomplete translations and test this locally?

It's not "incomplete", kab can basically never exist in Nextcloud as we only support lower ISO 2-letter languages.

You can test it easily by:
1. Settings your browser to 
image
 
2. Open the login page
3. Check if it's fully german

Before (half english half gergian) | After (full german)
---|---
image | image
