### PR TITLE
Only execute plain mimetype check for directories and do the fallback…

### LINKED ISSUE #182: Rule "File Mime-Typ is not Folder" not work anymore
Hi,

Nextcloud Version: 19.0.5 and 20.0.2
file_accesscontrol Version: latest (1.9.2 and 1.10.1)

i dont know when its start, becourse i not update some time bevor. After Update to the Versions what i write, the Rule "File Mime-Typ is not Folder" dont work anymore.

I use it to create a drop Folder that are only ZIP Files allowed. To Acces this Folder i need this Rule.

I hope you can fix it.

Thanks

### PR DESCRIPTION
**Pull request by MorrisJobke**
… only for non-directories

Introduced with #23096

Fixes https://github.com/nextcloud/files_accesscontrol/issues/182

@juliushaertl I'm open for other approaches, but this seems to be useful here.

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]

File: apps/workflowengine/lib/Check/FileMimeType.php [hunk 1]
```diff
@@ -102,8 +102,12 @@ protected function cacheAndReturnMimeType(string $storageId, ?string $path, stri
 	 */
 	public function executeCheck($operator, $value) {
 		$actualValue = $this->getActualValue();
-		return $this->executeStringCheck($operator, $value, $actualValue) ||
-			$this->executeStringCheck($operator, $value, $this->mimeTypeDetector->detectPath($this->path));
+		$plainMimetypeResult = $this->executeStringCheck($operator, $value, $actualValue);
+		if ($actualValue === 'httpd/unix-directory') {
```
Comment (blizzz) [inline apps/workflowengine/lib/Check/FileMimeType.php:106]: without looking deeper into  `detectPath` method, it should be OK to `or` this against `$plainMimetypeResult` since it is returned anyway if true. Unless `detectPath` must run for a reason?

Comment (MorrisJobke) [reply apps/workflowengine/lib/Check/FileMimeType.php:106]: This then would always lead to the check to be `true`.

Check for `!is MIMETYPE` means that either `httpd/unix-directory` or `application/octet-stream` does not match and therefore the check is useless, because it can't check for both.

Comment (MorrisJobke) [reply apps/workflowengine/lib/Check/FileMimeType.php:106]: To make it short: ` detectPath` never returns the folder mimetype, because it uses the extension to determine the mime type and if there is none, it returns `application/octet-stream`.

**Review by rullzer — APPROVED** [review]
Looks sane but I didn't test.
