### PR TITLE
fix(files): Ensure folders and favorites are sorted first regardless of sorting mode

### LINKED ISSUE #41510: [Bug]: Nc 28 beta 3: sorting favorites on top broken
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

So sorting Favorites on top is broken. When changing the date sort order, they are only on top when I sorted oldest-first. When I sort newest-first, the favorites get sorted to the bottom.

Screenshot 2023-11-15 at 15 32 48

### Steps to reproduce

1. Enable 'sort favorites first' in Files settings
2. Go to a folder with favorites and change the sort order, like time descending/ascending etc
3. See the favorites NOT always sorted first.

### Expected behavior

favorites always first!

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: #41510

## Summary
Add fixed sorting mode for "folder before files" and "favorites before other" - meaning those should if configured sorted before even for descending.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by nickvergessen** [comment]
> Conflicting files
apps/files/src/mixins/filesSorting.ts
dist/files-main.js
dist/files-main.js.map

**Comment by susnux** [comment]
@nickvergessen resolved - waiting for reviews.

File: apps/files/src/views/FilesList.vue [hunk 1]
```diff
@@ -217,6 +217,38 @@ export default Vue.extend({
...
+				// always sort folders before files
+				...this.sortingMode === 'basename' ? ['asc'] : [],
+				// Reverse if sorting by mtime as mtime higher means edited more recent -> lower
+				...this.sortingMode === 'mtime' ? [this.isAscSorting ? 'desc' : 'asc'] : [],
+				//
+				...this.sortingMode !== 'mtime' && this.sortingMode !== 'basename' ? [this.isAscSorting ? 'asc' : 'desc'] : [],
+				this.isAscSorting ? 'asc' : 'desc',
+				this.isAscSorting ? 'asc' : 'desc',
+			]
+			return [identifiers, orders] as const
```
Comment (artonge) [inline apps/files/src/views/FilesList.vue:249]: `as const` ?

File: apps/files/src/views/FilesList.vue [hunk 2]
```diff
@@ -217,6 +217,38 @@ export default Vue.extend({
...
+				// always sort favorites before normal files
+				...this.userConfig.sort_favorites_first ? ['asc'] : [],
+				// always sort folders before files
+				...this.sortingMode === 'basename' ? ['asc'] : [],
+				// Reverse if sorting by mtime as mtime higher means edited more recent -> lower
+				...this.sortingMode === 'mtime' ? [this.isAscSorting ? 'desc' : 'asc'] : [],
+				//
+				...this.sortingMode !== 'mtime' && this.sortingMode !== 'basename' ? [this.isAscSorting ? 'asc' : 'desc'] : [],
+				this.isAscSorting ? 'asc' : 'desc',
+				this.isAscSorting ? 'asc' : 'desc',
```
Comment (artonge) [inline apps/files/src/views/FilesList.vue:247]: Duplicate?

**Review by AndyScherzinger — APPROVED** [review]

File: apps/files/src/views/FilesList.vue (hunk 1 above)
Comment (susnux) [reply apps/files/src/views/FilesList.vue:249]: Yes otherwise the type would be `(v => bool | string)[]` using `const` the type is `[v => bool, string]` making it obvious that this only returns an array with exactly two elements. So that we can deconstruct it for `orderBy`

File: apps/files/src/views/FilesList.vue [hunk 3]
```diff
@@ -217,6 +217,38 @@ export default Vue.extend({
...
 		},
 
+		/**
+		 * Directory content sorting parameters
+		 * Provided by an extra computed property for caching
+		 */
+		sortingParameters() {
+			const identifiers = [
+				// Sort favorites first if enabled
+				...this.userConfig.sort_favorites_first ? [v => v.attributes?.favorite !== 1] : [],
```
[the remark this answers is not in the document]
Comment (susnux) [reply apps/files/src/views/FilesList.vue:227]: Copy paste from original code, but can fix this.

File: apps/files/src/views/FilesList.vue (hunk 2 above)
Comment (susnux) [reply apps/files/src/views/FilesList.vue:247]: No this needs to have exactly the same number of elements as the "identifiers" array, but I add comments.

File: apps/files/src/views/FilesList.vue (hunk 1 above)
Comment (susnux) [reply apps/files/src/views/FilesList.vue:251]: before | after
---|---
Screenshot_20231116_142714|Screenshot_20231116_143023

**Review by artonge — APPROVED** [review]
