### PR TITLE
Log and continue on Dav reader failure (repair uid)

### LINKED ISSUE #12764: Sabre webdav UTF-8 error after Upgrade to NC 15.0.0RC1
During the Upgrade from  NC14 to NC 15.0.0 RC1 got the follow error message:
```
occ upgrade -vvv
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
The current PHP memory limit is below the recommended value of 512MB.
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
2018-11-30T19:15:03+00:00 Set log level to debug
2018-11-30T19:15:03+00:00 Repair step: Repair MySQL collation
2018-11-30T19:15:03+00:00 Repair info: All tables already have the correct collation -> nothing to do
2018-11-30T19:15:03+00:00 Repair step: Repair SQLite autoincrement
2018-11-30T19:15:03+00:00 Repair step: Copy data from accounts table when migrating from ownCloud
2018-11-30T19:15:04+00:00 Repair step: Drop account terms table when migrating from ownCloud
2018-11-30T19:15:04+00:00 Updating database schema
2018-11-30T19:15:05+00:00 Updated database
2018-11-30T19:15:06+00:00 Checking for update of app cloud_federation_api in appstore
2018-11-30T19:15:06+00:00 Checked for update of app "cloud_federation_api" in appstore
2018-11-30T19:15:06+00:00 Checking for update of app dav in appstore
2018-11-30T19:15:06+00:00 Checked for update of app "dav" in appstore
2018-11-30T19:15:06+00:00 Checking for update of app federatedfilesharing in appstore
2018-11-30T19:15:06+00:00 Checked for update of app "federatedfilesharing" in appstore
2018-11-30T19:15:06+00:00 Checking for update of app files in appstore
2018-11-30T19:15:06+00:00 Checked for update of app "files" in appstore
2018-11-30T19:15:06+00:00 Checking for update of app files_external in appstore
2018-11-30T19:15:06+00:00 Checked for update of app "files_external" in appstore
2018-11-30T19:15:06+00:00 Checking for update of app logreader in appstore
2018-11-30T19:15:06+00:00 Checked for update of app "logreader" in appstore
2018-11-30T19:15:06+00:00 Checking for update of app lookup_server_connector in appstore
2018-11-30T19:15:06+00:00 Checked for update of app "lookup_server_connector" in appstore 2018-11-30T19:15:06+00:00 Checking for update of app notifications in appstore
2018-11-30T19:15:06+00:00 Checked for update of app "notifications" in appstore
2018-11-30T19:15:06+00:00 Checking for update of app oauth2 in appstore
2018-11-30T19:15:06+00:00 Checked for update of app "oauth2" in appstore
2018-11-30T19:15:06+00:00 Checking for update of app password_policy in appstore
2018-11-30T19:15:06+00:00 Checked for update of app "password_policy" in appstore
2018-11-30T19:15:06+00:00 Checking for update of app provisioning_api in appstore
2018-11-30T19:15:06+00:00 Checked for update of app "provisioning_api" in appstore
2018-11-30T19:15:06+00:00 Checking for update of app twofactor_backupcodes in appstore
2018-11-30T19:15:06+00:00 Checked for update of app "twofactor_backupcodes" in appstore
2018-11-30T19:15:06+00:00 Checking for update of app updatenotification in appstore
2018-11-30T19:15:06+00:00 Checked for update of app "updatenotification" in appstore
2018-11-30T19:15:06+00:00 Checking for update of app workflowengine in appstore
2018-11-30T19:15:06+00:00 Checked for update of app "workflowengine" in appstore
2018-11-30T19:15:06+00:00 Repair step: Repair MySQL collation
2018-11-30T19:15:06+00:00 Repair info: All tables already have the correct collation -> nothing to do
2018-11-30T19:15:06+00:00 Repair step: Repair mime types
2018-11-30T19:15:06+00:00 Repair step: Clean tags and favorites
2018-11-30T19:15:06+00:00 Repair info: 0 tags of deleted users have been removed.
2018-11-30T19:15:06+00:00 Repair info: 0 tags for delete files have been removed.
2018-11-30T19:15:06+00:00 Repair info: 0 tag entries for deleted tags have been removed.
2018-11-30T19:15:06+00:00 Repair info: 0 tags with no entries have been removed.
2018-11-30T19:15:06+00:00 Repair step: Repair invalid shares
2018-11-30T19:15:06+00:00 Repair step: Remove shares of a users root folder
2018-11-30T19:15:06+00:00 Repair step: Move .step file of updater to backup location
2018-11-30T19:15:06+00:00 Repair step: Fix potential broken mount points
2018-11-30T19:15:06+00:00 Repair info: No mounts updated
2018-11-30T19:15:06+00:00 Repair step: Repair invalid paths in file cache
2018-11-30T19:15:06+00:00 Repair step: Add log rotate job
2018-11-30T19:15:06+00:00 Repair step: Clear frontend caches
2018-11-30T19:15:06+00:00 Repair info: Image cache cleared
2018-11-30T19:15:06+00:00 Repair info: SCSS cache cleared
2018-11-30T19:15:06+00:00 Repair info: JS cache cleared
2018-11-30T19:15:06+00:00 Repair step: Clear every generated avatar on major updates
2018-11-30T19:15:06+00:00 Repair info: Avatar cache cleared
2018-11-30T19:15:06+00:00 Repair step: Add preview background cleanup job
2018-11-30T19:15:06+00:00 Repair step: Queue a one-time job to cleanup old backups of the updater
2018-11-30T19:15:06+00:00 Repair step: Repair pending cron jobs
2018-11-30T19:15:06+00:00 Repair info: No need to repair pending cron jobs.
2018-11-30T19:15:06+00:00 Repair step: Extract the vcard uid and store it in the db
2018-11-30T19:15:07+00:00 Sabre\VObject\ParseException: Unsupported CHARSET: UTF-8,UTF-8,UTF-8
2018-11-30T19:15:07+00:00 Update failed
2018-11-30T19:15:07+00:00 Maintenance mode is kept active
2018-11-30T19:15:07+00:00 Reset log level
```
Thank you.

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #12764 

@Dani22m

### CODE REVIEW

File: lib/private/Repair/NC15/SetVcardDatabaseUID.php [hunk 1]
```diff
@@ -78,10 +86,16 @@ private function getInvalidEntries() {
...
-			$uid = $vCard->UID->getValue();
-			return $uid;
+		try {
+			$vCard = Reader::read($cardData, Reader::OPTION_FORGIVING);
+			if ($vCard->UID) {
+				$uid = $vCard->UID->getValue();
+
+				return $uid;
+			}
+		} catch (\Exception $e) {
```
Comment (ChristophWurst) [inline lib/private/Repair/NC15/SetVcardDatabaseUID.php]: would it be possible to catch a more specific exception?

File: lib/private/Repair/NC15/SetVcardDatabaseUID.php [hunk 2]
```diff
@@ -132,6 +146,7 @@ private function shouldRun() {
 	}
 
 	public function run(IOutput $output) {
+		$this->output = $output;
```
Comment (ChristophWurst) [inline lib/private/Repair/NC15/SetVcardDatabaseUID.php]: :-1: pass `$output` as method parameter please

**Review by ChristophWurst — CHANGES_REQUESTED** [review]

File: lib/private/Repair/NC15/SetVcardDatabaseUID.php (hunk 1 above)
Comment (skjnldsv) [reply lib/private/Repair/NC15/SetVcardDatabaseUID.php]: Shall we?
Yes we can, but the goal is to keep going I guess? :)

File: lib/private/Repair/NC15/SetVcardDatabaseUID.php [hunk 3]
```diff
@@ -78,10 +86,16 @@ private function getInvalidEntries() {
 	 * @return string the uid or empty if none
 	 */
 	private function getUID(string $cardData): string {
-		$vCard = Reader::read($cardData);
-		if ($vCard->UID) {
-			$uid = $vCard->UID->getValue();
-			return $uid;
+		try {
+			$vCard = Reader::read($cardData, Reader::OPTION_FORGIVING);
+			if ($vCard->UID) {
```
[the remark this answers is not in the document]
Comment (skjnldsv) [reply lib/private/Repair/NC15/SetVcardDatabaseUID.php]: It's mandatory yes.
Otherwise it gets refused on upload :)

File: lib/private/Repair/NC15/SetVcardDatabaseUID.php (hunk 2 above)
Comment (skjnldsv) [reply lib/private/Repair/NC15/SetVcardDatabaseUID.php]: I hesitated to do that.
I did not wanted to pass it on every chained function. Is there a better suitable and clean looking way of doing so? :)

Comment (ChristophWurst) [reply lib/private/Repair/NC15/SetVcardDatabaseUID.php]: Yes, passing as parameter is the clean way :wink:

Comment (ChristophWurst) [reply lib/private/Repair/NC15/SetVcardDatabaseUID.php]: You just have to pass it to repair -> getUID

Comment (skjnldsv) [reply lib/private/Repair/NC15/SetVcardDatabaseUID.php]: Well, to repaid and then getuid, right? :)

File: lib/private/Repair/NC15/SetVcardDatabaseUID.php (hunk 3 above)
[the remark this answers is not in the document]
Comment (ChristophWurst) [reply lib/private/Repair/NC15/SetVcardDatabaseUID.php]: Where is the `UID` property coming from? Can you point me to the code?

[the remark this answers is not in the document]
Comment (ChristophWurst) [reply lib/private/Repair/NC15/SetVcardDatabaseUID.php]: `Document` extends `Component` Extends `Node` implements `ArrayAccess`. Did you mean to use `$vCard['UID']` instead?

File: lib/private/Repair/NC15/SetVcardDatabaseUID.php (hunk 1 above)
Comment (ChristophWurst) [reply lib/private/Repair/NC15/SetVcardDatabaseUID.php]: well, you'll catch almost everything that might be thrown in that block, though you're just interested in the missing UID. So, yes, we shall :wink:

File: lib/private/Repair/NC15/SetVcardDatabaseUID.php (hunk 2 above)
Comment (ChristophWurst) [reply lib/private/Repair/NC15/SetVcardDatabaseUID.php]: Correct! :)

File: lib/private/Repair/NC15/SetVcardDatabaseUID.php (hunk 3 above)
[the remark this answers is not in the document]
Comment (skjnldsv) [reply lib/private/Repair/NC15/SetVcardDatabaseUID.php]: No, ->UID is the proper way
http://sabre.io/vobject/vcard/

File: lib/private/Repair/NC15/SetVcardDatabaseUID.php (hunk 1 above)
Comment (skjnldsv) [reply lib/private/Repair/NC15/SetVcardDatabaseUID.php]: Okay :)

File: lib/private/Repair/NC15/SetVcardDatabaseUID.php [hunk 4]
```diff
@@ -78,10 +86,16 @@ private function getInvalidEntries() {
 	 * @return string the uid or empty if none
 	 */
 	private function getUID(string $cardData): string {
-		$vCard = Reader::read($cardData);
-		if ($vCard->UID) {
-			$uid = $vCard->UID->getValue();
-			return $uid;
+		try {
+			$vCard = Reader::read($cardData, Reader::OPTION_FORGIVING);
```
Comment (danielkesselberg) [inline lib/private/Repair/NC15/SetVcardDatabaseUID.php]: Could we use https://github.com/sabre-io/vobject/wiki/Sabre-VObject-Reader#option_ignore_invalid_lines here?

`$vCard = Reader::read($cardData, Reader::OPTION_FORGIVING | Reader::OPTION_IGNORE_INVALID_LINES);`

File: lib/private/Repair/NC15/SetVcardDatabaseUID.php [hunk 5]
```diff
@@ -83,18 +81,19 @@ private function getInvalidEntries() {
...
-			$vCard = Reader::read($cardData, Reader::OPTION_FORGIVING);
+			$vCard = Reader::read($cardData);
 			if ($vCard->UID) {
 				$uid = $vCard->UID->getValue();
 
 				return $uid;
 			}
-		} catch (\Exception $e) {
-			$this->output->warning('One vCard is broken. We logged the exception and will continue the repair.');
+		} catch (ParseException $e) {
```
Comment (ChristophWurst) [inline lib/private/Repair/NC15/SetVcardDatabaseUID.php]: :heart_eyes:

File: lib/private/Repair/NC15/SetVcardDatabaseUID.php [hunk 6]
```diff
@@ -146,11 +145,10 @@ private function shouldRun() {
 	}
 
 	public function run(IOutput $output) {
-		$this->output = $output;
-		if ($this->shouldRun()) {
-			$count = $this->repair();
+		// if ($this->shouldRun()) {
```
Comment (ChristophWurst) [inline lib/private/Repair/NC15/SetVcardDatabaseUID.php]: :thinking:

**Review by ChristophWurst — CHANGES_REQUESTED** [review]

File: lib/private/Repair/NC15/SetVcardDatabaseUID.php (hunk 4 above)
Comment (danielkesselberg) [reply lib/private/Repair/NC15/SetVcardDatabaseUID.php]: Thanks for looking into :+1:

File: lib/private/Repair/NC15/SetVcardDatabaseUID.php (hunk 6 above)
Comment (skjnldsv) [reply lib/private/Repair/NC15/SetVcardDatabaseUID.php]: I fixuped already :see_no_evil:

**Review by ChristophWurst — APPROVED** [review]
Code looks good!

**Review by kesselb — APPROVED** [review]

**Comment by skjnldsv** [comment]
BTW, we fixed this, but any REPORT request to the addressbook containing this vcard will fail. So in the end This is not really great! This is a fix to a problem that should not have happened :confused:
