### PR TITLE
fix: replace null character when serializing

### LINKED ISSUE #47879: [Bug]: Error PHP unserialize
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi
I would like to report a repeated error I can find in NC logs. I'm afraid I can't evaluate its consequences, many errors arrived at the same time: locked files, antivirus, SQL and redis server.

### Steps to reproduce

find logs in NC Logging:

```
[PHP] Error: unserialize(): Error at offset 40 of 43 bytes at /var/www/html/apps/dav/lib/DAV/CustomPropertiesBackend.php#574
	PROPFIND /remote.php/dav/addressbooks/users/UserName/
	from 185.252.235.96 by UserName at 8 sept. 2024, 19:22:05
```

### Expected behavior

no error

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 28.0.1 to 28.0.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

```shell
{"reqId":"YizWhMVEux6WGmu7Clxp","level":3,"time":"2024-09-08T17:22:05+00:00","remoteAddr":"185.252.235.96","user":"UserName","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/addressbooks/users/UserName/","message":"unserialize(): Error at offset 40 of 43 bytes at /var/www/html/apps/dav/lib/DAV/CustomPropertiesBackend.php#574","userAgent":"Mac OS X/10.15.7 (19H2026) AddressBookCore/1","version":"29.0.4.1","data":{"app":"PHP"},"id":"66e090d696463"}
```
```


### Additional info


#Server configuration detail
Operating system: Linux 5.10.0-32-amd64 [#](https://notre.rez0.net/s/ztLijxYSegjCmjt#h-server-configuration-detail)1 SMP Debian 5.10.223-1 (2024-08-10) x86_64

Webserver: Apache/2.4.62 (Unix) (fpm-fcgi)

Database: pgsql PostgreSQL 16.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, 64-bit

PHP version: 8.2.21

Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, hash, iconv, json, mbstring, SPL, session, PDO, pdo_sqlite, bz2, posix, random, readline, Reflection, standard, SimpleXML, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, bcmath, Phar, exif, ftp, gd, gmp, igbinary, imagick, imap, intl, ldap, memcached, pcntl, pdo_pgsql, pgsql, redis, smbclient, sodium, sysvsem, zip, libsmbclient, Zend OPcache

Nextcloud version: 29.0.4 - 29.0.4.1

Updated from an older Nextcloud/ownCloud or fresh install:

Where did you install Nextcloud from: unknown

<details><summary>Signing status</summary>

[]
</details>

<details><summary>List of activated apps</summary>


Enabled:
 - activity: 2.21.1
 - admin_audit: 1.19.0
 - announcementcenter: 6.8.1
 - auto_groups: 1.5.3
 - bruteforcesettings: 2.9.0
 - calendar: 4.7.16
 - cfg_share_links: 5.1.3
 - circles: 29.0.0-dev
 - cloud_federation_api: 1.12.0
 - collectives: 2.14.3
 - comments: 1.19.0
 - contacts: 6.0.0
 - contactsinteraction: 1.10.0
 - dashboard: 7.9.0
 - dav: 1.30.1
 - deck: 1.13.1
 - event_update_notification: 2.4.0
 - external: 5.4.0
 - federatedfilesharing: 1.19.0
 - files: 2.1.0
 - files_antivirus: 5.5.7
 - files_downloadlimit: 2.0.0
 - files_pdfviewer: 2.10.0
 - files_reminders: 1.2.0
 - files_sharing: 1.21.0
 - files_trashbin: 1.19.0
 - files_versions: 1.22.0
 - forms: 4.2.4
 - group_default_quota: 0.1.10
 - groupfolders: 17.0.3
 - integration_excalidraw: 2.2.0
 - integration_youtube: 0.3.0
 - logreader: 2.14.0
 - lookup_server_connector: 1.17.0
 - mail: 3.7.8
 - money: 0.28.0
 - nextcloud-aio: 0.6.0
 - nextcloud_announcements: 1.18.0
 - notes: 4.10.1
 - notifications: 2.17.0
 - notify_push: 0.7.0
 - oauth2: 1.17.0
 - password_policy: 1.19.0
 - polls: 7.2.2
 - provisioning_api: 1.19.0
 - quota_warning: 1.20.0
 - registration: 2.4.0
 - related_resources: 1.4.0
 - richdocuments: 8.4.6
 - settings: 1.12.0
 - sharebymail: 1.19.0
 - side_menu: 3.13.1
 - spreed: 19.0.8
 - support: 1.12.0
 - suspicious_login: 7.0.0
 - tasks: 0.16.1
 - terms_of_service: 2.5.0
 - text: 3.10.1
 - theming: 2.4.0
 - timemanager: 0.3.15
 - twofactor_backupcodes: 1.18.0
 - unroundedcorners: 1.1.3
 - user_status: 1.9.0
 - viewer: 2.3.0
 - welcome: 1.2.0
 - workflowengine: 2.11.0
Disabled:
 - encryption
 - federation: 1.17.0
 - files_external
 - firstrunwizard: 2.14.0
 - impersonate: 1.16.0
 - photos: 2.3.0
 - privacy: 1.13.0
 - recommendations: 1.4.0
 - serverinfo: 1.16.0
 - survey_client: 1.13.0
 - systemtags: 1.18.0
 - twofactor_totp: 7.0.0
 - user_ldap
 - weather_status: 1.5.0

</details>

<details><summary>Configuration (config/config.php)</summary>


{
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "password": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "overwriteprotocol": "https",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "notre.rez0.net",
        "kolab.koraland.net"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "skeletondirectory": "\/var\/lib\/docker\/volumes\/nextcloud_aio_nextcloud\/_data\/skeleton",
    "dbtype": "pgsql",
    "version": "29.0.4.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "check_data_directory_permissions": true,
    "maintenance": false,
    "loglevel": 2,
    "log_type": "file",
    "logfile": "\/var\/www\/html\/data\/nextcloud.log",
    "log_rotate_size": "10485760",
    "log.condition": {
        "apps": [
            "admin_audit"
        ]
    },
    "preview_max_x": "2048",
    "preview_max_y": "2048",
    "jpeg_quality": "60",
    "enabledPreviewProviders": {
        "1": "OC\\Preview\\Image",
        "2": "OC\\Preview\\MarkDown",
        "3": "OC\\Preview\\MP3",
        "4": "OC\\Preview\\TXT",
        "5": "OC\\Preview\\OpenDocument",
        "6": "OC\\Preview\\Movie",
        "0": "OC\\Preview\\Imaginary"
    },
    "enable_previews": true,
    "upgrade.disable-web": true,
    "trashbin_retention_obligation": "auto, 30",
    "versions_retention_obligation": "auto, 30",
    "activity_expire_days": "30",
    "simpleSignUpLink.shown": false,
    "share_folder": "\/Shared",
    "one-click-instance": true,
    "one-click-instance.user-limit": 100,
    "one-click-instance.link": "https:\/\/nextcloud.com\/all-in-one\/",
    "htaccess.RewriteBase": "\/",
    "files_external_allow_create_new_local": true,
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "preview_imaginary_url": "***REMOVED SENSITIVE VALUE***",
    "default_language": "fr",
    "default_locale": "fr_FR",
    "default_phone_region": "FR",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "allow_local_remote_servers": true,
    "updatedirectory": "\/nc-updater",
    "overwritehost": "notre.rez0.net",
    "overwrite.cli.url": "https:\/\/notre.rez0.net\/",
    "updater.release.channel": "stable",
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "upgrade.cli-upgrade-link": "https:\/\/github.com\/nextcloud\/all-in-one\/discussions\/2726",
    "davstorage.request_timeout": 3600,
    "dbpersistent": false,
    "appsallowlist": false,
    "maintenance_window_start": 100,
    "preview_imaginary_key": "***REMOVED SENSITIVE VALUE***",
    "defaultapp": "",
    "auth.bruteforce.protection.enabled": true,
    "ratelimit.protection.enabled": true
}
</details>

Cron Configuration: Array
(
[backgroundjobs_mode] => cron
[lastcron] => 1725993214
)

External storages: files_external is disabled

Encryption: no

User-backends:

OC\User\Database

Talk configuration:

STUN servers

185.252.235.96:443

TURN servers

turn:185.252.235.96:3478 - udp,tcp

Signaling servers (mode: default):

SIP dialin is disabled

SIP dialout is disabled

https://notre.rez0.net/standalone-signaling/ - 1.3.2~docker

Recording servers:

Recording is enabled

Recording consent is set to "default"

no recording server configured

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36

### LINKED ISSUE #48914: [Bug]: Trying to share a calendar in the iOS app breaks it
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Trying to share a calendar in the iOS app breaks it. 

I tried to share a calendar in the iOS app, like you would share an iCloud calendar. I wanted to see if it works. 

The result is, that the calendar now is gone. It is not deleted, but not shown anymore. The logs show. 

unserialize(): Error at offset 48 of 51 bytes at /var/www/html/apps/dav/lib/DAV/CustomPropertiesBackend.php#560 

I assume that the iOS calendar app writes some data that it should not be able to write into the database. 

### Steps to reproduce

1. Run latest Nextcloud-aio ( Nextcloud AIO v9.7.0)
2. Log into the caldav account on iOS
3. share the calender with an email 

### Expected behavior

Not to break a calendar and render all entire unavailable and basically deleted, when trying to share the calendar in the iOS app. 

### Nextcloud Server version

30

### Operating system

Other

### PHP engine version

Other

### Web server

Other

### Database engine version

Other

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

unserialize(): Error at offset 48 of 51 bytes at /var/www/html/apps/dav/lib/DAV/CustomPropertiesBackend.php#560

### Additional info

( Nextcloud AIO v9.7.0)

I know I am running AIO, but as far as I could track, the responsible code is here. If I should create another Issue in the AIO Repo, I can do this. 

For me this is solved, by creating a new calendar, since there was not much in the initial one, but I think that might be a major issue for someone with a lot of things in their calendar, so I thought I have to let someone know.

### PR DESCRIPTION
**Pull request by SebastianKrupinski**
* Resolves: #47879
* Resolves: https://github.com/nextcloud/server/issues/48914

## Summary
Serialize() creates string with null character, this causes issues when saving data in certain databases

## Checklist
- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by tcitworld** [comment]
While this seems a much simple way of fixing the issue that what I've tried at https://github.com/nextcloud/server/pull/39084, what happens when you unserialize the values? Are the objects valid and make sense, since you loose the fact that a property is set to `null`?

You also need to add a repair step to remove all broken values (see `preSchemaChange` in file `Version1032Date20230630084412.php` of my own PR).

**Comment by SebastianKrupinski** [comment]
> While this seems a much simple way of fixing the issue that what I've tried at #39084, what happens when you unserialize the values? Are the objects valid and make sense, since you loose the fact that a property is set to `null`?

Yes, they properly unserialize to a php object. If you replace the null character with a space. Tested this.
 
> You also need to add a repair step to remove all broken values (see `preSchemaChange` in file `Version1032Date20230630084412.php` of my own PR).

yes, a repair step will be needed. I just need to investigate, if we can just do one for Postgres only, MySQL seems to handle null character properly.

**Comment by tcitworld** [comment]
But the property that was previously `null` will now be set to a space. Won't that cause any trouble?

**Comment by SebastianKrupinski** [comment]
> But the property that was previously `null` will now be set to a space. Won't that cause any trouble?

So this is the value that was causing the issue, 
O:48:"Sabre\CalDAV\Xml\Property\ScheduleCalendarTransp":1:{s:8:" * value";s:6:"opaque";}

The part to the sting that is the issue is the " * value" the space before and after the * are a null characters, basically this "null*null". The word value is actually a property inside the object. I don't know all the in and outs of serialize but to me it looks like "null*null" is a marker for a private property.

On that note, you might be right if there is a value that is null and serialize converts it to a null character then there might be a issue. But then we are back to square 1, and there is no real way to fix this for postgres. The only other way I can think of, would be to replace the null with the word null and then replace it again on unserialize.

**Comment by tcitworld** [comment]
> But then we are back to square 1, and there is no real way to fix this for postgres. The only other way I can think of, would be to replace the null with the word null and then replace it again on unserialize.

The only way I've thought of is to [have the column type accept null terminators](https://github.com/nextcloud/server/pull/39084), by setting it to `BLOB`. But data migration is a hassle.

I think your solution might be an easier workaround that we can try until some other serious issue gets reported. It just needs the cleanup step.

**Comment by SebastianKrupinski** [comment]
> I think your solution might be an easier workaround that we can try until some other serious issue gets reported. It just needs the cleanup step.

I agree, done and done, made the repair step actually check if the property is broken, instead of just blindly removing them all.

File: apps/dav/lib/Migration/RemoveBrokenProperties.php [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+
+	/**
+	 * @inheritdoc
+	 */
+	public function run(IOutput $output) {
+		// select all calendar transparency properties 
+		$cmd = $this->db->getQueryBuilder();
+		$cmd->select('id', 'propertyvalue')
+			->from('properties')
+			->where($cmd->expr()->eq('propertyname', $cmd->createNamedParameter(self::CALENDAR_TRANSP_PROPERTY, IQueryBuilder::PARAM_STR), IQueryBuilder::PARAM_STR));
```
Comment (tcitworld) [inline apps/dav/lib/Migration/RemoveBrokenProperties.php:41]: Unfortunately transparency was not the only affected property. There's [at least](https://github.com/nextcloud/server/issues/37754#issuecomment-1613361252) `{DAV:}resourcetype` , and I'm pretty sure I saw some custom Apple-namedspaced properties as well at some point.

I'd consider selecting all properties of type object instead to check them.

Also, as this could be a heavy operation, maybe move to an expensive repair step if appropriate?

> If we have less than 50k rows (value yet to determine), perform the migrations straight away.
Otherwise, skip the migration, set an appconfig and add a red flag in system check. Then include as an expensive repair step.

**Comment by SebastianKrupinski** [comment]
Done. Made it handle all property types and run as a expensive repair step.

File: lib/private/Repair/RemoveBrokenProperties.php [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+	 */
+	public function getName() {
+		return 'Remove broken object properties';
+	}
+
+	/**
+	 * @inheritdoc
+	 */
+	public function run(IOutput $output) {
+		// select all calendar transparency properties
```
Comment (tcitworld) [inline lib/private/Repair/RemoveBrokenProperties.php:36]: Update comment

File: lib/private/Repair/RemoveBrokenProperties.php [hunk 3]
```diff
@@ -0,0 +1,66 @@
...
+				$object = @unserialize(str_replace('\x00', chr(0), $entry['propertyvalue']));
+				if ($object === false) {
+					$brokenIds[] = $entry['id'];
+				}
+			} else {
+				$brokenIds[] = $entry['id'];
+			}
+		}
+		$result->closeCursor();
+		// delete broken calendar transparency properties
```
Comment (tcitworld) [inline lib/private/Repair/RemoveBrokenProperties.php:55]: and there

File: lib/private/Repair/RemoveBrokenProperties.php [hunk 4]
```diff
@@ -0,0 +1,66 @@
...
+	public function getName() {
+		return 'Remove broken object properties';
+	}
+
+	/**
+	 * @inheritdoc
+	 */
+	public function run(IOutput $output) {
+		// select all calendar transparency properties
+		$cmd = $this->db->getQueryBuilder();
```
Comment (tcitworld) [inline lib/private/Repair/RemoveBrokenProperties.php:37]: Variable name `$cmd` seems… odd?

**Review by tcitworld — APPROVED** [review]

File: lib/private/Repair/RemoveBrokenProperties.php (hunk 2 above)
Comment (SebastianKrupinski) [reply lib/private/Repair/RemoveBrokenProperties.php]: Dang it, I always forget to update comments when I change the logic on reviews. :face_palm

Done.

File: lib/private/Repair/RemoveBrokenProperties.php (hunk 4 above)
Comment (SebastianKrupinski) [reply lib/private/Repair/RemoveBrokenProperties.php:37]: Its an "SQL Command", so I just used a generic variable name, "$cmd" so I can use it for Select and Delete.

File: lib/private/Repair/RemoveBrokenProperties.php (hunk 3 above)
Comment (SebastianKrupinski) [reply lib/private/Repair/RemoveBrokenProperties.php]: Done

File: lib/private/Repair/RemoveBrokenProperties.php (hunk 4 above)
Comment (ChristophWurst) [reply lib/private/Repair/RemoveBrokenProperties.php:37]: Use `$qb` for *query builder*. You can see that very often in our code base.

Comment (SebastianKrupinski) [reply lib/private/Repair/RemoveBrokenProperties.php]: Done

File: lib/private/Repair/RemoveBrokenProperties.php [hunk 5]
```diff
@@ -0,0 +1,66 @@
+<?php
+
```
Comment (ChristophWurst) [inline lib/private/Repair/RemoveBrokenProperties.php:2]: The file is missing strict types

File: lib/private/Repair/RemoveBrokenProperties.php [hunk 6]
```diff
@@ -0,0 +1,66 @@
...
+	public function __construct(
+		private IDBConnection $db,
+	) {
+	}
+
+	/**
+	 * @inheritdoc
+	 */
+	public function getName() {
+		return 'Remove broken object properties';
```
Comment (ChristophWurst) [inline lib/private/Repair/RemoveBrokenProperties.php:29]:
```suggestion
		return 'Remove broken DAV object properties';
```

**Review by ChristophWurst — COMMENTED** [review]
Looks sane!

Could you add a test for the unserialization of a legacy object?

File: lib/private/Repair/RemoveBrokenProperties.php (hunk 5 above)
Comment (SebastianKrupinski) [reply lib/private/Repair/RemoveBrokenProperties.php:2]: Done. That's what i get for copying another repair step.

**Comment by SebastianKrupinski** [comment]
> Could you add a test for the unserialization of a legacy object?

Done.

Did one for the current double encoding and for the legacy single encoding.

File: apps/dav/tests/unit/DAV/CustomPropertiesBackendTest.php [hunk 7]
```diff
@@ -458,4 +459,19 @@ public function moveProvider() {
...
+		$propertyType = 3;
+		$decodeValue = $this->invokePrivate($this->backend, 'decodeValueFromDatabase', [$propertyValue, $propertyType]);
+		$this->assertInstanceOf(\Sabre\CalDAV\Xml\Property\ScheduleCalendarTransp::class, $decodeValue);
+	}
+
+	public function testDecodeValueFromDatabaseObjectLegacy(): void {
+		$propertyValue = 'O:48:"Sabre\CalDAV\Xml\Property\ScheduleCalendarTransp":1:{s:8:"' . chr(0) . '*' . chr(0) . 'value";s:6:"opaque";}';
+		$propertyType = 3;
+		$decodeValue = $this->invokePrivate($this->backend, 'decodeValueFromDatabase', [$propertyValue, $propertyType]);
+		$this->assertInstanceOf(\Sabre\CalDAV\Xml\Property\ScheduleCalendarTransp::class, $decodeValue);
```
Comment (ChristophWurst) [inline apps/dav/tests/unit/DAV/CustomPropertiesBackendTest.php:474]: could you also assert the unserialized property value equality?

**Review by ChristophWurst — APPROVED** [review]

File: apps/dav/lib/DAV/CustomPropertiesBackend.php [hunk 8]
```diff
@@ -534,7 +536,9 @@ private function decodeValueFromDatabase(string $value, int $valueType) {
 			case self::PROPERTY_TYPE_HREF:
 				return new Href($value);
 			case self::PROPERTY_TYPE_OBJECT:
-				return unserialize($value);
+				// some databases can not handel null characters, these are custom encoded during serialization
+				// this custom encoding needs to be first reversed before unserializing
+				return unserialize(str_replace('\x00', chr(0), $value));
```
Comment (brakhane) [inline apps/dav/lib/DAV/CustomPropertiesBackend.php:541]: won't this cause problems if the thing we're deserializing contains a backslash?

Imagine a nerd band that names themselves 'The \x00s'. When I make a calender entry '\x00s concert', it will get deserialized into '<NUL>s concert', most likely breaking something else along the way.

Comment (SebastianKrupinski) [reply apps/dav/lib/DAV/CustomPropertiesBackend.php:541]:
```
\\x00
```
is a the actual value, the pattern is as unique as possible, also this is only used for very specific types and not for everything.

Comment (brakhane) [reply apps/dav/lib/DAV/CustomPropertiesBackend.php:541]: My point is that it is still possible to retroactively break stuff that used to work. I agree that the string '\x00' is unlikely to appear anywhere, but it's not impossible; so optimally there would be an escape sequence that makes in unambiguous; that would require a database migration, though.

But I agree it's better than the current situation; personally, I'd still prefer something more "unique"; if this is ever used for something that contains a windows path, for example, it might cause weird results  (think `C:\files\x0000.txt`)

Comment (SebastianKrupinski) [reply apps/dav/lib/DAV/CustomPropertiesBackend.php:541]: I agree there is a very tiny chance this might happen, but there is no better solution for this. The is a chance this might happen no matter what we use as an replacement for null.

The properties don't contain file names, also in your example the file name would have to be ```C:\files\\x0000.txt``` with two slashes. This would then get escaped by serialize and we then replace null characters that serialize produces with ```\\x00``` which is a common representation of null in serialization

Comment (brakhane) [reply apps/dav/lib/DAV/CustomPropertiesBackend.php:541]: ah, I see. Missed that we're replacing before deserializing. Guess it's not worth worrying about it that much.
