### PR TITLE
fix(db): remove redundant indices in properties

### LINKED ISSUE #42588: [Bug]: Redundant properties.property_index index
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The table (oc_)properties is defined as

```sql
create table oc_properties
(
    id            bigint auto_increment
        primary key,
    userid        varchar(64)  default '' not null,
    propertypath  varchar(255) default '' not null,
    propertyname  varchar(255) default '' not null,
    propertyvalue longtext                not null,
    valuetype     smallint     default 1  null
)
    collate = utf8mb4_bin
    row_format = COMPRESSED;

create index properties_path_index
    on oc_properties (userid, propertypath);

create index properties_pathonly_index
    on oc_properties (propertypath);

create index property_index
    on oc_properties (userid);
```

property_index and the concatenated index properties_path_index have userid as first column. Both indices can be used for userid lookups. properties_path_index can be used when propertypath is queried too.

The additional index makes INSERT and UPDATE  queries more expensive.

### Steps to reproduce

1. Look at Nextcloud's database

### Expected behavior

Optimized schema

### Installation method

None

### Nextcloud Server version

26

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by JohannesGGE**
* Resolves: #42588 

## Summary
Remove index `property_index` and `properties_pathonly_index` because `properties_path_index` already covers column `userid` and `propertypath`

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by solracsf** [comment]
Same as https://github.com/nextcloud/server/pull/43340#discussion_r1477806274

**Review by miaulalala — APPROVED** [review]

File: core/Migrations/Version29000Date20240131122720.php [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+		if ($tableProperties->hasIndex('property_index') &&
+			$tableProperties->hasIndex('properties_path_index')) {
+
+			$tableProperties->dropIndex('property_index');
+		}
+		if ($tableProperties->hasIndex('properties_pathonly_index') &&
+			$tableProperties->hasIndex('properties_path_index')) {
+
+			$tableProperties->dropIndex('properties_pathonly_index');
+		}
```
Comment (ChristophWurst) [inline core/Migrations/Version29000Date20240131122720.php:60]: `properties_path_index` is an index on (userid, propertypath). `properties_pathonly_index` is an index on (propertypath). The database can use properties_pathonly_index for queries on userid and userid+propertypath, but **not** for queries that only access propertypath.

> In general, a database can use a concatenated index when searching with the leading (leftmost) columns. An index with three columns can be used when searching for the first column, when searching with the first two columns together, and when searching using all columns.

https://use-the-index-luke.com/sql/where-clause/the-equals-operator/concatenated-keys

**Review by ChristophWurst — CHANGES_REQUESTED** [review]
properties_pathonly_index must stay

**Review by ChristophWurst — APPROVED** [review]
:sunglasses:
