### PR TITLE
Fix share admin page

### LINKED ISSUE #35301: [Bug]: Exclude groups from sharing broken
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I can't exclude groups from sharing, the required input field in the admin settings is not shown

### Steps to reproduce

1. Go to the admin settings -> sharing
2. check "Exclude Groups from sharing"

Nothing happens:

grafik

Tested with Nexcloud 25.0.1 and Nextcloud 24.0.7

After the checkbox is checked and I reload the page the input field is there. It seems like "just" the live switch is broken when I check the checkbox

### Expected behavior

A input field show up where I can select the groups I want to exclude:

grafik

### Installation method

_No response_

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database engine version

_No response_

### Is this bug present after an update or on a fresh install?

_No response_

### Are you using the Nextcloud Server Encryption module?

_No response_

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
-
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by CarlSchwan**
arrow function don't work that well with jquery

Fix #35301

### CODE REVIEW

File: apps/settings/src/admin.js [hunk 1]
```diff
@@ -206,11 +206,12 @@ window.addEventListener('DOMContentLoaded', () => {
 		})
 	})
 
-	$('#allowGroupSharing').change(() => {
+	$('#allowGroupSharing').change(function() {
 		$('#allowGroupSharing').toggleClass('hidden', !this.checked)
 	})
 
-	$('#shareapiExcludeGroups').change(() => {
+    console.error("loaded")
```
Comment (artonge) [inline apps/settings/src/admin.js:213]: To remove ?

**Review by PVince81 — APPROVED** [review]
:+1: nice find

**Review by artonge — APPROVED** [review]
What kind of error arrow function are triggering ?

File: apps/settings/src/admin.js (hunk 1 above)
Comment (CarlSchwan) [reply apps/settings/src/admin.js:213]: > What kind of error arrow function are triggering ?

this.checked is then undefined, because this as a different semantic in arrow functions

**Comment by artonge** [comment]
> What kind of error arrow function are triggering ?

Ah, `this` reference is changed... ok :)

**Review by szaimen — APPROVED** [review]
works

**Comment by szaimen** [comment]
drone build was killed?

**Comment by blizzz** [comment]
drone build at https://drone.nextcloud.com/nextcloud/server/26430

**Comment by solracsf** [comment]
This needs a 24 backport too.
Bug is present in 24.
