### PR TITLE
fix(dav): ajax request check on public remote endpoints

### LINKED ISSUE #42200: Public shared links refreshing continuously since v28 upgrade
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Demo url: https://cloud.datux.nl/s/qokf5AXDKN2S4E8

It keeps refreshing, nothing to see in the logs and nextcloud.log.

I'm running the official docker images behind a reverse proxy.  (nextcloud:fpm-alpine)

### Steps to reproduce

1. Share public link
2. Try to open it
3. Browser keeps refreshing.

### Expected behavior

should show the shared folder in the browser, without a reload loop.

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Other

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.datux.nl"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.0.11",
        "overwrite.cli.url": "https:\/\/cloud.datux.nl",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "overwriteprotocol": "https",
        "overwritehost": "cloud.datux.nl",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "maintenance": false,
        "theme": "",
        "app_install_overwrite": [
            "epubreader"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - bruteforcesettings: 2.8.0
  - cloud_federation_api: 1.11.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - files: 2.0.0
  - files_external: 1.20.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - notes: 4.9.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - related_resources: 1.3.0
  - settings: 1.10.0
  - sharebymail: 1.18.0
  - support: 1.11.0
  - suspicious_login: 6.0.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_totp: 10.0.0-beta.2
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - workflowengine: 2.10.0
Disabled:
  - admin_audit: 1.18.0
  - circles: 28.0.0-dev (installed 27.0.1)
  - comments: 1.18.0 (installed 1.17.0)
  - contactsinteraction: 1.9.0 (installed 1.8.0)
  - encryption: 2.16.0
  - federation: 1.18.0 (installed 1.17.0)
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - nextcloud_announcements: 1.17.0 (installed 1.16.0)
  - recommendations: 2.0.0 (installed 1.6.0)
  - serverinfo: 1.18.0 (installed 1.17.0)
  - survey_client: 1.16.0 (installed 1.15.0)
  - theming_customcss: 1.15.0 (installed 1.15.0)
  - user_ldap: 1.19.0
  - weather_status: 1.8.0 (installed 1.7.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
(empty log, only contained old entries)
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/server/issues/42200

## Context
The original legacy (8+ years) check used to search for an exact header match

But after https://github.com/nextcloud/server/pull/39924 (I think) the check went wrong and we ended  up with this
image

### CODE REVIEW

**Review by come-nc — APPROVED** [review]

**Review by artonge — APPROVED** [review]

File: apps/dav/appinfo/v1/publicwebdav.php [hunk 1]
```diff
@@ -73,7 +73,7 @@
 $filesDropPlugin = new \OCA\DAV\Files\Sharing\FilesDropPlugin();
 
 $server = $serverFactory->createServer($baseuri, $requestUri, $authPlugin, function (\Sabre\DAV\Server $server) use ($authBackend, $linkCheckPlugin, $filesDropPlugin) {
-	$isAjax = (isset($_SERVER['HTTP_X_REQUESTED_WITH']) && $_SERVER['HTTP_X_REQUESTED_WITH'] === 'XMLHttpRequest');
+	$isAjax = in_array('XMLHttpRequest', explode(',', $_SERVER['HTTP_X_REQUESTED_WITH']));
```
Comment (Altahrim) [inline apps/dav/appinfo/v1/publicwebdav.php:76]: We can even allows different case right? Something like:
```php
preg_match('/\bXMLHttpRequest\b/i', $_SERVER['HTTP_X_REQUESTED_WITH'])
```
Tested here: https://regex101.com/r/Bh5XNo/1

**Review by Altahrim — APPROVED** [review]

File: apps/dav/appinfo/v1/publicwebdav.php (hunk 1 above)
Comment (skjnldsv) [reply apps/dav/appinfo/v1/publicwebdav.php:76]: I used the same thing that is being use din other areas

https://github.com/nextcloud/server/blob/aa5f037af71c915424c6dcfd5ad2dc82797dc0d6/apps/dav/lib/Connector/Sabre/Auth.php#L224

https://github.com/nextcloud/server/blob/82b5a19a35b780bf18ebac46711166158a5a6cb2/apps/dav/lib/Connector/Sabre/PublicAuth.php#L215

https://github.com/nextcloud/server/blob/7b6a650b6e09b07d4b85a4ae84eb64a6c32b217f/apps/dav/lib/Connector/LegacyPublicAuth.php#L106

**Review by AndyScherzinger — APPROVED** [review]

File: apps/dav/appinfo/v1/publicwebdav.php (hunk 1 above)
Comment (susnux) [inline apps/dav/appinfo/v1/publicwebdav.php:76]: I think this causes an error 500 if `HTTP_X_REQUESTED_WITH` is not set. So maybe?
```suggestion
	$isAjax = in_array('XMLHttpRequest', explode(',', $_SERVER['HTTP_X_REQUESTED_WITH'] ?? ''));
```

**Review by susnux — DISMISSED** [review]

**Comment by skjnldsv** [comment]
Was failing because master was broken with `An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1 table oc_appconfig has no column named lazy`.
Rebased and cypress works now

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/pull/42882

**Comment by michnovka** [comment]
This fix did not solve everything. I cannot see image previews on public share links (my.cloud/s/XXXXXX), and I see that PROPFIND request to public.php/webdav/ gives the 401 error. Using the workaround mentioned in the original issue - https://github.com/nextcloud/server/issues/42200#issuecomment-1854772242 fixes this problem

**Comment by susnux** [comment]
@michnovka are you sure your Webserver correctly forwards all headers to PHP?
Especially X_REQUESTED_WITH

**Comment by michnovka** [comment]
I am using the nginx config from https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html (checked after update to 28.0.2 and it is identical to this one)

**Comment by michnovka** [comment]
@susnux I confirmed with adding `var_dump($_SERVER)` to public.php, and yes, all headers are passed. However, the X_REQUESTED_WITH header is not sent by JS request. See below request copied as CURL:

```
curl 'https://my.cloud/public.php/webdav/' --compressed -X PROPFIND -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0' -H 'Accept: text/plain,application/xml' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: text/plain;charset=UTF-8' -H 'Content-Length: 608' -H 'Depth: 0' -H 'Origin: https://my.cloud' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'Authorization: Basic TlFQc2lGRnFzQW15eTZTOg==' -H 'Connection: keep-alive' -H 'Cookie: __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; oc_sessionPassphrase=Tx3WTgJgIEIh0tkzXDMS3SvKZh3uiHenQaheDpb7%2BlDniZLexVDwYR%2F3OBmPBylRMyqnVxioHvVoPE8tTEKMLeUgZcO%2FUw%2Fp6rLLKJIm8hBle%2F2rKCmkn4FGi%2Fegt%2B%2Bj; ochoj4cc0e60=leb2vdq41oc2dr24i8pgvi5puf; nc_username=tomas; nc_token=JQl6MEydCWbUlt43KO%2B0UyEeFb%2BCGFnl; nc_session_id=leb2vdq41oc2dr24i8pgvi5puf' -H 'TE: trailers'
```

**Comment by kesselb** [comment]
/backport to stable24

https://github.com/nextcloud/server/pull/39924 was manually backported to 24, and therefore we need this change for 24 too.

**Comment by kesselb** [comment]
Manual backport: https://github.com/nextcloud/server/pull/44895
