### PR TITLE
Make sure the password contains special characters

### LINKED ISSUE #6089: Error message when creating new user with empty password field: Password need to contain at least one special character
### Steps to reproduce
1. Navigate to "(Gear top right-hand side) -> Administrator -> Security -> Password Complexity" and validate that you have a certain password complexity set (minimum length 12 characters, checkmarks on all complexity options)
2. Navigate to "(Gear top right-hand side) -> Users"
3. Attempt to create a couple of new users by only giving username (in my case a mail-address), a mail-address and group membership (leaving "Password" field empty!)

### Expected behaviour
According to the help message on the buttom left-hand "Settings" menu, a new user should be created and if the password field was left empty an email should be sent that requires the new user to set their own password. 

### Actual behaviour
In regular intervals I see the following error message "Password need to contain at least one special character" (see screenshot). I didn't specify/set a password, thus I'd expect that the generated password always follows the rules set in "Password Complexity". Can you please confirm that this function/method takes into account the rules set in password complexity?

This actually works fine from time to time, but fails often enough to be annoying.

error-message

### Additional information
In the old release of OwnCloud v8.2.2 (Community Edition) there was no way to require a password complexity from users. This was a hard request from our data privacy officer though, thus I used this plugin at the time to mandate a password complexity: https://apps.owncloud.com/content/show.php/Password+Policy?content=167207
I don't believe that this is related to the issue, after all those migrations up to NC v12.0.0, but wanted to share this just in case. One of the reasons to migrate to NextCloud was that this includes a password-complexity option.

### Server configuration

**Operating system**:
$ cat /etc/debian_version 
9.1

**Web server:**
Apache 2.4.25-3-deb9u

**Database:**
MariaDB
Art: mysql
Version: 10.1.23

**PHP version:**
$ php -v
PHP 7.0.19-1 (cli) (built: May 11 2017 14:04:47) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.19-1, Copyright (c) 1999-2017, by Zend Technologies

**Nextcloud version:** (see Nextcloud admin page)
12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Yes, OwnCloud 8.2.2 -> NC 9 -> NC 10 -> NC 11 -> NC 12.0.0

**Where did you install Nextcloud from:**
I downloaded the compressed archive from the NC website and used the occ CLI tool to carry out the migration/upgrade(s).

**Signing status:**
No errors have been found.

**List of activated apps:**
$ php occ app:list
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - previewgenerator: 1.0.6
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - encryption
  - files_external
  - theming
  - user_external
  - user_ldap

**Nextcloud configuration:**
$ php occ config:list system
{
    "system": {
        "instanceid": "ocgxcqlwbajh",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***.com",
            "192.168.70.20"
        ],
        "overwritehost": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***.com",
        "datadirectory": "\/var\/www\/owncloud\/data",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "default_language": "de",
        "theme": "ALE",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "owncloud",
        "mail_domain": "***REMOVED SENSITIVE VALUE***.com",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "192.168.30.20",
        "mail_smtpport": "8025",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 3,
        "appstore.experimental.enabled": true,
        "maintenance": false
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Google Chrome Version 60.0.3112.90 (Official Build) (64-bit)

**Operating system:**
macOS Sierra v10.12.6

#### Web server error log
For data privacy reasons of my users, I can't share this.

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #6089

### CODE REVIEW

File: settings/Controller/UsersController.php [hunk 1]
```diff
@@ -437,7 +437,9 @@ public function create($username, $password, array $groups = [], $email = '') {
 				);
 			}
 
-			$password = $this->secureRandom->generate(32);
+			$password = $this->secureRandom->generate(30);
+			// Make sure we pass the password_policy
+			$password .= $this->secureRandom->generate(2, '$!.,;:-~+*[]{}()');
```
Comment (nickvergessen) [inline settings/Controller/UsersController.php]: Didn't use `CHAR_SYMBOLS` because I want people to be able to enter it easy enough on their first login.
But on the other hand most people will just copy paste the 32 chars anyway, right?

**Review by MorrisJobke — APPROVED** [review]

File: settings/Controller/UsersController.php (hunk 1 above)
Comment (rullzer) [reply settings/Controller/UsersController.php]: Entropy wise this isn't really best practice. As now the final 2 chars are very limited.

However with 30 random chars before it should be fine.

**Review by blizzz — APPROVED** [review]

**Review by LukasReschke — APPROVED** [review]
