### PR TITLE
Fix installer deprecation warnings for PHP 8

### LINKED ISSUE #26745: Deprecated warnings for PHP 8 at /lib/private/Installer.php
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour

no logged error

### Actual behaviour

Log full of following combination of 3 times **error PHP**

**Error:** Function libxml_disable_entity_loader() is deprecated at /var/www/nextcloud/lib/private/Installer.php#346

1. */var/www/nextcloud/lib/private/Installer.php - line 346:*
   OC\Log\ErrorHandler::onError()

2. */var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php - line 445:*
   OC\Installer->downloadApp()

3. */var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 218:*
   OCA\Settings\Controller\AppSettingsController->enableApps()

4. */var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 127:*
   OC\AppFramework\Http\Dispatcher->executeController()

5. */var/www/nextcloud/lib/private/AppFramework/App.php - line 157:*
   OC\AppFramework\Http\Dispatcher->dispatch()

6. */var/www/nextcloud/lib/private/Route/Router.php - line 302:*
   OC\AppFramework\App::main()

7. */var/www/nextcloud/lib/base.php - line 993:*
   OC\Route\Router->match()

8. */var/www/nextcloud/index.php - line 37:*
   OC::handleRequest()

**Error:** Function libxml_disable_entity_loader() is deprecated at /var/www/nextcloud/lib/private/Installer.php#344

1. */var/www/nextcloud/lib/private/Installer.php - line 344:*
   OC\Log\ErrorHandler::onError()

2. */var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php - line 445:*
   OC\Installer->downloadApp()

3. */var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 218:*
   OCA\Settings\Controller\AppSettingsController->enableApps()

4. */var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 127:*
   OC\AppFramework\Http\Dispatcher->executeController()

5. */var/www/nextcloud/lib/private/AppFramework/App.php - line 157:*
   OC\AppFramework\Http\Dispatcher->dispatch()

6. */var/www/nextcloud/lib/private/Route/Router.php - line 302:*
   OC\AppFramework\App::main()

7. */var/www/nextcloud/lib/base.php - line 993:*
   OC\Route\Router->match()

8. */var/www/nextcloud/index.php - line 37:*
   OC::handleRequest()

**Error:** Function openssl_free_key() is deprecated at /var/www/nextcloud/lib/private/Installer.php#312

1. */var/www/nextcloud/lib/private/Installer.php - line 312:*
   OC\Log\ErrorHandler::onError()

2. */var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php - line 445:*
   OC\Installer->downloadApp()

3. */var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 218:*
   OCA\Settings\Controller\AppSettingsController->enableApps()

4. */var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 127:*
   OC\AppFramework\Http\Dispatcher->executeController()

5. */var/www/nextcloud/lib/private/AppFramework/App.php - line 157:*
   OC\AppFramework\Http\Dispatcher->dispatch()

6. */var/www/nextcloud/lib/private/Route/Router.php - line 302:*
   OC\AppFramework\App::main()

7. */var/www/nextcloud/lib/base.php - line 993:*
   OC\Route\Router->match()

8. */var/www/nextcloud/index.php - line 37:*
   OC::handleRequest()

### Server configuration

see #26743

### PR DESCRIPTION
**Pull request by solracsf**
Only use `libxml_disable_entity_loader` on PHP<8
PHP 8+ deprecates `openssl_free_key`

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

File: lib/private/Installer.php [hunk 1]
```diff
@@ -339,9 +342,13 @@ public function downloadApp($appId, $allowUnstable = false) {
 						}
 
 						// Check if appinfo/info.xml has the same app ID as well
-						$loadEntities = libxml_disable_entity_loader(false);
-						$xml = simplexml_load_file($extractDir . '/' . $folders[0] . '/appinfo/info.xml');
-						libxml_disable_entity_loader($loadEntities);
+						if ((PHP_VERSION_ID < 80000)) {
+							$loadEntities = libxml_disable_entity_loader(false);
```
Comment (nickvergessen) [inline lib/private/Installer.php:346]: @LukasReschke  can you haz a look?

Comment (LukasReschke) [reply lib/private/Installer.php:346]: https://github.com/php/php-src/blob/php-8.0.0/UPGRADING#L877-L879

```
- LibXML:
  . libxml_disable_entity_loader() has been deprecated. As libxml 2.9.0 is now
    required, external entity loading is guaranteed to be disabled by default,
    and this function is no longer needed to protect against XXE attacks.
```

**Review by LukasReschke — APPROVED** [review]
