### PR TITLE
Fix Calendarsubscriptions source column change on Oracle

### LINKED ISSUE #11975: Installing on oracle fails
Regression from #11668 

Ref owncloud/core#15058

```json
{
  "reqId": "56EAuClJtPPLv3gQMBT0",
  "level": 3,
  "time": "2018-10-22T09:28:17+02:00",
  "remoteAddr": "",
  "user": "--",
  "app": "index",
  "method": "",
  "url": "--",
  "message": {
    "Exception": "Doctrine\\DBAL\\Exception\\DriverException",
    "Message": "An exception occurred while executing 'ALTER TABLE \"oc_calendarsubscriptions\" MODIFY (\"source\" CLOB DEFAULT NULL)':\n\nORA-22858: invalid alteration of datatype",
    "Code": 0,
    "Trace": [
      {
        "file": "\/home\/travis\/build\/nextcloud\/server\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php",
        "line": 128,
        "function": "convertException",
        "class": "Doctrine\\DBAL\\Driver\\AbstractOracleDriver",
        "type": "->",
        "args": [
          "An exception occurred while executing 'ALTER TABLE \"oc_calendarsubscriptions\" MODIFY (\"source\" CLOB DEFAULT NULL)':\n\nORA-22858: invalid alteration of datatype",
          {
            "xdebug_message": "\nDoctrine\\DBAL\\Driver\\OCI8\\OCI8Exception: ORA-22858: invalid alteration of datatype in \/home\/travis\/build\/nextcloud\/server\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/OCI8\/OCI8Exception.php on line 33\n\nCall Stack:\n    0.0002     386064   1. {main}() \/home\/travis\/build\/nextcloud\/server\/index.php:0\n    0.0465    6985384   2. OC::handleRequest() \/home\/travis\/build\/nextcloud\/server\/index.php:42\n    0.0470    7068400   3. OC\\Core\\Controller\\SetupController->run() \/home\/travis\/build\/nextcloud\/server\/lib\/base.php:925\n    0.0474    7071488   4. OC\\Setup->install() \/home\/travis\/build\/nextcloud\/server\/core\/Controller\/SetupController.php:67\n   60.0539   10965304   5. OC\\Installer::installShippedApps() \/home\/travis\/build\/nextcloud\/server\/lib\/private\/Setup.php:386\n   76.9131   11809872   6. OC\\Installer::installShippedApp() \/home\/travis\/build\/nextcloud\/server\/lib\/private\/Installer.php:524\n   76.9144   11874672   7. OC\\DB\\MigrationService->migrate() \/home\/travis\/build\/nextcloud\/server\/lib\/private\/Installer.php:561\n  141.8350   12312144   8. OC\\DB\\MigrationService->executeStep() \/home\/travis\/build\/nextcloud\/server\/lib\/private\/DB\/MigrationService.php:392\n  157.0663   12674600   9. OC\\DB\\OracleConnection->migrateToSchema() \/home\/travis\/build\/nextcloud\/server\/lib\/private\/DB\/MigrationService.php:462\n  157.0664   12674784  10. OC\\DB\\OracleMigrator->migrate() \/home\/travis\/build\/nextcloud\/server\/lib\/private\/DB\/Connection.php:446\n  157.0664   12674784  11. OC\\DB\\OracleMigrator->applySchema() \/home\/travis\/build\/nextcloud\/server\/lib\/private\/DB\/Migrator.php:83\n  172.2809   13035944  12. OC\\DB\\OracleConnection->query() \/home\/travis\/build\/nextcloud\/server\/lib\/private\/DB\/Migrator.php:260\n  172.2809   13036320  13. Doctrine\\DBAL\\Driver\\OCI8\\OCI8Connection->query() \/home\/travis\/build\/nextcloud\/server\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php:954\n  172.2810   13037200  14. Doctrine\\DBAL\\Driver\\OCI8\\OCI8Statement->execute() \/home\/travis\/build\/nextcloud\/server\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/OCI8\/OCI8Connection.php:116\n",
            "__class__": "Doctrine\\DBAL\\Driver\\OCI8\\OCI8Exception"
          }
        ]
      },
      {
        "file": "\/home\/travis\/build\/nextcloud\/server\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php",
        "line": 964,
        "function": "driverExceptionDuringQuery",
        "class": "Doctrine\\DBAL\\DBALException",
        "type": "::",
        "args": [
          {
            "__class__": "Doctrine\\DBAL\\Driver\\OCI8\\Driver"
          },
          {
            "xdebug_message": "\nDoctrine\\DBAL\\Driver\\OCI8\\OCI8Exception: ORA-22858: invalid alteration of datatype in \/home\/travis\/build\/nextcloud\/server\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/OCI8\/OCI8Exception.php on line 33\n\nCall Stack:\n    0.0002     386064   1. {main}() \/home\/travis\/build\/nextcloud\/server\/index.php:0\n    0.0465    6985384   2. OC::handleRequest() \/home\/travis\/build\/nextcloud\/server\/index.php:42\n    0.0470    7068400   3. OC\\Core\\Controller\\SetupController->run() \/home\/travis\/build\/nextcloud\/server\/lib\/base.php:925\n    0.0474    7071488   4. OC\\Setup->install() \/home\/travis\/build\/nextcloud\/server\/core\/Controller\/SetupController.php:67\n   60.0539   10965304   5. OC\\Installer::installShippedApps() \/home\/travis\/build\/nextcloud\/server\/lib\/private\/Setup.php:386\n   76.9131   11809872   6. OC\\Installer::installShippedApp() \/home\/travis\/build\/nextcloud\/server\/lib\/private\/Installer.php:524\n   76.9144   11874672   7. OC\\DB\\MigrationService->migrate() \/home\/travis\/build\/nextcloud\/server\/lib\/private\/Installer.php:561\n  141.8350   12312144   8. OC\\DB\\MigrationService->executeStep() \/home\/travis\/build\/nextcloud\/server\/lib\/private\/DB\/MigrationService.php:392\n  157.0663   12674600   9. OC\\DB\\OracleConnection->migrateToSchema() \/home\/travis\/build\/nextcloud\/server\/lib\/private\/DB\/MigrationService.php:462\n  157.0664   12674784  10. OC\\DB\\OracleMigrator->migrate() \/home\/travis\/build\/nextcloud\/server\/lib\/private\/DB\/Connection.php:446\n  157.0664   12674784  11. OC\\DB\\OracleMigrator->applySchema() \/home\/travis\/build\/nextcloud\/server\/lib\/private\/DB\/Migrator.php:83\n  172.2809   13035944  12. OC\\DB\\OracleConnection->query() \/home\/travis\/build\/nextcloud\/server\/lib\/private\/DB\/Migrator.php:260\n  172.2809   13036320  13. Doctrine\\DBAL\\Driver\\OCI8\\OCI8Connection->query() \/home\/travis\/build\/nextcloud\/server\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php:954\n  172.2810   13037200  14. Doctrine\\DBAL\\Driver\\OCI8\\OCI8Statement->execute() \/home\/travis\/build\/nextcloud\/server\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/OCI8\/OCI8Connection.php:116\n",
            "__class__": "Doctrine\\DBAL\\Driver\\OCI8\\OCI8Exception"
          },
          "ALTER TABLE \"oc_calendarsubscriptions\" MODIFY (\"source\" CLOB DEFAULT NULL)"
        ]
      },
      {
        "file": "\/home\/travis\/build\/nextcloud\/server\/lib\/private\/DB\/Migrator.php",
        "line": 260,
        "function": "query",
        "class": "Doctrine\\DBAL\\Connection",
        "type": "->",
        "args": [
          "ALTER TABLE \"oc_calendarsubscriptions\" MODIFY (\"source\" CLOB DEFAULT NULL)"
        ]
      }
      ],
      "File": "\/home\/travis\/build\/nextcloud\/server\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/OCI8\/OCI8Exception.php",
      "Line": 33
    },
    "CustomMessage": "--"
  },
  "userAgent": "--",
  "version": "15.0.0.1"
}
```

### PR DESCRIPTION
**Pull request by georgehrke**
fixes #11975

### CODE REVIEW

File: apps/dav/lib/Migration/Version1008Date20181105104826.php [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+	/**
+	 * @param IOutput $output
+	 * @param Closure $schemaClosure The `\Closure` returns a `ISchemaWrapper`
+	 * @param array $options
+	 * @return null|ISchemaWrapper
+	 */
+	public function changeSchema(IOutput $output, Closure $schemaClosure, array $options) {
+		/** @var ISchemaWrapper $schema */
+		$schema = $schemaClosure();
+		if (!$schema->hasTable('calendarsubscriptions')) {
```
Comment (ChristophWurst) [inline apps/dav/lib/Migration/Version1008Date20181105104826.php]: We had this discussion in another PR recently (with @skjnldsv and @MorrisJobke if I recall). I don't see how that condition could ever evaluate to `true`. Just assume that the previous migrations were run and the table exists.

File: apps/dav/lib/Migration/Version1008Date20181105104826.php [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+			return $schema;
+		}
+
+		$table = $schema->getTable('calendarsubscriptions');
+		$column = $table->getColumn('source');
+		if ($column->getLength() === null) {
```
Comment (ChristophWurst) [inline apps/dav/lib/Migration/Version1008Date20181105104826.php]: When does that happen?

File: apps/dav/lib/Migration/Version1008Date20181105104833.php [hunk 3]
```diff
@@ -0,0 +1,39 @@
...
+	/**
+	 * @param IOutput $output
+	 * @param Closure $schemaClosure The `\Closure` returns a `ISchemaWrapper`
+	 * @param array $options
+	 * @return null|ISchemaWrapper
+	 */
+	public function changeSchema(IOutput $output, Closure $schemaClosure, array $options) {
+		/** @var ISchemaWrapper $schema */
+		$schema = $schemaClosure();
+		if (!$schema->hasTable('calendarsubscriptions')) {
```
Comment (ChristophWurst) [inline apps/dav/lib/Migration/Version1008Date20181105104833.php]: same as above

File: apps/dav/lib/Migration/Version1008Date20181105104833.php [hunk 4]
```diff
@@ -0,0 +1,39 @@
...
+			return $schema;
+		}
+
+		$table = $schema->getTable('calendarsubscriptions');
+		if (!$table->hasColumn('source_copy')) {
```
Comment (ChristophWurst) [inline apps/dav/lib/Migration/Version1008Date20181105104833.php]: just assume it's there

File: apps/dav/lib/Migration/Version1008Date20181105110300.php [hunk 5]
```diff
@@ -0,0 +1,69 @@
...
+	 */
+	public function changeSchema(IOutput $output, Closure $schemaClosure, array $options) {
+		/** @var ISchemaWrapper $schema */
+		$schema = $schemaClosure();
+		if (!$schema->hasTable('calendarsubscriptions')) {
+			return $schema;
+		}
+
+		$table = $schema->getTable('calendarsubscriptions');
+		if ($table->hasColumn('source') || !$table->hasColumn('source_copy')) {
```
Comment (ChristophWurst) [inline apps/dav/lib/Migration/Version1008Date20181105110300.php]: just assume they are there

File: apps/dav/lib/Migration/Version1008Date20181105112049.php [hunk 6]
```diff
@@ -0,0 +1,39 @@
...
+	/**
+	 * @param IOutput $output
+	 * @param Closure $schemaClosure The `\Closure` returns a `ISchemaWrapper`
+	 * @param array $options
+	 * @return null|ISchemaWrapper
+	 */
+	public function changeSchema(IOutput $output, Closure $schemaClosure, array $options) {
+		/** @var ISchemaWrapper $schema */
+		$schema = $schemaClosure();
+		if (!$schema->hasTable('calendarsubscriptions')) {
```
Comment (ChristophWurst) [inline apps/dav/lib/Migration/Version1008Date20181105112049.php]: same as above

File: apps/dav/lib/Migration/Version1008Date20181105112049.php [hunk 7]
```diff
@@ -0,0 +1,39 @@
...
+			return $schema;
+		}
+
+		$table = $schema->getTable('calendarsubscriptions');
+		if (!$table->hasColumn('source_copy')) {
```
Comment (ChristophWurst) [inline apps/dav/lib/Migration/Version1008Date20181105112049.php]: once again :see_no_evil:

File: apps/dav/lib/Migration/Version1007Date20181007225117.php [hunk 8]
```diff
@@ -1,54 +0,0 @@
...
-
-class Version1007Date20181007225117 extends SimpleMigrationStep {
-
-	/**
-	 * @param IOutput $output
-	 * @param Closure $schemaClosure The `\Closure` returns a `ISchemaWrapper`
-	 * @param array $options
-	 * @return null|ISchemaWrapper
-	 */
-	public function changeSchema(IOutput $output, Closure $schemaClosure, array $options) {
```
Comment (ChristophWurst) [inline apps/dav/lib/Migration/Version1007Date20181007225117.php]: Why did you remove this previous migration? IMO migrations should be removed unless they have known bugs that prevent them from running.

**Review by ChristophWurst — DISMISSED** [review]

File: apps/dav/lib/Migration/Version1007Date20181007225117.php (hunk 8 above)
Comment (ChristophWurst) [reply apps/dav/lib/Migration/Version1007Date20181007225117.php]: Okay, so (obviously) this migration triggers https://github.com/nextcloud/server/issues/11975. Is it still safe to remove the class in that case, @nickvergessen?

An alternative would be to just make it a NOP.

File: apps/dav/appinfo/info.xml [hunk 9]
```diff
@@ -5,7 +5,7 @@
 	<name>WebDAV</name>
 	<summary>WebDAV endpoint</summary>
 	<description>WebDAV endpoint</description>
-	<version>1.7.2</version>
+	<version>1.8.0</version>
```
Comment (nickvergessen) [inline apps/dav/appinfo/info.xml]: 1.7.3 should be fine, I increase it directly after each major release :see_no_evil:

File: apps/dav/lib/Migration/Version1008Date20181105104826.php [hunk 10]
```diff
@@ -0,0 +1,70 @@
...
+	 * @param IOutput $output
+	 * @param Closure $schemaClosure The `\Closure` returns a `ISchemaWrapper`
+	 * @param array $options
+	 * @return null|ISchemaWrapper
+	 */
+	public function changeSchema(IOutput $output, Closure $schemaClosure, array $options) {
+		/** @var ISchemaWrapper $schema */
+		$schema = $schemaClosure();
+		if (!$schema->hasTable('calendarsubscriptions')) {
+			return $schema;
```
Comment (nickvergessen) [inline apps/dav/lib/Migration/Version1008Date20181105104826.php]: return null instead so we know it didnt change and dont need to do anything

File: apps/dav/lib/Migration/Version1008Date20181105104826.php [hunk 11]
```diff
@@ -0,0 +1,70 @@
...
+		}
+
+		$table = $schema->getTable('calendarsubscriptions');
+		$column = $table->getColumn('source');
+		if ($column->getLength() === null) {
+			return $schema;
```
Comment (nickvergessen) [inline apps/dav/lib/Migration/Version1008Date20181105104826.php]: return null instead so we know it didnt change and dont need to do anything

**Review by nickvergessen — DISMISSED** [review]

File: apps/dav/lib/Migration/Version1007Date20181007225117.php (hunk 8 above)
Comment (nickvergessen) [reply apps/dav/lib/Migration/Version1007Date20181007225117.php]: It has to be removed, otherwise Oracle can never install again.

I guess NOP would also work, but well since the migration service doesnt care, I guess removing is the better idea

**Comment by georgehrke** [comment]
Set version to `1.7.3` and removed the extra checks.

File: apps/dav/lib/Migration/Version1008Date20181105104826.php [hunk 12]
```diff
@@ -0,0 +1,62 @@
...
+
+use Closure;
+use Doctrine\DBAL\Types\Type;
+use OCP\DB\ISchemaWrapper;
+use OCP\IDBConnection;
+use OCP\Migration\SimpleMigrationStep;
+use OCP\Migration\IOutput;
+
+/**
+ * Auto-generated migration step: Please modify to your needs!
```
Comment (ChristophWurst) [inline apps/dav/lib/Migration/Version1008Date20181105104826.php]: kill with :fire:

File: apps/dav/lib/Migration/Version1008Date20181105104833.php [hunk 13]
```diff
@@ -0,0 +1,31 @@
...
+
+namespace OCA\DAV\Migration;
+
+use Closure;
+use OCP\DB\ISchemaWrapper;
+use OCP\Migration\SimpleMigrationStep;
+use OCP\Migration\IOutput;
+
+/**
+ * Auto-generated migration step: Please modify to your needs!
```
Comment (ChristophWurst) [inline apps/dav/lib/Migration/Version1008Date20181105104833.php]: :fire:

File: apps/dav/lib/Migration/Version1008Date20181105110300.php [hunk 14]
```diff
@@ -0,0 +1,61 @@
...
+
+use Closure;
+use Doctrine\DBAL\Types\Type;
+use OCP\DB\ISchemaWrapper;
+use OCP\IDBConnection;
+use OCP\Migration\SimpleMigrationStep;
+use OCP\Migration\IOutput;
+
+/**
+ * Auto-generated migration step: Please modify to your needs!
```
Comment (ChristophWurst) [inline apps/dav/lib/Migration/Version1008Date20181105110300.php]: :fire:

**Review by ChristophWurst — CHANGES_REQUESTED** [review]
If possible I'd suggest to do a column rename instead of the second copy. Apart from that it looks good!

File: apps/dav/lib/Migration/Version1008Date20181105110300.php [hunk 15]
```diff
@@ -0,0 +1,58 @@
...
+	 * @param IOutput $output
+	 * @param Closure $schemaClosure The `\Closure` returns a `ISchemaWrapper`
+	 * @param array $options
+	 * @return null|ISchemaWrapper
+	 */
+	public function changeSchema(IOutput $output, Closure $schemaClosure, array $options) {
+		/** @var ISchemaWrapper $schema */
+		$schema = $schemaClosure();
+		$table = $schema->getTable('calendarsubscriptions');
+		$table->addColumn('source', Type::TEXT, [
```
Comment (ChristophWurst) [inline apps/dav/lib/Migration/Version1008Date20181105110300.php]: (somehow one of my review comments got lost) please use `$table->renameColumn` if possible. This was also suggested at https://stackoverflow.com/questions/13402510/oracle-changing-varchar2-column-to-clob and I guess is faster for DBs to execute than copy a full column.

**Review by ChristophWurst — CHANGES_REQUESTED** [review]

**Comment by georgehrke** [comment]
> If possible I'd suggest to do a column rename instead of the second copy. Apart from that it looks good!

Doctrine doesn't support that. It would simply delete the column and create a new empty one

**Comment by georgehrke** [comment]
See https://github.com/nextcloud/3rdparty/blob/b995ca8b8c7f69a180ad6fb49989ad3e35b1367e/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php#L340

**Review by ChristophWurst — APPROVED** [review]
Looks good!

**Comment by nickvergessen** [comment]
> I just realized the naming of the files is : Version1008Datexxx which probably means version 10.0.8. 

No, if the version is `X.Y.Z` the migration name is `XXXYYY` without leading zeros

File: apps/dav/lib/Migration/Version1008Date20181105104826.php [hunk 16]
```diff
@@ -0,0 +1,59 @@
...
+use OCP\Migration\SimpleMigrationStep;
+use OCP\Migration\IOutput;
+
+class Version1008Date20181105104826 extends SimpleMigrationStep {
+
+	/** @var IDBConnection */
+	private $connection;
+
+	/**
+	 * Version1007Date20181007225117 constructor.
```
Comment (blizzz) [inline apps/dav/lib/Migration/Version1008Date20181105104826.php]: :thinking:

**Review by skjnldsv — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Rebased to fix conflicts in autoloader.

File: apps/dav/lib/Migration/Version1008Date20181105104826.php [hunk 17]
```diff
@@ -0,0 +1,59 @@
+<?php
+
+declare(strict_types=1);
```
Comment (MorrisJobke) [inline apps/dav/lib/Migration/Version1008Date20181105104826.php]: There are license headers missing in all migration files 🙈
