### PR TITLE
Fix: Birthday calendar issue with shared calendars

### LINKED ISSUE #3914: Birthdays: some show up, some don’t
### Steps to reproduce
We have a shared address book and enter birthday dates via the date picker. 

### Expected behaviour
all birthdays show up

### Actual behaviour
Some birthdays show up in the birthday calendar, some don’t.
For the contacts whose birthdays don’t show up in calendar, it does not even help to change their birthday in the contacts webinterface nor in Thunderbird Cardbook. They just won’t show up at all.

I downloaded the birthday calendar as calDAV and looked for differences:

**Birthdays that show up as expected**
all the examples I saw were VERSION:3.0
some were PRODID;VALUE=TEXT:-//Thunderbird.net/NONSGML Thunderbird CardBook V37.6//DE
some were PRODID:-//Sabre//Sabre VObject 4.1.6//EN

**Birthdays that don't show up as expected**
some were VERSION:4.0
some were VERSION:3.0
some were PRODID:-//Nextcloud Contacts v3.5.1
some were PRODID:-//Sabre//Sabre VObject 4.1.6//EN

### Calendar app
**Calendar app version:** Calendar 3.0.2

### Client configuration
**Browser:** Firefox 96.0.1 

### Server configuration
**Nextcloud Version:** 22.2.3

Any ideas? Any other info you need?

I already asked here but did not get a solution https://help.nextcloud.com/t/birthdays-some-show-up-some-dont/130870

### PR DESCRIPTION
**Pull request by max65482**
Fixes [#3914](https://github.com/nextcloud/calendar/issues/3914) in nextcloud/calendar.

My understanding is that `{http://owncloud.org/ns}group-share` is wrongly assigned. It is `false` although an address book is shared with a group.

This leads the BirthdayService to not update birthday calendars of group members. See
https://github.com/nextcloud/server/blob/d2289519a3284f89f264de4d14aed565b66c46d7/apps/dav/lib/CalDAV/BirthdayService.php#L356

I must admit that I don't really understand the rationale of `{http://owncloud.org/ns}group-share`. So please review carefully :)

### CODE REVIEW

**Comment by tcitworld** [comment]
Seems a good idea but also seems to have a lot of side effects. :thinking:

**Comment by max65482** [comment]
I don't get how
`'{http://owncloud.org/ns}group-share' => is_null($p)`
was supposed to work in the first place.

`{http://owncloud.org/ns}group-share` indicates if something is shared with a group, right? In the error case, an address book was shared with a group and `{http://owncloud.org/ns}group-share` was false.

**Comment by max65482** [comment]
> seems to have a lot of side effects

I cannot find `{http://owncloud.org/ns}group-share` being used anywhere but in the BirthdayService (see my first comment) and tests.

**Comment by tcitworld** [comment]
I was referring to the failed tests, didn't get a chance to look at this yet.

**Comment by max65482** [comment]
Ok, fixed the problem. Let's see what the tests say now.

**Comment by demlak** [comment]
i tried to implement it.. get this error:

`[PHP] Error: Trying to access array offset on value of type null at /var/www/html/apps/dav/lib/DAV/Sharing/Backend.php#210`

this is line 210 right now:
`'{http://owncloud.org/ns}group-share' => substr_compare($p['uri'], 'principals/groups', 0, strlen('principals/groups')) === 0`

**Comment by max65482** [comment]
Are you sure you checked out the latest commit?
This looks like you are working with the previous commit. With that, the tests failed due to the null reference.
With the latest commit this is resolved.

**Comment by demlak** [comment]
thx.. you are correct.. my fault

File: apps/dav/lib/DAV/Sharing/Backend.php [hunk 1]
```diff
@@ -206,7 +206,7 @@ public function getShares($resourceId) {
 				'status' => 1,
 				'readOnly' => (int) $row['access'] === self::ACCESS_READ,
 				'{http://owncloud.org/ns}principal' => $row['principaluri'],
-				'{http://owncloud.org/ns}group-share' => is_null($p)
+				'{http://owncloud.org/ns}group-share' => isset($p['uri']) ? (substr_compare($p['uri'], 'principals/groups', 0, strlen('principals/groups')) === 0) : false
```
Comment (tcitworld) [inline apps/dav/lib/DAV/Sharing/Backend.php:209]: **suggestion:** Avoid `strlen` calculation each time.
```suggestion
                // 17 is the length of "principals/groups"
				'{http://owncloud.org/ns}group-share' => isset($p['uri']) ? (substr_compare($p['uri'], 'principals/groups', 0, 17) === 0) : false
```

**Review by tcitworld — APPROVED** [review]

File: apps/dav/lib/DAV/Sharing/Backend.php (hunk 1 above)
Comment (tcitworld) [reply apps/dav/lib/DAV/Sharing/Backend.php:209]: Nowdays `str_starts_with` would be more appropriate, but it would require to change backports for PHP < 8.0 compat.

Comment (max65482) [reply apps/dav/lib/DAV/Sharing/Backend.php]: > Avoid strlen calculation each time.

done

File: apps/dav/lib/DAV/Sharing/Backend.php [hunk 2]
```diff
@@ -206,7 +206,8 @@ public function getShares($resourceId) {
 				'status' => 1,
 				'readOnly' => (int) $row['access'] === self::ACCESS_READ,
 				'{http://owncloud.org/ns}principal' => $row['principaluri'],
-				'{http://owncloud.org/ns}group-share' => is_null($p)
+                // 17 is the length of "principals/groups"
+				'{http://owncloud.org/ns}group-share' => isset($p['uri']) ? (substr_compare($p['uri'], 'principals/groups', 0, 17) === 0) : false
```
Comment (come-nc) [inline apps/dav/lib/DAV/Sharing/Backend.php:210]:
```suggestion
				'{http://owncloud.org/ns}group-share' => isset($p['uri']) ? str_starts_with($p['uri'], 'principals/groups') : false
```

**Review by come-nc — COMMENTED** [review]
Small comment about the code, but I do not understand what this does and the implications.

File: apps/dav/lib/DAV/Sharing/Backend.php (hunk 1 above)
Comment (come-nc) [reply apps/dav/lib/DAV/Sharing/Backend.php]: > Nowdays `str_starts_with` would be more appropriate, but it would require to change backports for PHP < 8.0 compat.

We have a polyfill for it on older versions, so we can use it.

File: apps/dav/lib/DAV/Sharing/Backend.php (hunk 2 above)
Comment (max65482) [reply apps/dav/lib/DAV/Sharing/Backend.php]: Done

Comment (tcitworld) [reply apps/dav/lib/DAV/Sharing/Backend.php]: @come-nc That won't be backportable though, as `str_starts_with` is PHP 8.0+ only.

Comment (come-nc) [reply apps/dav/lib/DAV/Sharing/Backend.php]: We have a polyfill for it in symfony/polyfill

Comment (tcitworld) [reply apps/dav/lib/DAV/Sharing/Backend.php]: TIL, thanks!

**Review by miaulalala — APPROVED** [review]

**Comment by miaulalala** [comment]
@max65482 please rebase :)

**Comment by max65482** [comment]
Done!
