### PR TITLE
Fix installing Talk due to hardcoded route

### LINKED ISSUE #2806: Cannot declare class OCA\Talk\Migration\Version2000Date20170707093535
## Steps to reproduce
1. Install a fresh nextcloud 18.0.0.10 (latest current version)
2. Try to install Talk app
3. Check errors in nextcloud logs

{"reqId":"Xia6aNr0WbUmo-qoephJHQAAANM","level":3,"time":"2020-01-21T08:46:34+00:00","remoteAddr":"xx.xx.85.194","user":"******","app":"PHP","method":"POST","url":"/settings/apps/enable","message":"Cannot declare class OCA\\Talk\\Migration\\Version2000Date20170707093535, because the name is already in use at /var/www/html/nextcloud/apps/spreed/lib/Migration/Version2000Date20170707093535.php#31","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36","version":"18.0.0.10","id":"5e26ba7581626"}

**Operating system**: Centos 8

**Web server:** Apache

**Database:** Maria

**PHP version:** PHP 7.4.1 (cli)

**Nextcloud Version:** 18.0.0.10

Thanks for your help.

### PR DESCRIPTION
**Pull request by nickvergessen**
Due to the hardcoded routes in https://github.com/nextcloud/server/blob/302558cfd2b3dd37e6332c0d9c650174b64f20fb/core/routes.php#L98-L99 the spreed appid is registered with the namespace `Spreed` when it is not installed.

Now when the app is installed, it breaks because it tries to find the migration files in the MigrationService as it is searching with the wrong namespace because it was setup with the broken namespace. 

Fix https://github.com/nextcloud/spreed/issues/2806

### CODE REVIEW

**Comment by nickvergessen** [comment]
Alternate approach would be to copy the hardcoded problem into ` lib/private/AppFramework/App.php`:
```diff
diff --git a/lib/private/AppFramework/App.php b/lib/private/AppFramework/App.php
index 3fed3945e1..7b93b630ba 100644
--- a/lib/private/AppFramework/App.php
+++ b/lib/private/AppFramework/App.php
@@ -70,7 +70,11 @@ class App {
                        self::$nameSpaceCache[$appId] = trim($appInfo['namespace']);
                } else {
                        // if the tag is not found, fall back to uppercasing the first letter
-                       self::$nameSpaceCache[$appId] = ucfirst($appId);
+                       if ($appId === 'spreed') {
+                               self::$nameSpaceCache[$appId] = 'Talk';
+                       } else {
+                               self::$nameSpaceCache[$appId] = ucfirst($appId);
+                       }
                }
 
                return $topNamespace . self::$nameSpaceCache[$appId];
```

That would make sure nothing is set up with a wrong namespace before. But in case any app later on gets hardcoded too and has a non-default namespace, it will require the additional hack as well.

On the other hand, I'm not sure what the wrongly registered route means. Could it break stuff at somepoint when we do something while installing?

**Comment by ChristophWurst** [comment]
> Alternate approach would be to copy the hardcoded problem

Fine by me to do it this way.

**Comment by nickvergessen** [comment]
Another option would be to wrap:
https://github.com/nextcloud/server/blob/5bf3d1bb384da56adbf205752be8f840aac3b0c5/lib/private/AppFramework/Routing/RouteConfig.php#L173
with a check if the app is actually installed. should also prevent us from saving a wrong namespace, but makes the route unavailable for that request

File: lib/private/AppFramework/App.php [hunk 1]
```diff
@@ -69,7 +69,11 @@ public static function buildAppNamespace(string $appId, string $topNamespace='OC
 			self::$nameSpaceCache[$appId] = trim($appInfo['namespace']);
 		} else {
 			// if the tag is not found, fall back to uppercasing the first letter
-			self::$nameSpaceCache[$appId] = ucfirst($appId);
+			if ($appId === 'spreed') {
```
Comment (ChristophWurst) [inline lib/private/AppFramework/App.php]: Mind adding a bit of explanation here as a comment? I'm sure someone finding this code in the future will be grateful for that :)

Comment (nickvergessen) [reply lib/private/AppFramework/App.php]: Done

**Review by ChristophWurst — APPROVED** [review]

**Review by danxuliu — APPROVED** [review]
Tested and works :+1:

**Comment by tobby88** [comment]
This does not fix #19102 - see comments over there. Can you reopen the issue please? :)

**Comment by xg590** [comment]
I still got the same problem right now (May 24 2020) with NC 18.0.4.

**Comment by nickvergessen** [comment]
Yes, a complete fix was only possible for Nextcloud 19

**Comment by xg590** [comment]
> Yes, a complete fix was only possible for Nextcloud 19

For me, it is a false warning. 
Running 
```
sudo -u www-data php occ app:install spreed
```
will produce the error. However, the spread works anyhow after enable it.
```
sudo -u www-data php occ app:enable  spreed
```
