### PR TITLE
fix(oauth2): adjust db schemas when migrating from owncloud

### LINKED ISSUE #50186: [Bug]: The schema of `oc_oauth2_access_tokens` is not adjusted properly and its data is not migrated correctly when migrating from ownCloud
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Tokens from the OAuth2 app are not properly migrated when migrating from ownCloud to Nextcloud. There are two major problems:

1. The schema is not adjusted properly. The `token_id` column is missing and the `token` column is superfluous (not dropped).
2. The existing rows in `oc_oauth2_access_tokens` should be migrated properly. Currently, all new columns are just added and populated with empty values, yielding broken tokens which cannot be refreshed any more.

Regarding 2): If I understand the authentication logic correctly, we have to migrate tokens from `oc_oauth2_access_tokens` to `oc_authtoken` and then migrate refresh tokens from `oauth2_refresh_tokens` to `oc_oauth2_access_tokens`. The key difference between both implementations is that the actual authentication tokens are saved in `oc_authtoken` and the refresh tokens are saved inside `oc_oauth2_access_tokens` (encrypted) on our end. And we don't use the table `oauth2_refresh_tokens` any more.

### Steps to reproduce

1. Use ownCloud and set up some OAuth2 clients and access tokens.
2. Migrate to Nextcloud.
3. Try to run repair jobs -> **creates some of the new columns but errors out later:** `token is not a valid attribute` [OCA\OAuth2\Migration\SetTokenExpiration]
4. Try to authenticate from existing clients using previous access tokens -> **fails**
5. Try to refresh existing tokens -> **fails**

### Expected behavior

It should migrate existing access tokens and let me create new clients and tokens.

### Nextcloud Server version

29

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by st3iny**
* Resolves: #50186 

## Summary

See also https://github.com/nextcloud/server/pull/49075

This PR fixes two issues:
1. Not being able to create or auth using OAuth2 clients after migrating from ownCloud.
2. Not being able to refresh legacy tokens from ownCloud after migrating to Nextcloud.

It does not aim to migrate legacy access tokens from ownCloud as this incurs a lot of work and tokens are only valid for an hour. So, it does not make sense as the migration window set by admins is probably longer than their lifetime anyway.

### What I tested

1. Install ownCloud (latest) and install/enable the oauth2 app.
4. Add an oauth2 client, use it to generate an access token and refresh it at least once.
5. Dump related tables: `mysqldump owncloud oc_oauth2_access_tokens oc_oauth2_refresh_tokens oc_oauth2_clients`
6. Import dumped tables into Nextcloud.
7. Reset all oauth2 migrations and drop oauth2 tables (`oc_oauth2_access_tokens`, `oc_oauth2_refresh_tokens` and `oc_oauth2_clients`).
8. Import dumped tables.
9. Migrate oauth2 and run repair steps: `occ migrations:migrate oauth2 && occ maintenance:repair`
10. Refresh the token generated in step 2 using your oauth2 client (might be necessary to adjust the token URL if Nextcloud is on another domain).
11. Observe that the refreshed access token can still be used to log into Nextcloud.

## TODO

- [x] Needs to be tested with a live ownCloud instance (see above)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: lib/private/Repair/Owncloud/MigrateOauthTables.php [hunk 1]
```diff
@@ -157,5 +180,37 @@ public function run(IOutput $output) {
...
 			);
 		$qbDeleteClients->executeStatement();
+
+		// Migrate plain client secrets and widen the column
+		$clientsTable = $schema->getTable('oauth2_clients');
+		if ($clientsTable->getColumn('secret')->getLength() === 64) {
+			$output->info("Migrate client secrets.");
+
+			// Widen the column first
+			$clientsTable->getColumn('secret')->setLength(512);
```
Comment (st3iny) [inline lib/private/Repair/Owncloud/MigrateOauthTables.php:190]: TODO: We are going to have a problem when this migration breaks in the middle. Instead, loop through columns with a value that has 64 chars.

Comment (st3iny) [reply lib/private/Repair/Owncloud/MigrateOauthTables.php]: This code is already implemented properly in a migration.

File: lib/private/Repair.php [hunk 2]
```diff
@@ -167,7 +171,7 @@ public static function getRepairSteps(): array {
 				\OC::$server->getUserManager(),
 				\OC::$server->getConfig()
 			),
-			new MigrateOauthTables(\OC::$server->get(Connection::class)),
+			new MigrateOauthTables(\OC::$server->get(Connection::class), \OC::$server->get(AccessTokenMapper::class), \OC::$server->get(ITokenProvider::class), \OC::$server->get(ISecureRandom::class), \OC::$server->get(ITimeFactory::class), \OC::$server->get(ICrypto::class)),
```
Comment (nickvergessen) [inline lib/private/Repair.php:174]:
```suggestion
			\OC::$server->get(MigrateOauthTables::class),
```

File: lib/private/Repair/Owncloud/MigrateOauthTables.php [hunk 3]
```diff
@@ -37,25 +51,54 @@ public function run(IOutput $output) {
...
 		$table = $schema->getTable('oauth2_access_tokens');
 		if (!$table->hasColumn('hashed_code')) {
 			$table->addColumn('hashed_code', 'string', [
 				'notnull' => true,
 				'length' => 128,
 			]);
+
+			// Regenerate schema after migrating to it
+			$this->db->migrateToSchema($schema->getWrappedSchema());
+			$schema = new SchemaWrapper($this->db);
```
Comment (ChristophWurst) [inline lib/private/Repair/Owncloud/MigrateOauthTables.php:66]: This might take a moment. It might be insightful to write to the output before and after.

**Review by ChristophWurst — COMMENTED** [review]
Looks good so far

File: lib/private/Repair.php (hunk 2 above)
Comment (st3iny) [reply lib/private/Repair.php]: Done

File: lib/private/Repair/Owncloud/MigrateOauthTables.php (hunk 3 above)
Comment (st3iny) [reply lib/private/Repair/Owncloud/MigrateOauthTables.php:65]: I added an output inside the if block and one right after.

**Review by ChristophWurst — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Comment by st3iny** [comment]
/backport to stable29

Let's recreate the backport as it was incomplete.
