### PR TITLE
fix(ooo): add new ooo status with new emoji

### LINKED ISSUE #42300: [Bug]: OOO always saves the :palm_tree: emoji
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The Out of Office Automation always sets the :palm_tree: emoji

### Steps to reproduce

1. Set an OOO automation because you are sick
2. See the status being saved as vacation :palm_tree: 

### Expected behavior

When i set up my OOO i cannot choose an emoji, so maybe not show an emoji at all, or i should be able to select one that fits the absence reason.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info
Screenshot from 2023-12-15 09-03-14

_No response_

### PR DESCRIPTION
**Pull request by miaulalala**
* Fixes https://github.com/nextcloud/server/issues/42300

## Summary
The OOO status set the predefined vacation status which is awkward when you're out sick :sneezing_face: 

| Before | After |
|--------|--------|
|  image | image | 

It also solves the issue of an automation not running at all when the `last_run` timestamp is in the future.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by GretaD — APPROVED** [review]
looks better

File: lib/public/UserStatus/IUserStatus.php [hunk 1]
```diff
@@ -81,6 +81,12 @@ interface IUserStatus {
 	 */
 	public const MESSAGE_AVAILABILITY = 'availability';
 
+	/**
+	 * @var string
+	 * @since 25.0.0
```
Comment (nickvergessen) [inline lib/public/UserStatus/IUserStatus.php:86]: nop

Comment (miaulalala) [reply lib/public/UserStatus/IUserStatus.php:86]: i cri evry tim

File: lib/public/UserStatus/IUserStatus.php [hunk 2]
```diff
@@ -81,6 +81,12 @@ interface IUserStatus {
 	 */
 	public const MESSAGE_AVAILABILITY = 'availability';
 
+	/**
+	 * @var string
+	 * @since 28.0.1
```
Comment (nickvergessen) [inline lib/public/UserStatus/IUserStatus.php:86]:
```suggestion
	 * @since 28.0.2
```

**Review by nickvergessen — CHANGES_REQUESTED** [review]
All good apart from the version in the docs

**Comment by miaulalala** [comment]
> All good apart from the version in the docs

This is ok to go in to 28.0.1

File: lib/public/UserStatus/IUserStatus.php (hunk 2 above)
Comment (miaulalala) [reply lib/public/UserStatus/IUserStatus.php:86]: Will go into 28.0.1

**Review by bigcat88 — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]
LGTM didn't test

**Comment by miaulalala** [comment]
@blizzz approval for 28.0.1
