### PR TITLE
Clear avatar cache with frontend repair

### LINKED ISSUE #12058: User avatar generator issues with font
For the Mail app and the Contacts menu, the generated avatars look great:
Generated avatars in Mail app Generated avatars in Contacts menu

Now compare it to the user management and the Files app (here the sharing view).
The typeface is wrong, there are even completely varying thicknesses. Is this a caching issue?
users avatar generator wrong
font for avatars wrong

cc @nextcloud/designers

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #12058

@nextcloud/designers

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Code makes sense 👍

File: lib/private/AvatarManager.php [hunk 1]
```diff
@@ -104,4 +104,20 @@ public function getAvatar(string $userId) : IAvatar {
...
+
+	/**
+	 * Clear generated avatars
+	 */
+	public function clearCachedAvatars() {
+		$users = $this->config->getUsersForUserValue('avatar', 'generated', 'true');
+		foreach($users as $userId) {
+			try {
+				$folder = $this->appData->getFolder($userId);
+				$folder->delete();
```
Comment (rullzer) [inline lib/private/AvatarManager.php]: NO!
This deletes all avatars. Also custom set ones.

**Review by rullzer — DISMISSED** [review]

File: lib/private/AvatarManager.php (hunk 1 above)
Comment (rullzer) [reply lib/private/AvatarManager.php]: AH no it does not my bad for reading to fast

Comment (rullzer) [reply lib/private/AvatarManager.php]: But why do we do this? If a setup already has imagemagick it will just regenerate them. I can imagine people not being to happy if they have 50k userse.

Comment (skjnldsv) [reply lib/private/AvatarManager.php]: @rullzer If any changes are made on the generator, then all avatars are obsolete.
Shall we manually add a version trigger for this step?
Or its own individual step?

Comment (juliushaertl) [reply lib/private/AvatarManager.php]: I would just do this once when migrating from 14.x to 15 so this doesn't happen on every upgrade.

**Comment by skjnldsv** [comment]
Failure unrelated

File: lib/public/IAvatarManager.php [hunk 2]
```diff
@@ -44,4 +44,11 @@
 	 * @since 6.0.0
 	 */
 	public function getAvatar(string $user) : IAvatar;
+
+	/**
+	 * Clear generated avatars
+	 * @see IAvatar
+	 * @since 15.0.0
+	 */
+	public function clearCachedAvatars();
```
Comment (rullzer) [inline lib/public/IAvatarManager.php]: What is this doing in the public namespace.
IMO we should just inject the private class in the repair step and keep this out of here. I see no reason for an app to trigger this.

File: lib/private/Repair/ClearGeneratedAvatarCache.php [hunk 3]
```diff
@@ -0,0 +1,74 @@
...
+
+class ClearGeneratedAvatarCache implements IRepairStep {
+
+	/** @var IAvatarManager */
+	protected $avatarManager;
+
+	/** @var IConfig */
+	private $config;
+
+	public function __construct(IConfig $config, IAvatarManager $avatarManager) {
```
Comment (rullzer) [inline lib/private/Repair/ClearGeneratedAvatarCache.php]: Since this is private as well we can just inject the private class

**Review by rullzer — DISMISSED** [review]

File: lib/private/Repair/ClearGeneratedAvatarCache.php (hunk 3 above)
Comment (skjnldsv) [reply lib/private/Repair/ClearGeneratedAvatarCache.php]: With \OC::$server->query(AvatarManager::class)?

Comment (ChristophWurst) [reply lib/private/Repair/ClearGeneratedAvatarCache.php]: > It's throwing me an error from Repair.php

The exception message would certainly help diagnosing this :wink:

File: lib/private/Repair/ClearGeneratedAvatarCache.php [hunk 4]
```diff
@@ -0,0 +1,74 @@
...
+	}
+
+	/**
+	 * Check if this repair step should run
+	 *
+	 * @param Array $toVersion the version we're upgrading to
+	 * @return void
+	 */
+	private function shouldRun(Array $toVersion) {
+		$fromVersion      = $this->config->getSystemValue('version', '0.0.0.0');
```
Comment (rullzer) [inline lib/private/Repair/ClearGeneratedAvatarCache.php]: I do not get this function. This means it gets run every time there is a version upgraded right?
Shouldn't it test here for `< 15.0.0.4` so it is onyl run once?

Comment (skjnldsv) [reply lib/private/Repair/ClearGeneratedAvatarCache.php]: Every time the function is upgraded to a major yes :)

Comment (rullzer) [reply lib/private/Repair/ClearGeneratedAvatarCache.php]: I'd say lets just do this once for now. If needed a tiny PR can fix to do it again for the next release. But leaving it like this risks doing it for a few releaes until we figure out why instances with 50k users take so long each time ;)

Comment (skjnldsv) [reply lib/private/Repair/ClearGeneratedAvatarCache.php]: Done!

**Review by rullzer — APPROVED** [review]

File: lib/private/AvatarManager.php [hunk 5]
```diff
@@ -104,4 +104,20 @@ public function getAvatar(string $userId) : IAvatar {
 
 		return new Avatar($folder, $this->l, $user, $this->logger, $this->config);
 	}
+
+	/**
+	 * Clear generated avatars
+	 */
+	private function clearCachedAvatars() {
```
Comment (rullzer) [inline lib/private/AvatarManager.php]: Ha this function need to be public :see_no_evil:

**Review by rullzer — CHANGES_REQUESTED** [review]

File: lib/private/AvatarManager.php (hunk 5 above)
Comment (skjnldsv) [reply lib/private/AvatarManager.php]: But you told me to put private :cry:

**Review by rullzer — APPROVED** [review]

File: lib/private/Repair.php [hunk 6]
```diff
@@ -137,10 +143,11 @@ public static function getRepairSteps() {
 			new RepairInvalidPaths(\OC::$server->getDatabaseConnection(), \OC::$server->getConfig()),
 			new AddLogRotateJob(\OC::$server->getJobList()),
 			new ClearFrontendCaches(\OC::$server->getMemCacheFactory(), \OC::$server->query(SCSSCacher::class), \OC::$server->query(JSCombiner::class)),
+			new ClearGeneratedAvatarCache(\OC::$server->getConfig(), \OC::$server->query(AvatarManager::class)),
 			new AddPreviewBackgroundCleanupJob(\OC::$server->getJobList()),
 			new AddCleanupUpdaterBackupsJob(\OC::$server->getJobList()),
 			new RepairPendingCronJobs(\OC::$server->getDatabaseConnection(), \OC::$server->getConfig()),
-			new SetVcardDatabaseUID(\OC::$server->getDatabaseConnection(), \OC::$server->getConfig()),
+			new SetVcardDatabaseUID(\OC::$server->getDatabaseConnection(), \OC::$server->getConfig())
```
Comment (MorrisJobke) [inline lib/private/Repair.php]: We always kept a trailing `,` in arrays to make the diff for adding a new entry nicer. It then only has this one line added instead of also appending a `,` to the previous line.
