### PR TITLE
Get not only time-sensitive next job from list but any when not in cron-mode

### LINKED ISSUE #30899: [Bug]: cron.php executes successfully but Nextcloud says cronjob hasn't run
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I saw this message: 
Background jobs  Some jobs didn’t execute since yesterday. 
Please consider switching to system cron.

### Steps to reproduce

1. working instance 23.0
2. set the webcron  
3 cron being run by webcron 

### Expected behavior

The cron has seemingly run successfully, so I should not see this message in the UI? Can't see any issues in the Nextcloud log either.

### Installation method

Official Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "overwriteprotocol": "https",
        "objectstore": {
            "class": "\\OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "bucket": "nextcloud-prod-01",
                "key": "***REMOVED SENSITIVE VALUE***",
                "secret": "***REMOVED SENSITIVE VALUE***",
                "region": "hu-central-1",
                "hostname": "staging.s3.einfra.hu",
                "port": "",
                "objectPrefix": "urn:oid:",
                "autocreate": false,
                "use_ssl": true,
                "use_path_style": true,
                "legacy_auth": false
            }
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "nextcloud-prod-01.prod.caas.einfra.hu",
            "nextcloud.dinpi.hu"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.0.10",
        "overwrite.cli.url": "https:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_smtpport": "25",
        "loglevel": 0,
        "debug": true,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - admin_audit: 1.13.0
  - calendar: 3.0.5
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.0.7
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - event_update_notification: 1.4.0
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - group_default_quota: 0.1.3
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - mail: 1.11.6
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_ldap: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:
  - circles
  - encryption
  - files_external
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"j1YyIpzI8Jd67gESXKwa","level":0,"time":"2022-01-28T18:55:09+00:00","remoteAddr":"255.255.255.255","user":"--","app":"cron","method":"GET","url":"/cron.php","message":"Finished OCA\\Mail\\BackgroundJob\\TrainImportanceClassifierJob job with ID 2247 in 0 seconds","userAgent":"curl/7.81.0-DEV","version":"23.0.0.10","id":"61f43c0dcdef9"}

{"reqId":"j1YyIpzI8Jd67gESXKwa","level":0,"time":"2022-01-28T18:55:09+00:00","remoteAddr":"255.255.255.255","user":"--","app":"cron","method":"GET","url":"/cron.php","message":"Run OCA\\Mail\\BackgroundJob\\TrainImportanceClassifierJob job with ID 2247","userAgent":"curl/7.81.0-DEV","version":"23.0.0.10","id":"61f43c0dcdf95"}

{"reqId":"bXxjA2YbyH09Kix5PzKQ","level":0,"time":"2022-01-28T18:50:12+00:00","remoteAddr":"255.255.255.255","user":"--","app":"cron","method":"GET","url":"/cron.php","message":"Run OCA\\Mail\\BackgroundJob\\SyncJob job with ID 2502","userAgent":"curl/7.81.0-DEV","version":"23.0.0.10","id":"61f43ae53d1c1"}
```

### Additional info

Webcron container: 
Image: curlimages/curl:7.81.0
Cron Schedule: */5 * * * *

Command: curl -L -s https://nextcloud.ltd/cron.php
Result: {"status":"success"}

When I run cron.php manually inside the container it is successful (sudo -u www-data PHP_MEMORY_LIMIT=512M php /var/html/cron.php)

### LINKED ISSUE #31725: [Bug]: oc cronjob hangs after update to 23.0.3
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After the update to Nextcloud 23.0.3, I get the following message in the message center: 

image

I manually triggered the web cron about 100x via curl, the server responds with `{"status":"success"}`. Nevertheless, the Web UI keeps saying that the affected job was executed the last time on **24th March 2022, 19:40:01 MEZ**, even though the web cron was triggered so many times manually. Even another 100 time invocation of the web cron does not change the time stamp of the affected job. It says on 24th March 2022, 19:40:01 MEZ. No idea why this job won´t get triggered by the cron. 

```
MariaDB [nextcloud]> SELECT `id`,`class`,`last_run`,`last_checked`,`reserved_at` FROM `oc_jobs`;
+------+-----------------------------------------------------------------+------------+--------------+-------------+
| id   | class                                                           | last_run   | last_checked | reserved_at |
+------+-----------------------------------------------------------------+------------+--------------+-------------+
|    1 | OCA\Activity\BackgroundJob\EmailNotification                    | 1648394607 |   1648394607 |           0 |
|    2 | OCA\Activity\BackgroundJob\ExpireActivities                     | 1648230001 |   1648230001 |           0 |
|    3 | OCA\UpdateNotification\Notification\BackgroundJob               | 1648324801 |   1648394608 |           0 |
|    4 | OCA\Files\BackgroundJob\ScanFiles                               | 1648394604 |   1648394604 |           0 |
|    5 | OCA\Files\BackgroundJob\DeleteOrphanedItems                     | 1648392674 |   1648395993 |           0 |
|    6 | OCA\Files\BackgroundJob\CleanupFileLocks                        | 1648395503 |   1648395503 |           0 |
|    7 | OCA\NextcloudAnnouncements\Cron\Crawler                         | 1648342801 |   1648394604 |           0 |
|    8 | OCA\Files_Trashbin\BackgroundJob\ExpireTrash                    | 1648394240 |   1648394514 |           0 |
|    9 | OCA\Support\BackgroundJobs\CheckSubscription                    | 1559220306 |   1648396202 |           0 |
|   10 | OCA\Files_Versions\BackgroundJob\ExpireVersions                 | 1559221203 |   1648396802 |           0 |
|   11 | OCA\DAV\BackgroundJob\CleanupDirectLinksJob                     | 1648326001 |   1648394795 |           0 |
|   12 | OCA\DAV\BackgroundJob\UpdateCalendarResourcesRoomsBackgroundJob | 1648394241 |   1648394602 |           0 |
|   13 | OCA\DAV\BackgroundJob\CleanupInvitationTokenJob                 | 1648341601 |   1648394603 |           0 |
|   15 | OCA\Files_Sharing\DeleteOrphanedSharesJob                       | 1648394401 |   1648394605 |           0 |
|   16 | OCA\Files_Sharing\ExpireSharesJob                               | 1648147201 |   1648147201 |           0 |
|   17 | OCA\Files_Sharing\BackgroundJob\FederatedSharesDiscoverJob      | 1648369201 |   1648394605 |           0 |
|   18 | OCA\Federation\SyncJob                                          | 1648323601 |   1648394608 |           0 |
|   19 | OC\Authentication\Token\DefaultTokenCleanupJob                  | 1648394801 |   1648394801 |           0 |
|   20 | OC\Log\Rotate                                                   | 1648395497 |   1648395497 |           0 |
|   21 | OC\Preview\BackgroundCleanupJob                                 | 1648394205 |   1648395498 |           0 |
|   27 | OC\Core\BackgroundJobs\CleanupLoginFlowV2                       | 1648394223 |   1648395499 |           0 |
|   36 | OCA\UpdateNotification\ResetTokenBackgroundJob                  | 1648394202 |   1648394802 |           0 |
|   43 | OCA\Talk\BackgroundJob\ExpireSignalingMessage                   | 1648395499 |   1648395499 |           0 |
|   44 | OCA\Talk\BackgroundJob\RemoveEmptyRooms                         | 1648395500 |   1648395500 |           0 |
|   49 | OCA\DAV\BackgroundJob\EventReminderJob                          | 1648395001 |   1648395001 |           0 |
|   50 | OCA\Text\Cron\Cleanup                                           | 1648395498 |   1648395498 |           0 |
|   57 | OCA\Files\BackgroundJob\CleanupDirectEditingTokens              | 1648395501 |   1648395501 |           0 |
|   59 | OCA\WorkflowEngine\BackgroundJobs\Rotate                        | 1648388401 |   1648395507 |           0 |
|   63 | OCA\Talk\BackgroundJob\ExpireSignalingMessage                   | 1648395502 |   1648395502 |           0 |
|   64 | OCA\Talk\BackgroundJob\RemoveEmptyRooms                         | 1648395505 |   1648395505 |           0 |
|  269 | OCA\Mail\BackgroundJob\SyncJob                                  | 1592907601 |   1648410001 |           0 |
|  392 | OCA\Mail\BackgroundJob\TrainImportanceClassifierJob             | 1592907001 |   1648410001 |           0 |
|  714 | OCA\Mail\BackgroundJob\SyncJob                                  |          0 |   1648410001 |           0 |
|  715 | OCA\Mail\BackgroundJob\TrainImportanceClassifierJob             |          0 |   1648410001 |           0 |
|  716 | OCA\Mail\BackgroundJob\SyncJob                                  |          0 |   1648410001 |           0 |
|  717 | OCA\Mail\BackgroundJob\TrainImportanceClassifierJob             |          0 |   1648410001 |           0 |
|  718 | OCA\Mail\BackgroundJob\SyncJob                                  |          0 |   1648410001 |           0 |
|  719 | OCA\Mail\BackgroundJob\TrainImportanceClassifierJob             |          0 |   1648410001 |           0 |
|  720 | OCA\Mail\BackgroundJob\SyncJob                                  |          0 |   1648410001 |           0 |
|  721 | OCA\Mail\BackgroundJob\TrainImportanceClassifierJob             |          0 |   1648410001 |           0 |
| 1269 | OCA\Talk\BackgroundJob\ResetAssignedSignalingServer             | 1648395505 |   1648395505 |           0 |
| 1271 | OCA\ContactsInteraction\BackgroundJob\CleanupJob                | 1648198201 |   1648198201 |           0 |
| 1360 | OCA\Contacts\Cron\SocialUpdateRegistration                      | 1647905402 |   1648395497 |           0 |
| 1461 | OCA\Activity\BackgroundJob\DigestMail                           | 1648394424 |   1648394606 |           0 |
| 1464 | OCA\Talk\BackgroundJob\CheckHostedSignalingServer               | 1648394236 |   1648395506 |           0 |
| 1465 | OCA\Talk\BackgroundJob\CheckMatterbridges                       | 1648395601 |   1648395601 |           0 |
| 1466 | OCA\UserStatus\BackgroundJob\ClearOldStatusesBackgroundJob      | 1648394609 |   1648394609 |           0 |
| 1467 | OCA\Mail\BackgroundJob\SyncJob                                  |          0 |   1648411201 |           0 |
| 1468 | OCA\Mail\BackgroundJob\TrainImportanceClassifierJob             |          0 |   1648411201 |           0 |
| 1826 | OC\Security\Bruteforce\CleanupJob                               | 1648238402 |   1648238401 |           0 |
| 3721 | OCA\DAV\BackgroundJob\CalendarRetentionJob                      | 1648390233 |   1648394607 |           0 |
| 3722 | OCA\ServerInfo\Jobs\UpdateStorageStats                          | 1648390234 |   1648394609 |           0 |
| 3724 | OCA\Circles\Cron\Maintenance                                    | 1648395502 |   1648395502 |           0 |
| 3749 | OCA\Calendar\BackgroundJob\CleanUpOutdatedBookingsJob           | 1648213801 |   1648213801 |           0 |
| 3752 | OCA\Notifications\BackgroundJob\GenerateUserSettings            | 1648338001 |   1648396201 |           0 |
| 3753 | OCA\Notifications\BackgroundJob\SendNotificationMails           | 1648394514 |   1648394514 |           0 |
| 3765 | OCA\DAV\BackgroundJob\RefreshWebcalJob                          | 1648394610 |   1648394610 |           0 |
| 3766 | OCA\DAV\BackgroundJob\RefreshWebcalJob                          | 1648394795 |   1648394795 |           0 |
+------+-----------------------------------------------------------------+------------+--------------+-------------+
58 rows in set (0.000 sec)
```
```
MariaDB [nextcloud]> SELECT count(id) as jobs, class FROM oc_jobs GROUP by class ORDER BY jobs DESC;
+------+-----------------------------------------------------------------+
| jobs | class                                                           |
+------+-----------------------------------------------------------------+
|    6 | OCA\Mail\BackgroundJob\SyncJob                                  |
|    6 | OCA\Mail\BackgroundJob\TrainImportanceClassifierJob             |
|    2 | OCA\Talk\BackgroundJob\ExpireSignalingMessage                   |
|    2 | OCA\Talk\BackgroundJob\RemoveEmptyRooms                         |
|    2 | OCA\DAV\BackgroundJob\RefreshWebcalJob                          |
|    1 | OCA\NextcloudAnnouncements\Cron\Crawler                         |
|    1 | OCA\Notifications\BackgroundJob\GenerateUserSettings            |
|    1 | OCA\Notifications\BackgroundJob\SendNotificationMails           |
|    1 | OCA\ServerInfo\Jobs\UpdateStorageStats                          |
|    1 | OCA\Support\BackgroundJobs\CheckSubscription                    |
|    1 | OCA\Talk\BackgroundJob\CheckHostedSignalingServer               |
|    1 | OCA\Talk\BackgroundJob\CheckMatterbridges                       |
|    1 | OCA\Activity\BackgroundJob\DigestMail                           |
|    1 | OCA\Activity\BackgroundJob\EmailNotification                    |
|    1 | OCA\Activity\BackgroundJob\ExpireActivities                     |
|    1 | OCA\Talk\BackgroundJob\ResetAssignedSignalingServer             |
|    1 | OCA\Calendar\BackgroundJob\CleanUpOutdatedBookingsJob           |
|    1 | OCA\Text\Cron\Cleanup                                           |
|    1 | OCA\Circles\Cron\Maintenance                                    |
|    1 | OCA\UpdateNotification\Notification\BackgroundJob               |
|    1 | OCA\ContactsInteraction\BackgroundJob\CleanupJob                |
|    1 | OCA\UpdateNotification\ResetTokenBackgroundJob                  |
|    1 | OCA\Contacts\Cron\SocialUpdateRegistration                      |
|    1 | OCA\UserStatus\BackgroundJob\ClearOldStatusesBackgroundJob      |
|    1 | OCA\DAV\BackgroundJob\CalendarRetentionJob                      |
|    1 | OCA\WorkflowEngine\BackgroundJobs\Rotate                        |
|    1 | OCA\DAV\BackgroundJob\CleanupDirectLinksJob                     |
|    1 | OC\Authentication\Token\DefaultTokenCleanupJob                  |
|    1 | OCA\DAV\BackgroundJob\CleanupInvitationTokenJob                 |
|    1 | OC\Core\BackgroundJobs\CleanupLoginFlowV2                       |
|    1 | OCA\DAV\BackgroundJob\EventReminderJob                          |
|    1 | OC\Log\Rotate                                                   |
|    1 | OC\Preview\BackgroundCleanupJob                                 |
|    1 | OCA\DAV\BackgroundJob\UpdateCalendarResourcesRoomsBackgroundJob |
|    1 | OC\Security\Bruteforce\CleanupJob                               |
|    1 | OCA\Federation\SyncJob                                          |
|    1 | OCA\Files\BackgroundJob\CleanupDirectEditingTokens              |
|    1 | OCA\Files\BackgroundJob\CleanupFileLocks                        |
|    1 | OCA\Files\BackgroundJob\DeleteOrphanedItems                     |
|    1 | OCA\Files\BackgroundJob\ScanFiles                               |
|    1 | OCA\Files_Sharing\BackgroundJob\FederatedSharesDiscoverJob      |
|    1 | OCA\Files_Sharing\DeleteOrphanedSharesJob                       |
|    1 | OCA\Files_Sharing\ExpireSharesJob                               |
|    1 | OCA\Files_Trashbin\BackgroundJob\ExpireTrash                    |
|    1 | OCA\Files_Versions\BackgroundJob\ExpireVersions                 |
+------+-----------------------------------------------------------------+
45 rows in set (0.001 sec)

```

### Steps to reproduce

1. Update to 23.0.3
2. Wait a few days and check the cron jobs

### Expected behavior

1. All cron jobs were triggered in time

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

No

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxxxx",
            "xxxxx"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.3.2",
        "overwrite.cli.url": "https:\/\/xxxx.xxxxxxx.com\/",
        "overwrite.webroot": "\/",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mysql.utf8mb4": true,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "activity_expire_days": 30,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465 ",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 0,
        "default_phone_region": "DE"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - calendar: 3.2.2
  - circles: 23.1.0
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.1.0
  - contactsinteraction: 1.4.0
  - dav: 1.21.0
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - impersonate: 1.10.0
  - integration_twitter: 1.0.2
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - spreed: 13.0.4
  - systemtags: 1.13.0
  - tasks: 0.14.4
  - text: 3.4.1
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:
  - admin_audit
  - bruteforcesettings: 2.3.0
  - dashboard: 7.1.0
  - drawio: 1.0.2
  - encryption
  - files_external
  - files_versions: 1.9.0
  - previewgenerator: 4.0.0
  - recommendations: 0.4.0
  - rocketchat_nextcloud: 0.9.6
  - support: 1.0.0
  - survey_client: 1.4.0
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
No errors found
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by k-popov**
Fix https://github.com/nextcloud/server/issues/31725
Fix https://github.com/nextcloud/server/issues/30899

Before the change webcron used to select
**only** time-sensitive tasks.

Signed-off-by: Kirill Popov <kirill.s.popov@gmail.com>

### CODE REVIEW

File: lib/private/BackgroundJob/JobList.php [hunk 1]
```diff
@@ -203,7 +203,7 @@ public function getAll() {
 	 * @param bool $onlyTimeSensitive
 	 * @return IJob|null
 	 */
-	public function getNext(bool $onlyTimeSensitive = true): ?IJob {
+	public function getNext(bool $onlyTimeSensitive = false): ?IJob {
```
Comment (nickvergessen) [inline lib/private/BackgroundJob/JobList.php:206]: Also needs adjusting in lib/public/BackgroundJob/IJobList.php

Otherwise fine 👍

Comment (k-popov) [reply lib/private/BackgroundJob/JobList.php:206]: It's already `false` there by default: https://github.com/nextcloud/server/blob/20d7bf8a880ddf41874afdaf3784d29bc1bc925d/lib/public/BackgroundJob/IJobList.php#L92

Comment (k-popov) [reply lib/private/BackgroundJob/JobList.php:206]: Did you mean https://github.com/nextcloud/server/blob/20d7bf8a880ddf41874afdaf3784d29bc1bc925d/tests/lib/BackgroundJob/DummyJobList.php#L81 ? I'm not sure about this test.

Comment (nickvergessen) [reply lib/private/BackgroundJob/JobList.php:206]: Yeah also update the dummy

Comment (k-popov) [reply lib/private/BackgroundJob/JobList.php:206]: Done. `DummyJobList.php` has been updated too.

**Review by nickvergessen — APPROVED** [review]

**Review by PVince81 — APPROVED** [review]
:+1:
