### PR TITLE
fix: Shipped apps should include the Nextcloud version in the cache buster

### LINKED ISSUE #46976: [Bug]: Force reload required after upgrade 29 -> 30
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After upgrading from 29.0.4 to 30.0.0 Beta 3 a force reload was required on the users end (multiple apps were affected, like talk, forms,…). Seems that our cachebuster has an issue somewhere?

### Steps to reproduce

1. Upgrade from 29 to 30

### Expected behavior

No force reload required 

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: https://github.com/nextcloud/server/issues/46976

## Summary

1. The hash should also include the Nextcloud version if the app is shipped as every new Nextcloud update = new app version
2. Cache the hash to prevent re-generation if the path is the same (e.g. the same app uses a lot of scripts / styles).

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: tests/lib/TemplateLayoutTest.php [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+
+class TemplateLayoutTest extends \Test\TestCase {
+
+	protected function setUp(): void {
+		parent::setUp();
+	}
+
+	protected function tearDown(): void {
+		parent::tearDown();
+	}
```
Comment (provokateurin) [inline tests/lib/TemplateLayoutTest.php:26]:
```suggestion
```

**Review by provokateurin — APPROVED** [review]

**Review by come-nc — APPROVED** [review]
