### PR TITLE
Move calendar objects between calendars

### LINKED ISSUE #3325: Moving events back and forth between calendars causes trash bin conflicts
Moving an event to a different calendar B and back to the original calendar A is broken at the moment, because the original event is still present in calendar A due to how the trash bin works. See https://github.com/nextcloud/tasks/issues/1685 for the original report.

### PR DESCRIPTION
**Pull request by miaulalala**
When moving a calendar object from calendar A to calendar B, move the object instead of copying it to the new calendar and deleting the old object.

Fixes nextcloud/calendar#3325

### CODE REVIEW

**Comment by nickvergessen** [comment]
Not sure I have enough meta knowledge. But are URIs unique per calendar or globally? So could there be an error when moving a to be duplicate-URI element to another calendar which already has this URI?

**Comment by come-nc** [comment]
Lots of potential issues spotted by psalm.

File: apps/dav/lib/CalDAV/CalDavBackend.php [hunk 1]
```diff
@@ -1413,6 +1413,60 @@ public function updateCalendarObject($calendarId, $objectUri, $calendarData, $ca
...
+	 * Moves a calendar object from calendar to calendar.
+	 *
+	 * @param int $sourceCalendarId
+	 * @param int $targetCalendarId
+	 * @param int $objectId
+	 * @param string $principalUri
+	 * @param int $calendarType
+	 * @return string
+	 */
+	public function moveCalendarObject(int $sourceCalendarId, int $targetCalendarId, int $objectId, string $principalUri, $calendarType = self::CALENDAR_TYPE_CALENDAR) {
```
Comment (tcitworld) [inline apps/dav/lib/CalDAV/CalDavBackend.php:1426]: Add return type.

File: apps/dav/lib/CalDAV/Calendar.php [hunk 2]
```diff
@@ -422,4 +424,9 @@ public function restore(): void {
 	public function disableTrashbin(): void {
 		$this->useTrashbin = false;
 	}
+
+	public function moveInto($targetName, $sourcePath, INode $sourceNode) {
+		$this->caldavBackend->moveCalendarObject($sourceNode->getCalendarId(), $this->calendarInfo['id'], $sourceNode->getId(), $sourceNode->getPrincipalUri);
+		return true;
```
Comment (tcitworld) [inline apps/dav/lib/CalDAV/Calendar.php:430]: The function should return `true` only if the previous called succeeded. We should handle exceptions and return `false` if something failed, so that Sabre can handle the move itself like it did before.

https://github.com/nextcloud/3rdparty/blob/f6e3fb0265ac03394420525b26ab7f306ae373d5/sabre/dav/lib/DAV/IMoveTarget.php#L35-L37

File: apps/dav/lib/CalDAV/CalendarObject.php [hunk 3]
```diff
@@ -154,4 +154,12 @@ private function canWrite() {
 		}
 		return true;
 	}
+
+	public function getCalendarId(): array {
```
[the remark this answers is not in the document]
Comment (miaulalala) [reply apps/dav/lib/CalDAV/CalendarObject.php:158]: classic Copy paste

File: apps/dav/lib/CalDAV/CalDavBackend.php [hunk 4]
```diff
@@ -1413,6 +1413,60 @@ public function updateCalendarObject($calendarId, $objectUri, $calendarData, $ca
...
+						'subscriptionId' => $targetCalendarId,
+						'calendarData' => $subscriptionRow,
+						'shares' => [],
+						'objectData' => $object,
+					]
+				));
+			}
+		}
+
+		return '"' . $object['etag'] . '"';
```
[the remark this answers is not in the document]
Comment (miaulalala) [reply apps/dav/lib/CalDAV/CalDavBackend.php]: > This is outside `if (is_array($object)) {`. What if it's not an array?

Then it's null. I'm not sure what should happen then, because that means the object does not exist in the database any more. I really don't know how to handle that case though, should it throw an exception?

File: apps/dav/lib/CalDAV/CalDavBackend.php [hunk 5]
```diff
@@ -1413,6 +1414,42 @@ public function updateCalendarObject($calendarId, $objectUri, $calendarData, $ca
...
+	 *
+	 * @param int $sourceCalendarId
+	 * @param int $targetCalendarId
+	 * @param int $objectId
+	 * @param string $principalUri
+	 * @param int $calendarType
+	 * @throws Exception
+	 */
+	public function moveCalendarObject(int $sourceCalendarId, int $targetCalendarId, int $objectId, string $principalUri, int $calendarType = self::CALENDAR_TYPE_CALENDAR): void {
+		$object = $this->getCalendarObjectById($principalUri, $objectId);
```
Comment (tcitworld) [inline apps/dav/lib/CalDAV/CalDavBackend.php:1428]: There's probably a check by Sabre before `moveCalendarObject` is called, but here `getCalendarObjectById` can return `null`. Return `false` directly if so, and get 4 psalm following notices gone for the same price !

File: apps/dav/lib/CalDAV/CalDavBackend.php [hunk 6]
```diff
@@ -1413,6 +1414,42 @@ public function updateCalendarObject($calendarId, $objectUri, $calendarData, $ca
...
+		$this->purgeProperties($sourceCalendarId, $objectId);
+		$this->updateProperties($targetCalendarId, $object['uri'], $object['calendardata'], $calendarType);
+
+		$this->addChange($sourceCalendarId, $object['uri'], 1, $calendarType);
+		$this->addChange($targetCalendarId, $object['uri'], 3, $calendarType);
+
+		$object = $this->getCalendarObjectById($principalUri, $objectId);
+
+		if (is_array($object) && $calendarType === self::CALENDAR_TYPE_CALENDAR) {
+			$calendarRow = $this->getCalendarById($targetCalendarId);
```
Comment (tcitworld) [inline apps/dav/lib/CalDAV/CalDavBackend.php:1446]: Same here, handle `null` value.

File: apps/dav/lib/CalDAV/Calendar.php [hunk 7]
```diff
@@ -422,4 +430,18 @@ public function restore(): void {
...
 		$this->useTrashbin = false;
 	}
+
+	public function moveInto($targetName, $sourcePath, INode $sourceNode) {
+		if(!($sourceNode instanceof CalendarObject)) {
+			return false;
+		}
+
+		try {
+			$this->caldavBackend->moveCalendarObject($sourceNode->getCalendarId(), $this->calendarInfo['id'], $sourceNode->getId(), $sourceNode->getPrincipalUri());
```
Comment (tcitworld) [inline apps/dav/lib/CalDAV/Calendar.php:440]: Cast to `int` to make psalm happy.

File: apps/dav/lib/RootCollection.php [hunk 8]
```diff
@@ -47,13 +47,15 @@
...
 use OCP\IConfig;
+use Psr\Log\LoggerInterface;
 use Sabre\DAV\SimpleCollection;
 
 class RootCollection extends SimpleCollection {
 	public function __construct() {
 		$l10n = \OC::$server->getL10N('dav');
 		$random = \OC::$server->getSecureRandom();
 		$logger = \OC::$server->getLogger();
+		$psrLogger = \Oc::$server->get(LoggerInterface::class);
```
Comment (raimund-schluessler) [inline apps/dav/lib/RootCollection.php:58]:
```suggestion
		$psrLogger = \OC::$server->get(LoggerInterface::class);
```

**Comment by gohrner** [comment]
@miaulalala: I don't want to discredit this implementation, but to me it sounds as if it only catches a corner case.

I guess this PR won't help in cases where an event is moved from one calendar managed in Nextcloud to another calendar managed by some other server, and back again?

Nextcloud server will still have to provide a solution for this case in order not to break other CalDAV clients.

How about - probably in addition to this feature implemented here - allowing the Nextcloud Calender to "resurrect" and update items in the trashbin transparently if they are re-added by any client? This would also solve the "multiple servers" issue, and also additional ones (basically getting the CalDAV interface's semantics - to me knowledge - back in line with the RFCs).

**Comment by miaulalala** [comment]
> @miaulalala: I don't want to discredit this implementation, but to me it sounds as if it only catches a corner case.
> 
> I guess this PR won't help in cases where an event is moved from one calendar managed in Nextcloud to another calendar managed by some other server, and back again?
> 
> Nextcloud server will still have to provide a solution for this case in order not to break other CalDAV clients.
> 
> How about - probably in addition to this feature implemented here - allowing the Nextcloud Calender to "resurrect" and update items in the trashbin transparently if they are re-added by any client? This would also solve the "multiple servers" issue, and also additional ones (basically getting the CalDAV interface's semantics - to me knowledge - back in line with the RFCs).

I guess it depends on your definiton of "edge case" ;) but you're right, this does indeed not help with the problem of deletion conflicts.

I'll address this in a different PR.

File: apps/dav/lib/CalDAV/CalDavBackend.php [hunk 9]
```diff
@@ -1413,6 +1414,53 @@ public function updateCalendarObject($calendarId, $objectUri, $calendarData, $ca
...
+
+		$this->purgeProperties($sourceCalendarId, $objectId);
+		$this->updateProperties($targetCalendarId, $object['uri'], $object['calendardata'], $calendarType);
+
+		$this->addChange($sourceCalendarId, $object['uri'], 1, $calendarType);
+		$this->addChange($targetCalendarId, $object['uri'], 3, $calendarType);
+
+		$object = $this->getCalendarObjectById($principalUri, $objectId);
+		if (empty($object)) {
+			return false;
```
Comment (ChristophWurst) [inline apps/dav/lib/CalDAV/CalDavBackend.php:1448]: could you add a comment about when this happens and why you return early?

File: apps/dav/lib/CalDAV/CalDavBackend.php [hunk 10]
```diff
@@ -1413,6 +1414,53 @@ public function updateCalendarObject($calendarId, $objectUri, $calendarData, $ca
...
+		}
+
+		$calendarRow = $this->getCalendarById($targetCalendarId);
+		if (empty($calendarRow)) {
+			return false;
```
Comment (ChristophWurst) [inline apps/dav/lib/CalDAV/CalDavBackend.php:1453]: same :)

**Comment by st3iny** [comment]
Failing drone tests seem to be related (e.g. `OCA\DAV\Tests\Command\DeleteCalendarTest::testInvalidUser`).

**Comment by miaulalala** [comment]
```

1) OCA\DAV\Tests\Command\DeleteCalendarTest::testInvalidUser
--
165 | ArgumentCountError: Too few arguments to function OCA\DAV\Command\DeleteCalendar::__construct(), 4 passed in /drone/src/apps/dav/tests/unit/Command/DeleteCalendarTest.php on line 73 and exactly 5 expected

```

I can't figure this out. DeleteCalendar does not expect 5 arguments.
https://github.com/nextcloud/server/blob/dfbac05f7ba00c78ac15df61a425317a890b08d1/apps/dav/lib/Command/DeleteCalendar.php#L58-L63

File: apps/dav/lib/CalDAV/Calendar.php [hunk 11]
```diff
@@ -422,4 +430,18 @@ public function restore(): void {
...
+
+	public function moveInto($targetName, $sourcePath, INode $sourceNode) {
+		if (!($sourceNode instanceof CalendarObject)) {
+			return false;
+		}
+
+		try {
+			$result = $this->caldavBackend->moveCalendarObject($sourceNode->getCalendarId(), (int)$this->calendarInfo['id'], $sourceNode->getId(), $sourceNode->getPrincipalUri());
+		} catch (Exception $e) {
+			$this->logger->error('Could not move calendar object: ' . $e->getMessage(), ['excption' => $e]);
```
Comment (tcitworld) [inline apps/dav/lib/CalDAV/Calendar.php:442]:
```suggestion
			$this->logger->error('Could not move calendar object: ' . $e->getMessage(), ['exception' => $e]);
```

**Comment by miaulalala** [comment]
Drone Failure unrelated (Samba)

File: apps/dav/lib/CalDAV/Calendar.php [hunk 12]
```diff
@@ -422,4 +430,18 @@ public function restore(): void {
 	public function disableTrashbin(): void {
 		$this->useTrashbin = false;
 	}
+
```
Comment (tcitworld) [inline apps/dav/lib/CalDAV/Calendar.php:433]: In the past we seem to have put the PHPdoc documentation from the interface directly in our own implementations. If I understand [PHPDoc docs](https://docs.phpdoc.org/guide/guides/inheritance.html) correctly, `@inheritDoc` is probably enough though.

So that people know what happens when we return `false`.

**Review by tcitworld — APPROVED** [review]
Just a nitpick

File: apps/dav/lib/CalDAV/Calendar.php [hunk 13]
```diff
@@ -415,11 +423,31 @@ public function getChanges($syncToken, $syncLevel, $limit = null) {
...
+			return false;
+		}
+
+		try {
+			$result = $this->caldavBackend->moveCalendarObject($sourceNode->getCalendarId(), (int)$this->calendarInfo['id'], $sourceNode->getId(), $sourceNode->getPrincipalUri());
+		} catch (Exception $e) {
+			$this->logger->error('Could not move calendar object: ' . $e->getMessage(), ['exception' => $e]);
+			return false;
+		}
+		return $result;
```
Comment (ChristophWurst) [inline apps/dav/lib/CalDAV/Calendar.php:451]: inline to make the control flow clearer

File: apps/dav/lib/CalDAV/CalDavBackend.php [hunk 14]
```diff
@@ -1415,6 +1416,55 @@ public function updateCalendarObject($calendarId, $objectUri, $calendarData, $ca
...
+		$object = $this->getCalendarObjectById($principalUri, $objectId);
+		if (empty($object)) {
+			return false;
+		}
+
+		$query = $this->db->getQueryBuilder();
+		$query->update('calendarobjects')
+			->set('calendarid', $query->createNamedParameter($targetCalendarId))
+			->where($query->expr()->eq('id', $query->createNamedParameter($objectId)))
+			->andWhere($query->expr()->eq('calendartype', $query->createNamedParameter($calendarType)))
```
Comment (ChristophWurst) [inline apps/dav/lib/CalDAV/CalDavBackend.php:1439]: both columns and parameters are int. add type arguments.

File: apps/dav/lib/CalDAV/CalDavBackend.php [hunk 15]
```diff
@@ -1415,6 +1416,55 @@ public function updateCalendarObject($calendarId, $objectUri, $calendarData, $ca
...
+	 */
+	public function moveCalendarObject(int $sourceCalendarId, int $targetCalendarId, int $objectId, string $principalUri, int $calendarType = self::CALENDAR_TYPE_CALENDAR): bool {
+		$object = $this->getCalendarObjectById($principalUri, $objectId);
+		if (empty($object)) {
+			return false;
+		}
+
+		$query = $this->db->getQueryBuilder();
+		$query->update('calendarobjects')
+			->set('calendarid', $query->createNamedParameter($targetCalendarId))
```
Comment (ChristophWurst) [inline apps/dav/lib/CalDAV/CalDavBackend.php:1437]: this is also an int

File: apps/dav/lib/CalDAV/CalDavBackend.php [hunk 16]
```diff
@@ -1415,6 +1416,55 @@ public function updateCalendarObject($calendarId, $objectUri, $calendarData, $ca
...
 
+	/**
+	 * Moves a calendar object from calendar to calendar.
+	 *
+	 * @param int $sourceCalendarId
+	 * @param int $targetCalendarId
+	 * @param int $objectId
+	 * @param string $principalUri
+	 * @param int $calendarType
+	 * @throws Exception
```
Comment (ChristophWurst) [inline apps/dav/lib/CalDAV/CalDavBackend.php:1427]: this should probably not be a checked exception

**Review by ChristophWurst — COMMENTED** [review]
Looks good!

As a (future) enhancement this is also a good example of an operation we should do atomically. Either the calendar gets moved and the changes are tracked in the sync table, or everything is rolled back. Ref https://github.com/nextcloud/server/pull/31205.

File: apps/dav/lib/CalDAV/CalDavBackend.php (hunk 16 above)
Comment (ChristophWurst) [reply apps/dav/lib/CalDAV/CalDavBackend.php:1427]: if other methods also check it then leave it as is for consistency

Comment (miaulalala) [reply apps/dav/lib/CalDAV/CalDavBackend.php:1427]: it's only used in the CalDav Calendar.php and the exception is caught. I have left it in.

**Review by ChristophWurst — APPROVED** [review]

**Comment by kartoffelheinz** [comment]
We ran into this bug and after figuring out how to reproduce, we tried NC 24.0.4rc1 with the merged fix. Unfortunately it didn't fix the error, we can still reproduce broken events by switching between calenders.
