### PR TITLE
fix(SystemTagManager): Truncate overlong tag names

### LINKED ISSUE #694: String data, right truncated: 1406 Data too long for column 'name' at row 1
### Which version of recognize are you using?

3.5.0

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

WASM mode

### Which Nextcloud version do you have installed?

25.0.3

### Which Operating system do you have installed?

alpine 3.15 (docker)

### Which Docker container are you using to run Nextcloud? (if applicable)

linuxserver docker

### How much RAM does your server have?

16GB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

Nextcloud logs are filled with this entry:
```
[core] Error: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing a query: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'name' at row 1 at <<closure>>

 0. /config/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php line 1780
    Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert()
 1. /config/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php line 1719
    Doctrine\DBAL\Connection->handleDriverException()
 2. /config/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php line 1173
    Doctrine\DBAL\Connection->convertExceptionDuringQuery()
 3. /config/www/nextcloud/lib/private/DB/Connection.php line 294
    Doctrine\DBAL\Connection->executeStatement()
 4. /config/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php line 354
    OC\DB\Connection->executeStatement()
 5. /config/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php line 281
    Doctrine\DBAL\Query\QueryBuilder->execute()
 6. /config/www/nextcloud/lib/private/SystemTag/SystemTagManager.php line 205
    OC\DB\QueryBuilder\QueryBuilder->execute()
 7. /config/www/nextcloud/apps/recognize/lib/Service/TagManager.php line 33
    OC\SystemTag\SystemTagManager->createTag()
 8. /config/www/nextcloud/apps/recognize/lib/Service/TagManager.php line 71
    OCA\Recognize\Service\TagManager->getTag()
 9. <<closure>>
    OCA\Recognize\Service\TagManager->OCA\Recognize\Service\{closure}("*** sensitive parameters replaced ***")
10. /config/www/nextcloud/apps/recognize/lib/Service/TagManager.php line 70
    array_map()
11. /config/www/nextcloud/apps/recognize/lib/Classifiers/Images/LandmarksClassifier.php line 46
    OCA\Recognize\Service\TagManager->assignTags()
12. /config/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyLandmarksJob.php line 41
    OCA\Recognize\Classifiers\Images\LandmarksClassifier->classify()
13. /config/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifierJob.php line 70
    OCA\Recognize\BackgroundJobs\ClassifyLandmarksJob->classify()
14. /config/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyLandmarksJob.php line 33
    OCA\Recognize\BackgroundJobs\ClassifierJob->runClassifier()
15. /config/www/nextcloud/lib/public/BackgroundJob/Job.php line 78
    OCA\Recognize\BackgroundJobs\ClassifyLandmarksJob->run()
16. /config/www/nextcloud/lib/public/BackgroundJob/TimedJob.php line 103
    OCP\BackgroundJob\Job->start()
17. /config/www/nextcloud/lib/public/BackgroundJob/TimedJob.php line 93
    OCP\BackgroundJob\TimedJob->start()
18. /config/www/nextcloud/cron.php line 152
    OCP\BackgroundJob\TimedJob->execute()

at 2023-02-20T06:50:46+00:00
```

### Expected Behavior

No error logs.

### To Reproduce

Run recognize.

### Debug log

_No response_

### PR DESCRIPTION
**Pull request by marcelklehr**
* Resolves: https://github.com/nextcloud/recognize/issues/694

## Summary
The systemtag.name column has a length of 64 but the code never asserts the length of tag names. Thus without this patch you can get an exception when creating tags with long names.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: lib/private/SystemTag/SystemTagManager.php [hunk 1]
```diff
@@ -196,7 +196,7 @@ public function createTag(string $tagName, bool $userVisible, bool $userAssignab
 		$query = $this->connection->getQueryBuilder();
 		$query->insert(self::TAG_TABLE)
 			->values([
-				'name' => $query->createNamedParameter($tagName),
+				'name' => $query->createNamedParameter(substr($tagName, 0, 64)), // Length of name column is 64
```
Comment (nickvergessen) [inline lib/private/SystemTag/SystemTagManager.php:199]: Can you write this into a variable and return it on errors etc. Otherwise the error messages will not match what the DB tried to do and also the code around this does not know the new label

**Review by nickvergessen — CHANGES_REQUESTED** [review]

File: lib/private/SystemTag/SystemTagManager.php (hunk 1 above)
Comment (marcelklehr) [reply lib/private/SystemTag/SystemTagManager.php]: Ah, yes. Fixed now.

File: tests/lib/SystemTag/SystemTagManagerTest.php [hunk 2]
```diff
@@ -259,6 +259,14 @@ public function testCreateDuplicate($name, $userVisible, $userAssignable) {
 		$this->tagManager->createTag($name, $userVisible, $userAssignable);
 	}
 
+	public function testCreateOverlongName() {
+		try {
+			$this->tagManager->createTag('Zona circundante do Palácio Nacional da Ajuda (Jardim das Damas, Salão de Física, Torre Sineira, Paço Velho e Jardim Botânico)', true, true);
+		} catch (\Exception $e) {
+			$this->assertTrue(false, 'No exception thrown for create call');
+		}
```
Comment (nickvergessen) [inline tests/lib/SystemTag/SystemTagManagerTest.php:267]:
```suggestion
		$tag = $this->tagManager->createTag('Zona circundante do Palácio Nacional da Ajuda (Jardim das Damas, Salão de Física, Torre Sineira, Paço Velho e Jardim Botânico)', true, true);
		$this->assertSame('Zona circundante do Palácio Nacional da Ajuda (Jardim das Damas,', $tag->getName());
```

**Review by nickvergessen — CHANGES_REQUESTED** [review]

File: tests/lib/SystemTag/SystemTagManagerTest.php (hunk 2 above)
Comment (nickvergessen) [reply tests/lib/SystemTag/SystemTagManagerTest.php:267]: Afterwards it should be good to go

Comment (marcelklehr) [reply tests/lib/SystemTag/SystemTagManagerTest.php]: Ah, damn. `"Zona circundante do Palácio Nacional da Ajuda (Jardim das Damas,"` has 65 bytes...

**Comment by marcelklehr** [comment]
Do we backport this?

**Review by nickvergessen — APPROVED** [review]

**Review by come-nc — APPROVED** [review]

**Comment by nickvergessen** [comment]
> Do we backport this?

I guess we could as it's not breaking things that worked before?

**Comment by marcelklehr** [comment]
Great!
