### PR TITLE
fix(files): keep current folder on drag-n-drop

### LINKED ISSUE #57989: [Bug]: Drag and drop file upload ends up navigating to the home folder after the upload is done
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

See title. This doesn't happen when using the "Upload files" button, only with drag and drop.

### Steps to reproduce

1. Go to a subfolder
2. Upload a file via drag and drop
3. End up in the home folder

### Expected behavior

The view should stay in the folder.

### Nextcloud Server version

33

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

c.nc.c

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: https://github.com/nextcloud/server/issues/57989

## Summary
When drag and drop a file we only want to scroll to the uploaded file not changing the current view.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)
- [x] [Labels added](https://github.com/nextcloud/server/labels) where applicable (ex: bug/enhancement, `3. to review`, feature component)
- [x] [Milestone added](https://github.com/nextcloud/server/milestones) for target branch/version (ex: 32.x for `stable32`)

### CODE REVIEW

File: apps/files/src/components/DragAndDropNotice.vue [hunk 1]
```diff
@@ -204,16 +203,19 @@ export default defineComponent({
...
+						// Keep params but change file id
 						...this.$route.params,
-						fileid: String(lastUpload.response!.headers['oc-fileid']),
+						fileid,
 					},
-				}
-				this.$router.push(location)
+					query: {
+						dir: this.$route.query.dir,
+					},
```
Comment (provokateurin) [inline apps/files/src/components/DragAndDropNotice.vue:217]:
```suggestion
					query: this.$route.query,
```
Does this make sense? Just wondering if other parameters could be affected unintentionally as well.

Comment (susnux) [reply apps/files/src/components/DragAndDropNotice.vue:217]: No query is a reactive object, this is quite dangerous if not de-structured

Comment (susnux) [reply apps/files/src/components/DragAndDropNotice.vue:217]: (also this will cause thing like opening the sidebar etc - not sure if that is expected)

**Review by provokateurin — APPROVED** [review]

**Review by cristianscheid — APPROVED** [review]
