### PR TITLE
[stable31] ignore missing theming app

### LINKED ISSUE #52131: [Bug]: Latest versions 31.0.3 and 30.0.9 failing to start wizard due to missing `ThemesService` class
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Installing and starting a fresh instance of Nextcloud (via the tar.bz2 artifact) on the latest versions 31.0.3 and 30.0.9 results in the web server responding with a 500. Nextcloud log shows the following errors:
```
{"reqId":"FOaCwPhPgEWvwxJdzr0w","level":3,"time":"2025-04-11T14:45:38+00:00","remoteAddr":"192.168.13.227","user":"--","app":"index","method":"GET","url":"/","message":"Could not resolve OCA\\Theming\\Service\\ThemesService! Class \"OCA\\Theming\\Service\\ThemesService\" does not exist","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36","version":"","exception":{"Exception":"OC\\AppFramework\\Utility\\QueryNotFoundException","Message":"Could not resolve OCA\\Theming\\Service\\ThemesService! Class \"OCA\\Theming\\Service\\ThemesService\" does not exist","Code":0,"Trace":[{"file":"/app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php","line":124,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/app/www/public/lib/private/ServerContainer.php","line":155,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php","line":42,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"/app/www/public/lib/public/Server.php","line":39,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/app/www/public/lib/private/TemplateLayout.php","line":183,"function":"get","class":"OCP\\Server","type":"::"},{"file":"/app/www/public/lib/private/legacy/OC_Template.php","line":120,"function":"__construct","class":"OC\\TemplateLayout","type":"->"},{"file":"/app/www/public/lib/private/Template/Base.php","line":113,"function":"fetchPage","class":"OC_Template","type":"->"},{"file":"/app/www/public/lib/private/legacy/OC_Template.php","line":210,"function":"printPage","class":"OC\\Template\\Base","type":"->"},{"file":"/app/www/public/core/Controller/SetupController.php","line":83,"function":"printGuestPage","class":"OC_Template","type":"::"},{"file":"/app/www/public/core/Controller/SetupController.php","line":55,"function":"display","class":"OC\\Core\\Controller\\SetupController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/app/www/public/lib/base.php","line":973,"function":"run","class":"OC\\Core\\Controller\\SetupController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/app/www/public/index.php","line":24,"function":"handleRequest","class":"OC","type":"::"}],"File":"/app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php","Line":113,"message":"Could not resolve OCA\\Theming\\Service\\ThemesService! Class \"OCA\\Theming\\Service\\ThemesService\" does not exist","exception":{},"CustomMessage":"Could not resolve OCA\\Theming\\Service\\ThemesService! Class \"OCA\\Theming\\Service\\ThemesService\" does not exist"}}
{"reqId":"FOaCwPhPgEWvwxJdzr0w","level":3,"time":"2025-04-11T14:45:38+00:00","remoteAddr":"192.168.13.227","user":"--","app":"core","method":"GET","url":"/","message":"Could not resolve OCA\\Theming\\Service\\ThemesService! Class \"OCA\\Theming\\Service\\ThemesService\" does not exist","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36","version":"","exception":{"Exception":"OC\\AppFramework\\Utility\\QueryNotFoundException","Message":"Could not resolve OCA\\Theming\\Service\\ThemesService! Class \"OCA\\Theming\\Service\\ThemesService\" does not exist","Code":0,"Trace":[{"file":"/app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php","line":124,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/app/www/public/lib/private/ServerContainer.php","line":155,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php","line":42,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"/app/www/public/lib/public/Server.php","line":39,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/app/www/public/lib/private/TemplateLayout.php","line":183,"function":"get","class":"OCP\\Server","type":"::"},{"file":"/app/www/public/lib/private/legacy/OC_Template.php","line":120,"function":"__construct","class":"OC\\TemplateLayout","type":"->"},{"file":"/app/www/public/lib/private/Template/Base.php","line":113,"function":"fetchPage","class":"OC_Template","type":"->"},{"file":"/app/www/public/lib/private/legacy/OC_Template.php","line":210,"function":"printPage","class":"OC\\Template\\Base","type":"->"},{"file":"/app/www/public/core/Controller/SetupController.php","line":83,"function":"printGuestPage","class":"OC_Template","type":"::"},{"file":"/app/www/public/core/Controller/SetupController.php","line":55,"function":"display","class":"OC\\Core\\Controller\\SetupController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/app/www/public/lib/base.php","line":973,"function":"run","class":"OC\\Core\\Controller\\SetupController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/app/www/public/index.php","line":24,"function":"handleRequest","class":"OC","type":"::"}],"File":"/app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php","Line":113,"message":"Could not resolve OCA\\Theming\\Service\\ThemesService! Class \"OCA\\Theming\\Service\\ThemesService\" does not exist","exception":{},"CustomMessage":"Could not resolve OCA\\Theming\\Service\\ThemesService! Class \"OCA\\Theming\\Service\\ThemesService\" does not exist"}}
{"reqId":"FOaCwPhPgEWvwxJdzr0w","level":3,"time":"2025-04-11T14:45:38+00:00","remoteAddr":"192.168.13.227","user":"--","app":"core","method":"GET","url":"/","message":"Could not resolve OCA\\Theming\\Service\\ThemesService! Class \"OCA\\Theming\\Service\\ThemesService\" does not exist","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36","version":"","exception":{"Exception":"OC\\AppFramework\\Utility\\QueryNotFoundException","Message":"Could not resolve OCA\\Theming\\Service\\ThemesService! Class \"OCA\\Theming\\Service\\ThemesService\" does not exist","Code":0,"Trace":[{"file":"/app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php","line":124,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/app/www/public/lib/private/ServerContainer.php","line":155,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php","line":42,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"/app/www/public/lib/public/Server.php","line":39,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/app/www/public/lib/private/TemplateLayout.php","line":183,"function":"get","class":"OCP\\Server","type":"::"},{"file":"/app/www/public/lib/private/legacy/OC_Template.php","line":120,"function":"__construct","class":"OC\\TemplateLayout","type":"->"},{"file":"/app/www/public/lib/private/Template/Base.php","line":113,"function":"fetchPage","class":"OC_Template","type":"->"},{"file":"/app/www/public/lib/private/legacy/OC_Template.php","line":297,"function":"printPage","class":"OC\\Template\\Base","type":"->"},{"file":"/app/www/public/index.php","line":89,"function":"printExceptionErrorPage","class":"OC_Template","type":"::"}],"File":"/app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php","Line":113,"message":"Could not resolve OCA\\Theming\\Service\\ThemesService! Class \"OCA\\Theming\\Service\\ThemesService\" does not exist","exception":{},"CustomMessage":"Could not resolve OCA\\Theming\\Service\\ThemesService! Class \"OCA\\Theming\\Service\\ThemesService\" does not exist"}}
{"reqId":"tCNBueYQ2IcoXFiiCtst","level":3,"time":"2025-04-11T14:45:38+00:00","remoteAddr":"192.168.13.227","user":"--","app":"index","method":"GET","url":"/favicon.ico","message":"Could not resolve OCA\\Theming\\Service\\ThemesService! Class \"OCA\\Theming\\Service\\ThemesService\" does not exist","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36","version":"","exception":{"Exception":"OC\\AppFramework\\Utility\\QueryNotFoundException","Message":"Could not resolve OCA\\Theming\\Service\\ThemesService! Class \"OCA\\Theming\\Service\\ThemesService\" does not exist","Code":0,"Trace":[{"file":"/app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php","line":124,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/app/www/public/lib/private/ServerContainer.php","line":155,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php","line":42,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"/app/www/public/lib/public/Server.php","line":39,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/app/www/public/lib/private/TemplateLayout.php","line":183,"function":"get","class":"OCP\\Server","type":"::"},{"file":"/app/www/public/lib/private/legacy/OC_Template.php","line":120,"function":"__construct","class":"OC\\TemplateLayout","type":"->"},{"file":"/app/www/public/lib/private/Template/Base.php","line":113,"function":"fetchPage","class":"OC_Template","type":"->"},{"file":"/app/www/public/lib/private/legacy/OC_Template.php","line":210,"function":"printPage","class":"OC\\Template\\Base","type":"->"},{"file":"/app/www/public/core/Controller/SetupController.php","line":83,"function":"printGuestPage","class":"OC_Template","type":"::"},{"file":"/app/www/public/core/Controller/SetupController.php","line":55,"function":"display","class":"OC\\Core\\Controller\\SetupController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/app/www/public/lib/base.php","line":973,"function":"run","class":"OC\\Core\\Controller\\SetupController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/app/www/public/index.php","line":24,"function":"handleRequest","class":"OC","type":"::"}],"File":"/app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php","Line":113,"message":"Could not resolve OCA\\Theming\\Service\\ThemesService! Class \"OCA\\Theming\\Service\\ThemesService\" does not exist","exception":{},"CustomMessage":"Could not resolve OCA\\Theming\\Service\\ThemesService! Class \"OCA\\Theming\\Service\\ThemesService\" does not exist"}}
{"reqId":"tCNBueYQ2IcoXFiiCtst","level":3,"time":"2025-04-11T14:45:38+00:00","remoteAddr":"192.168.13.227","user":"--","app":"core","method":"GET","url":"/favicon.ico","message":"Could not resolve OCA\\Theming\\Service\\ThemesService! Class \"OCA\\Theming\\Service\\ThemesService\" does not exist","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36","version":"","exception":{"Exception":"OC\\AppFramework\\Utility\\QueryNotFoundException","Message":"Could not resolve OCA\\Theming\\Service\\ThemesService! Class \"OCA\\Theming\\Service\\ThemesService\" does not exist","Code":0,"Trace":[{"file":"/app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php","line":124,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/app/www/public/lib/private/ServerContainer.php","line":155,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php","line":42,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"/app/www/public/lib/public/Server.php","line":39,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/app/www/public/lib/private/TemplateLayout.php","line":183,"function":"get","class":"OCP\\Server","type":"::"},{"file":"/app/www/public/lib/private/legacy/OC_Template.php","line":120,"function":"__construct","class":"OC\\TemplateLayout","type":"->"},{"file":"/app/www/public/lib/private/Template/Base.php","line":113,"function":"fetchPage","class":"OC_Template","type":"->"},{"file":"/app/www/public/lib/private/legacy/OC_Template.php","line":210,"function":"printPage","class":"OC\\Template\\Base","type":"->"},{"file":"/app/www/public/core/Controller/SetupController.php","line":83,"function":"printGuestPage","class":"OC_Template","type":"::"},{"file":"/app/www/public/core/Controller/SetupController.php","line":55,"function":"display","class":"OC\\Core\\Controller\\SetupController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/app/www/public/lib/base.php","line":973,"function":"run","class":"OC\\Core\\Controller\\SetupController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/app/www/public/index.php","line":24,"function":"handleRequest","class":"OC","type":"::"}],"File":"/app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php","Line":113,"message":"Could not resolve OCA\\Theming\\Service\\ThemesService! Class \"OCA\\Theming\\Service\\ThemesService\" does not exist","exception":{},"CustomMessage":"Could not resolve OCA\\Theming\\Service\\ThemesService! Class \"OCA\\Theming\\Service\\ThemesService\" does not exist"}}
{"reqId":"tCNBueYQ2IcoXFiiCtst","level":3,"time":"2025-04-11T14:45:38+00:00","remoteAddr":"192.168.13.227","user":"--","app":"core","method":"GET","url":"/favicon.ico","message":"Could not resolve OCA\\Theming\\Service\\ThemesService! Class \"OCA\\Theming\\Service\\ThemesService\" does not exist","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36","version":"","exception":{"Exception":"OC\\AppFramework\\Utility\\QueryNotFoundException","Message":"Could not resolve OCA\\Theming\\Service\\ThemesService! Class \"OCA\\Theming\\Service\\ThemesService\" does not exist","Code":0,"Trace":[{"file":"/app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php","line":124,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/app/www/public/lib/private/ServerContainer.php","line":155,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php","line":42,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"/app/www/public/lib/public/Server.php","line":39,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/app/www/public/lib/private/TemplateLayout.php","line":183,"function":"get","class":"OCP\\Server","type":"::"},{"file":"/app/www/public/lib/private/legacy/OC_Template.php","line":120,"function":"__construct","class":"OC\\TemplateLayout","type":"->"},{"file":"/app/www/public/lib/private/Template/Base.php","line":113,"function":"fetchPage","class":"OC_Template","type":"->"},{"file":"/app/www/public/lib/private/legacy/OC_Template.php","line":297,"function":"printPage","class":"OC\\Template\\Base","type":"->"},{"file":"/app/www/public/index.php","line":89,"function":"printExceptionErrorPage","class":"OC_Template","type":"::"}],"File":"/app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php","Line":113,"message":"Could not resolve OCA\\Theming\\Service\\ThemesService! Class \"OCA\\Theming\\Service\\ThemesService\" does not exist","exception":{},"CustomMessage":"Could not resolve OCA\\Theming\\Service\\ThemesService! Class \"OCA\\Theming\\Service\\ThemesService\" does not exist"}}
```

### Steps to reproduce

1. Untar the tar.bz2 artifact on Ubuntu Noble
2. Serve it with nginx and php 8.3

### Expected behavior

Wizard page comes up

### Nextcloud Server version

31

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Nginx

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json
Nextcloud is not installed - only a limited number of commands are available

                                                            
  There are no commands defined in the "config" namespace.
```

### List of activated Apps

```shell
Nextcloud is not installed - only a limited number of commands are available

                                                         
  There are no commands defined in the "app" namespace.
```

### Nextcloud Signing status

```shell
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.
```

### Nextcloud Logs

```json
Included above ^^
```

### Additional info

Could be related to https://github.com/nextcloud/server/commit/cfdd691f28c7fb6789b98ff4e7335585514e0959

### PR DESCRIPTION
**Pull request by ArtificialOwl**
fix #52131

regression: https://github.com/nextcloud/server/commit/00580b369e770221edc6670a06de4c2d03832fdf

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

File: lib/private/TemplateLayout.php [hunk 1]
```diff
@@ -180,8 +180,12 @@ public function __construct($renderAs, $appId = '') {
 		}
 
 		// Set body data-theme
-		$themesService = \OCP\Server::get(\OCA\Theming\Service\ThemesService::class);
-		$this->assign('enabledThemes', $themesService->getEnabledThemes());
+		try {
+			$themesService = \OCP\Server::get(\OCA\Theming\Service\ThemesService::class);
```
Comment (susnux) [inline lib/private/TemplateLayout.php:184]: How can this class not exist? `theming` is force enabled - always.

File: lib/private/TemplateLayout.php [hunk 2]
```diff
@@ -180,8 +180,12 @@ public function __construct($renderAs, $appId = '') {
...
+		} catch (\Exception) {
```
Comment (susnux) [inline lib/private/TemplateLayout.php:185]:
```suggestion
		} catch (\OCP\AppFramework\QueryException) {
```

File: lib/private/TemplateLayout.php (hunk 1 above)
Comment (nickvergessen) [reply lib/private/TemplateLayout.php:184]: before installing?

Comment (ArtificialOwl) [reply lib/private/TemplateLayout.php:184]: it seems that it is not loaded during setup process

**Review by AndyScherzinger — APPROVED** [review]

File: lib/private/TemplateLayout.php (hunk 1 above)
Comment (nickvergessen) [reply lib/private/TemplateLayout.php:184]: Is it testable with CI?

**Comment by solracsf** [comment]
Also affects v30.

File: lib/private/TemplateLayout.php (hunk 1 above)
Comment (SystemKeeper) [reply lib/private/TemplateLayout.php:184]: Best would be to have e2e test for web setup (and also login flow...), most basic way would be to check if the setup page does not throw a 500 (before we install NC via occ)?

> docker run --rm --volume .:/var/www/html -it ghcr.io/nextcloud/continuous-integration-php8.1:latest bash -c "(php -S 0.0.0.0:80 -t /var/www/html &) && curl --retry 5 --retry-connrefused -I localhost"

**Review by susnux — APPROVED** [review]
