### PR TITLE
fix(user_status): use getFirstDay() from @nextcloud/l10n

### LINKED ISSUE #57804: [Bug]: Clear status after "This week" results in "There was an error saving the status"
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Setting "Clear status after" to "This week" results in a "There was an error saving the status" toast without any network requests and browser console errors.

### Steps to reproduce

1. Set a user status in the dialog
2. Set "Clear status after" to "This week"

### Expected behavior

No error like with any other value.

### Nextcloud Server version

33

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by cristianscheid**
* Resolves: #57804

## Summary
Fixes silent failure when setting "Clear status after: This week" from the status menu.

## Changes
- Fixed TypeError by importing and using `getFirstDay()` from `@nextcloud/l10n` instead of calling the non-existent `endOfWeek.getFirstDay()` method on a Date object

## Screenshots
[demo.webm](https://github.com/user-attachments/assets/9cf2e76f-3557-4289-951d-9545072cd305)

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)
- [x] [Labels added](https://github.com/nextcloud/server/labels) where applicable (ex: bug/enhancement, `3. to review`, feature component)
- [ ] [Milestone added](https://github.com/nextcloud/server/milestones) for target branch/version (ex: 32.x for `stable32`)

### CODE REVIEW

File: apps/user_status/src/services/clearAtService.js [hunk 1]
```diff
@@ -94,6 +94,6 @@ function getEndOfDay(date) {
  */
 function getEndOfWeek(date) {
 	const endOfWeek = getEndOfDay(date)
-	endOfWeek.setDate(date.getDate() + ((endOfWeek.getFirstDay() - 1 - endOfWeek.getDay() + 7) % 7))
+	endOfWeek.setDate(date.getDate() + ((getFirstDay() - 1 - endOfWeek.getDay() + 7) % 7))
```
Comment (Antreesy) [inline apps/user_status/src/services/clearAtService.js:97]: Works as expected:
Image

Image

**Review by Antreesy — APPROVED** [review]
Thanks!

I think something's messed up with the compiled assets, I'll check and rebase after second review, if needed

**Comment by Antreesy** [comment]
Checked `stable32` and `stable31`, there's still moment library used, so there's no silent error as on master. I removed the backport requests for those.

Although it gets the last day from user setting of 'locale', not user setting of 'first day of the week'. Should be adjusted separately for older branches, if needed

**Review by susnux — APPROVED** [review]
