### PR TITLE
Fix scanning app data with metadata

### LINKED ISSUE #32031: [Bug]: Call to a member function getFileInfo() on null in /var/www/nextcloud/lib/private/Metadata/FileEventListener.php:62
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When scanning the appdata I get the following error: 
```
Call to a member function getFileInfo() on null in /var/www/nextcloud/lib/private/Metadata/FileEventListener.php:62
```

### Steps to reproduce

1. Have an empty appdata folder
2. Run an `occ files:scan-app-data`

### Expected behavior

No errors

### Installation method

Manual installation

### Operating system

Other

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
-
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

```
Error: Call to a member function getFileInfo() on null in /var/www/nextcloud/lib/private/Metadata/FileEventListener.php:62
Stack trace:
#0 /var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php(87): OC\Metadata\FileEventListener->handle(Object(OCP\Files\Events\NodeRemovedFromCache))
#1 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(251): OC\EventDispatcher\ServiceEventListener->__invoke(Object(OCP\Files\Events\NodeRemovedFromCache), 'OCP\\Files\\Event...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'OCP\\Files\\Event...', Object(OCP\Files\Events\NodeRemovedFromCache))
#3 /var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php(88): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(OCP\Files\Events\NodeRemovedFromCache), 'OCP\\Files\\Event...')
#4 /var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php(100): OC\EventDispatcher\EventDispatcher->dispatch('OCP\\Files\\Event...', Object(OCP\Files\Events\NodeRemovedFromCache))
#5 /var/www/nextcloud/lib/private/Files/Utils/Scanner.php(235): OC\EventDispatcher\EventDispatcher->dispatchTyped(Object(OCP\Files\Events\NodeRemovedFromCache))
#6 [internal function]: OC\Files\Utils\Scanner->OC\Files\Utils\{closure}('appdata_oc7t2oj...')
#7 /var/www/nextcloud/lib/private/Hooks/EmitterTrait.php(106): call_user_func_array(Object(Closure), Array)
#8 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(273): OC\Hooks\BasicEmitter->emit('\\OC\\Files\\Cache...', 'removeFromCache', Array)
#9 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(475): OC\Files\Cache\Scanner->removeFromCache('appdata_oc7t2oj...')
#10 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(390): OC\Files\Cache\Scanner->handleChildren('appdata_oc7t2oj...', true, 3, 114983, true, 0)
#11 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(342): OC\Files\Cache\Scanner->scanChildren('appdata_oc7t2oj...', true, 3, 114983, true)
#12 /var/www/nextcloud/lib/private/Files/Cache/LocalRootScanner.php(39): OC\Files\Cache\Scanner->scan('appdata_oc7t2oj...', true, 3, true)
#13 /var/www/nextcloud/lib/private/Files/Utils/Scanner.php(256): OC\Files\Cache\LocalRootScanner->scan('appdata_oc7t2oj...', true, 3)
#14 /var/www/nextcloud/apps/files/lib/Command/ScanAppData.php(124): OC\Files\Utils\Scanner->scan('/appdata_oc7t2o...')
#15 /var/www/nextcloud/apps/files/lib/Command/ScanAppData.php(159): OCA\Files\Command\ScanAppData->scanFiles(Object(Symfony\Component\Console\Output\ConsoleOutput), '')
#16 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\ScanAppData->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/nextcloud/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\ScanAppData), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/nextcloud/console.php(99): OC\Console\Application->run()
#23 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
```
```


### Additional info

_No response_

### PR DESCRIPTION
**Pull request by CarlSchwan**
Previously we were listening to changes in the appdata folder but an
appdata scan didn't set up the file system, so the view was unavailable.

**Test plan:**

1. `rm -rf data/appdata_...../preview data/<user>/Media`
2. `occ files:scan-app-data`
3. `occ files:scan <user>`

No errors and the files and metadata are correctly removed from the
database too.

Fix #32031

### CODE REVIEW

File: lib/private/Metadata/FileEventListener.php [hunk 1]
```diff
@@ -52,13 +52,26 @@ private function shouldExtractMetadata(Node $node): bool {
...
 	public function handle(Event $event): void {
 		if ($event instanceof NodeRemovedFromCache) {
+			if (!$this->isCorrectPath($event->getPath())) {
+				// Don't listen to paths for which we don't extract metadata
+				return;
+			}
 			$view = Filesystem::getView();
+			if (!$view) {
+				// Should not happen since a scan in the user folder should setup
+				// the file system.
```
Comment (artonge) [inline lib/private/Metadata/FileEventListener.php:72]: If this is not supposed to happen, I would throw an exception here instead of returning.

Comment (CarlSchwan) [reply lib/private/Metadata/FileEventListener.php:72]: Not sure this is a good idea to throw an error as this would abord the scan but I should definitively at least log it as an error.

**Review by skjnldsv — APPROVED** [review]

File: lib/private/Metadata/FileEventListener.php [hunk 2]
```diff
@@ -31,12 +31,14 @@
 use OCP\Files\Node;
 use OCP\Files\NotFoundException;
 use OCP\Files\FileInfo;
+use Psr\Log\LoggerInterface;
 
 class FileEventListener implements IEventListener {
 	private IMetadataManager $manager;
```
Comment (skjnldsv) [inline lib/private/Metadata/FileEventListener.php:37]:
```suggestion
	private IMetadataManager $manager;
	private LoggerInterface $logger;
```

File: lib/private/Metadata/FileEventListener.php [hunk 3]
```diff
@@ -52,13 +54,31 @@ private function shouldExtractMetadata(Node $node): bool {
...
+			if (!$this->isCorrectPath($event->getPath())) {
+				// Don't listen to paths for which we don't extract metadata
+				return;
+			}
 			$view = Filesystem::getView();
+			if (!$view) {
+				// Should not happen since a scan in the user folder should setup
+				// the file system.
+				$e = new \Exception(); // don't trigger, just get backtrace
+				$this->log->error('Detecting deletion of a file with possible metadata but file system setup is not setup', [
```
Comment (skjnldsv) [inline lib/private/Metadata/FileEventListener.php:76]:
```suggestion
				$this->logger->error('Detecting deletion of a file with possible metadata but file system setup is not setup', [
```

File: lib/private/Metadata/FileEventListener.php (hunk 2 above)
Comment (skjnldsv) [inline lib/private/Metadata/FileEventListener.php:37]:
```suggestion
	private IMetadataManager $manager;
	private LoggerInterface $logger;
```

**Review by skjnldsv — CHANGES_REQUESTED** [review]

**Review by skjnldsv — APPROVED** [review]

**Review by PVince81 — APPROVED** [review]
:+1:
