### PR TITLE
Do not show 2FA settings if the user has no providers available

### LINKED ISSUE #13971: Personal Two-Factor Authentication settings visible even if no 2FA activated
### Steps to reproduce
1. Disable all 2FA apps (or never have activated one ever before)
2. Go to Settings > Personal > Security

### Expected behaviour
No settings for Two-Factor Authentication visible

### Actual behaviour
Two-Factor Authentication settings for Backup code generation visible

**Nextcloud version:**

15.0.2

### PR DESCRIPTION
**Pull request by ChristophWurst**
Fixes https://github.com/nextcloud/server/issues/13971

To test install a 2FA provider, then you will see the 2FA settings as a user. Once there is only the backup codes one left, the settings vanish.

### CODE REVIEW

File: apps/settings/lib/Settings/Personal/Security/TwoFactor.php [hunk 1]
```diff
@@ -69,13 +71,41 @@ public function getForm(): TemplateResponse {
...
+
+		// If there is at least one provider with personal settings but it's not
+		// the backup codes provider, then these settings should show.
+		foreach ($providers as $provider) {
+			if ($provider instanceof IProvidesPersonalSettings
+				&& !($provider instanceof BackupCodesProvider)) {
+				return true;
+			}
+		}
+		return false;
```
Comment (rullzer) [inline apps/settings/lib/Settings/Personal/Security/TwoFactor.php:106]: What about if the backupprovider is the onyl provider but it is still enabled?

Comment (ChristophWurst) [reply apps/settings/lib/Settings/Personal/Security/TwoFactor.php:105]: I tried to explain this on L97-98. If the backup codes provider is the only one, then we don't show the settings neither.

But now that I think about it maybe we should only hide this if there is no provide other than the backup provider and 2FA is not enforced.

Users who have it enforced should see the backup code provider settings.

Comment (ChristophWurst) [reply apps/settings/lib/Settings/Personal/Security/TwoFactor.php:116]: Fixed.

**Review by rullzer — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍
