### PR TITLE
fix(db): Create replacement index where original index is missing

### LINKED ISSUE #9810: missing indices after activating Mail in NC-AIO
### Steps to reproduce

1. install NC AIO
2. activate Mail app
3. got to system admin page
message displayed:
The database is missing some indexes. Due to the fact that adding indexes on big tables could take some time they were not added automatically. By running "occ db:add-missing-indices" those missing indexes could be added manually while the instance keeps running. Once the indexes are added queries to those tables are usually much faster. Missing optional index "mail_messages_strucanalyz_idx" in table "mail_messages". Missing optional index "mail_class_creat_idx" in table "mail_classifiers". Missing optional index "mail_acc_prov_idx" in table "mail_accounts". Missing optional index "mail_alias_accid_idx" in table "mail_aliases". Missing optional index "mail_messages_mb_id_uid_uidx" in table "mail_messages". Missing optional index "mail_smime_certs_uid_email_idx" in table "mail_smime_certificates". Missing optional index "mail_trusted_senders_idx" in table "mail_trusted_senders". Missing optional index "mail_coll_idx" in table "mail_coll_addresses".

### Expected behavior

all indices should be created

### Actual behavior

missing indices

### Mail app version

3.7.2

### Mailserver or service

_No response_

### Operating system

AWS ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database

PostgreSQL

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ChristophWurst**
* Resolves: https://github.com/nextcloud/mail/issues/9810

## Summary

While working on https://github.com/nextcloud/server/pull/51438 I noticed that replacement indexes are not created if the old indexes don't exist. This can happen in the following deployment

1. Table is created but without index
2. Optional index is added but admin never applies it
3. The previously optional index is replaced by another one

Before: old and new index were missing
After: new index is added

The setup check has already reported the affected indices as missing, but they were never added.

## TODO

- [x] Make the changes
- [x] Test the changes

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: core/Command/Db/AddMissingIndices.php [hunk 1]
```diff
@@ -53,6 +54,22 @@ protected function execute(InputInterface $input, OutputInterface $output): int
 		if ($missingIndices !== [] || $toReplaceIndices !== []) {
 			$schema = new SchemaWrapper($this->connection);
 
+			foreach ($toReplaceIndices as $toReplaceIndex) {
+				if ($schema->hasTable($toReplaceIndex['tableName'])) {
+					$table = $schema->getTable($toReplaceIndex['tableName']);
+					// If none of the previous indices existed we have to add the index
+					if (array_filter($toReplaceIndex['oldIndexNames'], static fn (string $indexName) => $table->hasIndex($indexName)) === []) {
+						$missingIndices[] = [
```
Comment (lars-sh) [inline core/Command/Db/AddMissingIndices.php:62]: I saw an entry in the Nextcloud log saying "Undefined array key "dropUnnamedIndex" at /knickrehm/www/cloud/core/Command/Db/AddMissingIndices.php#79" after applying this fix. From what I see, this array should contain a value for the key "dropUnnamedIndex" or 79 should not expect a value to exist for that key.

Comment (ChristophWurst) [reply core/Command/Db/AddMissingIndices.php:62]: Good catch!

**Review by come-nc — COMMENTED** [review]
Not sure I get it, there was a code path for when all old names existed, you added one for when non of them exists, but there is still an issue if only some of them exists, no?

Why not simply ignore the existing, add the new one and then drop the old ones if they exist?

**Comment by ChristophWurst** [comment]
Actually fair point. I'll look into that!

**Review by Altahrim — APPROVED** [review]

**Comment by ChristophWurst** [comment]
@come-nc thanks a lot for the suggestion. The code is a lot simpler now!

**Review by come-nc — APPROVED** [review]

**Review by Altahrim — APPROVED** [review]
