### PR TITLE
fix(settings): Fix infinitely loading account management page with pagination of groups

### LINKED ISSUE #50067: [Bug]: Administrative Account Page hangs when having many (ldap-)groups
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

During testing the migratability of a bigger owncloud instance to nextcloud i encountered an issue that the Administrative Account Page will not load, in the form that the tab will hang indefinitely or crash.

It seems that something goes awry with "too many" groups.

(10000 LDAP/AD-users, 15000 LDAP/AD-groups and 10 local-db-users, 500 local-db-groups; most of which are dead/inactive)

### Steps to reproduce

1. Have 10000 LDAP/AD-users, 15000 LDAP/AD-groups + 10 local-db-users, 500 local-db-groups
2. Open https://.../index.php/settings/users
3. Tab hangs or crashes.

Disable LDAP-Groups (set group filter to for example ``(&(|(objectclass=groupp)))``)
1. Have 10000 LDAP/AD-users, 0 LDAP/AD-groups + 10 local-db-users, 500 local-db-groups
2. Open https://.../index.php/settings/users
3. Tab loads after a while.

### Expected behavior

The Tab to load always.

### Nextcloud Server version

30

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [x] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by Pytal**
## Summary

- Fix https://github.com/nextcloud/server/issues/50067

With a large number of groups, e.g. >=10,000, the compute load on the server and client becomes excessive. On the server all groups are pre-computed in-memory resulting in increased response latency and excessive payload size. As a result the page loads indefinitely and becomes unresponsive.

### To Do

- Paginate groups
- Search for groups
- Remove unnecessary and expensive pre-computation of entire groups list on the server every page load
  - For 10,000 groups, server compute time is reduced by 5s
- Allow searching for groups when editing accounts or creating a new account
- Defer loading details of a user’s groups
- Adapt all logic dependent on having entire groups list in-memory for paginated groups list

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/provisioning_api/lib/Controller/UsersController.php [hunk 1]
```diff
@@ -1402,6 +1403,127 @@ public function getUsersGroups(string $userId): DataResponse {
 		}
 	}
 
+	/**
+	 * @NoSubAdminRequired
+	 *
+	 * Get a list of groups with details
+	 *
+	 * @param string $userId ID of the user
+	 * @return DataResponse<Http::STATUS_OK, array{groups: list<array{id: string, displayname: string, usercount: int, disabled: int, canAdd: bool, canRemove: bool}>}, array{}>
```
Comment (come-nc) [inline apps/provisioning_api/lib/Controller/UsersController.php:1412]:
```suggestion
	 * @return DataResponse<Http::STATUS_OK, array{groups: list<array{id: string, displayname: string, usercount: bool|int, disabled: bool|int, canAdd: bool, canRemove: bool}>}, array{}>
```

File: apps/provisioning_api/lib/Controller/UsersController.php [hunk 2]
```diff
@@ -1402,6 +1403,127 @@ public function getUsersGroups(string $userId): DataResponse {
...
+				// Not permitted
+				throw new OCSException('', OCSController::RESPOND_NOT_FOUND);
+			}
+		}
+	}
+
+	/**
+	 * @NoSubAdminRequired
+	 *
+	 * Get a list of the user's subadmin groups with details
```
Comment (come-nc) [inline apps/provisioning_api/lib/Controller/UsersController.php:1486]:
```suggestion
	 * Get a list of the groups the user is a subadmin of, with details
```
If I understood correctly what it does

Comment (come-nc) [inline apps/provisioning_api/lib/Controller/UsersController.php:1486]:
```suggestion
	 * Get a list of the groups the user is a subadmin of, with details
```
If I understood correctly what it does

Comment (come-nc) [inline apps/provisioning_api/lib/Controller/UsersController.php:1486]:
```suggestion
	 * Get a list of the groups the user is a subadmin of, with details
```
If I understood correctly what it does

**Comment by come-nc** [comment]
Copie d'écran_20250320_112212

I suppose I will not be the only one with numbered groups, maybe natural sorting would make sense?

**Comment by come-nc** [comment]
Apart from that, tested, all good, nice work!

**Comment by come-nc** [comment]
@Pytal Failed cypress tests are related I think

File: apps/provisioning_api/lib/Controller/UsersController.php [hunk 3]
```diff
@@ -1402,6 +1403,127 @@ public function getUsersGroups(string $userId): DataResponse {
...
+		$isDelegatedAdmin = $this->groupManager->isDelegatedAdmin($loggedInUser->getUID());
+		if ($targetUser->getUID() === $loggedInUser->getUID() || $isAdmin || $isDelegatedAdmin) {
+			// Self lookup or admin lookup
+			$groups = array_map(
+				function (Group $group) {
+					return [
+						'id' => $group->getGID(),
+						'displayname' => $group->getDisplayName(),
+						'usercount' => (int)$group->count(),
+						'disabled' => (int)$group->countDisabled(),
```
Comment (come-nc) [inline apps/provisioning_api/lib/Controller/UsersController.php:1436]: Wait, now `false` and `0`  will both end up being `0` and the frontend cannot know if the group is empty or if count is not supported.
You should either keep the false or turn it into a special value like `-1` so that the frontend knows what it means.
And in both cases it should be documented.

File: apps/settings/src/components/AppNavigationGroupList.vue [hunk 4]
```diff
@@ -0,0 +1,200 @@
...
+				:name="group.title"
+				:count="group.count" />
+			<div v-if="loadingGroups" role="note">
+				<NcLoadingIcon :name="t('settings', 'Loading groups…')" />
+			</div>
+		</NcAppNavigationList>
+	</Fragment>
+</template>
+
+<script setup lang="ts">
```
Comment (susnux) [inline apps/settings/src/components/AppNavigationGroupList.vue:59]: :heart: :rocket:

**Review by susnux — APPROVED** [review]

**Review by artonge — APPROVED** [review]

File: apps/provisioning_api/lib/Controller/UsersController.php (hunk 3 above)
Comment (Pytal) [reply apps/provisioning_api/lib/Controller/UsersController.php]: Now aligned with the `/groups/details` endpoint

**Comment by solracsf** [comment]
This PR is causing issues in groups display names: https://github.com/nextcloud/server/issues/52130

**Comment by provokateurin** [comment]
@solracsf please do it the other way around and mention the PR in the issue and avoid bumping merged PRs.
