### PR TITLE
fix(component): utilized NcDateTime component

### LINKED ISSUE #41261: Replace mtime render with `NcDateTime`
https://nextcloud-vue-components.netlify.app/#/Components/NcDateTime
https://github.com/nextcloud/server/blob/4db03884a566bc637e859cb83c806201b326bb3c/apps/files/src/components/FileEntry.vue#L80-L87

### PR DESCRIPTION
**Pull request by emoral435**
Resolves #41261
Replaces span element with custom Nc Vue Component
Signed-off-by: Eduardo Morales <emoral435@gmail.com>

* Resolves: #41261

## BEFORE
chrome_c0cPiphzOz
## AFTER
chrome_c0cPiphzOz

## Summary
Replaces span element with custom Nc Vue Component. Frontend looks the same, but the actual code uses the Nextcloud Component

## TODO

- [x] utilize prebuilt NcDateTime component from @nextcloud/vue library

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/files/src/components/FileEntry.vue [hunk 1]
```diff
@@ -20,7 +20,7 @@
   -
   -->
 
-<template>
+  <template>
```
Comment (skjnldsv) [inline apps/files/src/components/FileEntry.vue:23]:
```suggestion
<template>
```

File: apps/files/src/components/FileEntry.vue [hunk 2]
```diff
@@ -262,6 +264,12 @@ export default Vue.extend({
 			}
 			return t('files_trashbin', 'A long time ago')
 		},
+		mDateTime() {
+			if (this.source.mtime) {
+				return moment(this.source.mtime)
```
Comment (skjnldsv) [inline apps/files/src/components/FileEntry.vue:269]: Actually, I think `NcDateTime` requires a `Date` object, not `moment`
https://nextcloud-vue-components.netlify.app/#/Components/NcDateTime
image

File: apps/files/src/components/FileEntry.vue [hunk 3]
```diff
@@ -262,6 +264,12 @@ export default Vue.extend({
 			}
 			return t('files_trashbin', 'A long time ago')
```
Comment (skjnldsv) [inline apps/files/src/components/FileEntry.vue:265]:
```suggestion
			return t('files', 'A long time ago')
```

File: apps/files/src/components/FileEntry.vue [hunk 4]
```diff
@@ -262,6 +264,12 @@ export default Vue.extend({
...
 		},
+		mDateTime() {
+			if (this.source.mtime) {
+				return moment(this.source.mtime)
+			}
+			return t('files_trashbin', 'A long time ago')
```
Comment (skjnldsv) [inline apps/files/src/components/FileEntry.vue:271]:
```suggestion
			return t('files', 'A long time ago')
```

File: apps/files/src/components/FileEntry.vue (hunk 3 above)
Comment (skjnldsv) [inline apps/files/src/components/FileEntry.vue:265]: I think the entire`mtime` computed can be removed since it's unused ?

File: apps/files/src/components/FileEntry.vue [hunk 5]
```diff
@@ -83,7 +83,7 @@
 			class="files-list__row-mtime"
 			data-cy-files-list-row-mtime
 			@click="openDetailsIfAvailable">
-			<span>{{ mtime }}</span>
+			<NcDateTime :timestamp="mDateTime"/>
```
Comment (skjnldsv) [inline apps/files/src/components/FileEntry.vue:86]: I would suggest to remove the seconds with this:

```suggestion
			<NcDateTime :timestamp="mDateTime" :ignore-seconds="true" />
```

**Review by skjnldsv — DISMISSED** [review]
Nice!!
See inline comments :)

File: apps/files/src/components/FileEntry.vue (hunk 2 above)
Comment (susnux) [reply apps/files/src/components/FileEntry.vue:269]: Yes `Date` object means the JS native `Date`

**Comment by emoral435** [comment]
I removed the mtime computed section because yeah, it wasn't really being used! Nice catch!
And because the mtime member from the Node class returns a date object of when it was modified, I used that

File: apps/files/src/components/FileEntry.vue [hunk 6]
```diff
@@ -255,13 +257,6 @@ export default Vue.extend({
 				color: `color-mix(in srgb, var(--color-main-text) ${ratio}%, var(--color-text-maxcontrast))`,
 			}
 		},
-
-		mtime() {
-			if (this.source.mtime) {
```
Comment (susnux) [inline apps/files/src/components/FileEntry.vue:260]: Can this be empty? In this case NcDateTime will throw an error as the value must be int or Date. If not everything should be fine.

**Review by susnux — APPROVED** [review]

File: apps/files/src/components/FileEntry.vue (hunk 6 above)
Comment (susnux) [reply apps/files/src/components/FileEntry.vue:260]: >  And because the mtime member from the Node class returns a date object of when it was modified, I used that

Ah did not see that, then it should be fine

Comment (emoral435) [reply apps/files/src/components/FileEntry.vue:260]: I believe it can't be empty under most circumstances, but to comply with the rest of the checks in place with the rest of the file, I'll add in some checks so that if the mtime is empty, we get a default translatable string to display instead

Comment (emoral435) [reply apps/files/src/components/FileEntry.vue:260]: Actually, because this is only conditionally rendered when the mtime is not empty, then this wont throw an error, so your right! It should be fine

File: apps/files/src/components/FileEntry.vue (hunk 1 above)
Comment (emoral435) [reply apps/files/src/components/FileEntry.vue]: Moved this back in by a bit, I must have hit a space by accident! Whoops

File: apps/files/src/components/FileEntry.vue (hunk 3 above)
Comment (emoral435) [reply apps/files/src/components/FileEntry.vue]: Agreed, removed it 👍

File: apps/files/src/components/FileEntry.vue [hunk 7]
```diff
@@ -83,7 +83,7 @@
 			class="files-list__row-mtime"
 			data-cy-files-list-row-mtime
 			@click="openDetailsIfAvailable">
-			<span>{{ mtime }}</span>
+			<NcDateTime :timestamp="this.source.mtime" :ignore-seconds="true" />
```
Comment (Pytal) [inline apps/files/src/components/FileEntry.vue:86]:
```suggestion
			<NcDateTime :timestamp="source.mtime" :ignore-seconds="true" />
```
`this` is not needed in template

Comment (emoral435) [reply apps/files/src/components/FileEntry.vue:86]: changing this right now, thank you!

**Review by Pytal — APPROVED** [review]
