### PR TITLE
fix(Cron): Log WebCron access at INFO LEVEL

### LINKED ISSUE #58470: `RuntimeException Backgroundjobs are using system cron! log error while they are not`
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After upgrading to 33, a new error starts popping up in the server:

`RuntimeException Backgroundjobs are using system cron!`

First of all, the "Basic" configuration page literally encourages to use system cron:  "Use system cron service to call the cron.php file every 5 minutes." so it is kind of misleading.

My particular server does not use the system cron service (empty crontabs for all users), instead it uses the [recommended timer/system service combination](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/background_jobs_configuration.html#systemd) and according to the guide, it uses www-data as the service user.

### Steps to reproduce

1. On a <33.0 instance, create timer and service accordingly, set up various background workers.
2. Upgrade to 33.0
3. Errors start popping up in the logs.

### Expected behavior

No errors, as the server does not use system cron.

### Nextcloud Server version

33

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 31 to 32)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json
{
    "system": {
        "default_phone_region": "PL",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "serverid": 0,
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.jakobczyk.org",
            "www.home102"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "push": "https:\/\/cloud.jakobczyk.org\/push",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR",
            "HTTP_X_REAL_IP"
        ],
        "allow_local_remote_servers": true,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "",
        "dbtype": "mysql",
        "version": "33.0.0.16",
        "overwrite.cli.url": "https:\/\/cloud.jakobczyk.org\/",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "dbindex": 0,
            "timeout": 1.5
        },
        "maintenance": false,
        "theme": "",
        "maintenance_window_start": 1,
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 3,
        "simpleSignUpLink.shown": false,
        "log_rotate_size": 10485760,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": true,
        "mail_smtpport": "587",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "app.mail.imap.timeout": 10,
        "app.mail.smtp.timeout": 20,
        "app.mail.sieve.timeout": 15,
        "app.mail.verify-tls-peer": false,
        "app.mail.background-sync-interval": 600,
        "app_install_overwrite": [
            "occweb",
            "impersonate",
            "groupfolders"
        ],
        "memories.db.triggers.fcu": true,
        "memories.exiftool": "\/mnt\/www\/nextcloud\/apps\/memories\/bin-ext\/exiftool-amd64-glibc",
        "memories.vod.path": "\/mnt\/www\/nextcloud\/apps\/memories\/bin-ext\/go-vod-amd64",
        "memories.vod.ffmpeg": "\/usr\/bin\/ffmpeg",
        "memories.vod.ffprobe": "\/usr\/bin\/ffprobe",
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\Movie"
        ],
        "preview_max_x": 1024,
        "preview_max_y": 1024,
        "memories.gis_type": 1,
        "forbidden_filename_basenames": [
            "con",
            "prn",
            "aux",
            "nul",
            "com0",
            "com1",
            "com2",
            "com3",
            "com4",
            "com5",
            "com6",
            "com7",
            "com8",
            "com9",
            "com\u00b9",
            "com\u00b2",
            "com\u00b3",
            "lpt0",
            "lpt1",
            "lpt2",
            "lpt3",
            "lpt4",
            "lpt5",
            "lpt6",
            "lpt7",
            "lpt8",
            "lpt9",
            "lpt\u00b9",
            "lpt\u00b2",
            "lpt\u00b3"
        ],
        "forbidden_filename_characters": [
            "<",
            ">",
            ":",
            "\"",
            "|",
            "?",
            "*",
            "\\",
            "\/"
        ],
        "forbidden_filename_extensions": [
            " ",
            ".",
            ".filepart",
            ".part"
        ],
        "mail_smtpstreamoptions": {
            "ssl": {
                "allow_self_signed": false,
                "verify_peer": true,
                "verify_peer_name": true
            }
        }
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 6.0.0-dev.0
  - app_api: 33.0.0
  - assistant: 3.3.0
  - bruteforcesettings: 6.0.0-dev.0
  - circles: 33.0.0
  - cloud_federation_api: 1.17.0
  - comments: 1.23.0
  - contactsinteraction: 1.14.1
  - context_chat: 5.3.1
  - dashboard: 7.13.0
  - dav: 1.36.0
  - federatedfilesharing: 1.23.0
  - federation: 1.23.0
  - files: 2.5.0
  - files_downloadlimit: 5.1.0-dev.0
  - files_external: 1.25.1
  - files_pdfviewer: 6.0.0-dev.0
  - files_reminders: 1.6.0
  - files_sharing: 1.25.2
  - files_trashbin: 1.23.0
  - files_versions: 1.26.0
  - groupfolders: 21.0.5
  - impersonate: 4.0.0
  - integration_openai: 4.2.0
  - logreader: 6.0.0
  - lookup_server_connector: 1.21.0
  - mail: 5.7.0
  - nextcloud_announcements: 5.0.0
  - notifications: 6.0.0
  - notify_push: 1.3.0
  - oauth2: 1.21.0
  - password_policy: 5.0.0-dev.0
  - photos: 6.0.0-dev.0
  - previewgenerator: 5.12.1
  - privacy: 5.0.0-dev.0
  - profile: 1.2.0
  - provisioning_api: 1.23.0
  - recognize: 11.0.1
  - recommendations: 6.0.0-dev.0
  - related_resources: 4.0.0-dev.0
  - serverinfo: 5.0.0-dev.0
  - settings: 1.16.0
  - sharebymail: 1.23.0
  - support: 5.0.0
  - survey_client: 5.0.0-dev.0
  - systemtags: 1.23.0
  - text: 7.0.0-dev.3
  - theming: 2.8.0
  - twofactor_backupcodes: 1.22.0
  - twofactor_totp: 15.0.0-dev.0
  - updatenotification: 1.23.0
  - user_status: 1.13.0
  - viewer: 6.0.0-dev.0
  - weather_status: 1.13.0
  - webhook_listeners: 1.5.0
  - workflowengine: 2.15.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```json
{"reqId":"WYMqtSla42G05aaXqipM","level":3,"time":"2026-02-19T20:06:29+00:00","remoteAddr":"159.65.164.107","user":"--","app":"cron","method":"GET","url":"/cron.php","scriptName":"/cron.php","message":"Backgroundjobs are using system cron!","userAgent":"Cronless/2.0 (+http://cronless.com)","version":"33.0.0.16","exception":{"Exception":"RuntimeException","Message":"Backgroundjobs are using system cron!","Code":0,"Trace":[{"file":"/mnt/www/nextcloud/core/Service/CronService.php","line":100,"function":"runWeb","class":"OC\\Core\\Service\\CronService","type":"->"},{"file":"/mnt/www/nextcloud/cron.php","line":52,"function":"run","class":"OC\\Core\\Service\\CronService","type":"->"}],"File":"/mnt/www/nextcloud/core/Service/CronService.php","Line":229,"message":"Backgroundjobs are using system cron!","exception":"{\"class\":\"RuntimeException\",\"message\":\"Backgroundjobs are using system cron!\",\"code\":0,\"file\":\"/mnt/www/nextcloud/core/Service/CronService.php:229\",\"trace\":\"#0 /mnt/www/nextcloud/core/Service/CronService.php(100): OC\\Core\\Service\\CronService->runWeb()\\n#1 /mnt/www/nextcloud/cron.php(52): OC\\Core\\Service\\CronService->run()\\n#2 {main}\"}","CustomMessage":"Backgroundjobs are using system cron!"},"id":"6998c455b48c7"}
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by joshtrichards**
Fixes #58470

* Resolves: #58470 

## Summary

During a refactor (#55517), this error message was changed from only being sent (as web output) to the external caller (e.g. whatever this external service is that is calling your `/cron.php` URL via HTTP) to throwing a runtime exception and, as a result, then being logged on the instance now (albeit indirectly by throwing an exception).

This PR adjusts is so that:

- it no longer throws an exception that gets logged at level 3
- logs at info level only then returns silently

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)
- [ ] [Labels added](https://github.com/nextcloud/server/labels) where applicable (ex: bug/enhancement, `3. to review`, feature component)
- [ ] [Milestone added](https://github.com/nextcloud/server/milestones) for target branch/version (ex: 32.x for `stable32`)

### CODE REVIEW

File: core/Service/CronService.php [hunk 1]
```diff
@@ -226,7 +226,7 @@ private function runCli(string $appMode, ?array $jobClasses): void {
 	private function runWeb(string $appMode): void {
 		if ($appMode === 'cron') {
 			// Cron is cron :-P
-			throw new \RuntimeException('Backgroundjobs are using system cron!');
+			$this->logger->info('WebCron accessed even though backgroundjobs_mode is set to use system cron.', ['app' => 'cron']);
```
Comment (susnux) [inline core/Service/CronService.php:229]: Not sure because recommended log level is warning and then you would not get this warning about invalid access.
I think at least `warning` is the correct log level.

But also one can argue that the behavior is expected - you configured system cron but silently allow arbitrary webcron access?

Comment (joshtrichards) [reply core/Service/CronService.php:229]: The invalid access isn't an actual service problem. At best it may indicate a forgotten prior external cron setup (that isn't accomplishing anything); at worst it's noise from bots probing. I'd rather have the endpoint "disappear" (in a default situation) if webcron isn't in use. This is basically just an info or debug thing IMO. Particularly since the admin can't do anything about the second scenario.

**Review by susnux — APPROVED** [review]

**Review by Altahrim — APPROVED** [review]
