### PR TITLE
fix: improve checks for moving shares/storages into other mounts

### LINKED ISSUE #44249: [Bug]: Cannot move shared folders to external storages without parent folder
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I try to move a directly shared directory (someone shared it with me) to an external storage, the web interface says that it is not possible to move the item. However, if I move the shared directory to a random folder outside the external storage, I can move the random folder to the external storage.

### Steps to reproduce

1. Configure external Storage as user A
2. Generate as user A a direct share with user B
3.1 Login as user B and try to move the folder to external storage (result of MOVE: error 403) -> error
3.2 Login as user B, create a random directory and move the random folder to exterrnal storage -> success

### Expected behavior

The folder should be moved without random folder, not via step 3.2 (by Steps to reproduce).
Otherwise the shared folder should not be moved to external storage.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - bookmarks: 13.1.3
  - bruteforcesettings: 2.7.0
  - calendar: 4.6.5
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.5.2
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - deck: 1.11.4
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_external: 1.19.0
  - files_mindmap: 0.0.30
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - forms: 3.4.6
  - integration_ews: 1.0.37
  - integration_openproject: 2.6.1
  - keeweb: 0.6.13
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - nextcloud_announcements: 1.16.0
  - notifications: 2.15.0
  - notify_push: 0.6.9
  - oauth2: 1.15.2
  - onlyoffice: 8.2.4
  - password_policy: 1.17.0
  - photos: 2.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - spreed: 17.1.6
  - support: 1.10.0
  - survey_client: 1.15.0
  - systemtags: 1.17.0
  - text: 3.8.0
  - theming: 2.2.0
  - theming_customcss: 1.15.0
  - twofactor_backupcodes: 1.16.0
  - updatenotification: 1.17.0
  - user_ldap: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflow_script: 1.12.1
  - workflowengine: 2.9.0
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

```shell
... [16/Mar/2024:15:17:25 +0100] "MOVE /remote.php/dirToUser/testshare HTTP/2.0" 403 158 "-" ...
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by icewind1991**
- Also check for any mounts inside moved folders
- Throw an exception with a meaningful message instead of returning `false`
- [x] have the webui show the message instead of a generic error

Fixes #44249

### CODE REVIEW

File: lib/private/Files/View.php [hunk 1]
```diff
@@ -832,6 +840,34 @@ public function rename($source, $target) {
...
+			if (!$mount instanceof MoveableMount) {
+				throw new ForbiddenException("Storage {$sourcePath} cannot be moved", false);
+			}
+
+			if ($targetIsShared) {
+				throw new ForbiddenException("Moving a $sourceType ($sourcePath) into shared folder is not allowed", false);
+			}
+
+			if ($sourceMount !== $targetMount) {
+				throw new ForbiddenException("Moving a $sourceType ($sourcePath) into another $targetType ($targetPath) is not allowed", false);
```
Comment (Pytal) [inline lib/private/Files/View.php:866]: These messages should be translated for the web UI

Comment (icewind1991) [reply lib/private/Files/View.php]: Done

**Review by skjnldsv — APPROVED** [review]

**Review by sorbaugh — APPROVED** [review]

**Comment by icewind1991** [comment]
Annoyingly transfer ownership relies on the broken behavior of silently not moving mounts inside folders.

Added an option to ignore nested mounts when renaming folders. I hate it but doing it "properly" would be a pain.
