### PR TITLE
Fix integer overflow in ChunkingPlugin

### LINKED ISSUE #7948: Chunks on server do not sum up to X but to X (same number)
Sorry if I made mistakes in the new issue form. I had some trouble figuring out how to properly format the form. Hopefully it's not too bad.

Not sure if relevant. I updated to PHP 7.2.0 and afterwards noticed that Nextcloud didn't support it. After that, I've updated to Nextcloud 13 beta 2. During this period, unbeknownst to me, PHP started using a LOT of memory and basically thrashing the system. In subsequent updates (to later betas of Nextcloud and PHP 7.2.1), things got better, but some files now refuse to upload correctly.

### Steps to reproduce
1. Try to sync large-ish (>2GiB) files from Linux Client
2. Client Sync quietly fails

### Expected behaviour
If chunks don't sum up, retry upload. If they do, successfully combine chunks to file in server.

### Actual behaviour
Server claims chunks don't sum up, but they do (apparently)

### Server configuration
**Operating system**: Archlinux ARM (on an Odroid U2) - kernel 4.14.13
**Web server:** nginx 1.13.7
**Database:** mariab 10.1.30
**PHP version:** 7.2.1
**Nextcloud version:** 13.0.0.10

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from previous version (I think all the way to from owncloud 9)

**Where did you install Nextcloud from:** Downloaded from nextcloud and manually installed.

**Signing status:**No errors have been found.
**List of activated apps:**
<details>
<summary>App list</summary>
```
  - admin_audit: 1.3.0
  - bookmarks: 0.10.1
  - bruteforcesettings: 1.0.3
  - comments: 1.3.0
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - music: 0.5.5
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - previewgenerator: 1.0.9
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.0.1
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - unsplash: 1.0.5
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "mycloud.undo.it"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "version": "13.0.0.10",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "forcessl": true,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "asset-pipeline.enabled": true,
        "assetdirectory": "\/srv\/http\/nextcloud",
        "trashbin_retention_obligation": "auto",
        "appstoreenabled": true,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "filesystem_check_changes": 0,
        "overwrite.cli.url": "https:\/\/mycloud.undo.it",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "mysql.utf8mb4": true
    },
    "apps": {
        "activity": {
            "enabled": "no",
            "installed_version": "2.6.1",
            "types": "filesystem"
        },
        "admin_audit": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "logging"
        },
        "backgroundjob": {
            "lastjob": "236"
        },
        "bookmarks": {
            "enabled": "yes",
            "installed_version": "0.10.1",
            "types": ""
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "1.0.3",
            "types": ""
        },
        "calendar": {
            "enabled": "no",
            "installed_version": "1.5.5",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "no",
            "installed_version": "1.5.3",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1502745826.9598",
            "lastcron": "1516299390",
            "lastupdateResult": "[]",
            "lastupdatedat": "1516239083",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "scss.variables": "def3a709788cb02d255e48c549204afa",
            "updater.secret.created": "1516048791",
            "vendor": "nextcloud"
        },
        "dav": {
            "buildCalendarSearchIndex": "yes",
            "enabled": "yes",
            "installed_version": "1.4.6",
            "types": "filesystem"
        },
        "deck": {
            "enabled": "no",
            "installed_version": "0.2.3",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.3.1",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.5.1",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.2.1",
            "types": "logging"
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "18.0.0",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "ocsid": "170871",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "authentication"
        },
        "mail": {
            "enabled": "no",
            "installed_version": "0.7.3",
            "types": ""
        },
        "music": {
            "enabled": "yes",
            "installed_version": "0.5.5",
            "ocsid": "164319",
            "types": "filesystem"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100",
            "types": "logging"
        },
        "notes": {
            "enabled": "no",
            "installed_version": "2.3.1",
            "ocsid": "174554",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.1.2",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": ""
        },
        "previewgenerator": {
            "enabled": "yes",
            "installed_version": "1.0.9",
            "types": "filesystem"
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "prevent_group_restriction"
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "spreed": {
            "enabled": "yes",
            "installed_version": "3.0.1",
            "stun_servers": "[\"stun.nextcloud.com:443\"]",
            "types": "prevent_group_restriction"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "last_report": "{\"id\":\"oc77c6b5d905\",\"items\":[[\"server\",\"version\",\"12.0.3.3\"],[\"server\",\"code\",\"other\"],[\"server\",\"enable_avatars\",\"yes\"],[\"server\",\"enable_previews\",\"yes\"],[\"server\",\"memcache.local\",\"\\\\OC\\\\Memcache\\\\APCu\"],[\"server\",\"memcache.distributed\",\"none\"],[\"server\",\"asset-pipeline.enabled\",\"yes\"],[\"server\",\"filelocking.enabled\",\"yes\"],[\"server\",\"memcache.locking\",\"\\\\OC\\\\Memcache\\\\Redis\"],[\"server\",\"debug\",\"no\"],[\"server\",\"cron\",\"cron\"],[\"php\",\"version\",\"7.1.11\"],[\"php\",\"memory_limit\",134217728],[\"php\",\"max_execution_time\",0],[\"php\",\"upload_max_filesize\",1073741824],[\"database\",\"type\",\"mysql\"],[\"database\",\"version\",\"10.1.28\"],[\"database\",\"size\",286343168],[\"apps\",\"activity\",\"2.5.2\"],[\"apps\",\"bookmarks\",\"0.10.1\"],[\"apps\",\"bruteforcesettings\",\"1.0.2\"],[\"apps\",\"calendar\",\"disabled\"],[\"apps\",\"comments\",\"1.2.0\"],[\"apps\",\"contacts\",\"disabled\"],[\"apps\",\"dav\",\"1.3.0\"],[\"apps\",\"deck\",\"disabled\"],[\"apps\",\"federatedfilesharing\",\"1.2.0\"],[\"apps\",\"federation\",\"1.2.0\"],[\"apps\",\"files\",\"1.7.2\"],[\"apps\",\"files_pdfviewer\",\"1.1.1\"],[\"apps\",\"files_sharing\",\"1.4.0\"],[\"apps\",\"files_texteditor\",\"2.4.1\"],[\"apps\",\"files_trashbin\",\"1.2.0\"],[\"apps\",\"files_versions\",\"1.5.0\"],[\"apps\",\"files_videoplayer\",\"1.1.0\"],[\"apps\",\"firstrunwizard\",\"2.1\"],[\"apps\",\"gallery\",\"17.0.0\"],[\"apps\",\"logreader\",\"2.0.0\"],[\"apps\",\"lookup_server_connector\",\"1.0.0\"],[\"apps\",\"mail\",\"disabled\"],[\"apps\",\"music\",\"disabled\"],[\"apps\",\"nextcloud_announcements\",\"1.1\"],[\"apps\",\"notes\",\"disabled\"],[\"apps\",\"notifications\",\"2.0.0\"],[\"apps\",\"oauth2\",\"1.0.5\"],[\"apps\",\"password_policy\",\"1.2.2\"],[\"apps\",\"previewgenerator\",\"1.0.7\"],[\"apps\",\"provisioning_api\",\"1.2.0\"],[\"apps\",\"serverinfo\",\"1.2.0\"],[\"apps\",\"sharebymail\",\"1.2.0\"],[\"apps\",\"spreed\",\"disabled\"],[\"apps\",\"survey_client\",\"1.0.0\"],[\"apps\",\"systemtags\",\"1.2.0\"],[\"apps\",\"tasks\",\"disabled\"],[\"apps\",\"theming\",\"1.3.0\"],[\"apps\",\"twofactor_backupcodes\",\"1.1.1\"],[\"apps\",\"updatenotification\",\"1.2.0\"],[\"apps\",\"workflowengine\",\"1.2.0\"],[\"stats\",\"num_files\",535015],[\"stats\",\"num_users\",1],[\"stats\",\"num_storages\",3],[\"stats\",\"num_storages_local\",1],[\"stats\",\"num_storages_home\",2],[\"stats\",\"num_storages_other\",0],[\"stats\",\"num_comments\",0],[\"stats\",\"num_comment_markers\",0],[\"stats\",\"num_systemtags\",0],[\"stats\",\"num_systemtags_mappings\",0],[\"files_sharing\",\"num_shares\",0],[\"files_sharing\",\"num_shares_user\",0],[\"files_sharing\",\"num_shares_groups\",0],[\"files_sharing\",\"num_shares_link\",0],[\"files_sharing\",\"num_shares_link_no_password\",0],[\"files_sharing\",\"num_fed_shares_sent\",0],[\"files_sharing\",\"num_fed_shares_received\",0],[\"encryption\",\"enabled\",\"no\"],[\"encryption\",\"default_module\",\"no\"]]}",
            "last_sent": "1510057769",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "no",
            "installed_version": "0.9.5",
            "ocsid": "164356",
            "types": ""
        },
        "theming": {
            "cachebuster": "1",
            "enabled": "yes",
            "installed_version": "1.4.1",
            "name": "Nariyoshi MyCloud",
            "types": "logging"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.2.3",
            "types": ""
        },
        "unsplash": {
            "enabled": "yes",
            "installed_version": "1.0.5",
            "types": "authentication"
        },
        "updatenotification": {
            "bookmarks": "0.10.1",
            "bruteforcesettings": "1.0.3",
            "core": "12.0.4.3",
            "enabled": "yes",
            "installed_version": "1.3.0",
            "mail": "0.7.2",
            "previewgenerator": "1.0.9",
            "types": "",
            "update_check_errors": "0"
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        }
    }
}
```
</details>

**Are you using external storage, if yes which one:** NONE
**Are you using encryption:** NO
**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Not using browser, but client v2.3.3
**Operating system:** Archlinux

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Log was disabled at the time ):
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"fsaBIrXdcRbnJLyklSat","level":4,"time":"2018-01-17T17:06:35+00:00","remoteAddr":"35.9.132.227","user":"pnariyoshi","app":"webdav","method":"MOVE","url":"\/remote.php\/dav\/uploads\/pnariyoshi\/3633763883\/.file","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Message\":\"Chunks on server do not sum up to 2366986824 but to 2366986824 bytes\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Upload\\\/ChunkingPlugin.php(57): OCA\\\\DAV\\\\Upload\\\\ChunkingPlugin->verifySize()\\n#1 [internal function]: OCA\\\\DAV\\\\Upload\\\\ChunkingPlugin->beforeMove('uploads\\\/pnariyo...', 'files\\\/pnariyosh...')\\n#2 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(633): Sabre\\\\Event\\\\EventEmitter->emit('beforeMove', Array)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMove(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MOVE', Array)\\n#7 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(283): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(35): OCA\\\\DAV\\\\Server->exec()\\n#10 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/remote.php(164): require_once('\\\/usr\\\/share\\\/weba...')\\n#11 {main}\",\"File\":\"\\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Upload\\\/ChunkingPlugin.php\",\"Line\":103}","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.3.3 (Nextcloud)","version":"13.0.0.10"}
{"reqId":"k6kWzjwj0Ofn83CTIkN7","level":4,"time":"2018-01-17T20:15:45+00:00","remoteAddr":"35.9.132.227","user":"pnariyoshi","app":"webdav","method":"MOVE","url":"\/remote.php\/dav\/uploads\/pnariyoshi\/2097380633\/.file","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Message\":\"Chunks on server do not sum up to 2317707613 but to 2317707613 bytes\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Upload\\\/ChunkingPlugin.php(57): OCA\\\\DAV\\\\Upload\\\\ChunkingPlugin->verifySize()\\n#1 [internal function]: OCA\\\\DAV\\\\Upload\\\\ChunkingPlugin->beforeMove('uploads\\\/pnariyo...', 'files\\\/pnariyosh...')\\n#2 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(633): Sabre\\\\Event\\\\EventEmitter->emit('beforeMove', Array)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMove(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MOVE', Array)\\n#7 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(283): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(35): OCA\\\\DAV\\\\Server->exec()\\n#10 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/remote.php(164): require_once('\\\/usr\\\/share\\\/weba...')\\n#11 {main}\",\"File\":\"\\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Upload\\\/ChunkingPlugin.php\",\"Line\":103}","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.3.3 (Nextcloud)","version":"13.0.0.10"}
{"reqId":"Iu0RM6uT0ZfO9Fo8BXtt","level":4,"time":"2018-01-17T23:28:07+00:00","remoteAddr":"35.9.132.227","user":"pnariyoshi","app":"webdav","method":"MOVE","url":"\/remote.php\/dav\/uploads\/pnariyoshi\/920439079\/.file","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Message\":\"Chunks on server do not sum up to 2792926086 but to 2792926086 bytes\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Upload\\\/ChunkingPlugin.php(57): OCA\\\\DAV\\\\Upload\\\\ChunkingPlugin->verifySize()\\n#1 [internal function]: OCA\\\\DAV\\\\Upload\\\\ChunkingPlugin->beforeMove('uploads\\\/pnariyo...', 'files\\\/pnariyosh...')\\n#2 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(633): Sabre\\\\Event\\\\EventEmitter->emit('beforeMove', Array)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMove(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MOVE', Array)\\n#7 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(283): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(35): OCA\\\\DAV\\\\Server->exec()\\n#10 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/remote.php(164): require_once('\\\/usr\\\/share\\\/weba...')\\n#11 {main}\",\"File\":\"\\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Upload\\\/ChunkingPlugin.php\",\"Line\":103}","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.3.3 (Nextcloud)","version":"13.0.0.10"}
{"reqId":"6d7nBcSywBphyRnEiplm","level":4,"time":"2018-01-17T23:28:42+00:00","remoteAddr":"35.9.132.227","user":"pnariyoshi","app":"webdav","method":"MOVE","url":"\/remote.php\/dav\/uploads\/pnariyoshi\/3025104970\/.file","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Message\":\"Chunks on server do not sum up to 2305313811 but to 2305313811 bytes\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Upload\\\/ChunkingPlugin.php(57): OCA\\\\DAV\\\\Upload\\\\ChunkingPlugin->verifySize()\\n#1 [internal function]: OCA\\\\DAV\\\\Upload\\\\ChunkingPlugin->beforeMove('uploads\\\/pnariyo...', 'files\\\/pnariyosh...')\\n#2 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(633): Sabre\\\\Event\\\\EventEmitter->emit('beforeMove', Array)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMove(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MOVE', Array)\\n#7 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(283): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(35): OCA\\\\DAV\\\\Server->exec()\\n#10 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/remote.php(164): require_once('\\\/usr\\\/share\\\/weba...')\\n#11 {main}\",\"File\":\"\\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Upload\\\/ChunkingPlugin.php\",\"Line\":103}","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.3.3 (Nextcloud)","version":"13.0.0.10"}
{"reqId":"BpJF8VLEnNOJI2Ym6tDt","level":4,"time":"2018-01-18T07:55:31+00:00","remoteAddr":"35.9.132.227","user":"pnariyoshi","app":"webdav","method":"MOVE","url":"\/remote.php\/dav\/uploads\/pnariyoshi\/2055202812\/.file","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Message\":\"Chunks on server do not sum up to 2274697048 but to 2274697048 bytes\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Upload\\\/ChunkingPlugin.php(57): OCA\\\\DAV\\\\Upload\\\\ChunkingPlugin->verifySize()\\n#1 [internal function]: OCA\\\\DAV\\\\Upload\\\\ChunkingPlugin->beforeMove('uploads\\\/pnariyo...', 'files\\\/pnariyosh...')\\n#2 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(633): Sabre\\\\Event\\\\EventEmitter->emit('beforeMove', Array)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMove(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MOVE', Array)\\n#7 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(283): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(35): OCA\\\\DAV\\\\Server->exec()\\n#10 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/remote.php(164): require_once('\\\/usr\\\/share\\\/weba...')\\n#11 {main}\",\"File\":\"\\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Upload\\\/ChunkingPlugin.php\",\"Line\":103}","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.3.3 (Nextcloud)","version":"13.0.0.10"}
```
</details>

#### Client log
<details>
<summary>Client log</summary>

```
#=#=#=# Syncrun started 2018-01-18T11:59:08
#=#=#=#=# Propagation starts 2018-01-18T11:59:15 (last step: 6399 msec, total: 6399 msec)
||Research/CStability/NCs3.mat|INST_ERROR|Up|1514559300||2792926086||6|The item is not synced because of previous errors: Error transferring https://mycloud.undo.it/remote.php/dav/uploads/pnariyoshi/920439079/.file - server replied: Bad Request (Chunks on server do not sum up to 2792926086 but to 2792926086 bytes)|0|0|0|||INST_NONE|
||Research/CStability/NCs4.mat|INST_ERROR|Up|1514559367||2305313811||6|The item is not synced because of previous errors: Error transferring https://mycloud.undo.it/remote.php/dav/uploads/pnariyoshi/3025104970/.file - server replied: Bad Request (Chunks on server do not sum up to 2305313811 but to 2305313811 bytes)|0|0|0|||INST_NONE|
||Research/CStability/NCsaltQ12.mat|INST_ERROR|Up|1516170000||2366986824||6|The item is not synced because of previous errors: Error transferring https://mycloud.undo.it/remote.php/dav/uploads/pnariyoshi/3633763883/.file - server replied: Bad Request (Chunks on server do not sum up to 2366986824 but to 2366986824 bytes)|0|0|0|||INST_NONE|
||Research/CStability/NCsaltQ3.mat|INST_ERROR|Up|1516133215||2274697048||6|The item is not synced because of previous errors: Error transferring https://mycloud.undo.it/remote.php/dav/uploads/pnariyoshi/2055202812/.file - server replied: Bad Request (Chunks on server do not sum up to 2274697048 but to 2274697048 bytes)|0|0|0|||INST_NONE|
||Research/CStability/NCsaltQ6.mat|INST_ERROR|Up|1516113820||2317707613||6|The item is not synced because of previous errors: Error transferring https://mycloud.undo.it/remote.php/dav/uploads/pnariyoshi/2097380633/.file - server replied: Bad Request (Chunks on server do not sum up to 2317707613 but to 2317707613 bytes)|0|0|0|||INST_NONE|
#=#=#=# Syncrun finished 2018-01-18T11:59:15 (last step: 522 msec, total: 6921 msec)
```
</details>

### PR DESCRIPTION
**Pull request by MorrisJobke**
Avoids errors when the size exceeds MAX_INT because of the cast to int. Better cast it to float to avoid this.

Fix #7948 and https://github.com/nextcloud/server/pull/8109#issuecomment-361565581

@nariox @pasxalisk Could you check if this fixes the issue for you?

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
Ah 32bit systems?

**Comment by MorrisJobke** [comment]
> Ah 32bit systems?

Exactly - some raspberry Pis and stuff like that.

**Comment by pasxalisk** [comment]
@MorrisJobke For me it does fix it.
I managed to upload a single file 45gb on my RPi 3 running Nextcloud 13 RC3.

**Comment by pasxalisk** [comment]
@MorrisJobke 
EDIT: It did work with the solution i posted.
When i tried the above i saw a "Unkniwn CSync Error" on the windows client.

**Comment by pasxalisk** [comment]
@MorrisJobke 
EDIT2: I tried again on a clean install and it seems that the fix is working as expected.
I am sorry for any inconvinience.

**Comment by voxdemonix** [comment]
@pasxalisk Raspberry Pi 3 use a 64 bit ARM CPU ( https://en.wikipedia.org/wiki/ARM_Cortex-A53 ) can you check on another ARM CPU please?

**Comment by pasxalisk** [comment]
@voxdemonix true. It does use a x64 but the raspbian OS is 32bits. 
Unfortunatelly i don't own an ARM x64 OS device to test it.

File: apps/dav/lib/Upload/ChunkingPlugin.php [hunk 1]
```diff
@@ -99,7 +99,7 @@ private function verifySize() {
 			return;
 		}
 		$actualSize = $this->sourceNode->getSize();
-		if ((int)$expectedSize !== $actualSize) {
+		if ((float)$expectedSize !== (float)$actualSize) {
```
Comment (go2sh) [inline apps/dav/lib/Upload/ChunkingPlugin.php]: This actually might create some very very tricky corner cases, where two not equal numbers get casted to the fame float value, I think.

Comment (MorrisJobke) [reply apps/dav/lib/Upload/ChunkingPlugin.php]: Do you have an example? Currently this is exactly the case that one number is the float (because it can store higher numbers) and the other one is casted to integer and caused an overflow there and thus is not the same.

Comment (go2sh) [reply apps/dav/lib/Upload/ChunkingPlugin.php]: I created a small test program and with higher numbers there a ton of collisions. And it must be: Int has 31 bits for the actual number and a float only 23. See my other comment.

**Comment by go2sh** [comment]
Test program in c#:
```
namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
            int i = 0;
            for(i=0;i<= 2147483647;i++)
            {
                int j;
                float a = (float)i;
                for (j=i-128;j <= i+128;j++)
                {
                    float b = (float)j;
                    if (a == b && i != j)
                    {
                        System.Console.Out.WriteLine(String.Format("i: {0}, j: {1}, a: {2}, b: {3}", i,j,a,b));
                    }
                }
            }
        }
    }
}
```
Result:
```
...
i: 16782085, j: 16782084, a: 1,678208E+07, b: 1,678208E+07
i: 16782087, j: 16782088, a: 1,678209E+07, b: 1,678209E+07
i: 16782087, j: 16782089, a: 1,678209E+07, b: 1,678209E+07
i: 16782088, j: 16782087, a: 1,678209E+07, b: 1,678209E+07
i: 16782088, j: 16782089, a: 1,678209E+07, b: 1,678209E+07
i: 16782089, j: 16782087, a: 1,678209E+07, b: 1,678209E+07
i: 16782089, j: 16782088, a: 1,678209E+07, b: 1,678209E+07
i: 16782091, j: 16782092, a: 1,678209E+07, b: 1,678209E+07
i: 16782091, j: 16782093, a: 1,678209E+07, b: 1,678209E+07
i: 16782092, j: 16782091, a: 1,678209E+07, b: 1,678209E+07
i: 16782092, j: 16782093, a: 1,678209E+07, b: 1,678209E+07
i: 16782093, j: 16782091, a: 1,678209E+07, b: 1,678209E+07
i: 16782093, j: 16782092, a: 1,678209E+07, b: 1,678209E+07
i: 16782095, j: 16782096, a: 1,67821E+07, b: 1,67821E+07
i: 16782095, j: 16782097, a: 1,67821E+07, b: 1,67821E+07
i: 16782096, j: 16782095, a: 1,67821E+07, b: 1,67821E+07
i: 16782096, j: 16782097, a: 1,67821E+07, b: 1,67821E+07
i: 16782097, j: 16782095, a: 1,67821E+07, b: 1,67821E+07
i: 16782097, j: 16782096, a: 1,67821E+07, b: 1,67821E+07
i: 16782099, j: 16782100, a: 1,67821E+07, b: 1,67821E+07
...
```

**Comment by lnicola** [comment]
@go2sh I don't know what `float` and `int` usually are in PHP, but a C# `float` is 32-bit, the same as an `int`. So large `int`s will will map to the same `float`.

The PHP documentation seems to imply that `float` is usually `double`, which would work fine for this purpose, but it's probably not true on 32-bit ARM systems.

**Comment by lnicola** [comment]
On the other hand, this seems more like an extra safety check (a file size match won't actually guarantee that the data was received correctly. Worst case, an error won't be reported when it should, but this won't prevent uploads from succeeding.

**Comment by go2sh** [comment]
This very tricky... I have no proper solution.
@MorrisJobke You mean `getSize()` returns a float anyway, if its bigger than 2 GB on 32-bit systems?

File: apps/dav/lib/Upload/ChunkingPlugin.php (hunk 1 above)
Comment (jkroepke) [reply apps/dav/lib/Upload/ChunkingPlugin.php]: Why you have to cast the values? String comparison not good enough?

If not, maybe bcmath/gmp should be used on 32bit systems.

**Comment by nariox** [comment]
Thank you for the patch @MorrisJobke , it does "solve" my problem. 

For those interested, PHP only has INTs and FLOATs defined, but whether they are 32-bit or 64-bit depends on the platform. The default behavior in PHP is to (quietly) convert INTs to FLOATs if they exceed PHP_INT_MAX.

It seems like there is a proposal to introduce BIGINTs to PHP (https://wiki.php.net/rfc/bigint), but not implemented yet.

The main problem with both approaches (casting to floats or ints) is that we lose precision. Floats would miss "small" errors, where the chunk size difference is beyond the precision, while ints fail in 32-bit int implementations, which the overflow would allow "large" chunk size errors to pass. Maybe a better approach would be to compare both (and casting ints, so we are only comparing the LSBs)? (Or to convert both to string, although I don't know to prevent overflow errors from happening before that)

**Comment by nariox** [comment]
By the way, wouldn't it be better to checksum the files instead? This might require some changes in the client, but would give us a better check altogether than just chunk sizes and avoid the 32/64 bit debacle.

**Comment by lnicola** [comment]
This doesn't affect me, and I don't know the full context, but I'm thinking that:

- the check isn't that useful and if two different floats compare as equal it's just a false negative
- if the client is a browser, JavaScript has double precision support, so it can either compute the number of chunks, or send the size as a pair of integers (high and low part)
- if the client is PHP, though luck
- if the client is another application, this check might be annoying; one use case I have in mind is streaming a `tar` archive to the NextCloud server -- the client won't know the total size beforehand.

**Comment by davidpoza** [comment]
@pasxalisk 

> @MorrisJobke For me it does fix it.I managed to upload a single file 45gb on my RPi 3 running Nextcloud 13 RC3.

What OS are you running in the rpi3? I'm using hypriotOS (debian based) and cannot pass over 2GB. I've patched the code.

Thx

**Review by icewind1991 — APPROVED** [review]

File: apps/dav/lib/Upload/ChunkingPlugin.php (hunk 1 above)
Comment (MorrisJobke) [reply apps/dav/lib/Upload/ChunkingPlugin.php]: @icewind1991 @rullzer @nickvergessen What do you think about the cast to string? Is this the better approach?

**Comment by MorrisJobke** [comment]
I updated this to be a cast to string. @pasxalisk @davidpoza @nariox Could you try the new patch and check if this works properly for you?

**Comment by MorrisJobke** [comment]
@maanlooper and @danny3 reported that this already works in https://github.com/nextcloud/server/issues/7948#issuecomment-364606414

**Comment by nariox** [comment]
I'm now having a different issue, but not sure if it is part of this (seems to be).
My uploads fail with "Sabre\DAV\Exception: Error while copying file to target location (copied bytes: 2147483647, expected filesize: )"

2147483647 is 2³¹-1

The particular exception is being thrown by `/apps/dav/lib/Connector/Sabre/File.php ` at line 178:
`throw new BadRequest('expected filesize ' . $expected . ' got ' . $count);`
Commenting out this line leads to "successful" uploads, but files are cropped to 2GiB. My guess (as a non-PHP dev, is that casting the $expected to int causes it to be empt (maybe casting to strings might help?), but the copied bytes might need some work.

Since other people don't seem to having this problem, my guess is that I might want to file a new bug. But let me know what happens to you guys.

**Comment by MorrisJobke** [comment]
Let's get this in

**Comment by MorrisJobke** [comment]
backport to stable13 is in #8752
