### PR TITLE
Fix preview of theming

### LINKED ISSUE #5975: Preview of theming does not work anymore
* change a value in the theming app
* wait for it to be saved
* then the "Loading preview" will show up
* actual: it loads endlessly and if you look at the network it will show you a 404 on `css/core/server.css`
* expected: the server.css is properly loaded and the loading spinner goes away

Problem: The server.css is in my instance for example served under `css/core/72408cbdff8901cd16b886aeabcc367c-server.css` - I guess the `reloadStylesheets()` method needs an adjustment to fetch the current name of this an reload that css.

https://github.com/nextcloud/server/blob/3470d0a44ea2b7a477af407b3d9abee81de071e3/apps/theming/js/settings-admin.js#L44-L65

cc @danxuliu @juliushaertl @nextcloud/theming 

Valid for at least master.

### PR DESCRIPTION
**Pull request by danxuliu**
Pull request #5429 made cached SCSS files depend on a hash of the base URL, so the _/css/core/server.css_ file does no longer exist; as the file can not be loaded the _"Loading preview"_ message is never removed and the _"Saved"_ message is never shown.

As it now depends on the hash of the base URL the file to be reloaded can no longer be hardcoded, so the DataResponse from the controller now provides the full URL to the _server.css_ file that has to be reloaded (if any).

Fixes #5975

Acceptance tests for the preview after setting and resetting the color in the Theming app are also included in this pull request.

### CODE REVIEW

**Comment by danxuliu** [comment]
Oops, I had forgotten to add the acceptance tests for the Theming app to Drone; it is fixed now.

**Comment by MorrisJobke** [comment]
You are awesome!!!! 🚀 😍

Thanks again for helping that much 👍

File: apps/theming/js/settings-admin.js [hunk 1]
```diff
@@ -62,8 +62,18 @@ function preview(setting, value) {
...
 
-	reloadStylesheets('/css/core/server.css');
-	reloadStylesheets('/apps/theming/styles');
+	if (serverCssUrl !== undefined) {
+		stylesheetsLoaded++;
+
+		// Ensure that the URL starts by '/' to prevent "stylesheet.load" from
+		// prepending the URL of the current page.
+		if (serverCssUrl[0] !== '/') {
+			serverCssUrl = '/' + serverCssUrl;
```
Comment (MorrisJobke) [inline apps/theming/js/settings-admin.js]: This doesn't work for instances that are in a subfolder. It needs to be the full URL. linkToAbsolute or something like that should exist, which prepends you the webroot.

**Review by MorrisJobke — CHANGES_REQUESTED** [review]

File: apps/theming/js/settings-admin.js (hunk 1 above)
Comment (danxuliu) [inline apps/theming/js/settings-admin.js]: > This doesn't work for instances that are in a subfolder. It needs to be the full URL.

Totally right; [getCachedSCSS removes the webroot](https://github.com/nextcloud/server/blob/517dfdda0dfe928836e32db2dfffe04545abfe8e/lib/private/Template/SCSSCacher.php#L297).

> linkToAbsolute or something like that should exist, which prepends you the webroot.

I have used `Util::linkTo` instead, as `Util::linkToAbsolute` adds the webroot, but also the protocol and server host.

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
Tests fail:
```
There were 8 failures:

1) OCA\Theming\Tests\Controller\ThemingControllerTest::testUpdateStylesheet
```

**Review by nickvergessen — DISMISSED** [review]
Tests

**Comment by MorrisJobke** [comment]
And please rebase on master - we updated the drone config 🙈

**Comment by danxuliu** [comment]
@nickvergessen 
> Tests fail

:facepalm: Yes, I forgot to check the tests. And not only that, I also used a deprecated method (`OC\Util::linkTo`). Both are fixed now.

@MorrisJobke 
> And please rebase on master - we updated the drone config 🙈

Done.

**Comment by MorrisJobke** [comment]
> Edit: By the way, I have noticed that the commit order in the GitHub interface is messed up (as it is ordered chronologically instead of parent->child); I can change their timestamp and push again so they are showed in the right order for easier review if you want.

No - just leave it as it is :) That's fine :)

**Review by MorrisJobke — APPROVED** [review]
Tested again and works 👍 Code looks good

**Review by rullzer — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Huge thanks again @danxuliu for this awesome help here 👍 

Could I ask you to open  the backport to stable12? That would be nice :)

**Comment by danxuliu** [comment]
> Huge thanks again @danxuliu for this awesome help here 👍

My pleasure :-)

> Could I ask you to open the backport to stable12? That would be nice :)

Here you have (yes, I had it prepared already :-P ): #6067
