### PR TITLE
Do not log passwords in debug mode

### LINKED ISSUE #38461: [Bug]: user_ldap logs user passwords in plain text
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The user_ldap app seems to log all LDAP operations, including parameters, in plain text.

https://github.com/nextcloud/server/blob/b6d734375478c791a146e2ec5ad61ac1a699e436/apps/user_ldap/lib/LDAP.php#L320-L324

For the `ldap_bind` command this looks like

```
Calling LDAP function ldap_bind with parameters [{},"<full user DN>", "<plain text password"]
```

### Steps to reproduce

1. configure Nextcloud for LDAP user backend
2. connect external client (in my case Gnome online account)
3. trigger ldap_bind (e.g. by syncing the calendar in the client)
4. follow the `DEBUG` log

### Expected behavior

If logged, I would expect the line to not display the password, or to omit parameters completely:

```
Calling LDAP function ldap_bind with parameters [{},"<full user DN>", "********"]
```
or
```
Calling LDAP function ldap_bind
```

### Installation method

None

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
Enabled:
  - activity: 2.18.0
  - bruteforcesettings: 2.6.0                                                                                                                                   
  - calendar: 4.3.4                                                                                                                                             
  - circles: 26.0.0                                                                                                                                             
  - cloud_federation_api: 1.9.0                                                                                                                                 
  - comments: 1.16.0                                                                                                                                            
  - contacts: 5.2.0                                                                                                                                             
  - contactsinteraction: 1.7.0                                                                                                                                  
  - dashboard: 7.6.0                                                                                                                                            
  - dav: 1.25.0                                                                                                                                                 
  - federatedfilesharing: 1.16.0                                                                                                                                
  - federation: 1.16.0                                                                                                                                          
  - files: 1.21.1                                                                                                                                               
  - files_markdown: 2.4.0                                                                                                                                       
  - files_pdfviewer: 2.7.0                                                                                                                                      
  - files_rightclick: 1.5.0                                                                                                                                     
  - files_sharing: 1.18.0                                                                                                                                       
  - files_trashbin: 1.16.0                                                                                                                                      
  - files_versions: 1.19.1                                                                                                                                      
  - firstrunwizard: 2.15.0                                                                                                                                      
  - jitsi: 0.17.0                                                                                                                                               
  - logreader: 2.11.0       
  - lookup_server_connector: 1.14.0
  - nextcloud_announcements: 1.15.0
  - notes: 4.7.2
  - notifications: 2.14.0
  - oauth2: 1.14.0
  - onlyoffice: 7.8.0
  - password_policy: 1.16.0
  - photos: 2.2.0
  - privacy: 1.10.0
  - provisioning_api: 1.16.0
  - recommendations: 1.5.0
  - related_resources: 1.1.0-alpha1
  - serverinfo: 1.16.0
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - support: 1.9.0
  - systemtags: 1.16.0
  - tasks: 0.15.0
  - text: 3.7.2
  - theming: 2.1.1
  - twofactor_backupcodes: 1.15.0
  - updatenotification: 1.16.0
  - user_ldap: 1.16.0
  - user_status: 1.6.0
  - viewer: 1.10.0
  - weather_status: 1.6.0
  - workflowengine: 2.8.0
Disabled:
  - admin_audit: 1.16.0
  - deck: 1.8.3 (installed 1.8.3)
  - documentserver_community: 0.1.13 (installed 0.1.13)
  - encryption: 2.14.0
  - files_external: 1.18.0 (installed 1.7.0)
  - survey_client: 1.14.0 (installed 1.4.0)
  - suspicious_login: 4.4.0
  - twofactor_totp: 8.0.0-alpha.0
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by miaulalala**
* Resolves: https://github.com/nextcloud/server/issues/38461

## Summary

In debug mode, the passwords were logged.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/user_ldap/lib/LDAP.php [hunk 1]
```diff
@@ -317,6 +317,14 @@ protected function invokeLDAPMethod(string $func, ...$arguments) {
 
 	private function preFunctionCall(string $functionName, array $args): void {
 		$this->curArgs = $args;
+		if(strcasecmp($functionName, 'ldap_bind') === 0) {
+			// The arguments are not key value pairs
+			// \OCA\User_LDAP\LDAP::bind passes 3 arguments, the 3rd being the pw
+			// Remove it via direct array access for now, although a better solution could be found mebbe?
+			// @link https://github.com/nextcloud/server/issues/38461
+			unset($args[2]);
```
Comment (Altahrim) [inline apps/user_ldap/lib/LDAP.php:325]: Maybe only mask it like in reports?
```suggestion
			$args[2] = '***REMOVED SENSITIVE VALUE***';
```

Comment (miaulalala) [reply apps/user_ldap/lib/LDAP.php:325]: SMORT!

File: apps/user_ldap/lib/LDAP.php [hunk 2]
```diff
@@ -317,6 +317,14 @@ protected function invokeLDAPMethod(string $func, ...$arguments) {
 
 	private function preFunctionCall(string $functionName, array $args): void {
 		$this->curArgs = $args;
+		if(strcasecmp($functionName, 'ldap_bind') === 0) {
+			// The arguments are not key value pairs
+			// \OCA\User_LDAP\LDAP::bind passes 3 arguments, the 3rd being the pw
+			// Remove it via direct array access for now, although a better solution could be found mebbe?
+			// @link https://github.com/nextcloud/server/issues/38461
+			$args[2] = '***REMOVED SENSITIVE VALUE***';;
```
Comment (Altahrim) [inline apps/user_ldap/lib/LDAP.php:325]:
```suggestion
			$args[2] = '***REMOVED SENSITIVE VALUE***';
```
One should be enough :)

Comment (miaulalala) [reply apps/user_ldap/lib/LDAP.php:325]: god damnit :laughing:

**Review by Altahrim — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

File: apps/user_ldap/lib/LDAP.php [hunk 3]
```diff
@@ -317,6 +317,14 @@ protected function invokeLDAPMethod(string $func, ...$arguments) {
 
 	private function preFunctionCall(string $functionName, array $args): void {
 		$this->curArgs = $args;
+		if(strcasecmp($functionName, 'ldap_bind') === 0) {
+			// The arguments are not key value pairs
+			// \OCA\User_LDAP\LDAP::bind passes 3 arguments, the 3rd being the pw
+			// Remove it via direct array access for now, although a better solution could be found mebbe?
+			// @link https://github.com/nextcloud/server/issues/38461
+			$args[2] = '***REMOVED SENSITIVE VALUE***';
```
Comment (kesselb) [inline apps/user_ldap/lib/LDAP.php:325]:
```suggestion
			$args[2] = \OCP\IConfig::SENSITIVE_VALUE;
```

nit ;)
