### PR TITLE
fix(external_storage): hide local storage as an option for users

### LINKED ISSUE #57917: files_external: UI issues around Local storage backend and personal external storages
Please see the screen recording, but it an nutshell:

1. Go to admin settings → external storages
2. Allow some external storage types to be allowed, including *Local*
3. Switch to personal settings
4. Add an external storage and select a Local one, add the details
5. Confirm the password dialog
6. See it failing

Things to solve:

=> Local storages are not allowed for users for a good reason, it should not be offered in the first place
=> A user should only see external storage classes that are allowed to be added
=> Password confirmation should not repeat every time, when there was a recent run?
=> When it fails, it appears the password is wrong, but not the actual issue
=> All settings are lost when giving up and you'd have to start from scratch, e.g. when there was just a typo in the settings
=> To touble check: I am not convinced adding a storage is allowed at all. Quick tests for me always ended with a 403 response.

https://github.com/user-attachments/assets/b259445b-1e86-4313-9207-fb27d592de2c

### PR DESCRIPTION
**Pull request by leftybournes**
* Resolves: #57917 

## Summary

Admins can currently allow 'Local' storage backend as an option for people to mount. Non-admins aren't allowed to mount it so remove it from the options.

### Before
external_storages_with_local

### After
external_storages_without_local

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [X] Screenshots before/after for front-end changes
- [X] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)
- [X] [Labels added](https://github.com/nextcloud/server/labels) where applicable (ex: bug/enhancement, `3. to review`, feature component)
- [ ] [Milestone added](https://github.com/nextcloud/server/milestones) for target branch/version (ex: 32.x for `stable32`)

### CODE REVIEW

File: apps/files_external/lib/Controller/UserStoragesController.php [hunk 1]
```diff
@@ -98,8 +98,7 @@ public function create(
 		array $backendOptions,
 		?array $mountOptions,
 	): DataResponse {
-		$canCreateNewLocalStorage = $this->config->getSystemValue('files_external_allow_create_new_local', true);
```
Comment (szaimen) [inline apps/files_external/lib/Controller/UserStoragesController.php:101]: This setting is for the admin option

Comment (leftybournes) [reply apps/files_external/lib/Controller/UserStoragesController.php:101]: Ah I got it mixed up. I'll revert it. Thanks for catching that.

**Review by szaimen — APPROVED** [review]
Tested and seems to fix the reported problem :)

**Review by provokateurin — APPROVED** [review]
