### PR TITLE
Fix occ files:scan elapsed time

### LINKED ISSUE #13911: occ files:scan elapsed time not good after 1 day
NOT urgent

### Steps to reproduce
1. Scan a lots of files during more than 24H with 
occ files:scan --all

### Expected behaviour
+---------+--------+--------------+
| Folders | Files  | Elapsed time |
+---------+--------+--------------+
| 41936   | 454712 | 24:58:34     |
+---------+--------+--------------+

### Actual behaviour
It tells me it took only 58 minutes. But it tooks more than one day. I suspect it ran 24:58:34

+---------+--------+--------------+
| Folders | Files  | Elapsed time |
+---------+--------+--------------+
| 41936   | 454712 | 00:58:34     |
+---------+--------+--------------+

### Server configuration

**Operating system**:
Centos 7

**Web server:**
Apache 2.4.6

**Database:**
MariaDB 10.0.37

**PHP version:**
PHP 7.2.14

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 15.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
Nextcloud.com

### PR DESCRIPTION
**Pull request by joelselvaraj**
Fix #13911 `occ files:scan` command's elapsed time not displaying correctly when ran for more than 24hrs by formatting the elapsed seconds correctly.
Signed-off-by: Joel S <joel.devbox@protonmail.com>

### CODE REVIEW

**Comment by joelselvaraj** [comment]
Kindly review and let me know if any changes are required.

**Comment by kesselb** [comment]
image

image

File: apps/files/lib/Command/Scan.php [hunk 1]
```diff
@@ -289,10 +289,9 @@ protected function showSummary($headers, $rows, OutputInterface $output) {
 	 * @return string
 	 */
 	protected function formatExecTime() {
-		list($secs, ) = explode('.', sprintf("%.1f", $this->execTime));
-
-		# if you want to have microseconds add this:   . '.' . $tens;
-		return date('H:i:s', $secs);
+		$secs = round($this->execTime);
+		# convert seconds into HH:MM:SS form
+		return sprintf('%02d:%02d:%02d', ($secs/3600),($secs/60%60), $secs%60);
```
Comment (kesselb) [inline apps/files/lib/Command/Scan.php]:
```suggestion
		return sprintf('%02d:%02d:%02d', ($secs/3600), ($secs/60%60), $secs%60);
```

There is one space missing :laughing:

**Review by kesselb — APPROVED** [review]
Looks good to me. There is a similar logic in: https://github.com/nextcloud/server/blob/1ad42e8f81dd6f94c205af9cd3b5cb347f803dd4/apps/files/lib/Command/ScanAppData.php#L219 Would be nice to have them in sync.

File: apps/files/lib/Command/Scan.php (hunk 1 above)
Comment (joelselvaraj) [reply apps/files/lib/Command/Scan.php]: > Looks good to me. There is a similar logic in:
> 
> [server/apps/files/lib/Command/ScanAppData.php](https://github.com/nextcloud/server/blob/1ad42e8f81dd6f94c205af9cd3b5cb347f803dd4/apps/files/lib/Command/ScanAppData.php#L219)
> 
> Line 219 in [1ad42e8](/nextcloud/server/commit/1ad42e8f81dd6f94c205af9cd3b5cb347f803dd4)
>  		list($secs, ) = explode('.', sprintf("%.1f", $this->execTime)); 
> Would be nice to have them in sync.

Ok :+1: Let me change it too!

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍
