### PR TITLE
Avoid calling image* methods on boolean

### LINKED ISSUE #29990: imagedestroy(): Argument #1 ($image) must be of type GdImage, bool given
NC 22.2.3 with PHP 8.0.13
Cc @come-nc as you've worked on it at https://github.com/nextcloud/server/pull/29479

```
{
  "reqId": "m4ntpS1uGWE18wMmZMZa",
  "level": 4,
  "time": "2021-11-30T10:59:20+00:00",
  "app": "webdav",
  "method": "GET",
  "url": "/remote.php/dav/addressbooks/system/system/system/user_saml:pas.dof@ha.pl.vcf?photo&size=128",
  "message": "imagedestroy(): Argument #1 ($image) must be of type GdImage, bool given",
  "userAgent": "Mozilla/5.0 (iPhone; CPU iPhone OS 15_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/96.0.4664.53 Mobile/15E148 Safari/604.1",
  "version": "22.2.3.0",
  "exception": {
    "Exception": "TypeError",
    "Message": "imagedestroy(): Argument #1 ($image) must be of type GdImage, bool given",
    "Code": 0,
    "Trace": [
      {
        "file": "/lib/private/legacy/OC_Image.php",
        "line": 879,
        "function": "imagedestroy",
        "args": [
          false
        ]
      },
      {
        "file": "/apps/dav/lib/CardDAV/PhotoCache.php",
        "line": 163,
        "function": "resize",
        "class": "OC_Image",
        "type": "->",
        "args": [
          128
        ]
      },
      {
        "file": "/apps/dav/lib/CardDAV/PhotoCache.php",
        "line": 95,
        "function": "getFile",
        "class": "OCA\\DAV\\CardDAV\\PhotoCache",
        "type": "->",
        "args": [
          {
            "__class__": "OC\\Files\\SimpleFS\\SimpleFolder"
          },
          128
        ]
      },
      {
        "file": "/apps/dav/lib/CardDAV/ImageExportPlugin.php",
        "line": 104,
        "function": "get",
        "class": "OCA\\DAV\\CardDAV\\PhotoCache",
        "type": "->",
        "args": [
          "2",
          "user_saml:pal.doft@ha.fr.vcf",
          128,
          {
            "__class__": "Sabre\\CardDAV\\Card"
          }
        ]
      },
      {
        "file": "/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "httpGet",
        "class": "OCA\\DAV\\CardDAV\\ImageExportPlugin",
        "type": "->",
        "args": [
          {
            "__class__": "Sabre\\HTTP\\Request"
          },
          {
            "__class__": "Sabre\\HTTP\\Response"
          }
        ]
      },
      {
        "file": "/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 472,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "method:GET",
          [
            {
              "__class__": "Sabre\\HTTP\\Request"
            },
            {
              "__class__": "Sabre\\HTTP\\Response"
            }
          ]
        ]
      },
      {
        "file": "/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 253,
        "function": "invokeMethod",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          {
            "__class__": "Sabre\\HTTP\\Request"
          },
          {
            "__class__": "Sabre\\HTTP\\Response"
          }
        ]
      },
      {
        "file": "/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 321,
        "function": "start",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/apps/dav/lib/Server.php",
        "line": 333,
        "function": "exec",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/apps/dav/appinfo/v2/remote.php",
        "line": 35,
        "function": "exec",
        "class": "OCA\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/remote.php",
        "line": 166,
        "args": [
          "/apps/dav/appinfo/v2/remote.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/lib/private/legacy/OC_Image.php",
    "Line": 879,
    "CustomMessage": "--"
  },
  "id": "61a658026d4c5"
}
```

### PR DESCRIPTION
**Pull request by come-nc**
This avoids fatal errors on PHP>=8, and warnings on older versions.
Log should also be clearer.

Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

Fixes https://github.com/nextcloud/server/issues/29990

### CODE REVIEW

File: lib/private/legacy/OC_Image.php [hunk 1]
```diff
@@ -123,7 +124,11 @@ public function mimeType() {
 	 * @return int
 	 */
 	public function width() {
-		return $this->valid() ? imagesx($this->resource) : -1;
+		if ($this->valid() && (($width = imagesx($this->resource)) !== false)) {
```
Comment (nickvergessen) [inline lib/private/legacy/OC_Image.php:127]: I think we have a "no assignment in ifs" rule. so maybe you can put it in a second check?

Comment (come-nc) [reply lib/private/legacy/OC_Image.php:127]: Sure, incoming.
As it was a oneliner originally I tried to keep it short.

**Review by nickvergessen — APPROVED** [review]

**Review by solracsf — APPROVED** [review]
No more errors on my side. 👍
