### PR TITLE
fix(provisioning_api): Translate exceptions shown in the frontend

### LINKED ISSUE #13820: OCSExption "Cannot remove yourself from the admin group" is not translatable
Reported at forums.

See https://help.nextcloud.com/t/die-deutsche-ubersetzung-von-nextcloud-hier-diskutieren-und-fehler-melden/32139/120

Source line:

https://github.com/nextcloud/server/blob/b8b650aee697e4ab52f1f28e7e2287ac9a27456c/apps/provisioning_api/lib/Controller/UsersController.php#L751

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: https://github.com/nextcloud/server/issues/13820

## Summary
This exception messages are used by the front end to be displayed to the user, using hint exceptions would be quite breaking as hint exceptions are handled as HTTP error 500 for OCS controllers.
But I think it should be ok to simply translate the messages as for programmatically usage you should not use the message but the status code.

Also fixed some minor deprecation issue.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by rakekniven — DISMISSED** [review]

File: apps/provisioning_api/lib/Controller/UsersController.php [hunk 1]
```diff
@@ -1432,7 +1412,7 @@ public function removeFromGroup(string $userId, string $groupid): DataResponse {
 
 			if (count($userSubAdminGroups) <= 1) {
 				// Subadmin must not be able to remove a user from all their subadmin groups.
-				throw new OCSException('Not viable to remove user from the last group you are SubAdmin of', 105);
+				throw new OCSException($this->l10n->t('Not viable to remove user from the last group you are SubAdmin of'), 105);
```
[the remark this answers is not in the document]
Comment (susnux) [reply apps/provisioning_api/lib/Controller/UsersController.php]: > Here you use "SubAdmin" or "subadmin". Please align all occurences. My vote goes to "sub-admin"

Done :white_check_mark:

[the remark this answers is not in the document]
Comment (susnux) [reply apps/provisioning_api/lib/Controller/UsersController.php]: >  btw. I do not get the meaning of this sentence

If I understand this correctly a sub-admin is not allowed to remove a user from all groups that user is sub-admin of, meaning the user must stay sub-admin of at least one groupe (maybe @nickvergessen, as the author, can help)?

[the remark this answers is not in the document]
Comment (nickvergessen) [reply apps/provisioning_api/lib/Controller/UsersController.php]: yeah I think so, to avoid users that are managed by no one

File: apps/provisioning_api/lib/Controller/UsersController.php [hunk 2]
```diff
@@ -545,7 +525,7 @@ public function addUser(
 
 			// Send new user mail only if a mail is set
 			if ($email !== '') {
-				$newUser->setEMailAddress($email);
+				$newUser->setSystemEMailAddress($email);
```
Comment (nickvergessen) [inline apps/provisioning_api/lib/Controller/UsersController.php:528]: Please don't make functional changes in a PR named "Translate…" Also those are not the same and infact it might be impossible to manage the system email address. So this should stay as `setEMailAddress`

File: apps/provisioning_api/lib/Controller/UsersController.php [hunk 3]
```diff
@@ -1058,7 +1038,7 @@ public function editUser(string $userId, string $key, string $value): DataRespon
 				break;
 			case IAccountManager::PROPERTY_EMAIL:
 				if (filter_var($value, FILTER_VALIDATE_EMAIL) || $value === '') {
-					$targetUser->setEMailAddress($value);
+					$targetUser->setSystemEMailAddress($value);
```
Comment (nickvergessen) [inline apps/provisioning_api/lib/Controller/UsersController.php:1041]:
```suggestion
					$targetUser->setEMailAddress($value);
```

**Review by nickvergessen — DISMISSED** [review]

File: apps/provisioning_api/lib/Controller/UsersController.php (hunk 2 above)
Comment (susnux) [reply apps/provisioning_api/lib/Controller/UsersController.php:528]: Well just wanted to get rid of the deprecation warning and the docs say it is just an alias so one would expect both to be equal:

```php
	/**
	 * set the email address of the user
	 *
	 * It is an alias to setSystemEMailAddress()
	 *
	 * @param string|null $mailAddress
	 * @return void
	 * @since 9.0.0
	 * @deprecated 23.0.0 use setSystemEMailAddress() or setPrimaryEMailAddress()
	 */
	public function setEMailAddress($mailAddress);
```

But I understand this is not the scope of this PR.

Comment (susnux) [reply apps/provisioning_api/lib/Controller/UsersController.php]: Reverted that change.
But if both functions are really not identical that doc-comment is really misleading.

Comment (nickvergessen) [reply apps/provisioning_api/lib/Controller/UsersController.php]: Hmm was not aware of the deprecation, maybe I have wrong memory in my head

File: apps/provisioning_api/lib/Controller/UsersController.php [hunk 4]
```diff
@@ -461,15 +441,15 @@ public function addUser(
 				$group = $this->groupManager->get($groupid);
 				// Check if group exists
 				if ($group === null) {
-					throw new OCSException('Subadmin group does not exist', 102);
+					throw new OCSException('Sub-admin group does not exist', 102);
```
Comment (Pytal) [inline apps/provisioning_api/lib/Controller/UsersController.php:444]: Missing the translation?

File: apps/provisioning_api/lib/Controller/UsersController.php [hunk 5]
```diff
@@ -461,15 +441,15 @@ public function addUser(
...
 				}
 				// Check if trying to make subadmin of admin group
 				if ($group->getGID() === 'admin') {
-					throw new OCSException('Cannot create subadmins for admin group', 103);
+					throw new OCSException('Cannot create sub-admins for admin group', 103);
```
Comment (Pytal) [inline apps/provisioning_api/lib/Controller/UsersController.php:448]: Missing translation?

File: apps/provisioning_api/lib/Controller/UsersController.php [hunk 6]
```diff
@@ -461,15 +441,15 @@ public function addUser(
...
 				}
 				// Check if has permission to promote subadmins
 				if (!$subAdminManager->isSubAdminOfGroup($user, $group) && !$isAdmin) {
-					throw new OCSForbiddenException('No permissions to promote subadmins');
+					throw new OCSForbiddenException('No permissions to promote sub-admins');
```
Comment (Pytal) [inline apps/provisioning_api/lib/Controller/UsersController.php:452]: Missing translation?

**Comment by susnux** [comment]
@Pytal also added translations for the missing exceptions - at least where it makes sense.

**Review by Pytal — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]
