### PR TITLE
fix(TemplateManager): Bail early if templatedirectory is empty

### LINKED ISSUE #39266: Possibility to disable "Templates" directory creation in the config file
If a custom skeleton is used in the config file,

`'skeletondirectory' => '/home/nextcloud/skeleton',`

then an empty "Templates" folder is created for every new user.
This behavior is (somewhat) described in the documentation, see [#39227](https://github.com/nextcloud/server/issues/39227#issuecomment-1628630194)

I found counter-intuitive to create an empty folder, non-wanted by the administrators. I receive constant tickets from my users "For what we should use this "Templates" folder? Can I delete it?". They don't understand why they have this empty folder.

From my point of view, if we have in the config file:
`'templatedirectory' => '',` or similar,
then no "Templates" folder should be created.

Thank you!

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

### PR DESCRIPTION
**Pull request by marcelklehr**
* Resolves: #39266

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by juliusknorr — APPROVED** [review]

File: lib/private/Files/Template/TemplateManager.php [hunk 1]
```diff
@@ -275,6 +275,11 @@ public function initializeTemplateDirectory(string $path = null, string $userId
 		$isDefaultTemplates = $skeletonTemplatePath === $defaultTemplateDirectory;
 		$userLang = $this->l10nFactory->getUserLanguage($this->userManager->get($this->userId));
 
+		if (empty($skeletonTemplatePath)) {
```
Comment (nickvergessen) [inline lib/private/Files/Template/TemplateManager.php:278]:
```suggestion
		if ($skeletonTemplatePath === '') {
```

Since you use `getSystemValueString` it only returns string, then you can explicitly check for the empty string

**Review by ChristophWurst — APPROVED** [review]
Please squash your commits into one

**Review by nickvergessen — APPROVED** [review]
