### PR TITLE
Fix Slow logout on Chrome-like browsers

### LINKED ISSUE #41196: Slow logout on Chrome-like browsers
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

It seems it is due to "Clear-Site-Data": https://github.com/nextcloud/server/pull/17784.
It is related to the issue https://github.com/nextcloud/server/issues/9179 but the issue is closed.

### Steps to reproduce

1. Have a running Nextcloud instance
2. Log in
3. Log out 
4. Wait 30 secs+ because of Clear-Site-Data crap

No issues logging out fast on Safari.

### Expected behavior

1. Have a running Nextcloud instance
2. Log in
3. Log out 
4. Wait 2 secs max.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

Other

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.vip-sourcing.ch"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.1.3.2",
        "overwrite.cli.url": "https:\/\/cloud.vip-sourcing.ch",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 2,
        "default_phone_region": "CH",
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 1.5
        },
        "app_install_overwrite": [
            "mail_roundcube"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - calendar: 4.5.2
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.4.2
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - deck: 1.11.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - impersonate: 1.14.0
  - integration_google: 2.0.2
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - mail: 3.4.3
  - mail_roundcube: 1.0.2
  - nextcloud_announcements: 1.16.0
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - onlyoffice: 8.2.4
  - password_policy: 1.17.0
  - photos: 2.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - support: 1.10.0
  - survey_client: 1.15.0
  - systemtags: 1.17.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - updatenotification: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - admin_audit: 1.17.0
  - bruteforcesettings: 2.7.0
  - encryption: 2.15.0
  - files_external: 1.19.0
  - suspicious_login: 5.0.0
  - twofactor_totp: 9.0.0
  - user_ldap: 1.17.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by HLFH**
* Resolves: #41196

## Summary

It cancels PR #37405, removes all the regression code.
This issue is it has been 9 months than the logout takes 30 seconds on Chrome-like browsers since this PR.
If anything was interesting in the highly damaging PR #37405, I highly recommend to add any feature-related PR in a separate PR, as this one is only meant to fix a critical bug, which makes Nextcloud unusable.

## Checklist

- [x] Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [x] [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

@karlitschek

### CODE REVIEW

File: core/Controller/LoginController.php [hunk 1]
```diff
@@ -105,8 +106,7 @@ public function logout() {
 		$this->session->set('clearingExecutionContexts', '1');
 		$this->session->close();
 
-		if ($this->request->getServerProtocol() === 'https') {
-			// This feature is available only in secure contexts
+		if (!$this->request->isUserAgent([Request::USER_AGENT_CHROME, Request::USER_AGENT_ANDROID_MOBILE_CHROME])) {
```
Comment (artonge) [inline core/Controller/LoginController.php:109]:
```suggestion
		if (
			$this->request->getServerProtocol() === 'https' &&
			!$this->request->isUserAgent([Request::USER_AGENT_CHROME, Request::USER_AGENT_ANDROID_MOBILE_CHROME])
		) {
```

**Review by artonge — CHANGES_REQUESTED** [review]
Let's keep the HTTPS check :)

File: core/Controller/LoginController.php (hunk 1 above)
Comment (artonge) [reply core/Controller/LoginController.php:109]: Can you also add a link to [this issue](https://github.com/nextcloud/server/issues/41196) in a comment so we do not remove the condition again in the future?

**Review by szaimen — APPROVED** [review]
LGTM with the changes by @artonge

**Comment by HLFH** [comment]
I signed-off your commit. @artonge
I don't know if we need to add anything in `LoginControllerTest.php` with your commit.

**Review by artonge — APPROVED** [review]

**Comment by artonge** [comment]
Drone is not triggered. Merging.

**Comment by nickvergessen** [comment]
> Drone is not triggered. Merging.

Drone is actually red due to this PR:
```
Runtime:       PHP 8.2.14
Configuration: phpunit-autotest.xml

FFF............                                                   15 / 15 (100%)

Time: 00:00.049, Memory: 30.00 MB

There were 3 failures:

1) Tests\Core\Controller\LoginControllerTest::testLogoutWithoutToken
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
 OCP\AppFramework\Http\RedirectResponse Object (
     'headers' => Array (
         'Location' => '/login'
-        'Clear-Site-Data' => '"cache", "storage"'
     )
     'cookies' => Array ()
     'status' => 303

/home/nickv/Nextcloud/29/server/tests/Core/Controller/LoginControllerTest.php:160

2) Tests\Core\Controller\LoginControllerTest::testLogoutNoClearSiteData
Expectation failed for method name is "isUserAgent" when invoked 1 time(s).
Method was expected to be called 1 times, actually called 0 times.

3) Tests\Core\Controller\LoginControllerTest::testLogoutWithToken
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
 OCP\AppFramework\Http\RedirectResponse Object (
     'headers' => Array (
         'Location' => '/login'
-        'Clear-Site-Data' => '"cache", "storage"'
     )
     'cookies' => Array ()
     'status' => 303

/home/nickv/Nextcloud/29/server/tests/Core/Controller/LoginControllerTest.php:214
```

Drone is configured to no longer work on forks due to some security implications.

It is recommended to fork the PR into our org for now when they are good.

Can you follow up to make CI green again?

**Comment by HLFH** [comment]
@artonge Can this with https://github.com/nextcloud/server/pull/42633 be backported for stable-28 branch? For 28.0.3 release :)

**Comment by artonge** [comment]
@HLFH can you ensure that https://github.com/nextcloud/server/pull/42633 is included in the created PR?

File: core/Controller/LoginController.php [hunk 2]
```diff
@@ -105,8 +106,10 @@ public function logout() {
 		$this->session->set('clearingExecutionContexts', '1');
 		$this->session->close();
 
-		if ($this->request->getServerProtocol() === 'https') {
-			// This feature is available only in secure contexts
+		if (
+			$this->request->getServerProtocol() === 'https' &&
+			!$this->request->isUserAgent([Request::USER_AGENT_CHROME, Request::USER_AGENT_ANDROID_MOBILE_CHROME])
+		) {
 			$response->addHeader('Clear-Site-Data', '"cache", "storage"');
```
Comment (susnux) [inline core/Controller/LoginController.php:113]: I think this should have been fixed in the master pr. Instead of excluding Chrome just drop the cache part.

Thats what slows chrome down, because of a 7 years old chrome bug...

Comment (skjnldsv) [reply core/Controller/LoginController.php:113]: :eyes:
