### PR TITLE
fix(settings): only provide groups the subadmin has access to 

### LINKED ISSUE #52170: [Bug]: Group Admins are not able to create new Accounts after Upgrade to 30.0.9
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After upgrade to 30.0.9, Group Admins are not able to create new Accounts anymore. 
If you click on "New Account" the Group "admin" is prefilled in "Member of the following groups" and the Group Admin is not able to delete this Group. Adding another Group results in the Error "Logged in account must be an admin, sub admin...".

### Steps to reproduce

1. Create a group and an user with group admin rights for this group
2. Log in as this user and try to create a new user
3. The field "Member of the following groups" is prefilled with the group "admins"
4.  Try to delete this group an add the group created under 1.
5.  Try to create the new user with any other group

### Expected behavior

Group Admins should be able to create new users in their own group.

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 32.0.1 to 32.0.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

See Screenshots:

Image

Image

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: https://github.com/nextcloud/server/issues/52170

## Summary

The group endpoints do not allow to search for users if the user is a subadmin.
So we need to already provide the full list of groups on page load.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by provokateurin — CHANGES_REQUESTED** [review]

File: apps/settings/lib/Controller/UsersController.php [hunk 1]
```diff
@@ -181,6 +183,14 @@ public function usersList(): TemplateResponse {
 			'usercount' => $disabledUsers
 		];
 
+		if (!$isAdmin && !$isDelegatedAdmin) {
```
Comment (susnux) [inline apps/settings/lib/Controller/UsersController.php:186]:
```suggestion
		$subAdminGroups = [];
		if (!$isAdmin && !$isDelegatedAdmin) {
```

**Review by provokateurin — APPROVED** [review]
Backend LGTM

File: apps/settings/lib/Controller/UsersController.php [hunk 2]
```diff
@@ -181,6 +183,15 @@ public function usersList(): TemplateResponse {
 			'usercount' => $disabledUsers
 		];
 
+		$subAdminGroups = [];
+		if (!$isAdmin && !$isDelegatedAdmin) {
+			$subAdmin = \OCP\Server::get(ISubAdmin::class);
```
Comment (skjnldsv) [inline apps/settings/lib/Controller/UsersController.php:188]: No DI ?

**Review by skjnldsv — APPROVED** [review]

File: apps/settings/lib/Controller/UsersController.php (hunk 2 above)
Comment (susnux) [reply apps/settings/lib/Controller/UsersController.php:188]: fixed

**Comment by joshtrichards** [comment]
Related: #52383
