### PR TITLE
fix: (CalDav) Delete invitation link when deleting Calendars or Events

### LINKED ISSUE #12387: When a calendar event is deleted, corresponding calendar_invitation entries are not deleted
A note for minor cleanup.

When a calendarobject (a particular event) is deleted, any outstanding calendar_invitations for that event should be deleted as well.  Currently, I believe they are left dangling until they expire at the end time of the (now deleted) event, if the event has one.

### PR DESCRIPTION
**Pull request by SebastianKrupinski**
* Resolves: #12387

## Summary

When deleting a calendar or event also delete event invitation links

### CODE REVIEW

File: apps/dav/lib/CalDAV/CalDavBackend.php [hunk 1]
```diff
@@ -3527,4 +3535,40 @@ private function rowToSubscription($row, array $subscription): array {
...
+	protected function purgeCalendarInvitations(int $calendarId) {
+		// select all calendar object uid's
+		$cmd1 = $this->db->getQueryBuilder();
+		$cmd1->select('uid')
+			->from($this->dbObjectsTable)
+			->where('calendarid = :cid');
+		// delete all links that match object uid's
+		$cmd2 = $this->db->getQueryBuilder();
+		$cmd2->delete($this->dbObjectInvitationsTable)
+			->where($cmd2->expr()->in('uid', new Literal($cmd1->getSQL())))
```
Comment (tcitworld) [inline apps/dav/lib/CalDAV/CalDavBackend.php:3555]: Won't this explode on Oracle if there's a lot of events for the calendar?
https://github.com/nextcloud/server/blob/a2cfcf3ca71cf748d8507f8ac490df89405b2a68/lib/private/DB/QueryBuilder/QueryBuilder.php#L220

Isn't a join better here?

**Review by tcitworld — COMMENTED** [review]
We also need a repair step to purge all entries in `calendar_invitations` which don't match existing calendar objects.

File: apps/dav/lib/CalDAV/CalDavBackend.php (hunk 1 above)
Comment (SebastianKrupinski) [reply apps/dav/lib/CalDAV/CalDavBackend.php:3555]: Looks like join delete will not work... due to lack of alias support in DBAL.

We would need to execute something like this...
```
DELETE i
FROM oc_calendar_invitations i
INNER JOIN oc_calendarobjects o ON o.uid = i.uid
WHERE o.calendarid = 3432
```

And DBAL does not support DELETE i FROM...
https://github.com/doctrine/dbal/blob/7a8252418689feb860ea8dfeab66d64a56a64df8/src/Connection.php#L392

So our options are...
1) Using a raw sql statement (probably the most efficient)
2) Extending our DBAL implementation to support aliases and using a join (not sure this will really fly)
3) Pulling the UID's from CalendarObjects, splitting them up in chunks of 1k or smaller, and executing a "where in" on each chunk.

Lets have @ChristophWurst weigh in on this.

Comment (tcitworld) [reply apps/dav/lib/CalDAV/CalDavBackend.php:3555]: The raw SQL statement sounds the best then.

Comment (ChristophWurst) [reply apps/dav/lib/CalDAV/CalDavBackend.php:3555]: SELECT, chunk and DELETE like https://github.com/nextcloud/mail/pull/9761

**Comment by miaulalala** [comment]
> We also need a repair step to purge all entries in `calendar_invitations` which don't match existing calendar objects.

Set the expiration date for those outdated links to in the past, and the CleanupInvitationTokenJob will take care of it.

https://github.com/nextcloud/server/blob/af6de04e9e141466dc229e444ff3f146f4a34765/apps/dav/lib/BackgroundJob/CleanupInvitationTokenJob.php

It will probably need modifications like https://github.com/nextcloud/server/blob/af6de04e9e141466dc229e444ff3f146f4a34765/apps/dav/lib/BackgroundJob/DeleteOutdatedSchedulingObjects.php#L30-L34

as to not completely crash an instance until all outdated links are deleted.

Would be a good idea to get some data from our instance too to see how many of these links exist in our database. Please ask the sysadmins to run a query for you.

**Comment by tcitworld** [comment]
In my production instance, with ~22k rows in `oc_calendar_invitations` and 22M rows in `oc_calendarobjects`, I get `2162` entries for
```sql
select count(i.id) from oc_calendar_invitations i left join oc_calendarobjects o on i.uid = o.uid where o.id is null;
```

**Comment by SebastianKrupinski** [comment]
> In my production instance, with ~22k rows in `oc_calendar_invitations` and 22M rows in `oc_calendarobjects`, I get `2162` entries for

22M rows! wow. Can you tell how many calendar object the biggest calendar has?

**Comment by tcitworld** [comment]
> Can you tell how many calendar object the biggest calendar has?

51k objects

**Review by st3iny — APPROVED** [review]
Tested and works. Code looks good, too.

File: apps/dav/lib/CalDAV/CalDavBackend.php (hunk 1 above)
Comment (st3iny) [reply apps/dav/lib/CalDAV/CalDavBackend.php]: Select and chunk is the implemented approach.

File: apps/dav/lib/CalDAV/CalDavBackend.php [hunk 2]
```diff
@@ -3542,4 +3549,47 @@ private function rowToSubscription($row, array $subscription): array {
...
+			->from($this->dbObjectsTable)
+			->where($cmd->expr()->eq('calendarid', $cmd->createNamedParameter($calendarId)));
+		// execute command
+		$allIds = $cmd->executeQuery()->fetchAll(\PDO::FETCH_COLUMN);
+		$allIds = array_chunk($allIds, 1000);
+		// delete all links that match object uid's
+		foreach ($allIds as $chunckIds) {
+			$cmd = $this->db->getQueryBuilder();
+			$cmd->delete($this->dbObjectInvitationsTable)
+				->where($cmd->expr()->in('uid', $cmd->createNamedParameter($chunckIds, IQueryBuilder::PARAM_STR_ARRAY), IQueryBuilder::PARAM_STR_ARRAY));
```
Comment (ChristophWurst) [inline apps/dav/lib/CalDAV/CalDavBackend.php:3575]: perf: the same prepared statement will be created over and over. create the query outside of the loop with a parameter for the chunk ids, then always set the parameter value and execute the query in the loop.

File: apps/dav/lib/CalDAV/CalDavBackend.php [hunk 3]
```diff
@@ -3542,4 +3549,47 @@ private function rowToSubscription($row, array $subscription): array {
...
+			$cmd->executeStatement();
+		}
+	}
+
+	/**
+	 * delete all invitations from a given calendar event
```
Comment (ChristophWurst) [inline apps/dav/lib/CalDAV/CalDavBackend.php:3581]:
```suggestion
	 * Delete all invitations from a given calendar event
```

**Review by ChristophWurst — APPROVED** [review]
Looks good!

Performance wise, we can optimize the query loop a bit

File: apps/dav/lib/CalDAV/CalDavBackend.php (hunk 2 above)
Comment (SebastianKrupinski) [reply apps/dav/lib/CalDAV/CalDavBackend.php]: Done

File: apps/dav/lib/CalDAV/CalDavBackend.php (hunk 3 above)
Comment (SebastianKrupinski) [reply apps/dav/lib/CalDAV/CalDavBackend.php]: Done

**Comment by tcitworld** [comment]
Does someone mind creating an issue for this?
> We also need a repair step to purge all entries in calendar_invitations which don't match existing calendar objects.
