### PR TITLE
fix(systemtags): unify restrict_creation_to_admin handling

### LINKED ISSUE #51233: [Bug]: Multiple bugs concerning tags
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

- [ ] https://github.com/nextcloud/server/issues/51247
  - When tag creation is restricted to administrators (new feature), when a tag is entered in the search field, the creation suggestion should not appear. This creates confusion and, in any case, the error message is too generic (it just indicates that there is an error). End users might think this is a bug. 
- Bug 2: Any user who isn't an administrator can change the colour of tags (and this isn't logical or normal); at the very least, the colour should only change for the current user, otherwise it's a mess: in the current situation, any tag can change colour 10 times a year, depending on individual preferences (which will affect everyone on the platform). This also happens to tags created exclusively by administrators, which is all the more problematic. Apart from this problem, I think that colour changes should only be available for tags created by admins (in the admin settings, where the tags are created). The colour is then imposed by the admin for each tag, and this ensures that the colours don't change and that there's no possible confusion. As far as tags not created by admins are concerned, there are two solutions: the colour cannot be changed, or they can only be changed by admins and/or the creators of the tags in question. 

### Steps to reproduce

Check bug description above

### Expected behavior

Check bug description above

### Nextcloud Server version

31

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 32.0.1 to 32.0.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [x] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "domain.fr"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "31.0.0.18",
    "overwrite.cli.url": "https:\/\/domain.fr",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "updater.release.channel": "beta",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "log_type": "file",
    "logfile": "\/var\/log\/nextcloud\/domain.fr\/nextcloud.log",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "password": "***REMOVED SENSITIVE VALUE***",
        "port": 6379,
        "dbindex": 3,
        "timeout": 0
    },
    "skeletondirectory": "",
    "logtimezone": "Europe\/Paris",
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "PLAIN",
    "default_language": "fr",
    "default_phone_region": "FR",
    "defaultapp": "files",
    "trashbin_retention_obligation": "20,40",
    "versions_retention_obligation": "auto,40",
    "check_for_working_wellknown_setup": false,
    "quota_include_external_storage": false,
    "cron_log": true,
    "has_internet_connection": true,
    "updatechecker": true,
    "appstoreenabled": true,
    "filelocking.enabled": true,
    "session_keepalive": true,
    "knowledgebaseenabled": true,
    "allow_user_to_change_display_name": true,
    "enable_previews": true,
    "enable_avatars": true,
    "auth.bruteforce.protection.enabled": true,
    "loglevel": 1,
    "log_rotate_size": 104857600,
    "mail_smtpauth": 1,
    "mail_smtpport": 465,
    "session_lifetime": 86400,
    "remember_login_cookie_lifetime": 1296000,
    "preview_max_filesize_image": 50,
    "activity_expire_days": 120,
    "maintenance_window_start": 1,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "app_install_overwrite": [
        "admin_audit",
        "user_ldap",
        "mailnotifier",
        "onlyoffice",
        "workspace"
    ],
    "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
    "maintenance": false
}
```

### List of activated Apps

```shell
Enabled:
 - activity: 4.0.0
 - admin_audit: 1.21.0
 - app_api: 5.0.2
 - approval: 2.1.0
 - approve_links: 1.1.0
 - assistant: 2.4.0
 - bruteforcesettings: 4.0.0
 - calendar: 5.1.2
 - circles: 31.0.0-dev.0
 - collectives: 2.16.1
 - comments: 1.21.0
 - contacts: 7.0.1
 - contactsinteraction: 1.12.0
 - context_chat: 4.1.0
 - dashboard: 7.11.0
 - deck: 1.15.0
 - end_to_end_encryption: 1.17.0
 - federation: 1.21.0
 - files_downloadlimit: 4.0.0
 - files_lock: 31.0.1
 - files_pdfviewer: 4.0.0
 - files_reminders: 1.4.0
 - files_sharing: 1.23.1
 - files_trashbin: 1.21.0
 - files_versions: 1.24.0
 - firstrunwizard: 4.0.0
 - forms: 5.0.0
 - groupfolders: 19.0.3
 - impersonate: 2.0.0
 - integration_excalidraw: 2.4.0
 - integration_openai: 3.4.0
 - logreader: 4.0.0
 - mail: 4.2.2
 - mailnotifier: 0.0.3
 - nextcloud_announcements: 3.0.0
 - notes: 4.11.0
 - notifications: 4.0.0
 - openincryptpad: 0.3.7
 - ownershiptransfer: 1.1.0
 - password_policy: 3.0.0
 - photos: 4.0.0-dev.1
 - privacy: 3.0.0
 - recommendations: 4.0.0
 - related_resources: 2.0.0
 - richdocuments: 8.6.2
 - serverinfo: 3.0.0
 - sharebymail: 1.21.0
 - sharereview: 1.3.3
 - spreed: 21.0.0
 - support: 3.0.0
 - systemtags: 1.21.1
 - tables: 0.9.0
 - tasks: 0.16.1
 - text: 5.0.0
 - updatenotification: 1.21.0
 - user_ldap: 1.22.0
 - user_status: 1.11.0
 - users_picker: 1.2.0
 - weather_status: 1.11.0
 - webhook_listeners: 1.2.0
 - whiteboard: 1.0.5
 - workspace: 4.0.2-rc2
Disabled:
 - encryption: 2.19.0
 - files_external
 - onlyoffice: 9.7.0
 - survey_client: 3.0.0
 - suspicious_login
 - twofactor_nextcloud_notification
 - twofactor_totp
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```
Can be provided if necessary
```

### Additional info

Can be provided if necessary

### LINKED ISSUE #51247: restrict tag creation to admin not respected by frontend
Originally reported by @Jerome-Herbinet in https://github.com/nextcloud/server/issues/51233

Bug 1: When tag creation is restricted to administrators (new feature), when a tag is entered in the search field, the creation suggestion should not appear. This creates confusion and, in any case, the error message is too generic (it just indicates that there is an error). End users might think this is a bug.

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/server/issues/51233
Fix https://github.com/nextcloud/server/issues/51247

- [x] Properly allow bulk tagging if tag restriction is active, only prevent creation and color update
- [x] Added Bulk tagging cypress checks for this use case
- [x] Properly check restriction in dav plugin
- [x] Adjusted the differences between default (`false`) and value handling as `bool` (previously `string`)

### CODE REVIEW

File: apps/systemtags/src/components/SystemTagPicker.vue [hunk 1]
```diff
@@ -150,8 +153,8 @@ import PlusIcon from 'vue-material-design-icons/Plus.vue'
 import TagIcon from 'vue-material-design-icons/Tag.vue'
 
 import { createTag, fetchTag, fetchTags, getTagObjects, setTagObjects, updateTag } from '../services/api'
-import { getNodeSystemTags, setNodeSystemTags } from '../utils'
 import { elementColor, invertTextColor, isDarkModeEnabled } from '../utils/colorUtils'
+import { getNodeSystemTags, setNodeSystemTags } from '../utils'
```
Comment (susnux) [inline apps/systemtags/src/components/SystemTagPicker.vue:157]:
```suggestion
import { getNodeSystemTags, setNodeSystemTags } from '../utils.ts'
```

File: apps/systemtags/src/components/SystemTagPicker.vue [hunk 2]
```diff
@@ -204,6 +209,8 @@ export default defineComponent({
 			emit,
 			Status,
 			t,
+			// Either tag creation is not restricted to admins or the current user is an admin
+			canEditOrCreateTag: !restrictSystemTagsCreationToAdmin || getCurrentUser()?.isAdmin,
```
Comment (susnux) [inline apps/systemtags/src/components/SystemTagPicker.vue:213]: name clash with line 251

File: apps/systemtags/src/components/SystemTagsCreationControl.vue [hunk 3]
```diff
@@ -10,13 +10,13 @@
...
 		<p class="settings-hint">
-			{{ t('settings', 'If enabled, regular accounts will be restricted from creating new tags but will still be able to assign and remove them from their files.') }}
+			{{ t('settings', 'If enabled, regular accounts will be restricted from editing or creating new tags but will still be able to assign and remove them from their files.') }}
 		</p>
 
 		<NcCheckboxRadioSwitch type="switch"
 			:checked.sync="systemTagsCreationRestrictedToAdmin"
 			@update:checked="updateSystemTagsDefault">
-			{{ t('settings', 'Restrict tag creation to admins only') }}
+			{{ t('settings', 'Restrict tag edition and creation to admins only') }}
```
Comment (susnux) [inline apps/systemtags/src/components/SystemTagsCreationControl.vue:19]: I think it is

```suggestion
			{{ t('settings', 'Restrict tag editing and creation to admins only') }}
```

File: apps/systemtags/src/components/SystemTagsCreationControl.vue [hunk 4]
```diff
@@ -37,14 +38,19 @@ export default {
...
+		return {
+			t,
+		}
+	},
+
 	data() {
 		return {
 			// By default, system tags creation is not restricted to admins
-			systemTagsCreationRestrictedToAdmin: loadState('settings', 'restrictSystemTagsCreationToAdmin', '0') === '1',
+			systemTagsCreationRestrictedToAdmin: loadState<true|false>('settings', 'restrictSystemTagsCreationToAdmin', false) === true,
```
Comment (susnux) [inline apps/systemtags/src/components/SystemTagsCreationControl.vue:50]:
```suggestion
			systemTagsCreationRestrictedToAdmin: loadState('settings', 'restrictSystemTagsCreationToAdmin', false),
```

File: lib/public/SystemTag/ISystemTagManager.php [hunk 5]
```diff
@@ -129,6 +129,16 @@ public function canUserAssignTag(ISystemTag $tag, ?IUser $user): bool;
 	 */
 	public function canUserCreateTag(?IUser $user): bool;
 
+	/**
+	 * Checks whether the given user is allowed to update tags
+	 *
+	 * @param IUser|null $user user to check permission for
+	 * @return bool true if the user is allowed to update a tag, false otherwise
+	 *
+	 * @since 31.0.0
```
Comment (susnux) [inline lib/public/SystemTag/ISystemTagManager.php:138]:
```suggestion
	 * @since 31.0.1
```

File: lib/public/SystemTag/TagUpdateForbiddenException.php [hunk 6]
```diff
@@ -0,0 +1,18 @@
+<?php
+
+declare(strict_types=1);
+
+/**
+ * SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
```
Comment (susnux) [inline lib/public/SystemTag/TagUpdateForbiddenException.php:6]:
```suggestion
 * SPDX-FileCopyrightText: 2025 Nextcloud GmbH and Nextcloud contributors
```

File: lib/public/SystemTag/TagUpdateForbiddenException.php [hunk 7]
```diff
@@ -0,0 +1,18 @@
...
+ * SPDX-License-Identifier: AGPL-3.0-only
+ */
+
+namespace OCP\SystemTag;
+
+/**
+ * Exception when a user doesn't have the right to create a tag
+ *
+ * @since 31.0.0
```
Comment (susnux) [inline lib/public/SystemTag/TagUpdateForbiddenException.php:15]:
```suggestion
 * @since 31.0.1
```

File: apps/systemtags/src/components/SystemTagsCreationControl.vue (hunk 3 above)
Comment (skjnldsv) [reply apps/systemtags/src/components/SystemTagsCreationControl.vue:19]: I checked and you're right! What a weird phrazing :grin:
I would even go for 
```suggestion
			{{ t('settings', 'Restrict tag creation and editing to administrators only') }}
```

**Comment by skjnldsv** [comment]
> @skjnldsv also fixed #51247 ?

It should yes :+1:

File: lib/private/SystemTag/SystemTagManager.php [hunk 8]
```diff
@@ -206,6 +208,11 @@ public function updateTag(
 			);
 		}
 
+		$user = $this->userSession->getUser();
+		if (!$this->canUserCreateTag($user)) {
```
Comment (Altahrim) [inline lib/private/SystemTag/SystemTagManager.php:212]: Even if it's an alias, probably better to use it:
```suggestion
		if (!$this->canUserUpdateTag($user)) {
```

**Review by Altahrim — COMMENTED** [review]
PHP part looks good :) Thanks!

**Review by susnux — APPROVED** [review]

**Review by Altahrim — APPROVED** [review]
