### PR TITLE
fix(AppFramework): Check for responder existence

### LINKED ISSUE #55619: DomainException thrown in case of errors - No responder registered for format xhtml+xml!
> Opposed to `Controller::getResponderByHTTPHeader()` which was used before, this here no longer checks if there is a responder registered and does not fall back to the default type correctly.
> E.g. When you create a share for a file that can not have a preview (e.g. PDF without PDF being enabled), instead of having a proper 404, the response now is:
> ```
> Technische Details
> 
>     Entfernte Adresse: ::1
>     Anfragekennung: 3RuRvo3TEr52XxYi3pq6
>     Typ: DomainException
>     Code: 0
>     Nachricht: No responder registered for format xhtml+xml!
>     Datei: /home/nickv/Nextcloud/33/server/lib/public/AppFramework/Controller.php
>     Zeile: 139
> 
> 
> Trace
> 
> #0 /home/nickv/Nextcloud/33/server/lib/private/AppFramework/Http/Dispatcher.php(227): OCP\AppFramework\Controller->buildResponse(Object(OCP\AppFramework\Http\DataResponse), '...')
> #1 /home/nickv/Nextcloud/33/server/lib/private/AppFramework/Http/Dispatcher.php(118): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Files_Sharing\Controller\PublicPreviewController), '...')
> #2 /home/nickv/Nextcloud/33/server/lib/private/AppFramework/App.php(153): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Files_Sharing\Controller\PublicPreviewController), '...')
> #3 /home/nickv/Nextcloud/33/server/lib/private/Route/Router.php(321): OC\AppFramework\App::main('...', '...', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
> #4 /home/nickv/Nextcloud/33/server/lib/base.php(1096): OC\Route\Router->match('...')
> #5 /home/nickv/Nextcloud/33/server/index.php(25): OC::handleRequest()
> #6 {main}
> ```
> 
> This works properly until Nextcloud 31. 

 _Originally posted by @nickvergessen in [#54627](https://github.com/nextcloud/server/pull/54627/files#r2412990644)_

### PR DESCRIPTION
**Pull request by provokateurin**
Fixes https://github.com/nextcloud/server/issues/55619

Make sure to check that the responder actually exists, before trying to use it instead of falling back to the default.

### CODE REVIEW

File: lib/private/AppFramework/Http/Dispatcher.php [hunk 1]
```diff
@@ -222,6 +222,9 @@ private function executeController(Controller $controller, string $methodName):
 		// format response
 		if ($response instanceof DataResponse || !($response instanceof Response)) {
 			$format = $this->request->getFormat();
+			if ($format !== null && !$controller->isResponderRegistered($format)) {
+				$format = null;
+			}
 
 			if ($format !== null) {
```
Comment (nickvergessen) [inline lib/private/AppFramework/Http/Dispatcher.php]:
```suggestion
			if ($format !== null && !$controller->isResponderRegistered($format)) {
```

Comment (nickvergessen) [reply lib/private/AppFramework/Http/Dispatcher.php]: One difference is still that we don't check other headers that would be supported. But not sure it actually matters. We could otherwise add a "getRegisteredResponders" method that gives you the keys and hand that in to getFormat?

File: lib/private/AppFramework/Middleware/OCSMiddleware.php [hunk 2]
```diff
@@ -110,7 +110,12 @@ public function afterController($controller, $methodName, Response $response) {
 	 * @return V1Response|V2Response
 	 */
 	private function buildNewResponse(Controller $controller, $code, $message) {
-		$format = $this->request->getFormat() ?? 'xml';
+		$format = $this->request->getFormat();
+		if ($format !== null && !$controller->isResponderRegistered($format)) {
+			$format = null;
+		}
+
+		$format ??= 'xml';
```
Comment (nickvergessen) [inline lib/private/AppFramework/Middleware/OCSMiddleware.php]:
```suggestion
		if ($format === null || !$controller->isResponderRegistered($format)) {
			$format = 'xml';
		}
```

File: lib/private/AppFramework/Http/Dispatcher.php (hunk 1 above)
Comment (provokateurin) [reply lib/private/AppFramework/Http/Dispatcher.php]: The suggestion is good, but the diff is wrong because the `!` needs to be removed as well.

Comment (provokateurin) [reply lib/private/AppFramework/Http/Dispatcher.php]: > But not sure it actually matters

I doubt it, while it is possible it is unlikely anyone does it.

> hand that in to getFormat?

Possible I guess, but would be quite ugly.

**Review by nickvergessen — APPROVED** [review]

**Review by susnux — APPROVED** [review]

File: lib/public/AppFramework/Controller.php [hunk 3]
```diff
@@ -113,10 +114,10 @@ public function getResponderByHTTPHeader($acceptHeader, $default = 'json') {
 	/**
 	 * Registers a formatter for a type
 	 * @param string $format
-	 * @param \Closure $responder
+	 * @param Closure $responder
```
Comment (Altahrim) [inline lib/public/AppFramework/Controller.php:117]: Both can be removed

**Review by Altahrim — APPROVED** [review]

File: lib/public/AppFramework/Controller.php [hunk 4]
```diff
@@ -139,4 +140,8 @@ public function buildResponse($response, $format = 'json') {
 		throw new \DomainException('No responder registered for format '
 			. $format . '!');
 	}
+
+	public function isResponderRegistered(string $responder): bool {
```
Comment (blizzz) [inline lib/public/AppFramework/Controller.php:144]: @since is missing. Did we not have a check for this?

Comment (provokateurin) [reply lib/public/AppFramework/Controller.php:144]: Huh yes :thinking:
