### PR TITLE
FIX: Add feedback on user settings when no results 

### LINKED ISSUE #1070: User management: Search/filtering feedback when no results
When there are no results when searching/filtering, there should be a text saying:
**No users or groups found for searchterm.** (In the `class="emptycontent"` div like we do for files, and the search icon above.)

Otherwise it’s confusing as to if it’s still searching or not.

cc @raghunayyar @blizzz

### PR DESCRIPTION
**Pull request by gsambrotta**
Add visual feedback for users when searching in users settings and no results is found.

Fix #1070

Please review @nextcloud/javascript @nextcloud/designers

### CODE REVIEW

**Comment by jancborchardt** [comment]
Awesome! :) Congrats on your first pull request to Nextcloud, Gio!

Just one things:
- [ ] When you search for a user and there is no result, and you then create that user, the emptycontent still stays and the header is still gone. Let’s see if we can fix that case too :)

File: settings/js/users/users.js [hunk 1]
```diff
@@ -396,15 +397,22 @@ var UserList = {
...
 				});
+
 				if (result.length > 0) {
 					UserList.doSort();
 					$userList.siblings('.loading').css('visibility', 'hidden');
 					// reset state on load
 					UserList.noMoreEntries = false;
+					$userListHead.show();
+					emptyContainer.hide();
+					emptyContainer.find('h2 strong').html();
```
Comment (ChristophWurst) [inline settings/js/users/users.js]: This will *get* the HTML content, hence this function invocation doesn't have any effect. Did you want to clear the element?

File: settings/js/users/users.js [hunk 2]
```diff
@@ -383,6 +383,7 @@ var UserList = {
 		}
 		UserList.currentGid = gid;
 		var pattern = this.filter;
+		var emptyContainer = $userList.siblings('.emptycontent');
```
Comment (ChristophWurst) [inline settings/js/users/users.js]: To align with the variable naming conventions (especially in this file), name the variable `$emptyContainer` since it's a jQuery object :wink:

File: settings/js/users/users.js [hunk 3]
```diff
@@ -396,15 +397,22 @@ var UserList = {
...
+					$userListHead.show();
+					emptyContainer.hide();
+					emptyContainer.find('h2 strong').html();
 				}
 				else {
 					UserList.noMoreEntries = true;
 					$userList.siblings('.loading').remove();
+					$userListHead.hide();
+					emptyContainer.show();
+					emptyContainer.find('h2 strong').html(pattern);
```
Comment (ChristophWurst) [inline settings/js/users/users.js]: `.html(…)` is dangerous. Could you use `.text(…)` instead?

File: settings/templates/users/part.userlist.php [hunk 4]
```diff
@@ -67,3 +67,8 @@
 		</tr>
 	</tbody>
 </table>
+
+<div class="emptycontent" style="display:none">
+	<div class="icon-search"></div>
+	<h2><?php p($l->t("No user found for '"));?><strong></strong>' </h2>
```
Comment (ChristophWurst) [inline settings/templates/users/part.userlist.php]: This will probably not work for all languages. I'm sure @nickvergessen knows a trick for this 😉

**Review by ChristophWurst — CHANGES_REQUESTED** [review]

File: settings/js/users/users.js (hunk 1 above)
Comment (ChristophWurst) [inline settings/js/users/users.js]: See http://api.jquery.com/html/#html1

File: settings/templates/users/part.userlist.php (hunk 4 above)
Comment (jancborchardt) [inline settings/templates/users/part.userlist.php]: @ChristophWurst it’s similar the emptycontent message in the Files app search – but yeah, there it’s constructed via Javascript I think.

Comment (ChristophWurst) [inline settings/templates/users/part.userlist.php]: It will always show something like *No user found for*. The *strong* tag won't be propagated with the desired value this way..

Comment (gsambrotta) [inline settings/templates/users/part.userlist.php]: @ChristophWurst do you mean to add something like this: 
`$emptyContainer.find('h2').text(t('settings', 'No user found for ') + "<strong>" + pattern + "<strong>' ");`

Maybe i understood wrong but the filter value is it currently display in the strong tag. I personally think is more elegant write the translation in the html but if translation won't work like that i will change with the javascript translation.

File: settings/js/users/users.js (hunk 3 above)
Comment (gsambrotta) [inline settings/js/users/users.js]: oh, yes!

File: settings/js/users/users.js (hunk 1 above)
Comment (gsambrotta) [inline settings/js/users/users.js]: ah, yes, good point.

File: settings/templates/users/part.userlist.php (hunk 4 above)
Comment (nickvergessen) [inline settings/templates/users/part.userlist.php]: Should be something like:
```js
$emptyContainer.find('h2').text(t('settings', 'No user found for <strong>{pattern}</strong>', {pattern: pattern}));
```

**Review by nickvergessen — CHANGES_REQUESTED** [review]

File: settings/templates/users/part.userlist.php (hunk 4 above)
Comment (nickvergessen) [inline settings/templates/users/part.userlist.php]: HTML within the pattern placeholder should be escaped automatically with this way.

Comment (gsambrotta) [inline settings/templates/users/part.userlist.php]: i see! will do, thanks

Comment (jancborchardt) [inline settings/templates/users/part.userlist.php]: Yup, in @nickvergessen’s example the single quotes are also removed – which I wanted to recommend doing. :) They are not necessary because there’s already bolding.

**Comment by gsambrotta** [comment]
@jancborchardt i fix also the new user case. Now when user attempt to create a new user, search is reset and it comes back to initial status

**Review by nickvergessen — APPROVED** [review]
Works nicely

**Comment by jancborchardt** [comment]
Awesome, looks good to me! What’s up with the CI failures?

@ChristophWurst are your concerns addressed? :)

**Review by ChristophWurst — COMMENTED** [review]
looks good

**Review by ChristophWurst — APPROVED** [review]

**Comment by jancborchardt** [comment]
@ChristophWurst @nickvergessen @MorrisJobke what about the build failures? They look like they are not entirely relevant to this PR, but I’m not an expert. ;)

**Comment by ChristophWurst** [comment]
> @ChristophWurst @nickvergessen @MorrisJobke what about the build failures? They look like they are not entirely relevant to this PR, but I’m not an expert. ;)

They ran into a timeout, as shown by drone :-)

**Comment by gsambrotta** [comment]
@jancborchardt  thanks! I try to re-run the building couple of time (since i cannot understand what the failing tests are about ) and some of them passed but others similar failed. 
@ChristophWurst any suggestion on how to make them pass?

**Comment by jancborchardt** [comment]
> They ran into a timeout, as shown by drone :-)

So how do we continue? Just merge, or rerun them until all pass? :)

**Comment by ChristophWurst** [comment]
> So how do we continue? Just merge, or rerun them until all pass? :)

They fail almost all the time. Different issue, thus we can ignore this here 😉

**Comment by nickvergessen** [comment]
TImeout happens, can be ignored if nothing DB related was changed and at least one of the DB tests passed.

**Comment by MorrisJobke** [comment]
:/ I have no idea what the timeouts are caused by, but we ahould debug it somehow

**Comment by jancborchardt** [comment]
Yeeeehaaa @gsambrotta congrats on your first pull request to Nextcloud and fixing a nice issue! :tada:  :)
