### PR TITLE
Fixes the undefined index error with the DAV property getlastmodified

### LINKED ISSUE #15363: WebDAV Undefined index: {DAV:}getlastmodified
### Steps to reproduce
1. Add [OpenOLAT](https://www.openolat.com/) webdav share from in the external_files app
2. Credentials are Checked successfully (green arrow)
3. The folder stays empty (No files in here)

### Expected behaviour
WebDAV Files are listed and accessible. Any other tested WebDAV client (Windows, Konquerer, Nautilus, cadaver work just fine.

### Actual behaviour
The external_share shows up, but is empty (No files in here)
The log shows

```
{"reqId":"XMwmVv1CgHdPL6Q-Y8M6lAAAAAE","level":3,"time":"2019-05-03T11:30:30+00:00","remoteAddr":"123.123.123.123","user":"username","app":"PHP","method":"PROPFIND","url":"\/remote.php\/dav\/files\/username\/OLAT","message":"Undefined index: {DAV:}getlastmodified at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/DAV.php#800","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/73.0.3683.103 Safari\/537.36","version":"15.0.7.0"}
{"reqId":"XMwmVv1CgHdPL6Q-Y8M6lQAAAAE","level":3,"time":"2019-05-03T11:30:30+00:00","remoteAddr":"123.123.123.123","user":"username","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2FOLAT","message":"Undefined index: {DAV:}getlastmodified at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/DAV.php#800","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/73.0.3683.103 Safari\/537.36","version":"15.0.7.0"}
{"reqId":"XMwmVv1CgHdPL6Q-Y8M6lQAAAAE","level":3,"time":"2019-05-03T11:30:30+00:00","remoteAddr":"123.123.123.123","user":"username","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2FOLAT","message":"Undefined index: {DAV:}status at \/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Xml\/Element\/Response.php#236","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/73.0.3683.103 Safari\/537.36","version":"15.0.7.0"}
{"reqId":"XMwmVv1CgHdPL6Q-Y8M6lQAAAAE","level":3,"time":"2019-05-03T11:30:30+00:00","remoteAddr":"123.123.123.123","user":"username","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2FOLAT","message":"Undefined offset: 1 at \/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Xml\/Element\/Response.php#237","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/73.0.3683.103 Safari\/537.36","version":"15.0.7.0"}
{"reqId":"XMwmVv1CgHdPL6Q-Y8M6lQAAAAE","level":3,"time":"2019-05-03T11:30:30+00:00","remoteAddr":"123.123.123.123","user":"username","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2FOLAT","message":"Undefined index: {DAV:}status at \/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Xml\/Element\/Response.php#236","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/73.0.3683.103 Safari\/537.36","version":"15.0.7.0"}
{"reqId":"XMwmVv1CgHdPL6Q-Y8M6lQAAAAE","level":3,"time":"2019-05-03T11:30:30+00:00","remoteAddr":"123.123.123.123","user":"username","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2FOLAT","message":"Undefined offset: 1 at \/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Xml\/Element\/Response.php#237","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/73.0.3683.103 Safari\/537.36","version":"15.0.7.0"}
```

### Server configuration

**Operating system**: CentOS Linux release 7.6.1810 (Core)

**Web server:** Apache 2.4.6-89.el7.centos

**Database:** mariadb-server 5.5.60

**PHP version:** PHP 7.1.28

**Nextcloud version:** Nextcloud 15.0.7

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** ZIP from nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
bash-4.2$ php occ app:list
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - calendar: 1.6.5
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.1.1
  - dav: 1.8.1
  - external: 3.2.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_accesscontrol: 1.5.0
  - files_external: 1.6.0
  - files_markdown: 2.0.6
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - groupfolders: 2.0.4
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - notes: 2.6.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - onlyoffice: 2.1.10
  - ownpad: 0.6.12
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - qownnotesapi: 19.4.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_admin: 0.2.0
  - twofactor_backupcodes: 1.4.1
  - twofactor_totp: 2.1.2
  - updatenotification: 1.5.0
  - user_ldap: 1.5.0
  - workflowengine: 1.5.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
bash-4.2$ php occ config:list
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.example.com"
        ],
        "allow_user_to_change_display_name": false,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.7.0",
        "overwrite.cli.url": "https:\/\/cloud.example.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "proxy": "www-proxy.example.com:80",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "logfile": "\/data\/nextcloud.log",
        "loglevel": 2,
        "mail_sendmailmode": "smtp",
        "updater.release.channel": "stable"
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.8.2",
            "types": "filesystem"
        },
        "admin_audit": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "logging"
        },
        "backgroundjob": {
            "lastjob": "15"
        },
        "calendar": {
            "enabled": "[\"Calendar\"]",
            "installed_version": "1.6.5",
            "types": ""
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "[\"Contacts\"]",
            "installed_version": "3.1.1",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "installedat": "1555054181.0879",
            "lastcron": "1556886713",
            "lastupdateResult": "[]",
            "lastupdatedat": "0",
            "oc.integritycheck.checker": "[]",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "scss.variables": "ab669a3a54b500234cd0c2b15c389b61",
            "shareapi_default_permission_canshare": "no",
            "shareapi_default_permission_canupdate": "no",
            "shareapi_default_permissions": "13",
            "vendor": "nextcloud"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "1.8.1",
            "types": "filesystem"
        },
        "external": {
            "enabled": "yes",
            "installed_version": "3.2.0",
            "max_site": "3",
            "sites": "{\"1\":{\"icon\":\"roundcubemail.svg\",\"lang\":\"\",\"type\":\"link\",\"device\":\"browser\",\"groups\":[\"External_Sites\"],\"redirect\":true,\"id\":1,\"name\":\"Webmail\",\"url\":\"https:\\\/\\\/webmail.example.com\\\/roundcube\\\/\"},\"2\":{\"id\":2,\"name\":\"CIM Portal\",\"url\":\"https:\\\/\\\/cim.example.com\\\/cimportal\",\"lang\":\"\",\"type\":\"settings\",\"device\":\"browser\",\"icon\":\"cim-dark.svg\",\"groups\":[\"External_Sites\"],\"redirect\":false},\"3\":{\"icon\":\"external.svg\",\"lang\":\"\",\"type\":\"link\",\"device\":\"\",\"groups\":[\"External_Sites\"],\"redirect\":false,\"id\":3,\"name\":\"Calendar\",\"url\":\"https:\\\/\\\/cal.mail.example.com\\\/cal\\\/\"}}",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "federation": {
            "autoAddServers": "1",
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "default_quota": "5 GB",
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "filesystem"
        },
        "files_accesscontrol": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "filesystem"
        },
        "files_external": {
            "allow_user_mounting": "yes",
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "filesystem",
            "user_mounting_backends": "dav"
        },
        "files_markdown": {
            "enabled": "[\"Markdown\"]",
            "installed_version": "2.0.6",
            "types": ""
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "lookupServerUploadEnabled": "no",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.7.0",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.4.0",
            "types": "logging"
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "18.2.0",
            "types": ""
        },
        "groupfolders": {
            "enabled": "yes",
            "installed_version": "2.0.4",
            "types": "filesystem"
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "levels": "00111",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "authentication"
        },
        "nextcloud_announcements": {
            "enabled": "no",
            "installed_version": "1.4.0",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100",
            "types": "logging"
        },
        "notes": {
            "enabled": "yes",
            "installed_version": "2.6.0",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.3.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "authentication"
        },
        "onlyoffice": {
            "DocumentServerInternalUrl": "",
            "DocumentServerUrl": "https:\/\/ood1.example.com\/",
            "StorageUrl": "",
            "defFormats": "{\"csv\":\"false\",\"doc\":\"false\",\"docm\":\"false\",\"docx\":\"true\",\"dotx\":\"false\",\"epub\":\"false\",\"html\":\"false\",\"odp\":\"false\",\"ods\":\"false\",\"odt\":\"true\",\"pdf\":\"false\",\"potm\":\"false\",\"potx\":\"false\",\"ppsm\":\"false\",\"ppsx\":\"true\",\"ppt\":\"false\",\"pptm\":\"false\",\"pptx\":\"true\",\"rtf\":\"false\",\"txt\":\"false\",\"xls\":\"false\",\"xlsm\":\"false\",\"xlsx\":\"true\",\"xltm\":\"false\",\"xltx\":\"false\"}",
            "editFormats": "{\"csv\":\"true\",\"odp\":\"false\",\"ods\":\"false\",\"odt\":\"false\",\"rtf\":\"false\",\"txt\":\"true\"}",
            "enabled": "yes",
            "groups": "[]",
            "installed_version": "2.1.10",
            "jwt_secret": "",
            "ocsid": "174798",
            "sameTab": "true",
            "settings_error": "",
            "types": "filesystem"
        },
        "ownpad": {
            "enabled": "yes",
            "installed_version": "0.6.12",
            "types": ""
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "prevent_group_restriction"
        },
        "qownnotesapi": {
            "enabled": "yes",
            "installed_version": "19.4.0",
            "types": ""
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "filesystem"
        },
        "spreed": {
            "enabled": "no",
            "installed_version": "5.0.3",
            "signaling_servers": "{\"servers\":[],\"secret\":\"\"}",
            "stun_servers": "[\"stun.nextcloud.com:443\"]",
            "types": "prevent_group_restriction"
        },
        "support": {
            "enabled": "no",
            "installed_version": "1.0.0",
            "types": ""
        },
        "survey_client": {
            "enabled": "no",
            "installed_version": "1.3.0",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "logging"
        },
        "theming": {
            "backgroundMime": "image\/png",
            "cachebuster": "20",
            "color": "#9B0A7D",
            "enabled": "yes",
            "installed_version": "1.6.0",
            "logoMime": "image\/png",
            "name": "CAU Cloud",
            "slogan": "Testinstanz f\u00fcr einen CAU Sync und Share Dienst",
            "types": "logging",
            "url": "https:\/\/cloud.example.com"
        },
        "twofactor_admin": {
            "enabled": "yes",
            "installed_version": "0.2.0",
            "types": ""
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.4.1",
            "types": ""
        },
        "twofactor_totp": {
            "enabled": "yes",
            "installed_version": "2.1.2",
            "types": ""
        },
        "updatenotification": {
            "enabled": "[\"admin\"]",
            "groupfolders": "3.0.0",
            "installed_version": "1.5.0",
            "notes": "2.6.0",
            "onlyoffice": "2.1.10",
            "qownnotesapi": "19.4.0",
            "types": "",
            "update_check_errors": "0"
        },
        "user_ldap": {
            "background_sync_interval": "43200",
            "background_sync_offset": "0",
            "background_sync_prefix": "s01",
            "cleanUpJobOffset": "50",
            "enabled": "yes",
            "installed_version": "1.5.0",
            "s01_lastChange": "1556550192",
            "s01has_memberof_filter_support": "0",
            "s01home_folder_naming_rule": "attr:sAMAccountName",
            "s01last_jpegPhoto_lookup": "0",
            "s01ldap_agent_password": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_attributes_for_group_search": "",
            "s01ldap_attributes_for_user_search": "",
            "s01ldap_backup_host": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_backup_port": "636",
            "s01ldap_base": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_base_groups": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_base_users": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_cache_ttl": "600",
            "s01ldap_configuration_active": "1",
            "s01ldap_default_ppolicy_dn": "",
            "s01ldap_display_name": "displayname",
            "s01ldap_dn": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_dynamic_group_member_url": "",
            "s01ldap_email_attr": "mail",
            "s01ldap_experienced_admin": "1",
            "s01ldap_expert_username_attr": "sAMAccountName",
            "s01ldap_expert_uuid_group_attr": "",
            "s01ldap_expert_uuid_user_attr": "sAMAccountName",
            "s01ldap_gid_number": "gidNumber",
            "s01ldap_group_display_name": "cn",
            "s01ldap_group_filter": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_group_filter_mode": "0",
            "s01ldap_group_member_assoc_attribute": "member",
            "s01ldap_groupfilter_groups": "",
            "s01ldap_groupfilter_objectclass": "",
            "s01ldap_host": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_login_filter": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_login_filter_mode": "0",
            "s01ldap_loginfilter_attributes": "",
            "s01ldap_loginfilter_email": "0",
            "s01ldap_loginfilter_username": "1",
            "s01ldap_nested_groups": "1",
            "s01ldap_override_main_server": "",
            "s01ldap_paging_size": "500",
            "s01ldap_port": "636",
            "s01ldap_quota_attr": "",
            "s01ldap_quota_def": "",
            "s01ldap_tls": "0",
            "s01ldap_turn_off_cert_check": "0",
            "s01ldap_turn_on_pwd_change": "0",
            "s01ldap_user_avatar_rule": "default",
            "s01ldap_user_display_name_2": "",
            "s01ldap_user_filter_mode": "0",
            "s01ldap_userfilter_groups": "",
            "s01ldap_userfilter_objectclass": "",
            "s01ldap_userlist_filter": "***REMOVED SENSITIVE VALUE***",
            "s01use_memberof_to_detect_membership": "1",
            "s02_lastChange": "1556185882",
            "s02has_memberof_filter_support": "0",
            "s02home_folder_naming_rule": "attr:unixHomeDirectory",
            "s02last_jpegPhoto_lookup": "0",
            "s02ldap_agent_password": "***REMOVED SENSITIVE VALUE***",
            "s02ldap_attributes_for_group_search": "",
            "s02ldap_attributes_for_user_search": "",
            "s02ldap_backup_host": "***REMOVED SENSITIVE VALUE***",
            "s02ldap_backup_port": "636",
            "s02ldap_base": "***REMOVED SENSITIVE VALUE***",
            "s02ldap_base_groups": "***REMOVED SENSITIVE VALUE***",
            "s02ldap_base_users": "***REMOVED SENSITIVE VALUE***",
            "s02ldap_cache_ttl": "600",
            "s02ldap_configuration_active": "1",
            "s02ldap_default_ppolicy_dn": "",
            "s02ldap_display_name": "displayname",
            "s02ldap_dn": "***REMOVED SENSITIVE VALUE***",
            "s02ldap_dynamic_group_member_url": "",
            "s02ldap_email_attr": "mail",
            "s02ldap_experienced_admin": "1",
            "s02ldap_expert_username_attr": "sAMAccountName",
            "s02ldap_expert_uuid_group_attr": "",
            "s02ldap_expert_uuid_user_attr": "sAMAccountName",
            "s02ldap_gid_number": "gidNumber",
            "s02ldap_group_display_name": "cn",
            "s02ldap_group_filter": "",
            "s02ldap_group_filter_mode": "0",
            "s02ldap_group_member_assoc_attribute": "member",
            "s02ldap_groupfilter_groups": "",
            "s02ldap_groupfilter_objectclass": "",
            "s02ldap_host": "***REMOVED SENSITIVE VALUE***",
            "s02ldap_login_filter": "***REMOVED SENSITIVE VALUE***",
            "s02ldap_login_filter_mode": "0",
            "s02ldap_loginfilter_attributes": "",
            "s02ldap_loginfilter_email": "0",
            "s02ldap_loginfilter_username": "1",
            "s02ldap_nested_groups": "1",
            "s02ldap_override_main_server": "",
            "s02ldap_paging_size": "500",
            "s02ldap_port": "636",
            "s02ldap_quota_attr": "",
            "s02ldap_quota_def": "",
            "s02ldap_tls": "0",
            "s02ldap_turn_off_cert_check": "0",
            "s02ldap_turn_on_pwd_change": "0",
            "s02ldap_user_avatar_rule": "default",
            "s02ldap_user_display_name_2": "",
            "s02ldap_user_filter_mode": "0",
            "s02ldap_userfilter_groups": "",
            "s02ldap_userfilter_objectclass": "",
            "s02ldap_userlist_filter": "***REMOVED SENSITIVE VALUE***",
            "s02use_memberof_to_detect_membership": "1",
            "types": "authentication"
        },
        "user_saml": {
            "enabled": "no",
            "general-allow_multiple_user_back_ends": "1",
            "general-idp0_display_name": "Shibboleth",
            "general-require_provisioned_account": "1",
            "general-uid_mapping": "urn:oid:1.3.6.1.4.1.5923.1.1.1.6",
            "idp-entityId": "***REMOVED SENSITIVE VALUE***",
            "idp-singleSignOnService.url": "***REMOVED SENSITIVE VALUE***",
            "idp-x509cert": "***REMOVED SENSITIVE VALUE***",
            "installed_version": "2.2.0",
            "saml-attribute-mapping-displayName_mapping": "urn:oid:2.16.840.1.113730.3.1.241",
            "saml-attribute-mapping-email_mapping": "urn:oid:0.9.2342.19200300.100.1.3",
            "security-authnRequestsSigned": "1",
            "security-wantAssertionsEncrypted": "1",
            "security-wantAssertionsSigned": "1",
            "sp-privateKey": "***REMOVED SENSITIVE VALUE***",
            "sp-x509cert": "***REMOVED SENSITIVE VALUE***",
            "type": "saml",
            "types": "authentication"
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "filesystem"
        }
    }
}

```
</details>

**Are you using external storage, if yes which one:** webdav

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** ActiveDirectory and tested shibboleth before (deactivated)

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
not an LDAP problem...
```
</details>

### Client configuration
**Browser:** Google Chrome 73.0.3683.103

**Operating system:** Archlinux

#### Web server error log
<details>
<summary>Web server error log</summary>

```
error_log:
no entries for the problem described.

ssl_access_log:
123.123.123.123 - - [03/May/2019:14:54:55 +0200] "GET /index.php/apps/files/?dir=/OLAT&fileid=4328499 HTTP/1.1" 303 -
123.123.123.123 - - [03/May/2019:14:54:55 +0200] "GET /index.php/apps/files/?dir=/OLAT HTTP/1.1" 200 53121
123.123.123.123 - - [03/May/2019:14:54:55 +0200] "GET /apps/files_markdown/build/styles.css?v=637e04f2-20 HTTP/1.1" 302 -
123.123.123.123 - - [03/May/2019:14:54:55 +0200] "GET /index.php/apps/files/ HTTP/1.1" 200 53119
123.123.123.123 - - [03/May/2019:14:54:56 +0200] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 74
123.123.123.123 - - [03/May/2019:14:54:56 +0200] "GET /index.php/apps/gallery/config?extramediatypes=1 HTTP/1.1" 200 102
123.123.123.123 - - [03/May/2019:14:54:56 +0200] "GET /index.php/apps/ownpad/ajax/v1.0/getconfig HTTP/1.1" 200 138
123.123.123.123 - - [03/May/2019:14:54:56 +0200] "GET /index.php/apps/onlyoffice/ajax/settings HTTP/1.1" 200 2975
123.123.123.123 - - [03/May/2019:14:54:56 +0200] "GET /ocs/v2.php/core/whatsnew?format=json HTTP/1.1" 204 -
123.123.123.123 - - [03/May/2019:14:54:56 +0200] "GET /index.php/apps/systemtags/lastused HTTP/1.1" 200 2
123.123.123.123 - - [03/May/2019:14:54:56 +0200] "PROPFIND /remote.php/dav/files/username/OLAT HTTP/1.1" 207 1110
123.123.123.123 - - [03/May/2019:14:54:56 +0200] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2FOLAT HTTP/1.1" 200 210
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"XMw5kSLUC9r7rCK6Veka5AAAAAo","level":3,"time":"2019-05-03T12:52:33+00:00","remoteAddr":"123.123.123.123","user":"username","app":"PHP","method":"PROPFIND","url":"\/remote.php\/dav\/files\/username\/OLAT","message":"Undefined index: {DAV:}getlastmodified at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/DAV.php#800","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/73.0.3683.103 Safari\/537.36","version":"15.0.7.0"}
{"reqId":"XMw5kSLUC9r7rCK6Veka5QAAAAo","level":3,"time":"2019-05-03T12:52:33+00:00","remoteAddr":"123.123.123.123","user":"username","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2FOLAT","message":"Undefined index: {DAV:}getlastmodified at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/DAV.php#800","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/73.0.3683.103 Safari\/537.36","version":"15.0.7.0"}
{"reqId":"XMw5kSLUC9r7rCK6Veka5QAAAAo","level":3,"time":"2019-05-03T12:52:33+00:00","remoteAddr":"123.123.123.123","user":"username","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2FOLAT","message":"Undefined index: {DAV:}status at \/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Xml\/Element\/Response.php#236","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/73.0.3683.103 Safari\/537.36","version":"15.0.7.0"}
{"reqId":"XMw5kSLUC9r7rCK6Veka5QAAAAo","level":3,"time":"2019-05-03T12:52:33+00:00","remoteAddr":"123.123.123.123","user":"username","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2FOLAT","message":"Undefined offset: 1 at \/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Xml\/Element\/Response.php#237","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/73.0.3683.103 Safari\/537.36","version":"15.0.7.0"}
{"reqId":"XMw5kSLUC9r7rCK6Veka5QAAAAo","level":3,"time":"2019-05-03T12:52:33+00:00","remoteAddr":"123.123.123.123","user":"username","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2FOLAT","message":"Undefined index: {DAV:}status at \/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Xml\/Element\/Response.php#236","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/73.0.3683.103 Safari\/537.36","version":"15.0.7.0"}
{"reqId":"XMw5kSLUC9r7rCK6Veka5QAAAAo","level":3,"time":"2019-05-03T12:52:33+00:00","remoteAddr":"123.123.123.123","user":"username","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2FOLAT","message":"Undefined offset: 1 at \/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Xml\/Element\/Response.php#237","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/73.0.3683.103 Safari\/537.36","version":"15.0.7.0"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
console:
Refused to apply style from 'https://cloud.example.com/index.php/apps/files/' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
core.js?v=6f70d6f9-20:7 JQMIGRATE: Migrate is installed, version 1.4.0
```
</details>

#### Curl Logs
<details>
<summary>This is the PROPFIND reply of the webdav server.</summary>

```
user@host:~>curl -su username example.com/webdav/ -X PROPFIND                                               
Enter host password for user 'username':
<?xml version="1.0" encoding="utf-8"?>
<D:multistatus xmlns:D="DAV:"><D:response><D:href>/webdav/</D:href>
<D:propstat><D:prop><D:creationdate>1970-01-01T00:00:00Z</D:creationdate>
<D:displayname><![CDATA[webdav]]></D:displayname>
<D:resourcetype><D:collection/></D:resourcetype>
<D:source></D:source>
<D:supportedlock><D:lockentry><D:lockscope><D:exclusive/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry><D:lockentry><D:lockscope><D:shared/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry></D:supportedlock>
</D:prop>
<D:status>HTTP/1.1 200 OK</D:status>
</D:propstat>
</D:response>
<D:response><D:href>/webdav/groupfolders/</D:href>
<D:propstat><D:prop><D:creationdate>1970-01-01T00:00:00Z</D:creationdate>
<D:displayname><![CDATA[groupfolders]]></D:displayname>
<D:resourcetype><D:collection/></D:resourcetype>
<D:source></D:source>
<D:supportedlock><D:lockentry><D:lockscope><D:exclusive/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry><D:lockentry><D:lockscope><D:shared/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry></D:supportedlock>
</D:prop>
<D:status>HTTP/1.1 200 OK</D:status>
</D:propstat>
</D:response>
<D:response><D:href>/webdav/home/</D:href>
<D:propstat><D:prop><D:creationdate>1970-01-01T00:00:00Z</D:creationdate>
<D:displayname><![CDATA[home]]></D:displayname>
<D:resourcetype><D:collection/></D:resourcetype>
<D:source></D:source>
<D:supportedlock><D:lockentry><D:lockscope><D:exclusive/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry><D:lockentry><D:lockscope><D:shared/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry></D:supportedlock>
</D:prop>
<D:status>HTTP/1.1 200 OK</D:status>
</D:propstat>
</D:response>
<D:response><D:href>/webdav/sharedfolders/</D:href>
<D:propstat><D:prop><D:creationdate>1970-01-01T00:00:00Z</D:creationdate>
<D:displayname><![CDATA[sharedfolders]]></D:displayname>
<D:resourcetype><D:collection/></D:resourcetype>
<D:source></D:source>
<D:supportedlock><D:lockentry><D:lockscope><D:exclusive/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry><D:lockentry><D:lockscope><D:shared/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry></D:supportedlock>
</D:prop>
<D:status>HTTP/1.1 200 OK</D:status>
</D:propstat>
</D:response>
<D:response><D:href>/webdav/coursefolders/</D:href>
<D:propstat><D:prop><D:creationdate>1970-01-01T00:00:00Z</D:creationdate>
<D:displayname><![CDATA[coursefolders]]></D:displayname>
<D:resourcetype><D:collection/></D:resourcetype>
<D:source></D:source>
<D:supportedlock><D:lockentry><D:lockscope><D:exclusive/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry><D:lockentry><D:lockscope><D:shared/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry></D:supportedlock>
</D:prop>
<D:status>HTTP/1.1 200 OK</D:status>
</D:propstat>
</D:response>
<D:response><D:href>/webdav/doc-pool/</D:href>
<D:propstat><D:prop><D:creationdate>1970-01-01T00:00:00Z</D:creationdate>
<D:displayname><![CDATA[doc-pool]]></D:displayname>
<D:resourcetype><D:collection/></D:resourcetype>
<D:source></D:source>
<D:supportedlock><D:lockentry><D:lockscope><D:exclusive/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry><D:lockentry><D:lockscope><D:shared/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry></D:supportedlock>
</D:prop>
<D:status>HTTP/1.1 200 OK</D:status>
</D:propstat>
</D:response>
<D:response><D:href>/webdav/home/private/</D:href>
<D:propstat><D:prop><D:creationdate>1970-01-01T00:00:00Z</D:creationdate>
<D:displayname><![CDATA[private]]></D:displayname>
<D:resourcetype><D:collection/></D:resourcetype>
<D:source></D:source>
<D:supportedlock><D:lockentry><D:lockscope><D:exclusive/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry><D:lockentry><D:lockscope><D:shared/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry></D:supportedlock>
</D:prop>
<D:status>HTTP/1.1 200 OK</D:status>
</D:propstat>
</D:response>
<D:response><D:href>/webdav/home/public/</D:href>
<D:propstat><D:prop><D:creationdate>1970-01-01T00:00:00Z</D:creationdate>
<D:displayname><![CDATA[public]]></D:displayname>
<D:resourcetype><D:collection/></D:resourcetype>
<D:source></D:source>
<D:supportedlock><D:lockentry><D:lockscope><D:exclusive/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry><D:lockentry><D:lockscope><D:shared/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry></D:supportedlock>
</D:prop>
<D:status>HTTP/1.1 200 OK</D:status>
</D:propstat>
</D:response>
<D:response><D:href>/webdav/home/private/person-dark.svg</D:href>
<D:propstat><D:prop><D:creationdate>2019-05-03T11:15:31Z</D:creationdate>
<D:displayname><![CDATA[person-dark.svg]]></D:displayname>
<D:getlastmodified>Fri, 03 May 2019 11:15:31 GMT</D:getlastmodified>
<D:getcontentlength>2199</D:getcontentlength>
<D:getcontenttype>image/svg+xml</D:getcontenttype>
<D:getetag>W/"2199-1556882131000"</D:getetag>
<D:resourcetype/><D:source></D:source>
<D:supportedlock><D:lockentry><D:lockscope><D:exclusive/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry><D:lockentry><D:lockscope><D:shared/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry></D:supportedlock>
</D:prop>
<D:status>HTTP/1.1 200 OK</D:status>
</D:propstat>
</D:response>
</D:multistatus>
```
</details>

### PR DESCRIPTION
**Pull request by Maaxxs**
This PR fixes the undefined index {DAV:}getlastmodified error, which can occur in the `DAV.php` file.

The return value in the else clause is false if neither `getetag` nor `getlastmodified` is set. At least, I would argue that it should return false because false is returned if there is no response (`$response === false`), and in the exceptions, too.

It resolves some errors from issue #15363.

### CODE REVIEW

**Comment by tcitworld** [comment]
```
There was 1 failure:
1) OCA\Files_External\Tests\Storage\WebdavTest::testStat
Failed asserting that 0 is equal to 1647733789 or is greater than 1647733789. 
/drone/src/tests/lib/Files/Storage/Storage.php:318 
```

**Comment by Maaxxs** [comment]
Somehow I missed that typo yesterday night. Now it should get the proper modified time.

**Review by miaulalala — APPROVED** [review]

File: lib/private/Files/Storage/DAV.php [hunk 1]
```diff
@@ -587,7 +587,7 @@ public function stat($path) {
 				return false;
 			}
 			return [
-				'mtime' => strtotime($response['{DAV:}getlastmodified']),
+				'mtime' => isset($response['{DAV:}getlastmodified']) ? strtotime($response['{DAV:}getlastmodified']) : false,
```
Comment (PVince81) [inline lib/private/Files/Storage/DAV.php:590]: @icewind1991 @artonge can a "false" mtime in stat cause additional issues ?
should the attribute be removed completely when unset?

Comment (artonge) [reply lib/private/Files/Storage/DAV.php:590]: Don't know if it would cause an error, but mixed types are never a good idea IMO. Maybe defaulting to null would be better?

Comment (artonge) [reply lib/private/Files/Storage/DAV.php:590]: Not sure if setting to null is enough to unset the property in php.

Comment (Maaxxs) [reply lib/private/Files/Storage/DAV.php:590]: I set it to false because `strtotime` may return false, too. https://www.php.net/manual/en/function.strtotime.php

Regarding additional issues: I've seen it used [here](https://github.com/nextcloud/server/blob/0fa17f8902e7391f189227b406a0058af6c4a4e0/lib/private/Files/Storage/Common.php#L189) in `Common.php`:
```php
	public function filemtime($path) {
		$stat = $this->stat($path);
		if (isset($stat['mtime']) && $stat['mtime'] > 0) {
			return $stat['mtime'];
		} else {
			return 0;
		}
	}
```
Comparing the bool `false` to `0` should be fine as `false` is represented as `0` (as far as I understand php so far). However, I understand that mixing types is not that great. So, we could change it to `0` or null as you suggested (I'm not sure if it unsets the property in php but as long as there is the `isset` check first, I guess that's fine, too)

File: lib/private/Files/Storage/DAV.php [hunk 2]
```diff
@@ -587,7 +587,7 @@ public function stat($path) {
...
 				'size' => (int)isset($response['{DAV:}getcontentlength']) ? $response['{DAV:}getcontentlength'] : 0,
```
Comment (Maaxxs) [inline lib/private/Files/Storage/DAV.php:591]: Since the value of `$response['{DAV:}getcontentlength']` is used without modification if it exists, we could write
```suggestion
				'size' => $response['{DAV:}getcontentlength'] ?? 0,
```
Just a suggestion as I was looking at this line again.

File: lib/private/Files/Storage/DAV.php (hunk 1 above)
Comment (Maaxxs) [reply lib/private/Files/Storage/DAV.php]: Done. Not sure if I'm supposed to "resolve" this conversation or if you do :)

File: lib/private/Files/Storage/DAV.php (hunk 2 above)
Comment (artonge) [reply lib/private/Files/Storage/DAV.php:591]: Not sure which version of php introduced it. We need to support v7.3 for NC24 I think.

Comment (tcitworld) [reply lib/private/Files/Storage/DAV.php:591]: > We need to support v7.3 for NC24 I think

Far too late https://github.com/nextcloud/server/pull/29286 :)

Comment (Maaxxs) [reply lib/private/Files/Storage/DAV.php:591]: The null coalescing operator was [introduced with php 7](https://www.php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op). ([php rfc](https://wiki.php.net/rfc/isset_ternary))

So as long as we keep the `(int)` cast because `getcontentlength` is represented as string (I think?) that should be fine. However, I don't have a strong opinion about it. If you want to keep it the way it is, that's fine, too :)

Comment (artonge) [reply lib/private/Files/Storage/DAV.php:591]: Actually, `(int)null` give `0`, so it would probably work to keep the following:

```suggestion
 			'size' => (int)$response['{DAV:}getcontentlength']),
```

But it generates a warning `PHP Notice:  Undefined index: ko in php shell code on line 1`. Same with `??`. So let's not change the current way :).

**Review by artonge — APPROVED** [review]

File: lib/private/Files/Storage/DAV.php (hunk 2 above)
Comment (Maaxxs) [reply lib/private/Files/Storage/DAV.php:591]: Ok. I'm wondering how you get this notice? Executing the following snippet with php 7.4.3 results in a notice, which (I think) is the same as yours:

```php
<?php

$arr = ['length' => '123'];

// key defined in arr
$length = (int)$arr['length'] ?? 0;
$length2 = (int)($arr['length'] ?? 0);

// key not defined in arr
$not_def = (int)$arr['not_defined'] ?? 0; // notice here
$not_def2 = (int)($arr['not_defined'] ?? 0);


echo gettype($length) . ": " .$length ."\n";
echo gettype($length2) . ": " .$length2 ."\n";
echo gettype($not_def) . ": " .$not_def ."\n";
echo gettype($not_def2) . ": " .$not_def2 ."\n";
```

`PHP Notice:  Undefined index: not_defined in /home/user/nullthing.php on line 10`
The statement one line 11 does basically the same but with extra brackets around null coalescing operator. So I guess they are important. Did you use them? In your suggested change, I see one closing round bracket after the square bracket at the end of the line but no opening bracket in front of `$response`. So, I'm not sure if you forgot to remove the closing bracket or to add the opening bracket :'D

Comment (artonge) [reply lib/private/Files/Storage/DAV.php:591]: Forget the parenthesis, thanks for the example :) I am fine with your change

Comment (Maaxxs) [reply lib/private/Files/Storage/DAV.php]: Sounds good. I applied the suggestion

**Review by artonge — APPROVED** [review]

**Comment by artonge** [comment]
Thanks for the fix @Maaxxs !
