### PR TITLE
Return a default user record if json is broken

### LINKED ISSUE #16340: Unable to delete User
### Steps to reproduce
1. add new user with a php-skript
2. add Attribute 'address' extrakted from a csv.file in ANSI that contains a "ß" (no Problem with UTF-8)
3. login as admin in the nextcloud webinterface

### Actual behaviour
- User dont appear in Users --> everyone 
when scrolling down: all users, who would be listed after that user are not listed and  the message "An error occured during the request. Unable to proceed" appears
in loggig appears: 
TypeError: Argument 1 passed to OC\Accounts\AccountManager::addMissingDefaultValues() must be of the type array, null given, called in /var/www/html/nextcloud/lib/private/Accounts/AccountManager.php on line 139 at /var/www/html/nextcloud/lib/private/Accounts/AccountManager.php#176
- when clicking on a Group this user is a member of, none of the users is shown and the message "An error occured during the request. Unable to proceed" appears. 
- It is impossible to delete the user in the web interface because he is not listed.

With a php skript following oparations work:
- Get users:      shows all users and inclusive that user
- Get groups that user is a member of
- Add that user to a group  
- Change the Attribute 'displayname'

With a php skript following oparations do not work:
- Disabe that user
- Delete that user
- Change the attribute 'address'
- Remove that user from a group   
- Change the password of that user
always the same log-message: TypeError: Argument 1 passed to OC\Accounts\AccountManager::addMissingDefaultValues() must be of the type array, null given, called in /var/www/html/nextcloud/lib/private/Accounts/AccountManager.php on line 139 at /var/www/html/nextcloud/lib/private/Accounts/AccountManager.php#176

### Server configuration

**Operating system**:
Ubuntu 18-04 server

**Web server:**
apache2

**Database:**
mariadb-server

**PHP version:**
PHP 7.2.19

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 16.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
wget https://download.nextcloud.com/server/releases/latest.tar.bz2

**List of activated apps:**
calendar

**Are you using encryption:** yes/no
no

### PR DESCRIPTION
**Pull request by kesselb**
Fix #16340

It's possible that json_decode returns null. Mostly the json is broken.
AddMissingDefaultValues expects an array. Pass null will fail.

How to reproduce: Modify the json in oc_accounts.

Not sure if we need some repair job to kill those broken records. Looks like an edge case to me.

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
:+1: for @kesselb's fix.

Added some logging so this doesn't happen unnoticed.

File: lib/private/Accounts/AccountManager.php [hunk 1]
```diff
@@ -137,6 +146,11 @@ public function getUser(IUser $user) {
 		}
 
 		$userDataArray = json_decode($result[0]['data'], true);
+		$jsonError = json_last_error();
+		if ($userDataArray === null || $jsonError !== JSON_ERROR_NONE) {
+			$this->logger->critical("User data of $uid contained invalid JSON (error $jsonError), hence falling back to a default user record");
```
Comment (kesselb) [inline lib/private/Accounts/AccountManager.php]: `json_last_error_msg()` would log a readable error message.

File: lib/private/Accounts/Hooks.php [hunk 2]
```diff
@@ -87,12 +87,8 @@ public function changeUserHook($params) {
...
 	 */
 	protected function getAccountManager() {
-		if (is_null($this->accountManager)) {
-			$this->accountManager = new AccountManager(
-				\OC::$server->getDatabaseConnection(),
-				\OC::$server->getEventDispatcher(),
-				\OC::$server->getJobList()
-			);
+		if ($this->accountManager === null) {
+			$this->accountManager = \OC::$server->query(AccountManager::class);
```
Comment (kesselb) [inline lib/private/Accounts/Hooks.php]: Nice catch :+1:

**Comment by kesselb** [comment]
CI looks good to me.

File: lib/private/Accounts/AccountManager.php (hunk 1 above)
Comment (ChristophWurst) [reply lib/private/Accounts/AccountManager.php]: Didn't know about that!

For the sake of finally getting this in for 18 I'll leave it as is :)

**Review by blizzz — APPROVED** [review]

**Comment by kesselb** [comment]
18 is fine for me. We can backport it later if necessary.
