### PR TITLE
fix(CalDav): add support for Microsoft time zones

### LINKED ISSUE #48079: [Bug]: DateTimeZone::__construct(): Unknown or bad timezone (W. Europe Standard Time)
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When creating a new calendar meeting via eMClient on Windows, the server rejects the creation of the calendar event due to "unknown or bad timezone".

The client uses Windows 11. The timezone is configured per Windows default (UTC+01, Berlin, with daylight savings enabled).

The creation of appointments did work previously, so the issue was introduced either with NextCloud 30 (updated today) or previously, but not today, due to an updated emClient 10.

### Steps to reproduce

1. configure emClient on windows to access the calendar in NextCloud.
2. create a new event: schedule appointment with 3rd party. Don't specify the timezone explicitly, but use the defaults
3. The creation of the event fails with an Internal Server Error.

### Expected behavior

The event is created, even though the Windows timezone specified in the request is unknown to NextCloud/Linux.

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.aditsystems.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "30.0.0.14",
        "overwrite.cli.url": "https:\/\/cloud.aditsystems.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "DE",
        "htaccess.RewriteBase": "\/",
        "forcessl": true,
        "trashbin_retention_obligation": "auto",
        "allow_user_to_change_display_name": false,
        "lost_password_link": "disabled",
        "oidc_login_provider_url": "https:\/\/sso.a1a-server.de\/realms\/ADIT_Intern\/",
        "oidc_login_client_id": "nextcloud",
        "oidc_login_client_secret": "xxxx",
        "oidc_login_auto_redirect": true,
        "oidc_login_logout_url": "https:\/\/cloud.aditsystems.de\/apps\/oidc_login\/oidc",
        "oidc_login_end_session_redirect": true,
        "oidc_login_redir_fallback": false,
        "oidc_login_attributes": {
            "id": "preferred_username",
            "mail": "email"
        },
        "overwriteprotocol": "https",
        "oidc_login_default_quota": 26843545600,
        "oidc_login_button_text": "Log in with KeyCloak SSO",
        "oidc_login_hide_password_form": false,
        "oidc_login_use_id_token": false,
        "oidc_login_default_group": "",
        "oidc_login_use_external_storage": false,
        "oidc_login_scope": "openid profile",
        "oidc_login_proxy_ldap": false,
        "oidc_login_disable_registration": false,
        "oidc_login_alt_login_page": "assets\/login.php",
        "oidc_login_tls_verify": true,
        "oidc_create_groups": false,
        "oidc_login_webdav_enabled": false,
        "oidc_login_password_authentication": false,
        "oidc_login_public_key_caching_time": 86400,
        "oidc_login_min_time_between_jwks_requests": 10,
        "oidc_login_well_known_caching_time": 86400,
        "oidc_login_update_avatar": false,
        "oidc_login_skip_proxy": false,
        "oidc_login_code_challenge_method": "",
        "maintenance": false,
        "app_install_overwrite": [
            "bookmarks_fulltextsearch",
            "oidc_login",
            "groupfolders",
            "fulltextsearch_elasticsearch",
            "fulltextsearch",
            "files_fulltextsearch"
        ],
        "theme": "",
        "loglevel": 0,
        "maintenance_window_start": 1,
        "default_timezone": "Europe\/Berlin"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 3.0.0
  - admin_audit: 1.20.0
  - announcementcenter: 7.0.0
  - bookmarks: 15.0.1
  - bruteforcesettings: 3.0.0
  - calendar: 5.0.0
  - circles: 30.0.0-dev
  - cloud_federation_api: 1.13.0
  - comments: 1.20.1
  - contacts: 6.1.0
  - contactsinteraction: 1.11.0
  - dashboard: 7.10.0
  - dav: 1.31.1
  - deck: 1.14.0
  - federatedfilesharing: 1.20.0
  - federation: 1.20.0
  - files: 2.2.0
  - files_downloadlimit: 3.0.0
  - files_fulltextsearch: 30.0.0
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_retention: 1.19.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - firstrunwizard: 3.0.0
  - fulltextsearch: 30.0.0
  - fulltextsearch_elasticsearch: 29.0.1
  - groupfolders: 18.0.1
  - integration_gitlab: 3.1.1
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - mail: 4.0.0
  - nextcloud_announcements: 2.0.0
  - notes: 4.10.1
  - notifications: 3.0.0
  - oauth2: 1.18.1
  - oidc_login: 3.1.1
  - password_policy: 2.0.0
  - photos: 3.0.2
  - polls: 7.2.3
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - recognize: 8.0.0
  - recommendations: 3.0.0
  - related_resources: 1.5.0
  - richdocuments: 8.5.0
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - support: 2.0.0
  - survey_client: 2.0.0
  - suspicious_login: 8.0.0
  - systemtags: 1.20.0
  - tasks: 0.16.1
  - text: 4.1.0
  - theming: 2.5.0
  - twofactor_backupcodes: 1.19.0
  - twofactor_totp: 12.0.0-dev
  - updatenotification: 1.20.0
  - user_migration: 7.0.1
  - user_status: 1.10.0
  - viewer: 3.0.0
  - weather_status: 1.10.0
  - webhook_listeners: 1.1.0-dev
  - workflowengine: 2.12.0
Disabled:
  - bookmarks_fulltextsearch: 1.2.0 (installed 1.2.0)
  - encryption: 2.18.0
  - files_external: 1.22.0
  - twofactor_nextcloud_notification: 4.0.0
  - user_ldap: 1.21.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```json
{
  "reqId": "GcrC6nW8dnGiNPCbuZjY",
  "level": 3,
  "time": "2024-09-16T08:35:03+00:00",
  "remoteAddr": "2a02:3100:xxx",
  "user": "d.xxx",
  "app": "webdav",
  "method": "PUT",
  "url": "/remote.php/dav/calendars/d.xxx/migrated-personal/416a2afc-de72-436e-ba46-ca889b6e8fe6.ics",
  "message": "DateTimeZone::__construct(): Unknown or bad timezone (W. Europe Standard Time)",
  "userAgent": "eMClient/10.0.3530.0",
  "version": "30.0.0.14",
  "exception": {
    "Exception": "Exception",
    "Message": "DateTimeZone::__construct(): Unknown or bad timezone (W. Europe Standard Time)",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/aditcloud/htdocs/nextcloud/apps/dav/lib/CalDAV/EventReader.php",
        "line": 131,
        "function": "__construct",
        "class": "DateTimeZone",
        "type": "->",
        "args": [
          "W. Europe Standard Time"
        ]
      },
      {
        "file": "/var/www/aditcloud/htdocs/nextcloud/apps/dav/lib/CalDAV/Schedule/IMipService.php",
        "line": 140,
        "function": "__construct",
        "class": "OCA\\DAV\\CalDAV\\EventReader",
        "type": "->",
        "args": [
          [
            "Sabre\\VObject\\Component\\VEvent",
            [
              "Sabre\\VObject\\Component\\VCalendar",
              "*** sensitive parameters replaced ***",
              "VCALENDAR"
            ],
            "VEVENT"
          ]
        ]
      },
      {
        "file": "/var/www/aditcloud/htdocs/nextcloud/apps/dav/lib/CalDAV/Schedule/IMipPlugin.php",
        "line": 210,
        "function": "buildBodyData",
        "class": "OCA\\DAV\\CalDAV\\Schedule\\IMipService",
        "type": "->",
        "args": [
          [
            "Sabre\\VObject\\Component\\VEvent",
            [
              "Sabre\\VObject\\Component\\VCalendar",
              "*** sensitive parameters replaced ***",
              "VCALENDAR"
            ],
            "VEVENT"
          ],
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/aditcloud/htdocs/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "schedule",
        "class": "OCA\\DAV\\CalDAV\\Schedule\\IMipPlugin",
        "type": "->",
        "args": [
          [
            "Sabre\\VObject\\ITip\\Message",
            "416a2afc-de72-436e-ba46-ca889b6e8fe6",
            "VEVENT",
            "REQUEST",
            3,
            "mailto:d.xxx@xxx.de",
            [
              "Sabre\\VObject\\Parameter",
              "*** sensitive parameters replaced ***",
              "CN",
              false
            ],
            "mailto:xxx.xx@xx.de",
            "xxx xxx",
            "3.7;Could not find principal.",
            [
              "Sabre\\VObject\\Component\\VCalendar",
              "*** sensitive parameters replaced ***",
              "VCALENDAR"
            ],
            true
          ]
        ]
      },
      {
        "file": "/var/www/aditcloud/htdocs/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php",
        "line": 350,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "schedule",
          [
            [
              "Sabre\\VObject\\ITip\\Message",
              "416a2afc-de72-436e-ba46-ca889b6e8fe6",
              "VEVENT",
              "REQUEST",
              3,
              "mailto:d.xxx@xxx.de",
              [
                "Sabre\\VObject\\Parameter",
                "*** sensitive parameters replaced ***",
                "CN",
                false
              ],
              "mailto:xxx.xxx@xxx.de",
              "xxx xxx",
              "3.7;Could not find principal.",
              [
                "Sabre\\VObject\\Component\\VCalendar",
                "*** sensitive parameters replaced ***",
                "VCALENDAR"
              ],
              true
            ]
          ]
        ]
      },
      {
        "file": "/var/www/aditcloud/htdocs/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php",
        "line": 626,
        "function": "deliver",
        "class": "Sabre\\CalDAV\\Schedule\\Plugin",
        "type": "->",
        "args": [
          [
            "Sabre\\VObject\\ITip\\Message",
            "416a2afc-de72-436e-ba46-ca889b6e8fe6",
            "VEVENT",
            "REQUEST",
            3,
            "mailto:d.xxx@xxx.de",
            [
              "Sabre\\VObject\\Parameter",
              "*** sensitive parameters replaced ***",
              "CN",
              false
            ],
            "mailto:xxx.xxx@xxx.de",
            "xxx xxx",
            "3.7;Could not find principal.",
            [
              "Sabre\\VObject\\Component\\VCalendar",
              "*** sensitive parameters replaced ***",
              "VCALENDAR"
            ],
            true
          ]
        ]
      },
      {
        "file": "/var/www/aditcloud/htdocs/nextcloud/apps/dav/lib/CalDAV/Schedule/Plugin.php",
        "line": 190,
        "function": "processICalendarChange",
        "class": "Sabre\\CalDAV\\Schedule\\Plugin",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***",
          [
            "Sabre\\VObject\\Component\\VCalendar",
            "*** sensitive parameters replaced ***",
            "VCALENDAR"
          ],
          [
            "mailto:d.xxx@xxx.de",
            "/remote.php/dav/principals/users/d.xxx/"
          ],
          [],
          true
        ]
      },
      {
        "file": "/var/www/aditcloud/htdocs/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "calendarObjectChange",
        "class": "OCA\\DAV\\CalDAV\\Schedule\\Plugin",
        "type": "->",
        "args": [
          [
            "Sabre\\HTTP\\Request"
          ],
          [
            "Sabre\\HTTP\\Response"
          ],
          [
            "Sabre\\VObject\\Component\\VCalendar",
            "*** sensitive parameters replaced ***",
            "VCALENDAR"
          ],
          "calendars/d.xxx/migrated-personal",
          true,
          true
        ]
      },
      {
        "file": "/var/www/aditcloud/htdocs/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php",
        "line": 889,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "calendarObjectChange",
          [
            [
              "Sabre\\HTTP\\Request"
            ],
            [
              "Sabre\\HTTP\\Response"
            ],
            [
              "Sabre\\VObject\\Component\\VCalendar",
              "*** sensitive parameters replaced ***",
              "VCALENDAR"
            ],
            "calendars/d.xxx/migrated-personal",
            true,
            true
          ]
        ]
      },
      {
        "file": "/var/www/aditcloud/htdocs/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php",
        "line": 760,
        "function": "validateICalendar",
        "class": "Sabre\\CalDAV\\Plugin",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***",
          "*** sensitive parameters replaced ***",
          false,
          [
            "Sabre\\HTTP\\Request"
          ],
          [
            "Sabre\\HTTP\\Response"
          ],
          true
        ]
      },
      {
        "file": "/var/www/aditcloud/htdocs/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "beforeCreateFile",
        "class": "Sabre\\CalDAV\\Plugin",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***",
          "*** sensitive parameters replaced ***",
          [
            "OCA\\DAV\\CalDAV\\Calendar"
          ],
          false
        ]
      },
      {
        "file": "/var/www/aditcloud/htdocs/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 1094,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "beforeCreateFile",
          [
            "*** sensitive parameters replaced ***",
            "*** sensitive parameters replaced ***",
            [
              "OCA\\DAV\\CalDAV\\Calendar"
            ],
            false
          ]
        ]
      },
      {
        "file": "/var/www/aditcloud/htdocs/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
        "line": 504,
        "function": "createFile",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/aditcloud/htdocs/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "httpPut",
        "class": "Sabre\\DAV\\CorePlugin",
        "type": "->",
        "args": [
          [
            "Sabre\\HTTP\\Request"
          ],
          [
            "Sabre\\HTTP\\Response"
          ]
        ]
      },
      {
        "file": "/var/www/aditcloud/htdocs/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 472,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "method:PUT",
          [
            [
              "Sabre\\HTTP\\Request"
            ],
            [
              "Sabre\\HTTP\\Response"
            ]
          ]
        ]
      },
      {
        "file": "/var/www/aditcloud/htdocs/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 253,
        "function": "invokeMethod",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          [
            "Sabre\\HTTP\\Request"
          ],
          [
            "Sabre\\HTTP\\Response"
          ]
        ]
      },
      {
        "file": "/var/www/aditcloud/htdocs/nextcloud/apps/dav/lib/Server.php",
        "line": 370,
        "function": "start",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/aditcloud/htdocs/nextcloud/apps/dav/appinfo/v2/remote.php",
        "line": 19,
        "function": "exec",
        "class": "OCA\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/aditcloud/htdocs/nextcloud/remote.php",
        "line": 146,
        "args": [
          "/var/www/aditcloud/htdocs/nextcloud/apps/dav/appinfo/v2/remote.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/var/www/aditcloud/htdocs/nextcloud/apps/dav/lib/CalDAV/EventReader.php",
    "Line": 131,
    "message": "DateTimeZone::__construct(): Unknown or bad timezone (W. Europe Standard Time)",
    "exception": {},
    "CustomMessage": "DateTimeZone::__construct(): Unknown or bad timezone (W. Europe Standard Time)"
  }
}
```

### Additional info

I've compared the code of the "dav" app from v29 to v30. The newly introduced "EventReader" class directly hands over the `TZID` to `DateTime` when being called in `buildBodyData` - while previously `generateWhenString()` relied on `Property\ICalendar\DateTime $dtstart`.

The timezone submitted by emClient is the default naming in Windows. There seems to be a mapping from Windows timezone names to Linux (e.g., in https://stackoverflow.com/questions/4967903/linux-windows-timezone-mapping ). Others recommend using the Caldav Synchronizer in Outlook (which my colleague doesn't use).

### PR DESCRIPTION
**Pull request by SebastianKrupinski**
* Resolves: #https://github.com/nextcloud/server/issues/48079

## Summary
- Adds handling of Microsoft time zones, when generating iMip emails
- Corrects some spelling

## Checklist
- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/dav/lib/CalDAV/TimeZoneFactory.php [hunk 1]
```diff
@@ -0,0 +1,218 @@
...
+	 * conversion table of Microsoft time zones to IANA time zones
+	 *
+	 * @var array $ms2iana
+	 */
+	private static $ms2iana = [
+		'AUS Central Standard Time' => 'Australia/Darwin',
+		'Aus Central W. Standard Time' => 'Australia/Eucla',
+		'AUS Eastern Standard Time' => 'Australia/Sydney',
+		'Afghanistan Standard Time' => 'Asia/Kabul',
+		'Alaskan Standard Time' => 'America/Anchorage',
```
Comment (ChristophWurst) [inline apps/dav/lib/CalDAV/TimeZoneFactory.php:26]: What's the source of this list? Is it static?

File: apps/dav/lib/CalDAV/TimeZoneFactory.php [hunk 2]
```diff
@@ -0,0 +1,218 @@
...
+		// if zone name is MS convert to IANA, otherwise just assume the zone is IANA
+		if (self::isMS($name)) {
+			$zone = @timezone_open(self::toIANA($name));
+		} else {
+			$zone = @timezone_open($name);
+		}
+		if ($zone instanceof DateTimeZone) {
+			return $zone;
+		} else {
+			return new DateTimeZone('UTC');
```
Comment (ChristophWurst) [inline apps/dav/lib/CalDAV/TimeZoneFactory.php:215]: how about returning null here too so callers can distinguish between a successful translation and the fallback?

I think calling the method with ``$tz = TimeZoneFactor::fromName($foo) ?? new DateTimeZone('UTC')`` makes it more explicit when you actually want the fallback, and allows you to continue with null when you want to handle the failure.

File: apps/dav/lib/CalDAV/TimeZoneFactory.php [hunk 3]
```diff
@@ -0,0 +1,218 @@
...
+	/**
+	 * Generates DateTimeZone object for given time zone name
+	 *
+	 * @since Release 31.0.0
+	 *
+	 * @param string $name time zone name
+	 *
+	 * @return DateTimeZone
+	 */
+	public static function fromName(string $name): DateTimeZone {
```
Comment (ChristophWurst) [inline apps/dav/lib/CalDAV/TimeZoneFactory.php:205]: Could this be a dynamic method to allow overrides/mocks in tests?

File: apps/dav/lib/CalDAV/TimeZoneFactory.php [hunk 4]
```diff
@@ -0,0 +1,218 @@
...
+/**
+ * SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
+ * SPDX-License-Identifier: AGPL-3.0-or-later
+ */
+
+namespace OCA\DAV\CalDAV;
+
+use DateTimeZone;
+
+class TimeZoneFactory {
```
Comment (ChristophWurst) [inline apps/dav/lib/CalDAV/TimeZoneFactory.php:14]: ``@since`` missing

File: apps/dav/lib/CalDAV/TimeZoneFactory.php [hunk 5]
```diff
@@ -0,0 +1,218 @@
...
+
+	/**
+	 * conversion table of Microsoft time zones to IANA time zones
+	 *
+	 * @var array $ms2iana
```
Comment (ChristophWurst) [inline apps/dav/lib/CalDAV/TimeZoneFactory.php:19]:
```suggestion
	 * @var array<string, string> $ms2iana
```

didn't check but please make the type specific

File: apps/dav/lib/CalDAV/TimeZoneFactory.php [hunk 6]
```diff
@@ -0,0 +1,218 @@
...
+	 */
+	private static $ms2iana = [
```
Comment (ChristophWurst) [inline apps/dav/lib/CalDAV/TimeZoneFactory.php:21]: make this a constant

File: apps/dav/tests/unit/CalDAV/EventReaderTest.php [hunk 7]
```diff
@@ -16,18 +16,13 @@
...
-	private $vCalendar1b;
-	/** @var VCalendar */
-	private $vCalendar1c;
-	/** @var VCalendar */
-	private $vCalendar1d;
-	/** @var VCalendar */
-	private $vCalendar2;
-	/** @var VCalendar */
-	private $vCalendar3;
+	private VCalendar $vCalendar1a;
```
Comment (ChristophWurst) [inline apps/dav/tests/unit/CalDAV/EventReaderTest.php:19]: nitpick: try to avoid this in bug fixes, because it may make the backport process more complicated. I suggest to either have a separate commit for refactorings, which can be left out of the backport, or do this in a separate PR

**Review by ChristophWurst — COMMENTED** [review]
Very nice! Thank you

**Comment by ChristophWurst** [comment]
> ## Checklist
> 
>     * Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
> 
>     * [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
> 
>     *

@SebastianKrupinski please keep the original PR template from https://github.com/nextcloud/server/blob/master/.github/pull_request_template.md. Writing docs is very relevant here. Don't drop this.

File: apps/dav/lib/CalDAV/TimeZoneFactory.php [hunk 8]
```diff
@@ -0,0 +1,218 @@
...
+		'West Bank Standard Time' => 'Asia/Hebron',
+		'West Pacific Standard Time' => 'Pacific/Port_Moresby',
+		'Yakutsk Standard Time' => 'Asia/Yakutsk',
+		'Yukon Standard Time' => 'America/Whitehorse',
+	];
+
+	/**
+	 * Determines if given time zone name is a Microsoft time zone
+	 *
+	 * @since Release 31.0.0
```
Comment (ChristophWurst) [inline apps/dav/lib/CalDAV/TimeZoneFactory.php:169]:
```suggestion
	 * @since 31.0.0
```

same for the rest of the file

File: apps/dav/lib/CalDAV/TimeZoneFactory.php (hunk 4 above)
Comment (SebastianKrupinski) [reply apps/dav/lib/CalDAV/TimeZoneFactory.php:14]: Done

File: apps/dav/tests/unit/CalDAV/EventReaderTest.php (hunk 7 above)
Comment (SebastianKrupinski) [reply apps/dav/tests/unit/CalDAV/EventReaderTest.php:19]: Okay, I normally don't, I only did it in this fix because this class was only introduced in version 30 and there are no differences.

File: apps/dav/tests/unit/CalDAV/TimeZoneFactoryTest.php [hunk 9]
```diff
@@ -0,0 +1,49 @@
+<?php
```
Comment (ChristophWurst) [inline apps/dav/tests/unit/CalDAV/TimeZoneFactoryTest.php:1]: strict types

**Review by ChristophWurst — APPROVED** [review]
Looks good otherwise

File: apps/dav/lib/CalDAV/TimeZoneFactory.php [hunk 10]
```diff
@@ -0,0 +1,223 @@
...
+		} else {
+			$zone = @timezone_open($name);
+		}
+		if ($zone instanceof DateTimeZone) {
+			return $zone;
+		} else {
+			return null;
+		}
+	}
+}
```
[the remark this answers is not in the document]
Comment (SebastianKrupinski) [reply apps/dav/lib/CalDAV/TimeZoneFactory.php:223]: I bow to the master and wisdom of your mind. Great way to simplify this.

One question do we need the hard fail tho? If we use "@timezone_open" this would just produce a warning without a hard fail.

[the remark this answers is not in the document]
Comment (solracsf) [reply apps/dav/lib/CalDAV/TimeZoneFactory.php]: I'm not a fan of @ but this is personal 😆
Your new code is fine too ;)

**Comment by antondollmaier** [comment]
As written in #48079, thank you. This MR successfully resolves our issue!

**Review by tcitworld — APPROVED** [review]

File: apps/dav/lib/CalDAV/TimeZoneFactory.php (hunk 1 above)
Comment (solracsf) [reply apps/dav/lib/CalDAV/TimeZoneFactory.php:31]: File: [MS2IANAList.txt](https://github.com/user-attachments/files/18065787/MS2IANAList.txt)

I've got this list with minor changes and some aditions; feel free to take a look and merge :)

**Comment by SebastianKrupinski** [comment]
> As written in #48079, thank you. This MR successfully resolves our issue!

Thanks for testing, you should see the fix, included in the next release of NC30

File: apps/dav/lib/CalDAV/TimeZoneFactory.php (hunk 1 above)
Comment (SebastianKrupinski) [reply apps/dav/lib/CalDAV/TimeZoneFactory.php:31]: Had a look,

Good catch on,

India Standard Time
Nepal Standard Time
West Samoa Standard Time
Yekaterinburg Standard Time

But I will not include the deletions, these are legacy time zones that are still used.

**Comment by SebastianKrupinski** [comment]
> /backport to stable29

This does not exist in 29, 30+ only
