### PR TITLE
Ensured large image is unloaded from memory when generating previews

### LINKED ISSUE #108: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted
## Expected behavior
The preview generation task shouldn't use all PHP memory,

## Current behavior
If the preview generation is run, by e.g. executing the command `./occ preview:generate-all <user>`, the following PHP error might be shown. From my point of view it need to make sure that unused memory is freed instantly after the preview images have been created. Increasing the available PHP memory, as recommended here https://github.com/rullzer/previewgenerator/pull/106, is only half of the job and shouldn't replace a thrifty memory handling.
```
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 9792 bytes) in /srv/www/nextcloud/nextcloud/lib/private/legacy/image.php on line 496
```

### Steps to reproduce
1. Open a command line window
2. Execute: /occ preview:generate-all <user>

#### Server Configuration
OS: Linux 3.16.54
Web server: Apache2 2.4.29
Database: MariaDB 10.0.32
PHP version: 5.6.29
Nextcloud version: 12.0.5

#### Client Configuration
Browser: Mozilla Firefox 58.0.2
Operating system: Windows 10

### LINKED ISSUE #21995: Memory Leak in lib/private/Preview/Generator.php -> generatePreviews
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Cause generatePreviews to be executed many times from the same script (like running the previewgenerator app) with no existing previews - problem only occurs if a preview hasn't already been generated
2. Watch memory disappear until memory limit is reached (regardless of what the limit is set at - tried up to an 8gb memory limit)

### Expected behaviour
You shouldn't run out of memory

### Actual behaviour
You run out of memory

### Investigation Already Completed
* modified previewgenerator generate-all command to dump memory profile with php_memory_profiler
* determined that imagecreatefromstring being called from OC_Image::loadFromData was causing the memory issues (over 97% of memory used by imagecreatefromstring (see image below)
* traced call chain in nextcloud to the call loading $maxPreviewImage in the generatePreviews function
* modified generatePreviews to check if $maxPreviewImage is !== null prior to return, and if it is to call imagedestroy($maxPreviewImage->resource())
```
                if($maxPreviewImage !== null){
                        imagedestroy($maxPreviewImage->resource());
                }

                return $preview;
```
* problem went away - went from an OOM condition after 5-30 images to hundreds of previews being generated and memory consumption staying manageable

Is this the best solution?  🤷 does it work for this problem?  It appears so.

It seems there may be a memory leak in the underlying php imagecreatefromstring function but this work-around allows things to function as expected, at least for me.  I usually do most of my coding these days in python and go, so I may not be the best person to submit a PR for this.

### Server configuration

**Operating system:**
Official nextcloud docker image

**Web server:** apache - built into docker image base with all optional packages installed per nextcloud docker documentation

**Database:** mysql

**PHP version:** 7.4.8

**Nextcloud version:** 19.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 19.0.0 where issue was also observed

**Where did you install Nextcloud from:** dockerhub + addition of extra packages

2020-07-24 20_36_39-C__Users_elijah ARTYNET_scratch_callgrind out  unknown

### PR DESCRIPTION
**Pull request by elijahnyp**
PR to resolve #21995 
likely also resolves   https://github.com/rullzer/previewgenerator/issues/108
incorporates suggestion by @kesselb to use the destroy method of IImage instead of destroying the resource directly.

This change should be very low risk as it's destroying an image object that is only sometimes created.  It's created if there isn't a cached version of the preview and it is independent of the newly generated preview image.

It has been tested on 19.0.1

### CODE REVIEW

**Comment by kesselb** [comment]
Thanks :+1: 

1. Mind to rebase your branch with the latest changes from master? That should fix a lot of CI warnings.
2. GeneratorTest needs an update. The test mocks there are create from the IImage interface but the interface does not have a destory method hence the mocks do not contain the method and the tests are failing.
```

Index: tests/lib/Preview/GeneratorTest.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- tests/lib/Preview/GeneratorTest.php	(revision 701a44bcf93d26b2c27457ee4890992b6d861a14)
+++ tests/lib/Preview/GeneratorTest.php	(date 1595853526830)
@@ -183,7 +183,7 @@
 				$this->fail('Unexpected provider requested');
 			});
 
-		$image = $this->createMock(IImage::class);
+		$image = $this->createMock(\OC_Image::class);
 		$image->method('width')->willReturn(2048);
 		$image->method('height')->willReturn(2048);
 		$image->method('valid')->willReturn(true);
@@ -318,7 +318,7 @@
 	}
 
 	private function getMockImage($width, $height, $data = null) {
-		$image = $this->createMock(IImage::class);
+		$image = $this->createMock(\OC_Image::class);
 		$image->method('height')->willReturn($width);
 		$image->method('width')->willReturn($height);
 		$image->method('valid')->willReturn(true);

```

File: tests/lib/Preview/GeneratorTest.php [hunk 1]
```diff
@@ -31,7 +31,7 @@
 use OCP\Files\SimpleFS\ISimpleFile;
 use OCP\Files\SimpleFS\ISimpleFolder;
 use OCP\IConfig;
-use OCP\IImage;
+use OCP\OC_Image;
```
Comment (kesselb) [inline tests/lib/Preview/GeneratorTest.php:34]: Remove `use OCP\IImage;`

File: tests/lib/Preview/GeneratorTest.php [hunk 2]
```diff
@@ -183,7 +183,7 @@ public function testGetNewPreview() {
 				$this->fail('Unexpected provider requested');
 			});
 
-		$image = $this->createMock(IImage::class);
+		$image = $this->createMock(OC_Image::class);
```
Comment (kesselb) [inline tests/lib/Preview/GeneratorTest.php:186]:
```suggestion
		$image = $this->createMock(\OC_Image::class);
```

File: tests/lib/Preview/GeneratorTest.php [hunk 3]
```diff
@@ -318,7 +318,7 @@ public function testNoProvider() {
 	}
 
 	private function getMockImage($width, $height, $data = null) {
-		$image = $this->createMock(IImage::class);
+		$image = $this->createMock(OC_Image::class);
```
Comment (kesselb) [inline tests/lib/Preview/GeneratorTest.php:321]:
```suggestion
		$image = $this->createMock(\OC_Image::class);
```

Comment (elijahnyp) [reply tests/lib/Preview/GeneratorTest.php:321]: I thought I had - I guess I screwed up the commit.

File: tests/lib/Preview/GeneratorTest.php (hunk 1 above)
Comment (elijahnyp) [reply tests/lib/Preview/GeneratorTest.php]: Removed both - don't need OC_Image either

**Comment by elijahnyp** [comment]
Phew!  I think that did it.  The rebase pulled in a bunch of other commits though - I hope that's okay.

**Comment by elijahnyp** [comment]
There we go, nice and clean, should be good for reviews.  My apologies for the sloppy process to get to this point.

**Review by icewind1991 — APPROVED** [review]
Strange that gc doesn't trigger cleaning this up already

**Comment by elijahnyp** [comment]
> Strange that gc doesn't trigger cleaning this up already

From what I could find, it's just the way php has handled images for years.  There's something in the image libraries that keeps the resource referenced so GC doesn't see it as garbage unless the image is explicitly destroyed.

**Comment by lifesbest23** [comment]
Thanks for the solution, works well for me.
Shouldn't the `$maxPreviewImage instanceof IImage` line be changed to `$maxPreviewImage instanceof OCP\Image` as IImage does not implement the destroy function?

I find this to be the simplest solution for this problem :+1:

**Comment by kesselb** [comment]
> Shouldn't the `$maxPreviewImage instanceof IImage` part be changed to `$maxPreviewImage instanceof OCP\Image` as IImage does not implement the destroy function?

Yes.

**Review by MorrisJobke — APPROVED** [review]
Looks good and works 👍  I pushed a commit to fix the `instanceof` check.

**Comment by kesselb** [comment]
> imagedestroy() function is still available in PHP 8.0, but it does nothing. Memory and other resources will be freed when the \GdImage object is removed either with an explicit unset() call or when it falls out of scope. 

https://php.watch/versions/8.0#imagedestroy

**Review by kesselb — APPROVED** [review]
