### PR TITLE
fix: don't trigger moveShareInOrOutOfShare for reshares

### LINKED ISSUE #57919: [Bug]: Error while renaming a file by a shared user
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When a file is shared and reshared, a user who didn’t upload it (e.g., user2) can’t rename it and gets an error. The file doesn’t rename right away, but after reloading the page, the file got renamed.

### Steps to reproduce

1. As a user `user1`, upload a file named `file.txt`.
2. As a user `user1`, share the file `file.txt `with `user2`.
3. As a user `user2`, share the file `file.txt` with `user3`.
4. When as a `user2`, try to rename the file `file.txt` to `rename.txt`.

### Expected behavior

The file should be renamed from `file.txt` to `rename.txt` successfully.

### Nextcloud Server version

Nextcloud Hub 26 Winter (33.0.0 RC2)

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json
{
    "system": {
        "debug": true,
        "profiler": true,
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            },
            {
                "path": "\/var\/www\/html\/apps-shared",
                "url": "\/apps-shared",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/apps-writable",
                "url": "\/apps-writable",
                "writable": true
            }
        ],
        "allow_local_remote_servers": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "1025",
        "skeletondirectory": "\/skeleton",
        "setup_create_db_user": false,
        "loglevel": 2,
        "log_query": false,
        "query_log_file": "\/shared\/log\/querylog-nextcloud.log",
        "query_log_file_requestid": "yes",
        "diagnostics.logging": false,
        "diagnostics.logging.threshold": 0,
        "log.condition": {
            "apps": [
                "diagnostics",
                "admin_audit"
            ]
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "nextcloud.local",
            "nextcloud.local",
            "172.19.0.8",
            "localhost"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "33.0.0.13",
        "overwrite.cli.url": "https:\/\/nextcloud.local",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "git",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "lookup_server": "",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "user_oidc": {
            "oidc_provider_bearer_validation": true
        }
    }
}
```

### List of activated Apps

```shell
Enabled:
  - cloud_federation_api: 1.17.0
  - comments: 1.23.0
  - contactsinteraction: 1.14.1
  - dashboard: 7.13.0
  - dav: 1.36.0
  - federatedfilesharing: 1.23.0
  - federation: 1.23.0
  - files: 2.5.0
  - files_reminders: 1.6.0
  - files_sharing: 1.25.2
  - files_trashbin: 1.23.0
  - files_versions: 1.26.0
  - groupfolders: 21.0.2
  - lookup_server_connector: 1.21.0
  - oauth2: 1.21.0
  - oidc: 1.15.0
  - profile: 1.2.0
  - provisioning_api: 1.23.0
  - settings: 1.16.0
  - sharebymail: 1.23.0
  - systemtags: 1.23.0
  - theming: 2.8.0
  - twofactor_backupcodes: 1.22.0
  - updatenotification: 1.23.0
  - user_oidc: 8.3.0
  - user_status: 1.13.0
  - weather_status: 1.13.0
  - webhook_listeners: 1.5.0
  - workflowengine: 2.15.0
Disabled:
  - admin_audit: 1.23.0
  - encryption: 2.21.0
  - files_external: 1.25.1
  - integration_openproject: 3.0.0-alpha.1 (installed 3.0.0-alpha.1)
  - testing: 1.23.0
  - user_ldap: 1.24.0
```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes https://github.com/nextcloud/server/issues/57919#issuecomment-3835004339

### CODE REVIEW

**Review by provokateurin — APPROVED** [review]

File: apps/files_sharing/lib/Updater.php [hunk 1]
```diff
@@ -55,6 +55,10 @@ private static function moveShareInOrOutOfShare($path): void {
 			return;
 		}
 
+		if ($src->getMountPoint() instanceof SharedMount) {
+			return;
+		}
```
Comment (artonge) [inline apps/files_sharing/lib/Updater.php]: This will always be `true`, no?

Comment (icewind1991) [reply apps/files_sharing/lib/Updater.php]: Narrow it down to only bail out for the root of the share (so the share itself is being moved, not something being moved into a share)

Comment (artonge) [reply apps/files_sharing/lib/Updater.php]: I am really not sure about the new code either. I was not even able to reproduce the scenario of `moveShareInOrOutOfShare` :see_no_evil:.
Can you maybe add a comment at least?

Comment (icewind1991) [reply apps/files_sharing/lib/Updater.php]: Added a comment

**Review by artonge — APPROVED** [review]
