### PR TITLE
[stable27] Allow share expiry dates lower than enforced limits

### LINKED ISSUE #41076: [Bug]: share setting shows "download" permission twice
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

"Download" permission is showed twice on folder share

### Steps to reproduce

1. go to c.nc.com
2. share a folder
3. click the "..."-menu
4. this is what you see: 
image
5. if you uncheck one of the "allow download" options both get unchecked (same the other way arround)

### Expected behavior

Have only one "allow download" permission

### Installation method

None

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### LINKED ISSUE #41171: [Bug]: "Set expiration date" can be disabled but it doesn't look disabled
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The "Set expiration date" checkbox cannot be visually unchecked if a non-enforced default expiration date is configured by the admin.

This seems to have been introduced in https://github.com/nextcloud/server/pull/40629 in an attempt to fix https://github.com/nextcloud/server/issues/40612.

### Steps to reproduce

1. Admin: Enable "Set default expiration date for shares" and set a data but do NOT enable "Enforce expiration date" (under /settings/admin/sharing)
2. User: create a new share. Notice how since https://github.com/nextcloud/server/pull/40629 the default expiration date is correctly set
3.  Click "Set expiration date" in an attempt to un-check it

### Actual behaviour

The "Set expiration date" box remains checked. The date values are reset, and under the hood the expiration date is correctly unset. Just the UI is wrong.

### Expected behavior

The checkbox should become unchecked.

### Installation method

Community Docker image

### Nextcloud Server version

27.1.3

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
n/a, see https://github.com/nextcloud/server/issues/40612
```

### List of activated Apps

```shell
n/a, see https://github.com/nextcloud/server/issues/40612
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
n/a
```

### PR DESCRIPTION
**Pull request by nfebe**
Manual backport : https://github.com/nextcloud/server/pull/40927

### CODE REVIEW

**Review by artonge — APPROVED** [review]

File: apps/files_sharing/src/views/SharingDetailsTab.vue [hunk 1]
```diff
@@ -418,11 +417,16 @@ export default {
...
+		maxExpirationDateEnforced() {
+			if (this.isPublicShare) {
+				return this.config.defaultExpirationDate
+			}
+			if (this.isRemoteShare) {
+				return this.config.defaultRemoteExpirationDateString
+			}
+			// If it get's here then it must be an internal share
+			if (this.isExpiryDateEnforced) {
+				return this.config.defaultInternalExpirationDate
```
Comment (come-nc) [inline apps/files_sharing/src/views/SharingDetailsTab.vue:429]: Am I reading this wrong or is the date enforced even if the checkbox is not checked for public and remote shares?

Comment (Fenn-CS) [reply apps/files_sharing/src/views/SharingDetailsTab.vue:429]: Nice catch @come-nc, please review : https://github.com/nextcloud/server/pull/40933 and I would back port it here before merge.

**Review by come-nc — APPROVED** [review]
Tested and works
