### PR TITLE
Fixes password input being prompted every time.

### LINKED ISSUE #7106: Always prompt password input
### Steps to reproduce
1. login in
2. click add user
3. show this image

4.i input password ,but Always prompt password input,when i not input nothing click ok ,Nothing happened

5.i look logs

GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 10000 milliseconds with 0 out of 0 bytes received
/var/www/html/nextCloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 103: GuzzleHttp\Exception\RequestException wrapException(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Ring\Exception\ConnectException))
/var/www/html/nextCloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 132: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
/var/www/html/nextCloud/3rdparty/react/promise/src/FulfilledPromise.php - line 25: GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array)
/var/www/html/nextCloud/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php - line 55: React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
/var/www/html/nextCloud/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php - line 43: GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
/var/www/html/nextCloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 134: GuzzleHttp\Message\FutureResponse proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
/var/www/html/nextCloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 165: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
/var/www/html/nextCloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 125: GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
/var/www/html/nextCloud/lib/private/Http/Client/Client.php - line 138: GuzzleHttp\Client->get('https //apps.ne...', Array)
/var/www/html/nextCloud/lib/private/App/AppStore/Fetcher/Fetcher.php - line 99: OC\Http\Client\Client->get('https //apps.ne...', Array)
/var/www/html/nextCloud/lib/private/App/AppStore/Fetcher/AppFetcher.php - line 66: OC\App\AppStore\Fetcher\Fetcher->fetch('', '')
/var/www/html/nextCloud/lib/private/App/AppStore/Fetcher/Fetcher.php - line 162: OC\App\AppStore\Fetcher\AppFetcher->fetch('', '')
/var/www/html/nextCloud/lib/private/Installer.php - line 394: OC\App\AppStore\Fetcher\Fetcher->get()
/var/www/html/nextCloud/apps/updatenotification/lib/Notification/BackgroundJob.php - line 258: OC\Installer isUpdateAvailable('survey_client', Object(OC\App\AppStore\Fetcher\AppFetcher))
/var/www/html/nextCloud/apps/updatenotification/lib/Notification/BackgroundJob.php - line 155: OCA\UpdateNotification\Notification\BackgroundJob->isUpdateAvailable('survey_client')
/var/www/html/nextCloud/apps/updatenotification/lib/Notification/BackgroundJob.php - line 79: OCA\UpdateNotification\Notification\BackgroundJob->checkAppUpdates()
/var/www/html/nextCloud/lib/private/BackgroundJob/Job.php - line 59: OCA\UpdateNotification\Notification\BackgroundJob->run(NULL)
/var/www/html/nextCloud/lib/private/BackgroundJob/TimedJob.php - line 54: OC\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
/var/www/html/nextCloud/cron.php - line 147: OC\BackgroundJob\TimedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
{main}
   

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:
centos
**Web server:**
nginx
**Database:**
sqlite
**PHP version:**
php7-1-11
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 12.0.3

please help me ! thanks

### PR DESCRIPTION
**Pull request by Abijeet**
@rullzer, @nickvergessen - Want to confirm that we're on the same page on this - 

Take the following scenario.

| Server Time | Last Password Confirm | Local Time |
|-------------|-----------------------|------------|
| 12:00 AM    | 11:45 AM              | 5:00 AM    |

In this case, we are showing the confirm dialog, although the dialog shouldn't be shown until 5:15 AM local time.

I've pushed a potential fix but just want to confirm that you are thinking along the same lines.

Here's what the fix does,

1. Echoing the current server time via a JS variable and storing the current time on page load in JS.
2. Calculating the diff and taking it into account when deciding whether to show the password confirmation.

I'll somehow test this once you guys confirm. Also any ideas how I can add test cases for this?

### CODE REVIEW

**Comment by rullzer** [comment]
Yes that makes sense to me. :rocket: 

@danxuliu for ideas how to do fancy JS testing here ;)

**Comment by danxuliu** [comment]
I have not tested it, but I guess that you could unit test this by [stubbing](http://sinonjs.org/releases/v4.1.3/stubs/) the `window` object (so you can set `nc_pageLoad` and `nc_lastLogin` to whichever value you want and then easily restore them back to the original values without interfering with the rest of the tests) and stubbing the `now()` method in `moment` object (so you can control which time is _now_); something like [faking the timers](http://sinonjs.org/releases/v4.1.3/fake-timers/) does not seem necessary here.

Then it would be just a matter of asserting whether `OC.PasswordConfirmation.requiresPasswordConfirmation()` returns the expected value depending on the values of `nc_pageLoad`, `nc_lastLogin`, `moment.now()` and the original `moment.now()` returned when `OC.PasswordConfirmation.init()` was called.

Note that the objects and methods should be stubbed in a `beforeEach` function and restored in an `afterEach` function to ensure that the changes do not interfere with other tests, and they should be added inside a `describe` function for the password confirmation tests.

**Comment by Abijeet** [comment]
Yea, this is going to be a little PITA to test. Any comments on the code?

I'm wondering if you guys are OK with this - https://github.com/nextcloud/server/pull/7635/files#diff-ca285c18e7de20902667e21ba54d7b3eR155

**Review by nickvergessen — APPROVED** [review]
Didn't test, but looks good codewise.
I guess it's also easy enough for a backport, so everyone that uses servers/browsers with wrong time can still use their Nextcloud properly.

**Comment by Abijeet** [comment]
@nickvergessen - Thanks, I'll test and try to add test cases this weekend.

**Comment by Abijeet** [comment]
@danxuliu, @nickvergessen  - Sorry for the barrage of emails that you might have received while I was trying to fix some of the git issues on my end.

I've added the test cases.

File: core/js/tests/specs/passwordConfirmationSpec.js [hunk 1]
```diff
@@ -0,0 +1,42 @@
+describe('OC.PasswordConfirmation tests', function () {
```
Comment (danxuliu) [inline core/js/tests/specs/passwordConfirmationSpec.js]: Please move all these tests to _core/js/tests/specs/coreSpec.js_, as that file contains all the tests for _core/js/js.js_.

File: core/js/tests/specs/passwordConfirmationSpec.js [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+		});
+
+		it('should show the password confirmation dialog', function () {
+			// add server variables
+			window.nc_pageLoad = parseInt(new Date(2018, 0, 3, 1, 15, 0).getTime() / 1000);
+			window.nc_lastLogin = parseInt(new Date(2018, 0, 3, 1, 0, 0).getTime() / 1000);
+			window.backendAllowsPasswordConfirmation = true;
+
+			stubJsPageLoadTime = sinon.stub(OC.PasswordConfirmation, 'pageLoadTime').value(new Date(2018, 0, 3, 12, 0, 0).getTime());
+			stubMomentNow = sinon.stub(moment, 'now').returns(new Date(2018, 0, 3, 12, 20, 0).getTime());
```
Comment (danxuliu) [inline core/js/tests/specs/passwordConfirmationSpec.js]: I think that it would be better to keep the same `stubJsPageLoadTime` as in the previous test case and increase the value returned by `stubMomentNow`. In my opinion this would show the difference in the behaviour between calling `requiresPasswordConfirmation` after 5 minutes or after 30 in a clearer way.

File: core/js/tests/specs/passwordConfirmationSpec.js [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+
+			expect(OC.PasswordConfirmation.requiresPasswordConfirmation()).toBeTruthy();
+		});
+
+
+		afterEach(function () {
```
Comment (danxuliu) [inline core/js/tests/specs/passwordConfirmationSpec.js]: "Chronologically" it makes sense to have `afterEach` after the tests cases, but in all (or at least, most) JavaScript test files it is found before the test cases, so please move it there for consistency :-)

**Review by danxuliu — COMMENTED** [review]
>  Sorry for the barrage of emails that you might have received while I was trying to fix some of the git issues on my end.

Do not worry, no problem! :-)

However, can I ask you to rebase this branch onto the master branch, instead of merging the master branch into this branch? Thanks!

**Comment by Abijeet** [comment]
@danxuliu - Thanks for the review. I made the requested modifications.

**Comment by danxuliu** [comment]
@Abijeet Sorry for the delay, and thanks for the modifications :-)

As your third commit simply fixed the second one based on my requests I took the liberty to squash the third one into the second one. I have also pushed another one with some extra test cases.

**Review by danxuliu — APPROVED** [review]
👍

**Comment by Abijeet** [comment]
@danxuliu - Thank you. I'll keep the modifications you made in mind for future.
