### PR TITLE
fix: play single audio shares with the viewer

### LINKED ISSUE #34027: external audio playback is broken
See 
image

### PR DESCRIPTION
**Pull request by max-nextcloud**
Use the viewer to play audio files.

Close https://github.com/nextcloud/server/issues/34027

- [ ] wait for https://github.com/nextcloud/server/pull/34028 and do a rebase
- [ ] still lacks styling.

### CODE REVIEW

**Comment by szaimen** [comment]
Needs a rebase after https://github.com/nextcloud/server/pull/34028 is merged

File: apps/files_sharing/js/public.js [hunk 1]
```diff
@@ -153,7 +153,7 @@ OCA.Sharing.PublicApp = {
 		});
 
 		if (OCA.Viewer && OCA.Viewer.mimetypes.includes(mimetype)
-			&& (mimetype.startsWith('image/') || mimetype.startsWith('video/'))) {
+			&& (mimetype.startsWith('image/') || mimetype.startsWith('video/') || mimetype.startsWith('audio'))) {
```
Comment (skjnldsv) [inline apps/files_sharing/js/public.js:156]: Why not use the supported Viewer mimes?

**Comment by max-nextcloud** [comment]
Looks like the styling in the viewer relies on `viewer__content` to align the player in the middle. Maybe we should also have that when rendering the viewer in an element other than the modal.

**Comment by szaimen** [comment]
> Looks like the styling in the viewer relies on `viewer__content` to align the player in the middle. Maybe we should also have that when rendering the viewer in an element other than the modal.

lets have a look at the styling after https://github.com/nextcloud/server/pull/34028 is merged. However sounds like a good approach.

**Comment by szaimen** [comment]
Sorry, was on a different PR in my head...

**Comment by szaimen** [comment]
Will have a look at the styling now. @max-nextcloud @skjnldsv do you want to refactor the mimetype handling still?

**Comment by szaimen** [comment]
Style fixes are in https://github.com/nextcloud/server/pull/34055

File: apps/files_sharing/js/public.js (hunk 1 above)
Comment (max-nextcloud) [reply apps/files_sharing/js/public.js:156]: Text has its own hook into files_sharing and does a bunch of tweaks there for the ui.
I have not been able to figure out a good way to use viewer with the text component in this context without larger rewrites.

I agree it would be cleaner.

My understanding is that we are mostly doing this to enable video playback and it should be backported to earlier versions (22 at the time but now at least 24). So I tried to keep changes minimal.
