### PR TITLE
Fix Oracle query limit compliance in Comments

### LINKED ISSUE #26493: `Doctrine\DBAL\Query\QueryException`: More than 1000 expressions in a list are not allowed on Oracle
Getting the following error on Nextcloud 21.

Doctrine\DBAL\Query\QueryException: More than 1000 expressions in a list are not allowed on Oracle.

</details>

```
{"reqId":"LaqWXzUVqo7eg2AoX34h","level":3,"time":"2021-04-09T17:39:07+00:00","remoteAddr":","user":"","app":"core","method":"PROPFIND","url":"/remote.php/dav/files/axheli/Photos/","message":{"Exception":"Doctrine\\DBAL\\Query\\QueryException","Message":"More than 1000 expressions in a list are not allowed on Oracle.","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Comments/Manager.php","line":657,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/CommentPropertiesPlugin.php","line":89,"function":"getNumberOfUnreadCommentsForObjects","class":"OC\\Comments\\Manager","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/CommentPropertiesPlugin.php","line":117,"function":"cacheDirectory","class":"OCA\\DAV\\Connector\\Sabre\\CommentPropertiesPlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"handleGetProperties","class":"OCA\\DAV\\Connector\\Sabre\\CommentPropertiesPlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1052,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":984,"function":"getPropertiesByNode","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1661,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1646,"function":"writeMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":346,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":332,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","Line":268,"CustomMessage":"More than 1000 expressions in a list are not allowed on Oracle."},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36","version":"21.0.1.1","id":"6070916208dba"}

```
</details>

### PR DESCRIPTION
**Pull request by Simounet**
Hi there,
Resolving one more issue about Oracle query limit (#25036) on Nextcloud comments queries.
Could resolve #26493 and related to #4947.
Have a nice day and stay safe.

### CODE REVIEW

**Comment by andyxheli** [comment]
@ChristophWurst @rullzer When you get a chance can you please review :)

**Review by MorrisJobke — APPROVED** [review]
Code looks good 👍

File: lib/private/Comments/Manager.php [hunk 1]
```diff
@@ -634,27 +634,29 @@ public function getNumberOfCommentsForObject($objectType, $objectId, \DateTime $
...
+				))
+				->groupBy('c.object_id');
+
+			if ($verb !== '') {
+				$query->andWhere($query->expr()->eq('c.verb', $query->createNamedParameter($verb)));
+			}
 
-		if ($verb !== '') {
-			$query->andWhere($query->expr()->eq('c.verb', $query->createNamedParameter($verb)));
+			$result = $query->execute();
```
Comment (blizzz) [inline lib/private/Comments/Manager.php:658]: Am I wrong, or is only the last result set handled? Since this is always overwritten, but not processed here.

**Review by blizzz — CHANGES_REQUESTED** [review]

File: lib/private/Comments/Manager.php (hunk 1 above)
Comment (Simounet) [reply lib/private/Comments/Manager.php:658]: You're right. I should include the following lines with the `while`  using the `$result->fetch()`.

File: lib/private/Comments/Manager.php [hunk 2]
```diff
@@ -634,27 +634,29 @@ public function getNumberOfCommentsForObject($objectType, $objectId, \DateTime $
...
-			))
-			->where($query->expr()->eq('c.object_type', $query->createNamedParameter($objectType)))
-			->andWhere($query->expr()->in('c.object_id', $query->createNamedParameter($objectIds, IQueryBuilder::PARAM_STR_ARRAY)))
-			->andWhere($query->expr()->orX(
-				$query->expr()->gt('c.creation_timestamp', 'm.marker_datetime'),
-				$query->expr()->isNull('m.marker_datetime')
-			))
-			->groupBy('c.object_id');
+		foreach (array_chunk($objectIds, 1000) as $chunk) {
+			$query = $this->dbConn->getQueryBuilder();
```
Comment (nickvergessen) [inline lib/private/Comments/Manager.php:638]: Do this once and only set the parameter in the loop

**Review by ChristophWurst — APPROVED** [review]
Didn't test but code looks good

**Comment by MorrisJobke** [comment]
Failure is unrelated and a regression on master -> merge

**Comment by andyxheli** [comment]
Once i added the changes that @nickvergessen implanted the server stopped working  Fix populating the array and closing the cursors #27316

{"reqId":"IaCrQFzY4jvDY9zBZ77j","level":4,"time":"2021-06-01T19:16:58+00:00","remoteAddr":"0.0.0.0","user":"admin","app":"webdav","method":"PROPFIND","url":"/remote.php/dav/files/admin/","message":{"Exception":"Error","Message":"Call to undefined method OC\\DB\\QueryBuilder\\QueryBuilder::executeQuery()","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/CommentPropertiesPlugin.php","line":89,"function":"getNumberOfUnreadCommentsForObjects","class":"OC\\Comments\\Manager","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/CommentPropertiesPlugin.php","line":117,"function":"cacheDirectory","class":"OCA\\DAV\\Connector\\Sabre\\CommentPropertiesPlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"handleGetProperties","class":"OCA\\DAV\\Connector\\Sabre\\CommentPropertiesPlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1052,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":984,"function":"getPropertiesByNode","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1661,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1646,"function":"writeMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":346,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":332,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Comments/Manager.php","Line":662,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36","version":"21.0.2.1","id":"60b688d036699"}

**Review by AndyXheli — COMMENTED** [review]
Once i added the changes that @nickvergessen implanted in #27316 the server stopped working the code worked before the changes.

**Comment by andyxheli** [comment]
@MorrisJobke Just wanted to let you know that this is not on NC 21.0.3
