### PR TITLE
fix: Return correct list of managers for a user

### LINKED ISSUE #47642: [Bug]: accounts -> error message as group manager when you are not allowed to fetch the line manager details
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

[Screencast from 2024-08-30 15-51-30.webm](https://github.com/user-attachments/assets/47d20e04-721a-42d7-b231-357a6dcfb6e8)

### Steps to reproduce

1. Have Admin, Alice (group manager for A-Team), Bob (member of A-Team), Jim (member of A-Team), Tom (**not** a member of A-Team)
2. Admin: Set Tom as line manager for Bob
3. Alice: Login and open the account section
4. See a warning 

### Expected behavior

No warning

### PR DESCRIPTION
**Pull request by Pytal**
## Summary

Fix https://github.com/nextcloud/server/issues/47642

Subadmins may not have access to certain users so we only return the uids for users that are accessible.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: lib/private/User/User.php [hunk 1]
```diff
@@ -536,13 +556,27 @@ public function setQuota($quota) {
 	}
 
 	public function getManagerUids(): array {
+		$user = $this->userSession->getUser();
```
Comment (artonge) [inline lib/private/User/User.php:559]: To make it cleared as there is already a lot of reference to user in this file.
```suggestion
		$connectedUser = $this->userSession->getUser();
```

**Review by artonge — APPROVED** [review]

**Review by come-nc — CHANGES_REQUESTED** [review]
It feels arbitrary to me to be checking permissions for the logged in user in this method.

What if some code from a public page needs to list the managers from a user?
You should filter this from the calling controller, not in the User class.

File: apps/provisioning_api/lib/Controller/AUserData.php [hunk 2]
```diff
@@ -206,6 +191,37 @@ protected function getUserData(string $userId, bool $includeScopes = false): ?ar
...
 	}
 
+	/**
+	 * @return string[]
+	 */
+	protected function getManagers(IUser $user): array {
+		$currentLoggedInUser = $this->userSession->getUser();
+		$isAdmin = $this->groupManager->isAdmin($currentLoggedInUser->getUID());
+		$isDelegatedAdmin = $this->groupManager->isDelegatedAdmin($currentLoggedInUser->getUID());
+		$isSubAdmin = $this->subAdminManager->isSubAdmin($currentLoggedInUser);
```
Comment (come-nc) [inline apps/provisioning_api/lib/Controller/AUserData.php:201]: I may be wrong but getting these values may be expensive in some cases (like doing an LDAP request to check if the user is an group flagged as admin), so it’s better to only compute them if needed rather than all beforehand. I now I’ve seen the same thing in other places.
Only for performance reasons.

**Review by come-nc — APPROVED** [review]

File: apps/provisioning_api/lib/Controller/AUserData.php (hunk 2 above)
Comment (Pytal) [reply apps/provisioning_api/lib/Controller/AUserData.php]: Adjusted 🚀
