### PR TITLE
fix(Session): avoid password confirmation on SSO

### LINKED ISSUE #43612: [Bug]: Can not confirm my password for administrative actions when logged in via LDAP / SAML
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Nextcloud 28.0.2

We primarily use SAML via Active Directory for authentication. If I am logged in for a longer period of time I have to confirm my password for certain tasks such as disabling users, installing apps, etc.

When I now enter my SAML password I receive a 403 Forbidden in the console, and the confirmation prompt displays "wrong password"

### Steps to reproduce

1. Login via SAML
2. Wait some time to be asked for your password again
3. Enter the password and be denied

### Expected behavior

Password is checked against SAML and I can continue without having to log out and log in again

### Installation method

None

### Nextcloud Server version

28.0.2

### Operating system

Ubuntu

### PHP engine version

8.1.21

### Web server

Apache2

### Database engine version

Mysql

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [x] LDAP/ Active Directory
- [x] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.***REMOVED SENSITIVE VALUE***.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.2.5",
        "overwrite.cli.url": "http:\/\/172.22.1.77\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "1, 3",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "defaultapp": "files",
        "default_phone_region": "AT",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "skeletondirectory": "",
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "guest_app"
        ],
        "twofactor_enforced_excluded_groups": [],
        "app_install_overwrite": [
            "cfg_share_links",
            "files_downloadlimit"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - cfg_share_links: 4.2.0
  - cloud_federation_api: 1.11.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - files: 2.0.0
  - files_accesscontrol: 1.18.0
  - files_downloadlimit: 1.1.0
  - files_external: 1.20.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - group_default_quota: 0.1.8
  - groupfolders: 16.0.3
  - guests: 3.0.1
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - provisioning_api: 1.18.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - theming: 2.3.0
  - twofactor_admin: 4.4.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_totp: 10.0.0-beta.2
  - user_ldap: 1.19.0
  - user_saml: 6.1.1
  - viewer: 2.2.0
  - workflowengine: 2.10.0
Disabled:
  - circles: 28.0.0-dev (installed 27.0.1)
  - comments: 1.18.0 (installed 1.17.0)
  - contactsinteraction: 1.9.0 (installed 1.8.0)
  - dashboard: 7.8.0 (installed 7.0.0)
  - encryption: 2.16.0
  - federation: 1.18.0 (installed 1.17.0)
  - firstrunwizard: 2.17.0 (installed 2.16.0)
  - nextcloud_announcements: 1.17.0 (installed 1.16.0)
  - photos: 2.4.0 (installed 2.3.0)
  - privacy: 1.12.0 (installed 1.11.0)
  - recommendations: 2.0.0 (installed 1.6.0)
  - related_resources: 1.3.0 (installed 1.1.0-alpha1)
  - sharebymail: 1.18.0 (installed 1.17.0)
  - support: 1.11.0 (installed 1.10.0)
  - survey_client: 1.16.0 (installed 1.15.0)
  - suspicious_login: 6.0.0
  - systemtags: 1.18.0 (installed 1.17.0)
  - text: 3.9.1 (installed 3.9.1)
  - updatenotification: 1.18.0 (installed 1.17.0)
  - user_status: 1.8.1 (installed 1.0.1)
  - weather_status: 1.8.0 (installed 1.0.0)
```

### Nextcloud Signing status

```shell
too long, will upload paste if neccesary
```

### Nextcloud Logs

```shell
{"reqId":"tNWjYe683QXSWajw1iy6","level":2,"time":"2024-02-16T10:50:02+00:00","remoteAddr":"**removed**","user":"adminsega","app":"core","method":"POST","url":"/index.php/login/confirm","message":"Login failed: 'adminsega' (Remote IP: '**removed**')","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"core"},"id":"65cf3ddfb2338"}
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by blizzz**
* Resolves: #43612 

## Summary

SSO backends like SAML and OIDC tried a trick to suppress password confirmations as they are not possible by design. At least for SAML it was not reliable when existing user backends where used as user repositories.

Now we are setting a special scope with the token, and also make sure that the scope is taken over when tokens are regenerated.

The root source might be elsewhere actually… The _last-password-confirm_ value in the session that both SAML and OIDC store should persists (otherwise, if session data was lost, the SAML user would be logged out). It might be overwritten from elswhere, though I could not find a good candidate either. Anyway, modifying that timestamp in the session was a hack from the start.

## Todos

* [ ] In PasswordConfirmationMiddleware, confirm excludedUserBackEnds can go away and remove it

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [X] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by blizzz** [comment]
@ArtificialOwl do you think it works with GSS, there is also an IApacheBackend implemented, or would this be tricky?

**Comment by nickvergessen** [comment]
The scopes are for "what to access". Bringing in the origin into it sounds like abuse?

**Comment by blizzz** [comment]
> The scopes are for "what to access". Bringing in the origin into it sounds like abuse?

You could argue that, definitely. Extending the Tokens would break API though.

File: lib/private/Authentication/Token/PublicKeyTokenProvider.php [hunk 1]
```diff
@@ -265,6 +265,7 @@
 				OCPIToken::TEMPORARY_TOKEN,
 				$token->getRemember()
 			);
+			$newToken->setScope($token->getScope());
```
[the remark this answers is not in the document]
Comment (blizzz) [reply lib/private/Authentication/Token/PublicKeyTokenProvider.php:268]: IDE should have complained :thinking:

**Comment by juliushaertl** [comment]
> The scopes are for "what to access". Bringing in the origin into it sounds like abuse?

You could also argue that this new scope allow you to access password confirmation requiring endpoints without the password.

File: lib/private/AppFramework/Middleware/Security/PasswordConfirmationMiddleware.php [hunk 2]
```diff
@@ -86,8 +91,16 @@ public function beforeController($controller, $methodName) {
 				$backendClassName = $user->getBackendClassName();
 			}
 
+			$sessionId = $this->session->getId();
+			$token = $this->tokenProvider->getToken($sessionId);
+			$scope = $token->getScopeAsArray();
+			if (isset($scope['sso-based-login']) && $scope['sso-based-login'] === true) {
```
Comment (juliushaertl) [inline lib/private/AppFramework/Middleware/Security/PasswordConfirmationMiddleware.php:97]: Should we actually make those strings constants (also the only other scope `filesystem`) and put them to IToken so that we have somehow documented what is in use?

Comment (blizzz) [reply lib/private/AppFramework/Middleware/Security/PasswordConfirmationMiddleware.php:97]: Actually, yes, good idea.

**Comment by Keeper-of-the-Keys** [comment]
> The root source might be elsewhere actually… The _last-password-confirm_ value in the session that both SAML and OIDC store should persists (otherwise, if session data was lost, the SAML user would be logged out). It might be overwritten from elswhere, though I could not find a good candidate either. Anyway, modifying that timestamp in the session was a hack from the start.

I hope it is OK to reply/discuss here - maybe I misunderstood the comment but if not I just want to note that being thrown back to the IDP when the session is lost would be correct and good behavior then if the IDP still thinks you are logged in it will bounce you back to nextcloud without you even feeling it and if not you need to reidentify as you should, a session on the nextcloud side should not still be alive if the IDP logged you out.

It should also be noted that this doesn't just impact admin actions but also user actions that require password confirmation like creating an app password.

**Comment by blizzz** [comment]
> > The root source might be elsewhere actually… The _last-password-confirm_ value in the session that both SAML and OIDC store should persists (otherwise, if session data was lost, the SAML user would be logged out). It might be overwritten from elswhere, though I could not find a good candidate either. Anyway, modifying that timestamp in the session was a hack from the start.
> 
> I hope it is OK to reply/discuss here - maybe I misunderstood the comment but if not I just want to note that being thrown back to the IDP when the session is lost would be correct and good behavior then if the IDP still thinks you are logged in it will bounce you back to nextcloud without you even feeling it and if not you need to reidentify as you should, a session on the nextcloud side should not still be alive if the IDP logged you out.

You're definitely right there, and that would already be happening if the session is lost. The case is solely about the * last-password-confirm* timestamp we set in the session.  In some cases does not work reliably – unfortunately not in a manner i could reproduce. So it might be manipulated by some other event, or for whatever reason might be dropped.

> It should also be noted that this doesn't just impact admin actions but also user actions that require password confirmation like creating an app password.

:+1:

**Comment by blizzz** [comment]
@nickvergessen  @juliushaertl @joshtrichards @sorbaugh So, how do we move on?

File: lib/public/Authentication/Token/IToken.php [hunk 3]
```diff
@@ -53,6 +53,15 @@ interface IToken extends JsonSerializable {
 	 */
 	public const REMEMBER = 1;
 
+	/**
+	 * @since 29.0.0
```
Comment (nickvergessen) [inline lib/public/Authentication/Token/IToken.php:57]: 30 or 29.0.1

File: lib/public/Authentication/Token/IToken.php [hunk 4]
```diff
@@ -53,6 +53,15 @@ interface IToken extends JsonSerializable {
...
+	 */
+	public const SCOPE_FILESYSTEM = 'filesystem';
+	/**
+	 * @since 29.0.0
```
Comment (nickvergessen) [inline lib/public/Authentication/Token/IToken.php:61]: same

File: lib/public/Authentication/Token/IToken.php (hunk 3 above)
Comment (blizzz) [reply lib/public/Authentication/Token/IToken.php:57]: 30, 29.0.x on the backport

**Comment by blizzz** [comment]
PR is rebased, and CI is green now. Would appreciate reviews :dog:  @ChristophWurst @ArtificialOwl @artonge

File: lib/private/Template/JSConfigHelper.php [hunk 5]
```diff
@@ -313,4 +304,14 @@ public function getConfig(): string {
 
 		return $result;
 	}
+
+	protected function isUserLoggedInViaSSO(): bool {
```
[the remark this answers is not in the document]
Comment (blizzz) [reply lib/private/Template/JSConfigHelper.php:308]: `SCOPE_SKIP_PASSWORD_VALIDATION` then, otherwise it would be misleading.

[the remark this answers is not in the document]
Comment (blizzz) [reply lib/private/Template/JSConfigHelper.php]: Changed namings as following, and rebased.

| before | after |
| --- | --- |
| isUserLoggedInViaSSO	| canUserValidatePassword |
| SCOPE_SINGLE_SIGN_ON	| SCOPE_SKIP_PASSWORD_VALIDATION | 
| sso-based-login |			password-unconfirmable |

File: lib/private/Template/JSConfigHelper.php [hunk 6]
```diff
@@ -287,4 +278,14 @@ public function getConfig(): string {
...
 	}
+
+	protected function canUserValidatePassword(): bool {
+		try {
+			$token = $this->tokenProvider->getToken($this->session->getId());
+		} catch (ExpiredTokenException|WipeTokenException|InvalidTokenException|SessionNotAvailableException) {
+			return false;
+		}
+		$scope = $token->getScopeAsArray();
+		return isset($scope[IToken::SCOPE_SKIP_PASSWORD_VALIDATION]) && $scope[IToken::SCOPE_SKIP_PASSWORD_VALIDATION] === true;
```
Comment (artonge) [inline lib/private/Template/JSConfigHelper.php:289]: I am confused, shouldn't the condition be reversed? I can validate my password if `SCOPE_SKIP_PASSWORD_VALIDATION` is not set or set to `false`.

In any case, I would use `SCOPE_PASSWORD_VALIDATION` to have a naming scheme saying that the user can access the password validation resource.

**Review by artonge — APPROVED** [review]
Good enough for me with nitpick

File: lib/private/Template/JSConfigHelper.php (hunk 6 above)
Comment (blizzz) [reply lib/private/Template/JSConfigHelper.php:289]: Yeah, of course, with renaming everything changed its meaning, while the logic was not changed. https://github.com/nextcloud/server/pull/43942#discussion_r1620876217 :facepalm:

Comment (blizzz) [reply lib/private/Template/JSConfigHelper.php]: Fixed in this fixup commit for better review: https://github.com/nextcloud/server/pull/43942/commits/5b4ae1f96fbad1efada8d39d35aa5a54f03d14c9

That good? Then I squash it.

**Review by artonge — APPROVED** [review]
Good for me

**Comment by blizzz** [comment]
/backport 340939e688fab5c52061bc9e358587fbd8ec9fc8 to stable28

**Review by ChristophWurst — APPROVED** [review]
Change makes sense, code is clean (even split between a fix and a refactoring) but did not test

:shipit:

**Comment by blizzz** [comment]
/backport https://github.com/nextcloud/server/commit/340939e688fab5c52061bc9e358587fbd8ec9fc8 to stable27

**Comment by blizzz** [comment]
/backport 340939e688fab5c52061bc9e358587fbd8ec9fc8 to stable27

File: lib/public/Authentication/Token/IToken.php [hunk 7]
```diff
@@ -34,6 +34,15 @@ interface IToken extends JsonSerializable {
 	 */
 	public const REMEMBER = 1;
 
+	/**
+	 * @since 30.0.0
+	 */
+	public const SCOPE_FILESYSTEM = 'filesystem';
```
Comment (nickvergessen) [inline lib/public/Authentication/Token/IToken.php:40]: @blizzz Please document in https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_30.html#id1

Comment (blizzz) [reply lib/public/Authentication/Token/IToken.php:40]: https://github.com/nextcloud/documentation/pull/12047
