### PR TITLE
Properly handle if the deps file if for some reason empty

### LINKED ISSUE #5696: Files app is empty after upgrade from 11 to 12
### Steps to reproduce
1. Upgrade from NC 11 to 12
2. Go to Files
3. See empty view

### Expected behaviour

See files :P

### Actual behaviour

Files view is empty.  We can still access files through the desktop client.  nextcloud.log throws this message: "Invalid argument supplied for foreach() at /pub/lib/private/Template/JSCombiner.php#107" and web console show other errors (pasted below)

nc

### Server configuration

**Operating system**: Debian Jessie

**Web server:** Nginx 1.11

**Database:** MariaDB 10

**PHP version:** 5.6.30

**Nextcloud version:** 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 11.0.0

**Where did you install Nextcloud from:** downloaded release tarball

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - ownpad: 0.5.10
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_external: 0.4
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "default_language": "es",
        "mail_from_address": "xxxxx",
        "mail_smtpmode": "php",
        "mail_domain": "XXXXX",
        "user_backends": [
            {
                "class": "OC_User_IMAP",
                "arguments": [
                    "{XXXX:993\/imap\/ssl\/novalidate-cert}"
                ]
            }
        ],
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/srv\/http\/xxxxx\/pub\/data",
        "overwrite.cli.url": "https:\/\/xxxxx",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "XXXXX",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "ocd6tg26vyo4",
        "defaultapp": "calendar",
        "loglevel": 1,
        "maintenance": false,
        "debug": false,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "127.0.0.1",
            "port": 6379
        },
        "trusted_domains": [ XXX ]
    }
}


```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** IMAP

### Client configuration
**Browser:** Iceweasel 54.0

**Operating system:** Parabola GNU/Linux-libre

#### Web server error log
<details>
<summary>Web server error log</summary>

```
127.0.0.1 - - [12/Jul/2017:16:29:46 +0000] "GET /apps/files/ HTTP/1.0" 200 40491 "-" "Mozilla/5.0 (Windows NT 6.1; rv:54.0) Gecko/20100101 Firefox/54.0" "127.0.0.1" request_time=0.273

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"lRS4pK5jGKfeeiLMIG9r","level":3,"time":"2017-07-12T16:21:48+00:00","remoteAddr":"127.0.0.1","user":"xxxxxx","app":"PHP","method":"GET","url":"\/apps\/files\/","message":"Invalid argument supplied for foreach() at \/pub\/lib\/private\/Template\/JSCombiner.php#107","userAgent":"Mozilla\/5.0 (Windows NT 6.1; rv:54.0) Gecko\/20100101 Firefox\/54.0","version":"12.0.0.29"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
13:22:42.104 TypeError: OC.SystemTags is undefined 1 merged.js:479:4
	initialize https://xxxxxx/js/systemtags/merged.js:479:4
	Backbone.View https://xxxxxx/core/vendor/core.js:3805:5
	child https://xxxxxx/core/vendor/core.js:4465:34
	child https://xxxxxx/core/vendor/core.js:4465:34
	attach https://xxxxxx/js/systemtags/merged.js:424:32
	attach https://xxxxxx/js/core/merged-template-prepend.js:2064:5
	initialize https://xxxxxx/js/files/merged-index.js:4341:4
	FileList https://xxxxxx/js/files/merged-index.js:4012:3
	initialize https://xxxxxx/js/files/merged-index.js:82:20
	<anonymous> https://xxxxxx/js/files/merged-index.js:315:3
	_.delay/< https://xxxxxx/core/vendor/core.js:781:14
13:22:47.998 TypeError: this.fileList is null 1 merged-index.js:131:5
	_onActionsUpdated https://xxxxxx/js/files/merged-index.js:131:5
	bound _onActionsUpdated self-hosted:913:17
	dispatch https://xxxxxx/core/vendor/core.js:3:6414
	add/r.handle https://xxxxxx/core/vendor/core.js:3:3224
	trigger https://xxxxxx/core/vendor/core.js:3:5572
	a.event.trigger https://xxxxxx/core/vendor/core.js:7:7849
	trigger/< https://xxxxxx/core/vendor/core.js:3:11534
	each https://xxxxxx/core/vendor/core.js:2:2880
	each https://xxxxxx/core/vendor/core.js:2:845
	trigger https://xxxxxx/core/vendor/core.js:3:11513
	_notifyUpdateListeners https://xxxxxx/js/files/merged-index.js:8990:4
	registerAction https://xxxxxx/js/files/merged-index.js:9058:4
	register https://xxxxxx/js/files/merged-index.js:9017:11
	register https://xxxxxx/js/gallery/scripts-for-file-app.js:1310:5
	<anonymous> https://xxxxxx/js/gallery/scripts-for-file-app.js:1476:3
	then/</</< https://xxxxxx/core/vendor/core.js:2:28292
	j https://xxxxxx/core/vendor/core.js:2:26920
	fireWith https://xxxxxx/core/vendor/core.js:2:27738
	x https://xxxxxx/core/vendor/core.js:4:11251
	b/< https://xxxxxx/core/vendor/core.js:4:14765


```
</details>

### PR DESCRIPTION
**Pull request by MorrisJobke**
fixes #5696

@fauno Could you test this?

### CODE REVIEW

**Comment by fauno** [comment]
hey, sorry! i'll try to test it this week

File: tests/lib/Template/JSCombinerTest.php [hunk 1]
```diff
@@ -52,11 +55,14 @@ protected function setUp() {
...
 		$this->depsCache = $this->createMock(ICache::class);
+		$this->logger = $this->createMock(ILogger::class);
 		$this->jsCombiner = new JSCombiner(
 			$this->appData,
 			$this->urlGenerator,
 			$this->depsCache,
-			$this->config);
+			$this->config,
+			$this->logger
+		);
```
Comment (rullzer) [inline tests/lib/Template/JSCombinerTest.php]: If you have to touch the file you can also write a test @MorrisJobke! :wink:

**Review by rullzer — DISMISSED** [review]

File: tests/lib/Template/JSCombinerTest.php (hunk 1 above)
Comment (MorrisJobke) [inline tests/lib/Template/JSCombinerTest.php]: Done

**Review by nickvergessen — APPROVED** [review]

**Review by rullzer — APPROVED** [review]
