### PR TITLE
fix(dav): allow uploading of files with long filenames

### LINKED ISSUE #4046: failed to open stream: File name too long
### Steps to reproduce
1. Create file with name that is close to filesystem limit of 255 bytes (say 253 bytes)
2. Try to sync the file

### Expected behaviour
File is synchronized correctly

### Actual behaviour
File is not synchronized correctly because Nextcloud adds `.ocTransferId**********.part` suffix to the end of the file name and thus exceeds filesystem limit for the file name length.

### Additional details
I've got this long file name by synchronization of directory that contains eCryptfs data.

My local filesystem is btrfs, filesystem on server is ext4, both limited by 255 bytes for the filename.

Using completely random controllable filenames during uploading will solve issues like this once and forever.

### Server configuration
**Operating system**: Debian Jessie under Docker

**Web server:** Nginx 1.11.10

**Database:** MariaDB 10.1.22

**PHP version:** 7.0.17

**Nextcloud version:** 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** https://github.com/nazar-pc/docker-webserver-apps/tree/master/nextcloud

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{
	"reqId"      : "***",
	"remoteAddr" : "****",
	"app"        : "PHP",
	"message"    : "fopen(\/data\/nginx\/www\/data\/nazar\/files\/Nextcloud\/Encrypted\/ECRYPTFS_FNEK_ENCRYPTED.FWaZ3jSvM8HFIkYWHAexJ2WpOyhTopXGRhjBXNoIYclgjXbtIzBdPW1r8k--\/ECRYPTFS_FNEK_ENCRYPTED.FeaZ3jSvM8HFIkYWHAexJ2WpOyhTopXGRhjB38DwyoKD5SxcCU7QOetpI6bdC4EOd1t4q-voY-cm3NbMJ2sJEtsxmOvrVRdX1IdrLFx3J8LoIaSDFfhzfWsquuOO50JyIHM1MdNjfabjtgfLyVV1TQq-mzTV9MKUE8izTckfeMkVD.LjcKqy5s0A-FEVkxyosYAdqrxcmYoiFFgpf2amE6gmMW4J-mj6qG1x.ocTransferId1216630867.part): failed to open stream: File name too long at \/data\/nginx\/www\/lib\/private\/Files\/Storage\/Local.php#287",
	"level"      : 3,
	"time"       : "2017-03-24T19:28:36+00:00",
	"method"     : "MOVE",
	"url"        : "\/remote.php\/dav\/uploads\/nazar\/3759697667\/.file",
	"user"       : "nazar",
	"version"    : "11.0.2.7"
}
```
</details>

### LINKED ISSUE #24224: Support correctly long path or filename
### Steps to reproduce
1. Upload a file (desktop client) with a path of length 150 (for example Bibliography/VacuumLeaks/xxx where xxx is of length 138)

### Expected behaviour
The file should be correctly uploaded
### Actual behaviour
The GUI complains with the following error:
2020-11-03 14:23:31:820 [ warning nextcloud.gui.activity ]: Item “Bibliography/VacuumLeaks/xxxx” retrieved resulted in “File name too long”
### Server configuration

**Operating system:**
Ubuntu 20.04 (also tested with 18.04)
**Web server:**
nginx version: nginx/1.18.0 (Ubuntu)
**Database:**
mysqld 10.3.25-MariaDB-0ubuntu0.20.04.1
**PHP version:**
7.4 (also 7.2 tested)
**Nextcloud version:** (see Nextcloud admin page)
19.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated
**Where did you install Nextcloud from:**
Website of Nextcloud
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.1
  - admin_audit: 1.9.0
  - calendar: 2.0.4
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.4.1
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - encryption
  - files_accesscontrol-disabled
  - files_external
  - groupfolders
  - richdocuments_old
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "\/data\/default_data",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "19.0.4.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "timeout": 1.5
        },
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
N/A
**Operating system:**
Win 10
### Logs

2020-11-03 14:23:31:820 [ warning nextcloud.gui.activity ]: Item “Bibliography/VacuumLeaks/xxxx” retrieved resulted in “File name too long”

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: https://github.com/nextcloud/server/issues/24224
* Resolves https://github.com/nextcloud/server/issues/4046

## Summary
 A filename must be less or equal 255 characters, but when adding the
`.part` and `.ocfiletransfer` extensions we might overflow this limit.
So we should also use filename hashes for uploading when the file has a
long filename, similar like when we are uploading to the user storage directly.

## TODO

- [ ] discuss if it makes sense to align `oc_filecache.name`. Meaning to increase it from 250 to 255. cc @icewind1991 

### Before
Bildschirmfoto_20250315_135643

### After
Bildschirmfoto_20250315_135602

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/dav/lib/Connector/Sabre/File.php [hunk 1]
```diff
@@ -377,9 +379,21 @@ public function put($data) {
...
+			$filename = basename($path);
+			// length in bytes NOT characters
+			$filenameLength = strlen($filename);
+			// check if filename (with transfer id and part extension) overflows the filesystem limit of 255 BYTES
+			// 255 - strlen('.ocTransferId') - strlen('.part') - strlen((string)getrandmax())
+			if ($filenameLength >= 225) {
+				// hash does not need to be secure but fast and semi unique
+				$filename = hash('xxh128', $filename);
+				return substr($path, 0, strlen($path) - $filenameLength) . $filename;
+			}
```
Comment (provokateurin) [inline apps/dav/lib/Connector/Sabre/File.php:391]: Why not hash it all the time? Then there is one code path less to worry about and in this case where a magic constant (not calculated, but at least documented) is used, this would make a lot of sense.

File: build/integration/dav_features/dav-v2.feature [hunk 2]
```diff
@@ -103,32 +103,41 @@ Feature: dav-v2
...
 		When User "user0" uploads file "data/textfile.txt" to "/testquota/asdf.txt"
 		Then the HTTP status code should be "201"
 
+	Scenario: Uploading a file with very long filename
+		Given using new dav path
+		And As an "admin"
+		And user "user0" exists
+		And user "user0" has a quota of "10 MB"
+		And As an "user0"
+		When User "user0" uploads file "data/textfile.txt" to "/long-filename-with-250-characters-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.txt"
```
Comment (provokateurin) [inline build/integration/dav_features/dav-v2.feature:117]: Why 250 and not 255?
It would also be nice to have a test that uploads a file with a name that is actually too long.

**Review by provokateurin — COMMENTED** [review]
LGTM, just one idea to make it even better.

File: build/integration/dav_features/dav-v2.feature (hunk 2 above)
Comment (susnux) [reply build/integration/dav_features/dav-v2.feature:117]: > Why 250 and not 255?

See discussion above: Our database was limited to 250 instead of 255 :see_no_evil:

File: apps/dav/lib/Connector/Sabre/File.php (hunk 1 above)
Comment (susnux) [reply apps/dav/lib/Connector/Sabre/File.php:391]: Makes sense for me :+1:

Comment (susnux) [reply apps/dav/lib/Connector/Sabre/File.php]: done.

File: apps/dav/lib/Connector/Sabre/File.php [hunk 3]
```diff
@@ -129,8 +129,10 @@ public function put($data) {
 		$view = Filesystem::getView();
 
 		if ($needsPartFile) {
+			// use hex numbers to reduce length of the id
+			$transferId = \dechex(\rand());
```
Comment (provokateurin) [inline apps/dav/lib/Connector/Sabre/File.php:133]: This should not be needed anymore, right? Then I'd prefer if it stays like before since that was working just fine.

File: apps/dav/lib/Connector/Sabre/File.php [hunk 4]
```diff
@@ -383,9 +379,16 @@ public function put($data) {
 	private function getPartFileBasePath($path) {
 		$partFileInStorage = Server::get(IConfig::class)->getSystemValue('part_file_in_storage', true);
 		if ($partFileInStorage) {
-			return $path;
+			$filename = basename($path);
+			// length in bytes NOT characters
+			$filenameLength = strlen($filename);
+			// hash does not need to be secure but fast and semi unique
+			$filename = hash('xxh128', $filename);
+			return substr($path, 0, strlen($path) - $filenameLength) . $filename;
```
Comment (provokateurin) [inline apps/dav/lib/Connector/Sabre/File.php:387]: I'm not sure what this substr is supposed to do. This looks to me like you can force an arbitrary path by providing long file names. Also this seems to mix the length of the original file name and then appends the hashed one.

File: apps/dav/lib/Connector/Sabre/File.php (hunk 3 above)
Comment (susnux) [reply apps/dav/lib/Connector/Sabre/File.php:133]:
```suggestion
			$transferId = \rand();
```

File: apps/dav/lib/Connector/Sabre/File.php (hunk 4 above)
Comment (susnux) [reply apps/dav/lib/Connector/Sabre/File.php:386]: We are hashing the filename.
```
$input = '/some/path/file.ext`
$output = `/some/path/HASH`
```

File: apps/dav/lib/Connector/Sabre/File.php [hunk 5]
```diff
@@ -383,9 +378,16 @@ public function put($data) {
...
```
Comment (susnux) [inline apps/dav/lib/Connector/Sabre/File.php:386]:
```suggestion
			$filename = basename($path);
			// hash does not need to be secure but fast and semi unique
			$hasedFilename = hash('xxh128', $filename);
			return substr($path, 0, strlen($path) - strlen($filename)) . $hashedFilename;
```

File: apps/dav/lib/Connector/Sabre/File.php (hunk 4 above)
Comment (susnux) [reply apps/dav/lib/Connector/Sabre/File.php]: adjusted :white_check_mark:

File: build/integration/dav_features/dav-v2.feature [hunk 6]
```diff
@@ -108,6 +108,24 @@ Feature: dav-v2
...
```
Comment (provokateurin) [inline build/integration/dav_features/dav-v2.feature:117]:
```suggestion
		When User "user0" uploads file "data/textfile.txt" to "/long-filename-with-255-characters-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.txt"
```
This should work now

File: apps/dav/lib/Connector/Sabre/File.php [hunk 7]
```diff
@@ -383,9 +378,14 @@ public function put($data) {
 	private function getPartFileBasePath($path) {
 		$partFileInStorage = Server::get(IConfig::class)->getSystemValue('part_file_in_storage', true);
 		if ($partFileInStorage) {
-			return $path;
+			$filename = basename($path);
+			// hash does not need to be secure but fast and semi unique
+			$hasedFilename = hash('xxh128', $filename);
```
Comment (susnux) [inline apps/dav/lib/Connector/Sabre/File.php:383]:
```suggestion
			$hashedFilename = hash('xxh128', $filename);
```

File: build/integration/dav_features/dav-v2.feature (hunk 6 above)
Comment (provokateurin) [reply build/integration/dav_features/dav-v2.feature:117]: Mh ok, but can you then change the other test to test 251 bytes? So we have two tests that check for the exact limit above and below?

File: build/integration/dav_features/dav-v2.feature [hunk 8]
```diff
@@ -108,6 +108,24 @@ Feature: dav-v2
...
+		Then the HTTP status code should be "201"
+
+	Scenario: Uploading a file with a too long filename
+		Given using new dav path
+		And As an "admin"
+		And user "user0" exists
+		And user "user0" has a quota of "10 MB"
+		And As an "user0"
+		When User "user0" uploads file "data/textfile.txt" to "/long-filename-with-256-characters-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.txt"
```
Comment (susnux) [inline build/integration/dav_features/dav-v2.feature:126]:
```suggestion
		When User "user0" uploads file "data/textfile.txt" to "/long-filename-with-251-characters-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.txt"
```

**Review by come-nc — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Review by provokateurin — APPROVED** [review]
