### PR TITLE
Fix too many file download notifications when watching a video

### LINKED ISSUE #352: Shared videos count multiple times
### Steps to reproduce
1. Share video with public link
2. Click on that link
3. Look at activitys

### Expected behaviour
Should show that it was watched once

### Actual behaviour
For me, it shows 3 times downloaded, even tough it was only 1 person clicking on the link

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache2

**Database:** MySQL

**PHP version:**Php7.2

**Nextcloud version:** Newest 15.0.5

**Where did you install Nextcloud from:** Official nextcloud page

List of activated apps: https://pastebin.com/KknLGgD4

Config: https://pastebin.com/dcf5TZGw

### LINKED ISSUE #519: Hundreds of notifications when a shared video is played in the browser
### Steps to reproduce
1. Enable public link download notifications
2. Upload an iPhone video to Nextcloud, so that it ends up with the .mov extension. Share it via public link
3. Go to the public link
4. Play the video
5. Look at all the notifications and have an aneurysm

### Expected behaviour
A single notification should be sent, or maybe one when the user visits and another one when they actually download the file

### Actual behaviour
I get a notification that the file is being downloaded when I visit the link, then immediately another notification that just says “Nextcloud notification”, and then another one that the file is being downloaded. All before playing the video.

Once you press the play button... I start getting about 20 notifications a second, some of them saying the file is being downloaded and others just saying “Nextcloud notification” for some reason.

### Server configuration

**Operating system**: Linux (Docker)

**Web server:** Not sure

**Database:** MySQL (MariaDB) 10.5.5

**PHP version:** 7.3.2.3

**Nextcloud version:** (see Nextcloud admin page) 20.0.0

**Where did you install Nextcloud from:** Docker

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```

Enabled:
  - activity: 2.13.1
  - bruteforcesettings: 2.0.1
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - dav: 1.16.0
  - federatedfilesharing: 1.10.1
  - files: 1.15.0
  - files_downloadactivity: 1.9.0
  - files_external: 1.11.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - notes: 4.0.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.0
  - provisioning_api: 1.10.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_nextcloud_notification: 3.0.0
  - twofactor_totp: 5.0.0
  - updatenotification: 1.10.0
  - user_status: 1.0.0
  - viewer: 1.4.0
  - workflowengine: 2.2.0
Disabled:
  - accessibility
  - admin_audit
  - dashboard
  - encryption
  - federation
  - firstrunwizard
  - nextcloud_announcements
  - privacy
  - recommendations
  - sharebymail
  - support
  - survey_client
  - systemtags
  - tasks
  - user_ldap
  - weather_status
```

**Nextcloud configuration:**

```
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.***.com"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.0.9",
        "overwrite.cli.url": "https:\/\/nextcloud.***.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable"
    },
    "apps": {
        "accessibility": {
            "enabled": "no",
            "installed_version": "1.2.0",
            "types": ""
        },
        "activity": {
            "enable_email": "no",
            "enabled": "yes",
            "installed_version": "2.13.1",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "1982"
        },
        "bruteForce": {
            "whitelist_1": "*.*.*.*\/0"
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "2.0.1",
            "types": ""
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "logging"
        },
        "contactsinteraction": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "dav"
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "enterpriseLogoChecked": "yes",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1568505563.6541",
            "lastcron": "1602817500",
            "lastupdateResult": "[]",
            "lastupdatedat": "1602816663",
            "oc.integritycheck.checker": "[]",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "shareapi_exclude_groups": "no",
            "shareapi_exclude_groups_list": "[\"\"]",
            "shareapi_only_share_with_group_members": "no",
            "theming.variables": "f2b95d7611988ad39c523e206a9126ac",
            "updater.secret.created": "1602789790",
            "vendor": "nextcloud"
        },
        "dashboard": {
            "enabled": "no",
            "installed_version": "7.0.0",
            "types": ""
        },
        "dav": {
            "buildCalendarReminderIndex": "yes",
            "buildCalendarSearchIndex": "yes",
            "chunks_migrated": "1",
            "enabled": "yes",
            "installed_version": "1.16.0",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "types": "filesystem"
        },
        "deck": {
            "enabled": "no",
            "installed_version": "0.6.6",
            "types": "dav"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.10.1",
            "types": ""
        },
        "federation": {
            "enabled": "no",
            "installed_version": "1.6.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.15.0",
            "types": "filesystem"
        },
        "files_downloadactivity": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": "filesystem"
        },
        "files_external": {
            "enabled": "yes",
            "installed_version": "1.11.1",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "2.0.1",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "0.17.0",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "no",
            "installed_version": "2.14.0",
            "types": ""
        },
        "files_trackdownloads": {
            "enabled": "no",
            "installed_version": "1.9.0",
            "types": "filesystem"
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.10.1",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "no",
            "installed_version": "2.5.0",
            "types": "logging"
        },
        "gallery": {
            "enabled": "no",
            "installed_version": "18.4.0",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.5.0",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "authentication"
        },
        "nextcloud_announcements": {
            "enabled": "no",
            "installed_version": "1.5.0",
            "pub_date": "Mon, 02 Sep 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notes": {
            "enabled": "yes",
            "installed_version": "4.0.0",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.8.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.10.1",
            "types": "authentication"
        },
        "photos": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "privacy": {
            "enabled": "no",
            "installed_version": "1.0.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "prevent_group_restriction"
        },
        "recommendations": {
            "enabled": "no",
            "installed_version": "0.4.0",
            "types": ""
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": ""
        },
        "settings": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "no",
            "installed_version": "1.6.0",
            "types": "filesystem"
        },
        "spreed": {
            "enabled": "no",
            "installed_version": "6.0.4",
            "signaling_ticket_secret": "***REMOVED SENSITIVE VALUE***",
            "stun_servers": "***REMOVED SENSITIVE VALUE***",
            "types": "prevent_group_restriction"
        },
        "support": {
            "enabled": "no",
            "installed_version": "1.0.0",
            "types": ""
        },
        "survey_client": {
            "enabled": "no",
            "installed_version": "1.4.0",
            "types": ""
        },
        "systemtags": {
            "enabled": "no",
            "installed_version": "1.6.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "no",
            "installed_version": "0.13.4",
            "types": ""
        },
        "text": {
            "enabled": "yes",
            "installed_version": "3.1.0",
            "types": "dav"
        },
        "theming": {
            "cachebuster": "18",
            "color": "#0098EB",
            "enabled": "yes",
            "faviconMime": "image\/png",
            "installed_version": "1.11.0",
            "logoMime": "image\/png",
            "logoheaderMime": "image\/png",
            "name": "\u00fc",
            "slogan": "***REMOVED SENSITIVE VALUE***",
            "types": "logging",
            "url": "***REMOVED SENSITIVE VALUE***"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": ""
        },
        "twofactor_nextcloud_notification": {
            "enabled": "yes",
            "installed_version": "3.0.0",
            "***_enabled": "1",
            "***_enabled": "1",
            "***": ""
        },
        "twofactor_totp": {
            "enabled": "yes",
            "installed_version": "5.0.0",
            "types": ""
        },
        "updatenotification": {
            "core": "18.0.10.2",
            "enabled": "yes",
            "files_rightclick": "0.15.1",
            "installed_version": "1.10.0",
            "types": "",
            "update_check_errors": "0"
        },
        "uploaddetails": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "types": ""
        },
        "user_status": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "weather_status": {
            "enabled": "no",
            "installed_version": "1.0.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "2.2.0",
            "types": "filesystem"
        }
    }
}
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** All

**Operating system:** All

#### Nextcloud log (data/nextcloud.log)
```
No new messages when this happens
```

#### Browser log

### PR DESCRIPTION
**Pull request by szaimen**
Fix https://github.com/nextcloud/activity/issues/519
Fix https://github.com/nextcloud/activity/issues/352

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by szaimen** [comment]
I think the failing test is unrelated

**Comment by szaimen** [comment]
I think the failing test is unrelated

File: apps/files_sharing/lib/Activity/Providers/Downloads.php [hunk 1]
```diff
@@ -63,16 +63,17 @@ public function parseShortVersion(IEvent $event) {
...
 	 * @since 11.0.0
 	 */
-	public function parseLongVersion(IEvent $event) {
+	public function parseLongVersion(IEvent $event, IEvent $previousEvent = null) {
 		$parsedParameters = $this->getParsedParameters($event);
 
 		if ($event->getSubject() === self::SUBJECT_PUBLIC_SHARED_FILE_DOWNLOADED ||
 			$event->getSubject() === self::SUBJECT_PUBLIC_SHARED_FOLDER_DOWNLOADED) {
-			$subject = $this->l->t('{file} downloaded via public link');
+			$subject = $this->l->t('{file} downloaded via public link from {remote-address}');
```
Comment (nickvergessen) [inline apps/files_sharing/lib/Activity/Providers/Downloads.php:76]: This breaks on updates. Old translation and syntax needs to be retained and the parameters must be counted to decide which way to use

File: apps/files_sharing/lib/Controller/ShareController.php [hunk 2]
```diff
@@ -712,8 +713,10 @@ protected function singleFileDownloaded(Share\IShare $share, \OCP\Files\Node $no
 		} else {
 			if ($node instanceof \OCP\Files\File) {
 				$subject = Downloads::SUBJECT_PUBLIC_SHARED_FILE_DOWNLOADED;
+				$parameters[] = $remoteAddress;
```
Comment (nickvergessen) [inline apps/files_sharing/lib/Controller/ShareController.php:716]: I heavily dislike this. It logs ip addresses in a user accessible way (hello gdpr/dsgvo) before ips are only in sysadmin logs.

**Review by nickvergessen — CHANGES_REQUESTED** [review]

File: apps/files_sharing/lib/Controller/ShareController.php (hunk 2 above)
Comment (szaimen) [reply apps/files_sharing/lib/Controller/ShareController.php:716]: Yes, actually, this was the whole idea of this PR. So removing it again will make this PR probably useless...

Comment (szaimen) [reply apps/files_sharing/lib/Controller/ShareController.php:716]: I'd like to discuss whether it could be possible to do this nonetheless in a dsgvo conform way.
My argumentation would be based on the idea that you as owner of your files would want to know who is accessing your files via a public link because you might would act accordingly if there are e.g. too many addresses that access the shared file.

Comment (szaimen) [reply apps/files_sharing/lib/Controller/ShareController.php:716]: Is there maybe a way to anonymize the ip address in a way where it can still be used to identify how many/from where the remote PC comes? any idea?

File: apps/files_sharing/lib/Activity/Providers/Downloads.php (hunk 1 above)
Comment (szaimen) [reply apps/files_sharing/lib/Activity/Providers/Downloads.php:76]: How do I do that? do you have an example code where I can see what you suggest here?

File: apps/files_sharing/lib/Controller/ShareController.php (hunk 2 above)
Comment (Pytal) [reply apps/files_sharing/lib/Controller/ShareController.php:716]: @LukasReschke

Comment (szaimen) [reply apps/files_sharing/lib/Controller/ShareController.php:716]: I was thinking about anonymizing the ip-addresses like e.g. done here https://complianz.io/are-your-ip-addresses-anonymized/#:~:text=how%20anonymizing%20ip%20addresses%20works
What do you think?

File: apps/files_sharing/lib/Activity/Providers/Downloads.php (hunk 1 above)
Comment (szaimen) [reply apps/files_sharing/lib/Activity/Providers/Downloads.php]: I think I found a way to do it. please have a look again

File: apps/files_sharing/lib/Controller/ShareController.php (hunk 2 above)
Comment (szaimen) [reply apps/files_sharing/lib/Controller/ShareController.php]: I've now added an appvalue which disables this by default. I hope this solves the need to implement the feature in a dsgvo conform way. If it should still needed, I think the best approach would be anonymizing the ip addresses as said before.

**Review by skjnldsv — APPROVED** [review]

File: apps/files_sharing/lib/Controller/ShareController.php [hunk 3]
```diff
@@ -699,6 +699,9 @@ protected function singleFileDownloaded(Share\IShare $share, \OCP\Files\Node $no
 		$ownerFolder = $this->rootFolder->getUserFolder($share->getShareOwner());
 		$userPath = $userFolder->getRelativePath($userNode->getPath());
 		$ownerPath = $ownerFolder->getRelativePath($node->getPath());
+		if ($this->config->getAppValue('files_sharing', 'download_ip_address_activity', '0') === "1") {
```
Comment (juliushaertl) [inline apps/files_sharing/lib/Controller/ShareController.php:702]: Should be documented somewhere

File: lib/public/RichObjectStrings/Definitions.php [hunk 4]
```diff
@@ -511,6 +511,25 @@ class Definitions {
 				],
 			],
 		],
+		'remote-address' => [
+			'author' => 'Nextcloud',
+			'app' => 'files_sharing',
```
Comment (juliushaertl) [inline lib/public/RichObjectStrings/Definitions.php:516]:
```suggestion
			'app' => 'core',
```

**Comment by szaimen** [comment]
Lets wait with this for a second review of @nickvergessen but I'd honestly rather remove the configuration value again because ip-addresses get anonymized now which is hopefully a vaild approach on the dsgvo concerns that nickvergessen had.

File: apps/files_sharing/lib/Controller/ShareController.php (hunk 2 above)
Comment (szaimen) [reply apps/files_sharing/lib/Controller/ShareController.php]: I've also added ip-anonymization and would like to remove the config option again.

**Comment by kesselb** [comment]
> Some input from kesselb starting here and below https://cloud.nextcloud.com/call/wejc2q9q#message_771871

To summarize my input: 

A. Good to fix notification spam when a user plays a video
B. Fine by me to show the ip address for a download / play

But A and B should be independent of each other. My approach for A would be to extend the event merger with a generic way to compare one event with another. I would try to add a new method to IEvent that accepts an callable. Event merger check do we have a callable to compare the events. Probably a bit nice would be an additional interface and a decorator for IEvent.

**Comment by wagnbeu0** [comment]
So my current setup is to anonymize the IP Adresses in Apache itself by changing the last ipv4 digits to 0. Can this have an impact on this app?

**Comment by kemoantemo** [comment]
Why is this not implemented until now?

File: apps/files_sharing/lib/Controller/ShareController.php (hunk 2 above)
Comment (szaimen) [reply apps/files_sharing/lib/Controller/ShareController.php]: changed the implementation to only fix the bug

File: lib/public/RichObjectStrings/Definitions.php (hunk 4 above)
Comment (szaimen) [reply lib/public/RichObjectStrings/Definitions.php]: not needed anymore

File: apps/files_sharing/lib/Controller/ShareController.php [hunk 5]
```diff
@@ -712,8 +716,14 @@ protected function singleFileDownloaded(Share\IShare $share, \OCP\Files\Node $no
 		} else {
 			if ($node instanceof \OCP\Files\File) {
 				$subject = Downloads::SUBJECT_PUBLIC_SHARED_FILE_DOWNLOADED;
+				if (isset($remoteAddressHash)) {
```
Comment (nickvergessen) [inline apps/files_sharing/lib/Controller/ShareController.php:719]: isset should not be needed? It can never not be there. It's always an md5 of something?

File: apps/files_sharing/lib/Controller/ShareController.php [hunk 6]
```diff
@@ -712,8 +716,14 @@ protected function singleFileDownloaded(Share\IShare $share, \OCP\Files\Node $no
...
+					$parameters[] = $remoteAddressHash;
+				}
 			} else {
 				$subject = Downloads::SUBJECT_PUBLIC_SHARED_FOLDER_DOWNLOADED;
+				if (isset($remoteAddressHash)) {
+					$parameters[] = $remoteAddressHash;
+				}
```
Comment (nickvergessen) [inline apps/files_sharing/lib/Controller/ShareController.php:726]:
```suggestion
				$parameters[] = $remoteAddressHash;
```

File: apps/files_sharing/lib/Controller/ShareController.php [hunk 7]
```diff
@@ -712,8 +716,14 @@ protected function singleFileDownloaded(Share\IShare $share, \OCP\Files\Node $no
 		} else {
 			if ($node instanceof \OCP\Files\File) {
 				$subject = Downloads::SUBJECT_PUBLIC_SHARED_FILE_DOWNLOADED;
+				if (isset($remoteAddressHash)) {
+					$parameters[] = $remoteAddressHash;
+				}
```
Comment (nickvergessen) [inline apps/files_sharing/lib/Controller/ShareController.php:721]:
```suggestion
				$parameters[] = $remoteAddressHash;
```

isset should not be needed? It can never not be there. It's always an md5 of something?

**Review by nickvergessen — APPROVED** [review]

File: apps/files_sharing/lib/Controller/ShareController.php (hunk 6 above)
Comment (szaimen) [reply apps/files_sharing/lib/Controller/ShareController.php:726]: right, psalm said the same thing :D

File: apps/files_sharing/lib/Controller/ShareController.php (hunk 7 above)
Comment (szaimen) [reply apps/files_sharing/lib/Controller/ShareController.php:721]: right, psalm said the same thing :D

File: apps/files_sharing/lib/Controller/ShareController.php (hunk 6 above)
Comment (szaimen) [reply apps/files_sharing/lib/Controller/ShareController.php]: fixed

File: apps/files_sharing/lib/Controller/ShareController.php (hunk 7 above)
Comment (szaimen) [reply apps/files_sharing/lib/Controller/ShareController.php]: fixed

**Review by Pytal — APPROVED** [review]

**Comment by szaimen** [comment]
/rebase for checking if all checks pass
