### PR TITLE
Escape the name for the jquery selector

### LINKED ISSUE #2942: Double quotes in folder name creates display problem
### Steps to reproduce
1. In your file browser, inside a synchronised folder, Create a subfolder named 1-NormalName
2. Create a subfolder named 2-Name"With"Quotes
3. Create a subfolder named 3-OtherNormalName
4. Let your folder get synhronized
5. Open the folder in your web browser
### Expected behaviour
The three subfolders should be displayed

### Actual behaviour
Only the first subfolder is displayed
Please see attached screenshots
nautilusafter
nautilusbefore
webafter
webbefore

### Server configuration
**Operating system**:

**Web server:**

**Database:**
Type: mysql
Version: 10.0.28
**PHP version:**
Version: 5.6.28
**Nextcloud version:** (see Nextcloud admin page)
11.0.0 (stable)
**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**
Installed at owncube.com
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Firefox 50.1.0
**Operating system:**
Ubuntu 16.04 LTS
#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

### PR DESCRIPTION
**Pull request by nickvergessen**
Copied the method from [OCA.External.StatusManager](https://github.com/nextcloud/server/blob/b12db1b494376dc6ae35c11d127b35f3a156a97e/apps/files_external/js/statusmanager.js#L596-L602)
Not sure where the old code was from.

Fix https://help.nextcloud.com/t/nc11-files-missing-from-gui-but-available-on-disk-and-in-shared-link/6434/9

@rullzer @LukasReschke 

Fix #2942

Should backport to 11

### CODE REVIEW

File: apps/files/js/filelist.js [hunk 1]
```diff
@@ -1175,7 +1175,7 @@
 			var innernameSpan = $('<span></span>').addClass('innernametext').text(basename);
 
 			if (path && path !== '/') {
-				var conflictingItems = this.$fileList.find('tr[data-file="' + name.replace( /(:|\.|\[|\]|,|=)/g, "\\$1") + '"]');
+				var conflictingItems = this.$fileList.find('tr[data-file="' + this._jqSelEscape(name) + '"]');
```
Comment (nickvergessen) [inline apps/files/js/filelist.js]: I just noticed, that if you have two favorites `test/foo"bar.txt` and `other/foo"bar.txt` they don't show the path.

@nextcloud/javascript any idea what's wrong?

**Comment by blizzz** [comment]
> Copied the method from OCA.External.StatusManager

Code duplication?

**Review by blizzz — COMMENTED** [review]
Would prefer to  have a consolidated method and not copy it around to  various places.

It works however.

**Comment by nickvergessen** [comment]
@ChristophWurst can you take a look? We should really fix this for 11.0.1

**Review by ChristophWurst — APPROVED** [review]
tested and works

**Review by MorrisJobke — APPROVED** [review]
Tested and works
