### PR TITLE
Add DAV repair step to fix calendar data

### LINKED ISSUE #2264: Fix invalid VCALENDAR data in DB!
As described in https://github.com/nextcloud/server/issues/2249

If we have invalid data in the DB this might fail at some point. We should fix the invalid VCALENDAR data properly!

### PR DESCRIPTION
**Pull request by rullzer**
Should fix #2264

We add a live repair step to revalidate all calendar entries. Because some might have invalid vcard data in them.

@MorrisJobke @LukasReschke as discussed.

### CODE REVIEW

File: apps/dav/tests/unit/Migration/ValueFixTest.php [hunk 1]
```diff
@@ -0,0 +1,200 @@
...
+TRANSP:OPAQUE
+DTEND;VALUE=:20151223T223000Z
+LAST-MODIFIED:20151214T091032Z
+ORGANIZER;CN="User 1":mailto:user1@example.com
+UID:1234567890@example.com
+DTSTAMP:20151214T091032Z
+STATUS:CONFIRMED
+SEQUENCE:0
+SUMMARY:Ein Geburtstag 
+DTSTART:20151223T173000Z
```
Comment (nickvergessen) [inline apps/dav/tests/unit/Migration/ValueFixTest.php]: break here and on CREATED as well?

Comment (rullzer) [inline apps/dav/tests/unit/Migration/ValueFixTest.php]: You mean replace with `DTSTART;VALUE=:20151223T173000Z` ?

Comment (rullzer) [inline apps/dav/tests/unit/Migration/ValueFixTest.php]: Well basically the `;VALUE=:` is just invalid. (Type hinting can go on almost any field). The regex is simple and just replaces that.

I can add it to DTSTART as well if you prefer

Comment (rullzer) [inline apps/dav/tests/unit/Migration/ValueFixTest.php]: Done

File: apps/dav/lib/Migration/ValueFixInsert.php [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+		$this->userManager = $userManager;
+		$this->jobList = $jobList;
+	}
+
+	public function getName() {
+		return 'Insert ValueFix background job for each user';
+	}
+
+	public function run(IOutput $output) {
+		$this->userManager->callForSeenUsers(function (IUser $user) {
```
Comment (MorrisJobke) [inline apps/dav/lib/Migration/ValueFixInsert.php]: Could you add a check, that this is only done once? Otherwise on every minor upgrade this is re-inserted.

**Review by MorrisJobke — DISMISSED** [review]

File: apps/dav/lib/Migration/ValueFixInsert.php (hunk 2 above)
Comment (rullzer) [inline apps/dav/lib/Migration/ValueFixInsert.php]: Done

**Comment by MorrisJobke** [comment]
I inserted following event into the calendar:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Apple Inc.//Mac OS X 10.11.2//EN
CALSCALE:GREGORIAN
BEGIN:VEVENT
TRANSP:OPAQUE
DTEND;VALUE=:20151223T223000Z
LAST-MODIFIED:20151214T091032Z
ORGANIZER;CN="User 1":mailto:user1@example.com
UID:1234567890@example.com
DTSTAMP:20151214T091032Z
STATUS:CONFIRMED
SEQUENCE:0
SUMMARY:Ein Geburtstag 
DTSTART:20151223T173000Z
X-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC
CREATED:20151214T091032Z
END:VEVENT
END:VCALENDAR
```

Then did an `./occ upgrade` and ran the cron job multiple times `php cron.php` afterwards the calendar is still throwing the error.

@rullzer Any ideas?

**Comment by rullzer** [comment]
@MorrisJobke mmm maybe something else is still broken. I'll have a look soon.

**Comment by rullzer** [comment]
@MorrisJobke I can't reproduce that.

What I did:

1. Install stable10
2. Upload file to <server>/remote.php/dav/calendars/<user>/personal
3. Checkout branch
4. `./occ up`
5. `php cron.php` (few times)
6. In calendar go to December 2015
7. No :boom:

**Comment by LukasReschke** [comment]
@rullzer  Can we move that to 12? I'd prefer to consider 11 closed for any non-critical merges.

**Comment by rullzer** [comment]
Uhm. We'll sure as we mitigated the upgrade bug. But not having this means some people can still have invalid data in the db.

But fine by me

**Comment by rullzer** [comment]
@MorrisJobke lets get this in. Then we can take a look at your issue separatly

@nickvergessen @LukasReschke good to go from you?

**Review by MorrisJobke — APPROVED** [review]
At least fixes some cases 👍

**Review by LukasReschke — APPROVED** [review]

**Comment by rullzer** [comment]
Stable11 in #2807
