### PR TITLE
fix(imip): dont compare events for the reply message

### LINKED ISSUE #6701: Changes by attendee propagating to organiser
### Steps to reproduce

1. Create event as user1
2. Invite User 2
3. Login as User 2
4. Change date 
5. Accept event

### Expected behavior

User1 get a notification that only mentions the attendance status

### Actual behavior

Image

### Calendar app version

_No response_

### CalDAV-clients used

_No response_

### Browser

_No response_

### Client operating system

_No response_

### Server operating system

_No response_

### Web server

None

### Database engine version

None

### PHP engine version

None

### Nextcloud version

_No response_

### Updated from an older installed version or fresh install

None

### List of activated apps

```Text

```

### Nextcloud configuration

```Text

```

### Web server error log

```Text

```

### Log file

```Text

```

### Browser log

```Text

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by hamza221**
* Resolves: https://github.com/nextcloud/calendar/issues/6701
## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/dav/lib/CalDAV/Schedule/IMipPlugin.php [hunk 1]
```diff
@@ -185,7 +185,8 @@ public function schedule(Message $iTipMessage) {
 		switch (strtolower($iTipMessage->method)) {
 			case self::METHOD_REPLY:
 				$method = self::METHOD_REPLY;
-				$data = $this->imipService->buildBodyData($vEvent, $oldVevent);
+				$organizerEvent = $this->imipService->getOrganizerVEvent($vEvent->uid, $iTipMessage->recipient);
```
Comment (SebastianKrupinski) [inline apps/dav/lib/CalDAV/Schedule/IMipPlugin.php:188]: Hey, you can't just pull the event by the recipient, This will fail, for external organizers

**Comment by hamza221** [comment]
@SebastianKrupinski would it make sense to keep this even that it only works if the organiser is a local user? 
I mean check if he is and search for the event. Sent potentially wrong message in the other case? Would be better than nothing no ?

**Comment by SebastianKrupinski** [comment]
> @SebastianKrupinski would it make sense to keep this even that it only works if the organiser is a local user? I mean check if he is and search for the event. Sent potentially wrong message in the other case? Would be better than nothing no ?

I don't think having different code paths for internal and external attendees is a good idea, just makes it too complex, the only thing I would keep is the separate method for the reply message, as the reply does not need event comparison, and all the extra information that is normally generate

**Review by SebastianKrupinski — APPROVED** [review]

**Review by st3iny — APPROVED** [review]
Tested and works.
