### PR TITLE
fix: Add command to update re-share if shared-by user has been revoked

### LINKED ISSUE #42407: [Bug]: Sub folder shares were broken on ownership transfer
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After an ownership transfer (via the web interface), sub shares can be broken and it's impossible to restore.

### Steps to reproduce

- userA shares a folder D1 with userB
- userB creates and shares a subfolder D2 and shares it with userC
- userA revoke the share of D1 with userB
- userA transfers ownership of D1 to userD

After userD accepts the transfer:
- userC loses access to the folder D2
- if userD tries to share the folder D2 with userC : error message "Node for share not found, fileid: 132472"

### Expected behavior

My suggestion for expected behavior:
Re-share should be deleted if restore failed to not block creating new share for the same user.

### Installation method

Community Docker image

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by luka-nextcloud**
* Resolves: #42407

## Summary
Add command `occ sharing:fix-broken-shares` to fix the shares that were broken on transfer ownership.

## Checklist

- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: lib/private/Share20/Manager.php [hunk 1]
```diff
@@ -273,6 +273,12 @@ protected function generalCreateChecks(IShare $share) {
 		// And you cannot share your rootfolder
 		if ($this->userManager->userExists($share->getSharedBy())) {
 			$userFolder = $this->rootFolder->getUserFolder($share->getSharedBy());
+
+			// Share record of SharedBy user has been revoked or deleted
+			if (empty($userFolder->getById($share->getNode()->getId()))) {
+				$userFolder = $this->rootFolder->getUserFolder($share->getShareOwner());
+				$share->setSharedBy($share->getShareOwner());
+			}
```
[the remark this answers is not in the document]
Comment (luka-nextcloud) [reply lib/private/Share20/Manager.php:281]: I don't think deleting all shares of whole re-share hierarchy is a good approach. It might cause performance issue if sharing item is a folder that has a lot of children. So, I will come up with another fix.

**Comment by luka-nextcloud** [comment]
@artonge I've updated as you requested, please check again.

**Review by artonge — COMMENTED** [review]
Can you add comments to clarify what each `if` group does?

I am also wondering if we could find this shares with the following query:

```sql
SELECT
	f.fileid,
	f.path,
	f.storage,
	s.id as share_id,
	s.uid_owner as share_owner,
	s.uid_initiator as share_initiator,
	s.share_with as share_recipient
FROM
	oc_filecache f
	JOIN oc_share s ON f.fileid = s.file_source
	AND s.uid_initiator NOT IN (
		SELECT
			user_id
		FROM
			oc_mounts m
		WHERE
			f.storage = m.storage_id
	)
```

If so, then we could have a background job to remove them every hour or so like https://github.com/nextcloud/server/blob/master/apps/files_sharing/lib/DeleteOrphanedSharesJob.php, which might be easier than the current solution.

**Comment by luka-nextcloud** [comment]
> Can you add comments to clarify what each `if` group does?
> 
> I am also wondering if we could find this shares with the following query:
> 
> ```sql
> SELECT
> 	f.fileid,
> 	f.path,
> 	f.storage,
> 	s.id as share_id,
> 	s.uid_owner as share_owner,
> 	s.uid_initiator as share_initiator,
> 	s.share_with as share_recipient
> FROM
> 	oc_filecache f
> 	JOIN oc_share s ON f.fileid = s.file_source
> 	AND s.uid_initiator NOT IN (
> 		SELECT
> 			user_id
> 		FROM
> 			oc_mounts m
> 		WHERE
> 			f.storage = m.storage_id
> 	)
> ```
> 
> If so, then we could have a background job to remove them every hour or so like https://github.com/nextcloud/server/blob/master/apps/files_sharing/lib/DeleteOrphanedSharesJob.php, which might be easier than the current solution.

@artonge It only works if the shared-by user refreshes his files list after his share has revoked. So, I don't think this query would do the job.

File: apps/files_sharing/lib/Command/FixBrokenShares.php [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+ *
+ * This program is distributed in the hope that it will be useful,
+ * but WITHOUT ANY WARRANTY; without even the implied warranty of
+ * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+ * GNU Affero General Public License for more details.
+ *
+ * You should have received a copy of the GNU Affero General Public License
+ * along with this program.  If not, see <http://www.gnu.org/licenses/>.
+ *
+ */
```
Comment (come-nc) [inline apps/files_sharing/lib/Command/FixBrokenShares.php:22]:
```suggestion
/**
 * SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
```

File: apps/files_sharing/lib/Command/FixBrokenShares.php [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+use Symfony\Component\Console\Input\InputInterface;
+use Symfony\Component\Console\Output\OutputInterface;
+
+class FixBrokenShares extends Base {
+	private OrphanHelper $orphanHelper;
+
+	public function __construct(OrphanHelper $orphanHelper) {
+		parent::__construct();
+		$this->orphanHelper = $orphanHelper;
+	}
```
Comment (come-nc) [inline apps/files_sharing/lib/Command/FixBrokenShares.php:37]:
```suggestion
	public function __construct(
		private OrphanHelper $orphanHelper,
	) {
		parent::__construct();
	}
```

File: apps/files_sharing/lib/Command/FixBrokenShares.php [hunk 4]
```diff
@@ -0,0 +1,63 @@
...
+
+			$owner = $this->orphanHelper->findOwner($share['fileid']);
+
+			if (!empty($owner)) {
+				$this->orphanHelper->updateShareOwner($share['id'], $owner);
+				$output->writeln("Share {$share['id']} updated to owner $owner");
+			}
+		}
+
+		return 0;
```
Comment (come-nc) [inline apps/files_sharing/lib/Command/FixBrokenShares.php:61]:
```suggestion
		return static::SUCCESS;
```

File: apps/files_sharing/lib/OrphanHelper.php [hunk 5]
```diff
@@ -88,4 +92,25 @@ public function getAllShares() {
...
 	}
+
+	public function findOwner(int $fileId): ?string {
+		$mounts = $this->userMountCache->getMountsForFileId($fileId);
+		if (!$mounts) {
+			return null;
+		}
+		foreach ($mounts as $mount) {
+			if ($mount->getInternalPath()) {
+				return $mount->getUser()->getUID();
```
Comment (come-nc) [inline apps/files_sharing/lib/OrphanHelper.php:103]: Can you explain the logic in a comment here?
A file can have several owners and only one of them will be returned randomly, right? We may end up with less permissions than expected, no?

File: apps/files_sharing/lib/OrphanHelper.php [hunk 6]
```diff
@@ -88,4 +92,26 @@ public function getAllShares() {
...
+			}
+		}
+		return null;
+	}
+
+	public function updateShareOwner(int $shareId, string $owner): void {
+		$query = $this->connection->getQueryBuilder();
+		$query->update('share')
+			->set('uid_owner', $query->createNamedParameter($owner))
+			->where($query->expr()->eq('id', $query->createNamedParameter($shareId)));
```
Comment (come-nc) [inline apps/files_sharing/lib/OrphanHelper.php:114]:
```suggestion
			->where($query->expr()->eq('id', $query->createNamedParameter($shareId, IQueryBuilder::PARAM_INT)));
```

File: apps/files_sharing/lib/Command/FixBrokenShares.php [hunk 7]
```diff
@@ -0,0 +1,59 @@
...
+		$dryRun = $input->getOption('dry-run');
+
+		foreach ($shares as $share) {
+			if ($this->orphanHelper->isShareValid($share['owner'], $share['fileid']) || !$this->orphanHelper->fileExists($share['fileid'])) {
+				continue;
+			}
+
+			$owner = $this->orphanHelper->findOwner($share['fileid']);
+
+			if (!empty($owner)) {
```
Comment (come-nc) [inline apps/files_sharing/lib/Command/FixBrokenShares.php:47]:
```suggestion
			if ($owner !== null) {
```
`'0'` is a valid userid.

File: lib/private/Share20/Manager.php [hunk 8]
```diff
@@ -1117,6 +1117,71 @@ protected function deleteChildren(IShare $share) {
...
 
+	protected function deleteReshare(IShare $share) {
+		// If the user has another shares, we don't delete the shares by this user
+		if ($share->getShareType() === IShare::TYPE_USER) {
+			$groupShares = $this->getSharedWith($share->getSharedWith(), IShare::TYPE_GROUP, $share->getNode(), -1, 0);
+
+			if (count($groupShares) !== 0) {
+				return;
+			}
+		}
```
Comment (come-nc) [inline lib/private/Share20/Manager.php:1128]: This checks the user does not have access to the same file/folder through another share, right?

But it does not check the same thing for subfiles/subfolders, while still deleting shares of children below.

This PR should contains tests showing behavior in different scenarios where shares should be deleted or should not to validate that it behaves correctly.

**Review by come-nc — CHANGES_REQUESTED** [review]

**Comment by luka-nextcloud** [comment]
@come-nc Could you please review again? All checks have passed now.

File: apps/files_sharing/lib/OrphanHelper.php [hunk 9]
```diff
@@ -10,19 +10,23 @@
...
 class OrphanHelper {
 	private IDBConnection $connection;
 	private IRootFolder $rootFolder;
+	private IUserMountCache $userMountCache;
 
 	public function __construct(
 		IDBConnection $connection,
-		IRootFolder $rootFolder
+		IRootFolder $rootFolder,
+		IUserMountCache $userMountCache
```
Comment (come-nc) [inline apps/files_sharing/lib/OrphanHelper.php:25]:
```suggestion
		IUserMountCache $userMountCache,
```

File: lib/private/Share20/Manager.php [hunk 10]
```diff
@@ -1117,6 +1118,108 @@ protected function deleteChildren(IShare $share) {
...
+
+		// Delete re-share records (shared by "share with user") inside folder
+		if ($share->getNodeType() === 'folder' && $share->getShareType() === IShare::TYPE_USER) {
+			$sharesInFolder = $this->getSharesInFolder($share->getSharedWith(), $node, true);
+
+			foreach ($sharesInFolder as $shares) {
+				foreach ($shares as $child) {
+					$this->deleteShare($child);
```
Comment (come-nc) [inline lib/private/Share20/Manager.php:1160]: For subfiles you did not check that the user still has access to it, I think?

File: lib/private/Share20/Manager.php [hunk 11]
```diff
@@ -1117,6 +1118,108 @@ protected function deleteChildren(IShare $share) {
...
+
+					if (count($groupShares) !== 0 || count($userShares) !== 0) {
+						return;
+					}
+
+					$parentNode = $parentNode->getParent();
+				}
+			} catch (NotFoundException) {
+			}
+		}
```
Comment (come-nc) [inline lib/private/Share20/Manager.php:1152]: Instead of doing all this to check if the user still has access to the file or not, does it not make more sense to directly check if the user has access to the file? We must have some tooling for that, no?

Comment (luka-nextcloud) [reply lib/private/Share20/Manager.php:1152]: @come-nc  I cannot find another way to check this logic. Could you provide some suggestions?

Comment (come-nc) [reply lib/private/Share20/Manager.php]: Get the user folder of the user and use `getFirstNodeById` would work I think.

Comment (come-nc) [reply lib/private/Share20/Manager.php]: (Note that this would only work after deleting the share)

**Comment by come-nc** [comment]
@luka-nextcloud After talking with Robin, actually the ownership transfer is supposed to update the owner of the share so there should be no problem in the first place?

**Comment by luka-nextcloud** [comment]
@come-nc Does it mean that these changes are enough for this issue?

image

image

**Comment by come-nc** [comment]
> @come-nc Does it mean that these changes are enough for this issue?
> 
> image
> 
> image

No, the second diff looks like it will cause trouble by arbitrary changing sharedBy of shares.

I lost track of what you are trying to fix, can you explain how to reproduce your problem? Why do you remove the exception handling removing invalid shares in OwnershipTransferService?

**Comment by luka-nextcloud** [comment]
@come-nc
- Reproduce steps:
1. UserA share Folder1 to UserB
2. UserB share Folder1 to UserC
3. UserA deleted sharing to UserB
4. UserA transfer Folder1 to UserD
-> UserC lost access to Folder1. When UserC open sharing tab of Folder1, the error message `Error: Could not get proper share mount for . Failing since else the next calls are called with null` returned.

- Issue occurred because the sharing of UserB to UserC was not deleted or updated after UserA deleted sharing to UserB. Then, when UserA transfering Folder1 to UserD, that re-share record cannot be transferred because it throws `GenericShareException` error.

**Comment by come-nc** [comment]
> @come-nc
> 
> * Reproduce steps:
> 
> 1. UserA share Folder1 to UserB
> 2. UserB share Folder1 to UserC
> 3. UserA deleted sharing to UserB
> 4. UserA transfer Folder1 to UserD
>    -> UserC lost access to Folder1. When UserC open sharing tab of Folder1, the error message `Error: Could not get proper share mount for . Failing since else the next calls are called with null` returned.
> 
> * Issue occurred because the sharing of UserB to UserC was not deleted or updated after UserA deleted sharing to UserB. Then, when UserA transfering Folder1 to UserD, that re-share record cannot be transferred because it throws `GenericShareException` error.

UserC already loses access to Folder1 after step 3, right?
At that point the sharing tab shows no error?

**Comment by luka-nextcloud** [comment]
@come-nc 
> UserC already loses access to Folder1 after step 3, right?

No, UserC didn't lose access to Folder1 after step3. This is the issue we are trying to fix.

> At that point the sharing tab shows no error?

No error.

**Comment by luka-nextcloud** [comment]
@come-nc 
**Original problem:**
Re-share was not deleted when parent share deleted. Then, it caused error while transferring ownership.

**Reproduce steps:**
Mentioned above.

**Solution:**
Delete the re-share and its children when parent share is deleted.

File: lib/private/Share20/Manager.php [hunk 12]
```diff
@@ -1016,6 +1017,110 @@ protected function deleteChildren(IShare $share) {
...
+
+				if ($share->getNodeType() === 'folder') {
+					$sharesInFolder = $this->getSharesInFolder($user->getUID(), $node, true);
+
+					foreach ($sharesInFolder as $shares) {
+						foreach ($shares as $child) {
+							if ($this->hasNodeAccess($user->getUID(), $child->getNode())) {
+								continue;
+							}
+							$this->deleteShare($child);
```
Comment (come-nc) [inline lib/private/Share20/Manager.php:1093]: Why is generalCreateCheck method not directly run on `$child` instead?
I do not understand the logic in hasNodeAccess, it searches for other shares of the same node but only directly to the user?

Also, the code is duplicated between user shares and group shares, please first compute an array of target users and then loop on it.

Comment (luka-nextcloud) [reply lib/private/Share20/Manager.php]: @come-nc Ok, I have checked again. The logic in `hasNodeAccess` was not really correct. It missed some cases. So, I removed that function and updated approach for `deleteReshare`. First collect related user ids, then collect the re-share by those users, finally do `generalCreateCheck` on those re-share records.

File: lib/private/Share20/Manager.php [hunk 13]
```diff
@@ -1016,6 +1017,71 @@ protected function deleteChildren(IShare $share) {
...
+		}
+
+		$reshareRecords = [];
+		$shareTypes = [
+			IShare::TYPE_GROUP,
+			IShare::TYPE_USER,
+			IShare::TYPE_LINK,
+			IShare::TYPE_REMOTE,
+			IShare::TYPE_EMAIL
+		];
```
Comment (come-nc) [inline lib/private/Share20/Manager.php:1054]: From what I see in `getSharesInFolder` you can use `$providers = $this->factory->getAllProviders();` to directly get all providers without caring for the share type. Unless we explicitely only want to fetch for some type here?

File: lib/private/Share20/Manager.php [hunk 14]
```diff
@@ -1016,6 +1017,71 @@ protected function deleteChildren(IShare $share) {
...
+
+		foreach ($userIds as $userId) {
+			foreach ($shareTypes as $shareType) {
+				$provider = $this->factory->getProviderForType($shareType);
+				$shares = $provider->getSharesBy($userId, $shareType, $node, false, -1, 0);
```
Comment (come-nc) [inline lib/private/Share20/Manager.php:1059]: Why do you pass `false` for `$reshares` flag here but `true` in the call to `getSharesInFolder` below?

File: apps/files_sharing/lib/OrphanHelper.php [hunk 15]
```diff
@@ -73,4 +77,26 @@ public function getAllShares() {
...
 		}
 	}
+
+	public function findOwner(int $fileId): ?string {
+		$mounts = $this->userMountCache->getMountsForFileId($fileId);
+		if (!$mounts) {
+			return null;
+		}
+		foreach ($mounts as $mount) {
+			// Only the mount of owner has the internal path value
```
Comment (icewind1991) [inline apps/files_sharing/lib/OrphanHelper.php:87]: I don't think this is true

File: lib/private/Share20/Manager.php (hunk 13 above)
Comment (luka-nextcloud) [reply lib/private/Share20/Manager.php:1054]: We still need share type for calling `getSharesBy()` at line 1059.

File: apps/files_sharing/lib/OrphanHelper.php (hunk 15 above)
Comment (luka-nextcloud) [reply apps/files_sharing/lib/OrphanHelper.php:87]: @icewind1991 Could you provide a suggestion?

File: lib/private/Share20/Manager.php (hunk 13 above)
Comment (come-nc) [reply lib/private/Share20/Manager.php:1054]: Indeed, I missed that.

File: apps/files_sharing/lib/OrphanHelper.php (hunk 15 above)
Comment (icewind1991) [reply apps/files_sharing/lib/OrphanHelper.php:87]: You can check if `$mount` is a `HomeMountPoint` and then use `$mount->getUser()`

File: apps/files_sharing/lib/OrphanHelper.php [hunk 16]
```diff
@@ -68,4 +70,26 @@ public function getAllShares() {
...
 	}
+
+	public function findOwner(int $fileId): ?string {
+		$mounts = $this->userMountCache->getMountsForFileId($fileId);
+		if (!$mounts) {
+			return null;
+		}
+		foreach ($mounts as $mount) {
+			$userHomeMountPoint = '/' . $mount->getUser()->getUID() . '/';
+			if ($mount->getMountPoint() === $userHomeMountPoint) {
```
[the remark this answers is not in the document]
Comment (come-nc) [reply apps/files_sharing/lib/OrphanHelper.php:81]: I was wrong, $mount here is actually an instance of CachedMountFileInfo and it seems there’s no easy way to get a MountPoint/HomeMountPoint instead.

Let’s keep it that way if it works.
I’d like @icewind1991 to approve this just in case there is a corner case we missed.

**Review by come-nc — APPROVED** [review]

File: apps/files_sharing/lib/OrphanHelper.php (hunk 16 above)
[the remark this answers is not in the document]
Comment (icewind1991) [reply apps/files_sharing/lib/OrphanHelper.php:81]: Didn't realize `$mount` is a `CachedMountInfo`, then checking the mountpoint is probably the easiest.

**Review by icewind1991 — APPROVED** [review]
