### PR TITLE
fix: Filter for folders in cleanup old preview job

### LINKED ISSUE #35936: TypeError for SimpleFolder in /var/www/nextcloud/lib/private/Files/AppData/AppData.php when there are extra files in appdata folder
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I get this Exception thrown a few times an hour, looking at the code I am sorry but could not figure out what was wrong.

TypeError: OC\Files\SimpleFS\SimpleFolder::__construct(): Argument #1 ($folder) must be of type OCP\Files\Folder, OC\Files\Node\File given, called in /var/www/nextcloud/lib/private/Files/AppData/AppData.php on line 140

### Steps to reproduce

Firstly thank you, think this is a great platform.

I been seeing this for awhile so though I should now report it, but strange I don't seem to see others reporting this, was also happening in NC24, and now NC25.0.2 on full patched Debian.

This is triggered by the cron jobs that NC runs.

### Expected behavior

No exceptions in the log

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

SQlite

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
sudo -u www-data php occ config:list system
Cannot load Zend OPcache - it was already loaded
{
    "system": {
        "activity_expire_days": 90,
        "auth.bruteforce.protection.enabled": true,
        "blacklisted_files": [
            ".htaccess",
            "Thumbs.db",
            "thumbs.db"
        ],
        "enable_previews": "false",
        "preview_max_x": 100,
        "preview_max_filesize_image": 1,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "log_type": "file",
        "loglevel": 3,
        "logdateformat": "F d, Y H:i:s",
        "logtimezone": "Europe\/London",
        "trashbin_retention_obligation": "auto, 7",
        "defaultapp": "calendar,files",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "knowledgebaseenabledy": false,
        "skeletondirectory": "",
        "lost_password_link": "disabled",
        "updatechecker": true,
        "trusted_domains": [
            "**I REMOVED SENSITIVE VALUE**",
            "192.168.20.52:xxx",
            "127.0.0.1:xxx"
        ],
        "overwrite.cli.url": "https:\/\/**REMOVED SENSITIVE VALUE**:xxx",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite3",
        "version": "25.0.2.3",
        "installed": true,
        "maintenance": false,
        "mail_smtpsecure": "ssl"
    }
}
```

### List of activated Apps

```shell
sudo -u www-data php occ app:list
Cannot load Zend OPcache - it was already loaded
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - bookmarks: 12.0.0
  - calendar: 4.2.0
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.2
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - bruteforcesettings: 1.1.0
  - encryption
  - files_external
  - suspicious_login
  - twofactor_totp
  - user_ldap
root@d86ed09c4605:/var/www/nextcloud#
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
This is just repeat many time here is a sample then an expanded example:

Error	core	TypeError: OC\Files\SimpleFS\SimpleFolder::__construct(): Argument #1 ($folder) must be of type OCP\Files\Folder, OC\Files\Node\File given, called in /var/www/nextcloud/lib/private/Files/AppData/AppData.php on line 140	
January 01, 2023 10:15:03
Error	core	TypeError: OC\Files\SimpleFS\SimpleFolder::__construct(): Argument #1 ($folder) must be of type OCP\Files\Folder, OC\Files\Node\File given, called in /var/www/nextcloud/lib/private/Files/AppData/AppData.php on line 140	
January 01, 2023 09:00:03
Error	core	TypeError: OC\Files\SimpleFS\SimpleFolder::__construct(): Argument #1 ($folder) must be of type OCP\Files\Folder, OC\Files\Node\File given, called in /var/www/nextcloud/lib/private/Files/AppData/AppData.php on line 140	
January 01, 2023 07:45:02
Error	core	TypeError: OC\Files\SimpleFS\SimpleFolder::__construct(): Argument #1 ($folder) must be of type OCP\Files\Folder, OC\Files\Node\File given, called in /var/www/nextcloud/lib/private/Files/AppData/AppData.php on line 140	
January 01, 2023 06:30:03
Error	core	TypeError: OC\Files\SimpleFS\SimpleFolder::__construct(): Argument #1 ($folder) must be of type OCP\Files\Folder, OC\Files\Node\File given, called in /var/www/nextcloud/lib/private/Files/AppData/AppData.php on line 140	
January 01, 2023 05:15:03
Error	core	TypeError: OC\Files\SimpleFS\SimpleFolder::__construct(): Argument #1 ($folder) must be of type OCP\Files\Folder, OC\Files\Node\File given, called in /var/www/nextcloud/lib/private/Files/AppData/AppData.php on line 140	
January 01, 2023 04:00:02
Error	core	TypeError: OC\Files\SimpleFS\SimpleFolder::__construct(): Argument #1 ($folder) must be of type OCP\Files\Folder, OC\Files\Node\File given, called in /var/www/nextcloud/lib/private/Files/AppData/AppData.php on line 140	
January 01, 2023 02:45:07


=================expanded example:
Error	core	TypeError: OC\Files\SimpleFS\SimpleFolder::__construct(): Argument #1 ($folder) must be of type OCP\Files\Folder, OC\Files\Node\File given, called in /var/www/nextcloud/lib/private/Files/AppData/AppData.php on line 140

    /var/www/nextcloud/lib/private/Files/AppData/AppData.php - line 140:

    OC\Files\SimpleFS\SimpleFolder->__construct()

    /var/www/nextcloud/lib/private/Preview/Storage/Root.php - line 57:

    OC\Files\AppData\AppData->getFolder()

    /var/www/nextcloud/lib/private/Preview/BackgroundCleanupJob.php - line 66:

    OC\Preview\Storage\Root->getFolder()

    /var/www/nextcloud/lib/private/BackgroundJob/Job.php - line 54:

    OC\Preview\BackgroundCleanupJob->run()

    /var/www/nextcloud/lib/private/BackgroundJob/TimedJob.php - line 60:

    OC\BackgroundJob\Job->execute()

    /var/www/nextcloud/cron.php - line 152:

    OC\BackgroundJob\TimedJob->execute()


=======================and another
Error	core	TypeError: OC\Files\SimpleFS\SimpleFolder::__construct(): Argument #1 ($folder) must be of type OCP\Files\Folder, OC\Files\Node\File given, called in /var/www/nextcloud/lib/private/Files/AppData/AppData.php on line 140

    /var/www/nextcloud/lib/private/Files/AppData/AppData.php - line 140:

    OC\Files\SimpleFS\SimpleFolder->__construct()

    /var/www/nextcloud/lib/private/Preview/Storage/Root.php - line 57:

    OC\Files\AppData\AppData->getFolder()

    /var/www/nextcloud/lib/private/Preview/BackgroundCleanupJob.php - line 66:

    OC\Preview\Storage\Root->getFolder()

    /var/www/nextcloud/lib/private/BackgroundJob/Job.php - line 54:

    OC\Preview\BackgroundCleanupJob->run()

    /var/www/nextcloud/lib/private/BackgroundJob/TimedJob.php - line 60:

    OC\BackgroundJob\Job->execute()

    /var/www/nextcloud/cron.php - line 152:

    OC\BackgroundJob\TimedJob->execute()
```

### Additional info

64Bit Debian ruining in a docker image on a 64 bit installation of RPI4 raspberry OS all full patched. 
uname -a
Linux rpi4-cubox 5.15.84-v8+ #1610 SMP PREEMPT Mon Dec 19 18:54:50 GMT 2022 aarch64 GNU/Linux
# docker -v
Docker version 20.10.22, build 3a2c30b

then inside the container:
# uname -a
Linux d86ed09c4605 5.15.84-v8+ #1610 SMP PREEMPT Mon Dec 19 18:54:50 GMT 2022 aarch64 GNU/Linux

# php --version
Cannot load Zend OPcache - it was already loaded
PHP 8.1.13 (cli) (built: Nov 26 2022 14:27:02) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.13, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.13, Copyright (c), by Zend Technologies

# apache2 -v      
Server version: Apache/2.4.54 (Debian)
Server built:   2022-06-09T04:26:43

============
I have run the recommended scripts to secure the install, and the data section is held in a separate area. Everything seems to have been running fine... but my log file does fill up over time :-) so thought I should mention I am seeing this.

### PR DESCRIPTION
**Pull request by hammer065**
* Resolves: #35936

## Summary
When running `OC\Preview\BackgroundCleanupJob`, the main iteration loop in `run()` expects a folder,
however, `getOldPreviewLocations()` currently does not filter by mimetype
and therefore can yield a non-folder entry which causes an Exception when constructing the Folder impl.
Filtering for `httpd/unix-directory`, as `getNewPreviewLocations()` already does, fixes this issue.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by kesselb** [comment]
Same as https://github.com/nextcloud/server/pull/46072?

**Comment by hammer065** [comment]
As the above mentioned PR seems to be staled, I rebased and refined this one.

It now also incorporates the second improvement made in 0c7eeec43f50632c19513697f5ceed056a6e8c69 for the job also ignoring non-numeric named directories.
However, 0c7eeec43f50632c19513697f5ceed056a6e8c69 did this inefficiently by needing to cast *all* `filecache` row IDs to a string, which then also results in needing to perform expensive string comparisons for the `JOIN`.
The same goal is still achieved by further filtering the small amount of entries for this appid of type directory to match against a trivial RegExp.
As an expression to match against a RegExp was not present yet, I implemented it for this PR.

Requesting a review @artonge @kesselb @artonge

**Comment by solracsf** [comment]
Can you please explain why this PR is better than https://github.com/nextcloud/server/pull/46072 ?

**Comment by hammer065** [comment]
@solracsf Sure thing:
1. As I explained in https://github.com/nextcloud/server/pull/48581#issuecomment-2604447290, the changes in the other PR contain an majorly inefficient query change, which results in casting the numeric ID for *all* files/folders on the Nextcloud instance to a string to then be string-compared against a (to be expected) small list of files, fully bypassing any index, slowing down the periodic `BackgroundCleanupJob`.

2. This PR contains tests for the incorporated changes.

**Review by come-nc — APPROVED** [review]
This REGEX thing is a bit scary but I suppose if the tests pass on all DB we should be fine?

**Review by artonge — COMMENTED** [review]
Is the regexp part actually needed? What kind of directory were selected when they should not be?

**Comment by come-nc** [comment]
@hammer065 Thank you for your work on this and explanations.
What we were wondering when discussing this issue with @artonge is that the join on (int)name = fileid should already filter out non-numeric folder names. But there may be corner cases depending on DB servers, I remember that cast can behave quite weird in some situations.
Like '1.3' could be cast to 1 and not be filtered out on sqlite I think.

But that’s quite a niche cornercase, and the code after should survive. Worst case scenario I think it will delete a folder in the preview folder which should not be there in the first place.

So all in all I would vote for the simpler version of the PR without the regex usage. Maybe we can keep the regex implementation the queryBuilder though, it may prove useful some day.

**Comment by artonge** [comment]
Thanks for the detailed summary @hammer065. On my side, I indeed don't see the point in introducing such logic for a hypothetical edge case.

> my approach prevents the costly cast of all file-IDs to a string by just filtering out all non-numeric folder names using the RegExp

I would especially be against, as "all non-numeric folder names" would probably be only one.

**Comment by artonge** [comment]
> Maybe we can keep the regex implementation the queryBuilder though, it may prove useful some day.

Not sure about the performance of such operator. Unless it is fast, having it in by default might lead to being it use without knowing better and causing performance issues. If we don't have a use case, let's not keep it.

**Comment by hammer065** [comment]
Please let me know what the end position is after your (internal) discussions, so I can adapt the PR accordingly.

My personal stances are to both *not* support arbitrary *folders*, just files, in the previews directory and *not* to keep the RegEx code.

**Comment by come-nc** [comment]
> Please let me know what the end position is after your (internal) discussions, so I can adapt the PR accordingly.
> 
> My personal stances are to both _not_ support arbitrary _folders_, just files, in the previews directory and _not_ to keep the RegEx code.

We agree, please remove regex related code and keep the changes minimal, it will also be easier to backport.

**Comment by hammer065** [comment]
> We agree, please remove regex related code and keep the changes minimal, it will also be easier to backport.

@come-nc Done, you can review this now (finally) final commit :D

File: lib/private/Preview/BackgroundCleanupJob.php [hunk 1]
```diff
@@ -63,13 +63,13 @@ private function getOldPreviewLocations(): \Iterator {
...
-				$qb->expr()->eq('a.parent', $qb->createNamedParameter($this->previewFolder->getId()))
-			)->andWhere(
-				$qb->expr()->like('a.name', $qb->createNamedParameter('__%'))
+				$qb->expr()->andX(
+					$qb->expr()->isNull('b.fileid'),
+					$qb->expr()->eq('a.storage', $qb->createNamedParameter($this->previewFolder->getStorageId())),
+					$qb->expr()->eq('a.parent', $qb->createNamedParameter($this->previewFolder->getId())),
+					$qb->expr()->like('a.name', $qb->createNamedParameter('__%')),
+					$qb->expr()->eq('a.mimetype', $qb->createNamedParameter($this->mimeTypeLoader->getId('httpd/unix-directory')))
+				)
```
Comment (artonge) [inline lib/private/Preview/BackgroundCleanupJob.php:72]: I would have kept the `andWhere` syntax to reduce the amount of changes, but good anyway

**Review by artonge — APPROVED** [review]

File: lib/private/Preview/BackgroundCleanupJob.php (hunk 1 above)
Comment (hammer065) [reply lib/private/Preview/BackgroundCleanupJob.php:72]: I have done it as, in my opinion, the `->andWhere()` syntax is more verbose and less readable than the `->andX()` syntax. It additionally makes this consistent to the nearly identical query in L133-145.

Comment (artonge) [reply lib/private/Preview/BackgroundCleanupJob.php:72]: Consistency and low change count was my concern. If it is consistent with the sibling query, then perfect :+1:

**Review by come-nc — APPROVED** [review]

**Comment by come-nc** [comment]
@hammer065 Thanks a lot for your patience and team work here!

Would you be interested in a Guest account on our Nextcloud Talk instance where we host a dev chat?

**Comment by hammer065** [comment]
> Would you be interested in a Guest account on our Nextcloud Talk instance where we host a dev chat?
@come-nc Sure thing, would definitely speed up the discussion process for any potential future PRs :D
Can this be linked/Is this linkable to my account on my own Nextcloud instance or would it be a separate account all together?

**Comment by come-nc** [comment]
> > Would you be interested in a Guest account on our Nextcloud Talk instance where we host a dev chat?
> > @come-nc 
>
> Sure thing, would definitely speed up the discussion process for any potential future PRs :D
> Can this be linked/Is this linkable to my account on my own Nextcloud instance or would it be a separate account all together?

I invited you on the email used for the commit sign-off.
It’s a guest account using the guests app, it’s not linkable to a federated account. I think we did have federation enabled for Talk on our instance, but I’m not sure whether it’s enabled for community chat yet.
