### PR TITLE
SCSS hardening

### LINKED ISSUE #6752: NC12 slow with multiple domains
# Steps to reproduce
nextcloud with multiple trusted domains
slow, when multiple domains are used
on test system, multipe times load url from domain A is fast, multiple times from domain B is fast, but every change between domains is slow, multiple seconds to wait

### Expected behaviour
fast access, whatever hostname was previously used

### Actual behaviour
slow access, when prevoius request used another hostname

### Server configuration

**Operating system**: CentOS 6 and Ubuntu 16.04

**Web server:** Apache 2.2.15 and nginx 1.10.3

**Database:** MySQL

**PHP version:** 7.1.7 and 7.0

**Nextcloud version:** 12.0.3
since commit https://github.com/nextcloud/server/commit/5a9224fb4c736fbd07e0dd90058c2e87cbebbe16
#3531

**Updated from an older Nextcloud/ownCloud or fresh install:** Both.

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ocegfp59oanb",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "*tob.serpens.uberspace.de"
        ],
        "datadirectory": "\/home\/tob\/ncdata\/",
        "overwrite.cli.url": "https:\/\/tob.serpens.uberspace.de",
        "dbtype": "mysql",
        "version": "12.0.0.14",
        "dbname": "tob_nc",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false
    }
}

```
</details>

Test-URLs:
https://TestA.tob.serpens.uberspace.de/index.php/s/c8xRwV8ZZmGCGFE
https://TestB.tob.serpens.uberspace.de/index.php/s/c8xRwV8ZZmGCGFE
page loads measured with curl in bash-script:

```
TestA 4618
TestA 459
TestA 460
TestA 468
TestB 4353
TestB 473
TestB 441
TestA 3796
TestB 3888
TestB 437
TestA 5026
TestA 462
TestA 476
TestA 467
TestA 418
TestB 4815
TestB 563
TestB 549
TestA 3985
TestA 488
TestA 480
TestA 487
TestA 463
TestB 4076
TestB 456
TestA 4028
TestB 5167
TestB 591
TestB 585
TestB 439
```

### LINKED ISSUE #7977: CSS is not properly rendered after upgrade from 11 to 12.0.4
### Steps to reproduce
1. Upgrade Nextcloud from 11 to 12.0.4 via updater app
2. After upgrade is done, log into Nextcloud instance
3. Observe text all over the place, completely unusable interface (see: https://imgur.com/a/SAE0m) the big red symbol is a blown up logo of gpxpod, one of the installed apps.

### Expected behaviour
Nextcloud should be updated and continue to work as expected

### Actual behaviour
See above
I also noticed that the css folder for the files app does not contain css files but only scss files.

### Server configuration

**Operating system**:
Linux 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2
**Web server:**
apache2
**Database:**
mysql
**PHP version:**
php 7
**Nextcloud version:** (see Nextcloud admin page)
11.06
**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**
website
**Signing status:**
<details>
<summary>result of integrity check</summary>
Integrity checker has been disabled. Integrity cannot be verified.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.4.1
  - activitylog: 0.0.1
  - admin_audit: 1.1.0
  - admin_notifications: 1.0.1
  - bookmarks: 0.10.1
  - calendar: 1.5.7
  - comments: 1.1.0
  - contacts: 2.0.1
  - dav: 1.1.1
  - deck: 0.2.8
  - direct_menu: 0.10.2
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_downloadactivity: 1.0.1
  - files_markdown: 2.0.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - gpxedit: 0.0.7
  - gpxpod: 2.2.1
  - keeweb: 0.4.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notes: 2.3.2
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - richdocuments: 1.11.37
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreed: 1.2.0
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - lsd
  - user_external
  - user_ldap
  - user_saml

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "",
            "",
            ""
        ],
        "datadirectory": "\/var\/nextclouddata\/data",
        "appstoreurl": "https:\/\/apps.nextcloud.com\/api\/v0",
        "overwrite.cli.url": "https:\/\/nextcloud.\/",
        "overwriteprotocol": "https",
        "dbtype": "mysql",
        "version": "11.0.6.1",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "default_language": "de",
        "auth.bruteforce.protection.enabled": true,
        "instanceid": "ID",
        "updater.release.channel": "production",
        "maintenance": false,
        "theme": "",
        "logtype": "owncloud",
        "logfile": "\/var\/log\/nextcloud.log",
        "loglevel": 0,
        "appstore.experimental.enabled": true,
        "mail_from_address": "info",
        "mail_smtpmode": "sendmail",
        "mail_domain": "",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}

</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**
chrome latest version
**Operating system:**
fedora
#### Web server error log
<details>
<summary>Web server error log</summary>

the apache logs do not seem to have anything relevant.
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

{"reqId":"fZ4Bj8V4gB7gs9tqW1N7","level":3,"time":"2018-01-22T16:47:04+00:00","remoteAddr":"IP-address-redacted","user":"admin","app":"core","method":"GET","url":"\/index.php\/apps\/files\/","message":"Leafo\\ScssPhp\\Exception\\ParserException: parse error: failed at `$color-primary: ##5900b3;$color-primary-text: #ffffff;$color-primary-element: ##5900b3;@import \"server.scss\";` (stdin) on line 1 in \/var\/www\/nextcloud\/3rdparty\/leafo\/scssphp\/src\/Parser.php:128\nStack trace:\n#0 \/var\/www\/nextcloud\/3rdparty\/leafo\/scssphp\/src\/Parser.php(169): Leafo\\ScssPhp\\Parser->throwParseError()\n#1 \/var\/www\/nextcloud\/3rdparty\/leafo\/scssphp\/src\/Compiler.php(186): Leafo\\ScssPhp\\Parser->parse('@import \"variab...')\n#2 \/var\/www\/nextcloud\/lib\/private\/Template\/SCSSCacher.php(215): Leafo\\ScssPhp\\Compiler->compile('@import \"variab...')\n#3 \/var\/www\/nextcloud\/lib\/private\/Template\/SCSSCacher.php(112): OC\\Template\\SCSSCacher->cache('\/var\/www\/nextcl...', '115d4b62b085acb...', 'server.scss', Object(OC\\Files\\SimpleFS\\SimpleFolder), 'core\/css')\n#4 \/var\/www\/nextcloud\/lib\/private\/Template\/CSSResourceLocator.php(105): OC\\Template\\SCSSCacher->process('\/var\/www\/nextcl...', 'core\/css\/server...', 'core')\n#5 \/var\/www\/nextcloud\/lib\/private\/Template\/CSSResourceLocator.php(57): OC\\Template\\CSSResourceLocator->cacheAndAppendScssIfExist('\/var\/www\/nextcl...', 'core\/css\/server...')\n#6 \/var\/www\/nextcloud\/lib\/private\/Template\/ResourceLocator.php(76): OC\\Template\\CSSResourceLocator->doFind('css\/server')\n#7 \/var\/www\/nextcloud\/lib\/private\/TemplateLayout.php(225): OC\\Template\\ResourceLocator->find(Array)\n#8 \/var\/www\/nextcloud\/lib\/private\/TemplateLayout.php(170): OC\\TemplateLayout::findStylesheetFiles(Array)\n#9 \/var\/www\/nextcloud\/lib\/private\/legacy\/template.php(205): OC\\TemplateLayout->__construct('user', 'files')\n#10 \/var\/www\/nextcloud\/lib\/public\/AppFramework\/Http\/TemplateResponse.php(157): OC_Template->fetchPage()\n#11 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(113): OCP\\AppFramework\\Http\\TemplateResponse->render()\n#12 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php(114): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Files\\Controller\\ViewController), 'index')\n#13 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('ViewController', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#14 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#15 \/var\/www\/nextcloud\/lib\/private\/Route\/Router.php(299): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#16 \/var\/www\/nextcloud\/lib\/base.php(1004): OC\\Route\\Router->match('\/apps\/files\/')\n#17 \/var\/www\/nextcloud\/index.php(48): OC::handleRequest()\n#18 {main}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"fZ4Bj8V4gB7gs9tqW1N7","level":2,"time":"2018-01-22T16:47:04+00:00","remoteAddr":"IP-address-redacted","user":"admin","app":"core","method":"GET","url":"\/index.php\/apps\/files\/","message":"Failed to compile and\/or save \/var\/www\/nextcloud\/core\/css\/server.scss","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"fZ4Bj8V4gB7gs9tqW1N7","level":3,"time":"2018-01-22T16:47:04+00:00","remoteAddr":"IP-address-redacted","user":"admin","app":"cssresourceloader","method":"GET","url":"\/index.php\/apps\/files\/","message":"Could not find resource css\/server.css to load","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"fZ4Bj8V4gB7gs9tqW1N7","level":3,"time":"2018-01-22T16:47:04+00:00","remoteAddr":"IP-address-redacted","user":"admin","app":"core","method":"GET","url":"\/index.php\/apps\/files\/","message":"Leafo\\ScssPhp\\Exception\\ParserException: parse error: failed at `$color-primary: ##5900b3;$color-primary-text: #ffffff;$color-primary-element: ##5900b3;@import \"share.scss\";` (stdin) on line 1 in \/var\/www\/nextcloud\/3rdparty\/leafo\/scssphp\/src\/Parser.php:128\nStack trace:\n#0 \/var\/www\/nextcloud\/3rdparty\/leafo\/scssphp\/src\/Parser.php(169): Leafo\\ScssPhp\\Parser->throwParseError()\n#1 \/var\/www\/nextcloud\/3rdparty\/leafo\/scssphp\/src\/Compiler.php(186): Leafo\\ScssPhp\\Parser->parse('@import \"variab...')\n#2 \/var\/www\/nextcloud\/lib\/private\/Template\/SCSSCacher.php(215): Leafo\\ScssPhp\\Compiler->compile('@import \"variab...')\n#3 \/var\/www\/nextcloud\/lib\/private\/Template\/SCSSCacher.php(112): OC\\Template\\SCSSCacher->cache('\/var\/www\/nextcl...', '115d4b62b085acb...', 'share.scss', Object(OC\\Files\\SimpleFS\\SimpleFolder), 'core\/css')\n#4 \/var\/www\/nextcloud\/lib\/private\/Template\/CSSResourceLocator.php(105): OC\\Template\\SCSSCacher->process('\/var\/www\/nextcl...', 'core\/css\/share....', 'core')\n#5 \/var\/www\/nextcloud\/lib\/private\/Template\/CSSResourceLocator.php(56): OC\\Template\\CSSResourceLocator->cacheAndAppendScssIfExist('\/var\/www\/nextcl...', 'core\/css\/share....', 'core')\n#6 \/var\/www\/nextcloud\/lib\/private\/Template\/ResourceLocator.php(76): OC\\Template\\CSSResourceLocator->doFind('core\/css\/share')\n#7 \/var\/www\/nextcloud\/lib\/private\/TemplateLayout.php(225): OC\\Template\\ResourceLocator->find(Array)\n#8 \/var\/www\/nextcloud\/lib\/private\/TemplateLayout.php(170): OC\\TemplateLayout::findStylesheetFiles(Array)\n#9 \/var\/www\/nextcloud\/lib\/private\/legacy\/template.php(205): OC\\TemplateLayout->__construct('user', 'files')\n#10 \/var\/www\/nextcloud\/lib\/public\/AppFramework\/Http\/TemplateResponse.php(157): OC_Template->fetchPage()\n#11 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(113): OCP\\AppFramework\\Http\\TemplateResponse->render()\n#12 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php(114): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Files\\Controller\\ViewController), 'index')\n#13 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('ViewController', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#14 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#15 \/var\/www\/nextcloud\/lib\/private\/Route\/Router.php(299): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#16 \/var\/www\/nextcloud\/lib\/base.php(1004): OC\\Route\\Router->match('\/apps\/files\/')\n#17 \/var\/www\/nextcloud\/index.php(48): OC::handleRequest()\n#18 {main}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"fZ4Bj8V4gB7gs9tqW1N7","level":2,"time":"2018-01-22T16:47:04+00:00","remoteAddr":"IP-address-redacted","user":"admin","app":"core","method":"GET","url":"\/index.php\/apps\/files\/","message":"Failed to compile and\/or save \/var\/www\/nextcloud\/core\/css\/share.scss","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"fZ4Bj8V4gB7gs9tqW1N7","level":3,"time":"2018-01-22T16:47:04+00:00","remoteAddr":"IP-address-redacted","user":"admin","app":"cssresourceloader","method":"GET","url":"\/index.php\/apps\/files\/","message":"Could not find resource core\/css\/share.css to load","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"fZ4Bj8V4gB7gs9tqW1N7","level":3,"time":"2018-01-22T16:47:04+00:00","remoteAddr":"IP-address-redacted","user":"admin","app":"core","method":"GET","url":"\/index.php\/apps\/files\/","message":"Leafo\\ScssPhp\\Exception\\ParserException: parse error: failed at `$color-primary: ##5900b3;$color-primary-text: #ffffff;$color-primary-element: ##5900b3;@import \"merged.scss\";` (stdin) on line 1 in \/var\/www\/nextcloud\/3rdparty\/leafo\/scssphp\/src\/Parser.php:128\nStack trace:\n#0 \/var\/www\/nextcloud\/3rdparty\/leafo\/scssphp\/src\/Parser.php(169): Leafo\\ScssPhp\\Parser->throwParseError()\n#1 \/var\/www\/nextcloud\/3rdparty\/leafo\/scssphp\/src\/Compiler.php(186): Leafo\\ScssPhp\\Parser->parse('@import \"variab...')\n#2 \/var\/www\/nextcloud\/lib\/private\/Template\/SCSSCacher.php(215): Leafo\\ScssPhp\\Compiler->compile('@import \"variab...')\n#3 \/var\/www\/nextcloud\/lib\/private\/Template\/SCSSCacher.php(112): OC\\Template\\SCSSCacher->cache('\/var\/www\/nextcl...', '115d4b62b085acb...', 'merged.scss', Object(OC\\Files\\SimpleFS\\SimpleFolder), 'apps\/files\/css')\n#4 \/var\/www\/nextcloud\/lib\/private\/Template\/CSSResourceLocator.php(105): OC\\Template\\SCSSCacher->process('\/var\/www\/nextcl...', 'css\/merged.scss', 'files')\n#5 \/var\/www\/nextcloud\/lib\/private\/Template\/CSSResourceLocator.php(80): OC\\Template\\CSSResourceLocator->cacheAndAppendScssIfExist('\/var\/www\/nextcl...', 'css\/merged.scss', 'files')\n#6 \/var\/www\/nextcloud\/lib\/private\/Template\/ResourceLocator.php(76): OC\\Template\\CSSResourceLocator->doFind('css\/merged')\n#7 \/var\/www\/nextcloud\/lib\/private\/TemplateLayout.php(225): OC\\Template\\ResourceLocator->find(Array)\n#8 \/var\/www\/nextcloud\/lib\/private\/TemplateLayout.php(170): OC\\TemplateLayout::findStylesheetFiles(Array)\n#9 \/var\/www\/nextcloud\/lib\/private\/legacy\/template.php(205): OC\\TemplateLayout->__construct('user', 'files')\n#10 \/var\/www\/nextcloud\/lib\/public\/AppFramework\/Http\/TemplateResponse.php(157): OC_Template->fetchPage()\n#11 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(113): OCP\\AppFramework\\Http\\TemplateResponse->render()\n#12 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php(114): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Files\\Controller\\ViewController), 'index')\n#13 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('ViewController', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#14 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#15 \/var\/www\/nextcloud\/lib\/private\/Route\/Router.php(299): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#16 \/var\/www\/nextcloud\/lib\/base.php(1004): OC\\Route\\Router->match('\/apps\/files\/')\n#17 \/var\/www\/nextcloud\/index.php(48): OC::handleRequest()\n#18 {main}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"fZ4Bj8V4gB7gs9tqW1N7","level":2,"time":"2018-01-22T16:47:04+00:00","remoteAddr":"IP-address-redacted","user":"admin","app":"core","method":"GET","url":"\/index.php\/apps\/files\/","message":"Failed to compile and\/or save \/var\/www\/nextcloud\/apps\/files\/css\/merged.scss","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"fZ4Bj8V4gB7gs9tqW1N7","level":0,"time":"2018-01-22T16:47:04+00:00","remoteAddr":"IP-address-redacted","user":"admin","app":"files","method":"GET","url":"\/index.php\/apps\/files\/","message":"Could not find resource file \"\/apps\/files\/css\/merged.css\"","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"fZ4Bj8V4gB7gs9tqW1N7","level":3,"time":"2018-01-22T16:47:04+00:00","remoteAddr":"IP-address-redacted","user":"admin","app":"core","method":"GET","url":"\/index.php\/apps\/files\/","message":"Leafo\\ScssPhp\\Exception\\ParserException: parse error: failed at `$color-primary: ##5900b3;$color-primary-text: #ffffff;$color-primary-element: ##5900b3;@import \"mergedAdditionalStyles.scss\";` (stdin) on line 1 in \/var\/www\/nextcloud\/3rdparty\/leafo\/scssphp\/src\/Parser.php:128\nStack trace:\n#0 \/var\/www\/nextcloud\/3rdparty\/leafo\/scssphp\/src\/Parser.php(169): Leafo\\ScssPhp\\Parser->throwParseError()\n#1 \/var\/www\/nextcloud\/3rdparty\/leafo\/scssphp\/src\/Compiler.php(186): Leafo\\ScssPhp\\Parser->parse('@import \"variab...')\n#2 \/var\/www\/nextcloud\/lib\/private\/Template\/SCSSCacher.php(215): Leafo\\ScssPhp\\Compiler->compile('@import \"variab...')\n#3 \/var\/www\/nextcloud\/lib\/private\/Template\/SCSSCacher.php(112): OC\\Template\\SCSSCacher->cache('\/var\/www\/nextcl...', '115d4b62b085acb...', 'mergedAdditiona...', Object(OC\\Files\\SimpleFS\\SimpleFolder), 'apps\/files_shar...')\n#4 \/var\/www\/nextcloud\/lib\/private\/Template\/CSSResourceLocator.php(105): OC\\Template\\SCSSCacher->process('\/var\/www\/nextcl...', 'css\/mergedAddit...', 'files_sharing')\n#5 \/var\/www\/nextcloud\/lib\/private\/Template\/CSSResourceLocator.php(80): OC\\Template\\CSSResourceLocator->cacheAndAppendScssIfExist('\/var\/www\/nextcl...', 'css\/mergedAddit...', 'files_sharing')\n#6 \/var\/www\/nextcloud\/lib\/private\/Template\/ResourceLocator.php(76): OC\\Template\\CSSResourceLocator->doFind('css\/mergedAddit...')\n#7 \/var\/www\/nextcloud\/lib\/private\/TemplateLayout.php(225): OC\\Template\\ResourceLocator->find(Array)\n#8 \/var\/www\/nextcloud\/lib\/private\/TemplateLayout.php(170): OC\\TemplateLayout::findStylesheetFiles(Array)\n#9 \/var\/www\/nextcloud\/lib\/private\/legacy\/template.php(205): OC\\TemplateLayout->__construct('user', 'files')\n#10 \/var\/www\/nextcloud\/lib\/public\/AppFramework\/Http\/TemplateResponse.php(157): OC_Template->fetchPage()\n#11 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(113): OCP\\AppFramework\\Http\\TemplateResponse->render()\n#12 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php(114): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Files\\Controller\\ViewController), 'index')\n#13 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('ViewController', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#14 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#15 \/var\/www\/nextcloud\/lib\/private\/Route\/Router.php(299): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#16 \/var\/www\/nextcloud\/lib\/base.php(1004): OC\\Route\\Router->match('\/apps\/files\/')\n#17 \/var\/www\/nextcloud\/index.php(48): OC::handleRequest()\n#18 {main}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"fZ4Bj8V4gB7gs9tqW1N7","level":2,"time":"2018-01-22T16:47:04+00:00","remoteAddr":"IP-address-redacted","user":"admin","app":"core","method":"GET","url":"\/index.php\/apps\/files\/","message":"Failed to compile and\/or save \/var\/www\/nextcloud\/apps\/files_sharing\/css\/mergedAdditionalStyles.scss","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"fZ4Bj8V4gB7gs9tqW1N7","level":0,"time":"2018-01-22T16:47:04+00:00","remoteAddr":"IP-address-redacted","user":"admin","app":"files_sharing","method":"GET","url":"\/index.php\/apps\/files\/","message":"Could not find resource file \"\/apps\/files_sharing\/css\/mergedAdditionalStyles.css\"","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"fZ4Bj8V4gB7gs9tqW1N7","level":3,"time":"2018-01-22T16:47:04+00:00","remoteAddr":"IP-address-redacted","user":"admin","app":"core","method":"GET","url":"\/index.php\/apps\/files\/","message":"Leafo\\ScssPhp\\Exception\\ParserException: parse error: failed at `$color-primary: ##5900b3;$color-primary-text: #ffffff;$color-primary-element: ##5900b3;@import \"merged.scss\";` (stdin) on line 1 in \/var\/www\/nextcloud\/3rdparty\/leafo\/scssphp\/src\/Parser.php:128\nStack trace:\n#0 \/var\/www\/nextcloud\/3rdparty\/leafo\/scssphp\/src\/Parser.php(169): Leafo\\ScssPhp\\Parser->throwParseError()\n#1 \/var\/www\/nextcloud\/3rdparty\/leafo\/scssphp\/src\/Compiler.php(186): Leafo\\ScssPhp\\Parser->parse('@import \"variab...')\n#2 \/var\/www\/nextcloud\/lib\/private\/Template\/SCSSCacher.php(215): Leafo\\ScssPhp\\Compiler->compile('@import \"variab...')\n#3 \/var\/www\/nextcloud\/lib\/private\/Template\/SCSSCacher.php(112): OC\\Template\\SCSSCacher->cache('\/var\/www\/nextcl...', '115d4b62b085acb...', 'merged.scss', Object(OC\\Files\\SimpleFS\\SimpleFolder), 'apps\/files_text...')\n#4 \/var\/www\/nextcloud\/lib\/private\/Template\/CSSResourceLocator.php(105): OC\\Template\\SCSSCacher->process('\/var\/www\/nextcl...', 'css\/merged.scss', 'files_textedito...')\n#5 \/var\/www\/nextcloud\/lib\/private\/Template\/CSSResourceLocator.php(80): OC\\Template\\CSSResourceLocator->cacheAndAppendScssIfExist('\/var\/www\/nextcl...', 'css\/merged.scss', 'files_textedito...')\n#6 \/var\/www\/nextcloud\/lib\/private\/Template\/ResourceLocator.php(76): OC\\Template\\CSSResourceLocator->doFind('css\/merged')\n#7 \/var\/www\/nextcloud\/lib\/private\/TemplateLayout.php(225): OC\\Template\\ResourceLocator->find(Array)\n#8 \/var\/www\/nextcloud\/lib\/private\/TemplateLayout.php(170): OC\\TemplateLayout::findStylesheetFiles(Array)\n#9 \/var\/www\/nextcloud\/lib\/private\/legacy\/template.php(205): OC\\TemplateLayout->__construct('user', 'files')\n#10 \/var\/www\/nextcloud\/lib\/public\/AppFramework\/Http\/TemplateResponse.php(157): OC_Template->fetchPage()\n#11 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(113): OCP\\AppFramework\\Http\\TemplateResponse->render()\n#12 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php(114): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Files\\Controller\\ViewController), 'index')\n#13 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('ViewController', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#14 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#15 \/var\/www\/nextcloud\/lib\/private\/Route\/Router.php(299): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#16 \/var\/www\/nextcloud\/lib\/base.php(1004): OC\\Route\\Router->match('\/apps\/files\/')\n#17 \/var\/www\/nextcloud\/index.php(48): OC::handleRequest()\n#18 {main}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"fZ4Bj8V4gB7gs9tqW1N7","level":2,"time":"2018-01-22T16:47:04+00:00","remoteAddr":"IP-address-redacted","user":"admin","app":"core","method":"GET","url":"\/index.php\/apps\/files\/","message":"Failed to compile and\/or save \/var\/www\/nextcloud\/apps\/files_texteditor\/css\/merged.scss","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"fZ4Bj8V4gB7gs9tqW1N7","level":0,"time":"2018-01-22T16:47:04+00:00","remoteAddr":"IP-address-redacted","user":"admin","app":"files_texteditor","method":"GET","url":"\/index.php\/apps\/files\/","message":"Could not find resource file \"\/apps\/files_texteditor\/css\/merged.css\"","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"fZ4Bj8V4gB7gs9tqW1N7","level":3,"time":"2018-01-22T16:47:04+00:00","remoteAddr":"IP-address-redacted","user":"admin","app":"core","method":"GET","url":"\/index.php\/apps\/files\/","message":"Leafo\\ScssPhp\\Exception\\ParserException: parse error: failed at `$color-primary: ##5900b3;$color-primary-text: #ffffff;$color-primary-element: ##5900b3;@import \"systemtags.scss\";` (stdin) on line 1 in \/var\/www\/nextcloud\/3rdparty\/leafo\/scssphp\/src\/Parser.php:128\nStack trace:\n#0 \/var\/www\/nextcloud\/3rdparty\/leafo\/scssphp\/src\/Parser.php(169): Leafo\\ScssPhp\\Parser->throwParseError()\n#1 \/var\/www\/nextcloud\/3rdparty\/leafo\/scssphp\/src\/Compiler.php(186): Leafo\\ScssPhp\\Parser->parse('@import \"variab...')\n#2 \/var\/www\/nextcloud\/lib\/private\/Template\/SCSSCacher.php(215): Leafo\\ScssPhp\\Compiler->compile('@import \"variab...')\n#3 \/var\/www\/nextcloud\/lib\/private\/Template\/SCSSCacher.php(112): OC\\Template\\SCSSCacher->cache('\/var\/www\/nextcl...', '115d4b62b085acb...', 'systemtags.scss', Object(OC\\Files\\SimpleFS\\SimpleFolder), 'core\/css')\n#4 \/var\/www\/nextcloud\/lib\/private\/Template\/CSSResourceLocator.php(105): OC\\Template\\SCSSCacher->process('\/var\/www\/nextcl...', 'core\/css\/system...', 'core')\n#5 \/var\/www\/nextcloud\/lib\/private\/Template\/CSSResourceLocator.php(57): OC\\Template\\CSSResourceLocator->cacheAndAppendScssIfExist('\/var\/www\/nextcl...', 'core\/css\/system...')\n#6 \/var\/www\/nextcloud\/lib\/private\/Template\/ResourceLocator.php(76): OC\\Template\\CSSResourceLocator->doFind('css\/systemtags')\n#7 \/var\/www\/nextcloud\/lib\/private\/TemplateLayout.php(225): OC\\Template\\ResourceLocator->find(Array)\n#8 \/var\/www\/nextcloud\/lib\/private\/TemplateLayout.php(170): OC\\TemplateLayout::findStylesheetFiles(Array)\n#9 \/var\/www\/nextcloud\/lib\/private\/legacy\/template.php(205): OC\\TemplateLayout->__construct('user', 'files')\n#10 \/var\/www\/nextcloud\/lib\/public\/AppFramework\/Http\/TemplateResponse.php(157): OC_Template->fetchPage()\n#11 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(113): OCP\\AppFramework\\Http\\TemplateResponse->render()\n#12 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php(114): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Files\\Controller\\ViewController), 'index')\n#13 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('ViewController', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#14 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#15 \/var\/www\/nextcloud\/lib\/private\/Route\/Router.php(299): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#16 \/var\/www\/nextcloud\/lib\/base.php(1004): OC\\Route\\Router->match('\/apps\/files\/')\n#17 \/var\/www\/nextcloud\/index.php(48): OC::handleRequest()\n#18 {main}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"fZ4Bj8V4gB7gs9tqW1N7","level":2,"time":"2018-01-22T16:47:04+00:00","remoteAddr":"IP-address-redacted","user":"admin","app":"core","method":"GET","url":"\/index.php\/apps\/files\/","message":"Failed to compile and\/or save \/var\/www\/nextcloud\/core\/css\/systemtags.scss","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"fZ4Bj8V4gB7gs9tqW1N7","level":3,"time":"2018-01-22T16:47:04+00:00","remoteAddr":"IP-address-redacted","user":"admin","app":"cssresourceloader","method":"GET","url":"\/index.php\/apps\/files\/","message":"Could not find resource css\/systemtags.css to load","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"iqX1o71kljPkNnXX3zCS","level":0,"time":"2018-01-22T16:47:05+00:00","remoteAddr":"IP-address-redacted","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Run OC\\Command\\CommandJob job with ID 499","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"iqX1o71kljPkNnXX3zCS","level":0,"time":"2018-01-22T16:47:05+00:00","remoteAddr":"IP-address-redacted","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Finished OC\\Command\\CommandJob job with ID 499 in 0 seconds","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}
root@HOSTNAME:/var/log# tail -f nextcloud.log
{"reqId":"fZ4Bj8V4gB7gs9tqW1N7","level":2,"time":"2018-01-22T16:47:04+00:00","remoteAddr":"IP-address-redacted","user":"admin","app":"core","method":"GET","url":"\/index.php\/apps\/files\/","message":"Failed to compile and\/or save \/var\/www\/nextcloud\/apps\/files_sharing\/css\/mergedAdditionalStyles.scss","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"fZ4Bj8V4gB7gs9tqW1N7","level":0,"time":"2018-01-22T16:47:04+00:00","remoteAddr":"IP-address-redacted","user":"admin","app":"files_sharing","method":"GET","url":"\/index.php\/apps\/files\/","message":"Could not find resource file \"\/apps\/files_sharing\/css\/mergedAdditionalStyles.css\"","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"fZ4Bj8V4gB7gs9tqW1N7","level":3,"time":"2018-01-22T16:47:04+00:00","remoteAddr":"IP-address-redacted","user":"admin","app":"core","method":"GET","url":"\/index.php\/apps\/files\/","message":"Leafo\\ScssPhp\\Exception\\ParserException: parse error: failed at `$color-primary: ##5900b3;$color-primary-text: #ffffff;$color-primary-element: ##5900b3;@import \"merged.scss\";` (stdin) on line 1 in \/var\/www\/nextcloud\/3rdparty\/leafo\/scssphp\/src\/Parser.php:128\nStack trace:\n#0 \/var\/www\/nextcloud\/3rdparty\/leafo\/scssphp\/src\/Parser.php(169): Leafo\\ScssPhp\\Parser->throwParseError()\n#1 \/var\/www\/nextcloud\/3rdparty\/leafo\/scssphp\/src\/Compiler.php(186): Leafo\\ScssPhp\\Parser->parse('@import \"variab...')\n#2 \/var\/www\/nextcloud\/lib\/private\/Template\/SCSSCacher.php(215): Leafo\\ScssPhp\\Compiler->compile('@import \"variab...')\n#3 \/var\/www\/nextcloud\/lib\/private\/Template\/SCSSCacher.php(112): OC\\Template\\SCSSCacher->cache('\/var\/www\/nextcl...', '115d4b62b085acb...', 'merged.scss', Object(OC\\Files\\SimpleFS\\SimpleFolder), 'apps\/files_text...')\n#4 \/var\/www\/nextcloud\/lib\/private\/Template\/CSSResourceLocator.php(105): OC\\Template\\SCSSCacher->process('\/var\/www\/nextcl...', 'css\/merged.scss', 'files_textedito...')\n#5 \/var\/www\/nextcloud\/lib\/private\/Template\/CSSResourceLocator.php(80): OC\\Template\\CSSResourceLocator->cacheAndAppendScssIfExist('\/var\/www\/nextcl...', 'css\/merged.scss', 'files_textedito...')\n#6 \/var\/www\/nextcloud\/lib\/private\/Template\/ResourceLocator.php(76): OC\\Template\\CSSResourceLocator->doFind('css\/merged')\n#7 \/var\/www\/nextcloud\/lib\/private\/TemplateLayout.php(225): OC\\Template\\ResourceLocator->find(Array)\n#8 \/var\/www\/nextcloud\/lib\/private\/TemplateLayout.php(170): OC\\TemplateLayout::findStylesheetFiles(Array)\n#9 \/var\/www\/nextcloud\/lib\/private\/legacy\/template.php(205): OC\\TemplateLayout->__construct('user', 'files')\n#10 \/var\/www\/nextcloud\/lib\/public\/AppFramework\/Http\/TemplateResponse.php(157): OC_Template->fetchPage()\n#11 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(113): OCP\\AppFramework\\Http\\TemplateResponse->render()\n#12 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php(114): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Files\\Controller\\ViewController), 'index')\n#13 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('ViewController', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#14 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#15 \/var\/www\/nextcloud\/lib\/private\/Route\/Router.php(299): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#16 \/var\/www\/nextcloud\/lib\/base.php(1004): OC\\Route\\Router->match('\/apps\/files\/')\n#17 \/var\/www\/nextcloud\/index.php(48): OC::handleRequest()\n#18 {main}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"fZ4Bj8V4gB7gs9tqW1N7","level":2,"time":"2018-01-22T16:47:04+00:00","remoteAddr":"IP-address-redacted","user":"admin","app":"core","method":"GET","url":"\/index.php\/apps\/files\/","message":"Failed to compile and\/or save \/var\/www\/nextcloud\/apps\/files_texteditor\/css\/merged.scss","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"fZ4Bj8V4gB7gs9tqW1N7","level":0,"time":"2018-01-22T16:47:04+00:00","remoteAddr":"IP-address-redacted","user":"admin","app":"files_texteditor","method":"GET","url":"\/index.php\/apps\/files\/","message":"Could not find resource file \"\/apps\/files_texteditor\/css\/merged.css\"","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"fZ4Bj8V4gB7gs9tqW1N7","level":3,"time":"2018-01-22T16:47:04+00:00","remoteAddr":"IP-address-redacted","user":"admin","app":"core","method":"GET","url":"\/index.php\/apps\/files\/","message":"Leafo\\ScssPhp\\Exception\\ParserException: parse error: failed at `$color-primary: ##5900b3;$color-primary-text: #ffffff;$color-primary-element: ##5900b3;@import \"systemtags.scss\";` (stdin) on line 1 in \/var\/www\/nextcloud\/3rdparty\/leafo\/scssphp\/src\/Parser.php:128\nStack trace:\n#0 \/var\/www\/nextcloud\/3rdparty\/leafo\/scssphp\/src\/Parser.php(169): Leafo\\ScssPhp\\Parser->throwParseError()\n#1 \/var\/www\/nextcloud\/3rdparty\/leafo\/scssphp\/src\/Compiler.php(186): Leafo\\ScssPhp\\Parser->parse('@import \"variab...')\n#2 \/var\/www\/nextcloud\/lib\/private\/Template\/SCSSCacher.php(215): Leafo\\ScssPhp\\Compiler->compile('@import \"variab...')\n#3 \/var\/www\/nextcloud\/lib\/private\/Template\/SCSSCacher.php(112): OC\\Template\\SCSSCacher->cache('\/var\/www\/nextcl...', '115d4b62b085acb...', 'systemtags.scss', Object(OC\\Files\\SimpleFS\\SimpleFolder), 'core\/css')\n#4 \/var\/www\/nextcloud\/lib\/private\/Template\/CSSResourceLocator.php(105): OC\\Template\\SCSSCacher->process('\/var\/www\/nextcl...', 'core\/css\/system...', 'core')\n#5 \/var\/www\/nextcloud\/lib\/private\/Template\/CSSResourceLocator.php(57): OC\\Template\\CSSResourceLocator->cacheAndAppendScssIfExist('\/var\/www\/nextcl...', 'core\/css\/system...')\n#6 \/var\/www\/nextcloud\/lib\/private\/Template\/ResourceLocator.php(76): OC\\Template\\CSSResourceLocator->doFind('css\/systemtags')\n#7 \/var\/www\/nextcloud\/lib\/private\/TemplateLayout.php(225): OC\\Template\\ResourceLocator->find(Array)\n#8 \/var\/www\/nextcloud\/lib\/private\/TemplateLayout.php(170): OC\\TemplateLayout::findStylesheetFiles(Array)\n#9 \/var\/www\/nextcloud\/lib\/private\/legacy\/template.php(205): OC\\TemplateLayout->__construct('user', 'files')\n#10 \/var\/www\/nextcloud\/lib\/public\/AppFramework\/Http\/TemplateResponse.php(157): OC_Template->fetchPage()\n#11 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(113): OCP\\AppFramework\\Http\\TemplateResponse->render()\n#12 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php(114): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Files\\Controller\\ViewController), 'index')\n#13 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('ViewController', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#14 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#15 \/var\/www\/nextcloud\/lib\/private\/Route\/Router.php(299): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#16 \/var\/www\/nextcloud\/lib\/base.php(1004): OC\\Route\\Router->match('\/apps\/files\/')\n#17 \/var\/www\/nextcloud\/index.php(48): OC::handleRequest()\n#18 {main}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"fZ4Bj8V4gB7gs9tqW1N7","level":2,"time":"2018-01-22T16:47:04+00:00","remoteAddr":"IP-address-redacted","user":"admin","app":"core","method":"GET","url":"\/index.php\/apps\/files\/","message":"Failed to compile and\/or save \/var\/www\/nextcloud\/core\/css\/systemtags.scss","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"fZ4Bj8V4gB7gs9tqW1N7","level":3,"time":"2018-01-22T16:47:04+00:00","remoteAddr":"IP-address-redacted","user":"admin","app":"cssresourceloader","method":"GET","url":"\/index.php\/apps\/files\/","message":"Could not find resource css\/systemtags.css to load","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"iqX1o71kljPkNnXX3zCS","level":0,"time":"2018-01-22T16:47:05+00:00","remoteAddr":"IP-address-redacted","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Run OC\\Command\\CommandJob job with ID 499","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"iqX1o71kljPkNnXX3zCS","level":0,"time":"2018-01-22T16:47:05+00:00","remoteAddr":"IP-address-redacted","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Finished OC\\Command\\CommandJob job with ID 499 in 0 seconds","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"VjuW1EtNUZuCQDWNAQcs","level":0,"time":"2018-01-22T16:48:47+00:00","remoteAddr":"IP-address-redacted","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Run OC\\Command\\CommandJob job with ID 500","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}
{"reqId":"VjuW1EtNUZuCQDWNAQcs","level":0,"time":"2018-01-22T16:48:47+00:00","remoteAddr":"IP-address-redacted","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Finished OC\\Command\\CommandJob job with ID 500 in 0 seconds","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"12.0.4.3"}

</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

### PR DESCRIPTION
**Pull request by juliusknorr**
- Do not assume that empty CSS files are cached
- Use default scss variables in case the injected variables are somehow invalid (fixes https://github.com/nextcloud/server/issues/7977)
- Make sure we only build the injected variables string once
- Do not rewrite absolute URLs (starting with /)
  - With this we can remove the getAbsoluteUrl call from the the theming app, so the SCSSCacher will not interpret different domains as changes (fixes https://github.com/nextcloud/server/issues/6752)

### CODE REVIEW

File: lib/private/Template/SCSSCacher.php [hunk 1]
```diff
@@ -148,13 +156,14 @@ private function isCached($fileNameCSS, ISimpleFolder $folder) {
 				}
 				$deps = json_decode($deps, true);
 
-				foreach ($deps as $file=>$mtime) {
+				foreach ((array)$deps as $file=>$mtime) {
 					if (!file_exists($file) || filemtime($file) > $mtime) {
 						return false;
 					}
 				}
+				return true;
```
Comment (rullzer) [inline lib/private/Template/SCSSCacher.php]: yes please... the old code was clearly me messing up :wink:

**Comment by skjnldsv** [comment]
Awesome!!! Thanks @juliushaertl !

**Review by rullzer — APPROVED** [review]
:rocket:

**Review by MorrisJobke — APPROVED** [review]

**Comment by juliushaertl** [comment]
backport at https://github.com/nextcloud/server/pull/8156
