### PR TITLE
fix(core): ensure unique vcategory

### LINKED ISSUE #54087: [Bug]: Incomplete handling for tags with the same name
### Bug description

We received a report that some files marked as favorites are not displayed in the "Favorites" view. Additionally, users cannot remove the favorite state from these files. This issue is similar to https://github.com/nextcloud/server/issues/49395.

- [ ] The lib/private/Tags.php implementation does not properly verify if a given tag already exists. Although a check exists, the list of tags is loaded only once and never updated.
- [ ] The database table lacks a unique constraint, allowing multiple identical tags for the same user.

I've started working on patch: https://github.com/nextcloud/server/pull/49674

But adding that index on existing systems and ironing out the various issues I ran into while diving through the code needs more work, and therefore we would appreciate the files team taking over.

### Steps to reproduce

1. Delete the favorite tag from oc_vcategory
2. Select 2 or more files
3. Mark the files as favorite (as batch action)

The code in lib/private/Tags.php does not check if the given tag already exists properly. There's a check, but the list of tags is loaded only once and never updated. Also, there's no unique constraint on the table, and therefore it's a valid state to have the tag more than once for a user.

Image

### Expected behavior

Tags with the same name should be handled gracefully.

### PR DESCRIPTION
**Pull request by skjnldsv**
* Resolves https://github.com/nextcloud/server/issues/54087
* Closes https://github.com/nextcloud/server/pull/49674

## Summary
image

### CODE REVIEW

File: core/Listener/AddMissingIndicesListener.php [hunk 1]
```diff
@@ -210,5 +210,11 @@ public function handle(Event $event): void {
 			'systag_objecttype',
 			['objecttype']
 		);
+
+		$event->addMissingUniqueIndex(
+			'vcategory',
+			'unique_category_per_user',
+			['uid', 'type', 'category']
+		);
```
Comment (skjnldsv) [inline core/Listener/AddMissingIndicesListener.php:218]: Docs suggest to not add this into the migration for performance purposes.
But this is an important index. Is this still the right way to do this ?

https://docs.nextcloud.com/server/stable/developer_manual/basics/storage/migrations.html#adding-indices

File: core/Migrations/Version32000Date20250731062008.php [hunk 2]
```diff
@@ -0,0 +1,126 @@
...
+
+	/**
+	 * @param IOutput $output
+	 * @param Closure(): ISchemaWrapper $schemaClosure
+	 * @param array $options
+	 */
+	#[Override]
+	public function postSchemaChange(IOutput $output, Closure $schemaClosure, array $options): void {
+	}
+
```
Comment (come-nc) [inline core/Migrations/Version32000Date20250731062008.php]:
```suggestion
```
Do not override methods for no reason.

File: lib/private/Tags.php [hunk 3]
```diff
@@ -268,15 +268,17 @@ public function hasTag(string $name): bool {
 	public function add(string $name) {
 		$name = trim($name);
 
-		if ($name === '') {
+		if (empty($name)) {
```
Comment (come-nc) [inline lib/private/Tags.php]: :crying_cat_face:

File: lib/private/Tags.php [hunk 4]
```diff
@@ -547,7 +554,7 @@ public function tagAs($objid, $tag, string $path = '') {
 	public function unTag($objid, $tag, string $path = '') {
 		if (is_string($tag) && !is_numeric($tag)) {
 			$tag = trim($tag);
-			if ($tag === '') {
+			if (empty($tag)) {
 				$this->logger->debug(__METHOD__ . ', Tag name is empty');
 				return false;
 			}
```
Comment (come-nc) [inline lib/private/Tags.php]: I do not get the changes in this file?

**Review by come-nc — COMMENTED** [review]
Did I miss it or is there no change apart from the unique index?

File: core/Listener/AddMissingIndicesListener.php (hunk 1 above)
Comment (come-nc) [reply core/Listener/AddMissingIndicesListener.php:218]: Yes I think so, it’s to avoid having a really long migration. It helps admin plan for heavy DB steps.

File: core/Migrations/Version32000Date20250731062008.php (hunk 2 above)
Comment (skjnldsv) [reply core/Migrations/Version32000Date20250731062008.php]: That was the default generated file :see_no_evil:

File: lib/private/Tags.php (hunk 3 above)
Comment (skjnldsv) [reply lib/private/Tags.php]: Isn't it the recommended way? I remember seeing a discussion on this on tech debt :grin: 
It's not necessary, just because I saw it at the same time I was working on those files :)

File: lib/private/Tags.php (hunk 4 above)
Comment (skjnldsv) [reply lib/private/Tags.php]: Removing the `// TODO use unique db properties instead of an additional check`
Then got carried away on fixing one empty, then another.. Then it got out of hand

File: lib/private/Tags.php (hunk 3 above)
Comment (skjnldsv) [reply lib/private/Tags.php]: Removed

Comment (come-nc) [reply lib/private/Tags.php]: No we usually move the other way around, psalm hates empty.
`empty` is too much magic.
For instance, `'0'` is empty, is that not a valid tag name? Why? `'1'` is accepted.

**Comment by skjnldsv** [comment]
> Did I miss it or is there no change apart from the unique index?

the removal of duplicates in the migration ?

**Comment by come-nc** [comment]
> > Did I miss it or is there no change apart from the unique index?
> 
> the removal of duplicates in the migration ?

But that’s fixing the existing, but how did they get in there?
The code path that previously added them will now blow up with a DB exception, no?

**Comment by skjnldsv** [comment]
> But that’s fixing the existing, but how did they get in there? The code path that previously added them will now blow up with a DB exception, no?

As far as I understood, it's some very edge case where on a race condition, we cache the list of existing tags which means we can allow multiple to be created because the tag existing check won't have the most recent list.

Erroring out is ok from me :shrug: 
The goal is to fix the existing data and preventing it from happening again.
Allowing to handle favorites again

**Review by come-nc — APPROVED** [review]

**Review by kesselb — APPROVED** [review]
Thanks 🙏

File: core/Migrations/Version32000Date20250731062008.php [hunk 5]
```diff
@@ -0,0 +1,106 @@
...
+use OCP\DB\ISchemaWrapper;
+use OCP\IDBConnection;
+use OCP\Migration\IOutput;
+use OCP\Migration\SimpleMigrationStep;
+use Override;
+
+/**
+ * Make sure vcategory entries are unique per user and type
+ * This migration will clean up existing duplicates
+ * and add a unique constraint to prevent future duplicates.
```
Comment (nickvergessen) [inline core/Migrations/Version32000Date20250731062008.php:22]: It doesn't?

Comment (skjnldsv) [reply core/Migrations/Version32000Date20250731062008.php:22]: Leftover comment from previous approach.
