### PR TITLE
Cache fetched apps in update check

### LINKED ISSUE #7235: Slow performance when using Amazon S3 as primary storage
### Steps to reproduce
1. Setup a new nextcloud instance / don't enter admin password and database details yet!
2. After first opening of the setup screen, open config/config.php
3. Add your S3 bucket details:

`'objectstore' =>
  array (
    'class' => 'OC\\Files\\ObjectStore\\S3',
    'arguments' =>
    array (
      'bucket' => 'my-nextcloud-s3bucket',
      'autocreate' => true,
      'key' => 'ABC',
      'secret' => 'XYZ',
      'use_ssl' => true,
      'use_path_style' => false,
    ),
  ),`

4. Reload now the setup page
5. Enter admin password, database details, etc. to finish your Nextcloud installation

### Expected behaviour
You will be redirected after a few seconds to the "files"-section where you can upload and manage your files. Of course, I expect a bit slower behavior because file requests are not handled locally. Other sections like Apps or Settings should work normal.

### Actual behaviour

Loading of any elements is very slow after using S3 as primary storage, although the connection to the S3 service is very fast (~3 MB/sec. when downloading files directly from the S3 bucket).

The first login takes 1-2 minutes. I used Firefox 57.0 Dev Tools to meter the loading times: 

- 18,49s / Opening the "deactivated apps" Section
- 39,66s / Activating the module "Default encryption module"
- 20,79s / Opening the settings page
- 10,08s / Opening "encryption" section
- 1min, 33s / Login (including redirect from /login to /apps/files)

I was testing the same issue with Nextcloud 11, which was much faster than 12.0.3.

### Server configuration

**Operating system**: macOS 10.13 / Docker-Image based on Debian 8.9 "Jessie"

**Web server:** Apache/2.4.10 (Debian) 

**Database:** mysqld 10.2.10-MariaDB-10.2.10+maria~jessie

**PHP version:** PHP/7.1.11

**Nextcloud version:** 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** Nextcloud docker image

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - encryption: 1.6.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - files_external
  - user_external
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

`{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "oc1rx24w5lvn",
        "objectstore": {
            "class": "OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "bucket": "my-nextcloud-bucket",
                "autocreate": true,
                "key": "XXX",
                "secret": "XXX",
                "use_ssl": true,
                "use_path_style": false
            }
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost:8080"
        ],
        "datadirectory": "\/var\/www\/data",
        "overwrite.cli.url": "http:\/\/localhost:8080",
        "dbtype": "mysql",
        "version": "12.0.3.3",
        "dbname": "nextcloud",
        "dbhost": "db",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true
    }
}`

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
Amazon S3 (no clone, no Swift)

**Are you using encryption:** yes/no
Yes, but this doesn't make a difference, see above (first it was deactivated, during this test I activated it).

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox 57.0

**Operating system:**
macOS 10.13

<details>
<summary>Web server error log</summary>

error.log:
`AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.21.0.4. Set the 'ServerName' directive globally to suppress this message
[Tue Nov 21 10:30:52.701394 2017] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.10 (Debian) PHP/7.1.11 configured -- resuming normal operations
[Tue Nov 21 10:30:52.702204 2017] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Tue Nov 21 10:44:06.597205 2017] [php7:error] [pid 66] [client 172.21.0.1:45060] PHP Fatal error:  Uncaught Error: Access to undeclared static property: OC\\Files\\Filesystem::$normalizedPathCache in /var/www/html/lib/private/Files/Filesystem.php:804\nStack trace:\n#0 /var/www/html/lib/private/Files/View.php(2039): OC\\Files\\Filesystem::normalizePath('/admin/files/b8...')\n#1 /var/www/html/lib/private/Files/View.php(1170): OC\\Files\\View->unlockFile('/b807c2282ab0a4...', 1)\n#2 [internal function]: OC\\Files\\View->OC\\Files\\{closure}()\n#3 /var/www/html/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure))\n#4 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_close()\n#5 {main}\n  thrown in /var/www/html/lib/private/Files/Filesystem.php on line 804
[Tue Nov 21 10:46:03.569427 2017] [php7:error] [pid 102] [client 172.21.0.1:45366] PHP Fatal error:  Uncaught Error: Access to undeclared static property: OC\\Files\\Filesystem::$normalizedPathCache in /var/www/html/lib/private/Files/Filesystem.php:804\nStack trace:\n#0 /var/www/html/lib/private/Files/View.php(2039): OC\\Files\\Filesystem::normalizePath('/admin/files/b8...')\n#1 /var/www/html/lib/private/Files/View.php(1170): OC\\Files\\View->unlockFile('/b807c2282ab0a4...', 1)\n#2 [internal function]: OC\\Files\\View->OC\\Files\\{closure}()\n#3 /var/www/html/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure))\n#4 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_close()\n#5 {main}\n  thrown in /var/www/html/lib/private/Files/Filesystem.php on line 804
`

access.log:
`172.21.0.1 - - [21/Nov/2017:10:31:53 +0000] "GET / HTTP/1.1" 200 3735 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/vendor/strengthify/strengthify.css?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 875 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/css/jquery-ui-fixes.css?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 1152 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/css/guest.css?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 4760 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/css/jquery.ocdialog.css?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 965 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/vendor/jquery-ui/themes/base/jquery-ui.css?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 6310 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/vendor/select2/select2.css?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 3432 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/js/jquery.ocdialog.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 1995 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/js/eventsource.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 2039 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/js/oc-dialogs.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 7892 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/js/js.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 19190 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/js/l10n.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 2829 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/js/octemplate.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 1751 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/js/oc-requesttoken.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 518 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/js/apps.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 1555 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/js/config.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 1097 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/js/public/appconfig.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 1346 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/js/mimetypelist.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 1427 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/js/mimetype.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 1673 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/js/oc-backbone.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 554 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/js/select2-toggleselect.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 968 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/js/placeholder.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 2321 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/js/jquery.avatar.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 2193 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/search/js/search.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 3845 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/l10n/de.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 12552 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/vendor/strengthify/jquery.strengthify.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 2797 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/js/jquery.contactsmenu.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 1408 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/js/setup.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 1895 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/js/jquery-ui-fixes.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 558 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/js/files/fileinfo.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 1238 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/js/contactsmenu.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 3803 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/js/files/client.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 5489 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/js/jquery-showpassword.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 1582 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/js/installation.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 446 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/vendor/core.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 276990 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/img/actions/caret.svg HTTP/1.1" 200 485 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/img/actions/info-white.svg?v=2 HTTP/1.1" 200 881 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/img/actions/toggle.svg?v=1 HTTP/1.1" 200 598 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/img/background.jpg?v=1 HTTP/1.1" 200 95501 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:31:54 +0000] "GET /core/vendor/zxcvbn/dist/zxcvbn.js HTTP/1.1" 200 399984 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
127.0.0.1 - - [21/Nov/2017:10:31:59 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.10 (Debian) PHP/7.1.11 (internal dummy connection)"
127.0.0.1 - - [21/Nov/2017:10:32:00 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.10 (Debian) PHP/7.1.11 (internal dummy connection)"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET / HTTP/1.1" 200 3655 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/css/jquery-ui-fixes.css?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 1152 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/css/jquery.ocdialog.css?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 965 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/css/guest.css?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 4760 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/vendor/jquery-ui/themes/base/jquery-ui.css?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 6310 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/vendor/strengthify/strengthify.css?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 875 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/vendor/select2/select2.css?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 3432 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/js/oc-dialogs.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 7892 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/js/js.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 19190 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/js/l10n.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 2829 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/js/jquery.ocdialog.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 1995 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/js/octemplate.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 1751 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/js/eventsource.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 2039 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/js/oc-requesttoken.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 518 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/js/apps.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 1555 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/js/config.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 1097 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/js/public/appconfig.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 1346 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/js/mimetype.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 1673 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/js/mimetypelist.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 1427 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/js/oc-backbone.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 554 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/js/select2-toggleselect.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 968 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/js/placeholder.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 2321 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/js/jquery.avatar.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 2193 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/js/jquery.contactsmenu.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 1408 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/js/setup.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 1895 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/search/js/search.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 3845 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/vendor/strengthify/jquery.strengthify.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 2797 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/l10n/de.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 12552 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/js/files/fileinfo.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 1238 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/js/jquery-ui-fixes.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 558 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/js/contactsmenu.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 3803 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/js/jquery-showpassword.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 1582 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/js/files/client.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 5489 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/js/installation.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 446 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/vendor/core.js?v=ba222ded25d957b900c03bef914333cd HTTP/1.1" 200 276990 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/img/background.jpg?v=1 HTTP/1.1" 304 182 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/img/actions/caret.svg HTTP/1.1" 304 179 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/img/actions/toggle.svg?v=1 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/img/logo-icon.svg?v=1 HTTP/1.1" 200 1338 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/img/actions/info-white.svg?v=2 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:32:49 +0000] "GET /core/vendor/zxcvbn/dist/zxcvbn.js HTTP/1.1" 200 399984 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
127.0.0.1 - - [21/Nov/2017:10:32:55 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.10 (Debian) PHP/7.1.11 (internal dummy connection)"
172.21.0.1 - - [21/Nov/2017:10:33:07 +0000] "POST /index.php HTTP/1.1" 302 1100 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:04 +0000] "GET /index.php/apps/files/ HTTP/1.1" 200 7403 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:57 +0000] "GET /core/css/jquery-ui-fixes.css?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 1152 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:57 +0000] "GET /apps/files_pdfviewer/css/style.css?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 449 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:57 +0000] "GET /apps/files_videoplayer/css/style.css?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 2177 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:57 +0000] "GET /apps/files_versions/css/versions.css?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 807 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:57 +0000] "GET /core/vendor/select2/select2.css?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 3432 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:57 +0000] "GET /core/vendor/jquery-ui/themes/base/jquery-ui.css?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 6310 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:57 +0000] "GET /core/css/jquery.ocdialog.css?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 964 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:57 +0000] "GET /apps/notifications/css/styles.css?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 1313 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:57 +0000] "GET /apps/files_trashbin/css/trash.css?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 821 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:57 +0000] "GET /apps/comments/css/comments.css?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 1403 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:57 +0000] "GET /apps/firstrunwizard/css/colorbox.css?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 1121 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:57 +0000] "GET /apps/activity/css/style.css?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 1702 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:57 +0000] "GET /apps/firstrunwizard/css/firstrunwizard.css?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 839 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:57 +0000] "GET /apps/gallery/css/gallerybutton.css?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 1239 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:57 +0000] "GET /apps/gallery/css/slideshow.css?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 1621 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:57 +0000] "GET /apps/systemtags/css/systemtagsfilelist.css?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 776 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:57 +0000] "GET /apps/gallery/css/share.css?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 1655 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:57 +0000] "GET /settings/img/admin.svg?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28 HTTP/1.1" 200 627 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:57 +0000] "GET /apps/activity/img/activity.svg?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28 HTTP/1.1" 200 504 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:57 +0000] "GET /apps/files/img/app.svg?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28 HTTP/1.1" 200 821 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:57 +0000] "GET /settings/img/personal.svg?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28 HTTP/1.1" 200 1243 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:57 +0000] "GET /apps/gallery/img/app.svg?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28 HTTP/1.1" 200 858 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:57 +0000] "GET /settings/img/help.svg?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28 HTTP/1.1" 200 868 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:57 +0000] "GET /settings/img/users.svg?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28 HTTP/1.1" 200 1978 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:57 +0000] "GET /settings/img/apps.svg?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28 HTTP/1.1" 200 471 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:57 +0000] "GET /core/img/actions/logout.svg?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28 HTTP/1.1" 200 946 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:57 +0000] "GET /core/vendor/core.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 276990 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:58 +0000] "GET /core/search/js/search.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 3845 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:58 +0000] "GET /core/l10n/de.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 12552 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:58 +0000] "GET /core/js/backgroundjobs.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 938 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:58 +0000] "GET /apps/files_pdfviewer/js/previewplugin.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 2205 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:58 +0000] "GET /apps/files_videoplayer/js/viewer.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 1773 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:58 +0000] "GET /apps/gallery/l10n/de.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 3580 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:58 +0000] "GET /apps/notifications/l10n/de.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 508 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:58 +0000] "GET /core/js/jquery-ui-fixes.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 558 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:58 +0000] "GET /core/js/files/fileinfo.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 1238 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:58 +0000] "GET /core/js/files/client.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 5489 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:58 +0000] "GET /core/js/contactsmenu.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 3803 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:58 +0000] "GET /apps/files/l10n/de.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 4180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:58 +0000] "GET /apps/files_sharing/l10n/de.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 2916 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:58 +0000] "GET /apps/files_sharing/js/app.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 1897 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:58 +0000] "GET /apps/files_sharing/js/sharedfilelist.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 4469 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:58 +0000] "GET /apps/files_trashbin/l10n/de.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 886 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:58 +0000] "GET /apps/files_trashbin/js/app.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 1458 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:58 +0000] "GET /apps/files_trashbin/js/filelist.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 3470 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:58 +0000] "GET /apps/activity/l10n/de.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 1762 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:58 +0000] "GET /core/js/oc-backbone-webdav.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 3369 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:58 +0000] "GET /apps/comments/l10n/de.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 1122 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:58 +0000] "GET /apps/federatedfilesharing/l10n/de.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 2361 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:58 +0000] "GET /apps/federatedfilesharing/js/external.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 2127 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:58 +0000] "GET /apps/files_texteditor/l10n/de.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 1135 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:59 +0000] "GET /apps/files_versions/l10n/de.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 695 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:59 +0000] "GET /apps/firstrunwizard/l10n/de.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 1563 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:59 +0000] "GET /apps/firstrunwizard/js/jquery.colorbox.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 9193 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:59 +0000] "GET /apps/firstrunwizard/js/firstrunwizard.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 630 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:59 +0000] "GET /apps/firstrunwizard/js/activate.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 353 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:59 +0000] "GET /apps/systemtags/l10n/de.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 1371 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:59 +0000] "GET /core/img/logo.svg?v=0 HTTP/1.1" 200 1521 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:59 +0000] "GET /core/img/actions/more-white.svg?v=1 HTTP/1.1" 200 587 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:59 +0000] "GET /core/img/places/contacts.svg?v=1 HTTP/1.1" 200 2017 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:59 +0000] "GET /core/img/actions/settings-white.svg?v=1 HTTP/1.1" 200 1215 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:59 +0000] "GET /apps/gallery/config?extramediatypes=1 HTTP/1.1" 200 980 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:59 +0000] "GET /apps/firstrunwizard/wizard HTTP/1.1" 200 1846 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:00 +0000] "GET /core/img/desktopapp.svg HTTP/1.1" 200 11990 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:00 +0000] "GET /core/img/actions/view-close.svg HTTP/1.1" 200 886 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:00 +0000] "GET /core/img/googleplay.png HTTP/1.1" 200 18206 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:00 +0000] "GET /core/img/appstore.svg HTTP/1.1" 200 8494 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:00 +0000] "GET /core/img/places/calendar-dark.svg HTTP/1.1" 200 850 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:00 +0000] "GET /core/img/places/contacts-dark.svg HTTP/1.1" 200 2018 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:00 +0000] "GET /apps/files/img/folder.svg HTTP/1.1" 200 526 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:00 +0000] "GET /core/img/background.jpg HTTP/1.1" 200 95501 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:00 +0000] "GET /core/img/logo-icon.svg HTTP/1.1" 200 1338 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:59 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 324 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:59 +0000] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 4408 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:34:59 +0000] "GET /cron.php HTTP/1.1" 200 915 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:00 +0000] "GET /apps/systemtags/lastused HTTP/1.1" 200 878 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:01 +0000] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.1" 200 1079 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:04 +0000] "DELETE /apps/firstrunwizard/wizard HTTP/1.1" 200 878 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
127.0.0.1 - - [21/Nov/2017:10:35:10 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.10 (Debian) PHP/7.1.11 (internal dummy connection)"
172.21.0.1 - - [21/Nov/2017:10:35:13 +0000] "GET /settings/apps HTTP/1.1" 200 6501 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:15 +0000] "GET /settings/css/settings.css?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 5659 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:15 +0000] "GET /core/vendor/marked/marked.min.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 6009 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:15 +0000] "GET /settings/l10n/de.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 14738 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:15 +0000] "GET /settings/js/settings.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 1488 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:15 +0000] "GET /settings/js/apps.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-0 HTTP/1.1" 200 7488 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:15 +0000] "GET /cron.php HTTP/1.1" 200 915 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:15 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 726 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:15 +0000] "GET /settings/apps/categories HTTP/1.1" 200 1913 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:29 +0000] "GET /core/vendor/purify.min.js.map HTTP/1.1" 302 1424 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:29 +0000] "GET /login HTTP/1.1" 200 4532 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:45 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 726 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:15 +0000] "GET /settings/apps/list?category=installed HTTP/1.1" 200 41777 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /core/img/actions/checkmark.svg?v=1 HTTP/1.1" 200 481 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/systemtags/img/app.svg HTTP/1.1" 200 715 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/activity/img/activity.svg HTTP/1.1" 200 504 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/comments/img/comments.svg HTTP/1.1" 200 529 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/files_trashbin/img/app.svg HTTP/1.1" 200 552 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/federation/img/app.svg HTTP/1.1" 200 750 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/firstrunwizard/img/app.svg HTTP/1.1" 200 1849 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/files_sharing/img/app.svg HTTP/1.1" 200 750 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/gallery/img/app.svg HTTP/1.1" 200 858 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/logreader/img/app.svg HTTP/1.1" 200 799 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/serverinfo/img/app.svg HTTP/1.1" 200 717 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/nextcloud_announcements/img/app.svg HTTP/1.1" 200 1023 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/password_policy/img/app.svg HTTP/1.1" 200 653 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/files_pdfviewer/img/app.svg HTTP/1.1" 200 2434 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/sharebymail/img/app.svg HTTP/1.1" 200 750 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/files_texteditor/img/app.svg HTTP/1.1" 200 901 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/theming/img/app.svg HTTP/1.1" 200 898 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/updatenotification/img/app.svg HTTP/1.1" 200 573 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/survey_client/img/app.svg HTTP/1.1" 200 2085 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/files_versions/img/app.svg HTTP/1.1" 200 799 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/files_videoplayer/img/app.svg HTTP/1.1" 200 593 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /core/img/places/default-app-icon.svg HTTP/1.1" 200 1345 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/encryption/img/app.svg HTTP/1.1" 200 1377 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/user_external/img/app.svg HTTP/1.1" 200 1858 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/user_ldap/img/app.svg HTTP/1.1" 200 1238 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/files_external/img/app.svg HTTP/1.1" 200 654 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/notifications/img/notifications.svg?v=12.0.3.3 HTTP/1.1" 200 744 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/systemtags/img/app.svg?v=12.0.3.3 HTTP/1.1" 200 714 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/activity/img/activity.svg?v=12.0.3.3 HTTP/1.1" 200 504 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/comments/img/comments.svg?v=12.0.3.3 HTTP/1.1" 200 529 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/federation/img/app.svg?v=12.0.3.3 HTTP/1.1" 200 751 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/files_trashbin/img/app.svg?v=12.0.3.3 HTTP/1.1" 200 552 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/firstrunwizard/img/app.svg?v=12.0.3.3 HTTP/1.1" 200 1849 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/files_sharing/img/app.svg?v=12.0.3.3 HTTP/1.1" 200 750 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/logreader/img/app.svg?v=12.0.3.3 HTTP/1.1" 200 799 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/gallery/img/app.svg?v=12.0.3.3 HTTP/1.1" 200 858 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/serverinfo/img/app.svg?v=12.0.3.3 HTTP/1.1" 200 717 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/nextcloud_announcements/img/app.svg?v=12.0.3.3 HTTP/1.1" 200 1023 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/password_policy/img/app.svg?v=12.0.3.3 HTTP/1.1" 200 653 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/files_pdfviewer/img/app.svg?v=12.0.3.3 HTTP/1.1" 200 2434 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/sharebymail/img/app.svg?v=12.0.3.3 HTTP/1.1" 200 750 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/files_texteditor/img/app.svg?v=12.0.3.3 HTTP/1.1" 200 901 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/theming/img/app.svg?v=12.0.3.3 HTTP/1.1" 200 898 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/updatenotification/img/app.svg?v=12.0.3.3 HTTP/1.1" 200 573 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/survey_client/img/app.svg?v=12.0.3.3 HTTP/1.1" 200 2085 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/files_versions/img/app.svg?v=12.0.3.3 HTTP/1.1" 200 799 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/files_videoplayer/img/app.svg?v=12.0.3.3 HTTP/1.1" 200 593 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /core/img/places/default-app-icon.svg?v=12.0.3.3 HTTP/1.1" 200 1345 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/encryption/img/app.svg?v=12.0.3.3 HTTP/1.1" 200 1377 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/user_external/img/app.svg?v=12.0.3.3 HTTP/1.1" 200 1858 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/user_ldap/img/app.svg?v=12.0.3.3 HTTP/1.1" 200 1238 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:35:54 +0000] "GET /apps/files_external/img/app.svg?v=12.0.3.3 HTTP/1.1" 200 654 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
127.0.0.1 - - [21/Nov/2017:10:36:00 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.10 (Debian) PHP/7.1.11 (internal dummy connection)"
172.21.0.1 - - [21/Nov/2017:10:36:15 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 726 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:36:27 +0000] "GET /settings/apps/list?category=disabled HTTP/1.1" 200 9223 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:36:37 +0000] "GET /core/img/places/default-app-icon.svg HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:36:37 +0000] "GET /apps/encryption/img/app.svg HTTP/1.1" 304 181 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:36:37 +0000] "GET /apps/files_external/img/app.svg HTTP/1.1" 304 181 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:36:37 +0000] "GET /apps/user_external/img/app.svg HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:36:37 +0000] "GET /apps/user_ldap/img/app.svg HTTP/1.1" 304 181 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:36:45 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 726 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:37:15 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 726 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:37:36 +0000] "GET /core/templates/message.html HTTP/1.1" 200 464 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:37:36 +0000] "GET /core/img/actions/close.svg HTTP/1.1" 200 854 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:37:36 +0000] "GET /core/vendor/jquery-ui/themes/base/images/ui-icons_222222_256x240.png HTTP/1.1" 200 4656 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:37:41 +0000] "POST /login/confirm HTTP/1.1" 200 902 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:37:42 +0000] "POST /index.php/settings/ajax/enableapp.php HTTP/1.1" 200 948 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:37:45 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 726 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:37:42 +0000] "GET /apps/files HTTP/1.1" 200 7389 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:02 +0000] "GET /index.php/settings/ajax/navigationdetect.php HTTP/1.1" 200 1362 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:15 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 726 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:45 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 726 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:48 +0000] "GET /settings/admin HTTP/1.1" 200 7221 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:53 +0000] "GET /core/vendor/select2/select2.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 3432 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:53 +0000] "GET /core/css/jquery-ui-fixes.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1152 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:53 +0000] "GET /apps/files_pdfviewer/css/style.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 449 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:53 +0000] "GET /apps/files_versions/css/versions.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 807 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:53 +0000] "GET /core/vendor/jquery-ui/themes/base/jquery-ui.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 6310 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:53 +0000] "GET /apps/files_videoplayer/css/style.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 2176 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:53 +0000] "GET /apps/notifications/css/styles.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1313 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:53 +0000] "GET /settings/css/settings.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 5659 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:53 +0000] "GET /core/css/jquery.ocdialog.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 964 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:53 +0000] "GET /core/vendor/core.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 276990 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:53 +0000] "GET /css/core/37d007a56d816107ce5b52c10342db37-server.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 14537 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:53 +0000] "GET /css/core/37d007a56d816107ce5b52c10342db37-share.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 2042 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:55 +0000] "GET /settings/img/admin.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 200 627 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:55 +0000] "GET /settings/img/personal.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 200 1243 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:55 +0000] "GET /apps/gallery/img/app.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 200 858 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:55 +0000] "GET /settings/img/apps.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 200 471 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:55 +0000] "GET /apps/files/img/app.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 200 821 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:55 +0000] "GET /apps/activity/img/activity.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 200 504 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:55 +0000] "GET /settings/img/help.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 200 868 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:55 +0000] "GET /settings/img/users.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 200 1978 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:55 +0000] "GET /core/img/actions/logout.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 200 946 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:55 +0000] "GET /settings/img/admin.svg HTTP/1.1" 200 627 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:55 +0000] "GET /apps/serverinfo/img/app-dark.svg HTTP/1.1" 200 717 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:55 +0000] "GET /core/img/actions/share.svg HTTP/1.1" 200 718 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:55 +0000] "GET /core/img/actions/password.svg HTTP/1.1" 200 569 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:55 +0000] "GET /apps/activity/img/activity-dark.svg HTTP/1.1" 200 472 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:55 +0000] "GET /apps/theming/img/app-dark.svg HTTP/1.1" 200 899 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:55 +0000] "GET /core/img/actions/tag.svg HTTP/1.1" 200 750 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:55 +0000] "GET /core/img/actions/settings-dark.svg HTTP/1.1" 200 1203 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:55 +0000] "GET /apps/survey_client/img/app-dark.svg HTTP/1.1" 200 2085 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:55 +0000] "GET /apps/logreader/img/app-dark.svg HTTP/1.1" 200 801 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:55 +0000] "GET /core/img/googleplus.svg HTTP/1.1" 200 836 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:55 +0000] "GET /settings/img/help.svg HTTP/1.1" 200 868 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:55 +0000] "GET /core/img/facebook.svg HTTP/1.1" 200 799 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:55 +0000] "GET /core/img/twitter.svg HTTP/1.1" 200 1752 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:55 +0000] "GET /core/img/rss.svg HTTP/1.1" 200 904 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:55 +0000] "GET /core/img/mail.svg HTTP/1.1" 200 1263 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:55 +0000] "GET /js/core/merged-template-prepend.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 40548 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:58 +0000] "GET /core/search/js/search.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 3845 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:58 +0000] "GET /core/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 12552 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:58 +0000] "GET /core/js/backgroundjobs.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 938 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:58 +0000] "GET /apps/encryption/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 3037 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:59 +0000] "GET /apps/encryption/js/encryption.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 844 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:59 +0000] "GET /apps/files_pdfviewer/js/previewplugin.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 2205 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:38:59 +0000] "GET /js/core/merged-share-backend.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 23588 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:01 +0000] "GET /apps/files_videoplayer/js/viewer.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1773 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:01 +0000] "GET /apps/gallery/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 3580 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:01 +0000] "GET /apps/notifications/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 508 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:02 +0000] "GET /js/notifications/merged.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 6154 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:04 +0000] "GET /core/js/jquery-ui-fixes.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 558 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:04 +0000] "GET /core/js/files/fileinfo.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1238 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:04 +0000] "GET /core/js/files/client.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 5489 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:04 +0000] "GET /core/js/contactsmenu.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 3803 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:04 +0000] "GET /apps/updatenotification/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1687 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:04 +0000] "GET /apps/updatenotification/js/admin.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1353 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:04 +0000] "GET /settings/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 14738 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:04 +0000] "GET /settings/js/settings.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1488 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:04 +0000] "GET /settings/js/admin.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 2918 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:04 +0000] "GET /settings/js/log.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1222 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:04 +0000] "GET /settings/js/certificates.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1297 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:05 +0000] "GET /core/js/multiselect.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 3417 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:05 +0000] "GET /core/js/setupchecks.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 4045 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:05 +0000] "GET /apps/files/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 4180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:05 +0000] "GET /apps/files/js/jquery.fileupload.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 13824 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:05 +0000] "GET /core/img/logo.svg?v=0 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:05 +0000] "GET /core/img/actions/more-white.svg?v=1 HTTP/1.1" 304 181 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:05 +0000] "GET /core/img/places/contacts.svg?v=1 HTTP/1.1" 304 181 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:05 +0000] "GET /core/img/actions/settings-white.svg?v=1 HTTP/1.1" 304 181 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:05 +0000] "GET /core/img/actions/triangle-s.svg HTTP/1.1" 200 461 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:05 +0000] "GET /core/img/actions/info.svg?v=1 HTTP/1.1" 200 882 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:05 +0000] "GET /heartbeat HTTP/1.1" 200 888 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:05 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 725 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:05 +0000] "PROPFIND /remote.php/webdav HTTP/1.1" 207 1729 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:05 +0000] "GET /apps/encryption/ajax/getStatus HTTP/1.1" 200 1057 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:05 +0000] "GET /settings/ajax/checksetup HTTP/1.1" 200 1689 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:35 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 726 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:37 +0000] "GET /settings/admin/encryption HTTP/1.1" 200 6293 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:42 +0000] "GET /core/vendor/select2/select2.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 3432 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:42 +0000] "GET /core/vendor/jquery-ui/themes/base/jquery-ui.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 6310 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:42 +0000] "GET /apps/encryption/css/settings-admin.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 850 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:42 +0000] "GET /settings/css/settings.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 5659 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:42 +0000] "GET /core/vendor/core.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 276990 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:43 +0000] "GET /apps/encryption/js/settings-admin.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1278 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:44 +0000] "GET /apps/gallery/img/app.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:44 +0000] "GET /settings/img/apps.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:44 +0000] "GET /settings/img/users.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 181 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:44 +0000] "GET /settings/img/admin.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:44 +0000] "GET /settings/img/personal.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:44 +0000] "GET /settings/img/help.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 181 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:44 +0000] "GET /core/img/actions/logout.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 181 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:43 +0000] "GET /core/vendor/purify.min.js.map HTTP/1.1" 302 1430 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:44 +0000] "GET /settings/img/admin.svg HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:44 +0000] "GET /apps/theming/img/app-dark.svg HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:44 +0000] "GET /core/img/actions/share.svg HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:44 +0000] "GET /core/img/actions/password.svg HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:44 +0000] "GET /apps/serverinfo/img/app-dark.svg HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:44 +0000] "GET /core/img/actions/settings-dark.svg HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:44 +0000] "GET /apps/survey_client/img/app-dark.svg HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:44 +0000] "GET /apps/logreader/img/app-dark.svg HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:44 +0000] "GET /core/img/actions/tag.svg HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:44 +0000] "GET /settings/img/help.svg HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:44 +0000] "GET /heartbeat HTTP/1.1" 200 887 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:44 +0000] "GET /cron.php HTTP/1.1" 200 915 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:44 +0000] "PROPFIND /remote.php/webdav HTTP/1.1" 207 1729 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:44 +0000] "GET /apps/encryption/ajax/getStatus HTTP/1.1" 200 1056 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:44 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 725 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:44 +0000] "GET /settings/ajax/checksetup HTTP/1.1" 200 1689 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:44 +0000] "GET /login HTTP/1.1" 200 4569 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
127.0.0.1 - - [21/Nov/2017:10:39:51 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.10 (Debian) PHP/7.1.11 (internal dummy connection)"
127.0.0.1 - - [21/Nov/2017:10:39:53 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.10 (Debian) PHP/7.1.11 (internal dummy connection)"
127.0.0.1 - - [21/Nov/2017:10:39:54 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.10 (Debian) PHP/7.1.11 (internal dummy connection)"
172.21.0.1 - - [21/Nov/2017:10:40:14 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 726 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:39:05 +0000] "GET /cron.php HTTP/1.1" 200 915 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:40:16 +0000] "GET /core/img/actions/checkbox-mark.svg HTTP/1.1" 200 464 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:40:18 +0000] "POST /ocs/v2.php/apps/provisioning_api/api/v1/config/apps/core/encryption_enabled HTTP/1.1" 200 774 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:40:23 +0000] "GET /logout?requesttoken=wDAnW8q3koBScbkB1cKpCSCoi7crO6Ob5WA4dfh3Ky8%3D%3As2oRHY/bp886BP8qmLrKWFPnwcV8a8r5giNhGMg0WQQ%3D HTTP/1.1" 303 1572 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:40:25 +0000] "GET /login HTTP/1.1" 200 4077 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:40:31 +0000] "GET /core/css/jquery-ui-fixes.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1151 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:40:31 +0000] "GET /core/css/guest.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 4760 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:40:31 +0000] "GET /apps/files_versions/css/versions.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 807 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:40:31 +0000] "GET /apps/files_pdfviewer/css/style.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 449 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:40:31 +0000] "GET /core/css/jquery.ocdialog.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 965 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:40:31 +0000] "GET /apps/files_videoplayer/css/style.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 2177 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:40:31 +0000] "GET /core/img/loading-dark.gif HTTP/1.1" 200 4969 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:40:31 +0000] "GET /core/search/js/search.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 3845 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:40:31 +0000] "GET /core/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 12552 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:40:31 +0000] "GET /core/js/backgroundjobs.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 938 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:40:31 +0000] "GET /apps/encryption/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 3037 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:40:31 +0000] "GET /apps/encryption/js/encryption.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 844 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:40:32 +0000] "GET /apps/files_pdfviewer/js/previewplugin.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 2205 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:40:32 +0000] "GET /apps/files_videoplayer/js/viewer.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1773 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:40:32 +0000] "GET /apps/gallery/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 3580 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:40:32 +0000] "GET /core/js/jquery-ui-fixes.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 558 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:40:32 +0000] "GET /core/js/files/fileinfo.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1238 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:40:32 +0000] "GET /core/js/files/client.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 5489 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:40:32 +0000] "GET /core/js/contactsmenu.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 3803 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:40:32 +0000] "GET /core/vendor/jsTimezoneDetect/jstz.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 4235 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:40:31 +0000] "GET /core/vendor/purify.min.js.map HTTP/1.1" 302 1416 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:40:32 +0000] "GET /js/core/merged-login.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 2888 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:40:35 +0000] "GET /core/img/logo-icon.svg?v=1 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:40:35 +0000] "GET /core/img/background.jpg?v=1 HTTP/1.1" 304 182 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:40:35 +0000] "GET /core/img/actions/confirm-white.svg?v=2 HTTP/1.1" 200 1129 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:40:35 +0000] "GET /cron.php HTTP/1.1" 200 915 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:40:34 +0000] "GET /login HTTP/1.1" 200 4572 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
127.0.0.1 - - [21/Nov/2017:10:40:44 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.10 (Debian) PHP/7.1.11 (internal dummy connection)"
127.0.0.1 - - [21/Nov/2017:10:40:45 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.10 (Debian) PHP/7.1.11 (internal dummy connection)"
172.21.0.1 - - [21/Nov/2017:10:40:59 +0000] "GET /core/img/loading-small.gif HTTP/1.1" 200 2057 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:40:59 +0000] "POST /login HTTP/1.1" 303 999 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:05 +0000] "GET /apps/files/ HTTP/1.1" 200 7395 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:20 +0000] "GET /apps/activity/css/style.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1703 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:20 +0000] "GET /core/vendor/select2/select2.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 3432 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:20 +0000] "GET /apps/notifications/css/styles.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1314 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:20 +0000] "GET /apps/files_trashbin/css/trash.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 822 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:20 +0000] "GET /core/vendor/jquery-ui/themes/base/jquery-ui.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 6310 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:20 +0000] "GET /apps/comments/css/comments.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1403 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:20 +0000] "GET /apps/gallery/css/slideshow.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1621 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:20 +0000] "GET /apps/gallery/css/gallerybutton.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1239 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:20 +0000] "GET /apps/gallery/css/share.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1655 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:20 +0000] "GET /apps/systemtags/css/systemtagsfilelist.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 776 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:20 +0000] "GET /core/vendor/core.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 276990 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:20 +0000] "GET /css/files_sharing/37d007a56d816107ce5b52c10342db37-mergedAdditionalStyles.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1942 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:20 +0000] "GET /css/files/37d007a56d816107ce5b52c10342db37-merged.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 5469 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:20 +0000] "GET /css/files_texteditor/37d007a56d816107ce5b52c10342db37-merged.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 2233 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:20 +0000] "GET /css/core/37d007a56d816107ce5b52c10342db37-systemtags.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1441 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:30 +0000] "GET /core/search/js/search.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 3845 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:30 +0000] "GET /core/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 12552 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:30 +0000] "GET /core/js/backgroundjobs.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 938 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:31 +0000] "GET /apps/notifications/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 508 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:31 +0000] "GET /apps/files/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 4180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:31 +0000] "GET /js/files/merged-index.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 77734 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:35 +0000] "GET /apps/files_sharing/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 2916 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:35 +0000] "GET /apps/files_sharing/js/app.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1897 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:35 +0000] "GET /apps/files_sharing/js/sharedfilelist.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 4469 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:35 +0000] "GET /apps/files_trashbin/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 886 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:35 +0000] "GET /apps/files_trashbin/js/app.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1458 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:35 +0000] "GET /apps/files_trashbin/js/filelist.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 3470 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:35 +0000] "GET /apps/activity/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1762 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:35 +0000] "GET /js/activity/activity-sidebar.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 5175 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:39 +0000] "GET /core/js/oc-backbone-webdav.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 3369 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:39 +0000] "GET /apps/comments/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1122 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:39 +0000] "GET /js/comments/merged.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 8447 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:42 +0000] "GET /js/files_sharing/additionalScripts.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 5751 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:45 +0000] "GET /apps/files_versions/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 695 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:45 +0000] "GET /js/files_versions/merged.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 4597 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:48 +0000] "GET /apps/federatedfilesharing/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 2361 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:48 +0000] "GET /apps/federatedfilesharing/js/external.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 2127 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:48 +0000] "GET /apps/files_texteditor/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1135 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:48 +0000] "GET /js/files_texteditor/merged.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 138815 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:52 +0000] "GET /js/gallery/scripts-for-file-app.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 55465 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:56 +0000] "GET /js/core/merged.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 6380 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:59 +0000] "GET /apps/systemtags/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1371 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:41:59 +0000] "GET /js/systemtags/merged.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 6322 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:42:02 +0000] "GET /apps/gallery/img/app.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:42:02 +0000] "GET /apps/activity/img/activity.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:42:02 +0000] "GET /apps/files/img/app.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 181 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:42:03 +0000] "GET /settings/img/personal.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:42:03 +0000] "GET /settings/img/admin.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:42:03 +0000] "GET /settings/img/apps.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 179 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:42:03 +0000] "GET /settings/img/users.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:42:03 +0000] "GET /settings/img/help.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:42:03 +0000] "GET /core/img/actions/logout.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 181 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:42:03 +0000] "GET /core/img/logo.svg?v=0 HTTP/1.1" 304 181 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:42:03 +0000] "GET /core/img/actions/more-white.svg?v=1 HTTP/1.1" 304 181 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:42:03 +0000] "GET /core/img/places/contacts.svg?v=1 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:42:03 +0000] "GET /core/img/actions/settings-white.svg?v=1 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:42:03 +0000] "GET /apps/encryption/ajax/getStatus HTTP/1.1" 200 969 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:42:03 +0000] "GET /cron.php HTTP/1.1" 200 915 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:42:03 +0000] "GET /apps/gallery/config?extramediatypes=1 HTTP/1.1" 200 980 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:42:03 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 725 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:42:03 +0000] "GET /apps/systemtags/lastused HTTP/1.1" 200 878 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:42:03 +0000] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 4408 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:42:17 +0000] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.1" 200 1079 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
127.0.0.1 - - [21/Nov/2017:10:42:25 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.10 (Debian) PHP/7.1.11 (internal dummy connection)"
172.21.0.1 - - [21/Nov/2017:10:42:33 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 726 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:42:41 +0000] "GET /core/img/filetypes/folder.svg?v=1 HTTP/1.1" 200 542 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:42:41 +0000] "GET /core/img/filetypes/text.svg?v=1 HTTP/1.1" 200 708 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:42:40 +0000] "GET /core/img/actions/upload.svg?v=1 HTTP/1.1" 200 402 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:42:47 +0000] "GET /core/css/images/ui-bg_highlight-soft_100_eeeeee_1x100.png HTTP/1.1" 200 373 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:42:47 +0000] "PUT /remote.php/webdav/b807c2282ab0a491bd5c5c1051c6d312_k4PiHxO.jpg HTTP/1.1" 201 656 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:43:03 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 726 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:43:05 +0000] "PROPFIND /remote.php/webdav/b807c2282ab0a491bd5c5c1051c6d312_k4PiHxO.jpg HTTP/1.1" 207 1536 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:43:04 +0000] "GET /core/vendor/purify.min.js.map HTTP/1.1" 302 1422 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:43:08 +0000] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.1" 200 1079 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:43:08 +0000] "GET /login HTTP/1.1" 200 4572 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:43:29 +0000] "PROPFIND /remote.php/webdav/Documents HTTP/1.1" 207 2952 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:43:31 +0000] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2FDocuments HTTP/1.1" 200 1079 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:43:31 +0000] "GET /apps/theming/img/core/filetypes/x-office-document.svg?v=0 HTTP/1.1" 200 1428 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:43:34 +0000] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 5143 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:43:31 +0000] "GET /core/preview.png?file=%2FDocuments%2FAbout.txt&c=5a1400f4a5f4c&x=64&y=64&forceIcon=0 HTTP/1.1" 200 1390 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:43:33 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 726 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:43:39 +0000] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.1" 200 1079 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:44:03 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 726 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:43:44 +0000] "GET /remote.php/webdav/b807c2282ab0a491bd5c5c1051c6d312_k4PiHxO.jpg HTTP/1.1" 500 10204 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:02 +0000] "GET /apps/files/?dir=/&fileid=7 HTTP/1.1" 303 907 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:05 +0000] "GET /apps/files/?dir=/ HTTP/1.1" 200 7385 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:21 +0000] "GET /apps/systemtags/css/systemtagsfilelist.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 777 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:21 +0000] "GET /apps/comments/css/comments.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1404 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:21 +0000] "GET /apps/files_trashbin/css/trash.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 822 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:21 +0000] "GET /apps/gallery/css/gallerybutton.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1240 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:21 +0000] "GET /apps/activity/css/style.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1703 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:21 +0000] "GET /apps/notifications/css/styles.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1313 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:21 +0000] "GET /core/vendor/select2/select2.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 3432 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:21 +0000] "GET /core/css/jquery-ui-fixes.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1151 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:21 +0000] "GET /core/vendor/jquery-ui/themes/base/jquery-ui.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 6309 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:21 +0000] "GET /apps/files_pdfviewer/css/style.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 448 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:21 +0000] "GET /apps/files_versions/css/versions.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 806 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:21 +0000] "GET /apps/files_videoplayer/css/style.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 2176 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:21 +0000] "GET /core/css/jquery.ocdialog.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 964 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:21 +0000] "GET /apps/gallery/css/share.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1655 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:21 +0000] "GET /apps/gallery/css/slideshow.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1621 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:21 +0000] "GET /core/vendor/core.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 276990 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:22 +0000] "GET /core/search/js/search.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 3845 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:22 +0000] "GET /core/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 12552 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:22 +0000] "GET /core/js/backgroundjobs.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 938 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:22 +0000] "GET /apps/encryption/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 3037 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:22 +0000] "GET /apps/encryption/js/encryption.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 844 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:22 +0000] "GET /apps/files_pdfviewer/js/previewplugin.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 2205 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:22 +0000] "GET /apps/files_videoplayer/js/viewer.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1773 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:22 +0000] "GET /apps/gallery/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 3580 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:22 +0000] "GET /apps/notifications/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 508 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:22 +0000] "GET /core/js/jquery-ui-fixes.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 558 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:22 +0000] "GET /core/js/files/fileinfo.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1238 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:22 +0000] "GET /core/js/files/client.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 5489 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:22 +0000] "GET /core/js/contactsmenu.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 3803 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:22 +0000] "GET /apps/files/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 4180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:22 +0000] "GET /apps/files_sharing/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 2916 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:22 +0000] "GET /apps/files_sharing/js/app.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1897 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:22 +0000] "GET /apps/files_sharing/js/sharedfilelist.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 4469 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:22 +0000] "GET /apps/files_trashbin/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 886 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:22 +0000] "GET /apps/files_trashbin/js/app.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1458 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:23 +0000] "GET /apps/files_trashbin/js/filelist.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 3470 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:23 +0000] "GET /apps/activity/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1762 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:23 +0000] "GET /core/js/oc-backbone-webdav.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 3369 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:23 +0000] "GET /apps/comments/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1122 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:23 +0000] "GET /apps/files_versions/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 695 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:23 +0000] "GET /apps/federatedfilesharing/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 2361 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:23 +0000] "GET /apps/federatedfilesharing/js/external.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 2127 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:23 +0000] "GET /apps/files_texteditor/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1135 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:23 +0000] "GET /apps/systemtags/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1371 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:23 +0000] "GET /apps/gallery/img/app.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:23 +0000] "GET /apps/activity/img/activity.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 179 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:23 +0000] "GET /apps/files/img/app.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:23 +0000] "GET /settings/img/personal.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:23 +0000] "GET /settings/img/admin.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:23 +0000] "GET /settings/img/apps.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 179 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:23 +0000] "GET /settings/img/help.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:23 +0000] "GET /settings/img/users.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:23 +0000] "GET /core/img/actions/logout.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:23 +0000] "GET /core/img/actions/more-white.svg?v=1 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:23 +0000] "GET /core/img/places/contacts.svg?v=1 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:23 +0000] "GET /core/img/actions/settings-white.svg?v=1 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:23 +0000] "GET /core/img/logo.svg?v=0 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:21 +0000] "GET /core/vendor/purify.min.js.map HTTP/1.1" 302 1422 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:23 +0000] "GET /cron.php HTTP/1.1" 200 915 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:23 +0000] "GET /apps/encryption/ajax/getStatus HTTP/1.1" 200 969 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:24 +0000] "GET /apps/systemtags/lastused HTTP/1.1" 200 878 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:25 +0000] "GET /login HTTP/1.1" 200 4560 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:23 +0000] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 5142 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:23 +0000] "GET /apps/gallery/config?extramediatypes=1 HTTP/1.1" 200 980 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:23 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 725 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:32 +0000] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.1" 200 1079 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
127.0.0.1 - - [21/Nov/2017:10:45:39 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.10 (Debian) PHP/7.1.11 (internal dummy connection)"
127.0.0.1 - - [21/Nov/2017:10:45:41 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.10 (Debian) PHP/7.1.11 (internal dummy connection)"
127.0.0.1 - - [21/Nov/2017:10:45:44 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.10 (Debian) PHP/7.1.11 (internal dummy connection)"
172.21.0.1 - - [21/Nov/2017:10:45:53 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 726 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:10:45:49 +0000] "GET /remote.php/webdav/b807c2282ab0a491bd5c5c1051c6d312_k4PiHxO.jpg HTTP/1.1" 500 10204 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:16:49 +0000] "GET /index.php/settings/integrity/failed HTTP/1.1" 200 939 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:29 +0000] "GET / HTTP/1.1" 302 936 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:32 +0000] "GET /apps/files/ HTTP/1.1" 200 7386 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:48 +0000] "GET /core/vendor/select2/select2.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 3432 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:48 +0000] "GET /core/css/jquery-ui-fixes.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1152 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:48 +0000] "GET /apps/files_pdfviewer/css/style.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 449 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:48 +0000] "GET /apps/files_videoplayer/css/style.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 2177 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:48 +0000] "GET /apps/files_versions/css/versions.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 807 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:48 +0000] "GET /apps/notifications/css/styles.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1313 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:48 +0000] "GET /core/vendor/jquery-ui/themes/base/jquery-ui.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 6310 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:48 +0000] "GET /core/css/jquery.ocdialog.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 964 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:48 +0000] "GET /apps/activity/css/style.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1702 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:48 +0000] "GET /apps/files_trashbin/css/trash.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 821 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:48 +0000] "GET /apps/comments/css/comments.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1403 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:48 +0000] "GET /apps/gallery/css/slideshow.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1621 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:48 +0000] "GET /apps/gallery/css/share.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1655 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:48 +0000] "GET /apps/systemtags/css/systemtagsfilelist.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 776 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:48 +0000] "GET /apps/gallery/css/gallerybutton.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1239 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:48 +0000] "GET /core/vendor/core.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 276990 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:49 +0000] "GET /core/search/js/search.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 3845 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:49 +0000] "GET /core/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 12552 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:49 +0000] "GET /core/js/backgroundjobs.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 938 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:49 +0000] "GET /apps/encryption/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 3037 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:49 +0000] "GET /apps/encryption/js/encryption.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 844 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:49 +0000] "GET /apps/files_pdfviewer/js/previewplugin.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 2205 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:49 +0000] "GET /apps/files_videoplayer/js/viewer.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1773 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:49 +0000] "GET /apps/gallery/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 3580 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:49 +0000] "GET /apps/notifications/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 508 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:50 +0000] "GET /core/js/jquery-ui-fixes.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 558 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:50 +0000] "GET /core/js/files/fileinfo.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1238 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:50 +0000] "GET /core/js/files/client.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 5489 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:50 +0000] "GET /core/js/contactsmenu.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 3803 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:50 +0000] "GET /apps/files/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 4180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:50 +0000] "GET /apps/files_sharing/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 2916 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:50 +0000] "GET /apps/files_sharing/js/app.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1897 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:50 +0000] "GET /apps/files_sharing/js/sharedfilelist.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 4469 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:50 +0000] "GET /apps/files_trashbin/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 886 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:50 +0000] "GET /apps/files_trashbin/js/app.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1458 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:50 +0000] "GET /apps/files_trashbin/js/filelist.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 3470 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:50 +0000] "GET /apps/activity/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1762 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:50 +0000] "GET /core/js/oc-backbone-webdav.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 3369 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:50 +0000] "GET /apps/comments/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1122 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:51 +0000] "GET /apps/files_versions/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 695 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:51 +0000] "GET /apps/federatedfilesharing/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 2361 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:51 +0000] "GET /apps/federatedfilesharing/js/external.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 2127 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:51 +0000] "GET /apps/files_texteditor/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1135 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:48 +0000] "GET /core/vendor/purify.min.js.map HTTP/1.1" 302 1416 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:51 +0000] "GET /apps/systemtags/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1371 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:51 +0000] "GET /apps/activity/img/activity.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 179 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:51 +0000] "GET /apps/gallery/img/app.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:51 +0000] "GET /apps/files/img/app.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:51 +0000] "GET /settings/img/personal.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:51 +0000] "GET /settings/img/apps.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 179 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:51 +0000] "GET /settings/img/users.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:51 +0000] "GET /settings/img/admin.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:51 +0000] "GET /settings/img/help.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:51 +0000] "GET /core/img/actions/logout.svg?v=daccdb05d59ea58e30b4354d0a1c5a6d HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:51 +0000] "GET /core/img/actions/more-white.svg?v=1 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:51 +0000] "GET /core/img/logo.svg?v=0 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:51 +0000] "GET /core/img/places/contacts.svg?v=1 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:51 +0000] "GET /core/img/actions/settings-white.svg?v=1 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:51 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 725 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:51 +0000] "GET /apps/gallery/config?extramediatypes=1 HTTP/1.1" 200 980 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:51 +0000] "GET /login HTTP/1.1" 200 4562 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:51 +0000] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 5142 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:51 +0000] "GET /apps/encryption/ajax/getStatus HTTP/1.1" 200 969 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:52 +0000] "GET /apps/systemtags/lastused HTTP/1.1" 200 878 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:51 +0000] "GET /cron.php HTTP/1.1" 200 915 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:17:57 +0000] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.1" 200 1079 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
127.0.0.1 - - [21/Nov/2017:11:18:06 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.10 (Debian) PHP/7.1.11 (internal dummy connection)"
127.0.0.1 - - [21/Nov/2017:11:18:08 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.10 (Debian) PHP/7.1.11 (internal dummy connection)"
127.0.0.1 - - [21/Nov/2017:11:18:10 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.10 (Debian) PHP/7.1.11 (internal dummy connection)"
172.21.0.1 - - [21/Nov/2017:11:18:21 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 726 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:18:20 +0000] "GET /settings/apps HTTP/1.1" 200 6555 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:18:26 +0000] "GET /settings/css/settings.css?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 5659 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:18:27 +0000] "GET /core/vendor/marked/marked.min.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 6009 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:18:27 +0000] "GET /settings/l10n/de.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 14738 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:18:27 +0000] "GET /settings/js/settings.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 1488 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:18:27 +0000] "GET /settings/js/apps.js?v=daccdb05d59ea58e30b4354d0a1c5a6d-0 HTTP/1.1" 200 7488 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:18:27 +0000] "GET /apps/encryption/ajax/getStatus HTTP/1.1" 200 970 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:18:27 +0000] "GET /cron.php HTTP/1.1" 200 915 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:18:27 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 725 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:18:27 +0000] "GET /settings/apps/categories HTTP/1.1" 200 1913 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:18:57 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 726 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:19:27 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 726 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:18:27 +0000] "GET /settings/apps/list?category=installed HTTP/1.1" 200 41776 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:19:57 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 726 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:19:21 +0000] "GET /settings/apps/list?category=enabled HTTP/1.1" 200 35081 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/activity/img/activity.svg HTTP/1.1" 304 179 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /core/img/actions/checkmark.svg?v=1 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/systemtags/img/app.svg HTTP/1.1" 304 181 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/comments/img/comments.svg HTTP/1.1" 304 179 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/encryption/img/app.svg HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/files_trashbin/img/app.svg HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/federation/img/app.svg HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/files_sharing/img/app.svg HTTP/1.1" 304 181 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/firstrunwizard/img/app.svg HTTP/1.1" 304 181 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/gallery/img/app.svg HTTP/1.1" 304 181 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/logreader/img/app.svg HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/serverinfo/img/app.svg HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/nextcloud_announcements/img/app.svg HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/password_policy/img/app.svg HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/files_pdfviewer/img/app.svg HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/sharebymail/img/app.svg HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/files_texteditor/img/app.svg HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/theming/img/app.svg HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/updatenotification/img/app.svg HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/survey_client/img/app.svg HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/files_versions/img/app.svg HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/files_videoplayer/img/app.svg HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /core/img/places/default-app-icon.svg HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/notifications/img/notifications.svg?v=12.0.3.3 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/activity/img/activity.svg?v=12.0.3.3 HTTP/1.1" 304 179 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/systemtags/img/app.svg?v=12.0.3.3 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/comments/img/comments.svg?v=12.0.3.3 HTTP/1.1" 304 179 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/encryption/img/app.svg?v=12.0.3.3 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/files_trashbin/img/app.svg?v=12.0.3.3 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/federation/img/app.svg?v=12.0.3.3 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/files_sharing/img/app.svg?v=12.0.3.3 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/gallery/img/app.svg?v=12.0.3.3 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/serverinfo/img/app.svg?v=12.0.3.3 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/logreader/img/app.svg?v=12.0.3.3 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:06 +0000] "GET /apps/firstrunwizard/img/app.svg?v=12.0.3.3 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:07 +0000] "GET /apps/nextcloud_announcements/img/app.svg?v=12.0.3.3 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:07 +0000] "GET /apps/files_pdfviewer/img/app.svg?v=12.0.3.3 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:07 +0000] "GET /apps/password_policy/img/app.svg?v=12.0.3.3 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:07 +0000] "GET /apps/sharebymail/img/app.svg?v=12.0.3.3 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:07 +0000] "GET /apps/files_texteditor/img/app.svg?v=12.0.3.3 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:07 +0000] "GET /apps/theming/img/app.svg?v=12.0.3.3 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:07 +0000] "GET /apps/updatenotification/img/app.svg?v=12.0.3.3 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:07 +0000] "GET /apps/survey_client/img/app.svg?v=12.0.3.3 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:07 +0000] "GET /apps/files_versions/img/app.svg?v=12.0.3.3 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:07 +0000] "GET /apps/files_videoplayer/img/app.svg?v=12.0.3.3 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:07 +0000] "GET /core/img/places/default-app-icon.svg?v=12.0.3.3 HTTP/1.1" 304 180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
127.0.0.1 - - [21/Nov/2017:11:20:12 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.10 (Debian) PHP/7.1.11 (internal dummy connection)"
172.21.0.1 - - [21/Nov/2017:11:20:27 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 726 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:20:57 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 726 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:21:27 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 726 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:21:57 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 726 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
172.21.0.1 - - [21/Nov/2017:11:22:27 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 726 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"
`
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

The file nextcloud.log is empty.
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

### PR DESCRIPTION
**Pull request by MorrisJobke**
The code tried to find the apps with updates and thus was called for every available app. This caused to get the full appstore content as often as apps are available. The appstore request itself was cached nevertheless in an appdata dir, but with an object storage this is still a lot of round trips to read this cached result. Thus the instantiated list is now cached in a static variable (because it's a static method call).

Fixes #7235 

Diff of the before and after code base: https://blackfire.io/profiles/compare/0b59e81d-4ea4-4a22-ba14-640cf091d487/graph

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]
Static.... ⚱️

**Comment by nickvergessen** [comment]
Actually it should be cached already?
https://github.com/nextcloud/server/blob/2eb2b6e437446023004d81a0be0ea5c827a6359a/lib/private/App/AppStore/Fetcher/Fetcher.php#L143-L153

**Comment by nickvergessen** [comment]
Ah reading helps...

**Comment by nickvergessen** [comment]
```
There was 1 failure:

1) Test\InstallerTest::testIsUpdateAvailable with data set #1 (array(array('files', array(array('1.0')))), false)
Failed asserting that '1111.0' is identical to false.

/drone/src/github.com/nextcloud/server/tests/lib/InstallerTest.php:157
```

Static fun

**Comment by MorrisJobke** [comment]
> Static fun

And I have no idea what this is :/

**Comment by MorrisJobke** [comment]
> And I have no idea what this is :/

Ah - because it is cached and not cleared between those jobs :/

**Comment by MorrisJobke** [comment]
> Ah - because it is cached and not cleared between those jobs :/

Okay ... I needed to take a bigger reordering of how it works. basically the second commit in here brings the DI version to all places where the Installer is used. And the third commit replaced the static calls to `isUpdateAvailable` to normal method calls on the Installer object. I tested around and it works fine (enabling/disabling/updating apps).

@nickvergessen @rullzer @LukasReschke Please review

**Comment by blizzz** [comment]
Several tests are failing, but on first sight they seem unrelated… but those happen not on master.

**Comment by MorrisJobke** [comment]
> Several tests are failing, but on first sight they seem unrelated… but those happen not on master.

It was related. I forgot to mock the call in the tests, so it asked for actual updates in the appstore. 🙈

**Review by LukasReschke — APPROVED** [review]

File: lib/private/Installer.php [hunk 1]
```diff
@@ -375,27 +379,26 @@ public function downloadApp($appId) {
...
 		}
 
-		if ($isInstanceReadyForUpdates === false) {
+		if ($this->isInstanceReadyForUpdates === false) {
 			return false;
 		}
 
-		$apps = $appFetcher->get();
+		if ($this->apps === null) {
+			$apps = $this->appFetcher->get();
```
Comment (MorrisJobke) [inline lib/private/Installer.php]: Obviously I failed here too. 🙈 cc @rullzer @skjnldsv Let me fix that.
