### PR TITLE
fix(CardDAV): catch right exception when checking for federated app classes

### LINKED ISSUE #39054: [Bug]: User address book catches wrong exception
### Describe the bug

I accidentally updated my docker Nextcloud from 26.0.2 to 27 (because my docker compose had "latest" instead of "stable" and I didn't pay attention that 27 is now latest and 26.0.3 is now stable instead of 25.x).

Everything seems to work fine, except the web contacts page. This is stuck on "Loading contacts ..." with no menu or anything.

It seems that accessing the contacts via apps on my phone still works

### Steps to reproduce

1. log in to the web interface
2. switch to contacts via the menu icon

### Expected behavior

contacts page to load, show my contacts, show the contacts menu

### Actual behavior

it's stuck on "Loading contacts ..."

### Contact version

5.3.2

### Operating system

docker

### PHP engine version

Other

### Web server

Apache (supported)

### Database

MySQL

### Additional info

PHP 8.2.7

image

### PR DESCRIPTION
**Pull request by miaulalala**
* Resolves: #39054

## Summary

Tested by disabling the federation app. 

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

File: apps/dav/lib/CardDAV/UserAddressBooks.php [hunk 1]
```diff
@@ -28,6 +28,7 @@
  */
 namespace OCA\DAV\CardDAV;
 
+use OC\AppFramework\Utility\QueryNotFoundException;
```
Comment (blizzz) [inline apps/dav/lib/CardDAV/UserAddressBooks.php:31]: private?

**Review by nickvergessen — APPROVED** [review]

**Review by blizzz — APPROVED** [review]

**Review by tcitworld — APPROVED** [review]

**Comment by miaulalala** [comment]
Failing drone job is sharing - seems unrelated.
