### PR TITLE
fix: catch ManuallyLockedException and use app context

### LINKED ISSUE #123: Old versions can not be restored from the sidebar because file is locked
How to reproduce:
* open a file (.md or .odt)
* add some content so multiple versions exist
* open the versions tab in the sidebar
* try to restore previous version
* see `Could not restore version`.

The server responds with a 500 with this content
```xml
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>OCP\Lock\ManuallyLockedException</s:exception>
  <s:message>"files/AA.mine/test text/restore file version with lock.md" is locked, existing lock on file: files_lock/bd8abcbd-a01a-40c5-8332-b9c2e5c42cd2</s:message>
</d:error>
```
<details>
<summary>
Trace from the server:
</summary>

```yaml
{
app: webdav,
method: MOVE,
url: /remote.php/dav/versions/<user-id>/16523/1838744392,
message: "files/filename.docx" is locked, existing lock on file: files_lock/15551a66-c88c-49ea-8c3c-e85585df40a3,
exception: {
      Exception: OCP\Lock\ManuallyLockedException
      Message: "files/filename.docx" is locked, existing lock on file: files_lock/15551a66-c88c-49ea-8c3c-e85585df40a3
      Code: 0
      Trace: [ 
           {
               file: /var/www/html/nextcloud/apps/files_lock/lib/Storage/LockWrapper.php
               line: 214
               function: checkPermission
               class: OCA\FilesLock\Storage\LockWrapper"
               type: ->
           },
           {
               file: /var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php
               line: 301
               function: fopen
               class: OCA\FilesLock\Storage\LockWrapper"
               type: ->
           },
           {
               file: /var/www/html/nextcloud/apps/files_versions/lib/Storage.php
               line: 442
               function: fopen
               class: OCA\FilesLock\Wrapper\Wrapper"
               type: ->
           },
           {
               file: /var/www/html/nextcloud/apps/files_versions/lib/Storage.php
               line: 401
               function: copyFileContents
               class: OCA\Files_Versions\Storage
               type: ::
           },
    ]
}
```
</details>

### PR DESCRIPTION
**Pull request by max-nextcloud**
* Resolves: https://github.com/nextcloud/files_lock/issues/123

## Summary

The files_lock app may throw ManuallyLockedExceptions when attempting to revert a file that is currently opened. This would prevent the user from rolling back a opened file.

Text and Richdocuments handle changes of the file while editing. Allow reverting files even when they are locked by these apps and let the apps handle the conflict.

## Alternatives considered

I tried to tackle this in lower levels first:
* Inside the `Storage\LockWrapper` in `files_lock` - but it turns out we use different functions (`rename` and `fopen`) to rollback to an old version depending on the storage type. The `fopen` happens separatedly for the source and the target and therefore it's impossible to detect that it was triggered by a version rollback.
* Inside the `Storage` of `files_version` - it's possible to get a hold of the actual node there. But it would only fix the issue in the normal version storage. Separate fixes would still be required for `collectives` and `group_folders` and any other versioning implementation.

So i think this is the easiest way to go.

## TODO

- [x] checked if this could be moved into the `files_lock` app - looks like it cannot due to load order issues. Once the files_lock app is loaded other apps might already have dependency injected the VersionsManager. So we cannot change it from within the `files_lock` app.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/files_versions/lib/Versions/VersionManager.php [hunk 1]
```diff
@@ -133,4 +138,45 @@ public function deleteVersion(IVersion $version): void {
...
+	/**
+	 * Catch ManuallyLockedException and retry in app context if possible.
+	 *
+	 * The files_lock app may throw ManuallyLockedExceptions
+	 * when attempting to revert a file that is currently opened.
+	 * This would prevent the user from rolling back a opened file.
+	 *
+	 * Text and Richdocuments handle changes of the file while editing.
+	 * Allow reverting files even when they are locked by these apps
+	 * and let the apps handle the conflict.
```
Comment (artonge) [inline apps/files_versions/lib/Versions/VersionManager.php:151]: A bit nitpicky, but I find it cleared. I might be saying wrong things though.

```suggestion
	 * Context: The files_lock app will throw ManuallyLockedExceptions
	 * when writing to a file that is currently locked.
	 * This is to prevents a user from editing an already opened file.
	 *
	 * Exception: Text and Richdocuments can handle changes of the file while editing.
	 * So we execute the edition under their lock context
	 * to let them handle the conflict.
```

File: apps/files_versions/lib/Versions/VersionManager.php [hunk 2]
```diff
@@ -133,4 +138,45 @@ public function deleteVersion(IVersion $version): void {
...
+			$appsThatHandleUpdates = array("text", "richdocuments");
+			if (!in_array($owner, $appsThatHandleUpdates)) {
+				throw $e;
+			}
+			// The LockWrapper in the files_lock app only compares the lock type and owner
+			// when checking the lock against the current scope.
+			// So we do not need to get the actual node here
+			// and use the root node instead.
+			$root = \OC::$server->get(IRootFolder::class);
+			$lockContext = new LockContext($root, ILock::TYPE_APP, $owner());
```
[the remark this answers is not in the document]
Comment (max-nextcloud) [reply apps/files_versions/lib/Versions/VersionManager.php:172]: Good catch! Used to be `$e->getOwner()` but I now convert that to a `string` above to make sure it's not null. Funny that this is not caught by psalm.

File: apps/files_versions/lib/Versions/VersionManager.php (hunk 1 above)
Comment (max-nextcloud) [reply apps/files_versions/lib/Versions/VersionManager.php:151]: Thanks for the proposal. It's really only about rolling back to old versions - not about editing. I will take your changes as a starting point and rephrase from there. :)

Comment (max-nextcloud) [reply apps/files_versions/lib/Versions/VersionManager.php]: I did rephrase it. Curious to hear what you think @artonge

File: apps/files_versions/lib/Versions/VersionManager.php [hunk 3]
```diff
@@ -133,4 +138,48 @@ public function deleteVersion(IVersion $version): void {
...
+	 *
+	 * Allow users to go back to old versions via the versions tab in the sidebar
+	 * even when the file is opened in the viewer next to it.
+	 *
+	 * Context: If a file is currently opened for editing
+	 * the files_lock app will throw ManuallyLockedExceptions.
+	 * This prevented the user from rolling an opened file back to a previous version.
+	 *
+	 * Text and Richdocuments can handle changes of open files.
+	 * So we execute the rollback under their lock contex
```
Comment (artonge) [inline apps/files_versions/lib/Versions/VersionManager.php:153]:
```suggestion
* So we execute the rollback under their lock context
```

**Review by artonge — APPROVED** [review]
Typo, else nice :+1:

**Review by juliusknorr — APPROVED** [review]

**Comment by juliushaertl** [comment]
Failure unrelated
