### PR TITLE
Check the if we can actually access the storage cache for recent files

### LINKED ISSUE #16474: User can see files which he is not athirized to access
Hello I am "only"admin, on a cloud service setup by provider.

### Steps to reproduce
1. unauthorised User click recent files
2. files which he is not athirized to access
3. authorisation set by group folder

### Expected behaviour
See only files files which he is athirized to access

### Actual behaviour
Tell us what happens instead

### Server configuration

 version: 16.0.1.1  -
 versionstring: 16.0.1

Enabled:  
- accessibility: 1.2.0 
- activity: 2.9.1  
- calendar: 1.7.0  
- cloud_federation_api: 0.2.0 
- comments: 1.6.0  - dav: 1.9.2  
- federatedfilesharing: 1.6.0  
- federation: 1.6.0  - files: 1.11.0  
- files_pdfviewer: 1.5.0  
- files_rightclick: 0.13.0  
- files_sharing: 1.8.0  
- files_texteditor: 2.8.0  
- files_trashbin: 1.6.0  
- files_versions: 1.9.0  
- files_videoplayer: 1.5.0  
- firstrunwizard: 2.5.0  
- gallery: 18.3.0  
- groupfolders: 4.0.4  
- logreader: 2.1.0  
- lookup_server_connector: 1.4.0  
- nextcloud_announcements: 1.5.0  
- notifications: 2.4.1  
- oauth2: 1.4.2  
- occweb: 0.0.4  
- onlyoffice: 2.4.0  
- privacy: 1.0.0  
- provisioning_api: 1.6.0  
- serverinfo: 1.6.0  
- sharebymail: 1.6.0  
- systemtags: 1.6.0  
- theming: 1.7.0  
- twofactor_backupcodes: 1.5.0  
- viewer: 1.0.0  
- workflowengine: 1.6.0

Disabled:  
- admin_audit  
- contacts  
- encryption  
- files_external  
- password_policy  
- recommendations  
- registration  
- support  
- survey_client  
- updatenotification  
- user_ldap

### PR DESCRIPTION
**Pull request by juliusknorr**
This will make sure we check the storage cache if it actually holds an entry for the node returned by the recent files search. 

@nickvergessen I dropped the initial approach to just reuse getById as it will cause an additional query for each file, which caused quite a high load.

fixes #16474

### CODE REVIEW

File: lib/private/Files/Node/Folder.php [hunk 1]
```diff
@@ -442,6 +442,10 @@ private function recentParse($result, $mountMap, $mimetypeLoader) {
 		}, $result));
 
 		return array_values(array_filter($files, function (Node $node) {
+			$cacheEntry = $node->getStorage()->getCache()->get($node->getId());
```
Comment (nickvergessen) [inline lib/private/Files/Node/Folder.php]: Is this enough? Or should we check `isReadable` still, to make sure file access control and others also work?

Comment (juliushaertl) [reply lib/private/Files/Node/Folder.php]: Since the cache uses https://github.com/nextcloud/groupfolders/blob/master/lib/ACL/ACLCacheWrapper.php#L52 to format the cache entry for groupfolder files this should make sure that an inaccessible node is never included in the result. But hopefully @icewind1991 can also have a look and tell if that solution is already suitable.

Comment (nickvergessen) [reply lib/private/Files/Node/Folder.php]: https://github.com/nextcloud/files_accesscontrol/blob/master/lib/CacheWrapper.php#L65 Access control just restricts the permissions. So I guess we should do both: Check if we have a cache entry and if so check if the permissions have "is readable"

Comment (juliushaertl) [reply lib/private/Files/Node/Folder.php]: OK, makes sense :+1:

Comment (juliushaertl) [reply lib/private/Files/Node/Folder.php]: Pushed a commit for that as well and tested it with the files_accesscontrol app. The file is still listed in the users directory listing, but I would argue that this is expected behaviour in the files_accesscontrol case.

**Review by nickvergessen — APPROVED** [review]

**Review by MorrisJobke — APPROVED** [review]
Code makes sense 👍

**Comment by MorrisJobke** [comment]
Unit tests fail.

**Comment by juliushaertl** [comment]
Fixed.
