### PR TITLE
fix(files): middle click & ctrl new tab

### LINKED ISSUE #52380: [Bug]: The hotkeys Middle-Click and Ctrl + Left-Click not open File/Folder in new tab
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The hotkey functionality for Middle-Click and Ctrl + Left-Click is not operating as expected. When attempting to use these shortcuts to open a file or folder in a new tab, it's acting like normal Left-Click.

### Steps to reproduce

1. Navigate to Files app
2. Attempt to open file/folder in a new tab using Middle-Click or Ctrl + Left-Click

### Expected behavior

Using Middle-Click or Ctrl + Left-Click should open the selected file/folder in a new browser tab.

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/server/issues/52380

Regression from https://github.com/nextcloud/server/pull/45652

### CODE REVIEW

File: apps/files/src/components/FileEntryMixin.ts [hunk 1]
```diff
@@ -338,7 +338,7 @@ export default defineComponent({
 
 			// if ctrl+click / cmd+click (MacOS uses the meta key) or middle mouse button (button & 4), open in new tab
 			// also if there is no default action use this as a fallback
-			const metaKeyPressed = event.ctrlKey || event.metaKey || Boolean(event.button & 4)
+			const metaKeyPressed = event.ctrlKey || event.metaKey || event.button === 1
```
Comment (susnux) [inline apps/files/src/components/FileEntryMixin.ts:341]: I see it should have been `Boolean(event.buttons & 4)` (missing `s`).
So its an binary mask for bit 4 which means mouse wheel.

But then also the condition in line 330 is wrong.

**Review by susnux — APPROVED** [review]

**Review by artonge — APPROVED** [review]

**Comment by juliusknorr** [comment]
Any way we can add a test for this? I feel this broke quite a few times in the past already

**Comment by susnux** [comment]
> Any way we can add a test for this? I feel this broke quite a few times in the past already

At least not checking new tab is opened with Cypress. Does not work by design and would need a different test runner like playwright

File: apps/files/src/components/FileEntryMixin.ts (hunk 1 above)
Comment (susnux) [reply apps/files/src/components/FileEntryMixin.ts:359]: yes `button` vs `buttons`
