### PR TITLE
Use version from config to generate doclink

### LINKED ISSUE #12894: 15.0.0 RC 3: links on admin/overview link to version 14
### Steps to reproduce
1. Open Settings | Administration | Overview
2.1 link documentation links to .../docs.nextcloud.com/server/**14**/go.php?to=admin-setup-well-known-URL
2.1 link documentation links to ...docs.nextcloud.com/server/**14**/go.php?to=admin-performance
2.3 link  installation guides  links to  ...docs.nextcloud.com/server/**14**/go.php?to=admin-install

Screenshot of .../nextcloud/index.php/settings/admin/overview:

screenshot_2018-12-06 settings - nextcloud

### Expected behaviour
The links fits to the installed version , ex.  ......docs.nextcloud.com/server/**15**/...

### Actual behaviour
The links link to ...docs.nextcloud.com/server/**14**/...

**Nextcloud version:**
Nextcloud 15.0.0 RC 3

**Updated from an older Nextcloud/ownCloud or fresh install:**
deleted old folder /var/www/nextcloud
drop old database from nextcloud
then installation with nextcloud-15.0.0RC3.tar.bz2

### PR DESCRIPTION
**Pull request by kesselb**
Close #12894 

Use version to generate doc link.

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
I like it!

File: lib/private/legacy/defaults.php [hunk 1]
```diff
@@ -65,8 +64,8 @@ public function __construct() {
 		$this->defaultiTunesAppId = $config->getSystemValue('customclient_ios_appid', '1125420102');
 		$this->defaultAndroidClientUrl = $config->getSystemValue('customclient_android', 'https://play.google.com/store/apps/details?id=com.nextcloud.client');
 		$this->defaultDocBaseUrl = 'https://docs.nextcloud.com';
-		$this->defaultDocVersion = '14'; // used to generate doc links
-		$this->defaultSlogan = $this->l->t('a safe home for all your data');
+		$this->defaultDocVersion = substr($config->getSystemValue('version', '16.0.0.0'), 0, 2); // used to generate doc links
```
Comment (juliushaertl) [inline lib/private/legacy/defaults.php]: Please use `\OC_Util::getVersion()[0]` here

**Review by violoncelloCH — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]
