### PR TITLE
Fixes the app menu

### LINKED ISSUE #10786: Can't click the last app
### Steps to reproduce
1. Login to the system
2. Have the window size large enough to not have the three dots "more apps" menu
3. Try to click the last app in the list

### Expected behaviour
Can click the app - browser opens the app

### Actual behaviour
Can't click the app.

image

The navigation menu is above the last app.

### Server configuration

**Nextcloud version:** Nextcloud 14 RC1

### PR DESCRIPTION
**Pull request by weeman1337**
Adds and updates some z-index to make it possible to click the last app.

closes #10786

### CODE REVIEW

**Comment by skjnldsv** [comment]
Thanks I was preparing something as well! :)

**Review by MorrisJobke — APPROVED** [review]
Verified and works 👍

**Review by skjnldsv — APPROVED** [review]

File: core/js/js.js [hunk 1]
```diff
@@ -684,10 +684,16 @@ var OCP = {},
...
+		
+		// On link, the enter key trigger a click event
+		// Only use the click to avoid two fired events
+		$toggle.on($toggle.prop('tagName') === 'A'
+			? 'click.menu'
+			: 'click.menu keyup.menu', function(event) {
 			// prevent the link event (append anchor to URL)
 			event.preventDefault();
 
+			console.log(event);
```
Comment (MorrisJobke) [inline core/js/js.js]: Debug output? 🙈
