### PR TITLE
Redirect guests to login if they follow the link of a comment mention…

### LINKED ISSUE #11184: DI of `OCP\Files\Folder` fails for guests
E.g. https://github.com/nextcloud/server/blob/0eebff152a177dd59ed8773df26f1679f8a88e90/apps/comments/lib/Controller/Notifications.php#L75

> TypeError
> Argument 4 passed to OCA\Comments\Controller\Notifications::__construct() must implement interface OCP\Files\Folder, null given

The problem is, that the UserFolder is returned as null instead of something like e.g. `NonExistingFolder`
https://github.com/nextcloud/server/blob/0eebff152a177dd59ed8773df26f1679f8a88e90/lib/private/AppFramework/DependencyInjection/DIContainer.php#L111-L113

So either all apps which use Folder injection need to allow = null manually or they will throw if one of the roots is invoked by a guest.

@icewind1991 do you think `NonExistingFolder` would make sense, or should we just advice all consumers of the app to explicitly allow null or inject IRootFolder instead and get the folder once they are sure it's a logged in user.

### PR DESCRIPTION
**Pull request by nickvergessen**
…-notification

Fix #11184

### CODE REVIEW

File: apps/comments/lib/Controller/Notifications.php [hunk 1]
```diff
@@ -72,35 +74,50 @@ public function __construct(
...
+	 * @PublicPage
 	 * @NoCSRFRequired
 	 *
 	 * @param string $id		the comment ID
 	 * @return Response
 	 */
 	public function view($id) {
+		$currentUser = $this->userSession->getUser();
+		if (!$currentUser instanceof IUser) {
+			return new RedirectResponse(
```
Comment (blizzz) [inline apps/comments/lib/Controller/Notifications.php]: it's a bit of a hack. Would be more comfortable if that was dealt with on the middleware-level

Comment (nickvergessen) [reply apps/comments/lib/Controller/Notifications.php]: Yeah, fine by me. The middleware would basically do the same. Just instead of throwing an exception it makes a redirect response...

Comment (blizzz) [reply apps/comments/lib/Controller/Notifications.php]: Sure, but then we have it at one, reusable place, don't need to soften the restrictions of the controller and are less likely to refactor it away accidentally.

Comment (nickvergessen) [reply apps/comments/lib/Controller/Notifications.php]: I would still prefer this to be backported to 14 instead of a middleware change.
Also for the middleware, the constructor still needs to be changed to get rid of `Folder` I think, but we could test that later.

The other thing I'm not sure about is, if we should do that for all pages which are not `PublicPage` or if it should be explicit, because it makes no sense to do this for API calls.

Comment (blizzz) [reply apps/comments/lib/Controller/Notifications.php]: Fair enough.

If we can avoid another annotation we should go for it… I share your doubts about it, too. Thus tending towards an explicit statement.

**Review by blizzz — APPROVED** [review]
as discussed

File: apps/comments/lib/Controller/Notifications.php (hunk 1 above)
Comment (rullzer) [reply apps/comments/lib/Controller/Notifications.php]: So why isn't the default logic kicking in (to redirect if not logged in)?

Anyway lets do this as it is a bit specific to comments anyway.

**Review by rullzer — APPROVED** [review]
I rebased to run the tests again lets see :)
