### PR TITLE
fix(userstatus): CALL status should overwrite MEETING status

### LINKED ISSUE #42451: [Bug]: userstatus - "In a call" should take precedence over "In a meeting"
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When a user is in a call, the "in a call message" should be written. If the meeting automation sets its status earlier, then it might not be overwritten by in a call

### Steps to reproduce

1. Have meeting in calendar
2. start call
3. Meeting status is not overwritten

### Expected behavior

Meeting status is overwritten.

It needs a rollback of a possible "In a meeting" status in the "In a call" automation.

### Installation method

None

### Nextcloud Server version

28

### Operating system

Other

### PHP engine version

Other

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by miaulalala**
* Resolves: https://github.com/nextcloud/server/issues/42451

## Summary

When a meeting status is set, the call status will not be written if a backup exists. The code now shortcuts this single scenario and overwrites the existing status "In a meeting" with the "In a call" status irregardless of a backup status, since both are automated status and will revert to the backup after their respective automation has run.

This also fixes the issue of having a call while "in a meeting" is set, leaving the call, and the meeting status not coming back after.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/dav/lib/CalDAV/Status/StatusService.php [hunk 1]
```diff
@@ -123,19 +124,21 @@ public function processCalendarStatus(string $userId): void {
...
-		$this->logger->debug("Found $count applicable event(s), changing user status", ['user' => $userId]);
-		$this->userStatusService->setUserStatus(
-			$userId,
-			IUserStatus::AWAY,
-			IUserStatus::MESSAGE_CALENDAR_BUSY,
-			true
-		);
-
+		// Only update the status if it's neccesary otherwise we mess up the timestamp
+		if($currentStatus !== null && $currentStatus->getMessageId() !== IUserStatus::MESSAGE_CALENDAR_BUSY) {
```
Comment (ChristophWurst) [inline apps/dav/lib/CalDAV/Status/StatusService.php:128]: what would be messed up?

Comment (miaulalala) [reply apps/dav/lib/CalDAV/Status/StatusService.php:128]: I've had that in my local env. The timestamp is updated, thus the DTSTART is lower than the timestamp - which leads to a reset because no event is found (which is wrong).

File: apps/user_status/lib/Service/StatusService.php [hunk 2]
```diff
@@ -257,21 +255,38 @@ public function setUserStatus(string $userId,
...
+			$userStatus->setStatusTimestamp($this->timeFactory->getTime());
+			$userStatus->setIsUserDefined(true);
+			$userStatus->setIsBackup(false);
+			$userStatus->setMessageId($messageId);
+			$userStatus->setCustomIcon(null);
+			$userStatus->setCustomMessage($customMessage);
+			$userStatus->setClearAt(null);
+			$userStatus->setStatusMessageTimestamp($this->timeFactory->now()->getTimestamp());
+			return $this->mapper->update($userStatus);
+		}
```
Comment (ChristophWurst) [inline apps/user_status/lib/Service/StatusService.php:278]: :+1: makes sense

File: apps/dav/lib/CalDAV/Status/StatusService.php (hunk 1 above)
Comment (nickvergessen) [reply apps/dav/lib/CalDAV/Status/StatusService.php:128]: One of the unit tests fails, so I wonder if the test is actually right and the code here wrong?
Should it be:
```suggestion
		// Only update the status if it's neccesary otherwise we mess up the timestamp
		if ($currentStatus === null || $currentStatus->getMessageId() !== IUserStatus::MESSAGE_CALENDAR_BUSY) {
```

Otherwise the event status will only be set, when you had any status before?

**Review by nickvergessen — CHANGES_REQUESTED** [review]

**Review by nickvergessen — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Comment by nickvergessen** [comment]
Already done in https://github.com/nextcloud/server/pull/43107
