### PR TITLE
Properly check the data dir

### LINKED ISSUE #1364: Config htaccess.RewriteBase makes admin datadir check fail
### Steps to reproduce
1. Install
2. Set config `'htaccess.RewriteBase' => '/',`
3. Update the htaccess `./occ maintenance:update:htaccess`
4. Open admin page
### Expected behaviour

No warning
### Actual behaviour

> Your data directory and your files are probably accessible from the Internet. The .htaccess file is not working. We strongly suggest that you configure your web server in a way that the data directory is no longer accessible or you move the data directory outside the web server document root.

The problem is, that the check returns a 302, therefor does not match any more:
https://github.com/nextcloud/server/blob/44f3fcc187ed01a856dbd0ebdb2f2a090072d528/core/js/setupchecks.js#L201-L201

Not sure if adding 302 there is "save". Therefor I created the issue.
Maybe @LukasReschke knows more.

Reported by ThinkPrivacy in IRC

### PR DESCRIPTION
**Pull request by MorrisJobke**
* fixes #1364

cc @nickvergessen @LukasReschke @rullzer 

To test the setup check just comment out https://github.com/nextcloud/server/blob/506ccdbd8dd7a9438fa69fe09bc9307ca5f346e3/lib/private/Setup.php#L499-L499 and start the setup page.

To test the admin page check just remove the .htaccess file in the data dir and refresh ;)

### CODE REVIEW

File: core/js/setupchecks.js [hunk 1]
```diff
@@ -209,7 +210,7 @@
 
 			$.ajax({
 				type: 'GET',
-				url: OC.linkTo('', oc_dataURL+'/htaccesstest.txt?t=' + (new Date()).getTime()),
```
Comment (nickvergessen) [inline core/js/setupchecks.js]: then also kill the creation of this file

Comment (MorrisJobke) [inline core/js/setupchecks.js]: This was never created ;) (the server check creates it and kills it in the same call ;))

**Review by LukasReschke — APPROVED** [review]

**Comment by LukasReschke** [comment]
LGTM

**Comment by rullzer** [comment]
Lets do this. :+1:

**Comment by quenenni** [comment]
Hello,

I modified the 2 files but still have the same warning msg.
The call to "https://xxxxxxxxxxx/data/.ocdata?t=1481115617749" receives a response status of 200 and an empty responseText -> messages.push

Those things were checked:
- The file data/.ocdata exists and is accessible directly (not "Forbiden page" msg as it should be)
- The data/.htaccess file exists and should prevent the access to the data dir, 
- The AllowOverride All is in the vhost directives,
- The "Require all denied" is set for "<Directory /data/>" in the vhost file,
- I tested  that on a simple vhost, with just a data dir and the same .htaccess file => the access to the data dir is blocked.
