### PR TITLE
Fix: NotFoundException for anonymous users

### LINKED ISSUE #2435: OCP\Files\NotFoundException thrown when a file is submitted via link share and user is not logged in
Nextclod forms are working but i got a  NotFoundException Exception throw in the logfile if I submit a form.

-   Nextcloud-Version:  30.0.2 (Hub 9)
-   Forms-Version: 4.3.4
-

**Desktop (please complete the following information):**

-   OS: Linux
-   Browser: chrome
-   Version 131.0.6778.85

**Browser log**

```
ERROR] Files_PDFViewer: But this does not appear to be a public page Object
log @ index.mjs:54
```

<details>
<summary>Error in the logfile</summary>

```
[no app in context] Fehler: Exception thrown: OCP\Files\NotFoundException
	POST /cloud/ocs/v2.php/apps/forms/api/v3/forms/7/submissions

"reqId":"I505YQkFz1uV9lRhMF6D",
"level":3,
"time":"2024-11-27T10:35:51+00:00",
"remoteAddr":"x.x.x.x",
"user":"--",
"app":"no app in context",
"method":"POST",
"url":"/cloud/ocs/v2.php/apps/forms/api/v3/forms/7/submissions",
"message":"Exception thrown: OCP\\Files\\NotFoundException",
"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
"version":"30.0.2.2",
"exception": {
	"Exception":"OCP\\Files\\NotFoundException",
	"Message":"",
	"Code":0,
	"Trace":[
		{
			"file":"/var/www/nextcloud/lib/private/Files/Node/Node.php",
			"line":363,
			"function":"getFileInfo",
			"class":"OC\\Files\\Node\\Node",
			"type":"->"
		},{
			"file":"/var/www/nextcloud/apps/files_versions/lib/Listener/FileEventsListener.php",
			"line":362,
			"function":"getOwner",
			"class":"OC\\Files\\Node\\Node",
			"type":"->"
		},{
			"file":"/var/www/nextcloud/apps/files_versions/lib/Listener/FileEventsListener.php",
			"line":329,
			"function":"getPathForNode",
			"class":"OCA\\Files_Versions\\Listener\\FileEventsListener",
			"type":"->"
		},{
			"file":"/var/www/nextcloud/apps/files_versions/lib/Listener/FileEventsListener.php",
			"line":104,
			"function":"pre_renameOrCopy_hook",
			"class":"OCA\\Files_Versions\\Listener\\FileEventsListener",
			"type":"->"
		},{
			"file":"/var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php",
			"line":68,
			"function":"handle",
			"class":"OCA\\Files_Versions\\Listener\\FileEventsListener",
			"type":"->"
		},{
			"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
			"line":220,
			"function":"__invoke",
			"class":"OC\\EventDispatcher\\ServiceEventListener",
			"type":"->"
		},{
			"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
			"line":56,
			"function":"callListeners",
			"class":"Symfony\\Component\\EventDispatcher\\EventDispatcher",
			"type":"->"
		},{
			"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php",
			"line":67,
			"function":"dispatch",
			"class":"Symfony\\Component\\EventDispatcher\\EventDispatcher",
			"type":"->"
		},{
			"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php",
			"line":79,
			"function":"dispatch",
			"class":"OC\\EventDispatcher\\EventDispatcher",
			"type":"->"
		},{
			"file":"/var/www/nextcloud/lib/private/Files/Node/HookConnector.php",
			"line":155,
			"function":"dispatchTyped",
			"class":"OC\\EventDispatcher\\EventDispatcher",
			"type":"->"
		},{
			"file":"/var/www/nextcloud/lib/private/legacy/OC_Hook.php",
			"line":82,
			"function":"rename",
			"class":"OC\\Files\\Node\\HookConnector",
			"type":"->"
		},{
			"file":"/var/www/nextcloud/lib/private/Files/View.php",
			"line":737,
			"function":"emit",
			"class":"OC_Hook",
			"type":"::"
		},{
			"file":"/var/www/nextcloud/lib/private/Files/Node/Node.php",
			"line":448,
			"function":"rename",
			"class":"OC\\Files\\View",
			"type":"->"
		},{
			"file":"/var/www/nextcloud/apps/forms/lib/Controller/ApiController.php",
			"line":2727,
			"function":"move",
			"class":"OC\\Files\\Node\\Node",
			"type":"->"
		},{
			"file":"/var/www/nextcloud/apps/forms/lib/Controller/ApiController.php",
			"line":1176,
			"function":"storeAnswersForQuestion",
			"class":"OCA\\Forms\\Controller\\ApiController",
			"type":"->"
		},{
			"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
			"line":208,
			"function":"newSubmission",
			"class":"OCA\\Forms\\Controller\\ApiController",
			"type":"->"
		},{
			"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
			"line":114,
			"function":"executeController",
			"class":"OC\\AppFramework\\Http\\Dispatcher",
			"type":"->"
		},{
			"file":"/var/www/nextcloud/lib/private/AppFramework/App.php",
			"line":161,
			"function":"dispatch",
			"class":"OC\\AppFramework\\Http\\Dispatcher",
			"type":"->"
		},{
			"file":"/var/www/nextcloud/lib/private/Route/Router.php",
			"line":302,
			"function":"main",
			"class":"OC\\AppFramework\\App",
			"type":"::"
		},{
			"file":"/var/www/nextcloud/ocs/v1.php",
			"line":43,
			"function":"match",
			"class":"OC\\Route\\Router",
			"type":"->"
		},{
			"file":"/var/www/nextcloud/ocs/v2.php",
			"line":7,
			"args":["/var/www/nextcloud/ocs/v1.php"],
			"function":"require_once"
		}
	],
	"File":"/var/www/nextcloud/lib/private/Files/Node/Node.php",
	"Line":90,
	"CustomMessage":"Exception thrown: OCP\\Files\\NotFoundException"},
	"id":"6746f60985f0d"
}
```

</details>

### PR DESCRIPTION
**Pull request by Koc**
* Resolves: https://github.com/nextcloud/forms/issues/2435

- Follow-up of https://github.com/nextcloud/server/pull/41749

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by come-nc — APPROVED** [review]

File: apps/files_versions/lib/Listener/FileEventsListener.php [hunk 1]
```diff
@@ -359,7 +359,11 @@ private function getPathForNode(Node $node): ?string {
 			}
 		}
 
-		$owner = $node->getOwner()?->getUid();
+		try {
+			$owner = $node->getOwner()?->getUid();
```
Comment (susnux) [inline apps/files_versions/lib/Listener/FileEventsListener.php:363]: Is this not a deeper problem @come-nc ?
So this method is not marked as throwing, but just to return null if not found. 
Meaning should we fix the getOwner method or at least add the throwing to the docs?

Comment (come-nc) [reply apps/files_versions/lib/Listener/FileEventsListener.php:363]: This is how we manage non-existing files, see https://github.com/nextcloud/server/blob/master/lib/private/Files/Node/NonExistingFile.php

We could mark all methods as throwing but that would trigger a lot of false positive.

Comment (come-nc) [reply apps/files_versions/lib/Listener/FileEventsListener.php:363]: Actually for getOwner the throw comes from Node::getFileInfo directly I think.

Comment (susnux) [reply apps/files_versions/lib/Listener/FileEventsListener.php:363]: But in this case the file exists

**Review by susnux — APPROVED** [review]

File: apps/files_versions/lib/Listener/FileEventsListener.php (hunk 1 above)
Comment (come-nc) [reply apps/files_versions/lib/Listener/FileEventsListener.php:363]: No it does not.
Look at the trace in https://github.com/nextcloud/forms/issues/2435
It’s triggered by rename hook, so either source or target does not exist, depending if we are in the pre- or post- rename hook/event.
