### PR TITLE
fix(dav): add missing database index for dav_shares

### LINKED ISSUE #46015: [Bug]: Missing database index for dav_shares resourceid, type and access
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The database query
```sql
SELECT
  `publicuri`
FROM
  `oc_dav_shares`
WHERE
  (`resourceid` = ?)
  AND (`access` = ?)
```
does not always use an index:

image

Query id is 03601b9aa9c7478bcc9506bd3b202407.

### Steps to reproduce

1. ???

### Expected behavior

Efficient queries

### Installation method

None

### Nextcloud Server version

29

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by SebastianKrupinski**
* Resolves: #46015

## Summary
Added missing database indexes for dav_shares table, (resourceid, type) and (recourseid, access)

### CODE REVIEW

**Review by st3iny — APPROVED** [review]
Looks good otherwise.

**Comment by ChristophWurst** [comment]
Otherwise ... what?

File: apps/dav/lib/AppInfo/Application.php [hunk 1]
```diff
@@ -292,4 +306,5 @@ public function registerCalendarReminders(NotificationProviderManager $manager,
 			$logger->error($ex->getMessage(), ['exception' => $ex]);
 		}
 	}
+
```
Comment (st3iny) [inline apps/dav/lib/AppInfo/Application.php:309]:
```suggestion
```

My review somehow wasn't submitted 🙈

**Review by miaulalala — APPROVED** [review]
+1

File: apps/dav/lib/AppInfo/Application.php [hunk 2]
```diff
@@ -235,6 +236,19 @@ public function registerHooks(HookManager $hm,
 
 			// Here we should recalculate if reminders should be sent to new or old sharees
 		});
+
+		$dispatcher->addListener(AddMissingIndicesEvent::class, function (AddMissingIndicesEvent $event) {
```
Comment (juliushaertl) [inline apps/dav/lib/AppInfo/Application.php:240]: A separate listener class registered in the register method would be better as it is more lazy. Ideally we'd get rid of anything in boot 🙈

Comment (SebastianKrupinski) [reply apps/dav/lib/AppInfo/Application.php:240]: @juliushaertl I though of this when I was making the patch but just followed the existing code patterns. I will create a listener class.

File: apps/dav/lib/Migration/Version1004Date20170825134824.php [hunk 3]
```diff
@@ -471,6 +471,8 @@ public function changeSchema(IOutput $output, \Closure $schemaClosure, array $op
 			]);
 			$table->setPrimaryKey(['id']);
 			$table->addUniqueIndex(['principaluri', 'resourceid', 'type', 'publicuri'], 'dav_shares_index');
+			$table->addIndex(['resourceid', 'type'], 'dav_shares_resourceid_type');
```
[the remark this answers is not in the document]
Comment (SebastianKrupinski) [reply apps/dav/lib/Migration/Version1004Date20170825134824.php:474]: @ChristophWurst Okay, will do

File: apps/dav/lib/Listener/AddMissingIndicesListener.php [hunk 4]
```diff
@@ -0,0 +1,28 @@
...
+/**
+ * SPDX-FileCopyrightText: 2022 Nextcloud GmbH and Nextcloud contributors
+ * SPDX-License-Identifier: AGPL-3.0-or-later
+ */
+namespace OCA\DAV\Listener;
+
+use OCP\EventDispatcher\Event;
+use OCP\EventDispatcher\IEventListener;
+
+class AddMissingIndicesListener implements IEventListener {
```
Comment (st3iny) [inline apps/dav/lib/Listener/AddMissingIndicesListener.php:13]:
```suggestion
/**
 * @template-implements IEventListener<Event|AddMissingIndicesEvent>
 */
class AddMissingIndicesListener implements IEventListener {
```

Is probably required to make Psalm happy.

File: apps/dav/lib/Listener/AddMissingIndicesListener.php [hunk 5]
```diff
@@ -0,0 +1,28 @@
...
+
+	public function handle(Event $event): void {
```
Comment (st3iny) [inline apps/dav/lib/Listener/AddMissingIndicesListener.php:15]:
```suggestion
	public function handle(Event $event): void {
		if (!($event instanceof AddMissingIndicesEvent)) {
			return;
		}
```

Good practice

File: apps/dav/lib/Listener/AddMissingIndicesListener.php [hunk 6]
```diff
@@ -0,0 +1,28 @@
+<?php
+
+declare(strict_types=1);
+/**
+ * SPDX-FileCopyrightText: 2022 Nextcloud GmbH and Nextcloud contributors
+ * SPDX-License-Identifier: AGPL-3.0-or-later
+ */
+namespace OCA\DAV\Listener;
+
+use OCP\EventDispatcher\Event;
```
Comment (st3iny) [inline apps/dav/lib/Listener/AddMissingIndicesListener.php:10]:
```suggestion
use OCP\DB\Events\AddMissingIndicesEvent;
use OCP\EventDispatcher\Event;
```

File: apps/dav/lib/Migration/Version1004Date20170825134824.php (hunk 3 above)
[the remark this answers is not in the document]
Comment (st3iny) [reply apps/dav/lib/Migration/Version1004Date20170825134824.php:475]: Done

File: apps/dav/lib/AppInfo/Application.php (hunk 2 above)
Comment (st3iny) [reply apps/dav/lib/AppInfo/Application.php]: Done

File: apps/dav/lib/Listener/AddMissingIndicesListener.php (hunk 4 above)
Comment (SebastianKrupinski) [reply apps/dav/lib/Listener/AddMissingIndicesListener.php:13]: You're write psalm was not happy.

File: apps/dav/lib/Listener/AddMissingIndicesListener.php [hunk 7]
```diff
@@ -0,0 +1,35 @@
+<?php
+
+declare(strict_types=1);
+/**
+ * SPDX-FileCopyrightText: 2022 Nextcloud GmbH and Nextcloud contributors
```
Comment (kesselb) [inline apps/dav/lib/Listener/AddMissingIndicesListener.php:5]:
```suggestion
 * SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
```

File: apps/dav/lib/AppInfo/Application.php [hunk 8]
```diff
@@ -235,6 +239,7 @@ public function registerHooks(HookManager $hm,
 
 			// Here we should recalculate if reminders should be sent to new or old sharees
 		});
+
```
Comment (ChristophWurst) [inline apps/dav/lib/AppInfo/Application.php:242]: :fire:

**Review by ChristophWurst — COMMENTED** [review]
Looks good! Please squash into on single commit

File: apps/dav/lib/Migration/Version1004Date20170825134824.php [hunk 9]
```diff
@@ -471,6 +471,9 @@ public function changeSchema(IOutput $output, \Closure $schemaClosure, array $op
 			]);
 			$table->setPrimaryKey(['id']);
 			$table->addUniqueIndex(['principaluri', 'resourceid', 'type', 'publicuri'], 'dav_shares_index');
+			// modified on 2024-6-21 to add performance improving indices on new instances
+			$table->addIndex(['resourceid', 'type'], 'dav_shares_resourceid_type');
```
Comment (Altahrim) [inline apps/dav/lib/Migration/Version1004Date20170825134824.php:475]: I don't know if `principaluri` is used for searches, but if not, it could make sense to change the unique index instead of adding this new one: 
```php
$table->addUniqueIndex(['resourceid', 'type', 'principaluri', 'publicuri'], 'dav_shares_index');
```
