### PR TITLE
fix(FederatedShareProvider): Delete external shares when groups are deleted or users removed from a group

### LINKED ISSUE #35159: [Bug]: Remote group share persists after user loses group membership
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

In a federated setting a remote group share remains available to the user once the share is accepted but the group membership is lost to the user, eg. by leaving said group. This behavior differs from local groups where group membership determines access to the group share. 

### Steps to reproduce

1. On two instances A and B enable remote group sharing (sending and receiving)
2. On instance B create a user `alice` and add the user to a group `users`
3. Create a remote group share to group `users` on instance B from instance A
4. As user `alice` accept the share
5. As user `alice` leave group `users`
6. The share remains available

### Expected behavior

The share should be lost to user `alice` when the group membership is dissolved. The behavior for group shares should be the same for local and remote group shares.

### Installation method

Other Community project

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

_No response_

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "debug": true,
        "profiler": true,
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/apps-extra",
                "url": "\/apps-extra",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/apps-writable",
                "url": "\/apps-writable",
                "writable": true
            }
        ],
        "allow_local_remote_servers": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "1025",
        "skeletondirectory": "\/skeleton",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "log_query": false,
        "query_log_file": "\/var\/www\/html\/data\/query.log",
        "diagnostics.logging": false,
        "diagnostics.logging.threshold": 0,
        "log.condition": {
            "apps": [
                "diagnostics",
                "admin_audit"
            ]
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "nextcloud2.home.arpa",
            "172.20.0.6",
            "localhost"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "26.0.0.0",
        "overwrite.cli.url": "https:\/\/nextcloud2.home.arpa",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "app_install_overwrite": [
            "vo_federation"
        ],
        "theme": "",
        "maintenance": false,
        "overwriteprotocol": "https"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - cloud_federation_api: 1.9.0
  - comments: 1.16.0
  - contactsinteraction: 1.7.0
  - dashboard: 7.6.0
  - dav: 1.25.0
  - federatedfilesharing: 1.16.0
  - federation: 1.16.0
  - files: 1.21.0
  - files_sharing: 1.18.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.0
  - lookup_server_connector: 1.14.0
  - oauth2: 1.14.0
  - provisioning_api: 1.16.0
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - systemtags: 1.16.0
  - theming: 2.1.0
  - twofactor_backupcodes: 1.15.0
  - updatenotification: 1.16.0
  - user_status: 1.6.0
  - viewer: 1.10.0
  - vo_federation: 0.0.4
  - weather_status: 1.6.0
  - workflowengine: 2.8.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - testing
  - user_ldap
  - user_oidc
```

### Nextcloud Signing status

```shell
Integrity checker has been disabled. Integrity cannot be verified.
```

### Nextcloud Logs

_No response_

### Additional info

_No response_

### LINKED ISSUE #50289: [Bug]: Shares with deleted groups are not cleared
### Bug description

Shares with deleted groups are not cleared by occ command.

occ sharing:delete-orphan-shares

### Steps to reproduce

1. share file with group A
2. delete group A as admin
3. giving sharer still sees that files is shared with group A

### Expected behavior

file share with group A should not be visible for anybody

### Nextcloud Server version

master

### PR DESCRIPTION
**Pull request by provokateurin**
Fixes https://github.com/nextcloud/server/issues/35159
Fixes https://github.com/nextcloud/server/issues/50289

## Summary

1. The FederatedShareProvider never implemented cleaning up shares when a group was deleted or a user was removed from a group.
2. The related hooks that are supposed to do the cleanup weren't working: https://github.com/nextcloud/server/pull/24041. While the PR removed the hooks, I'm not certain that it is the source of the problem because I believe the cleanup was still working a few months ago.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by come-nc — APPROVED** [review]

File: apps/federatedfilesharing/lib/FederatedShareProvider.php [hunk 1]
```diff
@@ -882,30 +882,60 @@ public function userDeleted($uid, $shareType) {
...
+		$cursor->closeCursor();
+		if ($parentShareIds === []) {
+			return;
+		}
+
+		$qb = $this->dbConnection->getQueryBuilder();
+		$parentShareIdsParam = $qb->createNamedParameter($parentShareIds, IQueryBuilder::PARAM_INT_ARRAY);
+		$qb->delete('share_external')
+			->where($qb->expr()->in('parent', $parentShareIdsParam))
+			->andWhere($qb->expr()->eq('user', $uid))
```
Comment (kyteinsky) [inline apps/federatedfilesharing/lib/FederatedShareProvider.php:937]:
```suggestion
			->andWhere($qb->expr()->eq('user', $qb->createNamedParameter($uid)))
```

**Review by kyteinsky — COMMENTED** [review]
thanks for the nice work!
a small related issue is that users added back/freshly added to the target remote share group do not have gain access to the share. Maybe we can throw in a user-added event here too?

**Comment by provokateurin** [comment]
Will add a behat test for the event listeners to ensure it works and doesn't break again.

**Review by kyteinsky — APPROVED** [review]
nice!
