### PR TITLE
fix reading the ldapIgnoreNamingRule config value

### LINKED ISSUE #6851: Setting ldapIgnoreNamingRules does not wrong
### Steps to reproduce
1. Set config.php `'ldapIgnoreNamingRules' => true,`
2.  Add throw exception to see the value in log

### Expected behaviour
https://github.com/nextcloud/server/blob/66a5a45c503269699666df61c605d67f3c72c7c0/apps/user_ldap/lib/Access.php#L1252

should be `true`.

### Actual behaviour
Not `true` (Seems to be `null`)

### Server configuration

**Operating system**: alpine

**Web server:** nginx

**Database:** SQLITE

**PHP version:**  7

**Nextcloud version:** Nextcloud 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**  Fresh install

**Where did you install Nextcloud from:**  linuxserver/nextcloud docker

**Signing status:**
<details>
<summary>Signing status</summary>

```
N/A
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
    'debug' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'datadirectory' => '/data',
  'trusted_domains' => 
  array (
    0 => '192.168.1.95:8443',
  ),
  'overwrite.cli.url' => 'https://192.168.1.95:8443',
  'dbtype' => 'sqlite3',
  'version' => '12.0.3.3',
  'installed' => true,
  'ldapIgnoreNamingRules' => true,
  'ldapProviderFactory' => '\\OCA\\User_LDAP\\LDAPProviderFactory',
);
```
</details>

**Are you using external storage, if yes which one:**  No

**Are you using encryption:**  No

**Are you using an external user-backend, if yes which one:**  LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
N/A
```
</details>

### Client configuration
**Browser:** N/A

**Operating system:** N/A

#### Web server error log
<details>
<summary>Web server error log</summary>

```
N/A
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
N/A
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
N/A
```
</details>

### PR DESCRIPTION
**Pull request by blizzz**
fixes #6851 

How to test: with 'ldapIgnoreNamingRules' set to true in config.php new LDAP user names ignore constraints (e.g. conversion to ascii or replacing anything but letters, numbers and some chars).

### CODE REVIEW

File: apps/user_ldap/lib/Configuration.php [hunk 1]
```diff
@@ -531,6 +531,7 @@ public function getConfigTranslationArray() {
 			'ldap_experienced_admin'            => 'ldapExperiencedAdmin',
 			'ldap_dynamic_group_member_url'     => 'ldapDynamicGroupMemberURL',
 			'ldap_default_ppolicy_dn'           => 'ldapDefaultPPolicyDN',
+			'ldapIgnoreNamingRules'             => 'ldapIgnoreNamingRules',	// syconfig
```
Comment (MorrisJobke) [inline apps/user_ldap/lib/Configuration.php]: Typo: `sysconfig`

Comment (blizzz) [reply apps/user_ldap/lib/Configuration.php]: 📝 ☑️

**Review by MorrisJobke — APPROVED** [review]

**Review by rullzer — APPROVED** [review]
