### PR TITLE
fix(login): Fix JS error on login grant page

### LINKED ISSUE #41098: [Bug]: grant.js :: HTMLCollection does not have a .forEach method
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

There is a mistake in the code of grant.js

### Steps to reproduce

1. Try to setup an application (e.g. floccus)
2. login
3. get stuck on the Grant access page

This is how I noticed the issue. There is a js stack trace:

```
Uncaught TypeError: wrapper.getElementsByClassName(...).forEach is not a function
```

### Expected behavior

no stacktrace and hopefully the grant is setup correctly :-) 

### Installation method

Community Docker image

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

I cannot to a PR right now but the code

```
  wrapper.getElementsByClassName('icon-confirm-white').forEach(function(el) {
```

should be replaced with for example

```
  Array.from(wrapper.getElementsByClassName('icon-confirm-white')).forEach(function(el) {
```

### PR DESCRIPTION
**Pull request by callmemagnus**
* Resolves: #41098

## Summary

`HTMLCollection` does not have a `forEach` method, so convert to array first.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by susnux — APPROVED** [review]
good catch, thank you!

**Comment by joshtrichards** [comment]
That code has been in-place since NC20 via #17683.

Why hasn't this lead to more bug reports... Or has it? 🤔

**Review by kesselb — APPROVED** [review]

File: core/js/login/grant.js [hunk 1]
```diff
@@ -3,7 +3,7 @@ document.querySelector('form').addEventListener('submit', function(e) {
 	if (wrapper === null) {
 		return
 	}
-	wrapper.getElementsByClassName('icon-confirm-white').forEach(function(el) {
+	Array.from(wrapper.getElementsByClassName('icon-confirm-white')).forEach(function(el) {
```
Comment (kesselb) [inline core/js/login/grant.js:6]: Or `wrapper.querySelectorAll` which returns a NodeList.

**Review by nfebe — APPROVED** [review]

**Review by artonge — APPROVED** [review]

File: core/js/login/grant.js (hunk 1 above)
Comment (susnux) [reply core/js/login/grant.js:6]: I think this is fine as `querySelectorAll` will have to do extra checks (the query could be anything) it will take much longer than you gain by omitting the array conversion.

Comment (susnux) [reply core/js/login/grant.js:6]: (At least when I last benchmarked both with ~1k elements it took twice as long :sweat_smile: )

**Comment by susnux** [comment]
Cypress is unrelated this seems to happen only on foreign repositories, somehow the 3rdparty submodule does not match up and then CI fails
