### PR TITLE
Calendar events email reminders

### LINKED ISSUE #3979: Implement calendar notifications by email (sent from the server)
The Google calendar allows for notifications to be sent via mail. While I can setup such events with the Google calendar app for a Nextcloud calendar (using a DAVdroid account) this does not work, and I don't get any email notification at all. Mail notifications are often more useful than the native notification subsystem of the client itself, since it can be used for automation, etc.

### PR DESCRIPTION
**Pull request by tcitworld**
fixes #3979

Okay, this seems ready.

What it looks like:
## Email
Capture d’écran du 2019-03-16 18-37-02

## Notifications
Capture d’écran du 2019-03-16 18-59-26
(Browser notifications come as well)

---
Edited by @georgehrke:

ToDo:
- [x] support recurring events
- [x] support repeat / duration

### CODE REVIEW

File: apps/dav/lib/CalDAV/CalDavBackend.php [hunk 1]
```diff
@@ -920,6 +921,14 @@ function createCalendarObject($calendarId, $objectUri, $calendarData) {
 		));
 		$this->addChange($calendarId, $objectUri, 1);
 
+		if (!is_null($this->dispatcher)) {
```
Comment (nickvergessen) [inline apps/dav/lib/CalDAV/CalDavBackend.php]: can not be null, since it's not nullable in the constructor?

File: apps/dav/lib/CalDAV/CalDavBackend.php [hunk 2]
```diff
@@ -973,6 +981,14 @@ function updateCalendarObject($calendarId, $objectUri, $calendarData) {
 		}
 		$this->addChange($calendarId, $objectUri, 2);
 
+		if (!is_null($this->dispatcher)) {
```
Comment (nickvergessen) [inline apps/dav/lib/CalDAV/CalDavBackend.php]: same here

File: apps/dav/lib/CalDAV/CalDavBackend.php [hunk 3]
```diff
@@ -1020,6 +1036,13 @@ function deleteCalendarObject($calendarId, $objectUri) {
 		$stmt->execute([$calendarId, $objectUri]);
 
 		$this->addChange($calendarId, $objectUri, 3);
+
+		if (!is_null($this->dispatcher)) {
```
Comment (nickvergessen) [inline apps/dav/lib/CalDAV/CalDavBackend.php]: and here

File: apps/dav/appinfo/app.php [hunk 4]
```diff
@@ -54,3 +55,20 @@ function(GenericEvent $event) use ($app) {
...
 });
+
+$manager = \OC::$server->getNotificationManager();
+$manager->registerNotifier(function() {
+	return new Notifier(
+		\OC::$server->getL10NFactory()
+	);
+}, function() {
+	return [
+		'id' => 1,
```
Comment (nickvergessen) [inline apps/dav/appinfo/app.php]: id is `'dav_reminders'`

File: apps/dav/appinfo/app.php [hunk 5]
```diff
@@ -54,3 +55,20 @@ function(GenericEvent $event) use ($app) {
...
+		'name' => 'dav'
```
Comment (nickvergessen) [inline apps/dav/appinfo/app.php]: Should be translated and user friendly. In this case maybe "Calendar reminders"

**Review by nickvergessen — DISMISSED** [review]
What I dislike about this is all the duplication of notifications we will get with that.
The plan is to have notifications integrated into the mobile and desktop clients as well. So when you have an event coming up, you will have 4 notifications (laptop nextcloud, laptop calendar, phone nextcloud, phone calendar).

That is why I always stayed away from this notifications. Might make sense to have them in the web ui, but I think most people have at least one client running which already gives the notifications....

File: apps/dav/appinfo/app.php (hunk 4 above)
Comment (nickvergessen) [inline apps/dav/appinfo/app.php]: And also use that in the notifier itself as identifier.

**Comment by georgehrke** [comment]
> That is why I always stayed away from this notifications. Might make sense to have them in the web ui, but I think most people have at least one client running which already gives the notifications....

@nickvergessen 
The calendar standard defines different kinds of alarms. [Audio, display and email.](https://tools.ietf.org/html/rfc5545#page-73).
E-Mail alarms should obviously only be triggered when the user actually asked for an email :)

**Comment by rullzer** [comment]
What is the status here? Can this be reviewed soon?

**Comment by georgehrke** [comment]
@tcitworld What's your schedule for this feature? :)

**Comment by tcitworld** [comment]
Will change this to work on the backend already used for Activities made by @nickvergessen

**Comment by tcitworld** [comment]
Should emails reminders be sent to all `ATTENDEES` or just nextcloud users ?

**Comment by georgehrke** [comment]
> Should emails reminders be sent to all ATTENDEES or just nextcloud users ?

Did you check any  RFC for an answer on that? :)

**Comment by tcitworld** [comment]
When the action is "EMAIL", the alarm MUST include a "DESCRIPTION"
      property, which contains the text to be used as the message body,
      a "SUMMARY" property, which contains the text to be used as the
      message subject, and one or more "ATTENDEE" properties, which
      contain the email address of attendees to receive the message.  It
      can also include one or more "ATTACH" properties, which are
      intended to be sent as message attachments.  When the alarm is
      triggered, the email message is sent.

      [...]

      In an EMAIL alarm, the intended alarm effect is for an email
      message to be composed and delivered to all the addresses
      specified by the "ATTENDEE" properties in the "VALARM" calendar
      component.  The "DESCRIPTION" property of the "VALARM" calendar
      component MUST be used as the body text of the message, and the
      "SUMMARY" property MUST be used as the subject text.  Any "ATTACH"
      properties in the "VALARM" calendar component SHOULD be sent as
      attachments to the message.

@georgehrke @jancborchardt  Today, when you set an alarm, you are not automatically added as an attendee, but I guess you would like to get the notifications anyway. 
What about people with whom the calendar is shared (a group, for instance) ? Should they automatically get the notifications too while not manually added to `ATTENDEES` (they can be a lot) ?

Maybe an issue in calendar repo to automatically add yourself as an attendee ? Or another one to add a group as attendee ?

**Comment by tcitworld** [comment]
Also, if someone plz have a look why my notifications aren't displayed. :'(

**Comment by jancborchardt** [comment]
Sharing an event with someone should mean they are invited to add themselves as attending. But not set them as attending automatically.

**Comment by tcitworld** [comment]
> add themselves as attending

Would like to discuss more on that on the calendar app repo, maybe a easier way to add yourself as an attendee ? Would also be great if someone could tell me how Apple's iCal handle this for instance.

**Comment by pixelipo** [comment]
Hi @tcitworld any status on this? It's a killer feature for me and if there's a bounty, I'm willing to pitch in.

Also if you need some dev/design help, let me know.

**Comment by tcitworld** [comment]
[No bounty](https://www.bountysource.com/issues/43294685-implement-calendar-notifications-by-email-sent-from-the-server) yet. Feel free to have a look and add answers to my questions.

**Comment by georgehrke** [comment]
Not sure if there is a little confusion here:

We are talking about different kinds of attendees here.
There can be attendees in VEvents, the one you see in the event editor, and there are inside VAlarm blocks. The latter one are for sending out e-mail addresses. You can be an attendee inside the VAlarm block without being an actual attendee of the event.

> What about people with whom the calendar is shared (a group, for instance) ?

See my comment in https://github.com/nextcloud/server/issues/679#issuecomment-277437446

> Should they automatically get the notifications too while not manually added to ATTENDEES (they can be a lot) ?

They should be able to manage their own VAlarm block for each event and hence be able to add themselves for reminders. Not sure about the default here.
If u are an actual attendee of the event, you should get a notification too.

> Maybe an issue in calendar repo to automatically add yourself as an attendee ?

Yep, please open one :)

> Or another one to add a group as attendee ?

Maybe. It's important to provide an opt-out mechanism here imho.

**Comment by MorrisJobke** [comment]
@nickvergessen @tcitworld @georgehrke It doesn't look like something for 13, right?

**Comment by georgehrke** [comment]
No, we will have to postpone it

**Comment by Sebastian-Pohl** [comment]
Hello everybody, is the e-mail reminder in Nextcloud calendar app not working at all yet? If so, I do not have to check if me e-mail settings are somehow wrong. Same for ownCloud: Has it ever worked or is it a feature request here, too, to be implemented in the near future? Thank you, Sebastian

**Comment by FredMa01** [comment]
Hi 
same question than Sebastian about remind and new evenements notifications mails. 
The android app Etar propose remind mail but it doesnt work...
Thanks
Fred

**Comment by georgehrke** [comment]
> is the e-mail reminder in Nextcloud calendar app not working at all yet? 

Nope, it's not implemented yet. That's what this pull request is about.

>  Same for ownCloud: Has it ever worked or is it a feature request here, too, to be implemented in the near future?

Never worked, not aware of it being implemented at the moment, don't know about feature requests at ownCloud

**Comment by ClepToManix** [comment]
Hello, i have setuped the mail notify in my nc and this is still workling, but ive found a possibiltiy in calendar app to remind me via e-mail. If i checked this box my nextcloud still saying, that
E-mail reminders have not yet been implemented in the CalDAV server. What i have to do? Found nothing in documentation -.-

**Comment by georgehrke** [comment]
@tcitworld Can you estimate how much work is left here? :) 

What do you think about putting this up as a potential GSOC project?

**Comment by msharp1** [comment]
Hi, what's the status of this PR ? That's a must-have (and essential) feature to compete with Google...

**Comment by Nono-m0le** [comment]
Hi Guys,
I'm also very interested to have the feature (and the github notification).
IMO, I don't want to rely on any apps but want to get only mail notification.
still IMO, we should be able to email existing cloud user and non-existing/external email as well.

**Comment by MorrisJobke** [comment]
Nothing for 14 it seems -> moved to 15

**Comment by ulph0** [comment]
hi, left a feature request on nextcloud HP could you please tell me if @tcitworld or anyone else is still working on this and if not, tell me a starting point if i would like to do this for nextcloud?

**Comment by tcitworld** [comment]
> Also, I think it is important to have another type of notification, that is not a EMAIL, DISPLAY or AUDIO, but a HOOK to be used by another app.

Could be done through https://tools.ietf.org/id/draft-daboo-valarm-extensions-04.html#URI-ACTION

**Comment by MorrisJobke** [comment]
I guess we need to move this to 16 😢

**Comment by StCyr** [comment]
Hello, 

are there still things for which we can help in this matter?

I'm running NC 14.

Br,

Cyrille

**Comment by georgehrke** [comment]
> @tcitworld tcitworld force-pushed the dav-email-reminders  branch from a34c46f to c9b4ec0 14 days ago

Any update on this? :)

**Comment by tcitworld** [comment]
> Any update on this? :)

Advancing one step after another, you're free to have a look. ;)

File: apps/dav/lib/CalDAV/Reminder/NotificationProviderManager.php [hunk 6]
```diff
@@ -0,0 +1,54 @@
...
+class NotificationProviderManager {
+
+    /** @var array */
+    private $providers = [];
+
+    public function __construct(EmailProvider $emailProvider, PushProvider $pushProvider)
+    {
+        $this->providers[$emailProvider::NOTIFICATION_TYPE] = $emailProvider;
+        $this->providers[$pushProvider::NOTIFICATION_TYPE] = $pushProvider;
+    }
```
Comment (tcitworld) [inline apps/dav/lib/CalDAV/Reminder/NotificationProviderManager.php]: I would prefer an `addProvider()` method but I'm not sure how to instantiate things properly and where to do that.

File: apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php [hunk 7]
```diff
@@ -0,0 +1,153 @@
...
+	 * @return void
+	 * @throws \Exception
+	 */
+	public function send(VCalendar $vcalendar, IUser $user): void
+	{
+		if ($user->getEMailAddress() === null) {
+			return;
+		}
+
+		$this->setLangForUser($user);
```
Comment (tcitworld) [inline apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php]: This is dirty.

File: apps/dav/lib/CalDAV/Reminder/NotificationProviderManager.php (hunk 6 above)
Comment (nickvergessen) [reply apps/dav/lib/CalDAV/Reminder/NotificationProviderManager.php]: Also registration of a provider should not require an instance, but the class name only.

File: apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php [hunk 8]
```diff
@@ -0,0 +1,153 @@
...
+		$template->addFooter();
+		$message->useTemplate($template);
+
+		$attachment = $this->mailer->createAttachment(
+			$vcalendar->serialize(),
+			$event['uid'].'.ics',// TODO(leon): Make file name unique, e.g. add event id
+			'text/calendar'
+		);
+		$message->attach($attachment);
+		var_dump('Sending email');
```
Comment (nickvergessen) [inline apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php]: :see_no_evil:

File: apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php (hunk 7 above)
Comment (nickvergessen) [reply apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php]: Yeah, this looks wrong. Instead just pass in the language similar to notifications:
https://github.com/nextcloud/notifications/blob/master/lib/Controller/EndpointController.php#L92

**Review by nickvergessen — DISMISSED** [review]

File: apps/dav/lib/CalDAV/Reminder/NotificationProviderManager.php (hunk 6 above)
Comment (tcitworld) [reply apps/dav/lib/CalDAV/Reminder/NotificationProviderManager.php]: How can I instantiate providers then ? Through `SimpleContainer` in https://github.com/nextcloud/server/blob/master/apps/dav/lib/AppInfo/Application.php ?

File: apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php (hunk 8 above)
Comment (tcitworld) [reply apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php]: WIP's in the title. :)

File: apps/dav/lib/CalDAV/Reminder/NotificationProviderManager.php (hunk 6 above)
Comment (nickvergessen) [reply apps/dav/lib/CalDAV/Reminder/NotificationProviderManager.php]: https://github.com/nextcloud/server/blob/e24d5552814440f5c01ea3769f88ac2e0fcdb348/lib/private/Activity/Manager.php#L178-L196

Comment (tcitworld) [reply apps/dav/lib/CalDAV/Reminder/NotificationProviderManager.php]: Thanks ! :+1:

**Comment by tcitworld** [comment]
Okay, this seems ready.

What it looks like:
## Email
Capture d’écran du 2019-03-16 18-37-02

## Notifications
Capture d’écran du 2019-03-16 18-59-26
(Browser notifications come as well)

**Comment by jospoortvliet** [comment]
Exciting ;-)

**Comment by rullzer** [comment]
So CI is green. Lets get this in early once branched off

**Comment by jospoortvliet** [comment]
We're branched off, can I ping ping ping everyone ;-)
Time to merge all features :tada:

**Comment by georgehrke** [comment]
note to myself: 
Checklist: 
- [ ] what happens if i set up a reminder in the past
- [ ] test recurring events
- [ ] test recurrence exceptions
- [ ] are future reminders properly deleted when deleting an event
- [ ] ...

File: apps/dav/lib/CalDAV/Reminder/NotificationProvider/PushProvider.php [hunk 9]
```diff
@@ -0,0 +1,101 @@
...
+use OCP\Notification\IManager;
+use OCP\IUser;
+use OCP\Notification\INotification;
+use Sabre\VObject\Component\VCalendar;
+use OCP\AppFramework\Utility\ITimeFactory;
+
+class PushProvider extends AbstractNotificationProvider
+{
+
+	public const NOTIFICATION_TYPE = 'DISPLAY';
```
Comment (georgehrke) [inline apps/dav/lib/CalDAV/Reminder/NotificationProvider/PushProvider.php]: Maybe it would be good to handle both `DISPLAY` and `AUDIO` with the PushProvider for now.

At least, until we have proper audio notifications. Having a display instead of an audio notification is still better than not receiving the notification at all.

**Comment by georgehrke** [comment]
>  test recurring events

Recurring events are not supported at the moment. I would be fine with merging this without recurring events support for now, but I'm wondering whether we should already adapt the database structure to support it.

**Comment by georgehrke** [comment]
On MySQL i get the following error message: "An exception occurred while executing 'INSERT INTO `oc_calendar_reminders` (`uid`, `calendarid`, `objecturi`, `type`, `notificationdate`, `eventstartdate`) VALUES(?, ?, ?, ?, ?, ?)' with params [\"admin\", \"1\", \"5b673f82-9610-8d49-954a-7dab14d22caf.ics\", \"DISPLAY\", 1559828700, 1559829600]:\n\nSQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1559828700' for column 'notificationdate' at row 1"

File: apps/dav/lib/CalDAV/Reminder/AbstractNotificationProvider.php [hunk 10]
```diff
@@ -0,0 +1,208 @@
...
+
+	/**
+	 * Send notification
+	 *
+	 * @param VCalendar $vcalendar
+	 * @param string $calendarDisplayName
+	 * @param IUser $user
+	 * @return void
+	 */
+    public function send(VCalendar $vcalendar, string $calendarDisplayName, IUser $user): void {}
```
Comment (georgehrke) [inline apps/dav/lib/CalDAV/Reminder/AbstractNotificationProvider.php]: Maybe turn this into an abstract function to force subclasses to properly implement it?

**Comment by georgehrke** [comment]
ping @tcitworld :)

**Comment by wiswedel** [comment]
anyone motivated to move forward here?

**Comment by georgehrke** [comment]
@wiswedel I will for Nc 18. But right now it's time to polish the 17 release.

**Comment by georgehrke** [comment]
Todo for myself:
- [ ] Support for `RELATED=END` is missing.

**Comment by tcitworld** [comment]
> Support for RELATED=END is missing.

Odd, `VAlarm::getEffectiveTriggerTime()` should handle it.

**Comment by georgehrke** [comment]
Let me double check then, sorry. I only checked the code.

**Comment by georgehrke** [comment]
- [ ] This also needs a background job to fill oc_dav_reminders for existing entries

File: apps/dav/lib/CalDAV/Reminder/Backend.php [hunk 11]
```diff
@@ -0,0 +1,219 @@
...
+	 * Get all reminders with a notification date before now
+	 *
+	 * @return array
+	 * @throws \Exception
+	 */
+	public function getRemindersToProcess():array {
+		$query = $this->db->getQueryBuilder();
+		$query->select(['cr.*', 'co.calendardata', 'c.displayname', 'c.principaluri'])
+			->from('calendar_reminders', 'cr')
+//			->where($query->expr()->lte('cr.notification_date', $query->createNamedParameter($this->timeFactory->getTime())))
```
Comment (georgehrke) [inline apps/dav/lib/CalDAV/Reminder/Backend.php]: Todo: remove this comment before merging. 
it's only useful for testing to always trigger some reminders.

File: apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php [hunk 12]
```diff
@@ -0,0 +1,501 @@
...
+			$l10n = $this->getL10NForLang($lang);
+			$fromEMail = \OCP\Util::getDefaultEmailAddress('reminders-noreply');
+
+			$message = $this->mailer->createMessage();
+			$message->setFrom([$fromEMail]);
+			if ($organizer) {
+				$message->setReplyTo($organizer);
+			}
+			$message->setTo([])
+				->setBcc($emailAddresses);
```
Comment (georgehrke) [inline apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php]: @rullzer Do you know if this could cause any issue with certain mail servers? 

(Instead of sending out one email per attendee, we are only sending one email per language)

Comment (rullzer) [reply apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php]: Any reason to do this?
I guess the 99% of events do not ahve more than 10 attendees right?

Comment (georgehrke) [reply apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php]: An individual event probably not, but on a big instance it will not be uncommon to send out reminders for dozens of events at  a time, turning 10 attendees per event into hundreds of emails.

Comment (georgehrke) [reply apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php]: I'm fine with changing it, just thought it would be nice to take off load of the background-job and let the mailserver take care of sending out the individual emails.

File: apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php [hunk 13]
```diff
@@ -0,0 +1,501 @@
...
+		$emailAddresses = array_merge(
+			$emailAddressesOfAttendees,
+			$emailAddressesOfSharees
+		);
+
+		$sortedByLanguage = $this->sortEMailAddressesByLanguage($emailAddresses, $fallbackLanguage);
+		$organizer = $this->getOrganizerEMailAndNameFromEvent($vevent);
+
+		foreach($sortedByLanguage as $lang => $emailAddresses) {
+			if ($this->hasL10NForLang($lang)) {
```
Comment (hockdudu) [inline apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php]: Shouldn't this check be negated?

```suggestion
			if (!$this->hasL10NForLang($lang)) {
```

**Review by hockdudu — CHANGES_REQUESTED** [review]

File: apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php (hunk 13 above)
Comment (georgehrke) [reply apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php]: Indeed, let me fix that.

File: apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php (hunk 12 above)
Comment (rullzer) [reply apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php]: As far as I know most mailservers will accept this. But it might look weird.
You get stuff in you mail server like 'undisclosed-recipient' in the to field. Which looks silly IMO.

Comment (georgehrke) [reply apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php]: ok, let me change it tomorrow

Comment (tcitworld) [reply apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php]: Also it means the email can't be personalized for each attendee (even though we don't use this right now), so yeah, better send an email for each attendee.

File: apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php [hunk 14]
```diff
@@ -0,0 +1,500 @@
...
+			foreach ($emailAddresses as $emailAddress) {
+				$message = $this->mailer->createMessage();
+				$message->setFrom([$fromEMail]);
+				if ($organizer) {
+					$message->setReplyTo($organizer);
+				}
+				$message->setTo([$emailAddress]);
+				$message->useTemplate($template);
+
+				try {
```
Comment (fancycode) [inline apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php]: While you're at it: it would be great if you could dispatch an event here containing the message. This can be subscribed by other apps so they can modify / extend the message before it is sent out.

Comment (georgehrke) [reply apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php]: Can we do that in a  separate PR please? We are planning to release a beta of 17 later this week, so this has to get in if we want it in 17.

File: apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php [hunk 15]
```diff
@@ -0,0 +1,500 @@
...
+ * GNU Affero General Public License for more details.
+ *
+ * You should have received a copy of the GNU Affero General Public License
+ * along with this program.  If not, see <http://www.gnu.org/licenses/>.
+ *
+ */
+namespace OCA\DAV\CalDAV\Reminder\NotificationProvider;
+
+use DateTime;
+use DateTimeImmutable;
```
Comment (tcitworld) [inline apps/dav/lib/CalDAV/Reminder/NotificationProvider/EmailProvider.php]: `\DateTime` and `\DateTimeImmutable`

File: apps/dav/lib/BackgroundJob/BuildReminderIndexBackgroundJob.php [hunk 16]
```diff
@@ -0,0 +1,134 @@
...
+ * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+ * GNU Affero General Public License for more details.
+ *
+ * You should have received a copy of the GNU Affero General Public License
+ * along with this program.  If not, see <http://www.gnu.org/licenses/>.
+ *
+ */
+namespace OCA\DAV\BackgroundJob;
+
+use OC\BackgroundJob\QueuedJob;
```
Comment (rullzer) [inline apps/dav/lib/BackgroundJob/BuildReminderIndexBackgroundJob.php]: please use the one in OCP

File: apps/dav/lib/CalDAV/Reminder/Backend.php [hunk 17]
```diff
@@ -0,0 +1,219 @@
...
+
+use OCP\IDBConnection;
+use OCP\AppFramework\Utility\ITimeFactory;
+
+/**
+ * Class Backend
+ *
+ * @package OCA\DAV\CalDAV\Reminder
+ */
+class Backend {
```
Comment (rullzer) [inline apps/dav/lib/CalDAV/Reminder/Backend.php]: I'm fine with this for now. But it might make sense to try to eventually convert this to the Entity stuff of the appframework.

File: apps/dav/lib/CalDAV/Reminder/Notifier.php [hunk 18]
```diff
@@ -0,0 +1,316 @@
...
+
+		// Limiting to the first three components to prevent
+		// the string from getting too long
+		$firstThreeComponents = array_slice($components, 0, 2);
+		$diffLabel = implode(', ', $firstThreeComponents);
+
+		if ($diff->invert) {
+			$title = $this->l10n->t('%s (in %s)', [$title, $diffLabel]);
+		} else {
+			$title = $this->l10n->t('%s (%s ago)', [$title, $diffLabel]);
```
Comment (rullzer) [inline apps/dav/lib/CalDAV/Reminder/Notifier.php]: So i guess we either have to give good hints to the translators. Or we have to somehow fix this later to have proper translations. Because I can already see languages where this looks weird.

File: apps/dav/lib/CalDAV/Reminder/ReminderService.php [hunk 19]
```diff
@@ -0,0 +1,761 @@
...
+	/** @var IGroupManager */
+	private $groupManager;
+
+	/** @var CalDavBackend */
+	private $caldavBackend;
+
+	/** @var ITimeFactory */
+	private $timeFactory;
+
+	public const REMINDER_TYPE_EMAIL = 'EMAIL';
```
Comment (rullzer) [inline apps/dav/lib/CalDAV/Reminder/ReminderService.php]: If we have the types here. Shouldn't we just reference them from the providers themselfs?

File: apps/dav/lib/CalDAV/Reminder/ReminderService.php [hunk 20]
```diff
@@ -0,0 +1,761 @@
...
+	 */
+	public function onTouchCalendarObject(string $action,
+										  array $objectData):void {
+		// We only support VEvents for now
+		if (strcasecmp($objectData['component'], 'vevent') !== 0) {
+			return;
+		}
+
+		switch($action) {
+			case '\OCA\DAV\CalDAV\CalDavBackend::createCalendarObject':
```
Comment (rullzer) [inline apps/dav/lib/CalDAV/Reminder/ReminderService.php]: Ah magic string ;)
But yeah lets do it for now.

File: apps/dav/lib/Migration/Version1004Date20170825134824.php [hunk 21]
```diff
@@ -324,8 +324,7 @@ public function changeSchema(IOutput $output, \Closure $schemaClosure, array $op
 				'length' => 1,
 			]);
 			$table->addColumn('stripattachments', 'smallint', [
-				'notnull' => false,
-				'length' => 1,
+
```
Comment (rullzer) [inline apps/dav/lib/Migration/Version1004Date20170825134824.php]: uhm... why this? Then old intsallations won't be the the same as new ones...
If you want to change the attributes it should be handled in a migration

**Review by rullzer — CHANGES_REQUESTED** [review]
In general I'm all for merging this. I'm sure there are things we didn't think of yet. But lets get this in before it gets to huge.

I just wonder about the migration change.

File: apps/dav/lib/CalDAV/Reminder/ReminderService.php (hunk 19 above)
Comment (georgehrke) [reply apps/dav/lib/CalDAV/Reminder/ReminderService.php]: as in have a method `getSupportedTypes`?

File: apps/dav/lib/Migration/Version1004Date20170825134824.php (hunk 21 above)
Comment (georgehrke) [reply apps/dav/lib/Migration/Version1004Date20170825134824.php]: No clue what i did here, but not on purpose. Let me revert this.

**Comment by rullzer** [comment]
Depends on https://github.com/nextcloud/3rdparty/pull/321

**Review by rullzer — APPROVED** [review]
Looks good.
Lets see if phan is happy and get it in.

File: apps/dav/lib/CalDAV/Reminder/ReminderService.php (hunk 19 above)
Comment (remmesa) [reply apps/dav/lib/CalDAV/Reminder/ReminderService.php]: if you configure email reminder alert to calendar on nextcloud already please send step to configure take me

**Comment by remmesa** [comment]
> Also, if someone plz have a look why my notifications aren't displayed. :'(

**Comment by remmesa** [comment]
cloud to give me your ducement to configure email reminder alert to calendar on nextcloud

**Comment by Mic92** [comment]
Is this part of 17.0.1?
