### PR TITLE
fix(files_sharing): Prevent create/delete permissions on file shares

### LINKED ISSUE #53841: [Bug]: Error "Failed to update share" when using custom permissions during file sharing via email
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Encountering a “Failed to update share” error when using custom permissions while sharing a file via email.

### Steps to reproduce

1. Configure the following sharing settings:

- [X] Allow users to share via link and emails  
- [X] Always ask for a password  
- [ ] Enforce password protection
- [ ] Set default expiration date for shares   
- [ ] Set default expiration date for shares via link or mail  
- [ ] Enforce expiration date for remote shares

Default share permissions 

- [X] Create  
- [X] Change   
- [X] Delete  
- [ ] Reshare
 
2. Share a file via email and enter the recipient’s address.
3. The “Custom permissions” panel appears with Read, Edit, and Delete pre-selected.
4. Save the share.

Error message: “Failed to update share” but share works and user receives access to the file.

Observed this bug on NC 30.0.10.

### Expected behavior

No error message should be shown.

### Nextcloud Server version

30

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by nfebe**
File shares can't support create or delete permissions. This change ensures those permissions are stripped or ignored when the shared item is not a folder.

### CODE REVIEW

**Review by nfebe — COMMENTED** [review]
Tests pending

**Review by yemkareems — APPROVED** [review]

File: apps/files_sharing/src/views/SharingDetailsTab.vue [hunk 1]
```diff
@@ -38,7 +38,7 @@
 					<NcCheckboxRadioSwitch :button-variant="true"
 						data-cy-files-sharing-share-permissions-bundle="upload-edit"
 						:checked.sync="sharingPermission"
-						:value="bundledPermissions.ALL.toString()"
+						:value="isFolder ? bundledPermissions.ALL.toString() : bundledPermissions.ALL_FILE.toString()"
```
Comment (susnux) [inline apps/files_sharing/src/views/SharingDetailsTab.vue:41]: should this not better be a computed value?

**Review by susnux — APPROVED** [review]

File: apps/files_sharing/src/views/SharingDetailsTab.vue (hunk 1 above)
Comment (nfebe) [reply apps/files_sharing/src/views/SharingDetailsTab.vue:41]: Yes, it would make sense.

**Comment by AndyScherzinger** [comment]
Thanks a lot for the swift fix 🙏
