### PR TITLE
fix(settings): reset limit to groups state when switching apps

### LINKED ISSUE #20685: "Limit to groups" changes setting for all apps, not just the selected
I tried to use the "Limit to groups" settings to disable some apps for a certain user group, when I stumbled upon the following bug: everytime I check or uncheck this field for one app, the same setting is applied to all other apps as well. The list of groups is not affected, it behaves like expected.
Not shure if this issue belongs here or to [nextcloud/server](https://github.com/nextcloud/server).

## Details

* Browser and browser version: Firefox 74.0.1 and Safari 13.1 on MacOS 10.15.4

## JavaScript Console Output
marked(): sanitize and sanitizer parameters are deprecated since version 0.7.0, should not be used and will be removed in the future. Read more here: https://marked.js.org/#/USING_ADVANCED.md#options vue-7.js:1:23339

## Steps to reproduce

1. Log in to Nextcloud as Administrator, go to Apps
2. select one of the installed apps, e.g. Calendar
3. Check whether "Limit to groups" is checked
4. Select another app, e.g. Tasks
5. Click "Limit to groups" to change the setting
6. Go back to first app (Calendar) --> you will see the setting for "Limit to groups" changed according to the second app

### PR DESCRIPTION
**Pull request by pringelmann**
* Resolves: #20685

## Summary

Fixes an issue where "Limit to groups" settings leak between apps when navigating the sidebar.

#### Before:
https://github.com/user-attachments/assets/4b62e323-b800-40e1-a305-f7c6bad44bdd

#### After:
https://github.com/user-attachments/assets/5f409151-d34f-43cb-bd32-58954b9072e5

Vue was recycling the `AppDetailsTab` component, preserving its local state. I added `:key="app.id"` to `AppStoreSidebar` to force component re-creation when switching apps.

**Why this approach?**
I opted to force a re-mount instead of manually resetting state. While this introduces a negligible performance cost compared to instance reuse, it guarantees a 100% clean state for every app and allows us to remove fragile watcher logic. This makes the code more robust and easier to maintain.

 **A note on testing**
Unit tests were skipped because the settings app doesn't have a test harness set up yet.
 I also looked into adding this to the existing Cypress E2E tests, but it felt like overkill to spin up a full browser session just to check a checkbox state reset.

I manually verified the fix by switching between apps and confirming the "Limit to groups" setting resets correctly every time.

## Checklist

- [x] Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [x] [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)
- [ ] [Labels added](https://github.com/nextcloud/server/labels) where applicable (ex: bug/enhancement, `3. to review`, feature component)
- [ ] [Milestone added](https://github.com/nextcloud/server/milestones) for target branch/version (ex: 32.x for `stable32`)

### CODE REVIEW

File: apps/settings/src/components/AppStoreSidebar/AppDetailsTab.vue [hunk 1]
```diff
@@ -394,12 +394,6 @@ export default {
 		},
 	},
 
-	watch: {
-		'app.id': function() {
-			this.removeData = false
```
Comment (provokateurin) [inline apps/settings/src/components/AppStoreSidebar/AppDetailsTab.vue:399]: Can `removeData` get removed entirely? I only had a brief look, but didn't really understand what it's supposed to do.

Comment (pringelmann) [reply apps/settings/src/components/AppStoreSidebar/AppDetailsTab.vue:399]: Good question - I looked into it, seems this flag is not used by internal apps, however it is possible to supply this as a paramter to external apps to remove the docker volume on uninstall: 

https://github.com/nextcloud/app_api/blob/main/lib/Controller/ExAppsPageController.php#L435

**Review by provokateurin — APPROVED** [review]

**Review by sorbaugh — APPROVED** [review]

**Review by artonge — COMMENTED** [review]
Wouldn't a watcher on `app` work in this case? This would allow the `AppDetailsTab` component to properly react when the app changes.

**Comment by pringelmann** [comment]
> Wouldn't a watcher on `app` work in this case? This would allow the `AppDetailsTab` component to properly react when the app changes.

Yes, you're right that a watcher would work here, but I’d prefer to stick with the key approach.

The component relies on the `AppManagement` mixin which initializes state in `mounted()`, and also has its own local state like `removeData` and `deployOptions` that would need to be manually reset. Using `key` guarantees a clean state every time and feels much more future-proof, as we won't need to remember to update a watcher every time we add new local state or initialization logic.

**Review by artonge — APPROVED** [review]

**Comment by susnux** [comment]
> Using key guarantees a clean state every time and feels much more future-proof

Well its a performance drawback, on the long run we should properly clean the internal state so that we can reuse the mounted component. But agree with that mixin its harder to keep track of state, an additional reason to finally remove all of them.

**Comment by pringelmann** [comment]
> > Using key guarantees a clean state every time and feels much more future-proof
> 
> Well its a performance drawback, on the long run we should properly clean the internal state so that we can reuse the mounted component. But agree with that mixin its harder to keep track of state, an additional reason to finally remove all of them.

Agreed on all counts. The performance hit should be negligible for this component, but refactoring out the mixins to enable proper state reuse is definitely the better long-term goal
