### PR TITLE
fix(files): properly forward open params from short urls

### LINKED ISSUE #50155: [Bug]: Internal links lose `openfile` parameter value
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Ahoi,
when using the short file url for opening a file in a browser, the `openfile` query parameter gets lost on the internal redirects.

So, I do start with the request `https://my.nextcloud.internal/f/1337?openfile=false`. The nextcloud server redirects to something like `https://my.nextcloud.internal/apps/files/files/1337?dir=/Photos&openfile=true`. The file is opened.

My intention however is to open the file in the location, hence the given `openfile=false`, which gets lost in the redirect.

If I change the final url to `https://my.nextcloud.internal/apps/files/files/1337?dir=/Photos&openfile=false`, the desired state is displayed.

The issue was already reported inside another, related bug: https://github.com/nextcloud/server/issues/45731#issuecomment-2213846897

While the bug is fixed, this issue remains.

### Steps to reproduce

1. Fetch any file id of a file that has a browser preview, e.g. an `image/png`.
2. Browse to `https://[NEXTCLOUD_HOST]/f/[FILE_ID]?openfile=false`.

### Expected behavior

The browser view shows the parent directory and the chosen file is selected (details sidebar is open and file row is highlighted).

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json
{
    "system": {
        "htaccess.RewriteBase": "\/html\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "overwriteprotocol": "https",
        "overwrite.cli.url": "https:\/\/nextcloud-sub.local\/html",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud-sub.local"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "30.0.4.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "allow_local_remote_servers": "1",
        "theme": "",
        "loglevel": 2,
        "maintenance": false
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 3.0.0
  - app_api: 4.0.3
  - bruteforcesettings: 3.0.0
  - circles: 30.0.0
  - cloud_federation_api: 1.13.0
  - comments: 1.20.1
  - contactsinteraction: 1.11.0
  - dashboard: 7.10.0
  - dav: 1.31.1
  - federatedfilesharing: 1.20.0
  - federation: 1.20.0
  - files: 2.2.0
  - files_downloadlimit: 3.0.0
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - firstrunwizard: 3.0.0
  - groupfolders: 18.0.8
  - integration_openproject: 2.7.1
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - nextcloud_announcements: 2.0.0
  - notifications: 3.0.0
  - oauth2: 1.18.1
  - password_policy: 2.0.0
  - photos: 3.0.2
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - recommendations: 3.0.0
  - related_resources: 1.5.0
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - support: 2.0.0
  - survey_client: 2.0.0
  - systemtags: 1.20.0
  - text: 4.1.0
  - theming: 2.5.0
  - twofactor_backupcodes: 1.19.0
  - updatenotification: 1.20.0
  - user_status: 1.10.0
  - viewer: 3.0.0
  - weather_status: 1.10.0
  - webhook_listeners: 1.1.0-dev
  - workflowengine: 2.12.0
Disabled:
  - admin_audit: 1.20.0
  - encryption: 2.18.0
  - files_external: 1.22.0
  - suspicious_login: 8.0.0
  - twofactor_nextcloud_notification: 4.0.0
  - twofactor_totp: 12.0.0-dev
  - user_ldap: 1.21.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```json

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/server/issues/50155

### CODE REVIEW

File: lib/private/Route/Router.php [hunk 1]
```diff
@@ -160,11 +160,12 @@ public function loadRoutes($app = null) {
 				$this->root->addCollection($collection);
 			}
 		}
+
 		if (!isset($this->loadedApps['core'])) {
 			$this->loadedApps['core'] = true;
 			$this->useCollection('root');
 			$this->setupRoutes($this->getAttributeRoutes('core'), 'core');
-			require_once __DIR__ . '/../../../core/routes.php';
+			require __DIR__ . '/../../../core/routes.php';
```
Comment (skjnldsv) [inline lib/private/Route/Router.php:168]: This is an important point.
After a debug session with Christoph, we realised that it prevented routes.php files to be included again when running tests. Considering we already test that app have been loaded with `isset($this->loadedApps['core'])` and `isset($this->loadedApps[$app])`, we assumed it was safe to require/include without `_once`.

**Review by susnux — COMMENTED** [review]
Not fully sure as the opendetails is a new feature. Also I do not see any reason for neither having one of them for this endpoint. 

Meaning: if `openfile` is false set `opendetails`, setting both or none makes no sense.

File: apps/files/src/components/FilesListVirtual.vue [hunk 2]
```diff
@@ -220,23 +220,25 @@ export default defineComponent({
...
 
-				await this.handleOpenFile(this.fileId)
+				this.handleOpenFile(this.fileId)
 			},
 			immediate: true,
 		},
 
 		openDetails: {
-			handler() {
+			handler(openDetails) {
```
[the remark this answers is not in the document]
Comment (skjnldsv) [reply apps/files/src/components/FilesListVirtual.vue:234]: Code looking the same as the snipped above. Helps understanding both watchers behaves the same at quick glance

**Comment by skjnldsv** [comment]
> Meaning: if `openfile` is false set `opendetails`, setting both or none makes no sense.

I don't understand this sentence.
openfile and opendetails are two different properties, they have no link between each others.
you can  absolkutely have opendetails to true and openfile to false :thinking:

File: apps/files/lib/Controller/ViewController.php [hunk 3]
```diff
@@ -159,8 +156,6 @@ public function index($dir = '', $view = '', $fileid = null, $fileNotFound = fal
 				if (count($nodes) === 1 && $relativePath !== $dir && $nodePath !== $dir) {
 					return $this->redirectToFile((int)$fileid);
 				}
-			} else { // fileid does not exist anywhere
-				$fileNotFound = true;
```
Comment (come-nc) [inline apps/files/lib/Controller/ViewController.php:163]: I see that it seems `$fileNotFound` was not used, but I do remember recently being surprised to be silently redirected to index when following a link to a deleted file (or more probably a file I do not have access to).
There was this fileNotFound=true in the URL, but no error message on screen.

Is that fixed in an other way?

File: lib/private/Route/Router.php [hunk 4]
```diff
@@ -486,7 +487,7 @@ private function getAttributeRoutes(string $app): array {
 	 * @param string $appName
 	 */
 	private function requireRouteFile($file, $appName) {
-		$this->setupRoutes(include_once $file, $appName);
+		$this->setupRoutes(include $file, $appName);
```
Comment (come-nc) [inline lib/private/Route/Router.php:490]: What the hell I had no idea this is valid syntax :see_no_evil:

**Review by come-nc — COMMENTED** [review]
I agree with susnux comments about adding typing.
The logic around opendetails/openfile looks solid, so my only blocker here is this fileNotFound situation.

File: apps/files/lib/Controller/ViewController.php (hunk 3 above)
Comment (skjnldsv) [reply apps/files/lib/Controller/ViewController.php:163]: yes, we don't use that anymore

Comment (skjnldsv) [reply apps/files/lib/Controller/ViewController.php:163]: Hmm, actually you're partially right, we stopped showing a message when the short url redirect fails.
I'll have a look

File: lib/private/Route/Router.php (hunk 4 above)
Comment (skjnldsv) [reply lib/private/Route/Router.php:490]: Spent 1h debugging with Christoph, it was fun

**Comment by susnux** [comment]
> I don't understand this sentence.
> openfile and opendetails are two different properties, they have no link between each others.
> you can absolkutely have opendetails to true and openfile to false 🤔

Not sure about all apps (if you can control the sidebar when the file is opened), but if thats the case then maybe.

But my point was more like: That "internal link" feature make no sense with `openfile=false&opendetails=false` it also makes rather no sense with `openfile&opendetails`.
So what I mean is:

- if `/f/1234?openfile`
  - then `/apps/files/files/1234?openfile`
- if `/f/1234`
  - then `/apps/files/files/1234?openfile` (default open)
- if `/f/1234?openfile=false`
  - then `/apps/files/files/1234?opendetails`

Meaning there is no need for `opendetails` on the `/f/1234` endpoint as its value is implicit from the `openfile` value, because having both `true` or both `false` makes no sense for internal links.

That beeing said its no blocker from my side, having this new feature (parsing `opendetails´ on the internal-link endpoint) just makes no sense to me, but maybe I am overlooking something here :sweat_smile:

File: apps/files/lib/Controller/ViewController.php [hunk 5]
```diff
@@ -82,16 +82,18 @@ protected function getStorageInfo(string $dir = '/') {
 	 */
 	#[NoAdminRequired]
 	#[NoCSRFRequired]
-	public function showFile(?string $fileid = null): Response {
+	public function showFile(?string $fileid = null, ?string $opendetails = null, ?string $openfile = null): Response {
```
Comment (susnux) [inline apps/files/lib/Controller/ViewController.php:85]: What I meant is adding `openfile` here is a bugfix :white_check_mark: 
Adding `opendetails` is a feature I do not see the usecase on this endpoint.

**Review by susnux — APPROVED** [review]
Code looks sane :white_check_mark:

File: apps/files/lib/Controller/ViewController.php (hunk 5 above)
Comment (skjnldsv) [reply apps/files/lib/Controller/ViewController.php:85]: Ah right, it's kinda both you're right!
I'll adjust the backports to only cover the openfile anyway :)

**Comment by skjnldsv** [comment]
> Meaning there is no need for `opendetails` on the `/f/1234` endpoint as its value is implicit from the `openfile` value, because having both `true` or both `false` makes no sense for internal links.

Ah, yes there is the need, because otherwise the openXxxxx will be stripped from the URL.
Since We're fixing the open param for `openfile`, better do it properly and also cover the other `open` param: `opendetails`.

It's not about being a bugfix or not, it's mainly like: "since we're here, better do it properly and make it feature complete" :)

**Review by come-nc — APPROVED** [review]
