### PR TITLE
fix(ObjectStore): Fix regression when hostname is empty

### LINKED ISSUE #45637: S3 causes an issue when no hostname is set.
https://github.com/nextcloud/server/blob/3bb0c9b012f0e87ccddd37e4782d3fb5ae2025a6/lib/private/Files/ObjectStore/S3ConnectionTrait.php#L74

But according to the docs, a hostname doesn't have to be set.

Message in the log: `Undefined array key "hostname" at /var/www/html/lib/private/Files/ObjectStore/S3ConnectionTrait.php#74`

Version: 29.0.1

### PR DESCRIPTION
**Pull request by joshtrichards**
* Fixes #45637 

## Summary

The support for s3-accelerate added in #44496 introduced a regression in AWS S3 environments when `hostname` is blank (which is a valid configuration w/ AWS since the hostname gets auto-generated).

## TODO

- [x] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Review by kesselb — APPROVED** [review]

File: lib/private/Files/ObjectStore/S3ConnectionTrait.php [hunk 1]
```diff
@@ -44,7 +44,7 @@ protected function parseParams($params) {
 		$this->copySizeLimit = $params['copySizeLimit'] ?? 5242880000;
 		$this->useMultipartCopy = (bool)($params['useMultipartCopy'] ?? true);
 		$params['region'] = empty($params['region']) ? 'eu-west-1' : $params['region'];
-		$params['s3-accelerate'] = $params['hostname'] == 's3-accelerate.amazonaws.com' || $params['hostname'] == 's3-accelerate.dualstack.amazonaws.com';
+		$params['s3-accelerate'] = isset($params['hostname']) && ($params['hostname'] === 's3-accelerate.amazonaws.com' || $params['hostname'] === 's3-accelerate.dualstack.amazonaws.com');
```
Comment (susnux) [inline lib/private/Files/ObjectStore/S3ConnectionTrait.php:47]: Or just move it one line lower as the next line sets the fallback.

Comment (kesselb) [reply lib/private/Files/ObjectStore/S3ConnectionTrait.php:47]: @joshtrichards :ping_pong:

Comment (joshtrichards) [reply lib/private/Files/ObjectStore/S3ConnectionTrait.php]: Good call

**Review by susnux — APPROVED** [review]
