### PR TITLE
fix(files): disable `Unshare` until proper fix

### LINKED ISSUE #43130: [Bug]: Contents inside shared directory can be "Unshared" but are effectively deleted
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Inside a shared folder I can trigger an *Unshare* of of all files/folders. When I execute the action, the files are **deleted** for the sharerer.

image

*Unshare* should only be shown for the element that is shared, not it's children.

### Steps to reproduce

1. Create user1 and user2
2. Create "Shared folder" as user1
3. Upload a picture into "Shared folder" as user1
4. Share "Shared folder" with user2
5. Log in as user2
6. Go to "Shared folder"
7. Open the actions menu of the picture
8. Click *Unshare* (and note how there is no *Delete*)
9. Log in as user1
10. Open "Shared folder"

### Expected behavior

The picture is still there because user2 only unshared but didn't delete. At least that is what the UI says.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by skjnldsv**
Until we fix it for 28.0.3, it's safer to use the `Delete` wording

fix https://github.com/nextcloud/server/issues/43130

### CODE REVIEW

File: apps/files/src/actions/deleteAction.ts [hunk 1]
```diff
@@ -46,9 +46,10 @@ export const action = new FileAction({
 			return t('files', 'Delete and unshare')
```
Comment (szaimen) [inline apps/files/src/actions/deleteAction.ts:46]: Is this correct always?

Comment (nickvergessen) [reply apps/files/src/actions/deleteAction.ts:46]: Yeah, the problem is only the lower one, where you see unshare for children of shared folders, but clicking it executes a delete instead of unshare.

So showing both is fine, as you kind of agree to "yolo".

Comment (szaimen) [reply apps/files/src/actions/deleteAction.ts:46]: But is this always also shared?

**Comment by nickvergessen** [comment]
Conflict from https://github.com/nextcloud/server/pull/43084

File: apps/files/src/actions/deleteAction.ts (hunk 1 above)
Comment (skjnldsv) [reply apps/files/src/actions/deleteAction.ts]: @szaimen is right, removed as well!
I have a much rather improved fix coming next week

**Review by susnux — APPROVED** [review]

File: apps/files/src/actions/deleteAction.ts [hunk 2]
```diff
@@ -24,40 +24,17 @@ import { Permission, Node, View, FileAction } from '@nextcloud/files'
...
-			return t('files', 'Delete and unshare')
-		}
-
-		if (isAllUnshare(nodes)) {
-			return t('files', 'Unshare')
-		}
-
 		return view.id === 'trashbin'
 			? t('files', 'Delete permanently')
 			: t('files', 'Delete')
```
Comment (szaimen) [inline apps/files/src/actions/deleteAction.ts:35]: Maybe then?
```suggestion
			: t('files', 'Delete and/or unshare')
```

Comment (skjnldsv) [reply apps/files/src/actions/deleteAction.ts:35]: No, it's a revert to a previous state, we can move on, but let's not re-introduce weird changes

Comment (szaimen) [reply apps/files/src/actions/deleteAction.ts:35]: Okay

**Review by szaimen — APPROVED** [review]
LGTM then but didnt test
