### PR TITLE
fix: Fix orphan shares blocking moving other shares

### LINKED ISSUE #46467: [Bug]: move shared folder: "Node for share not found"
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I move a shared folder, I got the following error in log :

> SyntaxErrorException
> An exception occurred while executing a query: SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near ")" LINE 1: ...level" = $1) WHERE ("sh"."share_type" = $2) AND (()) AND ("s... ^
> Exception thrown: Doctrine\DBAL\Exception\SyntaxErrorException

I got this error only for some shared folders. I got this message because I activated the teams app. Before the teams app activated, I got the error message in log  :

> NotFoundException
> Node for share not found, fileid: 13485

### Steps to reproduce

1. Share a folder with files to another user of your instance
2. the other user move the shared folder in another folder

### Expected behavior

the other user move the shared folder in another folder

### Installation method

Community Docker image

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "nextcloud.example.com",
            "nginx-nextcloud"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "nextcloud.example.com",
        "overwriteprotocol": "https",
        "overwritewebroot": "\/",
        "overwirtecondaddr": "^172\\.18\\.0\\.3$",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "29.0.3.4",
        "overwrite.cli.url": "https:\/\/nextcloud.example.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 1,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "groupfolders",
            "files_mindmap"
        ],
        "onlyoffice": {
            "DocumentServerUrl": "\/ds-vpath\/",
            "DocumentServerInternalUrl": "http:\/\/onlyoffice\/",
            "StorageUrl": "http:\/\/nginx-nextcloud\/"
        },
        "allow_local_remote_servers": "true",
        "force_language": "fr",
        "default_locale": "fr_FR",
        "force_locale": "fr_FR",
        "default_language": "fr",
        "default_phone_region": "FR",
        "maintenance_window_start": "3",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "password": "***REMOVED SENSITIVE VALUE***"
        }
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.21.1
  - admin_audit: 1.19.0
  - announcementcenter: 6.8.1
  - calendar: 4.7.8
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - comments: 1.19.0
  - contactsinteraction: 1.10.0
  - dashboard: 7.9.0
  - dav: 1.30.1
  - drawio: 3.0.2
  - event_update_notification: 2.4.0
  - external: 5.4.0
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.0
  - files_downloadlimit: 2.0.0
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - firstrunwizard: 2.18.0
  - forms: 4.2.4
  - groupfolders: 17.0.1
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - nextcloud_announcements: 1.18.0
  - notes: 4.10.0
  - notifications: 2.17.0
  - oauth2: 1.17.0
  - onlyoffice: 9.2.2
  - password_policy: 1.19.0
  - photos: 2.5.0
  - polls: 7.1.2
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - support: 1.12.0
  - survey_client: 1.17.0
  - systemtags: 1.19.0
  - text: 3.10.1
  - theming: 2.4.0
  - twofactor_backupcodes: 1.18.0
  - updatenotification: 1.19.1
  - user_ldap: 1.20.0
  - user_status: 1.9.0
  - viewer: 2.3.0
  - weather_status: 1.9.0
  - workflowengine: 2.11.0
Disabled:
  - bruteforcesettings: 2.9.0
  - encryption: 2.17.0
  - files_external: 1.21.0
  - files_mindmap: 0.0.30 (installed 0.0.30)
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - registration: 2.4.0 (installed 2.4.0)
  - spreed: 19.0.4 (installed 19.0.4)
  - suspicious_login: 7.0.0
  - twofactor_totp: 11.0.0-dev
  - whiteboard: 0.0.3 (installed 0.0.3)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```json
{
  "reqId": "4zrSqheBpcs4NYR7H09I",
  "level": 3,
  "time": "2024-07-12T09:53:03+00:00",
  "remoteAddr": "134.214.47.72",
  "user": "aa262220-78ae-1039-8531-ed3c63ef8117",
  "app": "no app in context",
  "method": "MOVE",
  "url": "/remote.php/dav/files/aa262220-78ae-1039-8531-ed3c63ef8117/DMP",
  "message": "Exception thrown: Doctrine\\DBAL\\Exception\\SyntaxErrorException",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0",
  "version": "29.0.3.4",
  "exception": {
    "Exception": "Doctrine\\DBAL\\Exception\\SyntaxErrorException",
    "Message": "An exception occurred while executing a query: SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near \")\"\nLINE 1: ...level\" = $1) WHERE (\"sh\".\"share_type\" = $2) AND (()) AND (\"s...\n                                                             ^",
    "Code": 7,
    "Trace": [
      {
        "file": "/var/www/html/3rdparty/doctrine/dbal/src/Connection.php",
        "line": 1943,
        "function": "convert",
        "class": "Doctrine\\DBAL\\Driver\\API\\PostgreSQL\\ExceptionConverter",
        "type": "->",
        "args": [
          [
            "Doctrine\\DBAL\\Driver\\PDO\\Exception"
          ],
          [
            "Doctrine\\DBAL\\Query"
          ]
        ]
      },
      {
        "file": "/var/www/html/3rdparty/doctrine/dbal/src/Connection.php",
        "line": 1885,
        "function": "handleDriverException",
        "class": "Doctrine\\DBAL\\Connection",
        "type": "->",
        "args": [
          [
            "Doctrine\\DBAL\\Driver\\PDO\\Exception"
          ],
          [
            "Doctrine\\DBAL\\Query"
          ]
        ]
      },
      {
        "file": "/var/www/html/3rdparty/doctrine/dbal/src/Connection.php",
        "line": 1106,
        "function": "convertExceptionDuringQuery",
        "class": "Doctrine\\DBAL\\Connection",
        "type": "->",
        "args": [
          [
            "Doctrine\\DBAL\\Driver\\PDO\\Exception"
          ],
          "SELECT \"sh\".\"id\", \"sh\".\"share_type\", \"sh\".\"share_with\", \"sh\".\"uid_owner\", \"sh\".\"uid_initiator\", \"sh\".\"parent\", \"sh\".\"item_type\", \"sh\".\"item_source\", \"sh\".\"item_target\", \"sh\".\"file_source\", \"sh\".\"file_target\", \"sh\".\"permissions\", \"sh\".\"attributes\", \"sh\".\"stime\", \"sh\".\"accepted\", \"sh\".\"expiration\", \"sh\".\"token\", \"sh\".\"mail_send\", \"sh_cc\".\"unique_id\" AS \"sh_cc_unique_id\", \"sh_cc\".\"name\" AS \"sh_cc_name\", \"sh_cc\".\"display_name\" AS \"sh_cc_display_name\", \"sh_cc\".\"sanitized_name\" AS \"sh_cc_sanitized_name\", \"sh_cc\".\"source\" AS \"sh_cc_source\", \"sh_cc\".\"description\" AS \"sh_cc_description\", \"sh_cc\".\"settings\" AS \"sh_cc_settings\", \"sh_cc\".\"config\" AS \"sh_cc_config\", \"sh_cc\".\"contact_addressbook\" AS \"sh_cc_contact_addressbook\", \"sh_cc\".\"contact_groupname\" AS \"sh_cc_contact_groupname\", \"sh_cc\".\"creation\" AS \"sh_cc_creation\", \"sh_cc_wn\".\"circle_id\" AS \"sh_cc_wn_circle_id\", \"sh_cc_wn\".\"member_id\" AS \"sh_cc_wn_member_id\", \"sh_cc_wn\".\"single_id\" AS \"sh_cc_wn_single_id\", \"sh_cc_wn\".\"user_id\" AS \"sh_cc_wn_user_id\", \"sh_cc_wn\".\"instance\" AS \"sh_cc_wn_instance\", \"sh_cc_wn\".\"user_type\" AS \"sh_cc_wn_user_type\", \"sh_cc_wn\".\"level\" AS \"sh_cc_wn_level\", \"sh_cc_wn\".\"status\" AS \"sh_cc_wn_status\", \"sh_cc_wn\".\"note\" AS \"sh_cc_wn_note\", \"sh_cc_wn\".\"contact_id\" AS \"sh_cc_wn_contact_id\", \"sh_cc_wn\".\"cached_name\" AS \"sh_cc_wn_cached_name\", \"sh_cc_wn\".\"cached_update\" AS \"sh_cc_wn_cached_update\", \"sh_cc_wn\".\"contact_meta\" AS \"sh_cc_wn_contact_meta\", \"sh_cc_wn\".\"joined\" AS \"sh_cc_wn_joined\" FROM \"oc_share\" \"sh\" LEFT JOIN \"oc_circles_circle\" \"sh_cc\" ON \"sh_cc\".\"unique_id\" = \"sh\".\"share_with\" LEFT JOIN \"oc_circles_member\" \"sh_cc_wn\" ON (\"sh_cc_wn\".\"circle_id\" = \"sh_cc\".\"unique_id\") AND (\"sh_cc_wn\".\"level\" = ?) WHERE (\"sh\".\"share_type\" = ?) AND (()) AND (\"sh\".\"parent\" IS NULL)",
          [
            9,
            7
          ],
          [
            1,
            1
          ]
        ]
      },
      {
        "file": "/var/www/html/lib/private/DB/Connection.php",
        "line": 328,
        "function": "executeQuery",
        "class": "Doctrine\\DBAL\\Connection",
        "type": "->",
        "args": [
          "SELECT \"sh\".\"id\", \"sh\".\"share_type\", \"sh\".\"share_with\", \"sh\".\"uid_owner\", \"sh\".\"uid_initiator\", \"sh\".\"parent\", \"sh\".\"item_type\", \"sh\".\"item_source\", \"sh\".\"item_target\", \"sh\".\"file_source\", \"sh\".\"file_target\", \"sh\".\"permissions\", \"sh\".\"attributes\", \"sh\".\"stime\", \"sh\".\"accepted\", \"sh\".\"expiration\", \"sh\".\"token\", \"sh\".\"mail_send\", \"sh_cc\".\"unique_id\" AS \"sh_cc_unique_id\", \"sh_cc\".\"name\" AS \"sh_cc_name\", \"sh_cc\".\"display_name\" AS \"sh_cc_display_name\", \"sh_cc\".\"sanitized_name\" AS \"sh_cc_sanitized_name\", \"sh_cc\".\"source\" AS \"sh_cc_source\", \"sh_cc\".\"description\" AS \"sh_cc_description\", \"sh_cc\".\"settings\" AS \"sh_cc_settings\", \"sh_cc\".\"config\" AS \"sh_cc_config\", \"sh_cc\".\"contact_addressbook\" AS \"sh_cc_contact_addressbook\", \"sh_cc\".\"contact_groupname\" AS \"sh_cc_contact_groupname\", \"sh_cc\".\"creation\" AS \"sh_cc_creation\", \"sh_cc_wn\".\"circle_id\" AS \"sh_cc_wn_circle_id\", \"sh_cc_wn\".\"member_id\" AS \"sh_cc_wn_member_id\", \"sh_cc_wn\".\"single_id\" AS \"sh_cc_wn_single_id\", \"sh_cc_wn\".\"user_id\" AS \"sh_cc_wn_user_id\", \"sh_cc_wn\".\"instance\" AS \"sh_cc_wn_instance\", \"sh_cc_wn\".\"user_type\" AS \"sh_cc_wn_user_type\", \"sh_cc_wn\".\"level\" AS \"sh_cc_wn_level\", \"sh_cc_wn\".\"status\" AS \"sh_cc_wn_status\", \"sh_cc_wn\".\"note\" AS \"sh_cc_wn_note\", \"sh_cc_wn\".\"contact_id\" AS \"sh_cc_wn_contact_id\", \"sh_cc_wn\".\"cached_name\" AS \"sh_cc_wn_cached_name\", \"sh_cc_wn\".\"cached_update\" AS \"sh_cc_wn_cached_update\", \"sh_cc_wn\".\"contact_meta\" AS \"sh_cc_wn_contact_meta\", \"sh_cc_wn\".\"joined\" AS \"sh_cc_wn_joined\" FROM \"oc_share\" \"sh\" LEFT JOIN \"oc_circles_circle\" \"sh_cc\" ON \"sh_cc\".\"unique_id\" = \"sh\".\"share_with\" LEFT JOIN \"oc_circles_member\" \"sh_cc_wn\" ON (\"sh_cc_wn\".\"circle_id\" = \"sh_cc\".\"unique_id\") AND (\"sh_cc_wn\".\"level\" = ?) WHERE (\"sh\".\"share_type\" = ?) AND (()) AND (\"sh\".\"parent\" IS NULL)",
          [
            9,
            7
          ],
          [
            1,
            1
          ],
          null
        ]
      },
      {
        "file": "/var/www/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php",
        "line": 344,
        "function": "executeQuery",
        "class": "OC\\DB\\Connection",
        "type": "->",
        "args": [
          "SELECT \"sh\".\"id\", \"sh\".\"share_type\", \"sh\".\"share_with\", \"sh\".\"uid_owner\", \"sh\".\"uid_initiator\", \"sh\".\"parent\", \"sh\".\"item_type\", \"sh\".\"item_source\", \"sh\".\"item_target\", \"sh\".\"file_source\", \"sh\".\"file_target\", \"sh\".\"permissions\", \"sh\".\"attributes\", \"sh\".\"stime\", \"sh\".\"accepted\", \"sh\".\"expiration\", \"sh\".\"token\", \"sh\".\"mail_send\", \"sh_cc\".\"unique_id\" AS \"sh_cc_unique_id\", \"sh_cc\".\"name\" AS \"sh_cc_name\", \"sh_cc\".\"display_name\" AS \"sh_cc_display_name\", \"sh_cc\".\"sanitized_name\" AS \"sh_cc_sanitized_name\", \"sh_cc\".\"source\" AS \"sh_cc_source\", \"sh_cc\".\"description\" AS \"sh_cc_description\", \"sh_cc\".\"settings\" AS \"sh_cc_settings\", \"sh_cc\".\"config\" AS \"sh_cc_config\", \"sh_cc\".\"contact_addressbook\" AS \"sh_cc_contact_addressbook\", \"sh_cc\".\"contact_groupname\" AS \"sh_cc_contact_groupname\", \"sh_cc\".\"creation\" AS \"sh_cc_creation\", \"sh_cc_wn\".\"circle_id\" AS \"sh_cc_wn_circle_id\", \"sh_cc_wn\".\"member_id\" AS \"sh_cc_wn_member_id\", \"sh_cc_wn\".\"single_id\" AS \"sh_cc_wn_single_id\", \"sh_cc_wn\".\"user_id\" AS \"sh_cc_wn_user_id\", \"sh_cc_wn\".\"instance\" AS \"sh_cc_wn_instance\", \"sh_cc_wn\".\"user_type\" AS \"sh_cc_wn_user_type\", \"sh_cc_wn\".\"level\" AS \"sh_cc_wn_level\", \"sh_cc_wn\".\"status\" AS \"sh_cc_wn_status\", \"sh_cc_wn\".\"note\" AS \"sh_cc_wn_note\", \"sh_cc_wn\".\"contact_id\" AS \"sh_cc_wn_contact_id\", \"sh_cc_wn\".\"cached_name\" AS \"sh_cc_wn_cached_name\", \"sh_cc_wn\".\"cached_update\" AS \"sh_cc_wn_cached_update\", \"sh_cc_wn\".\"contact_meta\" AS \"sh_cc_wn_contact_meta\", \"sh_cc_wn\".\"joined\" AS \"sh_cc_wn_joined\" FROM \"oc_share\" \"sh\" LEFT JOIN \"oc_circles_circle\" \"sh_cc\" ON \"sh_cc\".\"unique_id\" = \"sh\".\"share_with\" LEFT JOIN \"oc_circles_member\" \"sh_cc_wn\" ON (\"sh_cc_wn\".\"circle_id\" = \"sh_cc\".\"unique_id\") AND (\"sh_cc_wn\".\"level\" = :dcValue2) WHERE (\"sh\".\"share_type\" = :dcValue1) AND (()) AND (\"sh\".\"parent\" IS NULL)",
          [
            7,
            9
          ],
          [
            1,
            1
          ],
          null
        ]
      },
      {
        "file": "/var/www/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php",
        "line": 384,
        "function": "executeQuery",
        "class": "Doctrine\\DBAL\\Query\\QueryBuilder",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php",
        "line": 280,
        "function": "execute",
        "class": "Doctrine\\DBAL\\Query\\QueryBuilder",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/html/apps/circles/lib/Tools/Db/ExtendedQueryBuilder.php",
        "line": 1046,
        "function": "execute",
        "class": "OC\\DB\\QueryBuilder\\QueryBuilder",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/html/apps/circles/lib/Tools/Db/ExtendedQueryBuilder.php",
        "line": 942,
        "function": "getRows",
        "class": "OCA\\Circles\\Tools\\Db\\ExtendedQueryBuilder",
        "type": "->",
        "args": [
          [
            [
              "OCA\\Circles\\Db\\CoreQueryBuilder"
            ],
            "parseSimpleSelectSql"
          ],
          "OCA\\Circles\\Model\\ShareWrapper",
          []
        ]
      },
      {
        "file": "/var/www/html/apps/circles/lib/Db/ShareWrapperRequestBuilder.php",
        "line": 120,
        "function": "asItems",
        "class": "OCA\\Circles\\Tools\\Db\\ExtendedQueryBuilder",
        "type": "->",
        "args": [
          "OCA\\Circles\\Model\\ShareWrapper"
        ]
      },
      {
        "file": "/var/www/html/apps/circles/lib/Db/ShareWrapperRequest.php",
        "line": 294,
        "function": "getItemsFromRequest",
        "class": "OCA\\Circles\\Db\\ShareWrapperRequestBuilder",
        "type": "->",
        "args": [
          [
            "OCA\\Circles\\Db\\CoreQueryBuilder"
          ]
        ]
      },
      {
        "file": "/var/www/html/apps/circles/lib/Service/ShareWrapperService.php",
        "line": 204,
        "function": "getSharesByFileIds",
        "class": "OCA\\Circles\\Db\\ShareWrapperRequest",
        "type": "->",
        "args": [
          [],
          true
        ]
      },
      {
        "file": "/var/www/html/apps/circles/lib/ShareByCircleProvider.php",
        "line": 664,
        "function": "getSharesByFileIds",
        "class": "OCA\\Circles\\Service\\ShareWrapperService",
        "type": "->",
        "args": [
          [],
          true
        ]
      },
      {
        "file": "/var/www/html/lib/private/Share20/Manager.php",
        "line": 1691,
        "function": "getAccessList",
        "class": "OCA\\Circles\\ShareByCircleProvider",
        "type": "->",
        "args": [
          [],
          true
        ]
      },
      {
        "file": "/var/www/html/lib/private/Share20/ShareHelper.php",
        "line": 51,
        "function": "getAccessList",
        "class": "OC\\Share20\\Manager",
        "type": "->",
        "args": [
          [
            "OC\\Files\\Node\\Folder"
          ],
          true,
          true
        ]
      },
      {
        "file": "/var/www/html/apps/activity/lib/FilesHooks.php",
        "line": 598,
        "function": "getPathsForAccessList",
        "class": "OC\\Share20\\ShareHelper",
        "type": "->",
        "args": [
          [
            "OC\\Files\\Node\\Folder"
          ]
        ]
      },
      {
        "file": "/var/www/html/apps/activity/lib/FilesHooks.php",
        "line": 295,
        "function": "getUserPathsFromPath",
        "class": "OCA\\Activity\\FilesHooks",
        "type": "->",
        "args": [
          "/",
          "aa262220-78ae-1039-8531-ed3c63ef8117"
        ]
      },
      {
        "file": "/var/www/html/apps/activity/lib/FilesHooksStatic.php",
        "line": 67,
        "function": "fileMove",
        "class": "OCA\\Activity\\FilesHooks",
        "type": "->",
        "args": [
          "/DMP",
          "/DISP/DMP"
        ]
      },
      {
        "file": "/var/www/html/lib/private/legacy/OC_Hook.php",
        "line": 105,
        "function": "fileMove",
        "class": "OCA\\Activity\\FilesHooksStatic",
        "type": "::",
        "args": [
          [
            "/DMP",
            "/DISP/DMP",
            true
          ]
        ]
      },
      {
        "file": "/var/www/html/lib/private/Files/View.php",
        "line": 770,
        "function": "emit",
        "class": "OC_Hook",
        "type": "::",
        "args": [
          "OC_Filesystem",
          "rename",
          [
            "/DMP",
            "/DISP/DMP",
            true
          ]
        ]
      },
      {
        "file": "/var/www/html/apps/dav/lib/Connector/Sabre/Directory.php",
        "line": 454,
        "function": "rename",
        "class": "OC\\Files\\View",
        "type": "->",
        "args": [
          "/DMP",
          "/DISP/DMP"
        ]
      },
      {
        "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Tree.php",
        "line": 178,
        "function": "moveInto",
        "class": "OCA\\DAV\\Connector\\Sabre\\Directory",
        "type": "->",
        "args": [
          "DMP",
          "files/aa262220-78ae-1039-8531-ed3c63ef8117/DMP",
          [
            "OCA\\DAV\\Connector\\Sabre\\Directory"
          ]
        ]
      },
      {
        "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
        "line": 612,
        "function": "move",
        "class": "Sabre\\DAV\\Tree",
        "type": "->",
        "args": [
          "files/aa262220-78ae-1039-8531-ed3c63ef8117/DMP",
          "files/aa262220-78ae-1039-8531-ed3c63ef8117/DISP/DMP"
        ]
      },
      {
        "file": "/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "httpMove",
        "class": "Sabre\\DAV\\CorePlugin",
        "type": "->",
        "args": [
          [
            "Sabre\\HTTP\\Request"
          ],
          [
            "Sabre\\HTTP\\Response"
          ]
        ]
      },
      {
        "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 472,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "method:MOVE",
          [
            [
              "Sabre\\HTTP\\Request"
            ],
            [
              "Sabre\\HTTP\\Response"
            ]
          ]
        ]
      },
      {
        "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 253,
        "function": "invokeMethod",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          [
            "Sabre\\HTTP\\Request"
          ],
          [
            "Sabre\\HTTP\\Response"
          ]
        ]
      },
      {
        "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 321,
        "function": "start",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/html/apps/dav/lib/Server.php",
        "line": 379,
        "function": "exec",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/html/apps/dav/appinfo/v2/remote.php",
        "line": 35,
        "function": "exec",
        "class": "OCA\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/html/remote.php",
        "line": 172,
        "args": [
          "/var/www/html/apps/dav/appinfo/v2/remote.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/var/www/html/3rdparty/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php",
    "Line": 62,
    "Previous": {
      "Exception": "Doctrine\\DBAL\\Driver\\PDO\\Exception",
      "Message": "SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near \")\"\nLINE 1: ...level\" = $1) WHERE (\"sh\".\"share_type\" = $2) AND (()) AND (\"s...\n                                                             ^",
      "Code": 7,
      "Trace": [
        {
          "file": "/var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php",
          "line": 132,
          "function": "new",
          "class": "Doctrine\\DBAL\\Driver\\PDO\\Exception",
          "type": "::",
          "args": [
            [
              "PDOException",
              [
                "42601",
                7,
                "ERROR:  syntax error at or near \")\"\nLINE 1: ...level\" = $1) WHERE (\"sh\".\"share_type\" = $2) AND (()) AND (\"s...\n                                                             ^"
              ]
            ]
          ]
        },
        {
          "file": "/var/www/html/3rdparty/doctrine/dbal/src/Connection.php",
          "line": 1099,
          "function": "execute",
          "class": "Doctrine\\DBAL\\Driver\\PDO\\Statement",
          "type": "->",
          "args": []
        },
        {
          "file": "/var/www/html/lib/private/DB/Connection.php",
          "line": 328,
          "function": "executeQuery",
          "class": "Doctrine\\DBAL\\Connection",
          "type": "->",
          "args": [
            "SELECT \"sh\".\"id\", \"sh\".\"share_type\", \"sh\".\"share_with\", \"sh\".\"uid_owner\", \"sh\".\"uid_initiator\", \"sh\".\"parent\", \"sh\".\"item_type\", \"sh\".\"item_source\", \"sh\".\"item_target\", \"sh\".\"file_source\", \"sh\".\"file_target\", \"sh\".\"permissions\", \"sh\".\"attributes\", \"sh\".\"stime\", \"sh\".\"accepted\", \"sh\".\"expiration\", \"sh\".\"token\", \"sh\".\"mail_send\", \"sh_cc\".\"unique_id\" AS \"sh_cc_unique_id\", \"sh_cc\".\"name\" AS \"sh_cc_name\", \"sh_cc\".\"display_name\" AS \"sh_cc_display_name\", \"sh_cc\".\"sanitized_name\" AS \"sh_cc_sanitized_name\", \"sh_cc\".\"source\" AS \"sh_cc_source\", \"sh_cc\".\"description\" AS \"sh_cc_description\", \"sh_cc\".\"settings\" AS \"sh_cc_settings\", \"sh_cc\".\"config\" AS \"sh_cc_config\", \"sh_cc\".\"contact_addressbook\" AS \"sh_cc_contact_addressbook\", \"sh_cc\".\"contact_groupname\" AS \"sh_cc_contact_groupname\", \"sh_cc\".\"creation\" AS \"sh_cc_creation\", \"sh_cc_wn\".\"circle_id\" AS \"sh_cc_wn_circle_id\", \"sh_cc_wn\".\"member_id\" AS \"sh_cc_wn_member_id\", \"sh_cc_wn\".\"single_id\" AS \"sh_cc_wn_single_id\", \"sh_cc_wn\".\"user_id\" AS \"sh_cc_wn_user_id\", \"sh_cc_wn\".\"instance\" AS \"sh_cc_wn_instance\", \"sh_cc_wn\".\"user_type\" AS \"sh_cc_wn_user_type\", \"sh_cc_wn\".\"level\" AS \"sh_cc_wn_level\", \"sh_cc_wn\".\"status\" AS \"sh_cc_wn_status\", \"sh_cc_wn\".\"note\" AS \"sh_cc_wn_note\", \"sh_cc_wn\".\"contact_id\" AS \"sh_cc_wn_contact_id\", \"sh_cc_wn\".\"cached_name\" AS \"sh_cc_wn_cached_name\", \"sh_cc_wn\".\"cached_update\" AS \"sh_cc_wn_cached_update\", \"sh_cc_wn\".\"contact_meta\" AS \"sh_cc_wn_contact_meta\", \"sh_cc_wn\".\"joined\" AS \"sh_cc_wn_joined\" FROM \"oc_share\" \"sh\" LEFT JOIN \"oc_circles_circle\" \"sh_cc\" ON \"sh_cc\".\"unique_id\" = \"sh\".\"share_with\" LEFT JOIN \"oc_circles_member\" \"sh_cc_wn\" ON (\"sh_cc_wn\".\"circle_id\" = \"sh_cc\".\"unique_id\") AND (\"sh_cc_wn\".\"level\" = ?) WHERE (\"sh\".\"share_type\" = ?) AND (()) AND (\"sh\".\"parent\" IS NULL)",
            [
              9,
              7
            ],
            [
              1,
              1
            ],
            null
          ]
        },
        {
          "file": "/var/www/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php",
          "line": 344,
          "function": "executeQuery",
          "class": "OC\\DB\\Connection",
          "type": "->",
          "args": [
            "SELECT \"sh\".\"id\", \"sh\".\"share_type\", \"sh\".\"share_with\", \"sh\".\"uid_owner\", \"sh\".\"uid_initiator\", \"sh\".\"parent\", \"sh\".\"item_type\", \"sh\".\"item_source\", \"sh\".\"item_target\", \"sh\".\"file_source\", \"sh\".\"file_target\", \"sh\".\"permissions\", \"sh\".\"attributes\", \"sh\".\"stime\", \"sh\".\"accepted\", \"sh\".\"expiration\", \"sh\".\"token\", \"sh\".\"mail_send\", \"sh_cc\".\"unique_id\" AS \"sh_cc_unique_id\", \"sh_cc\".\"name\" AS \"sh_cc_name\", \"sh_cc\".\"display_name\" AS \"sh_cc_display_name\", \"sh_cc\".\"sanitized_name\" AS \"sh_cc_sanitized_name\", \"sh_cc\".\"source\" AS \"sh_cc_source\", \"sh_cc\".\"description\" AS \"sh_cc_description\", \"sh_cc\".\"settings\" AS \"sh_cc_settings\", \"sh_cc\".\"config\" AS \"sh_cc_config\", \"sh_cc\".\"contact_addressbook\" AS \"sh_cc_contact_addressbook\", \"sh_cc\".\"contact_groupname\" AS \"sh_cc_contact_groupname\", \"sh_cc\".\"creation\" AS \"sh_cc_creation\", \"sh_cc_wn\".\"circle_id\" AS \"sh_cc_wn_circle_id\", \"sh_cc_wn\".\"member_id\" AS \"sh_cc_wn_member_id\", \"sh_cc_wn\".\"single_id\" AS \"sh_cc_wn_single_id\", \"sh_cc_wn\".\"user_id\" AS \"sh_cc_wn_user_id\", \"sh_cc_wn\".\"instance\" AS \"sh_cc_wn_instance\", \"sh_cc_wn\".\"user_type\" AS \"sh_cc_wn_user_type\", \"sh_cc_wn\".\"level\" AS \"sh_cc_wn_level\", \"sh_cc_wn\".\"status\" AS \"sh_cc_wn_status\", \"sh_cc_wn\".\"note\" AS \"sh_cc_wn_note\", \"sh_cc_wn\".\"contact_id\" AS \"sh_cc_wn_contact_id\", \"sh_cc_wn\".\"cached_name\" AS \"sh_cc_wn_cached_name\", \"sh_cc_wn\".\"cached_update\" AS \"sh_cc_wn_cached_update\", \"sh_cc_wn\".\"contact_meta\" AS \"sh_cc_wn_contact_meta\", \"sh_cc_wn\".\"joined\" AS \"sh_cc_wn_joined\" FROM \"oc_share\" \"sh\" LEFT JOIN \"oc_circles_circle\" \"sh_cc\" ON \"sh_cc\".\"unique_id\" = \"sh\".\"share_with\" LEFT JOIN \"oc_circles_member\" \"sh_cc_wn\" ON (\"sh_cc_wn\".\"circle_id\" = \"sh_cc\".\"unique_id\") AND (\"sh_cc_wn\".\"level\" = :dcValue2) WHERE (\"sh\".\"share_type\" = :dcValue1) AND (()) AND (\"sh\".\"parent\" IS NULL)",
            [
              7,
              9
            ],
            [
              1,
              1
            ],
            null
          ]
        },
        {
          "file": "/var/www/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php",
          "line": 384,
          "function": "executeQuery",
          "class": "Doctrine\\DBAL\\Query\\QueryBuilder",
          "type": "->",
          "args": []
        },
        {
          "file": "/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php",
          "line": 280,
          "function": "execute",
          "class": "Doctrine\\DBAL\\Query\\QueryBuilder",
          "type": "->",
          "args": []
        },
        {
          "file": "/var/www/html/apps/circles/lib/Tools/Db/ExtendedQueryBuilder.php",
          "line": 1046,
          "function": "execute",
          "class": "OC\\DB\\QueryBuilder\\QueryBuilder",
          "type": "->",
          "args": []
        },
        {
          "file": "/var/www/html/apps/circles/lib/Tools/Db/ExtendedQueryBuilder.php",
          "line": 942,
          "function": "getRows",
          "class": "OCA\\Circles\\Tools\\Db\\ExtendedQueryBuilder",
          "type": "->",
          "args": [
            [
              [
                "OCA\\Circles\\Db\\CoreQueryBuilder"
              ],
              "parseSimpleSelectSql"
            ],
            "OCA\\Circles\\Model\\ShareWrapper",
            []
          ]
        },
        {
          "file": "/var/www/html/apps/circles/lib/Db/ShareWrapperRequestBuilder.php",
          "line": 120,
          "function": "asItems",
          "class": "OCA\\Circles\\Tools\\Db\\ExtendedQueryBuilder",
          "type": "->",
          "args": [
            "OCA\\Circles\\Model\\ShareWrapper"
          ]
        },
        {
          "file": "/var/www/html/apps/circles/lib/Db/ShareWrapperRequest.php",
          "line": 294,
          "function": "getItemsFromRequest",
          "class": "OCA\\Circles\\Db\\ShareWrapperRequestBuilder",
          "type": "->",
          "args": [
            [
              "OCA\\Circles\\Db\\CoreQueryBuilder"
            ]
          ]
        },
        {
          "file": "/var/www/html/apps/circles/lib/Service/ShareWrapperService.php",
          "line": 204,
          "function": "getSharesByFileIds",
          "class": "OCA\\Circles\\Db\\ShareWrapperRequest",
          "type": "->",
          "args": [
            [],
            true
          ]
        },
        {
          "file": "/var/www/html/apps/circles/lib/ShareByCircleProvider.php",
          "line": 664,
          "function": "getSharesByFileIds",
          "class": "OCA\\Circles\\Service\\ShareWrapperService",
          "type": "->",
          "args": [
            [],
            true
          ]
        },
        {
          "file": "/var/www/html/lib/private/Share20/Manager.php",
          "line": 1691,
          "function": "getAccessList",
          "class": "OCA\\Circles\\ShareByCircleProvider",
          "type": "->",
          "args": [
            [],
            true
          ]
        },
        {
          "file": "/var/www/html/lib/private/Share20/ShareHelper.php",
          "line": 51,
          "function": "getAccessList",
          "class": "OC\\Share20\\Manager",
          "type": "->",
          "args": [
            [
              "OC\\Files\\Node\\Folder"
            ],
            true,
            true
          ]
        },
        {
          "file": "/var/www/html/apps/activity/lib/FilesHooks.php",
          "line": 598,
          "function": "getPathsForAccessList",
          "class": "OC\\Share20\\ShareHelper",
          "type": "->",
          "args": [
            [
              "OC\\Files\\Node\\Folder"
            ]
          ]
        },
        {
          "file": "/var/www/html/apps/activity/lib/FilesHooks.php",
          "line": 295,
          "function": "getUserPathsFromPath",
          "class": "OCA\\Activity\\FilesHooks",
          "type": "->",
          "args": [
            "/",
            "aa262220-78ae-1039-8531-ed3c63ef8117"
          ]
        },
        {
          "file": "/var/www/html/apps/activity/lib/FilesHooksStatic.php",
          "line": 67,
          "function": "fileMove",
          "class": "OCA\\Activity\\FilesHooks",
          "type": "->",
          "args": [
            "/DMP",
            "/DISP/DMP"
          ]
        },
        {
          "file": "/var/www/html/lib/private/legacy/OC_Hook.php",
          "line": 105,
          "function": "fileMove",
          "class": "OCA\\Activity\\FilesHooksStatic",
          "type": "::",
          "args": [
            [
              "/DMP",
              "/DISP/DMP",
              true
            ]
          ]
        },
        {
          "file": "/var/www/html/lib/private/Files/View.php",
          "line": 770,
          "function": "emit",
          "class": "OC_Hook",
          "type": "::",
          "args": [
            "OC_Filesystem",
            "rename",
            [
              "/DMP",
              "/DISP/DMP",
              true
            ]
          ]
        },
        {
          "file": "/var/www/html/apps/dav/lib/Connector/Sabre/Directory.php",
          "line": 454,
          "function": "rename",
          "class": "OC\\Files\\View",
          "type": "->",
          "args": [
            "/DMP",
            "/DISP/DMP"
          ]
        },
        {
          "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Tree.php",
          "line": 178,
          "function": "moveInto",
          "class": "OCA\\DAV\\Connector\\Sabre\\Directory",
          "type": "->",
          "args": [
            "DMP",
            "files/aa262220-78ae-1039-8531-ed3c63ef8117/DMP",
            [
              "OCA\\DAV\\Connector\\Sabre\\Directory"
            ]
          ]
        },
        {
          "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
          "line": 612,
          "function": "move",
          "class": "Sabre\\DAV\\Tree",
          "type": "->",
          "args": [
            "files/aa262220-78ae-1039-8531-ed3c63ef8117/DMP",
            "files/aa262220-78ae-1039-8531-ed3c63ef8117/DISP/DMP"
          ]
        },
        {
          "file": "/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
          "line": 89,
          "function": "httpMove",
          "class": "Sabre\\DAV\\CorePlugin",
          "type": "->",
          "args": [
            [
              "Sabre\\HTTP\\Request"
            ],
            [
              "Sabre\\HTTP\\Response"
            ]
          ]
        },
        {
          "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php",
          "line": 472,
          "function": "emit",
          "class": "Sabre\\DAV\\Server",
          "type": "->",
          "args": [
            "method:MOVE",
            [
              [
                "Sabre\\HTTP\\Request"
              ],
              [
                "Sabre\\HTTP\\Response"
              ]
            ]
          ]
        },
        {
          "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php",
          "line": 253,
          "function": "invokeMethod",
          "class": "Sabre\\DAV\\Server",
          "type": "->",
          "args": [
            [
              "Sabre\\HTTP\\Request"
            ],
            [
              "Sabre\\HTTP\\Response"
            ]
          ]
        },
        {
          "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php",
          "line": 321,
          "function": "start",
          "class": "Sabre\\DAV\\Server",
          "type": "->",
          "args": []
        },
        {
          "file": "/var/www/html/apps/dav/lib/Server.php",
          "line": 379,
          "function": "exec",
          "class": "Sabre\\DAV\\Server",
          "type": "->",
          "args": []
        },
        {
          "file": "/var/www/html/apps/dav/appinfo/v2/remote.php",
          "line": 35,
          "function": "exec",
          "class": "OCA\\DAV\\Server",
          "type": "->",
          "args": []
        },
        {
          "file": "/var/www/html/remote.php",
          "line": 172,
          "args": [
            "/var/www/html/apps/dav/appinfo/v2/remote.php"
          ],
          "function": "require_once"
        }
      ],
      "File": "/var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Exception.php",
      "Line": 28,
      "Previous": {
        "Exception": "PDOException",
        "Message": "SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near \")\"\nLINE 1: ...level\" = $1) WHERE (\"sh\".\"share_type\" = $2) AND (()) AND (\"s...\n                                                             ^",
        "Code": "42601",
        "Trace": [
          {
            "file": "/var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php",
            "line": 130,
            "function": "execute",
            "class": "PDOStatement",
            "type": "->",
            "args": [
              null
            ]
          },
          {
            "file": "/var/www/html/3rdparty/doctrine/dbal/src/Connection.php",
            "line": 1099,
            "function": "execute",
            "class": "Doctrine\\DBAL\\Driver\\PDO\\Statement",
            "type": "->",
            "args": []
          },
          {
            "file": "/var/www/html/lib/private/DB/Connection.php",
            "line": 328,
            "function": "executeQuery",
            "class": "Doctrine\\DBAL\\Connection",
            "type": "->",
            "args": [
              "SELECT \"sh\".\"id\", \"sh\".\"share_type\", \"sh\".\"share_with\", \"sh\".\"uid_owner\", \"sh\".\"uid_initiator\", \"sh\".\"parent\", \"sh\".\"item_type\", \"sh\".\"item_source\", \"sh\".\"item_target\", \"sh\".\"file_source\", \"sh\".\"file_target\", \"sh\".\"permissions\", \"sh\".\"attributes\", \"sh\".\"stime\", \"sh\".\"accepted\", \"sh\".\"expiration\", \"sh\".\"token\", \"sh\".\"mail_send\", \"sh_cc\".\"unique_id\" AS \"sh_cc_unique_id\", \"sh_cc\".\"name\" AS \"sh_cc_name\", \"sh_cc\".\"display_name\" AS \"sh_cc_display_name\", \"sh_cc\".\"sanitized_name\" AS \"sh_cc_sanitized_name\", \"sh_cc\".\"source\" AS \"sh_cc_source\", \"sh_cc\".\"description\" AS \"sh_cc_description\", \"sh_cc\".\"settings\" AS \"sh_cc_settings\", \"sh_cc\".\"config\" AS \"sh_cc_config\", \"sh_cc\".\"contact_addressbook\" AS \"sh_cc_contact_addressbook\", \"sh_cc\".\"contact_groupname\" AS \"sh_cc_contact_groupname\", \"sh_cc\".\"creation\" AS \"sh_cc_creation\", \"sh_cc_wn\".\"circle_id\" AS \"sh_cc_wn_circle_id\", \"sh_cc_wn\".\"member_id\" AS \"sh_cc_wn_member_id\", \"sh_cc_wn\".\"single_id\" AS \"sh_cc_wn_single_id\", \"sh_cc_wn\".\"user_id\" AS \"sh_cc_wn_user_id\", \"sh_cc_wn\".\"instance\" AS \"sh_cc_wn_instance\", \"sh_cc_wn\".\"user_type\" AS \"sh_cc_wn_user_type\", \"sh_cc_wn\".\"level\" AS \"sh_cc_wn_level\", \"sh_cc_wn\".\"status\" AS \"sh_cc_wn_status\", \"sh_cc_wn\".\"note\" AS \"sh_cc_wn_note\", \"sh_cc_wn\".\"contact_id\" AS \"sh_cc_wn_contact_id\", \"sh_cc_wn\".\"cached_name\" AS \"sh_cc_wn_cached_name\", \"sh_cc_wn\".\"cached_update\" AS \"sh_cc_wn_cached_update\", \"sh_cc_wn\".\"contact_meta\" AS \"sh_cc_wn_contact_meta\", \"sh_cc_wn\".\"joined\" AS \"sh_cc_wn_joined\" FROM \"oc_share\" \"sh\" LEFT JOIN \"oc_circles_circle\" \"sh_cc\" ON \"sh_cc\".\"unique_id\" = \"sh\".\"share_with\" LEFT JOIN \"oc_circles_member\" \"sh_cc_wn\" ON (\"sh_cc_wn\".\"circle_id\" = \"sh_cc\".\"unique_id\") AND (\"sh_cc_wn\".\"level\" = ?) WHERE (\"sh\".\"share_type\" = ?) AND (()) AND (\"sh\".\"parent\" IS NULL)",
              [
                9,
                7
              ],
              [
                1,
                1
              ],
              null
            ]
          },
          {
            "file": "/var/www/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php",
            "line": 344,
            "function": "executeQuery",
            "class": "OC\\DB\\Connection",
            "type": "->",
            "args": [
              "SELECT \"sh\".\"id\", \"sh\".\"share_type\", \"sh\".\"share_with\", \"sh\".\"uid_owner\", \"sh\".\"uid_initiator\", \"sh\".\"parent\", \"sh\".\"item_type\", \"sh\".\"item_source\", \"sh\".\"item_target\", \"sh\".\"file_source\", \"sh\".\"file_target\", \"sh\".\"permissions\", \"sh\".\"attributes\", \"sh\".\"stime\", \"sh\".\"accepted\", \"sh\".\"expiration\", \"sh\".\"token\", \"sh\".\"mail_send\", \"sh_cc\".\"unique_id\" AS \"sh_cc_unique_id\", \"sh_cc\".\"name\" AS \"sh_cc_name\", \"sh_cc\".\"display_name\" AS \"sh_cc_display_name\", \"sh_cc\".\"sanitized_name\" AS \"sh_cc_sanitized_name\", \"sh_cc\".\"source\" AS \"sh_cc_source\", \"sh_cc\".\"description\" AS \"sh_cc_description\", \"sh_cc\".\"settings\" AS \"sh_cc_settings\", \"sh_cc\".\"config\" AS \"sh_cc_config\", \"sh_cc\".\"contact_addressbook\" AS \"sh_cc_contact_addressbook\", \"sh_cc\".\"contact_groupname\" AS \"sh_cc_contact_groupname\", \"sh_cc\".\"creation\" AS \"sh_cc_creation\", \"sh_cc_wn\".\"circle_id\" AS \"sh_cc_wn_circle_id\", \"sh_cc_wn\".\"member_id\" AS \"sh_cc_wn_member_id\", \"sh_cc_wn\".\"single_id\" AS \"sh_cc_wn_single_id\", \"sh_cc_wn\".\"user_id\" AS \"sh_cc_wn_user_id\", \"sh_cc_wn\".\"instance\" AS \"sh_cc_wn_instance\", \"sh_cc_wn\".\"user_type\" AS \"sh_cc_wn_user_type\", \"sh_cc_wn\".\"level\" AS \"sh_cc_wn_level\", \"sh_cc_wn\".\"status\" AS \"sh_cc_wn_status\", \"sh_cc_wn\".\"note\" AS \"sh_cc_wn_note\", \"sh_cc_wn\".\"contact_id\" AS \"sh_cc_wn_contact_id\", \"sh_cc_wn\".\"cached_name\" AS \"sh_cc_wn_cached_name\", \"sh_cc_wn\".\"cached_update\" AS \"sh_cc_wn_cached_update\", \"sh_cc_wn\".\"contact_meta\" AS \"sh_cc_wn_contact_meta\", \"sh_cc_wn\".\"joined\" AS \"sh_cc_wn_joined\" FROM \"oc_share\" \"sh\" LEFT JOIN \"oc_circles_circle\" \"sh_cc\" ON \"sh_cc\".\"unique_id\" = \"sh\".\"share_with\" LEFT JOIN \"oc_circles_member\" \"sh_cc_wn\" ON (\"sh_cc_wn\".\"circle_id\" = \"sh_cc\".\"unique_id\") AND (\"sh_cc_wn\".\"level\" = :dcValue2) WHERE (\"sh\".\"share_type\" = :dcValue1) AND (()) AND (\"sh\".\"parent\" IS NULL)",
              [
                7,
                9
              ],
              [
                1,
                1
              ],
              null
            ]
          },
          {
            "file": "/var/www/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php",
            "line": 384,
            "function": "executeQuery",
            "class": "Doctrine\\DBAL\\Query\\QueryBuilder",
            "type": "->",
            "args": []
          },
          {
            "file": "/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php",
            "line": 280,
            "function": "execute",
            "class": "Doctrine\\DBAL\\Query\\QueryBuilder",
            "type": "->",
            "args": []
          },
          {
            "file": "/var/www/html/apps/circles/lib/Tools/Db/ExtendedQueryBuilder.php",
            "line": 1046,
            "function": "execute",
            "class": "OC\\DB\\QueryBuilder\\QueryBuilder",
            "type": "->",
            "args": []
          },
          {
            "file": "/var/www/html/apps/circles/lib/Tools/Db/ExtendedQueryBuilder.php",
            "line": 942,
            "function": "getRows",
            "class": "OCA\\Circles\\Tools\\Db\\ExtendedQueryBuilder",
            "type": "->",
            "args": [
              [
                [
                  "OCA\\Circles\\Db\\CoreQueryBuilder"
                ],
                "parseSimpleSelectSql"
              ],
              "OCA\\Circles\\Model\\ShareWrapper",
              []
            ]
          },
          {
            "file": "/var/www/html/apps/circles/lib/Db/ShareWrapperRequestBuilder.php",
            "line": 120,
            "function": "asItems",
            "class": "OCA\\Circles\\Tools\\Db\\ExtendedQueryBuilder",
            "type": "->",
            "args": [
              "OCA\\Circles\\Model\\ShareWrapper"
            ]
          },
          {
            "file": "/var/www/html/apps/circles/lib/Db/ShareWrapperRequest.php",
            "line": 294,
            "function": "getItemsFromRequest",
            "class": "OCA\\Circles\\Db\\ShareWrapperRequestBuilder",
            "type": "->",
            "args": [
              [
                "OCA\\Circles\\Db\\CoreQueryBuilder"
              ]
            ]
          },
          {
            "file": "/var/www/html/apps/circles/lib/Service/ShareWrapperService.php",
            "line": 204,
            "function": "getSharesByFileIds",
            "class": "OCA\\Circles\\Db\\ShareWrapperRequest",
            "type": "->",
            "args": [
              [],
              true
            ]
          },
          {
            "file": "/var/www/html/apps/circles/lib/ShareByCircleProvider.php",
            "line": 664,
            "function": "getSharesByFileIds",
            "class": "OCA\\Circles\\Service\\ShareWrapperService",
            "type": "->",
            "args": [
              [],
              true
            ]
          },
          {
            "file": "/var/www/html/lib/private/Share20/Manager.php",
            "line": 1691,
            "function": "getAccessList",
            "class": "OCA\\Circles\\ShareByCircleProvider",
            "type": "->",
            "args": [
              [],
              true
            ]
          },
          {
            "file": "/var/www/html/lib/private/Share20/ShareHelper.php",
            "line": 51,
            "function": "getAccessList",
            "class": "OC\\Share20\\Manager",
            "type": "->",
            "args": [
              [
                "OC\\Files\\Node\\Folder"
              ],
              true,
              true
            ]
          },
          {
            "file": "/var/www/html/apps/activity/lib/FilesHooks.php",
            "line": 598,
            "function": "getPathsForAccessList",
            "class": "OC\\Share20\\ShareHelper",
            "type": "->",
            "args": [
              [
                "OC\\Files\\Node\\Folder"
              ]
            ]
          },
          {
            "file": "/var/www/html/apps/activity/lib/FilesHooks.php",
            "line": 295,
            "function": "getUserPathsFromPath",
            "class": "OCA\\Activity\\FilesHooks",
            "type": "->",
            "args": [
              "/",
              "aa262220-78ae-1039-8531-ed3c63ef8117"
            ]
          },
          {
            "file": "/var/www/html/apps/activity/lib/FilesHooksStatic.php",
            "line": 67,
            "function": "fileMove",
            "class": "OCA\\Activity\\FilesHooks",
            "type": "->",
            "args": [
              "/DMP",
              "/DISP/DMP"
            ]
          },
          {
            "file": "/var/www/html/lib/private/legacy/OC_Hook.php",
            "line": 105,
            "function": "fileMove",
            "class": "OCA\\Activity\\FilesHooksStatic",
            "type": "::",
            "args": [
              [
                "/DMP",
                "/DISP/DMP",
                true
              ]
            ]
          },
          {
            "file": "/var/www/html/lib/private/Files/View.php",
            "line": 770,
            "function": "emit",
            "class": "OC_Hook",
            "type": "::",
            "args": [
              "OC_Filesystem",
              "rename",
              [
                "/DMP",
                "/DISP/DMP",
                true
              ]
            ]
          },
          {
            "file": "/var/www/html/apps/dav/lib/Connector/Sabre/Directory.php",
            "line": 454,
            "function": "rename",
            "class": "OC\\Files\\View",
            "type": "->",
            "args": [
              "/DMP",
              "/DISP/DMP"
            ]
          },
          {
            "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Tree.php",
            "line": 178,
            "function": "moveInto",
            "class": "OCA\\DAV\\Connector\\Sabre\\Directory",
            "type": "->",
            "args": [
              "DMP",
              "files/aa262220-78ae-1039-8531-ed3c63ef8117/DMP",
              [
                "OCA\\DAV\\Connector\\Sabre\\Directory"
              ]
            ]
          },
          {
            "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
            "line": 612,
            "function": "move",
            "class": "Sabre\\DAV\\Tree",
            "type": "->",
            "args": [
              "files/aa262220-78ae-1039-8531-ed3c63ef8117/DMP",
              "files/aa262220-78ae-1039-8531-ed3c63ef8117/DISP/DMP"
            ]
          },
          {
            "file": "/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
            "line": 89,
            "function": "httpMove",
            "class": "Sabre\\DAV\\CorePlugin",
            "type": "->",
            "args": [
              [
                "Sabre\\HTTP\\Request"
              ],
              [
                "Sabre\\HTTP\\Response"
              ]
            ]
          },
          {
            "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php",
            "line": 472,
            "function": "emit",
            "class": "Sabre\\DAV\\Server",
            "type": "->",
            "args": [
              "method:MOVE",
              [
                [
                  "Sabre\\HTTP\\Request"
                ],
                [
                  "Sabre\\HTTP\\Response"
                ]
              ]
            ]
          },
          {
            "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php",
            "line": 253,
            "function": "invokeMethod",
            "class": "Sabre\\DAV\\Server",
            "type": "->",
            "args": [
              [
                "Sabre\\HTTP\\Request"
              ],
              [
                "Sabre\\HTTP\\Response"
              ]
            ]
          },
          {
            "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php",
            "line": 321,
            "function": "start",
            "class": "Sabre\\DAV\\Server",
            "type": "->",
            "args": []
          },
          {
            "file": "/var/www/html/apps/dav/lib/Server.php",
            "line": 379,
            "function": "exec",
            "class": "Sabre\\DAV\\Server",
            "type": "->",
            "args": []
          },
          {
            "file": "/var/www/html/apps/dav/appinfo/v2/remote.php",
            "line": 35,
            "function": "exec",
            "class": "OCA\\DAV\\Server",
            "type": "->",
            "args": []
          },
          {
            "file": "/var/www/html/remote.php",
            "line": 172,
            "args": [
              "/var/www/html/apps/dav/appinfo/v2/remote.php"
            ],
            "function": "require_once"
          }
        ],
        "File": "/var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php",
        "Line": 130
      }
    },
    "CustomMessage": "Exception thrown: Doctrine\\DBAL\\Exception\\SyntaxErrorException"
  }
}```


### Additional info

_No response_

### PR DESCRIPTION
**Pull request by come-nc**
* Resolves: #46467

## Summary

Having an orphan/broken share should not prevent to move other shares.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)
- [ ] [Labels added](https://github.com/nextcloud/server/labels) where applicable (ex: bug/enhancement, `3. to review`, feature component)
- [ ] [Milestone added](https://github.com/nextcloud/server/milestones) for target branch/version (ex: 32.x for `stable32`)

### CODE REVIEW

File: lib/private/Files/View.php [hunk 1]
```diff
@@ -1883,7 +1883,12 @@ private function targetIsNotShared(string $user, string $targetPath): bool {
 		}, $providers));
 
 		foreach ($shares as $share) {
-			$sharedPath = $share->getNode()->getPath();
+			try {
+				$sharedPath = $share->getNode()->getPath();
+			} catch (NotFoundException) {
```
Comment (provokateurin) [inline lib/private/Files/View.php]: This should probably be logged

Comment (come-nc) [reply lib/private/Files/View.php]: I’m not convinced. It should be logged in other places already, this function is only checking whether the new target path is part of a share, it’s not its job to check other shares validity.

It’s also not clear to me whether it’s a valid usecase to have shares where the node is gone. It happens when a node is moved to trash, and it may be useful to keep it in case the node is restored later. It also happens when a user is removed from a group giving access to a team folder, and there also, not clear if adding back the user should restore the share.

I can log the exception to debug eventually?

Comment (provokateurin) [reply lib/private/Files/View.php]: I see your points, let's go with debug then.

**Review by provokateurin — APPROVED** [review]

**Review by Altahrim — APPROVED** [review]
