### PR TITLE
Fix nextcloud logo in email notifications misalignment 

### LINKED ISSUE #23357: nextcloud logo in email notifications is misaligned in version 20.0.0
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system:**

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

### LINKED ISSUE #23977: Share by mail template design issue (logo not centered on the circle)
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Connect to NextCloud server with following actived plugins : "Share by mail" & "File sharing"
2. Select a folder or file, and share by mail
3. Connect to your mail box and look for the mail received

### Expected behaviour
Looking to the email, the logo should be centered in the circle in the header of the email

### Actual behaviour
Currently, the logo is aligned on the top of the circle in the header of the email

Github - Bug 01

### Server configuration

**Operating system:**
Debian 10

**Web server:**
Apache 2.4

**Database:**
PG10

**PHP version:**
PHP 7.3

**Nextcloud version:** (see Nextcloud admin page)
NextCloud v 20.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
NextCloud v 17.0.9

Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed, paste the results here.
No errors have been found.

List of activated apps:
Accessibility 1.6.0
Activity 2.13.2
Calendar 2.1.2
Comments 1.10.0
Contacts 3.4.1
Contacts Interaction 1.1.0
Custom CSS 1.7.0
Dashboard 7.0.0
Data Request 1.7.0
Deleted files 1.10.1
DICOM Viewer 1.2.2
External sites 3.7.1
File sharing 1.12.0
Group folders 8.1.0
Log Reader 2.5.0
Notifications 2.8.0
Password policy 1.10.1
PDF viewer 2.0.1
Photos 1.2.0
Recommendations 0.8.0
Right click 0.17.0
Share by mail 1.10.0
Support 1.3.0
Text 3.1.0
Theming 1.11.0
Update notification 1.10.0
Usage survey 1.8.0
User status 1.0.0
Versions 1.13.0
Video player 1.9.0
Weather status 1.0.0

**Are you using external storage, if yes which one: no

**Are you using encryption: no

**Are you using an external user-backend, if yes which one: no

### Client configuration
Version 86.0.4240.111 (Build officiel) (64 bits)

**Operating system:**
Windows 10 Version 10.0.19041 Numéro 19041

### PR DESCRIPTION
**Pull request by medcloud**
Signed-off-by: medcloud <42641918+medcloud@users.noreply.github.com>

Fixes the good positionning of theming logo in the circle when sending emails (like share by email or by link) : the logo was on the top of the circle, and circle sometimes on the left aligned in iOS Gmail for instance.

The modification proposed is mainly focused on a square logo which would be correctly centered. However, for a logo like Nextcloud one (252x120px) the display is a bit different but acceptable. 

Fix #23357
Fix #23977

### CODE REVIEW

**Comment by medcloud** [comment]
For review please : @skjnldsv and @ChristophWurst 
Thanks

File: lib/private/Mail/EMailTemplate.php [hunk 1]
```diff
@@ -672,4 +672,4 @@ public function renderText(): string {
 		}
 		return $this->plainBody;
 	}
-}
+}
```
Comment (skjnldsv) [inline lib/private/Mail/EMailTemplate.php:675]: It seems that this changed and made our php lint test unhappy :)
Can you fix it?
It's missing a new line at the end and/or the bracket seems off?

Comment (medcloud) [reply lib/private/Mail/EMailTemplate.php:675]: Yes, strange > because I didn't changed that part. I will correct and I guess I must comit again ?

Comment (skjnldsv) [reply lib/private/Mail/EMailTemplate.php:675]: Ideally please amend your previous commit :)
That way we still have one commit, not two

**Review by skjnldsv — APPROVED** [review]
Other than the other code syntax fix, :+1:

File: lib/private/Mail/EMailTemplate.php (hunk 1 above)
Comment (medcloud) [reply lib/private/Mail/EMailTemplate.php]: sorry @skjnldsv  : There was still dfferences on lines that I had not changed > the last committed a few minutes ago has the right content. Sorry for these multiple commits > last one should be OK (checks on going).

Would you know how to amend previous commits in order to keep only 1 instead of 3 ?

Comment (skjnldsv) [reply lib/private/Mail/EMailTemplate.php]: yes, you can do the following:
`git rebase --autosquash -i HEAD~3`

Then you replace the `pick` of the last two commits by `f` to fixup.
They will be merged into the first commit

Capture d’écran_2020-11-14_19-06-34

Comment (skjnldsv) [reply lib/private/Mail/EMailTemplate.php]: Then you need to force push to this branch and you're good! :+1:

Comment (medcloud) [reply lib/private/Mail/EMailTemplate.php]: OK ! I will try and keep you posted. Thanks for your help

Comment (medcloud) [reply lib/private/Mail/EMailTemplate.php]: Done ! 1 single commit.

Last time, "continuous-integration/drone/pr had failed, would you know if there is something to do for that ?

Comment (skjnldsv) [reply lib/private/Mail/EMailTemplate.php]: > Last time, "continuous-integration/drone/pr had failed, would you know if there is something to do for that ?

Ah right, you need to fix the tests on `tests/lib/Mail/EMailTemplateTest.php`
https://drone.nextcloud.com/nextcloud/server/35550/10/4

**Comment by skjnldsv** [comment]
> Last time, "continuous-integration/drone/pr had failed, would you know if there is something to do for that ?

Ah right, you need to fix the tests on `tests/lib/Mail/EMailTemplateTest.php`
https://drone.nextcloud.com/nextcloud/server/35550/10/4

**Comment by medcloud** [comment]
> > Last time, "continuous-integration/drone/pr had failed, would you know if there is something to do for that ?
> 
> Ah right, you need to fix the tests on `tests/lib/Mail/EMailTemplateTest.php`
> https://drone.nextcloud.com/nextcloud/server/35550/10/4

The tests have been fixed but the build is still failing, but it seems unrelated.
There is now 1 failure in the mariadb10.4-php7.4 test that says:

1) Test\Share20\DefaultShareProviderTest::testGetSharedWithGroup with data set #0 ('home::shareOwner', 'files/test.txt', 'files/test2.txt')
Failed asserting that '47' matches expected 0.

/drone/src/tests/lib/Share20/DefaultShareProviderTest.php:1030

Could somebody with more experience have a look ?

**Comment by skjnldsv** [comment]
> 1. Test\Share20\DefaultShareProviderTest::testGetSharedWithGroup with data set #0 ('home::shareOwner', 'files/test.txt', 'files/test2.txt')
>    Failed asserting that '47' matches expected 0.

This seems unrelated. Ignore that

**Review by skjnldsv — APPROVED** [review]

**Review by rullzer — APPROVED** [review]
