### PR TITLE
set mimetype for objects uploaded to object storages

### LINKED ISSUE #19487: Files uploaded to S3 external storage given 'Content-type: application/octet-stream', always
### Steps to reproduce
1. Create an S3-backed external storage mount
2. Copy an existing file into the newly created mount

### Expected behaviour
Uploaded file is given a relevant content-type, based on extension or MIME

### Actual behaviour
File is given `application/octet-stream`

image

(The same file uploaded through the S3 web UI is given `image/png` correctly.

### Server configuration

**Operating system:** Ubuntu 18.04

**Web server:** NGINX

**Database:** MariaDB

**PHP version:** 7.3, I think

**Nextcloud version:** (see Nextcloud admin page) 18.0.1 (issue also present on 18.0.0)

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 18.0.0

**Where did you install Nextcloud from:** https://hub.docker.com/r/linuxserver/nextcloud

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_external: 1.9.0
  - files_markdown: 2.2.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_texteditor: 2.10.0
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.11.3
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.2
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - encryption
  - text
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
           **********
        ],
        "dbtype": "mysql",
        "version": "18.0.1.3",
        "overwrite.cli.url": "********",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/... S3

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox

**Operating system:** Arch Linux

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes #19487

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
Code looks fine :+1:

Assuming you retested all those storages already.
Will the trait method interface change affect/break existing third party implementation ?

File: lib/private/Files/ObjectStore/S3ObjectTrait.php [hunk 1]
```diff
@@ -91,6 +92,9 @@ public function writeObject($urn, $stream) {
 			'bucket' => $this->bucket,
 			'key' => $urn,
 			'part_size' => $this->uploadPartSize,
+			'params' => [
```
Comment (scriptsagency) [inline lib/private/Files/ObjectStore/S3ObjectTrait.php:95]: For the MultipartUploader this approach won't work. At least tested in NC18 will not setup the content type in S3 bucket. 
A different approach that seemed successful for some still won't work: 
'before_initiate' => function (\Aws\Command $command) use ($mimetype) {
				$command['ContentType'] = $mimetype;
}

Furthermore in the catch clause an empty file is uploaded. The content type needs to be added for that one too. In there it will work by adding 
$uploader = new ObjectUploader($this->getConnection(), $this->bucket, $urn, '', 'private', ['params' => ['ContentType' => $mimetype]]);

**Comment by icewind1991** [comment]
> Will the trait method interface change affect/break existing third party implementation ?

Object storages can't be implemented by apps at the moment

**Review by rullzer — APPROVED** [review]

**Comment by kesselb** [comment]
image

Tested with minio. Content-Type is now set :+1:

**Review by kesselb — APPROVED** [review]
