### PR TITLE
remove LogicException, because it's also triggered with legitimate parameters

### LINKED ISSUE #10727: [NC 14] Cannot sync calendars since updating to RC3
First, sorry for xposting this from [the forums](https://help.nextcloud.com/t/nc-14-cannot-sync-calendars-since-updating-to-rc3/35201).  I'm not sure where I should upload support requests. Please close this issue report if I violate some policy. 

The Issue: 
Since NC 14rc3 I no longer can sync calendar events to Davdroid or any other caldav client (tried with Thunderbird/Lightning on desktop as well). I updated today to 14rc4 but it didn't resolve the issue. 

Expected behavior:
I should be able to sync calendars with mobile and desktop calendars. 

==========================
Specs: 
Nextcloud 14rc4 (original upgrade from 13 through updater)

Ubuntu 16.04 

Apache
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2018-06-07T19:43:03

===============
PHP
PHP 7.0.30-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.30-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

=====
Database
mysql  Ver 15.1 Distrib 10.0.34-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

In my logs, I see this whenever I try to connect: 

LogicException: This is not supposed to happen

    /var/www/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php - line 345:

    OCA\DAV\CalDAV\Plugin->getCalendarHomeForPrincipal("principals/groups/admin")

    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/PropFind.php - line 98:

    Sabre\CalDAV\Plugin->Sabre\CalDAV\{closure}("*** sensiti ... *")

    /var/www/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php - line 349:

    Sabre\DAV\PropFind->handle("{urn:ietf:p ... t", Closure {})

    Sabre\CalDAV\Plugin->propFind(Sabre\DAV\PropFind {}, OCA\DAV\CalD ... {})

    /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:

    call_user_func_array([ OCA\DAV\Ca ... "], [ Sabre\DAV\ ... }])

    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1059:

    Sabre\Event\EventEmitter->emit("propFind", [ Sabre\DAV\ ... }])

    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 981:

    Sabre\DAV\Server->getPropertiesByNode(Sabre\DAV\PropFind {}, OCA\DAV\CalD ... {})

    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1666:

    Sabre\DAV\Server->getPropertiesIteratorForPath("principals/groups/admin", [ "{urn:ietf ... "], 0)

    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 359:

    Sabre\DAV\Server->generateMultiStatus(Generator {}, false)

    Sabre\DAV\CorePlugin->httpPropFind(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})

    /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:

    call_user_func_array([ Sabre\DAV\ ... "], [ Sabre\HTTP ... }])

    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479:

    Sabre\Event\EventEmitter->emit("method:PROPFIND", [ Sabre\HTTP ... }])

    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:

    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})

    /var/www/nextcloud/apps/dav/lib/Server.php - line 293:

    Sabre\DAV\Server->exec()

    /var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:

    OCA\DAV\Server->exec()

    /var/www/nextcloud/remote.php - line 163:

    require_once("/var/www/ne ... p")

========================

Does anyone have any idea how to fix this? I was stupid enough to accidentally switch to the beta channel in the updater which is why I upgraded. The server is my production environment :/

### PR DESCRIPTION
**Pull request by georgehrke**
fixes #10727 

Removes the LogicException, that was introduced by https://github.com/nextcloud/server/commit/2da510af0b537e3bef7d0563eff828bade51fcbd?diff=split#diff-1aec04ba25037067a4d2c1fc323ed253

removed in `getCalendarHomeForPrincipal`, because it doesn't provide calendar-homes for:
- `principals/groups/...`
- `principals/system/...`

removed in `getAddressbookHomeForPrincipal`, because it doesn't provide addressBook-homes for:
- `principals/calendar-resources/...`
- `principals/calendar-rooms/...`

### CODE REVIEW

**Comment by nickvergessen** [comment]
Maybe we adjust the message and catch the exception outside instead? Makes more sense to me then having 2 return types again :(

**Comment by georgehrke** [comment]
> Maybe we adjust the message and catch the exception outside instead? Makes more sense to me then having 2 return types again :(

Ideally we would just have `string?`, but that's PHP 7.1.

> So it just returns void if it can't find it?

Sabre/DAV expects so:
https://github.com/nextcloud/3rdparty/blob/b995ca8b8c7f69a180ad6fb49989ad3e35b1367e/sabre/dav/lib/CalDAV/Schedule/Plugin.php#L214

File: apps/dav/lib/CardDAV/Plugin.php [hunk 1]
```diff
@@ -42,7 +42,6 @@ function initialize(Server $server) {
 	 * @return string
```
Comment (nickvergessen) [inline apps/dav/lib/CardDAV/Plugin.php]: also null now

File: apps/dav/lib/CalDAV/Plugin.php [hunk 2]
```diff
@@ -30,8 +30,7 @@ class Plugin extends \Sabre\CalDAV\Plugin {
 	/**
 	 * @inheritdoc
```
Comment (nickvergessen) [inline apps/dav/lib/CalDAV/Plugin.php]: also returns null, (although the parent does not)

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
Tested and fixes davdroid

**Review by ChristophWurst — APPROVED** [review]
Changes look good, are covered by tests and users have [reported](https://github.com/nextcloud/server/issues/10727#issuecomment-418750844) that this fixes their issue, so :+1:
