### PR TITLE
Unified search improvements

### LINKED ISSUE #41381: Global search beta follow up
Follow up issues from https://github.com/nextcloud/server/pull/40823

### TODO

**High priority:**
- [x] Typing in the user search filter doesn't show all the users, it seems that it shows only the preloaded ones
- [x] When filtering the local view (e.g. users) it's impossible to reset the view. When reopening the search modal, it should be possible to reset the search.
- [x] Search result links that should be improved to be actual links for a11y reasons

**Other:** 
- [x] Icon inversion which does not work well now since icons come in white or black instead of one consistent color. (Black icons turn white and white icons turn black, leading to to white on white background issues)
- [x] Use the new people filter (selector) that @marcoambrosini is working on (Current people filter not completed) - DONE, however, NcPopover which is used has issues with closing triggers.
- [x] Update back-end API (if ability not already present) to show "Search in App" dynamically.
- [x] Remove person filter
- [x] BUG: Clicking outside the search modal needs two clicks on the magnifier icon to get the modal back.
- [x] BUG: Some app icons are white on white.
- [x] BUG: Modified timestamp bubbles change size on hover, have no pointing cursor.
- [x] BUG: Generally no feedback for no results.
- [x] BUG: Search people has white text on white background.
- [x] BUG: Search people has a tiny user bubble, barely wider than the avatar.
- [x] BUG: Search people No result goes to the top, overlaps other input.
- [x] BUG: Search people has no effect at all. The search string doesn't contain a person identifier.
- [x] Avatars are square. I guess that's because all previews are square so this makes sense *technically*. For a user, this is inconsistent with *avatars*, though
    image
- [x] When previews do not exist (endpoint returns 404) the browser renders a placeholder for the broken image
    Bildschirmfoto vom 2023-11-14 14-23-13
- [x] *x* on apps/person selection changes size on hover
- [x] No space for icons in modified (Fenn-CS : Best handled at component level, migrate to vue lib repo? "Do not reserve space for icon in NcActionButton if no icon is provided"???)
- [x] *x* on apps/person selection should have pointing cursor

image
- [ ] People are not sorted, at least not by name
    image

- [ ] Accidentally clicked the magnifier on mobile and found out it's impossible to close the modal
image

Needs full page reload to get back to the content.

### LINKED ISSUE #41939: Can not search for "own" search results
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps

* Write chat messages (or any thing else that has a search provider supporting the person/people filter)
* Try to search for things from yourself

### Expected

✅ 

### Actual

grafik

### Problem

The global search uses the `/index.php/contactsmenu/contacts` endpoint.

This is problematic in multiple ways:
1. Own user is not returned
2. Endpoint can not be used by desktop/mobile clients (needs OCS)

### Potential quick workarounds

Hard code the own user into the options because we can generate all the details from existing JS data.

### PR DESCRIPTION
**Pull request by nfebe**
Resolves : https://github.com/nextcloud/server/issues/41381, https://github.com/nextcloud/server/issues/41939

### CODE REVIEW

**Comment by Fenn-CS** [comment]
Users can now see themselves in the people filter as "Me" once, they start searching the filtering would exclude the authenticated user from the results.

Screenshot from 2023-12-12 19-45-15

**Comment by susnux** [comment]
@Fenn-CS conflicts

**Comment by Fenn-CS** [comment]
@susnux That was the result of compiling and merge : https://github.com/nextcloud/server/pull/42094, now fixed!

**Review by susnux — APPROVED** [review]

**Review by sorbaugh — APPROVED** [review]

File: core/src/services/UnifiedSearchService.js [hunk 1]
```diff
@@ -103,5 +104,20 @@ export async function getContacts({ searchTerm }) {
...
 	})
+	/*
+	 * Add authenticated user to list of contacts for search filter
+	 * If authtenicated user is searching/filtering, do not add them to the list
+	 */
+	if (!searchTerm) {
+		let authenticatedUser = getCurrentUser()
+		authenticatedUser = {
+			id: authenticatedUser.uid,
+			fullName: 'Me',
```
Comment (nickvergessen) [inline core/src/services/UnifiedSearchService.js:115]: Should use the displayname (like e.g. github does):
```
fullName: authenticatedUser.displayName,
```

Otherwise we need to translate it.

Comment (Fenn-CS) [reply core/src/services/UnifiedSearchService.js:115]: Thanks for catching that @nickvergessen here : https://github.com/nextcloud/server/pull/42205
