### PR TITLE
fix(files_versions): ensure users IDs are strings

### LINKED ISSUE #54727: Failures if `$uid` is an integer
Exemple (here `$uid` is 6151):

```
{
  "reqId": "qvDiiMQ3rImSaIOahPem",
  "level": 3,
  "app": "index",
  "method": "POST",
  "url": "/displaynames",
  "message": "strpos(): Argument nextcloud/guests#1 ($haystack) must be of type string, int given in file '/var/www/nextcloud/apps/guests/lib/UserBackend.php' line 299",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36",
  "version": "30.0.14.1",
  "exception": {
    "Exception": "Exception",
    "Message": "strpos(): Argument nextcloud/guests#1 ($haystack) must be of type string, int given in file '/var/www/nextcloud/apps/guests/lib/UserBackend.php' line 299",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/App.php",
        "line": 161,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OC\\Core\\Controller\\UserController"
          },
          "getDisplayNames"
        ]
      },
      {
        "file": "/var/www/nextcloud/lib/private/Route/Router.php",
        "line": 303,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::",
        "args": [
          "OC\\Core\\Controller\\UserController",
          "getDisplayNames",
          {
            "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
          },
          {
            "_route": "core.user.getdisplaynames"
          }
        ]
      },
      {
        "file": "/var/www/nextcloud/lib/base.php",
        "line": 1031,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->",
        "args": [
          "/displaynames"
        ]
      },
      {
        "file": "/var/www/nextcloud/index.php",
        "line": 24,
        "function": "handleRequest",
        "class": "OC",
        "type": "::",
        "args": []
      }
    ],
    "File": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
    "Line": 146,
    "Previous": {
      "Exception": "TypeError",
      "Message": "strpos(): Argument nextcloud/guests#1 ($haystack) must be of type string, int given",
      "Code": 0,
      "Trace": [
        {
          "file": "/var/www/nextcloud/apps/guests/lib/UserBackend.php",
          "line": 299,
          "function": "strpos",
          "args": [
            6151,
            "@"
          ]
        },
        {
          "file": "/var/www/nextcloud/apps/guests/lib/UserBackend.php",
          "line": 356,
          "function": "loadUser",
          "class": "OCA\\Guests\\UserBackend",
          "type": "->",
          "args": [
            6151
          ]
        },
        {
          "file": "/var/www/nextcloud/apps/user_saml/lib/UserBackend.php",
          "line": 421,
          "function": "userExists",
          "class": "OCA\\Guests\\UserBackend",
          "type": "->",
          "args": [
            6151
          ]
        },
        {
          "file": "/var/www/nextcloud/apps/user_saml/lib/UserBackend.php",
          "line": 188,
          "function": "getActualUserBackend",
          "class": "OCA\\User_SAML\\UserBackend",
          "type": "->",
          "args": [
            6151
          ]
        },
        {
          "file": "/var/www/nextcloud/lib/private/User/Manager.php",
          "line": 136,
          "function": "userExists",
          "class": "OCA\\User_SAML\\UserBackend",
          "type": "->",
          "args": [
            6151
          ]
        },
        {
          "file": "/var/www/nextcloud/core/Controller/UserController.php",
          "line": 39,
          "function": "get",
          "class": "OC\\User\\Manager",
          "type": "->",
          "args": [
            6151
          ]
        },
        {
          "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
          "line": 208,
          "function": "getDisplayNames",
          "class": "OC\\Core\\Controller\\UserController",
          "type": "->",
          "args": [
            [
              6151
            ]
          ]
        },
        {
          "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
          "line": 114,
          "function": "executeController",
          "class": "OC\\AppFramework\\Http\\Dispatcher",
          "type": "->",
          "args": [
            {
              "__class__": "OC\\Core\\Controller\\UserController"
            },
            "getDisplayNames"
          ]
        },
        {
          "file": "/var/www/nextcloud/lib/private/AppFramework/App.php",
          "line": 161,
          "function": "dispatch",
          "class": "OC\\AppFramework\\Http\\Dispatcher",
          "type": "->",
          "args": [
            {
              "__class__": "OC\\Core\\Controller\\UserController"
            },
            "getDisplayNames"
          ]
        },
        {
          "file": "/var/www/nextcloud/lib/private/Route/Router.php",
          "line": 303,
          "function": "main",
          "class": "OC\\AppFramework\\App",
          "type": "::",
          "args": [
            "OC\\Core\\Controller\\UserController",
            "getDisplayNames",
            {
              "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
            },
            {
              "_route": "core.user.getdisplaynames"
            }
          ]
        },
        {
          "file": "/var/www/nextcloud/lib/base.php",
          "line": 1031,
          "function": "match",
          "class": "OC\\Route\\Router",
          "type": "->",
          "args": [
            "/displaynames"
          ]
        },
        {
          "file": "/var/www/nextcloud/index.php",
          "line": 24,
          "function": "handleRequest",
          "class": "OC",
          "type": "::",
          "args": []
        }
      ],
      "File": "/var/www/nextcloud/apps/guests/lib/UserBackend.php",
      "Line": 299
    },
    "message": "strpos(): Argument nextcloud/guests#1 ($haystack) must be of type string, int given in file '/var/www/nextcloud/apps/guests/lib/UserBackend.php' line 299",
    "exception": [],
    "CustomMessage": "strpos(): Argument nextcloud/guests#1 ($haystack) must be of type string, int given in file '/var/www/nextcloud/apps/guests/lib/UserBackend.php' line 299"
  },
  "id": "68b15914bd9ff"
}
```

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/server/issues/54727

User IDs can be parsed as integers if the userid doesn't have an alphanumeric char in it.
It makes the `/displayname` api throw.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
LGTM but didnt test

**Review by provokateurin — APPROVED** [review]

**Comment by solracsf** [comment]
Do we need to normalize to string here also or not needed?

https://github.com/nextcloud/server/blob/3944e1848baeef7004571ea1de97f9d914e167a2/apps/files_versions/src/utils/versions.ts#L109

**Comment by skjnldsv** [comment]
> Do we need to normalize to string here also or not needed?
> 
> https://github.com/nextcloud/server/blob/3944e1848baeef7004571ea1de97f9d914e167a2/apps/files_versions/src/utils/versions.ts#L109

We could also sure :)

**Review by AndyScherzinger — APPROVED** [review]

File: apps/files_versions/src/utils/versions.ts [hunk 1]
```diff
@@ -106,7 +106,7 @@ function formatVersion(version: any, fileInfo: any): Version {
 		fileId: fileInfo.id,
 		// If version-label is defined make sure it is a string (prevent issue if the label is a number an PHP returns a number then)
 		label: version.props['version-label'] && String(version.props['version-label']),
-		author: version.props['version-author'] ?? null,
+		author: String(version.props['version-author']) ?? null,
```
Comment (solracsf) [inline apps/files_versions/src/utils/versions.ts:109]: If `version.props['version-author']` is missing, you’ll end up with "null" or "undefined" as the author ID because of operator precedence, no?

`author: version.props['version-author'] != null ? String(version.props['version-author']) : null`

Maybe I'm wrong perhaps :)

Comment (skjnldsv) [reply apps/files_versions/src/utils/versions.ts:109]: https://github.com/nextcloud/server/pull/54733
