### PR TITLE
fix(ObjectStore): Make copying behavior consistent with local storage

### LINKED ISSUE #41564: [Bug]: Inconsistent copy behavior between Object storage and local storage
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

If you copy a shared file on local storage the copied file has dropped all permissions, meaning you are the owner and have all permissions.
On object storage if you copy a shared file, the permissions are preserved, meaning if you could only view a file you can also only view the copied file.

### Steps to reproduce

1. Share a file and set permissions to view only
2. As the person with who you shared the file: Copy the file
3. See that on local storage you can reshare the copied file and on object storage you can not.

### Expected behavior

Consistent behavior (one of both).

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: #41564 

## Summary
Drop file permissions on copy like we do on local storage.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by Altahrim — APPROVED** [review]

File: lib/private/Files/ObjectStore/ObjectStoreStorage.php [hunk 1]
```diff
@@ -88,6 +90,7 @@ public function __construct($params) {
 		if (isset($params['validateWrites'])) {
 			$this->validateWrites = (bool)$params['validateWrites'];
 		}
+		$this->handleCopiesAsOwned = (bool)($params['handleCopiesAsOwned'] ?? false);
```
Comment (juliushaertl) [inline lib/private/Files/ObjectStore/ObjectStoreStorage.php:93]: Do we need a parameter for that actually? If we keep it it should be documented

**Review by juliusknorr — APPROVED** [review]
Small comment, but looks good otherwise

**Review by joshtrichards — COMMENTED** [review]
From your inline comments it seems you think the local  (non-object) policy is the broken one.  I'm not sure local's behavior is incorrect (seems object is), but I appreciate the conservativeness to add a config option to avoid changing existing behavior for object (in case someone is relying on it).

But I think it should just outright be made consistent with local as-is w/o config option if at all possible. There's just no justification for having different behavior (or a switch for one but not the other/etc)

Do we have any idea when this inconsistent behavior was introduced or has it seemingly "always" been this way?

**Comment by AndyScherzinger** [comment]
> Do we have any idea when this inconsistent behavior was introduced or has it seemingly "always" been this way?

@joshtrichards Has always been like this, since native S3 copying respects the original file's permissions. One could argue that it does so for a reason because the permission had been the decision of the original owner of the file. At the same time, like you mentioned you could also argue the other way around that the copy belongs to the copying party and hence all permission-limitations are dropped.

**Comment by icewind1991** [comment]
I think the new behavior is wrong, the permissions on object storages are not related to the permissions of the objects in the objectstore, but only the permissions from things like sharing/acls.

See https://github.com/nextcloud/server/pull/53733 for making the local storage behave as the object store used to.
