### PR TITLE
Sharing link & mail parity

### LINKED ISSUE #19562: Sharebymail does not respect deafult expiration date
### Steps to reproduce
1. Set a default expiration date as admin which is not enforced
image

2. Share a file or folder to an external email address

### Expected behaviour
The share should have the "Set expiration date" activated and the date should be 30 days in the future.

### Actual behaviour
The expiration is not activated!
image

Additional info:
When I manually enable the expiration by clicking the "Set expiration date" checkbox, the preselected date is 30 days in advance. So it seems the date is correctly calculated, just the activation is missing.
When "enforced" is configured in admin, the checkbox is activated (but as users should be able to change this, that's no option)

### Server configuration

**Operating system:**
Ubuntu 18.04 LTS

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
7.2

**Nextcloud version:** (see Nextcloud admin page)
18.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 18.0

**Where did you install Nextcloud from:**
Official package

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - apporder: 0.9.0
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.1
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.1.8
  - dav: 1.14.0
  - deck: 0.8.0
  - documentserver_community: 0.1.5
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_automatedtagging: 1.8.0
  - files_downloadactivity: 1.7.0
  - files_external: 1.9.0
  - files_fulltextsearch: 1.4.1
  - files_fulltextsearch_tesseract: 1.4.0
  - files_pdfviewer: 1.7.0
  - files_retention: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - fulltextsearch: 1.4.1
  - fulltextsearch_elasticsearch: 1.5.0
  - groupfolders: 6.0.1
  - guests: 1.4.1
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.1.2
  - maps: 0.1.5
  - nextcloud_announcements: 1.7.0
  - notes: 3.1.5
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - photos: 1.0.0
  - previewgenerator: 2.2.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - quota_warning: 1.7.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.4
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.11.3
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflow_pdf_converter: 1.3.1
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - bookmarks
  - encryption
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.3.6",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR",
            "HTTP_FORWARDED_FOR"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.1.3",
        "overwrite.cli.url": "https:\/\/cloud.fep.de\/",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "mysql.utf8mb4": true,
        "enable_avatars": true,
        "default_language": "en",
        "default_locale": "de_DE",
        "skeletondirectory": "\/var\/www\/skeleton",
        "share_folder": "\/Shared",
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": "2",
        "mail_smtpmode": "smtp",
        "remember_login_cookie_lifetime": "1800",
        "log_rotate_size": "10485760",
        "trashbin_retention_obligation": "30, 60",
        "versions_retention_obligation": "auto, 365",
        "check_for_working_webdav": true,
        "simpleSignUpLink.shown": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0.5,
            "dbindex": 0
        },
        "logtimezone": "Europe\/Berlin",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\Movie",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\MKV",
            "OC\\Preview\\MOV",
            "OC\\Preview\\MP4",
            "OC\\Preview\\AVI"
        ],
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "theme": "",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

### Client configuration
**Browser:**
Firefox, Chrome, Safari

**Operating system:**
Windows, MacOS, IOS

### LINKED ISSUE #24209: Share by mail, strange text input leading to incorrect recipient mail display
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Connect to NextCloud server
2. Create a folder and share it by mail to somebody
3. Click on detailed view of the share and type into upper text input visible on the popup
4. Click on right arrow to validate the text

### Expected behaviour
I don't know, as I don't understand what is the purpose of the upper input text in the popup.
At least, I don't expect any error on display

### Actual behaviour
Currently, nothing happen on click, but the recipient email is change to something like "Share the link ({tag})" info
If you refresh webpage again, the recipient email is displayed correctly again, and if you click again on detailed view of the share, nothing is visible in the upper text input in the popup.

Picture01

Picture02

Picture03

### Server configuration

**Operating system:** Debian 10.12-2
**Web server:** Apache 2.4
**Database:** PostgreSQL 10.12
**PHP version:** PHP 7.3.19
**Nextcloud version:** NextCloud v 20.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:** NextCloud v 17.0.9

No errors have been found when login as admin user into your Nextcloud and access to http://example.com/index.php/settings/integrity/failed

List of activated apps:
Accessibility 1.6.0 / Activity 2.13.2 / Calendar 2.1.2 / Comments 1.10.0 / Contacts 3.4.1 / Contacts Interaction 1.1.0 / Custom CSS 1.7.0 / Data Request 1.7.0 / Deleted files 1.10.1 / DICOM Viewer 1.2.2 / External sites 3.7.1 / File sharing 1.12.0 / Group folders 8.1.0 / Log Reader 2.5.0 / Notifications 2.8.0 / Password policy 1.10.1 / PDF viewer 2.0.1 / Photos 1.2.0 / Recommendations 0.8.0 / Right click 0.17.0 / Share by mail 1.10.0 / Support 1.3.0 / Text 3.1.0 / Theming 1.11.0 / Update notification 1.10.0 / Usage survey 1.8.0 / User status 1.0.0 / Versions 1.13.0 / Video player 1.9.0

**Are you using external storage, if yes which one: no
**Are you using encryption: no
**Are you using an external user-backend, if yes which one: no

### Client configuration
Version 86.0.4240.111 (Build officiel) (64 bits)

**Operating system:**
Windows 10 Version 10.0.19041 Numéro 19041

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/server/issues/24209
Fix https://github.com/nextcloud/server/issues/19562

Put the mail shares into he same check as link shares and unify settings
- [x] The password enforce was not making any sense here
- [x] Disabling the "send by mail" and enforcing password would lead to a random unknown password
  :arrow_right: we now show the dropdown automatically with the random password (if enforced)
- [x] Make sure the mail shares uses the proper expiration
- [x] Clear the input after adding a new share
- [x] Show the email on a second line if a label is set
  Capture d’écran_2020-11-25_10-15-05

___
Peek 25-11-2020 09-57

### CODE REVIEW

**Comment by skjnldsv** [comment]
@danxuliu could you help me fix the integration tests?
I changed some, but I have some weird errors still

```json
{
  "reqId": "OdgJseuExbSjfUS81AX4",
  "level": 3,
  "time": "2020-11-25T10:08:44+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "no app in context",
  "method": "",
  "url": "--",
  "message": {
    "Exception": "Error",
    "Message": "Call to a member function getContainer() on null",
    "Code": 0,
    "Trace": [
      {
        "file": "/drone/src/lib/private/AppFramework/Bootstrap/Coordinator.php",
        "line": 143,
        "function": "delegateContainerRegistrations",
        "class": "OC\\AppFramework\\Bootstrap\\RegistrationContext",
        "type": "->",
        "args": [
          {
            "spreed": {
              "__class__": "OCA\\Talk\\AppInfo\\Application"
            }
          }
        ]
      },
      {
        "file": "/drone/src/lib/private/AppFramework/Bootstrap/Coordinator.php",
        "line": 86,
        "function": "registerApps",
        "class": "OC\\AppFramework\\Bootstrap\\Coordinator",
        "type": "->",
        "args": [
          [
            "spreed"
          ]
        ]
      },
      {
        "file": "/drone/src/lib/private/Installer.php",
        "line": 144,
        "function": "runLazyRegistration",
        "class": "OC\\AppFramework\\Bootstrap\\Coordinator",
        "type": "->",
        "args": [
          "spreed"
        ]
      },
      {
        "file": "/drone/src/core/Command/App/Enable.php",
        "line": 123,
        "function": "installApp",
        "class": "OC\\Installer",
        "type": "->",
        "args": [
          "spreed",
          false
        ]
      },
      {
        "file": "/drone/src/core/Command/App/Enable.php",
        "line": 93,
        "function": "enableApp",
        "class": "OC\\Core\\Command\\App\\Enable",
        "type": "->",
        "args": [
          "spreed",
          [],
          false,
          {
            "__class__": "Symfony\\Component\\Console\\Output\\ConsoleOutput"
          }
        ]
      },
      {
        "file": "/drone/src/3rdparty/symfony/console/Command/Command.php",
        "line": 255,
        "function": "execute",
        "class": "OC\\Core\\Command\\App\\Enable",
        "type": "->",
        "args": [
          {
            "__class__": "Symfony\\Component\\Console\\Input\\ArgvInput"
          },
          {
            "__class__": "Symfony\\Component\\Console\\Output\\ConsoleOutput"
          }
        ]
      },
      {
        "file": "/drone/src/3rdparty/symfony/console/Application.php",
        "line": 1009,
        "function": "run",
        "class": "Symfony\\Component\\Console\\Command\\Command",
        "type": "->",
        "args": [
          {
            "__class__": "Symfony\\Component\\Console\\Input\\ArgvInput"
          },
          {
            "__class__": "Symfony\\Component\\Console\\Output\\ConsoleOutput"
          }
        ]
      },
      {
        "file": "/drone/src/3rdparty/symfony/console/Application.php",
        "line": 273,
        "function": "doRunCommand",
        "class": "Symfony\\Component\\Console\\Application",
        "type": "->",
        "args": [
          {
            "__class__": "OC\\Core\\Command\\App\\Enable"
          },
          {
            "__class__": "Symfony\\Component\\Console\\Input\\ArgvInput"
          },
          {
            "__class__": "Symfony\\Component\\Console\\Output\\ConsoleOutput"
          }
        ]
      },
      {
        "file": "/drone/src/3rdparty/symfony/console/Application.php",
        "line": 149,
        "function": "doRun",
        "class": "Symfony\\Component\\Console\\Application",
        "type": "->",
        "args": [
          {
            "__class__": "Symfony\\Component\\Console\\Input\\ArgvInput"
          },
          {
            "__class__": "Symfony\\Component\\Console\\Output\\ConsoleOutput"
          }
        ]
      },
      {
        "file": "/drone/src/lib/private/Console/Application.php",
        "line": 215,
        "function": "run",
        "class": "Symfony\\Component\\Console\\Application",
        "type": "->",
        "args": [
          {
            "__class__": "Symfony\\Component\\Console\\Input\\ArgvInput"
          },
          {
            "__class__": "Symfony\\Component\\Console\\Output\\ConsoleOutput"
          }
        ]
      },
      {
        "file": "/drone/src/console.php",
        "line": 100,
        "function": "run",
        "class": "OC\\Console\\Application",
        "type": "->",
        "args": []
      }
    ],
    "File": "/drone/src/lib/private/AppFramework/Bootstrap/RegistrationContext.php",
    "Line": 369,
    "CustomMessage": "Error during service alias registration of files_trashbin: Call to a member function getContainer() on null"
  },
  "userAgent": "--",
  "version": "21.0.0.7"
}
```

**Review by danxuliu — COMMENTED** [review]
I have extracted some of the changes to their own commits (please do not squash several fixes and changes in the same commit, as it makes reviewing more difficult both now and in the future in case a bisection is needed). I am not sure if it would be even better to extract them to different pull request to ease backporting (I have not checked if they need to be backported and to which versions, though, so maybe it is fine if they are all in the same pull request :-) ).

In any case, I have not addressed yet the integration test failures (although I think that they are legit and caused by an "overunification" :-) For example [the password of mail shares can not be hashed before passing it to the provider](https://github.com/nextcloud/server/blob/6e529d6c4788eef741e22c086c46372baeace651/lib/private/Share20/Manager.php#L750-L773) (as otherwise it would be hashed in the e-mail too)).

I was wondering if it would be better not to unify the settings. Although similar, mail shares are not link shares, and the infrastructure to enforce passwords in mail shares independently of link shares is already in place and _works_, so unifying it would be removing a feature that may (or may not) be useful for some people.

Due to this I would not unify the enforced password setting for link and mail shares. However, in this case I guess that an expiration date field specific to mail shares should be added too (as using the setting from link shares for this would be counterintuitive).

Additionally, the fact that mail shares require link shares to be enabled seems to be just due to [a check in the middleware](https://github.com/nextcloud/server/blob/caff1023ea72bb2ea94130e18a2a6e2ccf819e5f/lib/private/AppFramework/Middleware/PublicShare/PublicShareMiddleware.php#L57-L59). But I think that check should not be there :-) The public share page is generic and makes possible to view any share with a token, not only link shares. Due to this, if link shares are disabled, that check causes that mail shares and also shares in public Talk conversations to not be available.

Note that even if that check is removed [link shares would still not work when disabled](https://github.com/nextcloud/server/blob/bb411c75c6a7272f62a8e6b97b92075477694a3c/lib/private/Share20/Manager.php#L1420), but other token based shares will do (although in order to be able to create mail shares [another check should be removed too](https://github.com/nextcloud/server/blob/d89a75be0b01f0423a7c1ad2d58aac73c3cc1f3a/apps/files_sharing/lib/Controller/ShareAPIController.php#L520-L523)). This is probably something for a different pull request, but I thought that it was worth mentioning it.

All in all I think that the settings for link and mail shares should not be unified (although the changes in the WebUI for the label or enforced passwords are fine). Thoughts?

Whether the settings are unified or not I think that @tobiasKaminsky would like to know about this pull request :-)

Independently of all that, when passwords for mail shares are enforced and a new mail share is created the _Video verification_ checkbox should be initially disabled (exactly the same as after a password is set), as it will not be possible to enable it until a new password is typed.

**Comment by rullzer** [comment]
@jancborchardt are you OK with merging this.
As both are just link shares anyway. They even have the same config options in the front end.

File: tests/lib/Share20/ManagerTest.php [hunk 1]
```diff
@@ -3672,11 +3675,9 @@ public function testUpdateShareMailEnableSendPasswordByTalkWithPreviousPassword(
...
 		$manager->expects($this->never())->method('validateExpirationDate');
 
-		$this->hasher->expects($this->once())
-			->method('verify')
-			->with('password', 'passwordHash')
-			->willReturn(true);
-
+		// If the old & new passwords are the same, we don't do anything
+		$this->hasher->expects($this->never())
+			->method('verify');
```
Comment (skjnldsv) [inline tests/lib/Share20/ManagerTest.php:3680]: There was en error on the previous test. using the same password should NOT trigger a new hash.

File: apps/files_sharing/lib/Controller/ShareAPIController.php [hunk 2]
```diff
@@ -1592,7 +1591,6 @@ private function getSharesFromNode(string $viewer, $node, bool $reShares): array
 			IShare::TYPE_GROUP,
 			IShare::TYPE_LINK,
 			IShare::TYPE_EMAIL,
-			IShare::TYPE_EMAIL,
```
Comment (MorrisJobke) [inline apps/files_sharing/lib/Controller/ShareAPIController.php:1595]: 🙈

File: apps/files_sharing/src/views/SharingTab.vue [hunk 3]
```diff
@@ -295,18 +297,45 @@ export default {
...
+		 */
+		awaitForShare(share, resolve) {
+			let listComponent = this.$refs.shareList
+			// Only mail shares comes from the input, link shares
+			// are managed internally in the SharingLinkList component
+			if (share.type === this.SHARE_TYPES.SHARE_TYPE_EMAIL) {
+				listComponent = this.$refs.linkShareList
+			}
+
+			this.$nextTick(() => {
```
Comment (MorrisJobke) [inline apps/files_sharing/src/views/SharingTab.vue:333]: Nice! Didn't knew about this, but sounds useful for cases like this 👍

File: lib/private/Share20/Manager.php [hunk 4]
```diff
@@ -228,18 +228,19 @@ protected function generalCreateChecks(IShare $share) {
...
 			if ($share->getSharedWith() === null) {
 				throw new \InvalidArgumentException('SharedWith should not be empty');
 			}
-		} elseif ($share->getShareType() === IShare::TYPE_REMOTE_GROUP) {
+		} elseif ($share->getShareType() === IShare::TYPE_REMOTE) {
 			if ($share->getSharedWith() === null) {
 				throw new \InvalidArgumentException('SharedWith should not be empty');
 			}
-		} elseif ($share->getShareType() === IShare::TYPE_EMAIL) {
+		} elseif ($share->getShareType() === IShare::TYPE_REMOTE_GROUP) {
```
Comment (MorrisJobke) [inline lib/private/Share20/Manager.php:243]: Is there a reason why you rotated the constants here?

File: apps/files_sharing/src/components/SharingEntryLink.vue [hunk 5]
```diff
@@ -424,6 +424,11 @@ export default {
 					})
 				}
 				if (this.share.label && this.share.label.trim() !== '') {
+					if (this.isEmailShareType) {
+						return t('files_sharing', 'Mail share ({label})', {
```
Comment (MorrisJobke) [inline apps/files_sharing/src/components/SharingEntryLink.vue:428]:
```suggestion
						return t('files_sharing', '{label} (mail share)', {
```

Does that make sense? Because I set a label and I would like to have the highlight on my label and not on "Mail share"

Comment (MorrisJobke) [reply apps/files_sharing/src/components/SharingEntryLink.vue:428]: Without label:

Bildschirmfoto 2021-03-18 um 13 49 23

With label "My label":

Bildschirmfoto 2021-03-18 um 13 49 32

Comment (MorrisJobke) [reply apps/files_sharing/src/components/SharingEntryLink.vue:428]: Proposed change:

Bildschirmfoto 2021-03-18 um 13 50 42

**Review by MorrisJobke — APPROVED** [review]
Beside my nitpick it works great 👍

File: apps/files_sharing/src/views/SharingTab.vue (hunk 3 above)
Comment (skjnldsv) [reply apps/files_sharing/src/views/SharingTab.vue:333]: Do not abuse it though :wink:

File: apps/files_sharing/src/components/SharingEntryLink.vue (hunk 5 above)
Comment (skjnldsv) [reply apps/files_sharing/src/components/SharingEntryLink.vue:428]: I used the same syntax as the link share. Maybe let's fix it in followup then if Jan wants it :)

File: lib/private/Share20/Manager.php (hunk 4 above)
Comment (skjnldsv) [reply lib/private/Share20/Manager.php:243]: Have the email next to LINK for better code reading as they are very close

**Comment by skjnldsv** [comment]
Let me fix the integration tests

**Comment by PVince81** [comment]
some conflicts, related to the fix that went in for validation date: #26200

**Comment by skjnldsv** [comment]
> some conflicts, related to the fix that went in for validation date: #26200

:cry:

**Comment by skjnldsv** [comment]
Rebased and integration tests fixed! :robot:

**Comment by MorrisJobke** [comment]
> Rebased and integration tests fixed! 🤖

Now PHPUnit and Psalm are not happy 🙈

**Comment by skjnldsv** [comment]
Rebased™

**Comment by skjnldsv** [comment]
@PVince81 @rullzer @nickvergessen @MorrisJobke GREEN!
LGTM :ship:

**Review by rullzer — APPROVED** [review]

**Comment by skjnldsv** [comment]
@tobiasKaminsky @marinofaggiana you might be interested in this!
I don't know on what you rely for email share on the clients, but now mails and link shares behaves the same! :)
