### PR TITLE
Set error_logging correctly. Fixes #19847

### LINKED ISSUE #19847: Nextcloud ignores `error_reporting` setting from php.ini
Workaround: Remove [line 606](https://github.com/nextcloud/server/blob/master/lib/base.php#L606) in `lib/base.php`

### Steps to reproduce
1. Install Nextcloud
2. Configure LDAP authentication
3. Set `error_reporting` to 0 in php.ini

### Expected behaviour
No more LDAP log spam as described in #19097

### Actual behaviour
Log continues to be inundated with useless LDAP deprecation messages

### Server configuration

**Operating system:**
Gentoo Linux

**Web server:**
Nginx

**Database:**
Postgresql

**PHP version:**
7.4

**Nextcloud version:** (see Nextcloud admin page)
18.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Where did you install Nextcloud from:**
Tarball

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - calendar: 2.0.2
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.2.0
  - dav: 1.14.0
  - encryption: 2.6.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_external: 1.9.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - user_ldap: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.example.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.example.com",
        "dbtype": "pgsql",
        "version": "18.0.1.3",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapUserCleanupInterval": 51,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "theme": "",
        "log_type": "syslog",
        "maintenance": false,
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "appcodechecker": false,
        "singleuser": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory"
    },
    "apps": {
        "accessibility": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.4.0"
        },
        "activity": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "2.11.0",
            "signed": "true"
        },
        "admin_audit": {
            "types": "logging",
            "enabled": "yes",
            "installed_version": "1.8.0"
        },
        "backgroundjob": {
            "lastjob": "1092"
        },
        "bookmarks": {
            "installed_version": "0.4",
            "types": "",
            "ocsid": "168710",
            "enabled": "no"
        },
        "bruteforcesettings": {
            "installed_version": "1.5.0",
            "types": "",
            "enabled": "no"
        },
        "calendar": {
            "types": "",
            "enabled": "yes",
            "installed_version": "2.0.2",
            "signed": "true"
        },
        "cloud_federation_api": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "1.1.0"
        },
        "comments": {
            "types": "logging",
            "enabled": "yes",
            "installed_version": "1.8.0"
        },
        "configreport": {
            "installed_version": "0.1.1",
            "types": "filesystem",
            "enabled": "no"
        },
        "contacts": {
            "types": "",
            "installed_version": "3.2.0",
            "enabled": "yes",
            "signed": "true"
        },
        "core": {
            "installedat": "1424655940.6918",
            "public_gallery": "gallery\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_calendar": "calendar\/share.php",
            "public_caldav": "calendar\/share.php",
            "public_documents": "documents\/public.php",
            "global_cache_gc_lastrun": "1455568201",
            "lastcron": "1583622907",
            "lastupdatedat": "1583622851",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "backgroundjobs_mode": "cron",
            "repairlegacystoragesdone": "yes",
            "OC_Channel": "stable",
            "default_encryption_module": "OC_DEFAULT_MODULE",
            "shareapi_allow_public_upload": "no",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "encryption_enabled": "no",
            "vendor": "nextcloud",
            "moveavatarsdone": "yes",
            "previewsCleanedUp": "1",
            "installed.bundles": "[\"CoreBundle\"]",
            "scss.variables": "db81cddf52fdb3c8ca1e4c859e214124",
            "enterpriseLogoChecked": "yes",
            "lastupdateResult": "[]",
            "oc.integritycheck.checker": "[]",
            "theming.variables": "b92d206521717ac032f8aa58d3c7ff2f"
        },
        "dav": {
            "types": "filesystem",
            "enabled": "yes",
            "buildCalendarSearchIndex": "yes",
            "installed_version": "1.14.0",
            "buildCalendarReminderIndex": "yes",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "chunks_migrated": "1"
        },
        "deck": {
            "installed_version": "0.6.6",
            "types": "dav",
            "enabled": "no"
        },
        "documents": {
            "types": "",
            "ocsid": "168711",
            "enabled": "no",
            "installed_version": "0.10.2"
        },
        "encryption": {
            "masterKeyId": "master_7d50ce56",
            "types": "filesystem",
            "publicShareKeyId": "pubShare_1cddb519",
            "recoveryKeyId": "recoveryKey_39bbe64a",
            "enabled": "yes",
            "recoveryAdminEnabled": "1",
            "userSpecificKey": "1",
            "encryptHomeStorage": "0",
            "installed_version": "2.6.0",
            "useMasterKey": "0"
        },
        "federatedfilesharing": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.8.0"
        },
        "federation": {
            "types": "authentication",
            "enabled": "yes",
            "installed_version": "1.8.0"
        },
        "files": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "1.13.1",
            "cronjob_scan_files": "500"
        },
        "files_external": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "1.9.0"
        },
        "files_locking": {
            "installed_version": "",
            "types": "filesystem",
            "enabled": "no"
        },
        "files_pdfviewer": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.7.0",
            "signed": "true"
        },
        "files_rightclick": {
            "installed_version": "0.15.2",
            "types": "",
            "enabled": "yes"
        },
        "files_sharing": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "1.10.1"
        },
        "files_texteditor": {
            "types": "",
            "enabled": "no",
            "installed_version": "2.8.0",
            "signed": "true"
        },
        "files_trashbin": {
            "types": "filesystem,dav",
            "enabled": "yes",
            "installed_version": "1.8.0"
        },
        "files_versions": {
            "enabled": "yes",
            "types": "filesystem,dav",
            "installed_version": "1.11.0"
        },
        "files_videoplayer": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.7.0"
        },
        "files_videoviewer": {
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": "",
            "enabled": "no"
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.7.0",
            "types": "logging"
        },
        "gallery": {
            "types": "",
            "enabled": "no",
            "installed_version": "18.4.0",
            "signed": "true"
        },
        "logreader": {
            "types": "",
            "enabled": "yes",
            "installed_version": "2.3.0"
        },
        "lookup_server_connector": {
            "types": "authentication",
            "installed_version": "1.6.0",
            "enabled": "yes"
        },
        "mail": {
            "types": "",
            "installed_version": "0.17.0",
            "enabled": "no"
        },
        "market": {
            "types": "",
            "templateeditor": "0.3",
            "gallery": "16.1.1",
            "user_ldap": "0.11.0",
            "files_texteditor": "2.3.0",
            "files_pdfviewer": "0.11.0",
            "activity": "2.4.2",
            "calendar": "1.6.3",
            "contacts": "1.5.5",
            "market": "0.4.0",
            "signed": "true",
            "installed_version": "0.4.0",
            "enabled": "no"
        },
        "nextcloud_announcements": {
            "types": "logging",
            "enabled": "yes",
            "installed_version": "1.7.0",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200"
        },
        "notifications": {
            "types": "logging",
            "enabled": "yes",
            "installed_version": "2.6.0"
        },
        "oauth2": {
            "installed_version": "1.6.0",
            "types": "authentication",
            "enabled": "yes"
        },
        "ocsms": {
            "installed_version": "1.4.3",
            "types": "",
            "enabled": "no"
        },
        "password_policy": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.8.0"
        },
        "photos": {
            "installed_version": "1.0.0",
            "types": "",
            "enabled": "yes"
        },
        "privacy": {
            "installed_version": "1.2.0",
            "types": "",
            "enabled": "yes"
        },
        "provisioning_api": {
            "enabled": "yes",
            "types": "prevent_group_restriction",
            "installed_version": "1.8.0"
        },
        "recommendations": {
            "installed_version": "0.6.0",
            "types": "",
            "enabled": "yes"
        },
        "search_lucene": {
            "types": "filesystem",
            "installed_version": "0.7.0",
            "ocsid": "168709",
            "enabled": "no"
        },
        "serverinfo": {
            "installed_version": "1.8.0",
            "types": "",
            "enabled": "yes"
        },
        "settings": {
            "installed_version": "1.0.0",
            "types": "",
            "enabled": "yes"
        },
        "sharebymail": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "1.8.0"
        },
        "support": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "session"
        },
        "survey_client": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.6.0"
        },
        "systemtags": {
            "installed_version": "1.8.0",
            "types": "logging",
            "enabled": "yes"
        },
        "templateeditor": {
            "types": "",
            "enabled": "no",
            "installed_version": "0.4.0",
            "signed": "true"
        },
        "text": {
            "enabled": "yes",
            "types": "dav",
            "installed_version": "2.0.0"
        },
        "theming": {
            "types": "logging",
            "enabled": "yes",
            "installed_version": "1.9.0"
        },
        "twofactor_backupcodes": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.7.0"
        },
        "updatenotification": {
            "types": "",
            "enabled": "yes",
            "core": "13.0.12.1",
            "installed_version": "1.8.0",
            "update_check_errors": "0"
        },
        "updater": {
            "types": "",
            "installed_version": "0.6",
            "enabled": "no"
        },
        "user_external": {
            "installed_version": "0.4",
            "types": "authentication,prelogin",
            "enabled": "no"
        },
        "user_ldap": {
            "ldap_port": "389",
            "ldap_base": "dc=example,dc=com",
            "ldap_userfilter_objectclass": "inetOrgPerson\nsambaSamAccount",
            "ldap_group_filter": "(objectClass=posixGroup)",
            "types": "authentication",
            "ldap_dn": "",
            "ldap_host": "localhost",
            "ldap_backup_host": "",
            "ldap_backup_port": "",
            "ldap_tls": "1",
            "ldap_turn_off_cert_check": "0",
            "ldap_display_name": "displayname",
            "ldap_userfilter_groups": "",
            "ldap_groupfilter_objectclass": "",
            "ldap_groupfilter_groups": "",
            "ldap_group_display_name": "cn",
            "ldap_loginfilter_email": "0",
            "ldap_loginfilter_username": "1",
            "ldap_loginfilter_attributes": "",
            "ldap_quota_attr": "",
            "ldap_userlist_filter": "(|(objectclass=inetOrgPerson)(objectclass=sambaSamAccount))",
            "ldap_login_filter": "(&(|(objectclass=inetOrgPerson)(objectclass=sambaSamAccount))(uid=%uid))",
            "ldap_agent_password": "***REMOVED SENSITIVE VALUE***",
            "ldap_base_users": "dc=example,dc=com",
            "ldap_base_groups": "ou=Group,dc=example,dc=com",
            "ldap_group_filter_mode": "1",
            "ldap_login_filter_mode": "1",
            "ldap_user_filter_mode": "0",
            "enabled": "yes",
            "installed_version": "1.8.0",
            "ldap_group_member_assoc_attribute": "memberUid",
            "ldap_quota_def": "",
            "ldap_cache_ttl": "600",
            "ldap_attributes_for_user_search": "",
            "ldap_attributes_for_group_search": "",
            "ldap_experienced_admin": "0",
            "home_folder_naming_rule": "",
            "ldap_expert_uuid_group_attr": "",
            "last_jpegPhoto_lookup": "0",
            "ldap_nested_groups": "0",
            "ldap_paging_size": "500",
            "has_memberof_filter_support": "",
            "ldap_email_attr": "mail",
            "ldap_configuration_active": "1",
            "ldap_override_main_server": "0",
            "ldap_expert_uuid_user_attr": "cn",
            "cleanUpJobOffset": "0",
            "enforce_home_folder_naming_rule": "",
            "ldap_user_display_name_2": "",
            "use_memberof_to_detect_membership": "1",
            "ldap_expert_username_attr": "uid",
            "ldap_dynamic_group_member_url": "",
            "signed": "true",
            "ldap_user_name": "samaccountname",
            "ldap_gid_number": "gidNumber",
            "ldap_turn_on_pwd_change": "0",
            "ldap_default_ppolicy_dn": "",
            "background_sync_prefix": "",
            "background_sync_offset": "0",
            "background_sync_interval": "43200",
            "_lastChange": "1583273432"
        },
        "viewer": {
            "installed_version": "1.2.0",
            "types": "",
            "enabled": "yes"
        },
        "workflowengine": {
            "installed_version": "2.0.0",
            "types": "filesystem",
            "enabled": "yes"
        }
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
+-------------------------------+--------------------------------------------------------------------------+
| Configuration                 |                                                                          |
+-------------------------------+--------------------------------------------------------------------------+
| hasMemberOfFilterSupport      |                                                                          |
| homeFolderNamingRule          |                                                                          |
| lastJpegPhotoLookup           | 0                                                                        |
| ldapAgentName                 |                                                                          |
| ldapAgentPassword             | ***                                                                      |
| ldapAttributesForGroupSearch  |                                                                          |
| ldapAttributesForUserSearch   |                                                                          |
| ldapBackupHost                |                                                                          |
| ldapBackupPort                |                                                                          |
| ldapBase                      | dc=example,dc=com                                                      |
| ldapBaseGroups                | ou=Group,dc=example,dc=com                                             |
| ldapBaseUsers                 | dc=example,dc=com                                                      |
| ldapCacheTTL                  | 600                                                                      |
| ldapConfigurationActive       | 1                                                                        |
| ldapDefaultPPolicyDN          |                                                                          |
| ldapDynamicGroupMemberURL     |                                                                          |
| ldapEmailAttribute            | mail                                                                     |
| ldapExperiencedAdmin          | 0                                                                        |
| ldapExpertUUIDGroupAttr       |                                                                          |
| ldapExpertUUIDUserAttr        | cn                                                                       |
| ldapExpertUsernameAttr        | uid                                                                      |
| ldapExtStorageHomeAttribute   |                                                                          |
| ldapGidNumber                 | gidNumber                                                                |
| ldapGroupDisplayName          | cn                                                                       |
| ldapGroupFilter               | (objectClass=posixGroup)                                                 |
| ldapGroupFilterGroups         |                                                                          |
| ldapGroupFilterMode           | 1                                                                        |
| ldapGroupFilterObjectclass    |                                                                          |
| ldapGroupMemberAssocAttr      | memberUid                                                                |
| ldapHost                      | localhost                                                                |
| ldapIgnoreNamingRules         |                                                                          |
| ldapLoginFilter               | (&(|(objectclass=inetOrgPerson)(objectclass=sambaSamAccount))(uid=%uid)) |
| ldapLoginFilterAttributes     |                                                                          |
| ldapLoginFilterEmail          | 0                                                                        |
| ldapLoginFilterMode           | 1                                                                        |
| ldapLoginFilterUsername       | 1                                                                        |
| ldapNestedGroups              | 0                                                                        |
| ldapOverrideMainServer        | 0                                                                        |
| ldapPagingSize                | 500                                                                      |
| ldapPort                      | 389                                                                      |
| ldapQuotaAttribute            |                                                                          |
| ldapQuotaDefault              |                                                                          |
| ldapTLS                       | 1                                                                        |
| ldapUserAvatarRule            | default                                                                  |
| ldapUserDisplayName           | displayname                                                              |
| ldapUserDisplayName2          |                                                                          |
| ldapUserFilter                | (|(objectclass=inetOrgPerson)(objectclass=sambaSamAccount))              |
| ldapUserFilterGroups          |                                                                          |
| ldapUserFilterMode            | 0                                                                        |
| ldapUserFilterObjectclass     | inetOrgPerson;sambaSamAccount                                            |
| ldapUuidGroupAttribute        | auto                                                                     |
| ldapUuidUserAttribute         | auto                                                                     |
| turnOffCertCheck              | 0                                                                        |
| turnOnPasswordChange          | 0                                                                        |
| useMemberOfToDetectMembership | 1                                                                        |
+-------------------------------+--------------------------------------------------------------------------+
```
</details>

### Client configuration
**Browser:**
Several

**Operating system:**
Several

#### Web server error log
<details>
<summary>Web server error log</summary>
Irrelevant
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
Same as #19097
</details>

#### Browser log
<details>
<summary>Browser log</summary>
Irrelevant
</details>

### PR DESCRIPTION
**Pull request by Jose123456**
Fix #19847 

Don't override the error_logging setting from php.ini unless we're
debugging.

### CODE REVIEW

File: lib/base.php [hunk 1]
```diff
@@ -602,8 +602,12 @@ public static function init() {
 		\OC::$server->getEventLogger()->log('autoloader', 'Autoloader', $loaderStart, $loaderEnd);
 		\OC::$server->getEventLogger()->start('boot', 'Initialize');
 
+		// Override php.ini and log everything if we're troubleshooting
+		if (self::$config->getValue('loglevel') === ILogger::DEBUG) {
+			error_reporting(E_ALL | E_DEPRECATED);
```
Comment (kesselb) [inline lib/base.php]: I think E_DEPRECATED is redundant.

Comment (Jose123456) [reply lib/base.php]: You are correct, sir. Fixed

**Review by kesselb — APPROVED** [review]
Thanks :+1:

**Review by ChristophWurst — APPROVED** [review]

**Review by rullzer — APPROVED** [review]
