### PR TITLE
fix(settings): Send update request when clearing user manager

### LINKED ISSUE #44492: [Bug]: I cannot remove manager from a user
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I go to user settings and try to remove the manager of a contact. The name is removed from the input field but a loading icon is shown and when i save it the name of the manager still shows up there.

### Steps to reproduce

1. Go to user settings
2. Remove a manager from an existing user
3. Try to save it

### Expected behavior

The manager is removed

### Installation method

None

### Nextcloud Server version

29

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by nfebe**
* Based on https://github.com/nextcloud/server/pull/52831
* Resolves https://github.com/nextcloud/server/issues/44492

### CODE REVIEW

File: apps/settings/src/components/Users/UserRow.vue [hunk 1]
```diff
@@ -613,21 +619,23 @@ export default {
...
 					key: 'manager',
-					value: this.currentManager ? this.currentManager.id : '',
+					value: manager ? manager.id : '',
 				})
+
 			} catch (error) {
 				// TRANSLATORS This string describes a line manager in the context of an organization
 				showError(t('settings', 'Failed to update line manager'))
-				console.error(error)
+				console.error('Failed to update manager:', error)
```
Comment (artonge) [inline apps/settings/src/components/Users/UserRow.vue:635]:
```suggestion
				logger.error('Failed to update manager:', { error })
```

File: apps/settings/src/components/Users/UserRow.vue [hunk 2]
```diff
@@ -613,21 +619,23 @@ export default {
...
-			}
+		async updateUserManager() {
 			this.loading.manager = true
+
 			try {
 				await this.$store.dispatch('setUserData', {
 					userid: this.user.id,
 					key: 'manager',
-					value: this.currentManager ? this.currentManager.id : '',
+					value: manager ? manager.id : '',
```
Comment (artonge) [inline apps/settings/src/components/Users/UserRow.vue:629]: I cannot find the `manager` variable :thinking:

File: apps/settings/src/store/users.js [hunk 3]
```diff
@@ -767,23 +767,27 @@ const actions = {
...
-				try {
-					await api.requireAdmin()
-					await api.put(generateOcsUrl('cloud/users/{userid}', { userid }), { key, value })
-					return context.commit('setUserData', { userid, key, value })
-				} catch (error) {
-					context.commit('API_FAILURE', { userid, error })
-				}
+		const validKeys = ['email', 'language', 'quota', 'displayname', 'password', 'manager']
+		if (!validKeys.includes(key)) {
+			return Promise.reject(new Error('Invalid request data'))
```
Comment (artonge) [inline apps/settings/src/store/users.js:772]: Can't you simply throw?
```suggestion
			throw new Error('Invalid request data')
```

File: apps/settings/src/store/users.js [hunk 4]
```diff
@@ -767,23 +767,27 @@ const actions = {
...
+		}
+
+		try {
+			await api.requireAdmin()
+			if (typeof value === 'string' && value.length === 0 && allowedEmpty.includes(key)) {
```
Comment (artonge) [inline apps/settings/src/store/users.js:777]:
```suggestion
			if (value === '' && allowedEmpty.includes(key)) {
```

File: apps/settings/src/store/users.js [hunk 5]
```diff
@@ -767,23 +767,27 @@ const actions = {
...
+				// If value is empty and allowed to be empty, send DELETE request
+				await api.delete(generateOcsUrl('cloud/users/{userid}', { userid }), { key })
+				return context.commit('setUserData', { userid, key, value: '' })
 			}
+
+			if (typeof value === 'string' && (value.length > 0 || allowedEmpty.includes(key))) {
```
Comment (artonge) [inline apps/settings/src/store/users.js:783]:
```suggestion
			if (value === '' || allowedEmpty.includes(key))) {
```

File: apps/settings/src/components/Users/UserRow.vue [hunk 6]
```diff
@@ -613,11 +619,12 @@ export default {
...
 
-		async updateUserManager(manager) {
-			if (manager === null) {
-				this.currentManager = ''
-			}
+		async updateUserManager() {
 			this.loading.manager = true
+
+			// Store the current manager before making changes
+			const previousManager = this.currentManager
```
Comment (susnux) [inline apps/settings/src/components/Users/UserRow.vue:626]: Thats not the previous manager that already the new one

Comment (nfebe) [reply apps/settings/src/components/Users/UserRow.vue]: True, fixed. Thank you

**Review by nfebe — COMMENTED** [review]
@susnux I removed the watch you implemented because it causes the request to be sent twice as we experienced yesterday

**Review by susnux — APPROVED** [review]
Seems to work, but would feel better to add this to the existing Cypress test.

File: apps/settings/src/components/Users/UserRow.vue [hunk 7]
```diff
@@ -627,7 +628,10 @@ export default {
 			} catch (error) {
 				// TRANSLATORS This string describes a line manager in the context of an organization
 				showError(t('settings', 'Failed to update line manager'))
-				console.error(error)
+				logger.error('Failed to update manager:', error)
```
Comment (artonge) [inline apps/settings/src/components/Users/UserRow.vue:631]:
```suggestion
				logger.error('Failed to update manager:', { error })
```

**Review by artonge — APPROVED** [review]

File: apps/settings/src/components/Users/UserRow.vue (hunk 7 above)
Comment (nfebe) [reply apps/settings/src/components/Users/UserRow.vue:631]: Oh yeah : https://github.com/nextcloud/server/pull/53053
