### PR TITLE
fix(papercut) - rerendered submenu actions for time sensitive actions

### LINKED ISSUE #41336: Move reminder conditional rendering into action `enabled`
https://github.com/nextcloud/server/blob/32c1aebaae07b9b4d7e2dcdfca6b2cbd36a6cfc3/apps/files_reminders/src/actions/setReminderSuggestionActions.ts#L86

Since the presence of the action should be evaluated ideally on click instead of on script execution I think the `FileAction` enabled callback needs to be set to something like `() => Boolean(getDateTime(option.dateTimePreset))` to be more reactive

_Originally posted by @Pytal in https://github.com/nextcloud/server/pull/41010#discussion_r1385269899_

### PR DESCRIPTION
**Pull request by emoral435**
* Resolves #41336

## Summary
Changes submenu loading to re-render the actions in the submenu, as the items could potentially be time dependent. As of now, the items within the submenu are only loaded when dependencies change, or upon initial loading of the page, but by loading it whenever the user clicked the button, they wont have to reload the page, saving them an extra click ✅

## BEFORE
piM9LcEWjP

## AFTER
jFihBodbD6

## TODO

- [x] Since the presence of the action should be evaluated ideally on click instead of on script execution I think the FileAction enabled callback needs to be set to something like () => Boolean(getDateTime(option.dateTimePreset)) to be more reactive
- [x] Made it so that when an action within the dropdown changes the openedSubmenu dependency, reloads only the submenu action and doesn't change other computed dependencies, which would slow down the loading of the page

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by emoral435** [comment]
will compile assets once reviews look good!

File: apps/files/src/components/FileEntry/FileEntryActions.vue [hunk 1]
```diff
@@ -108,6 +108,7 @@ import NcLoadingIcon from '@nextcloud/vue/dist/Components/NcLoadingIcon.js'
 
 import CustomElementRender from '../CustomElementRender.vue'
 import logger from '../../logger.js'
+import type { LogLevel } from '@nextcloud/logger'
```
Comment (Pytal) [inline apps/files/src/components/FileEntry/FileEntryActions.vue:111]:
```suggestion
```

File: apps/files_reminders/src/actions/setReminderSuggestionActions.ts [hunk 2]
```diff
@@ -69,7 +69,7 @@ const nextWeek: ReminderOption = {
  * @param option The option to generate the action for
  * @return The file action or null if the option should not be shown
  */
-const generateFileAction = (option): FileAction|null => {
+const generateFileAction = (option: ReminderOption): FileAction|null => {
 	const dateTime = getDateTime(option.dateTimePreset)
 	if (!dateTime) {
 		return null
```
Comment (Pytal) [inline apps/files_reminders/src/actions/setReminderSuggestionActions.ts:75]:
```suggestion
```
This check should be removed

Now `getDateTime()` should be called and the returned Date used in the displayName, title, and exec methods instead

Comment (emoral435) [reply apps/files_reminders/src/actions/setReminderSuggestionActions.ts:75]: I see what you mean, I am updating any area with the current dateTime variable with a call to getDateTime()

**Review by susnux — DISMISSED** [review]
Why is 3rdparty changed?

**Review by Pytal — APPROVED** [review]
Thanks! Just gotta remove 3rdparty changes 🙈

**Comment by Pytal** [comment]
Let's squash these commits into one @emoral435 :)

File: apps/files/src/components/FileEntry/FileEntryActions.vue [hunk 3]
```diff
@@ -270,6 +270,32 @@ export default Vue.extend({
 			return action.displayName([this.source], this.currentView)
 		},
 
+		// same as enabledSubmenuActions computed function, but instead as a method to be able to
```
Comment (skjnldsv) [inline apps/files/src/components/FileEntry/FileEntryActions.vue:273]: Really not sure about this, the implementation looks very unusual.
Why would only sub-menus allowed to auto refresh?

I think this is something that should be fixed in a different way maybe?
Have you tried returning a reference for the displayName and have that reference change? Is the menu not already updating as is? I think ""in theory"" having dynamic string updated on render should already work.
The issue is that we're returning a string from  `displayName` or `title` instead of a `reference` to a string, so vue doesn't see any change :thinking:

Comment (emoral435) [reply apps/files/src/components/FileEntry/FileEntryActions.vue:273]: Yep, as of right now, I am trying to think of a clever way to have the submenu actions refresh so that time dependent actions are loaded depending on the time when the user clicked, and not when the page got loaded. 

I am trying to see ways around the caching such that we do not recompute too much so that the clients side does not slow down, so I will give what you said and other methods as well a shot

**Review by skjnldsv — COMMENTED** [review]
Please also remove the last `.filter(Boolean) as FileAction[]` then :)

File: apps/files/src/components/FileEntry/FileEntryActions.vue (hunk 3 above)
Comment (Pytal) [reply apps/files/src/components/FileEntry/FileEntryActions.vue:273]: Seems to work so fine with me ⏲

Comment (emoral435) [reply apps/files/src/components/FileEntry/FileEntryActions.vue:273]: I tried this out on my local dev, its fine with me as well! I like this solution, ties back to the original issue discussing how refreshing the submenu on every click may slow down performance :) submitting my pr changes right now

File: apps/files_reminders/src/actions/setReminderSuggestionActions.ts [hunk 4]
```diff
@@ -110,7 +115,27 @@ const generateFileAction = (option): FileAction|null => {
...
 
+[laterToday, tomorrow, thisWeekend, nextWeek].forEach((option) => {
+	// Generate the initial date string
+	const dateTime = getDateTime(option.dateTimePreset)
+	if (!dateTime) {
+		return
+	}
+	option.dateString = getDateString(dateTime)
+	option.verboseDateString = getVerboseDateString(dateTime)
+	+
```
[the remark this answers is not in the document]
Comment (emoral435) [reply apps/files_reminders/src/actions/setReminderSuggestionActions.ts:126]: Yep, embarrassed that got caught LOL, thank you!

**Review by skjnldsv — APPROVED** [review]
