### PR TITLE
fix(SetupManager): Include home and root providers when registering mounts

### LINKED ISSUE #52957: [Bug]: Already cached mounts are added over and over
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

A setup of the FS will add some mounts to oc_mounts again even though they are already present.
Found in https://github.com/nextcloud/server/pull/50157.

### Steps to reproduce

1. Place debugger at https://github.com/nextcloud/server/blob/13f23061e87b182f23dfd9757273a1b66419a7e3/lib/private/Files/Config/UserMountCache.php#L97
2. Observe the home mount being added every time the FS is setup.

### Expected behavior

Only fire the events when necessary

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by provokateurin**
## Summary

Fixes https://github.com/nextcloud/server/issues/52957.
On each setup of the FS the home mount for the user was added to the oc_mounts table (while already being present), so a lot of unnecessary overhead.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: lib/private/Files/Config/MountProviderCollection.php [hunk 1]
```diff
@@ -146,7 +127,7 @@ public function addMountForUser(IUser $user, IMountManager $mountManager, ?calla
 	 * @since 9.1.0
 	 */
 	public function getHomeMountForUser(IUser $user) {
-		/** @var \OCP\Files\Config\IHomeMountProvider[] $providers */
+		/** @var IHomeMountProvider[] $providers */
```
Comment (come-nc) [inline lib/private/Files/Config/MountProviderCollection.php:130]:
```suggestion
```
Should not be needed?

File: lib/private/Files/Config/MountProviderCollection.php [hunk 2]
```diff
@@ -160,7 +141,7 @@ public function getHomeMountForUser(IUser $user) {
 	/**
 	 * Add a provider for mount points
 	 *
-	 * @param \OCP\Files\Config\IMountProvider $provider
+	 * @param IMountProvider $provider
```
Comment (come-nc) [inline lib/private/Files/Config/MountProviderCollection.php:144]:
```suggestion
```
There is the strong type already

**Review by come-nc — APPROVED** [review]
Looks sane to me.

Any reason IHomeMountProvider and IRootMountProvider are not extending IMountProvider ?
Looks like an oversight to me.

**Comment by provokateurin** [comment]
> Any reason IHomeMountProvider and IRootMountProvider are not extending IMountProvider ?

No idea TBH

**Review by susnux — APPROVED** [review]
