### PR TITLE
Fix the HTML encoding when uploading a folder in FF when using french…

### LINKED ISSUE #459: Encoding error in error messages
### Steps to reproduce
1. Login as a user in Firefox
2. Switch language to "French"
3. Go to Files app and drag&drop a folder

### Expected behaviour
Error message should appear properly in the interface.

### Actual behaviour
Encoding of the message is broken. Screenshot:
screenshot3

A OC 8.2.7 setup on the same system doesn't show this problem.

### Server configuration
**Operating system**: Debian 8

**Web server:** Apache

**Database:** MariaDB

**PHP version:** php7.0 (dotdeb-packages)

**Nextcloud version:** 9.0.53

**Updated from an older Nextcloud/ownCloud or fresh install:** 9.0.52

**Signing status:** no error.

### PR DESCRIPTION
**Pull request by nickvergessen**
… l10n

Fix #459 

Please review @tflidd

### CODE REVIEW

**Comment by tflidd** [comment]
That was a quick fix. Thank you, it works perfectly.
:+1:

File: apps/files/js/file-upload.js [hunk 1]
```diff
@@ -474,9 +474,9 @@ OC.Upload = {
 						} else {
 							// HTTP connection problem
 							var message = t('files', 'Error uploading file "{fileName}": {message}', {
-								fileName: data.files[0].name,
+								fileName: escapeHTML(data.files[0].name),
 								message: data.errorThrown
-							});
+							}, undefined, {escape: false});
```
Comment (LukasReschke) [inline apps/files/js/file-upload.js]: I got to say that I consider this a kinda risky chance. While `data.errorThrown` may right now not echo back user controlled input this has still the potential to do bad things… 🙈

Comment (LukasReschke) [inline apps/files/js/file-upload.js]: Can we do that at https://github.com/nextcloud/server/blob/45c99c226bd221bdf21a8579834524204b034706/apps/files/js/file-upload.js#L357-L360? Then we prevent the double escaping.

Comment (nickvergessen) [inline apps/files/js/file-upload.js]: The file name is already escaped there, it is also escaped here.
The problem is, that the actual translation contains the `'`, and when using that string here as a parameter in the translation, it is html encoded and displayes as `&#...;`. So not sure how this could be fixed on the other place, if this place breaks it.

Comment (LukasReschke) [inline apps/files/js/file-upload.js]: Simply unescape https://github.com/nextcloud/server/blob/45c99c226bd221bdf21a8579834524204b034706/apps/files/js/file-upload.js#L357-L360? Then the escaping here will take care of it, or do I miss something?

Comment (LukasReschke) [inline apps/files/js/file-upload.js]: Aha… Gotcha now… Let me think…

Comment (nickvergessen) [inline apps/files/js/file-upload.js]: unescape what? the unescape option only affects parameters, but the parameter is not the problem. Also the value in `data.errorThrown` here is not a problem, it's still what we would display in the UI. It's the `t()` method here, which takes the translated string as an argument and thereby `s/'/&#..;` the first translation. TO avoid this I removed escaping from all parameters and only escaped the file name, since the string here is only translator controlled, not user controlled, we can and have to trust it anyway....

Comment (LukasReschke) [inline apps/files/js/file-upload.js]: Ok. You're right. This is also properly escaped all since we don't use showHTML.

**Comment by LukasReschke** [comment]
👍

**Comment by MorrisJobke** [comment]
@nickvergessen @LukasReschke Backport?
