### PR TITLE
fix(Request): Catch exceptions in `isTrustedProxy`

### LINKED ISSUE #1973: Upgraded from 24.0.11 to 25.0.5 then 25.0.6 but site is 500'ing
I apologize as I don't know where the actual issue is as I can't find much of anyone else having problems.

A few weeks back I upgraded from 24.0.11 via a docker compose file to 25.0.5. I started getting 500 errors when trying to load Nextcloud. I thought maybe it was Traefik, but I'm able to access a test .html file I put in the Nextcloud directory with no issue and I can access cron.php (though with errors). Everything I can tell from getting into the container is that things are working properly. I can run occ commands, etc. no problems there and could monitor the logs of the cron container and they were running fine.

I just upgraded to 25.0.6 and facing the same issue as I thought maybe that version in particular was the issue. While the app upgraded just fine, I'm still getting 500 errors.

Here is the upgrade process in docker:

Configuring Redis as session handler
Initializing nextcloud 25.0.6.1 ...
Upgrading nextcloud from 25.0.5.1 ...
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Starting code integrity check...
Finished code integrity check
Update successful
Turned off maintenance mode
Resetting log level
The following apps have been disabled:
Initializing finished

Here is my compose file.

```
version: '3'  

services:
  db:
    image: mariadb:10.6
    container_name: nextcloud-mariadb
    networks:
      - nextcloud
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=xxxxxxxxxxxxxxxxxx
      - MYSQL_PASSWORD=xxxxxxxxxxxxxxxxxx
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped

  redis:
    image: redis
    container_name: nextcloud-redis
    command: redis-server --requirepass xxxxxxxxxxxx
    networks:
      - nextcloud
    volumes:
      - /nextcloud/redis:/var/lib/redis
    restart: unless-stopped

  app:
    image: nextcloud:25.0.6
    container_name: nextcloud-app
    hostname: cloud.domain.net
    privileged: true
    networks:
      - traefik
      - nextcloud
    depends_on:
      - db
      - redis
    volumes:
      - /nextcloud/www:/var/www/html
      - /nextcloud/www/config:/var/www/html/config
      - /nextcloud/www/custom_apps:/var/www/html/custom_apps
      - /nextcloud/www/data:/var/www/html/data
      - /nextcloud/www/themes:/var/www/html/themes
      - /nextcloud/php/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini:ro
    environment:
      - REDIS_HOST=nextcloud-redis
      - REDIS_HOST_PASSWORD=xxxxxxxxxxxxx
      - MYSQL_PASSWORD=xxxxxxxxxxxx
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-mariadb
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.domain.net
      - TRUSTED_PROXIES=172.18.0.0/16,172.21.0.0/16
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.domain.net`)"
      - "traefik.http.routers.nextcloud.entrypoints=https"
      - "traefik.http.routers.nextcloud.tls.certresolver=dns-cloudflare"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-dav,nextcloud-sec"
      - "traefik.http.middlewares.nextcloud-sec.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.nextcloud-sec.headers.stsSeconds=155520011"
      - "traefik.http.middlewares.nextcloud-sec.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.nextcloud-sec.headers.stsPreload=true"
      - "traefik.http.middlewares.nextcloud-dav.replacepathregex.regex=^/.well-known/ca(l|rd)dav"
      - "traefik.http.middlewares.nextcloud-dav.replacepathregex.replacement=/remote.php/dav/"
    restart: unless-stopped

  cron:
    image: nextcloud:25.0.6
    container_name: nextcloud-cron
    restart: unless-stopped
    volumes:
      - /nextcloud/www:/var/www/html
    entrypoint: /cron.sh
    networks:
      - nextcloud
    depends_on:
      - db
      - redis

networks:
  traefik:
    external: true
    name: traefik  
  nextcloud:
    external: false
    name: nextcloud
```

The only thing that stands out to me is the persistent nextcloud-init-sync.lock file. No matter what I do to delete it, every time the container is restarted it comes back. And I see the file has an updated timestamp to just a few minutes ago because I just ran the upgrade.

I've looked at https://github.com/nextcloud/docker/issues/1756 as a possible similar problem, or https://github.com/nextcloud/docker/issues/1749 but the recommendation of deleting the file doesn't work. 

So, if this isn't a docker issue, i'll move it to the Nextcloud server repo, but this is a bit frustrating and I've been basically down for a month now. 

For what it's worth, if I load the cron.php file in a browser, this is the information I get. Not sure if this expected or not:

```
TypeError: substr_compare(): Argument #4 ($length) must be of type ?int, string given in /var/www/html/3rdparty/symfony/http-foundation/IpUtils.php:104 Stack trace: #0 /var/www/html/3rdparty/symfony/http-foundation/IpUtils.php(104): substr_compare('101011000001001...', '101011000001001...', 0, '16,172.21.0.0/1...') #1 /var/www/html/3rdparty/symfony/http-foundation/IpUtils.php(52): Symfony\Component\HttpFoundation\IpUtils::checkIp4('172.18.0.4', '172.18.0.0/16,1...') #2 /var/www/html/lib/private/AppFramework/Http/Request.php(588): Symfony\Component\HttpFoundation\IpUtils::checkIp('172.18.0.4', Array) #3 /var/www/html/lib/private/AppFramework/Http/Request.php(880): OC\AppFramework\Http\Request->isTrustedProxy(Array, '172.18.0.4') #4 /var/www/html/lib/private/AppFramework/Http/Request.php(808): OC\AppFramework\Http\Request->fromTrustedProxy() #5 /var/www/html/lib/private/Server.php(1225): OC\AppFramework\Http\Request->getInsecureServerHost() #6 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(162): OC\Server->OC\{closure}(Object(OC\Server)) #7 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container)) #8 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(129): Pimple\Container->offsetGet('ThemingDefaults') #9 /var/www/html/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query('ThemingDefaults', false) #10 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query('ThemingDefaults') #11 /var/www/html/lib/private/Server.php(2156): OC\AppFramework\Utility\SimpleContainer->get('ThemingDefaults') #12 /var/www/html/lib/private/Server.php(1408): OC\Server->getThemingDefaults() #13 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(162): OC\Server->OC\{closure}(Object(OC\Server)) #14 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container)) #15 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(129): Pimple\Container->offsetGet('OCP\\Defaults') #16 /var/www/html/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query('OCP\\Defaults', false) #17 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query('OCP\\Defaults') #18 /var/www/html/lib/private/legacy/OC_Util.php(521): OC\AppFramework\Utility\SimpleContainer->get('OCP\\Defaults') #19 /var/www/html/lib/base.php(687): OC_Util::checkServer(Object(OC\SystemConfig)) #20 /var/www/html/lib/base.php(1145): OC::init() #21 /var/www/html/cron.php(43): require_once('/var/www/html/l...') #22 {main}

```
And logs from the cron container.

```
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
crond: wakeup dt=60
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
crond: wakeup dt=60
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
crond: wakeup dt=60
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
crond: wakeup dt=60
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
crond:  job: 0 php -f /var/www/html/cron.php
crond: child running /bin/bash
crond: USER www-data pid   9 cmd php -f /var/www/html/cron.php
crond: wakeup dt=10
crond: wakeup dt=50
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
crond: wakeup dt=60
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
crond: wakeup dt=60
crond: file www-data:
crond:  line php -f /var/www/html/cron.php
```

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: https://github.com/nextcloud/docker/issues/1973

## Summary
The function fails if the configured trusted proxies contain invalid characters and the underlying IpUtils will throw. But as it is used by `getRemoteAddress` which is used by logging / templating, thrown errors are not reported but silently fail with error 500.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: lib/private/AppFramework/Http/Request.php [hunk 1]
```diff
@@ -573,7 +573,13 @@ public function getId(): string {
 	 * @return boolean true if $remoteAddress matches any entry in $trustedProxies, false otherwise
 	 */
 	protected function isTrustedProxy($trustedProxies, $remoteAddress) {
-		return IpUtils::checkIp($remoteAddress, $trustedProxies);
+		try {
+			return IpUtils::checkIp($remoteAddress, $trustedProxies);
+		} catch (\Throwable) {
+			// We can not log here as the logger is using `getRemoteAddress` which uses the function, so we would have a cyclic dependency
+			// Reaching this line means `trustedProxies` is in invalid format.
+			return false;
```
Comment (nickvergessen) [inline lib/private/AppFramework/Http/Request.php:581]:
```suggestion
			// We can not log here as the logger is using `getRemoteAddress` which uses the function, so we would have a cyclic dependency
			// Reaching this line means `trustedProxies` is in invalid format.
			error_log('Nextcloud trustedProxies has malformed entries');
			return false;
```

**Review by nickvergessen — APPROVED** [review]

**Review by artonge — APPROVED** [review]
