### PR TITLE
Fix for previews not being generated sometimes

### LINKED ISSUE #36463: [Bug]: Preview for some photos not generated
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

For some of my photos, no preview in no size will be generated.

I have ~60k photos in my Nextcloud file store. For most photos, the previews are generated and they work well in every app. 

However, there is a bunch of photos where no previews are generated and they will not be displayed by content in any app -- of course they are shown as files without previews. 

The metadata of the photos is shown on the details tab, so it's not a general file access issue.

After some investigation through the logs I think I have discovered that for these photos the preview folder is not generated correctly. The log message points to folders of this structure:
`/.../nextcloud/data/appdata_xxxx/preview/284054/1536-2048-max.jpg`
while it should be of this structure:
`/.../nextcloud/data/appdata_xxxx/preview/5/6/4/0/1/4/1/0/284054/1536-2048-max.jpg`

According to my investigations, the responsible code is found in `server/lib/private/Preview/Storage/Root.php`, function `public function getFolder(string $name): ISimpleFolder`.

Why does this code fail for some files while it doesn't for all the others?!?
What can I do to resolve this issue?!?

### Steps to reproduce

1. If only I knew...
2. Use my photo collection
3. ` occ preview:generate-all`
4. Click on "broken" photo in "files" app
   (the photo itself of course is not broken, it is clean when I open it in any program on Windows or Linux -- I tried many)

### Expected behavior

* in the "files" app, a small preview icon is shown
* after clicking on the photo, a large preview is shown

Both doesn't happen.
* a placeholder icon is shown
* "The image cannot be loaded" is shown 

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
# sudo -u www-data php /mnt/data/var/www/nextcloud/occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "x.y.z",
            "x",
            "192.168.1.1"
        ],
        "overwrite.cli.url": "https:\/\/x.y.z\/nextcloud",
        "htaccess.RewriteBase": "\/nextcloud",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.3.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "filelocking.enabled": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "loglevel": 0,
        "app_install_overwrite": [
            "bookmarks_fulltextsearch",
            "quickaccesssorting",
            "ocr",
            "files_downloadactivity",
            "checksum",
            "audioplayer_editor",
            "epubreader",
            "gpxmotion",
            "previewgenerator",
            "audioplayer_sonos",
            "camerarawpreviews",
            "apporder",
            "duplicatefinder",
            "files_markdown",
            "talked",
            "video_converter",
            "extract",
            "files_ebookreader",
            "talk_simple_poll"
        ],
        "loglevel:9": "",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "preview_max_memory": 4096,
        "preview_max_filesize_image": 256,
        "jpeg_quality": "60",
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MKV",
            "OC\\Preview\\MP4",
            "OC\\Preview\\AVI"
        ],
        "theme": "",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "default_phone_region": "DE",
        "trashbin_retention_obligation": "90, auto",
        "memories.exiftool": "\/mnt\/data\/var\/www\/nextcloud\/apps\/memories\/exiftool-bin\/exiftool-amd64-glibc",
        "memories.ffmpeg_path": "\/usr\/bin\/ffmpeg",
        "memories.ffprobe_path": "\/usr\/bin\/ffprobe",
        "memories.transcoder": "\/mnt\/data\/var\/www\/nextcloud\/apps\/memories\/exiftool-bin\/go-vod-amd64",
        "memories.no_transcode": false,
        "memories.qsv": true
    }
}
```

### List of activated Apps

```shell
# sudo -u www-data php /mnt/data/var/www/nextcloud/occ app:list
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - audioplayer: 3.3.1
  - bookmarks: 12.0.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.2.2
  - camerarawpreviews: 0.8.0
  - checksum: 1.2.0
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - cloud_py_api: 0.1.4
  - comments: 1.15.0
  - contacts: 5.0.3
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.3
  - event_update_notification: 2.0.0
  - external: 5.0.0
  - extract: 1.3.5
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_downloadactivity: 1.15.0
  - files_external: 1.17.0
  - files_fulltextsearch: 25.0.0
  - files_fulltextsearch_tesseract: 25.0.0
  - files_markdown: 2.3.6
  - files_mindmap: 0.0.27
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - flow_notifications: 1.5.0
  - fulltextsearch: 25.0.0
  - fulltextsearch_elasticsearch: 25.0.0
  - gpxmotion: 0.1.0
  - gpxpod: 5.0.4
  - groupfolders: 13.1.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.2.2
  - maps: 0.2.4
  - mediadc: 0.3.3
  - memories: 4.10.3
  - metadata: 0.17.0
  - music: 1.8.1
  - news: 20.0.1
  - nextcloud_announcements: 1.14.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - passwords: 2023.1.23
  - photos: 2.0.1
  - previewgenerator: 5.1.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - quickaccesssorting: 1.1.4
  - recommendations: 1.4.0
  - related_resources: 1.0.4
  - richdocuments: 7.1.0
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - side_menu: 3.5.2
  - spreed: 15.0.3
  - support: 1.8.0
  - survey_client: 1.13.0
  - suspicious_login: 4.3.0
  - systemtags: 1.15.0
  - talked: 0.4.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - video_converter: 1.0.5
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - welcome: 1.0.6
  - workflow_ocr: 1.25.3
  - workflowengine: 2.7.0
Disabled:
  - audioplayer_editor: 0.3.0
  - audioplayer_sonos: 1.3.0
  - bookmarks_fulltextsearch: 1.2.0
  - duplicatefinder: 0.0.15
  - encryption
  - epubreader: 1.4.7
  - facerecognition: 0.9.5
  - files_antivirus: 4.0.2
  - ransomware_protection: 1.14.0
  - recognize: 3.3.6
  - twofactor_totp
  - user_ldap: 1.10.2
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"WZAyV8M8jHYZHTrLtOVG","level":3,"time":"2023-01-31T19:23:00+00:00","remoteAddr":"2a02:560:56ac:2a00:e1b0:b437:9572:eb8d","user":"aaa","app":"PHP","method":"GET","url":"/nextcloud/core/preview?fileId=284057&c=2f7c0b38ddf242dcddb5fd0e6d13be55&x=375&y=375&forceIcon=0&a=0","message":"file_put_contents(/.../nextcloud/data/appdata_xxxxx/preview/284057/1536-2048-max.jpg): Failed to open stream: No such file or directory at /.../nextcloud/lib/private/Files/Storage/Local.php#311","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0","version":"25.0.3.2","exception":{"Exception":"Error","Message":"file_put_contents(/.../nextcloud/data/appdata_xxxxx/preview/284057/1536-2048-max.jpg): Failed to open stream: No such file or directory at /.../nextcloud/lib/private/Files/Storage/Local.php#311","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/.../nextcloud/lib/private/Files/Storage/Local.php","line":311,"function":"file_put_contents"},{"file":"/.../nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":258,"function":"file_put_contents","class":"OC\\Files\\Storage\\Local","type":"->"},{"file":"/.../nextcloud/lib/private/Files/View.php","line":1179,"function":"file_put_contents","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->"},{"file":"/.../nextcloud/lib/private/Files/View.php","line":705,"function":"basicOperation","class":"OC\\Files\\View","type":"->"},{"file":"/.../nextcloud/lib/private/Files/Node/Folder.php","line":192,"function":"file_put_contents","class":"OC\\Files\\View","type":"->"},{"file":"/.../nextcloud/lib/private/Files/SimpleFS/NewSimpleFile.php","line":121,"function":"newFile","class":"OC\\Files\\Node\\Folder","type":"->"},{"file":"/.../nextcloud/lib/private/Preview/Generator.php","line":363,"function":"putContent","class":"OC\\Files\\SimpleFS\\NewSimpleFile","type":"->"},{"file":"/.../nextcloud/lib/private/Preview/Generator.php","line":162,"function":"getMaxPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/.../nextcloud/lib/private/Preview/Generator.php","line":114,"function":"generatePreviews","class":"OC\\Preview\\Generator","type":"->"},{"file":"/.../nextcloud/lib/private/PreviewManager.php","line":185,"function":"getPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/.../nextcloud/core/Controller/PreviewController.php","line":144,"function":"getPreview","class":"OC\\PreviewManager","type":"->"},{"file":"/.../nextcloud/core/Controller/PreviewController.php","line":113,"function":"fetchPreview","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/.../nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"getPreviewByFileId","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/.../nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/.../nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/.../nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/.../nextcloud/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/.../nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/.../nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"63d96a950405a"}
```

The same message formatted:

[PHP] Fehler: Error: file_put_contents(/.../nextcloud/data/appdata_xxxxx/preview/284054/1536-2048-max.jpg): Failed to open stream: No such file or directory at /.../nextcloud/lib/private/Files/Storage/Local.php#311 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError()
 1. /.../nextcloud/lib/private/Files/Storage/Local.php line 311
    file_put_contents()
 2. /.../nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php line 258
    OC\Files\Storage\Local->file_put_contents()
 3. /.../nextcloud/lib/private/Files/View.php line 1179
    OC\Files\Storage\Wrapper\Wrapper->file_put_contents()
 4. /..../nextcloud/lib/private/Files/View.php line 705
    OC\Files\View->basicOperation()
 5. /..../nextcloud/lib/private/Files/Node/Folder.php line 192
    OC\Files\View->file_put_contents()
 6. /.../nextcloud/lib/private/Files/SimpleFS/NewSimpleFile.php line 121
    OC\Files\Node\Folder->newFile()
 7. /.../nextcloud/lib/private/Preview/Generator.php line 363
    OC\Files\SimpleFS\NewSimpleFile->putContent()
 8. /.../nextcloud/lib/private/Preview/Generator.php line 162
    OC\Preview\Generator->getMaxPreview()
 9. /.../nextcloud/lib/private/Preview/Generator.php line 114
    OC\Preview\Generator->generatePreviews()
10. /.../nextcloud/lib/private/PreviewManager.php line 185
    OC\Preview\Generator->getPreview()
11. /.../nextcloud/core/Controller/PreviewController.php line 144
    OC\PreviewManager->getPreview()
12. /.../nextcloud/core/Controller/PreviewController.php line 113
    OC\Core\Controller\PreviewController->fetchPreview()
13. /.../nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 225
    OC\Core\Controller\PreviewController->getPreviewByFileId()
14. /.../nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 133
    OC\AppFramework\Http\Dispatcher->executeController()
15. /..../nextcloud/lib/private/AppFramework/App.php line 172
    OC\AppFramework\Http\Dispatcher->dispatch()
16. /.../nextcloud/lib/private/Route/Router.php line 298
    OC\AppFramework\App::main()
17. /.../nextcloud/lib/base.php line 1047
    OC\Route\Router->match()
18. /.../nextcloud/index.php line 36
    OC::handleRequest()

GET /nextcloud/core/preview?fileId=284054&c=46f47f6cce3eee1cb4d3653abfd7b9d4&x=375&y=375&forceIcon=0&a=0
from 2a02:560:56ac:2a00:e1b0:b437:9572:eb8d by thomas at 2023-01-31T19:32:33+00:00
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by akhil1508**
* Resolves: https://github.com/nextcloud/server/issues/36463

## Summary
- A lot of unnecessary `rmdir` calls are done on the preview directory

- After investigating, here are the findings to justify the fix:
  - As per https://github.com/nextcloud/server/blob/834c9a209ebef7b8d5795b53a018577fe4e534ca/lib/private/Files/FileInfo.php#L164 there is a return type of `int` or `null`
  - A `null` return by this method call over [here](https://github.com/nextcloud/server/blob/834c9a209ebef7b8d5795b53a018577fe4e534ca/lib/private/Preview/Watcher.php#L64) makes sure that an empty string is passed to `$this->appData->getFolder()`
  - As per the logic, for an empty string this will return the preview folder i.e. `appdata_*****/preview` in our case
  - There is then an attempt to delete this entire folder

- On our instance we did find logs that a delete is attempted on the entire preview folder as per https://github.com/nextcloud/server/issues/36463#issuecomment-1766963639
- Further, by logging I could confirm that `$node->getId()` is indeed null in one case leading to consistent triggering of this `rmdir`
- One case is the upload of a partial file (`.part` extension)
  - The Nextcloud clients avoid this but certain DAV clients allow to upload to nextcloud servers
  - This kind of file is ignored by [`isPartialFile`](https://github.com/nextcloud/server/blob/834c9a209ebef7b8d5795b53a018577fe4e534ca/lib/public/Files/Cache/IScanner.php#L75) 
  - In this example a file with the `.part` extension succesfully triggers an `rmdir` of the entire preview directory 

#### Stack trace of the bug
```json
{
	"reqId": "*****",
	"level": 3,
	"time": "2023-10-17T17:50:58+00:00",
	"remoteAddr": "***.***.***.***",
	"user": "*****",
	"app": "PHP",
	"method": "MOVE",
	"url": "/remote.php/dav/uploads/*****/*****/*****",
	"message": "rmdir(/var/www/data/appdata_*****/preview/1): Directory not empty at /var/www/html/lib/private/Files/Storage/Local.php#139",
	"version": "25.0.8.2",
	"exception": {
		"Exception": "Error",
		"Message": "rmdir(/var/www/data/appdata_*****/preview/1): Directory not empty at /var/www/html/lib/private/Files/Storage/Local.php#139",
		"Code": 0,
		"Trace": [
			{
				"function": "onError",
				"class": "OC\\Log\\ErrorHandler",
				"type": "::",
				"args": [
					2,
					"rmdir(/var/www/data/appdata_*****/preview/1): Directory not empty",
					"/var/www/html/lib/private/Files/Storage/Local.php",
					139
				]
			},
			{
				"file": "/var/www/html/lib/private/Files/Storage/Local.php",
				"line": 139,
				"function": "rmdir",
				"args": [
					"/var/www/data/appdata_*****/preview/1"
				]
			},
			{
				"function": "rmdir",
				"class": "OC\\Files\\Storage\\Local",
				"type": "->",
				"args": [
					"appdata_*****/preview"
				]
			},
			{
				"file": "/var/www/html/apps/files_trashbin/lib/Storage.php",
				"line": 193,
				"function": "call_user_func",
				"args": [
					[
						[
							"OC\\Files\\Storage\\LocalRootStorage"
						],
						"rmdir"
					],
					"appdata_*****/preview"
				]
			},
			{
				"file": "/var/www/html/apps/files_trashbin/lib/Storage.php",
				"line": 125,
				"function": "doDelete",
				"class": "OCA\\Files_Trashbin\\Storage",
				"type": "->",
				"args": [
					"appdata_*****/preview",
					"rmdir"
				]
			},
			{
				"file": "/var/www/html/lib/private/Files/View.php",
				"line": 1181,
				"function": "rmdir",
				"class": "OCA\\Files_Trashbin\\Storage",
				"type": "->",
				"args": [
					"appdata_*****/preview"
				]
			},
			{
				"file": "/var/www/html/lib/private/Files/View.php",
				"line": 349,
				"function": "basicOperation",
				"class": "OC\\Files\\View",
				"type": "->",
				"args": [
					"rmdir",
					"/appdata_*****/preview",
					[
						"delete"
					]
				]
			},
			{
				"file": "/var/www/html/lib/private/Files/Node/Folder.php",
				"line": 363,
				"function": "rmdir",
				"class": "OC\\Files\\View",
				"type": "->",
				"args": [
					"/appdata_*****/preview"
				]
			},
			{
				"file": "/var/www/html/lib/private/Files/SimpleFS/SimpleFolder.php",
				"line": 68,
				"function": "delete",
				"class": "OC\\Files\\Node\\Folder",
				"type": "->",
				"args": []
			},
			{
				"file": "/var/www/html/lib/private/Preview/Watcher.php",
				"line": 65,
				"function": "delete",
				"class": "OC\\Files\\SimpleFS\\SimpleFolder",
				"type": "->",
				"args": []
			},
			{
				"file": "/var/www/html/lib/private/Preview/Watcher.php",
				"line": 54,
				"function": "deleteNode",
				"class": "OC\\Preview\\Watcher",
				"type": "->",
				"args": [
					"*** sensitive parameters replaced ***"
				]
			},
			{
				"file": "/var/www/html/lib/private/Preview/WatcherConnector.php",
				"line": 63,
				"function": "postWrite",
				"class": "OC\\Preview\\Watcher",
				"type": "->",
				"args": [
					"*** sensitive parameters replaced ***"
				]
			},
			{
				"function": "OC\\Preview\\{closure}",
				"class": "OC\\Preview\\WatcherConnector",
				"type": "->",
				"args": [
					"*** sensitive parameters replaced ***"
				]
			},
			{
				"file": "/var/www/html/lib/private/Hooks/EmitterTrait.php",
				"line": 106,
				"function": "call_user_func_array",
				"args": [
					[
						"Closure"
					],
					[
						"*** sensitive parameters replaced ***"
					]
				]
			},
			{
				"file": "/var/www/html/lib/private/Hooks/PublicEmitter.php",
				"line": 40,
				"function": "emit",
				"class": "OC\\Hooks\\BasicEmitter",
				"type": "->",
				"args": [
					"\\OC\\Files",
					"postWrite",
					[
						"*** sensitive parameters replaced ***"
					]
				]
			},
			{
				"file": "/var/www/html/lib/private/Files/Node/Root.php",
				"line": 143,
				"function": "emit",
				"class": "OC\\Hooks\\PublicEmitter",
				"type": "->",
				"args": [
					"\\OC\\Files",
					"postWrite",
					[
						"*** sensitive parameters replaced ***"
					]
				]
			},
			{
				"function": "emit",
				"class": "OC\\Files\\Node\\Root",
				"type": "->",
				"args": [
					"\\OC\\Files",
					"postWrite",
					[
						"*** sensitive parameters replaced ***"
					]
				]
			},
			{
				"file": "/var/www/html/lib/private/Files/Node/LazyFolder.php",
				"line": 72,
				"function": "call_user_func_array",
				"args": [
					[
						[
							"OC\\Files\\Node\\Root"
						],
						"emit"
					],
					[
						"\\OC\\Files",
						"postWrite",
						[
							"*** sensitive parameters replaced ***"
						]
					]
				]
			},
			{
				"file": "/var/www/html/lib/private/Files/Node/LazyFolder.php",
				"line": 100,
				"function": "__call",
				"class": "OC\\Files\\Node\\LazyFolder",
				"type": "->",
				"args": [
					"emit",
					[
						"\\OC\\Files",
						"postWrite",
						[
							"*** sensitive parameters replaced ***"
						]
					]
				]
			},
			{
				"file": "/var/www/html/lib/private/Files/Node/HookConnector.php",
				"line": 117,
				"function": "emit",
				"class": "OC\\Files\\Node\\LazyFolder",
				"type": "->",
				"args": [
					"\\OC\\Files",
					"postWrite",
					[
						"*** sensitive parameters replaced ***"
					]
				]
			},
			{
				"file": "/var/www/html/lib/private/legacy/OC_Hook.php",
				"line": 106,
				"function": "postWrite",
				"class": "OC\\Files\\Node\\HookConnector",
				"type": "->",
				"args": [
					[
						"/****/*****/*****/*****.part"
					]
				]
			},
			{
				"file": "/var/www/html/apps/dav/lib/Connector/Sabre/File.php",
				"line": 473,
				"function": "emit",
				"class": "OC_Hook",
				"type": "::",
				"args": [
					"OC_Filesystem",
					"post_write",
					[
						"/****/*****/*****/*****.part"
					]
				]
			},
			{
				"file": "/var/www/html/apps/dav/lib/Connector/Sabre/File.php",
				"line": 398,
				"function": "emitPostHooks",
				"class": "OCA\\DAV\\Connector\\Sabre\\File",
				"type": "->",
				"args": [
					true
				]
			},
			{
				"file": "/var/www/html/apps/dav/lib/Connector/Sabre/Directory.php",
				"line": 151,
				"function": "put",
				"class": "OCA\\DAV\\Connector\\Sabre\\File",
				"type": "->",
				"args": [
					null
				]
			},
			{
				"file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Tree.php",
				"line": 307,
				"function": "createFile",
				"class": "OCA\\DAV\\Connector\\Sabre\\Directory",
				"type": "->",
				"args": [
					"*****",
					null
				]
			},
			{
				"file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Tree.php",
				"line": 133,
				"function": "copyNode",
				"class": "Sabre\\DAV\\Tree",
				"type": "->",
				"args": [
					[
						"OCA\\DAV\\Upload\\FutureFile"
					],
					[
						"OCA\\DAV\\Connector\\Sabre\\Directory"
					],
					"*****"
				]
			},
			{
				"file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Tree.php",
				"line": 163,
				"function": "copy",
				"class": "Sabre\\DAV\\Tree",
				"type": "->",
				"args": [
					"uploads/*****/*****/*****",
					"files/*****/****/*****/*****/*****.part"
				]
			},
			{
				"file": "/var/www/html/apps/dav/lib/Upload/ChunkingPlugin.php",
				"line": 94,
				"function": "move",
				"class": "Sabre\\DAV\\Tree",
				"type": "->",
				"args": [
					"uploads/*****/*****/*****",
					"files/*****/****/*****/*****/*****.part"
				]
			},
			{
				"file": "/var/www/html/apps/dav/lib/Upload/ChunkingPlugin.php",
				"line": 76,
				"function": "performMove",
				"class": "OCA\\DAV\\Upload\\ChunkingPlugin",
				"type": "->",
				"args": [
					"uploads/*****/*****/*****",
					"files/*****/****/*****/*****/*****.part"
				]
			},
			{
				"file": "/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
				"line": 89,
				"function": "beforeMove",
				"class": "OCA\\DAV\\Upload\\ChunkingPlugin",
				"type": "->",
				"args": [
					"uploads/*****/*****/*****",
					"files/*****/****/*****/*****/*****.part"
				]
			},
			{
				"file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
				"line": 603,
				"function": "emit",
				"class": "Sabre\\DAV\\Server",
				"type": "->",
				"args": [
					"beforeMove",
					[
						"uploads/*****/*****/*****",
						"files/*****/****/*****/*****/*****.part"
					]
				]
			},
			{
				"file": "/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
				"line": 89,
				"function": "httpMove",
				"class": "Sabre\\DAV\\CorePlugin",
				"type": "->",
				"args": [
					[
						"Sabre\\HTTP\\Request"
					],
					[
						"Sabre\\HTTP\\Response"
					]
				]
			},
			{
				"file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php",
				"line": 472,
				"function": "emit",
				"class": "Sabre\\DAV\\Server",
				"type": "->",
				"args": [
					"method:MOVE",
					[
						[
							"Sabre\\HTTP\\Request"
						],
						[
							"Sabre\\HTTP\\Response"
						]
					]
				]
			},
			{
				"file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php",
				"line": 253,
				"function": "invokeMethod",
				"class": "Sabre\\DAV\\Server",
				"type": "->",
				"args": [
					[
						"Sabre\\HTTP\\Request"
					],
					[
						"Sabre\\HTTP\\Response"
					]
				]
			},
			{
				"file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php",
				"line": 321,
				"function": "start",
				"class": "Sabre\\DAV\\Server",
				"type": "->",
				"args": []
			},
			{
				"file": "/var/www/html/apps/dav/lib/Server.php",
				"line": 360,
				"function": "exec",
				"class": "Sabre\\DAV\\Server",
				"type": "->",
				"args": []
			},
			{
				"file": "/var/www/html/apps/dav/appinfo/v2/remote.php",
				"line": 35,
				"function": "exec",
				"class": "OCA\\DAV\\Server",
				"type": "->",
				"args": []
			},
			{
				"file": "/var/www/html/remote.php",
				"line": 172,
				"args": [
					"/var/www/html/apps/dav/appinfo/v2/remote.php"
				],
				"function": "require_once"
			}
		],
		"File": "/var/www/html/lib/private/Log/ErrorHandler.php",
		"Line": 92,
		"CustomMessage": "--"
	}
}
```

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: lib/private/Preview/Watcher.php [hunk 1]
```diff
@@ -61,6 +61,9 @@ protected function deleteNode(Node $node) {
 		}
 
 		try {
+			if (is_null($node->getId())) {
```
Comment (CarlSchwan) [inline lib/private/Preview/Watcher.php:64]: I wonder if you have a backtrace for when the deleteNode is called with a node without a node id.

It might be a good idea to fix it at the source (if possible)

Comment (akhil1508) [reply lib/private/Preview/Watcher.php:64]: The stack trace was in the issue https://github.com/nextcloud/server/issues/36463#issuecomment-1766963639 

I add it to the description of this PR :+1:

Comment (akhil1508) [reply lib/private/Preview/Watcher.php:64]: Yep @tcitworld seems the hook is indeed fired from here :+1: 

@CarlSchwan @tcitworld If you could suggest what would be the best way to fix it at the source, I will do it like that. As it will take me more time to understand the core code fully and you probably already know better :)

Comment (tcitworld) [reply lib/private/Preview/Watcher.php:64]: I don't think there's a better way to do that, looks fine to me.

**Review by tcitworld — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]
Doesn't hurt!

**Review by artonge — CHANGES_REQUESTED** [review]
@come-nc IIRC, you looked into the `null` file id on some file events. Is it similar?

**Review by come-nc — APPROVED** [review]

**Comment by come-nc** [comment]
> @come-nc IIRC, you looked into the `null` file id on some file events. Is it similar?

Not really, here it’s expected for the node to have no id since it’s new, I think. In the cases I looked into it was paths outside the user directory which ended up trigerring events on null paths.

**Review by artonge — APPROVED** [review]

**Comment by SystemKeeper** [comment]
@blizzz backport? 🤔

**Comment by blizzz** [comment]
I understand it was first discovered on 25, so since then everything is affected.

**Comment by SystemKeeper** [comment]
Hm, does backporting not work if it’s from a fork?

**Comment by susnux** [comment]
> getDefaultTextColorPrimary

cc @skjnldsv

**Comment by popos123** [comment]
hi, i see that fix was implemented in version 29.0.1? becouse i have this bug on the nevest version too
image

**Comment by chrisborell** [comment]
Still occuring for me in [Nextcloud Hub 8] (29.0.2)

Screenshot 2024-06-20 at 10 09 39 am
