### PR TITLE
fix(caldav): Do not load IMipPlugin before user auth and session is c…

### LINKED ISSUE #45081: [Bug]: From Name is not setting properly in Calendar invitations created from Thunderbird
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When sending calendar invite from Thunderbird or other CalDAV supported calendars, the From Name is not correct. When sent from within nextcloud web UI, the invitation email is sent with From name being "user via nextcloud". But when the calendar event is created from Thunderbird, the invitation email is sent with From name being "nextcloud". 

I wasn't sure if this is related to this issue - https://github.com/nextcloud/server/issues/5080 because I am not asking to chagne the from email Address. I am reporting an issue with the from name. I also have a fix for this. So, I thought that I can create a new issue and try to send a PR for this fix 

### Steps to reproduce

**These steps work fine:**
1. Login to NextCloud Web UI. 
2. Open the Calendar App. 
3. Add a new event in the Calendar 
4. The invitation email sent from the server contains the From name "User via Nextcloud"

**These steps produces the issue:** 
1. Add/Connect the Nexcloud CalDAV in Thunderbird (or any email client that supports CalDAV
2. Ensure that the calendar is setup to leverage server side scheduling
3. Add a new event in the Calendar
4. The invitation email sent from the server contains the From name "Nextcloud"

### Expected behavior

The invitation email sent from the server when the calendar event is created in Thurderbird should also be "User via Nextcloud". 

### Installation method

None

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by SebastianKrupinski**
* Resolves: #45081

## Summary
Do not load IMipPlugin before user is authenticated and user session is initilized

### CODE REVIEW

File: apps/dav/lib/CalDAV/Schedule/IMipPlugin.php [hunk 1]
```diff
@@ -206,17 +203,16 @@ public function schedule(Message $iTipMessage) {
...
 		}
-
-		// Try to get the sender name from the current user id if available.
-		if ($this->userId !== null && ($senderName === null || empty(trim($senderName)))) {
-			$senderName = $this->userManager->getDisplayName($this->userId);
+		elseif (is_string($iTipMessage->senderName) && !empty(trim($iTipMessage->senderName))) {
+			$senderName = $iTipMessage->senderName;
+		}
+		else {
+			$senderName = $this->userSession->getUser()->getDisplayName();
```
Comment (tcitworld) [inline apps/dav/lib/CalDAV/Schedule/IMipPlugin.php:215]: Might be an opportunity to trim `$senderName` afterwards for all cases.

Comment (tcitworld) [inline apps/dav/lib/CalDAV/Schedule/IMipPlugin.php:215]: Even though this should be safe when registered through dav server, it might not be when used through `apps/dav/appinfo/v1/caldav.php` (very legacy stuff, but still). I'd add a check to see if `getUser()` isn't `null` (and psalm would be happy).

**Comment by SebastianKrupinski** [comment]
@tcitworld thank you for the input. I will apply your recommendations.

**Comment by tcitworld** [comment]
`OCA\DAV\Tests\unit\CalDAV\Schedule\IMipPluginTest` needs to be changed with the new constructor.

**Review by tcitworld — APPROVED** [review]
Lint fix, otherwise ✅

**Review by ChristophWurst — APPROVED** [review]

**Comment by susnux** [comment]
@SebastianKrupinski could we backport this to stable29 ?

**Comment by SebastianKrupinski** [comment]
> @SebastianKrupinski could we backport this to stable29 ?

I have no issue back porting it... Let me just ask if there is any reason we shoudn't

**Comment by ChristophWurst** [comment]
Go :shipit:

**Comment by SebastianKrupinski** [comment]
Backport for 29 https://github.com/nextcloud/server/pull/47790

Backport for 28 https://github.com/nextcloud/server/pull/47791
