### PR TITLE
Make sure the relative path is always a string

### LINKED ISSUE #14082: Resharing broken
### Steps to reproduce
1. As user 1, create folder A and share to user 2.
2. As user 2, login and create Folder B in Folder A to an external e-mail address (example: test@nextcloud.localhost) 
=> No entry is created in activity timeline
3. As user 2, delete share on Folder A/Folder B.
=> UI update and it look like it is removed, but refresh screen and it is still there.
4. Go to the database and set expire date to yesterday.
5. As user 2, go to Folder A/Folder B
=> Loading screen spins forever, not possible to see files or modify share

Step 2 generates the following log error
TypeError: Argument 2 passed to OC\\Activity\\Event::setSubject() must be of the type array, string given, called in \/var\/www\/html\/apps\/sharebymail\/lib\/ShareByMailProvider.php on line 321 at \/var\/www\/html\/lib\/private\/Activity\/Event.php#208

Step 3 and 5 generate the followng log error
TypeError: Argument 3 passed to OC\\Activity\\Event::setObject() must be of the type string, null given, called in \/var\/www\/html\/apps\/sharebymail\/lib\/ShareByMailProvider.php on line 323 at \/var\/www\/html\/lib\/private\/Activity\/Event.php#377

### Expected behaviour
After resharing a folder, it should be logged correctly and unsharing should be possible.
When a share expire, it should be removed correctly and loading screen should not spin forever.

### Actual behaviour
See steps to reproduce

### Server configuration
Fresh install using latest docker image with tag15.0.2-apache
### Client configuration
**Browser:** Chrome 71.0.3578.98

**Operating system:** Ubuntu 18.04

#### Nextcloud log (data/nextcloud.log)

nextcloud-log_1  | {"reqId":"oRtAUaI6N1KOy1ZXSsp1","level":3,"time":"2019-02-07T12:18:45+00:00","remoteAddr":"172.25.0.3","user":"user 2","app":"PHP","method":"POST","url":"\/ocs\/v2.php\/apps\/files_sharing\/api\/v1\/shares?format=json","message":"TypeError: Argument 2 passed to OC\\Activity\\Event::setSubject() must be of the type array, string given, called in \/var\/www\/html\/apps\/sharebymail\/lib\/ShareByMailProvider.php on line 321 at \/var\/www\/html\/lib\/private\/Activity\/Event.php#208","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/72.0.3626.81 Safari\/537.36","version":"15.0.2.0"}

nextcloud-log_1  | {"reqId":"5nB94sCEarWnzsdPisBp","level":3,"time":"2019-02-07T12:25:35+00:00","remoteAddr":"172.25.0.3","user":"user 2","app":"PHP","method":"DELETE","url":"\/ocs\/v2.php\/apps\/files_sharing\/api\/v1\/shares\/3?format=json","message":"TypeError: Argument 3 passed to OC\\Activity\\Event::setObject() must be of the type string, null given, called in \/var\/www\/html\/apps\/sharebymail\/lib\/ShareByMailProvider.php on line 323 at \/var\/www\/html\/lib\/private\/Activity\/Event.php#377","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/72.0.3626.81 Safari\/537.36","version":"15.0.2.0"}

### PR DESCRIPTION
**Pull request by nickvergessen**
Not sure when this is triggered, but it happens:
https://github.com/nextcloud/server/blob/9d9f6903c9e2a94f2a1b230fd35ec586b18b7a77/lib/private/Files/Node/Folder.php#L65-L76

```
Exception

TypeError: Argument 3 passed to OC\Activity\Event::setObject() must be of the type string, null given, called in /var/www/html/apps/sharebymail/lib/ShareByMailProvider.php on line 323
  File "/var/www/html/lib/private/Activity/Event.php", line 377, in setObject
    public function setObject(string $objectType, int $objectId, string $objectName = ''): IEvent {
  File "sharebymail/lib/ShareByMailProvider.php", line 323, in publishActivity
    ->setObject('files', $fileId, $filePath);
  File "sharebymail/lib/ShareByMailProvider.php", line 257, in createShareActivity
    $userFolder->getRelativePath($share->getNode()->getPath())
  File "sharebymail/lib/ShareByMailProvider.php", line 757, in delete
    $this->createShareActivity($share, 'unshare');
  File "/var/www/html/lib/private/Share20/Manager.php", line 979, in deleteShare
    $provider->delete($share);
...
(13 additional frame(s) were not displayed)
```

Fix #14082

### CODE REVIEW

**Comment by nickvergessen** [comment]
Sentry issue: [NEXTCLOUD-NP](https://sentry.rullzer.com/sentry/nextcloud/issues/1046/)

File: apps/sharebymail/lib/ShareByMailProvider.php [hunk 1]
```diff
@@ -308,13 +308,13 @@ protected function createPasswordSendActivity(IShare $share, $sharedWith, $sendT
...
-	 * @param $fileId
-	 * @param $filePath
+	 * @param string $subject
+	 * @param array $parameters
+	 * @param string $affectedUser
+	 * @param int $fileId
+	 * @param string $filePath
 	 */
-	protected function publishActivity($subject, $parameters, $affectedUser, $fileId, $filePath) {
+	protected function publishActivity(string $subject, array $parameters, string $affectedUser, int $fileId, string $filePath) {
```
Comment (danielkesselberg) [inline apps/sharebymail/lib/ShareByMailProvider.php]: https://github.com/nextcloud/server/blob/8db2f3ec3adddb0a293bfb8c102561c08270d710/apps/sharebymail/lib/ShareByMailProvider.php#L267 :boom:

Comment (nickvergessen) [reply apps/sharebymail/lib/ShareByMailProvider.php]: Fixed

**Review by rullzer — APPROVED** [review]
makes sense.

**Review by MorrisJobke — APPROVED** [review]
Tested and still works 👍
