### PR TITLE
Unlock failed cron jobs and set a high "last_checked" value to avoid continous re-check

### LINKED ISSUE #9992: Cronjob blocking update (forever)
Both @skjnldsv and me had this issue earlier, when an update gave us this message:

> Waiting for cron to finish (check again in 5 seconds)

And that just kept coming again and again. Setting maintenance mode to false also does not work.

It can be fixed using `UPDATE oc_jobs SET reserved_at=0;` (thanks @nickvergessen), but should probably not happen.

cc @MorrisJobke @nickvergessen

### PR DESCRIPTION
**Pull request by MorrisJobke**
* fixes issue where cronjobs of a not-loaded app are marked as "still running" because there is a "reserved_at" value stored
* fixes #9992
* [x] add a repair step that sets the value of all jobs to 0 during upgrade to not run into this issue in the future for fast upgrades

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I also added another check in the updater to only wait for cron if the upgrade is from a version after this commit to have the fixed cron jobs already included. It could still cause trouble if there is this cronjob entry, then an upgrade to 14.0.0.7 happens and then directly the next upgrade happens without cron.php to execute to clean up the reserved jobs. Maybe I will add another repair step to reset the "reserved_at" entries.

File: lib/private/BackgroundJob/JobList.php [hunk 1]
```diff
@@ -214,6 +215,14 @@ public function getNext() {
 			$job = $this->buildJob($row);
 
 			if ($job === null) {
+				// set the last_checked to 12h in the future to not check failing jobs all over again
```
Comment (nickvergessen) [inline lib/private/BackgroundJob/JobList.php]: This is basically a non-exiting job or one of a disabled app, not a "failing job"

Comment (nickvergessen) [reply lib/private/BackgroundJob/JobList.php]: If `execute()` fails, it is still blocked for ever

**Review by jancborchardt — APPROVED** [review]
Fixes the update issue https://github.com/nextcloud/server/issues/9992 for me

**Comment by tobiasKaminsky** [comment]
I ran into this, and with this PR, I had to manually set maintenance to false and reload the upgrade process.
Now it works fine :+1: 
(thanks @rullzer for pointing me here)

**Comment by MorrisJobke** [comment]
Ready for review. I added a repair step and it worked over here.

**Review by rullzer — APPROVED** [review]
Does the trick for me.
I vote to merge as it at least improves the situation.

**Comment by MorrisJobke** [comment]
I just updated the version again as master had it already and added two times:

```
* @suppress SqlInjectionChecker
```

because there were two false positives.
