### PR TITLE
Try to delete the cypress folder of the viewer app

### LINKED ISSUE #16229: Failed Code Integrity because of EXTRA_FILE after Update from 16.0.1 to 16.0.2
Yesterday, I update my Nextcloud 15 to Nextcloud 16.0.1 and everything looked fine (just for context). Today, I saw the new 16.0.2 version and started the update and it finished without any problems `\OC\Updater::updateEnd: Update successful`.

But after the update, I went to the settings page and found that the NC was complaining about failed code integrity checks (see below). In addition, I noticed that I can't open the Apps list (maybe related, maybe a separate issue).

### Steps to reproduce
I didn't try to reproduce it, but I would guess: Update from 16.0.1.1 to 16.0.2.1

### Expected behaviour
The code integrity check should pass.

### Actual behaviour
The code integrity check fails.

### Server configuration

**Operating system:** Arch Linux 5.1.15

**Web server:** Apache

**Database:** SQLite

**PHP version:** 7.3.7

**Nextcloud version:** 16.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from 16.0.1

**Where did you install Nextcloud from:** Update via Web-Interface

**Signing status:**
<details>
<summary>Signing status</summary>

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- viewer
	- EXTRA_FILE
		- cypress/start.sh
		- cypress/stop.sh
		- cypress/fixtures/video.webm
		- cypress/fixtures/image.png
		- cypress/fixtures/image.svg
		- cypress/fixtures/video2.mp4
		- cypress/fixtures/image1.jpg
		- cypress/fixtures/image3.jpg
		- cypress/fixtures/image4.jpg
		- cypress/fixtures/image.gif
		- cypress/fixtures/video1.mp4
		- cypress/fixtures/image-small.png
		- cypress/fixtures/image2.jpg
		- cypress/fixtures/image.bmp
		- cypress/fixtures/video.mkv
		- cypress/fixtures/video.ogv
		- cypress/plugins/index.js
		- cypress/support/commands.js
		- cypress/support/index.js
		- cypress/utils/index.js
		- cypress/integration/image-small.png.spec.js
		- cypress/integration/video.ogv.spec.js
		- cypress/integration/video.mp4.spec.js
		- cypress/integration/image.svg.spec.js
		- cypress/integration/files.spec.js
		- cypress/integration/videos.spec.js
		- cypress/integration/images.spec.js
		- cypress/integration/image.png.spec.js
		- cypress/integration/video.webm.spec.js
		- cypress/integration/video.mkv.spec.js
		- cypress/integration/image.gif.spec.js
		- cypress.json

Raw output
==========
Array
(
    [viewer] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [cypress/start.sh] => Array
                        (
                            [expected] => 
                            [current] => 8692dc0c8489fc602d55da7fdb5a858d9be8bcfb878b21457ea80443cd6b8bf9239d7453e96bc1f266f8a5165918fff44e4df11d36d8d349b31053f05bc94ab8
                        )

                    [cypress/stop.sh] => Array
                        (
                            [expected] => 
                            [current] => ee4700342e52524f88da50a64426aeea94aa5857ac446ddae9015e35e8f1d92fd7e7baa5a4f80235bb149bb9c2d82903534d73ee03e75066f4cbf150141d27f0
                        )

                    [cypress/fixtures/video.webm] => Array
                        (
                            [expected] => 
                            [current] => 3ef5faf52f935d5e322227e2f5907b156816f8c5a254a785a8d989852e2694cf4510e4d2d6c046d9b31900583ff44cbd1fc722de5b30ec134e300f3d9e685bfb
                        )

                    [cypress/fixtures/image.png] => Array
                        (
                            [expected] => 
                            [current] => 50e54358eb0473f9894f54cffcf10a62321321d4db08d62425f6947149d5afde2d080d089fbe94c12d94e23c193e34393169c28f914f22004e61d3cd91fea448
                        )

                    [cypress/fixtures/image.svg] => Array
                        (
                            [expected] => 
                            [current] => 75d274e7440faee5caa412ed3f1be20b5684c9c5cd19b60cc1524607a32770f8c44ddad9926fc6ac56134936e7b6721d9152f17ec06784e7cfd02c16600c8898
                        )

                    [cypress/fixtures/video2.mp4] => Array
                        (
                            [expected] => 
                            [current] => 3ff782d0f1e29f573a7ba22e13007fc0927d5fec4845e77b9c6fe03f67de90b9133a6d145569f990080bee6c47a0a9939118afb113afbef848e3466a3bbb14c0
                        )

                    [cypress/fixtures/image1.jpg] => Array
                        (
                            [expected] => 
                            [current] => c219f5c35cf5f2ecbc1e2121537ffc1f9c8e063adeaad2fb820393704250c53c6b4ff388e294f4909c501e10688c691dc7257130600de230984f1f4110e78a99
                        )

                    [cypress/fixtures/image3.jpg] => Array
                        (
                            [expected] => 
                            [current] => c112fc23235a414a2f86435f3c9cace73fca507782043c7518e0b3c5c34e190ba0709622c0efd34c126753bc5d960fe1a78bec0de6a3ec83a3d5626b5f0a408d
                        )

                    [cypress/fixtures/image4.jpg] => Array
                        (
                            [expected] => 
                            [current] => 033ee655d82249a110a237c1519fa145afc7383a0f27a676b53933949795590be251b83c799ad2700847c8ae6cf85f331a21617f5117a51cc38b8c6c2425299c
                        )

                    [cypress/fixtures/image.gif] => Array
                        (
                            [expected] => 
                            [current] => 4b8fc05bc9b8546c77fc06577a6f7d771b2f89143eede005c7f240a154c2283e3cd68d84a8afbd61b9b2ff0b3d45a2965ed7495b8a0d73af233b80cc82dc61e2
                        )

                    [cypress/fixtures/video1.mp4] => Array
                        (
                            [expected] => 
                            [current] => 65e4b16ed459352fbce164a8d65ec8167dd4fafa4ebb8d00d2f2d8742f989afa09f4bb46ec51237ad10f346ba73e0415be8229be1dc929afb3dab8bb646ba0a1
                        )

                    [cypress/fixtures/image-small.png] => Array
                        (
                            [expected] => 
                            [current] => 6a6e063dd89639fe22aec424a83c940ad6f724bb1582c779548e6d548790b822d067cb5b339b60ce520f9ce6ba2a6e5f10a0c079428035b0ff970cf65bb98064
                        )

                    [cypress/fixtures/image2.jpg] => Array
                        (
                            [expected] => 
                            [current] => 81041d26e4f61d8b926e944cc457ba800b3062e2b835f2dc9286532da0c876ee0945193c54a1295aeb7bd212e55f842b67aed9b4e4c9a39630b0dc0c7b1ad0ce
                        )

                    [cypress/fixtures/image.bmp] => Array
                        (
                            [expected] => 
                            [current] => c9810c4167a43a3ddf16fc5d49cf8f6875c45dfb3bbb283b06d7345b4f9d97cf3633e3799216065e1db01291277332ab27b3acdd16285f2e81ed6a38fed57816
                        )

                    [cypress/fixtures/video.mkv] => Array
                        (
                            [expected] => 
                            [current] => 68c78a1437041453c713d447c0ac6aa466666a66369d98bde4b4d7ceb3f6fc1f683890caf5f6d5c500de1ca2a452697baa9b70e721ce4f9b39428a8a6e47c640
                        )

                    [cypress/fixtures/video.ogv] => Array
                        (
                            [expected] => 
                            [current] => e95c985cdaea0fd63ee1268ffa15feda87168c98e5a7114623b75bfd8d9782f51f77e16908975424285bd39aa52fae884fdd5a6625cd3a9c78a4cf8b2a9f3183
                        )

                    [cypress/plugins/index.js] => Array
                        (
                            [expected] => 
                            [current] => 03eb6d2dcce575ca0c1597700f6ad97014f96cb148785cbe948e2930588ec78aa234b8698c40883a318c65f8a88eb836093b85dada99ed1361dce3e4b050cb47
                        )

                    [cypress/support/commands.js] => Array
                        (
                            [expected] => 
                            [current] => 1cca271b4c349eefcc44450e439f17d53f84f2aa479291aceb14c2c9a69ad614d38bdd01611cbb1e7002493c84a934d548dfc5357808b61695ceb2cad7e28501
                        )

                    [cypress/support/index.js] => Array
                        (
                            [expected] => 
                            [current] => 782a5ca99cd32314d8d754ede1d867f95ba9aeb4f38014a94a04cb0d2e7ff6eab849a557e6022d16b780fe1728dc3e4db9157323b912a1892523e127847875fb
                        )

                    [cypress/utils/index.js] => Array
                        (
                            [expected] => 
                            [current] => 61e3b0405c0411708981a45154e13f124cc5bfc431a25d92580ae4ba5f276026d6df883702db3adc827a9dabfbe6bf377ceea5a2a7bcdc939ed2329cad2f8d33
                        )

                    [cypress/integration/image-small.png.spec.js] => Array
                        (
                            [expected] => 
                            [current] => daa93e864599bfd53fac612981afec3226cb189ab126a4b7e68ebed66905d409a940eeb2e8df0fd5b569da72db2cc476de03847a4bf429515187e88a81959c74
                        )

                    [cypress/integration/video.ogv.spec.js] => Array
                        (
                            [expected] => 
                            [current] => efbd8643c7977b5fd89265a0195c0fc856e9c97eccd6c7a71c66130463c2dd1c3156ffd02b7368af9addc2ec25fe9bd9d28f98c914eaffa9f5c24a7e17567bf3
                        )

                    [cypress/integration/video.mp4.spec.js] => Array
                        (
                            [expected] => 
                            [current] => b1961b28616b8abff2b634b81e74b39e045f2f5852c2c4276c75bb67e3c97e0a5396ae27a2f23e65ac2d7b12ef0d13125c88c53175391514c8a932e5d1a658d4
                        )

                    [cypress/integration/image.svg.spec.js] => Array
                        (
                            [expected] => 
                            [current] => cec04f1e2c153bbed680684ac78694f58ea3ded6e84af2b8f601b59e582c2379459795e484f7ab3b4b7f7a8facdd62811a3fa930d5517bc39aff6592d212b8c6
                        )

                    [cypress/integration/files.spec.js] => Array
                        (
                            [expected] => 
                            [current] => 7c295f26d37e0e2db83bfbd9e58beed08fe7da5b731e5944aefab568396d9bb328bb59d0c1b86c919cb8dd445bba37f77f83a8381c54ac8879c3d2b9c2798cd6
                        )

                    [cypress/integration/videos.spec.js] => Array
                        (
                            [expected] => 
                            [current] => f9de7731b4430677b0a5739ecfdf73ebad7d6912c7f468177846e09e5b75cfd962b576b3e31d7546c5ff055e2caf49311bce81c7a0fd407b262f71050366d076
                        )

                    [cypress/integration/images.spec.js] => Array
                        (
                            [expected] => 
                            [current] => 36df65eda12222d85676416c7f8771652c05bc05108d033bcd2b65527112cfddfb2df9137fb9e9f6253a5bebb76c9051b1bbe5ca31c60735680b8960ccc9c4ba
                        )

                    [cypress/integration/image.png.spec.js] => Array
                        (
                            [expected] => 
                            [current] => 475d783a88adfe90a7f2703b53edc406380979d1314c9f8726ebfb6378b0c6b6a645c78f591499b66bfb624e20e228f6fbb123f6daa5457223dd1be5856ad9fe
                        )

                    [cypress/integration/video.webm.spec.js] => Array
                        (
                            [expected] => 
                            [current] => a80b0c73c088ed9b38f3d611542b266418ec5ad1dd2688908ebe25488769327713e568b8b33526b1367695ab49211406251e49ed00fe73a06d66cf04624bef97
                        )

                    [cypress/integration/video.mkv.spec.js] => Array
                        (
                            [expected] => 
                            [current] => 554f3a94dc76c500244b5f55b1b1e7d3cb487932284ad908e7ebc0139d373cd5de9bde697bf54205d049e5174a85a888e59430b3b795b2db7c9f1f2f0c0de001
                        )

                    [cypress/integration/image.gif.spec.js] => Array
                        (
                            [expected] => 
                            [current] => aa460a5c24d921926a74bb18ac241103e7cfb0268843ae02fac2fc84dcf4e4c24e2060f020d7899e26fe39135a846f30c2859050ec75bd64dde87faeea344b14
                        )

                    [cypress.json] => Array
                        (
                            [expected] => 
                            [current] => bf773ddaccd4c55ed0653dfe26d462c7b459c894a21537dcbc153f02d676b0d894720354d842190ec2c4b9421b1cbfd1b772407c1c784577caf85abe556ecb54
                        )

                )

        )

)
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.2.0
  - admin_audit: 1.6.0
  - bookmarks: 1.0.6
  - bruteforcesettings: 1.3.0
  - calendar: 1.7.0
  - circles: 0.17.4
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.3
  - dav: 1.9.2
  - deck: 0.6.4
  - drawio: 0.9.3
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_markdown: 2.0.6
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - mail: 0.15.1
  - nextcloud_announcements: 1.5.0
  - notes: 3.0.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - polls: 0.10.2
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - spreed: 6.0.2
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - tasks: 0.11.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - activity
  - encryption
  - files_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite3",
        "version": "16.0.2.1",
        "installed": true,
        "lastupdatedat": "1337713330.9218",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "maintenance": false,
        "forcessl": false,
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "mail_smtpmode": "smtp",
        "loglevel": 3,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "appstore.experimental.enabled": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Operating system:** Arch Linux

#### Web server error log
<details>
<summary>Web server error log</summary>

```
[Thu Jul 04 06:33:30.490343 2019] [php7:error] [pid 4214] [client 129.204.233.215:41272] script '/srv/http/elrekt.php' not found or unable to stat
[Thu Jul 04 06:33:30.945654 2019] [php7:error] [pid 4184] [client 129.204.233.215:41773] script '/srv/http/index.php' not found or unable to stat
[Thu Jul 04 12:26:28.560345 2019] [authz_core:error] [pid 3565] [client 192.168.0.142:37136] AH01630: client denied by server configuration: /srv/http/owncloud/data/.ocdata
[Thu Jul 04 12:28:54.777594 2019] [authz_core:error] [pid 3615] [client 192.168.0.142:37400] AH01630: client denied by server configuration: /srv/http/owncloud/data/.ocdata
[Thu Jul 04 12:31:31.597134 2019] [authz_core:error] [pid 4690] [client 192.168.0.142:37790] AH01630: client denied by server configuration: /srv/http/owncloud/data/.ocdata
[Thu Jul 04 12:34:28.845725 2019] [authz_core:error] [pid 3375] [client 192.168.0.142:38134] AH01630: client denied by server configuration: /srv/http/owncloud/data/.ocdata
[Thu Jul 04 12:35:06.646933 2019] [authz_core:error] [pid 4633] [client 192.168.0.142:38254] AH01630: client denied by server configuration: /srv/http/owncloud/data/.ocdata
[Thu Jul 04 12:37:00.659473 2019] [authz_core:error] [pid 4898] [client 192.168.0.142:38454] AH01630: client denied by server configuration: /srv/http/owncloud/data/.ocdata
[Thu Jul 04 12:50:07.286895 2019] [authz_core:error] [pid 5143] [client 192.168.0.142:40142] AH01630: client denied by server configuration: /srv/http/owncloud/data/.ocdata
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

Today only:

```
{"reqId":"WS41A3hxgrED7Fi6yNIk","level":3,"time":"2019-07-04T10:30:02+00:00","remoteAddr":"192.168.0.142","user":"--","app":"jsresourceloader","method":"GET","url":"\/owncloud\/","message":"Could not find resource js\/config.js to load","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:05+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::maintenanceEnabled: Turned on maintenance mode","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":0,"time":"2019-07-04T10:30:05+00:00","remoteAddr":"192.168.0.142","user":"--","app":"core","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"starting upgrade from 16.0.1.1 to 16.0.2.1","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:05+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::step: Repair step: Repair MySQL collation","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:05+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::info: Repair info: Not a mysql database -> nothing to do","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:05+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::step: Repair step: Repair SQLite autoincrement","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:20+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::step: Repair step: Copy data from accounts table when migrating from ownCloud","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:20+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::step: Repair step: Drop account terms table when migrating from ownCloud","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:20+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::dbUpgradeBefore: Updating database schema","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:21+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::dbUpgrade: Updated database","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:21+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"accessibility\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"accessibility\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"admin_audit\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"admin_audit\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"bookmarks\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"bookmarks\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"bruteforcesettings\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"bruteforcesettings\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"calendar\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"calendar\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"circles\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"circles\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"cloud_federation_api\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"cloud_federation_api\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"comments\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"comments\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"contacts\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"contacts\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"dav\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"dav\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"deck\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"deck\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"drawio\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"drawio\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"federatedfilesharing\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"federatedfilesharing\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"federation\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"federation\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"files\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"files\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"files_markdown\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"files_markdown\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"files_pdfviewer\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"files_pdfviewer\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"files_rightclick\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"files_rightclick\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"files_sharing\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"files_sharing\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"files_texteditor\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"files_texteditor\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"files_trashbin\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"files_trashbin\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"files_versions\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"files_versions\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"files_videoplayer\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"files_videoplayer\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"firstrunwizard\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"firstrunwizard\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"gallery\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"gallery\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"logreader\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"logreader\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"lookup_server_connector\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"lookup_server_connector\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"mail\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"mail\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"nextcloud_announcements\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"nextcloud_announcements\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"notes\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"notes\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"notifications\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"notifications\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"oauth2\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"oauth2\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"password_policy\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"password_policy\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"polls\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"polls\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"privacy\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"privacy\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"provisioning_api\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"provisioning_api\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"recommendations\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"recommendations\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"serverinfo\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"serverinfo\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"sharebymail\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"sharebymail\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"spreed\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"spreed\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"support\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"support\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"survey_client\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"survey_client\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"systemtags\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"systemtags\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"tasks\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"tasks\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"theming\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"theming\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"twofactor_backupcodes\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"twofactor_backupcodes\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"updatenotification\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"updatenotification\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"viewer\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"viewer\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"workflowengine\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"workflowengine\" in appstore","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::step: Repair step: Repair MySQL collation","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::info: Repair info: Not a mysql database -> nothing to do","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::step: Repair step: Repair mime types","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::step: Repair step: Clean tags and favorites","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::info: Repair info: 0 tags of deleted users have been removed.","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::info: Repair info: 0 tags for delete files have been removed.","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::info: Repair info: 0 tag entries for deleted tags have been removed.","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::info: Repair info: 0 tags with no entries have been removed.","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::step: Repair step: Repair invalid shares","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::step: Repair step: Remove shares of a users root folder","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::step: Repair step: Move .step file of updater to backup location","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::info: Repair info: .step file exists","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::info: Repair info: .step-previous-update removed","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::info: Repair info: .step file moved to .step-previous-update","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::step: Repair step: Fix potential broken mount points","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::info: Repair info: No mounts updated","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::step: Repair step: Repair invalid paths in file cache","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::step: Repair step: Add log rotate job","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::step: Repair step: Clear frontend caches","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::info: Repair info: Image cache cleared","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:22+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::info: Repair info: SCSS cache cleared","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:23+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::info: Repair info: JS cache cleared","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:23+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::step: Repair step: Clear every generated avatar on major updates","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:23+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::step: Repair step: Add preview background cleanup job","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:23+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::step: Repair step: Queue a one-time job to cleanup old backups of the updater","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:23+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::step: Repair step: Repair pending cron jobs","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:23+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::info: Repair info: No need to repair pending cron jobs.","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:23+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::step: Repair step: Extract the vcard uid and store it in the db","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:23+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::step: Repair step: Cleanup invalid photocache files for carddav","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:23+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::step: Repair step: Add background job to cleanup login flow v2 tokens","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:23+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::step: Repair step: Remove potentially over exposing share links","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:23+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Repair::info: Repair info: No need to remove link shares.","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:23+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::startCheckCodeIntegrity: Starting code integrity check...","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:34+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::finishedCheckCodeIntegrity: Finished code integrity check","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:34+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::updateEnd: Update successful","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.2.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:34+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::maintenanceDisabled: Turned off maintenance mode","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.2.1"}
{"reqId":"C23BCotZmQ0pb0cpQwOX","level":1,"time":"2019-07-04T10:30:34+00:00","remoteAddr":"192.168.0.142","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=MrpvdURkIKAKwl9Bq57b2Ayu87k0CwMNoAV2Y1CP9o8%3D%3AU84fLAUpZuVLtC0IgK2LkyPcmeNNRHdPmVdFNhO4sOY%3D","message":"\\OC\\Updater::resetLogLevel: Reset log level to Error(3)","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.2.1"}
```
</details>

### PR DESCRIPTION
**Pull request by MorrisJobke**
Fixes #16229

### CODE REVIEW

**Comment by MorrisJobke** [comment]
As proposed by @jospoortvliet

**Comment by MorrisJobke** [comment]
I tested this on Nextcloud 16.0.2 and ran the `occ maintenance:repair` manually (which is triggered during the upgrade as well) and it worked.

File: lib/private/Repair/NC16/CleanupCypressFiles.php [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+ * This repair step removes "cypress" files and folder created by viewer app in 16.0.1
+ *
+ * See https://github.com/nextcloud/server/issues/16229 for more details.
+ */
+class CleanupCypressFiles implements IRepairStep {
+
+	/** @var Checker $checker */
+	private $checker;
+
+	private $pathToViewerApp = __DIR__ . '/../../../../apps/viewer';
```
Comment (nickvergessen) [inline lib/private/Repair/NC16/CleanupCypressFiles.php]: Can't we get it from the app manager? in case it was moved?

Comment (MorrisJobke) [reply lib/private/Repair/NC16/CleanupCypressFiles.php]: I do a `file_exists` anyways and it should only matter if the app was installed via the release package and not updated via appstore. So this is just the easiest way without the problem of dealing with multiple app directories.

**Comment by kesselb** [comment]
I would prefer `RemoveCypressFiles`

File: lib/private/Repair/NC16/CleanupCypressFiles.php [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+	public function getName(): string {
+		return 'Cleanup cypress files from viewer app';
+	}
+
+	public function __construct(Checker $checker) {
+		$this->checker = $checker;
+	}
+
+	public function run(IOutput $output): void {
+		$file = $this->pathToViewerApp . '/cypress.json';
```
Comment (kesselb) [inline lib/private/Repair/NC16/CleanupCypressFiles.php]: https://github.com/nextcloud/server/blob/11a27b247fefb8739ecfcaf5ba5a3c70e364197d/lib/private/Repair/NC16/CleanupCardDAVPhotoCache.php#L91-L103

I guess you want to release it today? You could add something like this if there is some time left.

**Comment by juliushaertl** [comment]
I think this should actually not be required. From a look at the updater code it seems that it only deletes files from apps listed in shipped.json.
https://github.com/nextcloud/updater/blob/master/lib/Updater.php#L787-L796 

For viewer that was not the case in 16.0.1 which is why the update to 16.0.2 doesn't delete those files. (See https://github.com/nextcloud/server/pull/15592/files) 

This means that if you have installed the RC of 16.0.2 and update to 16.0.2 the error will be gone, which might explain that some of us could not reproduce the issue with the release.

But I'm also fine to have this in, just to be sure :wink:

**Comment by juliushaertl** [comment]
Makes of course still sense to have this cleanup job, in case someone goes from 16.0.1 to 16.0.3 then :+1:

File: lib/private/Repair/NC16/CleanupCypressFiles.php (hunk 2 above)
Comment (MorrisJobke) [reply lib/private/Repair/NC16/CleanupCypressFiles.php]: It was there and the check for the actual outcome is far better IMO than the "lets assume some version number and check for that". And here the check for the outcome was pretty straight forward so I reduced the code to be better readable by just put it where it is checked.

**Comment by MorrisJobke** [comment]
> For viewer that was not the case in 16.0.1 which is why the update to 16.0.2 doesn't delete those files. (See https://github.com/nextcloud/server/pull/15592/files)
> 
> This means that if you have installed the RC of 16.0.2 and update to 16.0.2 the error will be gone, which might explain that some of us could not reproduce the issue with the release.

The argument by @jospoortvliet was that we should try to fix this proactive instead of assuming that it will resolve in the future by itself. ;) And as this is straight forward I'm fine with the proactive repair step.

**Comment by MorrisJobke** [comment]
Done ✅

**Comment by MorrisJobke** [comment]
> I would prefer `RemoveCypressFiles`

Done ✅

File: lib/private/Repair/NC16/CleanupCypressFiles.php (hunk 2 above)
Comment (kesselb) [reply lib/private/Repair/NC16/CleanupCypressFiles.php]: I'm okay with that. Would it make sense to mark this as deprecated to remove it in the future?

Comment (MorrisJobke) [reply lib/private/Repair/NC16/CleanupCypressFiles.php]: Let me add this.

Comment (MorrisJobke) [reply lib/private/Repair/NC16/CleanupCypressFiles.php]: In general that was also the idea of putting those repair steps in the NC16 folder for example. Because you know when they were added.

Comment (MorrisJobke) [reply lib/private/Repair/NC16/CleanupCypressFiles.php]: I also did some cleanup in https://github.com/nextcloud/server/pull/16292

**Comment by jospoortvliet** [comment]
thanks, good work :+1:

**Review by skjnldsv — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]
