### PR TITLE
fix(theming): use IAppConfig for all ThemingDefaults

### LINKED ISSUE #56016: [Bug]: Can't set disable-user-theming with occ in V32
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Setting the theming option with

`occ theming:config disable-user-theming 1` (same with on, true,  yes, etc.) 

results in a `string` type in Database:

```
+---------+----------------------+-------------+------+------+
| appid   | configkey            | configvalue | type | lazy |
+---------+----------------------+-------------+------+------+
| theming | disable-user-theming | 1           |    4 |    0 |
+---------+----------------------+-------------+------+------+
```

which will fail on next Request with Exception `"message":"conflict with value type from database"` in nextcloud.log giving an `Internal Server Error` in Browser.

Reason seems, that function `function getValueBool` in `lib/private/AppConfig.php` expects type `32` in Database. Unfortunately the command `occ theming:config` lacks an option to explicitly set type `bool`.  

### Steps to reproduce

1. Fresh install
2. Set option `disable-user-theming' to true (or false or anything else) using command occ

### Expected behavior

Same as having set the option via UI, which results in database entry

```
+---------+----------------------+-------------+------+------+
| appid   | configkey            | configvalue | type | lazy |
+---------+----------------------+-------------+------+------+
| theming | disable-user-theming | 1           |   32 |    0 |
+---------+----------------------+-------------+------+------+
```

### Nextcloud Server version

32

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json
n/a
```

### List of activated Apps

```shell
n/a
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```json
{"reqId":"B0bqY3ba6wrih6cGhHRd","level":3,"time":"2025-10-26T15:36:35+00:00","remoteAddr":"172.18.0.1","user":"ncadmin","app":"core","method":"GET","url":"/apps/files/","message":"conflict with value type from database","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:144.0) Gecko/20100101 Firefox/144.0","version":"32.0.1.2","exception":{"Exception":"OCP\\Exceptions\\AppConfigTypeConflictException","Message":"conflict with value type from database","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppConfig.php","line":427,"function":"getTypedValue","class":"OC\\AppConfig","type":"->","args":["theming","disable-user-theming","false",false,32]},{"file":"/var/www/html/apps/theming/lib/ThemingDefaults.php","line":526,"function":"getValueBool","class":"OC\\AppConfig","type":"->","args":["theming","disable-user-theming"]},{"file":"/var/www/html/apps/theming/lib/ThemingDefaults.php","line":180,"function":"isUserThemingDisabled","class":"OCA\\Theming\\ThemingDefaults","type":"->","args":[]},{"file":"/var/www/html/lib/public/Defaults.php","line":182,"function":"getColorPrimary","class":"OCA\\Theming\\ThemingDefaults","type":"->","args":[]},{"file":"/var/www/html/core/templates/layout.guest.php","line":29,"function":"getColorPrimary","class":"OCP\\Defaults","type":"->","args":[]},{"file":"/var/www/html/lib/private/Template/Base.php","line":140,"args":["/var/www/html/core/templates/layout.guest.php"],"function":"include"},{"file":"/var/www/html/lib/private/Template/Base.php","line":113,"function":"load","class":"OC\\Template\\Base","type":"->","args":["/var/www/html/lib/private/App/../../../core/templates/layout.guest.php",null]},{"file":"/var/www/html/lib/private/Template/Template.php","line":112,"function":"fetchPage","class":"OC\\Template\\Base","type":"->","args":[null]},{"file":"/var/www/html/lib/private/Template/Template.php","line":142,"function":"fetchPage","class":"OC\\Template\\Template","type":"->","args":[null]},{"file":"/var/www/html/lib/private/Template/Base.php","line":103,"function":"fetchPage","class":"OC\\Template\\Template","type":"->","args":[]},{"file":"/var/www/html/lib/private/Template/TemplateManager.php","line":129,"function":"printPage","class":"OC\\Template\\Base","type":"->","args":[]},{"file":"/var/www/html/index.php","line":90,"function":"printExceptionErrorPage","class":"OC\\Template\\TemplateManager","type":"->","args":[{"__class__":"OCP\\Exceptions\\AppConfigTypeConflictException"},500]}],"File":"/var/www/html/lib/private/AppConfig.php","Line":505,"message":"conflict with value type from database","exception":{},"CustomMessage":"conflict with value type from database"}}
```

### Additional info

n/a

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: https://github.com/nextcloud/server/issues/56016

## Summary
Fixes issues where values have the wrong type.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)
- [x] [Labels added](https://github.com/nextcloud/server/labels) where applicable (ex: bug/enhancement, `3. to review`, feature component)
- [x] [Milestone added](https://github.com/nextcloud/server/milestones) for target branch/version (ex: 32.x for `stable32`)

### CODE REVIEW

**Review by artonge — APPROVED** [review]
Might be a good opportunity to also use [`lib/private/AppFramework/Services/AppConfig.php`](https://github.com/nextcloud/server/blob/8dc64d794c133c7ed58e51f94a901c189cea2591/lib/private/AppFramework/Services/AppConfig.php#L18) which pre-fills the app name.

**Comment by susnux** [comment]
@artonge done

**Review by CarlSchwan — APPROVED** [review]

**Comment by oleksandr-nc** [comment]
@susnux can we backport this to Nextcloud 31?

File: apps/theming/lib/ThemingDefaults.php [hunk 1]
```diff
@@ -433,7 +431,18 @@ public function increaseCacheBuster(): void {
 	 * @param string $value
 	 */
 	public function set($setting, $value): void {
-		$this->appConfig->setValueString('theming', $setting, $value);
+		switch ($value) {
```
Comment (icewind1991) [inline apps/theming/lib/ThemingDefaults.php:434]: 🙈 https://github.com/nextcloud/server/pull/56626

**Comment by 1358** [comment]
It is kinda unlucky, that this has been backported, as it breaks legacy domain based theming (`domains.config.php` and the `themes-directory` (and the `defaults.php` there) **between 32.0.1 and 32.0.2.** while the theming app itself is still not capable handling this itself and breaks workarounds.

e.g. #27433, #46172, #23545

**Comment by susnux** [comment]
@1358 why should it be broken? This only migrates from IConfig to IAppConfig. `OC_Defaults` and `OCP\Defaults` are not touched.
