### PR TITLE
Check expiry enforcement for all share types

### LINKED ISSUE #40982: [Bug]:  share-expiration-calendar broken
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

In Nextcloud 27.1.2.1, the share-options are broken. If you share something via link and update the settings afterward,
the calendar to define a share-time doesn't work anymore, you can navigate through it but it doesn't accept any date except the next two days. Furthermore you can't set a date by typing, only thing that works is to use arrow-keys.

Bildschirmfoto 2023-10-19 um 15 29 35

I can't find anything in the logs.

### Steps to reproduce

1. Create a folder/file
2. share it (via link/person/mail)
3. Set an expiry date (or try to)

### Expected behavior

It should be possible to choose any date in the future.

### Installation method

Community Docker image

### Nextcloud Server version

27.1.2.1

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### LINKED ISSUE #41075: [Bug]: New share dialog, can't unckek expire date
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Can't uncheck the "expire date" setting of external links

### Steps to reproduce

1. create a externel link on c.nc.com
2. Go to "..."-menu -> "customize link"
3. this is how it look like: 
image
4. try to uncheck the expire date

### Expected behavior

check box for expire date is unchecked, instead just the date is removed but the checkbox is still ticked:

image

### Installation method

None

### Nextcloud Server version

27.1.3.1 (c.nc.com)

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by nfebe**
We should check that a maximum expiry date has been enforced for all shares and NOT JUST FOR internal shares before enforcing a UI max date, like in commit 9757e680e2f643fe19432255c4142e96fbc88df5

Resolves : _no issue_

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Review by come-nc — COMMENTED** [review]
Enforcing now works for all three kind of shares.

But default seems broken for remote share it’s not applied?

**Comment by Fenn-CS** [comment]
> Enforcing now works for all three kind of shares.
> 
> But default seems broken for remote share it’s not applied?

Added [commit](https://github.com/nextcloud/server/pull/40933/commits/963b86b7c024dd40518f4f30e07a22a6d862aa58) to fix it.  Which also turns addresses and issue that existing of not being able to not set default if desired. Thanks @come-nc

**Comment by come-nc** [comment]
Hum, forced default expiration date now works for all cases, but for default value it uses the normal share default value for all 3 cases, even email and remote share, which should use their own default.

File: apps/files_sharing/src/views/SharingDetailsTab.vue [hunk 1]
```diff
@@ -715,10 +703,23 @@ export default {
...
+					this.share.expireDate = this.config.defaultExpirationDate.toDateString()
+				}
+
+				if (this.isRemoteShare && this.config.isDefaultRemoteExpireDateEnabled) {
+					this.share.expireDate = this.config.defaultRemoteExpirationDateString.toDateString()
+				}
+
+				if (this.config.isDefaultInternalExpireDateEnabled) {
+					this.share.expireDate = this.config.defaultInternalExpirationDate.toDateString()
+				}
```
Comment (come-nc) [inline apps/files_sharing/src/views/SharingDetailsTab.vue:717]: This is not an elseif so it overrides previous date value.

Comment (come-nc) [inline apps/files_sharing/src/views/SharingDetailsTab.vue:717]:
```suggestion
				/* Set default expiration dates if set */
				if (this.isPublicShare && this.config.isDefaultExpireDateEnabled) {
					this.share.expireDate = this.config.defaultExpirationDate.toDateString()
				} else if (this.isRemoteShare && this.config.isDefaultRemoteExpireDateEnabled) {
					this.share.expireDate = this.config.defaultRemoteExpirationDateString.toDateString()
				} else if (this.config.isDefaultInternalExpireDateEnabled) {
					this.share.expireDate = this.config.defaultInternalExpirationDate.toDateString()
				}
```
This change fixes the behavior.

**Comment by come-nc** [comment]
I had to run «npm run build» to fix the admin UI, so something is fishy in the commited dist. You will have to rebase on master and rebuild anyway.

Also, there is a problem:

1. Set a default expiration date on all 3 types
2. Force it for email share and not for the others
3. Share with a user
4. Date is enforced while it should not

Please test thoroughly requesting for review again.

**Review by come-nc — CHANGES_REQUESTED** [review]
Enforcing is not working correctly (enforcing email enforces for local share, did not test other combinations)

**Comment by Fenn-CS** [comment]
> I had to run «npm run build» to fix the admin UI, so something is fishy in the commited dist. You will have to rebase on master and rebuild anyway.
> 
> Also, there is a problem:
> 
>     Set a default expiration date on all 3 types
>     Force it for email share and not for the others
>     Share with a user
>     Date is enforced while it should not
> 
> Please test thoroughly requesting for review again.

Sorry @come-nc it appears it merge conflict resolution overwrote some of the update, during a rebase.

**Review by come-nc — APPROVED** [review]
:partying_face:

**Comment by marcelklehr** [comment]
Can we please backport this to stable27?

**Comment by susnux** [comment]
Looks like this is already on stable27? At least when I cherry pick it is empty. cc @Fenn-CS

**Comment by Fenn-CS** [comment]
@susnux it is : https://github.com/nextcloud/server/pull/40928

**Comment by Fenn-CS** [comment]
@marcelklehr it has commits from both issues.
