### PR TITLE
fix(files_sharing): bring back handling of `hide-download` on public shares

### LINKED ISSUE #48954: "Hide download" in public shares is no longer "hide download" but "prevent download" in Nextcloud 31
Since the migration of public shares to Vue [enabling _Hide download_ also removes the download permissions](https://github.com/nextcloud/server/commit/1d16bc47ffe7fbbf3f98a773612df6cdfa56f7de#diff-dbbe017dd357504abc442a6f1d0305166520ebf80353f42814b3f879a3e241bc). But a hidden download is not the same as a disabled download; a hidden download does not disable the download, but simply removes the option from the UI (as some of the viewer apps (like the PDF viewer) need to actually download the file to be able to show it).

Note that just updating to Nextcloud 31 will not change the behaviour of existing shares. However, any share then marked as _Hide download_ will behave as _Prevent download_.

If that new behaviour is intended then at least it should be documented to avoid surprises (some file types no longer viewable in public shares if download is hidden) for users coming from previous versions :-)

Related:
- https://github.com/nextcloud/server/issues/46256
- https://github.com/nextcloud/server/issues/45412

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: https://github.com/nextcloud/server/issues/48954

## Summary

This includes also some features as we need a WebDAV property for the `hide-download` functionality,
in legacy sharing interface it was passed as some kind of state, but with the Vue files interface we need a node attribute.

Best to review each commit separately.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/dav/lib/Connector/Sabre/FilesPlugin.php [hunk 1]
```diff
@@ -64,6 +65,7 @@ class FilesPlugin extends ServerPlugin {
 	public const UPLOAD_TIME_PROPERTYNAME = '{http://nextcloud.org/ns}upload_time';
 	public const CREATION_TIME_PROPERTYNAME = '{http://nextcloud.org/ns}creation_time';
 	public const SHARE_NOTE = '{http://nextcloud.org/ns}note';
+	public const SHARE_HIDE_DOWNLOAD_PROPERTYNAME = '{http://nextcloud.org/ns}hide-download';
```
Comment (szaimen) [inline apps/dav/lib/Connector/Sabre/FilesPlugin.php:68]: Does this new propert, mean that also the clients need to add support for it? 

Cc @tobiasKaminsky @Rello

Comment (susnux) [reply apps/dav/lib/Connector/Sabre/FilesPlugin.php:68]: Not now as its only used by public shares.

Comment (szaimen) [reply apps/dav/lib/Connector/Sabre/FilesPlugin.php:68]: Ok

File: apps/files_sharing/lib/Controller/ShareAPIController.php [hunk 2]
```diff
@@ -1292,16 +1292,11 @@ public function updateShare(
 			|| $share->getShareType() === IShare::TYPE_EMAIL) {
 
 			// Update hide download state
-			$attributes = $share->getAttributes() ?? $share->newAttributes();
```
Comment (artonge) [inline apps/files_sharing/lib/Controller/ShareAPIController.php:1295]: What is the difference between the two?

File: apps/files_sharing/src/models/Share.ts [hunk 3]
```diff
@@ -252,6 +252,15 @@ export default class Share {
 	 * Hide the download button on public page
 	 */
 	set hideDownload(state: boolean) {
+		// disabling hide-download also enables the download permission
+		// needed for regression in Nextcloud 31.0.0 until (incl.) 31.0.3
+		if (!state) {
+			const attribute = this.attributes.find(({ key, scope }) => key === 'download' && scope === 'permissions')
+			if (attribute) {
+				attribute.value = true
```
Comment (artonge) [inline apps/files_sharing/src/models/Share.ts:260]: I am confused, shouldn't it be that?

```suggestion
				attribute.value = state // false
```

File: apps/files_sharing/lib/DefaultPublicShareTemplateProvider.php [hunk 4]
```diff
@@ -156,7 +156,7 @@ public function renderPage(IShare $share, string $token, string $path): Template
 			$headerActions[] = new SimpleMenuAction('download', $this->l10n->t('Download'), 'icon-download', $downloadUrl, 0, (string)$shareNode->getSize());
 
 			// If remote sharing is enabled also add the remote share action to the menu
-			if ($this->federatedShareProvider->isOutgoingServer2serverShareEnabled() && !$share->getHideDownload()) {
+			if ($this->federatedShareProvider->isOutgoingServer2serverShareEnabled()) {
```
[the remark this answers is not in the document]
Comment (susnux) [reply apps/files_sharing/lib/DefaultPublicShareTemplateProvider.php:159]: See line 148, its just moved up.
The difference is only that now we also hide the download button

File: apps/files_sharing/lib/Controller/ShareAPIController.php (hunk 2 above)
Comment (susnux) [reply apps/files_sharing/lib/Controller/ShareAPIController.php:1295]: `getAttributes` only gets them if there are some, if there are non we need to create a new attribute wrapper using `newAttributes`.

But thats not needed anymore - for now - as the attributes are about permissions and we only want to visually hide the download button as it was in 29 and below.

File: apps/files_sharing/lib/DefaultPublicShareTemplateProvider.php (hunk 4 above)
[the remark this answers is not in the document]
Comment (artonge) [reply apps/files_sharing/lib/DefaultPublicShareTemplateProvider.php:159]: Ah right, thought it was an addition.

File: apps/files_sharing/src/models/Share.ts (hunk 3 above)
Comment (artonge) [reply apps/files_sharing/src/models/Share.ts:260]: Oh, right

File: apps/files_sharing/lib/Controller/ShareAPIController.php (hunk 2 above)
Comment (susnux) [reply apps/files_sharing/lib/Controller/ShareAPIController.php:1295]: hide download: only hide the action / buttons in the UI. Theoretically you can still download it using the UI.

prevent download: disables all APIs that allow downloading (e.g. previews, GET on webdav, etc). But only allow viewing it using special apps (currently only Collabora).

30 and before behavior is:
- hide download for public shares
- prevent download for internal shares

Current behavior:
- prevent download everywhere

Intended behavior:
- 31: same as 30 (thats the revert here)
- 32+: hide download everywhere and prevent download only for legacy shares (where it was enabled).

Comment (artonge) [reply apps/files_sharing/lib/Controller/ShareAPIController.php:1295]: Thanks, make much more sense

**Review by artonge — APPROVED** [review]

**Review by szaimen — APPROVED** [review]
🐘

**Review by nfebe — COMMENTED** [review]
FYI : The was some feedback from @danxuliu here: https://github.com/nextcloud/server/pull/50897

Mentioning it case it is possible to align some or all of it.

Also, since the switch was not preventing download, is there a way for those who used to switch do undo it if they can identify the shares on which it was applied?

**Comment by susnux** [comment]
> FYI : The was some feedback from @danxuliu here: #50897

yes that covered by the webdav property

**Review by danxuliu — COMMENTED** [review]
> > FYI : The was some feedback from @danxuliu here: https://github.com/nextcloud/server/pull/50897
>
> yes that covered by the webdav property

As the `hideDownload` element is no longer provided please note that this pull request alone is not enough to bring back the old behaviour. Any app that used the `hideDownload` element must be updated to get the value from the new WebDAV property instead (so this should be documented somewhere).

For the PDF viewer I adjusted it in the last commit of https://github.com/nextcloud/files_pdfviewer/pull/1164

**Comment by susnux** [comment]
PR to viewer will be created right after merge
