### PR TITLE
fix(core): app menu label position and animation

### LINKED ISSUE #46542: [Bug]: Increased space between apps and name when hovering the apps menu
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

30:
Bildschirmfoto vom 2024-07-15 17-17-12
29:
Bildschirmfoto vom 2024-07-15 17-17-04

### Steps to reproduce

1. Log into Nextcloud daily
2. Hover the app menu

### Expected behavior

Good design

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

Tested with FF on Linux

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/server/issues/46542

| Before | After |
|:---------:|:------:|
|Peek 31-07-2024 15-14|Peek 31-07-2024 15-12|
|With notification :arrow_right: |Peek 31-07-2024 17-19|

### CODE REVIEW

File: core/src/components/AppMenuEntry.vue [hunk 1]
```diff
@@ -84,44 +84,49 @@ defineProps<{
...
+	&__icon,
+	&__label {
+		transition: all 0.1s ease-in-out;
+	}
+
 	// Make the hovered entry bold to see that it is hovered
-	&:hover &__label,
-	&:focus-within &__label {
+	&:hover .app-menu-entry__label,
+	&:focus-within .app-menu-entry__label {
```
Comment (susnux) [inline core/src/components/AppMenuEntry.vue:106]: Its the same?

**Review by ChristophWurst — APPROVED** [review]
Not my area of expertise but looks good on the videos :+1:

File: core/src/components/AppMenuEntry.vue (hunk 1 above)
Comment (skjnldsv) [reply core/src/components/AppMenuEntry.vue:106]: cleaner this way.

Took me a while to understand the nesting.

**Comment by skjnldsv** [comment]
> I think they are too narrow now, try to add a unread notification and it will overflow the text, you see it on the activity app icon: Label and icon do not have any spacing, but the unread notification will cover -5px.

I used the exact screenshots from a 28 instance

File: core/src/components/AppMenuEntry.vue [hunk 2]
```diff
@@ -61,10 +61,10 @@ defineProps<{
 		text-align: center;
 		bottom: 0;
 		left: 50%;
+		top: 50%;
```
Comment (susnux) [inline core/src/components/AppMenuEntry.vue:64]: This one is the only problematic place I think because with unread notification it looks like this now:
Screen Shot 2024-07-31 at 15 31 57

With this:

```suggestion
		top: 60%;
```

It would be:
Screen Shot 2024-07-31 at 15 31 38

**Comment by susnux** [comment]
> I used the exact screenshots from a ~28~ 29 instance

And that is what I tried to fix with the initial PR :sweat_smile:

**Review by susnux — APPROVED** [review]
Approve as it restores NC29 design, but please see my comment about the missing padding for notification :)

**Comment by skjnldsv** [comment]
Feel free to take over @susnux :see_no_evil:

File: core/src/components/AppMenuEntry.vue (hunk 2 above)
Comment (skjnldsv) [reply core/src/components/AppMenuEntry.vue:64]: Peek 31-07-2024 17-19

**Review by jancborchardt — COMMENTED** [review]
Notification bubble should be in the top right, as it is e.g. on iOS, Android and for our own notification icon as well. Then there is also no text overlap issue. cc @susnux in case it got lost in the other issue. :)

**Comment by skjnldsv** [comment]
@jancborchardt, I'll address it in a PR right now so it doesn't get lost
