### PR TITLE
fix: Update documentation for Mail Provider Send

### LINKED ISSUE #46883: Update documentation for IMessageSend.sendMessage
https://github.com/nextcloud/server/blob/18c0bcb2da2da1e046163e006ba581be165caed8/lib/public/Mail/Provider/IMessageSend.php#L21-L29

The method may throw a `OCP\Mail\Provider\Exception\SendException`

### PR DESCRIPTION
**Pull request by SebastianKrupinski**
* Resolves: #46883

### CODE REVIEW

File: lib/public/Mail/Provider/IMessageSend.php [hunk 1]
```diff
@@ -25,6 +25,8 @@ interface IMessageSend {
 	 *
 	 * @param IMessage $message			mail message object with all required parameters to send a message
 	 * @param array $options			array of options reserved for future use
+	 * 
+	 * @throws OCP\Mail\Provider\Exception\SendException on failure, check message for reason
```
Comment (susnux) [inline lib/public/Mail/Provider/IMessageSend.php:29]:
```suggestion
	 * @throws \OCP\Mail\Provider\Exception\SendException on failure, check message for reason
```

**Review by kesselb — APPROVED** [review]

**Review by susnux — APPROVED** [review]
