### PR TITLE
fix(files): Move aria-label for favorite icon from span to icon

### LINKED ISSUE #41891: [BITV] 9.4.1.2/3.3 - In the table, in the "Name" column, there are elements that have been marked as favorites with a star icon. (2)
However, the implementation for screen reader users is flawed because the "aria-label" attribute is erroneously used on the "span" element, which is not allowed - <span aria-label="Favorite" class="files-list__row-icon-favorite">.

https://report.bitvtest.de/default-en/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-bfbf07e5c3-v3-n3

9.4.1.2/11.3 - https://report.bitvtest.de/default-en/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-bfbf07e5c3-v11-n3

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: #41891

## Summary
Move the label from the span to the icon itself

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by ShGKme — APPROVED** [review]

**Review by Pytal — APPROVED** [review]

**Comment by susnux** [comment]
/backport f79a1ad33ec762e36ac6d66fa733cff4db7fa75d to stable28

File: apps/files/src/components/FileEntry/FavoriteIcon.vue [hunk 1]
```diff
@@ -52,10 +55,14 @@ export default {
 		await this.$nextTick()
 		// MDI default viewbox is "0 0 24 24" but we add a stroke of 10px so we must adjust it
 		const el = this.$el.querySelector('svg')
-		el.setAttribute('viewBox', '-4 -4 30 30')
+		el?.setAttribute?.('viewBox', '-4 -4 30 30')
```
Comment (ShGKme) [inline apps/files/src/components/FileEntry/FavoriteIcon.vue:58]: BTW, why add optional chaining here? Is it possible that there would be no SVG, or that the SVG element would not have the `setAttribute` method?
