### PR TITLE
Fix Uninitialized string offset 0 at GenerateMimetypeFileBuilder.php#39

### LINKED ISSUE #31973: [Bug]: Error: Uninitialized string offset 0 at /nextcloud/core/Command/Maintenance/Mimetype/GenerateMimetypeFileBuilder.php#39
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When executing ocr-workflow, an error is reported:
```
{
  "reqId": "03kwosS2zWgKoWQf6D35",
  "level": 3,
  "time": "2022-04-14T11:20:29+02:00",
  "remoteAddr": "",
  "user": "--",
  "app": "PHP",
  "method": "",
  "url": "--",
  "message": "Uninitialized string offset 0 at /var/www/nextcloud/core/Command/Maintenance/Mimetype/GenerateMimetypeFileBuilder.php#39",
  "userAgent": "--",
  "version": "22.2.5.1",
  "exception": {
    "Exception": "Error",
    "Message": "Uninitialized string offset 0 at /var/www/nextcloud/core/Command/Maintenance/Mimetype/GenerateMimetypeFileBuilder.php#39",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/nextcloud/core/Command/Maintenance/Mimetype/GenerateMimetypeFileBuilder.php",
        "line": 39,
        "function": "onError",
        "class": "OC\\Log\\ErrorHandler",
        "type": "::"
      },
      {
        "function": "OC\\Core\\Command\\Maintenance\\Mimetype\\{closure}",
        "class": "OC\\Core\\Command\\Maintenance\\Mimetype\\GenerateMimetypeFileBuilder",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/nextcloud/core/Command/Maintenance/Mimetype/GenerateMimetypeFileBuilder.php",
        "line": 40,
        "function": "array_filter"
      },
      {
        "file": "/var/www/nextcloud/lib/private/IntegrityCheck/Checker.php",
        "line": 203,
        "function": "generateFile",
        "class": "OC\\Core\\Command\\Maintenance\\Mimetype\\GenerateMimetypeFileBuilder",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/IntegrityCheck/Checker.php",
        "line": 388,
        "function": "generateHashes",
        "class": "OC\\IntegrityCheck\\Checker",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/IntegrityCheck/Checker.php",
        "line": 570,
        "function": "verify",
        "class": "OC\\IntegrityCheck\\Checker",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/IntegrityCheck/Checker.php",
        "line": 591,
        "function": "verifyCoreSignature",
        "class": "OC\\IntegrityCheck\\Checker",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/Updater.php",
        "line": 300,
        "function": "runInstanceVerification",
        "class": "OC\\IntegrityCheck\\Checker",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/Updater.php",
        "line": 132,
        "function": "doUpgrade",
        "class": "OC\\Updater",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/core/Command/Upgrade.php",
        "line": 235,
        "function": "upgrade",
        "class": "OC\\Updater",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/symfony/console/Command/Command.php",
        "line": 255,
        "function": "execute",
        "class": "OC\\Core\\Command\\Upgrade",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/symfony/console/Application.php",
        "line": 1009,
        "function": "run",
        "class": "Symfony\\Component\\Console\\Command\\Command",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/symfony/console/Application.php",
        "line": 273,
        "function": "doRunCommand",
        "class": "Symfony\\Component\\Console\\Application",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/symfony/console/Application.php",
        "line": 149,
        "function": "doRun",
        "class": "Symfony\\Component\\Console\\Application",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/Console/Application.php",
        "line": 209,
        "function": "run",
        "class": "Symfony\\Component\\Console\\Application",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/console.php",
        "line": 99,
        "function": "run",
        "class": "OC\\Console\\Application",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/occ",
        "line": 11,
        "args": [
          "/var/www/nextcloud/console.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/var/www/nextcloud/lib/private/Log/ErrorHandler.php",
    "Line": 92,
    "CustomMessage": "--"
  },
  "id": "6257ebb768e97"
}
```

### Steps to reproduce

1. Install app workflow_ocr + define workflow for mime-type PDF as described here: https://github.com/R0Wi/workflow_ocr/blob/master/README.md#settings
2. Copy PDF document to Nextcloud instance
3. Search the log for above error

### Expected behavior

Workflow should run without error

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

_No response_

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "defaultapp": "files",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.40.107",
            "192.168.40.102",
            "localhost"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.2.6.2",
        "overwrite.cli.url": "https:\/\/192.168.40.107",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "activity_expire_days": 14,
        "auth.bruteforce.protection.enabled": true,
        "blacklisted_files": [
            ".htaccess",
            "Thumbs.db",
            "thumbs.db"
        ],
        "cron_log": true,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "filesystem_check_changes": 0,
        "filelocking.enabled": "true",
        "htaccess.RewriteBase": "\/",
        "integrity.check.disabled": false,
        "knowledgebaseenabled": false,
        "logfile": "\/var\/nc_data\/nextcloud.log",
        "loglevel": 0,
        "logtimezone": "Europe\/Berlin",
        "log_rotate_size": 104857600,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "overwriteprotocol": "https",
        "preview_max_x": 1024,
        "preview_max_y": 768,
        "preview_max_scale_factor": 1,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "quota_include_external_storage": false,
        "share_folder": "\/Shares",
        "skeletondirectory": "",
        "theme": "",
        "trashbin_retention_obligation": "auto, 7",
        "updater.release.channel": "stable",
        "onlyoffice": {
            "verify_peer_off": true
        },
        "app_install_overwrite": [
            "keeweb"
        ],
        "allow_local_remote_servers": true,
        "default_phone_region": "DE"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - admin_audit: 1.12.0
  - analytics: 4.2.1
  - bruteforcesettings: 2.4.0
  - calendar: 3.2.2
  - circles: 22.3.0
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.1.0
  - contactsinteraction: 1.3.0
  - dashboard: 7.2.0
  - dav: 1.20.0
  - drawio: 1.0.2
  - duplicatefinder: 0.0.13
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_accesscontrol: 1.12.1
  - files_antivirus: 3.2.2
  - files_automatedtagging: 1.12.0
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - firstrunwizard: 2.11.0
  - flow_notifications: 1.2.0
  - groupfolders: 10.0.2
  - keeweb: 0.6.8
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - mail: 1.11.7
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - onlyoffice: 7.3.2
  - password_policy: 1.12.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - ransomware_protection: 1.13.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - systemtags: 1.12.0
  - text: 3.3.1
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflow_ocr: 1.22.5
  - workflowengine: 2.4.0
Disabled:
  - announcementcenter: 6.1.1
  - encryption
  - end_to_end_encryption: 1.8.1
  - files_external
  - files_videoplayer: 1.7.0
  - nextcloud_announcements: 1.7.0
  - photos: 1.0.0
  - recommendations: 0.6.0
  - sharebymail: 1.8.0
  - support: 1.1.1
  - survey_client: 1.6.0
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"03kwosS2zWgKoWQf6D35","level":3,"time":"2022-04-14T11:20:29+02:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Uninitialized string offset 0 at /var/www/nextcloud/core/Command/Maintenance/Mimetype/GenerateMimetypeFileBuilder.php#39","userAgent":"--","version":"22.2.5.1","exception":{"Exception":"Error","Message":"Uninitialized string offset 0 at /var/www/nextcloud/core/Command/Maintenance/Mimetype/GenerateMimetypeFileBuilder.php#39","Code":0,"Trace":[{"file":"/var/www/nextcloud/core/Command/Maintenance/Mimetype/GenerateMimetypeFileBuilder.php","line":39,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"function":"OC\\Core\\Command\\Maintenance\\Mimetype\\{closure}","class":"OC\\Core\\Command\\Maintenance\\Mimetype\\GenerateMimetypeFileBuilder","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/core/Command/Maintenance/Mimetype/GenerateMimetypeFileBuilder.php","line":40,"function":"array_filter"},{"file":"/var/www/nextcloud/lib/private/IntegrityCheck/Checker.php","line":203,"function":"generateFile","class":"OC\\Core\\Command\\Maintenance\\Mimetype\\GenerateMimetypeFileBuilder","type":"->"},{"file":"/var/www/nextcloud/lib/private/IntegrityCheck/Checker.php","line":388,"function":"generateHashes","class":"OC\\IntegrityCheck\\Checker","type":"->"},{"file":"/var/www/nextcloud/lib/private/IntegrityCheck/Checker.php","line":570,"function":"verify","class":"OC\\IntegrityCheck\\Checker","type":"->"},{"file":"/var/www/nextcloud/lib/private/IntegrityCheck/Checker.php","line":591,"function":"verifyCoreSignature","class":"OC\\IntegrityCheck\\Checker","type":"->"},{"file":"/var/www/nextcloud/lib/private/Updater.php","line":300,"function":"runInstanceVerification","class":"OC\\IntegrityCheck\\Checker","type":"->"},{"file":"/var/www/nextcloud/lib/private/Updater.php","line":132,"function":"doUpgrade","class":"OC\\Updater","type":"->"},{"file":"/var/www/nextcloud/core/Command/Upgrade.php","line":235,"function":"upgrade","class":"OC\\Updater","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/console/Command/Command.php","line":255,"function":"execute","class":"OC\\Core\\Command\\Upgrade","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/console/Application.php","line":1009,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/console/Application.php","line":273,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/console/Application.php","line":149,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/nextcloud/lib/private/Console/Application.php","line":209,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/nextcloud/console.php","line":99,"function":"run","class":"OC\\Console\\Application","type":"->"},{"file":"/var/www/nextcloud/occ","line":11,"args":["/var/www/nextcloud/console.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"6257ebb768e97"}
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by kesselb**
Fix #31973

Someone added a file `config/mimetypealiases.json` to my instance like below. Key is empty hence the check if the first character of the string is `_` fails.

```
{
	"": "x-office\/document",
	"application\/vnd.openxmlformats-officedocument.wordprocessingml.document.docxf": "x-office\/document",
	"application\/vnd.openxmlformats-officedocument.wordprocessingml.document.oform": "x-office\/document"
}
```

### CODE REVIEW

File: core/Command/Maintenance/Mimetype/GenerateMimetypeFileBuilder.php [hunk 1]
```diff
@@ -30,17 +30,15 @@
...
 	public function generateFile(array $aliases): string {
 		// Remove comments
-		$keys = array_filter(array_keys($aliases), function ($k) {
-			return $k[0] === '_';
-		});
-		foreach ($keys as $key) {
-			unset($aliases[$key]);
-		}
+		$aliases = array_values(array_filter($aliases, static function ($key) {
+			return !empty($key) && $key[0] !== '_';
```
[the remark this answers is not in the document]
Comment (kesselb) [reply core/Command/Maintenance/Mimetype/GenerateMimetypeFileBuilder.php]: Thanks

File: core/Command/Maintenance/Mimetype/GenerateMimetypeFileBuilder.php [hunk 2]
```diff
@@ -30,17 +30,15 @@
...
 		// Remove comments
-		$keys = array_filter(array_keys($aliases), function ($k) {
-			return $k[0] === '_';
-		});
-		foreach ($keys as $key) {
-			unset($aliases[$key]);
-		}
+		$aliases = array_filter($aliases, static function ($key) {
+			return !($key === '' || $key[0] === '_');
+		}, ARRAY_FILTER_USE_KEY);
```
Comment (come-nc) [inline core/Command/Maintenance/Mimetype/GenerateMimetypeFileBuilder.php:41]:
```suggestion
		$aliases = array_filter(
			$aliases, 
			fn (string $key) => !($key === '' || $key[0] === '_'), 
			ARRAY_FILTER_USE_KEY);
```
Why did you set function as static?

Comment (kesselb) [reply core/Command/Maintenance/Mimetype/GenerateMimetypeFileBuilder.php:41]: I'm using Php Inspections (a plugin for PHPStorm). It's a recommendation to declare closures static when possible. They say: better scoping; in some cases can improve performance.

The arrow function is a good suggestion thanks :+1: But I have to modify the PR with the backports then.

**Review by come-nc — APPROVED** [review]
Is it expected to have an empty string as a valid key is $aliases array though?

**Comment by kesselb** [comment]
> Is it expected to have an empty string as a valid key is $aliases array though?

I don't think so ;)

**Review by artonge — APPROVED** [review]

**Comment by vitormattos** [comment]
Hi @come-nc I found this error in an instance with version25.
Was the pull request with the backport made?

**Comment by come-nc** [comment]
> Hi @come-nc I found this error in an instance with version25. Was the pull request with the backport made?

No, I’m gonna retrigger the bot and backport by hand if needed.

**Comment by come-nc** [comment]
> Hi @come-nc I found this error in an instance with version25. Was the pull request with the backport made?

Merged in 25/24/23 now.
