### PR TITLE
fix(CSP): Add CSP nonce by default and convert `browserSupportsCspV3` to blacklist

### LINKED ISSUE #10207: CSP nonce by default
In https://github.com/nextcloud/server/pull/10205 I tried to always add the CSP nonce.

As most browsers if unsafe-inline is there and a nonce will ignore the unsafe-inline. This is the CSPv3 backwards compatibility idea.

However this seems to break on Edge. As edge doesn't properly parse the nonce on external resources.

We should investigate how to enable the nonce on more browsers.

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: https://github.com/nextcloud/server/issues/10207

## Summary

Every modern browser ("modern" like every version since 2013 (over 10 years now!)) support the nonce src.
So we should add it by default and only keep a blacklist instead.

This way even users with for us unknown user agents get the more secure version.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by SystemKeeper** [comment]
Tested with Talk iOS on iOS 15.5 and 17.0 and both worked for me.

**Review by MichaIng — APPROVED** [review]
Since IE is not (officially) supported by Nextcloud anymore, even the blacklist might not be needed. But good to have the facility, so we can add further entries in the unlikely but possible case that there are other browsers not supporting CSP nonce sources.

**Review by skjnldsv — APPROVED** [review]

File: lib/private/Security/CSP/ContentSecurityPolicyNonceManager.php [hunk 1]
```diff
@@ -65,17 +65,14 @@ public function getNonce(): string {
 	 * Check if the browser supports CSP v3
 	 */
 	public function browserSupportsCspV3(): bool {
-		$browserWhitelist = [
-			Request::USER_AGENT_CHROME,
-			Request::USER_AGENT_FIREFOX,
-			Request::USER_AGENT_SAFARI,
-			Request::USER_AGENT_MS_EDGE,
+		$browserBlacklist = [
```
Comment (Altahrim) [inline lib/private/Security/CSP/ContentSecurityPolicyNonceManager.php:68]: Nit:
```suggestion
		$browserBlocklist = [
```
But we can also get rid of the variable:
```php
public function browserSupportsCspV3(): bool {
	// Modern browsers all supports CSPv3
	return !$this->request->isUserAgent([Request::USER_AGENT_IE]]);
}
```

**Review by Altahrim — APPROVED** [review]

File: lib/private/Security/CSP/ContentSecurityPolicyNonceManager.php (hunk 1 above)
Comment (susnux) [reply lib/private/Security/CSP/ContentSecurityPolicyNonceManager.php:68]: The idea was to keep the variable for later usage.

Comment (Altahrim) [reply lib/private/Security/CSP/ContentSecurityPolicyNonceManager.php]: We can easily add one later if needed :)

**Review by juliusknorr — APPROVED** [review]
