### PR TITLE
use the email address configured in Nextcloud as sender instead of the users email address

### LINKED ISSUE #5047: Can't password protect shares because password email is sent from account email address
### Steps to reproduce
1. Share any document by typing the email address in the sharing dialog box
2. Check the password protect box, setting a password then pressing Tab
3. Receive an error message: "Expected response code 250 but got code "553", with message "553 Relaying disallowed as [username] (profile email address)"

### Expected behaviour

1. **The link should be protected with the password that was set.**
1. The email should be sent from the system account, like any other notification email.
1. If something fails, at least record it in the logs for future reference.

### Actual behaviour
This error appears, **the link is not protected**, and _nothing is recorded in the logs_.

### Server configuration

**Operating system:** Ubuntu 16.04

**Nextcloud version:** 12.0

### PR DESCRIPTION
**Pull request by schiessle**
fix https://github.com/nextcloud/server/issues/5047

### CODE REVIEW

File: apps/sharebymail/lib/ShareByMailProvider.php [hunk 1]
```diff
@@ -456,11 +456,24 @@ protected function sendPassword(IShare $share, $password) {
...
+			[
+				$initiatorDisplayName,
+				$instanceName
+			]
+		);
+		$message->setFrom([\OCP\Util::getDefaultEmailAddress($instanceName) => $senderName]);
 		if ($initiatorEmailAddress !== null) {
-			$message->setFrom([$initiatorEmailAddress => $initiatorDisplayName]);
+			$message->setReplyTo([$initiatorEmailAddress => $initiatorDisplayName]);
+			$emailTemplate->addFooter($instanceName . ' - ' . $this->defaults->getSlogan());
```
Comment (nickvergessen) [inline apps/sharebymail/lib/ShareByMailProvider.php]: this is the default text, so you can omit it?

Comment (schiessle) [inline apps/sharebymail/lib/ShareByMailProvider.php]: no, the default text contain an additional line that this is a auto generated mail and you can't reply to it which is not true if we set a valid reply-to header.

**Review by LukasReschke — APPROVED** [review]
