### PR TITLE
Can not change encryption directory

### LINKED ISSUE #6769: Encryption Module: moving keys will brake Nextcloud
Ubuntu 16.0.3 LTS X64 on ARM64 (oDroidC2)
Nextcloud 12.0.3 (plain/new installation from scratch)
PHP 7.1.10
MariaDB 10.0.31
Redis-Server 3.0.6
web-user: www-data
web-root: /var/www/nextcloud
data-dir: /var/nc_data

The encryption was configured properly on my test environement for all users:

When trying to move the keys as described in Nextclouds Admin-Documentation  [here](https://docs.nextcloud.com/server/12/admin_manual/configuration_files/encryption_configuration.html) the server will crash:
`mkdir /etc/keys`
`chown -R root:www-data /etc/keys`
`chmod -R 0770 /etc/keys`
`sudo -u www-data php occ encryption:change-key-storage-root ../../../etc/keys/`

grafik

grafik

No entries were generated while moving the keys. If trying to open Nextcloud the following entries are thrown:

> root@ncbox:/var/www/nextcloud# cat /var/nc_data/nextcloud.log
{"reqId":"fO3t18YMOqNVYFhKJ85E","level":3,"time":"2017-10-05T08:50:05+02:00","re2.168.2.125","user":"--","app":"index","method":"GET","url":"\/","message":"Exceeption\":\"OC\\\\ServiceUnavailableException\",\"Message\":\"Key Storage is not e\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/encryption\\\/appinf28): OC\\\\Encryption\\\\Manager->isReady()\\n#1 \\\/var\\\/www\\\/nextcloud\\\/e\\\/legacy\\\/app.php(209): require_once('\\\/var\\\/www\\\/nextcl...')\\n#2 \\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/app.php(149): OC_App::requireAppFile)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/app.php(124): pp('encryption')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(992): OC_Aprray)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/index.php(48): OC::handleRequest()\\n#File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Encryption\\\/Manager.":114}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko\/fox\/56.0","version":"12.0.3.3"}
root@ncbox:/var/www/nextcloud#

Running any occ the following errors appear:
> An unhandled exception has been thrown:
OC\ServiceUnavailableException: Key Storage is not ready in /var/www/nextcloud/lib/private/Encryption/Manager.php:114
Stack trace:
#0 /var/www/nextcloud/apps/encryption/appinfo/app.php(28): OC\Encryption\Manager->isReady()
#1 /var/www/nextcloud/lib/private/legacy/app.php(209): require_once('/var/www/nextcl...')
#2 /var/www/nextcloud/lib/private/legacy/app.php(149): OC_App::requireAppFile('encryption')
#3 /var/www/nextcloud/lib/private/legacy/app.php(124): OC_App::loadApp('encryption')
#4 /var/www/nextcloud/lib/private/Console/Application.php(104): OC_App::loadApps()
#5 /var/www/nextcloud/console.php(99): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')

Although moving the keys was mentioned as "successfull" the keys remain in the user location instead of "/etc/keys:":
  
grafik

What went wrong and what would help to repair this instance?
Cheers, Carsten

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #6769 

@schiessle there is an issue here
1. You require a path relative to the root storage
2. You use the view
3. The view does not allow `/../` in paths

Therefor you can only change the root inside your data directory, but not move it out of it.
If that is intended, we should have this commit here and display a better error message

### CODE REVIEW

File: core/Command/Encryption/ChangeKeyStorageRoot.php [hunk 1]
```diff
@@ -146,7 +146,7 @@ protected function prepareNewRoot($newRoot) {
 			'ownCloud will detect this folder as key storage root only if this file exists'
 		);
 
-		if ($result === false) {
+		if ($result !== true) {
```
Comment (nickvergessen) [inline core/Command/Encryption/ChangeKeyStorageRoot.php]: Currently the View returns `null`, because
https://github.com/nextcloud/server/blob/b9b88aa666ba8420311b6f6f24b42aadd03eed04/lib/private/Files/View.php#L1103
returns false and therefor nothing is executed.

**Comment by MorrisJobke** [comment]
@schiessle Any news for this? Would be good to get it in.

**Comment by MorrisJobke** [comment]
Let's move this to 14.

**Review by schiessle — APPROVED** [review]
tested and works with my changes

**Comment by schiessle** [comment]
second reviewer needed

**Comment by nickvergessen** [comment]
:+1: for not my code
