### PR TITLE
check if the file should really be encrypted before we update the file cache

### LINKED ISSUE #940: master-key encryption breaks file_versions on unencrypted home storage
### Steps to reproduce
1. Activate encryption with master-key
2. Disable home storage encryption
3. Upload two versions of one file into the home storage
4. Access the previous version of that file from that home storage
### Expected behavior

Serve the file without any complains.
### Actual behavior

Serves a incomplete and wrong file and fires an exception: 
Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.
### Server configuration

**Operating system**:
Ubuntu 16.04/ All services are running in docker container
**Web server:**
Nginx 1.10
**Database:**
MariaDB 10.1
**PHP version:**
7.0-fpm
**Nextcloud version:** (see Nextcloud admin page)
9.0.52
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from owncloud 9
**Where did you install Nextcloud from:**
nextcloud.com
**Signing status:**
<details>
<summary>

Signing status</summary>

No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>

App list</summary>

Enabled:
- activity: 2.2.1
- admin_audit: 1.0.0
- calendar: 1.3.2
- comments: 0.2
- contacts: true
- dav: 0.1.6
- encryption: 1.2.0
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_external: 0.5.2
- files_pdfviewer: 0.8.1
- files_sharing: 0.9.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 14.5.0
- notifications: 0.2.3
- ownbackup: 0.3.8
- password_policy: 1.0.0
- provisioning_api: 0.4.1
- systemtags: 0.2
- templateeditor: 0.1
- theming: 0.1.0
- updatenotification: 0.1.0
  Disabled:
- documents
- external
- files_texteditor
- mail
- music
- richdocuments
- tasks
- user_external
- user_ldap
- user_saml
  </details>

**The content of config/config.php:**
<details>
<summary>

Config report</summary>

{
    "system": {
        "instanceid": "occpxo4esnhe",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": [
            "owncloud.mydomain.org",
            "owncloud_1.mydomain.org",
            "owncloud.mydomain.org:443",
            "nextcloud.mydomain.org",
            "nextcloud_1.mydomain.org",
            "nextcloud.mydomain.org:443",
            "cloud.mydomain.org",
            "cloud.mydomain.org:443"
        ],
        "trusted_proxies": [
            "172.17.1.1",
            "pfsense.mydomain.org"
        ],
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR",
            "HTTP_FORWARDED_FOR"
        ],
        "overwritecondaddr": "^172\.17\.1\.1$",
        "overwrite.cli.url": "`https:\/\/cloud.mydomain.org`",
        "memcache.local": "\OC\Memcache\APCu",
        "memcache.locking": "\OC\Memcache\Redis",
        "redis": {
            "host": "redis",
            "port": 6379
        },
        "dbtype": "mysql",
        "version": "9.0.52.0",
        "dbname": "owncloud",
        "dbhost": "db",
        "dbtableprefix": "oc_",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "cloud",
        "mail_domain": "mydomain.org",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtphost": "smtp.mymail.org",
        "mail_smtpauth": 1,
        "mail_smtpport": "465",
        "mail_smtpname": "**_REMOVED SENSITIVE VALUE**_",
        "mail_smtppassword": "**_REMOVED SENSITIVE VALUE**_",
        "maintenance": false,
        "logtimezone": "Europe\/Berlin",
        "loglevel": 2,
        "singleuser": false,
        "blacklisted_files": [
            ".htaccess",
            "._*",
            ".DS_Store",
            ".DS_STORE",
            ".ds_store"
        ],
        "preview_max_filesize_image": 150,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore --convert-to pdf --outdir ",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/apps2",
                "url": "\/apps2",
                "writable": true
            }
        ]
    }
}
</details>

**Are you using external storage, if yes which one:** local
**Are you using encryption:** yes (master-key)
**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:**
Safari/9.1.2
Google Chrome/52
**Operating system:**
OSX:10.11
#### Web server error log

<details>
<summary>

Web server error log</summary>

192.168.1.1 - - [18/Aug/2016:16:23:18 +0200] "GET /index.php/settings/integrity/failed HTTP/1.1" 200 26 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:20 +0200] "GET / HTTP/1.1" 302 5 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:20 +0200] "GET / HTTP/1.1" 302 5 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:20 +0200] "GET /apps/files/ HTTP/1.1" 200 34572 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:20 +0200] "GET /apps/files/ HTTP/1.1" 200 34566 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:20 +0200] "GET /core/js/oc.js?v=d69f3e669ec28ffdfb6b442415f07579 HTTP/1.1" 200 2744 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:20 +0200] "GET /core/js/oc.js?v=d69f3e669ec28ffdfb6b442415f07579 HTTP/1.1" 200 2744 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:20 +0200] "GET /apps/theming/styles.css?v=4 HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:20 +0200] "GET /apps/theming/styles.css?v=4 HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:20 +0200] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 85 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:20 +0200] "GET /apps/gallery/config?extramediatypes=1 HTTP/1.1" 200 102 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:20 +0200] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 85 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:20 +0200] "GET /apps/gallery/config?extramediatypes=1 HTTP/1.1" 200 102 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:21 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 12509 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:21 +0200] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 85 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:21 +0200] "GET /apps/encryption/ajax/getStatus HTTP/1.1" 200 77 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:21 +0200] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.1" 200 213 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:21 +0200] "GET /core/preview.png?file=%2FNew+Document.odt&c=96a986daf408ea26f3d13f00ccb54323&x=64&y=64&forceIcon=0 HTTP/1.1" 404 6804 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:21 +0200] "GET /ocs/v1.php/apps/files_external/api/v1/mounts?format=json HTTP/1.1" 200 85 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:21 +0200] "GET /apps/encryption/ajax/getStatus HTTP/1.1" 200 77 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:21 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 12509 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:21 +0200] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.1" 200 213 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:21 +0200] "GET /core/preview.png?file=%2FNew+Document.odt&c=96a986daf408ea26f3d13f00ccb54323&x=64&y=64&forceIcon=0 HTTP/1.1" 404 6804 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:21 +0200] "GET /ocs/v1.php/apps/files_external/api/v1/mounts?format=json HTTP/1.1" 200 85 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
131.220.239.200 - - [18/Aug/2016:16:23:22 +0200] "PROPFIND /remote.php/webdav/BlackBerry/Backups/Device/photos/WhatsApp/2016-03/ HTTP/1.1" 207 22815 "-" "android-cloud-api - Android 4.3"
192.168.1.1 - - [18/Aug/2016:16:23:23 +0200] "GET /apps/activity/api/v2/activity/filter?format=json&object_type=files&object_id=3805 HTTP/1.1" 200 649 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:23 +0200] "PROPFIND /remote.php/dav/systemtags-relations/files/3805 HTTP/1.1" 207 561 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:24 +0200] "PROPFIND /remote.php/webdav/Star HTTP/1.1" 207 18921 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:24 +0200] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2FStar HTTP/1.1" 200 213 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:24 +0200] "GET /core/preview.png?file=%2FStar%2FBoxplots.R&c=e1d4e7e6e96abd0fe5b3f6731daf22a9&x=64&y=64&forceIcon=0 HTTP/1.1" 404 6804 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:24 +0200] "GET /core/preview.png?file=%2FStar%2FConfirmatoryAssays.7z&c=b67119e38139e237cd1a7c8bb97ddd2b&x=64&y=64&forceIcon=0 HTTP/1.1" 404 6804 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:24 +0200] "GET /core/preview.png?file=%2FStar%2FConfirmatoryAssays_sim.7z&c=6e548bca73e2a718cc97db157b2e79ca&x=64&y=64&forceIcon=0 HTTP/1.1" 404 6804 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:24 +0200] "GET /core/preview.png?file=%2FStar%2FMeeting_Template_slides_2014.pptx&c=fc73176750db16009e95682635902a0e&x=64&y=64&forceIcon=0 HTTP/1.1" 404 6804 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:24 +0200] "GET /core/preview.png?file=%2FStar%2FReport1.pdf&c=6052ece8be6226cfeb221d6d99a445f8&x=64&y=64&forceIcon=0 HTTP/1.1" 404 6804 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:24 +0200] "GET /core/preview.png?file=%2FStar%2FLDA-PCA.R&c=f512c66f51b76ae43a33f89708f64b21&x=64&y=64&forceIcon=0 HTTP/1.1" 404 6804 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:24 +0200] "GET /core/preview.png?file=%2FStar%2FReport1.pptx&c=dbf450142ab3057afd849deabc09be29&x=64&y=64&forceIcon=0 HTTP/1.1" 404 6804 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:24 +0200] "GET /core/preview.png?file=%2FStar%2FLSI_Template_slides_2014_new_LIMES_Logo.pptx&c=828d116c69449f8bd3d66c463f7c1064&x=64&y=64&forceIcon=0 HTTP/1.1" 404 6804 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:26 +0200] "OPTIONS /remote.php/dav/principals/users/thomas/ HTTP/1.1" 401 426 "-" "Mac OS X/10.11.6 (15G31) AddressBook/1679.10"
131.220.239.200 - - [18/Aug/2016:16:23:26 +0200] "PROPFIND /remote.php/webdav/BlackBerry/Backups/Device/photos/WhatsApp/2016-05/ HTTP/1.1" 207 1904 "-" "android-cloud-api - Android 4.3"
192.168.1.1 - - [18/Aug/2016:16:23:26 +0200] "GET /remote.php/webdav/Star/LDA-PCA.R HTTP/1.1" 200 2359 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - thomas [18/Aug/2016:16:23:26 +0200] "OPTIONS /remote.php/dav/principals/users/thomas/ HTTP/1.1" 200 0 "-" "Mac OS X/10.11.6 (15G31) AddressBook/1679.10"
131.220.239.200 - - [18/Aug/2016:16:23:26 +0200] "PROPFIND /remote.php/webdav/BlackBerry/Backups/Device/photos/WhatsApp/2016-06/ HTTP/1.1" 207 18036 "-" "android-cloud-api - Android 4.3"
192.168.1.1 - thomas [18/Aug/2016:16:23:27 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 385 "-" "Mozilla/5.0 (Macintosh) mirall/2.2.3 (build 3601)"
192.168.1.1 - - [18/Aug/2016:16:23:28 +0200] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 85 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:30 +0200] "GET /apps/activity/api/v2/activity/filter?format=json&object_type=files&object_id=70486 HTTP/1.1" 200 706 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:30 +0200] "GET /core/preview.png?file=%2FStar%2FLDA-PCA.R&x=150&y=150&c=f512c66f51b76ae43a33f89708f64b21&forceIcon=0 HTTP/1.1" 404 6804 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:30 +0200] "PROPFIND /remote.php/dav/systemtags-relations/files/70486 HTTP/1.1" 207 562 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:31 +0200] "GET /avatar/thomas/56 HTTP/1.1" 200 42 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:31 +0200] "REPORT /remote.php/dav/comments/files/70486/ HTTP/1.1" 207 259 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:32 +0200] "GET /ocs/v2.php/apps/files_sharing/api/v1/shares?format=json&path=%2FStar%2FLDA-PCA.R&reshares=true HTTP/1.1" 200 85 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:32 +0200] "GET /ocs/v2.php/apps/files_sharing/api/v1/shares?format=json&path=%2FStar%2FLDA-PCA.R&shared_with_me=true HTTP/1.1" 200 85 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - thomas [18/Aug/2016:16:23:33 +0200] "PROPFIND /remote.php/dav/principals/users/thomas/ HTTP/1.1" 207 1532 "-" "Mac OS X/10.11.6 (15G31) AddressBook/1679.10"
192.168.1.1 - - [18/Aug/2016:16:23:33 +0200] "PROPFIND /remote.php/dav/addressbooks/users/thomas/ HTTP/1.1" 401 426 "-" "Mac OS X/10.11.6 (15G31) AddressBook/1679.10"
192.168.1.1 - - [18/Aug/2016:16:23:33 +0200] "GET /apps/files_versions/ajax/getVersions.php?source=%2FStar%2FLDA-PCA.R&start=0 HTTP/1.1" 200 302 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:33 +0200] "GET /apps/files_versions/preview?file=%2FStar%2FLDA-PCA.R&version=1471423014 HTTP/1.1" 200 243 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
131.220.239.200 - - [18/Aug/2016:16:23:33 +0200] "PROPFIND /remote.php/webdav/BlackBerry/Backups/Device/photos/WhatsApp/2016-07/ HTTP/1.1" 207 85522 "-" "android-cloud-api - Android 4.3"
192.168.1.1 - thomas [18/Aug/2016:16:23:33 +0200] "PROPFIND /remote.php/dav/addressbooks/users/thomas/ HTTP/1.1" 207 3989 "-" "Mac OS X/10.11.6 (15G31) AddressBook/1679.10"
192.168.1.1 - thomas [18/Aug/2016:16:23:33 +0200] "REPORT /remote.php/dav/addressbooks/users/thomas/default/ HTTP/1.1" 207 332 "-" "Mac OS X/10.11.6 (15G31) AddressBook/1679.10"
192.168.1.1 - - [18/Aug/2016:16:23:34 +0200] "GET /apps/files_versions/download.php?file=%2FStar%2FLDA-PCA.R&revision=1471423014 HTTP/1.1" 503 9112 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
131.220.239.200 - - [18/Aug/2016:16:23:50 +0200] "PROPFIND /remote.php/webdav/BlackBerry/Backups/Device/photos/WhatsApp/2016-08/ HTTP/1.1" 207 15047 "-" "android-cloud-api - Android 4.3"
192.168.1.1 - - [18/Aug/2016:16:23:50 +0200] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 85 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:51 +0200] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 85 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.1 - - [18/Aug/2016:16:23:51 +0200] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 85 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
</details>
#### Nextcloud log (data/nextcloud.log)

<details>
{"reqId":"xGQgGELJMyWDosfN8zQL","remoteAddr":"192.168.1.1","app":"no app in context","message":"Exception: {\"Exception\":\"OC\\Encryption\\Exceptions\\DecryptionFailedException\",\"Message\":\"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/encryption.php(573): OCA\\Encryption\\Crypto\\Encryption->decrypt('require(MASS)\\nr...', '0end')\n#1 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/encryption.php(492): OC\\Files\\Storage\\Wrapper\\Encryption->fixUnencryptedSize('files_versions\\/...', 2077, 2077)\n#2 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/encryption.php(161): OC\\Files\\Storage\\Wrapper\\Encryption->verifyUnencryptedSize('files_versions\\/...', 2077)\n#3 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/encryption.php(400): OC\\Files\\Storage\\Wrapper\\Encryption->filesize('files_versions\\/...')\n#4 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/wrapper.php(287): OC\\Files\\Storage\\Wrapper\\Encryption->fopen('files_versions\\/...', 'rb')\n#5 \\/var\\/www\\/html\\/lib\\/private\\/files\\/view.php(1095): OC\\Files\\Storage\\Wrapper\\Wrapper->fopen('files_versions\\/...', 'rb')\n#6 \\/var\\/www\\/html\\/lib\\/private\\/files\\/view.php(943): OC\\Files\\View->basicOperation('fopen', 'thomas\\/files_ve...', Array, 'rb')\n#7 \\/var\\/www\\/html\\/lib\\/private\\/files\\/view.php(414): OC\\Files\\View->fopen('\\/thomas\\/files_v...', 'rb')\n#8 \\/var\\/www\\/html\\/apps\\/files_versions\\/download.php(48): OC\\Files\\View->readfile('\\/thomas\\/files_v...')\n#9 \\/var\\/www\\/html\\/lib\\/private\\/route\\/route.php(154) : runtime-created function(1): require_once('\\/var\\/www\\/html\\/a...')\n#10 [internal function]: __lambda_func()\n#11 \\/var\\/www\\/html\\/lib\\/private\\/route\\/router.php(276): call_user_func('\\x00lambda_907', Array)\n#12 \\/var\\/www\\/html\\/lib\\/base.php(967): OC\\Route\\Router->match('\\/apps\\/files_ver...')\n#13 \\/var\\/www\\/html\\/index.php(39): OC::handleRequest()\n#14 {main}\",\"File\":\"\\/var\\/www\\/html\\/apps\\/encryption\\/lib\\/crypto\\/encryption.php\",\"Line\":360}","level":3,"time":"2016-08-18T15:16:05+02:00","method":"GET","url":"\/apps\/files_versions\/download.php?file=%2FStar%2FLDA-PCA.R&revision=1471423014","user":"thomas"}
{"reqId":"xGQgGELJMyWDosfN8zQL","remoteAddr":"192.168.1.1","app":"PHP","message":"fread(): Length parameter must be greater than 0 at \/var\/www\/html\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#83","level":3,"time":"2016-08-18T15:16:05+02:00","method":"GET","url":"\/apps\/files_versions\/download.php?file=%2FStar%2FLDA-PCA.R&revision=1471423014","user":"thomas"}
{"reqId":"xGQgGELJMyWDosfN8zQL","remoteAddr":"192.168.1.1","app":"no app in context","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"2016-08-18T15:16:05+02:00","method":"GET","url":"\/apps\/files_versions\/download.php?file=%2FStar%2FLDA-PCA.R&revision=1471423014","user":"thomas"}
{"reqId":"FNi5jwiMKePxVapUl+uy","remoteAddr":"192.168.1.1","app":"no app in context","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"2016-08-18T15:16:29+02:00","method":"GET","url":"\/apps\/files_versions\/ajax\/getVersions.php?source=%2FStar%2FLDA-PCA.R&start=0","user":"thomas"}
{"reqId":"FNi5jwiMKePxVapUl+uy","remoteAddr":"192.168.1.1","app":"no app in context","message":"Couldn't re-calculate unencrypted size for files_versions\/Star\/LDA-PCA.R.v1471423014","level":3,"time":"2016-08-18T15:16:29+02:00","method":"GET","url":"\/apps\/files_versions\/ajax\/getVersions.php?source=%2FStar%2FLDA-PCA.R&start=0","user":"thomas"}
{"reqId":"FNi5jwiMKePxVapUl+uy","remoteAddr":"192.168.1.1","app":"no app in context","message":"Exception: {\"Exception\":\"OC\\Encryption\\Exceptions\\DecryptionFailedException\",\"Message\":\"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/encryption.php(573): OCA\\Encryption\\Crypto\\Encryption->decrypt('require(MASS)\\nr...', '0end')\n#1 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/encryption.php(492): OC\\Files\\Storage\\Wrapper\\Encryption->fixUnencryptedSize('files_versions\\/...', 2077, 2077)\n#2 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/encryption.php(161): OC\\Files\\Storage\\Wrapper\\Encryption->verifyUnencryptedSize('files_versions\\/...', 2077)\n#3 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/wrapper.php(142): OC\\Files\\Storage\\Wrapper\\Encryption->filesize('files_versions\\/...')\n#4 \\/var\\/www\\/html\\/lib\\/private\\/files\\/view.php(1097): OC\\Files\\Storage\\Wrapper\\Wrapper->filesize('files_versions\\/...')\n#5 \\/var\\/www\\/html\\/lib\\/private\\/files\\/view.php(403): OC\\Files\\View->basicOperation('filesize', 'files_versions\\/...')\n#6 \\/var\\/www\\/html\\/apps\\/files_versions\\/lib\\/storage.php(465): OC\\Files\\View->filesize('\\/files_versions...')\n#7 \\/var\\/www\\/html\\/apps\\/files_versions\\/ajax\\/getVersions.php(34): OCA\\Files_Versions\\Storage::getVersions('thomas', 'LDA-PCA.R', '\\/Star\\/LDA-PCA.R')\n#8 \\/var\\/www\\/html\\/lib\\/private\\/route\\/route.php(154) : runtime-created function(1): require_once('\\/var\\/www\\/html\\/a...')\n#9 [internal function]: __lambda_func()\n#10 \\/var\\/www\\/html\\/lib\\/private\\/route\\/router.php(276): call_user_func('\\x00lambda_7202', Array)\n#11 \\/var\\/www\\/html\\/lib\\/base.php(967): OC\\Route\\Router->match('\\/apps\\/files_ver...')\n#12 \\/var\\/www\\/html\\/index.php(39): OC::handleRequest()\n#13 {main}\",\"File\":\"\\/var\\/www\\/html\\/apps\\/encryption\\/lib\\/crypto\\/encryption.php\",\"Line\":360}","level":3,"time":"2016-08-18T15:16:29+02:00","method":"GET","url":"\/apps\/files_versions\/ajax\/getVersions.php?source=%2FStar%2FLDA-PCA.R&start=0","user":"thomas"}
{"reqId":"svC7C0Ly4GDHGLQOj2Iy","remoteAddr":"192.168.1.1","app":"no app in context","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"2016-08-18T15:16:30+02:00","method":"GET","url":"\/apps\/files_versions\/download.php?file=%2FStar%2FLDA-PCA.R&revision=1471423014","user":"thomas"}
{"reqId":"svC7C0Ly4GDHGLQOj2Iy","remoteAddr":"192.168.1.1","app":"no app in context","message":"Couldn't re-calculate unencrypted size for files_versions\/Star\/LDA-PCA.R.v1471423014","level":3,"time":"2016-08-18T15:16:30+02:00","method":"GET","url":"\/apps\/files_versions\/download.php?file=%2FStar%2FLDA-PCA.R&revision=1471423014","user":"thomas"}
{"reqId":"svC7C0Ly4GDHGLQOj2Iy","remoteAddr":"192.168.1.1","app":"no app in context","message":"Exception: {\"Exception\":\"OC\\Encryption\\Exceptions\\DecryptionFailedException\",\"Message\":\"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/encryption.php(573): OCA\\Encryption\\Crypto\\Encryption->decrypt('require(MASS)\\nr...', '0end')\n#1 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/encryption.php(492): OC\\Files\\Storage\\Wrapper\\Encryption->fixUnencryptedSize('files_versions\\/...', 2077, 2077)\n#2 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/encryption.php(161): OC\\Files\\Storage\\Wrapper\\Encryption->verifyUnencryptedSize('files_versions\\/...', 2077)\n#3 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/wrapper.php(142): OC\\Files\\Storage\\Wrapper\\Encryption->filesize('files_versions\\/...')\n#4 \\/var\\/www\\/html\\/lib\\/private\\/files\\/view.php(1097): OC\\Files\\Storage\\Wrapper\\Wrapper->filesize('files_versions\\/...')\n#5 \\/var\\/www\\/html\\/lib\\/private\\/files\\/view.php(403): OC\\Files\\View->basicOperation('filesize', 'thomas\\/files_ve...')\n#6 \\/var\\/www\\/html\\/apps\\/files_versions\\/download.php(44): OC\\Files\\View->filesize('\\/thomas\\/files_v...')\n#7 \\/var\\/www\\/html\\/lib\\/private\\/route\\/route.php(154) : runtime-created function(1): require_once('\\/var\\/www\\/html\\/a...')\n#8 [internal function]: __lambda_func()\n#9 \\/var\\/www\\/html\\/lib\\/private\\/route\\/router.php(276): call_user_func('\\x00lambda_1334', Array)\n#10 \\/var\\/www\\/html\\/lib\\/base.php(967): OC\\Route\\Router->match('\\/apps\\/files_ver...')\n#11 \\/var\\/www\\/html\\/index.php(39): OC::handleRequest()\n#12 {main}\",\"File\":\"\\/var\\/www\\/html\\/apps\\/encryption\\/lib\\/crypto\\/encryption.php\",\"Line\":360}","level":3,"time":"2016-08-18T15:16:30+02:00","method":"GET","url":"\/apps\/files_versions\/download.php?file=%2FStar%2FLDA-PCA.R&revision=1471423014","user":"thomas"}
{"reqId":"svC7C0Ly4GDHGLQOj2Iy","remoteAddr":"192.168.1.1","app":"no app in context","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"2016-08-18T15:16:30+02:00","method":"GET","url":"\/apps\/files_versions\/download.php?file=%2FStar%2FLDA-PCA.R&revision=1471423014","user":"thomas"}
{"reqId":"svC7C0Ly4GDHGLQOj2Iy","remoteAddr":"192.168.1.1","app":"no app in context","message":"Couldn't re-calculate unencrypted size for files_versions\/Star\/LDA-PCA.R.v1471423014","level":3,"time":"2016-08-18T15:16:30+02:00","method":"GET","url":"\/apps\/files_versions\/download.php?file=%2FStar%2FLDA-PCA.R&revision=1471423014","user":"thomas"}
{"reqId":"svC7C0Ly4GDHGLQOj2Iy","remoteAddr":"192.168.1.1","app":"no app in context","message":"Exception: {\"Exception\":\"OC\\Encryption\\Exceptions\\DecryptionFailedException\",\"Message\":\"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/encryption.php(573): OCA\\Encryption\\Crypto\\Encryption->decrypt('require(MASS)\\nr...', '0end')\n#1 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/encryption.php(492): OC\\Files\\Storage\\Wrapper\\Encryption->fixUnencryptedSize('files_versions\\/...', 2077, 2077)\n#2 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/encryption.php(161): OC\\Files\\Storage\\Wrapper\\Encryption->verifyUnencryptedSize('files_versions\\/...', 2077)\n#3 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/encryption.php(400): OC\\Files\\Storage\\Wrapper\\Encryption->filesize('files_versions\\/...')\n#4 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/wrapper.php(287): OC\\Files\\Storage\\Wrapper\\Encryption->fopen('files_versions\\/...', 'rb')\n#5 \\/var\\/www\\/html\\/lib\\/private\\/files\\/view.php(1095): OC\\Files\\Storage\\Wrapper\\Wrapper->fopen('files_versions\\/...', 'rb')\n#6 \\/var\\/www\\/html\\/lib\\/private\\/files\\/view.php(943): OC\\Files\\View->basicOperation('fopen', 'thomas\\/files_ve...', Array, 'rb')\n#7 \\/var\\/www\\/html\\/lib\\/private\\/files\\/view.php(414): OC\\Files\\View->fopen('\\/thomas\\/files_v...', 'rb')\n#8 \\/var\\/www\\/html\\/apps\\/files_versions\\/download.php(48): OC\\Files\\View->readfile('\\/thomas\\/files_v...')\n#9 \\/var\\/www\\/html\\/lib\\/private\\/route\\/route.php(154) : runtime-created function(1): require_once('\\/var\\/www\\/html\\/a...')\n#10 [internal function]: __lambda_func()\n#11 \\/var\\/www\\/html\\/lib\\/private\\/route\\/router.php(276): call_user_func('\\x00lambda_1334', Array)\n#12 \\/var\\/www\\/html\\/lib\\/base.php(967): OC\\Route\\Router->match('\\/apps\\/files_ver...')\n#13 \\/var\\/www\\/html\\/index.php(39): OC::handleRequest()\n#14 {main}\",\"File\":\"\\/var\\/www\\/html\\/apps\\/encryption\\/lib\\/crypto\\/encryption.php\",\"Line\":360}","level":3,"time":"2016-08-18T15:16:30+02:00","method":"GET","url":"\/apps\/files_versions\/download.php?file=%2FStar%2FLDA-PCA.R&revision=1471423014","user":"thomas"}
{"reqId":"svC7C0Ly4GDHGLQOj2Iy","remoteAddr":"192.168.1.1","app":"PHP","message":"fread(): Length parameter must be greater than 0 at \/var\/www\/html\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#83","level":3,"time":"2016-08-18T15:16:30+02:00","method":"GET","url":"\/apps\/files_versions\/download.php?file=%2FStar%2FLDA-PCA.R&revision=1471423014","user":"thomas"}
{"reqId":"svC7C0Ly4GDHGLQOj2Iy","remoteAddr":"192.168.1.1","app":"no app in context","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"2016-08-18T15:16:30+02:00","method":"GET","url":"\/apps\/files_versions\/download.php?file=%2FStar%2FLDA-PCA.R&revision=1471423014","user":"thomas"}
{"reqId":"Un8gkF+fjRAv0RuwJcgL","remoteAddr":"192.168.1.1","app":"no app in context","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"2016-08-18T15:16:36+02:00","method":"GET","url":"\/apps\/files_versions\/download.php?file=%2FStar%2FLDA-PCA.R&revision=1471423014","user":"thomas"}
{"reqId":"Un8gkF+fjRAv0RuwJcgL","remoteAddr":"192.168.1.1","app":"no app in context","message":"Couldn't re-calculate unencrypted size for files_versions\/Star\/LDA-PCA.R.v1471423014","level":3,"time":"2016-08-18T15:16:36+02:00","method":"GET","url":"\/apps\/files_versions\/download.php?file=%2FStar%2FLDA-PCA.R&revision=1471423014","user":"thomas"}
{"reqId":"Un8gkF+fjRAv0RuwJcgL","remoteAddr":"192.168.1.1","app":"no app in context","message":"Exception: {\"Exception\":\"OC\\Encryption\\Exceptions\\DecryptionFailedException\",\"Message\":\"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/encryption.php(573): OCA\\Encryption\\Crypto\\Encryption->decrypt('require(MASS)\\nr...', '0end')\n#1 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/encryption.php(492): OC\\Files\\Storage\\Wrapper\\Encryption->fixUnencryptedSize('files_versions\\/...', 2077, 2077)\n#2 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/encryption.php(161): OC\\Files\\Storage\\Wrapper\\Encryption->verifyUnencryptedSize('files_versions\\/...', 2077)\n#3 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/wrapper.php(142): OC\\Files\\Storage\\Wrapper\\Encryption->filesize('files_versions\\/...')\n#4 \\/var\\/www\\/html\\/lib\\/private\\/files\\/view.php(1097): OC\\Files\\Storage\\Wrapper\\Wrapper->filesize('files_versions\\/...')\n#5 \\/var\\/www\\/html\\/lib\\/private\\/files\\/view.php(403): OC\\Files\\View->basicOperation('filesize', 'thomas\\/files_ve...')\n#6 \\/var\\/www\\/html\\/apps\\/files_versions\\/download.php(44): OC\\Files\\View->filesize('\\/thomas\\/files_v...')\n#7 \\/var\\/www\\/html\\/lib\\/private\\/route\\/route.php(154) : runtime-created function(1): require_once('\\/var\\/www\\/html\\/a...')\n#8 [internal function]: __lambda_func()\n#9 \\/var\\/www\\/html\\/lib\\/private\\/route\\/router.php(276): call_user_func('\\x00lambda_7226', Array)\n#10 \\/var\\/www\\/html\\/lib\\/base.php(967): OC\\Route\\Router->match('\\/apps\\/files_ver...')\n#11 \\/var\\/www\\/html\\/index.php(39): OC::handleRequest()\n#12 {main}\",\"File\":\"\\/var\\/www\\/html\\/apps\\/encryption\\/lib\\/crypto\\/encryption.php\",\"Line\":360}","level":3,"time":"2016-08-18T15:16:36+02:00","method":"GET","url":"\/apps\/files_versions\/download.php?file=%2FStar%2FLDA-PCA.R&revision=1471423014","user":"thomas"}
{"reqId":"Un8gkF+fjRAv0RuwJcgL","remoteAddr":"192.168.1.1","app":"no app in context","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"2016-08-18T15:16:36+02:00","method":"GET","url":"\/apps\/files_versions\/download.php?file=%2FStar%2FLDA-PCA.R&revision=1471423014","user":"thomas"}
{"reqId":"Un8gkF+fjRAv0RuwJcgL","remoteAddr":"192.168.1.1","app":"no app in context","message":"Couldn't re-calculate unencrypted size for files_versions\/Star\/LDA-PCA.R.v1471423014","level":3,"time":"2016-08-18T15:16:36+02:00","method":"GET","url":"\/apps\/files_versions\/download.php?file=%2FStar%2FLDA-PCA.R&revision=1471423014","user":"thomas"}
{"reqId":"Un8gkF+fjRAv0RuwJcgL","remoteAddr":"192.168.1.1","app":"no app in context","message":"Exception: {\"Exception\":\"OC\\Encryption\\Exceptions\\DecryptionFailedException\",\"Message\":\"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/encryption.php(573): OCA\\Encryption\\Crypto\\Encryption->decrypt('require(MASS)\\nr...', '0end')\n#1 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/encryption.php(492): OC\\Files\\Storage\\Wrapper\\Encryption->fixUnencryptedSize('files_versions\\/...', 2077, 2077)\n#2 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/encryption.php(161): OC\\Files\\Storage\\Wrapper\\Encryption->verifyUnencryptedSize('files_versions\\/...', 2077)\n#3 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/encryption.php(400): OC\\Files\\Storage\\Wrapper\\Encryption->filesize('files_versions\\/...')\n#4 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/wrapper.php(287): OC\\Files\\Storage\\Wrapper\\Encryption->fopen('files_versions\\/...', 'rb')\n#5 \\/var\\/www\\/html\\/lib\\/private\\/files\\/view.php(1095): OC\\Files\\Storage\\Wrapper\\Wrapper->fopen('files_versions\\/...', 'rb')\n#6 \\/var\\/www\\/html\\/lib\\/private\\/files\\/view.php(943): OC\\Files\\View->basicOperation('fopen', 'thomas\\/files_ve...', Array, 'rb')\n#7 \\/var\\/www\\/html\\/lib\\/private\\/files\\/view.php(414): OC\\Files\\View->fopen('\\/thomas\\/files_v...', 'rb')\n#8 \\/var\\/www\\/html\\/apps\\/files_versions\\/download.php(48): OC\\Files\\View->readfile('\\/thomas\\/files_v...')\n#9 \\/var\\/www\\/html\\/lib\\/private\\/route\\/route.php(154) : runtime-created function(1): require_once('\\/var\\/www\\/html\\/a...')\n#10 [internal function]: __lambda_func()\n#11 \\/var\\/www\\/html\\/lib\\/private\\/route\\/router.php(276): call_user_func('\\x00lambda_7226', Array)\n#12 \\/var\\/www\\/html\\/lib\\/base.php(967): OC\\Route\\Router->match('\\/apps\\/files_ver...')\n#13 \\/var\\/www\\/html\\/index.php(39): OC::handleRequest()\n#14 {main}\",\"File\":\"\\/var\\/www\\/html\\/apps\\/encryption\\/lib\\/crypto\\/encryption.php\",\"Line\":360}","level":3,"time":"2016-08-18T15:16:36+02:00","method":"GET","url":"\/apps\/files_versions\/download.php?file=%2FStar%2FLDA-PCA.R&revision=1471423014","user":"thomas"}
{"reqId":"Un8gkF+fjRAv0RuwJcgL","remoteAddr":"192.168.1.1","app":"PHP","message":"fread(): Length parameter must be greater than 0 at \/var\/www\/html\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#83","level":3,"time":"2016-08-18T15:16:36+02:00","method":"GET","url":"\/apps\/files_versions\/download.php?file=%2FStar%2FLDA-PCA.R&revision=1471423014","user":"thomas"}
{"reqId":"Un8gkF+fjRAv0RuwJcgL","remoteAddr":"192.168.1.1","app":"no app in context","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"2016-08-18T15:16:36+02:00","method":"GET","url":"\/apps\/files_versions\/download.php?file=%2FStar%2FLDA-PCA.R&revision=1471423014","user":"thomas"}
{"reqId":"py1p0gyvZFpB9oN6Qzgh","remoteAddr":"","app":"PHP","message":"Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) at \/var\/www\/html\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#128","level":3,"time":"2016-08-18T15:45:02+02:00","method":"--","url":"--","user":"--"}
{"reqId":"jy69bA00H2BWu73jbZ1u","remoteAddr":"192.168.1.1","app":"no app in context","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"2016-08-18T16:23:33+02:00","method":"GET","url":"\/apps\/files_versions\/ajax\/getVersions.php?source=%2FStar%2FLDA-PCA.R&start=0","user":"thomas"}
{"reqId":"jy69bA00H2BWu73jbZ1u","remoteAddr":"192.168.1.1","app":"no app in context","message":"Couldn't re-calculate unencrypted size for files_versions\/Star\/LDA-PCA.R.v1471423014","level":3,"time":"2016-08-18T16:23:33+02:00","method":"GET","url":"\/apps\/files_versions\/ajax\/getVersions.php?source=%2FStar%2FLDA-PCA.R&start=0","user":"thomas"}
{"reqId":"jy69bA00H2BWu73jbZ1u","remoteAddr":"192.168.1.1","app":"no app in context","message":"Exception: {\"Exception\":\"OC\\Encryption\\Exceptions\\DecryptionFailedException\",\"Message\":\"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/encryption.php(573): OCA\\Encryption\\Crypto\\Encryption->decrypt('require(MASS)\\nr...', '0end')\n#1 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/encryption.php(492): OC\\Files\\Storage\\Wrapper\\Encryption->fixUnencryptedSize('files_versions\\/...', 2077, 2077)\n#2 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/encryption.php(161): OC\\Files\\Storage\\Wrapper\\Encryption->verifyUnencryptedSize('files_versions\\/...', 2077)\n#3 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/wrapper.php(142): OC\\Files\\Storage\\Wrapper\\Encryption->filesize('files_versions\\/...')\n#4 \\/var\\/www\\/html\\/lib\\/private\\/files\\/view.php(1097): OC\\Files\\Storage\\Wrapper\\Wrapper->filesize('files_versions\\/...')\n#5 \\/var\\/www\\/html\\/lib\\/private\\/files\\/view.php(403): OC\\Files\\View->basicOperation('filesize', 'files_versions\\/...')\n#6 \\/var\\/www\\/html\\/apps\\/files_versions\\/lib\\/storage.php(465): OC\\Files\\View->filesize('\\/files_versions...')\n#7 \\/var\\/www\\/html\\/apps\\/files_versions\\/ajax\\/getVersions.php(34): OCA\\Files_Versions\\Storage::getVersions('thomas', 'LDA-PCA.R', '\\/Star\\/LDA-PCA.R')\n#8 \\/var\\/www\\/html\\/lib\\/private\\/route\\/route.php(154) : runtime-created function(1): require_once('\\/var\\/www\\/html\\/a...')\n#9 [internal function]: __lambda_func()\n#10 \\/var\\/www\\/html\\/lib\\/private\\/route\\/router.php(276): call_user_func('\\x00lambda_5178', Array)\n#11 \\/var\\/www\\/html\\/lib\\/base.php(967): OC\\Route\\Router->match('\\/apps\\/files_ver...')\n#12 \\/var\\/www\\/html\\/index.php(39): OC::handleRequest()\n#13 {main}\",\"File\":\"\\/var\\/www\\/html\\/apps\\/encryption\\/lib\\/crypto\\/encryption.php\",\"Line\":360}","level":3,"time":"2016-08-18T16:23:33+02:00","method":"GET","url":"\/apps\/files_versions\/ajax\/getVersions.php?source=%2FStar%2FLDA-PCA.R&start=0","user":"thomas"}
{"reqId":"Zb3OpcOLqbOLyZM0v21p","remoteAddr":"192.168.1.1","app":"no app in context","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"2016-08-18T16:23:34+02:00","method":"GET","url":"\/apps\/files_versions\/download.php?file=%2FStar%2FLDA-PCA.R&revision=1471423014","user":"thomas"}
{"reqId":"Zb3OpcOLqbOLyZM0v21p","remoteAddr":"192.168.1.1","app":"no app in context","message":"Couldn't re-calculate unencrypted size for files_versions\/Star\/LDA-PCA.R.v1471423014","level":3,"time":"2016-08-18T16:23:34+02:00","method":"GET","url":"\/apps\/files_versions\/download.php?file=%2FStar%2FLDA-PCA.R&revision=1471423014","user":"thomas"}
{"reqId":"Zb3OpcOLqbOLyZM0v21p","remoteAddr":"192.168.1.1","app":"no app in context","message":"Exception: {\"Exception\":\"OC\\Encryption\\Exceptions\\DecryptionFailedException\",\"Message\":\"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/encryption.php(573): OCA\\Encryption\\Crypto\\Encryption->decrypt('require(MASS)\\nr...', '0end')\n#1 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/encryption.php(492): OC\\Files\\Storage\\Wrapper\\Encryption->fixUnencryptedSize('files_versions\\/...', 2077, 2077)\n#2 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/encryption.php(161): OC\\Files\\Storage\\Wrapper\\Encryption->verifyUnencryptedSize('files_versions\\/...', 2077)\n#3 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/wrapper.php(142): OC\\Files\\Storage\\Wrapper\\Encryption->filesize('files_versions\\/...')\n#4 \\/var\\/www\\/html\\/lib\\/private\\/files\\/view.php(1097): OC\\Files\\Storage\\Wrapper\\Wrapper->filesize('files_versions\\/...')\n#5 \\/var\\/www\\/html\\/lib\\/private\\/files\\/view.php(403): OC\\Files\\View->basicOperation('filesize', 'thomas\\/files_ve...')\n#6 \\/var\\/www\\/html\\/apps\\/files_versions\\/download.php(44): OC\\Files\\View->filesize('\\/thomas\\/files_v...')\n#7 \\/var\\/www\\/html\\/lib\\/private\\/route\\/route.php(154) : runtime-created function(1): require_once('\\/var\\/www\\/html\\/a...')\n#8 [internal function]: __lambda_func()\n#9 \\/var\\/www\\/html\\/lib\\/private\\/route\\/router.php(276): call_user_func('\\x00lambda_5227', Array)\n#10 \\/var\\/www\\/html\\/lib\\/base.php(967): OC\\Route\\Router->match('\\/apps\\/files_ver...')\n#11 \\/var\\/www\\/html\\/index.php(39): OC::handleRequest()\n#12 {main}\",\"File\":\"\\/var\\/www\\/html\\/apps\\/encryption\\/lib\\/crypto\\/encryption.php\",\"Line\":360}","level":3,"time":"2016-08-18T16:23:34+02:00","method":"GET","url":"\/apps\/files_versions\/download.php?file=%2FStar%2FLDA-PCA.R&revision=1471423014","user":"thomas"}
{"reqId":"Zb3OpcOLqbOLyZM0v21p","remoteAddr":"192.168.1.1","app":"no app in context","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"2016-08-18T16:23:34+02:00","method":"GET","url":"\/apps\/files_versions\/download.php?file=%2FStar%2FLDA-PCA.R&revision=1471423014","user":"thomas"}
{"reqId":"Zb3OpcOLqbOLyZM0v21p","remoteAddr":"192.168.1.1","app":"no app in context","message":"Couldn't re-calculate unencrypted size for files_versions\/Star\/LDA-PCA.R.v1471423014","level":3,"time":"2016-08-18T16:23:34+02:00","method":"GET","url":"\/apps\/files_versions\/download.php?file=%2FStar%2FLDA-PCA.R&revision=1471423014","user":"thomas"}
{"reqId":"Zb3OpcOLqbOLyZM0v21p","remoteAddr":"192.168.1.1","app":"no app in context","message":"Exception: {\"Exception\":\"OC\\Encryption\\Exceptions\\DecryptionFailedException\",\"Message\":\"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/encryption.php(573): OCA\\Encryption\\Crypto\\Encryption->decrypt('require(MASS)\\nr...', '0end')\n#1 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/encryption.php(492): OC\\Files\\Storage\\Wrapper\\Encryption->fixUnencryptedSize('files_versions\\/...', 2077, 2077)\n#2 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/encryption.php(161): OC\\Files\\Storage\\Wrapper\\Encryption->verifyUnencryptedSize('files_versions\\/...', 2077)\n#3 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/encryption.php(400): OC\\Files\\Storage\\Wrapper\\Encryption->filesize('files_versions\\/...')\n#4 \\/var\\/www\\/html\\/lib\\/private\\/files\\/storage\\/wrapper\\/wrapper.php(287): OC\\Files\\Storage\\Wrapper\\Encryption->fopen('files_versions\\/...', 'rb')\n#5 \\/var\\/www\\/html\\/lib\\/private\\/files\\/view.php(1095): OC\\Files\\Storage\\Wrapper\\Wrapper->fopen('files_versions\\/...', 'rb')\n#6 \\/var\\/www\\/html\\/lib\\/private\\/files\\/view.php(943): OC\\Files\\View->basicOperation('fopen', 'thomas\\/files_ve...', Array, 'rb')\n#7 \\/var\\/www\\/html\\/lib\\/private\\/files\\/view.php(414): OC\\Files\\View->fopen('\\/thomas\\/files_v...', 'rb')\n#8 \\/var\\/www\\/html\\/apps\\/files_versions\\/download.php(48): OC\\Files\\View->readfile('\\/thomas\\/files_v...')\n#9 \\/var\\/www\\/html\\/lib\\/private\\/route\\/route.php(154) : runtime-created function(1): require_once('\\/var\\/www\\/html\\/a...')\n#10 [internal function]: __lambda_func()\n#11 \\/var\\/www\\/html\\/lib\\/private\\/route\\/router.php(276): call_user_func('\\x00lambda_5227', Array)\n#12 \\/var\\/www\\/html\\/lib\\/base.php(967): OC\\Route\\Router->match('\\/apps\\/files_ver...')\n#13 \\/var\\/www\\/html\\/index.php(39): OC::handleRequest()\n#14 {main}\",\"File\":\"\\/var\\/www\\/html\\/apps\\/encryption\\/lib\\/crypto\\/encryption.php\",\"Line\":360}","level":3,"time":"2016-08-18T16:23:34+02:00","method":"GET","url":"\/apps\/files_versions\/download.php?file=%2FStar%2FLDA-PCA.R&revision=1471423014","user":"thomas"}
{"reqId":"Zb3OpcOLqbOLyZM0v21p","remoteAddr":"192.168.1.1","app":"PHP","message":"fread(): Length parameter must be greater than 0 at \/var\/www\/html\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#83","level":3,"time":"2016-08-18T16:23:34+02:00","method":"GET","url":"\/apps\/files_versions\/download.php?file=%2FStar%2FLDA-PCA.R&revision=1471423014","user":"thomas"}
{"reqId":"Zb3OpcOLqbOLyZM0v21p","remoteAddr":"192.168.1.1","app":"no app in context","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"2016-08-18T16:23:34+02:00","method":"GET","url":"\/apps\/files_versions\/download.php?file=%2FStar%2FLDA-PCA.R&revision=1471423014","user":"thomas"}
</details>
#### Produced File

<details>
<summary>

Produced File</summary>

`<!DOCTYPE html>`
`<!--[if lte IE 8]><html class="ng-csp ie ie8 lte9 lte8" data-placeholder-focus="false" lang="en" ><![endif]-->`
`<!--[if IE 9]><html class="ng-csp ie ie9 lte9" data-placeholder-focus="false" lang="en" ><![endif]-->`
`<!--[if (gt IE 9)|!(IE)]><!--><html class="ng-csp" data-placeholder-focus="false" lang="en" ><!--<![endif]-->`
    `<head data-requesttoken="">`
        `<meta charset="utf-8">`
        `<title>`
        `Nextcloud      </title>`
        `<meta http-equiv="X-UA-Compatible" content="IE=edge">`
        `<meta name="referrer" content="never">`
        `<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">`
        `<meta name="apple-itunes-app" content="app-id=1125420102">`
        `<meta name="theme-color" content="#0082c9">`
        `<link rel="shortcut icon" href="/core/img/favicon.ico">`
        `<link rel="apple-touch-icon-precomposed" href="/core/img/favicon-touch.png">`
        `<link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#1d2d44">`
                    `<link rel="stylesheet" href="/core/css/styles.css?v=d69f3e669ec28ffdfb6b442415f07579" media="screen">
                    <link rel="stylesheet" href="/core/css/inputs.css?v=d69f3e669ec28ffdfb6b442415f07579" media="screen">
                    <link rel="stylesheet" href="/core/css/header.css?v=d69f3e669ec28ffdfb6b442415f07579" media="screen">
                    <link rel="stylesheet" href="/core/css/mobile.css?v=d69f3e669ec28ffdfb6b442415f07579" media="screen">
                    <link rel="stylesheet" href="/core/css/icons.css?v=d69f3e669ec28ffdfb6b442415f07579" media="screen">
                    <link rel="stylesheet" href="/core/css/fonts.css?v=d69f3e669ec28ffdfb6b442415f07579" media="screen">
                    <link rel="stylesheet" href="/core/css/apps.css?v=d69f3e669ec28ffdfb6b442415f07579" media="screen">
                    <link rel="stylesheet" href="/core/css/global.css?v=d69f3e669ec28ffdfb6b442415f07579" media="screen">
                    <link rel="stylesheet" href="/core/css/fixes.css?v=d69f3e669ec28ffdfb6b442415f07579" media="screen">
                    <link rel="stylesheet" href="/core/css/multiselect.css?v=d69f3e669ec28ffdfb6b442415f07579" media="screen">
                    <link rel="stylesheet" href="/core/vendor/jquery-ui/theme
`
</details>

### PR DESCRIPTION
**Pull request by schiessle**
steps to test:

1. encryption server-side-encryption
2. enable default encryption module
3. disable "Encrypt the home storage" in the admin settings "encryption"
4. upload the same file multiple times (so that versions get created)
5. go to the sidebar and try to download a version

Result:

failure, because "encrypted" is set to >0 in the file cache and therefore we try to decrypt the file even if it is not encrypted.

Expected behavior:

File gets downloaded correctly

fix https://github.com/nextcloud/server/issues/940

cc @bronk0

### CODE REVIEW

**Comment by schiessle** [comment]
failing tests can be ignored... please review @LukasReschke @nickvergessen,...

**Comment by schiessle** [comment]
Who wants to review this... @icewind1991 @MorrisJobke @ChristophWurst ...

File: lib/private/Files/Storage/Wrapper/Encryption.php [hunk 1]
```diff
@@ -991,4 +992,31 @@ protected function isVersion($path) {
...
+		}
+
+		try {
+			$encryptionModule = $this->getEncryptionModule($fullPath);
+		} catch (ModuleDoesNotExistsException $e) {
+			return false;
+		}
+
+		if ($encryptionModule === null) {
+			$encryptionModule = $this->encryptionManager->getEncryptionModule();
```
Comment (ChristophWurst) [inline lib/private/Files/Storage/Wrapper/Encryption.php]: will this always return an object or could this call also return `null`?

Comment (schiessle) [inline lib/private/Files/Storage/Wrapper/Encryption.php]: it will always return a encryption module or throw a exception.

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by MorrisJobke** [comment]
The reporter also tested this successfully: https://github.com/nextcloud/server/issues/940#issuecomment-264703013

-> merge
