### PR TITLE
fix(CalDAV): add calendar enable

### LINKED ISSUE #6767: Calendar dashboard widget is showing me events of hidden calendars
### Steps to reproduce

Image

Just noticing that the calendar dashboard widget is showing me events of hidden calendars. For instance, I have three lunch breaks and three sales meetings planned in the next hours 🙃

### Expected behavior

Dashboard widget should show me event only for displaed calendars

### Actual behavior

Calendar dashboard widget is showing me events of hidden calendars

### Calendar app version

_No response_

### CalDAV-clients used

_No response_

### Browser

_No response_

### Client operating system

_No response_

### Server operating system

_No response_

### Web server

None

### Database engine version

None

### PHP engine version

None

### Nextcloud version

31

### Updated from an older installed version or fresh install

None

### List of activated apps

```Text

```

### Nextcloud configuration

```Text

```

### Web server error log

```Text

```

### Log file

```Text

```

### Browser log

```Text

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by SebastianKrupinski**
* Resolves: https://github.com/nextcloud/calendar/issues/6767

## Summary
- Adds ICalendarEnabled extension interface
- Adds Dav property redirection from properties table to calendars table
- Adds migration of property settings from properties table to calendars table

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/dav/lib/Migration/Version1032Date20250226000000.php [hunk 1]
```diff
@@ -0,0 +1,129 @@
...
+						$queryInner->createParameter('principle_prefix_length')
+					),
+					$queryInner->createParameter('uri_separator'),
+					$queryInner->prefixTableName('calendars') . '.uri'
+				)
+			));
+		$queryOuter->update('calendars')
+			->set(
+				$queryOuter->prefixTableName('calendars') . '.enabled',
+				$queryOuter->createFunction($queryInner->getSQL())
```
Comment (nickvergessen) [inline apps/dav/lib/Migration/Version1032Date20250226000000.php:113]:
```suggestion
				$queryOuter->createFunction('(' . $queryInner->getSQL() . ')')
```

Should fix the database error you are seeing.

That being said, the query is so complex and fishy that it should have a unit test. This way it is also ensured it works on all our supported databases

**Review by nickvergessen — DISMISSED** [review]

File: lib/private/DB/QueryBuilder/QueryBuilder.php [hunk 2]
```diff
@@ -838,10 +838,17 @@ public function rightJoin($fromAlias, $join, $alias, $condition = null) {
...
+			$this->queryBuilder->set(
+				$this->helper->quoteColumnName($key),
+				'(' . $value . ')'
+			);
+		} else {
+			$this->queryBuilder->set(
+				$this->helper->quoteColumnName($key),
+				$this->helper->quoteColumnName($value)
+			);
+		}
```
Comment (nickvergessen) [inline lib/private/DB/QueryBuilder/QueryBuilder.php:851]:
```suggestion
		$this->queryBuilder->set(
			$this->helper->quoteColumnName($key),
			$this->helper->quoteColumnName($value)
		);
```

File: apps/dav/lib/Migration/Version1032Date20250226000000.php [hunk 3]
```diff
@@ -0,0 +1,129 @@
...
+		/** @var ISchemaWrapper $schema */
+		$schema = $schemaClosure();
+
+		if (!$schema->hasTable('calendars') || !$schema->hasTable('calendarsubscriptions')) {
+			return;
+		}
+
+		if (!$schema->getTable('calendars')->hasColumn('enabled') || !$schema->getTable('calendarsubscriptions')->hasColumn('enabled')) {
+			return;
+		}
```
Comment (nickvergessen) [inline apps/dav/lib/Migration/Version1032Date20250226000000.php:64]:
```suggestion
```
You just added those columns, so you don't need to check it.

Comment (SebastianKrupinski) [reply apps/dav/lib/Migration/Version1032Date20250226000000.php:64]: Yes, I was just being overly conscious, to prevent migration errors. Removed.

File: apps/dav/lib/Migration/Version1032Date20250226000000.php (hunk 1 above)
Comment (SebastianKrupinski) [reply apps/dav/lib/Migration/Version1032Date20250226000000.php:113]: That worked! Wrapping it in bracket's fixed the quotes problem. Thank you

File: lib/private/DB/QueryBuilder/QueryBuilder.php (hunk 2 above)
Comment (SebastianKrupinski) [reply lib/private/DB/QueryBuilder/QueryBuilder.php:851]: Done. No longer needed.

File: apps/dav/lib/Migration/Version1032Date20250226000000.php (hunk 1 above)
Comment (SebastianKrupinski) [reply apps/dav/lib/Migration/Version1032Date20250226000000.php]: Had to abort this idea due to shared calendars.

File: lib/private/DB/QueryBuilder/QueryBuilder.php (hunk 2 above)
Comment (SebastianKrupinski) [reply lib/private/DB/QueryBuilder/QueryBuilder.php]: Had to abort this idea due to shared calendars.

File: apps/dav/lib/CalDAV/CalendarProvider.php [hunk 4]
```diff
@@ -44,4 +48,23 @@ public function getCalendars(string $principalUri, array $calendarUris = []): ar
...
+		$user = str_replace('principals/users/', '', $principalUri);
+		$path = 'calendars/' . $user . '/' . $calendarUri;
+
+		$properties = $this->propertyMapper->findPropertiesByPath($user, $path);
+
+		$list = [];
+		foreach ($properties as $property) {
+			if ($property instanceof Property) {
+				$list[$property->getPropertyname()] = match ($property->getPropertyname()) {
+					'{http://owncloud.org/ns}calendar-enabled' => (bool)$property->getPropertyvalue(),
```
Comment (tcitworld) [inline apps/dav/lib/CalDAV/CalendarProvider.php:62]: I don't like having the deserialization logic here duplicating what's done in `CustomPropertiesBackend::decodeValueFromDatabase`. Maybe the whole `getAdditionalProperties` method here should be moved to `CustomPropertiesBackend` ?

File: apps/dav/composer/composer/autoload_classmap.php [hunk 5]
```diff
@@ -342,6 +342,7 @@
     'OCA\\DAV\\Migration\\Version1029Date20231004091403' => $baseDir . '/../lib/Migration/Version1029Date20231004091403.php',
     'OCA\\DAV\\Migration\\Version1030Date20240205103243' => $baseDir . '/../lib/Migration/Version1030Date20240205103243.php',
     'OCA\\DAV\\Migration\\Version1031Date20240610134258' => $baseDir . '/../lib/Migration/Version1031Date20240610134258.php',
+    'OCA\\DAV\\Migration\\Version1032Date20250226000000' => $baseDir . '/../lib/Migration/Version1032Date20250226000000.php',
```
Comment (nickvergessen) [inline apps/dav/composer/composer/autoload_classmap.php:345]: file is missing

**Comment by SebastianKrupinski** [comment]
Apologies to everyone that got auto tagged for review! Rebase gone wrong!

**Review by ChristophWurst — APPROVED** [review]
:elephant:

File: apps/dav/lib/CalDAV/CalendarProvider.php (hunk 4 above)
Comment (st3iny) [reply apps/dav/lib/CalDAV/CalendarProvider.php:62]: I fully agree. However, currently the `CustomPropertiesBackend` needs an instance of `Server` to be constructed so we can't use it outside the DAV server's context.

I think we should factor the property mapping/serializing logic out of the backend class and make it reusable. The `CustomPropertiesBackend` can then continue to handle the Sabre/DAV related stuff (for example, the method overwritten methods).

This is something for another PR.

**Comment by SebastianKrupinski** [comment]
@nickvergessen do you mind removing your block, we are no longer migrating the data in this PR

File: apps/dav/lib/CalDAV/CalendarProvider.php (hunk 4 above)
Comment (st3iny) [reply apps/dav/lib/CalDAV/CalendarProvider.php:62]: I created: https://github.com/nextcloud/server/issues/52702

Thanks for the suggestion :)

**Review by st3iny — APPROVED** [review]

File: apps/dav/lib/CalDAV/CalendarProvider.php (hunk 4 above)
Comment (SebastianKrupinski) [reply apps/dav/lib/CalDAV/CalendarProvider.php:62]: I don't like the idea of this either but putting this in the CustomPropertiesBackend is not really a option, we would need to spin up the dav server just to pull a single property.
