### PR TITLE
fix(files): Prevent file list from jumping when selecting visible files

### LINKED ISSUE #54700: [Bug]: File list jumps after selecting it
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Have a list of files that extends your screen. Click a file that is not the first one in the list. See the files moving on top of the list while it is opening. This is a bit confusing, and it gives you the impression you selected the wrong file.

### Steps to reproduce

1. Have a list of files that extends your screen.
2. Click a file that is not the first one in the list
3. See the file in the background jump

### Expected behavior

The list stays as it is before opening the file

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by nfebe**
Skip scrolling when a file is clicked if it's already within the visible viewport, avoiding the confusing list jump behavior.

Fixes #54700

### CODE REVIEW

File: apps/files/src/components/FilesListVirtual.vue [hunk 1]
```diff
@@ -334,6 +334,13 @@ export default defineComponent({
 					showError(t('files', 'File not found'))
 				}
 
+				// Skip scrolling if the file is already visible
+				const table = this.$refs.table as ComponentPublicInstance<typeof VirtualList> | undefined
+				if (table?.isIndexVisible?.(index)) {
+					logger.debug('File already visible, skipping scroll', { fileId, index })
+					return
+				}
+
```
Comment (susnux) [inline apps/files/src/components/FilesListVirtual.vue]: why not directly do this in `scrollTo` of `apps/files/src/components/VirtualList.vue`?

Comment (nfebe) [reply apps/files/src/components/FilesListVirtual.vue]: Good point.

File: apps/files/src/components/VirtualList.vue [hunk 2]
```diff
@@ -336,6 +336,15 @@ export default defineComponent({
 				return
 			}
 
+			// Skip scrolling if the target index is already visible
+			if (this.isReady) {
```
Comment (susnux) [inline apps/files/src/components/VirtualList.vue]: Why do we only need to check the ready state for this block?
Is it needed?

**Review by susnux — COMMENTED** [review]
Logic seems fine, just not sure why we need the outer if here

File: apps/files/src/components/VirtualList.vue (hunk 2 above)
Comment (nfebe) [reply apps/files/src/components/VirtualList.vue]: If not ready, visibleRows would be 0. So you its not necessary, will removed.

**Review by susnux — APPROVED** [review]

**Review by cristianscheid — APPROVED** [review]
