### PR TITLE
Fixes bin2hex() in LDAP

### LINKED ISSUE #7400: LDAP error in Nextcloud 13 beta1
I just upgraded to Nextcloud 13 beta1 (user_ldap version: 1.3.1) and this error appears over and over in the logs when an LDAP user does any action, even when clicking a button or reloading the page.

> bin2hex() expects parameter 1 to be string, array given at /var/www/nextcloud/apps/user_ldap/lib/Access.php#1638

Everything seems to work fine for now, but even if this is a harmless error it fills the logs pretty quick with just one LDAP user logged in. With a few dozens of active users it will produce way more logs than wanted.

### PR DESCRIPTION
**Pull request by MorrisJobke**
Untangles the two if-else clauses into a more readable format.

Fixes #7400

### CODE REVIEW

**Comment by MorrisJobke** [comment]
The proof on 3v4l: https://3v4l.org/OdXp2

File: apps/user_ldap/lib/Access.php [hunk 1]
```diff
@@ -1253,11 +1253,13 @@ public function search($filter, $base, $attr = null, $limit = null, $offset = nu
...
 						if($key !== 'dn') {
-							$selection[$i][$key] = $this->resemblesDN($key) ?
-								$this->helper->sanitizeDN($item[$key])
-								: $key === 'objectguid' || $key === 'guid' ?
-									$selection[$i][$key] = $this->convertObjectGUID2Str($item[$key])
-									: $item[$key];
+							if($this->resemblesDN($key)) {
+								$selection[$i][$key] = $this->helper->sanitizeDN($item[$key]);
+							} else if($key === 'objectguid' || $key === 'guid') {
+								$selection[$i][$key] = [$this->convertObjectGUID2Str($item[$key][0])];
```
Comment (rullzer) [inline apps/user_ldap/lib/Access.php]: I'm assuming just taking the first element is fine?

Comment (MorrisJobke) [reply apps/user_ldap/lib/Access.php]: cc @blizzz

**Review by rullzer — APPROVED** [review]
Ok lets do this. @blizzz please do take a look at my comment since this part of ldap is dark magic to me.

**Comment by MorrisJobke** [comment]
As I only took the patch of @blizzz https://github.com/nextcloud/server/issues/7400#issuecomment-351351346 I also give this a :+1:

File: apps/user_ldap/lib/Access.php (hunk 1 above)
Comment (blizzz) [reply apps/user_ldap/lib/Access.php]: yes, because it is an identifier. if i get my hands on an AD i wanna doublecheck the format, however, and ideally add tests for it
