### PR TITLE
Make sure different webroots use different cached paths

### LINKED ISSUE #2190: URLGenerator->imagePath is not domain aware (cache)
### Description
URLGenerator->imagePath caches its result. The used caching key has no domain or URL awareness (Nextcloud root URL) which may lead to a wrong imagepath when accessed from another URL.

### Steps to reproduce
1. Setup Nextcloud with a caching system enabled (i.e. Redis)
2. Visit Nextcloud instance by external URL A (i.e. mynextcloud.com)
3. Visit Nextcloud instance by another URL B (i.e. 192.168.1.100/nextcloud)

### Expected behaviour
All images/icons load correctly.

### Actual behaviour
While the images/icons for URL A appear correctly some of them won't show on URL B (Error 404). 

### Proposal
Use a cache key which is domain aware, i.e.
$cacheKey = $nextcloudrooturl.'-'.$app.'-'.$image;

### Server configuration
**Operating system**: Debian Jessie (rpi2)

**Web server:** lighttpd

**Database:** mysql/mariadb

**PHP version:** 7.0

**Nextcloud version:** 10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** web installer

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #2190

I guess we can do this.

@rullzer @LukasReschke

### CODE REVIEW

**Comment by LukasReschke** [comment]
I'd prefer mixing domain and URL into https://github.com/nextcloud/server/blob/00c3f807db59f69cac37429f1b4be424720371e3/lib/private/Server.php#L371-L392

**Comment by nickvergessen** [comment]
Ah Server root is already in there, sounds a lot easier. The question is whether that is done late enough?

File: lib/private/Server.php [hunk 1]
```diff
@@ -377,7 +377,7 @@ public function __construct($webRoot, \OC\Config $config) {
 				$version = implode(',', $v);
 				$instanceId = \OC_Util::getInstanceId();
 				$path = \OC::$SERVERROOT;
-				$prefix = md5($instanceId . '-' . $version . '-' . $path);
+				$prefix = md5($instanceId . '-' . $version . '-' . $path . '-' . \OC::$WEBROOT);
```
Comment (MorrisJobke) [inline lib/private/Server.php]: `$WEBROOT` only contains the path not the domain: `/server` this is the webroot of my server.

**Review by MorrisJobke — CHANGES_REQUESTED** [review]

File: lib/private/Server.php (hunk 1 above)
Comment (nickvergessen) [inline lib/private/Server.php]: That is actually what we are trying to fix, not domain awareness, but subpath awareness. Domains are not cached in imagePath(), because the method only returns relative paths ;)

**Review by MorrisJobke — APPROVED** [review]

**Comment by nickvergessen** [comment]
@LukasReschke I changed it to the way you wanted, can I get a review now?

**Review by LukasReschke — APPROVED** [review]
