### PR TITLE
fix(dav): Make current ooo info time-dependent

### LINKED ISSUE #11059: Only show out of office message when applicable
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Set up OOO for upcoming (not current!) vacation 24th Dec to 8th Jan
2. Have DND user status (availability or manual)

### Expected behaviour
Nothing happens

### Actual behaviour
Bildschirmfoto vom 2023-11-30 22-34-39

THe OOO api endpoint returns start and end time. We should check it before displaying.

## Talk app

**Talk app version:** main

### PR DESCRIPTION
**Pull request by ChristophWurst**
* Helps resolve https://github.com/nextcloud/spreed/issues/11059

## Summary

* If there is an out of office absence info and it happens now -> return data
* Else: return no data

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by nickvergessen — CHANGES_REQUESTED** [review]
This will break the option for clients or potential admin features in the feature to show OOO in the form, etc.

Please let's not do this 🙈 
We should check the applicable time in talk, it's on the way.

File: apps/dav/lib/Controller/OutOfOfficeController.php [hunk 1]
```diff
@@ -66,8 +66,12 @@ public function __construct(
 	 */
 	#[NoAdminRequired]
 	public function getCurrentOutOfOfficeData(string $userId): DataResponse {
```
[the remark this answers is not in the document]
Comment (nickvergessen) [reply apps/dav/lib/Controller/OutOfOfficeController.php:68]: I'm fine with that change, but we should always return the data on the API so it can be used for multiple use cases (like settings + showing in chat, etc).

**Comment by ChristophWurst** [comment]
OOF. But the endpoint was specifically designed to only return data if it's currently active.

Do we need two endpoints?

**Review by Antreesy — APPROVED** [review]
Tested, works as expected, returning 404, if OoO is not in the effect yet (or expired)

Also wanted to ask about second endpoint. I understand that it might be useful for clients to get that data beforehand, but that's not the general case, I'd say

**Comment by ChristophWurst** [comment]
> I would say no, a simple date check on the returned date easily tells if it's applicable or not?

No, it's not, because you don't know the timezone of the other user.

Pushed another version. The old endpoint to get the absence data independent of time is back. In addition there is a timezone-aware endpoint that only returns data if the absence happens right now.

File: apps/dav/appinfo/routes.php [hunk 2]
```diff
@@ -33,7 +33,8 @@
 	],
 	'ocs' => [
 		['name' => 'direct#getUrl', 'url' => '/api/v1/direct', 'verb' => 'POST'],
-		['name' => 'out_of_office#getCurrentOutOfOfficeData', 'url' => '/api/v1/outOfOffice/{userId}', 'verb' => 'GET'],
+		['name' => 'out_of_office#getCurrentOutOfOfficeData', 'url' => '/api/v1/outOfOffice/{userId}/now', 'verb' => 'GET'],
+		['name' => 'out_of_office#getOutOfOffice', 'url' => '/api/v1/outOfOffice/{userId}', 'verb' => 'GET'],
```
Comment (nickvergessen) [inline apps/dav/appinfo/routes.php:37]: requires openapi.json update `bash build/openapi-checker.sh` (or something alike)

**Comment by ChristophWurst** [comment]
API changed another time for the new return type. Please let me know if it's usable.

**Review by provokateurin — APPROVED** [review]
OpenAPI looks good

File: lib/public/User/IOutOfOfficeData.php [hunk 3]
```diff
@@ -74,4 +75,18 @@ public function getShortMessage(): string;
...
+
+	/**
+	 * @return array {
+	 *      id: int,
+	 *      userId: string,
+	 *      startDate: int,
+	 *      endDate: int,
+	 *      shortMessage: string,
+	 *      message: string,
+	 *  }
```
Comment (nickvergessen) [inline lib/public/User/IOutOfOfficeData.php:87]: This needs to go to ResponseDefinitions.php and then be used as type in the annotation

Comment (ChristophWurst) [reply lib/public/User/IOutOfOfficeData.php:87]: This doesn't feel right. Then the public API is based on private API, no? I'm trying to get the definitions into this interface, then use them from the controller.

File: apps/dav/lib/Controller/OutOfOfficeController.php [hunk 4]
```diff
@@ -59,15 +61,45 @@ public function __construct(
 	 * Get the currently configured out-of-office data of a user.
 	 *
 	 * @param string $userId The user id to get out-of-office data for.
-	 * @return DataResponse<Http::STATUS_OK, DAVOutOfOfficeData, array{}>|DataResponse<Http::STATUS_NOT_FOUND, null, array{}>
+	 * @return DataResponse<Http::STATUS_OK, OutOfOfficeData, array{}>|DataResponse<Http::STATUS_NOT_FOUND, null, array{}>
```
[the remark this answers is not in the document]
Comment (nickvergessen) [reply apps/dav/lib/Controller/OutOfOfficeController.php:64]: It's reading the ResponseDefinitions.php and not actually eating/evaluating PHP code.

So temporary fix duplicate the data format to ResponseDefinitions.php

File: lib/public/User/IOutOfOfficeData.php (hunk 3 above)
Comment (nickvergessen) [reply lib/public/User/IOutOfOfficeData.php]: > Then the public API is based on private API, no?

Right, should duplicate in that case.

File: apps/dav/lib/Controller/OutOfOfficeController.php (hunk 4 above)
[the remark this answers is not in the document]
Comment (ChristophWurst) [reply apps/dav/lib/Controller/OutOfOfficeController.php:64]: oof

File: apps/dav/lib/Controller/OutOfOfficeController.php (hunk 1 above)
[the remark this answers is not in the document]
Comment (ChristophWurst) [reply apps/dav/lib/Controller/OutOfOfficeController.php:70]: Included in the latest push

File: apps/dav/lib/ResponseDefinitions.php [hunk 5]
```diff
@@ -35,6 +35,16 @@
  *     status: string,
  *     message: string,
  * }
+ *
+ * @todo this is a copy of \OCP\User\IOutOfOfficeData
+ * @psalm-type DAVOutOfOfficeData2 = array{
```
Comment (provokateurin) [inline apps/dav/lib/ResponseDefinitions.php:40]: I'd prefer if they extend a common type alias. Also, why are there two definitions that seem very similar?

Comment (ChristophWurst) [reply apps/dav/lib/ResponseDefinitions.php:40]: Because of https://github.com/nextcloud/server/pull/41962#pullrequestreview-1759433208

Comment (ChristophWurst) [reply apps/dav/lib/ResponseDefinitions.php:40]: What is a common type alias?

Comment (ChristophWurst) [reply apps/dav/lib/ResponseDefinitions.php]: Done

File: apps/dav/lib/ResponseDefinitions.php [hunk 6]
```diff
@@ -27,13 +27,24 @@
...
- *     message: string,
+ * }
+ *
+ * @todo this is a copy of \OCP\User\IOutOfOfficeData
+ * @psalm-type DAVOutOfOfficeData2 = DAVOutOfOfficeDataCommon&array{
+ *     id: string,
+ *     startDate: int,
+ *     endDate: int,
+ *     shortMessage: string,
  * }
```
Comment (provokateurin) [inline apps/dav/lib/ResponseDefinitions.php:48]: I have no idea how the backend works, but is there no way to align these a bit more? Why is the ID an int for one endpoint and a string for another? `status` and `shortMessage` also sound similar, are they different things?

**Review by nickvergessen — APPROVED** [review]

File: apps/dav/lib/ResponseDefinitions.php [hunk 7]
```diff
@@ -27,13 +27,24 @@
...
  *     id: int,
- *     userId: string,
  *     firstDay: string,
  *     lastDay: string,
  *     status: string,
- *     message: string,
+ * }
+ *
+ * @todo this is a copy of \OCP\User\IOutOfOfficeData
+ * @psalm-type DAVOutOfOfficeData2 = DAVOutOfOfficeDataCommon&array{
```
[the remark this answers is not in the document]
Comment (provokateurin) [reply apps/dav/lib/ResponseDefinitions.php:43]: Ok @nickvergessen already said it as well https://github.com/nextcloud/server/pull/41962#discussion_r1412073831

File: apps/dav/lib/ResponseDefinitions.php (hunk 6 above)
Comment (ChristophWurst) [reply apps/dav/lib/ResponseDefinitions.php:48]: I agree but we are in RC3 and I don't want to cause explosions right now.

Comment (provokateurin) [reply apps/dav/lib/ResponseDefinitions.php:48]: maybe a simple cast to int here is ok for now and it can be fixed later.

Comment (ChristophWurst) [reply apps/dav/lib/ResponseDefinitions.php:48]: maybe it's ok, maybe it's not. that is the risk I don't want to take at this stage

Comment (provokateurin) [reply apps/dav/lib/ResponseDefinitions.php]: Ok then keep it :woman_shrugging:

File: apps/dav/lib/Controller/OutOfOfficeController.php [hunk 8]
```diff
@@ -59,15 +61,45 @@ public function __construct(
 	 * Get the currently configured out-of-office data of a user.
 	 *
 	 * @param string $userId The user id to get out-of-office data for.
-	 * @return DataResponse<Http::STATUS_OK, DAVOutOfOfficeData, array{}>|DataResponse<Http::STATUS_NOT_FOUND, null, array{}>
+	 * @return DataResponse<Http::STATUS_OK, DAVCurentOutOfOfficeData, array{}>|DataResponse<Http::STATUS_NOT_FOUND, null, array{}>
```
[the remark this answers is not in the document]
Comment (ChristophWurst) [reply apps/dav/lib/Controller/OutOfOfficeController.php]: it's called *consistency*

**Comment by nickvergessen** [comment]
OpenAPI needs rebuild 🙈

**Comment by ChristophWurst** [comment]
CI is happy now. @nickvergessen are you, too?

**Review by nickvergessen — APPROVED** [review]
