### PR TITLE
fix(theming): Add migration to restore primary color after separating primary and background

### LINKED ISSUE #46980: [Bug]: custom primary color lost after upgrade from 29 to 30
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After upgrading and a hard browser refresh (there might be an issue with cache busting…) the primary color was reset to the default blue, instead of keeping the previous custom color.

Not entirely sure now, but I think it was based on the background.

### Steps to reproduce

1. Run NC 29
2. Set a custom background image and have a personal primary color set based on it 
4. Upgrade to 30 Beta 3

### Expected behavior

The primary color is kept

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by susnux**
* Resolves: https://github.com/nextcloud/server/issues/46980

## Summary

Not sure about the user color part, but at least it works :sweat_smile: 
Meaning not sure if that query would not take long on large instances.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/theming/lib/Migration/SeparatePrimaryColorAndBackground.php [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+
+use OCA\Theming\AppInfo\Application;
+use OCP\IConfig;
+use OCP\IDBConnection;
+use OCP\Migration\IOutput;
+
+class SeparatePrimaryColorAndBackground implements \OCP\Migration\IRepairStep {
+
+	public function __construct(
+		private IConfig $config,
```
Comment (skjnldsv) [inline apps/theming/lib/Migration/SeparatePrimaryColorAndBackground.php:20]:
```suggestion
		private IAppConfig $config,
```

File: apps/theming/lib/Migration/SeparatePrimaryColorAndBackground.php [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+
+	public function getName() {
+		return 'Restore custom primary color after separating primary color from background color';
+	}
+
+	public function run(IOutput $output) {
+		$defaultColor = $this->config->getAppValue(Application::APP_ID, 'color', '');
+		if ($defaultColor !== '') {
+			// Restore legacy value into new field
+			$this->config->setAppValue(Application::APP_ID, 'background_color', $defaultColor);
```
Comment (skjnldsv) [inline apps/theming/lib/Migration/SeparatePrimaryColorAndBackground.php:33]:
```suggestion
			$this->config->getValueString(Application::APP_ID, 'background_color', $defaultColor);
```

File: apps/theming/lib/Migration/SeparatePrimaryColorAndBackground.php [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+		private IDBConnection $connection,
+	) {
+	}
+
+	public function getName() {
+		return 'Restore custom primary color after separating primary color from background color';
+	}
+
+	public function run(IOutput $output) {
+		$defaultColor = $this->config->getAppValue(Application::APP_ID, 'color', '');
```
Comment (skjnldsv) [inline apps/theming/lib/Migration/SeparatePrimaryColorAndBackground.php:30]:
```suggestion
		$defaultColor = $this->config->getValueString(Application::APP_ID, 'color', '');
```

File: apps/theming/lib/Migration/SeparatePrimaryColorAndBackground.php [hunk 4]
```diff
@@ -0,0 +1,64 @@
...
+		if ($defaultColor !== '') {
+			// Restore legacy value into new field
+			$this->config->setAppValue(Application::APP_ID, 'background_color', $defaultColor);
+			$this->config->setAppValue(Application::APP_ID, 'primary_color', $defaultColor);
```
Comment (skjnldsv) [inline apps/theming/lib/Migration/SeparatePrimaryColorAndBackground.php:34]:
```suggestion
			$this->config->setValueString(Application::APP_ID, 'primary_color', $defaultColor);
```

File: apps/theming/lib/Migration/SeparatePrimaryColorAndBackground.php [hunk 5]
```diff
@@ -0,0 +1,64 @@
...
+			// Delete legacy field
+			$this->config->deleteAppValue(Application::APP_ID, 'color');
```
Comment (skjnldsv) [inline apps/theming/lib/Migration/SeparatePrimaryColorAndBackground.php:36]:
```suggestion
			$this->config->deleteKey(Application::APP_ID, 'color');
```

File: apps/theming/lib/Migration/SeparatePrimaryColorAndBackground.php [hunk 6]
```diff
@@ -0,0 +1,64 @@
...
+			// give some feedback
+			$output->info('Global primary color restored');
+		}
+
+		// This can only be executed once because `background_color` is again used with Nextcloud 30,
+		// so this part only works when updating -> Nextcloud 29 -> 30
+		$migrated = $this->config->getAppValue('theming', 'nextcloud_30_migration', 'false') === 'true';
```
Comment (skjnldsv) [inline apps/theming/lib/Migration/SeparatePrimaryColorAndBackground.php:43]:
```suggestion
		$migrated = $this->config->getValueBool('theming', 'nextcloud_30_migration', false) === true;
```

File: apps/theming/lib/Migration/SeparatePrimaryColorAndBackground.php [hunk 7]
```diff
@@ -0,0 +1,64 @@
...
+		if ($migrated) {
+			return;
+		}
+
+		$userThemingEnabled = $this->config->getAppValue('theming', 'disable-user-theming', 'no') !== 'yes';
```
Comment (skjnldsv) [inline apps/theming/lib/Migration/SeparatePrimaryColorAndBackground.php:48]:
```suggestion
		$userThemingEnabled = $this->config->getValueString('theming', 'disable-user-theming', 'no') !== 'yes';
```

File: apps/theming/lib/Migration/SeparatePrimaryColorAndBackground.php [hunk 8]
```diff
@@ -0,0 +1,64 @@
...
+			// Rename the `background_color` config to `primary_color` as this was the behavior on Nextcloud 29 and older
+			// with Nextcloud 30 `background_color` is a new option to define the background color independent of the primary color.
+			$qb->update('preferences')
+				->set('configkey', $qb->createNamedParameter('primary_color'))
+				->where($qb->expr()->eq('appid', $qb->createNamedParameter(Application::APP_ID)))
+				->andWhere($qb->expr()->eq('configkey', $qb->createNamedParameter('background_color')));
+			$qb->executeStatement();
+			$output->info('Primary color of users restored');
+		}
+		$this->config->setAppValue('theming', 'nextcloud_30_migration', 'true');
```
Comment (skjnldsv) [inline apps/theming/lib/Migration/SeparatePrimaryColorAndBackground.php:62]:
```suggestion
		$this->config->setValueBool('theming', 'nextcloud_30_migration', true);
```

**Review by skjnldsv — DISMISSED** [review]
use `IAppConfig` please :)

**Comment by susnux** [comment]
> use IAppConfig please :)

If it is fixed now, then I love to. It had a really bad bug that you cannot mix `IConfig->setAppValue` and e.g. `IAppConfig->setValueBool`.
Meaning you have to migrate **every** access to that value to the types access, in every place. Otherwise after using the typed access you can no longer access it with the `IConfig` variant.

One recent place were we needed to fix this: https://github.com/nextcloud/server/pull/46991

File: apps/theming/lib/Migration/SeparatePrimaryColorAndBackground.php [hunk 9]
```diff
@@ -0,0 +1,63 @@
...
+		private IAppConfig $appConfig,
+		private IDBConnection $connection,
+	) {
+	}
+
+	public function getName() {
+		return 'Restore custom primary color after separating primary color from background color';
+	}
+
+	public function run(IOutput $output) {
```
Comment (come-nc) [inline apps/theming/lib/Migration/SeparatePrimaryColorAndBackground.php:29]:
```suggestion
	public function run(IOutput $output): void {
```

File: apps/theming/lib/Migration/SeparatePrimaryColorAndBackground.php [hunk 10]
```diff
@@ -0,0 +1,63 @@
...
+			$this->appConfig->deleteKey(Application::APP_ID, 'color');
+			// give some feedback
+			$output->info('Global primary color restored');
+		}
+
+		// This can only be executed once because `background_color` is again used with Nextcloud 30,
+		// so this part only works when updating -> Nextcloud 29 -> 30
+		if ($this->appConfig->getValueBool('theming', 'nextcloud_30_migration')) {
+			return;
+		}
```
Comment (come-nc) [inline apps/theming/lib/Migration/SeparatePrimaryColorAndBackground.php:45]: Then this should be put in a migration and not a repair step?

**Review by come-nc — DISMISSED** [review]
The config key to check if repair step ran already is too ugly, please use a migration instead which by design run only once.

**Comment by susnux** [comment]
@come-nc I refactored this again, but we need to put parts of the migration into a background job. As we need to iterate a list of users which could take long if many users had custom backgrounds.

I reused the logic from the `dashboard -> theming` repair step / background job.

So it is now working correctly for me:

### Screen recording
#### Setup

[Bildschirmaufnahme_20240902_165334.webm](https://github.com/user-attachments/assets/77f12cdd-32b2-4947-844e-060513251a5b)


#### After Upgrade to Nextcloud 30 / 31

Please note the wrong colors in the beginning, I triggered the migration then and reload the page:

[Bildschirmaufnahme_20240902_170942.webm](https://github.com/user-attachments/assets/176b41a1-f388-4bec-8554-94d21e33d7c9)

**Comment by come-nc** [comment]
Psalm is quite angry

File: apps/theming/lib/Jobs/RestoreBackgroundImageColor.php [hunk 11]
```diff
@@ -0,0 +1,206 @@
...
+
+	/**
+	 * @throws NotPermittedException
+	 * @throws NotFoundException
+	 */
+	protected function runMigration(): void {
+		$allUserIds = $this->readUserIdsToProcess();
+		$notSoFastMode = count($allUserIds) > 1000;
+
+		$userIds = $notSoFastMode ? array_slice($allUserIds, 0, 1000) : $allUserIds;
```
Comment (come-nc) [inline apps/theming/lib/Jobs/RestoreBackgroundImageColor.php:97]:
```suggestion
		$userIds = array_slice($allUserIds, 0, 1000);
```
No need to check count first, `array_slice` will take care of it.

File: apps/theming/lib/Service/BackgroundService.php [hunk 12]
```diff
@@ -205,10 +205,15 @@ public function __construct(
 	) {
 	}
 
-	public function setDefaultBackground(): void {
-		$this->config->deleteUserValue($this->userId, Application::APP_ID, 'background_image');
-		$this->config->deleteUserValue($this->userId, Application::APP_ID, 'background_color');
-		$this->config->deleteUserValue($this->userId, Application::APP_ID, 'primary_color');
+	public function setDefaultBackground(?string $userId = null): void {
+		$userId = $userId ?? $this->userId;
+		if ($this->userId === null) {
```
Comment (come-nc) [inline apps/theming/lib/Service/BackgroundService.php:210]: Is it on purpose that the test is on `$this->userId` and not `$userId`?
Looks fishy

File: apps/theming/lib/Service/BackgroundService.php [hunk 13]
```diff
@@ -227,45 +232,65 @@ public function setFileBackground($path): void {
 
 		/** @var File $file */
 		$file = $userFolder->get($path);
+		$handle = $file->fopen('r');
+		if ($handle === false) {
+			throw new InvalidArgumentException('Invalid image file');
+		}
+		$this->getAppDataFolder()->newFile('background.jpg', $file->fopen('r'));
```
Comment (come-nc) [inline apps/theming/lib/Service/BackgroundService.php:239]:
```suggestion
		$this->getAppDataFolder()->newFile('background.jpg', $handle);
```
I suppose?

File: apps/theming/lib/Jobs/RestoreBackgroundImageColor.php [hunk 14]
```diff
@@ -0,0 +1,206 @@
...
+			$qb2 = $this->dbc->getQueryBuilder();
+
+			$innerSQL = $qb2->select('userid')
+				->from('preferences')
+				->where($qb2->expr()->eq('configkey', $qb->createNamedParameter('background_color')));
+
+			// Get those users, that have a background_image set - not the default, but no background_color.
+			$result = $qb->selectDistinct('a.userid')
+				->from('preferences', 'a')
+				->leftJoin('a', $qb->createFunction('('.$innerSQL->getSQL().')'), 'b', 'a.userid = b.userid')
```
[the remark this answers is not in the document]
Comment (susnux) [reply apps/theming/lib/Jobs/RestoreBackgroundImageColor.php:73]: Having a look at the definition: We explicitly handle functions passed, so this works. Probably just not in the public interface.
But otherwise we have to way to create sub queries.

[the remark this answers is not in the document]
Comment (susnux) [reply apps/theming/lib/Jobs/RestoreBackgroundImageColor.php:72]: See https://github.com/nextcloud/server/blob/9f9884930609addad3e37325731fb5406dd3aa44/lib/private/db/querybuilder/querybuilder.php#L1317-1320

[the remark this answers is not in the document]
Comment (come-nc) [reply apps/theming/lib/Jobs/RestoreBackgroundImageColor.php:72]: Either you cast to string or you change the IQueryBuilder/QueryBuilder leftJoin method to accept IQueryFunction for the second parameter.

File: apps/theming/lib/Migration/Version2006Date20240905111627.php [hunk 15]
```diff
@@ -0,0 +1,88 @@
...
+
+		$userThemingEnabled = $this->appConfig->getValueBool('theming', 'disable-user-theming') === false;
+		if ($userThemingEnabled) {
+			$this->restoreUserColors($output);
+		}
+
+		return null;
+	}
+
+	public function postSchemaChange(IOutput $output, Closure $schemaClosure, array $options) {
```
[the remark this answers is not in the document]
Comment (susnux) [reply apps/theming/lib/Migration/Version2006Date20240905111627.php:54]:
```suggestion
	public function postSchemaChange(IOutput $output, Closure $schemaClosure, array $options): void {
```

File: apps/theming/lib/Migration/Version2006Date20240905111627.php [hunk 16]
```diff
@@ -0,0 +1,88 @@
...
+
+	public function name(): string {
+		return 'Restore custom primary color';
+	}
+
+	public function description(): string {
+		return 'Restore custom primary color after separating primary color from background color';
+	}
+
+	public function preSchemaChange(IOutput $output, Closure $schemaClosure, array $options) {
```
[the remark this answers is not in the document]
Comment (susnux) [reply apps/theming/lib/Migration/Version2006Date20240905111627.php:39]:
```suggestion
	public function preSchemaChange(IOutput $output, Closure $schemaClosure, array $options): void {
```

File: apps/theming/lib/Jobs/RestoreBackgroundImageColor.php (hunk 14 above)
[the remark this answers is not in the document]
Comment (susnux) [reply apps/theming/lib/Jobs/RestoreBackgroundImageColor.php:72]: Done :heavy_check_mark:

[the remark this answers is not in the document]
Comment (come-nc) [reply apps/theming/lib/Jobs/RestoreBackgroundImageColor.php:72]: But that’s what the QueryBuilder is doing in the end, so what’s the difference?

[the remark this answers is not in the document]
Comment (susnux) [reply apps/theming/lib/Jobs/RestoreBackgroundImageColor.php:72]: If a string is passed the `getTableName` function will prepend `'*PREFIX*'` to the string, if a `IQueryFunction` is passed it is only cast to string but no prefix is added.

**Review by come-nc — APPROVED** [review]

**Review by ArtificialOwl — APPROVED** [review]
code looks good
