### PR TITLE
generate different UIDs for Birthday, Anniversary and Death event

### LINKED ISSUE #7706: Anniversary and birthday events have same ID in birthday calendar
(Re-reported from https://github.com/nextcloud/calendar/issues/691)

### Steps to reproduce
1. Create a contact with both a birthday and an anniversary
2. Use the "birthdays" calendar with https://github.com/pimutils/vdirsyncer
3. Observe an error like the following:

```
error: andreas_calendar/contact_birthdays: Storage "andreas_calendar_remote/contact_birthdays" contains multiple items with the same UID or even content. Vdirsyncer will now abort the synchronization of this collection, because the fix for this is not clear; It could be the result of a badly behaving server. You can try running:
error: 
error:     vdirsyncer repair andreas_calendar_remote/contact_birthdays
error: 
error: But make sure to have a backup of your data in some form. The offending hrefs are:
error: 
error: '/nextcloud/remote.php/caldav/calendars/andreas/contact_birthdays/contacts-24ffb9a1c0.vcf.ics'
error: '/nextcloud/remote.php/caldav/calendars/andreas/contact_birthdays/contacts-24ffb9a1c0.vcf-anniversary.ics'
```
### Server configuration

**Operating system**: Debian Linux "buster" (testing)

**Web server:** nginx

**Database:** pgsql 10

**PHP version:** 

```
PHP 7.0.26-1 (cli) (built: Nov 29 2017 09:48:46) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.26-1, Copyright (c) 1999-2017, by Zend Technologies
```

**Server version:** 12.0.3

**Calendar version:** 1.5.6

**Updated from an older installed version or fresh install:** Updated from owncloud 6, through each major version

**Signing status (ownCloud/Nextcloud 9.0 and above):**  `No errors have been found.`

**List of activated apps:**

```
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - bruteforcesettings: 1.0.3
  - calendar: 1.5.7
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - encryption
  - files_external
  - user_external
  - user_ldap
```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "51c904fc8c46c",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/lib\/owncloud\/data",
        "dbtype": "pgsql",
        "version": "12.0.3.3",
        "appstoreenabled": true,
        "apps_paths": [
            {
                "path": "\/web\/nextcloud\/nextcloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/web\/nextcloud\/nextcloud\/apps",
                "url": "\/apps2",
                "writable": true
            }
        ],
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "trusted_domains": [
            "ssl.tiker.net",
            "ssl.cbigman.net"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "overwrite.cli.url": "\/nextcloud",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "appstore.experimental.enabled": true,
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "htaccess.RewriteBase": "\/nextcloud"
    }
}
```

### PR DESCRIPTION
**Pull request by georgehrke**
fixes https://github.com/nextcloud/server/issues/7706

Would like to back port to stable12 and stable13

### CODE REVIEW

**Comment by inducer** [comment]
Thanks for working on this!

File: apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php [hunk 1]
```diff
@@ -64,7 +64,7 @@ public function setUp() {
 	 * @param string | null $data
 	 */
 	public function testBuildBirthdayFromContact($expectedSummary, $data) {
-		$cal = $this->service->buildDateFromContact($data, 'BDAY', '*');
+		$cal = $this->service->buildDateFromContact($data, 'BDAY', '', '*');
```
Comment (rullzer) [inline apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php]: This seems more like a hack to test it. :) can you also add a test with the proper postfix :P?

**Review by rullzer — APPROVED** [review]

**Comment by georgehrke** [comment]
Let me add more tests, but the actual code will stay unchanged and is ready to be reviewed

**Review by MorrisJobke — APPROVED** [review]

**Review by juliusknorr — APPROVED** [review]
