### PR TITLE
fix(migration): Make naming constraint fail softer on updates

### LINKED ISSUE #41253: [Bug]: Upgrade to NC 28.0.0-beta fails because of DB problems
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Just found NC 28.0.0 beta available and started the update on the command line. Here's the output of the upgrade process:

> Nextcloud Updater - version: v27.1.0rc3-15-gfa7af53
> 
> Current version is 27.1.3.
> 
> Update to Nextcloud 28.0.0 beta 1 available. (channel: "beta")
> Following file will be downloaded automatically: https://download.nextcloud.com/server/prereleases/nextcloud-28.0.0beta1.zip
> 
> Steps that will be executed:
> [ ] Check for expected files
> [ ] Check for write permissions
> [ ] Create backup
> [ ] Downloading
> [ ] Verify integrity
> [ ] Extracting
> [ ] Enable maintenance mode
> [ ] Replace entry points
> [ ] Delete old files
> [ ] Move new files in place
> [ ] Done
> 
> Start update? [y/N] y 
> 
> Info: Pressing Ctrl-C will finish the currently running step and then stops the updater.
> 
> [✔] Check for expected files
> [✔] Check for write permissions
> [✔] Create backup
> [✔] Downloading
> [✔] Verify integrity
> [✔] Extracting
> [✔] Enable maintenance mode
> [✔] Replace entry points
> [✔] Delete old files
> [✔] Move new files in place
> [✔] Done
> 
> Update of code successful.
> 
> Should the "occ upgrade" command be executed? [Y/n] y
> Nextcloud or one of the apps require upgrade - only a limited number of commands are available
> You may use your browser or the occ upgrade command to do the upgrade
> Setting log level to debug
> Repair step: Repair MySQL collation
> Repair info: All tables already have the correct collation -> nothing to do
> Repair step: Copy data from accounts table when migrating from ownCloud
> Repair step: Drop account terms table when migrating from ownCloud
> Updating database schema
> Exception: Database error when running migration 28000Date20230906104802 for app core
> Index name "ts_session" for table "oc_talk_sessions" collides with the constraint on table "oc_text_steps".
> Update failed
> Maintenance mode is kept active
> Resetting log level
> 
> Keep maintenance mode active? [y/N] 
> Nextcloud or one of the apps require upgrade - only a limited number of commands are available
> You may use your browser or the occ upgrade command to do the upgrade
> Maintenance mode disabled
> 
> Maintenance mode is disabled

### Steps to reproduce

1. have an update date NC 27 installation running
2. be on beta channel
3. start the upgrade once you find the notice

### Expected behavior

Upgrade running smootly without errors

### Installation method

None

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "example.org",
            "cloud.example.org",
            "192.168.1.*",
            "nextcloud.example.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.1.3.2",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "activity_expire_days": 14,
        "auth.bruteforce.protection.enabled": true,
        "blacklisted_files": [
            ".htaccess",
            "Thumbs.db",
            "thumbs.db"
        ],
        "cron_log": true,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "filesystem_check_changes": 1,
        "filelocking.enabled": "true",
        "htaccess.RewriteBase": "\/",
        "integrity.check.disabled": false,
        "knowledgebaseenabled": false,
        "logfile": "\/mnt\/STOR\/logs\/nextcloud.log",
        "loglevel": 0,
        "logtimezone": "Europe\/Berlin",
        "log_rotate_size": 104857600,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "overwriteprotocol": "https",
        "preview_max_x": 1024,
        "preview_max_y": 768,
        "preview_max_scale_factor": 1,
        "quota_include_external_storage": false,
        "share_folder": "\/Shares",
        "skeletondirectory": "",
        "theme": "",
        "trashbin_retention_obligation": "auto, 7",
        "updater.release.channel": "beta",
        "mail_smtpmode": "sendmail",
        "mail_sendmailmode": "pipe",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "default_phone_region": "DE",
        "app_install_overwrite": [
            "dicomviewer",
            "files_mindmap",
            "carnet",
            "onlyoffice",
            "richdocuments",
            "richdocumentscode",
            "documentserver_community",
            "files_photospheres",
            "telephoneprovider",
            "audioplayer",
            "audioplayer_editor",
            "extract",
            "tasks",
            "ocsms",
            "files_trackdownloads",
            "ocdownloader",
            "twofactor_u2f",
            "checksum",
            "event_update_notification",
            "mindmap_app",
            "contacts",
            "deck",
            "spreed",
            "twofactor_webauthn",
            "maps"
        ],
        "has_rebuilt_cache": true
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - audioplayer: 3.4.0
  - bruteforcesettings: 2.7.0
  - calendar: 4.6.0-beta.1
  - carnet: 0.25.2
  - checksum: 1.2.2
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.5.0-beta.3
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - deck: 1.11.0
  - documentserver_community: 0.1.13
  - event_update_notification: 2.2.0
  - extract: 1.3.6
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_external: 1.19.0
  - files_mindmap: 0.0.29
  - files_pdfviewer: 2.8.0
  - files_photospheres: 1.27.0
  - files_reminders: 1.0.0
  - files_sharing: 1.19.0
  - files_trackdownloads: 1.11.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - impersonate: 1.14.0
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - mail: 3.5.0-beta.1
  - maps: 1.2.0
  - nextcloud_announcements: 1.16.0
  - notes: 4.8.1
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - ocdownloader: 1.9.1
  - password_policy: 1.17.0
  - photos: 2.3.0
  - previewgenerator: 5.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - richdocuments: 8.2.2
  - richdocumentscode: 23.5.503
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - sociallogin: 5.5.4
  - spreed: 17.1.2
  - support: 1.10.0
  - survey_client: 1.15.0
  - suspicious_login: 5.0.0
  - systemtags: 1.17.0
  - tasks: 0.15.0
  - telephoneprovider: 1.0.3
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - twofactor_totp: 9.0.0
  - twofactor_webauthn: 1.2.0
  - updatenotification: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - encryption: 2.16.0
  - firstrunwizard: 2.17.0 (installed 2.7.0)
  - user_ldap: 1.19.0
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

```shell
none available
```

### Additional info

_No response_

### LINKED ISSUE #43173: [Bug]: upgrade 27.1.5.1 to 28.0.1.1 foreign key oc_polls_share
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Exception: Database error when running migration 28000Date20230906104802 for app core Foreign key name "FK_1C85E16C3C947C0F" for table "oc_polls_share" collides with the constraint on table "oc_polls_share".

### Steps to reproduce

didn't try on a fresh system

### Expected behavior

correct update of db scheme

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "blacklisted_files": [],
        "updatechecker": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.1.5.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "dbindex": 0
        },
        "loglevel": 2,
        "logtimezone": "Europe\/Berlin",
        "log_rotate_size": 104857600,
        "installed": true,
        "theme": "",
        "maintenance": false,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "files_antivirus.av_cmd_options": "",
        "files_antivirus.av_path": "\/usr\/bin\/clamscan",
        "allow_user_to_change_mail_address": "",
        "mysql.utf8mb4": true,
        "mail_sendmailmode": "smtp",
        "default_phone_region": "DE",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\Movie",
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\MP4",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF"
        ],
        "app_install_overwrite": [
            "richdocumentscode",
            "ransomware_protection",
            "files_downloadactivity"
        ],
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - announcementcenter: 6.7.0
  - audioplayer: 3.4.1
  - bruteforcesettings: 2.7.0
  - calendar: 4.6.2
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.5.1
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - external: 5.2.1
  - federatedfilesharing: 1.17.0
  - files: 1.22.0
  - files_antivirus: 5.4.0
  - files_downloadactivity: 1.16.0
  - files_external: 1.19.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_sharing: 1.19.0
  - files_texteditor: 2.15.1
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - impersonate: 1.14.0
  - integration_openstreetmap: 1.0.6
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - maps: 1.2.0
  - nextcloud_announcements: 1.16.0
  - notes: 4.9.2
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - photos: 2.3.0
  - polls: 5.4.2
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - quota_warning: 1.18.0
  - ransomware_protection: 1.14.0
  - recognize: 5.0.3
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - richdocuments: 8.2.3
  - richdocumentscode: 23.5.604
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - spreed: 17.1.4
  - stt_whisper: 1.0.7
  - support: 1.10.0
  - survey_client: 1.15.0
  - suspicious_login: 5.0.0
  - systemtags: 1.17.0
  - tasks: 0.15.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - updatenotification: 1.17.0
  - user_usage_report: 1.11.1
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - encryption: 2.16.0
  - federation: 1.18.0 (installed 1.17.0)
  - sharepoint: 1.15.0 (installed 1.15.0)
  - twofactor_totp: 10.0.0-beta.2
  - user_ldap: 1.19.0
  - user_status: 1.8.1 (installed 1.5.0)
```

### Nextcloud Signing status

```shell
upgrade stucked
```

### Nextcloud Logs

```json
{
	"reqId": "uHAbKnMedDkHYviN4viE",
	"level": 3,
	"time": "2024-01-12T13:20:09+01:00",
	"remoteAddr": "***REMOVED SENSITIVE VALUE***",
	"user": "--",
	"app": "updater",
	"method": "GET",
	"url": "/core/ajax/update.php?requesttoken=***REMOVED SENSITIVE VALUE***",
	"message": "\\OC\\Updater::failure: Exception: Database error when running migration 28000Date20230906104802 for app core\nForeign key name \"FK_1C85E16C3C947C0F\" for table \"oc_polls_share\" collides with the constraint on table \"oc_polls_share\".",
	"userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0",
	"version": "27.1.5.1",
	"data": {
		"app": "updater"
	}
}
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by szaimen**
Fix https://github.com/nextcloud/server/issues/41253
Fix #43173 
 
Follow-up to https://github.com/nextcloud/server/pull/39506

Admin check will be handled in https://github.com/nextcloud/server/pull/43432

### CODE REVIEW

File: lib/private/DB/MigrationService.php [hunk 1]
```diff
@@ -658,6 +658,9 @@ public function ensureOracleConstraints(Schema $sourceSchema, Schema $targetSche
 	public function ensureUniqueNamesConstraints(Schema $targetSchema): void {
 		$constraintNames = [];
 
+		/** @var LoggerInterface $logger */
+		$logger = \OC::$server->get(LoggerInterface::class);
```
Comment (come-nc) [inline lib/private/DB/MigrationService.php:662]:
```suggestion
		$logger = \OCP\Server::get(LoggerInterface::class);
```

**Comment by joshtrichards** [comment]
Just logging it for now does seem a practical solution. Seems friendlier and doesn't require a bunch of other engineering.

We could also do this in a setup check maybe? Not sure about resource usage though. The advantage there is we could provide a doc link + further encourage cleanup prior to upgrade runs.

**Review by bigcat88 — APPROVED** [review]

**Review by nickvergessen — DISMISSED** [review]
https://github.com/nextcloud/server/blame/cc6de72b11eff0a5b9c7d099281c0ae91afa7320/lib/private/DB/MigrationService.php#L654

> Naming constraints:
> * - Index, sequence and primary key names must be unique within a Postgres Schema

It will break at least on postgres anyway. To help developers we should just not allow this and always break so they are aware.

Also logging this is of 0 help as no dev checks their logs on CI runs to look for such things.

Definitely a No from me.

**Comment by szaimen** [comment]
Idea from Joas:
> We could weaken it for the update case, to only report in that case, but installing such an app/version/migration must be breaking

>
> Basically similarly to the oracle check we could hand in the sourceSchema
https://github.com/nextcloud/server/blob/6f39d82031202a2a8d1fb81ea448a2ffdc52cc29/lib/private/DB/MigrationService.php#L517-L521

>
> And check if the collision existed there as well already and in that case log the error

>
> [nextcloud/server/lib/private/DB/MigrationService.php](https://github.com/nextcloud/server/blob/6f39d82031202a2a8d1fb81ea448a2ffdc52cc29/lib/private/DB/MigrationService.php#L517-L521)
Zeile 517 bis 521 ([6f39d82](https://github.com/nextcloud/server/blob/6f39d82031202a2a8d1fb81ea448a2ffdc52cc29/lib/private/DB/MigrationService.php#L517-L521))
517 			$this->ensureUniqueNamesConstraints($targetSchema);
518 			if ($this->checkOracle) {
519 				$sourceSchema = $this->connection->createSchema();
520 				$this->ensureOracleConstraints($sourceSchema, $targetSchema, strlen($this->connection->getPrefix()));
521 			}

**Comment by nickvergessen** [comment]
Went for a more simplistic approach now, with hopefully no "production" impact (unless the release is containing a new broken migration), but it still fails hard on installation:

    Only on installation we want to break hard, so that all developers notice
    the bugs when installing the app on any database or CI, and can work on
    fixing their migrations before releasing a version incompatible with Postgres.
    
    In case of updates we might be running on production instances and the
    administrators being faced with the error would not know how to resolve it
    anyway. This can also happen with instances, that had the issue before the
    current update, so we don't want to make their life more complicated
    than needed.

**Review by Altahrim — APPROVED** [review]
