### PR TITLE
Fix primary key change in user_ldap migration

### LINKED ISSUE #30539: [23.0.1RC1, 22.2.4RC1] DB migration issue with user_ldap with postgres
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Get latest 22.2.3/23.0.0 and install it
2. enable LDAP, configure it with groups, visit users page to ensure the mapping tables are not empty
3. switch to beta channel
4. upgrade

### Expected behaviour

- upgrade procedure runs through smoothly

### Actual behaviour

- Exception: `Database error when running migration latest for app user_ldap`
- in the log we find: `SQLSTATE[42704]: Undefined object: 7 ERROR:  index \"primary\" does not exist"`

## Background

- The issue lies within https://github.com/nextcloud/server/blob/master/apps/user_ldap/lib/Migration/Version1130Date20211102154716.php#L107-L108
- There is no index called "primary", to resolve this the second line has to provide the existing name of the private key, which is `oc_ldap_group_mapping_pkey` for the table in question. Because when it is not the case, Doctrine will choose to drop `"primary"`
- It is fruitless nevertheless, because the index cannot be dropped: 
  - ``SQLSTATE[2BP01]: Dependent objects still exist: 7 ERROR:  cannot drop index oc_ldap_group_mapping_pkey because constraint oc_ldap_group_mapping_pkey on table oc_ldap_group_mapping requires it
HINT:  You can drop constraint oc_ldap_group_mapping_pkey on table oc_ldap_group_mapping instead.``
  - Removing line 107 does not help, for `n index with name 'oc_ldap_group_mapping_pkey' was already defined on table 'oc_ldap_group_mapping'.`
  - At the moment Doctrine does not support removing primary key constraints. This may be added, my naive attempts so far were not successful.
    - Upstream issue: https://github.com/doctrine/dbal/issues/2925
- Sqlite is not affected, MySQL and Oracle i have not tested.

@skjnldsv imo this is a release blocker

cc @nickvergessen @come-nc

### PR DESCRIPTION
**Pull request by come-nc**
Use a backup table to copy the data, drop table and recreate it with
 correct primary key, then copy the data back and drop the backup table.

Fix https://github.com/nextcloud/server/issues/30539

Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

### CODE REVIEW

File: apps/user_ldap/lib/Migration/Version1130Date20211102154716.php [hunk 1]
```diff
@@ -52,6 +52,50 @@ public function getName() {
...
+	 * @param IOutput $output
+	 * @param \Closure $schemaClosure The `\Closure` returns a `ISchemaWrapper`
+	 * @param array $options
+	 * @since 13.0.0
+	 */
+	public function preSchemaChange(IOutput $output, \Closure $schemaClosure, array $options) {
+		/** @var ISchemaWrapper $schema */
+		$schema = $schemaClosure();
+
+		if (!$schema->hasTable('twofactor_backup_codes')) {
```
Comment (blizzz) [inline apps/user_ldap/lib/Migration/Version1130Date20211102154716.php:65]: `twofactor_backup_codes`?

Comment (come-nc) [reply apps/user_ldap/lib/Migration/Version1130Date20211102154716.php]: Bad copy paste, see new version.

File: apps/user_ldap/lib/Migration/Version1130Date20220110154717.php [hunk 2]
```diff
@@ -0,0 +1,159 @@
...
+
+	protected function copyGroupMappingData(string $sourceTable, string $destinationTable): void {
+		$insert = $this->dbc->getQueryBuilder();
+		$insert->insert($destinationTable)
+			->values([
+				'ldap_dn' => $insert->createParameter('ldap_dn'),
+				'owncloud_name' => $insert->createParameter('owncloud_name'),
+				'directory_uuid' => $insert->createParameter('directory_uuid'),
+				'ldap_dn_hash' => $insert->createParameter('ldap_dn_hash'),
+			]);
```
[the remark this answers is not in the document]
Comment (blizzz) [reply apps/user_ldap/lib/Migration/Version1130Date20220110154717.php:57]: Otherwise looks good, would test. But state is still developing?

File: apps/user_ldap/lib/Migration/Version1130Date20211102154716.php [hunk 3]
```diff
@@ -103,11 +103,38 @@ public function changeSchema(IOutput $output, Closure $schemaClosure, array $opt
 					$table->addUniqueIndex(['directory_uuid'], 'ldap_group_directory_uuid');
 					$changeSchema = true;
 				}
-				if (!$table->hasPrimaryKey() || ($table->getPrimaryKeyColumns() !== ['owncloud_name'])) {
-					$table->dropPrimaryKey();
+				if (!$table->hasPrimaryKey()) {
```
Comment (nickvergessen) [inline apps/user_ldap/lib/Migration/Version1130Date20211102154716.php:106]: Logic from here onwards looks wild.
I would vote to remove all the logic parts and simply do the double copy/create in any case to make sure you didn't create a loop hole somewhere.

File: apps/user_ldap/lib/Migration/Version1130Date20220110154717.php [hunk 4]
```diff
@@ -0,0 +1,159 @@
...
+		/** @var ISchemaWrapper $schema */
+		$schema = $schemaClosure();
+
+		if (!$schema->hasTable('ldap_group_mapping_backup')) {
+			// Backup table does not exist
+			return null;
+		}
+
+		$schema->dropTable('ldap_group_mapping');
+		$table = $schema->createTable('ldap_group_mapping');
```
Comment (nickvergessen) [inline apps/user_ldap/lib/Migration/Version1130Date20220110154717.php:114]: You can not create a table again in the same migration where you drop it, as the dropping happens only after the migration and so the new tbale will be gone.

**Review by nickvergessen — CHANGES_REQUESTED** [review]

File: apps/user_ldap/lib/Migration/Version1130Date20211102154716.php (hunk 3 above)
Comment (come-nc) [reply apps/user_ldap/lib/Migration/Version1130Date20211102154716.php:106]: I want to avoid having a double copy for new installations that do not need the migration.

File: apps/user_ldap/lib/Migration/Version1130Date20220110154717.php (hunk 4 above)
Comment (come-nc) [reply apps/user_ldap/lib/Migration/Version1130Date20220110154717.php:114]: I was afraid of this, does it mean I need 4 migration classes?

File: apps/user_ldap/lib/Migration/Version1130Date20220110154717.php (hunk 2 above)
[the remark this answers is not in the document]
Comment (come-nc) [reply apps/user_ldap/lib/Migration/Version1130Date20220110154717.php:57]: If you know of a better way for copy/pasting from table to table I’ll take it, I used https://github.com/nextcloud/spreed/blob/dc518c46a710e13485feb0977b0f1343eea6d2ec/lib/Migration/Version10000Date20201015134000.php#L185 as an example, I am not fluent in Doctrine.
I did not test the migration yet as I was expecting something like https://github.com/nextcloud/server/pull/30568#discussion_r781431812 to come up.

File: apps/user_ldap/lib/Migration/Version1130Date20220110154717.php (hunk 4 above)
Comment (nickvergessen) [reply apps/user_ldap/lib/Migration/Version1130Date20220110154717.php:114]: * create backup + copy data
* remove orig
* create orig + copy data
* remove backup

yes.

File: apps/user_ldap/lib/Migration/Version1130Date20211102154716.php (hunk 3 above)
Comment (nickvergessen) [reply apps/user_ldap/lib/Migration/Version1130Date20211102154716.php:106]: well new installs will have no content so it's quick?

Comment (come-nc) [reply apps/user_ldap/lib/Migration/Version1130Date20211102154716.php:106]: I guess, but it still feels weird to create 3 tables where one is needed in installation process

File: apps/user_ldap/lib/Migration/Version1130Date20220110154717.php (hunk 4 above)
Comment (come-nc) [reply apps/user_ldap/lib/Migration/Version1130Date20220110154717.php:114]: Ok, will do

File: apps/user_ldap/lib/Migration/GroupMappingMigration.php [hunk 5]
```diff
@@ -0,0 +1,69 @@
...
+ * along with this program. If not, see <http://www.gnu.org/licenses/>.
+ *
+ */
+
+namespace OCA\User_LDAP\Migration;
+
+use OCP\IDBConnection;
+use OCP\Migration\SimpleMigrationStep;
+
+class GroupMappingMigration extends SimpleMigrationStep {
```
Comment (nickvergessen) [inline apps/user_ldap/lib/Migration/GroupMappingMigration.php:32]:
```suggestion
abstract class GroupMappingMigration extends SimpleMigrationStep {
```

File: apps/user_ldap/lib/Migration/Version1130Date20211102154716.php [hunk 6]
```diff
@@ -103,11 +103,38 @@ public function changeSchema(IOutput $output, Closure $schemaClosure, array $opt
...
 					$table->setPrimaryKey(['owncloud_name']);
 					$changeSchema = true;
 				}
+
+				if ($table->getPrimaryKeyColumns() !== ['owncloud_name']) {
```
Comment (nickvergessen) [inline apps/user_ldap/lib/Migration/Version1130Date20211102154716.php:111]: Mind to comment which case there could be? From this file it's either none (then it's created) or `'owncloud_name'`

File: apps/user_ldap/lib/Migration/Version1130Date20220110154718.php [hunk 7]
```diff
@@ -32,8 +32,44 @@
 use OCP\Migration\SimpleMigrationStep;
 
 class Version1130Date20220110154718 extends SimpleMigrationStep {
+	/** @var IDBConnection */
+	private $dbc;
+
+	public function __construct(IDBConnection $dbc) {
```
Comment (blizzz) [inline apps/user_ldap/lib/Migration/Version1130Date20220110154718.php]: lacks a use statement

File: apps/user_ldap/lib/Migration/Version1130Date20220110154717.php (hunk 2 above)
[the remark this answers is not in the document]
Comment (blizzz) [reply apps/user_ldap/lib/Migration/Version1130Date20220110154717.php]: i have found some ideas how it could go, but nothing that earned my trust. Let's leave it like this instead of opening another construction site.

**Review by nickvergessen — APPROVED** [review]

File: apps/user_ldap/lib/Migration/Version1130Date20211102154716.php (hunk 3 above)
Comment (nickvergessen) [reply apps/user_ldap/lib/Migration/Version1130Date20211102154716.php:106]: But the installation never does it. It is taking a fast trip to the end and only generates the final result

File: apps/user_ldap/lib/Migration/Version1130Date20211102154716.php (hunk 6 above)
Comment (come-nc) [reply apps/user_ldap/lib/Migration/Version1130Date20211102154716.php:111]: In 23 primary key for ldap_group_mapping was ldap_dn, which is the reason for all this.
It was changed in https://github.com/nextcloud/server/pull/29523/files#diff-305e20bed2077c1acd13cbf1051427e1179e19d0bfa3054635a99a83827e01a3R89-R95

File: apps/user_ldap/lib/Migration/Version1130Date20211102154716.php (hunk 3 above)
Comment (come-nc) [reply apps/user_ldap/lib/Migration/Version1130Date20211102154716.php:106]: I had to switch to always creating the table in the end because of other problems with mysql it was easier this way.

**Comment by come-nc** [comment]
Ok, I tested the migration and had to refactor a bit, as enlarging the ldap_dn column on ldap_group_mapping was failing because it was a primary key. So now it always goes through the double copy/drop to get the ldap_group_mapping table in the right shape. It worked for my test but I only tested mysql.
I also had to update the autoloader which triggered a lot of small psalm changes, not sure if expected or not.

**Comment by nickvergessen** [comment]
> Conflicting files
apps/dav/composer/composer/installed.php 

Maybe you can revert the autoloading paart and then only commit the modified files in apps/user_ldap?

**Review by nickvergessen — APPROVED** [review]
LGTM apart from the psalm/composer change

**Comment by skjnldsv** [comment]
Please rebase so we can merge :)

**Comment by come-nc** [comment]
Rebased and removed the autoloader update, can someone which understand this stuff do the autoloader update?

**Comment by nickvergessen** [comment]
```sh
bash build/autoloaderchecker.sh
git add apps/user_ldap/composer/composer/autoload_*
git commit
git restore apps/
```

Done

**Comment by come-nc** [comment]
Drone failure is unrelated

**Comment by blizzz** [comment]
With the latest commit, migration run through like a hot knife through butter! :medal_sports: @come-nc

**Review by blizzz — APPROVED** [review]
