### PR TITLE
Avoid zero division in setup checks

### LINKED ISSUE #30532: Division by zero in file 'apps/settings/lib/Controller/CheckSetupController.php' line 503
I just updated via `settings/admin/overview` from 23.0.0 to 23.0.1 RC1 (on beta channel), then reloaded `settings/admin/overview` three times. The first two times there was a warning that I shall update indices via occ or similar, since the third time I always get this error on `settings/admin/logging`:

```
Error | index | Exception: Division by zero in file 'apps/settings/lib/Controller/CheckSetupController.php' line 503
```

and in `nextcloud.log` respectively:

```
{"reqId":"pqpQOpO430mjkur7IQbW","level":3,"time":"2022-01-07T16:58:28+01:00","remoteAddr":"192.168.1.2","user":"admin","app":"index","method":"GET","url":"/settings/ajax/checksetup","message":"Division by zero in file 'apps/settings/lib/Controller/CheckSetupController.php' line 503","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0","version":"23.0.1.0","exception":{"Exception":"Exception","Message":"Division by zero in file 'apps/settings/lib/Controller/CheckSetupController.php' line 503","Code":0,"Trace":[{"file":"lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"lib/private/AppFramework/Http/Dispatcher.php","Line":158,"Previous":{"Exception":"DivisionByZeroError","Message":"Division by zero","Code":0,"Trace":[{"file":"apps/settings/lib/Controller/CheckSetupController.php","line":821,"function":"getOpcacheSetupRecommendations","class":"OCA\\Settings\\Controller\\CheckSetupController","type":"->"},{"file":"lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"check","class":"OCA\\Settings\\Controller\\CheckSetupController","type":"->"},{"file":"lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"apps/settings/lib/Controller/CheckSetupController.php","Line":503},"CustomMessage":"--"}}

```

**Operating system:** Arch Linux
**Web server:** NGINX
**Database:** MariaDB
**PHP version:** 8.0

### PR DESCRIPTION
**Pull request by MichaIng**
Fixes: https://github.com/nextcloud/server/issues/30532

### CODE REVIEW

**Comment by acsfer** [comment]
Shouldn't it be `!empty` ? 🤔

**Comment by MichaIng** [comment]
It's the free memory and the max cached keys. In both cases, when they are null, nothing can be cached anymore, hence the warning as a performance recommendation makes sense. Not sure whether any max value can be actually set to `0` without disabling OPcache all together, I'm currently failing to apply `opache.interned_strings_usage` on my server, the returned value remains at `8` 😕. I'll spin up another VM. However, it doesn't change something about the recommendation to always have 10% left free buffer, for interned strings, keys and overall OPcache size.

**Comment by MichaIng** [comment]
Another thing: Is there probably a flag for one of the CI checks/tools to fail on division of unverified variables?

File: apps/settings/lib/Controller/CheckSetupController.php [hunk 1]
```diff
@@ -492,15 +492,15 @@ protected function getOpcacheSetupRecommendations(): array {
 			$status = opcache_get_status(false);
 
 			// Recommend to raise value, if more than 90% of max value is reached
-			if ($status['opcache_statistics']['num_cached_keys'] / $status['opcache_statistics']['max_cached_keys'] > 0.9) {
+			if (empty($status['opcache_statistics']['max_cached_keys']) || $status['opcache_statistics']['num_cached_keys'] / $status['opcache_statistics']['max_cached_keys'] > 0.9) {
```
Comment (come-nc) [inline apps/settings/lib/Controller/CheckSetupController.php:495]: Feels like too many operators without parenthesis to me, with the line length it’s hard to read and you have to know by heart precedence of `|| / >`

Comment (MichaIng) [reply apps/settings/lib/Controller/CheckSetupController.php:495]: Arithmetic actions always have higher precedence than logical operators. Of course I also tested it. So it wouldn't change the logic, but we could either use `or` instead of `||` or add parenthesis to the right side comparison.

I agree with the line length isn't great. Any suggestions how to split? My suggestion would be to declare shortcut variables for the long array calls as IMHO splitting the condition itself makes reading it more difficult as well.

However, we must have this merged soon + backport into NC23 RC2 the one or the other way, otherwise some users run into PHP errors when visit the admin panel.

Comment (come-nc) [reply apps/settings/lib/Controller/CheckSetupController.php:495]:
```suggestion
			if (
				empty($status['opcache_statistics']['max_cached_keys']) || 
				($status['opcache_statistics']['num_cached_keys'] / $status['opcache_statistics']['max_cached_keys'] > 0.9)
			) {
```

Comment (come-nc) [reply apps/settings/lib/Controller/CheckSetupController.php:495]: Something like this I suppose.

Comment (MichaIng) [reply apps/settings/lib/Controller/CheckSetupController.php]: Applied.

**Review by come-nc — APPROVED** [review]

**Comment by MichaIng** [comment]
jsunit failure is unrelated, same as here: #30557

**Review by szaimen — APPROVED** [review]
