### PR TITLE
Disable Clear-Site-Data for Chrom* (and Opera, Brave, etc)

### LINKED ISSUE #9179: Slow log out.
### Steps to reproduce
1. Log into nextcloud
2. Log out
3.

### Expected behaviour
Log out should be as fast as log in.  There should not be a delay to get out of the system.

### Actual behaviour
I have two instances of Nextcloud (one mine, one is a friends). Both are V 13.1.  Either may take anywhere from 5 to 30 seconds to achieve log out.

### Server configuration

**Operating system**:
Ubuntu

**Web server:**
Apache2
**Database:**
MySQL
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
13.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
One of each
**Where did you install Nextcloud from:**
Web
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
Enabled:
  - activity: 2.6.1
  - apporder: 0.4.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.3
  - dashboard: 4.0.6
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - passman: 2.1.4
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - weather: 1.5.1
  - workflowengine: 1.3.0

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "bobbi1.is-an-artist.net",
            "192.168.0.16",
            "192.168.50.176"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/bobbi1.is-an-artist.net\/nextcloud",
        "dbtype": "mysql",
        "version": "13.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "defaultapp": "calendar,files,dashboard",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
chromium, Google Chrome
**Operating system:**
Ubuntu
### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

N/A
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"JTdr8OQ7ACQEgPi71sJ0","level":3,"time":"2018-04-13T17:23:54+00:00","remoteAddr":"71.48.121.114","user":"wjw","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/settings\/admin","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/nextcloud\/apps\/passman\/personal.php:1) at \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Output.php#69","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}

Insert your Nextcloud log here

</details>

#### Browser log
<details>
<summary>Browser log</summary>

N/A
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
JQMIGRATE: Migrate is installed, version 1.4.0
12:32:08.990 DevTools failed to parse SourceMap: https://bobbi1.is-an-artist.net/nextcloud/core/vendor/purify.min.js.map
12:32:09.381 inject.js:324 Found 1 logins for this site
12:32:09.443 inject.js:324 Found 1 logins for this site
</details>

### PR DESCRIPTION
**Pull request by kesselb**
Close #9179 (again)

I think Clear-Site-Data is a good feature but it will slow down the logout for chromium based browsers. For some reason clearing the site data (see https://github.com/nextcloud/server/issues/9179#issuecomment-502928769 and https://github.com/nextcloud/server/issues/9179#issuecomment-509629565) takes a while. There is nothing we can do.

People will always complain to their administrators about the slow logout. We should give them a way to opt out. I've been thinking about sending the header only for firefox but this makes things even more complicated. 

Since this patch has no real impact I would like to ask for a backport to 17.

### CODE REVIEW

**Comment by skjnldsv** [comment]
I'm really not sure :/
What is really the cause of slow logout on firefox? Why is ff taking so long? Is there an opened bug report for it?

**Comment by kesselb** [comment]
> What is really the cause of slow logout on firefox? Why is ff taking so long?

Chrome (and everything else based on chromium) ;) It's working fine with Firefox. 

>  Is there an opened bug report for it?

https://bugs.chromium.org/p/chromium/issues/detail?id=762417 They merged a fix for Chromium 77 (Stable Release Tue, Sep 10, 2019). Added this information to https://github.com/nextcloud/server/issues/9179#issuecomment-549144715. Let's wait for feedback ;)

**Comment by kesselb** [comment]
I think we should turn it off by default for now. There more than 70 reports over at #9179. We can't fix it but people will always think it's related to Nextcloud. 

According to https://bugs.chromium.org/p/chromium/issues/detail?id=762417#c37 GitHub does not send the header anymore for chrome.

**Review by ChristophWurst — APPROVED** [review]
I agree that there is no other way to fix this right now

:+1: :cry:

**Review by skjnldsv — APPROVED** [review]

**Comment by rullzer** [comment]
I don't like it.
Lets either kill it all together. Or do it by user agent.

Having it as a config option doesn't help. Because this is not something a lot of users can change.

**Comment by skjnldsv** [comment]
> Or do it by user agent.

Did not thought of this! Nice idea! :)

**Comment by kesselb** [comment]
> Or do it by user agent.

Fine by me but I'm not a fan :)

File: core/Controller/LoginController.php [hunk 1]
```diff
@@ -128,7 +128,11 @@ public function logout() {
 
 		$this->session->set('clearingExecutionContexts', '1');
 		$this->session->close();
-		$response->addHeader('Clear-Site-Data', '"cache", "storage"');
+
+		if (!$this->request->isUserAgent(['#Chrome/#'])) {
```
Comment (skjnldsv) [inline core/Controller/LoginController.php]: we have a list of valid user agent somewhere in a php class iirc :)

Comment (kesselb) [reply core/Controller/LoginController.php]: Yes. They are a bit more specific than `'#Chrome/#'` :laughing:

**Review by skjnldsv — APPROVED** [review]
