### PR TITLE
fix(db): remove redundant index in cards

### LINKED ISSUE #43118: [Bug]: Redundant oc_cards.cards_abid index
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

```sql
create index cards_abid
    on nextclouddev.oc_cards (addressbookid);

create index cards_abiduri
    on nextclouddev.oc_cards (addressbookid, uri);
```

cards_abiduri makes cards_abid. INSERT and DELETE queries need two indices to be maintained. UPDATE should not be affected as long as we ever write a new addressbookid or uri.

Tested with 26 (prod) and master/29 (dev).

### Steps to reproduce

1. Install Nextcloud

### Expected behavior

Efficient database index usage

### Installation method

None

### Nextcloud Server version

26

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by JohannesGGE**
* Resolves: #43118

## Summary
Remove index `cards_abid` because `cards_abiduri` already contains the column on the first position.

## TODO

- [ ] ...

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/dav/lib/Migration/Version1031Date20240131123900.php [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+	 * @param array $options
+	 * @return null|ISchemaWrapper
+	 */
+	public function changeSchema(IOutput $output, Closure $schemaClosure, array $options): ?ISchemaWrapper {
+		/** @var ISchemaWrapper $schema */
+		$schema = $schemaClosure();
+
+		$tableCards = $schema->getTable('cards');
+
+		if ($tableCards->hasIndex('cards_abid')) {
```
Comment (solracsf) [inline apps/dav/lib/Migration/Version1031Date20240131123900.php:48]:
```suggestion
		if ($tableCards->hasIndex('cards_abiduri')) &&
			($tableCards->hasIndex('cards_abid')) {
```
Maybe double check?

**Review by st3iny — APPROVED** [review]
Looks good

**Review by miaulalala — APPROVED** [review]

**Review by ChristophWurst — DISMISSED** [review]
Comment out the index creation in `\OCA\DAV\Migration\Version1004Date20170924124212::changeSchema` to avoid creating and dropping the index for new installations

**Review by st3iny — APPROVED** [review]
