### PR TITLE
(base) Give a hint in web interface if SimpleXML (php-xml) is missing

### LINKED ISSUE #2180: PHP7 Check for missing modules incomplete (should check for php-xml)
Nextcloud seems to check if a required php module is missing. This does not seem to be the case for php-xml. If this module is missing only a 500 server error is reported when accessing the page.

### Steps to reproduce
1. Install nextcloud on a machine using php7.0 and WITHOUT the php7.0-xml module installed
2. Access the nextcloud login page

### Expected behaviour
Nextcloud should tell me that the xml php module is missing as it does for other modules (like mbstring for example).

### Actual behaviour
A 500 server error is thrown and then I need to check the log. The log tells me: 
```
Exception: {\"Exception\":\"Error\",\"Message\":\"Call to undefined function OC\\\\AppFramework\\\\simplexml_load_file()\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/app.php(177): OC\\\\AppFramework\\\\App::buildAppNamespace('files')\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/app.php(115): OC_App::registerAutoloading('files', '\\\/var\\\/www\\\/nextcl...')\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(658): OC_App::loadApps(Array)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1059): OC::init()\\n#4 \\\/var\\\/www\\\/nextcloud\\\/index.php(46): require_once('\\\/var\\\/www\\\/nextcl...')\\n#5 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php\",\"Line\":60}
```
And then I have to figure out myself that this may be due to a missing php module.

### Server configuration
**Operating system**: Ubuntu Xenial

**Web server:** Apache 2x

**Database:** MariaDB

**PHP version:** 7.0

**Nextcloud version:** 10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from owncloud -> nextcloud 9 -> nextcloud 10.0.1

### PR DESCRIPTION
**Pull request by joshtrichards**
* Resolves: #2180  
* And prevents similar reports: 
  - #31473
  - #23970
  - #18610
  - #15708

## Summary

Avoids a 500 error and also gives a useful error message on the web interface if this module isn't installed, gets overlooked during a PHP upgrade, etc.

* While we check for it later, it's too late for session.
* Inspired by #17163
* Related to #2619 (which was never merged and seemed intended to silence things rather than give the user a useful hint for self-resolution)

## TODO

- [ ] Maybe some field testing?

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [ ] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by joshtrichards** [comment]
Test failures appear unrelated. jsunit had a bunch of setup errors.

**Review by come-nc — COMMENTED** [review]
How will cli behave in this situation?

**Comment by joshtrichards** [comment]
The CLI will behave how it does now - i.e. it'll generate an `Error: Call to undefined function OC\App\simplexml_load_file() in...` stack trace.

I suppose this is an opportunity to provide a friendly message at the command-line too, but the stack trace is at least visible there...

File: lib/base.php [hunk 1]
```diff
@@ -698,6 +698,28 @@ public static function init(): void {
...
+				http_response_code(503);
+				OC_Util::addStyle('guest');
+				try {
+					OC_Template::printGuestPage('', 'error', ['errors' => $errors]);
+					exit;
+				} catch (\Exception $e) {
+					// In case any error happens when showing the error page, we simply fall back to posting the text.
+					// This might be the case when e.g. the data directory is broken and we can not load/write SCSS to/from it.
+				}
+			}
```
Comment (come-nc) [inline lib/base.php:720]:
```suggestion
			throw new \OCP\HintException('The PHP SimpleXML/PHP-XML extension is not installed.', 'Install the extension or make sure it is enabled.');
			}
```

How about that?

Can you try both versions and show screenshots of the result if it is not the same?
It’s weird to have manual handling for this particular exception.

Comment (skjnldsv) [reply lib/base.php:722]: Works!

**Comment by skjnldsv** [comment]
Rebased and addressed :muscle:

**Review by skjnldsv — APPROVED** [review]

**Review by sorbaugh — APPROVED** [review]

**Comment by skjnldsv** [comment]
:tada: :tada: :tada:
