### PR TITLE
fix(files): handle empty view with error

### LINKED ISSUE #45190: "No files" display on Files tab w/ faulty federation shares or External Storage
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

A federation share (displayed as a top level folder) went down. On NC 27.1.9, I noticed nothing. After upgrading to 28.0.5, my files were not displayed with a message like "No files" in the NC files tab.

### Steps to reproduce

1. A federation share (displayed as a top level folder) goes down.
2. Click on Files tab.
3. No files/folders showing. (And the "+ New" button is greyed with the following message: "You don’t have permission to upload or create files here".)

### Expected behavior

Files showing. Maybe a message/pop-up to inform the user that the federation share is unavailable?

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nuage.casterlyrock.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.5.1",
        "overwrite.cli.url": "https:\/\/nuage.casterlyrock.net",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "app_install_overwrite": [
            "files_clipboard",
            "ncdownloader"
        ],
        "has_rebuilt_cache": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "default_phone_region": "FR",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - calendar: 4.7.2
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contacts: 5.5.3
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - mail: 3.6.0
  - nextcloud_announcements: 1.17.0
  - notes: 4.10.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - snappymail: 2.36.1
  - support: 1.11.1
  - survey_client: 1.16.0
  - suspicious_login: 6.0.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - circles: 28.0.0 (installed 28.0.0)
  - contactsinteraction: 1.9.0 (installed 1.5.0)
  - dashboard: 7.8.0 (installed 6.0.0)
  - encryption: 2.16.0
  - files_external: 1.20.0
  - twofactor_totp: 10.0.0-beta.2
  - user_ldap: 1.19.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

Too many logs. I hope this part is relevant:

```
{"reqId":"Y7nyAP0WnXD9pa2wHivP","level":3,"time":"2024-05-05T21:45:58+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Error while running background job (class: OCA\\Mail\\BackgroundJob\\QuotaJob, arguments: Array\n(\n    [accountId] => 1\n)\n)","userAgent":"--","version":"28.0.5.1","exception":{"Exception":"Horde_Imap_Client_Exception","Message":"Authentication failed.","Code":102,"Trace":[{"file":"/var/www/nextcloud/apps/mail/vendor/bytestream/horde-imap-client/lib/Horde/Imap/Client/Socket.php","line":4584,"function":"_responseCode","class":"Horde_Imap_Client_Socket","type":"->"},{"file":"/var/www/nextcloud/apps/mail/vendor/bytestream/horde-imap-client/lib/Horde/Imap/Client/Socket.php","line":4319,"function":"_getLine","class":"Horde_Imap_Client_Socket","type":"->"},{"file":"/var/www/nextcloud/apps/mail/vendor/bytestream/horde-imap-client/lib/Horde/Imap/Client/Socket.php","line":4243,"function":"_sendCmdChunk","class":"Horde_Imap_Client_Socket","type":"->"},{"file":"/var/www/nextcloud/apps/mail/vendor/bytestream/horde-imap-client/lib/Horde/Imap/Client/Socket.php","line":851,"function":"_sendCmd","class":"Horde_Imap_Client_Socket","type":"->"},{"file":"/var/www/nextcloud/apps/mail/vendor/bytestream/horde-imap-client/lib/Horde/Imap/Client/Socket.php","line":512,"function":"_tryLogin","class":"Horde_Imap_Client_Socket","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/mail/lib/IMAP/ImapClientRateLimitingDecorator.php","line":73,"function":"_login","class":"Horde_Imap_Client_Socket","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/mail/vendor/bytestream/horde-imap-client/lib/Horde/Imap/Client/Base.php","line":853,"function":"_login","class":"OCA\\Mail\\IMAP\\ImapClientRateLimitingDecorator","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/mail/vendor/bytestream/horde-imap-client/lib/Horde/Imap/Client/Base.php","line":1404,"function":"login","class":"Horde_Imap_Client_Base","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/mail/lib/IMAP/FolderMapper.php","line":66,"function":"listMailboxes","class":"Horde_Imap_Client_Base","type":"->"},{"file":"/var/www/nextcloud/apps/mail/lib/Service/MailManager.php","line":598,"function":"getFolders","class":"OCA\\Mail\\IMAP\\FolderMapper","type":"->"},{"file":"/var/www/nextcloud/apps/mail/lib/BackgroundJob/QuotaJob.php","line":97,"function":"getQuota","class":"OCA\\Mail\\Service\\MailManager","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/Job.php","line":81,"function":"run","class":"OCA\\Mail\\BackgroundJob\\QuotaJob","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":102,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":92,"function":"start","class":"OCP\\BackgroundJob\\TimedJob","type":"->"},{"file":"/var/www/nextcloud/cron.php","line":152,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/www/nextcloud/apps/mail/vendor/bytestream/horde-imap-client/lib/Horde/Imap/Client/Socket.php","Line":5048,"message":"Error while running background job (class: OCA\\Mail\\BackgroundJob\\QuotaJob, arguments: Array\n(\n    [accountId] => 1\n)\n)","exception":{"details":null,"logged":false,"raw_msg":"Authentication failed."},"CustomMessage":"Error while running background job (class: OCA\\Mail\\BackgroundJob\\QuotaJob, arguments: Array\n(\n    [accountId] => 1\n)\n)"}}
{"reqId":"Y7nyAP0WnXD9pa2wHivP","level":3,"time":"2024-05-05T21:45:58+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Error while running background job (class: OCA\\Mail\\BackgroundJob\\QuotaJob, arguments: Array\n(\n    [accountId] => 3\n)\n)","userAgent":"--","version":"28.0.5.1","exception":{"Exception":"Horde_Imap_Client_Exception","Message":"Too many auth attempts","Code":102,"Trace":[{"file":"/var/www/nextcloud/apps/mail/vendor/bytestream/horde-imap-client/lib/Horde/Imap/Client/Base.php","line":853,"function":"_login","class":"OCA\\Mail\\IMAP\\ImapClientRateLimitingDecorator","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/mail/vendor/bytestream/horde-imap-client/lib/Horde/Imap/Client/Base.php","line":1404,"function":"login","class":"Horde_Imap_Client_Base","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/mail/lib/IMAP/FolderMapper.php","line":66,"function":"listMailboxes","class":"Horde_Imap_Client_Base","type":"->"},{"file":"/var/www/nextcloud/apps/mail/lib/Service/MailManager.php","line":598,"function":"getFolders","class":"OCA\\Mail\\IMAP\\FolderMapper","type":"->"},{"file":"/var/www/nextcloud/apps/mail/lib/BackgroundJob/QuotaJob.php","line":97,"function":"getQuota","class":"OCA\\Mail\\Service\\MailManager","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/Job.php","line":81,"function":"run","class":"OCA\\Mail\\BackgroundJob\\QuotaJob","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":102,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":92,"function":"start","class":"OCP\\BackgroundJob\\TimedJob","type":"->"},{"file":"/var/www/nextcloud/cron.php","line":152,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/www/nextcloud/apps/mail/lib/IMAP/ImapClientRateLimitingDecorator.php","Line":66,"message":"Error while running background job (class: OCA\\Mail\\BackgroundJob\\QuotaJob, arguments: Array\n(\n    [accountId] => 3\n)\n)","exception":{"details":null,"logged":false,"raw_msg":"Too many auth attempts"},"CustomMessage":"Error while running background job (class: OCA\\Mail\\BackgroundJob\\QuotaJob, arguments: Array\n(\n    [accountId] => 3\n)\n)"}}
{"reqId":"Y7nyAP0WnXD9pa2wHivP","level":2,"time":"2024-05-05T21:46:00+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":"error while discovering ocm provider","userAgent":"--","version":"28.0.5.1","exception":{"Exception":"GuzzleHttp\\Exception\\ConnectException","Message":"cURL error 52: Empty reply from server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://wyqu84.a4.swdrive.fr/ocm-provider/","Code":0,"Trace":[{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php","line":158,"function":"createRejection","class":"GuzzleHttp\\Handler\\CurlFactory","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php","line":110,"function":"finishError","class":"GuzzleHttp\\Handler\\CurlFactory","type":"::"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php","line":47,"function":"finish","class":"GuzzleHttp\\Handler\\CurlFactory","type":"::"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":137,"function":"__invoke","class":"GuzzleHttp\\Handler\\CurlHandler","type":"->"},{"file":"/var/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php","line":161,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php","line":35,"function":"OC\\Http\\Client\\{closure}","class":"OC\\Http\\Client\\DnsPinMiddleware","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":31,"function":"__invoke","class":"GuzzleHttp\\PrepareBodyMiddleware","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php","line":71,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":63,"function":"__invoke","class":"GuzzleHttp\\RedirectMiddleware","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php","line":75,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":331,"function":"__invoke","class":"GuzzleHttp\\HandlerStack","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":168,"function":"transfer","class":"GuzzleHttp\\Client","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":187,"function":"requestAsync","class":"GuzzleHttp\\Client","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Http/Client/Client.php","line":230,"function":"request","class":"GuzzleHttp\\Client","type":"->"},{"file":"/var/www/nextcloud/lib/private/OCM/OCMDiscoveryService.php","line":86,"function":"get","class":"OC\\Http\\Client\\Client","type":"->"},{"file":"/var/www/nextcloud/apps/files_sharing/lib/External/Storage.php","line":87,"function":"discover","class":"OC\\OCM\\OCMDiscoveryService","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Mount/MountPoint.php","line":168,"function":"__construct","class":"OCA\\Files_Sharing\\External\\Storage","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Mount/MountPoint.php","line":193,"function":"createStorage","class":"OC\\Files\\Mount\\MountPoint","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Files/Mount/MountPoint.php","line":294,"function":"getStorage","class":"OC\\Files\\Mount\\MountPoint","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Config/UserMountCache.php","line":83,"function":"getStorageRootId","class":"OC\\Files\\Mount\\MountPoint","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/SetupManager.php","line":297,"function":"registerMounts","class":"OC\\Files\\Config\\UserMountCache","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/SetupManager.php","line":221,"function":"afterUserFullySetup","class":"OC\\Files\\SetupManager","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/SetupManager.php","line":392,"function":"setupForUser","class":"OC\\Files\\SetupManager","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Mount/Manager.php","line":97,"function":"setupForPath","class":"OC\\Files\\SetupManager","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1372,"function":"find","class":"OC\\Files\\Mount\\Manager","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Node/Root.php","line":203,"function":"getFileInfo","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Node/LazyUserFolder.php","line":47,"function":"get","class":"OC\\Files\\Node\\Root","type":"->"},{"function":"OC\\Files\\Node\\{closure}","class":"OC\\Files\\Node\\LazyUserFolder","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Files/Node/LazyFolder.php","line":70,"function":"call_user_func"},{"file":"/var/www/nextcloud/lib/private/Files/Node/LazyFolder.php","line":84,"function":"getRealFolder","class":"OC\\Files\\Node\\LazyFolder","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Node/LazyFolder.php","line":442,"function":"__call","class":"OC\\Files\\Node\\LazyFolder","type":"->"},{"file":"/var/www/nextcloud/core/BackgroundJobs/GenerateMetadataJob.php","line":97,"function":"getDirectoryListing","class":"OC\\Files\\Node\\LazyFolder","type":"->"},{"file":"/var/www/nextcloud/core/BackgroundJobs/GenerateMetadataJob.php","line":88,"function":"scanFolder","class":"OC\\Core\\BackgroundJobs\\GenerateMetadataJob","type":"->"},{"file":"/var/www/nextcloud/core/BackgroundJobs/GenerateMetadataJob.php","line":74,"function":"scanFilesForUser","class":"OC\\Core\\BackgroundJobs\\GenerateMetadataJob","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/Job.php","line":81,"function":"run","class":"OC\\Core\\BackgroundJobs\\GenerateMetadataJob","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":102,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":92,"function":"start","class":"OCP\\BackgroundJob\\TimedJob","type":"->"},{"file":"/var/www/nextcloud/cron.php","line":152,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php","Line":210,"message":"error while discovering ocm provider","exception":{},"remote":"https://wyqu84.a4.swdrive.fr","CustomMessage":"error while discovering ocm provider"}}
```
### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ShGKme**
* Resolves: https://github.com/nextcloud/server/issues/45190
* Same issue for any errors: no permissions, not found, server unavailable etc.

## Summary

Handles error during content fetching.

In Nextcloud 27 in case of an error it redirected to the `/` root and (sometimes) showed a toast message with an error.

https://github.com/nextcloud/server/blob/ba452f953c0bed415014b3123aed96bef3883888/apps/files/js/filelist.js#L2256-L2296

After migrating to Vue, there is no error handling. It just shows a folder as an empty folder.

It is especially confusing when it was supposed to be a valid link:
- Unshared/deleted shared folder
- Unavailable storage

It looks like the folder is available, just empty.

I found redirecting to the root less convenient to a user in flavor of explicitly showing an error and a button to reload it. 

But I'm not sure about the text/design.

## Screenshots

Before | After
---|---
image | image

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [ ] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/files/src/views/FilesList.vue [hunk 1]
```diff
@@ -75,16 +75,32 @@
...
 		<template v-else-if="!loading && isEmptyDir">
-			<div v-if="currentView?.emptyView" class="files-list__empty-view-wrapper">
+			<!-- Empty due to error -->
+			<NcEmptyContent v-if="error" :name="error" data-cy-files-content-error>
+				<template #action>
+					<NcButton type="secondary" @click="fetchContent">
+						<template #icon>
+							<IconReload :size="20" />
+						</template>
+						{{ t('files', 'Reload') }}
```
Comment (susnux) [inline apps/files/src/views/FilesList.vue:85]: Maybe retry?

Comment (skjnldsv) [reply apps/files/src/views/FilesList.vue:85]: Seconded

File: apps/files/src/views/FilesList.vue [hunk 2]
```diff
@@ -537,6 +557,22 @@ export default defineComponent({
...
+					} else if (status === 500) {
+						this.error = t('files', 'This directory is unavailable, please check the logs or contact the administrator')
+					} else if (status === 503) {
+						this.error = t('files', 'Storage is temporarily not available')
+					} else {
+						this.error = t('files', 'Unexpected error: {error}', { error: error.message })
+					}
+				} else {
+					this.error = t('files', 'Unknown error')
+				}
```
Comment (skjnldsv) [inline apps/files/src/views/FilesList.vue:575]: I've seen this code snippet before in our vue migration.
Maybe it should be a composable or mixin instead of a copy ? :thinking:

File: apps/files/src/views/FilesList.vue (hunk 1 above)
Comment (ShGKme) [reply apps/files/src/views/FilesList.vue:85]: Done

File: apps/files/src/views/FilesList.vue (hunk 2 above)
Comment (ShGKme) [reply apps/files/src/views/FilesList.vue:575]: It is not a direct copy, but addopted simular code (linked in the PR description).

Moving to an util (not a mixin/composable as this is not a part of Vue component).

File: apps/files/src/views/FilesList.vue (hunk 1 above)
Comment (skjnldsv) [reply apps/files/src/views/FilesList.vue:85]: Forgot to push @ShGKme ? :see_no_evil:

Comment (ShGKme) [reply apps/files/src/views/FilesList.vue]: Wanted to push together with the second change :)

File: apps/files/src/views/FilesList.vue (hunk 2 above)
Comment (ShGKme) [reply apps/files/src/views/FilesList.vue]: Moved to utils

Comment (ShGKme) [reply apps/files/src/views/FilesList.vue]: Maybe make sense to move to nextcloud-files

**Comment by ShGKme** [comment]
Icon is updated

image

File: apps/files/src/utils/davUtils.ts [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+import { t } from '@nextcloud/l10n'
+import type { WebDAVClientError } from 'webdav'
+
+/**
+ * Check whether this is a public share
+ * @return {boolean} Whether this is a public share
+ */
+export function isPublic() {
+	return !getCurrentUser()
+}
```
Comment (susnux) [inline apps/files/src/utils/davUtils.ts:16]: Where is this used? Should be removed as we have this in `@nextcloud/sharing/public`

File: apps/files/src/components/TemplatePreview.vue [hunk 4]
```diff
@@ -33,7 +33,7 @@
 <script>
 import { encodePath } from '@nextcloud/paths'
 import { generateUrl } from '@nextcloud/router'
-import { getToken, isPublic } from '../utils/davUtils.js'
+import { getToken, isPublic } from '../utils/davUtils.ts'
```
Comment (susnux) [inline apps/files/src/components/TemplatePreview.vue:36]: Ah overlooke this, should be just replaced with `@nextcloud/sharing` instead of keeping duplicates in server

File: apps/files/src/utils/davUtils.ts (hunk 3 above)
Comment (ShGKme) [reply apps/files/src/utils/davUtils.ts:16]: I only migrated module to TS 👀

File: apps/files/src/components/TemplatePreview.vue (hunk 4 above)
Comment (ShGKme) [reply apps/files/src/components/TemplatePreview.vue]: Done

**Review by susnux — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by ShGKme** [comment]
Rebased onto master, squashed
