### PR TITLE
Filter out backup user status (those beginning with _ as userId)

### LINKED ISSUE #34464: [Bug]: Dashboard "recent status": duplicate entry?
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When querying {{ base_url  }}/ocs/v2.php/apps/dashboard/api/v1/widget-items with user_status I got:
```
{
					"subtitle": "🇺🇦 no war, seconds ago",
					"title": "_julia",
					"link": "https:\/\/cloud.nextcloud.com\/u\/_julia",
					"iconUrl": "https:\/\/cloud.nextcloud.com\/avatar\/_julia\/44",
					"sinceId": "1665133772"
				},
				{
					"subtitle": "💬 In a call, 3 minutes ago",
					"title": "Julia …",
					"link": "https:\/\/cloud.nextcloud.com\/u\/julia",
					"iconUrl": "https:\/\/cloud.nextcloud.com\/avatar\/julia\/44",
					"sinceId": "1665133614"
				},
```

@eneiluj  as you developed it.

### Steps to reproduce

1. query endpoint
2. see duplicate

### Expected behavior

only real user

### Installation method

_No response_

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database engine version

_No response_

### Is this bug present after an update or on a fresh install?

_No response_

### Are you using the Nextcloud Server Encryption module?

_No response_

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
/
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix #34464 

Maybe it is smarter to do it directly on DB level, but I failed to do so…

### CODE REVIEW

File: apps/user_status/lib/Dashboard/UserStatusWidget.php [hunk 1]
```diff
@@ -152,7 +152,8 @@ private function getWidgetData(string $userId, ?string $since = null, int $limit
 				$this->service->findAllRecentStatusChanges($limit + 1, 0),
 				static function (UserStatus $status) use ($userId, $since): bool {
 					return $status->getUserId() !== $userId
-						&& ($since === null || $status->getStatusTimestamp() > (int) $since);
+						&& ($since === null || $status->getStatusTimestamp() > (int) $since)
+						&& !str_starts_with($status->getUserId(), "_");
```
Comment (nickvergessen) [inline apps/user_status/lib/Dashboard/UserStatusWidget.php:156]:
```suggestion
						&& !str_starts_with($status->getUserId(), '_');
```

File: apps/user_status/lib/Dashboard/UserStatusWidget.php [hunk 2]
```diff
@@ -152,7 +152,8 @@ private function getWidgetData(string $userId, ?string $since = null, int $limit
 				$this->service->findAllRecentStatusChanges($limit + 1, 0),
```
Comment (nickvergessen) [inline apps/user_status/lib/Dashboard/UserStatusWidget.php:152]: Will never be an issue on page one, as everyone with a backup status should have a newer other status, but in theory page 2 could be empty because of this, as you first get a set of statuses and then filter out some.

**Review by nickvergessen — APPROVED** [review]

**Review by CarlSchwan — APPROVED** [review]

**Review by CarlSchwan — CHANGES_REQUESTED** [review]
Actually doing that on the db status is a better idea. Can i push yo your branch?

**Comment by tobiasKaminsky** [comment]
> Actually doing that on the db status is a better idea. Can i push yo your branch?

Sure! I just was not able to do it, knowledge wise.
Else I would also have done it, as it is the cleaner way and also has not drawbacks as Joas mentioned.

**Review by YasinAshorian — APPROVED** [review]

**Comment by julien-nc** [comment]
@CarlSchwan I hope you don't mind me pushing here. I just fixed your typo leading to a syntax error.

**Review by julien-nc — APPROVED** [review]

**Comment by tobiasKaminsky** [comment]
> "message": "Internal Server Error\nAn exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column '_%' in 'where clause'"

File: apps/user_status/lib/Db/UserStatusMapper.php [hunk 3]
```diff
@@ -76,10 +76,15 @@ public function findAllRecent(?int $limit = null, ?int $offset = null): array {
...
-			->orWhere($qb->expr()->isNotNull('custom_icon'))
-			->orWhere($qb->expr()->isNotNull('custom_message'));
+			->where($qb->expr()->andX(
+				$qb->expr()->orX(
+					$qb->expr()->notIn('status', $qb->createNamedParameter([IUserStatus::ONLINE, IUserStatus::AWAY, IUserStatus::OFFLINE], IQueryBuilder::PARAM_STR_ARRAY)),
+					$qb->expr()->isNotNull('message_id'),
+					$qb->expr()->isNotNull('custom_icon'),
+					$qb->expr()->isNotNull('custom_message'),
+				),
+				$qb->expr()->notLike('user_id', '_%')
```
Comment (PVince81) [inline apps/user_status/lib/Db/UserStatusMapper.php:86]: need to use the escaping function for LIKE @julien-nc

**Review by nickvergessen — CHANGES_REQUESTED** [review]

**Comment by tobiasKaminsky** [comment]
This works now!  Thanks Joas!

**Review by nickvergessen — APPROVED** [review]
