### PR TITLE
Ensure that we don't merge broken json.

### LINKED ISSUE #18277: A new kind of failure when upgrading to 17 from 16, NULL page loads where Start Update should.
The https://help.nextcloud.com site won't let me login.
And I can't get to this page https://apps.nextcloud.com/apps/issuetemplate because the installation failed. I may have overused the Details tag. :-) 

### Steps to reproduce
1. Use the webpage based version upgrade to go from the latest Production channel of 16 to the latest regular channel of 17.0.1.
2. Click the button to leave maintenance mode and go back to the site to finish the installation.
3. Nothing happens. The site doesn't load, the page is a white screen, the view source option shows NULL content.

### Expected behavior
1. Use the webpage based version upgrade to go from the latest Production channel of 16 to the latest regular channel of 17.0.1.
2. Click the button to leave maintenance mode and go back to the site to finish the installation.
3. A bunch of things happen to update things and eventually, it's done.

### Actual behavior
1. Use the webpage based version upgrade to go from the latest Production channel of 16 to the latest regular channel of 17.0.1.
2. Click the button to leave maintenance mode and go back to the site to finish the installation.
3. Nothing happens. The site doesn't load, the page is a white screen, the view source option shows NULL content.

### Here's the Basic Info you need to know

<details>
<summary>Machine and Software State Information That You Want To Know About</summary>

### Server configuration

**Operating system:** Ubuntu Linux 18.04.1

**Web server:** Apache 2.4.41

**Database:** MySQL 5.7.28

**PHP version:** 7.3.12

**Nextcloud version:** It won't load, but probably 17.0.1 right now, or almost there.

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Nextcloud

**Signing status:** HA! Nope, can't sign in.

**List of activated apps:**
<details>
<summary>App list</summary>

```
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - admin_audit: 1.7.0
  - announcementcenter: 3.6.1
  - apporder: 0.8.0
  - audioplayer: 2.8.4
  - bookmarks: 2.3.1
  - bruteforcesettings: 1.4.0
  - calendar: 1.7.1
  - camerarawpreviews: 0.7.2
  - carnet: 0.18.11
  - checksum: 0.4.3
  - circles: 0.17.10
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.1.6
  - cookbook: 0.5.5
  - cospend: 0.1.5
  - dashboardcharts: 0.1.3
  - data_request: 1.4.0
  - dav: 1.13.0
  - event_update_notification: 1.0.0
  - extract: 1.2.2
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_accesscontrol: 1.7.0
  - files_downloadactivity: 1.6.0
  - files_markdown: 2.1.0
  - files_mindmap: 0.0.15
  - files_pdfviewer: 1.6.0
  - files_photospheres: 1.0.6
  - files_readmemd: 1.1.3
  - files_retention: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - flowupload: 0.1.7
  - gallery: 18.4.0
  - gpxedit: 0.0.12
  - gpxmotion: 0.0.10
  - gpxpod: 4.1.0
  - groupfolders: 5.0.4
  - guests: 1.3.1
  - impersonate: 1.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - mail: 0.20.0
  - maps: 0.1.2
  - metadata: 0.10.0
  - music: 0.11.1
  - news: 14.0.2
  - nextcloud_announcements: 1.6.0
  - notes: 3.0.3
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - ocsms: 2.1.6
  - password_policy: 1.7.0
  - passwords: 2019.12.0
  - phonetrack: 0.5.11
  - polls: 0.10.4
  - previewgenerator: 2.2.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - quota_warning: 1.6.0
  - rainloop: 6.0.4
  - ransomware_detection: 0.6.0
  - ransomware_protection: 1.5.1
  - recommendations: 0.5.0
  - registration: 0.4.7
  - richdocuments: 3.4.6
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - sharerenamer: 2.7.2
  - sharingpath: 0.1.0
  - social: 0.2.101
  - socialsharing_diaspora: 1.0.5
  - socialsharing_email: 1.0.6
  - socialsharing_facebook: 1.0.5
  - socialsharing_twitter: 1.0.5
  - spreed: 7.0.2
  - support: 1.0.1
  - survey_client: 1.5.0
  - suspicious_login: 3.0.0
  - systemtags: 1.7.0
  - talk_simple_poll: 1.0.0
  - tasks: 0.11.3
  - terms_of_service: 1.3.1
  - text: 1.1.1
  - theming: 1.8.0
  - theming_customcss: 1.4.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - video_converter: 0.1.2
  - viewer: 1.2.0
  - weather: 1.6.4
  - workflowengine: 1.7.0
Disabled:
  - dicomviewer
  - drawio
  - drop_account
  - encryption
  - files_antivirus
  - files_ebookreader
  - files_external
  - forms
  - radio
  - telephoneprovider
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
{
    "system": {
        "config_is_read_only": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.ruppssites.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.6.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "",
        "loglevel": 0,
        "default_language": "en",
        "enable_previews": true,
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "preview_max_scale_factor": 10,
        "preview_max_filesize_image": 50,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore --convert-to pdf --outdir ",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\Font",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\StarOffice"
        ],
        "tempdirectory": "\/home\/support\/domains\/cloud.ruppssites.com\/tmp\/nextcloudtemp",
        "overwrite.cli.url": "https:\/\/cloud.ruppssites.com\/",
        "updater.release.channel": "stable",
        "has_rebuilt_cache": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes for HTTPS, but not end-to-end

### Client configuration
**Browser:** Firefox and Chrome

**Operating system:** Ubuntu 18.04 Workstation

#### Web server error log
<details>
<summary>Web server error log</summary>

```
I checked and it was literally empty of errors related to this virtual server.
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
I took the liberty of deleting all the log data before the activities I did to do an upgrade.

[nextcloud.log](https://github.com/nextcloud/server/files/3934703/nextcloud.log)

</details>
</details>

### Here's the real story! It's the crap I did.

**Notes on what happened after the site wouldn't load to finish the updates/install of upgrade**
I've been through a lot of flawless upgrades over the years and a handful of failures. Each failure is a little different than the last. Because of messages about some apps that didn't have an upgrade candidate for 17, I disabled all the listed apps before trying to upgrade.

This was the first time after the initial upgrade page finished that there was no page to go back to. By that I mean, while in the Admin page for Overview where it tells you if you can upgrade to a new version, you click the button to upgrade and the page that follows goes through a procedure where it backs up files, pulls down new stuff and so on. That concludes with a binary choice depending on whether the user did a web-based installer or not and the decision is about staying in or leaving maintenance mode. I chose to leave maintenance mode (_turn it off_) and then I had nothing. The page that happened next was devoid of any content. No colors, no CSS, no data, no header, nothing at all. Just a white screen. I tried looking at older problems to see how they got solved before but there was trouble with signing into the help site.

#### First post failure actions...
<details>
<summary>I searched on Git for upgrade to 17 problems and thought this would work</summary>
Somebody with a slightly different problem got back to running by executing the `php occ upgrade` command from inside the web-root folder for Nextcloud. This is the content of what transpired in the shell: (it almost worked, see uncaught exceptions near the end)

<pre>$ php occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
<font color="#4E9A06">Set log level to debug</font>
<font color="#4E9A06">Turned on maintenance mode</font>
<font color="#4E9A06">Updating database schema</font>
<font color="#4E9A06">Updated database</font>
<font color="#C4A000">Disabled incompatible app: announcementcenter</font>
<font color="#C4A000">Disabled incompatible app: cospend</font>
<font color="#C4A000">Disabled incompatible app: data_request</font>
<font color="#C4A000">Disabled incompatible app: event_update_notification</font>
<font color="#C4A000">Disabled incompatible app: files_accesscontrol</font>
<font color="#C4A000">Disabled incompatible app: files_downloadactivity</font>
<font color="#C4A000">Disabled incompatible app: files_photospheres</font>
<font color="#C4A000">Disabled incompatible app: files_retention</font>
<font color="#C4A000">Disabled incompatible app: groupfolders</font>
<font color="#C4A000">Disabled incompatible app: impersonate</font>
<font color="#C4A000">Disabled incompatible app: quota_warning</font>
<font color="#C4A000">Disabled incompatible app: ransomware_detection</font>
<font color="#C4A000">Disabled incompatible app: ransomware_protection</font>
<font color="#C4A000">Disabled incompatible app: spreed</font>
<font color="#C4A000">Disabled incompatible app: terms_of_service</font>
<font color="#4E9A06">Updating &lt;accessibility&gt; ...</font>
<font color="#4E9A06">Updated &lt;accessibility&gt; to 1.3.0</font>
<font color="#4E9A06">Updating &lt;federatedfilesharing&gt; ...</font>
<font color="#4E9A06">Updated &lt;federatedfilesharing&gt; to 1.7.0</font>
<font color="#4E9A06">Updating &lt;files_pdfviewer&gt; ...</font>
<font color="#4E9A06">Updated &lt;files_pdfviewer&gt; to 1.6.0</font>
<font color="#4E9A06">Updating &lt;files_rightclick&gt; ...</font>
<font color="#4E9A06">Updated &lt;files_rightclick&gt; to 0.14.2</font>
<font color="#4E9A06">Updating &lt;files_videoplayer&gt; ...</font>
<font color="#4E9A06">Updated &lt;files_videoplayer&gt; to 1.6.0</font>
<font color="#4E9A06">Updating &lt;gallery&gt; ...</font>
<font color="#4E9A06">Updated &lt;gallery&gt; to 18.4.0</font>
<font color="#4E9A06">Updating &lt;logreader&gt; ...</font>
<font color="#4E9A06">Updated &lt;logreader&gt; to 2.2.0</font>
<font color="#4E9A06">Updating &lt;password_policy&gt; ...</font>
<font color="#4E9A06">Updated &lt;password_policy&gt; to 1.7.0</font>
<font color="#4E9A06">Updating &lt;privacy&gt; ...</font>
<font color="#4E9A06">Updated &lt;privacy&gt; to 1.1.0</font>
<font color="#4E9A06">Updating &lt;provisioning_api&gt; ...</font>
<font color="#4E9A06">Updated &lt;provisioning_api&gt; to 1.7.0</font>
<font color="#4E9A06">Updating &lt;recommendations&gt; ...</font>
<font color="#4E9A06">Updated &lt;recommendations&gt; to 0.5.0</font>
<font color="#4E9A06">Updating &lt;serverinfo&gt; ...</font>
<font color="#4E9A06">Updated &lt;serverinfo&gt; to 1.7.0</font>
<font color="#4E9A06">Updating &lt;support&gt; ...</font>
<font color="#4E9A06">Updated &lt;support&gt; to 1.0.1</font>
<font color="#4E9A06">Updating &lt;survey_client&gt; ...</font>
<font color="#4E9A06">Updated &lt;survey_client&gt; to 1.5.0</font>
<font color="#4E9A06">Updating &lt;text&gt; ...</font>
<font color="#4E9A06">Updated &lt;text&gt; to 1.1.1</font>
<font color="#4E9A06">Updating &lt;twofactor_backupcodes&gt; ...</font>
<font color="#4E9A06">Updated &lt;twofactor_backupcodes&gt; to 1.6.0</font>
<font color="#4E9A06">Updating &lt;updatenotification&gt; ...</font>
<font color="#4E9A06">Updated &lt;updatenotification&gt; to 1.7.0</font>
<font color="#4E9A06">Updating &lt;federation&gt; ...</font>
<font color="#4E9A06">Updated &lt;federation&gt; to 1.7.0</font>
<font color="#4E9A06">Updating &lt;lookup_server_connector&gt; ...</font>
<font color="#4E9A06">Updated &lt;lookup_server_connector&gt; to 1.5.0</font>
<font color="#4E9A06">Updating &lt;oauth2&gt; ...</font>
<font color="#4E9A06">Updated &lt;oauth2&gt; to 1.5.0</font>
<font color="#4E9A06">Updating &lt;files&gt; ...</font>
<font color="#4E9A06">Updated &lt;files&gt; to 1.12.0</font>
<font color="#4E9A06">Updating &lt;activity&gt; ...</font>
<font color="#4E9A06">Updated &lt;activity&gt; to 2.10.1</font>
<font color="#4E9A06">Updating &lt;cloud_federation_api&gt; ...</font>
<font color="#4E9A06">Updated &lt;cloud_federation_api&gt; to 1.0.0</font>
<font color="#4E9A06">Updating &lt;dav&gt; ...</font>
Fix broken values of calendar objects

 Done
    0/0 [&gt;---------------------------]   0%
<font color="#4E9A06">Updated &lt;dav&gt; to 1.13.0</font>
<font color="#4E9A06">Updating &lt;files_sharing&gt; ...</font>
<font color="#4E9A06">Updated &lt;files_sharing&gt; to 1.9.0</font>
<font color="#4E9A06">Updating &lt;files_trashbin&gt; ...</font>
<font color="#4E9A06">Updated &lt;files_trashbin&gt; to 1.7.0</font>
<font color="#4E9A06">Updating &lt;files_versions&gt; ...</font>
<font color="#4E9A06">Updated &lt;files_versions&gt; to 1.10.0</font>
<font color="#4E9A06">Updating &lt;sharebymail&gt; ...</font>
<font color="#4E9A06">Updated &lt;sharebymail&gt; to 1.7.0</font>
<font color="#4E9A06">Updating &lt;workflowengine&gt; ...</font>
<font color="#4E9A06">Updated &lt;workflowengine&gt; to 1.7.0</font>
<font color="#4E9A06">Updating &lt;admin_audit&gt; ...</font>
<font color="#4E9A06">Updated &lt;admin_audit&gt; to 1.7.0</font>
<font color="#4E9A06">Updating &lt;comments&gt; ...</font>
<font color="#4E9A06">Updated &lt;comments&gt; to 1.7.0</font>
<font color="#4E9A06">Updating &lt;firstrunwizard&gt; ...</font>
<font color="#4E9A06">Updated &lt;firstrunwizard&gt; to 2.6.0</font>
<font color="#4E9A06">Updating &lt;nextcloud_announcements&gt; ...</font>
<font color="#4E9A06">Updated &lt;nextcloud_announcements&gt; to 1.6.0</font>
<font color="#4E9A06">Updating &lt;notifications&gt; ...</font>
<font color="#4E9A06">Updated &lt;notifications&gt; to 2.5.0</font>
<font color="#4E9A06">Updating &lt;systemtags&gt; ...</font>
<font color="#4E9A06">Updated &lt;systemtags&gt; to 1.7.0</font>
<font color="#4E9A06">Updating &lt;theming&gt; ...</font>
<font color="#4E9A06">Updated &lt;theming&gt; to 1.8.0</font>
<font color="#4E9A06">Checking for update of app accessibility in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;accessibility&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app activity in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;activity&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app admin_audit in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;admin_audit&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app apporder in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;apporder&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app audioplayer in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;audioplayer&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app bookmarks in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;bookmarks&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app bruteforcesettings in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;bruteforcesettings&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app calendar in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;calendar&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app camerarawpreviews in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;camerarawpreviews&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app carnet in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;carnet&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app checksum in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;checksum&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app circles in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;circles&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app cloud_federation_api in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;cloud_federation_api&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app comments in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;comments&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app contacts in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;contacts&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app cookbook in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;cookbook&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app dashboardcharts in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;dashboardcharts&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app dav in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;dav&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app extract in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;extract&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app federatedfilesharing in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;federatedfilesharing&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app federation in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;federation&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app files in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;files&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app files_markdown in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;files_markdown&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app files_mindmap in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;files_mindmap&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app files_pdfviewer in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;files_pdfviewer&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app files_readmemd in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;files_readmemd&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app files_rightclick in appstore</font>
<font color="#4E9A06">Update app files_rightclick from appstore</font>
<font color="#4E9A06">Checked for update of app &quot;files_rightclick&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app files_sharing in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;files_sharing&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app files_trashbin in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;files_trashbin&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app files_versions in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;files_versions&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app files_videoplayer in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;files_videoplayer&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app firstrunwizard in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;firstrunwizard&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app flowupload in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;flowupload&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app gallery in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;gallery&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app gpxedit in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;gpxedit&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app gpxmotion in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;gpxmotion&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app gpxpod in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;gpxpod&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app guests in appstore</font>
<font color="#4E9A06">Update app guests from appstore</font>
<font color="#4E9A06">Checked for update of app &quot;guests&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app logreader in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;logreader&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app lookup_server_connector in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;lookup_server_connector&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app mail in appstore</font>
<font color="#4E9A06">Update app mail from appstore</font>
Purify and migrate collected mail addresses
 Done
 2/2 [============================] 100%
<font color="#4E9A06">Checked for update of app &quot;mail&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app maps in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;maps&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app metadata in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;metadata&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app music in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;music&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app news in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;news&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app nextcloud_announcements in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;nextcloud_announcements&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app notes in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;notes&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app notifications in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;notifications&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app oauth2 in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;oauth2&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app ocsms in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;ocsms&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app password_policy in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;password_policy&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app passwords in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;passwords&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app phonetrack in appstore</font>
<font color="#4E9A06">Update app phonetrack from appstore</font>
<font color="#4E9A06">Checked for update of app &quot;phonetrack&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app polls in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;polls&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app previewgenerator in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;previewgenerator&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app privacy in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;privacy&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app provisioning_api in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;provisioning_api&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app rainloop in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;rainloop&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app recommendations in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;recommendations&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app registration in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;registration&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app richdocuments in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;richdocuments&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app serverinfo in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;serverinfo&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app sharebymail in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;sharebymail&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app sharerenamer in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;sharerenamer&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app sharingpath in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;sharingpath&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app social in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;social&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app socialsharing_diaspora in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;socialsharing_diaspora&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app socialsharing_email in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;socialsharing_email&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app socialsharing_facebook in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;socialsharing_facebook&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app socialsharing_twitter in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;socialsharing_twitter&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app support in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;support&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app survey_client in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;survey_client&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app systemtags in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;systemtags&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app talk_simple_poll in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;talk_simple_poll&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app tasks in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;tasks&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app text in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;text&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app theming in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;theming&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app theming_customcss in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;theming_customcss&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app twofactor_backupcodes in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;twofactor_backupcodes&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app updatenotification in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;updatenotification&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app video_converter in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;video_converter&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app viewer in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;viewer&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app weather in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;weather&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app workflowengine in appstore</font>
<font color="#4E9A06">Checked for update of app &quot;workflowengine&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app announcementcenter in appstore</font>
<font color="#4E9A06">Update app announcementcenter from appstore</font>
Add read permissions for existing announcements
 Done
    0/0 [&gt;---------------------------]   0%
<font color="#4E9A06">Checked for update of app &quot;announcementcenter&quot; in appstore </font>
Add read permissions for existing announcements
 Done
    0/0 [&gt;---------------------------]   0%
<font color="#4E9A06">Checking for update of app cospend in appstore</font>
<font color="#4E9A06">Update app cospend from appstore</font>
<font color="#4E9A06">Checked for update of app &quot;cospend&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app data_request in appstore</font>
<font color="#4E9A06">Update app data_request from appstore</font>
<font color="#4E9A06">Checked for update of app &quot;data_request&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app event_update_notification in appstore</font>
<font color="#4E9A06">Update app event_update_notification from appstore</font>
<font color="#4E9A06">Checked for update of app &quot;event_update_notification&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app files_accesscontrol in appstore</font>
<font color="#4E9A06">Update app files_accesscontrol from appstore</font>
<font color="#4E9A06">Checked for update of app &quot;files_accesscontrol&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app files_downloadactivity in appstore</font>
<font color="#4E9A06">Update app files_downloadactivity from appstore</font>
<font color="#4E9A06">Checked for update of app &quot;files_downloadactivity&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app files_photospheres in appstore</font>
<font color="#4E9A06">Update app files_photospheres from appstore</font>
<font color="#4E9A06">Checked for update of app &quot;files_photospheres&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app files_retention in appstore</font>
<font color="#4E9A06">Update app files_retention from appstore</font>
<font color="#4E9A06">Checked for update of app &quot;files_retention&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app groupfolders in appstore</font>
<font color="#4E9A06">Update app groupfolders from appstore</font>
<font color="#4E9A06">Checked for update of app &quot;groupfolders&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app impersonate in appstore</font>
<font color="#4E9A06">Update app impersonate from appstore</font>
<font color="#4E9A06">Checked for update of app &quot;impersonate&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app quota_warning in appstore</font>
<font color="#4E9A06">Update app quota_warning from appstore</font>
<font color="#4E9A06">Checked for update of app &quot;quota_warning&quot; in appstore </font>
Add background jobs for existing users
 Done
    5/5 [============================] 100%
<font color="#4E9A06">Checking for update of app ransomware_detection in appstore</font>
<font color="#4E9A06">Update app ransomware_detection from appstore</font>
<font color="#4E9A06">Checked for update of app &quot;ransomware_detection&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app ransomware_protection in appstore</font>
<font color="#4E9A06">Update app ransomware_protection from appstore</font>
<font color="#4E9A06">Checked for update of app &quot;ransomware_protection&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app spreed in appstore</font>
<font color="#4E9A06">Update app spreed from appstore</font>
<font color="#4E9A06">Checked for update of app &quot;spreed&quot; in appstore </font>
<font color="#4E9A06">Checking for update of app terms_of_service in appstore</font>
<font color="#4E9A06">Update app terms_of_service from appstore</font>
<font color="#4E9A06">Checked for update of app &quot;terms_of_service&quot; in appstore </font>
Create notifications for users that already logged in
 Done
    5/5 [============================] 100%
<font color="#4E9A06">Checking for update of app suspicious_login in appstore</font>
<font color="#4E9A06">Update app suspicious_login from appstore</font>
<font color="#4E9A06">Checked for update of app &quot;suspicious_login&quot; in appstore </font>
An unhandled exception has been thrown:
TypeError: Argument 1 passed to OC\Core\Command\Maintenance\Mimetype\GenerateMimetypeFileBuilder::generateFile() must be of the type array, null given, called in /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/IntegrityCheck/Checker.php on line 205 and defined in /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/core/Command/Maintenance/Mimetype/GenerateMimetypeFileBuilder.php:33
Stack trace:
#0 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/IntegrityCheck/Checker.php(205): OC\Core\Command\Maintenance\Mimetype\GenerateMimetypeFileBuilder-&gt;generateFile(NULL)
#1 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/IntegrityCheck/Checker.php(374): OC\IntegrityCheck\Checker-&gt;generateHashes(Object(RecursiveIteratorIterator), &apos;/home/support/d...&apos;)
#2 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/IntegrityCheck/Checker.php(554): OC\IntegrityCheck\Checker-&gt;verify(&apos;/home/support/d...&apos;, &apos;/home/support/d...&apos;, &apos;core&apos;)
#3 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/IntegrityCheck/Checker.php(575): OC\IntegrityCheck\Checker-&gt;verifyCoreSignature()
#4 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/Repair/NC16/RemoveCypressFiles.php(80): OC\IntegrityCheck\Checker-&gt;runInstanceVerification()
#5 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/Repair.php(101): OC\Repair\NC16\RemoveCypressFiles-&gt;run(Object(OC\Repair))
#6 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/Updater.php(273): OC\Repair-&gt;run()
#7 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/Updater.php(128): OC\Updater-&gt;doUpgrade(&apos;17.0.1.1&apos;, &apos;16.0.6.1&apos;)
#8 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/core/Command/Upgrade.php(258): OC\Updater-&gt;upgrade()
#9 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade-&gt;execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/3rdparty/symfony/console/Application.php(908): Symfony\Component\Console\Command\Command-&gt;run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/3rdparty/symfony/console/Application.php(269): Symfony\Component\Console\Application-&gt;doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/3rdparty/symfony/console/Application.php(145): Symfony\Component\Console\Application-&gt;doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application-&gt;run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/console.php(97): OC\Console\Application-&gt;run()
#15 /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/occ(11): require_once(&apos;/home/support/d...&apos;)</pre>

</details>

All that got me to here...

Screenshot from 2019-12-06 23-15-46

...so I did this `php occ maintenance:mode --off` which got me to here...

Screenshot from 2019-12-06 23-18-51

And I assume clicking that **[ Start update ]** button is the same as `php occ upgrade`.

#### Here's what goes on with **Start update** in the browser
<details>
<summary>CLICK</summary>

Screenshot from 2019-12-06 23-23-18

**Detailed logs**
```
Preparing update

Set log level to debug

Turned on maintenance mode

Repair step: Repair MySQL collation

Repair info: All tables already have the correct collation -> nothing to do

Repair step: Repair SQLite autoincrement

Repair step: Copy data from accounts table when migrating from ownCloud

Repair step: Drop account terms table when migrating from ownCloud

Updating database schema

Updated database

Checking for update of app "accessibility" in appstore

Checked for update of app "accessibility" in appstore

Checking for update of app "activity" in appstore

Checked for update of app "activity" in appstore

Checking for update of app "admin_audit" in appstore

Checked for update of app "admin_audit" in appstore

Checking for update of app "announcementcenter" in appstore

Checked for update of app "announcementcenter" in appstore

Checking for update of app "apporder" in appstore

Checked for update of app "apporder" in appstore

Checking for update of app "audioplayer" in appstore

Checked for update of app "audioplayer" in appstore

Checking for update of app "bookmarks" in appstore

Checked for update of app "bookmarks" in appstore

Checking for update of app "bruteforcesettings" in appstore

Checked for update of app "bruteforcesettings" in appstore

Checking for update of app "calendar" in appstore

Checked for update of app "calendar" in appstore

Checking for update of app "camerarawpreviews" in appstore

Checked for update of app "camerarawpreviews" in appstore

Checking for update of app "carnet" in appstore

Checked for update of app "carnet" in appstore

Checking for update of app "checksum" in appstore

Checked for update of app "checksum" in appstore

Checking for update of app "circles" in appstore

Checked for update of app "circles" in appstore

Checking for update of app "cloud_federation_api" in appstore

Checked for update of app "cloud_federation_api" in appstore

Checking for update of app "comments" in appstore

Checked for update of app "comments" in appstore

Checking for update of app "contacts" in appstore

Checked for update of app "contacts" in appstore

Checking for update of app "cookbook" in appstore

Checked for update of app "cookbook" in appstore

Checking for update of app "cospend" in appstore

Checked for update of app "cospend" in appstore

Checking for update of app "dashboardcharts" in appstore

Checked for update of app "dashboardcharts" in appstore

Checking for update of app "data_request" in appstore

Checked for update of app "data_request" in appstore

Checking for update of app "dav" in appstore

Checked for update of app "dav" in appstore

Checking for update of app "event_update_notification" in appstore

Checked for update of app "event_update_notification" in appstore

Checking for update of app "extract" in appstore

Checked for update of app "extract" in appstore

Checking for update of app "federatedfilesharing" in appstore

Checked for update of app "federatedfilesharing" in appstore

Checking for update of app "federation" in appstore

Checked for update of app "federation" in appstore

Checking for update of app "files" in appstore

Checked for update of app "files" in appstore

Checking for update of app "files_accesscontrol" in appstore

Checked for update of app "files_accesscontrol" in appstore

Checking for update of app "files_downloadactivity" in appstore

Checked for update of app "files_downloadactivity" in appstore

Checking for update of app "files_markdown" in appstore

Checked for update of app "files_markdown" in appstore

Checking for update of app "files_mindmap" in appstore

Checked for update of app "files_mindmap" in appstore

Checking for update of app "files_pdfviewer" in appstore

Checked for update of app "files_pdfviewer" in appstore

Checking for update of app "files_photospheres" in appstore

Checked for update of app "files_photospheres" in appstore

Checking for update of app "files_readmemd" in appstore

Checked for update of app "files_readmemd" in appstore

Checking for update of app "files_retention" in appstore

Checked for update of app "files_retention" in appstore

Checking for update of app "files_rightclick" in appstore

Checked for update of app "files_rightclick" in appstore

Checking for update of app "files_sharing" in appstore

Checked for update of app "files_sharing" in appstore

Checking for update of app "files_trashbin" in appstore

Checked for update of app "files_trashbin" in appstore

Checking for update of app "files_versions" in appstore

Checked for update of app "files_versions" in appstore

Checking for update of app "files_videoplayer" in appstore

Checked for update of app "files_videoplayer" in appstore

Checking for update of app "firstrunwizard" in appstore

Checked for update of app "firstrunwizard" in appstore

Checking for update of app "flowupload" in appstore

Checked for update of app "flowupload" in appstore

Checking for update of app "gallery" in appstore

Checked for update of app "gallery" in appstore

Checking for update of app "gpxedit" in appstore

Checked for update of app "gpxedit" in appstore

Checking for update of app "gpxmotion" in appstore

Checked for update of app "gpxmotion" in appstore

Checking for update of app "gpxpod" in appstore

Checked for update of app "gpxpod" in appstore

Checking for update of app "groupfolders" in appstore

Checked for update of app "groupfolders" in appstore

Checking for update of app "guests" in appstore

Checked for update of app "guests" in appstore

Checking for update of app "impersonate" in appstore

Checked for update of app "impersonate" in appstore

Checking for update of app "logreader" in appstore

Checked for update of app "logreader" in appstore

Checking for update of app "lookup_server_connector" in appstore

Checked for update of app "lookup_server_connector" in appstore

Checking for update of app "mail" in appstore

Checked for update of app "mail" in appstore

Checking for update of app "maps" in appstore

Checked for update of app "maps" in appstore

Checking for update of app "metadata" in appstore

Checked for update of app "metadata" in appstore

Checking for update of app "music" in appstore

Checked for update of app "music" in appstore

Checking for update of app "news" in appstore

Checked for update of app "news" in appstore

Checking for update of app "nextcloud_announcements" in appstore

Checked for update of app "nextcloud_announcements" in appstore

Checking for update of app "notes" in appstore

Checked for update of app "notes" in appstore

Checking for update of app "notifications" in appstore

Checked for update of app "notifications" in appstore

Checking for update of app "oauth2" in appstore

Checked for update of app "oauth2" in appstore

Checking for update of app "ocsms" in appstore

Checked for update of app "ocsms" in appstore

Checking for update of app "password_policy" in appstore

Checked for update of app "password_policy" in appstore

Checking for update of app "passwords" in appstore

Checked for update of app "passwords" in appstore

Checking for update of app "phonetrack" in appstore

Checked for update of app "phonetrack" in appstore

Checking for update of app "polls" in appstore

Checked for update of app "polls" in appstore

Checking for update of app "previewgenerator" in appstore

Checked for update of app "previewgenerator" in appstore

Checking for update of app "privacy" in appstore

Checked for update of app "privacy" in appstore

Checking for update of app "provisioning_api" in appstore

Checked for update of app "provisioning_api" in appstore

Checking for update of app "quota_warning" in appstore

Checked for update of app "quota_warning" in appstore

Checking for update of app "rainloop" in appstore

Checked for update of app "rainloop" in appstore

Checking for update of app "ransomware_detection" in appstore

Checked for update of app "ransomware_detection" in appstore

Checking for update of app "ransomware_protection" in appstore

Checked for update of app "ransomware_protection" in appstore

Checking for update of app "recommendations" in appstore

Checked for update of app "recommendations" in appstore

Checking for update of app "registration" in appstore

Checked for update of app "registration" in appstore

Checking for update of app "richdocuments" in appstore

Checked for update of app "richdocuments" in appstore

Checking for update of app "serverinfo" in appstore

Checked for update of app "serverinfo" in appstore

Checking for update of app "sharebymail" in appstore

Checked for update of app "sharebymail" in appstore

Checking for update of app "sharerenamer" in appstore

Checked for update of app "sharerenamer" in appstore

Checking for update of app "sharingpath" in appstore

Checked for update of app "sharingpath" in appstore

Checking for update of app "social" in appstore

Checked for update of app "social" in appstore

Checking for update of app "socialsharing_diaspora" in appstore

Checked for update of app "socialsharing_diaspora" in appstore

Checking for update of app "socialsharing_email" in appstore

Checked for update of app "socialsharing_email" in appstore

Checking for update of app "socialsharing_facebook" in appstore

Checked for update of app "socialsharing_facebook" in appstore

Checking for update of app "socialsharing_twitter" in appstore

Checked for update of app "socialsharing_twitter" in appstore

Checking for update of app "spreed" in appstore

Checked for update of app "spreed" in appstore

Checking for update of app "support" in appstore

Checked for update of app "support" in appstore

Checking for update of app "survey_client" in appstore

Checked for update of app "survey_client" in appstore

Checking for update of app "suspicious_login" in appstore

Checked for update of app "suspicious_login" in appstore

Checking for update of app "systemtags" in appstore

Checked for update of app "systemtags" in appstore

Checking for update of app "talk_simple_poll" in appstore

Checked for update of app "talk_simple_poll" in appstore

Checking for update of app "tasks" in appstore

Checked for update of app "tasks" in appstore

Checking for update of app "terms_of_service" in appstore

Checked for update of app "terms_of_service" in appstore

Checking for update of app "text" in appstore

Checked for update of app "text" in appstore

Checking for update of app "theming" in appstore

Checked for update of app "theming" in appstore

Checking for update of app "theming_customcss" in appstore

Checked for update of app "theming_customcss" in appstore

Checking for update of app "twofactor_backupcodes" in appstore

Checked for update of app "twofactor_backupcodes" in appstore

Checking for update of app "updatenotification" in appstore

Checked for update of app "updatenotification" in appstore

Checking for update of app "video_converter" in appstore

Checked for update of app "video_converter" in appstore

Checking for update of app "viewer" in appstore

Checked for update of app "viewer" in appstore

Checking for update of app "weather" in appstore

Checked for update of app "weather" in appstore

Checking for update of app "workflowengine" in appstore

Checked for update of app "workflowengine" in appstore

Repair step: Repair MySQL collation

Repair info: All tables already have the correct collation -> nothing to do

Repair step: Repair mime types

Repair step: Clean tags and favorites

Repair info: 0 tags of deleted users have been removed.

Repair info: 0 tags for delete files have been removed.

Repair info: 0 tag entries for deleted tags have been removed.

Repair info: 0 tags with no entries have been removed.

Repair step: Repair invalid shares

Repair step: Move .step file of updater to backup location

Repair step: Fix potential broken mount points

Repair info: No mounts updated

Repair step: Add log rotate job

Repair step: Clear frontend caches

Repair info: Image cache cleared

Repair info: SCSS cache cleared

Repair info: JS cache cleared

Repair step: Clear every generated avatar on major updates

Repair step: Add preview background cleanup job

Repair step: Queue a one-time job to cleanup old backups of the updater

Repair step: Cleanup invalid photocache files for carddav

Repair step: Add background job to cleanup login flow v2 tokens

Repair step: Remove potentially over exposing share links

Repair info: No need to remove link shares.

Repair step: Clear access cache of projects

Repair step: Cleanup cypress files from viewer app

An error occurred.
```
And reloading the page shows I'm back in Maintenance Mode.
</details>

So right now I'm lost. I don't know how to read error messages properly.

### PR DESCRIPTION
**Pull request by kesselb**
Fix #18277 

How to test? Create `config/mimetypemapping.json` with:

```
{
	"kdbx": ["application/x-kdbx],
}
```

https://3v4l.org/N3hms `array_merge([], null);` will be null.

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
Wow nice!!

File: lib/private/Files/Type/Detection.php [hunk 1]
```diff
@@ -45,6 +46,10 @@
  * @package OC\Files\Type
  */
 class Detection implements IMimeTypeDetector {
+
+	public const CUSTOM_MIMETYPEMAPPING = 'mimetypemapping.json';
```
Comment (ChristophWurst) [inline lib/private/Files/Type/Detection.php]:
```suggestion
	private const CUSTOM_MIMETYPEMAPPING = 'mimetypemapping.json';
```

File: lib/private/Files/Type/Detection.php [hunk 2]
```diff
@@ -45,6 +46,10 @@
...
+	public const CUSTOM_MIMETYPEALIASES = 'mimetypealiases.json';
```
Comment (ChristophWurst) [inline lib/private/Files/Type/Detection.php]:
```suggestion
	private const CUSTOM_MIMETYPEALIASES = 'mimetypealiases.json';
```

File: lib/private/Files/Type/Detection.php [hunk 3]
```diff
@@ -110,6 +121,17 @@ public function registerTypeArray($types) {
 		}
 	}
 
+	private function loadCustomDefinitions(string $fileName, array &$definitions): void {
```
Comment (ChristophWurst) [inline lib/private/Files/Type/Detection.php]: nitpick: personally not so much a fan of call by ref. in this case the new could be returned, right?

File: tests/lib/Files/Type/DetectionTest.php [hunk 4]
```diff
@@ -114,13 +116,17 @@ public function testMimeTypeIcon() {
 			->disableOriginalConstructor()
 			->getMock();
 
+		$logger = $this->getMockBuilder(ILogger::class)
+			->disableOriginalConstructor()
+			->getMock();
```
Comment (nickvergessen) [inline tests/lib/Files/Type/DetectionTest.php]:
```suggestion
		$logger = $this->createMock(ILogger::class);
```

File: lib/private/Files/Type/Detection.php (hunk 3 above)
Comment (nickvergessen) [reply lib/private/Files/Type/Detection.php]: yws

**Comment by kesselb** [comment]
Done @nickvergessen @ChristophWurst

**Review by ChristophWurst — APPROVED** [review]
