### PR TITLE
Translate 'Busy' in CalDAV

### LINKED ISSUE #18782: "busy" event is not translated in public access
### Steps to reproduce
1. Create an event with option "when shared show only busy"
2. Share the calendar (tick public access)
3. go to to the shared link of the public calendar with a no english web browser 

### Expected behaviour
If your web browser is for example in french (but in a language other than English, it's the same problem), the event should display "occupé" (busy in french)

### Actual behaviour
If your web browser is in french (but in a language other than english, it's the same problem), the event displays "busy" and not the translation of "Busy" (it's OK only in english)

The word "busy" seems to be translated in transifax but not used in code ?

### Calendar app
**Calendar app version:** 1.7.1

### Client configuration
**Browser:**  Firefox 72.0.1 64 bits

**Operating system:** Windows 10

### Server configuration

**Operating system**: CentOS 7.7.1908

**Web server:** Apache 2.4.6

**Database:** MariaDB 5.5.64

**PHP version:** 7.2.23

**Nextcloud Version:**17.0.2

**Updated from an older installed version or fresh install:** Updated from an older installed

ncc_busy_no_translation

### PR DESCRIPTION
**Pull request by gary-kim**
Fixes #18782 

Thank you for your help @kesselb!
First time touching the DAV code
EDIT: Should we backport this?

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> First time touching the DAV code

welcome :)

File: apps/dav/lib/CalDAV/Calendar.php [hunk 1]
```diff
@@ -68,6 +71,7 @@ public function __construct(BackendInterface $caldavBackend, $calendarInfo, IL10
 		}
 
 		$this->config = $config;
+		$this->l = $l10n;
```
Comment (ChristophWurst) [inline apps/dav/lib/CalDAV/Calendar.php]: nit: we typically call this member `l10n`

Comment (gary-kim) [reply apps/dav/lib/CalDAV/Calendar.php]: Changed!

File: apps/dav/lib/CalDAV/CalendarObject.php [hunk 2]
```diff
@@ -25,26 +25,34 @@
...
 	/**
 	 * CalendarObject constructor.
 	 *
 	 * @param CalDavBackend $caldavBackend
+	 * @param IL10N $l
 	 * @param array $calendarInfo
 	 * @param array $objectData
 	 */
-	public function __construct(CalDavBackend $caldavBackend, array $calendarInfo,
+	public function __construct(CalDavBackend $caldavBackend, IL10N $l,
```
Comment (tcitworld) [inline apps/dav/lib/CalDAV/CalendarObject.php]: Argument name should be `$l10n` as well. :)

**Review by tcitworld — COMMENTED** [review]
You may assert in `apps/dav/tests/unit/CalDAV/CalendarTest.php` that `$this->l10n->t('Busy')` is being called.

File: apps/dav/tests/unit/CalDAV/CalendarTest.php [hunk 3]
```diff
@@ -419,7 +419,7 @@ public function testConfidentialClassification($expectedChildren, $isShared) {
 		$this->assertEquals($end, $event->VEVENT->DTEND->getValue());
 
 		if ($isShared) {
-			$this->assertEquals('Busy', $event->VEVENT->SUMMARY->getValue());
+			$this->assertEquals($this->l10n->t('Busy'), $event->VEVENT->SUMMARY->getValue());
```
Comment (kesselb) [inline apps/dav/tests/unit/CalDAV/CalendarTest.php]: Hmm. What are you trying to do? ;)

Comment (tcitworld) [reply apps/dav/tests/unit/CalDAV/CalendarTest.php]: Probably what I said in https://github.com/nextcloud/server/pull/18788#pullrequestreview-341687219

Comment (kesselb) [reply apps/dav/tests/unit/CalDAV/CalendarTest.php]: Looks weird ;)

Comment (gary-kim) [reply apps/dav/tests/unit/CalDAV/CalendarTest.php]: Yeah, I don't think I did it properly. I think I did it properly now but gonna wait for the CI to finish.

Comment (gary-kim) [reply apps/dav/tests/unit/CalDAV/CalendarTest.php]: Okay, tests fixed.

File: apps/dav/tests/unit/CalDAV/CalendarTest.php [hunk 4]
```diff
@@ -427,6 +427,19 @@ public function testConfidentialClassification($expectedChildren, $isShared) {
 		} else {
 			$this->assertEquals('Test Event', $event->VEVENT->SUMMARY->getValue());
 		}
+
+		// Test l10n
+		$l10n = \OC::$server->getL10NFactory()->get('dav', 'de');
```
Comment (ChristophWurst) [inline apps/dav/tests/unit/CalDAV/CalendarTest.php]: nit: we don't have a good separation of unit and integration tests but I would argue that you should use a mock here

**Review by ChristophWurst — APPROVED** [review]
Looks good otherwise!

File: apps/dav/tests/unit/CalDAV/CalendarTest.php (hunk 4 above)
Comment (gary-kim) [reply apps/dav/tests/unit/CalDAV/CalendarTest.php]: Done!

File: apps/dav/tests/unit/CalDAV/CalendarTest.php [hunk 5]
```diff
@@ -427,6 +429,20 @@ public function testConfidentialClassification($expectedChildren, $isShared) {
 		} else {
 			$this->assertEquals('Test Event', $event->VEVENT->SUMMARY->getValue());
 		}
+
+		// Test l10n
+		$l10n = $this->getMockBuilder(IL10N::class)
```
Comment (tcitworld) [inline apps/dav/tests/unit/CalDAV/CalendarTest.php]: You also need to assert `$l10n->t` is called with the correct parameter.

**Comment by gary-kim** [comment]
Okay, I'm struggling here, I'm not sure how to get a mock of `IL10N` that is configured with a language.

File: apps/dav/tests/unit/CalDAV/CalendarTest.php [hunk 6]
```diff
@@ -427,6 +429,25 @@ public function testConfidentialClassification($expectedChildren, $isShared) {
 		} else {
 			$this->assertEquals('Test Event', $event->VEVENT->SUMMARY->getValue());
 		}
+
+		// Test l10n
+		$l10n = $this->createMock(IL10N::class);
+		$l10n->expects($this->any())
+			->method('t')
+			->with('Busy')
+			->will($this->returnCallback(function ($text, $parameters = array()) {
```
Comment (kesselb) [inline apps/dav/tests/unit/CalDAV/CalendarTest.php]:
```suggestion
			->willReturnCallback(function ($text, $parameters = array()) {
```

File: apps/dav/tests/unit/CalDAV/CalendarTest.php [hunk 7]
```diff
@@ -427,6 +429,25 @@ public function testConfidentialClassification($expectedChildren, $isShared) {
...
+				return vsprintf($text, $parameters);
+			}));
```
Comment (kesselb) [inline apps/dav/tests/unit/CalDAV/CalendarTest.php]:
```suggestion
			});
```

File: apps/dav/tests/unit/CalDAV/CalendarTest.php [hunk 8]
```diff
@@ -427,6 +429,25 @@ public function testConfidentialClassification($expectedChildren, $isShared) {
...
+		$c = new Calendar($backend, $calendarInfo, $l10n, $this->config);
+
+		$calData = $c->getChild('event-1')->get();
+		$event = Reader::read($calData);
+
+		if ($isShared) {
+			$this->assertEquals($l10n->t('Busy'), $event->VEVENT->SUMMARY->getValue());
```
Comment (kesselb) [inline apps/dav/tests/unit/CalDAV/CalendarTest.php]: I would do it a bit different to ensure that we are actually fetching the translation. Change the mocked method to return `Very Busy` instead of the `vsprintf` and set `Very Busy` as expected value. That should ensure that a translation is returned for `Busy` because we call `t` at the right place. Does that make sense? :confused:

**Review by kesselb — APPROVED** [review]
LGTM :+1:

File: apps/dav/tests/unit/CalDAV/CalendarTest.php (hunk 8 above)
Comment (gary-kim) [reply apps/dav/tests/unit/CalDAV/CalendarTest.php]: Makes sense. I also set the expects correctly as well along with taking your advice. Should be good now. Thank you.

**Comment by gary-kim** [comment]
Going back through my PRs and I noticed this one is still open. Review please?

**Review by ChristophWurst — APPROVED** [review]
:+1: :)
