### PR TITLE
Fix translated app details

### LINKED ISSUE #6024: App with multi-lingual names is shown as Array when upgrading
### Steps to reproduce
1. Create an local app with `<name lang="en">User account deletion</name>` and another language, let's say `<name lang="fr">Supprimer son compte</name>`.
2. Install it.
3. Make a version upgrade manually

### Expected behaviour
The app name should show up in the users language, or at least the default app name in english should show up.
Putting just `<name>User account deletion</name>` inside the info.xml doesn't fixes this.

### Actual behaviour
App is named « Array »
selection_092

### Environment
git master - Nextcloud 13

### Nextcloud logs
```
[Tue Aug  8 10:49:06 2017] Array to string conversion at /home/tcit/dev/nextcloud/server/lib/private/legacy/template/functions.php#38
```

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #6024

### CODE REVIEW

File: lib/private/Installer.php [hunk 1]
```diff
@@ -163,8 +162,7 @@ public function installApp(string $appId, bool $forceEnable = false): string {
 		//run appinfo/install.php
 		self::includeAppScript($basedir . '/appinfo/install.php');
 
-		$appData = OC_App::getAppInfo($appId);
```
Comment (nickvergessen) [inline lib/private/Installer.php:166]: This is 6y old, the getAppInfo in line 117 is 5y old. I don't see much sense in it. Either they read the same info.xml anyway or we read data from 2 different sources and then either we run old repair-steps and save new remote/public handlers afterwards or the other way around.

**Comment by tcitworld** [comment]
Related to https://github.com/nextcloud/server/issues/6024 ?

**Comment by nickvergessen** [comment]
Yes, should fix it

**Review by blizzz — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]
