### PR TITLE
Show error message if config file is not readable

### LINKED ISSUE #180: white screen if webserver has no read access to config.php
### Steps to reproduce
1. make sure that config.php is neither readable nor writable by Nextcloud.

### Expected behaviour
Nextcloud should complain that it has no access to the config.php

### Actual behaviour
no data is returned. the browser page is completely white and there is no html source returned.

### Server configuration
**Operating system**:
Ubuntu
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
7
**Nextcloud version:** (see Nextcloud admin page)
9
**Updated from an older Nextcloud/ownCloud or fresh install:**
update from OC 8.2.5
**Where did you install Nextcloud from:**
manual install from zip file

**List of activated apps:**
Enabled:
  - activity: 2.2.1
  - admin_audit: 1.0.0
  - bookmarks: 0.7
  - calendar: 1.2.2
  - comments: 0.2
  - contacts: 1.3.1.0
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap

**The content of config/config.php:**

{
    "system": {
        "instanceid": "oc80d864d4c2",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/mnt\/data\/oc_data",
        "dbtype": "mysql",
        "version": "9.0.50.0",
        "dbname": "oc",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "logfile": "\/home\/oc\/logs\/owncloud.log",
        "forcessl": false,
        "theme": "",
        "maintenance": false,
        "trusted_domains": [
            ""***REMOVED SENSITIVE VALUE***"",
        ],
        "share_folder": "\/Shared",
        "loglevel": "1",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": ""***REMOVED SENSITIVE VALUE***"",
        "mail_smtpmode": "php",
        "mail_domain": ""***REMOVED SENSITIVE VALUE***"",
        "asset-pipeline.enabled": false,
        "filesystem_check_changes": 0,
        "trashbin_retention_obligation": "auto"
    }
}
**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Firefox
**Operating system:**
Linux

### PR DESCRIPTION
**Pull request by MorrisJobke**
- when the config file is not writable there is a error message shown
- same happens now if the config file is not readable
- fixes #180 

cc @adsworth @mar1u5 @williambargent @LukasReschke @schiessle

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@adsworth the stable9 patch looks like this (because of some refactoring this patch doesn't apply to stable9)

```patch
diff --git a/lib/private/config.php b/lib/private/config.php
index 368dafd..2a21cd6 100644
--- a/lib/private/config.php
+++ b/lib/private/config.php
@@ -184,10 +184,11 @@ class Config {
 
 		// Include file and merge config
 		foreach ($configFiles as $file) {
-			$filePointer = file_exists($file) ? fopen($file, 'r') : false;
+			$fileExistsAndIsReadable = file_exists($file) && is_readable($file);
+			$filePointer = $fileExistsAndIsReadable ? fopen($file, 'r') : false;
 			if($file === $this->configFilePath &&
 				$filePointer === false &&
-				@!file_exists($this->configFilePath)) {
+				!$fileExistsAndIsReadable) {
 				// Opening the main config might not be possible, e.g. if the wrong
 				// permissions are set (likely on a new installation)
 				continue;
```

File: lib/private/Config.php [hunk 1]
```diff
@@ -184,10 +184,11 @@ private function readData() {
 
 		// Include file and merge config
 		foreach ($configFiles as $file) {
-			$filePointer = file_exists($file) ? fopen($file, 'r') : false;
+			$fileExistsAndIsReadable = file_exists($file) && is_readable($file);
+			$filePointer = $fileExistsAndIsReadable ? fopen($file, 'r') : false;
 			if($file === $this->configFilePath &&
 				$filePointer === false &&
-				@!file_exists($this->configFilePath)) {
+				!$fileExistsAndIsReadable) {
```
Comment (schiessle) [inline lib/private/Config.php]: seems to be redundant, if `$fileExistsAndIsReadable` is false, then filePointer is already false, see L188

The old check, didn't checked if the config file but if the "configFilePath" exists. Don't know in which cases this makes a difference.

Comment (MorrisJobke) [inline lib/private/Config.php]: > Btw, the old check didn't checked if the config file exists but if the "configFilePath" exists.

`$file === $this->configFilePath` ;)

Comment (MorrisJobke) [inline lib/private/Config.php]: I tested your proposal and also thought about it and you are correct :) I fixed it

**Comment by LukasReschke** [comment]
LGTM

File: lib/private/Config.php (hunk 1 above)
Comment (schiessle) [inline lib/private/Config.php]: >> Btw, the old check didn't checked if the config file exists but if the "configFilePath" exists.

> `$file === $this->configFilePath` ;)

This just check if `$file` equals `$this->configFilePath`.

The old check evaluated the if-statement to false if `$this->configFilePath` exists but fopen() returned false. The new check would evaluate the if-statement to true.

But I believe that this is just a theoretical difference. I don't see how this should make a difference and also tested it.

**Comment by schiessle** [comment]
tested, LGTM
