### PR TITLE
Check whether we can json decode the translations

### LINKED ISSUE #3189: Zh-CN language error
### Steps to reproduce
1.Select Chinese language
2.
3.

### Expected behaviour
log errord

### Actual behaviour
log error

### Server configuration
**Operating sytem**:windows

**Web server:**linux

**Database:**mysql

**PHP version:**7.0.14

**Nextcloud version:** 11.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**yes

**Where did you install Nextcloud from:**The official website

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Warning    l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:54:15+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:54:09+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:53:40+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:53:40+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:53:39+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:53:39+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/comments/l10n/zh_CN.json - json error code: 3	2017-01-21T18:53:39+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:53:38+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:53:32+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:53:32+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:53:32+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:53:31+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:53:31+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:53:31+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:53:30+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:53:30+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:53:29+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:53:29+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #3189 

I'm sick of this, lets add a job to check this, so we dont release something like this again...

### CODE REVIEW

File: apps/comments/l10n/zh_CN.js [hunk 1]
```diff
@@ -14,7 +14,7 @@ OC.L10N.register(
     "Save" : "保存",
     "Allowed characters {count} of {max}" : "当前字数： {count}，最大允许：{max}",
     "Error occurred while retrieving comment with id {id}" : "检索 id 为 {id} 的评论出错",
-    "Error occurred while updating comment with id {id}" : "更新 id 为 {id} 的评论出错",
```
Comment (nickvergessen) [inline apps/comments/l10n/zh_CN.js]: There was a box character at the beginning of this string

**Review by LukasReschke — CHANGES_REQUESTED** [review]
Nice. But you need to add the test also to the matrix at the end of the .drone.yml :)

File: apps/comments/l10n/zh_CN.js (hunk 1 above)
Comment (nickvergessen) [inline apps/comments/l10n/zh_CN.js]: Btw I also fixed this on transifex, this is just to confirm that the script works.

File: build/translation-checker.php [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+ * but WITHOUT ANY WARRANTY; without even the implied warranty of
+ * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+ * GNU Affero General Public License for more details.
+ *
+ * You should have received a copy of the GNU Affero General Public License
+ * along with this program.  If not, see <http://www.gnu.org/licenses/>.
+ *
+ */
+
+$directories = [
```
Comment (ChristophWurst) [inline build/translation-checker.php]: this might get out of sync at some point, therefore it would make sense to just iterate over all subdirs in `apps`. https://github.com/nextcloud/server/pull/4485/files already handles non-existing `l10n` directories.

Comment (nickvergessen) [inline build/translation-checker.php]: Fixed

**Comment by nickvergessen** [comment]
@LukasReschke fixed

**Review by ChristophWurst — APPROVED** [review]
Looks good!

**Review by LukasReschke — APPROVED** [review]

**Comment by MorrisJobke** [comment]
@nickvergessen Could you also add this to the stable branches and all the apps we release 🙈

**Comment by nickvergessen** [comment]
No need to backport, the translation files contain the strings of 12, 11 and 10? So the check result will be the same for all?

**Comment by MorrisJobke** [comment]
> No need to backport, the translation files contain the strings of 12, 11 and 10? So the check result will be the same for all?

Ah right 🙈 

But could you create this for most of the apps out there?
