### PR TITLE
[files app]: Fix dark color mode detection for filelist

### LINKED ISSUE #33298: [Bug]: files app does not detect dark color mode if using system theming is enabled
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

On current master (did not test NC24, NC23 works) the files app does not correctly detects the dark color mode if `system theme` is selected for theming.

So the text is hardly readable, reading the date is quite impossible (black text on dark background), see this example:
file list with dark color mode is not readable

### Steps to reproduce

1. Open NC at current master
2. Open the file list
3. Set browser to dark color mode

### Expected behavior

App uses readable color for text

### Installation method

Other

### Operating system

_No response_

### PHP engine version

_No response_

### Web server

_No response_

### Database engine version

_No response_

### Is this bug present after an update or on a fresh install?

_No response_

### Are you using the Nextcloud Server Encryption module?

_No response_

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
Nothing more than the default apps
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by susnux**
* This fixes #33298

The color of the file list entries is dynamically calculated, but clipped to readable values.
This clipping is currently broken when using the system color theme and the system is using a dark color theme.

When system default color theme is selected for theming, the `enabledThemes` array
is empty or just contains one entry `'default'`, in this case the color theme has
to be retrieved from the browser to ensure text like the modified date is readable.

**Before**:
Color theme detection broken

**After:**
Readable file list as the colortheme detection is fixed

### CODE REVIEW

File: apps/files/js/filelist.js [hunk 1]
```diff
@@ -1787,8 +1787,11 @@
 			td.append(linkElem);
 			tr.append(td);
 
-			var enabledThemes = window.OCA?.Theming?.enabledThemes || []
-			var isDarkTheme = enabledThemes.join('').indexOf('dark') !== -1
+			const enabledThemes = window.OCA?.Theming?.enabledThemes || []
+			// Check enabled themes, if system default is selected check the browser
+			const isDarkTheme = enabledThemes && (enabledThemes.length > 1 || enabledThemes[0] != 'default')
+				? enabledThemes.join('').indexOf('dark') !== -1
+				: window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches
```
Comment (Pytal) [inline apps/files/js/filelist.js:1794]:
```suggestion
			const isDarkTheme = (!enabledThemes.length || enabledThemes[0] === 'default')
				? window.matchMedia('(prefers-color-scheme: dark)').matches
				: enabledThemes.join('').indexOf('dark') !== -1
```
Let's invert the logic

The `&&`'s don't seem necessary?

Comment (susnux) [reply apps/files/js/filelist.js]: You are right, fixed that.

File: apps/files/js/filelist.js [hunk 2]
```diff
@@ -1787,8 +1787,11 @@
 			td.append(linkElem);
 			tr.append(td);
 
-			var enabledThemes = window.OCA?.Theming?.enabledThemes || []
-			var isDarkTheme = enabledThemes.join('').indexOf('dark') !== -1
+			const enabledThemes = window.OCA?.Theming?.enabledThemes || []
+			// Check enabled themes, if system default is selected check the browser
+			const isDarkTheme = (enabledThemes.length === 0 || enabledThemes[0] === 'default')
+				? window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches
+				: enabledThemes.join('').indexOf('dark') !== -1
```
Comment (artonge) [inline apps/files/js/filelist.js:1794]: Wouldn't it work with only the following ?

```suggestion
			const isDarkTheme = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches
```

Comment (susnux) [reply apps/files/js/filelist.js:1794]: Then `isDarkTheme` would even be true if the browser uses a dark theme but NC is configured to use a bright theme

File: apps/files/js/filelist.js [hunk 3]
```diff
@@ -1787,8 +1787,11 @@
 			td.append(linkElem);
 			tr.append(td);
 
-			var enabledThemes = window.OCA?.Theming?.enabledThemes || []
-			var isDarkTheme = enabledThemes.join('').indexOf('dark') !== -1
+			const enabledThemes = window.OCA?.Theming?.enabledThemes || []
+			// Check enabled themes, if system default is selected check the browser
+			const isDarkTheme = (enabledThemes.length === 0 || enabledThemes[0] === 'default')
+				? window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches
```
Comment (Pytal) [inline apps/files/js/filelist.js:1793]:
```suggestion
				? window.matchMedia('(prefers-color-scheme: dark)').matches
```
Would this work @susnux?

Comment (susnux) [reply apps/files/js/filelist.js:1793]: As long as the browser supports the [`matchMedia` API](https://caniuse.com/?search=matchMedia): yes

Comment (Pytal) [reply apps/files/js/filelist.js:1793]: Could we remove the check since it's seems safe going by our browser target rules https://github.com/nextcloud/browserslist-config/blob/v2.2.0/browserlist.config.js and the compatible browsers https://browserslist.dev/?q=PjAuMjUlLCBub3QgaWUgMTEsIG5vdCBvcF9taW5pIGFsbCwgbm90IGRlYWQsIEZpcmVmb3ggRVNS?

Comment (susnux) [reply apps/files/js/filelist.js]: Done :)

**Review by artonge — APPROVED** [review]

**Review by Pytal — APPROVED** [review]

**Comment by artonge** [comment]
CI failure unrelated
