### PR TITLE
fix(job): Check if carddata is resource and read it to string

### LINKED ISSUE #46100: [Bug]: Error while running background job `OCA\\DAV\\Migration\\BuildSocialSearchIndexBackgroundJob`
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Error logged after upgrading to 29.0.3

### Steps to reproduce

1. upgrade to 29.0.3
2. see error in the logs
```json
{
  "reqId": "625OdztVi2fbvKqsf9dR",
  "level": 3,
  "time": "2024-06-25T10:57:17+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "core",
  "method": "",
  "url": "--",
  "message": "Error while running background job OCA\\DAV\\Migration\\BuildSocialSearchIndexBackgroundJob (id: 976, arguments: {\"offset\":0,\"stopAt\":23})",
  "userAgent": "--",
  "version": "29.0.3.4",
  "exception": {
    "Exception": "TypeError",
    "Message": "OCA\\DAV\\CardDAV\\CardDavBackend::getUID(): Argument #1 ($cardData) must be of type string, resource given, called in /var/www/html/apps/dav/lib/CardDAV/CardDavBackend.php on line 708",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/html/apps/dav/lib/CardDAV/CardDavBackend.php",
        "line": 708,
        "function": "getUID",
        "class": "OCA\\DAV\\CardDAV\\CardDavBackend",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/apps/dav/lib/Migration/BuildSocialSearchIndexBackgroundJob.php",
        "line": 90,
        "function": "updateCard",
        "class": "OCA\\DAV\\CardDAV\\CardDavBackend",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/apps/dav/lib/Migration/BuildSocialSearchIndexBackgroundJob.php",
        "line": 53,
        "function": "buildIndex",
        "class": "OCA\\DAV\\Migration\\BuildSocialSearchIndexBackgroundJob",
        "type": "->",
        "args": [
          23,
          23
        ]
      },
      {
        "file": "/var/www/html/lib/public/BackgroundJob/Job.php",
        "line": 80,
        "function": "run",
        "class": "OCA\\DAV\\Migration\\BuildSocialSearchIndexBackgroundJob",
        "type": "->",
        "args": [
          [
            0,
            23
          ]
        ]
      },
      {
        "file": "/var/www/html/lib/public/BackgroundJob/QueuedJob.php",
        "line": 57,
        "function": "start",
        "class": "OCP\\BackgroundJob\\Job",
        "type": "->",
        "args": [
          [
            "OC\\BackgroundJob\\JobList"
          ]
        ]
      },
      {
        "file": "/var/www/html/lib/public/BackgroundJob/QueuedJob.php",
        "line": 47,
        "function": "start",
        "class": "OCP\\BackgroundJob\\QueuedJob",
        "type": "->",
        "args": [
          [
            "OC\\BackgroundJob\\JobList"
          ]
        ]
      },
      {
        "file": "/var/www/html/cron.php",
        "line": 177,
        "function": "execute",
        "class": "OCP\\BackgroundJob\\QueuedJob",
        "type": "->",
        "args": [
          [
            "OC\\BackgroundJob\\JobList"
          ]
        ]
      }
    ],
    "File": "/var/www/html/apps/dav/lib/CardDAV/CardDavBackend.php",
    "Line": 1477,
    "message": "Error while running background job OCA\\DAV\\Migration\\BuildSocialSearchIndexBackgroundJob (id: 976, arguments: {\"offset\":0,\"stopAt\":23})",
    "exception": [],
    "CustomMessage": "Error while running background job OCA\\DAV\\Migration\\BuildSocialSearchIndexBackgroundJob (id: 976, arguments: {\"offset\":0,\"stopAt\":23})"
  },
  "id": "667aa2fd69054"
}
```

### Expected behavior

should not log an error

### Installation method

Official All-in-One appliance

### Nextcloud Server version

29

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

_No response_

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by wolandtel**
Check if oc_cards.carddata has been read as resource and read it to string.

* Resolves: #46100

### CODE REVIEW

**Review by SebastianKrupinski — APPROVED** [review]

File: apps/dav/lib/Migration/BuildSocialSearchIndexBackgroundJob.php [hunk 1]
```diff
@@ -71,7 +71,11 @@ private function buildIndex($offset, $stopAt) {
 		// refresh identified contacts in order to re-index
 		foreach ($social_cards as $contact) {
 			$offset = $contact['id'];
-			$this->davBackend->updateCard($contact['addressbookid'], $contact['uri'], $contact['carddata']);
+			$cardData = $contact['carddata'];
+			if (is_resource($cardData) && (get_resource_type($cardData) == 'stream')) {
```
Comment (ChristophWurst) [inline apps/dav/lib/Migration/BuildSocialSearchIndexBackgroundJob.php:75]:
```suggestion
			if (is_resource($cardData) && (get_resource_type($cardData) === 'stream')) {
```

Learn more at https://docs.nextcloud.com/server/latest/developer_manual/getting_started/codingguidelines.html#operators

**Review by ChristophWurst — COMMENTED** [review]
Thank you very much

**Review by ChristophWurst — APPROVED** [review]
Please squash your commits into one, then we are ready for shipping :shipit:

**Comment by solracsf** [comment]
> Please squash your commits into one, then we are ready for shipping :shipit:

And commit as [fix(job): Check if carddata is resource and read it to string](https://www.conventionalcommits.org/en/v1.0.0/) :)

**Review by skjnldsv — APPROVED** [review]

**Comment by wolandtel** [comment]
done
