### PR TITLE
fix(update-section): changed span to an interactive element

### LINKED ISSUE #42637: [BITV]: Move `title` and `aria-label` to interactive element
Screenshot from 2024-01-08 16-43-54

At settings/admin/overview

Screen reader won't read this information because `<span>` isn't an interactive element.

### PR DESCRIPTION
**Pull request by emoral435**
## Summary
Changes span to a link element, similar to how the above information button is like within the page!

🏚️ Before | 🏡 After
---|---
image|firefox_FTHm29rZl5

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [ ] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

File: apps/updatenotification/src/components/UpdateNotification.vue [hunk 1]
```diff
@@ -85,7 +85,7 @@
 			</template>
 			<template v-else>
 				{{ t('updatenotification', 'Your version is up to date.') }}
-				<span :title="lastCheckedOnString" :aria-label="lastCheckedOnString" class="icon-info svg" />
+				<a :title="lastCheckedOnString" :aria-label="lastCheckedOnString" href="https://nextcloud.com/changelog/" class="icon-info details"></a>
```
Comment (ShGKme) [inline apps/updatenotification/src/components/UpdateNotification.vue:88]: I think, it should be `target="_blank"`

**Review by Pytal — APPROVED** [review]

**Review by JuliaKirschenheuter — COMMENTED** [review]
Could you please add `aria-label` to all links for following pages: 
Screenshot from 2024-01-15 17-16-31


- settings/user/sharing - aria-label
- settings/user/workflow
- settings/admin/overview
- settings/admin
- settings/admin/sharing
- settings/admin/security
- settings/admin/theming
- settings/admin/groupware
- settings/admin/admindelegation
- settings/admin/workflow

**Review by ShGKme — APPROVED** [review]
