### PR TITLE
fix(files_external): broken credentials dialog

### LINKED ISSUE #44497: [Bug]: Enter missing credentials for external storage
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Clicking "Enter missing credentials", under Files, External Storage, results in a 401 Unauthorized error.
Screenshot from 2024-03-26 13-51-08

### Steps to reproduce

1. Click Files
2. Click External Storage
3. Click Enter Missing Credentials

### Expected behavior

I expect a dialog box to authenticate.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "files.xxx.ca"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.3.2",
        "overwrite.cli.url": "https:\/\/files.xxx.ca",
        "overwritehost": "files.xxx.ca",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "updater.release.channel": "stable",
        "allow_local_remote_servers": "true",
        "app_install_overwrite": [
            "cms_pico",
            "joplin",
            "printer",
            "passman",
            "files_markdown",
            "libresign"
        ],
        "onlyoffice": {
            "jwt_enable": true,
            "jwt_secret": "***REMOVED SENSITIVE VALUE***",
            "jwt_header": "AuthorizationJwt"
        },
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [
            "IT"
        ],
        "twofactor_enforced_excluded_groups": [],
        "default_phone_region": "CA",
        "lost_password_link": "https:\/\/reset.xxx.ca\/",
        "mail_smtpport": "25",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "maintenance_window_start": 1
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - announcementcenter: 6.8.1
  - bookmarks: 13.1.3
  - bruteforcesettings: 2.8.0
  - calendar: 4.6.7
  - calendar_resource_management: 0.7.0
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - deck: 1.12.2
  - event_update_notification: 2.3.0
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_external: 1.20.0
  - files_markdown: 2.4.1
  - files_mindmap: 0.0.30
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_retention: 1.17.1
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - groupfolders: 16.0.4
  - impersonate: 1.15.0
  - integration_mastodon: 2.0.4
  - integration_twitter: 1.0.7
  - integration_zammad: 2.0.7
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notes: 4.9.2
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - passman: 2.4.8
  - password_policy: 1.18.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - related_resources: 1.3.0
  - richdocuments: 8.3.2
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - side_menu: 3.11.8
  - support: 1.11.0
  - survey_client: 1.16.0
  - suspicious_login: 6.0.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_ldap: 1.19.0
  - user_status: 1.8.1
  - user_usage_report: 1.12.0
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - encryption: 2.16.0 (installed 2.8.1)
  - end_to_end_encryption: 1.14.3 (installed 1.14.3)
  - forms: 4.1.1 (installed 4.1.1)
  - integration_openai: 1.2.1 (installed 1.2.1)
  - photos: 2.4.0 (installed 1.2.3)
  - recommendations: 2.0.0 (installed 0.4.0)
  - twofactor_totp: 10.0.0-beta.2 (installed 10.0.0-beta.2)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

_No response_

### Additional info

The work around is for the user to go to Settings, under their profile icon, and then External Storage, after which they may enter and save credentials.

image

### PR DESCRIPTION
**Pull request by skjnldsv**
The browsers behavior changed and some stopped prompting the native browser auth dialog on xhr requests.

This replaces it with a proper dialog.
Fix https://github.com/nextcloud/server/issues/44497

### CODE REVIEW

**Review by susnux — APPROVED** [review]
Looks good!

File: apps/files_external/src/views/CredentialsDialog.vue [hunk 1]
```diff
@@ -0,0 +1,86 @@
...
+  - SPDX-License-Identifier: AGPL-3.0-or-later
+-->
+
+<template>
+	<NcDialog :buttons="dialogButtons"
+		class="external-storage-auth"
+		close-on-click-outside
+		data-cy-external-storage-auth
+		is-form
+		:name="t('files_external', 'Enter storage credentials')"
```
Comment (susnux) [inline apps/files_external/src/views/CredentialsDialog.vue:12]: You can ignore if you like but I think this would be more condensed, but fine with both :)

```suggestion
		:name="t('files_external', 'Storage credentials')"
```

**Review by provokateurin — APPROVED** [review]
