### PR TITLE
Fix federated link sharing permissions

### LINKED ISSUE #20692: "Error updating the share" when "allow editing" at sharing
Hi,

I have this issue on Nextcloud 18.0.4 and tested it also on Nextcloud 19.0.0 Beta 5.
In thread #18893  @skjnldsv advised me to open a new issue. 

### Steps to reproduce
1. I want to share a file or a directory (makes no difference) - with or without password (also no difference).
2. Additionally I want to allow editing of this shared file

screen3

3. This admin option (red arrow in screenshot) is **not** active:
screen4

### Expected behaviour
After clicking on "Allow editing" Nextcloud saves this option for this file and user with correct password can edit the file.

### Actual behaviour
After clicking on "Allow editing" this error appears: "Error updating the share". It seems to be activated, but it is not. A fresh page visit later: the option was not saved.

Only if I activate the admin config option "Allow public uploads" (see image number 2 above) the expected behaviour arise.

### Server configuration

**Operating system:** Debian 9 

**Web server:** Apache

**Database:** MariaDB 10.3

**PHP version:** 7.3

**Nextcloud version:** 18.0.4 and 19.0.0 Beta 5

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** manual install from nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.12.0
  - admin_audit: 1.9.0
  - audioplayer: 2.10.0
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.3.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - deck: 0.8.2
  - encryption: 2.7.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_pdfviewer: 1.8.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - nextcloud_announcements: 1.8.0
  - notes: 3.2.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.0
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - systemtags: 1.9.0
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - twofactor_totp: 4.1.3
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - accessibility
  - data_request
  - documentserver_community
  - files_external
  - files_lock
  - files_rightclick
  - firstrunwizard
  - onlyoffice
  - ransomware_protection
  - recommendations
  - richdocuments
  - spreed
  - support
  - survey_client
  - text
  - user_ldap
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 75.0

**Operating system:** Ubuntu 18.04 LTS

#### Web server error log
<details>
<summary>Web server error log</summary>

nothing during reproduction of the error

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
nothing during reproduction of the error
</details>
Audit log is also empty.

#### Browser log
<details>
<summary>Browser log</summary>

browser console:
screen

network requests:
screen2

After that i clicked the 400 failing request (bottom), select the repsonse tab and got this error:

`{"ocs":{"meta":{"status":"failure","statuscode":400,"message":"Public upload is not allowed"},"data":[]}}`
</details>

### PR DESCRIPTION
**Pull request by skjnldsv**
So, it of course means we don't store the SHARE permissions for link shares. We only add it on api GET.

It was mostly because of this https://github.com/nextcloud/server/blob/d221e7782c84a2fa1a69de951da70c473a470e29/apps/files_sharing/lib/Controller/ShareAPIController.php#L1002-L1005

i don't really know what we should do for this. So instead of changing 2 years old code that looks super speficic, I rathered make sure we keep it consistent. Maybe it's wrong, please suggest any better way :wave: 

In any case, this is a bit odd because when changint the link share to something like READ, we now see in the response that they have the SHARE permission, despite not really being asked for, but I guess it's fine as it behave like an enforced setting?

Reference: https://github.com/nextcloud/server/pull/19793#discussion_r417338916

It might fix https://github.com/nextcloud/server/issues/20692

### CODE REVIEW

**Comment by skjnldsv** [comment]
So, it of course means we don't store the SHARE permissions for link shares. We only add it on api GET.

It was mostly because of this https://github.com/nextcloud/server/blob/d221e7782c84a2fa1a69de951da70c473a470e29/apps/files_sharing/lib/Controller/ShareAPIController.php#L1002-L1005

i don't really know what we should do for this. So instead of changing 2 years old code that looks super speficic, I rathered make sure we keep it consistent. Maybe it's wrong, please suggest any better way :wave: 

In any case, this is a bit odd because when changint the link share to something like READ, we now see in the response that they have the SHARE permission, despite not really being asked for, but I guess it's fine as it behave like an enforced setting?

**Review by rullzer — APPROVED** [review]
does the job!

**Comment by rullzer** [comment]
Needs a rebase and then time to get it in

**Review by gary-kim — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Conflicts

**Review by MorrisJobke — APPROVED** [review]
Code makes sense 👍

**Comment by skjnldsv** [comment]
Lots of test sfailures :disappointed:

**Comment by MorrisJobke** [comment]
@skjnldsv @rullzer Why was this merged even if it had failures?

**Comment by rullzer** [comment]
mmm Did I hit merge on the wrong PR... guess so...

File: apps/files_sharing/lib/Controller/ShareAPIController.php [hunk 1]
```diff
@@ -215,11 +216,20 @@ protected function formatShare(\OCP\Share\IShare $share, Node $recipientNode = n
 			$result['expiration'] = $expiration->format('Y-m-d 00:00:00');
 		}
 
-		if ($share->getShareType() === Share::SHARE_TYPE_USER) {
+		// TODO: It might make sense to have a dedicated setting to allow/deny converting link shares into federated ones
```
Comment (rullzer) [inline apps/files_sharing/lib/Controller/ShareAPIController.php:219]: I remember the discussion here but I guess I only now see the full impact. The permission needs to be persisted in the DB else the share conversion still doesn't happen. Because other part of the NC code don't use this they uyse the share object.

So either we do not care at all. ANd just check where we need to. Or we need to also make sure it is correct in the db.

Comment (rullzer) [reply apps/files_sharing/lib/Controller/ShareAPIController.php:219]: I guess this basically reverts what we tried to do in https://github.com/nextcloud/server/pull/19793

Let me prepare a fix
