### PR TITLE
fix: Dispatch favorite event with an actual path

### LINKED ISSUE #2134: [Bug]: Activity: “Add to Favorites” does not show filename in Nextcloud 31
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce
1. Open Files app in Nextcloud 31 (official release).
2. Add any file or folder to Favorites (via star icon).
3. Open Activity app (web or mobile client).
4. Check the entry for the "added to favorites" action.

### Expected behavior
The Activity entry should display the filename (or folder name) that was added to Favorites.

### Actual behavior
The Activity entry only shows a generic message like:
"Added to your favorites"  
but **no filename is shown**.

Screenshots:
(see attached example: [add your screenshot here])

### Environment
- Nextcloud Server: 31.0.8 (official release, no third-party apps)
- PHP: 8.2
- Database:8.0
- OS: centos8

### Notes
- The file/folder is correctly added to Favorites (visible in the Files → Favorites list).
- The issue occurs in both **web UI** and **mobile app**.
- No third-party plugins are installed.
- Other Activity types (e.g. file changes, shares) correctly show filenames.  
- This seems to be a regression / bug introduced with the new “favorites activity” feature in Nextcloud 31.

### Impact
Users cannot identify which file/folder was added to or removed from Favorites by reading the Activity feed.

### Possible cause
The Activity entry created by the “favorite provider” does not include the file path or filename.

### Version tested
Nextcloud 31.0.8

### Steps to reproduce

1. Open Files app in Nextcloud 31 (official release).
2. Add any file or folder to Favorites (via star icon).
3. Open Activity app (web or mobile client).
4. Check the entry for the "added to favorites" action.

### Expected behavior

The file name should be recorded to let the user know which file was operated

### Nextcloud Server version

30

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json
"system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.100.105.90"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "31.0.8.1",
        "overwrite.cli.url": "http:\/\/xxx.xxx.com:8989",
        "overwritecondaddr": "^10\\.147\\.17\\.0\/24$",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_language": "zh_CN",
        "default_locale": "zh",
        "default_phone_region": "CN",
        "default_timezone": "Asia\/Shanghai",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "preview_ffmpeg_path": "\/usr\/bin\/ffmpeg",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "read_timeout": 0
        },
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP4",
            "OC\\Preview\\AVI",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Photoshop"
        ],
        "loglevel": 2,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpport": "465",
        "theme": "",
        "app_install_overwrite": [
            "onlyoffice"
        ],
        "maintenance_window_start": 1,
        "memories.db.triggers.fcu": true,
        "memories.exiftool_no_local": true,
        "memories.vod.path": "\/application\/nginx-1.25.2\/html\/nextcloud\/apps\/memories\/bin-ext\/go-vod-amd64",
        "memories.vod.ffmpeg": "\/usr\/bin\/ffmpeg",
        "memories.vod.ffprobe": "\/usr\/bin\/ffprobe",
        "memories.gis_type": 1
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 4.0.0
  - admin_audit: 1.21.0
  - app_api: 5.0.2
  - bruteforcesettings: 4.0.0
  - circles: 31.0.0
  - cloud_federation_api: 1.14.0
  - comments: 1.21.0
  - contactsinteraction: 1.12.0
  - dav: 1.33.0
  - federatedfilesharing: 1.21.0
  - federation: 1.21.0
  - files: 2.3.1
  - files_downloadlimit: 4.0.0
  - files_external: 1.23.0
  - files_pdfviewer: 4.0.0
  - files_reminders: 1.4.0
  - files_sharing: 1.23.1
  - files_trashbin: 1.21.0
  - files_versions: 1.24.0
  - firstrunwizard: 4.0.0
  - logreader: 4.0.0
  - lookup_server_connector: 1.19.0
  - memories: 7.6.2
  - nextcloud_announcements: 3.0.0
  - notifications: 4.0.0
  - oauth2: 1.19.1
  - password_policy: 3.0.0
  - photos: 4.0.0
  - privacy: 3.0.0
  - profile: 1.0.0
  - provisioning_api: 1.21.0
  - recommendations: 4.0.0
  - related_resources: 2.0.0
  - serverinfo: 3.0.0
  - settings: 1.14.0
  - sharebymail: 1.21.0
  - support: 3.0.0
  - survey_client: 3.0.0
  - systemtags: 1.21.1
  - text: 5.0.0
  - theming: 2.6.1
  - twofactor_backupcodes: 1.20.0
  - updatenotification: 1.21.0
  - user_status: 1.11.0
  - viewer: 4.0.0
  - weather_status: 1.11.0
  - webhook_listeners: 1.2.0
  - workflowengine: 2.13.0
Disabled:
  - dashboard: 7.11.0 (installed 7.0.0)
  - encryption: 2.19.0
  - suspicious_login: 9.0.1
  - twofactor_nextcloud_notification: 5.0.0
  - twofactor_totp: 13.0.0-dev.0
  - user_ldap: 1.22.0
[root@serverData ~]#
```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by artonge**
The `$path` argument was added in https://github.com/nextcloud/server/pull/48612, but was never actually used by the callers. The path was therefore missing in the favorite/unfavorite events, which lead to a broken activity information.

I also added a fallback to handle `addToFavorites` and `removeFromFavorites`, which are part of a public API, and are calling `tagAs` and `untag` without `$path`.

Fix https://github.com/nextcloud/activity/issues/2134

### CODE REVIEW

File: lib/private/TagManager.php [hunk 1]
```diff
@@ -56,7 +58,8 @@ public function load($type, $defaultTags = [], $includeShared = false, $userId =
 			}
 			$userId = $this->userSession->getUser()->getUId();
 		}
-		return new Tags($this->mapper, $userId, $type, $this->logger, $this->connection, $this->dispatcher, $this->userSession, $defaultTags);
+		$userFolder = $this->rootFolder->getUserFolder($userId);
+		return new Tags($this->mapper, $userId, $type, $this->logger, $this->connection, $this->dispatcher, $this->userSession, $userFolder);
```
Comment (provokateurin) [inline lib/private/TagManager.php]:
```suggestion
		return new Tags($this->mapper, $userId, $type, $this->logger, $this->connection, $this->dispatcher, $this->userSession, $userFolder, $defaultTags);
```

File: lib/public/ITags.php [hunk 2]
```diff
@@ -185,19 +185,23 @@ public function removeFromFavorites($objid);
 	 * @param int $objid The id of the object
 	 * @param string $tag The id or name of the tag
 	 * @return boolean Returns false on database error.
+	 * @param string $path The optional path of the node. Used when dispatching the favorite change event.
 	 * @since 6.0.0
+	 * @since 31.0.0 Added the $path argument.
```
Comment (provokateurin) [inline lib/public/ITags.php:190]:
```suggestion
	 * @since 33.0.0 Added the $path argument.
```

File: lib/public/ITags.php [hunk 3]
```diff
@@ -185,19 +185,23 @@ public function removeFromFavorites($objid);
...
 
 	/**
 	 * Delete single tag/object relation from the db
 	 *
 	 * @param int $objid The id of the object
 	 * @param string $tag The id or name of the tag
+	 * @param string $path The optional path of the node. Used when dispatching the favorite change event.
 	 * @return boolean
 	 * @since 6.0.0
+	 * @since 31.0.0 Added the $path argument.
```
Comment (provokateurin) [inline lib/public/ITags.php:203]:
```suggestion
	 * @since 33.0.0 Added the $path argument.
```

**Review by provokateurin — CHANGES_REQUESTED** [review]

File: lib/public/ITags.php (hunk 2 above)
Comment (artonge) [reply lib/public/ITags.php:190]: It was added in 31 by https://github.com/nextcloud/server/pull/48612

File: lib/public/ITags.php (hunk 3 above)
Comment (artonge) [reply lib/public/ITags.php:203]: It was added in 31 by https://github.com/nextcloud/server/pull/48612

File: lib/public/ITags.php (hunk 2 above)
Comment (provokateurin) [reply lib/public/ITags.php:190]: But the default value is changed in this PR

Comment (artonge) [reply lib/public/ITags.php:190]: True, will add a second line

**Review by provokateurin — APPROVED** [review]

**Review by AndyScherzinger — APPROVED** [review]
🐘

**Review by icewind1991 — APPROVED** [review]
