### PR TITLE
Convert value of timestamp metadata key in swift files_external

### LINKED ISSUE #13448: Upload to external swift storage fails
Hi, 

**Actual behaviour**
Uploading a file using the desktop client for Mac OSX (Version 2.5.1final (build 20181204)) fails with the following message: 
_The key provided "" has the wrong value type. You provided 1543265922 (integer) but was expecting string_

After a while, the client retries the upload and succeeds. The file is then also visible at the Nextcloud web Application. 

A similar behaviour occurs while uploading a file with the Android App (Version 3.4.1). The upload fails with the message _Server not found_. But looking at the web application shows the file correctly uploaded to the external swift storage. 

Uploading to the main (internal) storage, which is just a folder in the webserver does work in both cases without any errors. 

Android version: 8.0

Device model: Galaxy S7

Stock or customized system: Stock

Nextcloud app version: 3.4.1

Nextcloud server version: 15.0.0

Php version: 7.0.30-0+deb9u1

External Storage: OpenStack Swift hosted at OVH.net

**Logs**
[webdav] Fatal: Exception: The key provided "" has the wrong value type. You provided 1543265922 (integer) but was expecting string at <<closure>>

 0. /var/www/html/cloud/3rdparty/php-opencloud/openstack/src/Common/Api/Parameter.php line 196
    validateType(1543265922)
 1. /var/www/html/cloud/3rdparty/php-opencloud/openstack/src/Common/Api/Parameter.php line 242
    validate(1543265922)
 2. /var/www/html/cloud/3rdparty/php-opencloud/openstack/src/Common/Api/Parameter.php line 201
    validateObject({timestamp: 1543265922})
 3. /var/www/html/cloud/3rdparty/php-opencloud/openstack/src/Common/Api/Operation.php line 127
    validate({timestamp: 1543265922})
 4. /var/www/html/cloud/3rdparty/php-opencloud/openstack/src/Common/Api/OperatorTrait.php line 112
    validate({containerName:  ... }})
 5. /var/www/html/cloud/3rdparty/php-opencloud/openstack/src/Common/Api/OperatorTrait.php line 126
    sendRequest(OpenStack\Common\Api\Operation {}, {containerName:  ... }})
 6. /var/www/html/cloud/3rdparty/php-opencloud/openstack/src/ObjectStore/v1/Models/StorageObject.php line 186
    execute({method: "POST", ... }}, {containerName:  ... }})
 7. /var/www/html/cloud/apps/files_external/lib/Lib/Storage/Swift.php line 461
    mergeMetadata({timestamp: 1543265922})
 8. /var/www/html/cloud/lib/private/Files/Storage/Wrapper/Wrapper.php line 354
    touch("Upload/pdf.pdf", 1543265922)
 9. /var/www/html/cloud/lib/private/Files/Storage/Wrapper/Availability.php line 376
    touch("Upload/pdf.pdf", 1543265922)
10. /var/www/html/cloud/lib/private/Files/Storage/Wrapper/Wrapper.php line 354
    touch("Upload/pdf.pdf", 1543265922)
11. /var/www/html/cloud/lib/private/Files/View.php line 1144
    touch("Upload/pdf.pdf", 1543265922)
12. /var/www/html/cloud/lib/private/Files/View.php line 567
    basicOperation("touch", "/cloud_storage/Upload/pdf.pdf", ["touch"], 1543265922)
13. /var/www/html/cloud/apps/dav/lib/Connector/Sabre/File.php line 255
    touch("/cloud_storage/Upload/pdf.pdf", 1543265922)
14. /var/www/html/cloud/apps/dav/lib/Connector/Sabre/Directory.php line 156
    put(null)
15. /var/www/html/cloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1096
    createFile("pdf.pdf", null)
16. /var/www/html/cloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 525
    createFile("files/jos/cloud_storage/Upload/pdf.pdf", null, null)
17. <<closure>>
    httpPut(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
18. /var/www/html/cloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    call_user_func_array([Sabre\DAV\CorePlugin {},"httpPut"], [Sabre\HTTP\Requ ... }])
19. /var/www/html/cloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    emit("method:PUT", [Sabre\HTTP\Requ ... }])
20. /var/www/html/cloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
21. /var/www/html/cloud/apps/dav/lib/Server.php line 298
    exec()
22. /var/www/html/cloud/apps/dav/appinfo/v2/remote.php line 35
    exec()
23. /var/www/html/cloud/remote.php line 163
    require_once("/var/www/html/c ... p")

PUT /remote.php/dav/files/x/cloud_storage/Upload/pdf.pdf
from x.x.x.x by x at 2018-12-28T21:42:57+00:00

### PR DESCRIPTION
**Pull request by mzamot**
Fixes #13448 
The error reported in the logs mentions it is expecting a string, but an int was provided 

```
The key provided \"\" has the wrong value type. You provided 1550708014 (integer) but was expecting string
```
Before this change file uploads were failing when using Swift as external storage. I verified uploading several files and comparing with md5sum.

### CODE REVIEW

File: apps/files_external/lib/Lib/Storage/Swift.php [hunk 1]
```diff
@@ -451,7 +451,7 @@ public function touch($path, $mtime = null) {
 		if (is_null($mtime)) {
 			$mtime = time();
 		}
-		$metadata = ['timestamp' => $mtime];
+		$metadata = ['timestamp' => strval($mtime)];
```
Comment (kesselb) [inline apps/files_external/lib/Lib/Storage/Swift.php]: (string)$mtime is faster.

Comment (icewind1991) [reply apps/files_external/lib/Lib/Storage/Swift.php]: and the way it usually done in nc.

I would prefer to see this changed but it's not blocking imo

**Review by icewind1991 — APPROVED** [review]

File: apps/files_external/lib/Lib/Storage/Swift.php (hunk 1 above)
Comment (mzamot) [reply apps/files_external/lib/Lib/Storage/Swift.php]: Awesome, I changed it to (string)$mtime

**Review by rullzer — APPROVED** [review]
