### PR TITLE
Sort app scripts by dependencies

### LINKED ISSUE #30278: Issues with dependency logic in `Util::addScript`
The new dependency logic as implemented in https://github.com/nextcloud/server/pull/30015 is broken if dependencies themselves have dependencies. E.g. when text app depends on viewer and viewer depends on files, the script from text is loaded first while the script from viewer comes later:

The problem is that the `files` dependency of `viewer` moves `viewer/js/viewer-main` to the `last` element of `files`, while the `viewer` dependendy on `text` moves `text/js/text-viewer` to the `last` element of `viewer`. Viewer is before files but `viewer` no longer contains `viewer/js/viewer-main`, so loading `text/js/text-viewer` from `last` fails.

`self::$scripts` from https://github.com/nextcloud/server/blob/791d57051ad4d5fd6f24a0e8c200ca1fc8555c3e/lib/public/Util.php#L243 when loading the Collectives app:

```json
{
  "accessibility": {
    "first": [
      "accessibility/l10n/en",
      "accessibility/js/accessibilityoca"
    ]
  },
  "files_sharing": {
    "first": [
      "files_sharing/l10n/en",
      "files_sharing/js/dist/main"
    ]
  },
  "text": {
    "first": [
      "text/l10n/en"
    ]
  },
  "viewer": {
    "first": [
      "viewer/l10n/en"
    ],
    "last": [
      "text/js/text-viewer"
    ]
  },
  "files": {
    "first": [],
    "last": [
      "viewer/js/viewer-main"
    ]
  },
  "theming": {
    "first": [
      "theming/l10n/en",
      "theming/js/theming"
    ]
  },
  "user_status": {
    "first": [
      "user_status/l10n/en",
      "user_status/js/user-status-menu"
    ]
  },
  "core": {
    "first": [],
    "last": [
      "core/js/dist/unified-search"
    ]
  }
}
```

After removing `files` dependency from `viewer` (in https://github.com/nextcloud/viewer/pull/1081/files#diff-a14aae69340720190ddf327b54675eacd97116b45f5b57f583ddb52829a3f152R41):

```json
{
  "accessibility": {
    "first": [
      "accessibility/l10n/en",
      "accessibility/js/accessibilityoca"
    ]
  },
  "files_sharing": {
    "first": [
      "files_sharing/l10n/en",
      "files_sharing/js/dist/main"
    ]
  },
  "text": {
    "first": [
      "text/l10n/en"
    ]
  },
  "viewer": {
    "first": [
      "viewer/l10n/en",
      "viewer/js/viewer-main"
    ],
    "last": [
      "text/js/text-viewer"
    ]
  },
  "theming": {
    "first": [
      "theming/l10n/en",
      "theming/js/theming"
    ]
  },
  "user_status": {
    "first": [
      "user_status/l10n/en",
      "user_status/js/user-status-menu"
    ]
  },
  "core": {
    "first": [],
    "last": [
      "core/js/dist/unified-search"
    ]
  }
}
```

So I guess we need to improve the logic and sort scripts by dependencies.

### PR DESCRIPTION
**Pull request by mejo-**
There must be a smarter and less expensive way to implement this, it's
just a first attempt.

Fix #30278

| unsorted | sorted |
|:---------:|:------:|
|||

### CODE REVIEW

File: lib/public/Util.php [hunk 1]
```diff
@@ -241,10 +246,28 @@ public static function getScripts(): array {
...
+				$sortedScripts[$app] = array_merge($scripts, $sortedScripts[$app]);
+			}
+		}
+
 		// sort core first
-		$scripts = array_merge(isset($appScripts['core']) ? $appScripts['core'] : [], ...array_values($appScripts));
+		$finalScripts = array_merge(isset($sortedScripts['core']) ? $sortedScripts['core'] : [], ...array_values($sortedScripts));
 		// remove duplicates
-		return array_unique($scripts);
+		return array_unique($finalScripts);
```
Comment (skjnldsv) [inline lib/public/Util.php:270]:
```suggestion
		$sortByDeps = function(string $app1, string $app2): int {
			// Always sort core first
			if ($app1 === 'core') {
				return -1;
			}
			if ($app2 === 'core') {
				return 1;
			}

			// If app1 depends on app2
			if (array_key_exists($app1, self::$scriptDeps) && self::$scriptDeps[$app1] === $app2) {
				return 1;
			}
			// If app2 depends on $app1
			if (array_key_exists($app2, self::$scriptDeps) && self::$scriptDeps[$app2] === $app1) {
				return -1;
			}
			return 0;
		};
		uksort($appScripts, $sortByDeps);

		// flatten array and remove duplicates 
		return array_unique(array_merge(...array_values($appScripts)));
```

Comment (skjnldsv) [reply lib/public/Util.php:270]: See my suggestion for simpler and cleaner code!
Nice job storing the deps, the logic makes much more sense! :rocket:

**Review by skjnldsv — CHANGES_REQUESTED** [review]

**Comment by skjnldsv** [comment]
Something I've been wondering, shall we make all the translations depends on core?
Like we init the base layer, then all translations, then apps?

Since apps can have their scripts loaded far before their translations, I feel this is safer:
```php
// addTranslations
self::$scripts['core']['last'][] = $path;
```

**Review by skjnldsv — CHANGES_REQUESTED** [review]
```php
	/**
	 * Return the list of scripts injected to the page
	 * @return array
	 * @since 24.0.0
	 */
	public static function getScripts(): array {
		// Merging first and last data set
		$mapFunc = function (array $scriptsArray): array {
			return array_merge(...array_values($scriptsArray));
		};
		$appScripts = array_map($mapFunc, self::$scripts);

		// Sort by dependency if any
		$sortByDeps = function(string $app1, string $app2): int {
			// Always sort core first
			if ($app1 === 'core') {
				return -1;
			}
			if ($app2 === 'core') {
				return 1;
			}

			// If app1 depends on app2
			if (array_key_exists($app1, self::$scriptDeps) && self::$scriptDeps[$app1] === $app2) {
				return 1;
			}
			// If app2 depends on $app1
			if (array_key_exists($app2, self::$scriptDeps) && self::$scriptDeps[$app2] === $app1) {
				return -1;
			}
			return 0;
		};
		uksort($appScripts, $sortByDeps);

		// Flatten array and remove duplicates 
		return array_unique(array_merge(...array_values($appScripts)));
	}
```

Here is my suggestion for simpler and cleaner code!
Nice job storing the deps, the logic makes much more sense! :rocket:

**Comment by skjnldsv** [comment]
Please not that might create some unsupported setups though.
Like scripts can depends on various different apps
But we store the deps per app, and not per script.

So if I have the following: 
```php
Util::addScript('viewer, 'viewer-main', 'files');
Util::addScript('text, 'text-main', 'viewer');
// for some reason
Util::addScript('text, 'text-public', 'core');
```

Then I might have `text` put after `core` and not after `viewer`

**Comment by mejo-** [comment]
> Here is my suggestion for simpler and cleaner code!

Thanks @skjnldsv! Unfortunately your solution doesn't fix the problem. Consider a situation with `$appScripts` containing apps `[one, four, three, two]`, and app `four` depending on `two`. Since they're never directly compared, they won't be exchanged by `sortByDeps` :cry:

File: lib/public/Util.php [hunk 2]
```diff
@@ -241,10 +246,28 @@ public static function getScripts(): array {
...
+
+		// Sort app scripts by dependency
+		$sortedScripts = [];
+		foreach ($appScripts as $app => $scripts) {
+			if (array_key_exists($app, self::$scriptDeps)) {
+				$dep = self::$scriptDeps[$app];
+				if (!array_key_exists($dep, $sortedScripts)) {
+					$sortedScripts[$dep] = [];
+				}
+				$sortedScripts[$dep] += array_merge($sortedScripts[$dep], $scripts);
```
Comment (come-nc) [inline lib/public/Util.php:258]: Is `+=` on purpose? It is redundant with the `array_merge`, no?

**Comment by skjnldsv** [comment]
> Since they're never directly compared, they won't be exchanged by `sortByDeps`

Nice catch. Good enough?

```php

	/**
	 * Return the list of scripts injected to the page
	 * @return array
	 * @since 24.0.0
	 */
	public static function getScripts(): array {
		// Merging first and last data set
		$mapFunc = function (array $scriptsArray): array {
			return array_merge(...array_values($scriptsArray));
		};
		$appScripts = array_map($mapFunc, self::$scripts);

		// Sort by dependency if any
		$sortedScripts = [];
		foreach(array_keys($appScripts) as $app) {
			// If we already processed the scripts by a dependency, continue
			if (array_key_exists($app, $sortedScripts)) {
				continue;
			}

			// If app depends on another one, append the dependency scripts first
			if (array_key_exists($app, self::$scriptDeps)) {
				$dep = self::$scriptDeps[$app];
				$sortedScripts[] = $appScripts[$dep];
			}
			// Append scripts
			$sortedScripts[] = $appScripts[$app];
		}

		// Flatten array and remove duplicates 
		return array_unique(array_merge(...array_values($sortedScripts)));
	}
```

**Comment by come-nc** [comment]
`isset` is both faster and clearer than `array_key_exists`, no?

**Comment by skjnldsv** [comment]
> `isset` is both faster and clearer than `array_key_exists`, no?

https://gist.github.com/alcaeus/536156663fac96744eba77b3e133e50a
```
$ php in_array_vs_isset_vs_array_key_exists.php 
Function call in_array took 1.51871 seconds
Function call isset took 0.14684 seconds
Function call array_key_exists took 0.22123 seconds
```

File: lib/public/Util.php (hunk 2 above)
Comment (mejo-) [reply lib/public/Util.php:258]: You're right, good catch :blush:

**Comment by mejo-** [comment]
> > Since they're never directly compared, they won't be exchanged by `sortByDeps`
> 
> Nice catch. Good enough?

Sorry to say, but still doesn't solve the problem. Imagine the following graph:

`self::$scripts`:
```yaml
- text:
    first:
      - text/l10n/en
    last: []
- viewer:
    first:
      - viewer/l10n/en
    last:
      - text/js/text-viewer
- files:
    first: []
    last:
      - viewer/js/viewer-main
```

`self::$scriptDeps`:
```yaml
- text: viewer
- viewer: files
```

Your approach will result in:

```yaml
- viewer:
    - viewer/l10n/en
    - text/js/text-viewer
- text:
    - text/l10n/en
- files:
    - viewer/js/viewer-main
```

Files, which holds the viewer script (that is the real dependency for the text script) is still the last in order.

**Comment by mejo-** [comment]
I pushed an updated version of my solution, using `array_push` instead of `array_merge` for better performance.

**Comment by skjnldsv** [comment]
Thanks for tackling this, I'm not in the best algo mindset lately it seems :)

**Review by skjnldsv — APPROVED** [review]

**Comment by mejo-** [comment]
Well, after further thinking this through, I found a flaw in my implementation - and as it turned out in the whole `first`/`last` logic.

I ended up adding proper unit tests to check for all the logic that we want: https://github.com/nextcloud/server/pull/30279/commits/3cef72e85354c843386e5f37b6b2ce5b73882d44

And then I came up with a solution that hopefully implements proper topological sorting for the scripts by its dependencies. I removed the former `first`/`last` logic in `addScript()` and instead just store the dependencies in an own array. In `getScripts()` I sort the scripts using `uksort()`. In the `uksort()` callable, I check whether the script is still before its dependency and in this case move it backwards:

```php
		$sortByDeps = static function (string $app1, string $app2): int {
			// Always sort core first
			if ($app1 === 'core') {
				return -1;
			}
			if ($app2 === 'core') {
				return 1;
			}

			// If app1 has a dependency
			if (array_key_exists($app1, self::$scriptDeps)) {
				$apps = array_keys(self::$scripts);
				// Move app1 backwards if dep comes afterwards
				if (array_search($app1, $apps, true) <
					array_search(self::$scriptDeps[$app1], $apps, true)) {
					return 1;
				}
			}

			return 0;
		};
		uksort(self::$scripts, $sortByDeps);

		// Flatten array and remove duplicates
		return array_unique(array_merge(...array_values(self::$scripts)));
```

**Review by skjnldsv — APPROVED** [review]

File: lib/public/Util.php [hunk 3]
```diff
@@ -236,15 +212,32 @@ public static function addScript($application, $file = null, $afterAppId = null)
...
 		};
-		$appScripts = array_map($mapFunc, self::$scripts);
-		// sort core first
-		$scripts = array_merge(isset($appScripts['core']) ? $appScripts['core'] : [], ...array_values($appScripts));
-		// remove duplicates
-		return array_unique($scripts);
+		uksort(self::$scripts, $sortByDeps);
+
+		// Flatten array and remove duplicates
+		return array_unique(array_merge(...array_values(self::$scripts)));
```
Comment (juliushaertl) [inline lib/public/Util.php:240]: This line causes CI failure on installation/maintenance mode:

```
{
  "Exception": "Error",
  "Message": "array_merge() expects at least 1 parameter, 0 given at /drone/src/lib/public/Util.php#240",
  "Code": 0,
  "Trace": [
    {
      "function": "onError",
      "class": "OC\\Log\\ErrorHandler",
      "type": "::",
      "args": [
        2,
        "array_merge() expects at least 1 parameter, 0 given",
        "/drone/src/lib/public/Util.php",
        240,
        {
          "sortByDeps": {
            "__class__": "Closure"
          }
        }
      ]
    },
    {
      "file": "/drone/src/lib/public/Util.php",
      "line": 240,
      "function": "array_merge",
      "args": []
    },
    {
      "file": "/drone/src/lib/private/TemplateLayout.php",
      "line": 212,
      "function": "getScripts",
      "class": "OCP\\Util",
      "type": "::",
      "args": []
    },
    {
      "file": "/drone/src/lib/private/legacy/OC_Template.php",
      "line": 177,
      "function": "__construct",
      "class": "OC\\TemplateLayout",
      "type": "->",
      "args": [
        "guest",
        ""
      ]
    },
    {
      "file": "/drone/src/lib/private/Template/Base.php",
      "line": 132,
      "function": "fetchPage",
      "class": "OC_Template",
      "type": "->",
      "args": []
    },
    {
      "file": "/drone/src/lib/private/legacy/OC_Template.php",
      "line": 267,
      "function": "printPage",
      "class": "OC\\Template\\Base",
      "type": "->",
      "args": []
    },
    {
      "file": "/drone/src/core/Controller/SetupController.php",
      "line": 106,
      "function": "printGuestPage",
      "class": "OC_Template",
      "type": "::",
      "args": [
        "",
        "installation",
        {
          "adminlogin": "",
          "adminpass": "",
          "dbuser": "",
          "dbpass": "",
          "dbname": "",
          "0": "And 13 more entries, set log level to debug to see all entries"
        }
      ]
    },
    {
      "file": "/drone/src/core/Controller/SetupController.php",
      "line": 85,
      "function": "display",
      "class": "OC\\Core\\Controller\\SetupController",
      "type": "->",
      "args": [
        "*** sensitive parameters replaced ***"
      ]
    },
    {
      "file": "/drone/src/lib/base.php",
      "line": 939,
      "function": "run",
      "class": "OC\\Core\\Controller\\SetupController",
      "type": "->",
      "args": [
        "*** sensitive parameters replaced ***"
      ]
    },
    {
      "file": "/drone/src/index.php",
      "line": 36,
      "function": "handleRequest",
      "class": "OC",
      "type": "::",
      "args": []
    }
  ],
  "File": "/drone/src/lib/private/Log/ErrorHandler.php",
  "Line": 92,
  "CustomMessage": "--"
}
```

**Review by juliusknorr — CHANGES_REQUESTED** [review]

File: lib/public/Util.php (hunk 3 above)
Comment (juliushaertl) [reply lib/public/Util.php:240]: I guess we do not load any scripts there

Comment (come-nc) [reply lib/public/Util.php:240]: This will only happen on PHP < 7.4: https://www.php.net/manual/fr/function.array-merge.php

So not a problem for Nextcloud 24, but needs to be fixed if this will be backported to 23 or lower.

Comment (mejo-) [reply lib/public/Util.php]: Thanks for the pointer, should be fixed now:

```diff
--- a/lib/public/Util.php
+++ b/lib/public/Util.php
@@ -237,7 +237,7 @@ class Util {
                uksort(self::$scripts, $sortByDeps);
 
                // Flatten array and remove duplicates
-               return array_unique(array_merge(...array_values(self::$scripts)));
+               return self::$scripts ? array_unique(array_merge(...array_values(self::$scripts))) : [];
        }
 
        /**
```

**Review by juliusknorr — APPROVED** [review]
