### PR TITLE
fix(files): handle multidimensional arrays in scanner 

### LINKED ISSUE #43408: [Bug]: enabling external storage on 28.0.2 generates error during `occ files:scan`
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

New / fresh installation of Nextcloud 28.0.2

### Steps to reproduce

1. Fresh install of 28.0.2
2. Enable external storage
3. Configure S3 object storage
4. Add user with access to S3 storage
5. Run  nocc-cldtst01 files:scan timv (alias to below)

alias nocc-cldtst01="sudo -u www-data php /var/www/cldtst01.site1.com/html/occ"

### Expected behavior

Output
root@X.X.X.X:~$ nocc-cldtst01-site1 files:scan --all
Starting scan for user 1 out of 1 (admin)
Error during scan: Array to string conversion
Error during scan: Array to string conversion
....................
Error during scan: Array to string conversion
Error during scan: Array to string conversion
+---------+-------+-----+---------+---------+--------+--------------+
| Folders  | Files     | New | Updated | Removed | Errors | Elapsed time |
+---------+-------+-----+---------+---------+--------+--------------+
| 49          | 218      | 0      | 1           | 0                | 84      | 00:00:01         |
+---------+-------+-----+---------+---------+--------+--------------+
root@X.X.X.X:~$

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
root@X.X.X.X:~$ nocc-cldtst01-site1 config:list system
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "vmi1517.site1.com",
            "cldtst01.site1.com",
            "X.X.X.X"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.2.5",
        "overwrite.cli.url": "https:\/\/cldtst01.site1.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "cldtst01.site1.com",
        "activity_expire_days": 14,
        "allow_local_remote_servers": true,
        "auth.bruteforce.protection.enabled": true,
        "blacklisted_files": [
            ".htaccess",
            "Thumbs.db",
            "thumbs.db"
        ],
        "cron_log": true,
        "default_phone_region": "US",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "filesystem_check_changes": 0,
        "filelocking.enabled": "true",
        "htaccess.RewriteBase": "\/",
        "integrity.check.disabled": false,
        "knowledgebaseenabled": false,
        "log_rotate_size": "104857600",
        "logfile": "\/var\/log\/nextcloud\/cldtst01-site1.log",
        "loglevel": 2,
        "logtimezone": "America\/Los_Angeles",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "overwriteprotocol": "https",
        "preview_max_x": 1024,
        "preview_max_y": 768,
        "preview_max_scale_factor": 1,
        "profile.enabled": false,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 0.5,
            "dbindex": 1
        },
        "quota_include_external_storage": false,
        "share_folder": "\/StorageShare",
        "skeletondirectory": "",
        "trashbin_retention_obligation": "auto, 7"
    }
}
root@X.X.X.X:~$
```

### List of activated Apps

```shell
root@X.X.X.X:~$ nocc-cldtst01-site1 app:list
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - cloud_federation_api: 1.11.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - files: 2.0.0
  - files_external: 1.20.0
  - files_pdfviewer: 2.9.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - viewer: 2.2.0
  - workflowengine: 2.10.0
Disabled:
  - bruteforcesettings: 2.8.0
  - circles: 28.0.0-dev (installed 28.0.0-dev)
  - comments: 1.18.0 (installed 1.18.0)
  - contactsinteraction: 1.9.0 (installed 1.9.0)
  - dashboard: 7.8.0 (installed 7.8.0)
  - encryption: 2.16.0
  - federation: 1.18.0 (installed 1.18.0)
  - files_reminders: 1.1.0 (installed 1.1.0)
  - firstrunwizard: 2.17.0 (installed 2.17.0)
  - nextcloud_announcements: 1.17.0 (installed 1.17.0)
  - notifications: 2.16.0 (installed 2.16.0)
  - recommendations: 2.0.0 (installed 2.0.0)
  - related_resources: 1.3.0 (installed 1.3.0)
  - support: 1.11.0 (installed 1.11.0)
  - survey_client: 1.16.0 (installed 1.16.0)
  - suspicious_login: 6.0.0
  - systemtags: 1.18.0 (installed 1.18.0)
  - twofactor_totp: 10.0.0-beta.2
  - user_ldap: 1.19.0
  - user_status: 1.8.1 (installed 1.8.1)
  - weather_status: 1.8.0 (installed 1.8.0)
root@X.X.X.X:~$
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
root@X.X.X.X:/var/log/nextcloud$ tail -f cldtst01-site1.log
{"reqId":"BsKXnLgxxgk9OrTCg4dN","level":2,"time":"2024-02-06T13:25:37-08:00","remoteAddr":"Z.Z.Z.Z","user":"--","app":"no app in context","method":"POST","url":"/login","message":"Login failed: timv (Remote IP: Z.Z.Z.Z3)","userAgent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36","version":"28.0.2.5","data":[]}
```

### Additional info

_No response_

### LINKED ISSUE #43642: [Bug]: Unable to upload "big" files to S3 external storage
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I simply can't upload files larger than at least 80MB using Nextcloud. It uploads just fine on S3 console.

### Steps to reproduce

1. Setup an S3 bucket as external storage mounted on /
2. Try to upload my file in Additional information

### Expected behavior

It should upload.

### Installation method

None

### Nextcloud Server version

26

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "cache_path": "\/tmp\/nextcloud-cache",
        "one-click-instance": true,
        "one-click-instance.user-limit": 100,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "appsallowlist": [],
        "check_data_directory_permissions": false,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "overwritehost": "nextcloud.hyoretsu.com",
        "overwriteprotocol": "https",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "nextcloud.hyoretsu.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "28.0.2.5",
        "overwrite.cli.url": "https:\/\/nextcloud.hyoretsu.com\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "updatedirectory": "\/nc-updater",
        "loglevel": "2",
        "app_install_overwrite": [
            "nextcloud-aio",
            "facerecognition"
        ],
        "log_type": "file",
        "logfile": "\/var\/www\/html\/data\/nextcloud.log",
        "log_rotate_size": "10485760",
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "enabledPreviewProviders": {
            "1": "OC\\Preview\\Image",
            "2": "OC\\Preview\\MarkDown",
            "3": "OC\\Preview\\MP3",
            "4": "OC\\Preview\\TXT",
            "5": "OC\\Preview\\OpenDocument",
            "6": "OC\\Preview\\Movie",
            "7": "OC\\Preview\\Krita"
        },
        "enable_previews": true,
        "upgrade.disable-web": true,
        "mail_smtpmode": "smtp",
        "trashbin_retention_obligation": "auto, 30",
        "versions_retention_obligation": "auto, 30",
        "activity_expire_days": "30",
        "simpleSignUpLink.shown": false,
        "share_folder": "\/Shared",
        "one-click-instance.link": "https:\/\/nextcloud.com\/all-in-one\/",
        "upgrade.cli-upgrade-link": "https:\/\/github.com\/nextcloud\/all-in-one\/discussions\/2726",
        "allow_local_remote_servers": true,
        "davstorage.request_timeout": 3600,
        "htaccess.RewriteBase": "\/",
        "dbpersistent": false,
        "files_external_allow_create_new_local": false,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - calendar: 4.6.5
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contacts: 5.5.1
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - deck: 1.12.2
  - drawio: 3.0.2
  - encryption: 2.16.0
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_3dmodelviewer: 0.0.12
  - files_external: 1.20.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - integration_deepl: 1.1.2
  - integration_github: 2.0.6
  - integration_openai: 1.2.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - maps: 1.3.1
  - nextcloud-aio: 0.4.0
  - nextcloud_announcements: 1.17.0
  - notes: 4.9.2
  - notifications: 2.16.0
  - notify_push: 0.6.9
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recognize: 6.0.1
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - richdocuments: 8.3.1
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - spreed: 18.0.3
  - support: 1.11.0
  - survey_client: 1.16.0
  - systemtags: 1.18.0
  - tasks: 0.15.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_totp: 10.0.0-beta.2
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - bruteforcesettings: 2.8.0
  - suspicious_login: 6.0.0
  - user_ldap: 1.19.0 (installed 1.19.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"zrnIVrlXpiyFW2SMF5PV","level":3,"time":"2024-02-18T12:15:22+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/hyoretsu/@UFPB/","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"zrnIVrlXpiyFW2SMF5PV","level":3,"time":"2024-02-18T12:15:22+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/hyoretsu/@UFPB/","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"zrnIVrlXpiyFW2SMF5PV","level":3,"time":"2024-02-18T12:15:22+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/hyoretsu/@UFPB/","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"zrnIVrlXpiyFW2SMF5PV","level":3,"time":"2024-02-18T12:15:22+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/hyoretsu/@UFPB/","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"zrnIVrlXpiyFW2SMF5PV","level":3,"time":"2024-02-18T12:15:22+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/hyoretsu/@UFPB/","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"zrnIVrlXpiyFW2SMF5PV","level":3,"time":"2024-02-18T12:15:22+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/hyoretsu/@UFPB/","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"zrnIVrlXpiyFW2SMF5PV","level":3,"time":"2024-02-18T12:15:22+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/hyoretsu/@UFPB/","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"Bo1VAT5cWhC8JcTpNxh1","level":3,"time":"2024-02-18T12:17:25+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/webdav","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"Bo1VAT5cWhC8JcTpNxh1","level":3,"time":"2024-02-18T12:17:25+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/webdav","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"Bo1VAT5cWhC8JcTpNxh1","level":3,"time":"2024-02-18T12:17:25+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/webdav","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"Bo1VAT5cWhC8JcTpNxh1","level":3,"time":"2024-02-18T12:17:25+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/webdav","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"Bo1VAT5cWhC8JcTpNxh1","level":3,"time":"2024-02-18T12:17:25+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/webdav","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"Bo1VAT5cWhC8JcTpNxh1","level":3,"time":"2024-02-18T12:17:25+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/webdav","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"Bo1VAT5cWhC8JcTpNxh1","level":3,"time":"2024-02-18T12:17:25+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/webdav","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"Bo1VAT5cWhC8JcTpNxh1","level":3,"time":"2024-02-18T12:17:25+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/webdav","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"Bo1VAT5cWhC8JcTpNxh1","level":3,"time":"2024-02-18T12:17:25+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/webdav","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"Bo1VAT5cWhC8JcTpNxh1","level":3,"time":"2024-02-18T12:17:25+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/webdav","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"Bo1VAT5cWhC8JcTpNxh1","level":3,"time":"2024-02-18T12:17:25+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/webdav","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"Bo1VAT5cWhC8JcTpNxh1","level":3,"time":"2024-02-18T12:17:25+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/webdav","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"cTTiTDrNCtM0MEEfkauL","level":3,"time":"2024-02-18T12:18:30+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/webdav","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"cTTiTDrNCtM0MEEfkauL","level":3,"time":"2024-02-18T12:18:30+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/webdav","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"cTTiTDrNCtM0MEEfkauL","level":3,"time":"2024-02-18T12:18:30+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/webdav","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"cTTiTDrNCtM0MEEfkauL","level":3,"time":"2024-02-18T12:18:30+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/webdav","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"cTTiTDrNCtM0MEEfkauL","level":3,"time":"2024-02-18T12:18:30+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/webdav","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"cTTiTDrNCtM0MEEfkauL","level":3,"time":"2024-02-18T12:18:30+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/webdav","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"cTTiTDrNCtM0MEEfkauL","level":3,"time":"2024-02-18T12:18:30+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/webdav","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"cTTiTDrNCtM0MEEfkauL","level":3,"time":"2024-02-18T12:18:30+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/webdav","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"cTTiTDrNCtM0MEEfkauL","level":3,"time":"2024-02-18T12:18:30+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/webdav","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"cTTiTDrNCtM0MEEfkauL","level":3,"time":"2024-02-18T12:18:30+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/webdav","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"cTTiTDrNCtM0MEEfkauL","level":3,"time":"2024-02-18T12:18:30+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/webdav","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"cTTiTDrNCtM0MEEfkauL","level":3,"time":"2024-02-18T12:18:30+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/webdav","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"6R9HvYsR4Dvy0yLG1xR3","level":3,"time":"2024-02-18T12:19:08+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"GET","url":"/remote.php/dav/files/hyoretsu/.Hello/JAV/SSNI-890.mp4","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"6R9HvYsR4Dvy0yLG1xR3","level":3,"time":"2024-02-18T12:19:08+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"GET","url":"/remote.php/dav/files/hyoretsu/.Hello/JAV/SSNI-890.mp4","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"6R9HvYsR4Dvy0yLG1xR3","level":3,"time":"2024-02-18T12:19:08+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"GET","url":"/remote.php/dav/files/hyoretsu/.Hello/JAV/SSNI-890.mp4","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"6R9HvYsR4Dvy0yLG1xR3","level":3,"time":"2024-02-18T12:19:08+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"GET","url":"/remote.php/dav/files/hyoretsu/.Hello/JAV/SSNI-890.mp4","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"OYhRYe0OuL4n2lrf0CL5","level":3,"time":"2024-02-18T12:20:27+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"GET","url":"/remote.php/dav/files/hyoretsu/.Hello/JAV/SSNI-916.mp4","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"OYhRYe0OuL4n2lrf0CL5","level":3,"time":"2024-02-18T12:20:27+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"GET","url":"/remote.php/dav/files/hyoretsu/.Hello/JAV/SSNI-916.mp4","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"OYhRYe0OuL4n2lrf0CL5","level":3,"time":"2024-02-18T12:20:27+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"GET","url":"/remote.php/dav/files/hyoretsu/.Hello/JAV/SSNI-916.mp4","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"OYhRYe0OuL4n2lrf0CL5","level":3,"time":"2024-02-18T12:20:27+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"GET","url":"/remote.php/dav/files/hyoretsu/.Hello/JAV/SSNI-916.mp4","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:38+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:38+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:38+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:38+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:38+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:38+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:38+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:38+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:38+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:38+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:38+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:38+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TCuMoJfyYiq5rA1FeNUw","level":3,"time":"2024-02-18T12:21:39+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"--","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TgzoEHndKYeZ9GDPOq0D","level":3,"time":"2024-02-18T12:24:35+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"GET","url":"/remote.php/dav/files/hyoretsu/.Hello/JAV/SW-304.mp4","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TgzoEHndKYeZ9GDPOq0D","level":3,"time":"2024-02-18T12:24:35+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"GET","url":"/remote.php/dav/files/hyoretsu/.Hello/JAV/SW-304.mp4","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TgzoEHndKYeZ9GDPOq0D","level":3,"time":"2024-02-18T12:24:35+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"GET","url":"/remote.php/dav/files/hyoretsu/.Hello/JAV/SW-304.mp4","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"TgzoEHndKYeZ9GDPOq0D","level":3,"time":"2024-02-18T12:24:35+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"GET","url":"/remote.php/dav/files/hyoretsu/.Hello/JAV/SW-304.mp4","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"Y5pqWDJSXM7ynq5AzhWz","level":3,"time":"2024-02-18T12:25:35+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"GET","url":"/remote.php/dav/files/hyoretsu/.Hello/JAV/WANZ-956.mp4","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"Y5pqWDJSXM7ynq5AzhWz","level":3,"time":"2024-02-18T12:25:35+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"GET","url":"/remote.php/dav/files/hyoretsu/.Hello/JAV/WANZ-956.mp4","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"Y5pqWDJSXM7ynq5AzhWz","level":3,"time":"2024-02-18T12:25:35+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"GET","url":"/remote.php/dav/files/hyoretsu/.Hello/JAV/WANZ-956.mp4","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"Y5pqWDJSXM7ynq5AzhWz","level":3,"time":"2024-02-18T12:25:35+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"GET","url":"/remote.php/dav/files/hyoretsu/.Hello/JAV/WANZ-956.mp4","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"6uri7ngi0XScOfbb5L1A","level":3,"time":"2024-02-18T12:26:56+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/hyoretsu/","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"6uri7ngi0XScOfbb5L1A","level":3,"time":"2024-02-18T12:26:56+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/hyoretsu/","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"6uri7ngi0XScOfbb5L1A","level":3,"time":"2024-02-18T12:26:56+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/hyoretsu/","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"6uri7ngi0XScOfbb5L1A","level":3,"time":"2024-02-18T12:26:56+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/hyoretsu/","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"6uri7ngi0XScOfbb5L1A","level":3,"time":"2024-02-18T12:26:56+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/hyoretsu/","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"6uri7ngi0XScOfbb5L1A","level":3,"time":"2024-02-18T12:26:56+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/hyoretsu/","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"6uri7ngi0XScOfbb5L1A","level":3,"time":"2024-02-18T12:26:56+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/hyoretsu/","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"6uri7ngi0XScOfbb5L1A","level":3,"time":"2024-02-18T12:26:56+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/hyoretsu/","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"6uri7ngi0XScOfbb5L1A","level":3,"time":"2024-02-18T12:26:56+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/hyoretsu/","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"6uri7ngi0XScOfbb5L1A","level":3,"time":"2024-02-18T12:26:56+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/hyoretsu/","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"6uri7ngi0XScOfbb5L1A","level":3,"time":"2024-02-18T12:26:56+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/hyoretsu/","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
{"reqId":"6uri7ngi0XScOfbb5L1A","level":3,"time":"2024-02-18T12:26:56+00:00","remoteAddr":"172.21.0.1","user":"hyoretsu","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/hyoretsu/","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#222","userAgent":"Mozilla/5.0 (Windows) mirall/3.12.0stable-Win64 (build 20240213) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"28.0.2.5","data":{"app":"PHP"}}
```

### Additional info

Using Caddy and here's the file: https://drive.google.com/file/d/1YiYQhWQxqOA8fBGJPQhrWT2snHOUeJix/view?usp=sharing

### LINKED ISSUE #45082: [Bug]: Nextcloud Hub 8, copying files to Object Storage configured as Primary Storage isn't reliable
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When you copy a hierarchy of folders via browser _–or even a single folder with nested subfolders inside–_ all folders/files are successfully copied and usable too but, very often but not always, folder sizes are shown incorrectly (i.e. 0 bytes) moreover  the copy is unexpectedly halted too. This makes copying to external storage as primary storage impossible. I didn't test copying to other external storages. 
One and only one error is costantly reported:
<Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#224>

### Steps to reproduce

1. Set an External Storage (Amazon s3), with multipart enabled, as Primary Storage
2. From your PC/Mac⁽*⁾  copy a folder containing a hierarchy of subfolders and files
3. This is the result in the 90% of cases:
Screenshot 2024-04-27 at 21 48 21
but, actually those empty folders contain other folders and files:
Screenshot 2024-04-27 at 21 48 47
4. and..., often, the copy is stopped 

⁽*⁾ a Mac in my case

### Expected behavior

I would like the batch of files and folders to be entirely copied and the metadata to be evaluated correctly.

### Installation method

Official All-in-One appliance

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "one-click-instance": true,
        "one-click-instance.user-limit": 100,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "appsallowlist": false,
        "check_data_directory_permissions": false,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "overwritehost": "*****.*****.com",
        "overwriteprotocol": "https",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
"trusted_domains": [
            "localhost",
            "****.****.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "29.0.0.19",
        "overwrite.cli.url": "https:\/\/****.****.com\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "updatedirectory": "\/nc-updater",
        "loglevel": 3,
        "app_install_overwrite": [
            "nextcloud-aio"
        ],
        "log_type": "file",
        "logfile": "\/var\/www\/html\/data\/nextcloud.log",
        "log_rotate_size": "10485760",
        "log.condition": {
            "apps": [
                "admin_audit"
    ]
        },
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "enabledPreviewProviders": {
            "1": "OC\\Preview\\Image",
            "2": "OC\\Preview\\MarkDown",
            "3": "OC\\Preview\\MP3",
            "4": "OC\\Preview\\TXT",
            "5": "OC\\Preview\\OpenDocument",
            "6": "OC\\Preview\\Movie",
            "7": "OC\\Preview\\Krita",
            "0": "OC\\Preview\\Imaginary"
        },
        "enable_previews": true,
        "upgrade.disable-web": true,
        "mail_smtpmode": "smtp",
        "trashbin_retention_obligation": "auto, 30",
        "versions_retention_obligation": "auto, 30",
        "activity_expire_days": "30",
        "simpleSignUpLink.shown": false,
        "share_folder": "\/Shared",
        "one-click-instance.link": "https:\/\/nextcloud.com\/all-in-one\/",
        "upgrade.cli-upgrade-link": "https:\/\/github.com\/nextcloud\/all-in-one\/discussions\/2726",
        "maintenance_window_start": 100,
        "allow_local_remote_servers": true,
        "davstorage.request_timeout": 3600,
"htaccess.RewriteBase": "\/",
        "dbpersistent": false,
        "auth.bruteforce.protection.enabled": true,
        "ratelimit.protection.enabled": true,
        "files_external_allow_create_new_local": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "preview_imaginary_url": "***REMOVED SENSITIVE VALUE***",
        "preview_imaginary_key": "e98427df8dc02767b14ec376d116129d156a79af2311ba2c",
        "objectstore": {
            "class": "\\OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "bucket": "***REMOVED SENSITIVE VALUE***",
                "key": "***REMOVED SENSITIVE VALUE***",
                "secret": "***REMOVED SENSITIVE VALUE***",
                "use_ssl": true,
                "hostname": "***REMOVED SENSITIVE VALUE***"
            }
        },
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "defaultapp": "dashboard,files,mail,calendar,contacts,spreed",
        "auth.bruteforce.protection.enabled": true,
        "ratelimit.protection.enabled": true,
        "files_external_allow_create_new_local": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "preview_imaginary_url": "***REMOVED SENSITIVE VALUE***",
        "preview_imaginary_key": "e98427df8dc02767b14ec376d116129d156a79af2311ba2c",
        "objectstore": {
            "class": "\\OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "bucket": "***REMOVED SENSITIVE VALUE***",
                "key": "***REMOVED SENSITIVE VALUE***",
                "secret": "***REMOVED SENSITIVE VALUE***",
                "use_ssl": true,
                "hostname": "***REMOVED SENSITIVE VALUE***"
            }
        },
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "defaultapp": "dashboard,files,mail,calendar,contacts,spreed"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.21.1
  - admin_audit: 1.19.0
  - app_api: 2.5.0
  - approval: 1.2.0
  - calendar: 4.7.1
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - comments: 1.19.0
  - contacts: 6.0.0
  - contactsinteraction: 1.10.0
  - dashboard: 7.9.0
  - dav: 1.30.1
  - deck: 1.13.0
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.0
  - files_accesscontrol: 1.19.0
  - files_automatedtagging: 1.19.0
  - files_confidential: 2.1.0
  - files_downloadlimit: 2.0.0
  - files_external: 1.21.0
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_retention: 1.18.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - firstrunwizard: 2.18.0
  - forms: 4.2.3
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - mail: 3.6.0
  - nextcloud-aio: 0.5.0
  - nextcloud_announcements: 1.18.0
  - notes: 4.10.0
  - notifications: 2.17.0
  - notify_push: 0.6.10
  - oauth2: 1.17.0
  - password_policy: 1.19.0
  - photos: 2.5.0
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - related_resources: 1.4.0
  - richdocuments: 8.4.0
  - richdocumentscode: 24.4.103
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - spreed: 19.0.0
  - stt_helper: 1.1.1
  - support: 1.12.0
  - survey_client: 1.17.0
  - suspicious_login: 7.0.0
  - systemtags: 1.19.0
  - tables: 0.7.0
  - text: 3.10.0
  - theming: 2.4.0
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - related_resources: 1.4.0
  - richdocuments: 8.4.0
  - richdocumentscode: 24.4.103
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - spreed: 19.0.0
  - stt_helper: 1.1.1
  - support: 1.12.0
  - survey_client: 1.17.0
  - suspicious_login: 7.0.0
  - systemtags: 1.19.0
  - tables: 0.7.0
  - text: 3.10.0
  - theming: 2.4.0
  - twofactor_backupcodes: 1.18.0
  - user_status: 1.9.0
  - viewer: 2.3.0
  - weather_status: 1.9.0
  - workflowengine: 2.11.0
Disabled:
  - bruteforcesettings: 2.9.0
  - encryption: 2.17.0
  - recommendations: 2.1.0 (installed 2.1.0)
  - tasks: 0.15.0
  - twofactor_totp: 11.0.0-dev (installed 11.0.0-dev)
  - user_ldap: 1.20.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"vfjSUwVApKFg9XMY67Cl","level":3,"time":"2024-04-27T18:32:49+00:00","remoteAddr":"***.***.***.***","user":"Stefano","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/Stefano/OLD-Storico/Progetti%20CLOSED/300_LB_myDanishContainers/","message":"Array to string conversion at /var/www/html/lib/private/Files/Cache/Scanner.php#224","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36","version":"29.0.0.19","data":{"app":"PHP"}}
. . .
```

### Additional info

Same behaviours with Safari 17.4 and [unsupported] Brave 1.42.95

### PR DESCRIPTION
**Pull request by joshtrichards**
* Resolves: #43408 
* Also likely fixes #45082 and #43642

## Summary

`array_diff_assoc()` doesn't  support multidimensional arrays on its own (and, when attempted, it internally casts any embedded array elements to strings to attempt to compare them - not only generating warnings like "Array to string conversion" but also then overlooking differences).

_But sometimes we're passing it a multidimensional array._

I *think* the reason this became a new problem in v28 is because the `metadata` (#40761 / etc) gets embedded as a second level array here. It happens that triggering a scan on an Object Store is one way to trigger this code path just right to see the behavior found in #43408. (In other words: there *may* be other cases where an n-level array ends up here, but I don't know of one off-hand; and this should accommodate any of them in any case). 

## TODO

- Housekeeping 
  - [x] Fix code formatting
  - [x] Fix docblock
  - [x] Fix commits (squash, change message)
- [ ] Confirm whether also fixes/closes #45082 
- [ ] Confirm whether also fixes/closes #43642

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [x] Screenshots before/after for front-end changes
- [x] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Comment by solracsf** [comment]
Another potential approach: iterating over each element in the `$data` array and then compares each nested element individually, instead of serialize/unserialize _(**not tested** though, may need some adjustements)_.

```
$newData = [];
foreach ($data as $key => $value) {
    if (is_array($value)) {
        if (!array_key_exists($key, $cacheData) || !is_array($cacheData[$key])) {
            $newData[$key] = $value;
        } else {
            $nestedDiff = [];
            foreach ($value as $nestedKey => $nestedValue) {
                if (!array_key_exists($nestedKey, $cacheData[$key]) || $cacheData[$key][$nestedKey] !== $nestedValue) {
                    $nestedDiff[$nestedKey] = $nestedValue;
                }
            }
            if (!empty($nestedDiff)) {
                $newData[$key] = $nestedDiff;
            }
        }
    } else {
        if (!array_key_exists($key, $cacheData) || $cacheData[$key] !== $value) {
            $newData[$key] = $value;
        }
    }
}
```

**Review by lavigne958 — APPROVED** [review]
I tried this fix on my instance and it works. no more error logs from `array_diff_assoc`.

**Review by artonge — APPROVED** [review]
Thanks for the investigation and lengthy explanation. It makes sense IMO. :)

**Comment by joshtrichards** [comment]
@solracsf Are you aware of any pros to that approach?

**Comment by hyoretsu** [comment]
Please, merge this commit, it makes NextCloud usable again without manually applying it.

**Comment by come-nc** [comment]
I’d feel better with a recursive comparison than serialization.

**Comment by icewind1991** [comment]
[`array-diff-uassoc`](https://www.php.net/manual/en/function.array-diff-uassoc.php) can be used to customize how the comparison is done.

I'm not a fan of round-tripping data through serialize if we can avoid it

**Comment by ahcm** [comment]
Sorry, if this in the wild, I just skimmed through the code.

Is it really worthwhile to only updating the diff?
Whatever DB is behind will do that probably anyways or be faster writing all.

**Comment by compuguy** [comment]
> Sorry, if this in the wild, I just skimmed through the code.
> 
> Is it really worthwhile to only updating the diff? Whatever DB is behind will do that probably anyways or be faster writing all.

I don't know. Honestly the patch in its current form works with the latest release of Nextcloud 28. I understand it could add some overhead, but I can also see this resolving an annoying issue that shouldn't fill my logs.....

**Comment by DaanSelen** [comment]
Is this patch slated to release for version 30 or any minor patches for 29?

**Comment by joshtrichards** [comment]
Reimplemented w/o serialization. Tests reasonably in my test bed. Mostly housekeeping items left.

> Is this patch slated to release for version 30 or any minor patches for 29?

It'll likely make it into the next monthly maintenance releases for v27/v28/v29 (well before v30 is formally published).

File: lib/private/Files/Cache/Scanner.php [hunk 1]
```diff
@@ -369,6 +370,64 @@ public function scan($path, $recursive = self::SCAN_RECURSIVE, $reuse = -1, $loc
...
+	 * Comparisons are strict just like array_diff_assoc
+	 * Order of keys/values does not matter
+	 *
+  	 * @param array $array1
+	 * @param array|? $array2
+	 * @return array with the differences between $array1 and $array1
+  	 * @throws \InvalidArgumentException if $array1 isn't an actual array 
+   	 *
+	 */
+	protected function array_diff_assoc_multi($array1, $array2) {
```
Comment (come-nc) [inline lib/private/Files/Cache/Scanner.php:388]:
```suggestion
	protected function array_diff_assoc_multi(array $array1, mixed $array2): array {
```

File: lib/private/Files/Cache/Scanner.php [hunk 2]
```diff
@@ -369,6 +370,64 @@ public function scan($path, $recursive = self::SCAN_RECURSIVE, $reuse = -1, $loc
...
+			if (!array_key_exists($key, $array2)) {
+        		$result[$key] = $value;
+				continue;
+			}
+		
+			// if $array2's value for the same key is different, that's a result
+			if ($array2[$key] !== $value && !is_array($value)) {
+        		$result[$key] = $value;
+				continue;
+			}
```
Comment (come-nc) [inline lib/private/Files/Cache/Scanner.php:413]: This is the same test that on 422 but with strict comparison, no?

**Review by lavigne958 — APPROVED** [review]
This code has been running on my instance for the past 12h and not a single line of error has raised, it works fine :+1:

File: lib/private/Files/Cache/Scanner.php (hunk 2 above)
Comment (joshtrichards) [reply lib/private/Files/Cache/Scanner.php:413]: Indeed. Oops. L421-L426 are extraneous. Once I made this recursive I was looking at what values were still popping out at the end and cleaned it all up, but seems I overlooked those couple lines. I can't find any legitimate results that will ever flow flow to L421.

Comment (joshtrichards) [reply lib/private/Files/Cache/Scanner.php]: Cleaned up. Took care of all other items as well.

**Review by come-nc — APPROVED** [review]
