### PR TITLE
Fix illegible text color in columns Size and Modified on dark theme

### LINKED ISSUE #11441: Dark Theme Has Illegible Text Color for File Sizes in MegaBytes and GigaBytes
### Steps to reproduce
1. Enable Dark Theme
2. Have Files/Directories that Have File Sizes in MegaBytes or Gigabytes 
3. Login and view files/directories

### Expected behaviour
Text should be formatted in grey to match the color of directory/file sizes reported in KiloBytes.  

### Actual behaviour
Text is rendered in black, making it illegible in the dark theme.  The issue is clear in the screenshot I illustrated.

nc_bug1
nc_bug2

### Server configuration

**Operating system**: FreeBSD

**Web server:** Nginx

**Database:** Postgresql

**PHP version:** 7.1

**Nextcloud version:** 14.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from version 14.0

**Where did you install Nextcloud from:** FreeBSD ports

### PR DESCRIPTION
**Pull request by lex111**
Resolves #11441

image

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
Very simple, I really like it :)

File: lib/private/Template/JSConfigHelper.php [hunk 1]
```diff
@@ -260,6 +260,7 @@ public function getConfig() {
 				'shortFooter' => $this->defaults->getShortFooter(),
 				'longFooter' => $this->defaults->getLongFooter(),
 				'folder' => \OC_Util::getTheme(),
+				'themeName' => $this->config->getUserValue($uid, 'accessibility', 'theme', false),
```
Comment (juliushaertl) [inline lib/private/Template/JSConfigHelper.php]: I'm not sure if we should add more app dependencies into the server. Also themeName is kind of confusing, since a theme is actually something different.

@skjnldsv Maybe we can make the accessibility app expose a global namespace for that usecase, similar to the theming app: https://github.com/nextcloud/server/blob/master/apps/theming/lib/Controller/ThemingController.php#L434-L451

Something like:
```
OCA.Accessibility.Config = {
    theme: 'dark'
}
```

**Review by juliusknorr — CHANGES_REQUESTED** [review]

File: lib/private/Template/JSConfigHelper.php (hunk 1 above)
Comment (lex111) [reply lib/private/Template/JSConfigHelper.php]: @juliushaertl I can do this, i.e. add `theme` property in `OCA.Theming`?

Comment (juliushaertl) [reply lib/private/Template/JSConfigHelper.php]: It should be in the accessibility app, since the theming app could be disabled and we still want accessibility to work.

Comment (lex111) [reply lib/private/Template/JSConfigHelper.php]: You mean the `AccessibilityController` controller?

Comment (lex111) [reply lib/private/Template/JSConfigHelper.php]: Hi @juliushaertl 

I reworked my PR the way you wanted, can you look please?

**Comment by lex111** [comment]
Hi guys, please watch this PR :smiley:

**Review by jancborchardt — APPROVED** [review]
Looks good to me, great work @lex111!

**Review by juliusknorr — APPROVED** [review]

**Comment by lex111** [comment]
@juliushaertl done :heavy_check_mark:

**Comment by lex111** [comment]
friendly ping @denismosolov I'm not late? :smile:

**Comment by skjnldsv** [comment]
> Yes, fine by me now. Does this also work for you @skjnldsv ?

Good for me ;)

**Comment by MorrisJobke** [comment]
> Good for me ;)

Then press also the green button ;)

**Comment by denismosolov** [comment]
> friendly ping @denismosolov I'm not late?

You're rock!
