### PR TITLE
Remove wrong entry in admin_settings that causes 500

### LINKED ISSUE #5067: OCP\AppFramework\QueryException: Could not resolve OCA\External\Settings\Admin
### Steps to reproduce
1. Enable External Storages
2. Go to settings and Enable then Disable it for users

### Expected behaviour
No error

### Actual behaviour
``` 
OCP\AppFramework\QueryException: Could not resolve OCA\External\Settings\Admin! Class OCA\External\Settings\Admin does not exist
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 117: OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\External\\Se...')
/var/www/nextcloud/lib/private/ServerContainer.php - line 132: OC\AppFramework\Utility\SimpleContainer->query('OCA\\External\\Se...')
/var/www/nextcloud/lib/private/Settings/Manager.php - line 261: OC\ServerContainer->query('OCA\\External\\Se...')
/var/www/nextcloud/lib/private/Settings/Manager.php - line 352: OC\Settings\Manager->query('OCA\\External\\Se...')
/var/www/nextcloud/settings/Controller/AdminSettingsController.php - line 138: OC\Settings\Manager->getAdminSettings('additional')
/var/www/nextcloud/settings/Controller/AdminSettingsController.php - line 72: OC\Settings\Controller\AdminSettingsController->getNavigationParameters('server')
[internal function] OC\Settings\Controller\AdminSettingsController->index('server')
/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OC\Settings\Controller\AdminSettingsController), 'index')
/var/www/nextcloud/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Settings\Controller\AdminSettingsController), 'index')
/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OC\\Settings\\Con...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/var/www/nextcloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/var/www/nextcloud/lib/base.php - line 1000: OC\Route\Router->match('/settings/admin')
/var/www/nextcloud/index.php - line 40: OC handleRequest()
{main}
```

### Server configuration
**Operating system**: Linux cloud.techandme.se 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64

**Web server:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 5.7.18

**PHP version:** 7.0.15-0ubuntu0.16.04.4
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, intl, json, ldap, exif, mcrypt, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 12.0.0 - 12.0.0.29

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** 

**Signing status:**
<details>
	<summary>Signing status</summary>

```
{
    "core": {
        "INVALID_HASH": {
            ".htaccess": {
                "expected": "da8e0075f23227b107fc705aa1b20378107d3a1c195d96ed13e5f4f25c38d6c660aab75be183ae5799a4ff7eae0ea739a14c944430ee8bb9e9a824235aa136eb",
                "current": "e0da651dd6f73f11ff3b792867ccd3fcbfa61dfe18f90b9705638797d982d5597b830a180ad13c73d0fc8a2f246d34361d1c57d45c1e2dd0ab8fe3cbaaaa5281"
            }
        }
    },
    "qownnotesapi": {
        "EXCEPTION": {
            "class": "OC\\IntegrityCheck\\Exceptions\\InvalidSignatureException",
            "message": "Certificate is not valid."
        }
    }
}
```

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>
```
Enabled:
 - activity: 2.5.2
 - admin_notifications: 1.0.0
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_downloadactivity: 1.1.1
 - files_external: 1.3.0
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.6.4
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - ocsms: 1.12.0
 - ownnote: 1.08
 - password_policy: 1.2.2
 - previewgenerator: 1.0.6
 - provisioning_api: 1.2.0
 - qownnotesapi: 17.5.0
 - richdocuments: 1.12.28
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - socialsharing_diaspora: 1.0.1
 - socialsharing_email: 1.0.1
 - socialsharing_facebook: 1.0.1
 - socialsharing_googleplus: 1.0.1
 - socialsharing_twitter: 1.0.1
 - spreed: 2.0.1
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - twofactor_totp: 1.3.0
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0

Disabled:
 - admin_audit
 - encryption
 - external
 - files_accesscontrol
 - files_automatedtagging
 - files_retention
 - user_external
 - user_ldap
 - user_saml
```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "updatechecker": false,
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "192.168.4.111",
        "cloud.techandme.se",
        "office.techandme.se"
    ],
    "datadirectory": "\/var\/ncdata",
    "overwrite.cli.url": "https:\/\/cloud.techandme.se\/",
    "dbtype": "mysql",
    "version": "12.0.0.29",
    "dbname": "owncloud_db",
    "dbhost": "localhost",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "Europe\/Stockholm",
    "installed": true,
    "instanceid": "oc7aii0tkiol",
    "appstore.experimental.enabled": "true",
    "mail_smtpmode": "smtp",
    "mail_smtpauth": 1,
    "mail_smtpport": "587",
    "mail_smtphost": "smtp.gmail.com",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "no-reply",
    "mail_domain": "techandme.se",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "allowZipDownload": true,
    "session_lifetime": 1800,
    "forcessl": true,
    "logfile": "\/var\/log\/nfs-share\/nextcloud.log",
    "loglevel": 2,
    "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": true,
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "\/var\/run\/redis\/redis.sock",
        "port": 0,
        "timeout": 0,
        "dbindex": 0
    },
    "trusted_proxies": [
        [
            "192.168.4.201"
        ]
    ],
    "forwarded_for_headers": [
        "HTTP_X_FORWARDED",
        "HTTP_FORWARDED_FOR"
    ],
    "maintenance": false,
    "mail_smtpsecure": "tls",
    "htaccess.RewriteBase": "\/",
    "theme": "",
    "updater.release.channel": "stable",
    "mysql.utf8mb4": true
}
```
</details>

**Are you using external storage, if yes which one:** Array
(
    [0] => \OC\Files\Storage\Local
    [1] => \OCA\Files_External\Lib\Storage\FTP
    [2] => \OC\Files\Storage\DAV
    [3] => \OCA\Files_External\Lib\Storage\OwnCloud
    [4] => \OCA\Files_External\Lib\Storage\SFTP
    [5] => \OCA\Files_External\Lib\Storage\AmazonS3
    [6] => \OCA\Files_External\Lib\Storage\Dropbox
    [7] => \OCA\Files_External\Lib\Storage\Google
    [8] => \OCA\Files_External\Lib\Storage\Swift
    [9] => \OCA\Files_External\Lib\Storage\SFTP
    [10] => \OCA\Files_External\Lib\Storage\SMB
    [11] => \OCA\Files_External\Lib\Storage\SMB
)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/58.0.3029.110 Chrome/58.0.3029.110 Safari/537.36

**Operating system:**

#### Web server error log
<details>
	<summary>Web server error log</summary>
	```
	Insert your webserver log here
	```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
	<summary>Nextcloud log</summary>
	```
	Insert your Nextcloud log here
	```
</details>

#### Browser log
<details>
	<summary>Browser log</summary>
	```
	Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
	```
</details>

### LINKED ISSUE #5313: Nexcloud 11 upgrade to 12 workaround
After upgrade from Nexcloud 11 to 12 version with updater. And admin panel could not be reached. Gave Internal Server Error.

Nexcloud:
  - installed: true
  - version: 12.0.0.29
  - versionstring: 12.0.0
  - edition:

System:
  - Ubuntu 16.04.2 LTS
  - PHP 7.0.18-0ubuntu0.16.04.1
  - 10.0.29-MariaDB
  - Apache/2.4.18 (Ubuntu)

Pretty error format:

> Type: OCP\AutoloadNotAllowedException
> Code: 0
> Message: Autoload path not allowed: /var/www/nextcloud/apps/onlyoffice/lib/adminsettings.php
>  File: /var/www/nextcloud/lib/autoloader.php
> 

Not so pretty:

> {"reqId":"ckJflwhjUkoQFInqyVq6","level":3,"time":"June 09, 2017 08:48:28","remoteAddr":"<IP-REMOVED-FROM-PUBLIC>","user":"administrator","app":"index","method":"GET","url":"\/index.php\/settings\/admin","message":"Exception: {\"Exception\":\"OCP\\\\AutoloadNotAllowedException\",\"Message\":\"Autoload path not allowed: \\\/var\\\/www\\\/nextcloud\\\/apps\\\/onlyoffice\\\/lib\\\/adminsettings.php\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/autoloader.php(158): OC\\\\Autoloader->isValidPath('\\\/var\\\/www\\\/nextcl...')\\n#1 [internal function]: OC\\\\Autoloader->load('OCA\\\\\\\\Onlyoffice\\\\\\\\...')\\n#2 [internal function]: spl_autoload_call('OCA\\\\\\\\Onlyoffice\\\\\\\\...')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(94): ReflectionClass->__construct('OCA\\\\\\\\Onlyoffice\\\\\\\\...')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(117): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OCA\\\\\\\\Onlyoffice\\\\\\\\...')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/ServerContainer.php(132): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OCA\\\\\\\\Onlyoffice\\\\\\\\...')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Settings\\\/Manager.php(261): OC\\\\ServerContainer->query('OCA\\\\\\\\Onlyoffice\\\\\\\\...')\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Settings\\\/Manager.php(352): OC\\\\Settings\\\\Manager->query('OCA\\\\\\\\Onlyoffice\\\\\\\\...')\\n#8 \\\/var\\\/www\\\/nextcloud\\\/settings\\\/Controller\\\/AdminSettingsController.php(138): OC\\\\Settings\\\\Manager->getAdminSettings('server')\\n#9 \\\/var\\\/www\\\/nextcloud\\\/settings\\\/Controller\\\/AdminSettingsController.php(72): OC\\\\Settings\\\\Controller\\\\AdminSettingsController->getNavigationParameters('server')\\n#10 [internal function]: OC\\\\Settings\\\\Controller\\\\AdminSettingsController->index('server')\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#12 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\AdminSettingsController), 'index')\\n#13 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\AdminSettingsController), 'index')\\n#14 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Settings\\\\\\\\Con...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#15 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#16 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#17 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1000): OC\\\\Route\\\\Router->match('\\\/settings\\\/admin')\\n#18 \\\/var\\\/www\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#19 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/autoloader.php\",\"Line\":134}","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.110 Safari\/537.36","version":"12.0.0.29"}

Workaround:
 DELETE FROM `oc_admin_settings` WHERE `class` LIKE '%Onlyoffice%'

seems that it fixed the issue for now. But might be inturesting to take a look. (I have a db dump when it didn't work). Hope it is useful.

### PR DESCRIPTION
**Pull request by MorrisJobke**
* having a stale entry like this in the oc_admin_settings table:

```sql
INSERT INTO oc_admin_settings(class, section, priority)
VALUES ('OCA\\OnlyOffice\\AdminSettings', 'server', 1);
```

* also have the only office app code in your apps directory but disable the app
* open the admin settings
* actual: 500 internal server error like in #5313
* expected: load the admin settings

This PR cleans up those stale entries and avoids the 500.

Should we maybe backport this to 12?

Fixes #5313
Fixes #5067

### CODE REVIEW

**Review by icewind1991 — APPROVED** [review]

File: lib/private/Settings/Manager.php [hunk 1]
```diff
@@ -471,6 +472,9 @@ public function getAdminSettings($section) {
 				$settings[$row['priority']][] = $this->query($row['class']);
 			} catch (QueryException $e) {
 				// skip
+			} catch (AutoloadNotAllowedException $e) {
+				// skip error and remove remnant of disabled app
+				$this->mapper->remove(Mapper::TABLE_ADMIN_SETTINGS, $row['class']);
```
Comment (rullzer) [inline lib/private/Settings/Manager.php]: Please log this so we have a trace that it happened.

**Review by rullzer — CHANGES_REQUESTED** [review]

File: lib/private/Settings/Manager.php (hunk 1 above)
Comment (MorrisJobke) [reply lib/private/Settings/Manager.php]: Done

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
Backport in #7455
