### PR TITLE
fix: expect interface, not a specific implementation

### LINKED ISSUE #1068: Can't delete folders while the app is enabled
*Edit by @paulijar: Read the summary below from https://github.com/owncloud/music/issues/1068#issuecomment-1591763499*

*The original post:*

**Fixed disabling the Music app.**

```
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' =>
  array (
    0 => 'cloud.org',
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '26.0.2.1',
  'overwrite.cli.url' => 'https://cloud.org/',
  'htaccess.RewriteBase' => '/',
  'dbname' => 'nextcloud',
  'dbhost' => '127.0.0.1',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => '',
  'default_phone_region' => '3166-2:ES',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'updater.release.channel' => 'stable',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_smtphost' => '',
  'mail_from_address' => '',
  'mail_domain' => '',
  'mail_smtpport' => '465',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtpname' => '',
  'mail_smtppassword' => '',
  'mail_smtpsecure' => 'ssl',
  'updater.secret' => '',
);
```

```
[webdav] Error: TypeError: OC\Files\Cache\QuerySearchHelper::getCachesAndMountPointsForSearch(): Argument #1 ($root) must be of type OC\Files\Node\Root, OC\Files\Node\LazyRoot given, called in /var/www/nextcloud/lib/private/Files/Node/Folder.php on line 237 at <<closure>>

 0. /var/www/nextcloud/lib/private/Files/Node/Folder.php line 237
    OC\Files\Cache\QuerySearchHelper->getCachesAndMountPointsForSearch()
 1. /var/www/nextcloud/lib/private/Files/Node/Folder.php line 291
    OC\Files\Node\Folder->search()
 2. /var/www/nextcloud/apps/music/lib/Utility/Scanner.php line 383
    OC\Files\Node\Folder->searchByMime()
 3. /var/www/nextcloud/apps/music/lib/Hooks/FileHooks.php line 42
    OCA\Music\Utility\Scanner->deleteFolder()
 4. <<closure>>
    OCA\Music\Hooks\FileHooks::deleted()
 5. /var/www/nextcloud/lib/private/Hooks/EmitterTrait.php line 105
    call_user_func_array()
 6. /var/www/nextcloud/lib/private/Hooks/PublicEmitter.php line 40
    OC\Hooks\BasicEmitter->emit()
 7. /var/www/nextcloud/lib/private/Files/Node/Root.php line 143
    OC\Hooks\PublicEmitter->emit()
 8. <<closure>>
    OC\Files\Node\Root->emit()
 9. /var/www/nextcloud/lib/private/Files/Node/LazyFolder.php line 72
    call_user_func_array()
10. /var/www/nextcloud/lib/private/Files/Node/LazyFolder.php line 100
    OC\Files\Node\LazyFolder->__call()
11. /var/www/nextcloud/lib/private/Files/Node/HookConnector.php line 145
    OC\Files\Node\LazyFolder->emit()
12. /var/www/nextcloud/lib/private/legacy/OC_Hook.php line 105
    OC\Files\Node\HookConnector->delete()
13. /var/www/nextcloud/lib/private/Files/View.php line 1295
    OC_Hook::emit()
14. /var/www/nextcloud/lib/private/Files/View.php line 1165
    OC\Files\View->runHooks()
15. /var/www/nextcloud/lib/private/Files/View.php line 351
    OC\Files\View->basicOperation()
16. /var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php line 307
    OC\Files\View->rmdir()
17. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 179
    OCA\DAV\Connector\Sabre\Directory->delete()
18. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 281
    Sabre\DAV\Tree->delete()
19. /var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpDelete()
20. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 472
    Sabre\DAV\Server->emit()
21. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 253
    Sabre\DAV\Server->invokeMethod()
22. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 321
    Sabre\DAV\Server->start()
23. /var/www/nextcloud/apps/dav/lib/Server.php line 366
    Sabre\DAV\Server->exec()
24. /var/www/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
25. /var/www/nextcloud/remote.php line 172
    require_once("/var/www/nextcl ... p")

DELETE /remote.php/dav/files/giou/Obsidiane
from IP by giou at 2023-05-26T21:05:08+00:00
```

### PR DESCRIPTION
**Pull request by blizzz**
* Resolves: https://github.com/owncloud/music/issues/1068

## Summary

- fixes a regression when deleting folders while music app was enabled, for a LazyRoot was passed to this method.

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [ ] Tests ([unit](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#unit-tests), [integration](https://docs.nextcloud.com/server/latest/developer_manual/app_development/tutorial.html#integration-tests), api and/or acceptance) are included
- [X] Screenshots before/after for front-end changes
- [X] Documentation ([manuals](https://github.com/nextcloud/documentation/) or wiki) has been updated or is not required
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by icewind1991 — APPROVED** [review]

File: lib/private/Files/Cache/QuerySearchHelper.php [hunk 1]
```diff
@@ -196,23 +195,31 @@ public function searchInCaches(ISearchQuery $searchQuery, array $caches): array
...
 	/**
-	 * @return array{array<string, ICache>, array<string, IMountPoint>}
+	 * @return array{0?: array<string, ICache>, 1?: array<string, IMountPoint>}
 	 */
-	public function getCachesAndMountPointsForSearch(Root $root, string $path, bool $limitToHome = false): array {
+	public function getCachesAndMountPointsForSearch(IRootFolder $root, string $path, bool $limitToHome = false): array {
 		$rootLength = strlen($path);
-		$mount = $root->getMount($path);
-		$storage = $mount->getStorage();
+		if (method_exists($root, 'getMount')) {
```
Comment (come-nc) [inline lib/private/Files/Cache/QuerySearchHelper.php:202]:
```suggestion
		$storage = null;
		if (method_exists($root, 'getMount')) {
```
Would feel more readable this way.

File: lib/private/Files/Node/Root.php [hunk 2]
```diff
@@ -342,7 +343,7 @@ public function isShareable() {
 	 * @return Node
```
Comment (come-nc) [inline lib/private/Files/Node/Root.php:343]:
```suggestion
```

File: lib/private/Files/FileInfo.php [hunk 3]
```diff
@@ -79,7 +80,7 @@ class FileInfo implements \OCP\Files\FileInfo, \ArrayAccess {
 
 	/**
 	 * @param string|boolean $path
-	 * @param Storage\Storage $storage
+	 * @param Storage\Storage|IStorage $storage
```
Comment (come-nc) [inline lib/private/Files/FileInfo.php:83]: The return type of getStorage needs to be adapted as well, no?

File: lib/private/Files/Cache/QuerySearchHelper.php [hunk 4]
```diff
@@ -196,23 +195,31 @@ public function searchInCaches(ISearchQuery $searchQuery, array $caches): array
...
+			/** @var ICache[] $caches */
 			$caches = ['' => new CacheJail($storage->getCache(''), $internalPath)];
 		} else {
+			/** @var ICache[] $caches */
 			$caches = ['' => $storage->getCache('')];
 		}
 		$mountByMountPoint = ['' => $mount];
 
-		if (!$limitToHome) {
+		if (!$limitToHome && method_exists($root, 'getMountsIn')) {
```
Comment (come-nc) [inline lib/private/Files/Cache/QuerySearchHelper.php:222]: Does it actually happen in the wild to not have these methods on `$root`?
If not they should be added to the interface, no?

**Comment by JoshuaPettus** [comment]
Why is this slated for NC28?  It's a regression that effects NC26 and 27.

**Comment by paulijar** [comment]
>  It's a regression that effects NC26 and 27.

And also NC25.

File: lib/private/Files/Cache/QuerySearchHelper.php (hunk 4 above)
Comment (blizzz) [reply lib/private/Files/Cache/QuerySearchHelper.php:222]: I was haunted by `Folder` which has custom implementations… but this one looks rather safe indeed, at least on Github there does not seem to be a custom implemenation of it: https://github.com/search?q=org%3Anextcloud+%2Fimplements.*IRootFolder%2F&type=code

I'll add it to the interface then, i don't like handling and guessing on private classes at all.

**Comment by blizzz** [comment]
```
ERROR: UndefinedInterfaceMethod - lib/private/Files/Node/Folder.php:347:24 - Method OCP\Files\IRootFolder::createNode does not exist (see https://psalm.dev/181)
                return [$this->root->createNode(

```

Wow, how did this even work, ever? `createNode` is `protected`.

File: lib/public/Files/IRootFolder.php [hunk 5]
```diff
@@ -55,4 +56,16 @@ public function getUserFolder($userId);
...
+	 * @return IMountPoint[]
+	 *
+	 * @since 28.0.0
+	 */
+	public function getMountsIn(string $mountPoint): array;
+
+	/**
+	 * @since 28.0.0
+	 */
+	public function getMount(string $mountPoint): IMountPoint;
```
Comment (marcelklehr) [inline lib/public/Files/IRootFolder.php:70]: I'm not sure what's the policy on adding to interfaces in backports

File: lib/private/Files/FileInfo.php [hunk 6]
```diff
@@ -143,10 +144,7 @@ public function getPath() {
 		return $this->path;
 	}
 
-	/**
-	 * @return \OCP\Files\Storage
-	 */
-	public function getStorage() {
+	public function getStorage(): Storage\Storage|IStorage {
```
Comment (marcelklehr) [inline lib/private/Files/FileInfo.php:147]: Will this clash with the public FileInfo interface?

File: lib/public/Files/IRootFolder.php (hunk 5 above)
Comment (blizzz) [reply lib/public/Files/IRootFolder.php:70]: Ah, right, backports are not relevant anymore.

Comment (blizzz) [reply lib/public/Files/IRootFolder.php:70]: Correct to bring that up. Afaik the IRootFolder is not implemented by others, then additions to the API are not breaking.

File: lib/private/Files/FileInfo.php (hunk 6 above)
Comment (blizzz) [reply lib/private/Files/FileInfo.php:147]: It's legitimate to narrow down return types in implementations.

Comment (blizzz) [reply lib/private/Files/FileInfo.php:147]: So it does not clash code wise, but you might argue it clashes with the phpdoc-type. But not really. The public interface documents `IStorage` to return, while the implementation returned `Storage` – which implements `IStorage` however..

`\OCP\Files\Storage`  is an interface deprecated since 9.0.0, and it is advised to use IStorage instead. 

Right now I am unsure about `Storage\Storage` (also implementing the deprecated interface…) as return type, I will double check this tomorrow.

Comment (blizzz) [reply lib/private/Files/FileInfo.php:147]: World of pain. 

While `OCP\Files\Storage` was deprecated in 9.0.0, it got a new method in 12.0.0, which is missing in `OCP\Files\Storage\IStorage`.  Then there is private interface `OC\Files\Storage\Storage` which is then having three additional methods.

Adding the `IStorage` on my side is probably not necessary, as both `Storage` interfaces implement it. I'd also remove the return type hint to be on the safe side.

File: lib/public/Files/IRootFolder.php (hunk 5 above)
Comment (blizzz) [reply lib/public/Files/IRootFolder.php:70]: Yes, only implemented in the server repo, only in `Root` and `LazyRoot`. https://github.com/search?q=org%3Anextcloud+%2Fimplements.*IRootFolder%2F&type=code

**Review by marcelklehr — APPROVED** [review]
