### PR TITLE
fix(ReferenceApiController): Bump rate limit for public resolve endpoint

### LINKED ISSUE #1607: 429: Too Many Requests
**Describe the bug**
Collective doesn't load all the images from links preview. Instead, get status code: 429 Too many requests.
I give you a Nextcloud URL for example: https://www.home-cloud.fr/apps/collectives/p/Br6CwGz7ZNXRfFG/TestImage

I get this kind of error only with collective or Nextcloud text app, not with memories or other apps that load many images.

**To Reproduce**
1. Go to `Collective` app
2. Create a new `Collective`
3. Add a lot of link with the image preview
4. Reload the page (delete the cache before) or share the public link and load it in a new tab

**Expected behavior**
To have all the link image preview.

**Screenshots**
Image

**Server details:**
- Collectives app version: 2.15.1
- Nextcloud version: 30.0.2
- PHP Version: 8.2
- Database: MariaDB

**Client details:**
 - OS: Linux
 - Browser: Firefox and Chrome
 - Device: Phone and desktop

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
{
    "message": "Request failed with status code 429",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 429\n    at ze (https://www.home-cloud.fr/apps/text/js/index-Br6XaFoY.chunk.mjs:2:46617)\n    at XMLHttpRequest.C (https://www.home-cloud.fr/apps/text/js/index-Br6XaFoY.chunk.mjs:2:51615)\n    at Z.request (https://www.home-cloud.fr/apps/text/js/index-Br6XaFoY.chunk.mjs:2:59323)",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": [
            "xhr",
            "http",
            "fetch"
        ],
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "requesttoken": "oilAEGyj6oAJwPhim+5LmEwHljPZe8LP4u09Kbz6F20=:8X8Ndgf2r9lrgaojy41z1wBd8kOXT/KW24NObtfNLwc=",
            "X-Requested-With": "XMLHttpRequest"
        },
        "method": "get",
        "url": "https://www.home-cloud.fr/ocs/v2.php/references/resolvePublic?reference=https%3A%2F%2Fwww.imdb.com%2Ftitle%2Ftt0116209%2F%3Fref_%3Dnv_sr_srsg_0_tt_1_nm_0_in_0_q_Le%252520patient%252520anglais&sharingToken=Br6CwGz7ZNXRfFG"
    },
    "code": "ERR_BAD_REQUEST",
    "status": 429
}

</details>

### PR DESCRIPTION
**Pull request by mejo-**
E.g. text documents might contain hundreds of links whose previews need to get loaded.

Fixes: nextcloud/collectives#1607

## Checklist

- Code is [properly formatted](https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/continuous_integration.html#linting)
- [Sign-off message](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) is added to all commits
- [x] [Backports requested](https://github.com/nextcloud/backportbot/#usage) where applicable (ex: critical bugfixes)

### CODE REVIEW

**Review by blizzz — APPROVED** [review]

File: core/Controller/ReferenceApiController.php [hunk 1]
```diff
@@ -128,7 +128,7 @@ public function resolveOne(string $reference): DataResponse {
 	 */
 	#[ApiRoute(verb: 'GET', url: '/resolvePublic', root: '/references')]
 	#[PublicPage]
-	#[AnonRateLimit(limit: 10, period: 120)]
+	#[AnonRateLimit(limit: 200, period: 120)]
```
Comment (nickvergessen) [inline core/Controller/ReferenceApiController.php:131]:
```suggestion
	#[AnonRateLimit(limit: 200, period: 3600)]
```

Comment (juliusknorr) [reply core/Controller/ReferenceApiController.php:131]: I think the tricky part is that we do not cache invalid responses, so you can still issue a lot more requests, though I find it hard to come up with a reasonable amount there. 

We could also think about doing lazy loading on the frontend side there as an additional step to only fetch the ones that are visible in the browsers viewport, but even with that 10 in 120 seconds might be to low for examples like the one shared in the collectives ticket.

Comment (mejo-) [reply core/Controller/ReferenceApiController.php]: Changed to `limit: 25, period: 120` now in the hope that this would be acceptable.

**Review by nickvergessen — APPROVED** [review]
