### PR TITLE
Fix caching routes by users with an active session

### LINKED ISSUE #56789: [Bug]: memcache.local
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Bei aktiviertem memcache.local funktionieren einige Apps nach einiger Zeit nicht mehr. Es kommt die Fehlermeldung "Seite nicht gefunden". 
Es sind nicht Core-Apps wie ocs_api_viewer, passwords, sharereview usw. betroffen.
Das Problem tritt bei  
'memcache.local' => '\\OC\\Memcache\\**APCu**' 
und
'memcache.locking' => '\\OC\\Memcache\\**Redis**'
auf.
Ein umschalten des 'memcache.local' hilft nur temporär für einige Zeit. Nach mehrmaligem hin her her schalten muss ich den 'memcache.local' deaktivieren etwas warten und kann dann von vorn mit aktivieren und deaktivieren anfangen.

-----

When memcache.local is enabled, some apps stop working after a while. The error message "Page not found" appears.
Core apps such as ocs_api_viewer, passwords, sharereview, etc. are not affected.
The problem occurs with
'memcache.local' => '\OC\Memcache\APCu'
and
'memcache.locking' => '\OC\Memcache\Redis'.

Switching 'memcache.local' only helps temporarily for a while. After switching back and forth several times, I have to deactivate 'memcache.local', wait a while, and then I can start activating and deactivating again.

Image

### Steps to reproduce

1.aktivieren: 'memcache.local' => '\\OC\\Memcache\\**APCu**' 
2.warten bis Fehler auftritt
3.aktivieren: 'memcache.local' => '\\OC\\Memcache\\**Redis**'
4.warten bis Fehler auftritt
5.'memcache.local' komplett deaktivieren
6. warten und bei 1. wieder anfangen

------

1. Activate: 'memcache.local' => '\\OC\\Memcache\\**APCu**'
2. Wait until an error occurs
3. Activate: 'memcache.local' => '\\OC\\Memcache\\**Redis**'
4. Wait until an error occurs
5. Completely deactivate 'memcache.local'
6. Wait and start again at 1.

### Expected behavior

Das die Apps mit aktiviertem 'memcache.local' wie unter NC 31 funktionieren.

### Nextcloud Server version

32

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.4

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 31 to 32)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "nextcloud.my.de",
            "Nextcloud.my.local"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "32.0.2.2",
        "overwrite.cli.url": "https:\/\/nextcloud.my.de",
        "overwritehost": "nextcloud.my.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "activity_expire_days": 14,
        "auth.bruteforce.protection.enabled": true,
        "forbidden_filenames": [
            ".htaccess",
            "Thumbs.db",
            "thumbs.db"
        ],
        "cron_log": true,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Image",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\MKV",
            "OC\\Preview\\MP4",
            "OC\\Preview\\AVI"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "filesystem_check_changes": 1,
        "check_data_directory_permissions": false,
        "default_phone_region": "DE",
        "default_language": "de",
        "default_locale": "de_DE",
        "lost_password_link": "disabled",
        "filelocking.enabled": "false",
        "allow_self_signed": true,
        "allow_local_address": true,
        "allow_local_remote_servers": true,
        "share_folder": "\/Shares",
        "htaccess.RewriteBase": "\/",
        "integrity.check.disabled": false,
        "knowledgebaseenabled": false,
        "logfile": "\/var\/tmp\/nextcloud.log",
        "loglevel": 2,
        "logtimezone": "Europe\/Berlin",
        "log_rotate_size": 104857600,
        "maintenance": false,
        "maintenance_window_start": 1,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "cache_app_config": true,
        "overwriteprotocol": "https",
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "preview_max_scale_factor": 1,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 0.5,
            "dbindex": 1
        },
        "quota_include_external_storage": false,
        "skeletondirectory": "\/mnt\/nextclouddata\/benutzer_vorlage",
        "theme": "",
        "trashbin_retention_obligation": "auto, 7",
        "updater.release.channel": "stable",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtptimeout": 30,
        "mail_smtpauthtype": "NTLM",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [],
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [
            "Speziale"
        ],
        "remember_login_cookie_lifetime": 0,
        "session_lifetime": 900,
        "session_keepalive": false,
        "auto_logout": true,
        "forbidden_filename_characters": [
            "<",
            ">",
            ":",
            "\"",
            "|",
            "?",
            "*",
            "\\",
            "\/"
        ],
        "forbidden_filename_extensions": [
            " ",
            ".",
            ".filepart",
            ".part"
        ],
        "memories.db.triggers.fcu": true,
        "memories.exiftool": "\/var\/www\/nextcloud\/apps\/memories\/bin-ext\/exiftool-amd64-glibc",
        "memories.vod.path": "\/var\/www\/nextcloud\/apps\/memories\/bin-ext\/go-vod-amd64",
        "memories.vod.ffmpeg": "\/usr\/bin\/ffmpeg",
        "memories.vod.ffprobe": "\/usr\/bin\/ffprobe",
        "memories.gis_type": 1,
        "preview_max_memory": 2028,
        "preview_max_filesize_image": 512,
        "forbidden_filename_basenames": [
            "con",
            "prn",
            "aux",
            "nul",
            "com0",
            "com1",
            "com2",
            "com3",
            "com4",
            "com5",
            "com6",
            "com7",
            "com8",
            "com9",
            "com\u00b9",
            "com\u00b2",
            "com\u00b3",
            "lpt0",
            "lpt1",
            "lpt2",
            "lpt3",
            "lpt4",
            "lpt5",
            "lpt6",
            "lpt7",
            "lpt8",
            "lpt9",
            "lpt\u00b9",
            "lpt\u00b2",
            "lpt\u00b3"
        ],
        "defaultapp": "dashboard"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 5.0.0-dev.0
  - admin_audit: 1.22.0
  - announcementcenter: 7.2.2
  - bruteforcesettings: 5.0.0-dev.0
  - calendar: 6.1.0
  - circles: 32.0.0
  - cloud_federation_api: 1.16.0
  - collectives: 3.3.0
  - comments: 1.22.0
  - contacts: 8.1.0
  - contactsinteraction: 1.13.1
  - csp_editor: 1.8.0
  - dashboard: 7.12.0
  - dav: 1.34.2
  - deck: 1.16.2
  - external: 7.0.0
  - federatedfilesharing: 1.22.0
  - federation: 1.22.0
  - files: 2.4.0
  - files_accesscontrol: 3.0.2
  - files_antivirus: 6.1.0
  - files_automatedtagging: 3.0.1
  - files_downloadlimit: 5.0.0-dev.0
  - files_fulltextsearch: 32.0.2
  - files_pdfviewer: 5.0.0-dev.0
  - files_reminders: 1.5.0
  - files_retention: 3.0.0
  - files_sharing: 1.24.1
  - files_trashbin: 1.22.0
  - files_versions: 1.25.0
  - forms: 5.2.3
  - fulltextsearch: 32.0.0
  - fulltextsearch_elasticsearch: 32.0.0
  - impersonate: 3.0.0
  - integration_mastodon: 4.0.0
  - logreader: 5.0.0-dev.0
  - lookup_server_connector: 1.20.0
  - memories: 7.7.0
  - news: 27.2.0
  - nextcloud_announcements: 4.0.0-dev.0
  - notes: 4.12.4
  - notifications: 5.0.0-dev.0
  - notify_push: 1.2.1
  - oauth2: 1.20.0
  - ocs_api_viewer: 1.0.11
  - password_policy: 4.0.0-dev.0
  - passwords: 2025.11.20
  - photos: 5.0.0-dev.1
  - previewgenerator: 5.11.0
  - privacy: 4.0.0-dev.0
  - profile: 1.1.0
  - provisioning_api: 1.22.0
  - recommendations: 5.0.0-dev.0
  - related_resources: 3.0.0-dev.0
  - richdocuments: 9.0.2
  - richdocumentscode: 25.4.702
  - serverinfo: 4.0.0-dev.0
  - settings: 1.15.1
  - sharebymail: 1.22.0
  - sharereview: 2.0.0
  - spreed: 22.0.4
  - support: 4.0.0-dev.0
  - systemtags: 1.22.0
  - tables: 1.0.1
  - text: 6.0.1
  - theming: 2.7.0
  - thesearchpage: 1.2.16
  - twofactor_backupcodes: 1.21.0
  - twofactor_totp: 14.0.0
  - twofactor_webauthn: 2.4.1
  - updatenotification: 1.22.0
  - user_status: 1.12.0
  - viewer: 5.0.0-dev.0
  - weather_status: 1.12.0
  - webhook_listeners: 1.3.0
  - whiteboard: 1.4.2
  - workflow_script: 3.0.0
  - workflowengine: 2.14.0
Disabled:
  - app_api: 32.0.0 (installed 3.2.0)
  - encryption: 2.20.0
  - files_external: 1.24.0 (installed 1.23.0)
  - firstrunwizard: 5.0.0-dev.0 (installed 2.9.0)
  - survey_client: 4.0.0-dev.0 (installed 1.8.0)
  - suspicious_login: 10.0.0-dev.0
  - twofactor_nextcloud_notification: 6.0.0-dev.0 (installed 5.0.0)
  - user_ldap: 1.23.0
```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

"cache_app_config": true, wurde von der Community vorgeschlagen brachte aber keine Erfolg.
Das Problem tritt unter Debian 12 und 13 sowie PHP 8.3 und 8.4 auf.

Das 
    'host' = '/var/run/redis/redis-server.sock',
    'port' = 0,
oder das
    'host' = '127.0.0.1',
    'port' = 6379,
hat auch nicht geholfen.

----

"cache_app_config": true, was suggested by the community but did not work.
The problem occurs under Debian 12 and 13 as well as PHP 8.3 and 8.4.

The 
    'host' = '/var/run/redis/redis-server.sock',
    'port' = 0,
or the
    'host' = '127.0.0.1',
    'port' = 6379,
did not help either.

### PR DESCRIPTION
**Pull request by danxuliu**
Fixes #56789, which is a regression introduced in #52793

When a user has an active session only the apps that are enabled for the user are initially loaded*. In order to cache the routes [the routes for all apps are loaded](https://github.com/nextcloud/server/blob/b188fad8e84491b0631a7e33a28c55ccecbecaf4/lib/private/Route/CachingRouter.php#L80-L81), but [routes defined in _routes.php_ are taken into account only if the app was already loaded](https://github.com/nextcloud/server/blob/a98ba27a0f3439521c03464f1454b9e9f5032832/lib/private/Route/Router.php#L156-L161). Therefore, when the routes were cached in a request by a user with an active session only the routes for apps enabled for that user were cached, and those routes were used by any other user, independently of which apps they had access to. To solve that now all the enabled apps are explicitly loaded before caching the routes.

Note that this did not affect routes defined using annotations on the controller files; in that case the loaded routes do not depend on the previously loaded apps, as [it explicitly checks all the enabled apps](https://github.com/nextcloud/server/blob/a98ba27a0f3439521c03464f1454b9e9f5032832/lib/private/Route/Router.php#L128-L130).

*[As soon as the session is initialized](https://github.com/nextcloud/server/blob/eb54143c2d6ccc9ad4220207f1be617abb6e71e4/lib/base.php#L734), which happens [when loading _base.php_](https://github.com/nextcloud/server/blob/eb54143c2d6ccc9ad4220207f1be617abb6e71e4/lib/base.php#L1227), the legacy `OC_APP::getEnabledApps` [will return only the apps enabled for the user](https://github.com/nextcloud/server/blob/bdff12361c227c8ba71e3f8739a90a10a0fd9dec/lib/private/legacy/OC_App.php#L188). That method [is used by `AppManager::loadApps`](https://github.com/nextcloud/server/blob/ab9a92fac850b41da6ac3285360275ba34db0488/lib/private/App/AppManager.php#L250), so once the session is initialized any load of (several) apps will be restricted to those enabled for the user (explicitly loading a single app still works as expected). Therefore, when `$appManager->loadApps()` is called from the [OCS handler](https://github.com/nextcloud/server/blob/7127ac4b43bad98f91855fb74428748e47d032fb/ocs/v1.php#L52) or from the [_index.php_ handler (through `handleRequest` in _base.php_)](https://github.com/nextcloud/server/blob/eb54143c2d6ccc9ad4220207f1be617abb6e71e4/lib/base.php#L1056) only the apps for the user are loaded.

## Steps to reproduce

- Use a development server and ensure that no other requests than the ones below are handled
- Enable APCu cache (add `'memcache.local' => '\\OC\\Memcache\\APCu'`, to _config.php_) if not enabled already
- Enable the `weather_status` app only for a specific group (for simplicity admin is used here)
```
occ app:enable --groups admin weather_status`
```

- Adjust the variables below as needed for your setup and run the following Bash code:
```
export ADMIN_NAME=admin
export ADMIN_PASSWORD=admin
export USER_NAME=user0
export USER_PASSWORD=user0
export SERVER_URL=http://127.0.0.1:8000

function extractRequestToken() {
	echo $(echo $1 | grep --perl-regexp --only-matching 'data-requesttoken="\K([^"]*)')
}

function extractAuthenticationToken() {
	echo $(echo $1 | grep --perl-regexp --only-matching '"token":"\K([^"]*)')
}

# Open login page to get the request token
loginPage=$(curl --silent --cookie-jar "/tmp/cookie-jar-$USER_NAME" "$SERVER_URL/index.php/login")

requestToken=$(extractRequestToken "$loginPage")

# Perform actual login
loginPost=$(curl --silent --location --cookie "/tmp/cookie-jar-$USER_NAME" --cookie-jar "/tmp/cookie-jar-$USER_NAME" --header "Origin: $SERVER_URL" --data-urlencode "user=$USER_NAME" --data-urlencode "password=$USER_PASSWORD" --data-urlencode "requesttoken=$requestToken" "$SERVER_URL/index.php/login")

requestToken=$(extractRequestToken "$loginPost")
```

- Clear the APCu cache (call `apcu_clear_cache()` somehow, for example using https://github.com/krakjoe/apcu/blob/master/apc.php or the helper apps/testing/clean_apcu_cache.php added in this pull request; restarting the web server would reset the APCu cache, but it might also kill the user session and make the test invalid)

- In the same Bash terminal as before, do a request with the logged in user, for example:
```
curl --silent --location --cookie "/tmp/cookie-jar-$USER_NAME" --cookie-jar "/tmp/cookie-jar-$USER_NAME" --header "requesttoken: $requestToken" "$SERVER_URL/ocs/v1.php/cloud/user?format=json"
```

- Now request an endpoint in the `weather_status` app by a user member of the group that it is enabled for (again for simplicity admin is used here):
```
curl --user "$ADMIN_NAME:$ADMIN_PASSWORD" --header "OCS-ApiRequest: true" "$SERVER_URL/ocs/v2.php/apps/weather_status/api/v1/location"
```

### Result with this pull request

The query succeeded

### Result without this pull request

Invalid query returned; if the APCu cache is cleared again and the request repeated then it will now succeed (as the routes will be regenerated by the admin, which has access to the app)

### CODE REVIEW

**Comment by solracsf** [comment]
Is this still needed after https://github.com/nextcloud/server/pull/56926 ?

**Comment by provokateurin** [comment]
Yes the other PR was just a quick fix for the release. We still need to enable caching again and probably with this PR. @danxuliu can you rebase and revert my commit?

File: apps/testing/lib/Controller/RoutesController.php [hunk 1]
```diff
@@ -0,0 +1,51 @@
+<?php
+
+/**
+ * SPDX-FileCopyrightText: 2025 Nextcloud GmbH and Nextcloud contributors
+ * SPDX-License-Identifier: AGPL-3.0-only
```
Comment (provokateurin) [inline apps/testing/lib/Controller/RoutesController.php]:
```suggestion
 * SPDX-License-Identifier: AGPL-3.0-or-later
```

File: apps/testing/lib/Controller/RoutesController.php [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+
+class RoutesController extends OCSController {
+
+	/**
+	 * @param string $appName
+	 * @param IRequest $request
+	 * @param IAppManager $appManager
+	 */
+	public function __construct(
+		$appName,
```
Comment (provokateurin) [inline apps/testing/lib/Controller/RoutesController.php]:
```suggestion
	public function __construct(
		string $appName,
```

File: apps/testing/lib/Controller/RoutesController.php [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+		IRequest $request,
+		private IAppManager $appManager,
+	) {
+		parent::__construct($appName, $request);
+	}
+
+	/**
+	 * @param string $app
+	 * @return DataResponse
+	 */
```
Comment (provokateurin) [inline apps/testing/lib/Controller/RoutesController.php]:
```suggestion
```

File: apps/testing/lib/Controller/RoutesController.php [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+		} catch (AppPathNotFoundException) {
+			return new DataResponse([], Http::STATUS_NOT_FOUND);
+		}
+
+		$file = $appPath . '/appinfo/routes.php';
+		if (!file_exists($file)) {
+			return new DataResponse();
+		}
+
+		$routes = include $file;
```
Comment (provokateurin) [inline apps/testing/lib/Controller/RoutesController.php:38]: Maybe for this particular test it's enough, but you're skipping the attribute routes this way.

File: build/integration/routing_features/apps-and-routes.feature [hunk 5]
```diff
@@ -50,3 +50,22 @@ Feature: appmanagement
     Given As an "admin"
     And sending "DELETE" to "/cloud/apps/weather_status"
     And app "weather_status" is disabled
+
+  Scenario: Cache routes from routes.php with a user in a group without some apps enabled
+    Given invoking occ with "config:system:set memcache.local --value \OC\Memcache\APCu"
```
Comment (provokateurin) [inline build/integration/routing_features/apps-and-routes.feature:55]: Can you somehow verify the cache is actually working? Because if that's not the case, then the rest of the test is not going to fail if we'd have a regression.

**Review by provokateurin — CHANGES_REQUESTED** [review]
LGTM and also thanks for adding a test!

File: apps/testing/lib/Controller/RoutesController.php (hunk 1 above)
Comment (danxuliu) [reply apps/testing/lib/Controller/RoutesController.php]: :facepalm: Fixed.

File: apps/testing/lib/Controller/RoutesController.php (hunk 2 above)
Comment (danxuliu) [reply apps/testing/lib/Controller/RoutesController.php]: Sorry, habit from the dark ages without argument types ;-) Fixed.

File: apps/testing/lib/Controller/RoutesController.php (hunk 3 above)
Comment (danxuliu) [reply apps/testing/lib/Controller/RoutesController.php]: Fixed.

File: apps/testing/lib/Controller/RoutesController.php (hunk 4 above)
Comment (danxuliu) [reply apps/testing/lib/Controller/RoutesController.php:38]: That is on purpose :-) The issue does not happen with attribute routes, so the test explicitly uses routes defined in _routes.php_ first to actually test the issue, and second to ensure that, if at some point in the future the _weather_status_ app no longer defines the tested route in _routes.php_, the test will fail and can be adjusted to use another route or app.

Independently of that, it would be indeed nice to add another test that explicitly checks attribute routes so, even if right now there is no issue, it could catch it in case of a future regression. Unfortunately I could not add it due to lack of time, sorry.

File: build/integration/routing_features/apps-and-routes.feature (hunk 5 above)
Comment (danxuliu) [reply build/integration/routing_features/apps-and-routes.feature:55]: If the class set in _memcache.local_ is not found the test will actually fail. And I assume that if the APCu extension is not available then the class will fail to load due to `apcu_*` functions not being defined. But if the class exists and the extension is available then I am afraid that I do not know how to verify that it is actually working, and even more, that it is working specifically for the routes.

File: apps/testing/lib/Controller/RoutesController.php (hunk 4 above)
Comment (provokateurin) [reply apps/testing/lib/Controller/RoutesController.php:38]: Ah yes I remember that difference when I implemented route attributes. It was really strange because it should be fine to limit the loaded routes to only enabled routes, if you do that the stuff starts to break.

**Review by provokateurin — APPROVED** [review]

**Comment by danxuliu** [comment]
Rebased again to fix the DCO in the revert commit.

**Review by come-nc — APPROVED** [review]

**Comment by come-nc** [comment]
I’m still wondering whether we should just load all enabled apps (for any user) even for users for which the application is not enabled.

The whole feature about enabling only for some users is a bit weird.

File: lib/private/Route/CachingRouter.php [hunk 6]
```diff
@@ -74,12 +74,17 @@ private function serializeRouteCollection(RouteCollection $collection): array {
...
+			// Ensure that all apps are loaded, as for users with an active
+			// session only the apps that are enabled for that user might have
+			// been loaded.
+			$enabledApps = $this->appManager->getEnabledApps();
+			foreach ($enabledApps as $app) {
+				$this->appManager->loadApp($app);
+			}
 			parent::loadRoutes();
 			$cachedRoutes = $this->serializeRouteCollection($this->root);
 			$this->cache->set($key, $cachedRoutes, ($this->config->getSystemValueBool('debug') ? 3 : 3600));
```
Comment (nickvergessen) [inline lib/private/Route/CachingRouter.php:90]: Are we sure debug is false in this test, otherwise the 3s can be ran over between the requests and the cache already expired
